changelog/change_mark_unsafe_autocorrect_for_lint_incompatible_io_select_with_fiber_scheduler.md, config/default.yml, lib/rubocop/cop/lint/incompatible_io_select_with_fiber_scheduler.rb
Fixes #10269.
`Lint/IncompatibleIoSelectWithFiberScheduler`cop's autocorrection is unsafe because `NoMethodError` occurs if `require 'io/wait'` is not called.
```console
% ruby -rio/wait -ve 'IO.new(IO.sysopen("/tmp")).wait_readable'
ruby 3.1.0dev (2021-11-21T10:23:36Z master 784f1e1538) [x86_64-darwin19]
```
```console
% ruby -ve 'IO.new(IO.sysopen("/tmp")).wait_readable'
ruby 3.1.0dev (2021-11-21T10:23:36Z master 784f1e1538) [x86_64-darwin19]
-e:1:in `<main>': undefined method `wait_readable' for #<IO:fd 9> (NoMethodError)
IO.new(IO.sysopen("/tmp")).wait_readable
^^^^^^^^^^^^^^
```
=> [Fix #10269] Mark unsafe autocorrect for `Lint/IncompatibleIoSelectWithFiberScheduler`

changelog/fix_false_positive_for_internal_affairs_undefined_config.md, lib/rubocop/cop/internal_affairs/undefined_config.rb, spec/rubocop/cop/internal_affairs/undefined_config_spec.rb
Fixes #10273.
This PR fixes a false positive for `InternalAffairs/UndefinedConfig` when inheriting a `Base` class other than RuboCop's `Base` class.
=> [Fix #10273] Fix a false positive for `InternalAffairs/UndefinedConfig`

lib/rubocop/cli/command/suggest_extensions.rb
Follow up to https://github.com/rubocop/rubocop/pull/10178#issuecomment-981897123.
RubyGems URL is better than GitHub repository URL because it is likely to match `require` extension gem name.
https://guides.rubygems.org/name-your-gem/
This makes suggested RuboCop extension URL unaffected by repository location.
=> Tweak suggested RuboCop extension URL

lib/rubocop/cop/style/character_literal.rb
"good" example for `?\C-\M-d` doesn't have any explanation.
Personally I didn't understand why until friends told me,
so I thought we should document it.
=> Explain why `?\C-\M-d` is good

changelog/fix_incorrect_autocorrect_for_style_redundant_interpolation.md, lib/rubocop/cop/style/redundant_interpolation.rb, spec/rubocop/cop/style/redundant_interpolation_spec.rb
Fixes #10276.
This PR fixes an incorrect autocorrect for `Style/RedundantInterpolation` when using a method call without parentheses in string interpolation.
=> [Fix #10276] Fix an incorrect autocorrect for `Style/RedundantInterpolation`

changelog/new_support_ruby31_anonymous_block_argument_syntax.md, rubocop.gemspec
Follow up to https://github.com/rubocop/rubocop-ast/pull/218.
This PR supports Ruby 3.1's anonymous block argument syntax and fixes the following error.
```console
% ruby -v
ruby 3.1.0dev (2021-12-01T02:00:10Z master 0b53a8895f) [x86_64-darwin19]
% echo 'def foo(&) = bar(&)' | be rubocop --enable-pending-cops --stdin example.rb
.
0 files inspected, no offenses detected
undefined method `type' for nil:NilClass
/Users/koic/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:131:in
`on_block_pass'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/commissioner.rb:71:in
`on_block_pass'
/Users/koic/.rbenv/versions/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:159:in
`block in on_send' …
```
=> Support Ruby 3.1's anonymous block argument syntax

changelog/fix_incorrect_autocorrect_for_style_sole_nested_conditional.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
Fixes #10285.
This PR fixes an incorrect autocorrect for `Style/SoleNestedConditional` when using nested `if` within `if foo = bar`.
=> [Fix #10285] Fix an incorrect autocorrect for `Style/SoleNestedConditional`

changelog/fix_incorrect_autocorrect_for_style_redundant_regexp_character_class.md, lib/rubocop/cop/style/redundant_regexp_character_class.rb, spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb
Fixes #10284.
This PR fixes an incorrect autocorrect for `Style/RedundantRegexpCharacterClass` when regexp containing an unescaped `#`.
It will be the same auto-correction code as the existing escaped `\#`.
https://github.com/rubocop/rubocop/blob/v1.23.0/spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb#L268-L279
=> [Fix #10284] Fix an incorrect autocorrect for `Style/RedundantRegexpCharacterClass`

changelog/fix_incorrect_autocorrect_for_style_empty_case_condition.md, lib/rubocop/cop/style/empty_case_condition.rb, spec/rubocop/cop/style/empty_case_condition_spec.rb
Fixes #10282.
This PR fixes an incorrect autocorrect for `Style/EmptyCaseCondition` when using `when ... then` in `case` in `return`.
This issue occurs not only with `return`, also with method calls.
And indentation of auto-corrected code will be entrusted to another existing cop.
=> [Fix #10282] Fix an incorrect autocorrect for `Style/EmptyCaseCondition`

changelog/new_support_hash_value_omission_for_layout_space_after_colon.md, lib/rubocop/cop/layout/space_after_colon.rb, rubocop.gemspec, spec/rubocop/cop/layout/space_after_colon_spec.rb
This PR supports Ruby 3.1's hash value omission syntax for `Layout/SpaceAfterColon`.
The `Layout/SpaceAfterColon` cop have already accepted the following required keyword arguments:
```ruby
def initialize(foo:, bar:)
end
```
This PR will also make this cop accept Ruby 3.1 hash value omission.
```ruby
{foo:, bar:}
do_something(foo:, bar:)
```
=> Support Ruby 3.1's hash value omission syntax for `Layout/SpaceAfterColon`

changelog/fix_false_positive_for_lint_deprecated_open_ssl_constant.md, lib/rubocop/cop/lint/deprecated_open_ssl_constant.rb, spec/rubocop/cop/lint/deprecated_open_ssl_constant_spec.rb
Fixes #10297.
This PR fixes a false positive for `Lint/DeprecatedOpenSSLConstant` when building digest using an algorithm string and nested digest constants.
It aims to prevent the false positive. I may open a separated PR for another cop about detection of redundant constants.
=> [Fix #10297] Fix a false positive for `Lint/DeprecatedOpenSSLConstant`

changelog/fix_incorrect_autocorrect_for_dot_position_and_redudant_self.md, lib/rubocop/cop/layout/dot_position.rb, lib/rubocop/cop/style/redundant_self.rb, spec/rubocop/cli/autocorrect_spec.rb
Fixes #10300
This PR fixes an incorrect autocorrect for `Layout/DotPosition` and `Style/RedundantSelf` when auto-correction conflicts.
=> [Fix #10300] Fix an incorrect autocorrect for `Layout/DotPosition` and `Style/RedundantSelf`

changelog/fix_incorrect_autocorrect_for_style_hash_conversion.md, lib/rubocop/cop/style/hash_conversion.rb, spec/rubocop/cop/style/hash_conversion_spec.rb
Fixes #10305.
This PR fixes an incorrect autocorrect for `Style/HashConversion` when using `Hash[a || b]`.
=> [Fix #10305] Fix an incorrect autocorrect for `Style/HashConversion`

changelog/new_support_numbered_parameter_for_metrics_length_cops.md, lib/rubocop/cop/metrics/block_length.rb, lib/rubocop/cop/metrics/method_length.rb, lib/rubocop/cop/metrics/module_length.rb, lib/rubocop/cop/metrics/utils/code_length_calculator.rb, spec/rubocop/cop/metrics/block_length_spec.rb, spec/rubocop/cop/metrics/class_length_spec.rb, spec/rubocop/cop/metrics/method_length_spec.rb, spec/rubocop/cop/metrics/module_length_spec.rb
This PR supports Ruby 2.7's numbered parameter for `Metrics/BlockLength`, `Metrics/ClassLength`, `Metrics/MethodLength`, and `Metrics/ModuleLength` cops.
=> Support Ruby 2.7's numbered parameter for `Metrics/*Length` cops

changelog/new_support_hash_value_omission_for_layout_hash_alignment.md, lib/rubocop/cop/layout/hash_alignment.rb, lib/rubocop/cop/mixin/hash_alignment_styles.rb, spec/rubocop/cop/layout/hash_alignment_spec.rb
This PR supports Ruby 3.1's hash value omission syntax for `Layout/HashAlignment`.
And it prevents the following false positive and incorrect auto-correction.
```console
% cat hash_value_omission.rb
{
foo: 42,
bar:
}
% bundle exec rubocop --only Layout/HashAlignment -a hash_value_omission.rb
(snip)
C
Offenses:
hash_value_omission.rb:3:3: C: [Corrected] Layout/HashAlignment: Align
the keys of a hash literal if they span more than one line.
bar:
^^^^
hash_value_omission.rb:3:8: C: [Corrected] Layout/HashAlignment:
Align the keys of a hash literal if they span more than one line.
bar:
^^^^
0 files inspected, 2 offenses detected, 2 offenses corrected
/Users/koic/src/github.com/koic/rubocop-issues/ruby31/hash_value_omission.rb
and caused by …
```
=> Support Ruby 3.1's hash value omission for `Layout/HashAlignment`

changelog/new_make_style_collection_compact_aware_of_block_pass.md, lib/rubocop/cop/style/collection_compact.rb, spec/rubocop/cop/style/collection_compact_spec.rb
This PR makes `Style/CollectionCompact` aware of the following block pass argument.
```ruby
array.reject(&:nil?)
array.reject!(&:nil?)
array.compact
array.compact!
```
=> Make `Style/CollectionCompact` aware of block pass

changelog/fix_false_positive_bundler_duplicated_gem.md, lib/rubocop/cop/bundler/duplicated_gem.rb, spec/rubocop/cop/bundler/duplicated_gem_spec.rb
On the following code
```ruby
if defined?(@ar_gem_requirement)
gem "activerecord", @ar_gem_requirement
gem "railties", @ar_gem_requirement
else
gem "activerecord"
gem "railties" # to test generator
end
```
I got this output:
```
Offenses:
Gemfile:15:3: C: Bundler/DuplicatedGem: Gem activerecord requirements already given on line 12 of the Gemfile.
gem "activerecord"
^^^^^^^^^^^^^^^^^^
Gemfile:16:3: C: Bundler/DuplicatedGem: Gem railties requirements already given on line 13 of the Gemfile.
gem "railties" # to test generator
^^^^^^^^^^^^^^
1 file inspected, 2 offenses detected
```
`Bundler/DuplicatedGem` does not take into account that conditional branches can have multiple statements.
=> Fix a false positive for `Bundler/DuplicatedGem` when a gem conditionally duplicated within multi-statement bodies

changelog/new_allowed_numbers_option_to_style_numeric_literals.md, config/default.yml, lib/rubocop/cop/style/numeric_literals.rb, spec/rubocop/cli/auto_gen_config_spec.rb, spec/rubocop/cop/style/numeric_literals_spec.rb
Fixes #10303.
This PR adds `AllowedNumbers` option to `Style/NumericLiterals`.
```ruby
#
```
Any default values will not set because false negatives occur when `3000`, `8080` (,and other values) are used other than the port numbers.
=> [Fix #10303] Add `AllowedNumbers` option to `Style/NumericLiterals`

changelog/new_add_new_naming_block_forwarding_cop.md, config/default.yml, lib/rubocop.rb, lib/rubocop/cop/naming/block_forwarding.rb, spec/rubocop/cop/naming/block_forwarding_spec.rb
This PR adds new `Naming/BlockForwarding` cop.
Ruby 3.1 will be introduced anonymous block forwarding syntax:
https://bugs.ruby-lang.org/issues/11256
This cop identifies places where `do_something(&block)` can be replaced by `do_something(&)`.
```ruby
def foo(&block)
bar(&block)
end
def foo(&)
bar(&)
end
```
AFAIK, in most cases, block argument is given name similar to `&block` or `&proc`. Their names have no information and `&` will be sufficient for syntactic meaning.
=> Add new `Naming/BlockForwarding` cop

changelog/fix_map_to_hash_newline.md, lib/rubocop/cop/style/map_to_hash.rb, spec/rubocop/cop/style/map_to_hash_spec.rb
=> [Fix #10313] Fix autocorrect `Style/MapToHash` with multiline code

lib/rubocop/cop/internal_affairs/redundant_method_dispatch_node.rb, spec/rubocop/cop/internal_affairs/redundant_method_dispatch_node_spec.rb
This PR fixes the following error for `InternalAffairs/RedundantMethodDispatchNode`
when using `send_node.method_name`.
```console
undefined method `begin_pos' for nil:NilClass
range = range_between(dispatch_node.loc.dot.begin_pos, dispatch_node.loc.selector.end_pos)
^^^^^^^^^^
/Users/koic/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.24.0/lib/rubocop/cop/internal_affairs/redundant_method_dispatch_node.rb:37:in `on_send'
````
=> Fix an error for `InternalAffairs/RedundantMethodDispatchNode

changelog/fix_incorrect_autocorrect_for_style_file_write.md, lib/rubocop/cop/style/file_write.rb, spec/rubocop/cop/style/file_write_spec.rb
Fixes #10320.
This PR fixes an incorrect autocorrect for `Style/FileWrite` when using heredoc argument.
=> [Fix #10320] Fix an incorrect autocorrect for `Style/FileWrite`

changelog/fix_a_false_positive_for_combinable_loop.md, rubocop.gemspec, spec/rubocop/cop/style/combinable_loops_spec.rb
Fixes #10319.
This PR requires rubocop-ast 1.15.1 (https://github.com/rubocop/rubocop-ast/pull/220) to fix a false positive for `Style/CombinableLoop` when the same method with different arguments and safe navigation.
=> [Fix #10319] Fix a false positive for `Style/CombinableLoop`

.circleci/config.yml
This commit uses cimg instead of deprecated circleci images.
> This image is designed to supercede the legacy CircleCI Ruby image, `circleci/ruby`.
https://hub.docker.com/r/cimg/ruby
=> Use `cimg/ruby` instead of deprecated `circleci/ruby` images

changelog/fix_false_positive_for_style_method_call_with_args_parentheses.md, lib/rubocop/cop/style/method_call_with_args_parentheses.rb, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
Fixes #10317.
This PR fixes a false positive for `Style/MethodCallWithArgsParentheses` when using hash value omission.
=> [Fix #10317] Fix a false positive for `Style/MethodCallWithArgsParentheses`

changelog/fix_false_positive_for_style_method_def_parentheses.md, lib/rubocop/cop/style/method_def_parentheses.rb, spec/rubocop/cop/style/method_def_parentheses_spec.rb
Fixes #10321.
This PR fixes a false positive for `Style/MethodDefParentheses` when using `EnforcedStyle: require_no_parentheses` and Ruby 3.1's anonymous block forwarding.
=> [Fix #10321] Make `Style/MethodDefParentheses` aware of anonymous block forwarding

changelog/fix_incorrect_autocorrect_for_gemspec_require_mfa.md, lib/rubocop/cop/gemspec/require_mfa.rb, spec/rubocop/cop/gemspec/require_mfa_spec.rb
When we have `spec.metadata = {...}`, insert `rubygems_mfa_required` setting there. 
Otherwise, just always add `spec.metadata["rubygems_mfa_required"] = "true"`. 
Closes #10251
=> Fix an incorrect autocorrect for `Gemspec/RequireMFA` when .gemspec file contains `metadata` keys assignments

changelog/fix_false_positive_for_lint_parentheses_as_grouped_expression.md, lib/rubocop/cop/lint/parentheses_as_grouped_expression.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/lint/parentheses_as_grouped_expression_spec.rb
Fixes #10329.
This PR fixes a false positive for `Lint/ParenthesesAsGroupedExpression` and an incorrect autocorrect for the cop with `Style/TernaryParentheses` when using ternary expression as a first argument.
=> [Fix #10329] Fix a false positive for `Lint/ParenthesesAsGroupedExpression`

changelog/fix_incorrect_autocorrect_for_naming_block_forwarding.md, lib/rubocop/cop/naming/block_forwarding.rb, lib/rubocop/cop/style/method_def_parentheses.rb, lib/rubocop/cop/util.rb, spec/rubocop/cop/naming/block_forwarding_spec.rb
This PR fixes an incorrect autocorrect for `Naming/BlockForwarding` using explicit block forwarding without method definition parentheses.
First, specify named block variable explicitly.
```ruby
def foo(&blk)
bar
end
```
```console
% ruby-parse example.rb
(def :foo
(args
(blockarg :blk))
(send nil :bar))
```
Next, specify anonymous block forwarding.
```ruby
def foo(&)
bar
end
```
The structure of AST is the same.
```console
% ruby-parse example.rb
(def :foo
(args
(blockarg nil))
(send nil :bar))
```
Finally, omit the method definition parentheses.
```ruby
def foo &
bar
end
```
The structure of the AST will breaking change.
```console
% ruby-parse example.rb
(def :foo
(args
(blockarg :bar)) nil)
```
This PR enforces parentheses to maintain …
=> Fix an incorrect autocorrect for `Naming/BlockForwarding`

LICENSE.txt, README.md, docs/modules/ROOT/pages/about/license.adoc
This PR bumps license years to 2022.
Happy New Year and 10th anniversary 🎉 
=> Bump license years to 2022

lib/rubocop/cop/naming/block_forwarding.rb, spec/rubocop/cop/naming/block_forwarding_spec.rb
Fixes #10335.
This PR fixes a false positive for `Naming/BlockForwarding` when using multiple proc arguments.
=> [Fix #10335] Fix a false positive for `Naming/BlockForwarding`

changelog/fix_false_positive_for_style_ternary_parentheses.md, lib/rubocop/cop/style/ternary_parentheses.rb, spec/rubocop/cop/style/ternary_parentheses_spec.rb
Fixes #10336.
This PR fixes a false positive for `Style/TernaryParentheses` when using `in` keyword pattern matching as a ternary condition.
=> [Fix #10336] Fix a false positive for `Style/TernaryParentheses`

changelog/change_require_parser_3_1_0_0.md, docs/modules/ROOT/pages/compatibility.adoc, rubocop.gemspec
Ruby 3.1 and Parser 3.1.0.0 have been released.
- https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/
- https://rubygems.org/gems/parser/versions/3.1.0.0
This PR requires Parser 3.1.0.0 or higher and removes "experimental" label from support matrix.
=> Require Parser 3.1.0.0 or higher

changelog/fix_false_negative_for_lint_incompatible_io_select_with_fiber_scheduler.md, lib/rubocop/cop/lint/incompatible_io_select_with_fiber_scheduler.rb, spec/rubocop/cop/lint/incompatible_io_select_with_fiber_scheduler_spec.rb
This PR fixes the following false negative for `Lint/IncompatibleIoSelectWithFiberScheduler` when using `IO.select` with the first argument only.
```ruby
IO.select([io])
```
=> Fix a false negative for `Lint/IncompatibleIoSelectWithFiberScheduler`

changelog/fix_false_positive_for_style_collection_compact.md, lib/rubocop/cop/style/collection_compact.rb, spec/rubocop/cop/style/collection_compact_spec.rb
This PR fixes a false positive for `Style/CollectionCompact` when without receiver for bad methods.
If no receiver is specified, it may be used in a custom method or open class. For custom methods, there is no guarantee that `compact` corresponding to `reject` will exist.
The following is a use case of false positive.
https://github.com/artichoke/artichoke/pull/1582/commits/250bf7e
In fact, without a receiver may lead to false positives for these cases.
=> Fix a false positive for `Style/CollectionCompact`

changelog/new_support_auto_correction_for_naming_forwarding.md, config/default.yml, lib/rubocop/cop/naming/block_forwarding.rb, spec/rubocop/cop/naming/block_forwarding_spec.rb
Fixes #10339 and Follow up to https://github.com/rubocop/rubocop/pull/10290#issuecomment-999708816.
This PR supports auto-correction for `EnforcedStyle: explicit` of `Naming/BlockForwarding`.
User can specify the block variable name for auto-correction with `BlockForwardingName`. The default variable name is `block`. If the name is already in use, it will not be auto-corrected.
=> [Fix #10339] Support auto-correction for `Naming/BlockForwarding`

changelog/new_support_enforced_shorthand_syntax_either_option_for_style_hash_syntax.md, config/default.yml, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, lib/rubocop/cop/style/hash_syntax.rb, spec/rubocop/cli/auto_gen_config_spec.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
Follow up to https://github.com/testdouble/standard/issues/375#issuecomment-1007505392.
This PR supports `EnforcedShorthandSyntax: either` option for `Style/HashSyntax`.
It accepts both shorthand and explicit use of hash literal value.
```ruby
{foo: foo, bar: bar}
{foo:, bar:}
```
I think that we can change the default enforced style in response to future feedback and discussion. Anyway at this point it only adds the new style.
=> Support `EnforcedShorthandSyntax: either` for `Style/HashSyntax`

changelog/fix_improve_argument_alignment_correction.md, lib/rubocop/cop/layout/argument_alignment.rb, spec/rubocop/cop/layout/argument_alignment_spec.rb
This fixes detection of incorrect indentation for the case where
- ArgumentAlignment is configured with EnforcedStyle `with_fixed_indentation`
- A method call has both regular arguments and keyword arguments
- The first keyword argument is on the same line as at least one of the regular arguments
In the original code, the keyword arguments would be seen as one single argument, and because it starts on the same line as the previous argument, alignment adjustment would be skipped.
Also, because of the fixed indentation style, HashAlignment always skips adjustment of the keyword argument block. This means neither cop would correct the alignment.
This change adjusts this behaviour by treating each keyword argument as a separate argument if EnforcedStyle is `with_fixed_indentation`.
This has …
=> [Fix #8032] Improve argument alignment correction for kwargs

changelog/fix_use_different_symbol_in_ruby_3.md, lib/rubocop/cop/lint/ambiguous_regexp_literal.rb, spec/rubocop/cop/lint/ambiguous_regexp_literal_spec.rb
At work, we recently started using Rubocop via [Standard](https://github.com/testdouble/standard), and we still have a long `.rubocop_todo.yml`. Luckily, this helped to uncover a bug in RuboCop! :D
After upgrading a Rails app to Ruby 3.0 and setting `TargetRubyVersion: 3.0`, I noticed that all todos relating to `Lint/AmbiguousRegexpLiteral` disappeared. But we hadn't changed the files, and the "bad" code was still in there.
```diff
- # Offense count: 7
- # Cop supports --auto-correct.
- Lint/AmbiguousRegexpLiteral:
-   Exclude:
-     - 'spec/features/example/example_spec.rb'
-     - 'spec/models/example.rb'
-     - 'spec/views/admin/example/example.haml_spec.rb'
```
Digging further, a colleague and I noticed that this _only_ happened with `TargetRubyVersion: 3.0`, and that the offenses …
=> Use `:ambiguous_regexp` to detect ambiguous Regexp in Ruby 3

changelog/fix_fix_gemspecrequiredrubyversion_version.md, lib/rubocop/cop/gemspec/required_ruby_version.rb, spec/rubocop/cop/gemspec/required_ruby_version_spec.rb
Fixes a bug (which I believe was introduced by #10157) where the `Gemspec/RequiredRubyVersion` cop no longer handled multiple requirements when they were passed as a `Gem::Requirement` object rather than an array.
I.e. the following would fail when the target version was `2.6`:
```
spec.required_ruby_version = Gem::Requirement.new('>= 2.6.0', '< 2.8')
```
Which should pass like the following does:
```
spec.required_ruby_version = ['>= 2.6.0', '< 2.8']
```
=> Fix Gemspec/RequiredRubyVersion version matcher

changelog/fix_style_sample_chrash.md, lib/rubocop/cop/style/sample.rb, spec/rubocop/cop/style/sample_spec.rb
`Style/Sample` crashes when `Array#shuffle` is indexed with beginless or endless range:
```ruby
items.shuffle[...5]
```
This change adds support for reasonable auto-corrections and accepted inputs:
```ruby
items.shuffle[..6]  # => auto-corrects to `items.sample(5)`
items.shuffle[...5] # => auto-corrects to `items.sample(5)` as well
items.shuffle[5...] # accepted, takes everting but the first 5 items
```
=> Fix Style/Sample crash on beginless or endless range shuffle indexes

changelog/fix_false_positive_on_hash_syntax_value_omission.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
👋  Looking for feedback as my current PR could be affecting other cases that I might have not noticed.  🙏 
The PR is more on the safe side of not doing code changes that break the syntax although I understand this might not be the desired direction.
There are certain cases that suggestion of Style/HashSyntax: Omit the hash value and then the autocorrect both (`-a` or `-A`) will produce invalid syntax. 
Here is a scenario of a specific code block:
```ruby
RSpec.shared_examples 'Examples' do |option_a:|
include_examples 'Example A', option_a: option_a if option_a
include_examples 'Example B', option_a: option_a
describe '.describe' do
it { true }
end
include_examples 'Example C', option_a: option_a
end
```
When we run the autocorrect currently will it produce the following result:
```ruby …
```
=> Fix "Style/HashSyntax: Omit the hash value cases" that breaks syntax for specific cases

changelog/fix_cop_generator_for_nested_departments.md, lib/rubocop/cop/generator.rb, spec/rubocop/cop/generator_spec.rb
Fixes #10117 
Unfortunately, currently the generator will generate 
```ruby
module TopDepartment::SecondDepartment
end
``` 
instead of 
```ruby
module TopDepartment
module SecondDepartment
end
end
```
inside the cop source code, which then raises `NameError: uninitialized constant RuboCop::Cop::TopDepartment` if this is the first cop generated in the department and unless module `TopDepartment` exists. So the user should manually update the code to be like in the second example.
We can do this automatically, but this will require a non-trivial amount of ugly code changes to `generator.rb` to handle the case with nested departments. So I'm wondering if this is worth it? This PR already makes life easier.
=> Fix cop generator for nested departments

changelog/fix_false_positive_for_style_hash_syntax.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
Fixes #10359.
This PR fixes a false positive and negative for `Style/HashSyntax` when using hash value omission.
It resolves the lack of consideration for https://bugs.ruby-lang.org/issues/18396 and false positives for modifier forms.
=> [Fix #10359] Fix a false positive and negative for `Style/HashSyntax`

changelog/fix_false_positive_for_style_method_call_with_args_parentheses.md, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
Fixes #10366.
This PR fixes a false positive for `Style/MethodCallWithArgsParentheses` when setting `EnforcedStyle: omit_parentheses` and using hash value omission with modifier from.
=> [Fix #10366] Fix a false positive for `Style/MethodCallWithArgsParentheses`

lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
Follow up to https://github.com/rubocop/rubocop/pull/10363#issuecomment-1016233254.
This PR fixes a false positive for `Style/HashSyntax` when using hash value omission.
It does not have a changelog entry because a regression of unreleased #10363.
=> Fix a false positive for `Style/HashSyntax`

changelog/fix_false_negative_for_style_hash_syntax.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
Follow up to https://github.com/rubocop/rubocop/pull/10368#issuecomment-1017488540.
This PR fixes a false negative for `Style/HashSyntax` when `Hash[foo: foo]` or `{foo: foo}` is followed by a next expression.
https://bugs.ruby-lang.org/issues/18396 issue does not occur when hash syntax is enclosed in `[]`, `{}`, or `()`.
=> Fix a false negative for `Style/HashSyntax`

changelog/fix_an_error_for_layout_rescue_ensure_alignment.md, lib/rubocop/cop/layout/rescue_ensure_alignment.rb, spec/rubocop/cop/layout/rescue_ensure_alignment_spec.rb
Fixes #10376.
This PR fixes an error for `Layout/RescueEnsureAlignment` when using `.()` call with block.
=> [Fix #10376] Fix an error for `Layout/RescueEnsureAlignment`

changelog/fix_an_error_for_layout_empty_lines_around_exception_handling_keywords.md, lib/rubocop/cop/layout/empty_lines_around_exception_handling_keywords.rb, spec/rubocop/cop/layout/empty_lines_around_exception_handling_keywords_spec.rb
Fix #10379.
This PR fixes an error for `Layout/EmptyLinesAroundExceptionHandlingKeywords` when `rescue` and `end` are on the same line.
=> [Fix #10379] Fix an error for `Layout/EmptyLinesAroundExceptionHandlingKeywords`

changelog/fix_an_error_for_style_redundant_begin.md, lib/rubocop/cop/style/redundant_begin.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
Fixes #10387.
This PR fixes an error for `Style/RedundantBegin` when assigning nested `begin` blocks.
=> [Fix #10387] Fix an error for `Style/RedundantBegin`

changelog/fix_an_error_for_style_swap_values.md, lib/rubocop/cop/style/swap_values.rb, spec/rubocop/cop/style/swap_values_spec.rb
Fixes #10394.
This PR fixes an error for `Style/SwapValues` when assigning receiver object at `def`.
=> [Fix #10394] Fix an error for `Style/SwapValues`

changelog/fix_an_error_for_style_hash_alignment.md, lib/rubocop/cop/layout/hash_alignment.rb, spec/rubocop/cli/autocorrect_spec.rb
Fixes #10364.
This PR fixes an infinite loop error for `Layout/HashAlignment` when `EnforcedStyle: with_fixed_indentation` is specified for `Layout/ArgumentAlignment`.
The issue context is that the first keyword argument and the argument before it
are on the same line.
=> [Fix #10364] Fix an infinite loop error for `Style/HashAlignment`

lib/rubocop/formatter/disabled_config_formatter.rb, spec/rubocop/cli/auto_gen_config_spec.rb
The auto-gen-config output will say "Cop supports --auto-correct" for
cops which do not support --auto-correct, but which do support
--auto-correct-all. Let's update the output to reflect that. When
someone is working on the todo list, this can be helpful information to
have at hand.
I'll often run something like:
`bin/rubocop --only Style/StringConcatenation -a` and then realize
actually that won't work, and this would save me a few seconds.
Hi there. This is my first contribution in a few years. Happy to be back. WDYT about this idea?
Unfortunately `bundle exec rake default` is failing for me locally with this test failure, which is unrelated to my change:
<details>
<summary>Failure</summary>
```
==> Failures
1) RuboCop::TargetFinder#find_files prevents infinite loops …
```
=> Update auto-gen-config's comment re auto-correct

lib/rubocop/cop/style/optional_boolean_parameter.rb, spec/rubocop/cop/style/optional_boolean_parameter_spec.rb
Fixes #10397.
This PR fixes offense message for `Style/OptionalBooleanParameter` when defining method with optional boolean arg that has no space.
=> [Fix #10397] Fix offense message for `Style/OptionalBooleanParameter`

changelog/fix_a_false_positive_for_style_hash_syntax.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
Fixes #10401.
This PR fixes a false positive for `Style/HashSyntax` when local variable hash key and hash value are the same.
=> [Fix #10401] Fix a false positive for `Style/HashSyntax`

docs/modules/ROOT/pages/cops_layout.adoc
The current formatting is a bit off, see here:
=> Fix doc formatting for Layout/CaseIndentation

changelog/fix_an_error_for_style_string_concatenation.md, lib/rubocop/cop/style/string_concatenation.rb, spec/rubocop/cop/style/string_concatenation_spec.rb
Fixes #10403.
This PR fixes an error for `Style/StringConcatenation` when string concatenation with multiline heredoc text.
=> [Fix #10403] Fix an error for `Style/StringConcatenation`

changelog/change_mark_lint_inherit_exception_as_unsafe.md, config/default.yml, lib/rubocop/cop/lint/inherit_exception.rb
This PR marks `Lint/InheritException` as unsafe auto-correction.
This cop's autocorrection is unsafe because `rescue` that omit exception class handle `StandardError` and its subclasses,
but not `Exception` and its subclasses.
```ruby
begin
rescue # Handles only `StandardError` and its subclasses because exception class is omitted.
end
```
It's still unsafe after #10406 is resolved.
=> Mark `Lint/InheritException` as unsafe auto-correction

changelog/change_enforced_style_for_lint_inherit_exception.md, config/default.yml, lib/rubocop/cop/lint/inherit_exception.rb
This PR change `EnforcedStyle` from `runtime_error` to `standard_error` for `Lint/InheritException`.
I noticed this while investigating #10406.
Below is the inheritance tree for the exception classes.
```
---------------
|  Exception  |
---------------
^
|
---------------
|StandardError| (default for `rescue`)
---------------
^
|
---------------
|RuntimeError | (default for `raise`)
---------------
```
AFAIK, it seems that custom exceptions generally inherit from `StandardError`.
Subclasses of `StandardError` are handled with `rescue` by default.
`raise` creates a `RuntimeError` when the exception class is omitted.
If custom exception inherits from `RuntimeError`, the custom exception and `RuntimeError` will be is-a.
If custom exception inherits from `StandardError`, the custom exception …
=> Change `EnforcedStyle` to `standard_error` for `Lint/InheritException`

changelog/fix_a_false_positive_for_lint_inherit_exception.md, lib/rubocop/cop/lint/inherit_exception.rb, spec/rubocop/cop/lint/inherit_exception_spec.rb
Fixes https://github.com/testdouble/standard/issues/388 and reverts https://github.com/rubocop/rubocop/pull/3427.
This PR prevents the following false positive and auto-correction.
```diff
class TestClass
-  FatalError = Class.new(Interrupt)
+  FatalError = Class.new(RuntimeError)
end
```
Below is an inheritance tree for the exception classes.
```
---------------
| BasicObject |
---------------
^
|
---------------
|   Kernel    |
---------------
^
|
---------------
|   Object    |
---------------
^
|
---------------
|  Exception  |
---------------
^
|
|------------------|
---------------  -----------------
|StandardError|  |SignalException|
---------------  -----------------
^                  ^
|                  |
---------------  -----------------
|RuntimeError |  |   Interrupt   | …
```
=> Fix a false positive for `Lint/InheritException`

changelog/fix_an_error_for_lint_useless_times.md, lib/rubocop/cop/lint/useless_times.rb, spec/rubocop/cop/lint/useless_times_spec.rb
Fixes #10415.
This PR fixes an error for `Lint/UselessTimes` when using `1.times` with method chain.
This bug fix case does not support auto-correction because it is complicated to cover the usage of the methods of `Enumerator` returned by `Integer#times` method.
=> [Fix #10415] Fix an error for `Lint/UselessTimes`

lib/rubocop/cop/layout/multiline_operation_indentation.rb
It was unclear that the special rule for `return` statements (and other cases where an operation follows a keyword) did not include implicit returns.
Also, the examples given for the `aligned` style did not reflect was was said about the second operand always being indented except after a keyword.
=> [Fix #10345] Update docs for MultilineOperationIndentation

changelog/fix_a_false_positive_for_security_yaml_load.md, lib/rubocop/cop/security/yaml_load.rb, lib/rubocop/cop/variable_force.rb, spec/rubocop/cop/security/yaml_load_spec.rb
This PR fixes a false positive for `Security/YamlLoad` when using Ruby 3.1+ (Psych 4).
And it also makes the examples a bit more specific.
Ruby 3.1+ (Psych 4) uses `Psych.load` as `Psych.safe_load` by default.
https://github.com/ruby/psych/pull/487
We may consider removing this cop in the future, but not yet.
=> Fix a false positive for `Security/YamlLoad`

changelog/fix_make_style_def_with_parentheses_aware_of_endless_method_definition.md, lib/rubocop/cop/style/def_with_parentheses.rb, spec/rubocop/cop/style/def_with_parentheses_spec.rb
Fixes #10421.
This PR makes `Style/DefWithParentheses` aware of endless method definition.
`def foo() do_something end` will continue to allow because `def foo do_something end` is a syntax error.
On the other hand, be aware that the endless method definition's parentheses can be omitted.
=> [Fix #10421] Make `Style/DefWithParentheses` aware of endless method definition

changelog/change_mark_style_for_as_unsafe.md, config/default.yml, lib/rubocop/cop/style/for.rb
- The Ruby Style Guide (https://rubystyle.guide/#no-for-loops) states that "for doesn’t introduce a new scope (unlike each) and variables defined in its block will be visible outside it". This means that auto-correcting can break existing, working code because of the change in variable scope.
- Fixes #10427.
The only thing I didn't do in the PR checklist is add tests, because a recent, different PR to mark a cop as unsafe (10408) didn't have any. Hope that's OK!
=> [Fix #10427] Style/For: Mark auto-correction as unsafe

CONTRIBUTING.md
- Apparently this is no longer necessary, automation populates the username links: https://github.com/rubocop/rubocop/pull/10429#discussion_r810593622.
=> CONTRIBUTING: Remove instruction for first-timers to edit the CHANGELOG

changelog/change_auto_correct_message.md, lib/rubocop/formatter/disabled_config_formatter.rb, spec/rubocop/cli/auto_gen_config_spec.rb, spec/rubocop/formatter/disabled_config_formatter_spec.rb
This is a follow-up to https://github.com/rubocop/rubocop/pull/10384, following a suggestion from bbatsov in the code review.
=> Update auto-gen-config's auto-correction comments

changelog/new_support_ruby_3_2_experimental.md, docs/modules/ROOT/pages/compatibility.adoc, lib/rubocop/rspec/shared_contexts.rb, lib/rubocop/target_ruby.rb, rubocop.gemspec, spec/rubocop/cli_spec.rb
RuboCop AST 1.6 supports Ruby 3.2.
https://github.com/rubocop/rubocop-ast/pull/223.
This PR supports `TargetRubyVersion 3.2`.
=> Support `TargetRubyVersion 3.2` (experimental)

changelog/fix_an_error_when_using_regexp_with_noencoding_option.md, lib/rubocop/cop/variable_force.rb, spec/rubocop/cop/variable_force_spec.rb
This PR fixes the following error when using regexp with non-encoding option.
```console
% cat /tmp/example.rb
/\x82/n =~ 'a'
% rubocop -d /tmp/example.rb
(snip)
For /tmp: An error occurred while VariableForce cop was inspecting /tmp/example.rb.
invalid multibyte escape: /\x82/
/Users/koic/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/cop/variable_force.rb:193:in
`initialize'
/Users/koic/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rubocop-1.25.1/lib/rubocop/cop/variable_force.rb:193:in `new'
```
This error is due to `VariableForce#regexp_captured_names` not processing the regexp option.
This PR uses `RegexpNode#to_regexp` to prevent the regexp option from being cut.
In addition, the test code replaces the Parser gem (plain) AST with `ProcessedSource#ast` so …
=> Fix an error when using regexp with non-encoding option

lib/rubocop/cop/generator.rb, spec/rubocop/cop/generator_spec.rb
After generating a new cop, we get the following offense:
InternalAffairs/NodeMatcherDirective: Precede def_node_matcher with a @!method YARD directive.
Since this is mandatory, the generator template should include it.
_No user observable change_
=> Add YARD node matcher annotation to generator

lib/rubocop/cop/generator.rb
Rubocop only supports Ruby 2.5+ now, so as per the comment we can clean this up.
I noticed while editing the generator in #10442.
* ~Added tests.~ _Not applicable_
_No user-observable changes_
=> Replace `<<-HEREDOC.gsub(indent)` with `<<~HEREDOC`

lib/rubocop/cops_documentation_generator.rb
This fixes an issue where file paths were not escaped and were displayed as follows:
* [-] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
=> Fix doc formatting written in unescaped file path

config/default.yml, docs/modules/ROOT/pages/cops_gemspec.adoc, lib/rubocop/cop/gemspec/require_mfa.rb
I got the error, and did not remember what MFA meant. The doc did not help, hence this pull request to add the acronym meaning.
=> Indicate what MFA means in Gemspec/RequireMFA doc

changelog/fix_an_error_style_sole_nested_conditional.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/10436.
This PR fixes an error for `Style/SoleNestedConditional` when code like the following:
```ruby
if foo
do_something
end if bar
```
=> [Fix #10436] Fix an error for `Style/SoleNestedConditional` raises exception when inspecting `if ... end if ...`

changelog/fix_false_positive_for_layout_multiline_method_call_indentation.md, lib/rubocop/cop/mixin/multiline_expression_indentation.rb, spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb
Fixes #10456.
This PR fixes a false positive for `Layout/MultilineMethodCallIndentation` when using `EnforcedStyle: indented` with indented assignment method.
=> [Fix #10456] Fix a false positive for `Layout/MultilineMethodCallIndentation`

changelog/fix_unless_else_autocorrect.md, lib/rubocop/cop/style/unless_else.rb, spec/rubocop/cop/style/unless_else_spec.rb
An `unless`/`else` nested inside another `unless`/`else` would cause rewrite clobbering when auto-correcting both offenses. By ignoring the node after correcting it and skipping auto-correction for inner nodes with the same offense, we avoid this problem.
The auto-correct loop will pick up the remaining offense and fix it. No test case is added for this particular aspect, but it's standard RuboCop behavior.
=> [Fix #10375] Defer auto-correction of nested unless/else

changelog/fix_make_style_select_by_regexp_aware_of_env_const.md, lib/rubocop/cop/style/select_by_regexp.rb, spec/rubocop/cop/style/select_by_regexp_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/10155#issuecomment-1071477282.
This PR makes `Style/SelectByRegexp` aware of `ENV` const.
=> Make `Style/SelectByRegexp` aware of `ENV` const

changelog/fix_an_incorrect_autocorrect_for_lint_symbol_conversion.md, lib/rubocop/cop/lint/symbol_conversion.rb, spec/rubocop/cop/lint/symbol_conversion_spec.rb
Fixes #10462.
This PR fixes an incorrect autocorrect for `Lint/SymbolConversion` when using a quoted symbol key with hash rocket.
=> [Fix #10462] Fix an incorrect autocorrect for `Lint/SymbolConversion`

changelog/fix_a_false_positive_for_layout_line_length.md, lib/rubocop/cop/mixin/line_length_help.rb, spec/rubocop/cop/layout/line_length_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/10374
This PR fixes a false positive for `Layout/LineLength` when when long URIs in yardoc comments to have titles.
=> [Fix #10374] Fix a false positive for `Layout/LineLength` when long URIs in yardoc comments to have titles

changelog/fix_fix_false_positive_for.md, lib/rubocop/cop/naming/block_forwarding.rb, spec/rubocop/cop/naming/block_forwarding_spec.rb
If the block argument is used in an assignment, it has to be explicitly named.
Fixes #10465.
=> [Fix #10465] Fix false positive for `Naming/BlockForwarding` when the block argument is redefined

lib/rubocop/config_obsoletion/extracted_cop.rb
The current implementation has the problem of not being able to create a Cop named `RailsFoo/Bar` or `PerformanceFoo/Bar`.
In fact, I tried to create a Cop named `RailsDeprecation/ToFormattedS` in the following gem, but it didn't work because of this problem (I renamed it with `Deprecation/ToFormattedS` as a workaround for now):
- https://github.com/r7kamura/rubocop-rails_deprecation
=> Fix obsolete department checker

changelog/fix_fix_false_positive_for_double_negation.md, lib/rubocop/cop/style/double_negation.rb, spec/rubocop/cop/style/double_negation_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/10474
This PR fixes a false positive for `Style/DoubleNegation` when code like the following:
```ruby
def foo?
if condition_foo?
!!foo
elsif condition_bar?
do_something
!!bar
else
!!baz
end
end
def foo
if condition_foo?
{ foo: !!foo0, bar: bar0, baz: baz0 }
elsif condition_bar?
do_something
{ foo: !!foo1, bar: bar1, baz: baz1 }
else
{ foo: !!foo2, bar: bar2, baz: baz2 }
end
end
def foo
case condition
when foo
[ !!foo0, bar0, baz0 ]
when bar
do_something
[ !!foo1, bar1, baz1 ]
else
[ !!foo2, bar2, baz2 ]
end
end
```
=> [Fix #10474] Fix a false positive for `Style/DoubleNegation` with `EnforcedStyle: allowed_in_returns` when inside returned conditional clauses

changelog/fix_a_false_positive_for_style_file_write.md, lib/rubocop/cop/style/file_write.rb, spec/rubocop/cop/style/file_write_spec.rb
Fixes #10468
This PR fixes a false positive for `Style/FileWrite` when a splat argument is passed to `f.write`.
There are different method signatures between `File.write` (class method) and `File#write` (instance method).
- https://ruby-doc.org/core-3.1.1/IO.html#method-c-write
- https://ruby-doc.org/core-3.1.1/IO.html#method-i-write
This PR accepts the case of using splat argument as an argument for `File#write` because static analysis does not know the contents of the splat argument.
=> [Fix #10468] Fix a false positive for `Style/FileWrite`

changelog/fix_an_incorrect_autocorrect_for_lint_incompatible_io_select_with_fiber_scheduler.md, lib/rubocop/cop/lint/incompatible_io_select_with_fiber_scheduler.rb, spec/rubocop/cop/lint/incompatible_io_select_with_fiber_scheduler_spec.rb
Fixes #10464.
This PR fixes an incorrect autocorrect for `Lint/IncompatibleIoSelectWithFiberScheduler` when using `IO.select` with read (or write) argument and using return value.
When the method is successful the return value of `IO.select` is `[[IO]]`, and the return value of `io.wait_readable` and `io.wait_writable` are `self`.
They are not auto-corrected when assigning a return value because these types are different. It's up to user how to handle the return value.
=> [Fix #10464] Fix an incorrect autocorrect for `Lint/IncompatibleIoSelectWithFiberScheduler`

changelog/fix_fix_false_positive_for_shadowing_outer_local_variable_conditional_statement.md, lib/rubocop/cop/lint/shadowing_outer_local_variable.rb, spec/rubocop/cop/lint/shadowing_outer_local_variable_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/10479
=> [Fix #10479] Fix a false positive for `Lint/ShadowingOuterLocalVariable` conditional statement and block variable

config/default.yml, spec/rubocop/cop/lint/useless_method_definition_spec.rb
The `AllowComments` was removed from the `UselessMethodDefinition` cop in 92d3fc681fff7961bdba701f9dbdffd2f08e4350 but the config was not updated to reflect that.
=> Remove obsolete AllowComments option

changelog/fix_comment_handling_when_allow_comments_is_true.md, lib/rubocop/cop/lint/empty_conditional_body.rb, lib/rubocop/cop/lint/empty_in_pattern.rb, lib/rubocop/cop/lint/empty_when.rb, lib/rubocop/cop/mixin/comments_help.rb, spec/rubocop/cop/lint/empty_conditional_body_spec.rb, spec/rubocop/cop/lint/empty_in_pattern_spec.rb, spec/rubocop/cop/lint/empty_when_spec.rb
This fixes the remaining issue in #7999 and also the same issue appearing in 2 other cops: `Lint/EmptyConditionalBody` and `Lint/EmptyInPattern`
=> Consider only the comments relevant for the node being checked

changelog/fix_a_false_positive_for_style_hash_syntax.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
Fixes #10494.
This PR fixes a false positive for `Style/HashSyntax` when `return` with one line `if` condition follows (without parentheses).
=> [Fix #10494] Fix a false positive for `Style/HashSyntax`

changelog/fix_a_false_positive_for_lint_lambda_without_literal_block.md, lib/rubocop/cop/lint/lambda_without_literal_block.rb, spec/rubocop/cop/lint/lambda_without_literal_block_spec.rb
Fixes #10489.
This PR fixes a false positive for `Lint/LambdaWithoutLiteralBlock` when using lambda with a symbol proc.
=> [Fix #10489] Fix a false positive for `Lint/LambdaWithoutLiteralBlock`

changelog/fix_fix_an_incorrectly_adds_a_disable_statement_for_space_inside_array_literal_brackets.md, lib/rubocop/cop/autocorrect_logic.rb, lib/rubocop/cop/mixin/surrounding_space.rb, spec/rubocop/cli/disable_uncorrectable_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/10388
=> [Fix #10388] Fix an incorrectly adds a disable statement for `Layout/SpaceInsideArrayLiteralBrackets` with `--disable-uncorrectable`

changelog/fix_display-style-guide.md, lib/rubocop/formatter/offense_count_formatter.rb, spec/rubocop/formatter/offense_count_formatter_spec.rb
Up until now, a `--display-style-guide` given together with `--format offenses` has just been swallowed without affecting the output. This is probably not what users expect.
Let the `OffenseCountFormatter` retrieve style guide links by checking if `--display-style-guide` was given and then parse the offense messages.
=> [Fix #10189] Support --display-style-guide with -f offenses

lib/rubocop/result_cache.rb
This is a proposal not to have the symlink warning on the FreeBSD system.
ref: #6228
=> Fix symlink warning always triggered on FreeBSD

changelog/fix_a_false_positive_for_lint_unused_method_argument.md, lib/rubocop/cop/lint/unused_method_argument.rb, spec/rubocop/cop/lint/unused_method_argument_spec.rb
Fixes #10504.
This PR fixes a false positive for `Lint/UnusedMethodArgument` when using `raise NotImplementedError` with optional arguments.
=> [Fix #10504] Fix a false positive for `Lint/UnusedMethodArgument`

changelog/fix_an_error_for_style_raise_args.md, lib/rubocop/cop/style/raise_args.rb, spec/rubocop/cop/style/raise_args_spec.rb
Fixes #10506.
This PR fixes an error for `Style/RaiseArgs` when `raise` with `new` method without receiver.
=> [Fix #10506] Fix an error for `Style/RaiseArgs`

changelog/change_add_option_for_safe_navigation.md, config/default.yml, lib/rubocop/cop/style/safe_navigation.rb, spec/rubocop/cop/style/safe_navigation_spec.rb
Resolve #10191
This PR add `MaxChainLength` option to `Style/SafeNavigation` and the option is 2 by default.
=> [Fix#10191] Add `MaxChainLength` option to `Style/SafeNavigation`

changelog/fix_an_error_for_style_single_argument_dig.md, lib/rubocop/cop/style/single_argument_dig.rb, spec/rubocop/cop/style/single_argument_dig_spec.rb
Fixes #10510.
This PR fixes an error for `Style/SingleArgumentDig` when using multiple `dig` in a method chain.
And this is the same solution as #10461.
=> [Fix #10510] Fix an error for `Style/SingleArgumentDig`

changelog/change_add_option_for_guard_clause.md, config/default.yml, lib/rubocop/cop/style/guard_clause.rb, spec/rubocop/cop/style/guard_clause_spec.rb
Resolve #10356
This PR add `AllowConsecutiveConditionals` option to `Style/GuardClause` and the option is false by default.
=> [FIx #10356] Add `AllowConsecutiveConditionals` option to `Style/GuardClause`

changelog/new_add_security_compound_hash_cop.md, config/default.yml, lib/rubocop.rb, lib/rubocop/cop/offense.rb, lib/rubocop/cop/security/compound_hash.rb, lib/rubocop/cop/variable_force/branch.rb, spec/rubocop/cop/security/compound_hash_spec.rb
Hash codes for Ruby objects are a potential security issue. Bad hash codes may make us vulnerable to denial-of-service-attacks, where users are able to craft objects that trigger hash collisions. Hash collisions may cause linear instead of constant-time behaviour, or they may cause thrashing of caches. Let Ruby's implementation manage the construction of hash codes from multiple objects using `Array#hash`, via `[...].hash`, rather than rolling your own hash.
This cop checks implementations of the `hash` method which combine value using the XOR operator instead of delegating to `Array#hash`.
`Array#hash` is
- faster
- clearer
- standardized
Ruby has an existing way to combine multiple hash values, so users should not implement their own. …
=> Add `Security/CompoundHash` cop

docs/modules/ROOT/pages/cops_gemspec.adoc, lib/rubocop/cop/gemspec/date_assignment.rb
This PR fixes typo for Gemspec/DateAssignment examples.
- Variable names are corrected from `s` to `spec`.
=> Fix typo for Gemspec/DateAssignment examples

changelog/fix_an_error_for_lint_empty_conditional_body.md, lib/rubocop/cop/mixin/comments_help.rb, spec/rubocop/cop/lint/empty_conditional_body_spec.rb
Fixes #10514.
This PR fixes an error for `Lint/EmptyConditionalBody` when missing second `elsif` body.
=> [Fix #10514] Fix an error for `Lint/EmptyConditionalBody`

changelog/fix_autocorrect_for_style_sole_nested_confitional.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
=> [Fix #10529] Fix autocorrect for `Style/SoleNestedConditional`

changelog/change_mark_unsafe_for_style_redundant_initialize.md, config/default.yml, lib/rubocop/cop/style/redundant_initialize.rb
Fixes #10524.
This PR marks `Style/RedundantInitialize` as unsafe because if subclass overrides `initialize` method with a different arity than superclass.
```ruby
class Base
def initialize
end
end
class Derived < Base
def initialize(arg)
end
end
Derived.new(arg) # Requires one argument.
```
Therefore, the following is a false positive.
```console
% bundle exec rubocop example.rb --only Style/RedundantInitialize
C
Offenses:
example.rb:8:3: C: Style/RedundantInitialize: Remove unnecessary empty initialize method.
def initialize(a) ...
^^^^^^^^^^^^^^^^^
```
The same can be said for Module mix-in, which cannot be determined by static analysis.
[1]: …
=> [Fix #10524] Mark `Style/RedundantInitialize` as unsafe

changelog/fix_code_length_calculation_when_kwargs_written_in_single_line.md, lib/rubocop/cop/metrics/utils/code_length_calculator.rb, spec/rubocop/cop/metrics/utils/code_length_calculator_spec.rb
Fixes #10469.
This PR fixes a wrong calculation for code length of kwargs at single line when asked folding.
=> [Fix #10469] Fix code length calculation when kwargs written in single line

changelog/fix_a_false_positive_for_style_redundant_regexp_character_class.md, lib/rubocop/cop/style/redundant_regexp_character_class.rb, spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb
Fixes #10530.
This PR fixes a false positive for `Style/RedundantRegexpCharacterClass` when using regexp character class with a character class containing multiple unicode code-points.
=> [Fix #10530] Fix a false positive for `Style/RedundantRegexpCharacterClass`

changelog/new_support_autocorrect_for_lint_duplicate_require.md, config/default.yml, lib/rubocop/cop/lint/duplicate_require.rb, spec/rubocop/cop/lint/duplicate_require_spec.rb
This PR supports auto-correction for `Lint/DuplicateRequire`.
The auto-correction is unsafe because it may break the dependency order of `require`.
=> Support auto-correction for `Lint/DuplicateRequire`

changelog/fix_an_error_for_alignment.md, lib/rubocop/cop/layout/case_indentation.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/layout/case_indentation_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/10528
The following rubocop.yml and run rubocop, resulted in an infinite loop.
```
Layout/BeginEndAlignment:
EnforcedStyleAlignWith: start_of_line
AutoCorrect: true
Layout/CaseIndentation:
EnforcedStyle: end
```
This doesn’t always occur, but only in edge cases.
This occurs when `when` and `end` are on the same line, as in the following code:
```
case thing
when 3 then 1
when 2 then 2
else 3 end
```
This means that if `Layout/CaseIndentation` is `EnforcedStyle: end` and `when` or `else` is on the same line as `end`, it will try to adjust the indentation of `else` or `end` to match that of `end`, but will not Because they are on the same line, the indentation adjustment will run many times.
So, if `when` or `else` is on the same line as `end` …
=> [Fix #10528] Fix an infinite loop at autocorrect for `Layout/CaseIndentation`

Gemfile, spec/rubocop/config_obsoletion/renamed_cop_spec.rb, spec/rubocop/cop/annotation_comment_spec.rb, spec/rubocop/version_spec.rb
You can see the new changes at https://github.com/rubocop/rubocop-rspec/releases/tag/v2.10.0 – the most relevant being the addition of an `RSpec/VerifiedDoubleReference` cop that suggests using class references instead of strings as argument to e.g. `instance_double`.
=> Upgrade RuboCop-RSpec to the latest version

changelog/new_add_allow_comments_option_for_style_redundant_initialize.md, config/default.yml, lib/rubocop/cop/style/redundant_initialize.rb, spec/rubocop/cop/style/redundant_initialize_spec.rb
Follow up https://github.com/rubocop/rubocop/issues/10524#issuecomment-1102191692.
This PR add `AllowComments` option to `Style/RedundantInitialize` is true by default.
```ruby
def initialize
end
def initialize
end
```
This cop has been reported as false positive and has already been marked as unsafe. In addition, cases such as the follow up address have been reported. This PR allows intentional overrides with explicit comments to be allowed by default.
=> Add `AllowComments` option to `Style/RedundantInitialize`

changelog/fix_incorrect_code_length_calculations.md, lib/rubocop/cop/metrics/utils/code_length_calculator.rb, spec/rubocop/cop/metrics/utils/code_length_calculator_spec.rb
Follow up #10469 and #10520.
This PR improve code length calculation for few more patterns like follows:
```rb
def test
foo(
foo,
foo: :bar,
)
end
def test
foo(foo: :bar,
baz: :quux)
end
```
Previously, it always subtracted 2 under certain conditions, but now it considers cases where hash begins/ends on the same line as the parentheses or there are other arguments.
=> Fix incorrect code length calculations for few more patterns

.rubocop.yml, changelog/new_add_command_line_options.md, docs/modules/ROOT/pages/usage/basic_usage.adoc, lib/rubocop/options.rb, lib/rubocop/runner.rb, spec/rubocop/options_spec.rb, spec/rubocop/runner_spec.rb
Resolves #10481.
Added `--display-only-correctable` and `--display-only-safe-correctable` requested by the issue.
=> [Fix #10481] Add command-line options to return only correctable offenses

changelog/fix_an_incorrect_autocorrect_for_style_special_global_vars.md, lib/rubocop/cop/style/special_global_vars.rb, spec/rubocop/cop/style/special_global_vars_spec.rb
This PR fixes the following incorrect autocorrect for `Style/SpecialGlobalVars` when global variable as Perl name is used multiple times.
Example:
```ruby
$*[0]
$*[1]
% bundle exec rubocop --only Style/SpecialGlobalVars -A
Inspecting 3 files
.C.
Offenses:
example.rb:1:1: C: [Corrected] Style/SpecialGlobalVars: Prefer $ARGV
from the stdlib 'English' module (don't forget to require it) or ARGV
over $*.
$*[0]
^^
example.rb:2:1: C: [Corrected] Style/SpecialGlobalVars: Prefer $ARGV
from the stdlib 'English' module (don't forget to require it) or ARGV
over $*.
$*[1]
^^
3 files inspected, 2 offenses detected, 2 offenses corrected
```
This auto-correction will add `require 'English'` twice:
```ruby
require 'English'
require 'English'
$ARGV[0]
$ARGV[1]
```
This PR …
=> Fix an incorrect autocorrect for `Style/SpecialGlobalVars`

changelog/fix_layout_multiline_method_call_indentation_for_nesting.md, lib/rubocop/cop/layout/multiline_method_call_indentation.rb, spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb
Fixes #10488.
Please see also #10549.
=> [Fix #10488] Fix autocorrection for `Layout/MultilineMethodCallIndentation` breaks indentations

changelog/change_add_option_for_symbol_proc.md, config/default.yml, lib/rubocop/cop/style/symbol_proc.rb, spec/rubocop/cop/style/symbol_proc_spec.rb
Resolve: https://github.com/rubocop/rubocop/issues/10280
=> [Fix #10280] Add `AllowComments` option to `Style/SymbolProc`

changelog/fix_fix_crash_with_trailing_tabs_in_heredocs.md, lib/rubocop/cop/layout/trailing_whitespace.rb, spec/rubocop/cop/layout/trailing_whitespace_spec.rb
Fix `undefined method ``length' for nil:NilClass` when encountering a trailing tab in a heredoc.
Fixes #10553.
=> [Fix #10553] Fix crash with trailing tabs in heredocs for `Layout/TrailingWhitespace`

changelog/new_support_autocorrect_for_style_redundant_initialize.md, lib/rubocop/cop/style/redundant_initialize.rb, spec/rubocop/cop/style/redundant_initialize_spec.rb
This PR supports autocorrection for `Style/RedundantInitialize`.
=> Support autocorrection for `Style/RedundantInitialize`

changelog/fix_a_false_positive_for_style_fetch_env_var.md, lib/rubocop/cop/style/fetch_env_var.rb, spec/rubocop/cop/style/fetch_env_var_spec.rb
Fixes #10557.
This PR fixes a false positive for `Style/FetchEnvVar` when `ENV['key']` is a receiver of `||=`.
=> [Fix #10557] Fix a false positive for `Style/FetchEnvVar`

changelog/fix_crash_on_codelengthcalculator_if.md, lib/rubocop/cop/metrics/utils/code_length_calculator.rb, spec/rubocop/cop/metrics/utils/code_length_calculator_spec.rb
First I apologize for introduced the crash into the anniversary version. I love RuboCop and will work more carefully in the future. 
Fixes #10559.
=> [Fix #10559] Fix crash on CodeLengthCalculator if method call is not parenthesized

changelog/fix_a_false_positive_for_lint_ambiguous_block_association.md, lib/rubocop/cop/lint/ambiguous_block_association.rb, spec/rubocop/cop/lint/ambiguous_block_association_spec.rb
Fixes #10566.
This PR fixes a false positive for `Lint/AmbiguousBlockAssociation` when using proc is used as a last argument.
=> [Fix #10566] Fix a falase positive for `Lint/AmbiguousBlockAssociation`

changelog/fix_style_blockdelimiters_deletes_block_on_moving_comment.md, lib/rubocop/cop/style/block_delimiters.rb, spec/rubocop/cop/style/block_delimiters_spec.rb
...on moving comment if methods with block are chained.
Fixes #10563.
This PR fixes `Style/BlockDelimiters` not correctly looking for the end of method chain with block. (The test is passing, but I'm worry about it's not destroying the other cases.)
=> [Fix #10563] Fix `Style/BlockDelimiters` unexpectedly deletes block

changelog/fix_a_false_positive_for_single_argment_dig.md, lib/rubocop/cop/style/single_argument_dig.rb, spec/rubocop/cop/style/single_argument_dig_spec.rb
=> [Fix #10574] Fix a false positive for `Style/SingleArgumentDig`

changelog/fix_a_style_fetch_env_var.md, lib/rubocop/cop/style/fetch_env_var.rb, spec/rubocop/cop/style/fetch_env_var_spec.rb
This PR improves the edge case of `Style/FetchEnvVar`.
There are cases that are false positive and true negative, and it improves them.
false positive cases are as follows:
```ruby
ENV['X'] &&= y
```
true negative cases are as follows:
```ruby
y ||= ENV['X']
y &&= ENV['X']
```
This PR follows up on the same issue as the Issue raised at https://github.com/rubocop/rubocop/issues/10557.
=> Fix a false positive and a true negative for `Style/FetchEnvVar`

changelog/fix_a_false_positive_for_layout_space_before_brackets.md, lib/rubocop/cop/layout/space_before_brackets.rb, spec/rubocop/cop/layout/space_before_brackets_spec.rb
…when using desugared `Hash#[]` method.
Fixes #10573.
=> [Fix #10573] Fix a false positive for `Layout/SpaceBeforeBrackets`

changelog/new_add_new_option_to_namingvariablenumber.md, config/default.yml, lib/rubocop/cop/naming/variable_name.rb, lib/rubocop/cop/naming/variable_number.rb, spec/rubocop/cop/naming/variable_name_spec.rb, spec/rubocop/cop/naming/variable_number_spec.rb
Fix #10539, redo of #10540
Also fix global variables not being matched correctly, discovered by
filling in the tests with global variable examples and having failures.
=> Add AllowedPatterns to Naming/VariableNumber,VariableName

changelog/fix_a_false_positive_for_style_fetch_env_var.md, lib/rubocop/cop/style/fetch_env_var.rb, spec/rubocop/cop/style/fetch_env_var_spec.rb
Fixes #10579.
This PR fixes a false positive for `Style/FetchEnvVar` when calling a method with safe navigation.
=> [Fix #10579] Fix a false positive for `Style/FetchEnvVar`

changelog/fix_autocorrect_for_styleraiseargs.md, lib/rubocop/cop/style/raise_args.rb, spec/rubocop/cop/style/raise_args_spec.rb
…and exception object is assigned to a local variable.
Fixes #10589.
=> [Fix #10589] Fix autocorrect for `Style/RaiseArgs` with `EnforcedStyle: compact`

.rubocop.yml, changelog/new_add_gemspec_dependency_version_cop.md, config/default.yml, lib/rubocop.rb, lib/rubocop/cop/gemspec/dependency_version.rb, rubocop.gemspec, spec/rubocop/cop/gemspec/dependency_version_spec.rb
Resolves #10570.
This cop requires/forbids version specifications or a commit reference for gem dependency in gemspec.
The name for cop suggested in the issue was `GemVersion`, but I'm renaming it because cop is interested in the version of the dependency, not the gem owning gemspec.
```ruby
spec.add_dependency 'rubocop'
end
spec.add_dependency 'rubocop', '~> 1.28'
end
```
```ruby
spec.add_dependency 'rubocop', '~> 1.28'
end
spec.add_dependency 'rubocop'
end
```
=> [Fix #10570] Add new `Gemspec/DependencyVersion` cop

changelog/fix_a_false_positive_for_style_fetch_env_var_cop.md, lib/rubocop/cop/style/fetch_env_var.rb, spec/rubocop/cop/style/fetch_env_var_spec.rb
Fixes #10581.
This PR fixes a false positive for `Style/FetchEnvVar` when comparing with `ENV['TERM']`.
`ENV['DISABLE_DOTENV'] != '1'` could be treated the same as the already allowed in `used_as_flag?` (that is, used as a flag).
=> [Fix #10581] Fix a false positive for `Style/FetchEnvVar`

changelog/fix_a_false_positive_double_negation.md, lib/rubocop/cop/style/double_negation.rb, spec/rubocop/cop/style/double_negation_spec.rb
=> [Fix #10586] Fix a false positive for `Style/DoubleNegation`

changelog/fix_validation_for_commandline_options.md, lib/rubocop/options.rb, spec/rubocop/options_spec.rb
… of `--display-only-fail-level-offenses` and `--auto-correct`
Fixes #10536.
I looked at the files at f3716273260a45fcb1bbcc01df47c0c87d8d770f, and there was no flag that matched `autocorrect` exactly, so I can't be sure, but I think this is a bug.
=> [Fix #10536] Fix validation for command-line options combination

changelog/fix_infinite_loop_on_style_multiline_ternary_operator.md, lib/rubocop/cop/style/multiline_ternary_operator.rb, spec/rubocop/cop/style/multiline_ternary_operator_spec.rb
…if using assignment method and condition/branch is multiline.
Fixes #10592.
=> [Fix #10592] Fix infinite loop on `Style/MultilineTernaryOperator`

changelog/change_enhance_the_autocorrect_for_fetch_env_var.md, config/default.yml, lib/rubocop/cop/style/fetch_env_var.rb, spec/rubocop/cop/style/fetch_env_var_spec.rb
https://github.com/rubocop/rubocop/issues/10578
This PR enhances the autocorrect for `Style/FetchEnvVar`.
When an `ENV[]` is the LHS of `||`, the autocorrect makes the RHS the default value of `ENV.fetch`.
Examples
```ruby
ENV['X'] || 'y'
ENV.fetch('X', 'y')
```
```ruby
ENV['X'] || ENV['Y'] || a
ENV.fetch('X') { ENV.fetch('Y') { a } }
```
```ruby
z || ENV['X'] || y || ENV['Z'] || a || ENV['B']
z || ENV.fetch('X') { y } || ENV.fetch('Z') { a } || ENV.fetch('B', nil)
```
```ruby
ENV['X'] || y.map do |a|
a * 2
end
ENV.fetch('X') do
y.map do |a|
a * 2
end
end
```
Please refer to the RSpec file for more examples.
=> Enhance the autocorrect for `Style/FetchEnvVar`

lib/rubocop/cop/gemspec/duplicated_assignment.rb, lib/rubocop/cop/internal_affairs.rb, lib/rubocop/cop/internal_affairs/method_name_end_with.rb, lib/rubocop/cop/lint/return_in_void_context.rb, lib/rubocop/cop/naming/predicate_name.rb, lib/rubocop/cop/style/collection_compact.rb, lib/rubocop/cop/style/redundant_self_assignment.rb, lib/rubocop/cop/style/trivial_accessors.rb, spec/rubocop/cop/internal_affairs/method_name_end_with_spec.rb
Added new cop inspired by https://github.com/rubocop/rubocop/pull/10594#discussion_r862368888.
This cop checks potentially usage of method identifier predicates instead of `method_name.to_s.end_with?`.
```ruby
node.method_name.to_s.end_with?('=')
node.assignment_method?
node.method_name.to_s.end_with?('?')
node.predicate_method?
node.method_name.to_s.end_with?('!')
node.bang_method?
```
I also did some refactoring of existing cops to conform to this cop.
=> Add new `InternalAffairs/MethodNameEndWith` cop

.rubocop.yml, CODE_OF_CONDUCT.md, docs/modules/ROOT/pages/usage/auto_correct.adoc, docs/modules/ROOT/pages/usage/basic_usage.adoc, lib/rubocop/cop/lint/ambiguous_range.rb, lib/rubocop/cop/lint/loop.rb, lib/rubocop/cop/lint/non_deterministic_require_order.rb, lib/rubocop/cop/lint/or_assignment_to_constant.rb, lib/rubocop/cop/lint/raise_exception.rb, lib/rubocop/cop/security/yaml_load.rb, lib/rubocop/cop/style/and_or.rb, lib/rubocop/cop/style/case_like_if.rb, lib/rubocop/cop/style/date_time.rb, lib/rubocop/cop/style/identical_conditional_branches.rb, lib/rubocop/cop/style/optional_arguments.rb, lib/rubocop/cop/style/optional_boolean_parameter.rb, lib/rubocop/cop/style/redundant_regexp_character_class.rb, lib/rubocop/cop/style/redundant_regexp_escape.rb, lib/rubocop/cop/style/safe_navigation.rb, lib/rubocop/cop/style/string_chars.rb
This PR is unified word fluctuation.
Use "behavior" instead of "behaviour"
~* [ ] Added tests.~
~* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.~
=> Tweak uniformity of expression was implemented

docs/modules/ROOT/pages/installation.adoc
Version 1.0 is already out, so this note feels unnecessary.
I just edited this on GitHub. Apologies for the poor branch name, let me know if you need a better one :)
=> Remove an old reference to version 1.0

changelog/fix_enhance_style_redundantcondition.md, lib/rubocop/cop/style/redundant_condition.rb, spec/rubocop/cop/style/redundant_condition_spec.rb
Fixes #10325.
The example using `nil?` given in the issue is not supported here, as it would destroy the code whose intent is to execute else_branch when `value  == false`.
```ruby
def lock_retrier=(value)
if value.nil?
@lock_retrier = NullLockRetrier.new
else
@lock_retrier = value
end
end
def lock_retrier=(value)
if value
@lock_retrier = NullLockRetrier.new
else
@lock_retrier = value
end
end
```
=> [Fix #10325] Enhance `Style/RedundantCondition` for the case that variable assignments in each branch

changelog/fix_a_false_for_style_fetch_env_var.md, lib/rubocop/cop/style/fetch_env_var.rb, spec/rubocop/cop/style/fetch_env_var_spec.rb
Fixes #10569.
This PR fixes a false positive for `Style/FetchEnvVar` when using the same value of `ENV` as `if` condition in the body.
The `ENV` var as a `if` condition is currently allowed.
So the `ENV` var already used in the condition will be accepted as well.
And the following (maybe) corner case is accepted in this PR.
```ruby
if ENV['foo']
ENV.delete('foo')
puts 'some code'
puts ENV['foo']
puts 'other code'
end
```
https://github.com/rubocop/rubocop/issues/10569#issuecomment-1106213970
=> [Fix #10569] Fix a false positive for `Style/FetchEnvVar`

changelog/fix_autocorrect_for_style_redundant_condition_with_hash.md, lib/rubocop/cop/style/redundant_condition.rb, spec/rubocop/cop/style/redundant_condition_spec.rb
...if argument for method in else branch is hash without braces.
Fixes #10605.
=> [Fix #10605] Fix autocorrect for `Style/RedundantCondition`

changelog/fix_an_error_inclusive_language.md, lib/rubocop/cop/naming/inclusive_language.rb, spec/rubocop/cop/naming/inclusive_language_spec.rb
This fixes an issue when `CheckStrings: true` and string with invalid byte sequence in UTF-8 
would cause an error in the `Naming/InclusiveLanguage` cop.
In fact, when we ran RuboCop on this repository's own code as follows, an error occurred.
```yml
Naming/InclusiveLanguage:
+  CheckStrings: true
FlaggedTerms:
behaviour:
Suggestions:
- behavior
offence:
Suggestions:
- offense
Exclude:
- lib/rubocop/cop/naming/inclusive_language.rb
```
```
bundle exec rubocop --only Naming/InclusiveLanguage
```
```
6 errors occurred:
An error occurred while Naming/InclusiveLanguage cop was inspecting /Users/ydah/rubocop/spec/rubocop/cop/layout/end_of_line_spec.rb.
An error occurred while Naming/InclusiveLanguage cop was inspecting /Users/ydah/rubocop/spec/rubocop/cop/lint/percent_string_array_spec.rb.
An …
```
=> Fix an error for `Naming/InclusiveLanguage` string with invalid byte sequence in UTF-8

changelog/fix_autocorrect_for_style_redundant_condition_with_parenthesized_method_call.md, lib/rubocop/cop/style/redundant_condition.rb, spec/rubocop/cop/style/redundant_condition_spec.rb
Fixes #10607.
Sorry that was my bad, the cop now supports parenthesized method calls.
```ruby
if foo
some_method(foo)
else
some_method('bar')
end
foo ? some_method(foo) : some_method('bar')
```
And fixed highlight range for ternary expression when expression contains method call.
```ruby
test.rb:4:5: C: [Correctable] Style/RedundantCondition: Use double pipes || instead.
foo ? some_method(foo) : some_method('bar')
^^^^^^^^^^^^^^^^^^^^
test.rb:4:1: C: [Correctable] Style/RedundantCondition: Use double pipes || instead.
foo ? some_method(foo) : some_method('bar')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
=> [Fix #10607] Fix autocorrect for `Style/RedundantCondition` with parenthesized method call

config/default.yml, spec/project_spec.rb
In the current `config/default.yml`, some cop descriptions start with 'This cop' and others with a verb (e.g. 'Checks ...'). 
So unify this fluctuation with the majority, which starts with a verb.
=> Unify to remove 'This cop' from cop description in default.yml

changelog/fix_make_lint_non_deterministic_require_order_aware_of_require_relative.md, lib/rubocop/cop/lint/non_deterministic_require_order.rb, spec/rubocop/cop/lint/non_deterministic_require_order_spec.rb
Fixes #10614.
This PR makes `Lint/NonDeterministicRequireOrder` aware of `require_relative`.
=> [Fix #10614] Make `Lint/NonDeterministicRequireOrder` aware of `require_relative`

changelog/fix_restore_target_ruby_version_ruby_25.md, lib/rubocop/cop/lint/erb_new_arguments.rb, lib/rubocop/cop/style/map_to_hash.rb, lib/rubocop/cop/style/slicing_with_range.rb, lib/rubocop/rspec/shared_contexts.rb, lib/rubocop/target_ruby.rb, spec/rubocop/cli_spec.rb, spec/rubocop/cop/lint/ambiguous_range_spec.rb, spec/rubocop/cop/lint/deprecated_constants_spec.rb, spec/rubocop/cop/lint/duplicate_hash_key_spec.rb, spec/rubocop/cop/lint/erb_new_arguments_spec.rb, spec/rubocop/cop/style/hash_transform_keys_spec.rb, spec/rubocop/cop/style/hash_transform_values_spec.rb, spec/rubocop/cop/style/map_to_hash_spec.rb, spec/rubocop/cop/style/sample_spec.rb, spec/rubocop/cop/style/slicing_with_range_spec.rb
Fixes #10625 and reverts part of #10577.
Only the Ruby version (2.5) to runtime should have been dropped, not code analysis.
This PR the specification to `TargetRubyVersion: 2.5` So, this keeps it compatible with `TargetRubyVersion` up to 1.28.2.
=> [Fix #10625] Restore the specification to `TargetRubyVersion: 2.5`

changelog/fix_a_false_positive_for_style_raise_args.md, lib/rubocop/cop/style/raise_args.rb, spec/rubocop/cop/style/raise_args_spec.rb
Fixes #10622.
This PR fixes a false positive for `Style/RaiseArgs` when error type class constructor with keyword arguments and message argument.
The signature of `raise` is below.
```ruby
raise
raise(string, cause: $!)
raise(exception [, string [, array]], cause: $!)
```
https://ruby-doc.org/core-3.1.0/Kernel.html#method-i-raise
So #10622 would be a false positive because `raise MyError.new(data: 'mydata'), 'message'` and `raise MyError.new('message', data: 'mydata')` are incompatible.
=> [Fix #10622] Fix a false positive for `Style/RaiseArgs`

changelog/fix_default_target_ruby_version.md, lib/rubocop/target_ruby.rb, spec/rubocop/cli_spec.rb
This PR fixes default Ruby version from 2.5 to 2.6.
In #10626 (RuboCop 1.29.1) , the default target Ruby version is 2.5. This is an unexpected regression behavior and the default target Ruby version is expected to be 2.6.
=> Fix default target Ruby version from 2.5 to 2.6

changelog/change_markdown_formatter_to_skip_files_with_no_offenses.md, lib/rubocop/formatter/markdown_formatter.rb, spec/fixtures/markdown_formatter/expected.md, spec/fixtures/markdown_formatter/project, spec/fixtures/markdown_formatter/project/app/controllers/application_controller.rb, spec/fixtures/markdown_formatter/project/app/controllers/books_controller.rb, spec/fixtures/markdown_formatter/project/app/models/book.rb, spec/fixtures/markdown_formatter/project/app/models/shelf.rb
I've started using the new markdown formatter with GitHub's [job summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/), but the formatter is very verbose, listing all files with no offenses:
```markdown
...
```
This PR skips files with no offenses.
=> Markdown formatter: skip files with no offenses

changelog/fix_recover_ruby_24_code_analysis.md, lib/rubocop/cop/style/hash_transform_keys.rb, lib/rubocop/cop/style/redundant_begin.rb, lib/rubocop/rspec/shared_contexts.rb, lib/rubocop/target_ruby.rb, spec/rubocop/cli_spec.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/lint/suppressed_exception_spec.rb, spec/rubocop/cop/style/hash_transform_keys_spec.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
Fixes #10258 and reverts part of #9648.
Only the Ruby version (2.4) to runtime should have been dropped, not code analysis.
This PR makes Ruby 2.4 code analysis with `TargetRubyVersion: 2.4`.
So, this keeps it compatible with `TargetRubyVersion` up to RuboCop 1.12.1 as semver.
It aims to solve essentially the same problem as #10626.
=> [Fix #10258] Recover Ruby 2.4 code analysis using `TargetRubyVersion: 2.4`

changelog/new_add_commandline_option_ignore_unrecognized_cops.md, docs/modules/ROOT/pages/usage/basic_usage.adoc, lib/rubocop/cli.rb, lib/rubocop/config_loader.rb, lib/rubocop/config_validator.rb, lib/rubocop/options.rb, spec/rubocop/cli_spec.rb, spec/rubocop/config_spec.rb, spec/rubocop/options_spec.rb
…to ignore any unknown cops or departments in .rubocop.yml.
Fixes #10627.
This PR implements new command-line option `--ignore-unrecognized-cops`.
```rb
AllCops:
NewCops: enable
Foo:
Enabled: true
Bar/Baz:
Enabled: true
```
```sh
$ rubocop
Error: unrecognized cop or department Foo found in .rubocop.yml
unrecognized cop or department Bar/Baz found in .rubocop.yml
$ bundle exec rubocop --ignore-unrecognized-cops
The following cops or departments are not recognized and will be ignored:
unrecognized cop or department Foo found in .rubocop.yml
unrecognized cop or department Bar/Baz found in .rubocop.yml
Inspecting 3 files
...
#...
```
=> [Fix #10627] Add command-line option `--ignore-unrecognized-cops`

changelog/fix_fix_infinite_autocorrection_loop_in.md, lib/rubocop/cop/style/accessor_grouping.rb, spec/rubocop/cop/style/accessor_grouping_spec.rb
Previously when the same accessor was listed more than once, the autocorrection would continually add it to the grouped accessor. This fixes it to ensure that the accessor will only show up once.
Fixes #10633.
=> [Fix #10633] Fix infinite autocorrection loop in `Style/AccessorGrouping` when combining multiple of the same accessor

changelog/fix_fix_false_positive_in.md, lib/rubocop/cop/style/redundant_condition.rb, spec/rubocop/cop/style/redundant_condition_spec.rb
=> [Fix #10636] Fix false positive in `Style/RedundantCondition` when the branches call the same method on different receivers

changelog/new_add_new_gemspec_test_files_assignment_cop.md, config/default.yml, lib/rubocop.rb, lib/rubocop/cop/gemspec/test_files_assignment.rb, spec/rubocop/cop/gemspec/test_files_assignment_spec.rb
Fixes #10065.
This PR adds new `Gemspec/TestFilesAssignment` cop.
This cop checks that `test_files =` is not used in gemspec file.
if removing `test_files =`, then user could receive smaller packed gems.
```ruby
spec.name = 'your_cool_gem_name'
spec.test_files = Dir.glob('test/**/*')
end
spec.name = 'your_cool_gem_name'
spec.test_files += Dir.glob('test/**/*')
end
spec.name = 'your_cool_gem_name'
end
```
=> [Fix #10065] Add new `Gemspec/TestFilesAssignment` cop

changelog/fix_linebreakcorrector_so_that_it_wont_remove_semicolon_in_the_class_module_body.md, lib/rubocop/cop/correctors/line_break_corrector.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/style/trailing_body_on_class_spec.rb, spec/rubocop/cop/style/trailing_body_on_module_spec.rb
Fixes #10618
This PR fixes `LineBreakCorrector` (used by `Style/TrailingBodyOnClass` and `Style/TrailingBodyOnModule`).
It currently breaks the code by removing a semicolon in the class/module body when the class body is trailing class/module definition without a semicolon after the class/module name.
For example,
```ruby
class Foo def bar; end
end
class Foo bar
a; b
end
```
is wrongly corrected into
```ruby
class Foo 
def bar end # Unexpected correction
end
class Foo 
bar
a b # Unexpected correction
end
```
=> [Fix #10618] Fix `LineBreakCorrector` so that it won't remove a semicolon in the class/module body

changelog/new_add_sorbets_typed_sigil_as_a_magic_comment.md, lib/rubocop/magic_comment.rb, spec/rubocop/cop/layout/empty_line_after_magic_comment_spec.rb, spec/rubocop/magic_comment_spec.rb
Hello! This PR adds Sorbet's `typed` sigil as a magic comment. I'm aware of the `rubocop-sorbet` project, but I thought this might belong here here because of the existing rules around magic comments.
I'm aware I didn't check all of the boxes below! I will come back and finish this up if you too believe this belongs here.
=> Add Sorbet's `typed` sigil as a magic comment

lib/rubocop/cop/style/rescue_standard_error.rb
This PR corrects the spelling.
Use "explicit" instead of "exlicit"
~* [ ] Added tests.~
~* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.~
=> Use "explicit" instead of "exlicit"

changelog/fix_stylehashsyntax_not_adding_config_when_auto_gen_config.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cli/auto_gen_config_spec.rb
=> [Fix #10639] Fix `Style/HashSyntax` to exclude files that violate it with `EnforceHashShorthandSyntax` when running `auto-gen-config`

changelog/fix_recover_ruby_23_code_analysis.md, lib/rubocop/cop/lint/unified_integer.rb, lib/rubocop/cop/style/hash_transform_values.rb, lib/rubocop/cop/style/unpack_first.rb, lib/rubocop/rspec/shared_contexts.rb, lib/rubocop/target_ruby.rb, rubocop.gemspec, spec/rubocop/cli_spec.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/lint/unified_integer_spec.rb, spec/rubocop/cop/style/hash_transform_values_spec.rb, spec/rubocop/cop/style/unpack_first_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/10632#issuecomment-1125909580.
Reverts part of #7869 and #8056.
Only the Ruby version (2.3) to runtime should have been dropped, not code analysis.
This PR makes Ruby 2.3 code analysis with `TargetRubyVersion: 2.3`.
It aims to solve essentially the same problem as #10626 and #10632.
And this change requires RuboCop AST 1.18 or later:
https://github.com/rubocop/rubocop-ast/pull/233
=> Recover Ruby 2.3 code analysis using `TargetRubyVersion: 2.3`

docs/modules/ROOT/pages/extensions.adoc
@bquorning helped me fork the repo for `RuboCop::ThreadSafety`. I'm updating links to match :)
=> [doc] RuboCop::ThreadSafety moved into the RuboCop org

changelog/fix_fix_autocorrect_for_styleredundantbegin.md, lib/rubocop/cop/style/redundant_begin.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
Fixes #10631
This PR fixes autocorrect for `Style/RedundantBegin` to avoid the `swallowed_insertions_conflict` clobbering error against nested offensive begin blocks.
The autocorrect currently causes a clobbering error when correcting this code
```ruby
@foo ||= begin
@bar ||= begin
baz
end
end
```
```
$ exe/rubocop --only=Style/RedundantBegin -a -d test.rb
...
```
With this fix, the code is properly corrected without any errors.
```ruby
@foo ||= @bar ||= baz
```
=> [Fix #10631] Fix autocorrect for `Style/RedundantBegin`

changelog/fix_false_negative_for_style_symbol_proc.md, lib/rubocop/cop/style/symbol_proc.rb, spec/rubocop/cop/style/symbol_proc_spec.rb
This PR fixes a false negative for `Style/SymbolProc` when method has no arguments and `AllowMethodsWithArguments: true`.
The cause of the false negative was that they were counted using block arguments instead of method arguments.
=> Fix a false negative for `Style/SymbolProc`

changelog/fix_autogenerateconfig_command_ignores_config.md, lib/rubocop/cli/command/auto_genenerate_config.rb, spec/rubocop/cli/auto_gen_config_spec.rb
Fixes #10657.
This PR fixes a bug that caused config files specified by `--config` options to be unintentionally ignored in `AutoGenerateConfig` command.
=> [Fix #10657] Fix `AutoGenerateConfig` command ignores specified config file by option

changelog/fix_an_incorrect_autocorrect_for_style_sole_nested_conditional.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
Fixes #10646.
This PR fixes an incorrect autocorrect for `Style/SoleNestedConditional` when using `unless` and `&&` without parens in the outer condition and nested modifier condition.
=> [Fix #10646] Fix an incorrect autocorrect for `Style/SoleNestedConditional`

changelog/changelog/fix_recover_ruby_22_code_analysis.md, lib/rubocop/cop/lint/safe_navigation_chain.rb, lib/rubocop/cop/style/frozen_string_literal_comment.rb, lib/rubocop/cop/style/numeric_predicate.rb, lib/rubocop/cop/util.rb, lib/rubocop/rspec/shared_contexts.rb, lib/rubocop/target_ruby.rb, spec/rubocop/cli_spec.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/lint/safe_navigation_chain_spec.rb, spec/rubocop/cop/style/empty_literal_spec.rb, spec/rubocop/cop/style/for_spec.rb, spec/rubocop/cop/style/frozen_string_literal_comment_spec.rb, spec/rubocop/cop/style/lambda_spec.rb, spec/rubocop/cop/style/numeric_predicate_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/10632#issuecomment-1125909580.
Reverts part of #6766, #7026, and #7030.
Only the Ruby version (2.2) to runtime should have been dropped, not code analysis.
This PR makes Ruby 2.2 code analysis with `TargetRubyVersion: 2.2`.
It aims to solve essentially the same problem as #10626, #10632, and #10640.
Previously, there was the following default enforced style `when_needed` for `Style/FrozenStringLiteralComment` cop.
```ruby
#
#
```
This PR does not restore that option, but sets the `minimum_target_ruby_version 2.3` to make `always (default)` apply by default. It is a simple solution that does not handle frozen literal magic comment added in Ruby 2.3 when `TargetRubyVersion` is Ruby 2.2 or lower.
Before submitting the PR …
=> Recover Ruby 2.2 code analysis using `TargetRubyVersion: 2.2`

changelog/fix_autocorrect_for_stylefor_when_using_array_with_operator_method.md, lib/rubocop/cop/correctors/for_to_each_corrector.rb, spec/rubocop/cop/style/for_spec.rb
=> [Fix #10651] Fix autocorrect for `Style/For` when using array with operator methods as collection

lib/rubocop/cop/style/fetch_env_var.rb
This PR refactors `Style/FetchEnvVar` cop.
- Reduced the code for finding the correction target node.
- Renamed variables to improve readability.
=> Refactor `Style/FetchEnvVar` cop

changelog/new_add_new_gemspec_deprecated_attribute_assignments_cop.md, changelog/new_add_new_gemspec_test_files_assignment_cop.md, config/default.yml, lib/rubocop.rb, lib/rubocop/cop/gemspec/deprecated_attribute_assignment.rb, spec/rubocop/cop/gemspec/deprecated_attribute_assignment_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/10105#issuecomment-924588815.
This PR renames `Gemspec/TestFilesAssignment` to `Gemspec/DeprecatedAttributeAssignment`.
The already released `Gemspec/DateAssignment` can be integrated in the future. However that integration is pending as breaking changes cannot be made in RuboCop 1.x.
Anyway, I think #10634 can be able to integrate into the cop of this name.
There is no changelog as this is an unreleased cop naming change.
=> Rename `Gemspec/TestFilesAssignment` to `Gemspec/DeprecatedAttributeAssignment`

lib/rubocop/cop/style/guard_clause.rb
Fix a typo "do_someting" -> "do_something"
~* [ ] Added tests.~
~* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.~
=> Fix a typo "do_someting" -> "do_something"

changelog/fix_recover_ruby_20_code_analysis.md, lib/rubocop/cop/style/dir.rb, lib/rubocop/cop/style/symbol_array.rb, lib/rubocop/rspec/shared_contexts.rb, lib/rubocop/target_ruby.rb, spec/rubocop/cli_spec.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/style/optional_arguments_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/10632#issuecomment-1125909580.
Reverts part of https://github.com/rubocop/rubocop/pull/4787.
Only the Ruby version (2.0) to runtime should have been dropped, not code analysis.
This PR makes Ruby 2.0 code analysis with `TargetRubyVersion: 2.0`.
It aims to solve essentially the same problem as #10626, #10632, #10640, #10644, and #10662.
=> Recover Ruby 2.0 code analysis using `TargetRubyVersion: 2.0`

changelog/fix_path_for_inherit_from_is_incorrect.md, lib/rubocop/cli/command/auto_genenerate_config.rb, spec/rubocop/cli/auto_gen_config_spec.rb
… is incorrect if specified config file in a subdirectory as an option.
Fixes #10659.
Here is the example project using rubocop with custom config in a subdirectory.
```sh
.
├── example.rb
└── dir
└── .another_rubocop.yml
```
Current behavior for `rubocop --auto-gen-config --config dir/.another_rubocop.yml` is:
- Generates `.rubocop_todo.yml` in project root.
- Appends `inherit_from .rubocop_todo.yml` to `dir/.another_rubocop.yml`.
After running the command, modified configuration causes an error `Configuration file not found` because `.rubocop_todo.yml` is not exists in same directory of `.another_rubocop.yml`. So, after the fix, the generated location of .rubocop_todo.yml will be kept as it is, and the relative path will be used to the config for `inherit_from`.
Before …
=> [Fix #10659] Fix automatically appended path for `inherit_from` by `auto-gen-config`

changelog/fix_an_incorrect_autocorrect_for_layout_argument_alignment.md, lib/rubocop/cop/layout/argument_alignment.rb, lib/rubocop/cop/layout/hash_alignment.rb, spec/rubocop/cli/autocorrect_spec.rb
Fixes #10665.
This PR fixes an incorrect autocorrect for `EnforcedStyle: with_first_argument` of `Layout/ArgumentAlignment` and `EnforcedColonStyle: separator` of `Layout/HashAlignment`.
=> [Fix #10665] Fix an incorrect autocorrect for `Layout/ArgumentAlignment`

changelog/fix_ignore_unrecognized_cops_option.md, lib/rubocop/config_validator.rb, spec/rubocop/config_spec.rb
The internal condition was wrong, and the message `The following cops or departments are ...` was always displayed with just the option is specified.
Reported at: https://github.com/rubocop/rubocop/pull/10630#issuecomment-1140263726
```rb
$ bundle exec rubocop --ignore-unrecognized-cops
The following cops or departments are not recognized and will be ignored: # <--- 👀 
Inspecting 2 files
.W
...
```
=> Fix `--ignore-unrecognized-cops` option always showing empty warning even if there was no problem

changelog/fix_false_positive_for_fetch_env_var.md, lib/rubocop/cop/style/fetch_env_var.rb, spec/rubocop/cop/style/fetch_env_var_spec.rb
Follow up: https://github.com/rubocop/rubocop/pull/10653#issuecomment-1135884969
```ruby
if ENV['X'] = x
puts ENV['X']
end
if ENV['X'] = x
puts ENV.fetch('X', nil)
end
```
=> Fix a false positive for `Style/FetchEnvVar` in the body with assignment method

README.md, docs/modules/ROOT/pages/compatibility.adoc
Follow up https://github.com/rubocop/rubocop/pull/10632#issuecomment-1125893493.
RuboCop targets Ruby 2.0+ code analysis since RuboCop 1.30. This PR tweaks docs about target Ruby version.
NOTE: Ruby 1.9 code analysis is not restored because its some incompatibilities with Ruby 2.0+ cops. It may not be worth the maintenance cost.
=> Tweak docs about target Ruby version

changelog/fix_a_false_positive_for_style_safe_navigation.md, lib/rubocop/cop/style/safe_navigation.rb, spec/rubocop/cop/style/safe_navigation_spec.rb
Fixes #10679.
Fix a false positive for `Style/SafeNavigation` when `TargetRubyVersion: 2.2` or lower.
=> [Fix #10679] Fix a false positive for `Style/SafeNavigation`

.pre-commit-hooks.yaml
this silences a warning when used with `pre-commit`
=> fix "--auto-correct is deprecated; use --autocorrect"

changelog/fix_a_false_positive_accessor_method_name.md, lib/rubocop/cop/naming/accessor_method_name.rb, spec/rubocop/cop/naming/accessor_method_name_spec.rb
This PR is fixed based on a similar problem: https://github.com/rubocop/rubocop/issues/10574
`Naming/AccessorMethodName` should only inform offense
if the type of the first argument is `arg`.
```ruby
def set_something(arg)
end
def set_something(arg = :default)
end
def set_something(*args)
end
def set_something(k: v)
end
def set_something(k:)
end
def set_something(**options)
end
def set_something(&block)
end
def set_something(...)
end
```
=> Fix a false positive for `Naming/AccessorMethodName` with type of the first argument is other than `arg`

changelog/fix_a_false_positive_for_style_string_concatenation.md, lib/rubocop/cop/style/string_concatenation.rb, spec/rubocop/cop/style/string_concatenation_spec.rb
Fixes #10685.
This PR fixes a false positive for `Style/StringConcatenation` when `Mode: conservative` and first operand is not string literal. It also resolves the following feedback:
https://github.com/rubocop/rubocop/pull/9153#discussion_r616956347
`Mode: conservative` should be allowed considering the possibility that receiver is a `Pathname` object.
=> [Fix #10685] Fix a false positive for `Style/StringConcatenation`

docs/modules/ROOT/pages/cops_layout.adoc, docs/modules/ROOT/pages/cops_naming.adoc, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/layout/empty_lines_around_block_body.rb, lib/rubocop/cop/layout/empty_lines_around_class_body.rb, lib/rubocop/cop/layout/empty_lines_around_module_body.rb, lib/rubocop/cop/layout/first_argument_indentation.rb, lib/rubocop/cop/layout/space_inside_array_literal_brackets.rb, lib/rubocop/cop/layout/trailing_empty_lines.rb, lib/rubocop/cop/naming/variable_number.rb, lib/rubocop/cop/style/and_or.rb, lib/rubocop/cop/style/empty_else.rb, lib/rubocop/cop/style/missing_else.rb, lib/rubocop/cop/style/rescue_standard_error.rb, lib/rubocop/cops_documentation_generator.rb
Previously, not all default enforced styles were at the top.
Known limitations:
1. only checks for `EnforcedStyle:`, not e.g.  `EnforcedStyleForMultiline:` (which is the **only**) enforced style type in `Style/TrailingCommaInArrayLiteral` cop.
2. only checks for `EnforcedStyle:` when other enforced style types are present, e.g. `EnforcedStyleForEmptyBrackets:` for `Layout/SpaceInsideArrayLiteralBrackets` (also has regular `EnforcedStyle:`).
3. No autocorrection 😄 
Follow-up to https://github.com/rubocop/rubocop-rspec/pull/1289, basing on [this discussion](https://github.com/rubocop/rubocop-rspec/pull/1279#discussion_r884678237).
* [-] Commit message starts with `[Fix #issue-number]` (if the related issue …
=> Add a check for EnforcedStyle: (default) examples

CHANGELOG.md
Rubocop v0.74.0 [changelog](https://github.com/rubocop/rubocop/blob/master/CHANGELOG.md#0740-2019-07-31) says:
```
Deprecate the SafeMode option. Users will need to upgrade rubocop-performance to 1.15.0+ before the SafeMode module is removed. ([@rrosenblum](https://github.com/rrosenblum))
```
But rubocop-performance version 1.15.0 does not exist. This was introduced in this [PR](https://github.com/rubocop/rubocop/pull/7249/files) 
It should say 1.5.0 instead of 1.15.0. 
According to [rubocop-performance releases](https://github.com/rubocop/rubocop-performance/releases/tag/v1.5.0), SafeMode was removed in version 1.5.0
=> Fix: rubocop-performance SafeMode deprecation version 

tasks/new_cop.rake, tasks/prof.rake
If you try to add a new cop and use the wrong command in the rake task, you will get the following warning.
```console
❯ bundle exec rake new_cop                                     
usage: bundle exec rake new_cop[Department/Name]
```
If you try to execute it as is, you will face the following error.
```console
❯ bundle exec rake new_cop[Department/Name]
zsh: no matches found: new_cop[Department/Name]
```
https://github.com/rubocop/rubocop/pull/10695#issuecomment-1147019057
As noted in the documentation, it should be in a format that can be executed by zsh by enclosing it in single quotation marks.
* [-] …
=> Change command for the rake task with arguments to a style that can also be used in zsh

changelog/change_add_ignore_case_for_empty_lines_around_attribute_accessor.md, lib/rubocop/cop/layout/empty_lines_around_attribute_accessor.rb, spec/rubocop/cop/layout/empty_lines_around_attribute_accessor_spec.rb
Resolve: https://github.com/rubocop/rubocop/issues/10693
=> [Fix #10693] Add ignore case for `Style/EmptyLinesAroundAttributeAccessor` when there is a comment line on the next line.

changelog/fix_displaying_extension_versions.md, lib/rubocop/version.rb, spec/rubocop/version_spec.rb
The rubocop extension namespaces not always match the gem name. We already had the mapping done for rubocop-rspec. This adds the mapping for rubocop-md, rubocop-thread_safety and rubocop-graphql.
Note that I also changed is so it would try to check the `RuboCop::<extension>::Version::STRING` constant if the load itself fails. This was needed in order to write the test, but since it also handles the constant not being defined gracefully, I decided there is no harm in the check still being performed.
rubocop-md was the worst offender, as the folder structure doesn't follow the gem name (the files are under `markdown` folder and not `md`). So it required one additional mapping - quite ugly at this point, but since it's the only exception, I hope it's acceptable 🙏 
Any suggestions for further …
=> Fix displaying version information for known extensions

changelog/change_rename_custom_rake_task_to_rubocop_autocorrect.md, docs/modules/ROOT/pages/integration_with_other_tools.adoc, lib/rubocop/rake_task.rb, spec/rubocop/rake_task_spec.rb
Follow up #10547.
This PR renames custom rake task from `rubocop:auto_correct` to `rubocop:autocorrect`.
```console
rake rubocop                              # Run RuboCop
rake rubocop:auto_correct                 # Autocorrect RuboCop offenses
```
```console
rake rubocop                             # Run RuboCop
rake rubocop:autocorrect                 # Autocorrect RuboCop offenses
```
For compatibility, `rubocop:auto_correct` task is left, but the task is deprecated and does not display in `rake -T`.
When executed, the following warning will be displayed:
```console
% bundle exec rake rubocop:auto_correct
rubocop:auto_correct task is deprecated; use rubocop:autocorrect task instead.
Running RuboCop...
``` …
=> Rename custom rake task to `rubocop:autocorrect`

changelog/fix_an_error_for_style_multiline_ternary_operator.md, lib/rubocop/cop/style/multiline_ternary_operator.rb, spec/rubocop/cop/style/multiline_ternary_operator_spec.rb
Fixes #10711.
This PR fixes an error for `Style/MultilineTernaryOperator` when the false branch is on a separate line.
=> [Fix #10711] Fix an error for `Style/MultilineTernaryOperator`

.rubocop.yml, lib/rubocop.rb, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, lib/rubocop/formatter/simple_text_formatter.rb, lib/rubocop/options.rb, lib/rubocop/rake_task.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/options_spec.rb, spec/rubocop/rake_task_spec.rb
In this PR, we have made the following word's suggestions
- auto-correct -> autocorrect
- auto_correct -> autocorrect
Also considered "AutoCorrect" but are hesitant to change the naming of the "RuboCop::Cop::AutoCorrector" module because of its large impact.
In addition, the "auto-correct" command, which is scheduled to be deprecated, is suppressed by including a comment to disable RuboCop in the section containing it.
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces …
=> Add a setting for "autocorrect" in `Naming/InclusiveLanguage`

changelog/fix_a_false_positive_for_lint_parentheses_as_grouped_expression.md, lib/rubocop/cop/lint/parentheses_as_grouped_expression.rb, spec/rubocop/cop/lint/parentheses_as_grouped_expression_spec.rb
Fixes #10719 and follow up #8039.
This PR fixes a false positive for `Lint/ParenthesesAsGroupedExpression` when using safe navigation operator.
=> [Fix #10719] Fix a false positive for `Lint/ParenthesesAsGroupedExpression`

docs/modules/ROOT/pages/usage/server.adoc, lib/rubocop/server/cache.rb, lib/rubocop/server/client_command.rb, lib/rubocop/server/client_command/base.rb, lib/rubocop/server/client_command/exec.rb, lib/rubocop/server/client_command/start.rb, spec/rubocop/server/rubocop_server_spec.rb
This PR supports auto-restart RuboCop server when updating RuboCop.
First, cache RuboCop version when the RuboCop server starts.
And, auto-restarts when the runtime (client) RuboCop version does not match the cached RuboCop version.
=> Support auto-restart RuboCop server

changelog/change_change_output_timing_of.md, lib/rubocop/formatter/git_hub_actions_formatter.rb, spec/rubocop/formatter/git_hub_actions_formatter_spec.rb
This pull request changes the output timing of GitHubActionsFormatter from `#file_finished` to `#finished`.
When workflow commands are used, file path and line number are hidden in the GitHub Action log. So, if we want to use github formatter and still be able to identify the problematic file info from the log, we need to use it with another formatter like `--format progress --format github`.
However, the output timing of the current github formatter is a bit inconveninent when used with the progress formatter like this:
```
$ bundle exec rubocop --format progress --format github
Inspecting 2 files
C
Error: Bundler/OrderedGems: Gems should be sorted in an alphabetical order within their section of the Gemfile. Gem `paper_trail` should appear before `foo`.
Error: Layout/TrailingEmptyLines: …
```
=> Change output timing of GitHubActionsFormatter

changelog/fix_space_inside_block_braces_with_numbered_arguments.md, lib/rubocop/cop/layout/space_inside_block_braces.rb, spec/rubocop/cop/layout/space_inside_block_braces_spec.rb
The `Layout/SpaceInsideBlockBraces` was not being applied for blocks with
numbered arguments as they have AST node type of `numblock` and the cop
only ran for `block` nodes.
At Dext we caught spacing errors during code review and wandered why the
cop didn't run at all. The piece of code was in the lines of:
```ruby
Tax.where(condition).partition {_1.by_something}
```
Not running `Layout/SpaceInsideBlockBraces` for `numblock` nodes was the
cause.
=> Fix Layout/SpaceInsideBlockBraces for blocks with numbered arguments

lib/rubocop.rb, lib/rubocop/config_loader.rb, lib/rubocop/formatter.rb, lib/rubocop/formatter/formatter_set.rb, lib/rubocop/formatter/html_formatter.rb, lib/rubocop/formatter/offense_count_formatter.rb, lib/rubocop/formatter/simple_text_formatter.rb
Normally, only one formatter is used at the `rubocop` run time,  so not all  formatters need to be required.
No dramatic performance improvements have been made, but waste can be reduced.
`rubocop/formatter/formatter_set` is not a selective module, it keeps using `require_relative`.
Also `rubocop/formatter/text_util` is used as a common util, it uses `require_relative`.
=> Reduce unused `require_relative` for formatters

lib/rubocop/cop/gemspec/require_mfa.rb
- Fix the indentation of the example code docs for Gemspec/RequireMFA.
=> [Docs] Fix Gemspec/RequireMFA example code spacing

changelog/fix_fix_crash_in_styleconditionalassignment.md, lib/rubocop/cop/style/conditional_assignment.rb, spec/rubocop/cop/style/conditional_assignment_assign_in_condition_spec.rb
Because this cop adds node handlers for all the assignment types, but an `op-asgn` node contains an `lvasgn`, the `assignment_node` method was crashing with:
```
undefined method `begin_type?' for :bar:Symbol
assignment, = *assignment if assignment.begin_type? && assignment.children.one?
^^^^^^^^^^^^
```
This change ignores assignments inside `op-asgn`, `or_asgn` and `and_asgn` nodes, as they will have already been covered by the relevant `on_*` method.
Fixes #10737.
=> [Fix #10737] Fix crash in `Style/ConditionalAssignment` with `EnforcedStyle: assign_inside_condition` when op-assigning a variable inside a `resbody`

changelog/fix_fix_style_format_string_token_false_positive.md, lib/rubocop/cop/style/format_string_token.rb, spec/rubocop/cop/style/format_string_token_spec.rb
Fixes #7900.
Types of format strings:
- `annotated`: `'%<name>s'` (where `s` is the format type)
- `template`: `'%{name}'`
- `unannotated`: `'%s'`
The format string `'%{name}'` is only equivalent to `'%<name>s'`, so when enforcing the `template` style, no offenses should be reported if the format type is not `s` (for example, `'%<name>f'`).
The autocorrection from `template` style `%[flags][width][.precision]{name}` to `annotated` style is `%<name>[flags][width][.precision]s`, and vice versa.
Because `unannotated` has no names, it can't be autocorrected to `annotated` or `template`.
Autocorrecting from either `annotated` or `template` to `unannotated` is possible, but I haven't attempted adding this yet. The method arguments must be updated too, so `def on_send` would need to be added …
=> [Fix #7900] Fix `Style/FormatStringToken` false positive with formatted input and `template` style enforced, and add autocorrection

changelog/change_rename_custom_rake_task_to_rubocop_autocorrect.md, lib/rubocop/rake_task.rb, spec/rubocop/rake_task_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/10709#discussion_r905164287.
This PR splits deprecated `rubocop:auto_correct` custom rake task into `rubocop:autocorrect` and `rubocop:autocorrect_all`.
=> Split a custom rake task into `rubocop:autocorrect` and `rubocop:autocorrect_all`

changelog/fix_update_styleemptymethod_to_not_correct.md, lib/rubocop/cop/style/empty_method.rb, spec/rubocop/cop/style/empty_method_spec.rb
When an empty method definition is longer than the `Max` allowed by `Layout/LineLength`, autocorrection ends up in an infinite loop: `Layout/LineLength` splits the method onto two lines, and then `Style/EmptyMethod` puts it back onto one line.
This changes `Style/EmptyMethod` to not perform autocorrection with `EnforcedStyle: compact` if the resulting change will exceed the allowed line length. An offense will still be registered but it will be up to the user to determine how to resolve it, which will prevent the infinite loop.
NOTE: this makes an assumption that `Layout/LineLength` takes priority over `Style/EmptyMethod` for the purposes of correction.
Fixes #10700.
[1]: …
=> [Fix #10700] Update `Style/EmptyMethod` to not correct if the correction would exceed the configuration for `Layout/LineLength`

changelog/change_make_styleguardclause_a_bit_more_lenient.md, config/default.yml, lib/rubocop/cop/style/guard_clause.rb, spec/rubocop/cop/style/guard_clause_spec.rb
We currently have an exception in `Style/GuardClause` when the suggested replacement would be too long.
```ruby
def test
if something && something_that_makes_the_guard_clause_too_long_to_fit_on_one_line
work
end
end
```
RuboCop suggests replacing this with:
```ruby
def test
unless something && something_that_makes_the_guard_clause_too_long_to_fit_on_one_line
return
end
work
end
```
However, this makes the code more verbose (adds a line that doesn't really add any benefit) and harder to understand (since this only happens when the line is too long, it's a safe assumption that the condition is long, and flipping it with `unless` adds cognitive overhead).
This exception is not covered in the [style guide](https://rubystyle.guide/#no-nested-conditionals) either, so it should be …
=> Make `Style/GuardClause` a bit more lenient when the replacement would make the code more verbose

lib/rubocop/cop/style/empty_method.rb
Adds a comment to the documentation as per @bbatsov's comment https://github.com/rubocop/rubocop/pull/10742#issuecomment-1165262149
=> Add note to `Style/EmptyMethod` documentation about autocorrection re: `Layout/LineLength`

changelog/fix_block_delimiters_with_numbered_arguments.md, lib/rubocop/cop/style/block_delimiters.rb, spec/rubocop/cop/style/block_delimiters_spec.rb
With `EnforcedStyle` of `line_count_based`, the default, the following code **will** issue an offense, and will be auto-corrected:
```ruby
[1, 2, 3].map { |n| # [1, 2, 3].map do |n|
n + 1             #   n + 1
}                   # end
```
While the code below won't be converted to a multiline `do ... end` block:
```ruby
[1, 2, 3].map {
_1 + 1
}
```
This is yet another case of missing `on_numblock` implementation. I see a dozen of those in the codebase and I think whenever we handle `block` AST nodes we should also handle `numblock` nodes. I can go over the codebase and fix those problems on a per-cop basis, or I can try to fix it generally.
Currently, my best idea is to write an `InternalAffairs` cop that warns when we define `on_block` handlers, but we miss a `on_block` implementation. …
=> Fix Style/BlockDelimiters for blocks with numbered arguments

changelog/fix_recover_slow_running_rubocop.md, lib/rubocop/formatter.rb, lib/rubocop/formatter/simple_text_formatter.rb
Recovers #10735 regression.
This PR recovers 7x slower running `rubocop`.
Originally it was about 12 seconds:
```console
% git chceckout v1.30.1
% bundle exec rubocop --display-time
Inspecting 1366 files
(snip)
1366 files inspected, no offenses detected
Finished in 12.27936500031501 seconds
```
7x slower in my local environment:
```console
% bundle exec rubocop --display-time
Inspecting 1393 files
(snip)
1393 files inspected, no offenses detected
Finished in 88.82363200001419 seconds
```
It recovers to the same speed as v1.30.1:
```console
% bundle exec rubocop --display-time
Inspecting 1393 files
(snip)
1393 files inspected, no offenses detected
Finished in 12.322518999688327 seconds
```
The cause has not been clarified yet, but it seems that it was caused by changing `require_relative` …
=> Recover 7x slow running `rubocop`

changelog/fix_a_false_positive_for_lint_literal_as_condition.md, lib/rubocop/cop/lint/literal_as_condition.rb, spec/rubocop/cop/lint/literal_as_condition_spec.rb
Fixes #10755.
This PR fixes a false positive for `Lint/LiteralAsCondition` when using a literal in `case-in` condition where the match variable is used in `in` are accepted as a pattern matching.
=> [Fix #10755] Fix a false positive for `Lint/LiteralAsCondition`

changelog/fix_an_incorrect_autocorrect_for_style_hash_except.md, lib/rubocop/cop/style/hash_except.rb, spec/rubocop/cop/style/hash_except_spec.rb
Fixes #10754.
This PR fixes an incorrect autocorrect for `Style/HashExcept` when using a non-literal collection receiver for `include?`.
=> [Fix #10754] Fix an incorrect autocorrect for `Style/HashExcept`

changelog/fix_a_false_positive_for_non_atomic_file_operation.md, lib/rubocop/cop/lint/non_atomic_file_operation.rb, spec/rubocop/cop/lint/non_atomic_file_operation_spec.rb
Fixes #10760.
This PR fixes a false positive for `Lint/NonAtomicFileOperation` when using `FileTest.exist?` with `if` condition that has `else` branch.
=> [Fix #10760] Fix a false positive for `Lint/NonAtomicFileOperation`

spec/spec_helper.rb
This PR fixes the following build errors on CircleCI. These tests were expected to be skipped by `broken_on: :jruby`.
```console
rspec ./spec/rubocop/cli_spec.rb:1632 # RuboCop::CLI configuration from
file fails when a configuration file has invalid YAML syntax
rspec ./spec/rubocop/cop/variable_force_spec.rb:36 #
RuboCop::Cop::VariableForce#process_node when processing a regex with
regopt does not raise an error
```
https://app.circleci.com/pipelines/github/rubocop/rubocop/6657/workflows/834f8c9c-af93-429c-b434-10b8fa481cdb/jobs/227978
The following is the result of checking by ssh to `jruby-9.3-ascii_spec` job of CircleCI.
```ruby
> ENV['CIRCLE_STAGE']
=> nil
> ENV['CIRCLE_JOB']
=> "jruby-9.3-ascii_spec"
```
`CIRCLE_STAGE` is not expected to return `nil`.
As far as I can tell, the …
=> Fix build errors on CircleCI

changelog/fix_autocorrect_for_first_hash_element_indentation.md, lib/rubocop/cop/mixin/multiline_element_indentation.rb, spec/rubocop/cop/layout/first_array_element_indentation_spec.rb, spec/rubocop/cop/layout/first_hash_element_indentation_spec.rb
Fixes #10751
`Layout/FirstHashElementIndentation` should allow a hash where the content of the first pair is indented relative to the base column specified with configured cop style, and the second pair begins on the same line with the right brace of the first pair; because those two keys won't be aligned with each other by `Layout/HashAlignment`, not like the case of #10689.
With no parenthesis
```ruby
post :create, params: {
foo: { bar: 'Baz' }
}, as: :json
```
With the parenthesis and `special_inside_parentheses` style
```ruby
post(:create, params: {
foo: { bar: 'Baz' }
}, as: :json)
```
With the parenthesis and `consistent` style
```ruby
post(:create, params: {
foo: { bar: 'Baz' }
}, as: :json)
```
[1]: …
=> [Fix #10751] Fix autocorrect for Layout/FirstHashElementIndentation

changelog/fix_a_false_positive_for_layout_line_continuation_spacing.md, lib/rubocop/cop/layout/line_continuation_spacing.rb, spec/rubocop/cop/layout/line_continuation_spacing_spec.rb
Fixes #10763.
This PR fixes a false positive for `Layout/LineContinuationSpacing` when using continuation keyword `\` after `__END__`.
=> [Fix #10763] Fix a false positive for `Layout/LineContinuationSpacing`

changelog/fix_an_error_when_using_old_json_gem.md, rubocop.gemspec
Fixes #10745.
This PR fixes the following incompatible API error when using JSON 2.2 or lower.
```console
% bunlde exec rspec  ./spec/rubocop/result_cache_spec.rb:45
Run options: include {:focus=>true,
:locations=>{"./spec/rubocop/result_cache_spec.rb"=>[45]}}
Randomized with seed 40926
FF
Failures:
1) RuboCop::ResultCache cached result that was saved with no command
line option when no option is given is valid and can be loaded
Failure/Error: deserialize_offenses(JSON.parse(text))
ArgumentError:
wrong number of arguments (given 2, expected 1)
Shared Example Group: "valid" called from
./spec/rubocop/result_cache_spec.rb:121
2) RuboCop::ResultCache cached result that was saved with no command
line option when --format …
```
=> [Fix #10745] Fix an error when using old JSON gem

changelog/fix_false_negatives_in_documentation_comment.md, lib/rubocop.rb, lib/rubocop/cop/mixin/def_node.rb, spec/rubocop/cop/style/documentation_method_spec.rb
[Similar to Rails/Delegate](https://github.com/rubocop/rubocop-rails/pull/736) this cop was just checking the previous lines for a `private` declaration. This fails when there is a private method in a nested class, or as the added spec illustrates - when private methods are declared before the public ones
=> Fix false negatives when public method is defined after a private one

changelog/fix_a_false_negative_for_style_redundant_parentheses.md, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
This PR fixes a false negative for `Style/RedundantParentheses` when parens around a receiver of a method call with an argument.
=> Fix a false negative for `Style/RedundantParentheses`

changelog/fix_a_false_positive_for_lint_non_atomic_file_operation.md, lib/rubocop/cop/lint/non_atomic_file_operation.rb, spec/rubocop/cop/lint/non_atomic_file_operation_spec.rb
Fixes #10786.
This PR fixes a false positive for `Lint/NonAtomicFileOperation` when using complex conditional.
=> [Fix #10786] Fix a false positive for `Lint/NonAtomicFileOperation`

changelog/fix_performance_issue_for_multiline_element_indentation.md, lib/rubocop/cop/layout/first_array_element_indentation.rb, lib/rubocop/cop/layout/first_hash_element_indentation.rb, lib/rubocop/cop/mixin/multiline_element_indentation.rb
Fixes #10764.
In rubocop v1.31.0, `MultilineElementIndentation` that is used by `Layout/FirstHashElementIndentation` and `Layout/FirstArrayElementIndentation` walks all nodes through in the code to find a hash pair node where its value part begins with the given left-brace; That computation is expensive, so I made a change so that the hash pair is passed by each class that uses `MultilineElementIndentation`.
I ran rubocop by the following command to make sure the performance problem was fixed by this PR. The input file is the file provided in https://github.com/rubocop/rubocop/issues/10764#issuecomment-1170011469
```bash
$ time exe/rubocop --cache false test.rb
```
Result:
- With v1.30.1
```
exe/rubocop --cache false test.rb  1.51s user 0.33s system 41% cpu 4.410 total
```
- With v1.31.0 …
=> [Fix #10764] Fix performance issue for Layout/FirstHashElementIndentation and Layout/FirstArrayElementIndentation

changelog/fix_inherit_mode_resolution.md, lib/rubocop/config_loader_resolver.rb, spec/rubocop/cli/options_spec.rb, spec/rubocop/config_loader_spec.rb
The problem was that we deleted the `inherit_mode` entry in the configuration hash while processing the resolution of inheritance from base configurations (`inherit_from`, etc.). When the merging of default configuration and user configuration was done at a later stage, the `inherit_mode` parameter was gone.
By not deleting `inherit_mode`, we fix the problem. I don't think it has any unwanted side effects, but `inherit_mode` does show up in the output from `--show-cops` now. This should be OK.
=> [Fix #10026] Fix inherit_mode resolution for parent and default config

changelog/fix_a_suggestions_for_safer_conversions_non_atomic_file_operation.md, lib/rubocop/cop/lint/non_atomic_file_operation.rb, spec/rubocop/cop/lint/non_atomic_file_operation_spec.rb
This PR is fix a suggestions for safer conversions for `Lint/NonAtomicFileOperation`.
Change the uniform conversion to `rm_rf` or `mkdir_p` to a safe change proposal as follows.
For non-recurrent file deletions
```ruby
if File.exist?(path)
File.remove(path)
end
FileUtils.rm_f(path)
```
For cases that do not require replacement
```ruby
if File.exist?(path)
FileUtils.makedirs(path)
end
FileUtils.makedirs(path)
```
In addition, when replacing a non-atomic file operation with a forced file creation or deletion, an offense message has been added as follows.
```ruby
if FileTest.exist?(path)
^^^^^^^^^^^^^^^^^^^^^^^^ Remove an unnecessary existence checks `FileTest.exist?`.
FileUtils.remove(path)
^^^^^^^^^^^^^^^^ Use atomic file operation method `FileUtils.rm_f`.
end
```
Before …
=> Fix a suggestions for safer conversions for `Lint/NonAtomicFileOperation`

changelog/change_preserve_multiline_on_stylesymbolarray.md, lib/rubocop/cop/mixin/percent_array.rb, lib/rubocop/cop/style/symbol_array.rb, lib/rubocop/cop/style/word_array.rb, spec/rubocop/cop/style/symbol_array_spec.rb, spec/rubocop/cop/style/word_array_spec.rb
To fix https://github.com/rubocop/rubocop/issues/10455.
Example:
```diff
-%w(
- foo
- bar
- baz
-)
+["foo", "bar", "baz"]
-%w(
- foo
- bar
- baz
-)
+[
+  "foo",
+  "bar",
+  "baz"
+]
```
To mimic the original whitespace semantics, I decided to extract three types of whitespace and reuse them in autocorrection.
```ruby
"%w[\n  foo\n  bar\n  baz\n]\n"
"[\n  'foo',\n  'bar',\n  'baz'\n]\n"
```
Note that this commit also changes the offense message like this (on multiline case):
```ruby
%w(
^^^ Use `[
'foo',
'bar'
]` for an array of words.
foo
bar
)
%w(
^^^ Use an array literal `[...]` for an array of words.
foo
bar
)
```
This means that the auto-corrected code no longer appears in the offense message (on multiline case). I think this is a reasonable change because this format is already used …
=> Preserve multiline semantics on `Style/SymbolArray` and `Style/WordArray`

changelog/change_add_leading_style_to_LineContinuationLeadingSpace.md, config/default.yml, lib/rubocop/cop/layout/line_continuation_leading_space.rb, spec/rubocop/cop/layout/line_continuation_leading_space_spec.rb
You can now choose between `EnforcedStyle: leading` and `EnforcedStyle: trailing`. `trailing` remains the default option.
Motivation:
- https://github.com/rubocop/rubocop/pull/10717#issuecomment-1168480753
- https://github.com/rubocop/rubocop/pull/10715#issuecomment-1160037386
=> Make Layout/LineContinuationLeadingSpace configurable

lib/rubocop/cop/internal_affairs/useless_restrict_on_send.rb, lib/rubocop/cop/style/top_level_method_definition.rb, spec/rubocop/cop/internal_affairs/useless_restrict_on_send_spec.rb, spec/rubocop/cop/style/top_level_method_definition_spec.rb
This PR updates #10743
Currently `1.31.2` looks all method callings on top-level are [falling](https://github.com/kachick/ruby-ulid/runs/7243055726?check_suite_focus=true) when enabled `Style/TopLevelMethodDefinition` even if `require_relative`.
```yaml
Style/TopLevelMethodDefinition:
Enabled: true
```
Fixes #10799
=> Fix wrong offense with `Style/TopLevelMethodDefinition` when just calling methods on top-level

changelog/fix_an_incorrect_autocorrect_for_style_semicolon.md, lib/rubocop/cop/style/semicolon.rb, spec/rubocop/cop/style/semicolon_spec.rb
Fixes #10791.
This PR fixes an incorrect autocorrect for `Style/Semicolon` when using endless range before semicolon.
=> [Fix #10791] Fix an incorrect autocorrect for `Style/Semicolon`

changelog/change_allow_parallel_autocorrect.md, docs/modules/ROOT/pages/usage/basic_usage.adoc, lib/rubocop/cli.rb, lib/rubocop/options.rb, lib/rubocop/runner.rb, spec/rubocop/cli_spec.rb, spec/rubocop/options_spec.rb
Allow the `-P`/`--parallel` flag together with the autocorrection flags `--[safe-]auto-correct`/`-a` `--auto-correct-all`/`-A` and  `--fix-layout`/`-x`. Also make this the default, so that `--no-parallel` has to be given for a single core run.
The algorithm for normal parallel inspection is followed, so that a cache warm-up phase is run first. This phase only does caching of inspection results. It doesn't update any files. Then it does a single core run that takes advantage of the cached results and does the corrections. The speed gain from this approach is probably smaller than writing files in parallel, but it's a pretty small change that still outputs correction results in the same way as before.
Also fix the documentation for `--parallel`, which did not mention `--no-parallel`.
=> [Fix #10613] Allow parallel inspection for autocorrect

lib/rubocop/cop/lint/ambiguous_block_association.rb, lib/rubocop/cop/lint/number_conversion.rb, lib/rubocop/cop/metrics/block_length.rb, lib/rubocop/cop/metrics/method_length.rb, lib/rubocop/cop/style/class_equality_comparison.rb, lib/rubocop/cop/style/format_string_token.rb, lib/rubocop/cop/style/method_call_without_args_parentheses.rb, lib/rubocop/cop/style/numeric_predicate.rb, lib/rubocop/cop/style/symbol_proc.rb
This PR is documentation was added according to the following policy for "IgnoredMethods" option
- Add code examples for cop that don't have code examples
- Add default values for cop that don't have default values
The code example also clearly shows the difference in behavior from the default when the default for "IgnoredMethods" is an empty array.
I thought We could flag "IgnoredMethods" as obsolete and merge it into "AllowedMethods".
Refs (case of "AllowedPatterns") : https://github.com/rubocop/rubocop/pull/10555
In the future, if it looks like it would be better to merge them, I would like to handle it other PR.
* [-] …
=> Enhanced documentation for "IgnoredMethods" option

changelog/change_support_csend_on_stylesymbolproc.md, lib/rubocop/cop/style/symbol_proc.rb, spec/rubocop/cop/style/symbol_proc_spec.rb
I think the following bad side code should also be treated as an offense:
```ruby
array&.map { |element| element.upcase }
array&.map(&:upcase)
```
* There doesn't seem to be an existing issue on this
=> Support `csend` on `Style/SymbolProc`

.github/workflows/rubocop.yml, .rspec, lib/rubocop/rspec/shared_contexts.rb, lib/rubocop/rspec/support.rb, spec/spec_helper.rb, spec/support/alignment_examples.rb, spec/support/empty_lines_around_body_shared_examples.rb, spec/support/multiline_literal_brace_layout_examples.rb, spec/support/multiline_literal_brace_layout_method_argument_examples.rb, spec/support/multiline_literal_brace_layout_trailing_comma_examples.rb
See RSpec 4 changes in https://github.com/rspec/rspec-metagem/issues/61
[Sibling PR for `rubocop-rspec`](https://github.com/rubocop/rubocop-rspec/pull/1322).
=> Add RSpec 4 prerelease CI job and make the test suite compatible with it

changelog/new_autocorrect_wraps_method_definitions.md, lib/rubocop/cop/layout/line_length.rb, lib/rubocop/cop/mixin/check_line_breakable.rb, spec/rubocop/cop/layout/line_length_spec.rb
Add autocorrect capabilities to `Layout/LineLength`, by wrapping method definitions on multiple lines.
```ruby
def foo(abc: "100000", def: "100000", ghi: "100000", jkl: "100000", mno: "100000")
end
def foo(abc: "100000", def: "100000", 
ghi: "100000", jkl: "100000", mno: "100000")
end
```
Combined with https://github.com/rubocop/rubocop/pull/10691 it allows for some nice autocorrect.
This was split from the larger WIP pull request here: https://github.com/rubocop/rubocop/pull/10681
=> Break long method definitions when auto-correcting

changelog/change_support_csend_on_stylesymbolproc.md, lib/rubocop/cop/style/symbol_proc.rb, spec/rubocop/cop/style/symbol_proc_spec.rb
Added some improvements about #10810. 
Thank you @koic 
* No issue about this change
* Enough tests are already written.
* No user-observable changes
=> Improve `Style/SymbolProc` about #10810 changes

changelog/fix_recursive_deletions_to_suppression_in_non_atomic_file_operation.md, lib/rubocop/cop/lint/non_atomic_file_operation.rb, spec/rubocop/cop/lint/non_atomic_file_operation_spec.rb
Fixes: rubocop#10813
This PR is suppress offense in case of
recursive deletion in `Lint/NonAtomicFileOperation`.
=> [Fix rubocop#10813] Fix recursive deletion to suppression in `Lint/NonAtomicFileOperation`

changelog/fix_an_error_when_using_changed_parameters_by_external_library.md, lib/rubocop/config_obsoletion.rb, spec/rubocop/config_obsoletion_spec.rb
This PR fixes the following error when using `changed_parameters` in obsoletion.yml by external library.
```console
NoMethodError: undefined method `merge' for
[{"cops"=>["Layout/SpaceAroundOperators", "Style/SpaceAroundOperators"],
"parameters"=>"MultiSpaceAllowedForOperators", "reason"=>"If your
intention was to allow extra spaces for alignment, please use `AllowFoy
first.merge(second)
^^^^^^
/Users/koic/src/github.com/rubocop/rubocop-rails/lib/rubocop/rails/inject.rb:11:in `new'
/Users/koic/src/github.com/rubocop/rubocop-rails/lib/rubocop/rails/inject.rb:11:in `defaults!'
/Users/koic/src/github.com/rubocop/rubocop-rails/lib/rubocop-rails.rb:13:in `<top (required)>'
```
[1]: …
=> Fix an error when using `changed_parameters` by external library

changelog/fix_an_incorrect_autocorrect_for_style_class_and_module_children.md, lib/rubocop/cop/style/class_and_module_children.rb, spec/rubocop/cop/style/class_and_module_children_spec.rb
Fixes #10825.
This PR fixes an incorrect autocorrect for `Style/ClassAndModuleChildren` when using nested one-liner class.
=> [Fix #10825] Fix an incorrect autocorrect for `Style/ClassAndModuleChildren`

changelog/fix_an_incorrect_autocorrect_for_style_redundant_condition.md, lib/rubocop/cop/style/redundant_condition.rb, spec/rubocop/cop/style/redundant_condition_spec.rb
Fixes #10833.
This PR fixes an incorrect autocorrect for `Style/RedundantCondition` when branches contains arithmetic operation.
=> [Fix #10833] Fix an incorrect autocorrect for `Style/RedundantCondition`

changelog/fix_an_incorrect_autocorrect_for_layout_block_end_new_line.md, lib/rubocop/cop/layout/block_end_newline.rb, spec/rubocop/cop/layout/block_end_newline_spec.rb
Fixes #10832.
This PR fixes an incorrect autocorrect for `Layout/BlockEndNewline` when multiline block `}` is not on its own line and using heredoc argument.
=> [Fix #10832] Fix an incorrect autocorrect for `Layout/BlockEndNewline`

changelog/fix_an_incorrect_autocorrect_for_layout_first_argument_indentation.md, lib/rubocop/cop/layout/first_argument_indentation.rb, spec/rubocop/cli/autocorrect_spec.rb
Fixes #10830.
This PR fixes an incorrect autocorrect for `Layout/FirstArgumentIndentation` when specifying `EnforcedStyle: with_fixed_indentation` of `Layout/ArgumentAlignment` and `EnforcedStyle: consistent` of `Layout/FirstArgumentIndentation` and enabling `Layout/FirstMethodArgumentLineBreak`.
=> [Fix #10830] Fix an incorrect autocorrect for `Layout/FirstArgumentIndentation`

changelog/fix_a_false_positive_for_style_hash_except.md, lib/rubocop/cop/style/hash_except.rb, spec/rubocop/cop/style/hash_except_spec.rb
Fixes #10843.
This PR fix a false positive for `Style/HashExcept` when using `reject` and calling `include?` method with symbol array and
second block value.
=> [Fix #10843] Fix a false positive for `Style/HashExcept`

changelog/fix_fix_styleclassequalitycomparison.md, lib/rubocop/cop/style/class_equality_comparison.rb, spec/rubocop/cop/style/class_equality_comparison_spec.rb
In the situation where `Module.nesting` is not empty, `bar.class.name == 'Bar'` and `bar.instance_of?(Bar)` yield different results.
This is a simple example of the problematic case:
(In reality, it is more complicated because constant search is done by tracing back to ancestor inheritance tree)
```ruby
module Foo
class << self
def bar1?(value)
value.instance_of?(Bar)
end
def bar2?(value)
value.class.name == 'Bar'
end
end
class Bar
end
end
class Bar
end
p Foo.bar1?(Bar.new) #=> false
p Foo.bar1?(Foo::Bar.new) #=> true
p Foo.bar2?(Bar.new) #=> true
p Foo.bar2?(Foo::Bar.new) #=> false
```
So I changed it to prepend `::` in those situations.
=> Fix `Style/ClassEqualityComparison` autocorrection within module

changelog/fix_make_server_mode_aware_of_command_line_option, lib/rubocop/server/cache.rb, lib/rubocop/server/cli.rb, spec/rubocop/server/cache_spec.rb, spec/rubocop/server/cli_spec.rb
Fix #10771.
This PR makes server mode aware of `--cache-root` command line option.
The logic for getting `--cache-root` from command line option is original to make the implementation lighter. Because the client of server mode should be lightweight.
#10842 needs a different solution than `--cache-root` option. I'm working on it separately from solving this issue.
=> [Fix #10771] Make server mode aware of `--cache-root` command line option

README.md
Previously the wording implied that between major versions the API won't change.
But it's pretty clear from the surrounding wording and general semvar concept
that the API _will_ change between major versions... it's only between minor/patch
versions that it won't change.
=> Clarify the API stability wording

changelog/fix_an_autocorrect_for_style_redundant_sort.md, lib/rubocop/cop/style/redundant_sort.rb, spec/rubocop/cop/style/redundant_sort_spec.rb
This PR is fix an autocorrect for `Style/RedundantSort` with logical operator
If you have a code like the following:
```ruby
[1, 2, 3]
.sort_by { |x| x.length }
.first || []
```
After autocorrection it will look like this:
```ruby
[1, 2, 3]
.sort_by { |x| x.length }
|| []
```
This is a syntax error.
```
Error: : eval:3: syntax error, unexpected '|', expecting end-of-input
|| []
^
(SyntaxError)
```
=> Fix an autocorrect for `Style/RedundantSort` with logical operator

changelog/fix_make_server_mode_aware_of_cache_root_directory.md, lib/rubocop/cache_config.rb, lib/rubocop/cli/command/auto_genenerate_config.rb, lib/rubocop/cli/command/init_dotfile.rb, lib/rubocop/config_finder.rb, lib/rubocop/config_loader.rb, lib/rubocop/result_cache.rb, lib/rubocop/server/cache.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/generator_spec.rb, spec/rubocop/server/cache_spec.rb
Fixes #10842 and follow up #10849.
This PR makes server mode aware of `CacheRootDirectory` config option value, `RUBOCOP_CACHE_ROOT`, and `XDG_CACHE_HOME` environment variables.
`RuboCop::ConfigLoader` and `RuboCop::ResultCache` classes to get these values has many dependencies. So, it is not suitable for use in server mode where speed is required.
This solution is to extract `ConfigPathFinder` class from `ConfigLoader` class and `CacheRoot` class from `ResultCache` class. This allows server mode to depend on lightweight `ConfigPathFinder` and `CacheRoot` classes.
=> [Fix #10842] Make server mode aware of `CacheRootDirectory` and two env vars

lib/rubocop/cop/lint/debugger.rb
I noticed that the documentation for `Lint/Debugger` had a typo in it for the example for how to disable a category of debug statements. I also updated it to give an example of how to add additional debugger methods that are not covered by default.
=> Update documentation for `Lint/Debugger`

changelog/change_dont_hash_shared_libraries_for_cache_key.md, lib/rubocop/result_cache.rb
Shared libraries often contain timestamps of when they were compiled and other non-stable data
hence would often produce different hashes on different machines. This happens often in our CI.
Related to https://github.com/rubocop/rubocop/pull/8633
cc @casperisfine
=> Don't hash shared libraries for cache key

changelog/fix_a_false_positive_for_style_symbol_proc_when_using_hash_reject.md, lib/rubocop/cop/style/symbol_proc.rb, spec/rubocop/cop/style/symbol_proc_spec.rb
Fixes #10864.
This PR fixes a false positive for `Style/SymbolProc` when using `Hash#reject`.
The same is true for `Haash#select`.
```ruby
{foo: :bar}.reject { p _1 } # `_1` is `:foo`
{foo: :bar}.select { p _1 } # `_1` is `:foo`
{foo: :bar}.detect { p _1 } # `_1` is `[:foo, :bar]`
{foo: :bar}.map { p _1 }    # `_1` is `[:foo, :bar]`
```
It fixes `on_block` method because the same issue occurs in normal blocks.
```ruby
{foo: :bar}.select {|item| item.nil? } #=> no erros.
{foo: :bar}.select(&:nil?)             #=> wrong number of arguments (given 1, expected 0) (ArgumentError)
```
`Style/SymbolProc` is already marked as unsafe, but it avoids avoidable issues.
=> [Fix #10864] Fix a false positive for `Style/SymbolProc`

changelog/change_add_autocorrection_to.md, config/default.yml, lib/rubocop/cop/lint/empty_conditional_body.rb, lib/rubocop/cop/mixin/comments_help.rb, spec/rubocop/cop/lint/empty_conditional_body_spec.rb
I noticed in https://github.com/rubocop/rubocop/issues/10858#issuecomment-1204175590 that `Lint/EmptyConditionalBody` does not have autocorrection, so I added it. It does the following:
* Removes the empty branch, including any comments if `AllowComments` is false.
* Handles subsequent branches, including changing `elsif` to `if` and `else` to `if`/`unless` appropriately, if the topmost branch is the one being removed.
* Can handle the `if` statement being preceded by another node.
I believe I've covered the edge cases here but if there's one you can think of let me know and I'll add it in. I also was unsure if we should mark this as `SafeAutoCorrect: false` but am happy to do so.
[1]: …
=> Add autocorrection to `Lint/EmptyConditionalBody`

lib/rubocop/cop/naming/predicate_name.rb
`Naming/PredicateName` did not have documentation in the guide about how to use the `NamePrefix` and `ForbiddenPrefixes` configuration options.
=> Rewrite documentation for `Naming/PredicateName` to better clarify its configuration options

changelog/fix_mark_autocorrection_for.md, config/default.yml, lib/rubocop/cop/lint/empty_conditional_body.rb
There are cases I wasn't considering where the autocorrection added in #10862 can change the behaviour of the code, so as an immediate step, autocorrection is being marked as unsafe.
=> Mark autocorrection for `Lint/EmptyConditionalBody` as unsafe

changelog/fix_fix_lintdebugger_to_be_able_to_handle.md, config/default.yml, lib/rubocop/cop/lint/debugger.rb, spec/rubocop/cop/lint/debugger_spec.rb
`Lint/Debugger` was not handling method chains properly, so this fixes it. It also removes the implicit `Kernel` prefix and makes it explicit in the configuration (it wasn't working as expected anyways).
Fixes #10859.
=> [Fix #10859] Fix `Lint/Debugger` to be able to handle method chains correctly

changelog/fix_fix_a_false_negative_for_double_negation.md, lib/rubocop/cop/style/double_negation.rb, spec/rubocop/cop/style/double_negation_spec.rb
=> [Fix #10846] Fix a false negative for `Style/DoubleNegation` when there is a hash or an array at return location of method.

changelog/fix_restore_rubocop_config_loader_project_root.md, lib/rubocop/config_loader.rb
Fixes #10871 and https://github.com/utkarsh2102/rubocop-packaging/issues/44.
This PR restores `RuboCop::ConfigLoader.project_root` as deprecated.
It fixes the following build error.
```console
% cd path/to/github.com/utkarsh2102/rubocop-packaging
% bundle update && bundle exec rake
(snip)
Failures:
1) RuboCop::Cop::Packaging::BundlerSetupInTests when `require
bundler/setup` is used in a Rakefile does not register an offense
Failure/Error: let(:project_root) {
RuboCop::ConfigLoader.project_root }
NoMethodError:
undefined method `project_root' for RuboCop::ConfigLoader:Class
`block (2 levels) in <top (required)>'
`block (3 levels) in <top (required)>'
`block (3 levels) in <top (required)>'
```
I considered a soft deprecation, but decided to issue a warning as it is probably of limited use. …
=> [Fix #10871] Restore `RuboCop::ConfigLoader.project_root` as deprecated

changelog/change_add_allowedpatterns_to.md, config/default.yml, lib/rubocop/cop/style/numeric_literals.rb, spec/rubocop/cli/auto_gen_config_spec.rb, spec/rubocop/cop/style/numeric_literals_spec.rb
Allows additional allowed patterns to be specified for `Style/NumericLiterals` so that special patterns will not register offenses. The patterns are forced to be anchored (so `\d{4}_\d{4}` will only match exactly that, and not substrings), and this does not affect autocorrection, which will continue to add underscores between groups of 3 digits.
Fixes #10857.
=> [Fix #10857] Add `AllowedPatterns` to `Style/NumericLiterals`.

changelog/fix_fix_an_obsolete_option_configuration.md, lib/rubocop/formatter/disabled_config_formatter.rb, spec/rubocop/cli/auto_gen_config_spec.rb
Create two files with the following code:
```ruby
def fooBar; end
```
Set the following in .rubocop.yml:
```yml
Style/MethodName:
IgnoredPatterns:
- pattern1
- pattern2
```
Run `rubocop --auto-gen-config`
Then duplicate configuration values are enumerated in `.rubocop_todo.yml` as follows:
```yml
Naming/MethodName:
Exclude:
- 'test1.rb'
- 'test2.rb'
```
=> Fix an obsolete option configuration values are duplicated when generating `.rubocop_todo.yml`

changelog/fix_fix_crash_with_layoutblockendnewline.md, lib/rubocop/cop/layout/block_end_newline.rb, spec/rubocop/cop/layout/block_end_newline_spec.rb
Autocorrection for `Layout/BlockEndNewline` tries to handle heredocs but now crashes in some cases where `heredoc?` is not defined.
Fixes #10877.
=> [Fix #10877] Fix crash with `Layout/BlockEndNewline` heredoc detection.

changelog/change_allow_styleternaryparentheses_to_take.md, lib/rubocop/cop/style/redundant_parentheses.rb, lib/rubocop/cop/style/ternary_parentheses.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb, spec/rubocop/cop/style/ternary_parentheses_spec.rb
`Style/TernaryParentheses` allows RuboCop to require ternary conditions are wrapped in parentheses, but this behaviour doesn't take effect when `Style/RedundantParentheses` is also enabled, in order to prevent an infinite loop.
However, it makes more sense for `TernaryParentheses` to take priority here and have `RedudantParentheses` allow the parentheses instead of creating an infinite autocorrection loop.
This change moves the infinite loop protection into `RedundantParentheses` instead.
=> [Fix #10648] Allow `Style/TernaryParentheses` to take priority over `Style/RedundantParentheses` for requiring parentheses

changelog/fix_a_false_positive_for_shadowing_outer_local_variable.md, lib/rubocop/cop/lint/shadowing_outer_local_variable.rb, spec/rubocop/cop/lint/shadowing_outer_local_variable_spec.rb
=> [Fix #10512] Fix a false positive for `Lint/ShadowingOuterLocalVariable` conditional statement and block variable

spec/rubocop/cop/layout/line_end_string_concatenation_indentation_spec.rb
- Resolves what seems to be an unintentional typo where `elif` (as a method call) is being use in place of the `elsif` keyword.
=> Fix `elif` (`elsif`) typo

changelog/fix_add_min_and_max_to_list_of_false_positives_for_style_symbol_proc.md, lib/rubocop/cop/style/symbol_proc.rb, spec/rubocop/cop/style/symbol_proc_spec.rb
This PR fixes a false positive for Style/SymbolProc when using Array#min and Array#max
The cop incorrectly assumes that the two invocations below are the same, and recommends the former:
```
> [1,2,3].min(&:to_i)
ArgumentError: wrong number of arguments (given 1, expected 0)
> [1,2,3].min { |x| x.to_i }
=> 1
```
Style/SymbolProc is already marked as unsafe, but it avoids avoidable issues.
=> add min and max to list of false positives for Style/SymbolProc

changelog/change_update_parser_gem_to_3121.md, rubocop.gemspec
The `parser` gem has been updated which fixes a crash parsing one line patterns without braces. See https://github.com/whitequark/parser/pull/864.
Fixes #10773.
=> [Fix #10773] Update `parser` gem to >= 3.1.2.1

lib/rubocop/cop/lint/shadowed_exception.rb
After #10861 I figured we can improve the documentation for `Lint/ShadowedException`.
=> Improve documentation for `Lint/ShadowedException`

changelog/fix_fix_stylesolenestedconditional_to.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
`Style/SoleNestedConditional` adds parentheses around `send` nodes that have unparenthesized arguments, but this wasn't being done for `csend` or `block` nodes, so this change fixes that.
Fixes #10881.
=> [Fix #10881] Fix `Style/SoleNestedConditional` to properly wrap `block` and `csend` nodes when necessary

changelog/fix_an_error_for_no_bundle_exec.md, lib/rubocop/feature_loader.rb
Fixes #10893.
This PR fixes an error when running `rubocop` without `bundle exec`.
=> [Fix #10893] Fix an error when running `rubocop` without `bundle exec`

changelog/new_allow_asking_to_avoid_mixing_hash.md, config/default.yml, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, lib/rubocop/cop/style/hash_syntax.rb, spec/rubocop/cli/auto_gen_config_spec.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
For those who want to use hash shorthand style, but don't want to mix shorthand and explicit styles in the same hash we provide a new option for `EnforcedShorthandSyntax` called `consistent` that raises an offence if we've mixed styles.
E.g.
{foo: , bar: bar}
{foo:, bar:}
{foo: , bar: baz}
{foo: foo, bar: baz}
I don't particularly like the implementation.  Prior to this commit `HashSyntax` mixed in `HashShorthandSyntax` but was otherwise unaware of it.  With this change I've had to make `HashSyntax` aware of `HashShorthandSyntax` so it can call `on_hash_for_mixed_shorthand` in `on_hash`.  I don't think there's a way to enforce a no mixing style at the pair level meaning we can't do this in `on_pair` already present in `HashShorthandSyntax` and have to use `on_hash` to look at the whole …
=> Allow asking to avoid mixing hash shorthand styles in single hashes

changelog/fix_fix_incorrect_autocomplete_in.md, lib/rubocop/cop/correctors/parentheses_corrector.rb, lib/rubocop/cop/mixin/range_help.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
Heredocs always causing problems :grin:
Fixes `Style/RedundantParentheses` to put the comma in the correct spot. Fixes #10895.
=> [Fix #10895] Fix incorrect autocomplete in `Style/RedundantParentheses` when a heredoc is used in an array

spec/rubocop/server/rubocop_server_spec.rb
This PR skips the following flaky test for RSpec 4 GitHub Actions job.
```console
1) rubocop --server when using `--server` option after updating
RuboCop displays a restart information message
Failure/Error:
expect(`ruby -I . "#{rubocop}" #{options}`).to start_with(
'RuboCop version incompatibility found, RuboCop server restarting...'
)
expected "RuboCop server starting on 127.0.0.1:36753.\nInspecting
1 file\n\e[32m.\e[0m\n\n1 file inspected, \e[32mno offenses\e[0m
detected\n" to start with "RuboCop version incompatibility found,
RuboCop server restarting...
```
Unfortunately, the root cause is unknown yet. It may be related that test-queue is not available.
In any case, this test is run on a CI other than RSpec 4 (beta) job, so there's nothing I've overlooked.
Before …
=> Skip a flaky test for RSpec 4

changelog/fix_style_class_methods_definitions_for_non_self_receivers.md, lib/rubocop/cop/style/class_methods_definitions.rb, spec/rubocop/cop/style/class_methods_definitions_spec.rb
The `Style/ClassMethodsDefinitions` cop controls if class methods should be defined using
```ruby
class Klass
class << self
def method_name
```
or
```ruby
class Klass
def self.method_name
```
Given the current error message, it should not apply to singleton methods defined on objects that aren't `self`:
```ruby
object = Object.new
def object.method_name
```
> **Note**
> We could potentially follow up with a config that allows controlling if this cop applies **only** to **`self`** or to **_any_ receiver**.
=> Fix `Style/ClassMethodsDefinitions` for non-self receivers

.yardopts, Gemfile
I found some YARD documentation pages are wrongly rendered in HTML.
Currently `--markup markdown` is specified, but many comments appear to use AsciiDoc notation. Perhaps it should be `--markup asciidoc`?
For example, see the difference of `RuboCop::Cop::Style::RedundantArgument` doc page:
To reproduce this, run thw following command,
```
bundle install
bundle exec rake yard
```
then open `./doc/RuboCop/Cop/Style/RedundantArgument.html`.
=> Change yard `--markup` option from `markdown` to `asciidoc`

changelog/fix_fix_loading_behavior_on_running_without.md, lib/rubocop/feature_loader.rb, spec/rubocop/feature_loader_spec.rb
This is an additional fix for #10893 and #10894.
The error in normal usage was fixed at #10894, but there is one more `Kernel.require` so there is a possible error in the case where users try to use the new feature.
=> [Fix #10893] Fix loading behavior on running without `bundle exec`

changelog/fix_make_style_arguments_forwarding_aware_of_anonymous_block_argument.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
Fixes #10913.
This PR makes `Style/ArgumentsForwarding` aware of anonymous block argument.
=> [Fix #10913] Make `Style/ArgumentsForwarding` aware of anonymous block argument

lib/rubocop/cop/lint/erb_new_arguments.rb
The documentation code snippet does not render as code, but as plaintext.
Indenting it causes it to be interpreted as a block of code.
* ~Added tests.~
=> Fix `Lint/ErbNewArguments` code snippet formatting

lib/rubocop/cop/layout/line_length.rb
Both ArgumentAlignment and HashAlignment are listed so it looks like
ArrayAlignment should also be included.
=> Add ArrayAlignment to list of recommended Layout cops for LineLength

changelog/fix_an_error_when_dot_rubocop_yml_is_empty.md, lib/rubocop/server/cache.rb, spec/rubocop/server/cache_spec.rb
This PR fixes the following error when .rubocop.yml is empty.
```console
% touch .rubocop.yml
% rubocop
/Users/koic/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.34.1/lib/rubocop/server/cache.rb:75:in
`block in cache_root_dir_from_config': undefined method `dig' for nil:NilClass (NoMethodError)
config_yaml.dig('AllCops', 'CacheRootDirectory')
^^^^
from /Users/koic/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.34.1/lib/rubocop/cache_config.rb:9:in
`root_dir'
from /Users/koic/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.34.1/lib/rubocop/server/cache.rb:61:in
`cache_root_dir_from_config'
from /Users/koic/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.34.1/lib/rubocop/server/cache.rb:54:in
`cache_path'
from …
```
=> Fix an error when .rubocop.yml is empty

changelog/fix_an_error_for_lint_shadowing_outer_local_variable.md, lib/rubocop/cop/lint/shadowing_outer_local_variable.rb, spec/rubocop/cop/lint/shadowing_outer_local_variable_spec.rb
Fixes #10899.
This PR fixes an error for `Lint/ShadowingOuterLocalVariable` when the same variable name as a block variable is used in return value assignment of `if`.
=> [Fix #10899] Fix an error for `Lint/ShadowingOuterLocalVariable`

changelog/fix_an_incorrect_autocorrect_for_style_sole_nested_conditional.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
Fixes #10920.
This PR fixes an incorrect autocorrect for `Style/SoleNestedConditional` when using nested conditional and branch contains a comment.
It removes `return if config.for_cop('Style/IfUnlessModifier')['Enabled']` that introduced in #9195. That logic is now unnecessary due to https://github.com/rubocop/rubocop/commit/3fea162 change.
=> [Fix #10920] Fix an incorrect autocorrect for `Style/SoleNestedConditional`

changelog/fix_an_error_for_lint_non_atomic_file_operation.md, lib/rubocop/cop/lint/non_atomic_file_operation.rb, spec/rubocop/cop/lint/non_atomic_file_operation_spec.rb
Fixes #10936.
This PR fixes an error for `Lint/NonAtomicFileOperation` when using `FileTest.exist?` as a condition for `elsif`.
Complex cases such as `if`/`elsif`/`else` don't autocorrect and respect user changes.
=> [Fix #10936] Fix an error for `Lint/NonAtomicFileOperation`

changelog/fix_make_style_safe_navigation_aware_of_a_redundant_nil_check.md, lib/rubocop/cop/style/safe_navigation.rb, spec/rubocop/cop/style/safe_navigation_spec.rb
Fixes #10926.
This PR makes `Style/SafeNavigation` aware of a redundant nil check.
IMHO, the context of this patch is a minimal update. OTOH, a new cop like `Style/RedundantNilCheck` cop may be implemented if it is not suitable for this `Style/SafeNavigation` cop. (But I'm not sure if it's the best.)
=> [Fix #10926] Make `Style/SafeNavigation` aware of a redundant nil check

changelog/fix_an_error_when_using_erb_in_confi.md, lib/rubocop/server/cache.rb, spec/rubocop/server/cache_spec.rb
Fixes #10921.
This PR fixes an error when ERB pre-processing of the configuration file.
=> [Fix #10921] Fix an error when processing configuration file

lib/rubocop/cop/lint/redundant_safe_navigation.rb
This PR, we have added a supplement on the `AllowedMethods` option and changed the examples.
Ref: https://github.com/rubocop/rubocop/pull/10876#issuecomment-1207885926
=> Enhanced documentation for `Lint/RedundantSafeNavigation`

tasks/prof.rake
https://github.com/rubocop/rubocop/pull/8962 broke `rake prof:slow_cops`.
```
rake prof:slow_cops
```
**Before**
```
182  (  100.0%)  Array#each
181  (   99.5%)  Kernel#public_send
code:
```
**After**
```
9  (    4.9%)  RuboCop::Cop::Layout::RedundantLineBreak#on_send
7  (    3.8%)  RuboCop::Cop::Layout::IndentationConsistency#on_begin
6  (    3.3%)  RuboCop::Cop::Lint::DuplicateMethods#on_def
6  (    3.3%)  RuboCop::Cop::MethodComplexity#on_def
5  (    2.7%)  RuboCop::Cop::MultilineExpressionIndentation#on_send
... snip ...
```
cc @koic
=> Fix `rake prof:slow_cops` to return correct results

lib/rubocop/cop/style/safe_navigation.rb, spec/rubocop/cop/style/safe_navigation_spec.rb
Running rubocop on
```ruby
link && !link&.persisted?
```
```
Scanning foobar.rb
An error occurred while Style/SafeNavigation cop was inspecting foobar.rb:11:54.
Expected a Parser::Source::Range, Comment or RuboCop::AST::Node, got NilClass
/Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/cop/corrector.rb:91:in `to_range'
/Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/cop/corrector.rb:100:in `check_range_validity'
/Users/fatkodima/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter.rb:398:in `combine'
/Users/fatkodima/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter.rb:207:in `wrap'
/Users/fatkodima/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter. …
```
=> Fix `Style/SafeNavigation` for negated method call with a safe navigation

changelog/fix_an_incorrect_autocorrect_for_lint_literal_in_interpolation.md, lib/rubocop/cop/lint/literal_in_interpolation.rb, spec/rubocop/cop/lint/literal_in_interpolation_spec.rb
Fixes #10944.
This PR fixes an incorrect autocorrect for `Lint/LiteralInInterpolation` when using `"#{nil}"`.
=> [Fix #10944] Fix an incorrect autocorrect for `Lint/LiteralInInterpolation`

changelog/fix_an_error_for_style_next.md, lib/rubocop/cop/style/next.rb, spec/rubocop/cop/style/next_spec.rb
Fixes #10939.
This PR fixes an error for `Style/Next` when line break before condition. The removed indentation logic can be delegated to `Layout/IndentationConsistency`.
=> [Fix #10939] Fix an error for `Style/Next`

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md, changelog/change_add_server_mode_to_version_option.md, lib/rubocop/version.rb
When YJIT (disabled by default) is enabled in Ruby, it is displayed as follows.
```console
% ruby --yjit -ve 'RubyVM::YJIT.enabled?'
ruby 3.2.0dev (2022-08-18T08:09:08Z master b0b9f7201a) +YJIT [x86_64-darwin19]
```
`+YJIT` is added when YJIT is enabled.
This is a change inspired by it. Below is before and after `rubocop -V`.
```console
% rubocop -V
1.35.0 (using Parser 3.1.2.1, rubocop-ast 1.21.0, running on ruby 3.2.0 x86_64-darwin19)
- rubocop-performance 1.14.3
- rubocop-rake 0.6.0
- rubocop-rspec 2.11.1
```
It makes the `-V` format like `ruby --version`.
The platform (`x86_64-darwin19`) display will change slightly.
```console
% rubocop -V
1.35.0 (using Parser 3.1.2.1, rubocop-ast 1.21.0, running on ruby 3.2.0) [x86_64-darwin19]
- rubocop-performance 1.14.3
- rubocop-rake 0.6.0
- …
```
=> Add server mode status to `-V` option

changelog/fix_a_false_positive_for_style_hash_transform_values.md, lib/rubocop/cop/mixin/hash_transform_method.rb, spec/rubocop/cop/style/hash_transform_keys_spec.rb, spec/rubocop/cop/style/hash_transform_values_spec.rb
Fixes #10927.
This PR fixes a false positive for `Style/HashTransformKeys` and `Style/HashTransformValues` when not using transformed block argument.
=> [Fix #10927] Fix a false positive for `Style/HashTransformKeys` and `Style/HashTransformValues`

spec/rubocop/formatter/formatter_set_spec.rb
This PR skips the following build error of formatter_set_spec.rb in the windows mingw CI matrix.
```console
Failures:
1) RuboCop::Formatter::FormatterSet add_formatter when output path is specified when parent directories don't exist creates them
Failure/Error: after { FileUtils.rm_rf(tmpdir) }
Errno::EACCES:
Permission denied @ apply2files - D:/a/_temp/d20220824-1696-gdx8qj/path/does/not/exist
Finished in 2 minutes 34.9 seconds (files took 3.68 seconds to load)
18699 examples, 1 failure, 15 pending
```
https://github.com/rubocop/rubocop/runs/7986996059
=> Workaround for a build error of formatter_set_spec.rb  in the windows mingw CI matrix

.github/workflows/linting.yml, .github/workflows/rubocop.yml, .gitignore, spec/rubocop/formatter/formatter_set_spec.rb
Commits:
Three commits, first is a spec fix, next two make working in a fork easier.
1. 'formatter/formatter_set_spec.rb - remove references to file IO on Windows' - Windows will error if a file is deleted when references to its File object exist.  Removes the 'skip' code from PR #10955.
2. '.gitignore - add `vendor/` for local development' - if one prefers to `bundle install` within the repo, this is the standard folder.
3. `Actions - add workflow_dispatch for use in forks` - Currently, running `linting.yml` and `rubocop.yml` are difficult to run in a fork.  `workflow_dispatch` allows an owner/maintainer to force a workflow to run on any branch.
=> Windows specs - remove references to File objects before unlinking

tasks/spec_runner.rake
Currently, the `spec` & `ascii_spec` steps in GitHub Actions are rendered in color by RSpec.   That adds a lot of characters to the 'dot' output, and for whatever reason, GitHub Actions doesn't display the logs of those steps in the web ui.
Actions defines an ENV variable `GITHUB_ACTIONS`.  Use it to switch RSpec output to `--no-color`.
=> Actions - use --no-color so 'web ui' shows logs for RSpec steps

changelog/fix_fix_an_infinite_loop_for_layout_space_inside_block_braces.md, lib/rubocop/cop/layout/space_inside_block_braces.rb, spec/rubocop/cop/layout/space_inside_block_braces_spec.rb
=> [Fix #10958] Fix an infinite loop for `Layout/SpaceInsideBlockBraces` when multiline block

changelog/fix_a_false_positive_for_layout_indentation_width.md, lib/rubocop/cop/layout/indentation_width.rb, spec/rubocop/cop/layout/indentation_width_spec.rb
Fixes #10963.
This PR fixes a false positive for `Layout/IndentationWidth` when using aligned empty `else` in pattern matching.
=> [Fix #10963] Fix a false positive for `Layout/IndentationWidth`

changelog/fix_fix_a_huge_performance_regression.md, lib/rubocop/cop/mixin/allowed_methods.rb, lib/rubocop/cop/mixin/allowed_pattern.rb, spec/rubocop/cli/auto_gen_config_spec.rb
Fix: #10919
Before:
- 1.32.0 (using Parser 3.1.2.1, rubocop-ast 1.21.0, running on ruby 2.7.2 x86_64-darwin21)
`bundle exec rubocop --cache false --only   16.83s user 1.30s system 93% cpu 19.320 total`
- 1.35.0 (using Parser 3.1.2.1, rubocop-ast 1.21.0, running on ruby 2.7.2 x86_64-darwin21)
`bundle exec rubocop --cache false --only   1255.21s user 5.32s system 71% cpu 29:17.76 total`
After:
`bundle exec rubocop --cache false --only 16.64s user 1.25s system 94% cpu 19.002 total`
=> [Fix #10919] Fix a huge performance regression between 1.32.0 and 1.33.0

changelog/change_add_autocorrect_support_to.md, config/default.yml, lib/rubocop/cop/style/access_modifier_declarations.rb, spec/rubocop/cop/style/access_modifier_declarations_spec.rb
I would like to change `Style/AccessModifierDeclarations` to be able to autocorrect.
I made a little effort about indentation and empty lines with `RuboCop::Cop::RangeHelp#range_by_whole_lines` and some other treatments, but it does not handle them perfectly. They should be autocorrected by other Layout cops.
=> Add autocorrect support to `Style/AccessModifierDeclarations`

changelog/fix_a_false_positive_for_lint_shadowing_outer_local_variable.md, lib/rubocop/cop/lint/shadowing_outer_local_variable.rb, spec/rubocop/cop/lint/shadowing_outer_local_variable_spec.rb
=> [Fix #10962] Fix a false positive for `Lint/ShadowingOuterLocalVariable` when conditional with if/elsif/else branches

changelog/fix_fix_an_autocorrection_error_for_lint_empty_conditional_body.md, lib/rubocop/cop/lint/empty_conditional_body.rb, spec/rubocop/cop/lint/empty_conditional_body_spec.rb
=> [Fix #10951] Fix an autocorrection error for `Lint/EmptyConditionalBody` when some conditional branch is empty

lib/rubocop/cop/lint/duplicate_require.rb, lib/rubocop/cop/lint/shadowed_exception.rb, lib/rubocop/cop/lint/unreachable_loop.rb, lib/rubocop/cop/style/symbol_proc.rb
I found some documentation pages are wrongly rendered.
This is due to incorrect use of backtick in Asciidoc. If you want to insert character immediately after the code element without any spaces, you need to write a double backtick like this.
=> Fix some wrong backtick use in Asciidoc documents

lib/rubocop/cop/lint/useless_ruby2_keywords.rb
I found a problem with the `UselessRuby2Keywords` cop documentation page not rendered well.
- https://docs.rubocop.org/rubocop/1.34/cops_lint.html#lintuselessruby2keywords
Look around the `<strong>` element.
```html
<p><code>ruby2_keywords</code> should only be called on methods that accept an argument splat
(<code><strong>args</code>) but do not explicit keyword arguments (<code>k:</code> or <code>k: true</code>) or
a keyword splat (<code></strong>*kwargs</code>).</p>
```
```html
<p><code>ruby2_keywords</code> should only be called on methods that accept an argument splat
(<code>*args</code>) but do not explicit keyword arguments (<code>k:</code> or <code>k: true</code>) or
a keyword splat (<code>**kwargs</code>).</p>
``` …
=> Fix wrong asterisk use in `Lint/UselessRuby2Keywords` document

lib/rubocop/cop/style/symbol_proc.rb
Since `Symbol#to_proc` is a bit difficult concept to understand in Ruby and is often tripped up by beginners, I thought it would be better to document it more precisely.
The original text explains it as follows:
> ``proc``s and blocks work differently
but this is not a very appropriate explanation I think, since both equally create an instance of the `Proc` class, so it is not reasonable to explain them as opposites. And worse, Ruby also has a keyword `proc`, so it is better to avoid using this word in a way that could be misinterpreted as a keyword as much as possible.
=> Improve safety section on `Style/SymbolProc`

changelog/fix_possible_wrong_autocorrection_in_namespace_on.md, lib/rubocop/cop/style/perl_backrefs.rb, spec/rubocop/cop/style/perl_backrefs_spec.rb
Inserting constants in the code without `::` prefix may cause problems in situations where `Module.nesting` is not empty, as the test case I added describes.
In order to eliminate the possibility of such unsafe autocorrection, it would be better to prepend `::`, even if it looks a bit verbose.
=> Fix possible wrong autocorrection in namespace on `Style/PerlBackrefs`

changelog/fix_speed_up_single_file_inspection.md, lib/rubocop/runner.rb, spec/rubocop/cli/options_spec.rb
This MR makes it so that if there is only a single file to be inspected, we do not split off extra worker processes to do the work. This is because doing the work in a separate process can never be faster than doing it inline. I benchmarked this change on my dev machine (with 6 physical cores) and it saves 40-50 ms per run (only if only a single file is inspected of course, otherwise it will take as long as before).
I did not know what to update the test with, so I just made it expect the new text. Let me know if this should be different.
(This is a fixed version of https://github.com/rubocop/rubocop/pull/10889, where I had messed up the rebasing)
=> Single file skip parallel

changelog/new_add_allowonselfclass_option_to.md, config/default.yml, lib/rubocop/cop/style/case_equality.rb, spec/rubocop/cop/style/case_equality_spec.rb
`Style/CaseEquality`'s `AllowOnConstant` option allows the use of constants, to allow for case equality with classes and modules. `self.class` is a special case also referring to a class, and may be required in cases where the other object might be a `BasicObject`.
=> Add `AllowOnSelfClass` option to `Style/CaseEquality`

.circleci/config.yml, .github/workflows/rubocop.yml, spec/spec_helper.rb
This is an update similar to #10326.
https://hub.docker.com/r/circleci/jruby hasn't been updated in a while.
This PR migrates the JRuby CI matrix from CircleCI to GitHub Actions to keep up with the latest JRuby version.
=> Use GitHub Actions instead of CircleCI for JRuby matrix

changelog/fix_a_false_positive_for_style_redundant_parentheses.md, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
Fixes #10979.
This PR fixes a false positive for `Style/RedundantParentheses` when using parentheses with pin operator except for variables.
This PR also allows literals because:
`foo in { bar: ^(1) }` should be corrected to `foo in { bar: 1 }`.
`foo in { bar: ^([1]) }` should be corrected to `foo in { bar: [1] }`.
`foo in { bar: ^([var]) }` should be allowed because `foo in { bar: [var] }` performs capture.
=> [Fix #10979] Fix a false positive for `Style/Style/RedundantParentheses`

changelog/change_autocorrect_0origin_range_with_block.md, lib/rubocop/cop/style/each_for_simple_loop.rb, spec/rubocop/cop/style/each_for_simple_loop_spec.rb
If there is a block argument, it should be autocorrectable when the starting point of the range is 0.
```ruby
(0...10).each do |i|
puts i
end
10.times do |i|
puts i
end
```
=> Add more autocorrect support on `Style/EachForSimpleLoop`

lib/rubocop/cop/lint/useless_access_modifier.rb
It is not appropriate to use `public` in this example.
```ruby
class Foo
public
def self.method3
end
end
```
As explained in the previous example, the access is `public` by default, which makes no sense regardless of whether it is a singleton method or not.
=> Improve singleton method example on `Lint/UselessAccessModifier` cop

spec/rubocop/server/rubocop_server_spec.rb
This PR adds a spec for server mode that applies .rubocop.yml configuration changes even during server startup.
This is already achieved because the server loads .rubocop.yml configuration for each analysis request from the client.
The feature mentioned in the following article has been implemented for configuration change of .rubocop.yml.
> You should keep in mind that you'll need to restart the server manually
> if you change RuboCop's configuration.
https://metaredux.com/posts/2022/07/26/rubocop-serves-much-faster.html
The test this PR adds ensure that behavior.
=> Add a spec for server mode

changelog/change_warn_for_both_safe_and_unsafe_autocorrect_options_are_specified.md, lib/rubocop/options.rb, spec/rubocop/options_spec.rb
If both `-a` option and `-A` option are specified then `-a` is applied. This is obviously misused and will raise an error.
```console
% echo 'puts "Hi"' | bundle exec rubocop --stdin example.rb -A -a
Error: Both safe and unsafe autocorrect options are specified, use only one.
```
=> Display warning message when both safe and unsafe autocorrect options are specified

lib/rubocop/rspec/shared_contexts.rb, spec/rubocop/server/rubocop_server_spec.rb
While working on https://github.com/rubocop/rubocop/pull/10987, I sometimes had intermittent test failures in `/rubocop/server/rubocop_server_spec.rb`, one example can be seen [here](https://app.circleci.com/pipelines/github/rubocop/rubocop/7260/workflows/2ec04e3d-e56f-4704-b1c6-a9871c48daea/jobs/240271).
I managed to reproduce on the master branch with `bundle exec rspec ./spec/rubocop/server/cli_spec.rb[1:5:1] ./spec/rubocop/server/rubocop_server_spec.rb[1:1:1] --seed 61707 -fd`, and finally figured out the following: 
When doing `RuboCop::Server::Cache.write_version_file('0.99.9')`, `RuboCop::Server::Cache` was still using memoized data generated during the run of `spec/rubocop/server/cli_spec.rb`, which is the previous isolated environment, so the version cache file read during the …
=> Fix server cache pollution between tests 

docs/modules/ROOT/pages/index.adoc
Not sure if that deserves a Changelog entry altogether.
I'm not an expert english person but I think those look like unintentional mistake unless I'm unaware of some additional language rules:
- "there are **so** many" instead of "there are **some** many" 
- "The early feedback we got **led** us" should be a past tense because of "got"
- "adopt **a** philosophy" instead of "adopt **of**"
=> Fix some wording

changelog/fix_an_error_when_running_3rd_party_gem_that_does_not_require_server.md, lib/rubocop/version.rb, spec/rubocop/version_spec.rb
Fixes #10994.
This PR fixes an error when running 3rd party gem that does not require server.
=> [Fix #10994] Fix an error when running 3rd party gem that does not require server

.gitignore, changelog/new_make_rubocop_aware_of_server_option_from_file_and_env.md, docs/modules/ROOT/pages/usage/server.adoc, lib/rubocop/arguments_env.rb, lib/rubocop/arguments_file.rb, lib/rubocop/options.rb, lib/rubocop/server/cli.rb, spec/rubocop/server/cli_spec.rb
This PR makes `rubocop` command aware of `--server` option from .rubocop and RUBOCOP_OPTS.
If `RUBOCOP_OPTS` environment variable or `.rubocop` file contains `--server` option, `rubocop` command defaults to server mode. Other server options such as `stop-server`, `restart-server` specified on the command line will take precedence over them.
This feature rides on the existing following feature.
> Default command-line options are loaded from `.rubocop` and `RUBOCOP_OPTS` and
> are combined with command-line options that are explicitly passed to `rubocop`.
> Thus, the options have the following order of precedence (from highest to lowest):
>
> 1. Explicit command-line options
>
> 2. Options from RUBOCOP_OPTS environment variable
>
> 3. Options from .rubocop file. …
=> Make `rubocop` command aware of `--server` option from .rubocop and RUBOCOP_OPTS

CONTRIBUTING.md, spec/project_spec.rb
CHANGELOG.md is already mixed with and without URLs, so direct editing of CHANGELOG.md was hard to prevent formatting without URL, but the new form of adding future changelog entry to the changelog directory can force URL.
Instead of reviewer pointing out, the automated test failure can inform that to reviewee.
=> Add a project spec for future changelog entry

changelog/fix_parens_in_assignments_in_condition.md, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
Parentheses are required in assignments that call methods in conditional branches. Removing them is a syntax error and the `Style/MethodCallWithArgsParentheses` cop with the style of `omit_parentheses` has been doing just that during autocorrection.
Here is an example that needs the parentheses but is improperly autocorrected:
```ruby
if success = destroy_remote(server)
delete server
end
```
Removing them, as the autocorrection does, is a syntax error:
```ruby
if success = destroy_remote server # 💣
delete server
end
```
Such is the case for any assignment or shorthand assignment in any Ruby conditional.
=> Do not omit parentheses for calls in assignments in conditional branches

changelog/fix_fix_an_autocorrect_for_lint_empty_conditional_body.md, lib/rubocop/cop/lint/empty_conditional_body.rb, spec/rubocop/cop/lint/empty_conditional_body_spec.rb
Syntax Error was generated when the following code was autocorrect.
```ruby
if condition
else
end
```
```ruby
end
```
```
E
Offenses:
test.rb:1:1: W: [Corrected] Lint/EmptyConditionalBody: Avoid if branches without a body.
if condition ...
^^^^^^^^^^^^
test.rb:1:1: C: [Corrected] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
if condition
^
test.rb:2:1: E: Lint/Syntax: unexpected token kEND
end
^^^
test.rb:2:1: C: [Corrected] Style/EmptyElse: Redundant else-clause.
else
^^^^
1 file inspected, 4 offenses detected, 3 offenses corrected
```
* [-] Commit message starts with `[Fix …
=> Fix an autocorrect for `Lint/EmptyConditionalBody` that causes a SyntaxError when missing `if` and `else` body

lib/rubocop/cop/lint/ambiguous_block_association.rb, lib/rubocop/cop/lint/number_conversion.rb, lib/rubocop/cop/lint/unreachable_loop.rb, lib/rubocop/cop/style/block_delimiters.rb, lib/rubocop/cop/style/class_equality_comparison.rb, lib/rubocop/cop/style/format_string_token.rb, lib/rubocop/cop/style/numeric_predicate.rb, lib/rubocop/cop/style/symbol_proc.rb, spec/rubocop/cop/style/block_delimiters_spec.rb, spec/rubocop/cop/style/class_equality_comparison_spec.rb, spec/rubocop/cop/style/method_call_without_args_parentheses_spec.rb, spec/rubocop/cop/style/numeric_literals_spec.rb, spec/rubocop/cop/style/numeric_predicate_spec.rb, spec/rubocop/cop/style/symbol_proc_spec.rb
This PR is fix a wrong AllowedPatterns example
When specifying in the .rubocop.yml file, it is necessary
to specify `AllowedPatterns: ['foo']` instead of `AllowedPatterns: [/foo/]`.
Follow up: https://github.com/rubocop/rubocop-rspec/issues/1395
The test code was also modified to match the actual behavior as mentioned in https://github.com/rubocop/rubocop-rspec/pull/1396#issuecomment-1257026847 .
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry …
=> Fix a wrong AllowedPatterns example

changelog/fix_an_incorrect_autocorrect_for_style_redundant_condition.md, lib/rubocop/cop/style/redundant_condition.rb, spec/rubocop/cop/style/redundant_condition_spec.rb
Fixes #11022.
This PR fixes an incorrect autocorrect for `Style/RedundantCondition` when using redundant brackets access condition.
=> [Fix #11022] Fix an incorrect autocorrect for `Style/RedundantCondition`

changelog/fix_an_error_occurred_for_style_symbol_array_and_style_word_array.md, lib/rubocop/cop/style/symbol_array.rb, lib/rubocop/cop/style/word_array.rb, spec/rubocop/cop/style/symbol_array_spec.rb, spec/rubocop/cop/style/word_array_spec.rb
Fixes #11026.
This PR fixed an error with an empty percent array.
The original issue #11026 was reported for `Style/SymbolArray`, but it was also occurring for `Style/WordArray`,
so it has been corrected.
=> [Fix #11026] Fix an error occurred for `Style/SymbolArray` and `Style/WordArray` when empty percent array

changelog/fix_a_false_positive_for_lint_require_parentheses.md, lib/rubocop/cop/lint/require_parentheses.rb, spec/rubocop/cop/lint/require_parentheses_spec.rb
Fixes #11028
This PR fixes a false positive for `Lint/RequireParentheses` when using ternary operator in square bracksts.
This case should be allowed because it's the same as the already accepted ternary operator (`foo && bar ? baz : qux`) and the precedence is clear.
=> [Fix #11028] Fix a false positive for `Lint/RequireParentheses`

changelog/fix_an_incorrect_autocorrect_for_lint_unused_method_argument.md, lib/rubocop/cop/lint/unused_method_argument.rb, lib/rubocop/cop/style/explicit_block_argument.rb, spec/rubocop/cli/autocorrect_spec.rb
Fixes #11030.
This PR fixes an incorrect autocorrect for `Lint/UnusedMethodArgument` and `Style::ExplicitBlockArgument` when autocorrection conflicts for `&block` argument.
=> [Fix #11030] Fix an incorrect autocorrect for `Lint/UnusedMethodArgument`

changelog/fix_a_false_positive_for_style_collection_compact.md, lib/rubocop/cop/style/collection_compact.rb, spec/rubocop/cop/style/collection_compact_spec.rb
Fixes #11037.
This PR fixes a false positive for `Style/CollectionCompact` when using `to_enum.reject` or `lazy.reject` methods with Ruby 3.0 or lower.
=> [Fix #11037] Fix a false positive for `Style/CollectionCompact`

lib/rubocop/cop/generator.rb, spec/rubocop/cop/generator_spec.rb
This PR fix cop generator for nested department start with `RSpec`. For example, the following execute new_cop:
```
bundle exec rake 'new_cop[RSpec/Foo/Bar]'
```
Then expect the following file to be created:
```
lib/rubocop/cop/rspec/foo/bar.rb
spec/rubocop/cop/rspec/foo/bar_spec.rb
```
In actual, however, the following file is generated:
```
lib/rubocop/cop/r_spec/foo/bar.rb
spec/rubocop/cop/r_spec/foo/bar_spec.rb
```
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. …
=> Fix cop generator for nested department start with `RSpec`

config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/hash_syntax.rb
`EnforcedShorthandSyntax: consistent` behave more like `either` than `always`
Why is it not like `always`:
- `consistent` allows regular and shorthand hash syntax, but not mixed
- `always`     allows only the shorthand syntax
=> `consistent` does not behave like `always
Why is like `either`:
- `consistent` allows regular and shorthand hash syntax, but not mixed
- `either`     allows regular and shorthand hash syntax.
=> `consistent` is similar to `either` but does not allow mixing syntax.
=> Fixes documentation message for EnforcedShorthandSyntax: consistent

changelog/fix_preserve_comments_on.md, lib/rubocop/cop/style/access_modifier_declarations.rb, spec/rubocop/cop/style/access_modifier_declarations_spec.rb
=> [Fix #11051] Preserve comments on `Style/AccessModifierDeclarations` autocorrection

changelog/fix_a_false_positive_for_lint_safe_navigation_chain.md, lib/rubocop/cop/lint/safe_navigation_chain.rb, spec/rubocop/cop/lint/safe_navigation_chain_spec.rb
Fixes #11047.
This PR fixes an incorrect autocorrect for `Style/SafeNavigationChain` when using `+@` and `-@` methods.
These methods are not intended for use with safe navigation.
=> [Fix #11047] Fix an incorrect autocorrect for `Style/SafeNavigationChain`

spec/rubocop/cop/mixin/enforce_superclass_spec.rb
Right now when running `bundle exec rspec` to run the test suite, the following warning pops several times:
```
`RuboCop::Cop::EnforceSuperclass` is deprecated and will be removed in RuboCop 2.0. Please upgrade to RuboCop Rails 2.9 or newer to continue.
```
As I believe it's expected behavior, I'm suggesting to silence them during the test suite
=> Expect warnings for `EnforceSuperclass` during tests

lib/rubocop/server.rb, lib/rubocop/server/cache.rb, spec/rubocop/server/cache_spec.rb
I regularly see the following error message while running the test suite:
```
$ bundle exec rspec spec/rubocop/cli/options_spec.rb:98
Run options: include {:locations=>{"./spec/rubocop/cli/options_spec.rb"=>[98]}}
Randomized with seed 64160
/Users/thierry/workspace_personal/rubocop/lib/rubocop/server/cache.rb:107:in `read': No such file or directory @ rb_sysopen - /private/var/folders/r6/h3876w6964lg75khh9435lx00000gn/T/d20221009-54597-an33p1/home/.cache/rubocop_cache/server/private+var+folders+r6+h3876w6964lg75khh9435lx00000gn+T+d20221009-54597-an33p1+work/pid (Errno::ENOENT)
from /Users/thierry/workspace_personal/rubocop/lib/rubocop/server/cache.rb:107:in `read'
from /Users/thierry/workspace_personal/rubocop/lib/rubocop/server/cache.rb:107:in `pid_running?'
from …
```
=> Fix exception in `Server::Cache#pid_running?`

changelog/new_implement_lintduplicatemethods_for.md, lib/rubocop/cop/lint/duplicate_methods.rb, spec/rubocop/cop/lint/duplicate_methods_spec.rb
The cop implementation for an object singleton class when opening `class << foo` hadn't been done, this implements the expected behavior in the pending tests.
=> Implement `Lint/DuplicateMethods` for object singleton class

changelog/change_make_lint_redundant_require_statement_aware_of_pp_ruby2_keywords_and_fiber.md, lib/rubocop/cop/lint/redundant_require_statement.rb, spec/rubocop/cop/lint/redundant_require_statement_spec.rb
This PR makes `Lint/RedundantRequireStatement` aware of `pp`, `ruby2_keywords`, and `fiber`. Also, RuboCop's `TargetRubyVersion` has been recovered up to 2.0, so it will be corrected as follows.
- 2.2+: `enumerator`, `thread`, `rational`, and `complex`
- 2.0+: `enumerator`
- 2.1+: `thread`
- 2.2+: `rational` and `complex`
- 2.5+: `pp`
- 2.7+: `ruby2_keywords`
- 3.1+: `fiber`
=> Make `Lint/RedundantRequireStatement` aware of `pp`, `ruby2_keywords`, and `fiber`

changelog/fix_preserve_comments_on_style_accessor_grouping.md, lib/rubocop/cop/style/accessor_grouping.rb, spec/rubocop/cop/style/accessor_grouping_spec.rb
When using `Style/AccessorGrouping` with `EnforcedStyle: separated`, I encountered a problem with comments being eraced by autocorrection.
```diff
class A
-  attr_reader :foo,
-    :bar, # FIXME: remove this
-    :baz
+  attr_reader :foo
+  attr_reader :bar
+  attr_reader :baz
end
```
I created this Pull Request to fix this problem. This change will result in the following autocorrection:
```diff
class A
-  attr_reader :foo,
-    :bar, # FIXME: remove this
-    :baz
+  attr_reader :foo
+  # FIXME: remove this
+  attr_reader :bar
+  attr_reader :baz
end
```
=> Preserve comments on `Style/AccessorGrouping` autocorrection

spec/project_spec.rb, spec/rubocop/config_obsoletion_spec.rb, spec/rubocop/cop/cop_spec.rb, spec/support/cops/same_name_in_multiple_namespace.rb
There are 2 tests currently xitted in the codebase:
1. Behavior of `qualified_cop_name` when 2 cops have the same name in different namespaces
Re-enabling this one by adding test cops matching this condition
2. One about `ConfigObsoletion` behavior for extracted cops which had been disabled because of random failures.
I was able to reproduce by running `rspec ./spec/rubocop/config_obsoletion_spec.rb[1:1:2:3:1,1:1:3:1] --seed 47550 -fd` and tracked it down to pollution of the `RuboCop::ConfigObsoletion.files` class variables, fixed by setting a cleanup `after` block for all tests in that file.
I also re-ordered values of some `expect` to have the expected order `expect(value).to eq expected_value` for the failure messages to be accurate. …
=> Re-enable xitted tests

changelog/change_mark_lint_ordered_magic_comments_as_unsafe_autocorrection.md, config/default.yml, lib/rubocop/cop/lint/ordered_magic_comments.rb
This cop's autocorrection is unsafe because file encoding may change.
```console
p [''.frozen?, ''.encoding] #=> [true, #<Encoding:UTF-8>]
p [''.frozen?, ''.encoding] #=> [true, #<Encoding:US-ASCII>]
```
It may be the intended file encoding, but the behavior is changed.
=> Mark `Lint/OrderedMagicComments` as unsafe autocorrection

changelog/fix_an_error_for_lint_redundant_cop_disable_directive.md, lib/rubocop/cop/lint/redundant_cop_disable_directive.rb, spec/rubocop/cop/lint/redundant_cop_disable_directive_spec.rb
Fix #11069.
This PR fixes an incorrect autocorrect for `Lint/RedundantCopDisableDirective` when disable directive contains free comment.
=> [Fix #11069] Fix an incorrect autocorrect for `Lint/RedundantCopDisableDirective`

changelog/fix_a_false_positive_for_lint_redundant_cop_disable_directive.md, lib/rubocop/cop/lint/redundant_dir_glob_sort.rb, spec/rubocop/cop/lint/redundant_dir_glob_sort_spec.rb
Fixes #11074.
This PR fixes a false positive for `Lint/RedundantDirGlobSort` when using `Dir.glob` with multiple arguments.
=> [Fix #11074] Fix a false positive for `Lint/RedundantDirGlobSort`

changelog/fix_a_false_positive_for_style_redundant_begin.md, lib/rubocop/cop/style/redundant_begin.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
This PR fixes a false positive for `Style/RedundantBegin` when using endless method definition for `begin` with multiple statements.
For example, the following `begin` is not redundant.
```ruby
def foo = begin
bar
baz
end
```
=> Fix a false positive for `Style/RedundantBegin`

changelog/fix_fix_indentation_of_super_method.md, lib/rubocop/cop/layout/first_argument_indentation.rb, spec/rubocop/cop/layout/first_argument_indentation_spec.rb
Fixes the indentation of the first argument of `super` method. This is reported in https://github.com/rubocop/rubocop/issues/9116 and https://github.com/rubocop/rubocop/issues/11062 as bugs for the `Layout/FirstMethodArgumentLineBreak` cop but is actually the responsability of `Layout/FirstArgumentIndentation` for common methods.
=> [Fix #9116] Fix indentation of `super` method arguments

changelog/change_style_negated_if_else_condition_looks_inside_parentheses.md, lib/rubocop/cop/style/negated_if_else_condition.rb, spec/rubocop/cop/style/negated_if_else_condition_spec.rb
Style/NegatedIfElseCondition looks inside parentheses for checking negated conditions.
```ruby
(x != y) ? do_something : do_something_else
```
would be marked offense and corrected into:
```ruby
(x == y) ? do_something_else : do_something
```
As a bonus, `begin-end`s used as conditions receive the same treatment.
=> [Fix #10924] `Style/NegatedIfElseCondition` looks inside parentheses (and begin-ends)

changelog/fix_a_false_positive_for_lint_duplicate_regexp_character_class_element.md, lib/rubocop/cop/lint/duplicate_regexp_character_class_element.rb, spec/rubocop/cop/lint/duplicate_regexp_character_class_element_spec.rb
Fixes #11067.
This PR fixes a false positive for `Lint/DuplicateRegexpCharacterClassElement` when using regexp character starts with escaped zero number.
=> [Fix #11067] Fix a false positive for `Lint/DuplicateRegexpCharacterClassElement`

changelog/fix_a_false_positive_for_style_redundant_regexp_character_class.md, lib/rubocop/cop/style/redundant_regexp_character_class.rb, spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb
This is a similar issue to https://github.com/rubocop/rubocop/issues/11067.
This PR fixes a false positive for `Style/RedundantRegexpCharacterClass` when using starting with "\0" number.
=> Fix a false positive for `Style/RedundantRegexpCharacterClass`

changelog/change_space_array_bracket_compact_mode.md, lib/rubocop/cop/layout/space_inside_array_literal_brackets.rb, lib/rubocop/cop/mixin/surrounding_space.rb, rubocop.gemspec, spec/rubocop/cop/layout/space_inside_array_literal_brackets_spec.rb
The `compact` mode for `Layout/SpaceInsideArrayLiteralBrackets` wasn't implemented according to the expected behavior in the tests, this PRs makes the relevant fixes for the tests to pass.
=> Implement correct compact mode for `SpaceInsideArrayLiteralBrackets`

changelog/change_detect_empty_hash_literal_braces.md, lib/rubocop/cop/layout/space_inside_hash_literal_braces.rb, spec/rubocop/cop/layout/space_inside_hash_literal_braces_spec.rb
I changed `Layout/SpaceInsideHashLiteralBraces` so that it can detect the following pattern as empty Hash literal braces:
```ruby
foo = {
}
foo = {}
```
One reason I think this should be is that `Layout/SpaceInsideArrayLiteralBrackets` already bahaves like this.
```ruby
foo = [
]
foo = []
```
=> Detect empty Hash literal braces containing only newlines and spaces on `Layout/SpaceInsideHashLiteralBraces`

changelog/new_add_autocorrect_for_style_static_class.md, lib/rubocop/cop/style/static_class.rb, spec/rubocop/cop/style/static_class_spec.rb
Bad:
```rb
class SomeClass
def self.some_method
end
class << self
def some_other_method
end
end
end
```
Autocorrect:
1. Change `class` -> `module` and add `module_function`
3. Delete `self.` in method definitions
4. Unwrap `class << self`
```rb
module SomeModule
module_function
def some_method
end
def some_other_method
end
end
```
=> Add autocorrect for `Style/StaticClass`

changelog/fix_fix_an_error_for_redundant_string_escape.md, lib/rubocop/cop/style/redundant_string_escape.rb, spec/rubocop/cop/style/redundant_string_escape_spec.rb
=> [Fix #11089] Fix an error for `Style/RedundantStringEscape` when using character literals (e.g. `?a`)

changelog/fix_an_error_for_style_redundant_string_escape.md, lib/rubocop/cop/style/redundant_string_escape.rb, spec/rubocop/cop/style/redundant_string_escape_spec.rb
This PR fixes the following error for `Style/RedundantStringEscape` cop when using `?\n` string character literal.
```console
?\n
% bundle exec rubocop --only Style/RedundantStringEscape -d
(snip)
An error occurred while Style/RedundantStringEscape cop was inspecting /Users/koic/src/github.com/koic/rubocop-issues/11090/example.rb:1:0.
undefined method `source' for nil:NilClass
delimiters = [node.loc.begin.source[-1], node.loc.end.source[0]]
^^^^^^^
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/redundant_string_escape.rb:162:in `delimiter?'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/redundant_string_escape.rb:110:in `single_quoted?'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/redundant_string_escape.rb:103:in …
```
=> Fix an error for `Style/RedundantStringEscape` cop

docs/modules/ROOT/pages/configuration.adoc
I will add some more description to the documentation about `--no-exclude-limit` option.
- https://github.com/rubocop/rubocop/pull/11036
- https://docs.rubocop.org/rubocop/configuration.html#automatically-generated-configuration
=> Update docs page about `--no-exclude-limit` option

changelog/fix_an_error_when_specifing_suggest_extensions_is_true.md, docs/modules/ROOT/pages/extensions.adoc, lib/rubocop/cli/command/suggest_extensions.rb, spec/rubocop/cli/suggest_extensions_spec.rb
Fixes #11088.
This PR fixes an error when specifying `SuggestExtensions: true`.
It's no wonder users think they can set `SuggestExtensions: true` when they can specify `SuggestExtensions: false`.
So, suggest default extensions if `SuggestExtensions: true`. Anyway, it shouldn't be an error.
=> [Fix #11088] Fix an error when specifying `SuggestExtensions: true`

changelog/fix_an_error_for_style_collection_compact.md, lib/rubocop/cop/style/collection_compact.rb, spec/rubocop/cop/style/collection_compact_spec.rb
Fixes #11104.
This PR fixes an error for `Style/CollectionCompact` when using `reject` method and receiver is a variable.
=> [Fix #11104] Fix an error for `Style/CollectionCompact`

changelog/fix_fix_false_positive_for.md, lib/rubocop/cop/style/redundant_string_escape.rb, spec/rubocop/cop/style/redundant_string_escape_spec.rb
Fix incorrect false-positives for escaped interpolation when escaping the character following the `#` instead of the `#` itself.
=> [Fix #11098] Fix false positive for Style/RedundantStringEscape

changelog/fix_an_error_for_style_access_modifier_declaration.md, lib/rubocop/cop/style/access_modifier_declarations.rb, spec/rubocop/cop/style/access_modifier_declarations_spec.rb
Fixes #11102.
This PR fixes an error for `Style/AccessModifierDeclarations` when using access modifier in a block.
It wouldn't be expected to enforce a style on how it's used as a method call within a block like this:
```ruby
module MyModule
singleton_methods.each { |method| module_function(method) }
end
```
=> [Fix #11102] Fix an error for `Style/AccessModifierDeclarations`

.rubocop.yml, lib/rubocop/cop/internal_affairs.rb, lib/rubocop/cop/internal_affairs/example_heredoc_delimiter.rb, spec/rubocop/cop/bundler/duplicated_gem_spec.rb, spec/rubocop/cop/bundler/gem_comment_spec.rb, spec/rubocop/cop/internal_affairs/example_heredoc_delimiter_spec.rb, spec/rubocop/cop/layout/heredoc_indentation_spec.rb, spec/rubocop/cop/style/documentation_method_spec.rb
In response to the following review comment, I have created a cop to consistently use `RUBY` delimiter for heredocs in cop tests.
- https://github.com/rubocop/rubocop-performance/pull/297#discussion_r930636473
cc: @koic 
=> Add `InternalAffairs/ExampleHeredocDelimiter` cop

changelog/fix_a_false_positive_for_style_operator_method_call.md, lib/rubocop/cop/style/operator_method_call.rb, spec/rubocop/cop/style/operator_method_call_spec.rb
Fixes #11107.
This PR fixes a false positive for `Style/OperatorMethodCall` when a constant receiver uses an operator method.
=> [Fix #11107] Fix a false positive for `Style/OperatorMethodCall`

lib/rubocop/cop/internal_affairs.rb, lib/rubocop/cop/internal_affairs/create_empty_file.rb, spec/rubocop/cli/options_spec.rb, spec/rubocop/cop/internal_affairs/create_empty_file_spec.rb, spec/rubocop/server/cache_spec.rb, spec/rubocop/server/rubocop_server_spec.rb, spec/support/file_helper.rb
This PR adds new `InternalAffairs/CreateEmptyFile` cop. It checks for uses of `create_file` with empty string second argument.
```ruby
create_file(path, '')
create_empty_file(path)
```
=> Add new `InternalAffairs/CreateEmptyFile` cop

changelog/fix_an_error_for_style_operator_method_call.md, lib/rubocop/cop/style/operator_method_call.rb, spec/rubocop/cop/style/operator_method_call_spec.rb
Fixes #11114
This PR fixes an error for `Style/OperatorMethodCall` when using `obj.!`.
=> [Fix #11114] Fix an error for `Style/OperatorMethodCall`

changelog/new_add_option_to_raise_cop_errors.md, docs/modules/ROOT/pages/cops.adoc, docs/modules/ROOT/pages/usage/basic_usage.adoc, lib/rubocop/cop/commissioner.rb, lib/rubocop/options.rb, spec/rubocop/cop/commissioner_spec.rb, spec/rubocop/options_spec.rb
Fix https://github.com/rubocop/rubocop/issues/10977
We want to be able to rescue cop-related errors. 
There exists `:raise_error`, but it's used for internal tests such as through [cop helper](https://github.com/rubocop/rubocop/blob/master/lib/rubocop/rspec/cop_helper.rb#L49). 
I added a new option that raises with `RuboCop::ErrorWithAnalyzedFileLocation`, which surfaces more information. 
=> [Fix #10977] Add option to raise cop errors, `--raise-cop-error`

changelog/fix_a_false_positive_for_block_delimiters.md, lib/rubocop/cop/style/block_delimiters.rb, spec/rubocop/cop/style/block_delimiters_spec.rb
Fixes #11117.
This PR fixes a false positive for `Style/BlockDelimiters` when specifying `EnforcedStyle: semantic` and using a single line block with {} followed by a safe navigation method call.
=> [Fix #11117] Fix a false positive for `Style/BlockDelimiters`

changelog/fix_an_error_for_layout_space_inside_hash_literal.md, lib/rubocop/cop/layout/space_inside_hash_literal_braces.rb, spec/rubocop/cop/layout/space_inside_hash_literal_braces_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/11032#issuecomment-1292304322.
This PR fixes an error for `Layout/SpaceInsideHashLiteralBraces` when using method argument that both key and value are hash literals.
=> Fix an error for `Layout/SpaceInsideHashLiteralBraces`

changelog/new_add_set_to_redundant_require_statement.md, lib/rubocop/cop/lint/redundant_require_statement.rb, spec/rubocop/cop/lint/redundant_require_statement_spec.rb
In Ruby 3.2, `set` will be included by default.
From the Ruby [announcement](https://www.ruby-lang.org/en/news/2022/09/09/ruby-3-2-0-preview2-released/):
> Set is now available as a builtin class without the need for `require "set"`. [[Feature #16989](https://bugs.ruby-lang.org/issues/16989)] It is currently autoloaded via the `Set` constant or a call to `Enumerable#to_set`.
This PR updates `Lint/RedundantRequireStatement` to flag `require "set"` when configured to inspect Ruby 3.2 or higher.
=> Make Lint/RedundantRequireStatement mark set as a redundant require in Ruby 3.2+

changelog/change_report_the_count_of_files_in_the_worst.md, changelog/change_report_the_count_of_files_in_worst_and_offenses.md, lib/rubocop/formatter/offense_count_formatter.rb, lib/rubocop/formatter/worst_offenders_formatter.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cli/options_spec.rb, spec/rubocop/cli_spec.rb, spec/rubocop/formatter/offense_count_formatter_spec.rb, spec/rubocop/formatter/worst_offenders_formatter_spec.rb, spec/rubocop/rake_task_spec.rb
Report the count of files in the Worst and the Offence Counts formatters. Their output now looks like this:
```
4  exe/rubocop
3  spec/spec_helper.rb
2  lib/rubocop.rb
--
9  Total in 3 files
2  CopC
1  CopA
1  CopB
--
4  Total in 1 files
```
=> Report the count of files in the Worst and Offense Count formatters

lib/rubocop/cop/style/collection_compact.rb
- This PR fixes #11066. 
- Essentially, there's a situation that can happen where Rubocop says that `params.reject { |n| ... }` should be replaced with `params.compact`. However, the params object doesn't have an implementation of `compact`. 
- Since `Style/CollectionCompact` is already marked unsafe, the solution here was to update the associated documentation.
* Didn't actually add tests seeing as this is a documentation change, but if y'all have some way to run unit tests against docs lemme know and I'm happy to get that added 😁 
* `"If the new code introduces user-observable changes"` -- I don't believe these changes are user-observable, but am more than happy to add this if it's necessary.
[1]: …
=> [Fix #11066] -- Update Docs for `Style/CollectionCompact`

lib/rubocop/rspec/shared_contexts.rb, lib/rubocop/server/core.rb, spec/rubocop/server/rubocop_server_spec.rb
There seems to be a pretty random test failure on the test 
```
rubocop --server when using `--server` option after updating RuboCop displays a restart information message
```
For instance:
- https://github.com/rubocop/rubocop-ast/actions/runs/3210248983/jobs/5247557361
- https://app.circleci.com/pipelines/github/rubocop/rubocop/7366/workflows/aec22370-2fcf-4b4e-bd91-71c89ef3d638/jobs/242160
I'm unfortunately unable to reproduce locally, so trying to understand a bit more about it
Please let me know if using a PR for that purpose isn't appropriate and if you have alternative suggestions
=> Fix random test failures for server reload behavior

changelog/new_optin_cop_compatibility_in_redundant.md, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop/comment_config.rb, lib/rubocop/cop/lint/missing_cop_enable_directive.rb, lib/rubocop/cop/lint/redundant_cop_disable_directive.rb, lib/rubocop/cop/registry.rb, lib/rubocop/cop/team.rb, lib/rubocop/ext/processed_source.rb, lib/rubocop/rspec/cop_helper.rb, lib/rubocop/runner.rb, spec/rubocop/cli_spec.rb, spec/rubocop/cop/layout/line_end_string_concatenation_indentation_spec.rb, spec/rubocop/cop/lint/missing_cop_enable_directive_spec.rb, spec/rubocop/cop/lint/redundant_cop_disable_directive_spec.rb, spec/rubocop/cop/lint/redundant_cop_enable_directive_spec.rb, spec/rubocop/cop/registry_spec.rb, spec/rubocop/cop/style/parallel_assignment_spec.rb, spec/rubocop/cop/team_spec.rb
Add compatibility in `Lint/RedundantCopDisableDirective`, `Lint/RedundantCopEnableDirective` and `Lint/MissingCopEnableDirective` for opt-in cops.
I mean by "opt-in" having a cop which is globally disabled in the configuration, but that we want to enable only on specific parts of a file.
My use-case specifically is the following: we sometimes have large-ish arrays maintaining list of allowed values for an attribute, let's imagine:
```ruby
allowed_prefixes = %w[
ab_
ad_
bc_
...
zz_
]
```
I wrote a custom cop that checks that this array remains alphabetically sorted for human readibility. Obviously, I don't want to enable it globally in the codebase as array ordering is important in many use-cases, but would like to enable it specifically on that part with:
```ruby
allowed_prefixes = %w[ …
```
=> Opt-in cop compatibility in redundant directives

changelog/new_add_simple_autocorrect_for_style_guard_clause.md, lib/rubocop/cop/style/guard_clause.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cli/options_spec.rb, spec/rubocop/cop/style/guard_clause_spec.rb
This adds autocorrection for `Style/GuardClause`. For example:
```rb
def test
if foo1
return foo2
else
foo3
end
if bar1
bar2
bar3
end
end
```
becomes
```rb
def test
return foo2 if foo1
foo3
return unless bar1
bar2
bar3
end
```
More complex `if-else` statements are not autocorrected and left as-is:
```rb
if foo
bar || return
else
baz
end
```
=> Add simple autocorrect for `Style/GuardClause`

changelog/fix_clobbering_error_on_lint_empty_conditional_body.md, lib/rubocop/cop/lint/empty_conditional_body.rb, spec/rubocop/cop/lint/empty_conditional_body_spec.rb
Fix https://github.com/rubocop/rubocop/issues/11132.
=> [Fix #11132] Fix clobbering error on `Lint/EmptyConditionalBody`

changelog/change_check_newline_in_empty_reference_bracket.md, lib/rubocop/cop/layout/space_inside_reference_brackets.rb, lib/rubocop/cop/mixin/surrounding_space.rb, spec/rubocop/cop/layout/space_inside_reference_brackets_spec.rb
This is the reference bracket version of the following Pull Request:
- https://github.com/rubocop/rubocop/pull/11032
which will add the following rule about newline in empty reference bracket:
```ruby
foo[
]
foo[]
foo[ ]
```
=> Check newline in empty reference bracket on `Layout/SpaceInsideReferenceBrackets`

changelog/fix_an_incorrect_autocorrect_for_lint_redundant_require_statement.md, lib/rubocop/cop/lint/redundant_require_statement.rb, spec/rubocop/cop/lint/redundant_require_statement_spec.rb
Fixes #11120.
This PR fixes an incorrect autocorrect for `Lint/RedundantRequireStatement` when using redundant `require` with modifier form.
For example, in essential it is unknown how many times `do_something` will be executed when `require 'enumerator' while do_something`. So it does not autocorrects when modifier form is used to avoid side effects.
=> [Fix #11120] Fix an incorrect autocorrect for `Lint/RedundantRequireStatement`

changelog/change_module_function-forbidden_msg.md, lib/rubocop/cop/style/module_function.rb, spec/rubocop/cop/style/module_function_spec.rb
**Context:**
``` yml
Style/ModuleFunction:
EnforcedStyle: forbidden
```
When `extend self` or `module_function` is used in this context ⬆️, the cop message might suggest to "_Open the singleton class with `class << self` instead._".
WDYT?
=> Suggest to "Open the singleton class with `class << self`" when `Style/ModuleFunction` is set to `forbidden`

lib/rubocop/cops_documentation_generator.rb
Follow up https://github.com/rubocop/rubocop/pull/11134#issuecomment-1296134804.
This PR uses broken vertical bar as adoc table separator. It specifies `[separator=¦]` for adoc table to prevent broken regexp format. https://docs.asciidoctor.org/asciidoc/latest/tables/data-format/#escape-the-cell-separator
adoc generation is updated as follows:
```diff
% bundle exec rake update_cops_documentation
(snip)
% git diff
(snip)
@@ -587,12 +603,13 @@ EOS
=== Configurable attributes
+[separator=¦]
|===
| Name | Default value | Configurable values
-| ForbiddenDelimiters
-| `(?-mix:(^|\s)(EO[A-Z]{1}|END)(\s|$))`
-| Array
+¦ ForbiddenDelimiters
+¦ `(?-mix:(^|\s)(EO[A-Z]{1}|END)(\s|$))`
+¦ Array
|===
=== References
```
[1]: …
=> Use broken vertical bar as adoc table separator

changelog/change_allow_multiple_elsif_for_style_if_with_boolean_literal_branches.md, lib/rubocop/cop/style/if_with_boolean_literal_branches.rb, spec/rubocop/cop/style/if_with_boolean_literal_branches_spec.rb
Fixes #11006.
This PR allows multiple `elsif` for `Style/IfWithBooleanLiteralBranches`.
I think it's good to allow when multiple `elsif`s are used instead of a new config option. OTOH, if there is only single `elsif`, `elsif` will not exist due to autocorrection. So I think the current behavior can be kept.
=> [Fix #11006] Allow multiple `elsif` for `Style/IfWithBooleanLiteralBranches`

lib/rubocop/cops_documentation_generator.rb
Follow up https://github.com/rubocop/rubocop/pull/11135#issuecomment-1298131681.
This PR fixes `table missing leading separator; recovering automatically` error when runnig `antora --fetch antora-playbook.yml` in the docs.rubocop.org repo.
I've tried some things, but unfortunately `[separator=¦]` doesn't behave as expected. So, this PR escapes `|` with backslash to prevent the regexp `|` is not used as a table separator.
https://github.com/rubocop/docs.rubocop.org
`Configurable attributes` table is broken.
All tables are broken...
All tables (includes `Configurable attributes`) are recovered.
=> Fix `table missing leading separator; recovering automatically`

changelog/fix_style_redundant_each_for_non_chaining.md, lib/rubocop/cop/style/redundant_each.rb, spec/rubocop/cop/style/redundant_each_spec.rb
`Style/RedundantEach` fails for `[1, 2, 3].each` with no method `block_type?` for nil.
And incorrectly detects as offense the following:
```ruby
build_enumerator(outer: [[1, 2, 3].each]).each
```
=> Fix `Style/RedundantEach` for non-chained `each_` calls

docs/modules/ROOT/pages/formatters.adoc
Update the sample output for the Offense Count and the Worst Offenders formatters to match the changes in #11113.
=> [docs] Update sample output for offenses and worst formatters

changelog/fix_fix_a_false_positive_for_style_redundant_each.md, lib/rubocop/cop/style/redundant_each.rb, spec/rubocop/cop/style/redundant_each_spec.rb
=> [Fix #11137] Fix a false positive for `Style/RedundantEach` when using `each` with a symbol proc argument

changelog/change_check_blank_percent_literal.md, lib/rubocop/cop/layout/space_inside_array_percent_literal.rb, lib/rubocop/cop/layout/space_inside_percent_literal_delimiters.rb, spec/rubocop/cop/layout/space_inside_percent_literal_delimiters_spec.rb
Previously, no particular investigation was made for whitespace in blank percent array literals on `Layout/SpaceInsideArrayPercentLiteral`.
I will change it in this Pull Request so that they are inspected as well.
```ruby
%w[ ]
%w[    ]
%w[
]
%w[]
```
This is a similar change to:
- https://github.com/rubocop/rubocop/pull/11032
---
edit: At first I tried to change `Layout/SpaceInsideArrayPercentLiteral` Cop, but after discussion, it was decided to use `Layout/SpaceInsidePercentLiteralDelimiters` Cop instead.
=> Check blank percent literal by `Layout/SpaceInsidePercentLiteralDelimiters`

lib/rubocop/cop/mixin/range_help.rb, lib/rubocop/cop/style/access_modifier_declarations.rb, spec/rubocop/cop/range_help_spec.rb
Add a convenience method in response to the following comment:
- https://github.com/rubocop/rubocop-rails/pull/857#issuecomment-1304315239
=> Add `RuboCop::Cop::RangeHelp#range_with_comments_and_lines`

changelog/fix_styleoperatormethodcall.md, lib/rubocop/cop/style/operator_method_call.rb, spec/rubocop/cop/style/operator_method_call_spec.rb
Ran it in Dext and this little gem of a code...
```ruby
receipt_total = receipt.total_amount.*(convert_rate).round(2)
receipt_vat = receipt.tax_amount.*(convert_rate).round(2)
```
got autocorrected to:
```ruby
receipt_total = receipt.total_amount(*convert_rate.round(2))
receipt_vat = receipt.tax_amount(*convert_rate.round(2))
```
I expected:
```ruby
receipt_total = (receipt.total_amount * convert_rate).round(2)
receipt_vat = (receipt.tax_amount * convert_rate).round(2)
```
The `Style/OperatorMethodCall` didn't autocorrect operator method calls in chaining properly so I made it so.
=> Fix `Style/OperatorMethodCall` autocorrection when operators are chained

changelog/fix_fix_a_false_negative_for_style_hash_each_methods.md, lib/rubocop/cop/style/hash_each_methods.rb, spec/rubocop/cop/style/hash_each_methods_spec.rb
=> [Fix #11139] Fix a false negative for `Style/HashEachMethods` when using each with a symbol proc argument

changelog/change_add_if_to_allowed_names_list.md, config/default.yml
In library development, we sometimes use `if` as a keyword argument.
The meaning of `if` is clear enough so we can accept it as an allowed name.
I'm not sure if it deserves its own CHANGELOG entry, but please let me know if I should add it.
=> Add `if` to allowed names list for MethodParameterName

changelog/fix_a_false_positive_for_style_hash_as_last_array_item.md, lib/rubocop/cop/style/hash_as_last_array_item.rb, spec/rubocop/cop/style/hash_as_last_array_item_spec.rb
Fixes #11161.
This PR fixes a false positive for `Style/HashAsLastArrayItem` when using double splat operator.
=> [Fix #11161] Fix a false positive for `Style/HashAsLastArrayItem`

changelog/change_mark_style_hash_except_as_unsafe.md, config/default.yml, lib/rubocop/cop/style/hash_except.rb
I think it would be better to assume that `Style/HashExcept` is unsafe because it detects and replaces even things that should not be replaced.
For example:
```ruby
invalid_values = [3, 5]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].each_slice(2).reject do |value1, _value2|
invalid_values.include?(value1)
end
#=> [[1, 2], [7, 8], [9, 10]]
```
The above code is currently auto-corrected as follows:
```ruby
invalid_values = [3, 5]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].each_slice(2).except(*invalid_values)
#=> undefined method `except' for #<Enumerator: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:each_slice(2)> (NoMethodError)
```
=> Mark `Style/HashExcept` as unsafe

changelog/change_support_visibility_definition.md, lib/rubocop/cop/mixin/visibility_help.rb, spec/rubocop/cop/layout/class_structure_spec.rb, spec/rubocop/cop/visibility_help_spec.rb
The following patterns have not been supported by `RuboCop::Cop::VisibilityHelp#node_visibility`:
```ruby
class A
private def x
end
end
```
```ruby
class A
def x
end
private :x
end
```
```ruby
node_visibility(def_x_node) #=> :public
```
I think it would be good to support them as well.
The background leading me to this change is as follows:
I am trying to create a Cop that inspects unrecommended visibility of some method definitions. I tried to use the `#node_visibility` for this implementation, but realized that this would not work as intended in this case if inline style visibility was used. There seemed to be no obvious reason not to support it, so I decided to create this Pull Request.
(FYI: In fact, I'm trying to create a cop that detects some public methods in Rails controller that …
=> Support inline visibility definition on checking visibility

changelog/fix_false_positive_for_style_redundant_each.md, lib/rubocop/cop/style/redundant_each.rb, spec/rubocop/cop/style/redundant_each_spec.rb
Follow up https://github.com/faker-ruby/faker/pull/2613#issuecomment-1304316381.
Fixes #11165.
This PR fixes a false positive for `Style/RedundantEach` when any method is used between methods containing `each` in the method name.
That method in between may convert from `Enumerator` to `Array`. e.g. `map(&:do_something)`
```ruby
'string'.each_char.class             # => Enumerator
'string'.each_char.map(&:to_i).class # => Array
```
`each_with_index` is a method of `Array`, not of `Enumerator`.
```ruby
'string'.each_char.map(&:to_i).respond_to?(:each_with_index) # => true
'string'.each_char.map(&:to_i).respond_to?(:with_index)      # => false
```
Therefore, it allows any method to be used between methods containing `each` to prevent `NoMethodError`.
Before submitting the …
=> [Fix #11165] Fix a false positive for `Style/RedundantEach`

changelog/fix_suppress_a_server_mode_message.md, lib/rubocop/server/core.rb, spec/rubocop/server/rubocop_server_spec.rb
Fixes #11164
This PR suppresses "RuboCop server starting..." message with `--server --format json` because JSON format does not expected output message when IDE integration with server mode.
=> [Fix #11164] Suppress a server mode message

changelog/fix_an_incorrect_autocorrect_for_style_class_equality_comparison.md, lib/rubocop/cop/style/class_equality_comparison.rb, spec/rubocop/cop/style/class_equality_comparison_spec.rb
Fixes #11168.
This PR fixes an incorrect autocorrect for `Style/ClassEqualityComparison` when using instance variable comparison in module.
=> [Fix #11168] Fix an incorrect autocorrect for `Style/ClassEqualityComparison`

changelog/new_add_autocorrect_for_layout_line_continuation_leading_space.md, lib/rubocop/cop/layout/line_continuation_leading_space.rb, spec/rubocop/cop/layout/line_continuation_leading_space_spec.rb
Autocorrects
```rb
'this text contains a lot of' \
'               spaces'
```
to
```rb
'this text contains a lot of               ' \
'spaces'
```
[Layout/LineContinuationLeadingSpace](https://docs.rubocop.org/rubocop/cops_layout.html#layoutlinecontinuationleadingspace)
=> Add autocorrect for `Layout/LineContinuationLeadingSpace`

changelog/fix_incorrect_autocorrect_for_style_collection_compact.md, lib/rubocop/cop/style/collection_compact.rb, spec/rubocop/cop/style/collection_compact_spec.rb
Fixes #11173.
This PR fixes an incorrect autocorrect for `Style/CollectionCompact` when using `reject` with block pass arg and no parentheses.
=> [Fix #11173] Fix an incorrect autocorrect for `Style/CollectionCompact`

changelog/fix_auto_correction_bug_for_string_literals.md, lib/rubocop/cop/style/quoted_symbols.rb, lib/rubocop/cop/util.rb, spec/rubocop/cop/style/string_literals_spec.rb
Fix: https://github.com/rubocop/rubocop/issues/11123
Before:
```
a = {
b: "{\"[\\\"*\\\"]\""
}
```
was corrected to:
```
a = {
b: '{"["*"]"'
}
```
These two strings are not the same.
After my changes it should result in correct string:
```
a = {
b: '{"[\"*\"]"'
}
```
=> [Fix #11123 ] Fix auto correction bug for Style/StringLiterals

changelog/fix_improve_redundant_regex_escape_catching.md, lib/rubocop/cop/style/redundant_regexp_escape.rb, spec/rubocop/cop/style/redundant_regexp_escape_spec.rb
Fix: #11150 
It should catch redundant regexp escape when the hyphen is being escaped and at the same time is the first or the last character within the character class.
=> [Fix #11150] Catch redundant hyphen escape within character class

changelog/fix_a_false_positive_for_lint_duplicate_methods.md, lib/rubocop/cop/lint/duplicate_methods.rb, spec/rubocop/cop/lint/duplicate_methods_spec.rb
This PR fixes the following false positive cases for `Lint/DuplicateMethods` when using duplicate nested method.
It prevents false positives in test cases such as:
```ruby
def test_foo
class A
def x
prepare_for_foo
end
end
assert...
end
def test_bar
class A
def x
prepare_for_bar
end
end
assert...
end
```
The above is a false positive found in the rails/rails repository.
Also as an edge case, nested methods may have been intended.
```ruby
def foo
def x
puts 'foo'
end
end
def bar
def x
puts 'bar'
end
end
foo
x #=> foo
bar
x #=> bar
foo
x #=> foo
```
=> Fix a false positive for `Lint/DuplicateMethods`

changelog/fix_a_false_positive_for_style_object_then.md, lib/rubocop/cop/style/object_then.rb, spec/rubocop/cop/style/object_then_spec.rb
`Object#then` was introduced in Ruby 2.6.0, so this cop should target Ruby version 2.6 or later.
- https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/
* no related issue exists. 
=> Fix a false positive for `Style/ObjectThen` cop with TargetRubyVersion < 2.6

changelog/fix_error_for_lint_shadowing_outer_local_variable.md, lib/rubocop/cop/lint/shadowing_outer_local_variable.rb, spec/rubocop/cop/lint/shadowing_outer_local_variable_spec.rb
Fixes #11184.
This PR fixes an error for `Lint/ShadowingOuterLocalVariable` when a block local variable has same name as an outer `until` scope variable.
=> [Fix #11184] Fix an error for `Lint/ShadowingOuterLocalVariable`

changelog/fix_an_error_for_style_if_with_semicolon.md, lib/rubocop/cop/style/if_with_semicolon.rb, spec/rubocop/cop/style/if_with_semicolon_spec.rb
This PR fixes the following error for `Style/IfWithSemicolon` when one using line if/;/end without then boby.
```ruby
if cond; else dont end
```
```console
bundle exec rubocop --only Style/IfWithSemicolon
(snip)
undefined method `source' for nil:NilClass
"#{node.condition.source} ? #{node.if_branch.source} : #{else_code}"
^^^^^^^
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/if_with_semicolon.rb:44:in `autocorrect'
```
=> Fix an error for `Style/IfWithSemicolon`

changelog/fix_a_false_positive_for_guard_clause.md, lib/rubocop/cop/style/guard_clause.rb, spec/rubocop/cop/style/guard_clause_spec.rb
Fixes #11196.
This PR fix a false positive for `Style/GuardClause` when using `raise` in `then` body of `if..elsif..end` form.
It would be unexpected to replace complex conditional forms using `elsif` with modifier form.
=> [Fix #11196] Fix a false positive for `Style/GuardClause`

.rubocop_todo.yml, changelog/change_make_style_hash_syntax_aware_of_without_parentheses_call_expr_follows.md, changelog/fix_an_incorrect_autocorrect_for_style_if_unless_modifier.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, lib/rubocop/cop/mixin/statement_modifier.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/style/hash_syntax_spec.rb, spec/rubocop/cop/style/if_unless_modifier_spec.rb
This PR intentionally separates two commits to resolve #11182.
First, this resolution of #11182 requires a change of `Style/HashSyntax` behavior.
The first change makes `Style/HashSyntax` aware of without parentheses call expr follows. It prepares to prevent `Style/HashSyntax` with `Style/IfUnlessModifier` autocorrection conflicts that resolve #11182.
Previously `Style/HashSyntax` accepted the following syntax to prevent syntax errors:
```ruby
foo bar value: value
baz
```
This avoids the following incompatible syntax:
```ruby
foo bar value:
baz
```
`Style/HashSyntax` registers an offense for:
```ruby
foo bar value: value
baz
```
And the autocorrection adds parentheses to prevent syntax errors shown in the URL:
https://bugs.ruby-lang.org/issues/18396
```ruby
foo bar(value:)
baz
```
By …
=> [Fix #11182] Fix an incorrect autocorrect for `Style/IfUnlessModifier` with `Style/HashSyntax`

changelog/fix_error_for_lint_empty_conditional_body.md, lib/rubocop/cop/lint/empty_conditional_body.rb, spec/rubocop/cop/lint/empty_conditional_body_spec.rb
This PR fixes the following error for `Lint/EmptyConditionalBody` when one using line if/;/end without then boby.
```ruby
if cond; else dont end
```
```console
bundle exec rubocop --stdin example.rb --only Lint/EmptyConditionalBody -d
(snip)
```
=> Fix an error for `Lint/EmptyConditionalBody`

changelog/change_support_multiple_arguments_on.md, lib/rubocop/cop/lint/send_with_mixin_argument.rb, spec/rubocop/cop/lint/send_with_mixin_argument_spec.rb
These mixin methods can take multiple arguments, so these patterns should also be supported in this cop.
- `Module#include`
- `Module#prepend`
- `Object#extend`
=> Support multiple arguments on `Lint/SendWithMixinArgument`

changelog/fix_an_incorrect_autocorrect_for_layout_multiline_method_call_brace_layout.md, lib/rubocop/cop/correctors/multiline_literal_brace_corrector.rb, spec/rubocop/cop/layout/multiline_method_call_brace_layout_spec.rb
Fixes #11200.
This PR fixes an incorrect autocorrect for `Layout/MultilineMethodCallBraceLayout` when using method chain for heredoc argument in multiline literal brace layout.
=> [Fix #11200] Fix an incorrect autocorrect for `Layout/MultilineMethodCallBraceLayout`

lib/rubocop/cop/registry.rb
- This PR fixes https://github.com/rubocop/rubocop/issues/11157.
- `RuboCop::Cop::Cop` is deprecated, so updated to `RuboCop::Cop::Registry`
- Updated to run `qualified_cop_name` on the `registry` as opposed to the array of cops (`RuboCop::Cop::Cop.all`)
- Added `warn` yard documentation 
* Didn't add tests as this is a documentation change
* did not add one - I checked other documentation only PR's and appears it is required for `user-observable changes` 
=> [fix rubocop#11157] -- Update Registry Docs

changelog/fix_redundant_cop_disable_with_departments.md, lib/rubocop/cop/lint/redundant_cop_disable_directive.rb, spec/rubocop/cop/lint/redundant_cop_disable_directive_spec.rb
This is a fix for #11143 and #11160, and the issue was introduced in this Opt-In PR: #10987.
It seems like the current implementation of `RedundantCopDisableDirective` is designed to ignore department-disable comments (based on specs). 
The `RedundantCopDisableDirective` has 2 different reasons to mark a cop disable comment as redundant: it is already disabled, OR there is no reason to disable it since there are no offenses of this type
```
def each_redundant_disable(&block)
cop_disabled_line_ranges.each do |cop, line_ranges|
each_already_disabled(cop, line_ranges, &block)
each_line_range(cop, line_ranges, &block)
end
end
```
The error occurs due to unnecessary cops added in the `each_already_disabled` block. It only happens when we have 2 or more department-disable comments. If we have …
=> [fix #11143] Fix RedundantCopDisableDirective when used with departments

changelog/change_lint_interpolation_check.md, config/default.yml, lib/rubocop/cop/lint/interpolation_check.rb
In this Cop, I think it would be easier to understand to have a simple policy that all `#{...}` in single-quotes are considered offenses, regardless of how they are intended to be written. Given this, it would be nice to set `SafeAutoCorrect: false`, since I don't think there are any false-positives cases under this policy.
What do you think?
=> Change `Lint/InterpolationCheck` from `Safe: false` to `SafeAutoCorrect: false`

changelog/new_add_autocorrect_for_lint_assignment_in_condition.md, config/default.yml, lib/rubocop/cop/lint/assignment_in_condition.rb, spec/rubocop/cop/lint/assignment_in_condition_spec.rb
I think adding support for unsafe autocorrection to `Lint/AssignmentInCondition` would be more useful in some cases. Now that `SafeAutoCorrect: false` allows us to indicate to users that it is unsafe, I don't think we will have much trouble because of this support.
I decided to replace the code as assignment by default in this autocorrection because it does not change the behavior of the current code. If there seem to be many use cases where the behavior of autocorrection needs to be changed, we can add such configuration in this Pull Request or the future change. (In fact, is there any Cop that allows the autocorrection behavior to be switched by configuration in that way?)
Depending on the policy, this type of autocorrection support may not be acceptable in RuboCop. In which case, …
=> Add autocorrect for `Lint/AssignmentInCondition`

lib/rubocop/cop/internal_affairs.rb, lib/rubocop/cop/internal_affairs/lambda_or_proc.rb, lib/rubocop/cop/lint/ambiguous_block_association.rb, lib/rubocop/cop/lint/empty_block.rb, lib/rubocop/cop/style/nil_lambda.rb, spec/rubocop/cop/internal_affairs/lambda_or_proc_spec.rb
Enforces the use of `node.lambda_or_proc?` instead of `node.lambda? || node.proc?`.
```ruby
node.lambda? || node.proc?
node.proc? || node.lambda?
node.lambda_or_proc?
```
=> Add new `InternalAffairs/LambdaOrProc` cop

changelog/change_make_style_redundant_argument_aware_of_array_sum.md, config/default.yml, lib/rubocop/cop/style/redundant_argument.rb, spec/rubocop/cop/style/redundant_argument_spec.rb
This PR makes `Style/RedundantArgument` aware of `Array#sum`.
For example, by omitting the initial value argument of `sum` it could be simply updated by `Style/SymbolProc`.
```ruby
items.sum(0) { |item| item.price }
items.sum(&:price)
```
=> Make `Style/RedundantArgument` aware of `Array#sum`

changelog/change_update_raise_severity_of_some_cops_to_warning.md, config/default.yml
`Bundler` and `RubyGems` are special departments that depend on specific tools (not language) , and some cops belonging to them should be treated as de facto Lints.
So, the following cops below belong to linting, not style preference, make set the severity to warning.
1. The following emulates warnings for deprecated usage:
- `Bundler/InsecureProtocolSource` cop
2. The following suggests incorrect usage of Bundler and RubyGems APIs:
- `Bundler/DuplicatedGem` cop
- `Gemspec/DeprecatedAttributeAssignment` cop
- `Gemspec/DuplicatedAssignment` cop
- `Gemspec/RequiredRubyVersion` cop
- `Gemspec/RubyVersionGlobalsUsage` cop
3. RubyGems strongly recommends MFA, so I think the following cop is equivalent to linting:
- `Gemspec/RequireMFA` cop …
=> Update severity of some `Bundler` and `RubyGems` cops to warning

changelog/new_add_no_auto_gen_enforced_style_cli_option.md, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop/formatter/disabled_config_formatter.rb, lib/rubocop/options.rb, spec/rubocop/cli/auto_gen_config_spec.rb, spec/rubocop/options_spec.rb
This PR is add `--[no-]auto-gen-enforced-style` CLI option.
As a motivation, for a cop that has EnforcedStyle and other options as configurable options, the offense may remain
even if `--auto-gen-cofig` is done.
Normally, this may not be a problem, but there are cases where you want to update RuboCop, and you want to make only updates.
For example, if we do not want to include the newly added cop violations up to the point of fixing them, we can run `rubocop --auto-gen-config` when updating and slowly resolve them later.
The following is a case where `rubocop --auto-gen-config` does not make all offense TODO:
```ruby
a = {
}
```
Run `bundle exec rubocop --auto-gen-config`.
The following TODO configuration file is then created.
```yaml
Layout/SpaceInsideHashLiteralBraces:
EnforcedStyle: …
```
=> Add `--[no-]auto-gen-enforced-style` CLI option

changelog/new_make_style_select_by_regexp_aware_of_doesnt_match.md, lib/rubocop/cop/style/select_by_regexp.rb, spec/rubocop/cop/style/select_by_regexp_spec.rb
Fixes #11219.
This PR makes `Style/SelectByRegexp` aware of `!~` method.
=> [Fix #11219] Make `Style/SelectByRegexp` aware of `!~` method

changelog/change_make_lint_void_aware_of_lambda_and_proc.md, lib/rubocop/cop/lint/void.rb, spec/rubocop/cop/lint/void_spec.rb
This PR makes `Lint/Void` aware of used lambda and proc in void context. e.g.:
```ruby
def foo
-> { bar }
lambda { bar }
proc { bar }
Proc.new { bar }
top
end
```
These blocks of lambdas and procs are never called.
=> Make `Lint/Void` aware of used lambda and proc

changelog/change_add_cc_to_allowednames_of_methodparametername.md, config/default.yml, docs/modules/ROOT/pages/cops_naming.adoc
`cc` is a common method parameter for email-related methods, e.g.:
```ruby
def invitation_email(to:, cc:, subject:)
end
```
=> Add `cc` to `AllowedNames` of `MethodParameterName` cop

.github/workflows/rubocop.yml
Simplify GHA CI setup a little bit.
No user-visible changes.
=> CI: Let ruby/setup-run install gems

changelog/change_safe_navigation_to_handle_ternaries.md, lib/rubocop/cop/style/redundant_sort.rb, lib/rubocop/cop/style/safe_navigation.rb, lib/rubocop/cop/variable_force/assignment.rb, spec/rubocop/cop/style/safe_navigation_spec.rb
Closes #11116.
It handles new ternary cases like:
```ruby
x ? x.foo : nil
x.nil? ? nil : x.foo
!x.nil? ? x.foo : nil
!x ? nil : x.foo
```
=> Handle ternaries in `Style/SafeNavigation`

changelog/fix_an_incorrect_autocorrect_for_lint_safe_navigation_chain.md, lib/rubocop/cop/lint/safe_navigation_chain.rb, spec/rubocop/cop/lint/safe_navigation_chain_spec.rb
Fixes #11230.
This PR fixes an incorrect autocorrect for `Lint/SafeNavigationChain` when using safe navigation with `[]` operator followed method chain.
=> [Fix #11230] Fix an incorrect autocorrect for `Lint/SafeNavigationChain`

changelog/fix_multifile_require_config.md, lib/rubocop/config_loader.rb
This PR fixes loading of configuration files that inherit from other configuration files, which require a gem. This was first documented in https://github.com/rubocop/rubocop/issues/5251.
Locally I used three files for reproduction.
```yaml
inherit_from:
- more-rubocop.yml
RSpec/VariableName:
Enabled: false
AllCops:
NewCops: enable
```
```yaml
require:
```
```ruby
RSpec.describe 'Banana' do
let(:Banana) { '🍌' }
it 'is delicious' do
expect(send(:Banana)).to eq '🍌'
end
end
```
```
.rubocop.yml: RSpec/VariableName has the wrong namespace - should be Naming
C
Offenses:
my_spec.rb:4:7: C: RSpec/VariableName: Use snake_case for variable names.
let(:Banana) { '🍌' }
^^^^^^^
```
This is unexpected:
* the offending cop should …
=> Fix loading of configuration in multi-file edge case

changelog/change_count_as_one_accepts_arguments.md, lib/rubocop/cop/metrics/block_length.rb, lib/rubocop/cop/metrics/class_length.rb, lib/rubocop/cop/metrics/method_length.rb, lib/rubocop/cop/metrics/module_length.rb, lib/rubocop/cop/metrics/utils/code_length_calculator.rb, spec/rubocop/cop/metrics/utils/code_length_calculator_spec.rb
Closes #11070.
With the
```yaml
Metric/MethodLength:
CountAsOne: ['arguments']
```
the following will be counted as 1 line:
```ruby
foo(
1,
2
)
```
=> Add ability to count method arguments as one line to code length related `Metric` cops

changelog/change_remove_respond_to_from_allowed_methods_of_style_symbol_proc.md, config/default.yml, lib/rubocop/cop/style/symbol_proc.rb
The commit below adds `respond_to` to the config, which looks like a Rails method:
https://github.com/rubocop/rubocop/commit/54ff86ec93c270a267eb65879f7f7ab73cc02fb9
Ruby has method called `respond_to?`, not `respond_to`. So `respond_to` is a Rails API and `respond_to?` doesn't take a block argument.
RuboCop core does not depend on Rails, so move the `respond_to` config from RuboCop core to RuboCop Rails.
I noticed this by https://github.com/rubocop/rubocop-rails/issues/779.
This removed setting was added in RuboCop Rails 2.17. Rails application developers can get this change in the upgrade.
https://github.com/rubocop/rubocop-rails/pull/806
=> Remove `respond_to` from default value of `AllowedMethods` for `Style/SymbolProc`

changelog/fix_redundant_department_disable.md, lib/rubocop/cop/lint/redundant_cop_disable_directive.rb, lib/rubocop/cop/registry.rb, lib/rubocop/rspec/cop_helper.rb, spec/rubocop/cop/lint/redundant_cop_disable_directive_spec.rb
Fixes #11213 
The `Registry#disabled?` was not including cops disabled via department config like `Metrics => {'Enabled' => false}` this is why I added a new `Registry#find_cops_by_directive` which also finds cops for given department config (`#find_by_cop_name` ignores it since a department is not a cop).
=> Support redundant department disable in scope of `RedundantCopDisable`

.github/workflows/linting.yml, .github/workflows/rubocop.yml, .github/workflows/spell_checking.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using https://github.com/step-security/secure-workflows.
GitHub recommends defining minimum GITHUB_TOKEN permissions for securing GitHub Actions workflows 
- https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/  
- https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
- The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) treats not setting token permissions as a high-risk issue 
This project is part of the top 100 critical projects as per OpenSSF (https://github.com/ossf/wg-securing-critical-projects), so fixing the token permissions to improve …
=> ci: add GitHub token permissions for workflows

.rubocop.yml, changelog/new_add_stylerequireorder_cop.md, config/default.yml, exe/rubocop, lib/rubocop.rb, lib/rubocop/config_loader.rb, lib/rubocop/config_loader_resolver.rb, lib/rubocop/cop/style/require_order.rb, lib/rubocop/formatter.rb, lib/rubocop/formatter/html_formatter.rb, lib/rubocop/result_cache.rb, lib/rubocop/rspec/support.rb, lib/rubocop/server/core.rb, spec/rubocop/cop/style/require_order_spec.rb, spec/rubocop/rake_task_spec.rb, spec/spec_helper.rb, tasks/cops_documentation.rake
Many projects have `require` and `require_relative` in alphabetical order by convention, the rubocop gem itself being one example. I thought it would be good to have a cop to provide such consistency.
As a good example, rubocop-rspec inspects this with tests. Such checks are replaced by this cop.
- https://github.com/rubocop/rubocop-rspec/blob/v2.15.0/spec/project/project_requires_spec.rb
Like `Bundler/OrderedGems`, code separated by a blank line is considered a different group, so if there are obvious dependencies but you really don't want to write `require_relative` in each file, it is better to separate the groups. lib/rubocop/formatter.rb is a good example of that.
- https://github.com/rubocop/rubocop/blob/v1.39.0/lib/rubocop/formatter.rb#L9-L27
Unfortunately, the dependencies written …
=> Add `Style/RequireOrder` cop

changelog/fix_an_incorrect_autocorrect_for_style_guard_clause.md, lib/rubocop/cop/style/guard_clause.rb, spec/rubocop/cop/style/guard_clause_spec.rb
Fixes #11239.
This PR fixes an incorrect autocorrect for `Style/GuardClause` when using heredoc as an argument of raise in branch body.
Let `Layout/HeredocIndentation`, `Layout/ClosingHeredocIndentation`, and `Layout/IndentationConsistency` cops autocorrect inconsistent indentations.
=> [Fix #11239] Fix an incorrect autocorrect for `Style/GuardClause`

changelog/fix_a_false_negative_for_style_redundant_return.md, lib/rubocop/cop/style/redundant_return.rb, spec/rubocop/cop/style/redundant_return_spec.rb
=> [Fix #11244] Fix a false negative for `Style/RedundantReturn` when dynamic define methods

changelog/new_style_array_intersect_cop.md
s/arra1/array2/
Follow up: https://github.com/rubocop/rubocop/pull/11224
=> Fix a typo for CHANGELOG entry

changelog/fix_fix_an_error_for_guard_clause.md, lib/rubocop/cop/style/guard_clause.rb, spec/rubocop/cop/style/guard_clause_spec.rb
This PR is fix an error for `Style/GuardClause` when a method call whose last argument is not a string is in the condition body
Prepare the following files
```ruby
def foo
if foo?
foo(bar)
end
end
```
Get the following error when running RuboCop
```
bundle exec rubocop test.rb -d
For /ydah/test: configuration from /ydah/test/.rubocop.yml
configuration from /ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-performance-1.15.1/config/default.yml
configuration from /ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-performance-1.15.1/config/default.yml
Default configuration from /ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/config/default.yml
configuration from /ydah/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-rake-0.6.0/config/default.yml …
```
=> Fix an error for `Style/GuardClause` when a method call whose last argument is not a string is in the condition body

index.html
=> Fix links on rubocop.org to reference new GitHub org name

changelog/fix_an_error_for_style_require_order.md, lib/rubocop/cop/style/require_order.rb, spec/rubocop/cop/style/require_order_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/11235#issuecomment-1342934983.
This PR fixes an error for `Style/RequireOrder` when `require` is a method argument.
=> Fix an error for `Style/RequireOrder`

changelog/fix_fix_an_error_for_style_require_order_no_args.md, lib/rubocop/cop/style/require_order.rb, spec/rubocop/cop/style/require_order_spec.rb
=> [Fix #11255] Fix an error for `Style/RequireOrder` when `require` with no arguments is put between `require`

.rubocop_todo.yml, changelog/fix_an_incorrect_autocorrect_for_style_hash_syntax.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, lib/rubocop/options.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
Fixes #11256.
This PR fixes an incorrect autocorrect for `Style/HashSyntax` when without parentheses call expr follows after multiple keyword arguments method call.
=> [Fix #11256] Fix an incorrect autocorrect for `Style/HashSyntax`

lib/rubocop/config.rb, lib/rubocop/cop/badge.rb, lib/rubocop/cop/base.rb, lib/rubocop/cop/lint/redundant_cop_enable_directive.rb, lib/rubocop/cop/registry.rb, lib/rubocop/directive_comment.rb, lib/rubocop/path_util.rb, spec/rubocop/cop/badge_spec.rb, spec/rubocop/cop/cop_spec.rb, spec/rubocop/cop/registry_spec.rb
Tested on Gitlab's `lib/` directory.
Time: `223.3s`
Memory: `1.17 GB (16961837 objects)`
```
Mode: wall(1000)
Samples: 222211 (0.05% miss rate)
GC: 11808 (5.31%)
9497   (4.3%)        9497   (4.3%)     (sweeping)   <========
8099   (3.6%)        8065   (3.6%)     RuboCop::Config#for_cop  <========
13641   (6.1%)        7715   (3.5%)     RuboCop::AST::Descendence#each_child_node
7630   (3.4%)        7630   (3.4%)     block (2 levels) in <class:Node>
11282   (5.1%)        7269   (3.3%)     Parser::Lexer#advance
5510   (2.5%)        5510   (2.5%)     Gitlab::Styles::Rubocop::ModelHelpers#in_model?
9903   (4.5%)        5357   (2.4%)     RuboCop::Cop::Base#cop_config
6016   (2.7%) …
```
=> More rubocop optimizations

CONTRIBUTING.md
This PR is add description of linting YAML files to CONTRIBUTING.md
Ref: https://github.com/rubocop/rubocop/pull/10392
=> Add description of linting YAML files to CONTRIBUTING.md

CONTRIBUTING.md
This PR is fixed missing link in CONTRIBUTING.md.
=> Fixed missing link in CONTRIBUTING.md

changelog/fix_a_false_positive_for_lint_duplicate_methods.md, lib/rubocop/cop/lint/duplicate_methods.rb, spec/rubocop/cop/lint/duplicate_methods_spec.rb
Fixes #11273.
This PR fixes a false positive for `Lint/DuplicateMethods` when there are same `alias_method` name outside `rescue` or `ensure` scopes.
=> [Fix #11273] Fix a false positive for `Lint/DuplicateMethods`

changelog/new_allow_multiline_final_element_option_for_line_breaks_cops.md, config/default.yml, docs/modules/ROOT/pages/cops_layout.adoc, docs/modules/ROOT/partials/cops_layout_footer.adoc, lib/rubocop/cop/layout/first_array_element_line_break.rb, lib/rubocop/cop/layout/first_hash_element_line_break.rb, lib/rubocop/cop/layout/first_method_argument_line_break.rb, lib/rubocop/cop/layout/first_method_parameter_line_break.rb, lib/rubocop/cop/layout/multiline_array_line_breaks.rb, lib/rubocop/cop/layout/multiline_hash_key_line_breaks.rb, lib/rubocop/cop/layout/multiline_method_argument_line_breaks.rb, lib/rubocop/cop/layout/multiline_method_parameter_line_breaks.rb, lib/rubocop/cop/mixin/first_element_line_break.rb, lib/rubocop/cop/mixin/multiline_element_line_breaks.rb, lib/rubocop/cops_documentation_generator.rb, spec/rubocop/cop/layout/first_array_element_line_break_spec.rb, spec/rubocop/cop/layout/first_hash_element_line_break_spec.rb, spec/rubocop/cop/layout/first_method_argument_line_break_spec.rb, spec/rubocop/cop/layout/first_method_parameter_line_break_spec.rb, spec/rubocop/cop/layout/multiline_array_line_breaks_spec.rb, spec/rubocop/cop/layout/multiline_hash_key_line_breaks_spec.rb, spec/rubocop/cop/layout/multiline_method_argument_line_breaks_spec.rb, spec/rubocop/cop/layout/multiline_method_parameter_line_breaks_spec.rb
This add a `AllowMultilineFinalElement` option, that when set to `true` allows the following cops to not consider a statement to be multiline even if the last (or only) element (value, argument or parameter) itself is multiline:
```
FirstArrayElementLineBreak
FirstHashElementLineBreak
FirstMethodArgumentLineBreak
FirstMethodParameterLineBreak
MultilineArrayLineBreaks
MultilineHashKeyLineBreaks
MultilineMethodArgumentLineBreaks
MultilineMethodParameterLineBreaks
```
The goal of this addition is to be able to use `Layout/LineLength` to format each elements on a new line, while not forcing some of the use cases that are considered "ok exceptions" by some people.
```ruby
foo(a, b, bar(
c,
d
))
{ a: b, c: {
foo: bar,
baz: qux,
}}
[ 1, 2, [
foo,
bar,
]]
foo({
a: b,
})
a = { foo: [
bar,
baz,
]} …
```
=> Introduce new AllowMultilineFinalElement option for all __LineBreak(s) cops

changelog/fix_nomethoderror_for_styledocumentation.md, lib/rubocop/cop/style/documentation.rb, spec/rubocop/cop/style/documentation_spec.rb
Style/Documentation raises NoMethodError for the following code:
```ruby
module self::Foo
end
module foo::Bar
end
```
output:
```console
$ rubocop --only Style/Documentation test.rb
An error occurred while Style/Documentation cop was inspecting /tmp/test.rb:1:0.
An error occurred while Style/Documentation cop was inspecting /tmp/test.rb:4:0.
.
2 errors occurred:
An error occurred while Style/Documentation cop was inspecting /tmp/test.rb:1:0.
An error occurred while Style/Documentation cop was inspecting /tmp/test.rb:4:0.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker. …
```
=> Fix NoMethodError for Style/Documentation when a class nested under non-constant values

changelog/fix_an_incorrect_autocorrect_for_style_word_array.md, lib/rubocop/cop/mixin/percent_array.rb, spec/rubocop/cop/style/word_array_spec.rb
Fixes #11284.
This PR fixes an incorrect autocorrect for `Style/WordArray` when assigning `%w()` array.
=> [Fix #11284] Fix an incorrect autocorrect for `Style/WordArray`

changelog/fix_fix_base_dir_in_target_finder_find_files.md, lib/rubocop/target_finder.rb, spec/rubocop/target_finder_spec.rb
`dir` variable in `TargetFinder#find_files()` doesn't exist:
```
undefined local variable or method `dir' for 
```
I think it was just a misprint.
=> Fix `base_dir` in `TargetFinder#find_files()`

changelog/fix_an_error_for_non_atomic_file_operation.md, lib/rubocop/cop/lint/non_atomic_file_operation.rb, spec/rubocop/cop/lint/non_atomic_file_operation_spec.rb
This PR fixes the following error for `Lint/NonAtomicFileOperation` when use file existence checks line break `unless` by postfix before creating file.
```ruby
FileUtils.mkdir(path) unless
FileTest.exist?(path)
```
```console
% bundle exec rubocop example.rb --only Lint/NonAtomicFileOperation -d
(snip)
Expected a Parser::Source::Range, Comment or RuboCop::AST::Node, got NilClass
/Users/koic/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/corrector.rb:91:in `to_range'
/Users/koic/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.40.0/lib/rubocop/cop/corrector.rb:100:in `check_range_validity'
```
=> Fix an error for `Lint/NonAtomicFileOperation`

changelog/fix_correctly_detect_rails_version.md, lib/rubocop/config.rb, spec/rubocop/target_ruby_spec.rb
The rails gem is a metapackage that [only contains the readme, license file](https://github.com/rails/rails/blob/main/rails.gemspec#L21) and a list of dependencies (including railties). The [railties gem](https://rubygems.org/gems/railties/) exists since Rails 3.0 and [contains the code](https://github.com/rails/rails/blob/main/railties/railties.gemspec#L20) that actually ties Rails together.
Apps requiring a subset of Rails in their Gemfile (eg skipping Action Cable/Text/Mailbox but keeping the rest) will have railties in their Gemfile.lock but not rails. The setup looks a bit like this:
```ruby
rails_version = ["~> 7.0.3", ">= 7.0.3.1"]
gem "activesupport", rails_version
gem "actionpack", rails_version
gem "actionview", rails_version
gem "activemodel", rails_version
gem "activerecord", …
```
=> Correctly detect Rails version when using only parts of the framework

bin/rubocop-profile
Previously, it was just dumping a lot of the lines into the stdout making it hard to work with.
=> Print `memory_profiler` report to the file

changelog/fix_safe_navigation_chain_brackets_then_method_chain.md, lib/rubocop/cop/lint/safe_navigation_chain.rb, spec/rubocop/cop/lint/safe_navigation_chain_spec.rb
Fixes #11298.
It shrinks an offenses range a bit, but this makes a cop much simpler, imo. Is this a problem?
=> Fix `Lint/SafeNavigationChain` to correctly handle `[]` operator followed by save navigation and method chain

lib/rubocop/config_loader.rb
Presently, extensions (e.g. [rubocop-rspec](https://github.com/rubocop/rubocop-rspec/blob/63908ab48fad95e08c4e0dc21073a716cb91d06c/lib/rubocop/rspec/inject.rb#L8), [rubocop-rails](https://github.com/rubocop/rubocop-rails/blob/f94b23596821f80c861e6632807a959dbc306aab/lib/rubocop/rails/inject.rb#L8)) all include a similar piece of code, that is [called from their entry point](https://github.com/rubocop/rubocop-rspec/blob/63908ab48fad95e08c4e0dc21073a716cb91d06c/lib/rubocop-rspec.rb#L43).
This change would allow getting rid of this common code and streamline `config/default.yml` injection:
```ruby
require_relative 'rubocop/cop/capybara_cops'
project_root = File.join(__dir__, '..')
RuboCop::ConfigLoader.inject_defaults!(project_root)
```
:warning: no docs, no tests, no changelog entry - I …
=> Allow extensions inject their defaults

changelog/fix_fix_an_error_for_style_require_order_modifier_conditional.md, lib/rubocop/cop/style/require_order.rb, spec/rubocop/cop/style/require_order_spec.rb
=> [Fix #11267] Fix an error for Style/RequireOrder when modifier conditional is used between `require`

changelog/fix_false_negative_for_style_documentation.md, lib/rubocop/cop/style/documentation.rb, lib/rubocop/formatter.rb, spec/fixtures/html_formatter/expected.html, spec/fixtures/markdown_formatter/expected.md, spec/rubocop/cop/style/documentation_spec.rb, tasks/spec_runner.rake
Fixes #11293.
This PR fixes a false negative for `Style/Documentation` when using custom macro.
The built-in macros (e.g. `include`, `extend`, `prepend`) and DSL like `belongs_to` should be treated differently. Only `include`, `extend`, and `prepend` will be needed to resolve #8788.
=> [Fix #11293] Fix a false negative for `Style/Documentation`

changelog/fix_fix_an_error_for_style_guard_clause.md, lib/rubocop/cop/style/guard_clause.rb, spec/rubocop/cop/style/guard_clause_spec.rb
Follow up: https://github.com/rubocop/rubocop/pull/11250#issuecomment-1359051959
=> Fix an error for `Style/GuardClause` when using lvar as an argument of raise in `else` branch

changelog/fix_a_false_positive_for_style_redundant_string_escape.md, lib/rubocop/cop/style/redundant_string_escape.rb, spec/rubocop/cop/style/redundant_string_escape_spec.rb
Fixes #11309.
This PR fixes a false positive for `Style/RedundantStringEscape` when using a redundant escaped string interpolation `\#\{foo}`.
=> [Fix #11309] Fix a false positive for `Style/RedundantStringEscape`

changelog/fix_block_forwarding_reassignments.md, lib/rubocop/cop/naming/block_forwarding.rb, spec/rubocop/cop/naming/block_forwarding_spec.rb
Fixes #11313.
`node_parts[0]` is a name of a local variable.
=> Fix a false positive for `Naming/BlockForwarding` when the block argument is reassigned

changelog/fix_disabling_departments_via_comment.md, lib/rubocop/cop/lint/redundant_cop_disable_directive.rb
Fixes #11308.
This is a solution as in a similar from this cop - https://github.com/rubocop/rubocop/blob/8bb0c47e7a654a72dcfb7024083cbb4898cae03d/lib/rubocop/cop/lint/redundant_cop_disable_directive.rb#L127
I was not able to reproduce it on an existing app, only on a sample new app (as mentioned in the issue description).
Was not able to create a failing test script for this too.
=> Fix disabling departments via comment

lib/rubocop/cop/layout/class_structure.rb, lib/rubocop/cops_documentation_generator.rb
Resolve: https://github.com/rubocop/rubocop-rspec/issues/772
=> Add support `@see` tags in our document

changelog/fix_fix_a_false_positive_for_style_alias.md, lib/rubocop/cop/style/alias.rb, spec/rubocop/cop/style/alias_spec.rb
The following cases will result in a NoMethodError if replaced with alias_method.
Therefore, it is correct to regard it as a violation and not to replace it.
```ruby
def foo
alias :ala :bala
end
```
=> Fix a false positive for `Style/Alias`cop when alias in a method def

changelog/fix_false_positive_for_lint_require_parentheses.md, lib/rubocop/cop/lint/require_parentheses.rb, spec/rubocop/cop/lint/require_parentheses_spec.rb
Fixes #11320.
This PR fixes a false positive for `Lint/RequireParentheses` when assigning ternary operator.
=> [Fix #11320] Fix a false positive for `Lint/RequireParentheses`

changelog/fix_a_false_negative_for_lint_redundant_cop_disable_directive.md, lib/rubocop/runner.rb, spec/rubocop/cli/options_spec.rb
Fixes #11204.
This PR fixes a false negative for `Lint/RedundantCopDisableDirective` when using `--except` command line option.
=> [Fix #11204] Fix a false negative for `Lint/RedundantCopDisableDirective`

changelog/change_make_style_zero_length_predicate_aware_of_zero.md, lib/rubocop/cop/style/block_comments.rb, lib/rubocop/cop/style/zero_length_predicate.rb, spec/rubocop/cop/style/zero_length_predicate_spec.rb
Closes #11314.
Follow https://github.com/rubocop/rubocop/issues/11314#issuecomment-1362982236.
This PR makes `Style/ZeroLengthPredicate` aware of `array.length.zero?`.
I'm not sure if `array.any?` is better than `array.length.positive` as answered in #11314.
But `array.length == 0` and `array.length.zero?` are equivalent, it should be possible to convert to `array.emtpy?` in the same way.
=> Make `Style/ZeroLengthPredicate` aware of `array.length.zero?`

changelog/fix_require_order_for_require_inside_rescue.md, lib/rubocop/cop/style/require_order.rb, spec/rubocop/cop/style/require_order_spec.rb
For the following code
```ruby
begin
rescue
require "foo"
end
```
I got
```
undefined method `if_type?' for nil:NilClass
node.if_type? && !node.modifier_form?
^^^^^^^^^
rubocop/lib/rubocop/cop/style/require_order.rb:102:in `not_modifier_form?'
rubocop/lib/rubocop/cop/style/require_order.rb:121:in `sibling_node'
rubocop/lib/rubocop/cop/style/require_order.rb:107:in `block in find_previous_older_sibling'
rubocop/lib/rubocop/cop/style/require_order.rb:106:in `each'
rubocop/lib/rubocop/cop/style/require_order.rb:106:in `find'
rubocop/lib/rubocop/cop/style/require_order.rb:106:in `find_previous_older_sibling'
rubocop/lib/rubocop/cop/style/require_order.rb:87:in `on_send'
rubocop/lib/rubocop/cop/commissioner.rb:137:in `public_send'
```
`Node#left_siblings` returns all (sibling) children of the …
=> Fix an error for `Style/RequireOrder` when using `require` inside `rescue` body

changelog/fix_class_structure_freezed_consts_and_public_class_methods.md, lib/rubocop/config.rb, lib/rubocop/cop/base.rb, lib/rubocop/cop/cop.rb, lib/rubocop/cop/corrector.rb, lib/rubocop/cop/layout/class_structure.rb, lib/rubocop/cop/metrics/utils/abc_size_calculator.rb, lib/rubocop/cop/registry.rb, lib/rubocop/cop/style/trailing_comma_in_arguments.rb, lib/rubocop/cop/team.rb, lib/rubocop/target_ruby.rb, spec/rubocop/cop/layout/class_structure_spec.rb, tasks/changelog.rb
This PR fixes 2 problems:
1. Previously, rubocop hasn't correctly detected and autocorrected class methods (as you can see from the 2nd commit), because of the misspelling.
2. Simple `.freeze` constants are considered as "dynamic constants" and are ignored from the consideration. Changed that.
This PR also fixes #8034.
As a follow up to this, I will extend this cop to be able to detect private constants and class methods, to avoid having disables like https://github.com/rubocop/rubocop/blob/20b32e434160716d07182d512be6da3d8ba96d71/lib/rubocop/cop/base.rb#L330-L333 - that constant is used in the method that follows and makes sense to keep it near that method (not at the top as `Layout/ClassStructure` currently suggests, thats why `# rubocop:disable`).
=> Accept simple freezed constants in `Layout/ClassStructure` and correctly handle class methods

changelog/change_concat_array_literals_support_autocorrection_for_percent_literals.md, lib/rubocop/cop/style/concat_array_literals.rb, spec/rubocop/cop/style/concat_array_literals_spec.rb
Fixes #11325.
`%W`/`%I` literals with interpolations inside are skipped for autocorrection, because they are rare and could further complicate this cop's logic. Other cases are pretty common.
=> Support autocorrection for percent literals in `Style/ConcatArrayLiterals`

changelog/fix_space_around_keyword_accept_super_within_ranges.md, lib/rubocop/cop/layout/space_around_keyword.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/layout/space_around_keyword_spec.rb
Fixes #8751.
For the following
```ruby
1..super
```
An infinite loop is detected:
```
Infinite loop detected in snippet.rb and caused by Layout/SpaceAroundKeyword -> Layout/SpaceInsideRangeLiteral
rubocop/lib/rubocop/runner.rb:311:in `check_for_infinite_loop'
rubocop/lib/rubocop/runner.rb:294:in `block in iterate_until_no_changes'
rubocop/lib/rubocop/runner.rb:293:in `loop'
rubocop/lib/rubocop/runner.rb:293:in `iterate_until_no_changes'
```
=> Accept `super` within ranges for `Layout/SpaceAroundKeyword` cop

changelog/fix_identical_conditional_branches_ignore_empty_left_branches.md, lib/rubocop/cop/style/identical_conditional_branches.rb, spec/rubocop/cop/style/identical_conditional_branches_spec.rb
Fixes #10858.
We should ignore branches with identical leading lines, if any of them has only one child and the whole `if`/`case`/etc is used in return contexts, like
```ruby
def method
if something
foo
else
foo
bar
end
end
```
because otherwise it will be changed to
```ruby
def method
foo
if something
else
bar
end
end
```
and incorrectly return `nil` when `something` is truthy, instead of the value of `foo` (as before).
=> Fix `Style/IdenticalConditionalBranches` to ignore identical leading lines when branch has single child and is used in return context

changelog/fix_error_for_style_guard_clause.md, lib/rubocop/cop/style/guard_clause.rb, spec/rubocop/cop/style/guard_clause_spec.rb
This PR fixes the following error for `Style/GuardClause` when using heredoc as an argument of raise in `then` branch and it does not have `else` branch:
```ruby
def func
if condition
raise <<~MESSAGE
oops
MESSAGE
end
end
```
```console
% bundle exec rubocop --only Style/GuardClause -d
(snip)
An error occurred while Style/GuardClause cop was inspecting /Users/koic/src/github.com/koic/rubocop-issues/guard_clause/example.rb:1:0.
undefined method `source_range' for nil:NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/guard_clause.rb:209:in `autocorrect_heredoc_argument'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/guard_clause.rb:191:in `autocorrect'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/guard_clause.rb:179:in `block in …
```
=> Fix an error for `Style/GuardClause`

changelog/new_allow_inherit_from_to_accept_a_glob.md, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop/config_loader_resolver.rb, lib/rubocop/path_util.rb, spec/rubocop/config_loader_spec.rb
This PR allows `inherit_from` to accept a glob.
I ran benchmarks on `rails` to determine if this change causes a performance regression.
This reflects the basic startup time of Rubocop to process configurations and resolve inheritance.
```
real    0m1.325s
real    0m1.260s
real    0m1.255s
real    0m1.293s
real    0m1.241s
real    0m1.240s
real    0m1.220s
real    0m1.147s
real    0m1.168s
real    0m1.211s
```
```
real    0m1.164s
real    0m1.213s
real    0m1.203s
real    0m1.200s
real    0m1.126s
real    0m1.198s
real    0m1.194s
real    0m1.191s
real    0m1.199s
real    0m1.200s
```
No change.
This reflects overall rubocop execution time.
```
real    0m3.245s …
```
=> Allow inherit_from to accept a glob

changelog/change_class_structure_to_ignore_private_constants.md, lib/rubocop/cop/base.rb, lib/rubocop/cop/layout/class_structure.rb, lib/rubocop/cop/mixin/annotation_comment.rb, lib/rubocop/cop/variable_force.rb, lib/rubocop/target_ruby.rb, spec/rubocop/cop/layout/class_structure_spec.rb
Follow up to https://github.com/rubocop/rubocop/pull/11329.
Closes https://github.com/rubocop/rubocop/issues/8366.
Example: often times we need to have a constant to act like a cache (see autocorrected changes in this PR) and it makes sense to make it private and keep it near the method that uses it. Rubocop suggests to move it to the top, which is not much useful. 
The same probably needs to be done for private class methods, as they are currently incorrectly considered as "public class methods". But we need to decide where to place them in the class hierarchy (after the public class methods, or before private instance methods, or ...)?
=> Ignore private constants in `Layout/ClassStructure` cop

changelog/fix_false_positive_style_redundant_string_escape.md, lib/rubocop/cop/style/redundant_string_escape.rb, spec/rubocop/cop/style/redundant_string_escape_spec.rb
Fixes #11346.
This PR fixes a false positive for `Style/RedundantStringEscape` when using escaped space in heredoc.
=> [Fix #11346] Fix a false positive for `Style/RedundantStringEscape`

changelog/fix_error_for_style_select_by_regexp.md, lib/rubocop/cop/style/select_by_regexp.rb, spec/rubocop/cop/style/select_by_regexp_spec.rb
This PR fixes the following error for `Style/SelectByRegexp` when block body is empty:
```ruby
array.select { }
```
```console
% bundle exec rubocop --only Style/SelectByRegexp -d
(snip)
An error occurred while Style/SelectByRegexp cop was inspecting /Users/koic/src/github.com/koic/rubocop-issues/empty_body/example.rb:1:0.
undefined method `begin_type?' for nil:NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/select_by_regexp.rb:89:in `on_send'
```
=> Fix an error for `Style/SelectByRegexp`

.circleci/config.yml
Ruby 3.2.0 has been released and this Ruby version is available on `cimg/ruby:3.2` image.
- https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
- https://circleci.com/developer/en/images/image/cimg/ruby
=> CircleCI against Ruby 3.2

changelog/fix_false_positive_for_style_method_def_parentheses.md, lib/rubocop/cop/style/method_def_parentheses.rb, spec/rubocop/cop/style/method_def_parentheses_spec.rb
Fixes #11361
This PR fixes a false positive for `Style/MethodDefParentheses` when using `EnforcedStyle: require_no_parentheses` and Ruby 3.2's anonymous rest and keyword rest arguments.
=> [Fix #11361] Make `Style/MethodDefParentheses` aware of anonymous rest and keyword rest args

docs/modules/ROOT/pages/configuration.adoc
In the existing example, the `.gitignore` lines would not be properly translated to something rubocop understands:
given the following setup in gitignore:
```
node_modules/**/*
```
The `git` command outputs `!! node_modules/`
result:
```
Exclude:
- node_modules/
```
However rubocop needs `- node_modules/**/*` to actually ignore, this change makes the documentation more immediately useful. I have crossed out the below tasks I thought weren't needed in a documentation change of this type.
* ~[ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).~
* ~[ ] Squashed related commits together.~
* ~[ ] Added tests.~
* ~[ ] Ran `bundle exec rake default`. It executes all tests and runs …
=> Docs: Make example code for ERB parsing function as expected

changelog/fix_an_incorrect_autocorrect_for_lint_regexp_as_condition.md, lib/rubocop/cop/lint/regexp_as_condition.rb, spec/rubocop/cop/lint/regexp_as_condition_spec.rb
This PR fixes the following incorrect autocorrect for `Lint/RegexpAsCondition` when using regexp literal with bang:
```ruby
if !/foo/ =~ $_ =~ $_
end
```
```console
% be rubocop --only Lint/RegexpAsCondition -a
(snip)
Offenses:
example.rb:1:5: W: [Corrected] Lint/RegexpAsCondition: Do not use regexp literal as a condition. The regexp literal matches $_ implicitly.
if !/foo/
^^^^^
```
```diff
% git diff .
diff --git a/regexp_as_condition/example.rb b/regexp_as_condition/example.rb
index 3cb37b3..6f925a3 100644
--- a/regexp_as_condition/example.rb
+++ b/regexp_as_condition/example.rb
@@ -1,2 +1,2 @@
-if !/foo/
+if !/foo/ =~ $_ =~ $_
end
```
[1]: …
=> Fix an incorrect autocorrect for `Lint/RegexpAsCondition`

lib/rubocop/cop/lint/unused_method_argument.rb, spec/rubocop/cli/disable_uncorrectable_spec.rb, spec/rubocop/cop/lint/unused_method_argument_spec.rb
Closes https://github.com/rubocop/rubocop/issues/11322
=> [Fix #11322] Fix message for Lint/UnusedMethodArgument

changelog/change_out_of_range_regexp_ref_pattern_matching.md, lib/rubocop/cop/lint/out_of_range_regexp_ref.rb, spec/rubocop/cop/lint/out_of_range_regexp_ref_spec.rb
Closes #10976.
Note: This is the first time I familiarized myself with the pattern matching in ruby, so be a little more careful when reviewing this PR.
=> Support pattern matching for `Lint/OutOfRangeRegexpRef` cop

changelog/new_add_new_style_yoda_expression_cop.md, config/default.yml, lib/rubocop.rb, lib/rubocop/cli.rb, lib/rubocop/cop/corrector.rb, lib/rubocop/cop/layout/multiline_block_layout.rb, lib/rubocop/cop/metrics/perceived_complexity.rb, lib/rubocop/cop/style/yoda_expression.rb, lib/rubocop/result_cache.rb, spec/rubocop/cop/corrector_spec.rb, spec/rubocop/cop/style/yoda_expression_spec.rb, spec/rubocop/formatter/progress_formatter_spec.rb, spec/rubocop/formatter/tap_formatter_spec.rb
Closes #9222.
Considerations:
1. I excluded `*` from the checked binary operators, as it looks fine for me both ways: `1000 * milliseconds` vs `milliseconds * 1000`.
2. I check only for integer values, because of the same reason as above: `0.8 + 0.2 * count` vs `0.2 * count + 0.8`.
3. This cop only forbids yoda expressions. Should it be able to enforce it?
4. When forbiding, which edge cases we should ignore? 
5. Etc.
=> Add new `Style/YodaExpression` cop

changelog/fix_word_array_to_accept_2d_arrays.md, lib/rubocop/cop/style/word_array.rb, spec/rubocop/cop/style/word_array_spec.rb
Fixes #10194.
Should we check for more than 2 dimensions?
=> Accept bracketed arrays within 2d arrays containing subarrays with complex content for `Style/WordArray` cop

rubocop.gemspec
https://github.com/rubocop/rubocop-ast/pull/249 was released in `1.24.1`.
=> Update `rubocop-ast` to include performance improvements

lib/rubocop/cop/style/word_array.rb
Follow up to https://github.com/rubocop/rubocop/pull/11334#issuecomment-1368177758.
=> Add examples for 2d arrays to `Style/WordArray` cop

lib/rubocop/cop/style/min_max_comparison.rb
Follow up https://github.com/rubocop/rubocop/issues/11338#issuecomment-1366406576.
This PR adds mention of the following to the doc of `Style/MinMaxComparison` based on the above discussion:
> NOTE: It can be used if you want to present limit or threshold in Ruby 2.7+.
> That it is slow though. So autocorrection will apply generic `max` or `min`:
>
> ```ruby
> a.clamp(b..) # Same as `[a, b].max`
> a.clamp(..b) # Same as `[a, b].min`
> ```
=> [Doc] Update the doc for `Style/MinMaxComparison`

LICENSE.txt, README.md, docs/modules/ROOT/pages/about/license.adoc
This PR bumps license years to 2023.
Happy New Year 🎉 
=> Bump license years to 2023

lib/rubocop/cop/style/word_array.rb, spec/rubocop/cop/style/word_array_spec.rb
In https://github.com/rubocop/rubocop/pull/11334, I introduced a bug for nested arrays 😐
```ruby
[['one', 'One'], 2, 3]
```
```
Failure/Error: parent.values.any? { |subarray| complex_content?(subarray.values) }
NoMethodError:
undefined method `values' for s(:int, 2):RuboCop::AST::IntNode
Did you mean?  value
```
=> Fix `Style/WordArray` for subarrays

changelog/fix_an_error_for_lint_useless_ruby2_keywords.md, lib/rubocop/cop/lint/useless_ruby2_keywords.rb, spec/rubocop/cop/lint/useless_ruby2_keywords_spec.rb
This PR fixes the following error for `Lint/UselessRuby2Keywords` when using `Proc#ruby2_keywords`.
```ruby
block = proc { |_, *args| klass.new(*args) }
block.ruby2_keywords if block.respond_to?(:ruby2_keywords
```
```console
% bundle exec rubocop --only Lint/UselessRuby2Keywords -d
(snip)
An error occurred while Lint/UselessRuby2Keywords cop was inspecting /Users/koic/src/github.com/koic/rubocop-issues/ruby2_keywords/example.rb:2:0.
undefined method `def_type?' for nil:NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/lint/useless_ruby2_keywords.rb:80:in `on_send'
```
=> Fix an error for `Lint/UselessRuby2Keywords`

changelog/fix_an_error_for_style_string_hash_keys.md, lib/rubocop/cop/style/string_hash_keys.rb, spec/rubocop/cop/style/string_hash_keys_spec.rb
This PR fixes the following error for `Style/StringHashKeys` when using invalid symbol in encoding UTF-8 as keys.
```ruby
{ "Test with malformed utf8 \251" => 'test-with-malformed-utf8' }
```
```console
% bundle exec rubocop --only Style/StringHashKeys -d
(snip)
An error occurred while Style/StringHashKeys cop was inspecting /Users/koic/src/github.com/koic/rubocop-issues/style_string_hash_keys/example.rb:1:2.
invalid symbol in encoding UTF-8 :"Test with malformed utf8 \xA9"
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/string_hash_keys.rb:47:in `to_sym'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/string_hash_keys.rb:47:in `block in on_pair'
```
[1]: …
=> Fix an error for `Style/StringHashKeys`

changelog/fix_fix_operatormethodcall_when_forwarding.md, lib/rubocop/cop/style/operator_method_call.rb, spec/rubocop/cop/style/operator_method_call_spec.rb
`...` cannot be used as an argument to an operator, so it should not be an offense. For example,
```ruby
def m(...) = obj.==(...)
```
would be autocorrected as
```ruby
def m(...) = obj ==(...)
```
which is a syntax error, as would be
```ruby
def m(...) = obj == (...)
```
and
```ruby
def m(...) = obj == ...
```
---
Closes #11377
=> Fix `OperatorMethodCall` when forwarding arguments

changelog/change_require_parser_3_2_0_0.md, docs/modules/ROOT/pages/compatibility.adoc, rubocop.gemspec
Ruby 3.2 and Parser 3.2.0.0 have been released.
- https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
- https://rubygems.org/gems/parser/versions/3.2.0.0
This PR requires Parser 3.2.0.0 or higher and removes "experimental" label from support matrix.
=> Require Parser 3.2.0.0 or higher

spec/tasks/changelog_spec.rb, tasks/changelog.rb
Small convenience to avoid editing the generated file name.
Before:
```
▶ bundle exec rake changelog:new
Entry 'changelog/new_add_new_lintuselessrescue_cop.md' created and added to git index
```
After:
```
▶ bundle exec rake changelog:new
Entry 'changelog/new_add_new_lint_useless_rescue_cop.md' created and added to git index
```
=> Improve generated changelog filenames

changelog/change_require_unicode_display_width_2_4_0.md, rubocop.gemspec
Context - https://github.com/rubocop/rubocop/pull/11373#discussion_r1059767728.
The new version of `unicode-display_width` gem was just released.
=> Require `unicode-display_width` 2.4.0 or higher

lib/rubocop/path_util.rb
Optimized for a case when the project has many offenses (for example, when the rubocop was run for the first time).
Time: `278.3s`
```
Mode: wall(1000)
Samples: 277552 (0.26% miss rate)
GC: 20278 (7.31%)
28670  (10.3%)       15972   (5.8%)     Parser::Lexer#advance
12764   (4.6%)       12764   (4.6%)     Parser::Source::Buffer#slice
11578   (4.2%)       11578   (4.2%)     Unicode::DisplayWidth.of  <========
10336   (3.7%)       10336   (3.7%)     (sweeping)
9762   (3.5%)        9762   (3.5%)     (marking)
11572   (4.2%)        8778   (3.2%)     Parser::Source::Buffer#line_index_for_position
16685   (6.0%)        6799   (2.4%)     RuboCop::AST::Descendence#each_child_node …
```
=> Optimize `ClangStyleFormatter`

changelog/change_disable_style_yoda_expression_by_default.md, config/default.yml, lib/rubocop/cop/style/yoda_expression.rb
Follow https://github.com/rubocop/rubocop/pull/11333#issuecomment-1369486444
This PR disables `Style/YodaExpression` by default to respect user intentions such as:
```ruby
config.server_port = 9000 + ENV["TEST_ENV_NUMBER"].to_i
```
=> Disable `Style/YodaExpression` by default

changelog/fix_a_false_positive_for_style_operator_method_call.md, lib/rubocop/cop/style/operator_method_call.rb, spec/rubocop/cop/style/operator_method_call_spec.rb
This PR fixes a false positive for `Style/OperatorMethodCall` when using anonymous forwarding.
A similar case to #11378. It adds tests for anonymous block forwarding, anonymous rest arguments forwarding, and anonymous keyword rest argument forwarding to pass.
=> Fix a false positive for `Style/OperatorMethodCall`

.rubocop_todo.yml, changelog/fix_an_incorrect_autocorrect_for_style_hash_syntax.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
Fixes #11390.
This PR fixes an incorrect autocorrect for `Style/HashSyntax` when hash first argument key and hash value only are the same which has a method call on the next line.
=> [Fix #11390] Fix an incorrect autocorrect for `Style/HashSyntax`

changelog/fix_an_incorrect_autocorrect_for_style_redundant_double_splat_hash_braces.md, lib/rubocop/cop/style/redundant_double_splat_hash_braces.rb, spec/rubocop/cop/style/redundant_double_splat_hash_braces_spec.rb
Fixes https://github.com/testdouble/standard/issues/505.
This PR fixes an incorrect autocorrect for `Style/RedundantDoubleSplatHashBraces` using double splat in double splat hash braces.
=> Fix an incorrect autocorrect for `Style/RedundantDoubleSplatHashBraces`

changelog/fix_an_error_for_redundant_regexp_escape.md, lib/rubocop/cop/style/redundant_regexp_escape.rb, spec/rubocop/cop/style/redundant_regexp_escape_spec.rb
In https://github.com/rubocop/rubocop/pull/11152 i added catching of redundant hyphen escape within character class.
It [turned out](https://github.com/rubocop/rubocop/issues/11180) this can cause `SyntaxError` due to the corrected Regexp when it is provided using `%r{...}` literal.
=> [Fix rubocop#11180] Fix `Style/RedundantRegexpEscape` bug when regexp provided within `%r{...}` literal

changelog/fix_bad_offense_for_parenthesised_calls.md, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
In `omit_parentheses` style of `Style/MethodCallWithArgsParentheses` we issued an offense for code like this:
```ruby
[
Stat.new("Users Today") do
^^^^^^^^^^^^^^^ Omit parentheses for method calls with arguments.
User.today.count
end,
Stat.new("Servers Today") do
^^^^^^^^^^^^^^^^^ Omit parentheses for method calls with arguments.
Server.today.count
end
]
```
The problem here is that removing the parentheses leads invalid Ruby, and we should allow them:
```ruby
[
Stat.new "Users Today" do
User.today.count
end,
Stat.new "Servers Today" do
Server.today.count
end
]
```
We have a check that allows parentheses in calls in literals but we missed the case for the calls with attached blocks.
=> Fix bad offense for parenthesised calls in literals

changelog/fix_undefined_method_range_between.md, lib/rubocop/cop/mixin/statement_modifier.rb, spec/support/condition_modifier_cop.rb
Fixes https://github.com/rubocop/rubocop/issues/11405
* [x ] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [ x] Wrote [good commit messages][1].
=> [Fix #11405] Fix Style/WhileUntilModifier with ruby 3.1

changelog/fix_an_error_for_hash_syntax.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
For something like
```ruby
hash[cache_key] = { repository: repository }
cache_key
```
I got
```
Parser::Source::Range: end_pos must not be less than begin_pos
/Users/fatkodima/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.2.0.0/lib/parser/source/range.rb:39:in `initialize'
rubocop/lib/rubocop/cop/mixin/range_help.rb:37:in `new'
rubocop/lib/rubocop/cop/mixin/range_help.rb:37:in `range_between'
rubocop/lib/rubocop/cop/mixin/hash_shorthand_syntax.rb:52:in `block in register_offense'
rubocop/lib/rubocop/cop/base.rb:363:in `correct'
rubocop/lib/rubocop/cop/base.rb:181:in `add_offense'
rubocop/lib/rubocop/cop/mixin/hash_shorthand_syntax.rb:50:in `register_offense'
rubocop/lib/rubocop/cop/mixin/hash_shorthand_syntax.rb:43:in `on_pair'
```
The bug was introduced in …
=> Fix an error for `Style/HashSyntax` when expression follows hash key assignment

changelog/fix_make_style_hash_each_methods_aware_of_thread_current.md, config/default.yml, lib/rubocop/cop/style/hash_each_methods.rb, spec/rubocop/cop/style/hash_each_methods_spec.rb
Fixes #8990.
This PR makes `Style/HashEachMethods` aware of built-in `Thread.current`. And `Thread.current` is set to `AllowedReceivers` by default that can be specified for method calls.
=> [Fix #8990] Make `Style/HashEachMethods` aware of `Thread.current`

changelog/fix_a_false_positive_for_style_hash_syntax.md, lib/rubocop/cop/style/hash_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
Fixes #11409.
This PR fixes an incorrect autocorrect for `Style/HashSyntax` when using hash value omission and `EnforcedStyle: no_mixed_keys`.
=> [Fix #11409] Fix an incorrect autocorrect for `Style/HashSyntax`

changelog/change_make_metrics_parameter_lists_aware_of_struct_new_and_data_define.md, lib/rubocop/cop/metrics/parameter_lists.rb, spec/rubocop/cop/metrics/parameter_lists_spec.rb
Fixes #11303.
This PR makes `Metrics/ParameterLists` aware of `Struct.new` and `Data.define` blocks.
The number of these `initialize` arguments depends on the number of arguments of `Struct.new` and `Data.define`, so it wouldn't make sense as a metrics.
One abandoned design, the number of `initialize` argument will check no more than the number of `Struct.new` and `Data.define` arguments. However, considering a special case that the `keyword_init` parameter can be included in the number, I think there is no much benefit for the complexity of the design.
So this PR chooses an approach that doesn't always check for the number of `initialize` arguments.
=> [Fix #11303] Make `Metrics/ParameterLists` aware of `Struct.new` and `Data.define` blocks

changelog/new_add_autocorrect_for_style_missing_else.md, lib/rubocop/cop/style/missing_else.rb, spec/rubocop/cop/style/missing_else_spec.rb
If the enforced style for [`EmptyElse`](https://docs.rubocop.org/rubocop/cops_style.html#styleemptyelse) is `empty`, `MissingElse` is autocorrected like so:
```rb
if cond; foo end
if cond; foo else; nil; end
```
If the enforced style is `nil`:
```rb
if cond; foo end
if cond; foo else; end
```
No corrections are made if the enforced style is `both`
=> Add autocorrect for `Style/MissingElse`

lib/rubocop/rspec/expect_offense.rb
Recommend `expect_no_corrections` if no corrections are expected, not if no corrections are made.
=> Improve error messages for `expect_correction`.

.github/workflows/linting.yml, .github/workflows/rubocop.yml, .github/workflows/spell_checking.yml
~~This reverts commit bf6ea9bd153d33d9e5e263c8c7f584b9314b646a.~~
~~This reverts the setting introduced in #11402.~~
When multiple commits continue, the workflow that wants to know the outcome is also canceled, like this: https://github.com/rubocop/rubocop/actions
~~That "GitHub Actions concurrency" way, if CI has a failing commit, we don't know where it failed on CI. I think this risk reduction should be taken over GitHub Actions concurrency in this repository. There may be repositories where this is useful, but at least not in this repository.~~
To reduce this risk, apply GitHub Actions concurrency only to `pull_requests` events:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
Before submitting the PR …
=> Apply concurrency for GHA workflow `pull_requests` envents only

changelog/fix_a_false_negative_for_methods_that_take_a_block_in_void_context.md, lib/rubocop/cop/lint/void.rb, spec/rubocop/cop/lint/void_spec.rb
Co-authored-by: Ryan Quanz <ryan.quanz@shopify.com>
Co-authored-by: Anderson Sequera <anderson.sequera@shopify.com>
`Lint/Void` cop detects nonmutating methods that act in a void context and marks them as an offence. Prior to this PR, if those methods took a block the cop would fail to detect the offence; this PR fixes those false negatives.
=> Fix a false negative on `Lint/Void`

changelog/fix_a_false_positive_for_lint_useless_rescue.md, lib/rubocop/cop/lint/useless_rescue.rb, spec/rubocop/cop/lint/useless_rescue_spec.rb
Fixes #11420.
This PR fixes a false positive for `Lint/UselessRescue` when using exception variable in `ensure` clause.
=> [Fix #11420] Fix a false positive for `Lint/UselessRescue`

changelog/fix_a_false_positive_for_lint_useless_method_definition.md, lib/rubocop/cop/lint/useless_method_definition.rb, spec/rubocop/cop/lint/useless_method_definition_spec.rb
Fixes #11415.
This PR fixes a false positive for `Lint/UselessMethodDefinition` when method definition contains rest arguments.
=> [Fix #11415] Fix a false positive for `Lint/UselessMethodDefinition`

changelog/fix_a_false_positive_for_style_method_call_with_args_parentheses.md, lib/rubocop/cop/style/method_call_with_args_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
Fixes #11418.
This PR fixes a false positive for `Style/MethodCallWithArgsParentheses` when using anonymous rest arguments or anonymous keyword rest arguments.
These parentheses are always required because omitting them would result in either a semantic change or a syntax error.
=> [Fix #11418] Fix a false positive for `Style/MethodCallWithArgsParentheses`

changelog/fix_value_omissions_in_super.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
Invocation to `super` were not covered by the special cases of value omissions that method calls have.
We ended up with a bad autocorrection in a super invocation. We got:
```ruby
return super current_user, primary: primary unless condition
```
autocorrected to:
```ruby
return super current_user, primary: unless condition
```
The code above is invalid Ruby. If we apply them method call edge cases to super invocations we end up with valid Ruby.
=> Apply value omission exceptions in super invocations

changelog/fix_an_infinite_loop_error_for_layout_block_end_newline.md, lib/rubocop/cop/layout/block_end_newline.rb, spec/rubocop/cop/layout/block_end_newline_spec.rb
Fixes #11430.
This PR fixes an infinite loop error for `Layout/BlockEndNewline`. when multiline blocks with newlines before the `; end`. Below is a minimal reproduction:
```ruby
test do
foo
; end
```
```ruby
% bundle exec rubocop -a --only Layout/BlockEndNewline
(snip)
Offenses:
example.rb:3:3: C: [Corrected] Layout/BlockEndNewline: Expression at 3, 3 should be on its own line.
; end
^^^
Infinite loop detected in /Users/koic/src/github.com/koic/rubocop-issues/11430/example.rb and caused by Layout/BlockEndNewline
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/runner.rb:311:in `check_for_infinite_loop'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/runner.rb:294:in `block in iterate_until_no_changes'
``` …
=> [Fix #11430] Fix an infinite loop error for `Layout/BlockEndNewline`

tasks/changelog.rb
Not a big deal, but a small convenience.
When generating a changelog entry for https://github.com/rubocop/rubocop/pull/11432, it was truncated to just `new_add_new.md`. 
Looking at the existing `changelog/` intries lengths, I think we can increase this limit.
=> Increase generated changelog entry's length

changelog/fix_a_crash_in_style_hash_syntax.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
The crash used to happen when an offense is registered in method receiving hash literals. Here is real world example that results in a crash inside RuboCop:
```ruby
attributes = {account: account, integ_name: shop_name, primary_integ_id: primary_integ_id}.merge attributes
```
The crash was:
```
undefined method `pairs' for s(:lvar, :attributes):RuboCop::AST::Node
corrector.insert_after(last_argument, ')') if node == last_argument.pairs.last
^^^^^^^^^^^^^
```
=> Fix a crash in Style/HashSyntax

changelog/fix_an_incorrect_autocorrect_for_style_min_max_comparison.md, lib/rubocop/cop/style/min_max_comparison.rb, spec/rubocop/cop/style/min_max_comparison_spec.rb
=> [Fix #11439] Fix an incorrect autocorrect for `Style/MinMaxComparison` when using `a < b a : b` with `elsif/else`

changelog/fix_an_error_for_style_access_modifier_declarations.md, lib/rubocop/cop/style/access_modifier_declarations.rb, spec/rubocop/cop/style/access_modifier_declarations_spec.rb
This PR fixes an error for `Style/AccessModifierDeclarations` when access modifier is inlined with a method on the top level:
```ruby
private def foo
end
```
```console
% bundle exec rubocop --only Style/AccessModifierDeclarations -d
(snip)
An error occurred while Style/AccessModifierDeclarations cop was inspecting /Users/koic/src/github.com/koic/rubocop-issues/access_modifier/example.rb:1:0.
undefined method `each_child_node' for nil:NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/access_modifier_declarations.rb:176:in `find_argument_less_modifier_node'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/access_modifier_declarations.rb:189:in `insert_def'
```
[1]: …
=> Fix an error for `Style/AccessModifierDeclarations`

changelog/fix_a_false_positive_for_style_redundant_require_statemen.md, lib/rubocop/cop/lint/redundant_require_statement.rb, spec/rubocop/cop/lint/redundant_require_statement_spec.rb
Fixes #11419.
This PR fixes a false positive for `Style/RedundantRequireStatement` when using `pretty_inspect`.
It also fixes false positives for similar method usage.
=> [Fix #11419] Fix a false positive for `Style/RedundantRequireStatement`

changelog/fix_an_incorrect_autocorrect_for_style_block_delimiters.md, lib/rubocop/cop/style/block_delimiters.rb, spec/rubocop/cop/style/block_delimiters_spec.rb
Fixes #11445.
This PR fixes an incorrect autocorrect for `Style/BlockDelimiters` when there is a comment after the closing brace and bracket.
=> [Fix #11445] Fix an incorrect autocorrect for `Style/BlockDelimiters`

lib/rubocop/cop/layout/space_inside_array_literal_brackets.rb
The author forgot to delete it in https://github.com/rubocop/rubocop/pull/11054.
=> Remove stale TODO

changelog/fix_a_false_positive_for_lint_shadowing_outer_local_variable.md, lib/rubocop/cop/variable_force.rb, spec/rubocop/cop/lint/shadowing_outer_local_variable_spec.rb
Fixes #11444.
This PR fixes a false positive for `Lint/ShadowingOuterLocalVariable` when using numbered block parameter.
It also fixes the following error as a side effect:
```ruby
array.each {
bar = _1
}.each { |bar|
}
```
```console
% bundle exec rubocop example.rb --only Lint/ShadowingOuterLocalVariable -d
(snip)
Scanning /Users/koic/src/github.com/koic/rubocop-issues/11448/example.rb
An error occurred while VariableForce cop was inspecting /Users/koic/src/github.com/koic/rubocop-issues/11448/example.rb.
undefined method `when_type?' for nil:NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/lint/shadowing_outer_local_variable.rb:86:in `variable_node'
```
[1]: …
=> [Fix #11444] Fix a false positive for `Lint/ShadowingOuterLocalVariable`

changelog/new_make_metrics_block_nesting_aware_of_pattern_matching.md, lib/rubocop/cop/metrics/block_nesting.rb, spec/rubocop/cop/metrics/block_nesting_spec.rb
This PR makes `Metrics/BlockNesting` aware of pattern matching.
=> Make `Metrics/BlockNesting` aware of pattern matching

changelog/fix_make_lint_useless_ruby2_keywords_aware_of.md, lib/rubocop/cop/lint/useless_ruby2_keywords.rb, spec/rubocop/cop/lint/useless_ruby2_keywords_spec.rb
The following code is not flagged yet:
```ruby
def foo(**args)
end
ruby2_keywords :foo if respond_to?(:ruby2_keywords, true)
```
This PR fixes this issue.
Real world example: https://gitlab.com/gitlab-org/gitlab/-/blob/4598296ccc6d31414dd22d288882603d23a12296/config/initializers/6_labkit_middleware.rb#L13. Discovered during enabling this rule in https://gitlab.com/gitlab-org/ruby/gems/gitlab-styles/-/merge_requests/160.
=> Make `Lint/UselessRuby2Keywords` aware of conditions

changelog/fix_a_false_negative_for_lint_format_parameter_mismatch.md, lib/rubocop/cop/lint/format_parameter_mismatch.rb, spec/rubocop/cop/lint/format_parameter_mismatch_spec.rb
This PR is fix a false negative for `Lint/FormatParameterMismatch` when include interpolated string.
=> Fix a false negative for `Lint/FormatParameterMismatch` when include interpolated string

changelog/fix_an_error_for_style_operator_method_call.md, lib/rubocop/cop/style/operator_method_call.rb, spec/rubocop/cop/style/operator_method_call_spec.rb
Fixes #11460.
This PR fixes an error for `Style/OperatorMethodCall` when using `foo.> 42`.
=> [Fix #11460] Fix an error for `Style/OperatorMethodCall`

changelog/fix_a_false_negative_for_style_method_call_without_args_parentheses.md, lib/rubocop/cop/style/method_call_without_args_parentheses.rb, spec/rubocop/cop/style/method_call_without_args_parentheses_spec.rb
Fixes #11467.
This PR fixes a false negative for `Style/MethodCallWithoutArgsParentheses` when calling method on a receiver and assigning to a variable with the same name.
=> [Fix #11467] Fix a false negative for `Style/MethodCallWithoutArgsParentheses`

changelog/fix_value_omissions_in_yield_invocations.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
I #11428, I have tried to fix the value omission syntax in `super` invocations. I have missed `yield` invocations too. They can have value omissions too.
=> Fix value omissions in `yield` invocations

.rubocop.yml
Here and there are error reports that some cop fails on an empty file. The latest of them - https://github.com/rubocop/rubocop-minitest/issues/225. Some of the cops already have test cases for empty files, but it is tedious to write them and very often just forgotten.
So I added an empty file into the project so that cops (at least which are not disabled) are always tested (implicitly) on an empty file.
I think, we should add a similar file to the `test/` directory of the `rubocop-minitest` gem and somewhere to the `rubocop-rails` too.
=> Add intentionally empty file to implicitly test cops on it

changelog/change_make_style_semicolon_aware_of_semicolon_in_block.md, lib/rubocop/cop/style/semicolon.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/style/semicolon_spec.rb
This PR makes `Style/Semicolon` aware of redundant semicolon in block.
=> Make `Style/Semicolon` aware of redundant semicolon in block

lib/rubocop/cop/lint/void.rb, spec/rubocop/cop/lint/void_spec.rb
Using `map` in a void context can either be replaced with `map!` if mutation of the underlying object is desired, or with `each` when it is only being invoked for the side effects produced by a block passed in.
This PR updates the cop to suggest `each` in instead of `map!`.
Fixes https://github.com/rubocop/rubocop/issues/8270
Fixes https://github.com/rubocop/rubocop/issues/4305
Fixes https://github.com/rubocop/rubocop/issues/1052
=> Suggest `each` when `map` or `collect` is used in void context

changelog/fix_crash_with_super_value_omission_followed_by_a.md, spec/rubocop/cop/style/hash_syntax_spec.rb
I #11428, I have tried to fix the value omission syntax in `super` calls. Ironically, I have also introduced a crash for code like the following:
```ruby
super value: value
foo z
```
This case requires parentheses, because it's invalid with value omission but without parentheses. It should be autocorrected to:
```ruby
super(value:)
foo z
```
However, the code that handles value omissions followed by code afterwards making it require parentheses didn't expect to get location produced by keyword nodes.
In #11428, I have changed the `def_node_that_require_parentheses` method to return `super` nodes, along the other method dispatch nodes with types of `send` and `csend`. This created an issue, because `super` returns a `Parser::Source::Map::Keyword` instance for its `#location`. …
=> Fix crash with `super value_omission:` followed by a method call

changelog/new_make_lint_deprecated_class_methods_aware_of_obsoleted_attr.md, lib/rubocop/cop/lint/deprecated_class_methods.rb, spec/rubocop/cop/lint/deprecated_class_methods_spec.rb
Fixes #11350.
This PR make `Lint/DeprecatedClassMethods` aware of deprecated `attr` with boolean 2nd argument. This method was already deprecated in Ruby 1.9. And it also doesn't seem to be deprecated when not using boolean 2nd argument.
=> [Fix #11350] Make `Lint/DeprecatedClassMethods` aware of deprecated `attr` method

lib/rubocop/config_loader.rb
This PR removes old Pysch code because Ruby 2.5 runtime support already dropped.
```console
% ruby -ryaml -ve 'p Psych::VERSION'
ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-darwin19]
"3.0.2"
% ruby -ryaml -ve 'p Psych::VERSION'
ruby 2.6.10p210 (2022-04-12 revision 67958) [x86_64-darwin19]
"3.1.0"
% ruby -ryaml -ve 'p Psych::VERSION'
jruby 9.3.9.0 (2.6.8) 2022-10-24 537cd1f8bc Java HotSpot(TM) 64-Bit Server VM 25.271-b09 on 1.8.0_271-b09 +jit [x86_64-darwin]
"3.3.4
```
And it removes redundant `permitted_symbols` keyword parameter (`[]` by default) from `YAML.safe_load`.
=> Remove obsolete code for Psych

changelog/fix_an_error_when_using_yaml_alias_with_server_mode.md, lib/rubocop/server/cache.rb, spec/rubocop/server/cache_spec.rb
Fixes #11477.
This PR fixes an error when using YAML alias with server mode. YAML alias should be allowed as well as non server mode.
=> [Fix #11477] Fix an error when using YAML alias with server mode

changelog/change_change_to_not_output_not_configured_warning.md, lib/rubocop/config_loader.rb, lib/rubocop/cop/registry.rb, spec/rubocop/config_loader_spec.rb
This PR is change to not output not configured warning when renamed and pending cop.
Resolve: https://github.com/rubocop/rubocop-rspec/issues/1561
This will help eliminate some of the confusion that occurred when we extracted from the Capybara section of RuboCop RSpec to RuboCop Capybara.
RuboCop RSpec 2.18.0 renamed and extracted cop still pending in RuboCop Capybara section.
`RSpec/Capybara/FooCop` -> `Capybara/FooCop`.
If we have the following .rubocop.yml.
```yaml
require:
- rubocop-capybara
Capybara/MatchStyle:
Enabled: true
Capybara/NegationMatcher:
Enabled: true
Capybara/SpecificActions:
Enabled: true
Capybara/SpecificFinders:
Enabled: true
Capybara/SpecificMatcher:
Enabled: true
```
If we run RuboCop in this state, we will get the following warning:
```
The …
```
=> Change to not output not configured warning when renamed and pending cop

changelog/new_add_gemspec_development_dependencies_cop.md, config/default.yml, lib/rubocop.rb, lib/rubocop/cop/gemspec/development_dependencies.rb, spec/rubocop/cop/gemspec/development_dependencies_spec.rb
This cop checks that development dependencies are specified in `Gemfile` rather than `gemspec`. It also supports `EnforcedStyle: gems.rb`, which behaves the same way, but mentions `gems.rb` in the error message, or `EnforcedStyle: gemspec`, which inverts the check and enforces that all dependencies be specified in the gemspec file.
An `AllowedGems` config is also included, for projects that want to include some gems in their gemspec. For example, Rubocop itself specifies
```ruby
s.add_development_dependency 'bundler'
```
but specifies all other development dependencies in `Gemfile`.
* ~Commit message starts with `[Fix #issue-number]` (if the related issue exists)~.
=> Add `Gemspec/DevelopmentDependencies` cop

lib/rubocop/cop/lint/mixed_regexp_capture_types.rb
This PR is add @example tag for `Lint/MixedRegexpCaptureTypes` in document.
=> Add @example tag for `Lint/MixedRegexpCaptureTypes` in document

lib/rubocop/cop/lint/heredoc_method_call_position.rb
This PR is fix an indentation for `Lint/HeredocMethodCallPosition` cop's documentation.
=> Fix an indentation for `Lint/HeredocMethodCallPosition` cop's documentation

changelog/fix_a_false_positive_for_lint_format_paramater_mismatch.md, lib/rubocop/cop/lint/format_parameter_mismatch.rb, spec/rubocop/cop/lint/format_parameter_mismatch_spec.rb
This PR is Follow up: https://github.com/rubocop/rubocop/pull/11464#issuecomment-1400880819
=> Fix a false positive for `Lint/FormatParameterMismatch` when format string is only interpolated string

changelog/fix_a_false_positive_for_lint_useless_assignment.md, lib/rubocop/cop/variable_force/variable_table.rb, spec/rubocop/cop/lint/useless_assignment_spec.rb
Fixes #11485.
This PR fixes a false positive for `Lint/UselessAssignment` when using numbered block parameter.
=> [Fix #11485] Fix a false positive for `Lint/UselessAssignment`

changelog/fix_an_error_for_lint_void.md, lib/rubocop/cop/lint/void.rb, spec/rubocop/cop/lint/void_spec.rb
Fixes #11492.
This PR fixes an error for `Lint/Void` when configuring `CheckForMethodsWithNoSideEffects: true`.
=> [Fix #11492] Fix an error for `Lint/Void`

config/default.yml, spec/rubocop/cli/auto_gen_config_spec.rb, spec/rubocop/cli_spec.rb, spec/rubocop/config_loader_spec.rb
This PR is fix to remove obsolete option in default.yml
Fix: https://github.com/rubocop/rubocop-rails/pull/902/files#r1086061881
We have taken the same action with RuboCop RSpec and have confirmed that it works as well, even with the obsolete configuration.
Ref: https://github.com/rubocop/rubocop-rspec/pull/1411#issuecomment-1279255691
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUT …
=> Remove obsolete option in default.yml

changelog/change_allow_initialize_method_in_sytle_documentation_method.md, lib/rubocop/cop/style/documentation_method.rb, spec/rubocop/cop/style/documentation_method_spec.rb
Fixes #11504.
This PR makes to allow `initialize` method in `Style/DocumentationMethod` because `initialize` is a special method called from `new`. In some languages they are called constructor to distinguish it from method.
So it would be different from the following intent that this cop wants to detect.
> Checks for missing documentation comment for public methods.
> It can optionally be configured to also require documentation for
> non-public methods.
=> [Fix #11504] Allow `initialize` method in `Style/DocumentationMethod`

changelog/fix_a_false_positive_for_style_redundant_condition.md, lib/rubocop/cop/style/redundant_condition.rb, spec/rubocop/cop/style/redundant_condition_spec.rb
Fixes #11503.
This PR fixes a false positive for `Style/RedundantCondition` when using method argument with operator.
It fixes false positives that produce syntax errors in addition to the cases reported in #11503.
=> [Fix #11503] Fix a false positive for `Style/RedundantCondition`

changelog/fix_a_false_positive_for_style_operator_method_call.md, lib/rubocop/cop/style/operator_method_call.rb, spec/rubocop/cop/style/operator_method_call_spec.rb
Fixes #11508.
This PR fixes a false positive for `Style/OperatorMethodCall` when using multiple arguments for operator method.
=> [Fix #11508] Fix a false positive for `Style/OperatorMethodCall`

changelog/fix_a_false_negative_for_heredoc_delimiter_naming.md, config/default.yml
This PR fix a false negative for `Naming/HeredocDelimiterNaming` when using lowercase. (e.g. `End`)
=> Fix a false negative for `Naming/HeredocDelimiterNaming`

changelog/fix_a_crash_on_lint_useless_assignment.md, lib/rubocop/cop/variable_force/scope.rb, spec/rubocop/cop/lint/useless_assignment_spec.rb
The crash is:
```
TypeError:
no implicit conversion from nil to integer
```
it happened for nodes like:
```
s(:numblock,
s(:send,
s(:begin,
s(:irange,
s(:int, 0),
s(:int, 10))), :each), 1,
s(:op_asgn,
s(:lvasgn, :checksum_total), :+,
s(:send,
s(:send,
s(:lvar, :checksum_multiplier_by_position), :[],
s(:lvar, :_1)), :*,
s(:send,
s(:send,
s(:lvar, :contact_tax_number), :[],
s(:lvar, :_1)), :to_i))))
```
=> Fix a crash on Lint/UselessAssignment

changelog/change_make_lint_debugger_aware_of_some_debug_methods.md, config/default.yml
Fixes #11517.
This PR makes `Lint/Debugger` aware of `p`, `PP.pp`, and `pp` methods. These are used for debugging purposes basically. OTOH, `puts` is not included in the config because it is used for the intended standard output.
=> [Fix #11517] Make `Lint/Debugger` aware of some debug methods

lib/rubocop/config_loader_resolver.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/bundler/duplicated_gem_spec.rb, spec/rubocop/cop/bundler/gem_comment_spec.rb, spec/rubocop/cop/cop_spec.rb
This PR is intended to fix a bug for how relative paths are calculated for configuration created from using `inherit_from` with a child `.rubocop.yml`.
See https://github.com/rubocop/rubocop/pull/11260#discussion_r1064169254 for more information.
cc @jonas054 
=> Have `fix_include_path` make paths relative to Dir.pwd

lib/rubocop/cop/layout/space_inside_array_literal_brackets.rb, lib/rubocop/cop/layout/space_inside_reference_brackets.rb, lib/rubocop/cop/layout/space_inside_string_interpolation.rb, lib/rubocop/cop/mixin/surrounding_space.rb
Pass pre-filtered tokens instead of looking up left and right tokens in all processed tokens. This avoids scanning the whole (and potential huge) `processed_source.tokens` list over and over again.
`empty_brackets?` popped up in stack profile when investigating performance of RuboCop at GitLab. See https://gitlab.com/gitlab-org/gitlab/-/issues/377469#note_1130358088.
This commit improves performance when inspecting files in rubocop repository. The runtime drops from 62s seconds to 59s when running `bundle exec bin/rubocop-profile`. The offended method `empty_brackets?` disappears in the stack profile from the top 100 (`stackprof --limit 100 tmp/stackprof.dump`).
Runtime: 62.5s
```
Mode: wall(1000)
Samples: 62473 (0.01% miss rate)
GC: 2846 (4.56%) …
```
=> Speed up `empty_brackets?`

changelog/fix_parentheses_in_shorthand_hash_syntax_as.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
Previously, `Style/HashSyntax` would autocorrect the code:
```ruby
raise Errors.new 'No!', foo: foo
```
to 👇:
```ruby
raise Errors.new 'No!', foo:
```
While it may lead to valid code _in this case_, parentheses around `Error.new` are required in edge cases like condition that we can inline to a modifier form after we apply the shorthand hash syntax.
In this example:
```ruby
if condition?
raise Error.new 'A long error message...', foo: foo
end
```
we would autocorrect to invalid Ruby code:
```ruby
raise Error.new 'A long error message...', foo: if condition?
```
Putting parentheses in method calls that return value as an argument in another call is the safest autocorrection in this case. I'm starting to wonder whether we always put the parentheses in them method calls as it's generally …
=> Fix missing parentheses in shorthand hash syntax as argument calls

changelog/fix_a_false_negative_for_style_yoda_condition.md, lib/rubocop/cop/layout/space_around_keyword.rb, lib/rubocop/cop/style/yoda_condition.rb, lib/rubocop/server/client_command/exec.rb, spec/rubocop/cop/style/yoda_condition_spec.rb
Fixes #11511.
This PR fixes a false negative for `Style/YodaCondition` when using constant.
Yoda conditions targets constant but only handles literal. This patch makes constant aware.
=> [Fix #11511] Fix a false negative for `Style/YodaCondition`

changelog/fix_a_false_negative_for_style_yoda_expression.md, lib/rubocop/cop/style/yoda_expression.rb, spec/rubocop/cop/style/yoda_expression_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/11512#issuecomment-1408044549.
This PR fixes a false negative for `Style/YodaExpression` when using constant.
=> Fix a false negative for `Style/YodaExpression`

changelog/fix_don_t_default_keyword_arguments_in.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
This PR fixes the following false positive for :policeman: `Style/ArgumentsForwarding` with `AllowOnlyRestArgument: false`:
```ruby
def migrate_in(*args, coordinator: coordinator_for_tracking_database)
with_migration_context do
coordinator.perform_in(*args)
end
end
```
It was flagged with:
```
lib/gitlab/database/migrations/background_migration_helpers.rb:203:24: C: [Correctable] Style/ArgumentsForwarding: Use arguments forwarding.
def migrate_in(*args, coordinator: coordinator_for_tracking_database)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/gitlab/database/migrations/background_migration_helpers.rb:205:36: C: [Correctable] Style/ArgumentsForwarding: Use arguments forwarding.
coordinator.perform_in(*args)
^^^^^
```
When auto-corrected, the default argument is dropped which …
=> Don't flag default keyword arguments in `Style/ArgumentsForwarding`

CHANGELOG.md, changelog/fix_a_crash_on_lint_useless_assignment.md, spec/project_spec.rb
This PR adds a spec to `project_spec.rb` to make sure that all used cop names in upcoming changelog entries (in `changelog/`) have valid cop names with backticks.
This is to anticipate review comments like https://github.com/rubocop/rubocop/pull/11522#pullrequestreview-1276590353.
This PR also fixes changelog entries in `CHANGELOG.md` starting with `1.0.0` to also use valid cop names with backticks. Note, that `CHANGELOG.md` is not checked in `project_spec.rb` because it should not be necessary.
A possible failure message looks like:
```
Failures:
1) RuboCop Project Changelog future entries For /home/peter/devel/rubocop/changelog/fix_a_crash_on_lint_useless_assignment.md has valid cop name with backticks
Got 3 failures:
1.1) Failure/Error: expect(cop_names.include?(cop_name)).to be(true), …
```
=> Ensure cop names are valid with backticks in future changelog entries

changelog/fix_a_false_positive_for_lint_format_parameter_mismatch.md, lib/rubocop/cop/lint/format_parameter_mismatch.rb, spec/rubocop/cop/lint/format_parameter_mismatch_spec.rb
Fixes #11521.
This PR fixes a false positive for `Lint/FormatParameterMismatch` when using `Kernel.format` with the interpolated number of decimal places fields match.
=> [Fix #11521] Fix a false positive for `Lint/FormatParameterMismatch`

docs/modules/ROOT/pages/compatibility.adoc
Due to the structural and grammatical similarity of terms it isn't clear that "here" refers to the link and not the section of the page being read. This makes the assumption explicit, which will help those unfamiliar with the reference.
When used in an anchor tag' text "here" commonly refers to what is in the anchor's href target.
However, less familiar RuboCop users may not know that there is a setting literally called `TargetRubyVersion`, while the preceeding sentence uses the exact same language "target ruby version", and is not directly referring to the setting.  This can result in the reference to "here" being ambiguous.
Better to be explicit.
=> Documentation: Clarify reference to TargetRubyVersion

changelog/fix_an_incorrect_autocorrect_for_layout_class_structure.md, lib/rubocop/cop/layout/class_structure.rb, spec/rubocop/cop/layout/class_structure_spec.rb
This PR is fix an incorrect autocorrect for `Layout/ClassStructure` when definitions that need to be sorted are defined alternately.
```ruby
class A
private def foo; end
def bar; end
private def baz; end
def qux; end
end
```
Automatically corrected as follows:
```ruby
class A
def bar; end
def qux; end
private def foo; end
private def baz; end
end
```
Automatically corrected as follows:
```ruby
class A
def qux; end
def bar; end
def qux; end # <------ Duplicate
private def foo; end
private def baz; end
end
```
=> Fix an incorrect autocorrect for `Layout/ClassStructure` when definitions that need to be sorted are defined alternately

changelog/fix_an_incorrect_autocorrect_for_style_access_modifier_declarations.md, lib/rubocop/cop/style/access_modifier_declarations.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/style/access_modifier_declarations_spec.rb
This PR is fix an incorrect autocorrect for `Style/AccessModifierDeclarations` when multiple groupable access modifiers are defined.
```ruby
class Test
private def foo; end
private def bar; end
def baz; end
end
```
Automatically corrected as follows:
```ruby
class Test
def baz; end
private
def foo; end
def bar; end
end
```
Automatically corrected as follows:
```ruby
class Test
def baz; end
private
def bar; end # <--- The order is changing
private # <--- Duplicate
def foo; end # <--- The order is changing
end
```
=> Fix an incorrect autocorrect for `Style/AccessModifierDeclarations` when multiple groupable access modifiers are defined

changelog/new_add_api_for_3rd_party_template.md, docs/modules/ROOT/pages/extensions.adoc, lib/rubocop/cop/base.rb, lib/rubocop/cop/commissioner.rb, lib/rubocop/cop/team.rb, lib/rubocop/runner.rb, spec/rubocop/runner_spec.rb
As I discussed at the following thread, I would like to add 3rd party template language plugins support to RuboCop.
- https://github.com/rubocop/rubocop/discussions/10768
To support template languages, I figured we need a new API to extract a set of Ruby code from one source code, so I added `RuboCop::Runner.ruby_extractors` in this pull request.
Ruby extractor is a callable object that takes a `RuboCop::ProcessedSource` and returns an `Array` of `Hash` (or returns nil for unrelated file) like this:
```ruby
ruby_extractor.call(processed_source)
```
```ruby
[
{
offset: 2,
processed_source: #<RuboCop::ProcessedSource>
},
{
offset: 10,
processed_source: #<RuboCop::ProcessedSource>
},
]
```
On the 3rd party plugin side, the following code would be written.
```ruby …
```
=> Add API for 3rd party template support

changelog/fix_infinite_loop_error_for_layout_array_alignment.md, lib/rubocop/cop/layout/array_alignment.rb, spec/rubocop/cop/layout/array_alignment_spec.rb
Fixes https://github.com/testdouble/standard/issues/517.
This PR fixes an infinite loop error for `Layout/ArrayAlignment` when using assigning unbracketed array elements.
=> Fix an infinite loop error for `Layout/ArrayAlignment`

Gemfile, changelog/change_remove_bundler_from_default_allowed_gems.md, config/default.yml, rubocop.gemspec
Follow up https://github.com/rubocop/rubocop/pull/11469#issuecomment-1400134564.
This PR removes `bundler` from default `AllowedGems` of `Gemspec/DevelopmentDependencies` It is a oversight of RuboCop development and should not be configured globally in config/default.yml.
=> Remove `bundler` from the default `AllowedGems` of `Gemspec/DevelopmentDependencies`

changelog/fix_a_false_positive_for_style_numbered_parameters_limit.md, lib/rubocop/cop/style/numbered_parameters_limit.rb, spec/rubocop/cop/style/numbered_parameters_limit_spec.rb
Fixes #11535.
This PR fixes a false positive for `Style/NumberedParametersLimit` when only `_2` or higher numbered parameter is used.
=> [Fix #11535] Fix a false positive for `Style/NumberedParametersLimit`

changelog/change_enable_autocorrection_for_line_continuation_leading_space.md, config/default.yml
Autocorrect was implemented in https://github.com/rubocop/rubocop/pull/11091.
=> Enable autocorrection for Layout/LineContinuationLeadingSpace

changelog/change_layout_assignment_indentation_and_lint_assignment_in_condition_safe_auto_correct.md, config/default.yml
https://github.com/rubocop/rubocop/pull/11211 added autocorrect for `Lint/AssignmentInCondition`, but marked `Layout/AssignmentIndentation` as unsafe for autocorrection.
=> Move SafeAutoCorrect: false to correct cop config

spec/project_spec.rb
Sometimes cops are renamed or removed so it should be allowed to use this name in changelog entries.
A follow-up of https://github.com/rubocop/rubocop/pull/11525.
Tested by using a removed or renamed cop name in changelog entry like `Gemspec/DateAssignment`:
```diff
diff --git a/changelog/fix_a_false_negative_for_style_yoda_expression.md b/changelog/fix_a_false_negative_for_style_yoda_expression.md
index 874f0b535..3071b22de 100644
--- a/changelog/fix_a_false_negative_for_style_yoda_expression.md
+++ b/changelog/fix_a_false_negative_for_style_yoda_expression.md
@@ -1 +1 @@
-* [#11520](https://github.com/rubocop/rubocop/pull/11520): Fix a false negative for `Style/YodaExpression` when using constant. ([@koic][])
+* [#11520](https://github.com/rubocop/rubocop/pull/11520): Fix a false …
```
=> Allow legacy cop names in upcoming changelog entries

lib/rubocop/cop/style/redundant_heredoc_delimiter_quotes.rb, spec/rubocop/cop/style/redundant_heredoc_delimiter_quotes_spec.rb
This commit adds a missing spec to highlight how escapes are handled.
Follow-up of https://github.com/rubocop/rubocop/pull/11528.
=> Lint/RedundantHeredocDelimiterQuotes: Add spec for escapes

changelog/fix_a_false_positive_for_lint_nested_method_definition.md, lib/rubocop/cop/lint/nested_method_definition.rb, spec/rubocop/cop/lint/nested_method_definition_spec.rb
This PR fixes the following false positive for `Lint/NestedMethodDefinition` when using numbered parameter:
```ruby
class Foo
def self.define
Module.new do
def y
end
do_something(_1)
end
end
end
```
```console
(snip)
Offenses:
example.rb:4:7: W: Lint/NestedMethodDefinition: Method definitions must not be nested. Use lambda instead.
def y ...
^^^^^
```
Since there is no warning for block parameter:
```ruby
class Foo
def self.define
Module.new do |m|
def y
end
do_something(m)
end
end
end
```
So, numbered parameter should behave the same.
=> Fix a false positive for `Lint/NestedMethodDefinition`

changelog/fix_an_incorrect_autocorrect_for_style_multiline_ternary_operator.md, lib/rubocop/cop/mixin/comments_help.rb, lib/rubocop/cop/style/multiline_ternary_operator.rb, spec/rubocop/cop/style/multiline_ternary_operator_spec.rb
Fix an incorrect autocorrect for `Style/MultilineTernaryOperator`  when contains a comment
This PR is fix an incorrect autocorrect for `Style/MultilineTernaryOperator`  when contains a comment.
For example, we have the following code
```ruby
foo = condition? ?
(do_something rescue rescued) : # rubocop:todo Style/RescueModifier
other_something
```
When we run `bundle exec rubocop -A --only Style/MultilineTernaryOperator`, the comment disappears as follows
```ruby
foo = if condition?
(do_something rescue rescued)
else
other_something
end
```
=> Fix an incorrect autocorrect for `Style/MultilineTernaryOperator`  when contains a comment

changelog/new_make_useless_access_modifier_aware_of_data_define.md, lib/rubocop/cop/lint/useless_access_modifier.rb, spec/rubocop/cop/lint/useless_access_modifier_spec.rb
Ruby 3.2 introduced immutable `Data.define`. Since this is similar to `Struct.new`. This `Lint/UselessAccessModifier` will handle `Struct.new` and `Data.define` in the same way.
=> Make `Lint/UselessAccessModifier` aware of Ruby 3.2's `Data.define`

changelog/fix_an_error_for_third_party_cops.md, lib/rubocop/cop/cop.rb
Fixes #11549.
This PR fixes an error for third party cops when inheriting `RuboCop::Cop::Cop`. It makes the same changes to `RuboCop::Cop::Cop` as `RuboCop::Cop::Base` in #10839. Confirmed that rubocop-i18n tests pass again.
=> [Fix #11549] Fix an error for third party cops

changelog/fix_an_error_for_style_redundant_condition.md, lib/rubocop/cop/style/redundant_condition.rb, spec/rubocop/cop/style/redundant_condition_spec.rb
Fixes #11554.
This PR fixes an error for `Style/RedundantCondition` when the branches contains empty hash literal argument.
=> [Fix #11554] Fix an error for `Style/RedundantCondition`

spec/rubocop/cop/variable_force_spec.rb
This PR reverts a pending test of #10432 because https://github.com/jruby/jruby/issues/7113 has been resolved in JRuby 9.3.9.0.
`RegexpError` error will occur:
```console
% rbenv local jruby-9.3.3.0
% ruby -e "Regexp.new('\x82', Regexp::NOENCODING)"
RegexpError: invalid multibyte escape: /\x82/
initialize at org/jruby/RubyRegexp.java:956
new at org/jruby/RubyClass.java:893
<main> at -e:1
```
No errors:
```console
% rbenv local jruby-9.3.9.0
% ruby -e "Regexp.new('\x82', Regexp::NOENCODING)"
% rbenv local jruby-9.4.1.0
% ruby -e "Regexp.new('\x82', Regexp::NOENCODING)"
```
=> Restore a pending test for processing a regex with regopt

changelog/fix_a_false_positive_for_lint_debugger.md, lib/rubocop/cop/lint/debugger.rb, spec/rubocop/cop/lint/debugger_spec.rb
This PR is fix a false positive for `Lint/Debugger` when methods containing different method chains.
I don't think that methods such as `p.do_something` for example should be an offense of this cop. I think it would be better to make it a violation only if it is an exact match, including the method chain, but what do you think?
```ruby
p 'foo'
foo(p 'foo')
p(p 'foo')
p.do_something # <--- Before the change, it is a bad code
Foo.p
```
=> Fix a false positive for `Lint/Debugger` when methods containing different method chains

.github/workflows/rubocop.yml
JRuby 9.4.1.0 is now available on setup-ruby.
https://github.com/ruby/setup-ruby/releases/tag/v1.136.0
JRuby 9.4 is MRI 3.1 compatible and JRuby 9.3 is MRI 2.6 compatible. JRuby 9.3 is still supported as a RuboCop runtime, but presumably any new JRuby issues found may be fixed in JRuby 9.4. And MRI 2.6 will be dropped from the runtime in the not distant future.
So, JRuby 9.3 will not be retained and will be replaced by JRuby 9.4 because CI latency.
=> CI against JRuby 9.4 instead of JRuby 9.3

changelog/fix_an_error_for_style_access_modifier_declarations.md, lib/rubocop/cop/style/access_modifier_declarations.rb, spec/rubocop/cop/style/access_modifier_declarations_spec.rb
This PR is fix an error for `Style/AccessModifierDeclarations` when if a non method definition was included.
```ruby
class Test
private def foo; end
private def bar; end
def baz; end
QUX = ['qux']
end
```
```
Failures:
1) RuboCop::Cop::Style::AccessModifierDeclarations when `group` is configured offends when multiple groupable access modifiers are defined
Failure/Error: sibling.method?(node.method_name) && !sibling.arguments.empty?
NoMethodError:
undefined method `method?' for s(:casgn, nil, :QUX,
s(:array)):RuboCop::AST::CasgnNode
```
=> Fix an error for `Style/AccessModifierDeclarations` when if a non method definition was included

changelog/fix_octal_handling_in_regexp_char_classes_.md, lib/rubocop/cop/style/redundant_regexp_character_class.rb, spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb
regexp_parser v2.7.0 introduced a fix that makes it correctly detect octal escapes (e.g. "\141", which equals "a") inside character classes, e.g. `/[\141]/`.
Previously, these were incorrectly interpreted and chunked, c.f. https://github.com/ammar/regexp_parser/issues/86
The incorrect chunking made your build green. This is because `\032` emitted `\0`, which was checked for specifically in `#backslash_zero?`.
The fix in regexp_parser v2.7.0, however, made this spec red.
The correct output by rubocop would be to detect this case as a redundant use of a char class, because it is.
The same goes for the original example "\0":
```ruby
[/\0/.match?("\0"), /[\0]/.match?("\0")] # => [true, true]
```
For `\1` to `\7`, putting them in a char class is not redundant but actually required, because …
=> Fix octal handling in `Style/RedundantRegexpCharacterClass`

changelog/fix_a_false_positive_for_lint_debugger.md, lib/rubocop/cop/lint/debugger.rb, spec/rubocop/cop/lint/debugger_spec.rb
Fixes #11556.
This PR fixes a false positive for `Lint/Debugger` when `p` is an argument of method call. Basically, debugger methods are not used as a method argument without arguments.
=> [Fix #11556] Fix a false positive for `Lint/Debugger`

changelog/change_remove_print_debug_methods_from_default_for_lint_debugger.md, config/default.yml, spec/rubocop/cop/lint/debugger_spec.rb
This PR rolls back the print debug default configuration (#11518) of `Lint/Debugger` based on the following feedback.
- https://github.com/rubocop/rubocop/pull/11557#issuecomment-1423819556
- https://github.com/rubocop/rubocop/pull/11552#issuecomment-1423489150
- https://github.com/rubocop/rubocop/pull/11518#issuecomment-1425847503
It seems like it was a bad idea to mix debugger and print debug methods by default.
This PR updates `Lint/Debugger` cop defaults to handle only debugger methods as per the cop name. OTOH, it leaves the logic in #11557 to prevent false positives when user configures print debug methods. e.g. https://github.com/rubocop/rubocop/issues/11517#issuecomment-1407695703
[1]: …
=> Remove print debug methods from default for `Lint/Debugger`

CHANGELOG.md, spec/project_spec.rb, spec/tasks/changelog_spec.rb, tasks/changelog.rb
Occasionally I review direct edit to the CHANGELOG.md:
- https://github.com/rubocop/rubocop/pull/11559#discussion_r1101152654
- https://github.com/rubocop/rubocop/pull/11406#discussion_r1064492125
- https://github.com/rubocop/rubocop/pull/11395#discussion_r1064000369
It might be communicated a little more efficiently if listed in the CHANGELOG.md. And the triple dash for commenting out is used intentionally.
https://stackoverflow.com/questions/4823468/comments-in-markdown/4829998#4829998
It affects when markdown is viewed on GitHub. This is unnecessary note for user viewing the CHANGELOG.md on GitHub.
Also add changelog/.gitkeep to prevent dead link after release.
=> Add contribution note for CHANGELOG.md

changelog/new_support_ruby_3_3_experimental.md, docs/modules/ROOT/pages/compatibility.adoc, lib/rubocop/rspec/shared_contexts.rb, lib/rubocop/target_ruby.rb, rubocop.gemspec, spec/rubocop/cli_spec.rb
RuboCop AST 1.25 supports Ruby 3.3.
https://github.com/rubocop/rubocop-ast/pull/256
This PR supports `TargetRubyVersion 3.3`.
=> Support `TargetRubyVersion 3.3` (experimental)

changelog/fix_fix_layout_end_alignment_false_negative.md, lib/rubocop/cop/layout/end_alignment.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/layout/end_alignment_spec.rb
Fixes #11567
This PR adds the singleton class definition to the inspection targets of `Layout/EndAlignment`.
=> [Fix #11567] Fix `Layout/EndAlignment` false negative

spec/rubocop/cli_spec.rb
https://github.com/jruby/jruby/issues/6365 has been resolved in JRuby 9.4. This PR restores a pending test for JRuby.
MRI and JRuby return different error messages, the regex is tweaked for the error messages:
```console
% ruby -ryaml -ve "YAML.load('Exclude: **/*_old.rb')"
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-darwin19]
/Users/koic/.rbenv/versions/3.2.1/lib/ruby/3.2.0/psych/parser.rb:62:in `_native_parse': (<unknown>):
did not find expected alphabetic or numeric character while scanning an alias at line 1 column 10 (Psych::SyntaxError)
from /Users/koic/.rbenv/versions/3.2.1/lib/ruby/3.2.0/psych/parser.rb:62:in `parse'
from /Users/koic/.rbenv/versions/3.2.1/lib/ruby/3.2.0/psych.rb:455:in `parse_stream'
from /Users/koic/.rbenv/versions/3.2.1/lib/ruby/3.2.0/psych.rb:399:in …
```
=> Restore a pending test for JRuby

changelog/fix_a_broken_shorthand_syntax_autocorrection.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
Calls like `foo(bar: bar).baz` were autocorrected to `foo(bar:)).baz`. Notice the extra parentheses. I have broken this in #11516.
=> Fix a broken shorthand syntax autocorrection

changelog/fix_an_error_for_lint_useless_rescue.md, lib/rubocop/cop/lint/useless_rescue.rb, spec/rubocop/cop/lint/useless_rescue_spec.rb
This PR fixes an error for `Lint/UselessRescue` when `rescue` does not exception variable and `ensure` has empty body:
```ruby
def foo
rescue => e
ensure
end
```
```console
% bundle exec rubocop --only Lint/UselessRescue -d
(snip)
undefined method `each_descendant' for nil:NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/lint/useless_rescue.rb:78:in `use_exception_variable_in_ensure?'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/lint/useless_rescue.rb:60:in `only_reraising?'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/lint/useless_rescue.rb:54:in `on_rescue'
```
=> Fix an error for `Lint/UselessRescue`

changelog/fix_an_error_for_layout_heredoc_argument_closing_parenthesis.md, lib/rubocop/cop/layout/heredoc_argument_closing_parenthesis.rb, spec/rubocop/cop/layout/heredoc_argument_closing_parenthesis_spec.rb
This PR fixes an error for `Layout/HeredocArgumentClosingParenthesis` when heredoc is a method argument in a parenthesized block argument:
```ruby
foo(bar do
baz <<~EOS
EOS
end)
```
```console
% bundle exec rubocop --only Layout/HeredocArgumentClosingParenthesis
(snip)
undefined method `begin_pos' for nil:NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/layout/
heredoc_argument_closing_parenthesis.rb:220:in `exist_argument_between_heredoc_end_and_closing_parentheses?'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/layout/
heredoc_argument_closing_parenthesis.rb:73:in `on_send'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/commissioner.rb:107:in `public_send'
```
[1]: …
=> Fix an error for `Layout/HeredocArgumentClosingParenthesis`

lib/rubocop/cop/mixin/multiline_element_line_breaks.rb
These were internal to Flexport and not needed here.
=> Remove irrelevant comments

changelog/change_documentation_method_accept_handle_ruby2_keywords.md, lib/rubocop/cop/style/documentation_method.rb, spec/rubocop/cop/style/documentation_method_spec.rb
=> Handle `ruby2_keywords` in `Style/DocumentationMethod` cop

changelog/change_optimize_style_word_array_complex_matrix_check.md, lib/rubocop/cop/style/word_array.rb, spec/rubocop/cop/style/word_array_spec.rb
One of the checks we do in `Style/WordArray` is to check if an otherwise simple array is a member of a parent array consisting exclusively of arrays, including at least one with "complex" content.
This means that for each sub-array, we navigate up to the parent, and check all of its children, resulting in `n²` array complexity checks.
By maintaining a cache of checked parent array nodes per investigation (i.e. per file), we can reduce this to `n` array complexity checks.
This has a massive impact on performance when investigating files containing large arrays of arrays. A test is added with a timeout that does not pass when using the non-caching implementation **(it would take over a minute; now takes under a second)**. …
=> Optimize `Style/WordArray` complex matrix check

lib/rubocop/cop/lint/redundant_cop_disable_directive.rb
Measured in Gitlab's codebase. They have a few old-named (yet to be renamed) cops disabled in the codebase.
Execution time: `225s`
```
Mode: wall(1000)
Samples: 224700 (0.73% miss rate)
GC: 10689 (4.76%)
==> 31853  (14.2%)       31853  (14.2%)     DidYouMean::Jaro.distance
15008   (6.7%)        9356   (4.2%)     Parser::Lexer#advance
5485   (2.4%)        5485   (2.4%)     (sweeping)
5118   (2.3%)        5118   (2.3%)     (marking)
10074   (4.5%)        4588   (2.0%)     RuboCop::AST::Descendence#each_child_node
4430   (2.0%)        4430   (2.0%)     Parser::Source::Buffer#slice
5470   (2.4%)        4252   (1.9%)     Parser::Source::Buffer#line_index_for_position
4860   (2.2%)        3668   (1.6%) …
```
=> Cache similar name suggestions in `Lint/RedundantCopDisableDirective` cop

changelog/fix_a_false_positive_for_layout_line_continuation_spacing.md, lib/rubocop/cop/layout/line_continuation_spacing.rb, spec/rubocop/cop/layout/line_continuation_spacing_spec.rb
This PR fixes a false positive for `Layout/LineContinuationSpacing` when using percent literals.
Space with `\` has meaning in percent literals. e.g.:
```ruby
p %i[
x \
]
p %i[
x\
]
```
```console
% ruby example.rb
[:x, :"\n"]
[:"x\n"]
```
=> Fix a false positive for `Layout/LineContinuationSpacing`

changelog/change_make_naming_variable_number_to_allow_x86_64_by_default.md, config/default.yml, spec/rubocop/config_loader_spec.rb
Fixes #11604.
This PR makes `Naming/VariableNumber` to allow `x86_64` CPU architecture name by default. CPU architecture names such as "x86" and "arm64" are not added as they do not require underscore separators like "x86_64".
=> [Fix #11604] Make `Naming/VariableNumber` to allow `x86_64` by default

changelog/fix_parentheses_in_value_omissions_for_multiple.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
I'm on a quest to run the `EnforcedShorthandSyntax: always` style on a big codebase. One of the latest thins I found was a value omission in multiple assignments. Not the best idea, but it is a real "production" code usage, I guess. Here is an estimation of the code:
```ruby
foo = foo = do_stuff arg, opt1: opt1,
opt2: opt2
something.each { pass }
```
The multiple assignment in the code above tricks the current version of the parentheses detection code and we don't put the parens when autocorrecting:
```ruby
foo = foo = do_stuff arg, opt1:,
opt2:
something.each { pass }
```
While not a syntax error, Ruby is treating it like:
```ruby
foo = foo = do_stuff arg, opt1:,
opt2: something.each { pass }
```
We do need to put the parentheses for end result like:
```ruby
foo = foo = do_stuff(arg, …
```
=> Fix parentheses in value omissions for multiple assignments

changelog/fix_an_error_for_refinement_import_methods.md, lib/rubocop/cop/lint/refinement_import_methods.rb, spec/rubocop/cop/lint/refinement_import_methods_spec.rb
This PR fixes an error for `Lint/RefinementImportMethods` when using `include` on the top level.
```ruby
include Foo
```
```console
% bundle exec rubocop --only Lint/RefinementImportMethods -d
(snip)
undefined method `block_type?' for nil:NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/lint/refinement_import_methods.rb:44:in `on_send'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/commissioner.rb:143:in `public_send'
```
=> Fix an error for `Lint/RefinementImportMethods`

changelog/fix_line_begins_check_for_large_offset.md, lib/rubocop/cop/util.rb, spec/rubocop/cop/layout/indentation_width_spec.rb
Fixes #11582.
50 is pretty reasonable number, I think. For bigger offsets we just fallback to the previous behavior.
=> Fix checking if token with large offset begins its line

changelog/fix_actually_run_temporarily_enabled_cops.md, lib/rubocop/comment_config.rb, lib/rubocop/cop/team.rb, lib/rubocop/rspec/cop_helper.rb, spec/rubocop/cli_spec.rb, spec/rubocop/cop/team_spec.rb
A follow-up on https://github.com/rubocop/rubocop/pull/10987, I was trying to use the temporarily cop enablement feature, and realized that it wasn't working as intended. Although rubocop does not complain about unneeded directives in such case, it turns out those temporarily enabled cops weren't reporting any offense.
I think I overlooked 2 things in the original implementation:
- the fact that `Team.mobilize_cops` was going to exclude those cops from the beginning and never invoke them
- the [test](https://github.com/rubocop/rubocop/pull/10987/files#diff-46b3c2cf6f8085fc01a6be8ddf84f83b741c9065ecb04cd0cb3409ee29bf9379R282) that I wrote was checking that the temporarily enabled cop wasn't reported as an unneeded directive, but not that it was actually reporting offenses, this is now …
=> Actually run temporarily enabled cops

changelog/change_make_style_accessor_grouping_aware_of_method_call_before_accessor_method.md, lib/rubocop/cop/style/accessor_grouping.rb, spec/rubocop/cop/style/accessor_grouping_spec.rb
Fixes #11596.
This PR makes `Style/AccessorGrouping` aware of method call before accessor.
If there is a method call before the accessor method it is always allowed as it might be intended like Sorbet . Note, it respects user's intentions, not just Sorbet. Because (annotation) comments are already allowed, so (annotation) methods can be generalized as well.
=> [Fix #11596] Make `Style/AccessorGrouping` aware of method call before accessor

changelog/fix_a_false_positive_for_lint_to_enum_arguments.md, lib/rubocop/cop/lint/to_enum_arguments.rb, spec/rubocop/cop/lint/to_enum_arguments_spec.rb
Fixes #11591.
THis PR fixes a false positive for `Lint/ToEnumArguments` when enumerator is not created for `__callee__` and `__callee__` methods.
=> [Fix #11591] Fix a false positive for `Lint/ToEnumArguments`

lib/rubocop/cop/style/accessor_grouping.rb
Follow up https://github.com/rubocop/rubocop/pull/11602#issuecomment-1440585242.
This PR adds examples for `Style/AccessorGrouping`.
=> Add examples for `Style/AccessorGrouping`

changelog/fix_an_error_for_lint_constant_resolution.md, lib/rubocop/cop/lint/constant_resolution.rb, spec/rubocop/cop/lint/constant_resolution_spec.rb
This PR fixes an error for `Lint/ConstantResolution` when using `__ENCODING__`.
```ruby
__ENCODING__
```
```console
$ rubocop constant_resolution.rb --only Lint/ConstantResolution -d
(snip)
undefined method `expression' for nil:NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/base.rb:419:in `range_from_node_or_range'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/base.rb:173:in `add_offense'
```
=> Fix an error for `Lint/ConstantResolution`

changelog/fix_a_false_positive_for_style_redundant_regexp_escape.md, lib/rubocop/cop/style/redundant_regexp_escape.rb, spec/rubocop/cop/style/redundant_regexp_escape_spec.rb
Fixes #11607.
This PR fixes a false positive for `Style/RedundantRegexpEscape` when an escaped hyphen follows after an escaped opening square bracket within a character class.
=> [Fix #11607] Fix a false positive for Style/RedundantRegexpEscape

changelog/fix_a_false_negative_for_lint_missing_super.md, changelog/fix_a_false_positive_for_lint_missing_super.md, lib/rubocop/cop/lint/missing_super.rb, spec/rubocop/cop/lint/missing_super_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/11615.
This PR fixes two bugs reported in #11615:
- Fix a false negative when no `super` call with `Class.new` block.
- Fix a false positive when using `Class.new` without parent class argument.
=> [Fix #11615] Fix false negative and positive for `Lint/MissingSuper`

changelog/change_add_rubocop_capybara_to_suggested_extensions.md, config/default.yml, docs/modules/ROOT/pages/extensions.adoc
This PR adds [rubocop-capybara](https://github.com/rubocop/rubocop-capybara) to the `SuggestExtensions` list and extension doc.
=> Add rubocop-capybara to suggested extensions and extension doc

changelog/fix_autocorrect_class_structure_method_with_heredoc.md, lib/rubocop/cop/layout/class_structure.rb, spec/rubocop/cop/layout/class_structure_spec.rb
=> Fix an incorrect autocorrect for `Layout/ClassStructure` using heredoc inside method

changelog/fix_a_false_positive_for_style_zero_length_predicate.md, lib/rubocop/cop/style/zero_length_predicate.rb, spec/rubocop/cop/style/zero_length_predicate_spec.rb
Fixes #11626.
This PR fixes a false positive for `Style/ZeroLengthPredicate` when using `File.new(path).size.zero?`.
The same goes for the existing `Tempfile` and `StringIO`.
=> [Fix #11626] Fix a false positive for `Style/ZeroLengthPredicate`

changelog/fix_handle_modifier_looping_conditionals_in.md, lib/rubocop/cop/variable_force/variable.rb, spec/rubocop/cop/lint/useless_assignment_spec.rb
The modifier `if` and `unless` expressions were fixed in [fca7d43][], but it didn't also fix it for the modifier forms of `while` and `until`. This commit builds on that commit so that the following code no longer fails the Lint/UselessAssignment cop:
```
middleware = nil
middleware.call(env) while (middleware = rack_middleware.next)
```
[fca7d43]: https://github.com/rubocop/rubocop/commit/fca7d435b438ea407854adccac11b4a1beb1301d
=> Handle modifier looping conditionals so `Lint/UselessAssignment` doesn't give false positives

changelog/fix_an_incorrect_autocorrect_for_style_arguments_forwarding.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
Fixes #11631.
This PR fixes an incorrect autocorrect for `Style/ArgumentsForwarding` when using arguments forwarding for `.()` call.
=> [Fix #11631] Fix an incorrect autocorrect for `Style/ArgumentsForwarding`

changelog/fix_a_false_positive_for_style_if_unless_modifier.md, lib/rubocop/cop/style/if_unless_modifier.rb, spec/rubocop/cop/style/if_unless_modifier_spec.rb
Fixes #11040.
This PR fixes a false positive for `Style/IfUnlessModifier` when `defined?`'s argument value is undefined.
=> [Fix #11040] Fix a false positive for `Style/IfUnlessModifier`

changelog/fix_only_flag_usage_with_auto_gen_config.md, lib/rubocop/cli/command/auto_generate_config.rb, spec/rubocop/cli/auto_gen_config_spec.rb
**Fixes https://github.com/rubocop/rubocop/issues/11202
This PR fixes the usage of the `--only` flag with the `--auto-gen-config` when the `Layout/LineLength` COP is enabled.
It will only generate the config for the given COPs if we use use the `--only` flag.**
=> [Fix #11202] Fix `--only` flag usage with `--auto-gen-config` and `Layout/LineLength`

changelog/fix_incorrect_shorthand_autocorrections_in_calls.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
If you happen to have a method call without parentheses that is inside outer parentheses like the following example:
```ruby
(create :integration_shop, account: account)
pass
```
We would have still thought that we need to add parentheses to the `create` call during `Style/HashSyntax` autocorrection like so:
```ruby
(create(:integration_shop, account:))
pass
```
While this is not a problem in isolation, it can lead to invalid Ruby autocorrections when `Style/HashSyntax` is used in combination with `Style/RedundantParentheses` (enabled by default) and `Style/MethodCallWithArgsParentheses` (disabled by default) with `EnforcedStyle: omit_parentheses`:
```yaml
AllCops:
TargetRubyVersion: 3.1
Style/HashSyntax:
EnforcedShorthandSyntax: always
Style/RedundantParentheses:
Enabled: true …
```
=> Fix incorrect shorthand autocorrections in calls inside parentheses

changelog/fix_an_error_for_style_negated_if_else_condition.md, lib/rubocop/cop/style/negated_if_else_condition.rb, spec/rubocop/cop/style/negated_if_else_condition_spec.rb
This PR fixes an error for `Style/NegatedIfElseCondition` when using `()` as a condition.
```ruby
if ()
else
do_something
end
```
```console
$ bundle exec rubocop --only Style/NegatedIfElseCondition -d
(snip)
undefined method `begin_type?' for nil:NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/negated_if_else_condition.rb:76:in `unwrap_begin_nodes'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/negated_if_else_condition.rb:52:in `on_if'
```
=> Fix an error for `Style/NegatedIfElseCondition`

changelog/fix_an_error_for_style_if_with_boolean_literal_branches.md, lib/rubocop/cop/style/if_with_boolean_literal_branches.rb, spec/rubocop/cop/style/if_with_boolean_literal_branches_spec.rb
This PR fixes an error for `Style/IfWithBooleanLiteralBranches` when using `()` as a condition.
```ruby
if ()
else
end
```
```console
$ bundle exec rubocop --only Style/IfWithBooleanLiteralBranches -d
(snip)
undefined method `begin_type?' for nil:NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/if_with_boolean_literal_branches.rb:121:
in `return_boolean_value?'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/if_with_boolean_literal_branches.rb:122:
in `return_boolean_value?'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/if_with_boolean_literal_branches.rb:75:
in `if_with_boolean_literal_branches?'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/if_with_boolean_literal_branches.rb:77:
in `on_if'
``` …
=> Fix an error for `Style/IfWithBooleanLiteralBranches`

changelog/fix_style_accessor_grouping_fix_detection_of_sorbet.md, lib/rubocop/cop/style/accessor_grouping.rb, spec/rubocop/cop/style/accessor_grouping_spec.rb
- Sorbet `sig { returns(Integer) }` annotations above `attr_reader` methods should be ignored after ~9921cdcd03b1883a9ce66de769c457da4c3317b7~ df7c4cd1f4e2f0cb912feb69eea2fd9f9ab5e5b7, per the docs, but they weren't being (see the test I added here for evidence).
- Sorbet `sig {}` constructs are blocks (hence the braces), not `send_type?` directly.
- Hence, we now check if the previous expression is a block and if so, descend into its child nodes until we find a `send_type`, then use that to determine if the accessor is groupable.
- Relates to https://github.com/rubocop/rubocop/issues/11596, but that issue is already closed.
=> Style/AccessorGrouping: Fix detection of Sorbet `sig {}` blocks

changelog/fix_a_false_negative_for_lint_missing_super.md, lib/rubocop/cop/lint/missing_super.rb, spec/rubocop/cop/lint/missing_super_spec.rb
Follow part of https://github.com/rubocop/rubocop/pull/11619#issuecomment-1452021939.
This PR fixes a false positive for `Lint/MissingSuper` when no `super` call and when defining some method.
=> Fix a false negative for `Lint/MissingSuper`

changelog/change_avoid_comment_deletion_by_style_if_unless_modifier.md, lib/rubocop/cop/style/if_unless_modifier.rb, spec/rubocop/cop/style/if_unless_modifier_spec.rb
This PR fixes #11482.
Now the cop corrects code from:
```rb
some_statement if some_quite_long_condition # The condition might have been long, but this comment is longer. In fact, it is too long for Rubocop
```
to:
```rb
some_statement if some_quite_long_condition
```
I think the correction is ok. But the message for the offense is still indicate `if` is bad, not comment.
Any ideas for this?
```console
test.rb:3:16: C: [Corrected] Style/IfUnlessModifier: Modifier form of if makes the line too long.
some_statement if some_quite_long_condition # The condition might have been long, but this comment is longer. In fact, it is too long for Rubocop
^^
```
=> [Fix #11482] Avoid comment deletion by `Style/IfUnlessModifier` when the modifier form expression has long comment

changelog/fix_an_incorrect_autocorrect_for_lint_or_assignment_to_constant.md, lib/rubocop/cop/lint/or_assignment_to_constant.rb, spec/rubocop/cop/lint/or_assignment_to_constant_spec.rb
This PR fixes the following incorrect autocorrect for `Lint/OrAssignmentToConstant` when using or-assignment to a constant in method definition.
```ruby
def foo
M::N ||= 42
end
```
```console
$ ruby -v
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-darwin19]
$ ruby -c example.rb
Syntax OK
$ bundle exec rubocop --only Lint/OrAssignmentToConstant -a
(snip)
Offenses:
example.rb:2:8: W: Lint/OrAssignmentToConstant: Avoid using or-assignment with constants.
M::N ||= 42
^^^
```
```ruby
def foo
M::N = 42
end
```
```console
$ ruby -c example.rb
example.rb: example.rb:2: dynamic constant assignment (SyntaxError)
M::N = 42
^~~~
```
It's reasonable to display the offense, but it wouldn't be reasonable to have this syntax error caused by autocorrection. …
=> Fix an incorrect autocorrect for `Lint/OrAssignmentToConstant`

changelog/fix_an_error_for_style_documentation.md, lib/rubocop/cop/style/documentation.rb, spec/rubocop/cop/style/documentation_spec.rb
This PR fixes an error for `Style/Documentation` when namespace is a variable.
```ruby
m = Module.new
module n::N
def method
end
end
```
```console
% rubocop documentation.rb --only Style/Documentation -d
(snip)
undefined method `namespace' for s(:lvar, :m):RuboCop::AST::Node
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/documentation.rb:187:in `qualify_const'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/documentation.rb:187:in `qualify_const'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/documentation.rb:181:in `block in identifier'
```
It also complements missing cbase and namespaces in offense messages. e.g.:
```diff
class ::MyClass
-^^^^^^^^^^^^^^^ Missing top-level documentation comment for `class MyClass`.
+^^^^^^^^^^^^^^^ …
```
=> Fix an error for `Style/Documentation`

changelog/fix_fix_a_false_positive_for_lint_useless_access_modifier.md, lib/rubocop/cop/lint/useless_access_modifier.rb, spec/rubocop/cop/lint/useless_access_modifier_spec.rb
This PR is fix a false positive for `Lint/UselessAccessModifier` when using same access modifier inside and outside the `included` block.
If an included block is used within a class, as shown below, I think it should not be a violation even if the same access modifier is used inside and outside the `included` block.
```ruby
class SomeClass
included do
private
def foo; end
end
private
def bar; end
end
```
=> Fix a false positive for `Lint/UselessAccessModifier` when using same access modifier inside and outside the `included` block

changelog/fix_use_cop_name_inside_registry_enabled_check.md, lib/rubocop/cop/registry.rb, lib/rubocop/cop/team.rb
Fixes https://github.com/rubocop/rubocop/issues/11657.
Previously, `@for_cop` cache https://github.com/rubocop/rubocop/blob/951507a2cd70518aeca2351b405a301534be195b/lib/rubocop/config.rb#L34-L40
always received only cop names (strings) or cop classes, but after https://github.com/rubocop/rubocop/pull/11603/files#diff-1c2f3a3b82c13964ec1f4f0ce72bb04f429cc9258514611cd6b6d735ec8aea6aR163 it started to receive cop instances, and so this cache became needlessly bigger and bigger.
=> Use cop name to check if cop inside registry is enabled

changelog/fix_an_incorrect_autocorrect_for_style_block_delimiters.md, lib/rubocop/cop/style/block_delimiters.rb, spec/rubocop/cop/style/block_delimiters_spec.rb
Fixes #11665.
This PR fixes an incorrect autocorrect for `Style/BlockDelimiters` when multi-line blocks to `{` and `}` with arithmetic operation method chain.
=> [Fix #11663] Fix an incorrect autocorrect for `Style/BlockDelimiters`

lib/rubocop/formatter/junit_formatter.rb
In https://github.com/rubocop/rubocop/issues/11657, I identified inefficiency of junit formatter.
With the https://github.com/ruby/rexml/pull/94 (see there for all the details regarding how I profiled etc), I was able to optimize memory usage quite a lot.
```
Total allocated: 630.15 MB (8838482 objects)
Total retained:  53.50 MB (445069 objects)
allocated memory by gem
294.26 MB  rexml/lib
214.78 MB  rubocop/lib
38.60 MB  rubocop-ast/lib
31.62 MB  parser-3.2.1.0
31.43 MB  other
10.02 MB  lib
3.11 MB  rubocop-rspec-2.18.1
1.95 MB  rubocop-performance-1.16.0
1.83 MB  regexp_parser-2.7.0
1.61 MB  ast-2.4.2
405.71 kB  unicode-display_width-2.4.2
287.16 kB  rubocop-capybara-2.17.1
244.96 kB  rubocop-rake-0.6.0
5.00 kB  rubygems …
```
=> Cache `classname_attribute_value` in junit formatter

changelog/fix_fix_rubocop_11164_suppress_server_mode_message.md, lib/rubocop/server/core.rb, spec/rubocop/server/rubocop_server_spec.rb
A followup to https://github.com/rubocop/rubocop/pull/11167 and https://github.com/rubocop/rubocop/issues/11164. I noticed "RuboCop server starting..." is still printed when running in server mode with `-f json`. It should be suppressed :zipper_mouth_face: 
=> [Fix rubocop#11164] Suppress server mode message with -f json

changelog/fix_incorrect_style_hash_syntax_autocorrection_for.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
In Ruby 3.1 and above, code like:
```ruby
object.attr = {foo: foo}
^^^ Omit the hash value.
pass
```
was incorrectly autocorrected to:
```ruby
object.attr({foo:})
pass
```
The autocorrected code is valid Ruby, but is semantically different. This may and will lead to subtle bugs in user codebases.
=> Fix incorrect Style/HashSyntax autocorrection for assignment methods

changelog/fix_an_error_for_layout_block_end_newline.md, lib/rubocop/cop/layout/block_end_newline.rb, spec/rubocop/cop/layout/block_end_newline_spec.rb
Fixes #11672.
This PR fixes an error for `Layout/BlockEndNewline` when multiline block `}` is not on its own line and it is used as multiple arguments.
And the following case is handled by `Style/Semicolon`:
```ruby
test do
foo
; end
```
So make it out of the responsibility of `Layout/BlockEndNewline`.
=> [Fix #11672] Fix an error for `Layout/BlockEndNewline`

lib/rubocop/cop/naming/method_name.rb, spec/rubocop/cop/naming/method_name_spec.rb
None of the code paths lead to scenarios in which a method name could possibly include leading or trailing whitespace, so there is no reason for the documentation or test patterns to include optional whitespace.
Instead, we can show an example of anchoring on both ends, to exactly match the method name.
[1]: …
=> Improve `Naming/MethodName` example `AllowedPatterns`

changelog/fix_style_accessor_grouping_fix_sibling_detection_for.md, lib/rubocop/cop/style/accessor_grouping.rb, spec/rubocop/cop/style/accessor_grouping_spec.rb
- Over in `Homebrew/brew`, trying to enable this cop after 008506d59f094140636269aa588e32fb69001018 was released, we were seeing the following offenses which were incorrect since we can't combine attrs that follow on from typed ones.
```
sig { returns(Pathname) }
attr_reader :cached_location
attr_reader :cache, :meta, :name, :version
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Group together all `attr_reader` attributes
```
- This commit ensures that sibling accessors are groupable before raising an offense that they should be grouped.
- Also add more tests to ensure the offense detection and subsequent autocorrection still works.
- Follow up to #11650.
=> Style/AccessorGrouping: Fix sibling detection for methods with type sigs

changelog/fix_a_false_positive_for_lint_useless_rescue.md, lib/rubocop/cop/lint/useless_rescue.rb, spec/rubocop/cop/lint/useless_rescue_spec.rb
Fixes #11682.
This PR fixes a false positive for `Lint/UselessRescue` when using `Thread#raise` in `rescue` clause. In fact, any method call with a receiver will not be "useless rescue", not just `Thread#raise`.
=> [Fix #11682] Fix a false positive for `Lint/UselessRescue`

changelog/fix_the_severity_for_lint_syntax.md, lib/rubocop/cop/lint/syntax.rb, spec/rubocop/cli_spec.rb, spec/rubocop/cop/lint/syntax_spec.rb
Fixes #11677.
This PR fixes the severity for `Lint/Syntax`. The `Lint/Syntax` severity must always be `fatal`.
> There is one exception from the general rule above and that is `Lint/Syntax`, a special cop that checks for syntax errors before the other cops are invoked. It cannot be disabled and its severity (`fatal`) cannot be changed in configuration.
https://docs.rubocop.org/rubocop/1.46/configuration.html#severity
In addition to #11666, it also fixes the following issues:
```ruby
def foobar
t = {
a: "foo"  # missing "," syntax error
b: 'bar'
}
return t
end
```
The severity that mult be `fatal` (`F`) is unexpectedly `error` (`E`):
```console
(snip)
E
Offenses:
example.rb:4:5: E: Lint/Syntax: unexpected token tIDENTIFIER
(Using Ruby 3.2 parser; …
```
=> [Fix #11677] Fix the severity for `Lint/Syntax`
