changelog/fix_lint_syntax_when_enabled_false.md, lib/rubocop/config.rb, spec/rubocop/cli_spec.rb
Here's another fix I found in work on #11688.
Ruby code has a syntax error and .rubocop.yml with `Lint` department is disabled:
```ruby
def foobar
t = {
a: "foo"  # missing "," syntax error
b: 'bar'
}
return t
end
```
```yaml
Lint:
Enabled: false
```
But `Lint/Syntax` must not be disabled:
> There is one exception from the general rule above and that is `Lint/Syntax`, a special cop that checks for syntax errors before the other cops are invoked. It cannot be disabled and its severity (`fatal`) cannot be changed in configuration.
https://docs.rubocop.org/rubocop/1.46/configuration.html#severity
The syntax is invalid but an offense is not registerd:
```console
(snip)
.
```
`Lint/Syntax` detects invalid syntax as …
=> Fix `Lint/Syntax` behavior when `Enabled: false` of `Lint` department

changelog/fix_an_error_for_gemspec_dependency_version.md, lib/rubocop/cop/gemspec/dependency_version.rb, spec/rubocop/cop/gemspec/dependency_version_spec.rb
This PR fixes the following error for `Gemspec/DependencyVersion` when `add_dependency` without version argument and method called on gem name argument:
```ruby
spec.add_dependency('parser'.freeze)
end
```
```console
$ bundle exec rubocop --only Gemspec/DependencyVersion -d
(snip)
undefined method `value' for s(:send,
s(:str, "parser"), :freeze):RuboCop::AST::SendNode
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/gemspec/dependency_version.rb:97:in `allowed_gem?'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/gemspec/dependency_version.rb:84:in `on_send'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/commissioner.rb:143:in `public_send'
``` …
=> Fix an error for `Gemspec/DependencyVersion`

docs/modules/ROOT/pages/configuration.adoc
Follow up #11689.
I read back through the configuration doc and noticed that the description of `DisabledByDefault` behavior was not strict.
This PR updates the doc to consider `Lint/Syntax` which is always enabled.
This makes the description consistent with:
> There is one exception from the general rule above and that is `Lint/Syntax`,
> a special cop that checks for syntax errors before the other cops are invoked.
> It cannot be disabled and its severity (`fatal`) cannot be changed in configuration.
https://docs.rubocop.org/rubocop/1.46/configuration.html#severity
=> [Doc] Tweak the doc for `DisabledByDefault` config

changelog/fix_registers_pry_as_an_offense.md, config/default.yml, spec/rubocop/cop/lint/debugger_spec.rb
Fix for #11658 : `pry` alone is now an offense
=> Fix #11658: registers pry as an offense

lib/rubocop/cli.rb
A small UX improvement. There was a small confusion recently - https://github.com/ruby/rexml/pull/94#discussion_r1134623220
=> Print locations of generated profile files when profiling rubocop

changelog/fix_fix_incorrect_directive_comment_insertion_when.md, lib/rubocop/cop/autocorrect_logic.rb, spec/rubocop/cli/disable_uncorrectable_spec.rb
Fixes #11685.
The problem was that directive comments were inserted inside percent literals and thus had no effect.
So I've added a condition to detect percent array as well as heredoc.
```rb
ARRAY = %i[
AAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBB].freeze
```
=> [Fix #11685] Fix incorrect directive comment insertion when percent array violates `Layout/LineLength` cop

changelog/fix_fix_infinite_loop_when_disable_uncorrectable.md, lib/rubocop/cop/autocorrect_logic.rb, spec/rubocop/cli/disable_uncorrectable_spec.rb
Fixes #11706, follows up #11701.
=> [Fix #11706] Fix infinite loop when `--disable-uncorrectable` option and there is a multi-line percent array violates `Layout/LineLength`

.github/workflows/linting.yml
- Only run if a YML/YAML file or the config is touched
- Remove duplicate permission setting already set at job level
- Pin GitHub Action to tagged version so Dependabot can control version
=> Only run Yamllint CI if required

changelog/fix_fix_a_false_negative_for_layout_extra_spacing_when.md, lib/rubocop/cop/layout/extra_spacing.rb, spec/rubocop/cop/layout/extra_spacing_spec.rb
Closes #11641.
This PR fixes a false negative for `Layout/ExtraSpacing` that caused the first and last comments to be assumed to be aligned when there are many comments with extra spaces.
=> [Fix #11641] Fix a false negative for `Layout/ExtraSpacing` when there are many comments with extra spaces

changelog/new_make_style_class_equality_comparison_aware_of_class_to_s_and_inspect.md, lib/rubocop/cop/style/class_equality_comparison.rb, spec/rubocop/cop/style/class_equality_comparison_spec.rb
Fixes #11699.
This PR makes `Style/ClassEqualityComparison` aware of `Class#to_s` and `Class#inspect` for class equality comparison. `Class#to_s` and `Class#inspect` are aliases for `Class#name`.
=> [Fix #11699] Make `Style/ClassEqualityComparison` aware of `to_s` and `inspect`

changelog/new_support_autocorrection_for_naming_inclusive_language.md, config/default.yml, lib/rubocop/cop/naming/inclusive_language.rb, spec/rubocop/cop/naming/inclusive_language_spec.rb
This PR makes `Naming/InclusiveLanguage` support autocorrection when there is only one suggestion. When there are multiple suggestions, the best suggestion cannot be identified and will not be autocorrected.
=> Support autocorrection for `Naming/InclusiveLanguage`

changelog/fix_a_false_positive_for_lint_useless_method_definition.md, lib/rubocop/cop/lint/useless_method_definition.rb, spec/rubocop/cop/lint/useless_method_definition_spec.rb
Fixes #11704.
This PR fixes a false positive for `Lint/UselessMethodDefinition` when method definition with non access modifier containing only `super` call.
=> [Fix #11704] Fix a false positive for `Lint/UselessMethodDefinition`

.github/workflows/spell_checking.yml
The project offers a GitHub Action directly, so swapping out the custom PIP install setup
=> Use CodeSpell GitHub Action

changelog/fix_fix_a_crash_in_lint_empty_conditional_body.md, lib/rubocop/cop/mixin/comments_help.rb, spec/rubocop/cop/lint/empty_conditional_body_spec.rb
```ruby
var =
unless object.action value:, other:
condition || other_condition # This is the value of `other:`, like so:
end
```
The code above is tricky, because we may think `condition || other_condition` is the body of the condition, however the code is a valid case for the `Lint/EmptyConditionalBody` rule. It is equivalent to:
```ruby
var =
unless object.action value:, other: condition || other_condition
end
```
However, the variable assignment is tricking `CommentsHelp#find_end_line` method into calling an `#end` method of `Parser::Source::Map::Variable` object. `Parser::Source::Map::Variable` **does not respond** to it. Other `Parser::Source::Map` subclasses also do not respond to `#end` methods so we need to check for its existing. `Parser::Source::Map::RescueBody` can be a parent …
=> Fix a crash in `Lint/EmptyConditionalBody`

.github/workflows/spell_checking.yml
How about checking about codespell for hidden files (those starting with ".") and file name as well?
- https://github.com/codespell-project/actions-codespell#parameter-check_filenames
- https://github.com/codespell-project/actions-codespell#parameter-check_hidden
[1]: …
=> Add options to the actions-codespell configuration to check hidden files and file name

changelog/fix_value_omission_false_positive_in.md, lib/rubocop/cop/style/method_call_with_args_parentheses.rb, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
Omitting the parentheses in cases like the example below is ambigious, we don't need to enforce their omission in the `EnforcedStyle: omit_parentheses`
```ruby
var =
unless object.action(value:, other:)
condition || other_condition
end
```
If the parentheses in the condition above are omitted, the semantic of
the code is changed:
```ruby
var =
unless object.action value:, other:
condition || other_condition
end
var =
unless object.action value:, other: condition || other_condition
end
```
We should allow parentheses in value omissions in conditional nodes.
=> Fix value omission false positive in `Style/MethodCallWithArgsParentheses`

changelog/fix_an_error_when_accessing_cache_directory.md, lib/rubocop/server/cache.rb, spec/rubocop/server/cache_spec.rb
Fixes #11725.
This PR fixes an error when insufficient permissions to server cache dir are granted.
=> [Fix #11725] Fix an error when accessing cache directory

changelog/fix_a_false_positive_for_style_if_unless_modifier.md, lib/rubocop/cop/style/if_unless_modifier.rb, spec/rubocop/cop/style/if_unless_modifier_spec.rb
Fixes #11723.
This PR fixes a false positive for `Style/IfUnlessModifier` when using one-line pattern matching as a `if` condition.
=> [Fix #11723] Fix a false positive for `Style/IfUnlessModifier`

changelog/fix_ensure_default_configuration_loads.md, lib/rubocop/config.rb, spec/rubocop/config_spec.rb, spec/rubocop/cop/mixin/enforce_superclass_spec.rb
Fixes #11715.
There was an issue where the default configuration was not loaded when instantiating cop with no arguments. This patch ensures default configuration by passing `RuboCop::ConfigLoader.default_configuration` to `RuboCop::Config.new` default argument.
=> [Fix #11715] Ensure default configuration loads

changelog/fix_lint_syntax_when_only_option.md, lib/rubocop/options.rb, spec/rubocop/cli/options_spec.rb
Fixes #11697.
This PR fixes `Lint/Syntax` behavior when `--only` is not given the cop name. The cop must always be executed.
=> [Fix #11697] Fix `Lint/Syntax` behavior when using `--only` option

changelog/new_make_style_map_to_hash_and_map_to_set_aware_of_symbol_proc.md, lib/rubocop/cop/style/map_to_hash.rb, lib/rubocop/cop/style/map_to_set.rb, spec/rubocop/cop/style/map_to_hash_spec.rb, spec/rubocop/cop/style/map_to_set_spec.rb
Fixes #11732.
This PR makes `Style/MapToHash` and `Style/MapToSet` aware of symbol proc.
=> [Fix #11732] Make `Style/MapToHash` and `Style/MapToSet` aware of symbol proc

lib/rubocop/cop/style/redundant_string_escape.rb
Follow up: https://github.com/rubocop/rubocop/pull/11694#discussion_r1147219922
=> Remove redundant module mix-in for `Style/RedundantStringEscape`

changelog/new_fix_an_error_for_layout_hash_alignment.md, rubocop.gemspec, spec/rubocop/cop/layout/hash_alignment_spec.rb
Fixes #11730.
This PR fixes an error for `Layout/HashAlignment` when using anonymous keyword rest arguments.
=> [Fix #11730] Fix an error for `Layout/HashAlignment`

changelog/new_make_style_map_to_hash_and_map_to_set_aware_of_numblock.md, lib/rubocop/cop/style/map_to_hash.rb, lib/rubocop/cop/style/map_to_set.rb, spec/rubocop/cop/style/map_to_hash_spec.rb, spec/rubocop/cop/style/map_to_set_spec.rb
I noticed it when working on https://github.com/rubocop/rubocop/pull/11735.
This PR makes `Style/MapToHash` and `Style/MapToSet` aware of numbered parameters.
=> Make `Style/MapToHash` and `Style/MapToSet` aware of numblock

lib/rubocop/cop/style/hash_syntax.rb
It's not obvious that "either" also allows mixed style.
=> Add good example for Style/HashSyntax EnforcedShorthandSyntax: either

changelog/fix_fix_a_false_positive_for_lint-nested_method_definition.md, lib/rubocop/cop/lint/nested_method_definition.rb, spec/rubocop/cop/lint/nested_method_definition_spec.rb
This PR fix a false positive for `Lint/NestedMethodDefinition` when nested definition inside `*_eval` and `*_exec` method call with a numblock.
```ruby
class Foo
def x(obj)
obj.instance_eval do
@bar = _1
def y
end
end
end
end
class Foo
def x(obj)
obj.instance_exec(3) do
@bar = _1
def y
end
end
end
end
```
=> Fix a false positive for `Lint/NestedMethodDefinition` when nested definition inside `*_eval` and `*_exec` method call with a numblock

changelog/fix_error_handling_in_bundler_standalone_mode.md, lib/rubocop/cli/command/execute_runner.rb
When RuboCop errors, it prints a message that includes the issue tracker URL. It pulls this URL from the gem spec metadata.
Relying on the gem spec can cause problems in bundler standalone mode, where everything is set up by the standalone file and `Gem.loaded_specs` is not populated with the bundled gems.
```
$ bundle init
$ bundle add rubocop --skip-install
$ bundle install --standalone
$ ruby -r ./bundle/bundler/setup.rb -e 'require "rubocop"; Gem.loaded_specs["bundler"].metadata['bug_tracker_uri']'
undefined method `metadata' for nil:NilClass (NoMethodError)
```
This means that if RuboCop errors, instead of a helpful error message we get a cryptic error that masks the underlying problem. We've seen this a number of times at GitHub (although mostly when developing our own internal cops …
=> Fix error when trying to display error message

changelog/new_make_layout_end_alignment_aware_of_pattern_matching.md, lib/rubocop/cop/layout/end_alignment.rb, spec/rubocop/cop/layout/end_alignment_spec.rb
This PR makes `Layout/EndAlignment` aware of pattern matching.
=> Make `Layout/EndAlignment` aware of pattern matching

changelog/change_use_the_path_given_by_cache_root_to_be_the_parent.md, lib/rubocop/result_cache.rb, spec/rubocop/result_cache_spec.rb
=> [Fix #10766] Use the path given by `--cache-root` to be the parent for  `rubocop_cache` dir like other ways to specify it

changelog/new_make_metrics_block_nesting_aware_of_numbered_parameter.md, lib/rubocop/cop/metrics/block_nesting.rb, spec/rubocop/cop/metrics/block_nesting_spec.rb
This PR makes `Metrics/BlockNesting` aware of numbered parameter.
=> Make `Metrics/BlockNesting` aware of numbered parameter

changelog/fix_false_positive_for_style_redundant_line_continuation.md, lib/rubocop/cop/style/redundant_line_continuation.rb, spec/rubocop/cop/style/redundant_line_continuation_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/11694#issuecomment-1493936758
This PR fixes a false positive for `Style/RedundantLineContinuation` when using line concatenation and calling a method without parentheses.
=> Fix a false positive for `Style/RedundantLineContinuation`

changelog/fix_a_false_positive_for_redundant_line_continuation.md, lib/rubocop/cop/style/redundant_line_continuation.rb, spec/rubocop/cop/style/redundant_line_continuation_spec.rb
Fixes #11758.
This PR fixes a false positive for `Style/RedundantLineContinuation` when line continuations for string.
=> [Fix #11758] Fix a false positive for `Style/RedundantLineContinuation`

changelog/fix_an_incorrect_autocorrect_for_class_equality_comparison.md, lib/rubocop/cop/style/class_equality_comparison.rb, spec/rubocop/cop/style/class_equality_comparison_spec.rb
Fixes #11762.
This PR fixes an incorrect autocorrect for `Style/ClassEqualityComparison` when comparing a variable or return value for equality.
when a variable or return value of a method is used, it cannot be suggested and safe autocorrected because the type is not known. So this PR tweaks the cop that doesn't suggest `instance_of` argument at those times and doesn't autocorrect. Anyway, detection is possible.
=> [Fix #11762] Fix an incorrect autocorrect for `Style/ClassEqualityComparison`

config/default.yml, lib/rubocop/cop/style/file_empty.rb
This PR remove `SafeAutoCorrect: false` from `Style/FileEmpty`, `Style/NumericPredicate` and update the documentation.
It seems that other cops also appear to be choosing one or the other, so I thought it would be best to set only one of them to false for this cop. WDYT? …
=> Remove redundant `SafeAutoCorrect: false`

changelog/fix_an_error_for_style_multiline_method_signature.md, lib/rubocop/cop/style/multiline_method_signature.rb, spec/rubocop/cop/style/multiline_method_signature_spec.rb
Fixes #11765.
This PR fixes an error for `Style/MultilineMethodSignature` when line break after `def` keyword.
It seems preferable that the following cases can be detected by a new different cop:
```ruby
def
method_name arg; end
```
This is probably not a common line break, the new cop will be able to handle `class`, `module`, class method definitions, and others as well.
And this `Style/MultilineMethodSignature` cop is disabled by default, but I have a feeling that the new cop can be enabled by default.
=> [Fix #11765] Fix an error for `Style/MultilineMethodSignature`

changelog/new_make_layout_class_structure_aware_of_singleton_class.md, lib/rubocop/config_loader.rb, lib/rubocop/cop/layout/class_structure.rb, spec/rubocop/cop/layout/class_structure_spec.rb
It is necessary to consider how to handle module better, but singleton class (`class << self`) can be handled in the same way as class. Because they are both `class`.
Also this PR fixes the following new offense:
```console
(snip)
Offenses:
lib/rubocop/config_loader.rb:168:7: C: [Correctable] Layout/ClassStructure: constants is supposed to appear before public_methods.
PENDING_BANNER = <<~BANNER
^^^^^^^^^^^^^^^^^^^^^^^^^^
1481 files inspected, 1 offense detected, 1 offe
```
=> Make `Style/ClassStructure` aware of singleton class

changelog/new_make_style_trailing_body_on_class_aware_of_singleton_class.md, lib/rubocop/cop/style/trailing_body_on_class.rb, spec/rubocop/cop/style/trailing_body_on_class_spec.rb
This PR makes `Style/TrailingBodyOnClass` aware of singleton class. So, singleton class can be handled in the same way as class.
=> Make `Style/TrailingBodyOnClass` aware of singleton class

changelog/new_make_metrics_class_length_aware_of_singleton_class.md, lib/rubocop/cop/metrics/class_length.rb, lib/rubocop/cop/metrics/utils/code_length_calculator.rb, spec/rubocop/cop/metrics/class_length_spec.rb, spec/rubocop/cop/metrics/utils/code_length_calculator_spec.rb
This PR makes `Metrics/ClassLength` aware of singleton class. It can detect singleton class length with the same matrix as normal class length.
=> Make `Metrics/ClassLength` aware of singleton class

changelog/new_make_lint_redundant_string_coercion_aware_of_print_method_arguments.md, lib/rubocop/cop/lint/redundant_string_coercion.rb, spec/rubocop/cop/lint/redundant_string_coercion_spec.rb, spec/rubocop/runner_formatter_invocation_spec.rb
This PR makes `Lint/RedundantStringCoercion` aware of print method arguments. The name of this cop is "RedundantStringCoercion", so it makes more sense to extend the feature than to provide a new cop I think.
=> Make `Lint/RedundantStringCoercion` aware of print method arguments

changelog/fix_false_negatives_for_style_parallel_assignment.md, lib/rubocop/cop/style/parallel_assignment.rb, spec/rubocop/cop/style/parallel_assignment_spec.rb
This PR fix false negatives for `Style/ParallelAssignment` when Ruby 2.7+. Because AST changed between Ruby 2.6 and Ruby 2.7 as follows:
```console
$ ruby-parse --26 -e "a, b = 1, 2 rescue foo"
(rescue
(masgn
(mlhs
(lvasgn :a)
(lvasgn :b))
(array
(int 1)
(int 2)))
(resbody nil nil
(send nil :foo)) nil)
```
```console
$ ruby-parse --27 -e "a, b = 1, 2 rescue foo"
(masgn
(mlhs
(lvasgn :a)
(lvasgn :b))
(rescue
(array
(int 1)
(int 2))
(resbody nil nil
(send nil :foo)) nil))
```
This PR makes `Style/ParallelAssignment` to handle both AST.
Refer: https://github.com/ruby/ruby/commit/53b3be5d58a9bf1efce229b3dce723f96e820c79
=> Fix false negatives for `Style/ParallelAssignment`

changelog/fix_a_false_positive_for_lint_duplicate_match_pattern.md, lib/rubocop/cop/lint/duplicate_match_pattern.rb, spec/rubocop/cop/lint/duplicate_match_pattern_spec.rb
Fixes #11787
This PR fixes a false positive for `Lint/DuplicateMatchPattern` when repeated `in` patterns but different `if` guard is used.
=> [Fix #11787] Fix a false positive for `Lint/DuplicateMatchPattern`

changelog/fix_an_error_for_lint_duplicate_match_pattern.md, lib/rubocop/cop/lint/duplicate_match_pattern.rb, spec/rubocop/cop/lint/duplicate_match_pattern_spec.rb
Fixes #11792.
This PR fixes an error for `Lint/DuplicateMatchPattern` when using hash pattern with `if` guard.
=> [Fix #11792] Fix an error for `Lint/DuplicateMatchPattern`

changelog/fix_mark_style_invertible_unless_condition_as_unsafe.md, config/default.yml
Fixes #11800.
This PR marks `Style/InvertibleUnlessCondition` as unsafe. `@safety` is already documented:
https://github.com/rubocop/rubocop/blob/v1.50.1/lib/rubocop/cop/style/invertible_unless_condition.rb#L20-L23
=> [Fix #11800] Mark `Style/InvertibleUnlessCondition` as unsafe

docs/modules/ROOT/pages/cops_gemspec.adoc, lib/rubocop/cop/gemspec/deprecated_attribute_assignment.rb
[ci skip]
Hello, I'm not a native English speaker, this looks like a typo but I'm not sure
=> Fix typo in DeprecatedAttributeAssignment cop

lib/rubocop/cop/style/redundant_fetch_block.rb
Fixes #11803.
This PR adds a note to the doc for `Style/RedundantFetchBlock` about the difference in behavior between enabled and disabled frozen string magic literal comment.
=> [Fix #11803] Update the doc for `Style/RedundantFetchBlock`

.circleci/config.yml, .github/workflows/rubocop.yml, .mergify.yml, .rubocop.yml, README.md, changelog/change_drop_ruby_26.md, config/default.yml, docs/modules/ROOT/pages/compatibility.adoc, lib/rubocop/config_obsoletion.rb, lib/rubocop/cop/correctors/alignment_corrector.rb, lib/rubocop/cop/internal_affairs/node_matcher_directive.rb, lib/rubocop/cop/layout/heredoc_argument_closing_parenthesis.rb, lib/rubocop/cop/lint/out_of_range_regexp_ref.rb, lib/rubocop/cop/style/conditional_assignment.rb, lib/rubocop/cop/style/percent_literal_delimiters.rb, lib/rubocop/cop/style/special_global_vars.rb, lib/rubocop/cop/team.rb, lib/rubocop/rspec/cop_helper.rb, lib/rubocop/target_ruby.rb, lib/rubocop/version.rb, rubocop.gemspec, spec/project_spec.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cli_spec.rb, spec/rubocop/cop/gemspec/required_ruby_version_spec.rb, spec/rubocop/cop/lint/circular_argument_reference_spec.rb, spec/rubocop/cop/lint/syntax_spec.rb, spec/rubocop/target_ruby_spec.rb, spec/rubocop/version_spec.rb, tasks/spec_runner.rake
This PR drops Ruby 2.6 runtime support. The next release will be the time to drop Ruby 2.6 support:
- https://www.ruby-lang.org/en/downloads/branches/
- https://docs.rubocop.org/rubocop/compatibility.html#support-matrix
CRuby 2.6 compatible JRuby 9.3 will be dropped and CRuby 2.7 compatible JRuby 9.4+ is required.
=> Drop Ruby 2.6 runtime support

changelog/fix_an_incorrect_autocorrect_for_naming_rescued_exceptions_variable_name.md, lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb, spec/rubocop/cop/naming/rescued_exceptions_variable_name_spec.rb
Fixes #11809.
This PR fixes an incorrect autocorrect for `Naming/RescuedExceptionsVariableName` when exception variable is referenced after `rescue` statement.
=> [Fix #11809] Fix an incorrect autocorrect for `Naming/RescuedExceptionsVariableName`

changelog/new_make_collection_compact_aware_of_delete_if.md, lib/rubocop/cop/style/collection_compact.rb, spec/rubocop/cop/style/collection_compact_spec.rb
This PR makes `Style/CollectionCompact` aware of `delete_if`.
Note, `Enumerator` does not have `delete_if`, the following use case are allowed:
```ruby
% ruby -ve '[1, 2, 3].to_enum.delete_if { |e| e.nil? }'
ruby 3.3.0dev (2023-03-17T00:50:41Z master f29c9d6d36) [x86_64-darwin19]
-e:1:in `<main>': undefined method `delete_if' for an instance of Enumerator (NoMethodError)
[1, 2, 3].to_enum.delete_if { |e| e.nil? }
^^^^^^^^^^
```
It doesn't register an offense as well as `to_enum` when `lazy` is used.
=> Make `Style/CollectionCompact` aware of `delete_if`

changelog/fix_a_false_negative_for_style_attr.md, lib/rubocop/cop/style/attr.rb, lib/rubocop/result_cache.rb, spec/rubocop/cop/style/attr_spec.rb
Fixes #11812.
This PR fixes a false negative for `Style/Attr` when using `attr` and method definitions.
=> [Fix #11812] Fix a false negative for `Style/Attr`

changelog/new_add_autocorrection_for_lint_ambiguous_block_association.md, lib/rubocop/cop/lint/ambiguous_block_association.rb, spec/rubocop/cop/lint/ambiguous_block_association_spec.rb
This autocorrection assumes the current code behavior is correct and fills in the missing parentheses. So this is a safe autocorrection because the behavior does not change before and after the change.
=> Add autocorrection for `Lint/AmbiguousBlockAssociation`

changelog/fix_lint_empty_conditional_body_false_positives.md, lib/rubocop/cop/mixin/comments_help.rb, spec/rubocop/cop/lint/empty_conditional_body_spec.rb
=> [Fix #11820] Fix `Lint/EmptyConditionalBody` false-positives for commented empty `elsif` body

docs/modules/ROOT/pages/extensions.adoc
Adding `rubocop-sketchup` to the list of known third party extensions.
=> Add rubocop-sketchup to list of third party extensions.

changelog/fix_an_error_for_layout_space_inside_block_braces.md, lib/rubocop/cop/layout/space_inside_block_braces.rb, spec/rubocop/cop/layout/space_inside_block_braces_spec.rb
Fixes #11822.
This PR fixes an error for `Layout/SpaceInsideBlockBraces` when a method call with a multiline block is used as an argument.
=> [Fix #11822] Fix an error for `Layout/SpaceInsideBlockBraces`

changelog/new_add_autocorrection_for_top_level_return_with_argument.md, lib/rubocop/cop/lint/top_level_return_with_argument.rb, spec/rubocop/cop/lint/top_level_return_with_argument_spec.rb
I have added an autocorrection that simply removes the argument part from top-level `return`.
=> Add autocorrection for `Lint/TopLevelReturnWithArgument`

changelog/change_exclude_non_standard_ruby_files_from.md, config/default.yml
Since non-standard Ruby files such as `*.jb` and so on are expected to be used via `eval` or equivalent, it would be better to exclude them from this Cop's inspection to reduce false positives.
See also the following discussion for more information:
- https://github.com/rubocop/rubocop/pull/11825#issuecomment-1527002005
The patterns specified in `Exclude` are based from `default_configuration['AllCops']['Include']`, excluding the following patterns:
- `**/*.rb`
- `**/*.rbw`
- `**/*.rbx`
- `**/*.ruby`
=> Exclude `**/*.jb` from `Lint/TopLevelReturnWithArgument`

changelog/fix_an_error_for_style_if_unless_modifier.md, lib/rubocop/cop/style/if_unless_modifier.rb, spec/rubocop/cop/style/if_unless_modifier_spec.rb
This PR fixes the following error for `Style/IfUnlessModifier` when using multiple `if` modifier in the long one line:
```ruby
return value if items.filter_map { |item| item.loooooooooooooooooooooooooooooooooooooooooooooooooooog if item.something? }
```
```console
$ bundle exec rubocop --only Style/IfUnlessModifier -a -d
(snip)
Scanning /Users/koic/src/github.com/koic/rubocop-issues/if_unless_modifier/example.rb
An error occurred while Style/IfUnlessModifier cop was inspecting /Users/koic/src/github.com/koic/rubocop-issues/if_unless_modifier/example.rb:1:42.
```
=> Fix an error for `Style/IfUnlessModifier`

changelog/fix_a_false_positive_for_style_redundant_line_continuation.md, lib/rubocop/cop/style/redundant_line_continuation.rb, spec/rubocop/cop/style/redundant_line_continuation_spec.rb
Fixes #11844.
This PR fixes a false positive for `Style/RedundantLineContinuation` when using line concatenation for assigning a return value and without argument parentheses.
=> [Fix #11844] Fix a false positive for `Style/RedundantLineContinuation`

changelog/fix_a_false_positive_for_lint_redundant_string_coercion.md, lib/rubocop/cop/lint/redundant_string_coercion.rb, spec/rubocop/cop/lint/redundant_string_coercion_spec.rb
Fixes #11846.
This PR fixes a false positive for `Lint/RedundantStringCoercion` when using `to_s(argument)` in `puts` argument.
=> [Fix #11846] Fix a false positive for `Lint/RedundantStringCoercion`

changelog/new_add_autocorrection_for_naming_memoized_instance_variable_name.md, lib/rubocop/cop/naming/memoized_instance_variable_name.rb, spec/rubocop/cop/naming/memoized_instance_variable_name_spec.rb
I have implemented a simple autocorrection that simply changes the variables names to suggested ones.
=> Add autocorrection for `Naming/MemoizedInstanceVariableName`

changelog/new_add_autocorrection_for_lint_void.md, lib/rubocop/cop/lint/void.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/lint/void_spec.rb, spec/rubocop/cop/team_spec.rb
To complement the `Lint/UselessAssignment` autocorrection proposed in #11840, I thought it would be nice to have `Lint/Void` autocorrection as well.
- https://github.com/rubocop/rubocop/pull/11840
=> Add autocorrection for `Lint/Void`

changelog/fix_an_incorrect_autocorrect_for_style_eval_with_location.md, lib/rubocop/cop/style/eval_with_location.rb, spec/rubocop/cop/style/eval_with_location_spec.rb
Fixes #11852.
This PR fixes an incorrect autocorrect for `Style/EvalWithLocation` when using `eval` without line number and with parenthesized method call.
=> [Fix #11852] Fix an incorrect autocorrect for `Style/EvalWithLocation`

lib/rubocop/cop/style/combinable_loops.rb
I found a comment that mentions compatibility with Ruby 2.6-. Since this cop already requires Ruby 2.7 or higher at its gemspec, I think it's safe to remove this `to_s`.
- https://github.com/rubocop/rubocop/pull/11791
=> Remove unnecessary `Symbol#to_s` used for Ruby 2.6- compatibility

changelog/new_add_autocorrection_for_style_combinable_loops.md, lib/rubocop/cop/style/combinable_loops.rb, spec/rubocop/cop/style/combinable_loops_spec.rb
As long as the offense is not a false positive, I believe this autocorrection would be safe.
What I am a little concerned about now is what the outcome should be if there are comments in between 🤔 
=> Add autocorrection for `Style/CombinableLoops`

changelog/fix_an_error_for_style_conditional_assignment.md, lib/rubocop/cop/style/conditional_assignment.rb, spec/rubocop/cop/style/conditional_assignment_assign_in_condition_spec.rb
Fixes #11849.
This PR fixes an error for `Style/ConditionalAssignment` when `EnforcedStyle: assign_inside_condition` and using empty `case` condition.
=> [Fix #11849] Fix an error for `Style/ConditionalAssignment`

lib/rubocop/config.rb, lib/rubocop/cop/base.rb
When debugging errors, cops and configs may be inspected as part of error messages.
Extremely long error messages can be problematic when debugging, as they may exhaust the terminal scrollback buffer, without the visible portion necesarily providing useful information.
Because the config typically contains at least the entire default config, its `inspect` output is unusably long.
Because cops contain many instance variables relating to the file being investigated (which may be long), their `inspect` output is often unusably long.
Simplifying the `inspect` output for such objects makes error output more usable, and is a technique used in other gems, such as Rails.
* ~Commit message starts with `[Fix …
=> Simplify `inspect` output

changelog/new_add_autocorrection_for_lint_useless_assignment.md, config/default.yml, lib/rubocop/cop/lint/useless_assignment.rb, lib/rubocop/cop/variable_force/assignment.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cli/options_spec.rb, spec/rubocop/cli_spec.rb, spec/rubocop/cop/lint/useless_assignment_spec.rb, spec/rubocop/cop/team_spec.rb
As discussed in https://github.com/rubocop/rubocop/issues/11597, this autocorrection does not take care of responsibilities that should be handled by `Lint/Void`.
- https://github.com/rubocop/rubocop/pull/11848
=> Add autocorrection for `Lint/UselessAssignment`

changelog/fix_find_end_line_for_blocks.md, lib/rubocop/cop/mixin/comments_help.rb, spec/rubocop/cop/style/symbol_proc_spec.rb
When two block nodes are in the root, e.g.
```ruby
block1 do
end
block2 do
end
```
calling `find_end_line` on the second will return `1` instead of `7`.
=> Fix `find_end_line` for block nodes.

docs/modules/ROOT/pages/development.adoc
It may not be obvious to contributors how to resolve the problem of correction clobbering, requiring investigation to find a solution.
This documents the problem and typical solution, for better discoverability.
* ~Added tests.~
=> Add dev docs on preventing correction clobbering

changelog/change_add_rubocop_factory_bot_to_suggested_extensions.md, config/default.yml, docs/modules/ROOT/pages/extensions.adoc
This PR adds [rubocop-factory_bot](https://github.com/rubocop/rubocop-factory_bot) to the `SuggestExtensions` list and extension doc.
=> Add rubocop-factory_bot to suggested extensions and extension doc

changelog/fix_a_false_positive_for_layout_space_after_semicolon.md, lib/rubocop/cop/mixin/space_after_punctuation.rb, spec/rubocop/cop/layout/space_after_semicolon_spec.rb
Fixes #11861.
This PR fixes a false positive for `Layout/SpaceAfterSemicolon` when no space between a semicolon and a closing brace of string interpolation.
=> [Fix #11861] Fix a false positive for `Layout/SpaceAfterSemicolon`

changelog/fix_a_false_positive_for_naming_constant_name.md, lib/rubocop/cop/naming/constant_name.rb, spec/rubocop/cop/naming/constant_name_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/8422#issuecomment-1540027264.
This PR fixes an error for `Naming/ConstantName` when assigning a constant from an empty branch of `else`.
=> Fix an error for `Naming/ConstantName`

changelog/new_make_semicolon_aware_of_string_interpolation.md, lib/rubocop/cop/style/semicolon.rb, spec/rubocop/cop/style/semicolon_spec.rb
Follow up https://github.com/rubocop/rubocop/issues/11861.
> I would probably expect rubocop to get rid of that semicolon, but that's a bonus.
This PR makes `Style/Semicolon` aware of redundant semicolons in string interpolation braces.
=> Make `Style/Semicolon` aware of string interpolation

changelog/fix_an_error_for_style_if_inside_else.md, lib/rubocop/cop/style/if_inside_else.rb, spec/rubocop/cop/style/if_inside_else_spec.rb
This PR fixes the following error for `Style/IfInsideElse` when a deep nested multiline `if...then...elsif...else...end`:
```console
if cond
else
if nested_one
else
if c
if d
else
if e
end
end
end
end
end
```
```console
$ bundle exec rubocop --only Style/IfInsideElse -a
An error occurred while Style/IfInsideElse cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/if_inside_else/example.rb:6:6.
C
Offenses:
example.rb:3:3: C: [Corrected] Style/IfInsideElse: Convert if nested inside else to elsif.
if nested_one
^^
example.rb:5:5: C: [Corrected] Style/IfInsideElse: Convert if nested inside else to elsif.
if c
^^
example.rb:6:9: C: [Corrected] Style/IfInsideElse: Convert if nested inside else to …
```
=> Fix an error for `Style/IfInsideElse`

changelog/change_mark_some_cops_as_unsafe.md, config/default.yml, spec/project_spec.rb
This PR marks `Style/DataInheritance` as unsafe autocorrect, `Style/OpenStructUse` as unsafe, and `Security/CompoundHash` as unsafe.
This PR adds a project spec as the below and marks `Style/DataInheritance` as unsafe autocorrect:
```console
$ bundle exec rspec spec/project_spec.rb
(snip)
Failures:
1) RuboCop Project default configuration file does not detect missing `Safe: false` and `SafeAutoCorrect: false`
Failure/Error:
expect(unsafe).to(
be(true),
"`#{cop_name}` cop should be set `Safe: false` or `SafeAutoCorrect: false` " \
'because `@safety` YARD tag exists.'
)
`Style/DataInheritance` cop should be set `Safe: false` or `SafeAutoCorrect: false` because `@safety` YARD tag exists.
Finished in 0.25698 seconds (files took 1.13 seconds to load)
1 example, 1 failure
rspec …
```
=> Mark some cops as unsafe

changelog/fix_a_false_positive_for_lint_incompatible_io_select_with_fiber_scheduler.md, lib/rubocop/cop/lint/incompatible_io_select_with_fiber_scheduler.rb, spec/rubocop/cop/lint/incompatible_io_select_with_fiber_scheduler_spec.rb
This PR fixes a false positive for `Lint/IncompatibleIoSelectWithFiberScheduler` when using excepts argument.
AFAIK, `IO.wait_readable` and `IO.wait_writable` cannot replace IO objects waiting for exceptions.
=> Fix a false positive for `Lint/IncompatibleIoSelectWithFiberScheduler`

changelog/new_add_comparisons_threshold_to_multiple_comparison.md, config/default.yml, lib/rubocop/cop/style/multiple_comparison.rb, spec/rubocop/cop/style/multiple_comparison_spec.rb
I want to use `Style/MultipleComparison`, but only when at least 3 comparisons are made. It enforces this style when there are 2. Personally, I do not see much benefit for myself from this in most of the cases. So I made this value configurable, while preserving the original value of 2.
=> Add `MinComparisonsCount` config option to `Style/MultipleComparison`

changelog/fix_a_false_positive_for_style_select_by_regexp.md, lib/rubocop/cop/style/select_by_regexp.rb, spec/rubocop/cop/style/select_by_regexp_spec.rb
This PR fixes a false positive for `Style/SelectByRegexp` when using regexp mismatching with Ruby 2.2 or lower because `grep_v` requires Ruby 2.3+.
=> Fix a false positive for `Style/SelectByRegexp` when Ruby 2.2 or lower analysis

changelog/fix_a_false_positive_for_style_exact_regexp_match.md, lib/rubocop/cop/style/exact_regexp_match.rb, spec/rubocop/cop/style/exact_regexp_match_spec.rb
Fixes #11880.
This PR fixes a false positive for `Style/ExactRegexpMatch` when using literal with quantifier in regexp.
=> [Fix #11880] Fix a false positive for `Style/ExactRegexpMatch`

changelog/fix_display_factory_bot_version_when_verbose_version.md, lib/rubocop/version.rb, spec/rubocop/version_spec.rb
Fixes #11884.
This PR makes `rubocop -V` display rubocop-factory_bot version when using it.
Also, the rubocop-capybara version is already displaying up fine, but this PR adds a spec for that because it lacks the spec when extracted rubocop-capybara and rubocop-factory_bot from rubocop-rspec.
=> [Fix #11884] Make `rubocop -V` display rubocop-factory_bot version when using it

spec/rubocop/cli/suggest_extensions_spec.rb, spec/rubocop/cop/layout/comment_indentation_spec.rb, spec/rubocop/cop/layout/extra_spacing_spec.rb, spec/rubocop/cop/layout/space_around_operators_spec.rb, spec/rubocop/cop/lint/unified_integer_spec.rb, spec/rubocop/cop/naming/variable_number_spec.rb, spec/rubocop/cop/range_help_spec.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb, spec/rubocop/cop/style/ternary_parentheses_spec.rb, spec/rubocop/cop/visibility_help_spec.rb, spec/rubocop/formatter/offense_count_formatter_spec.rb, spec/support/multiline_literal_brace_layout_examples.rb, spec/support/multiline_literal_brace_layout_trailing_comma_examples.rb
- Drops a number of unused `let`s.
- In one case, I attempted to recreate what appeared to be the intent of the spec. Happy to do something different if preferred as it seems like the test passes with or without the configuration overridden.
- Generally just test-driving a release of my [`rspectre`](https://github.com/dgollahon/rspectre) tool on popular repos
=> Remove superfluous test setup

docs/modules/ROOT/pages/integration_with_other_tools.adoc
This adds a note about RuboCop integration with the [Helix Editor](https://helix-editor.com/). For more info on the underlying implementation, see here: https://docs.helix-editor.com/languages.html#language-configuration
> `formatter` The  formatter for the language, it will take precedence over the lsp when  defined. The formatter must be able to take the original file as input  from stdin and write the formatted file to stdout
=> Add integration info for Helix Editor

changelog/fix_a_false_negative_for_lint_redundant_safe_navigation.md, lib/rubocop/cop/lint/redundant_safe_navigation.rb, spec/rubocop/cop/lint/redundant_safe_navigation_spec.rb
This PR fixes a false negative for `Lint/RedundantSafeNavigation` when `&.` is used for `to_d`.
=> Fix a false negative for `Lint/RedundantSafeNavigation`

changelog/fix_accessor_grouping_macros_and_accessors_space.md, lib/rubocop/cop/style/accessor_grouping.rb, spec/rubocop/cop/style/accessor_grouping_spec.rb
Fixes #11891.
I changed this cop to consider some code, which precedes accessors, as annotations if there is no space between them.
=> Fix `Style/AccessorGrouping` to accept macros separated from accessors by space

changelog/fix_false_positive_for_lint_inherit_exception.md, lib/rubocop/cop/lint/inherit_exception.rb, spec/rubocop/cop/lint/inherit_exception_spec.rb
Fixes #11893.
This PR fixes a false positive for `Lint/InheritException` when inheriting `Exception` with omitted namespace.
=> [Fix #11893] Fix a false positive for `Lint/InheritException`

changelog/fix_offences_in_calls_inside_blocks_with_braces.md, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
For the `omit_parentheses` enforced style, I noticed that calls with parentheses in calls **inside** braced blocks were not linted in a code base of mine, so I investigated. It turned out I had a bad detection of the callers that the braced blocks are attached to, they do **need** the parentheses for the call to be syntactically correct. However, the detection leaked into the calls inside the braces that **don't need** the parentheses.
Example:
```ruby
client.images.map { Image.new _1 }
```
```lisp
(numblock
(send
(send
(send nil :client) :images) :map) 1
(send
(const nil :Image) :new
(lvar :_1)))
```
Here, `(send (const nil :Image) :new (lvar :_1)))`, was considered a **call with braced block**, because the detection used to check for the parent node being a block node. This is not …
=> Fix offences in calls inside blocks with braces for Style/MethodCallWithArgsParentheses

changelog/fix_an_incorrect_autocorrect_for_style_single_line_methods.md, lib/rubocop/cop/style/single_line_methods.rb, spec/rubocop/cop/style/single_line_methods_spec.rb
Fixes #11899.
This PR fixes an incorrect autocorrect for `Style/SingleLineMethods` when using Ruby 3.0 and `Style/EndlessMethod` is disabled.
This is an overlooked bug due to the lack of `:ruby30` in the target test code.
=> [Fix #11899] Fix an incorrect autocorrect for `Style/SingleLineMethods`

changelog/fix_a_false_positive_for_style_require_order.md, lib/rubocop/cop/style/require_order.rb, spec/rubocop/cop/style/require_order_spec.rb
This PR fixes a false positive for `Style/RequireOrder` when single-quoted string and double-quoted string are mixed.
=> Fix a false positive for `Style/RequireOrder`

changelog/fix_an_error_for_lint_useless_assignment.md, lib/rubocop/cop/lint/useless_assignment.rb, lib/rubocop/cop/variable_force.rb, lib/rubocop/cop/variable_force/assignment.rb, spec/rubocop/cop/lint/useless_assignment_spec.rb, spec/rubocop/cop/variable_force/assignment_spec.rb
Fixes #11905.
This PR fixes an error for `Lint/UselessAssignment` when a variable is assigned with rest assignment and unreferenced.
=> [Fix #11905] Fix an error for `Lint/UselessAssignment`

config/default.yml, spec/project_spec.rb
This PR adds a spec to detect a redundant `SafeAutoCorrect: false` config and remove the detected redundant config:
```console
% bundle exec rspec  spec/project_spec.rb
(snip)
Failures:
1) RuboCop Project default configuration file does not include unnecessary `SafeAutoCorrect: false`
Failure/Error:
expect(safe_autocorrect).not_to(
be(false), "`#{cop_name}` has unnecessary `SafeAutoCorrect: false` config."
)
`Lint/UselessSetterCall` has unnecessary `SafeAutoCorrect: false` config.
Finished in 2.48 seconds (files took 1.19 seconds to load)
205 examples, 1 failure
```
=> Remove a redundant `SafeAutoCorrect: false` config

changelog/new_support_allowed_receivers_for_style_collection_compact.md, config/default.yml, lib/rubocop.rb, lib/rubocop/cop/mixin/allowed_receivers.rb, lib/rubocop/cop/style/collection_compact.rb, lib/rubocop/cop/style/hash_each_methods.rb, spec/rubocop/cop/style/collection_compact_spec.rb
Fixes #11908.
This PR supports `AllowedReceivers` for `Style/CollectionMethods`. For example, by setting `AllowedReceivers: ['params']` in RuboCop Rails or user configuration, the following false positive for `params` can be prevented:
```ruby
def selection_params(current, last_category = nil, params = {})
params.merge(
category_id: current.is_a?(Category) ? current.to_param : last_category.to_param,
site_id: current.is_a?(Site) ? current.to_param : nil,
).delete_if { |_k, v| v.nil? }
end
```
The configuration to `params` is not set in the RuboCop core due to Rails specific issues. So if this approach is accepted, I will add it to RuboCop Rails's default configuration.
[1]: …
=> [Fix #11908] Support `AllowedReceivers` for `Style/CollectionMethods`

changelog/fix_server_mode_only_read_stdin_when_s_or_stdin.md, lib/rubocop/server/client_command/exec.rb, spec/rubocop/server/client_command/exec_spec.rb
When using `--server` in a non-tty environment, rubocop hangs reading
STDIN. Avoid this by only reading STDIN when the `-s` or `--stdin`
arguments are provided, in which case text on STDIN is expected.
This change allows `rubocop --server` to be used in non-tty contexts,
such as File Watchers or External Tools in RubyMine.
=> Server mode: only read $stdin when -s or --stdin argument provided

changelog/fix_switch_back_the_docs_version.md, lib/rubocop/cop/lint/redundant_safe_navigation.rb, spec/rubocop/cop/lint/redundant_safe_navigation_spec.rb
A Rails project I work on has code vaguely similar
```rb
maybe_time&.to_s(:iso8601) || '(Unknown)'
```
The changes made in https://github.com/rubocop/rubocop/pull/11890 cause `Lint/RedundantSafeNavigation` to suggest removing the safe navigation from the above code. This has been discussed before in https://github.com/rubocop/rubocop/issues/8867, but to summarize, removing the safe navigation is undesirable because:
- `nil.to_s(:iso8601)` would raise an `ArgumentError`
- Even in the more general case, when there are no extra arguments to `to_s`, removing the safe navigation changes the semantics:
```rb
nil&.to_s || '(Unknown)' # => 'Unknown'
nil.to_s || '(Unknown)' # => ''
```
This PR reverts https://github.com/rubocop/rubocop/pull/11890 and adds a test to prevent regressions. …
=> Fix `Lint/RedundantSafeNavigation` when using `to_s`

lib/rubocop/cop/lint/shadowed_exception.rb
Revert https://github.com/rubocop/rubocop/commit/1533ece5b3d41ee8a1a2f154f23b7c1297e53a85
Current RuboCop (1.52) requires Ruby 2.7+ and JRuby 9.4+. So JRuby 9.2 has been dropped from runtime version.
https://github.com/jruby/jruby/issues/6642 has been resolved in JRuby 9.4:
```ruby
require 'ripper'
class RipperParser < Ripper
def on_parse_error(message)
raise message
end
end
RipperParser.new(<<~RUBY).parse
foo do
bar do
end
rescue NameError
converted << nil
end
RUBY
```
```console
$ ruby -v
jruby 9.4.2.0 (3.1.0) 2023-03-08 90d2913fda Java HotSpot(TM) 64-Bit Server VM 25.271-b09 on 1.8.0_271-b09 +jit [x86_64-darwin]
$ ruby example.rb # No errors
```
=> Revert "Workaround for Style/RedundantBegin when using JRuby 9.2"

changelog/fix_error_for_lint_useless_assignment.md, lib/rubocop/cop/lint/useless_assignment.rb, lib/rubocop/cop/variable_force/assignment.rb, spec/rubocop/cop/lint/useless_assignment_spec.rb, spec/rubocop/cop/variable_force/assignment_spec.rb
Fixes #11919.
This PR fixes an error for `Lint/UselessAssignment` when a variable is assigned and unreferenced in `for`.
=> [Fix #11919] Fix an error for `Lint/UselessAssignment`

lib/rubocop/cop/style/class_equality_comparison.rb
Fixes #11914.
This PR fixes an incorrect examples for `Style/ClassEqualityComparison`.
The original `IgnoredMethods` (later renamed `AllowedMethods`) was introduced by #8833. OTOH, #10809 seems to have mis-documented #8833.
=> [Fix #11914] Fix an incorrect examples for `Style/ClassEqualityComparion`

lib/rubocop/cop/internal_affairs/cop_description.rb, lib/rubocop/cop/layout/closing_heredoc_indentation.rb, lib/rubocop/cop/lint/erb_new_arguments.rb, lib/rubocop/cop/lint/identity_comparison.rb, lib/rubocop/cop/lint/incompatible_io_select_with_fiber_scheduler.rb, lib/rubocop/cop/lint/ordered_magic_comments.rb, lib/rubocop/cop/lint/send_with_mixin_argument.rb, lib/rubocop/cop/style/begin_block.rb, lib/rubocop/cop/style/special_global_vars.rb, spec/rubocop/cop/internal_affairs/cop_description_spec.rb
This PR add support for cases starting with an empty comment line in `InternalAffairs/CopDescription` cop. Corresponds to a case that begins with an empty comment line as follows:
```ruby
#
class SomeCop < Base
...
end
class SomeCop < Base
...
end
```
[1]: …
=> Add support for cases starting with an empty comment line in `InternalAffairs/CopDescription` cop

lib/rubocop/cop/style/file_read.rb
I might find other node patterns to clean up, so feel free to hold off on merging this PR (as it is admittedly a pretty a small change).
=> Use unification to match `File.open` block param with `#read` receiver

Gemfile
Follow up https://github.com/ruby/ruby/pull/7877.
Ruby 3.3.0dev is set to promote Racc to a bundled gem. Therefore, this PR provides a workaround for Parser 3.2.2.2 or lower with Ruby 3.3.0dev to prevents the following Ruby 3.3.0dev CI matrix error:
```console
bundle exec rake internal_investigation
rake aborted!
LoadError: cannot load such file -- racc/parser
<internal:/usr/local/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/usr/local/bundle/gems/parser-3.2.2.1/lib/parser.rb:12:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in …
```
=> Workaround for Parser 3.2.2.2 or lower with Ruby 3.3.0dev

changelog/fix_an_incorrect_for_style_sole_nested_conditional.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cli/autocorrect_spec.rb
This PR fixes an incorrect autocorrect for `Style/SoleNestedConditional` with `Style/MethodCallWithArgsParentheses`.
```ruby
if items.include? item
if condition
do_something
end
end
```
```console
$ bundle exec rubocop -a --only Style/MethodCallWithArgsParentheses,Style/SoleNestedConditional
F
Offenses:
example.rb:1:4: C: [Corrected] Style/MethodCallWithArgsParentheses: Use parentheses for method calls with arguments.
if items.include? item
example.rb:1:24: F: Lint/Syntax: unexpected token tRPAREN
(Using Ruby 3.3 parser; configure using TargetRubyVersion parameter, under AllCops)
if items.include?(item)) && condition
^
example.rb:2:3: C: [Corrected] Style/SoleNestedConditional: Consider merging nested conditions into outer if conditions.
if condition …
```
=> Fix an incorrect autocorrect for `Style/SoleNestedConditional`

changelog/fix_error_for_style_conditional_assignment.md, lib/rubocop/cop/style/conditional_assignment.rb, spec/rubocop/cop/style/conditional_assignment_assign_in_condition_spec.rb
Fixes #11947.
This PR fixes an error for `Style/ConditionalAssignment` with an assignment that uses `if` branch bodies, which include a block.
=> [Fix #11947] Fix an error for `Style/ConditionalAssignment`

changelog/fix_an_error_for_style_identical_conditional_branches.md, lib/rubocop/cop/style/identical_conditional_branches.rb, spec/rubocop/cop/style/identical_conditional_branches_spec.rb
This PR fixes the following error for `Style/IdenticalConditionalBranches` when using empty parentheses in the `if` branch:
```console
if condition
()
else
foo
end
$ bundle exec rubocop --only Style/IdenticalConditionalBranches -d
(snip)
An error occurred while Style/IdenticalConditionalBranches cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/identical_conditional_branches/example.rb:1:0.
undefined method `assignment?' for nil:NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/identical_conditional_branches.rb:161:in `duplicated_expressions?'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/identical_conditional_branches.rb:146:in `check_branches'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/ident …
```
=> Fix an error for `Style/IdenticalConditionalBranches`

changelog/fix_false_negatives_for_layout_empty_lines_around_exception_handling_keywords.md, lib/rubocop/cop/layout/empty_lines_around_exception_handling_keywords.rb, spec/rubocop/cop/layout/empty_lines_around_exception_handling_keywords_spec.rb
This PR fixes false negatives for `Layout/EmptyLinesAroundExceptionHandlingKeywords` when using Ruby 2.5's `rescue` inside block and Ruby 2.7's numbered block.
=> Fix false negatives for `Layout/EmptyLinesAroundExceptionHandlingKeywords`

changelog/fix_a_false_negative_for_lint_duplicate_hash_key.md, lib/rubocop/cop/lint/duplicate_hash_key.rb, spec/rubocop/cop/lint/duplicate_hash_key_spec.rb
Fixes #11953.
This PR fixes a false negative for `Lint/DuplicateHashKey` when there is a duplicated constant key in the hash literal.
=> [Fix #11953] Fix a false negative for `Lint/DuplicateHashKey`

changelog/fix_an_error_for_style_redundant_string_escape.md, lib/rubocop/cop/style/redundant_string_escape.rb, spec/rubocop/cop/style/redundant_string_escape_spec.rb
Fixes #11962.
This PR fixes an error for `Style/RedundantStringEscape` when an escaped double quote precedes interpolation in a symbol literal.
=> [Fix #11962] Fix an error for `Style/RedundantStringEscape`

changelog/fix_octal_handling_in_duplicate_char_class_element.md, lib/rubocop/cop/lint/duplicate_regexp_character_class_element.rb, spec/rubocop/cop/lint/duplicate_regexp_character_class_element_spec.rb
This improves the handling of escaped octals (as long as we allow regexp_parser < 2.7)
for the duplicate regexp character class element cop.
=> Fix handling of escaped octals in duplicate regexp cop

changelog/change_merge_pull_request_11936_from.md, config/default.yml, lib/rubocop/cop/lint/missing_super.rb, spec/rubocop/cop/lint/missing_super_spec.rb
Add `AllowedParentClasses ` config to `Lint/MissingSuper`.
The default value of `%w[BasicObject Object]` is kept for backwards compatibility, but users can now add to that list using the `AllowedParentClasses ` config value.
It's important to note that the value of `AllowedParentClasses ` will be ADDED to the default value.
This is because I don't foresee scenarios where users would want to remove `BasicObject` or `Object` from this list, and removes the requirement for always specifying them.
I'm open to feedback on this assumption and happy to change it into a full replacement, I simply went with the most logical approach in my opinion.
=> [Fix #8506] Add AllowedParentClasses config to Lint/MissingSuper.

changelog/change_layout_class_structure_autorrect_safety.md, config/default.yml, lib/rubocop/cop/layout/class_structure.rb
Autocorrection is unsafe because class instance methods and module inclusion may behave dynamically, based on which methods or constants have been defined.  ~~Constant definitions may also depend upon pre-existing methods or included modules.~~ _Only literal constants are autocorrected: #7808._
`ClassStructure` could be updated to make autocorrection behave differently for `-a` vs `-A`, i.e: method `def`s can be safely re-ordered if all "macros" are anchored to their current position.  But that would be a more complicated PR.
=> Mark `Layout/ClassStructure` as unsafe to autocorrect

lib/rubocop/config_loader_resolver.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/bundler/duplicated_gem_spec.rb, spec/rubocop/cop/bundler/gem_comment_spec.rb, spec/rubocop/cop/cop_spec.rb
Reverts rubocop/rubocop#11416
As discussed in #11968
=> Revert "Have `fix_include_path` make paths relative to Dir.pwd"

changelog/fix_a_false_positive_for_lint_redundant_require_statement.md, lib/rubocop/cop/lint/redundant_require_statement.rb, spec/rubocop/cop/lint/redundant_require_statement_spec.rb
Follow up https://github.com/rubocop/rubocop/issues/11099#issuecomment-1577117258
This PR fixes a false positive for `Lint/RedundantRequireStatement` when using `PP.pp`.
=> Fix a false positive for `Lint/RedundantRequireStatement`

changelog/fix_an_error_for_lint_void.md, lib/rubocop/cop/lint/void.rb, spec/rubocop/cop/lint/void_spec.rb
Fixes #11972.
This PR fixes an error for `Lint/Void` when `CheckForMethodsWithNoSideEffects: true` and using a method definition.
=> [Fix #11972] Fix an error for `Lint/Void`

docs/modules/ROOT/pages/usage/lsp.adoc
vscode-rubocop has been released:
https://marketplace.visualstudio.com/items?itemName=rubocop.vscode-rubocop
This PR adds vscode-rubocop to the LSP doc.
=> Add vscode-rubocop to the LSP doc

CHANGELOG.md
Ruby 2.6 runtime support was actually dropped in PR: #11791, not in #10791.
* [n/a] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [n/a] Squashed related commits together.
* [n/a] Added tests.
* [n/a] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [n/a] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.
----
- Fixes up #11791
=> Fix PR reference in CHANGELOG.md 1.51.0

changelog/fix_an_error_for_style_redundant_current_directory_in_path.md, lib/rubocop/cop/style/redundant_current_directory_in_path.rb, spec/rubocop/cop/style/redundant_current_directory_in_path_spec.rb
Fixes #11974.
This PR fixes an error for `Style/RedundantCurrentDirectoryInPath` when using string interpolation in `require_relative`.
=> [Fix #11974] Fix an error for `Style/RedundantCurrentDirectoryInPath`

changelog/fix_should_not_offence_single_quoted_symbol_containing_double_quotes.md, lib/rubocop/cop/lint/symbol_conversion.rb, spec/rubocop/cop/lint/symbol_conversion_spec.rb
Fixies https://github.com/rubocop/rubocop/issues/11836
This PR should not offense single-quoted symbol containing double quotes in `Lint/SymbolConversion`
=> [#11836] should not offense single-quoted symbol containing double quotes in `Lint/SymbolConversion`

changelog/fix_an_incorrect_autocorrect_for_style_redundant_regexp_argument.md, lib/rubocop/cop/style/redundant_regexp_argument.rb, spec/rubocop/cop/style/redundant_regexp_argument_spec.rb
Fixes #11981.
This PR fixes an incorrect autocorrect for `Style/RedundantRegexpArgument` when using double quote and single quote characters.
=> [Fix #11981] Fix an incorrect autocorrect for `Style/RedundantRegexpArgument`

changelog/change_fix_11738_enhances_empty_line_between_defs_to.md, config/default.yml, lib/rubocop/cop/layout/empty_line_between_defs.rb, spec/rubocop/cop/layout/empty_line_between_defs_spec.rb
Resolves https://github.com/rubocop/rubocop/issues/11738
This pr enhances the Layout/EmptyLineBetweenDefs cop to treat macros in the `EmptyLineBetweenMacros` config as if they were defs.  See the issue for more detail
=> Enhance Layout/EmptyLineBetweenDefs to include macros

changelog/fix_a_false_positive_for_lint_mixed_case_range.md, lib/rubocop/cop/lint/mixed_case_range.rb, spec/rubocop/cop/lint/mixed_case_range_spec.rb
Fixes #11986.
This PR fixes a false positive for `Lint/MixedCaseRange` when the number of characters at the start or end of range is other than 1.
=> [Fix #11986] Fix a false positive for `Lint/MixedCaseRange`

changelog/fix_an_incorrect_auttocorrect_for_style_redundant_regexp_argument.md, lib/rubocop/cop/style/redundant_regexp_argument.rb, spec/rubocop/cop/style/redundant_regexp_argument_spec.rb
Fixes #11989.
This PR fixes an incorrect autocorrect for `Style/RedundantRegexpArgument` when using unicode chars.
This is a resolution applying the feedback below:
https://github.com/rubocop/rubocop/pull/11595#discussion_r1231268032
=> [Fix #11989] Fix an incorrect autocorrect for `Style/RedundantRegexpArgument`

changelog/fix_an_error_for_builtin_lsp.md, lib/rubocop/lsp/server.rb, spec/rubocop/lsp/server_spec.rb
Fixes #11992.
This PR fixes an unexpected `NoMethodError` for LSP mode when an internal error occurs.
=> [Fix #11992] Fix an error for built-in language server

changelog/fix_an_error_for_style_if_with_semicolon.md, lib/rubocop/cop/style/if_with_semicolon.rb, spec/rubocop/cop/style/if_with_semicolon_spec.rb
Fixes #11996.
This PR fixes an error for `Style/IfWithSemicolon` when without branch bodies.
=> [Fix #11996] Fix an error for `Style/IfWithSemicolon`

changelog/fix_an_error_for_layout_line_end_string_concatenation_indentation.md, lib/rubocop/cop/layout/line_end_string_concatenation_indentation.rb, spec/rubocop/cop/layout/line_end_string_concatenation_indentation_spec.rb
Fixes #11994.
This PR fixes an error for `Layout/LineEndStringConcatenationIndentation` when inspecting the `%` form string `%\n\n`.
=> [Fix #11994] Fix an error for `Layout/LineEndStringConcatenationIndentation`

changelog/fix_lint_void_cop_for_encoding_constant.md, lib/rubocop/cop/lint/void.rb, spec/rubocop/cop/lint/void_spec.rb
Fixes #12002.
`__ENCODING__` is parsed as a constant without a name (`s(:const, s(:const, nil, :Encoding), :UTF_8)`), hence is an error. Other constants, like `__FILE__` or `__LINE__` are parsed as `str` and `int` nodes respectively, so these are identified as literals and are already processed correctly.
=> Fix `Lint/Void` cop for `__ENCODING__` constant

changelog/fix_code_length_calculator_for_method_calls_with_heredoc.md, lib/rubocop/cop/metrics/utils/code_length_calculator.rb, spec/rubocop/cop/metrics/utils/code_length_calculator_spec.rb
Fixes #12001.
The  problem is that for the code like 
```ruby
other_method <<~ANY
2
3
ANY
```
the `.source` method returns just the first line (`other_method <<~ANY`), and so for the example from the linked issue, the total method length included all the lines, but when considering method calls as a single line (`CountAsOne` option), only the first line of the method call was considered and subtracted from the total, leaving all the rest lines from heredoc.
This PR fixes the `CodeLengthCalculator` to correctly calculate sources when the node includes a heredoc in its body.
=> Fix code length calculator for method calls with heredoc

changelog/fix_an_error_when_inspecting_blank_heredoc_delimiter.md, lib/rubocop/cop/mixin/heredoc.rb, spec/rubocop/cop/naming/heredoc_delimiter_case_spec.rb, spec/rubocop/cop/style/redundant_heredoc_delimiter_quotes_spec.rb
Fixes #11998.
This PR fixes an error when inspecting blank heredoc delimiter.
=> [Fix #11998] Fix an error when inspecting blank heredoc delimiter

changelog/new_support_safe_autocorrect_config_for_lsp.md, docs/modules/ROOT/pages/usage/lsp.adoc, lib/rubocop/lsp/routes.rb, lib/rubocop/lsp/runtime.rb, lib/rubocop/lsp/server.rb, spec/rubocop/lsp/server_spec.rb
This PR supports safe or unsafe autocorrect config for LSP.
The autocorrection is still safe by default (`rubocop -a`).
LSP client can switch to unsafe autocorrection (`rubocop -A`) by passing the following `safeAutocorrect` parameter in the `initialize` request.
```json
{
"jsonrpc": "2.0",
"id": 42,
"method": "initialize",
"params": {
"initializationOptions": {
"safeAutocorrect": false
}
}
}
```
Some users may want to set unsafe autocorrection as the default for the LSP, understanding the risks involved.
However, considering that the default should be safe, unsafe is an option.
=> Support safe or unsafe autocorrect config for LSP

changelog/fix_a_false_negative_for_lint_debugger.md, lib/rubocop/cop/lint/debugger.rb, spec/rubocop/cop/lint/debugger_spec.rb
Fixes #12005.
This PR fixes a false negative for `Lint/Debugger` when using debugger method inside lambda.
=> [Fix #12005] Fix a false negative for `Lint/Debugger`

changelog/fix_an_error_for_layout_space_around_operators.md, lib/rubocop/cop/layout/space_around_operators.rb, spec/rubocop/cop/layout/space_around_operators_spec.rb
Fixes #12007.
This PR fixes an error for `Layout/SpaceAroundOperators` when using unary operator with double colon.
=> [Fix #12007] Fix an error for `Layout/SpaceAroundOperators`

changelog/fix_an_error_for_style_yoda_condition.md, lib/rubocop/cop/style/yoda_condition.rb, spec/rubocop/cop/style/yoda_condition_spec.rb
This PR fixes an error for `Style/YodaCondition` when equality check method is used without the first argument:
```ruby
foo.==
```
```console
% rubocop /tmp/example.rb --only Style/YodaCondition -d
(snip)
For /tmp: An error occurred while Style/YodaCondition cop was inspecting /tmp/example.rb:1:0.
undefined method `literal?' for nil:NilClass
An error occurred while Style/YodaCondition cop was inspecting /tmp/example.rb:1:0.
undefined method `literal?' for nil
/Users/koic/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubocop-1.53.1/lib/
rubocop/cop/style/yoda_condition.rb:144:in `constant_portion?'
/Users/koic/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubocop-1.53.1/lib/
rubocop/cop/style/yoda_condition.rb:126:in `valid_yoda?'
```
Before submitting the …
=> Fix an error for `Style/YodaCondition`

changelog/fix_false_negatives_for_style_redundant_regexp_argument.md, lib/rubocop/cop/style/redundant_regexp_argument.rb, spec/rubocop/cop/style/redundant_regexp_argument_spec.rb
This PR fixes false negatives for `Style/RedundantRegexpArgument` when using safe navigation operator.
=> Fix false negatives for `Style/RedundantRegexpArgument`

changelog/fix_an_error_for_metrics_method_length.md, lib/rubocop/cop/metrics/utils/code_length_calculator.rb, spec/rubocop/cop/metrics/method_length_spec.rb
This PR fixes the following error for `Metrics/MethodLength` when using a heredoc in a block without block arguments:
```console
$ cd path/to/rubocop-ast
$ bundle exec rubocop -d --only Metrics/MethodLength lib/rubocop/ast/node_pattern/compiler/sequence_subcompiler.rb
(snip)
Scanning /Users/koic/src/github.com/rubocop/rubocop-ast/lib/rubocop/ast/node_pattern/compiler/sequence_subcompiler.rb
An error occurred while Metrics/MethodLength cop was inspecting /Users/koic/src/github.com/rubocop/rubocop-ast/lib/
rubocop/ast/node_pattern/compiler/sequence_subcompiler.rb:88:10.
undefined method `last_line' for nil
/Users/koic/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/parser-3.2.2.3/lib/parser/source/map.rb:118:
in `last_line'
/Users/koic/src/github.com/rubocop/rubocop-ast/lib/rubocop/ast/ …
```
=> Fix an error for `Metrics/MethodLength`

lib/rubocop/cop/internal_affairs/location_line_equality_comparison.rb, spec/rubocop/cop/internal_affairs/location_line_equality_comparison_spec.rb
This PR if fix an error for `InternalAffairs/LocationLineEqualityComparison` when inside block.
Code to reproduce:
```ruby
nodes.select do |node|
node.first_line == nodes.first.first_line
end
```
Log:
```
An error occurred while InternalAffairs/LocationLineEqualityComparison cop was inspecting /ydah/rubocop-rspec/a.rb:2:2.
undefined method `method?' for s(:lvar, :node):RuboCop::AST::Node
/ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.54.0/lib/rubocop/cop/internal_affairs/location_line_equality_comparison.rb:54:in `extract_receiver'
/ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.54.0/lib/rubocop/cop/internal_affairs/location_line_equality_comparison.rb:41:in `on_send'
/ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rubocop-1.54.0/lib/rubocop/cop/commissi …
```
=> Fix an error for `InternalAffairs/LocationLineEqualityComparison` when inside block

changelog/fix_an_error_for_lint_useless_assignment.md, lib/rubocop/cop/variable_force/assignment.rb, spec/rubocop/cop/lint/useless_assignment_spec.rb
Fixes #12014.
This PR fixes an error for `Lint/UselessAssignment` when part of a multiple assignment is enclosed in parentheses.
=> [Fix #12014] Fix an error for `Lint/UselessAssignment`

changelog/fix_a_false_positive_for_lint_redundant_regexp_quantifiers.md, lib/rubocop/cop/lint/redundant_regexp_quantifiers.rb, spec/rubocop/cop/lint/redundant_regexp_quantifiers_spec.rb
Fixes #12024.
This PR fixes a false positive for `Lint/RedundantRegexpQuantifiers` when interpolation is used in a regexp literal.
=> [Fix #12024] Fix a false positive for `Lint/RedundantRegexpQuantifiers`

changelog/fix_an_error_for_layout_space_after_comma.md, lib/rubocop/cop/layout/space_after_comma.rb, spec/rubocop/cli/autocorrect_spec.rb
Fixes #12020.
This PR fixes an infinite loop error for `Layout/SpaceAfterComma` with `Layout/SpaceBeforeSemicolon` when autocorrection conflicts.
The use of semicolon after comma (`,;`) is limited, so making it difficult to default the presence or absence of space between the semicolon and the comma. This PR aims to prevent an infinite loop error occurrences by always allowing the absence of space after comma when it is followed by semicolon.
=> [Fix #12020] Fix an error for `Layout/SpaceAfterComma` with `Layout/SpaceBeforeSemicolon`

lib/rubocop/cop/style/return_nil_in_predicate_method_definition.rb
This PR fixes a couple of small typos in the `Style/ReturnNilInPredicateMethodDefinition` docs: `AllowedMethod` and `AllowedPattern` should both be pluralized.
=> Fix typo in Style/ReturnNilInPredicateMethodDefinition docs

lib/rubocop/cop/naming/heredoc_delimiter_naming.rb, spec/rubocop/cop/naming/heredoc_delimiter_naming_spec.rb
Follow https://github.com/rubocop/rubocop/pull/11999#issuecomment-1613469560
This PR tweaks offense range highlight.
```console
$ cat /tmp/heredoc.rb
<<~''
```
It was registering an offense as expected, but the offense range was not showing:
```console
$ bundle exec rubocop /tmp/heredoc.rb --only Naming/HeredocDelimiterNaming
C
Offenses:
/tmp/heredoc.rb:1:1: C: Naming/HeredocDelimiterNaming: Use meaningful heredoc delimiters.
```
It registers an offense as expected and shows the offense range:
```console
$ bundle exec rubocop /tmp/heredoc.rb --only Naming/HeredocDelimiterNaming
C
Offenses:
/tmp/heredoc.rb:1:1: C: Naming/HeredocDelimiterNaming: Use meaningful heredoc delimiters.
<<~''
^^^^^
1 file inspected, 1 offense …
```
=> Tweak offense range highlight for `Naming/HeredocDelimiterNaming`

changelog/fix_an_error_when_allcops_exclude_is_empty.md, lib/rubocop/target_finder.rb, spec/rubocop/cli_spec.rb
Fixes #1867.
This PR fixes the following error when `AllCops:Exclude` is empty in .rubocop.yml.
```console
$ cat .rubocop.yml
AllCops:
Exclude:
(snip)
private method `select' called for nil:NilClass
/Users/koic/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubocop-1.54.1/lib/rubocop/target_finder.rb:118:in `combined_exclude_glob_patterns'
/Users/koic/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubocop-1.54.1/lib/rubocop/target_finder.rb:85:in `find_files'
/Users/koic/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubocop-1.54.1/lib/rubocop/target_finder.rb:59:in `target_files_in_dir'
```
=> [Fix #1867] Fix an error when `AllCops:Exclude` is empty in .rubocop.yml

changelog/fix_an_error_when_using_an_invalid_encoding_string.md, lib/rubocop/cop/style/frozen_string_literal_comment.rb, spec/rubocop/cli_spec.rb
Fixes #12034.
This PR fixes invalid byte sequence in UTF-8 error when using an invalid encoding string.
=> [Fix #12034] Fix an error when using an invalid encoding string

changelog/fix_output_the_server_restarting_message_to_stderr.md, lib/rubocop/server/client_command/exec.rb, spec/rubocop/server/rubocop_server_spec.rb
When using Rubocop with `--autocorrect --stderr`, the standard output should not contain anything other than the autocorrected source.
=> Output the "server restarting" message to stderr

changelog/fix_a_false_positive_for_layout_trailing_empty_lines.md, lib/rubocop/cop/layout/trailing_empty_lines.rb, spec/rubocop/cop/layout/trailing_empty_lines_spec.rb
This PR fixes a false positive for `Layout/TrailingEmptyLines` to prevent the following incorrect autocorrection when inspecting the `%` form string `%\n\n`.
First, `Layout/TrailingEmptyLines` cop detects an offense upon inspection, but it's valid syntax:
```console
$ echo "x = %\n\n" | be rubocop --stdin example.rb --only Layout/TrailingEmptyLines
C
Offenses:
example.rb:2:1: C: [Correctable] Layout/TrailingEmptyLines: 2 trailing blank lines detected.
1 file inspected, 1 offense detected, 1 offense autocorrectable
```
Next, `Layout/TrailingEmptyLines` cop autocorrects to an invalid syntax and `Lint/Syntax` occurs:
```
$ echo "x = %\n\n" | be rubocop --stdin example.rb --only Layout/TrailingEmptyLines -a
F
Offenses:
example.rb:1:5: F: Lint/Syntax: …
```
=> Fix a false positive for `Layout/TrailingEmptyLines`

changelog/fix_a_false_negative_for_layout_extra_spacing.md, lib/rubocop/cop/mixin/preceding_following_alignment.rb, lib/rubocop/string_interpreter.rb, spec/rubocop/cop/layout/extra_spacing_spec.rb, spec/rubocop/target_finder_spec.rb
This PR fixes a false negative for `Layout/ExtraSpacing` when some character are vertically aligned.
For example, there is a wasted space before the `do` keyword.
```ruby
d_is_vertically_aligned  do
_______________________d
end
```
The `d` char is accidentally vertically aligned and cannot be detected:
```console
$ bundle exec rubocop --only Layout/ExtraSpacing
(snip)
```
Looking at the test code, it looks like this is to allow vertical alignment of dots in method calls:
```ruby
y, m = (year * 12 + (mon - 1) + n).divmod(12)
m,   = (m + 1)                    .divmod(1)
```
https://github.com/rubocop/rubocop/blob/v1.54.1/spec/rubocop/cop/layout/extra_spacing_spec.rb#L172-L177
Therefore, this PR tweaks the alignment logic to be closer to the expected …
=> Fix a false negative for `Layout/ExtraSpacing`

changelog/new_make_lsp_support_layout_only_parameter.md, docs/modules/ROOT/pages/usage/lsp.adoc, lib/rubocop/lsp/routes.rb, lib/rubocop/lsp/runtime.rb, lib/rubocop/lsp/server.rb, spec/rubocop/lsp/server_spec.rb
Fixes #12044.
LSP client can run layout cops by passing the following `layoutMode` parameter in the `initialize` request.
```json
{
"jsonrpc": "2.0",
"id": 42,
"method": "initialize",
"params": {
"initializationOptions": {
"layoutMode": true
}
}
}
```
Furthermore, enabling autocorrect in a LSP client at the time of saving equates to the effect of `rubocop -x` option.
For detailed instructions on setting the parameter, please refer to the configuration methods of your LSP client.
=> [Fix #12044] Make LSP server support `layoutMode` parameter

changelog/new_make_style_return_nil_in_predicate_method_definition_aware_of_nil.md, lib/rubocop/cop/style/return_nil_in_predicate_method_definition.rb, spec/rubocop/cop/style/return_nil_in_predicate_method_definition_spec.rb
Fixes #12046.
This PR makes `ReturnNilInPredicateMethodDefinition` aware of `nil` at the end of predicate method definition.
=> [Fix #12046] Make `ReturnNilInPredicateMethodDefinition` aware of `nil` at the end of method

changelog/change_mark_style_hash_conversion_as_unsafe_autocorrection.md, config/default.yml, lib/rubocop/cop/style/hash_conversion.rb
Fixes #12015.
This PR marks `Style/HashConversion` as unsafe autocorrection.
This cop's autocorrection is unsafe because `ArgumentError` occurs if the number of elements is odd:
```ruby
Hash[[[1, 2], [3, 4], [5]]] #=> {1=>2, 3=>4, 5=>nil}
[[1, 2], [3, 4], [5]].to_h  #=> wrong array length at 2 (expected 2, was 1) (ArgumentError)
```
For example, this cannot be avoided when the arguments are variables.
=> [Fix #12015] Mark `Style/HashConversion` as unsafe autocorrection

changelog/fix_an_error_for_layout_redundant_line_break.md, lib/rubocop/cop/layout/redundant_line_break.rb, spec/rubocop/cop/layout/redundant_line_break_spec.rb
This PR fixes a false positive for `Layout/RedundantLineBreak` to prevent the following incorrect autocorrection when inspecting the `%` form string `%\n\n`.
First, `Layout/RedundantLineBreak` cop detects an offense upon inspection, but it's valid syntax:
```console
$ echo "x = %\n\n" | be rubocop --stdin example.rb --enable-pending-cops --only Layout/RedundantLineBreak
C
Offenses:
example.rb:1:1: C: [Correctable] Layout/RedundantLineBreak: Redundant line break detected.
x = % ...
^^^^^
1 file inspected, 1 offense detected, 1 offense autocorrectable
```
Next, `Layout/RedundantLineBreak` cop autocorrects to an invalid syntax and `Lint/Syntax` occurs:
```console
% echo "x = %\n\n" | be rubocop --stdin example.rb --enable-pending-cops --only Layout/RedundantLineBreak -a …
```
=> Fix a false positive for `Layout/RedundantLineBreak`

changelog/fix_allow_parentheses_in_single_line_match_patterns.md, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
```ruby
execute(query) => {elapsed:, sql_count:}
```
is a single-line pattern-match. The current version of the `omit_parentheses` style in `Style/MethodCallWithArgsParentheses` forces us to omit the parens in the call, making it a call with an options hash that has a string key and a value omitted hash as an value:
```ruby
execute query => {elapsed:, sql_count:}
```
This is yet another ambiguity and we need to allow the parentheses when we pattern match the value of a call.
=> Allow parentheses in single-line match patterns

changelog/fix_improve_handling_of_bracket_and_parentheses_with_percent_symbol_arrays.md, lib/rubocop/cop/style/symbol_array.rb, spec/rubocop/cop/style/symbol_array_spec.rb
Addresses https://github.com/rubocop/rubocop/issues/11802, but also accounts for `()`
=> [Fix #11802] Improve handling of [] and () with percent symbol arrays

changelog/fix_combinable_loops_when_one_of_the_loops_is_empty.md, lib/rubocop/cop/style/combinable_loops.rb, spec/rubocop/cop/style/combinable_loops_spec.rb
`Style/CombinableLoops` raises an error when one of the loops is empty:
```
An error occurred while Style/CombinableLoops cop was inspecting example.rb:2:0.
undefined method `source' for nil:NilClass
rubocop/lib/rubocop/cop/style/combinable_loops.rb:108:in `combine_with_left_sibling'
rubocop/lib/rubocop/cop/style/combinable_loops.rb:72:in `block in on_block'
rubocop/lib/rubocop/cop/base.rb:377:in `correct'
rubocop/lib/rubocop/cop/base.rb:181:in `add_offense'
rubocop/lib/rubocop/cop/style/combinable_loops.rb:71:in `on_block'
rubocop/lib/rubocop/cop/commissioner.rb:107:in `public_send'
```
Example (where this error was caught): https://github.com/rails/rails/blob/04c97aec8aa696165e98f46ecec2b13410629be0/activerecord/test/cases/batches_test.rb#L717-L718
=> Fix `Style/CombinableLoops` when one of the loops is empty

changelog/new_make_lsp_support_lint_mode_parameter.md, docs/modules/ROOT/pages/usage/lsp.adoc, lib/rubocop/lsp/routes.rb, lib/rubocop/lsp/runtime.rb, lib/rubocop/lsp/server.rb, spec/rubocop/lsp/server_spec.rb
This PR will provide `lintMode` (`rubocop -l`) as well as `layoutMode` (`rubocop -x`) . I think it's probably less demanding than LSP integration for formatters only, but this PR can provide it in advance.
LSP client can run lint cops by passing the following `lintMode` parameter in the `initialize` request if you only want to enable the feature as a linter like `ruby -w`:
```json
{
"jsonrpc": "2.0",
"id": 42,
"method": "initialize",
"params": {
"initializationOptions": {
"lintMode": true
}
}
}
```
Furthermore, enabling autocorrect in a LSP client at the time of saving equates to the effect of `rubocop -l` option.
For detailed instructions on setting the parameter, please refer to the configuration methods of your LSP client. …
=> Make LSP server support `lintMode` parameter

changelog/change_make_redundant_argument_aware_of_exit_and_exit_bang.md, config/default.yml, lib/rubocop/cop/style/redundant_argument.rb, rubocop.gemspec, spec/rubocop/cop/style/redundant_argument_spec.rb
This PR makes aware of `Style/RedundantArgument` aware of `exit` and `exit!`. It require RuboCop AST 1.28.1+ that includes https://github.com/rubocop/rubocop-ast/pull/262.
=> Make `Style/RedundantArgument` aware of `exit` and `exit!`

changelog/fix_false_positive_for_when_variable_in_inside.md, lib/rubocop/cop/lint/shadowing_outer_local_variable.rb, spec/rubocop/cop/lint/shadowing_outer_local_variable_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/11834
This PR fixes a false positive offence for a variable in inside a conditional branch in a nested node.
Please suggest better naming for the new method and the new spec. 
=> [Fix #11834] Fix false positive for variable in inside conditional branch in nested node

changelog/new_enable_anonymous_forwarding_in_style_arguments_forwarding.md, config/default.yml, config/obsoletion.yml, lib/rubocop/config_obsoletion/parameter_rule.rb, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/config_obsoletion_spec.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
Adds support for anonymous [rest/kwrest argument forwarding](https://rubyreferences.github.io/rubychanges/3.2.html#anonymous-arguments-passing-improvements) on Ruby 3.2+ and also rewrites the existing functionality for "forwarding all" (`...`)
Some questions I'd like to answer before fleshing this PR out any further:
1. Should this be a new cop? (I _think_ no, due to the overlap, but e.g. `Naming/BlockForwarding` seems relevant)
1. Should there be configuration to enable/disable anonymous forwarding? (I think yes but haven't done it yet - config name suggestions very welcome)
1. Is there an existing mechanism to alert for now-unnecessary options in later Ruby versions (specifically `AllowOnlyRestArgument` isn't needed in Ruby 3.2+) …
=> Enable anonymous forwarding in Style/ArgumentsForwarding for Ruby 3.2+

lib/rubocop/result_cache.rb
There is a particular edge case when RuboCop is loaded from a fully symlinked environment. This is the default for Bazel which creates a tree of symlinks for every dependency, mimicking the real file tree structure.
In such a setup, RuboCop would fail to load with an error. Resolving the path to an absolute one fixes it.
```
No such file or directory - //?/D:/_bazel/external/bundle/ruby/3.0.0/gems/rubocop-1.36.0/lib/rubocop/../../exe
...
//?/D:/_bazel/external/bundle/ruby/3.0.0/gems/rubocop-1.36.0/lib/rubocop/result_cache.rb:208:in `each'
```
I am not sure what is the best way to write a test for this, I could use some guidance.
=> Fix `LoadError` on Windows when loading RuboCop from symlinks

changelog/fix_correct_rubocop_for_private_class_method_method.md, lib/rubocop/cop/mixin/def_node.rb, spec/rubocop/cop/style/documentation_method_spec.rb
The `private_class_method` modifier was not respected when checking whether a method needs documentation. I was able to fix that, but unable to fix the corresponding spec when documentation is present. Rubocop unfortunately still complains.
=> Correct Rubocop for `private_class_method` method documentation.

changelog/fix_a_false_positive_for_style_return_nil_in_predicate_method_definition.md, lib/rubocop/cop/style/return_nil_in_predicate_method_definition.rb, spec/rubocop/cop/style/return_nil_in_predicate_method_definition_spec.rb
Fixes #12068.
This PR fixes a false positive for `Style/ReturnNilInPredicateMethodDefinition` when the last method argument in method definition is `nil`.
=> [Fix #12068] Fix a false positive for `Style/ReturnNilInPredicateMethodDefinition`

changelog/fix_an_error_for_lint_useless_assignment.md, lib/rubocop/cop/variable_force/assignment.rb, spec/rubocop/cop/lint/useless_assignment_spec.rb
Fixes #12082.
This PR fixes an error for `Lint/UselessAssignment` when a variable is assigned and unreferenced in `for` with multiple variables.
=> [Fix #12082] Fix an error for `Lint/UselessAssignment`

changelog/fix_an_error_for_style_mixin_grouping.md, lib/rubocop/cop/style/mixin_grouping.rb, spec/rubocop/cop/style/mixin_grouping_spec.rb
Fixes #12079.
This PR fixes an error for `Style/MixinGrouping` when mixin method has no arguments.
=> [Fix #12079] Fix an error for `Style/MixinGrouping`

changelog/fix_style_symbol_array_false_positives.md, lib/rubocop/cop/style/symbol_array.rb, spec/rubocop/cop/style/symbol_array_spec.rb
Fixes #12071. Some false positives offenses were introduced in https://github.com/rubocop/rubocop/pull/12037.
For example, `%I[#{one}_two three]` and `%i[one[2] three]` are currently returning offenses when they should not be.
=> [Fix #12071] Fix `Style/SymbolArray` false positives when using square brackets or interpolation in a symbol literal within a percent style array

changelog/fix_error_for_lint_suppressed_exception.md, lib/rubocop/cop/lint/suppressed_exception.rb, spec/rubocop/cop/lint/suppressed_exception_spec.rb
Fixes #12085.
This PR fixes an error for `Lint/SuppressedException` when `AllowNil: true` is set and endless method definition is used.
=> [Fix #12085] Fix an error for `Lint/SuppressedException`

changelog/fix_support_regex_in_string_literals_in_interpolation.md, lib/rubocop/cop/mixin/string_help.rb, lib/rubocop/cop/style/string_literals_in_interpolation.rb, spec/rubocop/cop/style/string_literals_in_interpolation_spec.rb
Interpolation can occur in strings, symbols, and regular expressions, so update code to support regex and extend code examples in documentation comments.
=> [Fix #12061] Support regex in StringLiteralsInInterpolation

changelog/change_add_base64_to_runtime_dependency.md, rubocop.gemspec
This PR add `base64` to runtime dependency to suppress the following Ruby 3.3's warning:
```console
$ ruby -v
ruby 3.3.0dev (2023-08-03T00:11:08Z master 4b6c584023) [x86_64-darwin22]
base64 is not part of the default gems since Ruby 3.4.0. Add it to your Gemfile.
```
=> Add `base64` to runtime dependency

changelog/new_make_lsp_server_support_format_autocorrects_all_execute_command.md, docs/modules/ROOT/pages/usage/lsp.adoc, lib/rubocop/lsp/routes.rb, lib/rubocop/lsp/runtime.rb, lib/rubocop/lsp/server.rb, spec/rubocop/lsp/server_spec.rb
This PR makes LSP server support `rubocop.formatAutocorrectsAll` execute command. The user can run `rubocop -A` with the execute command in the editor.
The existing `rubocop.formatAutocorrects` execute command equivalent to `rubocop -a` can be used as follows: https://github.com/rubocop/vscode-rubocop#manually-triggering-a-format-with-autocorrects
The new `rubocop.formatAutocorrectsAll` execute command is the provide execute command for that `rubocop -A`.
=> Make LSP server support `rubocop.formatAutocorrectsAll` execute command

changelog/fix_a_false_positive_for_style_class_equality_comparison.md, lib/rubocop/cop/style/class_equality_comparison.rb, spec/rubocop/cop/style/class_equality_comparison_spec.rb
This PR fixes a false positive to prevent an incorrect autocorrect for `Style/ClassEqualityComparison` when comparing interpolated string class name for equality.
For example, autocorrect the code below:
```console
var.class.name == "String#{interpolation}"
$ bundle exec rubocop --only Style/ClassEqualityComparison -a
C
Offenses:
example.rb:1:5: C: [Corrected] Style/ClassEqualityComparison: Use instance_of?("String#{interpolation}") instead of comparing classes.
var.class.name == "String#{interpolation}"
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
The `instance_of?` argument is still a string.
```console
var.instance_of?("String#{interpolation}")
```
But the `instance_of?` argument …
=> Fix a false positive for `Style/ClassEqualityComparison`

changelog/fix_an_incorrect_for_style_alias.md, lib/rubocop/cop/style/alias.rb, spec/rubocop/cop/style/alias_spec.rb
This PR fixes the following incorrect autocorrection for `Style/Alias` when `EncforcedStyle: prefer_alias_method` and using `alias` with interpolated symbol argument:
```console
alias :"string#{interpolation}" :symbol
$ cat .rubocop.yml
Style/Alias:
EnforcedStyle: prefer_alias_method
```
```console
$ bundle exec rubocop -a --only Style/Alias
(snip)
Offenses:
example.rb:1:1: C: [Corrected] Style/Alias: Use alias_method instead of alias.
alias :"string#{interpolation}" :symbol
^^^^^
example.rb:1:14: F: Lint/Syntax: unexpected token tCOLON
(Using Ruby 3.2 parser; configure using TargetRubyVersion parameter, under AllCops)
alias_method :, :symbol
^
```
```console
alias_method :, :symbol
$ ruby -c …
```
=> Fix an incorrect autocorrect for `Style/Alias`

changelog/fix_an_error_for_style_lambda_call.md, lib/rubocop/cop/style/lambda_call.rb, spec/rubocop/cop/style/lambda_call_spec.rb
This PR fixes an error for `Style/LambdaCall` when using nested lambda call `x.().()`:
```console
x.(a, b).(c)
$ buncle exec rubocop example.rb --only Style/LambdaCall -a -d
(snip)
An error occurred while Style/LambdaCall cop was inspecting /Users/koic/src/github.com/koic/rubocop-issues/lambda_call/example.rb:1:0.
/Users/koic/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/parser-3.2.2.3/lib/parser/source/tree_rewriter.rb:427:in `trigger_policy'
```
=> Fix an error for `Style/LambdaCall`

changelog/fix_false_positives_for_style_arguments_forwarding.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
Additionally fixes:
* #12089
* #12096
* #12100
In Ruby < 3.2 this cop was overzealous and not considering various additional args/kwargs and other reasons to not allow forward-all (`...`), and was additionally assuming that forward-all meant all arguments were replaced, which was not always the case.
=> [Fix #12087] Fix false positives for Style/ArgumentsForwarding

changelog/fix_with_fail_level_a_ignore_non_correctable_offenses.md, docs/modules/ROOT/pages/usage/basic_usage.adoc, lib/rubocop/runner.rb, spec/rubocop/cli/options_spec.rb
The current implementation of `--fail-level autocorrect` fails for all
offenses, no matter what. Notably, this includes non-correctable
offenses with the :info severity.
Change the implementation to only fail:
* Any _correctable_ offense, regardless of severity
* Non-correctable offenses with severity :refactor (the default) or
higher
=> With `--fail-level A` ignore non-correctable offenses at :info severity

changelog/new_add_new_bundler_duplicated_group_cop.md, config/default.yml, lib/rubocop.rb, lib/rubocop/cop/bundler/duplicated_group.rb, spec/rubocop/cop/bundler/duplicated_group_spec.rb
New cop validating each gem group (or a set of groups) is only defined once. 
```ruby
group :development do
gem 'rubocop'
end
group :development do
gem 'rubocop-rails'
end
group :development, :test do
gem 'rubocop'
end
group :test, :development do
gem 'rspec'
end
group :development do
gem 'rubocop'
end
group :development, :test do
gem 'rspec'
end
gem 'rubocop', groups: [:development, :test]
gem 'rspec', groups: [:development, :test]
```
This has been suggested many years ago here https://github.com/rubocop/rubocop/issues/3600 but I couldn't find any attempts at implementing it. 
=> Add new `Bundler/DuplicatedGroup` cop

changelog/fix_an_error_for_style_arguments_forwarding_cop_when_forwarding_kwargs_block.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
Fix: https://github.com/rubocop/rubocop/issues/12109
=> [Fix: #12109] Fix an error for `Style/ArgumentsForwarding` cop when forwarding kwargs/block arg and an additional arg

changelog/fix_an_error_for_bundler_duplicated_group.md, lib/rubocop/cop/bundler/duplicated_group.rb, spec/rubocop/cop/bundler/duplicated_group_spec.rb
Fixes #12111.
This PR fixes an error for `Bundler/DuplicatedGroup` group declaration has keyword option.
=> [Fix #12111] Fix an error for `Bundler/DuplicatedGroup`

changelog/fix_an_error_for_style_arguments_forwarding_when_not_always_forwarding_block.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
With `TargetRubyVersion < 3.2`, if some call sites forwarded the block but others didn't then the cop didn't classify the without-block call site as a forwarding call, and thus didn't notice the discrepancy between those that did forward the block and those that didn't.
=> [Fix #12117] Fix `Style/ArgumentsForwarding` when not always forwarding a block

changelog/fix_false_positives_for_style_symbol_array.md, lib/rubocop/cop/style/symbol_array.rb, spec/rubocop/cop/style/symbol_array_spec.rb
This PR fixes false positives for `Style/SymbolArray` when `%i` array containing unescaped `[`, `]`, `(`, or `)`.
I noticed the following false positive in the RuboCop AST repository:
```console
$ cd path/to/rubocop-ast
$ bundle exec rubocop --only Style/SymbolArray
(snip)
spec/rubocop/ast/node_pattern/lexer_spec.rb:36:9: C: [Correctable] Style/SymbolArray:
Use [:'(', :array, :sym, :'$', :int, :+, :x, :')'] for an array of symbols.
%i[( array sym $ int + x )]
^^^^^^^^^^^^^^^^^^^^^^^^^^^
163 files inspected, 1 offense detected, 1 offense autocorrectable
```
=> Fix false positives for `Style/SymbolArray`

changelog/fix_a_false_positive_for_bundler_duplicated_group.md, lib/rubocop/cop/bundler/duplicated_group.rb, spec/rubocop/cop/bundler/duplicated_group_spec.rb
Fix #12113.
This PR fixes a false positive for `Bundler/DuplicatedGroup` when groups are duplicated but `source`, `git`, `platforms`,  or `path` values are different.
=> [Fix #12113] Fix a false positive for `Bundler/DuplicatedGroup`

changelog/fix_false_positives_for_style_redundant_parentheses.md, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
Fixes #12124.
This PR fixes false positives for `Style/RedundantParentheses` when parentheses in `super` or `yield` call with multiline style argument.
=> [Fix #12124] Fix false positives for `Style/RedundantParentheses`

changelog/fix_target_ruby_gem_requirement_support_multiple_version_constraints.md, lib/rubocop/target_ruby.rb, spec/rubocop/target_ruby_spec.rb
This PR adjusts the `gem_requirement` matcher to support multiple version constraints if `Gem::Requirement` is used as a value for `required_ruby_version` in the gemspec. It also allows version constraints in `Gem::Requirement` where the string was frozen with `.freeze`.
More information can be found in the linked issue #12105.
Example which is now supported with this PR:
```ruby
Gem::Specification.new do |s|
s.required_ruby_version = Gem::Requirement.new(['>= 2.3.1'.freeze, '< 3.0.0'.freeze])
end
```
=> [Fix #12105] Adjust target ruby gem requirement matcher and version parsing to support multiple version constraints

changelog/fix_style_redundant_self_assignment_branch_to_handle_heredocs.md, lib/rubocop/cop/style/redundant_self_assignment_branch.rb, spec/rubocop/cop/style/redundant_self_assignment_branch_spec.rb
There is a bug in the autocorrection of `Style/RedundantSelfAssignmentBranch`, which causes the following replacement if `opposite_branch` is a heredoc.
Before:
```ruby
foo =
if some_condition
foo
else
<<~TEXT
bar
TEXT
end
```
After:
```ruby
foo =
<<~TEXT unless some_condition
```
So in this pull request, I will modify it to make up for the missing parts in the case of heredoc.
This implementation is roughly the same as other methods of dealing with heredocs, for example, in `Style/FileWrite`:
https://github.com/rubocop/rubocop/blob/dd299948479c15cc7dd254a339631d241938b20b/lib/rubocop/cop/style/file_write.rb#L108-L121
=> Fix `Style/RedundantSelfAssignmentBranch` to handle heredocs

changelog/fix_a_false_positive_for_style_method_call_with_args_parentheses.md, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
Fixes #12134.
This PR fixes a false positive for `Style/MethodCallWithArgsParentheses` when parentheses are used in one-line `in` pattern matching.
=> [Fix #12134] Fix a false positive for `Style/MethodCallWithArgsParentheses`

changelog/fix_a_false_negative_for_layout_leading_comment_space.md, lib/rubocop/cop/layout/leading_comment_space.rb, spec/rubocop/cop/layout/leading_comment_space_spec.rb
This PR fixes a false negative for `Layout/LeadingCommentSpace` when using `#+` or `#-` as they are not RDoc comments.
They are followed by `+` or `-` twice, such as `#++` and `#--`.
=> Fix a false negative for `Layout/LeadingCommentSpace`

changelog/fix_fix_false_positive_for_style_arguments_forwarding.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
If additional kwargs are supplied then forward-all (`...`) cannot be used.
=> [Fix #12141] Fix false positive for `Style/ArgumentsForwarding`

changelog/fix_a_false_positive_for_lint_to_enum_arguments.md, lib/rubocop/cop/lint/to_enum_arguments.rb, spec/rubocop/cop/lint/to_enum_arguments_spec.rb
Fixes #12143.
This PR fixes a false positive for `Lint/ToEnumArguments` when using anonymous keyword arguments forwarding.
=> [Fix #12143] Fix a false positive for `Lint/ToEnumArguments`

changelog/fix_a_false_positive_for_layout_line_continuation_leading_space.md, lib/rubocop/cop/layout/line_continuation_leading_space.rb, spec/rubocop/cop/layout/line_continuation_leading_space_spec.rb
Fixes rubocop#12138.
This PR fixes a false positive for `Layout/LineContinuationLeadingSpace` when a backslash is part of a multiline string literal.
=> [Fix #12138] Fix a false positive for `Layout/LineContinuationLeadingSpace`

changelog/fix_an_incorrect_autocorrect_for_lint_non_atomic_file_operation.md, lib/rubocop/cop/lint/non_atomic_file_operation.rb, spec/rubocop/cop/lint/non_atomic_file_operation_spec.rb
This PR fixes an incorrect autocorrect for `Lint/NonAtomicFileOperation` when using `FileUtils.remove_dir`, `FileUtils.remove_entry`, or `FileUtils.remove_entry_secure`. The behavior of these methods is closer to `FileUtils.rm_rf` than `FileUtils.rm`, since it also deletes the directory specified as an argument.
=> Fix an incorrect autocorrect for `Lint/NonAtomicFileOperation`

Gemfile
Follow up https://github.com/ruby/ruby/commit/1c93288f8bbf667cb95eb7137b2fe64213894b77.
This PR suppresses the following warning when using Ruby 3.3.0dev
```consle
$ cd path/to/rubocop
$ ruby -v
ruby 3.3.0dev (2023-08-22T14:46:32Z master 7127f39bac) [x86_64-darwin22]
$ bundle exec rake spec
/Users/koic/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/crack-0.4.5/lib/crack/xml.rb:9:
warning: bigdecimal will be not part of the default gems since Ruby 3.4.0. Add it to your Gemfile.
```
crack is a dependency for the testing tool WebMock, so it will be added to the Gemfile:
```console
$ cat Gemfile.lock
(snip)
webmock (3.18.1)
addressable (>= 2.8.0)
crack (>= 0.3.2)
hashdiff (>= 0.4.0, < 2.0.0)
```
The `bigdecimal` dependency can be removed when https://github.com/jnunemaker/crack/pull/75 …
=> Suppress a Ruby warning when using Ruby 3.3.0dev

docs/modules/ROOT/pages/usage/lsp.adoc
Follow up https://github.com/emacs-lsp/lsp-mode/pull/4090.
Emacs LSP Mode supports the built-in language server. So, This PR adds Emacs LSP Mode to the LSP doc.
=> [Docs] Add Emacs (LSP Mode) to the LSP doc

changelog/fix_incorrect_diagnostic_provider_value_of_lsp.md, lib/rubocop/lsp/routes.rb, spec/rubocop/lsp/server_spec.rb
Fixes #12154.
This PR fixes incorrect `diagnosticProvider` value of LSP.
`diagnosticProvider` cannot accept true as below. This PR replaces the originally acceptable value.
```typescript
/**
* The server has support for pull model diagnostics.
*
* @since 3.17.0
*/
diagnosticProvider?: DiagnosticOptions | DiagnosticRegistrationOptions;
```
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize
=> [Fix #12154] Fix incorrect `diagnosticProvider` value of LSP

lib/rubocop/cop/internal_affairs/redundant_method_dispatch_node.rb, lib/rubocop/cop/metrics/method_length.rb, lib/rubocop/cop/style/combinable_loops.rb, lib/rubocop/cop/style/for.rb, spec/rubocop/cop/internal_affairs/redundant_method_dispatch_node_spec.rb
This PR makes `InternalAffairs/RedundantMethodDispatchNode` aware of `method?`:
```ruby
node.send_node.method?(:method_name)
node.method?(:method_name)
```
=> Make `InternalAffairs/RedundantMethodDispatchNode` aware of `method?`

changelog/fix_fix_12168_fix_bug_in_style_arguments_forwarding.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
We were using nodes as Hash keys, which is not supported - the metadata (source location) is not used to distinguish nodes. Thus the two occurrences of the same send (method name and args) were collapsed into one, causing only one of two offense sites to be reported.
=> [Fix #12168]: Fix bug in `Style/ArgumentsForwarding`

changelog/fix_a_false_positive_for_style_empty_case_condition.md, lib/rubocop/cop/style/empty_case_condition.rb, spec/rubocop/cop/style/empty_case_condition_spec.rb
Fixes #12172.
This PR fixes a false positive for `Style/EmptyCaseCondition` when using `return`, `break`, `next` or method call before empty case condition.
=> [Fix #12172] Fix a false positive for `Style/EmptyCaseCondition`

changelog/fix_an_incorrrect_autocorrect_for_style_multiline_ternary_operator.md, lib/rubocop/cop/style/multiline_ternary_operator.rb, spec/rubocop/cop/style/multiline_ternary_operator_spec.rb
This PR fixes an incorrect autocorrect for `Style/MultilineTernaryOperator` when returning a multiline ternary operator expression with safe navigation method call:
```ruby
obj&.x foo ?
bar :
baz
```
It is autocorrected to invalid syntax as follows:
```console
$ bundle exec rubocop --only Style/MultilineTernaryOperator -a
F
Offenses:
example.rb:1:8: C: [Corrected] Style/MultilineTernaryOperator: Avoid multi-line ternary operators, use if or unless instead.
obj&.x foo ? ...
^^^^^
example.rb:3:1: F: Lint/Syntax: unexpected token kELSE
(Using Ruby 3.3 parser; configure using TargetRubyVersion parameter, under AllCops)
else
^^^^
obj&.x if foo
bar
else
baz
end
$ ruby -c example.rb …
```
=> Fix an incorrect autocorrect for `Style/MultilineTernaryOperator`

changelog/fix_an_incorrect_autocorrect_for_style_sole_nested_conditional.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
Fixes #12187.
This PR fixes an incorrect autocorrect for `Style/SoleNestedConditional` when comment is in an empty nested `if` body.
=> [Fix #12187] Fix an incorrect autocorrect for `Style/SoleNestedConditional`

changelog/fix_set_target_version_for_layout_heredoc_indentation.md, lib/rubocop/cop/layout/heredoc_indentation.rb, spec/rubocop/cop/layout/heredoc_indentation_spec.rb
The squiggly heredoc syntax was introduced in Ruby 2.3. Therefore, this
linter should not flag any offenses for Ruby < 2.3 code.
Additionally, this linter is considered to be safe for autocorrection,
meaning that it is likely to break compatibility with older Ruby
versions.
=> Set target version for Layout/HeredocIndentation

changelog/fix_a_false_positive_for_layout_space_around_operators.md, lib/rubocop/cop/mixin/preceding_following_alignment.rb, spec/rubocop/cop/layout/space_around_operators_spec.rb
Fixes #12190.
This PR fixes a false positive for `Layout/SpaceAroundOperators` when aligning operators vertically.
=> [Fix #12190] Fix a false positive for `Layout/SpaceAroundOperators`

changelog/fix_an_error_for_lint_useless_assignment.md, lib/rubocop/cop/lint/useless_assignment.rb, spec/fixtures/html_formatter/expected.html, spec/fixtures/markdown_formatter/expected.md, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/lint/useless_assignment_spec.rb
Fixes #12182.
This PR fixes an error for `Lint/UselessAssignment` when variables are assigned with chained assignment and unreferenced.
As we added to spec/rubocop/cli/autocorrect_spec.rb, detection and autocorrection will eventually be possible as before.
=> [Fix #12182] Fix an error for `Lint/UselessAssignment`

changelog/fix_a_false_positive_for_style_array_intersect.md, lib/rubocop/cop/style/array_intersect.rb, spec/rubocop/cop/style/array_intersect_spec.rb
Fixes #12171.
This PR fixes a false positive for `Style/ArrayIntersect` when using block argument for `Enumerable#any?`.
Note: This cop is already marked as unsafe.
=> [Fix #12171] Fix a false positive for `Style/ArrayIntersect`

changelog/fix_a_false_negative_for_layout_space_after_not.md, lib/rubocop/cop/layout/space_after_not.rb, spec/rubocop/cop/layout/space_after_not_spec.rb
Fixes #12195.
This PR fixes a false negative for `Layout/SpaceAfterNot` when a newline is present after `!`.
=> [Fix #12195] Fix a false negative for `Layout/SpaceAfterNot`

changelog/new_make_layout_empty_line_after_guard_clause_allow_nocov_direcive.md, lib/rubocop/cop/layout/empty_line_after_guard_clause.rb, spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb
Resolves #12151.
This PR makes `Layout/EmptyLineAfterGuardClause` allow `:nocov:` directive after guard clause.
SimpleCov excludes code from the coverage report by wrapping it in `# :nocov:`: https://github.com/simplecov-ruby/simplecov#ignoringskipping-code
=> [Fix #12151] Make `Layout/EmptyLineAfterGuardClause` allow `:nocov:` directive

lib/rubocop/file_finder.rb, lib/rubocop/rspec/shared_contexts.rb, spec/isolated_environment_spec.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/team_spec.rb, spec/rubocop/target_finder_spec.rb, spec/support/file_helper.rb
Previously, stop_dir was ignored when FileFinde.root_level was present.
Tests that should have relied on stop_dir being set correctly, instead passed because the root_level happened to be the same as the stop_dir because of how the test was constructed.
Shift where FileFinder.root_level is set so that we use root_level only for protecting the test environment tmpdir. It is now set to the actual root of the tmpdir, above which nothing should be written in isolated environment tests.
This is a partial extraction of fixes in #12147, which had to fix too many problems like this and became too large.
=> Fix shadowing of FileFinder stop_dir in isolated tests.

changelog/change_make_style_collection_methods_aware_of_collect_concat.md, config/default.yml, lib/rubocop/cop/style/collection_methods.rb
This PR makes `Style/CollectionMethods` aware of `collect_concat` because matches the existing `map` and `collect` terminology selection.
=> Make `Style/CollectionMethods` aware of `collect_concat`

changelog/fix_false_negatives_for_layout_multiline_method_call_indentation.md, lib/rubocop/cop/layout/multiline_method_call_indentation.rb, lib/rubocop/cop/mixin/multiline_expression_indentation.rb, spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb
Fixes #12199.
This PR fixes false negatives for `Layout/MultilineMethodCallIndentation` when using safe navigation operator.
=> [Fix #12199] Fix false negatives for `Layout/MultilineMethodCallIndentation`

changelog/fix_an_incorrect_autocorrect_for_style_redundant_conditional.md, lib/rubocop/cop/style/redundant_conditional.rb, spec/rubocop/cop/style/redundant_conditional_spec.rb
This PR fix an incorrect autocorrect for `Style/RedundantConditional` when unless/else with boolean results.
The following code:
```ruby
unless x == y
true
else
false
end
```
Expected autocorrection
```ruby
!(x == y)
```
Actual autocorrection
```ruby
x == y
```
=> Fix an incorrect autocorrect for `Style/RedundantConditional` when unless/else with boolean results

changelog/fix_an_incorrect_autocorrect_for_lint_safe_navigation_chain.md, lib/rubocop/cop/lint/safe_navigation_chain.rb, spec/rubocop/cop/lint/safe_navigation_chain_spec.rb
This PR fixes an incorrect autocorrect for `Lint/SafeNavigationChain` when using safe navigation with comparison operator as an expression of logical operator or comparison operator's operand:
The autocorrected code is a syntax error:
```console
$ echo 'do_something && x&.foo >= bar' | be rubocop --stdin example.rb -a
F
Offenses:
example.rb:1:2: C: [Corrected] Layout/InitialIndentation: Indentation of first line in file detected.
do_something && x&.foo >= bar
^^^^^^^^^^^^
example.rb:1:24: W: [Corrected] Lint/SafeNavigationChain: Do not chain ordinary method call after safe navigation operator.
do_something && x&.foo >= bar
^^^^^^^
example.rb:1:29: F: Lint/Syntax: unexpected token tIDENTIFIER
(Using Ruby 2.7 parser; configure using TargetRubyVersion parameter, under …
```
=> Fix an incorrect autocorrect for `Lint/SafeNavigationChain`

lib/rubocop/cop/internal_affairs/example_description.rb, spec/rubocop/cop/internal_affairs/example_description_spec.rb
This PR supports autocorrect for `InternalAffairs/ExampleDescription`.
=> Support autocorrect for `InternalAffairs/ExampleDescription`

changelog/fix_an_error_for_style_operator_method_call.md, lib/rubocop/cop/style/operator_method_call.rb, spec/rubocop/cop/style/operator_method_call_spec.rb
Fixes #12205.
This PR fixes an error for `Style/OperatorMethodCall` when using `foo bar./ baz`.
=> [Fix #12205] Fix an error for `Style/OperatorMethodCall`

changelog/fix_an_incorrect_autocorrect_for_style_operator_method_call.md, lib/rubocop/cop/style/operator_method_call.rb, spec/rubocop/cop/style/operator_method_call_spec.rb
This PR fixes an incorrect autocorrect for `Style/OperatorMethodCall` when using `foo./bar`:
```console
% echo 'arg./100.0' | bundle exec rubocop --stdin example.rb -a -d
(snip)
F
Offenses:
example.rb:1:4: C: [Corrected] Style/OperatorMethodCall: Redundant dot detected.
arg./100.0
^
example.rb:1:5: F: Lint/Syntax: ambiguous first argument; put parentheses or a space even after the operator
arg /100.0
^
arg /100.0
```
It solves the above `Lint/Syntax`.
=> Fix an incorrect autocorrect for `Style/OperatorMethodCall`

lib/rubocop/cop/style/return_nil.rb
This PR updates the doc for `Style/ReturnNil` based on the following comments about why `Style/ReturnNil` cop is disabled by default.
https://github.com/rubocop/rubocop/pull/4638#issuecomment-325219286
=> [Docs] Update the doc for `Style/ReturnNil`

changelog/fix_a_false_positive_for_lint_ordered_magic_comments.md, lib/rubocop/magic_comment.rb, spec/rubocop/cop/lint/ordered_magic_comments_spec.rb
Fixes #12213.
This PR fixes a false positive for `Lint/OrderedMagicComments` when comment text `# encoding: ISO-8859-1` is embedded within example code as source code comment.
=> [Fix #12213] Fix a false positive for `Lint/OrderedMagicComments`

changelog/fix_an_incorrect_autocorrect_for_disable_uncorrectable_option.md, lib/rubocop/cop/autocorrect_logic.rb, spec/rubocop/cli/disable_uncorrectable_spec.rb
Fixes #12208.
This PR fixes an incorrect autocorrect for the `--disable-uncorrectable` command line option when registering an offense is outside a percent array.
=> [Fix #12208] Fix an incorrect autocorrect for the `--disable-uncorrectable` option

changelog/fix_a_false_positive_for_layout_empty_line_after_guard_clause.md, lib/rubocop/cop/layout/empty_line_after_guard_clause.rb, spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb
Fixes #12221.
This PR fixes a false positive for `Layout/EmptyLineAfterGuardClause` when using `return` before guard condition with heredoc.
=> [Fix #12221] Fix a false positive for `Layout/EmptyLineAfterGuardClause`

changelog/change_mark_style_redundant_filter_chain_as_unsafe_autocorrect.md, config/default.yml, lib/rubocop/cop/style/redundant_filter_chain.rb
Fixes #12210.
This PR marks `Style/RedundantFilterChain` as unsafe autocorrect.
=> [Fix #12210] Mark `Style/RedundantFilterChain` as unsafe autocorrect

changelog/change_make_style_guard_clause_aware_of_define_method.md, lib/rubocop/cop/style/guard_clause.rb, spec/rubocop/cop/style/guard_clause_spec.rb
Fixes #12128.
This PR makes `Style/GuardClause` aware of `define_method`.
=> [Fix #12128] Make `Style/GuardClause` aware of `define_method`

changelog/change_make_style_redundant_filter_chain_aware_of_select_present.md, lib/rubocop/cop/style/redundant_filter_chain.rb, spec/rubocop/cop/style/redundant_filter_chain_spec.rb
Resolves: rubocop/rubocop-rails#1048.
This PR makes `Style/RedundantFilterChain` aware of `select.present?` when `AllCops/ActiveSupportExtensionsEnabled: true`.
=> Make `Style/RedundantFilterChain` aware of `select.present?`

changelog/fix_false_negatives_for_style_multiline_block_chain.md, lib/rubocop/cop/style/multiline_block_chain.rb, spec/rubocop/cop/style/multiline_block_chain_spec.rb
This PR fixes false negatives for `Style/MultilineBlockChain` when using multiline block chain with safe navigation operator.
=> Fix false negatives for `Style/MultilineBlockChain`

changelog/fix_false_positives_for_layout_multiline_method_call_indentation.md, lib/rubocop/cop/layout/multiline_method_call_indentation.rb, spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb
Fixes #12226.
This PR fixes false positives for `Layout/MultilineMethodCallIndentation` when aligning methods in multiline block chain.
=> [Fix #12226] Fix false positives for `Layout/MultilineMethodCallIndentation`

lib/rubocop/cop/style/redundant_begin.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
This PR tweaks autocorrection for `Style/RedundantBegin` when using endless method definition with redundant `begin`.
```ruby
def foo = begin
bar
end
```
```console
% bundle exec rubocop --only Style/RedundantBegin -a
(snip)
example.rb:1:11: C: [Corrected] Style/RedundantBegin: Redundant begin block detected.
def foo = begin
^^^^^
```
```ruby
def foo =
bar
```
```ruby
def foo =  bar
```
This would be more closer to a one-liner endless idiom.
=> Tweak autocorrection for `Style/RedundantBegin`

changelog/change_enable_auto_parallel_inspection_when_config_file.md, lib/rubocop/cli.rb, spec/rubocop/cli_spec.rb
This change also allows automatic parallel inspection when a config file is explicitly specified.
=> Enable auto parallel inspection when config file is specified

changelog/fix_an_error_for_style_nested_ternary_operator.md, lib/rubocop/cop/style/nested_ternary_operator.rb, spec/rubocop/cop/style/nested_ternary_operator_spec.rb
Fixes #12237.
This PR fixes an error for `Style/NestedTernaryOperator` when a ternary operator has a nested ternary operator within an `if`.
=> [Fix #12237] Fix an error for `Style/NestedTernaryOperator`

changelog/fix_a_false_negative_for_metrics_module_length.md, lib/rubocop/cop/metrics/utils/code_length_calculator.rb, spec/rubocop/cop/metrics/module_length_spec.rb
Fixes #12231.
This PR fixes a false negative for `Metrics/ModuleLength` when defining a singleton class in a module.
=> [Fix #12231] Fix a false negative for `Metrics/ModuleLength`

changelog/fix_an_error_for_flip_flop_with_beginless_or_endless_ranges.md, rubocop.gemspec
Fixes #12198.
Parser 3.2.2.4 includes https://github.com/whitequark/parser/pull/946.
This PR requires Parser 3.2.2.4+ to fix an error for flip-flop with beginless or endless ranges.
=> [Fix #12198] Fix an error for flip-flop with beginless or endless ranges

changelog/fix_a_false_negative_for_lint_debugger.md, lib/rubocop/cop/lint/debugger.rb, spec/rubocop/cop/lint/debugger_spec.rb
Fixes #12244.
This PR fixes a false negative for `Lint/Debugger` when using debugger method inside block.
=> [Fix #12244] Fix a false negative for `Lint/Debugger`

changelog/new_make_lint_redundant_safe_navigation_aware_of_const_receiver.md, lib/rubocop/cop/lint/redundant_safe_navigation.rb, spec/rubocop/cop/lint/redundant_safe_navigation_spec.rb
Fixes https://github.com/rubocop/rubocop-rails/issues/1104.
This is an issue with RuboCop Rails, but it can likely be addressed as a generic issue.
So, this PR makes `Lint/RedundantSafeNavigation` aware of constant receiver. Because use cases where a constant is `nil` are rare and an offense is detected when the receiver is a constant. And this cop is already marked as unsafe.
=> Make `Lint/RedundantSafeNavigation` aware of constant receiver

changelog/change_enhance_style_format_string_autocorrection.md, lib/rubocop/cop/style/format_string.rb, spec/rubocop/cop/style/format_string_spec.rb
This PR enhances `Style/FormatString`'s autocorrection when using known conversion methods whose return value is not an array.
=> Enhance `Style/FormatString`'s autocorrection

changelog/change_mark_lint_redundant_require_statement_as_unsafe_autocorrect.md, config/default.yml, lib/rubocop/cop/lint/redundant_require_statement.rb
Follow up https://github.com/rubocop/rubocop/pull/11931#issuecomment-1603717583.
This PR marks `Lint/RedundantRequireStatement` as unsafe autocorrect because if `require 'pp'` is removed from one file, `NameError` can be encountered when another file uses `PP.pp`.
=> Mark `Lint/RedundantRequireStatement` as unsafe autocorrect

changelog/fix_false_negatives_for_style_redundant_parentheses.md, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
This PR fix false negatives for `Style/RedundantParentheses` when using logical or comparison expressions with redundant parentheses.
e.g. `assert(('rubocop-minitest' == actual))`
=> Fix false negatives for `Style/RedundantParentheses`

changelog/fix_accept_empty_string_literal_interpolated_in_words_literal.md, lib/rubocop/cop/lint/literal_in_interpolation.rb, spec/rubocop/cop/lint/literal_in_interpolation_spec.rb
An empty string in those words literals is significant and should not be expanded.
e.g.
```ruby
system(*%W[git commit -m #{""} file])
```
=> Lint/LiteralInInterpolation: Accept an empty string literal interpolated in %W[]/%I[]

changelog/fix_a_false_positive_for_style_identical_conditional_branches.md, lib/rubocop/cop/style/identical_conditional_branches.rb, spec/rubocop/cop/style/identical_conditional_branches_spec.rb
Fixes #12249.
This PR fixes a false positive `Style/IdenticalConditionalBranches` when `if`..`else` with identical leading lines and assign to condition value.
=> [Fix #12249] Fix a false positive `Style/IdenticalConditionalBranches`

changelog/new_make_style_redundant_double_splat_hash_braces_aware_of_merge.md, lib/rubocop/cop/style/redundant_double_splat_hash_braces.rb, spec/rubocop/cop/style/redundant_double_splat_hash_braces_spec.rb
Resolves #12257.
This PR makes `Style/RedundantDoubleSplatHashBraces` aware of `merge` methods. Instead of introducing a new cop, this `Style/RedundantDoubleSplatHashBraces` cop can be extended.
=> [Fix #12257] Make `Style/RedundantDoubleSplatHashBraces` aware of `merge`

changelog/fix_an_error_for_lint_mixed_case_range.md, lib/rubocop/cop/lint/mixed_case_range.rb, spec/rubocop/cop/lint/mixed_case_range_spec.rb
Fixes #12259.
This PR fixes an error for `Lint/MixedCaseRange` when using nested character class in regexp.
=> [Fix #12259] Fix an error for `Lint/MixedCaseRange`

changelog/fix_inconsistent_cache_key_caused_by_fileutils_require.md, lib/rubocop/server/cache.rb
This PR fixes #12076.
The reproduction script: https://gist.github.com/K-S-A/1d79105baaa88adde1b6e5f6b05d641a
Please, suggest on how to proceed with the "tests" checklist item.
=> RuboCop::Server::Cache: explicitly require 'fileutils'

changelog/fix_an_incorrect_autocorrect_for_style_redundant_exception.md, lib/rubocop/cop/style/redundant_exception.rb, spec/rubocop/cop/style/redundant_exception_spec.rb
The following autocorrection is performed, but when the message is not a string, the behavior changes after the autocorrection.
```ruby
raise RuntimeError, Object.new
raise Object.new
```
Therefore, this PR fixes so that the behavior does not change.
```ruby
irb(main):001:0> e = raise Object.new rescue $!
=> #<TypeError: exception class/object expected>
irb(main):002:0> e = raise RuntimeError, Object.new rescue $!
=> #<RuntimeError: #<Object:0x000000010f369da8>>
irb(main):003:0> e = raise Object.new.to_s rescue $!
=> #<RuntimeError: #<Object:0x000000010f3402a0>>
irb(main):004:0> e = raise RuntimeError.new(Object.new) rescue $!
=> #<RuntimeError: #<Object:0x00000001049d3e88>>
irb(main):005:0> e = raise RuntimeError.new Object.new  rescue $!
=> #<RuntimeError: #<Object:0x00000001079dadc0>> …
```
=> Fix an incorrect autocorrect for `Style/RedundantException` when message is not string

changelog/fix_an_error_for_layout_multiline_method_call_indentation.md, lib/rubocop/cop/layout/multiline_method_call_indentation.rb, spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb
Fixes #12265.
This PR fixes an error for `Layout/MultilineMethodCallIndentation` when usingarithmetic operation with block inside a grouped expression.
=> [Fix #12265] Fix an error for `Layout/MultilineMethodCallIndentation`

changelog/fix_an_infinite_loop_for_layout_multiline_method_call_indentation.md, lib/rubocop/cop/layout/multiline_method_call_indentation.rb, spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb
Fix: https://github.com/rubocop/rubocop/issues/12261
=> Fix an infinite loop for `Layout/MultilineMethodCallIndentation`

changelog/fix_false_positive_for_style_redundant_double_splat_hash_braces.md, lib/rubocop/cop/style/redundant_double_splat_hash_braces.rb, spec/rubocop/cop/style/redundant_double_splat_hash_braces_spec.rb
Fixes #12263.
This PR fixes false positives for `Style/RedundantDoubleSplatHashBraces` when method call for no hash braced double splat receiver.
The code shown in #12263 is incompatible as shown below and is a false positive:
```ruby
def x(opts) = puts(opts)
h = {foo: :bar}
x(**h.merge(k: :h)) #=> {:foo=>:bar, :k=>:h}
x(k: :v, **h)       #=> {:k=>:v, :foo=>:bar}
```
=> Fix false positives for `Style/RedundantDoubleSplatHashBraces`

changelog/fix_a_false_positive_for_lint_redundant_safe_navigation.md, lib/rubocop/cop/lint/redundant_safe_navigation.rb, spec/rubocop/cop/lint/redundant_safe_navigation_spec.rb
Fixes #12271.
This PR fixes a false positive for `Lint/RedundantSafeNavigation` when using snake case constant receiver.
Camel case is used for naming classes and modules, while snake case is used for all other constants. This naming conforms with `Naming/ConstantName` cop.
Since constants that turn into classes or modules are normally not `nil`, they will continue to be detected.
However, this PR will update to allow safe navigation for constants in snake case.
This change resolves both issue https://github.com/rubocop/rubocop-rails/issues/1104 and #12271.
=> [Fix #12271] Fix a false positive for `Lint/RedundantSafeNavigation`

changelog/fix_false_positives_for_style_redundant_double_splat_hash_brace.md, lib/rubocop/cop/style/redundant_double_splat_hash_braces.rb, spec/rubocop/cop/style/redundant_double_splat_hash_braces_spec.rb
Fixes #12275.
This PR fixes a false positive for `Style/RedundantDoubleSplatHashBraces` when using double splat within block argument containing a hash literal in an array literal.
=> [Fix #12275] Fix a false positive for `Style/RedundantDoubleSplatHashBraces`

changelog/fix_false_positives_for_lint_empty_conditional_body.md, lib/rubocop/cop/mixin/comments_help.rb, spec/rubocop/cop/lint/empty_conditional_body_spec.rb
Fixes #12279.
This PR fixes false positives for `Lint/EmptyConditionalBody` when missing 2nd `if` body with a comment.
=> [Fix #12279] Fix false positives for `Lint/EmptyConditionalBody`

changelog/fix_an_error_for_style_single_line_do_end_block.md, lib/rubocop/cop/style/single_line_do_end_block.rb, spec/rubocop/cop/style/single_line_do_end_block_spec.rb
This PR fixes the following error for `Style/SingleLineDoEndBlock` when using single line `do`...`end` with no body
```console
$ echo 'foo do end' | bunlde exec rubocop --stdin test.rb -d --only Style/SingleLineDoEndBlock
(snip)
An error occurred while Style/SingleLineDoEndBlock cop was inspecting
/Users/koic/src/github.com/rubocop/rubocop/test.rb:1:0.
Expected a Parser::Source::Range, Comment or RuboCop::AST::Node, got NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/corrector.rb:111:in `to_range'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/corrector.rb:120:in `check_range_validity'
/Users/koic/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/parser-3.2.2.4/
lib/parser/source/tree_rewriter.rb:398:in `combine' …
```
=> Fix an error for `Style/SingleLineDoEndBlock`

changelog/fix_false_positive_for_style_redundant_double_splat_hash_braces.md, lib/rubocop/cop/style/redundant_double_splat_hash_braces.rb, spec/rubocop/cop/style/redundant_double_splat_hash_braces_spec.rb
Fixes #12286.
This PR fix false positives for `Style/RedundantDoubleSplatHashBraces` when using double splat with a hash literal enclosed in parenthesized ternary operator.
=> [Fix #12286] Fix false positives for `Style/RedundantDoubleSplatHashBraces`

changelog/fix_a_false_positive_for_metrics_class_length.md, lib/rubocop/cop/metrics/class_length.rb, spec/rubocop/cop/metrics/class_length_spec.rb
Fixes #12291.
This PR fixes a false positive for `Metrics/ClassLength` when a class with a singleton class definition.
=> [Fix #12291] Fix a false positive for `Metrics/ClassLength`

changelog/changelog/fix_a_false_positive_for_style_redundant_double_splat_hash_braces.md, lib/rubocop/cop/style/redundant_double_splat_hash_braces.rb, spec/rubocop/cop/style/redundant_double_splat_hash_braces_spec.rb
Fixes #12293.
This PR fixes a false positive for `Style/RedundantDoubleSplatHashBraces` when using double splat hash braces with `merge` and method chain.
=> [Fix #12293] Fix a false positive for `Style/RedundantDoubleSplatHashBraces`

changelog/fix_a_false_positive_for_style_redundant_parentheses.md, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
Fixes #12298.
This PR fixes a false positive for `Style/RedundantParentheses` when using a parenthesized hash literal as the first argument in a method call without parentheses.
=> [Fix #12298] Fix a false positive for `Style/RedundantParentheses`

changelog/fix_make_style_redundant_filter_chain_aware_of_safe_navigation.md, lib/rubocop/cop/style/redundant_filter_chain.rb, spec/rubocop/cop/style/redundant_filter_chain_spec.rb
Fixes #12301.
This PR makes `Style/RedundantFilterChain` aware of safe navigation.
=> [Fix #12301] Make `Style/RedundantFilterChain` aware of safe navigation

changelog/fix_false_positives_for_style_single_argument_dig.md, lib/rubocop/cop/style/single_argument_dig.rb, spec/rubocop/cop/style/single_argument_dig_spec.rb
Fixes #12284.
This PR fixes false positives for `Style/SingleArgumentDig` when using some anonymous argument syntax.
=> [Fix #12284] Fix false positives for `Style/SingleArgumentDig`

changelog/fix_error_for_style_identical_conditional_branches.md, lib/rubocop/cop/style/identical_conditional_branches.rb, spec/rubocop/cop/style/identical_conditional_branches_spec.rb
Fixes #12300.
This PR fixes an error for `Style/IdenticalConditionalBranches` when `if`...`else` with identical leading lines and using index assign.
In RuboCop, the `send` node is used instead of the `indexasgn` node, so `name` cannot be used. https://github.com/rubocop/rubocop-ast/blob/v1.29.0/lib/rubocop/ast/node/indexasgn_node.rb
=> [Fix 12300] Fix an error for `Style/IdenticalConditionalBranches`

changelog/fix_auto_gen_config_with_erb.md, lib/rubocop/cli/command/auto_generate_config.rb, spec/rubocop/cli/auto_gen_config_spec.rb
The problem with the existing algorithm, for generating the `inherit_from` line in `--auto-gen-config` runs, was that we started by removing the `inherit_from` (if present) and then inserted it later.
The things we must deal with in the algorithm are
* there could be a pre-existing `inherit_from` in `.rubocop.yml`, or not
* there could be a YAML doc start `---`, or not
* there could be inheritance from one or multiple files
A more robust approach to the removing, generating, and re-inserting is to assume that any pre-existing `inherit_from` directive is already in the right place. By replacing it with a placeholder and later replacing the placeholder with the new inheritance directive, we will get it right without much effort.
=> [Fix #11652] Generate inherit_from correctly also with ERB

changelog/fix_a_false_positive_for_lint_void.md, lib/rubocop/cop/lint/void.rb, spec/rubocop/cop/lint/void_spec.rb
Fixes #12274.
This PR fixes a false positive for `Lint/Void` when `each`'s receiver is an object of `Enumerator` to which `filter` has been applied.
`each` blocks are allowed to prevent false positives. The expression inside the following block is not void:
```ruby
enumerator = [1, 2, 3].filter
enumerator.each { |item| item >= 2 } #=> [2, 3]
```
This might introduce false negatives, but higher severity Lint cop should aim for as safe detections as possible, I think.
=> [Fix #12274] Fix a false positive for `Lint/Void`

changelog/fix_an_infinite_loop_error_for_layout_end_alignment.md, lib/rubocop/cop/layout/end_alignment.rb, spec/rubocop/cop/layout/end_alignment_spec.rb
Fixes #12307.
This PR fixes an infinite loop error for `Layout/EndAlignment` when `EnforcedStyleAlignWith: variable` and using a conditional statement in a method argument on the same line and `end` with method call is not aligned.
=> [Fix #12307] Fix an infinite loop error for `Layout/EndAlignment`

changelog/fix_drop_base64_gem_from_runtime_dependency.md, lib/rubocop/formatter/html_formatter.rb, rubocop.gemspec
Fixes #12310.
This PR drops `base64` gem from runtime dependency.
RuboCop only uses `Base64.encode64` from the `base64` gem. Therefore, there's no need to depend on the entire `base64` gem. The implementation of `Base64.encode64` is quite simple: https://github.com/ruby/base64/blob/v0.1.1/lib/base64.rb#L27-L40
This change is a better approach that has also been adopted by https://github.com/rack/rack/pull/2110.
=> [Fix #12310] Drop `base64` gem from runtime dependency

changelog/fix_an_incorrect_autocorrect_style_hash_syntax.md, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
Fixes #12312.
This PR fixes an incorrect autocorrect for `Style/HashSyntax` when braced hash key and value are the same and it is used in `if`...`else`.
=> [Fix #12312] Fix an incorrect autocorrect for `Style/HashSyntax`

docs/modules/ROOT/pages/usage/lsp.adoc
The [newly released Helix 23.10](https://helix-editor.com/news/release-23-10-highlights/) changed the language config structure with the introduction of multiple language server support.
This change updates the example to reflect the current configuration instructions based on the docs: https://docs.helix-editor.com/languages.html#language-server-configuration
=> Update Helix LSP config based on v23.10 changes

spec/project_spec.rb
Follow up https://github.com/rubocop/rubocop/commit/d995cb4
This PR adds a project spec to prevent an unexpected changelog entry file path. For instance, if an unexpected file named `changelog/changelog/fix_foo.md` exists, it will fail as follows:
```console
$ bundle exec rspec spec/project_spec.rb:309
(snip)
1) RuboCop Project Changelog future entries will not have a directory
Failure/Error: expect(Dir[dir].all? { |path| File.file?(path) }).to be(true)
expected true
got false
Finished in 0.02034 seconds (files took 1.71 seconds to load)
1 example, 1 failure
rspec ./spec/project_spec.rb:308 # RuboCop Project Changelog future entries will not have a directory
```
[1]: …
=> Add a project spec

changelog/fix_error_for_layout_rescue_ensure_alignment.md, lib/rubocop/cop/layout/rescue_ensure_alignment.rb, spec/rubocop/cop/layout/rescue_ensure_alignment_spec.rb
Fixes #12324.
This PR fixes an error for `Layout/RescueEnsureAlignment` when using `rescue` in `do`...`end` block assigned to object attribute.
=> [Fix #12324] Fix an error for `Layout/RescueEnsureAlignment`

changelog/fix_error_for_style_combinable_loops.md, lib/rubocop/cop/style/combinable_loops.rb, spec/rubocop/cop/style/combinable_loops_spec.rb
Fixes #12322.
This PR fixes an error for `Style/CombinableLoops` when looping over the same data for the third consecutive time or more.
=> [Fix #12322] Fix an error for `Style/CombinableLoops`

changelog/fix_an_error_for_style_redundant_double_splat_hash_braces.md, lib/rubocop/cop/style/redundant_double_splat_hash_braces.rb, spec/rubocop/cop/style/redundant_double_splat_hash_braces_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/12275#issuecomment-1786554892.
This PR fixes an error for `Style/RedundantDoubleSplatHashBraces` when method call for parenthesized no hash double double splat.
=> Fix an error for `Style/RedundantDoubleSplatHashBraces`

lib/rubocop/cop/internal_affairs/method_name_equal.rb, lib/rubocop/cop/lint/duplicate_methods.rb, lib/rubocop/cop/style/auto_resource_cleanup.rb, lib/rubocop/cop/style/conditional_assignment.rb, spec/rubocop/cop/internal_affairs/method_name_equal_spec.rb
This PR makes `InternalAffairs/MethodNameEqual` aware of `node.method_name != method_name` and suppresses the following new offenses:
```console
$ bundle exec rubocop -a
(snip)
Offenses:
lib/rubocop/cop/lint/duplicate_methods.rb:256:13: C: [Corrected] InternalAffairs/MethodNameEqual:
Use !ancestor.method?(:class_eval) instead.
ancestor.method_name != :class_eval && !ancestor.class_constructor?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/rubocop/cop/style/auto_resource_cleanup.rb:28:13: C: [Corrected] Style/NegatedIf:
Favor unless over if for negative conditions.
next if !node.method?(target_method)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/rubocop/cop/style/auto_resource_cleanup.rb:28:21: C: [Corrected] InternalAffairs/MethodNameEqual:
Use !node.method?(target_method) instead.
next if …
```
=> Make `InternalAffairs/MethodNameEqual` aware of `!=`

changelog/change_change_make_style_auto_resource_cleanup_aware_of_tempfile_open.md, lib/rubocop/cop/style/auto_resource_cleanup.rb, spec/rubocop/cop/style/auto_resource_cleanup_spec.rb
Fixes #12328.
This PR makes `Style/AutoResourceCleanup` aware of `Tempfile.open`.
=> [Fix #12328] Make `Style/AutoResourceCleanup` aware of `Tempfile.open`

changelog/fix_an_incorrect_autocorrect_for_naming_block_fowarding.md, lib/rubocop/cop/naming/block_forwarding.rb, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cli/autocorrect_spec.rb
Fixes #12361.
Fix an incorrect autocorrect for `Naming/BlockForwarding` and `Style/ArgumentsForwarding` when autocorrection conflicts for anonymous arguments.
=> [Fix #12361] Fix an incorrect autocorrect for `Naming/BlockForwarding`

changelog/change_support_a_new_enforced_style_for_layout_space_around_operators.md, config/default.yml, lib/rubocop/cop/layout/space_around_operators.rb, spec/rubocop/cli/auto_gen_config_spec.rb, spec/rubocop/cop/layout/space_around_operators_spec.rb
Fixes #12337.
This PR supports `EnforcedStyleForRationalLiterals` option for `Layout/SpaceAroundOperators`. Like `SupportedStylesForExponentOperator` option, the default follows the style guide with `no_space`.
=> [Fix #12337] Support `EnforcedStyleForRationalLiterals` for `Layout/SpaceAroundOperators`

changelog/fix_incorrect_rendering_in_formatter_html_formatter.md, lib/rubocop/formatter/html_formatter.rb, spec/fixtures/html_formatter/expected.html, spec/fixtures/html_formatter/project/app/models/book.rb, spec/rubocop/formatter/html_formatter_spec.rb
Fixes #12363.
This PR fixes incorrect rendering of HTML character entities in `HTMLFormatter` formatter.
=> [Fix #12363] Fix incorrect rendering in `HTMLFormatter` formatter

changelog/fix_false_negative_for_layout_extra_spacing.md, lib/rubocop/cop/layout/extra_spacing.rb, spec/rubocop/cop/layout/extra_spacing_spec.rb
Currently we use `each_cons(3)` to find comments that align with their neighbours, but this means the first and last comments aren't checked. We treat them as always aligned, but this leads to false negatives.
We can instead use `each_cons(2)` to look at each pair of comments and add both if they're aligned. This does mean that sometimes lines are added twice, but this is fine since `Set#<<` is idempotent.
=> Don't assume first and last comments are aligned

changelog/fix_a_false_negative_for_lint_debugger.md, lib/rubocop/cop/lint/debugger.rb, spec/rubocop/cop/lint/debugger_spec.rb
Fixes #12372.
This PR fixes a false negative for `Lint/Debugger` when used within method arguments a `begin`...`end` block.
=> [Fix #12372] Fix a false negative for `Lint/Debugger`

changelog/fix_false_negatives_for_style_redundant_parentheses.md, lib/rubocop/cop/mixin/preceding_following_alignment.rb, lib/rubocop/cop/style/redundant_parentheses.rb, lib/rubocop/cop/style/redundant_string_escape.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
Fixes #12311.
This PR fixes false negatives for `Style/RedundantParentheses` when parentheses around logical operator keywords in method definition.
=> [Fix #12311] Fix false negatives for `Style/RedundantParentheses`

changelog/fix_a_false_positive_for_layout_space_before_semicolon.md, lib/rubocop/cop/mixin/space_before_punctuation.rb, spec/rubocop/cop/layout/space_before_semicolon_spec.rb
Fixes #12374.
This PR fixes a false positive for `Layout/SpaceBeforeSemicolon` when a space between an opening lambda brace and a semicolon.
NOTE: When `Token#left_curly_brace?` supports `:tLAMBEG`, the condition `token.type == :tLAMBEG` can be removed.
=> [Fix #12374] Fix a false positive for `Layout/SpaceBeforeSemicolon`

changelog/fix_a_false_negative_for_style_semicolon.md, lib/rubocop/cop/style/semicolon.rb, spec/rubocop/cop/style/semicolon_spec.rb
This PR fixes a false negative for `Style/Semicolon` when a semicolon at the beginning of a lambda block.
=> Fix a false negative for `Style/Semicolon`

changelog/change_make_style_redundant_parentheses_aware_of_lambda_or_proc.md, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
Fixes #12380.
This PR makes `Style/RedundantParentheses` aware of lambda or proc.
=> [Fix #12380] Make `Style/RedundantParentheses` aware of lambda or proc

docs/modules/ROOT/pages/integration_with_other_tools.adoc, docs/modules/ROOT/pages/usage/lsp.adoc
Hello everyone,
I just updated the docs regarding Sublime Text plugins and LSP. Hope this helps other users.
Please feel free to request changes or do them on your own if I missed something. Thanks!
Cheers!
* [x ] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [ x] Wrote [good commit messages][1].
* [ -] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x ] Feature branch is up-to-date with `master` (if not - rebase it).
* [ -] Added tests.
* [- ] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
=> [Docs] Add Sublime Text section for LSP usage

changelog/fix_false_negatives_for_style_redundant_return.md, lib/rubocop/cop/style/redundant_return.rb, spec/rubocop/cop/style/redundant_return_spec.rb
Fixes #12394.
This PR fixes false negatives for `Style/RedundantReturn` when `lambda`, `->`, or `proc` ending with `return`.
=> [Fix #12394] Fix false negatives for `Style/RedundantReturn`

changelog/fix_false_positives_for_lint_void.md, lib/rubocop/cop/lint/void.rb, spec/rubocop/cop/lint/void_spec.rb
Fixes #12377.
This PR fixes false positives for `Lint/Void` when a collection literal that includes non-literal elements in a method definition.
=> [Fix #12377] Fix false positives for `Lint/Void`

changelog/fix_false_negative_for_lint_symbol_conversion.md, lib/rubocop/cop/gemspec/deprecated_attribute_assignment.rb, lib/rubocop/cop/lint/symbol_conversion.rb, lib/rubocop/cop/lint/useless_access_modifier.rb, spec/rubocop/cop/lint/symbol_conversion_spec.rb
Issue #12373: This PR fixes a false negative for `Lint/SymbolConversion` when using string interpolation
* [ x Feature branch is up-to-date with `master` (if not - rebase it).
=> [Fix #12373] Fix a false negative for Lint/SymbolConversion

changelog/change_support_redundant_options_for_style_arguments_forwarding.md, config/default.yml, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
Fixes #12296.
This PR supports `RedundantRestArgumentNames`, `RedundantKeywordRestArgumentNames`, and `RedundantBlockArgumentNames` options for `Style/ArgumentsForwarding`.
Meaningless names that are commonly used can be anonymized by default as part of the new `Redundant*Names` defaults. e.g., `*args`, `**options`, `&block`, and some argument names.
Names not on this list are likely to be meaningful and are allowed by default.
This approach is designed to only detect generally meaningless names without the need for users to edit the configuration for each meaningful name, with the expectation that the default settings will work well for most cases.
=> [Fix #12296] Support `Redundant*Names` options for `Style/ArgumentsForwarding`

changelog/change_make_hash_each_methods_aware_of_unused_block_value.md, lib/rubocop/cop/style/bisected_attr_accessor.rb, lib/rubocop/cop/style/hash_each_methods.rb, spec/rubocop/cop/style/hash_each_methods_spec.rb
Fixes #12370.
This PR makes `Style/HashEachMethods` aware of unused block value. And this PR suppresses the following new offense in this repository:
```console
$ bundle exec rubocop --only Style/HashEachMethods -A
(snip)
Offenses:
lib/rubocop/cop/style/bisected_attr_accessor.rb:36:11: C: [Corrected] Style/HashEachMethods:
Use each_value instead of each, and remove the unused _visibility block argument.
find_macros(class_node.body).each do |_visibility, macros| ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1519 files inspected, 1 offense detected, 1 offense corrected
```
=> [Fix #12370] Make `Style/HashEachMethods` aware of unused block value

changelog/fix_false_negatives_for_style_redundant_line_continuation.md, lib/rubocop/cop/style/redundant_line_continuation.rb, spec/rubocop/cop/style/redundant_line_continuation_spec.rb
Fixes #12402.
This PR fixes false negatives for `Style/RedundantLineContinuation` when redundant line continuations for a block are used, especially without parentheses around first argument.
=> [Fix #12402] Fix false negatives for `Style/RedundantLineContinuation`

changelog/fix_a_false_positive_for_layout_rescue_ensure_alignment.md, lib/rubocop/cop/layout/rescue_ensure_alignment.rb, spec/rubocop/cop/layout/rescue_ensure_alignment_spec.rb
Fixes #12404.
This PR fixes a false positive for `Layout/RescueEnsureAlignment` when aligned `rescue` in `do`-`end` numbered block in a method.
=> [Fix #12404] Fix a false positive for `Layout/RescueEnsureAlignment`

changelog/fix_incorrect_autocorrect_for_layout_single_line_block_chain_with_style_map_to_hash.md, lib/rubocop/cop/layout/single_line_block_chain.rb, lib/rubocop/cop/style/map_to_hash.rb, spec/rubocop/cli/autocorrect_spec.rb
This PR fixes an incorrect autocorrect for `Style/MapToHash` with `Layout/SingleLineBlockChain`, which makes the following syntax error occur:
```console
obj.map { |i| foo(i) }.to_h
.bar
$ bundle exec rubocop -A example.rb --only Style/MapToHash,Layout/SingleLineBlockChain
F
Offenses:
example.rb:1:5: C: [Corrected] Style/MapToHash: Pass a block to to_h instead of calling map.to_h.
obj.map { |i| foo(i) }.to_h
^^^
example.rb:1:23: C: [Corrected] Layout/SingleLineBlockChain: Put method call on a separate line if chained to a single line block.
obj.map { |i| foo(i) }.to_h
^^^^^
example.rb:3:4: F: Lint/Syntax: unexpected token tDOT
(Using Ruby 3.3 parser; configure using TargetRubyVersion parameter, under AllCops)
.bar
^
1 file inspected, 3 offenses detected, …
```
=> Fix an incorrect autocorrect for `Style/MapToHash` with `Layout/SingleLineBlockChain`

changelog/fix_incorrect_autocorrect_for_lint_safe_navigation_chain.md, lib/rubocop/cop/lint/safe_navigation_chain.rb, spec/rubocop/cop/lint/safe_navigation_chain_spec.rb
Fixes #12409.
This PR fixes an incorrect autocorrect for `Lint/SafeNavigationChain` when ordinary method chain exists after safe navigation leading dot method call.
=> [Fix #12409] Fix an incorrect autocorrect for `Lint/SafeNavigationChain`

changelog/fix_make_style_map_to_hash_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/map_to_hash.rb, spec/rubocop/cop/style/map_to_hash_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/12407#issuecomment-1825353313.
This PR makes `Style/MapToHash` aware of safe navigation operator.
=> Make `Style/MapToHash` aware of safe navigation operator

changelog/fix_make_style_inverse_methods_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/inverse_methods.rb, spec/rubocop/cop/style/inverse_methods_spec.rb
Fixes #12413.
This PR makes `Style/InverseMethods` aware of safe navigation operator.
=> [Fix #12413] Make `Style/InverseMethods` aware of safe navigation operator

changelog/change_lint_redundant_safe_navigation_to_handle_conversions_with_defaults.md, lib/rubocop/cop/lint/redundant_safe_navigation.rb, spec/rubocop/cop/lint/redundant_safe_navigation_spec.rb
Fixes #12412.
With these changes I found a few offenses in the gitlab's codebase.
=> Enhance `Lint/RedundantSafeNavigation` to handle conversion methods with defaults

changelog/change_lint_self_assignment_to_check_attribute_assignment_and_key_assignment.md, lib/rubocop/cop/lint/self_assignment.rb, spec/rubocop/cop/lint/self_assignment_spec.rb
This is an implementation of #12410 for `Lint/SelfAssignment`.
```ruby
foo.bar = foo.bar
foo["bar"] = foo["bar"]
```
=> Enhance `Lint/SelfAssignment` to check attribute assignment and key assignment

changelog/fix_a_false_positive_for_float_comparision_with_zero_nonzero.md, lib/rubocop/cop/lint/float_comparison.rb, spec/rubocop/cop/lint/float_comparison_spec.rb
Allow comparing against 0. See https://github.com/rubocop/rubocop/pull/12387#issuecomment-1818508562
=> [Fix #12146] Fix a false positive for `Lint/FloatComparison`

changelog/change_make_style_self_assignment_aware_of_some_operators.md, lib/rubocop/cop/style/self_assignment.rb, spec/rubocop/cop/style/self_assignment_spec.rb
Follow up https://github.com/rubocop/rubocop/issues/12410#issuecomment-1825941817.
This PR makes `Style/SelfAssignment` aware of `%`, `^`, `<<`, and `>>` operators.
=> Make `Style/SelfAssignment` aware of some operators

lib/rubocop/config_obsoletion.rb
Did a simple profiling of rspec tests. 
Got
```
34229  (17.1%)       20146  (10.1%)     Psych::Parser#_native_parse <==========
13387   (6.7%)        7628   (3.8%)     RuboCop::Cop::Registry#cops_for_department
6845   (3.4%)        6845   (3.4%)     (marking)
6372   (3.2%)        6372   (3.2%)     (sweeping)
5304   (2.7%)        5304   (2.7%)     Kernel#`
52086  (26.1%)        5027   (2.5%)     Class#new
4999   (2.5%)        4999   (2.5%)     String#match?
8569   (4.3%)        4262   (2.1%)     RuboCop::YAMLDuplicationChecker.traverse
6471   (3.2%)        4032   (2.0%)     Parser::Lexer#advance
3533   (1.8%)        3489   (1.7%)     IO.read
3071   (1.5%)        3071   (1.5%)     File.expand_path
```
Before, tests run is around `5m15s`, after - …
=> Optimize rspec tests

changelog/fix_make_style_hash_each_methods_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/hash_each_methods.rb, spec/rubocop/cop/style/hash_each_methods_spec.rb
Fixes #12424.
This PR makes `Style/HashEachMethods` aware of safe navigation operator.
=> [Fix #12424] Make `Style/HashEachMethods` aware of safe navigation operator

changelog/fix_false_positive_for_lint_literal_assignment_in_condition.md, lib/rubocop/cop/lint/literal_assignment_in_condition.rb, spec/rubocop/cop/lint/literal_assignment_in_condition_spec.rb
This PR fixes the following false positive for `Lint/LiteralAssignmentInCondition` when using parallel assignment with splat operator:
```ruby
return if do_something do |z|
x, y = *z
end
```
```console
$ bundle exec rubocop example.rb --only Lint/LiteralAssignmentInCondition
W
Offenses:
example.rb:2:8: W: Lint/LiteralAssignmentInCondition: Don't use literal assignment = *z
in conditional, should be == or non-literal operand.
x, y = *z
^^^^
```
This is a false positive because `ruby -w` doesn't warn.
=> Fix false positive for `Lint/LiteralAssignmentInCondition`

docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/array_first_last.rb
Small correction of the documentation for `Style/ArrayFirstLast`, where a word is missing.
=> Correction: Style/ArrayFirstLast documentation typo

changelog/fix_false_positives_for_style_hash_each_methods.md, lib/rubocop/cop/style/hash_each_methods.rb, spec/rubocop/cop/style/hash_each_methods_spec.rb
Fixes #12441.
This PR fixes false positives for `Style/HashEachMethods` when using destructed block arguments.
=> [Fix #12441] Fix false positives for `Style/HashEachMethods`

lib/rubocop/cop/layout/heredoc_indentation.rb
This PR fixes the broken inline code in the document for https://docs.rubocop.org/rubocop/cops_layout.html#layoutheredocindentation.
=> Fix inline code for `Layout/HeredocIndentation` document

changelog/fix_make_style_hash_except_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/hash_except.rb, spec/rubocop/cop/style/hash_except_spec.rb
Fixes #12446.
This PR makes `Style/HashExcept` aware of safe navigation operator.
=> [Fix #12446] Make `Style/HashExcept` aware of safe navigation operator

changelog/fix_make_lint_unmodified_reduce_accumulator_aware_of_safe_navigation_operator.md, lib/rubocop/cop/lint/unmodified_reduce_accumulator.rb, spec/rubocop/cop/lint/unmodified_reduce_accumulator_spec.rb
Fixes #12493.
This PR makes `Lint/UnmodifiedReduceAccumulator` aware of safe navigation operator.
=> [Fix #12493] Make `Lint/UnmodifiedReduceAccumulator` aware of safe navigation operator

changelog/fix_make_lint_redundant_with_index_aware_of_safe_navigation_operator.md, lib/rubocop/cop/lint/redundant_with_index.rb, spec/rubocop/cop/lint/redundant_with_index_spec.rb
Fixes #12491.
This PR makes `Lint/RedundantWithIndex` aware of safe navigation operator.
=> [Fix #12491] Make `Lint/RedundantWithIndex` aware of safe navigation operator

changelog/fix_make_lint_number_conversion_aware_of_safe_navigation_operator.md, lib/rubocop/cop/lint/number_conversion.rb, spec/rubocop/cop/lint/number_conversion_spec.rb
Fixes #12490.
This PR makes `Lint/NumberConversion` aware of safe navigation operator.
=> [Fix #12490] Make `Lint/NumberConversion` aware of safe navigation operator

changelog/fix_make_style_strip_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/strip.rb, spec/rubocop/cop/style/strip_spec.rb
Fixes #12468.
This PR makes `Style/Strip` aware of safe navigation operator.
=> [Fix #12468] Make `Style/Strip` aware of safe navigation operator

changelog/fix_make_style_single_argument_dig_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/single_argument_dig.rb, spec/rubocop/cop/style/single_argument_dig_spec.rb
Fixes #12460.
This PR makes `Style/SingleArgumentDig` aware of safe navigation operator.
=> [Fix #12460] Make `Style/SingleArgumentDig` aware of safe navigation operator

changelog/fix_make_style_sample_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/sample.rb, spec/rubocop/cop/style/sample_spec.rb
Fixes #12457.
This PR makes `Style/Sample` aware of safe navigation operator.
=> [Fix #12457] Make `Style/Sample` aware of safe navigation operator

changelog/fix_make_style_redundant_sort_by_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/redundant_sort_by.rb, spec/rubocop/cop/style/redundant_sort_by_spec.rb
Fixes #12456.
This PR makes `Style/RedundantSortBy` aware of safe navigation operator.
=> [Fix #12456] Make `Style/RedundantSortBy` aware of safe navigation operator

changelog/fix_make_style_redundant_fetch_block_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/redundant_fetch_block.rb, spec/rubocop/cop/style/redundant_fetch_block_spec.rb
Fixes #12454.
This PR makes `Style/RedundantFetchBlock` aware of safe navigation operator.
=> [Fix #12454] Make `Style/RedundantFetchBlock` aware of safe navigation operator

changelog/fix_make_style_unpack_first_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/unpack_first.rb, spec/rubocop/cop/style/unpack_first_spec.rb
Fixes #12469.
This PR makes `Style/UnpackFirst` aware of safe navigation operator and tweaks offense message.
=> [Fix #12469] Make `Style/UnpackFirst` aware of safe navigation operator

changelog/fix_make_style_concat_array_literals_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/concat_array_literals.rb, spec/rubocop/cop/style/concat_array_literals_spec.rb
Fixes #12474.
This PR makes `Style/ConcatArrayLiterals` aware of safe navigation operator.
=> [Fix #12474] Make `Style/ConcatArrayLiterals` aware of safe navigation operator

changelog/fix_make_style_each_with_object_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/each_with_object.rb, spec/rubocop/cop/style/each_with_object_spec.rb
Fixes #12479.
This PR makes `Style/EachWithObject` aware of safe navigation operator.
=> [Fix #12479] Make `Style/EachWithObject` aware of safe navigation operator

changelog/fix_make_style_next_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/next.rb, spec/rubocop/cop/style/next_spec.rb
Fixes #12484.
This PR makes `Style/Next` aware of safe navigation operator.
=> [Fix #12484] Make `Style/Next` aware of safe navigation operator

changelog/fix_make_style_redundant_argument_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/redundant_argument.rb, spec/rubocop/cop/style/redundant_argument_spec.rb
Fixes #12486.
This PR makes `Style/RedundantArgument` aware of safe navigation operator.
=> [Fix #12486] Make `Style/RedundantArgument` aware of safe navigation operator

changelog/fix_make_style_redundant_line_break_aware_of_safe_navigation_operator.md, lib/rubocop/cop/layout/redundant_line_break.rb, lib/rubocop/cop/naming/constant_name.rb, spec/rubocop/cop/layout/redundant_line_break_spec.rb
Fixes #12495.
This PR makes `Layout/RedundantLineBreak` aware of safe navigation operator.
=> [Fix #12495] Make `Layout/RedundantLineBreak` aware of safe navigation operator

changelog/fix_make_style_single_line_block_chain_aware_of_safe_navigation_operator.md, lib/rubocop/cop/layout/single_line_block_chain.rb, spec/rubocop/cop/layout/single_line_block_chain_spec.rb
Fixes #12494.
This PR makes `Layout/SingleLineBlockChain` aware of safe navigation operator.
=> [Fix #12494] Make `Layout/SingleLineBlockChain` aware of safe navigation operator

changelog/fix_make_lint_hash_compare_by_identity_aware_of_safe_navigation_operator.md, lib/rubocop/cop/lint/hash_compare_by_identity.rb, spec/rubocop/cop/lint/hash_compare_by_identity_spec.rb
Fixes #12488.
This PR makes `Lint/HashCompareByIdentity` aware of safe navigation operator.
=> [Fix #12488] Make `Lint/HashCompareByIdentity` aware of safe navigation operator

changelog/fix_a_false_positive_for_lint_self_assignment.md, lib/rubocop/cop/lint/self_assignment.rb, spec/rubocop/cop/lint/self_assignment_spec.rb
Fixes #12435.
This PR fixes a false positive for `Lint/SelfAssignment` when using attribute assignment with method call with arguments.
=> [Fix #12435] Fix a false positive for `Lint/SelfAssignment`

changelog/fix_false_positives_for_style_redundant_parentheses.md, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
Fixes #12436.
This PR fixes false positives for `Style/RedundantParentheses` when a part of range is a parenthesized condition.
=> [Fix #12436] Fix false positives for `Style/RedundantParentheses`

changelog/fix_a_false_positive_for_lint_literal_assignment_in_condition.md, lib/rubocop/cop/lint/literal_assignment_in_condition.rb, spec/rubocop/cop/lint/literal_assignment_in_condition_spec.rb
Fixes #12434.
This PR fixes a false positive for `Lint/LiteralAssignmentInCondition` when using interpolated string or xstring literals.
=> [Fix #12434] Fix a false positive for `Lint/LiteralAssignmentInCondition`

changelog/fix_make_style_select_by_regexp_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/select_by_regexp.rb, spec/rubocop/cop/style/select_by_regexp_spec.rb
Fixes #12458.
This PR makes `Style/SelectByRegexp` cops aware of safe navigation operator.
=> [Fix #12458] Make `Style/SelectByRegexp` cops aware of safe navigation operator

changelog/fix_a_false_positive_for_style_hash_each_methods.md, lib/rubocop/cop/style/hash_each_methods.rb, spec/rubocop/cop/style/hash_each_methods_spec.rb
Fixes #12444.
This PR fixes false positive for `Style/HashEachMethods` when receiver literal is not a hash literal.
=> [Fix #12444] Fix false positive for `Style/HashEachMethods`

changelog/change_make_style_method_call_without_args_parentheses_respect_ruby33_warn.md, lib/rubocop/cop/style/method_call_without_args_parentheses.rb, spec/rubocop/cop/style/method_call_without_args_parentheses_spec.rb
This PR makes `Style/MethodCallWithoutArgsParentheses` allow the parenthesized `it` method in a block.
It respects following Ruby 3.3's warning:
```console
$ ruby -e '0.times { begin; it; end }'
-e:1: warning: `it` calls without arguments will refer to the first block param in Ruby 3.4; use it() or self.it
```
Related PR ... https://github.com/rubocop/rubocop/pull/12518
=> Make `Style/MethodCallWithoutArgsParentheses` allow parenthesized `it`

changelog/fix_a_false_positive_for_style_method_call_with_args_parentheses.md, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
Fixes #12524.
This PR fixes a false positive for `Style/MethodCallWithArgsParentheses` when `EnforcedStyle: omit_parentheses` and parens in `when` clause is used to pass an argument.
=> [Fix #12524] Fix a false positive for `Style/MethodCallWithArgsParentheses`

changelog/fix_false_positives_for_style_parentheses_around_condition.md, lib/rubocop/cop/style/parentheses_around_condition.rb, spec/rubocop/cop/style/parentheses_around_condition_spec.rb
Fixes #12529.
This PR fixes false positives for `Style/ParenthesesAroundCondition` when using a method call with `do`...`end` block as a condition in a loop.
=> [Fix #12529] Fix false positives for `Style/ParenthesesAroundCondition`

docs/modules/ROOT/pages/usage/lsp.adoc
The pattern for `Buf*` commands in neovim looks to be a file names pattern, not file types. When set to `ruby`, automatic formatting doesn't work. It starts working only when I set it to `*.rb`.
Reference:
https://neovim.io/doc/user/api.html#:~:text=%22BufWinEnter%22%7D%2C%20%7B-,pattern%20%3D%20%7B%22*.c%22%2C%20%22*.h%22%7D,-%2C%0A%20%20callback%20%3D%20function
=> Fix BufPreWrite pattern in nvim-lspconfig rubocop formatting example

changelog/fix_false_positives_for_lint_literal_assignment_in_condition.md, lib/rubocop/cop/lint/literal_assignment_in_condition.rb, spec/rubocop/cop/lint/literal_assignment_in_condition_spec.rb
This PR fixes the following false positive for `Lint/LiteralAssignmentInCondition` when a collection lireal contains non-literal elements:
```console
$ echo 'x = 1; if test = [42, x]; end' | be rubocop --stdin test.rb --only Lint/LiteralAssignmentInCondition
W
Offenses:
test.rb:1:16: W: Lint/LiteralAssignmentInCondition: Don't use literal assignment = [42, x] in conditional,
should be == or non-literal operand.
x = 1; if test = [42, x]; end
^^^^^^^^^
```
In cases where non-literal elements are included in the collection, no warning will be displayed.
```console
$ ruby -we 'x = 1; if test = [42, x]; end'
```
=> Fix false positives for `Lint/LiteralAssignmentInCondition`

changelog/fix_false_positives_for_style_hash_each_methods.md, lib/rubocop/cop/style/hash_each_methods.rb, spec/rubocop/cop/style/hash_each_methods_spec.rb
Fixes #12540.
This PR fixes false positives for `Style/HashEachMethods` when rest block argument of `Enumerable#each` method is used.
=> [Fix #12540] Fix false positives for `Style/HashEachMethods`

changelog/fix_false_positives_for_redundant_parentheses.md, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
Fixes #12537.
This PR fixes false positives for `Style/RedundantParentheses` when `AllowInMultilineConditions: true` of `Style/ParenthesesAroundCondition`.
=> [Fix #12537] Fix false positives for `Style/RedundantParentheses`

changelog/fix_a_false_positive_for_style_redundant_line_continuation.md, lib/rubocop/cop/style/redundant_line_continuation.rb, spec/rubocop/cop/style/redundant_line_continuation_spec.rb
Fixes #12549.
This PR fixes a false positive for `Style/RedundantLineContinuation` when line continuations for multiline leading dot method chain with a blank line.
=> [Fix #12549] Fix a false positive for `Style/RedundantLineContinuation`

lib/rubocop/cop/style/each_for_simple_loop.rb, spec/rubocop/cop/style/each_for_simple_loop_spec.rb
Fixes #12478.
This PR makes `Style/EachForSimpleLoop` cops aware of safe navigation operator.
=> [Fix #12478] Make `Style/EachForSimpleLoop` cops aware of safe navigation operator

changelog/fix_fix_false_negative_in_style_arguments_forwarding.md, lib/rubocop/cop/registry.rb, lib/rubocop/cop/style/arguments_forwarding.rb, lib/rubocop/cop/style/parallel_assignment.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
The following code gets registered as a false negative by `Style/ArgumentsForwarding`
```ruby
def foo(*args, &block)
bar(*args, &block)
baz(&block)
end
```
Which results in the following invalid autocorrection (`&block` is now longer defined):
```ruby
def foo(...)
bar(...)
baz(&block)
end
```
This change fixes that case by considering block arguments when determining if forwarding is possible. 
This had two side effects:
1. The test for different argument names failed due to the block parameter now being considered when determining if there is an offense. To fix this, we now check that the rest and kwrest arguments have the same name.
2. This revealed a few offenses in rubocop code where only a block argument should have been replaced with forwarding.
Before submitting …
=>  Fix false negative in `Style/ArgumentsForwarding` when a block is forwarded but other args aren't

changelog/fix_an_incorrect_autocorrect_for_style_map_to_hash.md, lib/rubocop/cop/style/map_to_hash.rb, spec/rubocop/cop/style/map_to_hash_spec.rb
Fixes #12558.
This PR fixes an incorrect autocorrect for `Style/MapToHash` when using `map.to_h` without receiver.
=> [Fix #12558] Fix an incorrect autocorrect for `Style/MapToHash`

changelog/fix_false_positives_for_style_redundant_parentheses.md, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
Fixes #12556.
This PR fixes false positives for `Style/RedundantParentheses` when parentheses are used around a semantic operator in expressions within assignments.
=> [Fix #12556] Fix false positives for `Style/RedundantParentheses`

lib/rubocop/cop/style/map_to_hash.rb, spec/rubocop/cop/style/map_to_hash_spec.rb
Follow https://github.com/rubocop/rubocop/pull/12560#discussion_r1432423841
This PR fixes an incorrect autocorrect for `Style/MapToHash` using safe navigation operator.
NOTE: This is a partial unreleased regression of #12560. So, it has not been added to the changelog.
=> Fix an incorrect autocorrect for `Style/MapToHash`

changelog/change_allow_autocorrect_with.md, lib/rubocop/options.rb, spec/rubocop/options_spec.rb
The `--display-only-fail-level-offenses` option uses
`considered_failure?` to determine what to print. The same method is
used to determine the exit code of `rubocop`, so the two options should
be entirely safe to use together.
This change is useful when using rubocop as part of a pre-commit hook.
When the hook fails becuase rubocop exited with a non-zero status, we
can use `--display-only-fail-level-offenses` to avoid having the output
cluttered up with non-blocking offenses.
=> Allow autocorrect with display-only-fail-level-offenses

lib/rubocop/cop/style/invertible_unless_condition.rb, spec/rubocop/cop/style/invertible_unless_condition_spec.rb
The existing message is ambiguous about how to invert the condition, leading many to assume the cop is suggesting replacing code like
```ruby
unless number.odd?
^^^^^^^^^^^^^^^^^^ Favor `if` with inverted condition over `unless`.
```
with
```ruby
if !number.odd?
```
which would conflict with `Style/NegatedIf`.
This updates the message to clearly describe the change being recommended:
```ruby
unless number.odd?
^^^^^^^^^^^^^^^^^^ Prefer `if number.even?` over `unless number.odd?`.
```
=> Improve invertible unless message

changelog/change_make_style_redundant_each_aware_of_safe_navigation_operator.md, lib/rubocop/cop/style/redundant_each.rb, spec/rubocop/cop/style/redundant_each_spec.rb
Fixes #12453.
This PR makes `Style/RedundantEach` aware of safe navigation operator.
And offense range has been tweaked to clarify whether the target for removal, associated with the detection of safe navigation, is `.` or `&.`.
=> [Fix #12453] Make `Style/RedundantEach` aware of safe navigation operator

changelog/fix_an_error_for_layout_first_array_element_indentation.md, lib/rubocop/cop/layout/first_array_element_indentation.rb, spec/rubocop/cli/autocorrect_spec.rb
Fixes #12548.
This PR fixes an infinite loop error for `Layout/FirstArgumentIndentation` when specifying `EnforcedStyle: with_fixed_indentation` of `Layout/ArrayAlignment`.
=> [Fix #12548] Fix an infinite loop error for `Layout/FirstArgumentIndentation`

lib/rubocop/cop/style/symbol_proc.rb
This documents the false positive for `Style/SymbolProc` when used with a `protected` method. `public` and `private` method behaviour matches, but `protected` methods which work in the normal block style break when using `Symbol#to_proc`.
The motivation for this is that it's not something that comes up very often (`protected` is not as common as `public` or `private`, and even less so used in iteration/blocks), so reviewers will often need to ask why a `rubocop:disable Style/SymbolProc` comment is being added. Documenting this makes it easier to discover the reason.
* ~Added tests.~
* ~Added an entry (file) to the [changelog …
=> Document `Style/SymbolProc` protected method incompatibility

changelog/fix_an_error_for_style_identical_conditional_branches.md, lib/rubocop/cop/style/identical_conditional_branches.rb, spec/rubocop/cop/style/identical_conditional_branches_spec.rb
Fixes #12569.
This PR fixes an error for `Style/IdenticalConditionalBranches` when using `if`...`else` with identical leading lines that assign to `self.foo`.
NOTE: It would be better to update `RuboCop::AST::OpAsgnNode` to handle `self.foo ||= value` to solve the issue in future.
=> [Fix #12569] Fix an error for `Style/IdenticalConditionalBranches`

changelog/change_follow_ruby33_warning_for_security_open.md, lib/rubocop/cop/security/open.rb, spec/rubocop/cop/security/open_spec.rb
This PR follows the following Ruby 3.3 warning for `Security/Open` when `open` with a literal string starting with a pipe:
```console
$ ruby -we "open('| ls')"
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-darwin22]
-e:1: warning: Calling Kernel#open with a leading '|' is deprecated
and will be removed in Ruby 4.0; use IO.popen instead
```
=> Follow a Ruby 3.3 warning for `Security/Open `

changelog/fix_an_error_for_layout_end_alignment.md, lib/rubocop/cop/layout/end_alignment.rb, spec/rubocop/cli/autocorrect_spec.rb
Fixes https://github.com/standardrb/standard/issues/598.
This PR fixes an infinite loop error for `Layout/EndAlignment` when misaligned in singleton class assignments with `EnforcedStyleAlignWith: variable`.
=> Fix an infinite loop error for `Layout/EndAlignment`

changelog/fix_an_error_for_lint_shadowed_argument.md, lib/rubocop/cop/lint/shadowed_argument.rb, spec/rubocop/cop/lint/shadowed_argument_spec.rb
Fixes #12236.
This PR fixes an error for `Lint/ShadowedArgument` when self assigning to a block argument in `for`.
=> [Fix #12236] Fix an error for `Lint/ShadowedArgument`

changelog/fix_bug_for_unrecognized_style.md, lib/rubocop/cop/mixin/configurable_formatting.rb, spec/rubocop/cli/auto_gen_config_spec.rb
When there are supported styles in the cop configuration, auto-generated configuration should get an `EnforcedStyle` entry if the inspected code base conforms, not to the currently select style, but to one of the other styles, and follows that style in all places.
If the code base contains code the conforms to different styles, we should get an `Exclude` entry instead. The same goes for code that doesn't conform to any of the cop's supported styles. This last case is where we had a bug. We didn't mark the style as unrecognized, which is why we got an `EnforcedStyle` instead of an `Exclude`.
=> [Fix #12574] Handle unrecognized style better in --auto-gen-config

.circleci/config.yml
Ruby 3.3.0 has been released and this Ruby version is available on `cimg/ruby:3.3` image.
- https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/
- https://circleci.com/developer/en/images/image/cimg/ruby
=> CircleCI against Ruby 3.3

rubocop.gemspec
This PR tweaks changelog URL on RubyGems.org.
https://rubygems.org/gems/rubocop
The CHANGELOG.md is extensive, so the link of the changelog on RubyGems.org will be updated to point to the GitHub release page, focusing on the release version. e.g., https://github.com/rubocop/rubocop/releases/tag/v1.59.0
The idea is the same as in https://github.com/rubocop/rubocop/pull/8775.
=> Tweak the changelog URL on RubyGems.org

LICENSE.txt, README.md, docs/modules/ROOT/pages/about/license.adoc
This PR updates the license year to 2024.
=> Bump license years to 2024

spec/rubocop/cop/naming/heredoc_delimiter_case_spec.rb, spec/rubocop/cop/naming/heredoc_delimiter_naming_spec.rb
Pending two specs until the following error in Parser 3.3.0.1 is resolved. https://github.com/whitequark/parser/pull/987
=> Workaround for an error when parsing heredoc with non-word delimiters

changelog/fix_auto_gen_config_exclude_with_max_set.md, lib/rubocop/formatter/disabled_config_formatter.rb, spec/rubocop/cli/auto_gen_config_spec.rb, spec/rubocop/formatter/disabled_config_formatter_spec.rb
For a cop that has a `Max` setting, if that setting is overridden in user configuration, creating a `Max` property in `.rubocop_todo.yml` will be useless. User configuration will take precedence and after running `rubocop --auto-gen-config` there can still be offenses that get reported in the next `rubocop` run.
With this modification, we avoid the problem by generating `Exclude` instead of `Max` in those situations.
=> [Fix #12179] Generate Exclude when Max is overridden

changelog/fix_a_false_positive_for_style_multiline_ternary_operator.md, lib/rubocop/cop/style/multiline_ternary_operator.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/style/multiline_ternary_operator_spec.rb
Fixes #12603.
This PR fixes an infinite loop error for `Style/MultilineTernaryOperator` when using a method call as a ternary operator condition with a line break between receiver and method.
=> [Fix #12603] Fix an infinite loop error for `Style/MultilineTernaryOperator`

changelog/change_require_parser_3_3_0_0.md, docs/modules/ROOT/pages/compatibility.adoc, rubocop.gemspec
Ruby 3.3 and Parser 3.3.0.2 have been released.
- https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released
- https://rubygems.org/gems/parser/versions/3.3.0.2
This PR requires Parser 3.3.0.2 or higher and removes "experimental" label from support matrix.
The Parser gem specifies version 3.3.0.2+, not 3.3.0.0, as it applies the following patch:
https://github.com/whitequark/parser/pull/987
=> Require Parser 3.3.0.2 or higher

changelog/fix_false_positive_for_style_redundant_parentheses.md, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
This PR fixes a false positive for `Style/RedundantParentheses` when regexp literal attempts to match against a parenthesized condition.
The presence or absence of parentheses here changes the meaning of the syntax, so the parentheses are not redundant:
```console
$ ruby-parse -e '/regexp/ =~ (foo || bar)'
(match-with-lvasgn
(regexp
(str "regexp")
(regopt))
(begin
(or
(send nil :foo)
(send nil :bar))))
$ ruby-parse -e '/regexp/ =~ foo || bar'
(or
(match-with-lvasgn
(regexp
(str "regexp")
(regopt))
(send nil :foo))
(send nil :bar))
```
=> Fix a false positive for `Style/RedundantParentheses`

changelog/fix_an_error_for_style_method_call_with_args_parentheses.md, lib/rubocop/cop/style/method_call_with_args_parentheses.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
Fixes #12437.
This PR fixes an infinite loop error for `EnforcedStyle: omit_parentheses` of `Style/MethodCallWithArgsParentheses` with `Style/SuperWithArgsParentheses`.
In #12390, `super` has become a separate `Style/SuperWithArgsParentheses` cop. This PR prevents the infinite loop error by ensuring that `Style/MethodCallWithArgsParentheses` no longer detects `super`, following the separation of `super` into `Style/SuperWithArgsParentheses` cop.
This approach aligns with the perspective that methods and `super` have different considerations regarding parentheses usage, as mentioned in #12390.
=> [Fix #12437] Fix an infinite loop error for `Style/MethodCallWithArgsParentheses`

changelog/change_make_style_slicing_with_range_aware_of_beginless_range.md, config/default.yml, lib/rubocop/cop/style/slicing_with_range.rb, spec/rubocop/cop/style/slicing_with_range_spec.rb
Fixes #12233.
This PR makes `Style/SlicingWithRange` aware of redundant and beginless range.
Ruby 2.7 introduced beginless ranges. But, unlike the somewhat obscure `-1` in `ary[1..-1]`, the `0` in `ary[0..42]` is clear as a starting point. In fact, changing it to `ary[..42]` could potentially make it less readable. Therefore, `ary[0..42]` should respect the original programmer's intent. On the other hand, `ary[nil..42]` could be replaced with `ary[..42]`. Similarly, `ary[1..nil]` could be replaced with `ary[1..]`.
Moreover, `[0..-1]` in `ary[0..-1]` is redundant and simply synonymous with `ary`. This PR has also made adjustments to detect this case. While this is a byproduct of supporting beginless and endless ranges, I think including this change in `Style/SlicingWithRange` cop may be …
=> [Fix #12233] Make `Style/SlicingWithRange` aware of beginless range

lib/rubocop/cop/base.rb, lib/rubocop/cop/lint/syntax.rb, lib/rubocop/rspec/shared_contexts.rb, lib/rubocop/rspec/support.rb, spec/rubocop/cop/lint/syntax_spec.rb
Fixes #11033.
This PR changes warning message for `Lint/Syntax` between LSP and the command line.
The redundancy of the offense message probably depends on the context. The context in which the issue has been reported is LSP.
In LSP, source code being typed may still be evaluated as invalid syntax. On the other hand, when executed via the `rubocop` command line, the input is usually complete and evaluated as valid syntax in most cases. This means that suggesting a possible misconfiguration in .rubocop.yml would be sufficient only when using the command line.
So, this is because the difference in evaluation timing of source code. Therefore, it is implemented as a distinction based on the execution context, rather than as a configuration option.
To resolve this, it seems reasonable to …
=> [Fix #11033] Change warning message for `Lint/Syntax` when using LSP

changelog/fix_false_positives_for_style_arguments_forwarding.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/12571#issuecomment-1870575888.
This PR fixes false positives for `Style/ArgumentsForwarding` when rest arguments forwarding to a method in block.
=> Fix false positives for `Style/ArgumentsForwarding`

changelog/fix_false_positives_for_naming_block_forwarding.md, lib/rubocop/cop/naming/block_forwarding.rb, spec/rubocop/cop/naming/block_forwarding_spec.rb
Fixes #12571.
This PR fixes false positives for `Naming/BlockForwarding` when using explicit block forwarding in block method.
=> [Fix #12571] Fix false posives for `Naming/BlockForwarding`

changelog/fix_accept_parentheses_in_argument_calls_with_blocks.md, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
In `Style/MethodCallWithArgsParentheses` with `omit_parentheses` enforced style we need to allow parentheses in method calls with blocks, when their value is used as an arguments in method dispatch calls. We have syntax errors when we enforce their omissions:
```ruby
foo(
Class.new(Base) do
end
)
```
Should be allowed as the example below is invalid Ruby:
```ruby
foo(
Class.new Base do
end
)
```
=> Accept parentheses in argument calls with blocks

changelog/fix_false_positive_for_lint_mixed_regexp_capture_types.md, lib/rubocop/ext/regexp_node.rb, spec/rubocop/cop/lint/mixed_regexp_capture_types_spec.rb
Fix false positive for `Lint/MixedRegexpCaptureTypes` when > is included in the look-ahead matcher rubocop recognizes the matcher as a named matcher.
=> [Fix #12542] Fix false positive for `Lint/MixedRegexpCaptureTypes`

changelog/fix_make_style_each_for_simple_loop_allows_block_with_no_params.md, lib/rubocop/cop/style/each_for_simple_loop.rb, spec/rubocop/cop/style/each_for_simple_loop_spec.rb
Fixes #12601.
This PR makes `Style/EachForSimpleLoop` accept block with no parameters.
This is the behavior according to the documentation:
> This check only applies if the block takes no parameters.
https://docs.rubocop.org/rubocop/1.59/cops_style.html#styleeachforsimpleloop
=> [Fix #12601] Make `Style/EachForSimpleLoop` accept block with no parameters

changelog/change_reject_additional_enforced_style_options.md, lib/rubocop/formatter/disabled_config_formatter.rb, spec/rubocop/cli/auto_gen_config_spec.rb
It seems to me that when the `--no-auto-gen-enforced-style` is given, not only `EnforcedStyle` should be rejected, but also all 'expanded' `EnforcedStyle` options as well, like for example `EnforcedStyleForEmptyBraces`. In order to achieve this I used a Regex when checking which keys should be rejected.
=> Include expanded EnforcedStyle options when --no-auto-gen-enforced-style is given

changelog/fix_false_positives_for_style_redundant_parentheses.md, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
Fixes #12614.
This PR fixes false positiveis for `Style/RedundantParentheses` when parentheses in control flow keyword with multiline style argument.
=> [Fix #12614] Fix false positiveis for `Style/RedundantParentheses`

changelog/change_make_style_collection_compact_aware_of_grep_v_with_nil.md, lib/rubocop/cop/style/collection_compact.rb, spec/rubocop/cop/style/collection_compact_spec.rb
Resolves #12617.
This PR makes `Style/CollectionCompact` aware of `grep_v` with nil.
=> [Fix #12617] Make `Style/CollectionCompact` aware of `grep_v` with nil

changelog/fix_errno_erofs.md, lib/rubocop/server/cache.rb, spec/rubocop/server/cache_spec.rb
This PR addresses an issue encountered when running RuboCop in a Docker container configured with `read_only: true` in the `docker-compose` file.
Changes in this PR include:
- Added `Errno::EROFS` to the rescue clause in `lib/rubocop/server/cache.rb` to handle `Read-only file system` errors. This change allows the application to gracefully handle situations where the filesystem is read-only, such as in certain Docker configurations.
=> Add Errno::EROFS exception handling for read-only file systems

changelog/fix_a_false_positive_for_style_arguments_forwarding.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/12618#issuecomment-1896227199.
This PR fixes a false positive for `Style/ArgumentsForwarding` when naming a block argument `&`.
=> Fix a false positive for `Style/ArgumentsForwarding`

Gemfile
This PR fixes the following build error on windows mingw matrix:
```console
D:/a/rubocop/rubocop/vendor/bundle/ruby/3.4.0+0/gems/crack-0.4.5/lib/crack/xml.rb:9:
warning: bigdecimal was loaded from the standard library, but is not part of the default gems since Ruby 3.4.0.
Add bigdecimal to your Gemfile or gemspec.
An error occurred while loading spec_helper. - Did you mean?
rspec ./spec/spec_helper.rb
Failure/Error: require 'webmock/rspec'
LoadError:
cannot load such file -- bigdecimal
```
https://github.com/rubocop/rubocop/actions/runs/7567518866/job/20606843322?pr=12633
This occurred due to BigDecimal has been extracted as a bundled gem: ruby/ruby#9573
=> Fix a build error on windows mingw matrix

changelog/fix_a_false_positive_for_layout_redundant_line_break.md, lib/rubocop/cop/layout/redundant_line_break.rb, spec/rubocop/cop/layout/redundant_line_break_spec.rb
Fix #12627.
This PR fixes a false positive for `Layout/RedundantLineBreak` when using index access call chained on multiple lines with backslash.
=> [Fix #12627] Fix a false positive for `Layout/RedundantLineBreak`

changelog/fix_a_false_positive_for_style_hash_each_methods.md, lib/rubocop/cop/style/hash_each_methods.rb, spec/rubocop/cop/style/hash_each_methods_spec.rb
```rb
foo.each { |k, v| do_something }
foo.each_key { |k| do_something }
```
`Lint/UnusedBlockArgument` should instead say something about this:
```
test.rb:1:13: W: [Correctable] Lint/UnusedBlockArgument: Unused block argument - k. You can omit all the arguments if you don't care about them.
foo.each { |k, v| do_something }
^
test.rb:1:16: W: [Correctable] Lint/UnusedBlockArgument: Unused block argument - v. You can omit all the arguments if you don't care about them.
foo.each { |k, v| do_something }
```
=> Fix a false positive for `Style/HashEachMethods` when both arguments are unused

changelog/fix_an_error_for_style_hash_each_methods.md, lib/rubocop/cop/style/hash_each_methods.rb, spec/rubocop/cop/style/hash_each_methods_spec.rb
Depends on #12635.
`Lint/EmptyBlock` takes care of this case:
```
test.rb:1:1: W: Lint/EmptyBlock: Empty block detected.
foo.each { |k, v| }
```
I have based this on #12635 because without this the cop would produce the following offense for the added testcase:
```rb
foo.each { |k, v| }
foo.each_key { |k| }
```
=> Fix an error for `Style/HashEachMethods` when a block with both parameters has no body

changelog/fix_an_error_when_using_sever_mode.md, lib/rubocop/server/client_command/exec.rb, lib/rubocop/server/server_command/exec.rb
Fixes #12638.
There is a possibility of a race condition occurring with the status file when using server mode. The status file is updated to a new status by `Cache.write_status_file` (`Pathname#write`), so there is no need to clear it by deleting the file.
Due to the difficulty in reproducing this race conditions, test code for this have not been added.
=> [Fix #12638] Fix an `Errno::ENOENT` error when using server mode

changelog/fix_infinite_loop_error_for_style_argument_forwarding.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cli/autocorrect_spec.rb
Fixes #12632.
This PR fixes an infinite loop error when `EnforcedStyle: explicit` of `Naming/BlockForwarding` with `Style/ArgumentsForwarding`.
=> [Fix #12632] Fix an infinite loop error for `Style/ArgumentsForwarding`

docs/modules/ROOT/pages/compatibility.adoc
This PR proposes to update the Compatibility Policy.
There are major version incompatibilities between Ruby 2.7 and Ruby 3.0. And the latest stable version of Ruby on Rails, 7.1, still supports Ruby 2.7. So, dropping support for Ruby 2.7 from RuboCop might be premature for the market at this stage.
At least for the duration that Rails 7.1 is classified as being in the "Bug Fix" phase under the [Maintenance Policy for Ruby on Rails] (https://guides.rubyonrails.org/maintenance_policy.html), RuboCop will continue to support Ruby 2.7.
In reality, RuboCop is mostly used for code analysis with the same version of the Ruby runtime. I think that ensuring such users can smoothly upgrade their RuboCop version justifies maintaining support for older Ruby version 2.7 for an extended period. …
=> Update the Compatibility Policy

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Sorry if this is intentional, but I noticed that the issue templates don't have default tags and I thought it's convenient to have them.
=> Add default tags to issue templates

changelog/fix_false_positives_for_style_hash_each_methods_when_array_converter.md, lib/rubocop/cop/style/hash_each_methods.rb, spec/rubocop/cop/style/hash_each_methods_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/12534#issuecomment-1871676010.
This PR fixes false positives for `Style/HashEachMethods` when using array converter method.
Hash object converted to an Array cannot process `Hash#each_key` and `Hash#each_value`. Therefore, if methods that convert to an Array are used before `each`, they should be ignored.
=> Fix false positives for `Style/HashEachMethods`

changelog/change_mark_style_raise_args_as_unsafe.md, config/default.yml, lib/rubocop/cop/style/raise_args.rb
`.exception` and `.new` behave roughly the same way, but I don't think they are guaranteed to always be so.
What do you think?
=> Mark `Style/RaiseArgs` as unsafe

lib/rubocop/cop/base.rb, lib/rubocop/cop/lint/syntax.rb, lib/rubocop/lsp/server.rb, lib/rubocop/rspec/shared_contexts.rb, spec/rubocop/lsp/server_spec.rb
The original LSP mode determination relied on the `--lsp` command-line argument, making it hard to set the mode from 3rd party LSP(-like) tools. This PR refines the API to resolve this issue. Additionally, as a side effect, it improves the mocking part of spec.
However, the APIs are still experimental and not yet mature.
=> LSP mode configurable from external source

changelog/fix_numblock_regressions_in_omit_parentheses.md, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
My [last change](https://github.com/rubocop/rubocop/pull/12610) was trying to fix an edge case where RuboCop wanted us to remove parentheses in the following example, but removing the parens was resulting in a `SyntaxError`:
```ruby
AnyCable.middleware.use(
Class.new(AnyCable::Middleware) do
^^^^^^^^^^^^^^^^^^^^^^ Omit parentheses for method calls with arguments.
pass
end
)
```
As it often happens, though, I broke a few other cases where we now want to remove parens, while the removal can result in ambiguous code:
**Case 1**
```ruby
Foo::Bar.find(pending.things.map { _1['code'] })
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Omit parentheses for method calls with arguments.
```
While we can remove the parentheses in *Case 1*, the author has to be well aware of the difference between the do/end and …
=> Fix numblock regressions in `omit_parentheses` Style/MethodCallWithArgsParentheses`

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Reverts #12644.
It's been a few days since the introduction, but there are false reports of the "bug" label being applied to items that are not confirmed as bugs or are not bugs. The default "bug" label is confusing for unconfirmed feedback. Despite considering user likelihood to change labels, submissions are often made with the default.
For feature request, sometimes labels other than "enhancement", like "feature" or others, are more appropriate.
Labeling can suit mechanical operations (e.g., bot), but may not fit uncertain feedback needing review, as seen in this repository.
To avoid misleading labels on unresolved issues, the default labels will be removed from the issue template for maintenance reasons. …
=> Revert "Add default tags to issue templates"

changelog/change_source_order_for_target_ruby.md, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop/target_ruby.rb, spec/rubocop/target_ruby_spec.rb
Currently, if I have a gem that has both a `.ruby-version` file and a `required_ruby_version` in the gemspec, Rubocop would default to the ruby version in the `.ruby-version` file.
However, it would be more correct to take the ruby version in the gemspec as the `TargetRubyVersion` [should be the oldest version of Ruby which your project supports with](https://docs.rubocop.org/rubocop/configuration.html#setting-the-target-ruby-version). `required_ruby_version` would specify any minimum Ruby version. The `.ruby-version` and other sources would get the development version in the project and might not be the oldest supported version. 
Moved the GemspecFile source to be under the rubocop config.
[1]: …
=> Check gemspec `required_ruby_version` before `.ruby-version` and other sources

changelog/fix_error_for_layout_redundant_line_break.md, lib/rubocop/cop/layout/redundant_line_break.rb, spec/rubocop/cop/layout/redundant_line_break_spec.rb
This PR fixes the following error for `Layout/RedundantLineBreak` when using index access call chained on multiline hash literal:
```console
{
key: value
}[key]
$ bundle exec rubocop --only Layout/RedundantLineBreak -a -d
(snip)
An error occurred while Layout/RedundantLineBreak cop was inspecting /tmp/example.rb:1:0.
undefined method `method?' for an instance of RuboCop::AST::HashNode
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/layout/redundant_line_break.rb:92:in `index_access_call_chained?'
```
=> Fix an error for `Layout/RedundantLineBreak`

changelog/change_error_message_on_incorrect_namespace.md, lib/rubocop/cop/registry.rb, spec/rubocop/cli_spec.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/registry_spec.rb
Updates the error message when the namespace is incorrect to specify the exact action the developer must take to fix the error. 
The error message as it exists today does not immediately signal an action to fix it to developers unfamiliar with Rubocop terminology.
=> Make error message clearer when the namespace is incorrect

Gemfile
This is a follow up on https://github.com/rubocop/rubocop/pull/12153 . The mentioned PR was merged in to `crack` and released as v0.4.6
* Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* Added tests.
* Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.
=> Resolve Fixme in Gemfile, remove bigdecimal

changelog/fix_an_incorrect_autocorrect_for_lint_empty_conditional_body.md, lib/rubocop/cop/lint/empty_conditional_body.rb, spec/rubocop/cop/lint/empty_conditional_body_spec.rb
Fixes #12668.
This PR fixes an incorrect autocorrect for `Lint/EmptyConditionalBody` when missing `if` body with conditional `else` body.
=> [Fix #12668] Fix an incorrect autocorrect for `Lint/EmptyConditionalBody`

lib/rubocop/cop/style/hash_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
This PR fixes the following error `Style/HashSyntax` when using `Prism::Translation::Parser` as a parser:
```console
$ bundle exec ruby -rprism/translation/parser/rubocop $(bundle exec which rubocop) \
--only Style/HashSyntax -d lib/rubocop/cop/style/not.rb
(snip)
An error occurred while Style/HashSyntax cop was inspecting
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/not.rb:23:27.
undefined method `loc' for an instance of AST::Node
/Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/parser-3.3.0.5/lib/parser/builders/default.rb:1875:
in `join_exprs'
```
Other ways to resolve this might exist, but using `RuboCop::Cop::Base#parser` is not necessary.
Currently, no repro tests have been added as it is sufficient to verify that it is not broken with the Parser gem. …
=> Fix an error for `Style/HashSyntax` when using `Prism::Translation::Parser`

changelog/fix_false_negative_for_style_redundant_return.md, lib/rubocop/cop/style/redundant_return.rb, spec/rubocop/cop/style/redundant_return_spec.rb
This PR fixes false negatives for `Style/RedundantReturn` when using pattern matching.
=> Fix false negatives for `Style/RedundantReturn`

changelog/new_publish_lsp_enable_api.md, docs/modules/ROOT/pages/usage/lsp.adoc, lib/rubocop/cli/command/lsp.rb, lib/rubocop/cop/base.rb, lib/rubocop/cop/lint/syntax.rb, lib/rubocop/lsp.rb, lib/rubocop/lsp/logger.rb, lib/rubocop/lsp/routes.rb, lib/rubocop/lsp/runtime.rb, lib/rubocop/lsp/server.rb, lib/rubocop/lsp/severity.rb, lib/rubocop/rspec/shared_contexts.rb, lib/rubocop/rspec/support.rb, spec/rubocop/cop/lint/syntax_spec.rb, spec/rubocop/lsp/server_spec.rb, spec/rubocop/lsp/severity_spec.rb, spec/rubocop/lsp_spec.rb, spec/support/lsp_helper.rb
`RuboCop::Cop::Base.enable_lsp_mode` will be renamed to `RuboCop::LSP.enable`.
Before:
```ruby
RuboCop::Cop::Base.enable_lsp_mode
```
After:
```ruby
RuboCop::LSP.enable
```
This is because whether or not it is LSP should not be set per cop but should be a state controlled for the entire RuboCop process.
Since `RuboCop::Cop::Base.enable_lsp_mode` was an experimental private API, it will be renamed without a deprecation warning.
Along with this, the module name has been changed from `RuboCop::Lsp` to `RuboCop::LSP`. This change is made to align with Ruby's standard API, like `RubyVM::YJIT.enable`, making it `RuboCop::LSP.enable` instead. `RuboCop::Lsp.enable` does not look as pretty name.
With the renaming to `RuboCop::LSP.enable`, the usage of this API will be documented. This allows …
=> Publish `RuboCop::LSP.enable` to enable LSP mode

changelog/fix_false_negatives_for_lint_redundant_safe_navigation.md, lib/rubocop/cop/lint/redundant_safe_navigation.rb, spec/rubocop/cop/lint/redundant_safe_navigation_spec.rb
This is similar to detection #12246.
This PR fixes false negatives for `Lint/RedundantSafeNavigation` when using safe navigation operator for literal receiver.
=> Fix false negatives for `Lint/RedundantSafeNavigation`

changelog/new_make_offense_count_formatter_display_autocorrection_info.md, docs/modules/ROOT/pages/formatters.adoc, lib/rubocop/formatter/offense_count_formatter.rb, spec/rubocop/cli/auto_gen_config_spec.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cli/options_spec.rb, spec/rubocop/cli_spec.rb, spec/rubocop/formatter/offense_count_formatter_spec.rb, spec/rubocop/rake_task_spec.rb
Fixes #12273.
This PR makes `OffenseCountFormatter` display autocorrection information.
This solves the use case of checking and selectively applying cops that support autocorrection when there are some unresolved offenses.
Although it may be possible to provide an option, finding use cases for making them optional seems unlikely. Therefore, the new autocorrection information will always be displayed.
=> [Fix #12273] Make `OffenseCountFormatter` display autocorrection info

lib/rubocop/cop/style/redundant_line_continuation.rb, spec/rubocop/cop/style/redundant_line_continuation_spec.rb
This PR fixes the following error `Style/RedundantLineContinuation` when using `Prism::Translation::Parser` as a parser:
```console
$ bundle exec ruby -rprism/translation/parser/rubocop $(bundle exec which rubocop)
(snip)
An error occurred while Style/RedundantLineContinuation cop was inspecting
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/lint/out_of_range_regexp_ref.rb.
undefined method `complete?' for an instance of AST::Node
/Users/koic/src/github.com/rubocop/rubocop-ast/lib/rubocop/ast/node.rb:104:in `block in initialize'
```
This is a similar error to #12677.
=> Fix an error for `Style/RedundantLineContinuation` when using `Prism::Translation::Parser`

spec/rubocop/options_spec.rb
This PR makes the following options_spec as pending when using Ruby 3.4.0dev.
```console
$ ruby -v
ruby 3.4.0dev (2024-02-09T12:28:26Z master 08b77dd682) [x86_64-darwin23]
$ bundle exec rspec './spec/rubocop/options_spec.rb[1:1:1:2]'
(snip)
1 example, 1 failure
rspec ./spec/rubocop/options_spec.rb:29 # RuboCop::Options option -h/--help shows help text
```
https://github.com/rubocop/rubocop/actions/runs/7845618444/job/21410458812?pr=12657
The pending spec should be update to behavior in accordance with the inquiry results of https://bugs.ruby-lang.org/issues/20252.
=> Make an options_spec as pending when using Ruby 3.4.0dev

lib/rubocop/cop/style/redundant_argument.rb
This PR avoids redundant repetitive `parse` for `Style/RedundantArgument`.
Similar to #12677 and #12678, there is no need to parse code that has already been parsed once.
=> Avoid redundant `parse` for `Style/RedundantArgument`

changelog/new_extend_autocorrect_option_for_lsp.md, config/default.yml, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop/config_validator.rb, lib/rubocop/cop/autocorrect_logic.rb, lib/rubocop/cop/base.rb, lib/rubocop/cops_documentation_generator.rb, lib/rubocop/rspec/shared_contexts.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cli/options_spec.rb, spec/rubocop/cli_spec.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/lsp/server_spec.rb
This PR introduces `AutoCorrect: contextual` option that prevents autocorrection during typing in LSP.
This option extends the existing `AutoCorrect` parameter.
- Before: `AutoCorrect: true` or `AutoCorrect: false`
- After: `AutoCorrect: always`, `AutoCorrect: disabled`, or `AutoCorrect: contextual`
Note, `AutoCorrect: always` maintains compatibility with `AutoCorrect: true`,
and `AutoCorrect: disabled` maintains compatibility with `AutoCorrect: false`.
For example, `Style/EmptyMethod` should not autocorrect to one-liner while in the process of writing the body of the method.
This isn't an issue with autocorrection itself, but rather due to differing requirements in contexts such as editing (LSP) and command line (e.g., CI).
So, `AutoCorrect: contextual` is set for some cops like this. …
=> Support `AutoCorrect: contextual` option for LSP

changelog/new_add_editor_mode_option.md, docs/modules/ROOT/pages/configuration.adoc, docs/modules/ROOT/pages/usage/basic_usage.adoc, lib/rubocop/cli.rb, lib/rubocop/options.rb, spec/rubocop/cli/options_spec.rb, spec/rubocop/options_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/12657#issuecomment-1937084864.
This PR adds `--editor-mode` CLI option, which optimize real-time feedback in editors, adjusting behaviors for editing experience.
Editors that run RuboCop directly (e.g., by shelling out) encounter the same issues as with `--lsp`. This option is designed for such editors.
=> Add `--editor-mode` CLI option

changelog/fix_an_incorrect_autocorrect_for_style_map_compact_with_conditional_block.md, lib/rubocop/cop/style/map_compact_with_conditional_block.rb, spec/rubocop/cop/style/map_compact_with_conditional_block_spec.rb
Fixes #12683
This PR fixes an incorrect autocorrect for `Style/MapCompactWithConditionalBlock` when using guard clause with `next` implicitly nil. It also fixes the incorrect test code.
=> [Fix #12683] Fix an incorrect autocorrect for `Style/MapCompactWithConditionalBlock`

changelog/fix_false_positive_for_lint_void.md, lib/rubocop/cop/lint/void.rb, spec/rubocop/cop/lint/void_spec.rb
Fixes #12687.
This PR fixes a false positive for `Lint/Void` when `each` block with conditional expressions that has multiple statements.
=> [Fix #12687] Fix a false positive for `Lint/Void`

changelog/fix_false_positives_for_style_inverse_methods.md, lib/rubocop/cop/style/inverse_methods.rb, spec/rubocop/cop/style/inverse_methods_spec.rb
Fixes #12649.
This PR fixes false positives for `Style/InverseMethods` when using relational comparison operator with safe navigation.
=> [Fix #12649] Fix false positives for `Style/InverseMethods`

changelog/fix_error_for_style_multiline_ternary_operator.md, lib/rubocop/cop/style/multiline_ternary_operator.rb, spec/rubocop/cop/style/multiline_ternary_operator_spec.rb
Fixes #12691.
This PR fixes an error for `Style/MultilineTernaryOperator` when nesting multiline ternary operators.
=> [Fix #12691] Fix an error for `Style/MultilineTernaryOperator`

changelog/fix_an_incorrect_for_style_object_then.md, lib/rubocop/cop/style/object_then.rb, spec/rubocop/cop/style/object_then_spec.rb
Fixes #12693.
This PR fixes an incorrect autocorrect for `Style/ObjectThen` when using `yield_self` without receiver.
=> [Fix #12693] Fix an incorrect autocorrect for `Style/ObjectThen`

changelog/fix_an_error_for_style_case_like_if.md, lib/rubocop/cop/style/case_like_if.rb, spec/rubocop/cop/style/case_like_if_spec.rb
Fixes #12690.
This PR fixes an error for `Style/CaseLikeIf` when using `==` with literal and using ternary operator.
=> [Fix #12690] Fix an error for `Style/CaseLikeIf`

changelog/new_support_dot_config.md, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop/config_finder.rb, spec/rubocop/config_loader_spec.rb
Follow https://github.com/rubocop/rubocop/pull/12700#issuecomment-1949764386
This PR supports searching for `rubocop/config.yml` in compliance with dot-config.
This PR adds `project_root/.config/rubocop/config.yml` to the list of paths to search, matching XDG path format of the already targeted `~/.config/rubocop/config.yml`.
However, support for `~/.config/rubocop.yml` is not included in this PR, as the outcome of inquiry https://github.com/dot-config/dot-config.github.io/issues/17 regarding it is still pending.
=> Support searching for `rubocop/config.yml` in compliance with dot-config

changelog/fix_false_negative_for_style_redundant_assignment.md, lib/rubocop/cop/style/redundant_assignment.rb, spec/rubocop/cop/style/redundant_assignment_spec.rb
This PR fixes false negative for `Style/RedundantAssignment` when using pattern matching.
=> Fix false negative for `Style/RedundantAssignment`

changelog/fix_config_include_bug.md, lib/rubocop/path_util.rb, spec/rubocop/cli_spec.rb
When we inherit configuration from a file in a parent or ancestor directory, and that file is called `.rubocop.yml`, the paths in its Include parameters are interpreted as being relative to the file, or rather its directory. This is specific for file names starting with `.rubocop`. The problem is that file name matching that we do when searching for target files to inspect doesn't work for patterns that start with `..`. Solve the problem by matching absolute paths in these corner cases.
=> [Fix #12695] Handle Include from inherited file in parent directory

lib/rubocop/path_util.rb
A spelling mistake that I made. The change was already merged when I was made aware of it.
=> Fix spelling

changelog/fix_auto_gen_config_SpaceBeforeBlockBraces.md, lib/rubocop/cop/layout/space_before_block_braces.rb, spec/rubocop/cop/layout/space_before_block_braces_spec.rb
The `Layout/SpaceBeforeBlockBraces` cop has two separate style parameters, `EnforcedStyle` and `EnforcedStyleForEmptyBraces`. The logic for generating `Enabled: false` when opposite styles are detected during `--auto-gen-config` was implemented for `EnforcedStyle`, but it was missing for `EnforcedStyleForEmptyBraces`.
=> [Fix #12646] Handle opposite styles for Layout/SpaceBeforeBlockBraces

changelog/fix_an_error_for_gemspec_required_ruby_version.md, lib/rubocop/cop/gemspec/required_ruby_version.rb, spec/rubocop/cop/gemspec/required_ruby_version_spec.rb
Fixes #12714.
This PR fixes an error for `Gemspec/RequiredRubyVersion` when `required_ruby_version` is specified with `Gem::Requirement.new` and is higher than `TargetRubyVersion`.
When specifying only an upper version limit, an offense is registered because lower Ruby version that matches `TargetRubyVersion` is unknown.
=> [Fix #12714] Fix an error for `Gemspec/RequiredRubyVersion`

changelog/fix_false_negatives_for_style_arguments_forwarding.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
This PR fixes false negatives for `Style/ArgumentsForwarding` when using forwardable block arguments with Ruby 3.2+.
The anonymous block forwarding that worked up to Ruby 3.1 stopped functioning from Ruby 3.2+. This PR ensures consistent behavior even in Ruby 3.2+.
=> Fix false negatives for `Style/ArgumentsForwarding`

changelog/fix_commented_keyword.md, lib/rubocop/cop/style/commented_keyword.rb, spec/rubocop/cop/style/commented_keyword_spec.rb
To make sure we don't have a different, more strict definition of what constitutes a `rubocop:disable` or `rubocop:todo` comment in the cop compared to elsewhere in the code, use the definition implemented in `DirectiveComment`.
We also get the `rubocop:enable` comments included in this definition, but it's not a problem if we allow those comments in the cop, as they don't make any sense as end-of-line comments and are unlikely to occur.
=> [Fix #12717] Re-use definition of directive comments from CommentedKeyword

changelog/fix_handle_implicit_receivers_in.md, lib/rubocop/cop/style/invertible_unless_condition.rb, spec/rubocop/cop/style/invertible_unless_condition_spec.rb
Previously, we would attempt to call `node.receiver.source`, but `node.receiver` could be `nil`.
```
An error occurred while Style/InvertibleUnlessCondition cop was inspecting /path/to/file.rb:123:4.
undefined method `source' for nil
```
This teaches the cop to handle implicit receivers.
=> Handle implicit receivers in `Style/InvertibleUnlessCondition`

lib/rubocop/cop/style/invertible_unless_condition.rb
These changes were meant to appear in #12711 in response to feedback on the PR, but were accidentally not pushed.
cc. @bbatsov
* ~Added tests.~
=> Add missing PR feedback changes from #12711

spec/rubocop/options_spec.rb
Reverts #12680.
#12680's issue has been resolved by https://github.com/ruby/optparse/commit/78afdab307.
=> Restore a spec of options_spec for Ruby 3.4.0dev

changelog/fix_invalid_autocorrect_in_layout_space_inside_hash_literal_braces.md, lib/rubocop/cop/layout/space_inside_hash_literal_braces.rb, spec/rubocop/cop/layout/space_inside_hash_literal_braces_spec.rb, spec/rubocop/cop/registry_spec.rb
Fix an invalid autocorrect in `Layout/SpaceInsideHashLiteralBraces` when the last hash element’s value is the text '{'.
Fixes #12736
=> Fix invalid autocorrect in Layout/SpaceInsideHashLiteralBraces

lib/rubocop/config.rb, lib/rubocop/config_validator.rb, lib/rubocop/target_ruby.rb
There was remaining code where `ParserEngine` parameter was not used by `ProcessedSource`, and Parser gem was always used. With this PR, switching between Parser and Prism will be implemented at all usage points of `RuboCop::ProcessedSource`.
=> Use `ParserEngine` parameter to parse gemspec

changelog/fix_loading_of_excluded_config.md, lib/rubocop/target_finder.rb, spec/rubocop/target_finder_spec.rb
This change fixes an error that can occur when file names are given explicitly on the command line together with `--force-exclusion`.
In order to check if the given files are to be excluded, we must load configuration. The problem is that `.rubocop.yml` files in directories with excluded files (e.g. a `vendor` directory) might contain directives that will cause RuboCop to crash, such as `require` with an extension that's not available.
What saves us in this situation is that we don't need to load configuration for the file as such. We can load configuration for the current directory instead. The reason is that `Exclude` parameters on the top level are not shadowed by `Exclude` in other `.rubocop.yml` files in subdirectories, as documented here: …
=> [Fix #12667] Avoid loading excluded configuration

changelog/fix_an_error_for_style_encoding.md, lib/rubocop/magic_comment.rb, spec/rubocop/cop/style/encoding_spec.rb
Fixees #12738.
This PR fixes an error for `Style/Encoding` when magic encoding with mixed case present.
=> [Fix #12738] Fix an error for `Style/Encoding`

lib/rubocop/rspec/expect_offense.rb
Fixes #12740.
This PR tweaks annotation pattern for `expect_offense`.
When there is no space between `^` annotation and message, as follows:
```ruby
expect_offense(<<~RUBY)
#!/usr/bin/env ruby
^^^^^^^^^^^^^^^^^Unnecessary utf-8 encoding comment.
def foo() end
RUBY
```
Despite being correct with `expect_offense`, it suggests using `expect_no_offenses`:
```console
$ bundle exec rspec spec/rubocop/cop/style/encoding_spec.rb
(snip)
Failures:
1) RuboCop::Cop::Style::Encoding registers an offense when encoding present on 2nd line after shebang
Failure/Error: raise 'Use `expect_no_offenses` to assert that no offenses are found'
RuntimeError:
Use `expect_no_offenses` to assert that no offenses are found
```
It suggests that the usage of annotation is incorrect:
```console
$ bundle exec rspec …
```
=> [Fix #12740] Tweak annotation pattern for `expect_offense`

Gemfile, changelog/fix_call_value_to_get_gemspec_required_ruby_version.md, lib/rubocop/target_ruby.rb, spec/rubocop/target_ruby_spec.rb
fixes #12744
This change avoids an exception (NoMethodError: undefined method \`value' for an instance of RuboCop::AST::SendNode) that currently occurs in `rubocop` version 1.61.0 when the project has a gemspec file and that gemspec specifies a `required_ruby_version` by reading from another file (such as `.ruby-version`).
**Example of an affected gemspec file:**
```rb
spec.required_ruby_version = Gem::Requirement.new(">= #{File.read('.ruby-version').rstrip}")
end
```
This bug began occurring in several of my projects as a result of #12645 (d1746bedd) ("Check gemspec `required_ruby_version` before `.ruby-version` and other sources"). My projects have both a `.ruby-version` file and also a gemspec that (as in the example above) sets the …
=> Call .value to get gemspec required_ruby_version only if str_type?

changelog/fix_a_false_positive_for_lint_to_enum_arguments.md, lib/rubocop/cop/lint/to_enum_arguments.rb, spec/rubocop/cop/lint/to_enum_arguments_spec.rb
Fixes #12746.
This PR fixes a false positive for `Lint/ToEnumArguments` when enumerator is created for another method in no arguments method definition.
=> [Fix #12746] Fix a false positive for `Lint/ToEnumArguments`

changelog/fix_error_for_lint_mixed_case_range.md, lib/rubocop/cop/utils/regexp_ranges.rb, spec/rubocop/cop/lint/mixed_case_range_spec.rb
Closes #12703
While this fixes the above issues, there is still a problem with this cop. If a regex contains this escape _and_ also contains an offense, it will still error. I have openend #12750 for this. Fixing this as well turned out to be too complicated for me.
=> [Fix #12703] Fix an error for `Lint/MixedCaseRange` with invalid byte sequence in UTF-8

changelog/fix_an_error_for_gemspec_required_ruby_version.md, lib/rubocop/cop/gemspec/required_ruby_version.rb, spec/rubocop/cop/gemspec/required_ruby_version_spec.rb
This happens if you have `ruby-lsp` enabled and create a new gemspec file.
=> Fix an error for `Gemspec/RequiredRubyVersion` when the file is empty

changelog/fix_error_for_redundant_current_directory_in_path.md, lib/rubocop/cop/style/redundant_current_directory_in_path.rb, spec/rubocop/cop/style/redundant_current_directory_in_path_spec.rb
Consider the following (completely valid) ruby program:
```ruby
require_relative
```
Checking it with rubocop produces the following exception:
```bash
bundle exec rubocop -d test.rb
...
undefined method `str_content' for nil:NilClass
/home/viralpraxis/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/rubocop-1.61.0/lib/rubocop/cop/style/redundant_current_directory_in_path.rb:25:in `on_send'
...
```
To fix the issue we can simply enhance
`return unless node.first_argument.str_content&.start_with?(CURRENT_DIRECTORY_PATH)`
so that it returns if `node.first_argument` is `nil`
1.62.0 (using Parser 3.3.0.5, rubocop-ast 1.31.1, running on ruby 3.3.0) [x86_64-linux]
=> Fix `RedundantCurrentDirectoryInPath` cop exception in case of `require_relative` without any arguments

changelog/fix_only_parse_target_ruby_from_gemspec_if_array.md, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop/target_ruby.rb, spec/rubocop/target_ruby_spec.rb
This fixes an issue mentioned in [this comment](https://github.com/rubocop/rubocop/issues/12579#issuecomment-1974916930) on issue #12579. (I believe that the main/original issue mentioned in issue #12579 has essentially already been fixed by #12732.)
This change is a related/similar followup to #12732 (50263938f). That PR avoided an exception that was occurring in the
`RuboCop::TargetRuby::GemspecFile` target Ruby finder when a project's gemspec determines the value of `required_ruby_version` in some dynamic way (such as by reading from a `.ruby-version` file).
However, #12732 did not handle a case where the dynamic value for the gemspec's `required_ruby_version` is wrapped within an array, and, in such a case, currently, an exception like the following will occur:
``` …
```
=> Only parse target Ruby from gemspec if array elements are strings

changelog/change_skip_line_length_phase_on_auto_gen_only_exclude.md, lib/rubocop/cli/command/auto_generate_config.rb, spec/rubocop/cli/auto_gen_config_spec.rb
Phase 1 of config auto-generation runs the `Layout/LineLength` cop on all files to discover the `Max` line length, so it can be used by cops which depend on it.
The `--auto-gen-only-exclude` config skips generating any `Max` configs, meaning phase 1 is redundant, as we won't generate the `Max` for use by phase 2.
Therefore, we can skip phase 1 entirely. Even though we're only running `Layout/LineLength`, parsing the entire codebase twice can get quite time consuming on large repositories.
=> Skip `LineLength` phase on `--auto-gen-only-exclude`

changelog/fix_a_false_positive_for_style_hash_each_methods.md, lib/rubocop/cop/style/hash_each_methods.rb, spec/rubocop/cop/style/hash_each_methods_spec.rb
Fixes #12761.
This PR fixes a false positive for `Style/HashEachMethods` when the key block argument of `Enumerable#each` method is unused after `chunk`.
=> [Fix #12761] Fix a false positive for `Style/HashEachMethods`

changelog/fix_lint_syntax_being_disabled_by_directive_comments.md, lib/rubocop/directive_comment.rb, spec/rubocop/cli_spec.rb, spec/rubocop/comment_config_spec.rb
Fixes #12663
This would swallow the syntax error, making it look like the file is all good.
In reality all other cops are not being run, even if `Lint/Syntax` is "enabled" again later on.
This code for example would show as having no offenses.
```rb
1 /// 2
a = ""
b = ''
```
=> [Fix #12663] Prevent `Lint/Syntax` being disabled by directive comments

changelog/fix_false_positive_for_layout_redundant_line_break.md, lib/rubocop/cop/layout/redundant_line_break.rb, spec/rubocop/cop/layout/redundant_line_break_spec.rb
Fixes #12758.
This PR fixes false positives for `Layout/RedundantLineBreak` when using `&&` or `||` after a backslash newline.
=> [Fix #12758] Fix false positives for `Layout/RedundantLineBreak`

changelog/fix_and_error_for_layout_multiline_method_call_indentation.md, lib/rubocop/cop/mixin/multiline_expression_indentation.rb, spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb
It wasn't checking for csend, resulting in `:method_name=.begin_pos` later down.
=> Fix an error for `Layout/MultilineMethodCallIndentation` with safe navigation and assignment method

changelog/fix_infinite_loop_for_style_multiline_method_signature.md, lib/rubocop/cop/style/multiline_method_signature.rb, lib/rubocop/rspec/expect_offense.rb, spec/rubocop/cop/style/multiline_method_signature_spec.rb
This undoes a part of #8090, specifically at https://github.com/rubocop/rubocop/pull/8090/commits/448eb9662d2e5067b65c1e8de9b4dd8019cc9e0c. There don't seem to be any consequences of doing so except for uncovering this bug.
A test case for this issue has already been added in #11768 but after the result has been reached there are still correctors that result in an infinite loop. In practice some other cop comes in first and makes this situation unlikely to actually encounter, unless it is disabled of course.
While I was working on #12753 I got into a similar situation, where my assertions where passing but actually running it on the codebase resulted in an infinite loop. 
This PR fixes the ininite loop and makes these situations impossible by only considering a correction done if there …
=> Fix an infinite loop for `Style/MultilineMethodSignature` when line break after def

changelog/fix_a_false_positive_for_style_nil_comparison.md, lib/rubocop/cop/style/nil_comparison.rb, spec/rubocop/cop/style/nil_comparison_spec.rb
This would previously show an offense and get into an infinite loop during correction.
=> Fix a false positive for `Style/NilComparison` without receiver and `EnforcedStyle: comparison`

changelog/fix_an_error_for_lint_redundant_with_index.md, lib/rubocop/cop/lint/redundant_with_index.rb, spec/rubocop/cop/lint/redundant_with_index_spec.rb
Did not validate that there even is a receiver.
=> Fix an error for `Lint/RedundantWithIndex` when there is no receiver

changelog/fix_an_error_for_style_class_vars.md, lib/rubocop/cop/style/class_vars.rb, spec/rubocop/cop/style/class_vars_spec.rb
LSP stuff, happens when you type and excessively save.
=> Fix an error for `Style/ClassVars` when calling `class_variable_set` without arguments

changelog/fix_an_error_for_style_for.md, lib/rubocop/cop/style/for.rb, spec/rubocop/cop/style/for_spec.rb
There is no autocorrect I can see that makes sense in this case.
=> Fix an error for `Style/For` with `EnforcedStyle: for` when no receiver

lib/rubocop/cop/internal_affairs/node_matcher_directive.rb, spec/rubocop/cop/internal_affairs/node_matcher_directive_spec.rb
See https://github.com/rubocop/rubocop/pull/12753#issuecomment-1987246707
cc @bquorning, thanks for trying it out early.
=> Fix a wrong offense message for `InternalAffairs/NodeMatcherDirective`

changelog/fix_infinite_loop_for_style_raise_args.md, lib/rubocop/cop/style/raise_args.rb, lib/rubocop/rspec/expect_offense.rb
The following test causes the loop: https://github.com/rubocop/rubocop/blob/5ee786dcadfa3c91096d9e81dcd16e4776ca6186/spec/rubocop/cop/style/raise_args_spec.rb#L130-L140
This changes `expect_no_corrections`  to always raise if there are correctors. In this case the corrector replaced nothing, resulting in the same cop being invocted again for the same reason.
Undoing the cop change while keeping the assertion change will produce a failure. The source assertion is left in because it produces nice diffs if there are actually changes.
=> Fix an infinite loop for `Style/RaiseArgs` with `EnforcedStyle: compact` when passing more than 2 arguments to `raise`

changelog/fix_an_error_for_lint_useless_times.md, lib/rubocop/cop/lint/useless_times.rb, spec/rubocop/cop/lint/useless_times_spec.rb
Another thing that's more common with an LSP.
=> Fix an error for `Lint/UselessTimes` when no block is present

changelog/change_make_lint_debugger_aware_of_require.md, config/default.yml, lib/rubocop/cop/lint/debugger.rb, spec/rubocop/cop/lint/debugger_spec.rb
I debated adding requires like `debug` or `pry` but believe that would do more harm than good.
RuboCops own spec_helper requires pry. This seems to come from some sort of template.
=> [Fix #12721] Add `DebuggerRequires` to `Lint/Debugger`

lib/rubocop/cop/internal_affairs/example_description.rb, spec/rubocop/cop/internal_affairs/example_description_spec.rb, spec/rubocop/cop/style/require_order_spec.rb
Follow up: https://github.com/rubocop/rubocop/pull/12777
=> Add support for `InternalAffairs/ExampleDescription` when using "registers no offense"

changelog/fix_an_error_for_style_redundant_each.md, lib/rubocop/cop/style/redundant_each.rb, spec/rubocop/cop/style/redundant_each_spec.rb
=> Fix an error for `Style/RedundantEach` when using `reverse_each.each` without a block

changelog/fix_an_error_for_style_exact_regexp_match.md, lib/rubocop/cop/style/exact_regexp_match.rb, spec/rubocop/cop/style/exact_regexp_match_spec.rb
`match(/\Astring\z/)` for example raises.
=> Fix an error for `Style/ExactRegexpMatch` when calling `match` without a receiver

changelog/fix_an_error_for_style_alias.md, lib/rubocop/cop/style/alias.rb, spec/rubocop/cop/style/alias_spec.rb
This happens in every context. Classes, Modules, etc. I don't believe it necessary to add one for each. I've also added tests for the other EnforcedStyle but it doesn't raise currently.
I've added no tests for `alias` calls with fewer arguments call since that is just a syntax error.
=> Fix an error for `Style/Alias` when calling `alias_method` with fewer than 2 arguments.

changelog/fix_a_false_positive_for_lint_redundant_with_index.md, lib/rubocop/cop/lint/redundant_with_index.rb, spec/rubocop/cop/lint/redundant_with_index_spec.rb
Fixes #12769.
This PR fixes a false positive for `Lint/RedundantWithIndex` when calling `with_index` with receiver and a block.
=> [Fix #12769] Fix a false positive for `Lint/RedundantWithIndex`

changelog/fix_make_redundant_percent_q_safe_on_multiline_strings.md, lib/rubocop/cop/style/redundant_percent_q.rb, spec/rubocop/cop/style/redundant_percent_q_spec.rb
The regex used in `Style/RedundantPercentQ` is not resilient to multiline input, meaning that its autocorrect would unsafely operate on strings defined across multiple lines with `%Q` where these used quotes. This PR changes the anchors on the regex used by the cop so that its autocorrect determines the correct delimiter safely.
=> Make Style/RedundantPercentQ handle multiline source safely

spec/rubocop/rspec/expect_offense_spec.rb, spec/support/cops/infinite_loop_during_autocorrect.rb, spec/support/cops/infinite_loop_during_autocorrect_with_change.rb
This relates to #12763 and #12774, where behaviour for these two methods was changed. Undoing changes from these PRs will make these new tests fail.
I thought it would be nice to explicitly test against since there shouldn't ever be code here where this behaviour is actually triggered. I haven't found a place where the expectations were already tested so I made a new file for that.
=> Add tests for `expect_no_corrections` and `expect_correction` loop behaviour

changelog/fix_false_positives_for_style_eval_with_location.md, lib/rubocop/cop/style/eval_with_location.rb, spec/rubocop/cop/style/eval_with_location_spec.rb
This PR fixes false positives for `Style/EvalWithLocation` when using eval with a line number from a method call or a variable.
These cases should be respected under the assumption that they are intentional.
=> Fix false positives for `Style/EvalWithLocation`

changelog/change_handle_empty_obsoletion_config.md, lib/rubocop/config_obsoletion.rb, spec/rubocop/config_obsoletion_spec.rb
Extension maintainers may want to create a `config/obsoletion.yml` prior to having any obsoletions, just so it is hooked up and ready.
Prior to this change, this would result in a `TypeError`:
no implicit conversion of nil into Hash
=> Handle empty obsoletion config

changelog/fix_false_positives_for_style_redundant_line_continuation.md, lib/rubocop/cop/style/redundant_line_continuation.rb, spec/rubocop/cop/style/redundant_line_continuation_spec.rb
Fixes #12797.
This PR fixes false positives for `Style/RedundantLineContinuation` when using line continuations with `&&` or `||` operator in assignment.
=> [Fix #12797] Fix false positives for `Style/RedundantLineContinuation`

changelog/fix_return_global_offenses_for_inclusive_naming_and_file_name.md, lib/rubocop/cop/naming/file_name.rb, lib/rubocop/cop/naming/inclusive_language.rb, spec/rubocop/cop/naming/file_name_spec.rb, spec/rubocop/cop/naming/inclusive_language_spec.rb
When checking against filenames, a global offense should be added. The current behaviour causes problems in things like LSPs that inspect the offense for location information since some operations on these offenses will raise a `IndexError`.
I've tweaked the specs for `InclusiveLanguage` since they just passed without any changes. With the annotation expectations, it actually checks the offense location (or lack thereof).
```rb
require "rubocop"
processed_source = RuboCop::ProcessedSource.new("", 3.3)
range = Class.new.extend(RuboCop::Cop::RangeHelp).send(:source_range, processed_source.buffer, 1, 0)
offense = RuboCop::Cop::Offense.new(:info, range, "global offense", "Naming/FileName", :unsupported)
offense.highlighted_area.begin_pos
=> # …
```
=> Return global offenses for `Naming/FileName` and `Naming/InclusiveLanguage`

changelog/fix_false_positive_for_style_redundant_line_continuation.md, lib/rubocop/cop/style/redundant_line_continuation.rb, spec/rubocop/cop/style/redundant_line_continuation_spec.rb
Part of #12793.
This PR fixes false positives for `Style/RedundantLineContinuation` when using line continuation with modifier.
=> Fix false positives for `Style/RedundantLineContinuation`

changelog/fix_false_positives_for_naming_block_forwarding.md, lib/rubocop/cop/naming/block_forwarding.rb, spec/rubocop/cop/naming/block_forwarding_spec.rb
Fixes #12807.
This PR fixes false positives for `Naming/BlockForwarding` when using explicit block forwarding in block method and others.
=> [Fix #12807] Fix false positives for `Naming/BlockForwarding`

docs/modules/ROOT/pages/usage/profiling.adoc
Two missing spaces, plus the `a` sounds awkward (there's only one stackprof gem).
=> Small tweaks to profiling docs

changelog/fix_return_global_offenses_for_style_copyright.md, lib/rubocop/cop/style/copyright.rb, lib/rubocop/formatter/clang_style_formatter.rb, lib/rubocop/formatter/tap_formatter.rb, lib/rubocop/rspec/expect_offense.rb, spec/rubocop/cop/style/copyright_spec.rb
Very similar to #12802
This adds a check that the returned offenses have a location that formatters can display. While the standard formatter catched the `IndexError`, barely any others did.
Since it is not possible to autocorrect global offenses, just don't do that. Adding autocorrect support would be a bunch more work. I've kept autocorrect for cases where the file isn't empty since, while the offense location isn't technically correct, it works.
---
Note that I removed the catching of `IndexError` for the default formatter. Barely any others, except for Tap did that. Formatters like html and markdown would raise when inspecting a empty file with `Style/Copyright`.
The added extra expectations would have caught the `Style/Copyright` and `Naming/FileName` cases, and it also raises for …
=> Return global offenses for `Style/Copyright` when the file is empty

changelog/fix_assignment_in_condition_safe_nav_setter.md, lib/rubocop/cop/lint/assignment_in_condition.rb, lib/rubocop/cop/mixin/safe_assignment.rb, spec/rubocop/cop/lint/assignment_in_condition_spec.rb
In order to detect code like `if test&.method = 10` we need to find not only `send` nodes but also `csend` nodes.
=> [Fix #12731] Treat csend the same way as send for setter methods

changelog/fix_false_positives_for_style_redundant_line_continuation_cop.md, lib/rubocop/cop/style/redundant_line_continuation.rb, spec/rubocop/cop/style/redundant_line_continuation_spec.rb
Fixes #12793.
This PR fixes false positives for `Style/RedundantLineContinuation` when multi-line continuations with operators.
In #12678, the use of `RuboCop::Cop::Base#parse` method was avoided due to errors in Prism. Now, the error in Prism have been fixed:
https://github.com/rubocop/rubocop/pull/12677#issuecomment-1932189221
And given redundant line continuation patterns is too varied, this PR have reverted to a simpler implementation using the `parse` method.
=> [Fix #12793] Fix false positives for `Style/RedundantLineContinuation`

changelog/fix_false_positives_for_style_redundant_argument.md, lib/rubocop/cop/style/redundant_argument.rb, spec/rubocop/cop/style/redundant_argument_spec.rb
Fixes #12794.
This PR fixes false positives for `Style/RedundantArgument` when when single-quoted strings for cntrl character.
=> [Fix #12794] Fix false positives for `Style/RedundantArgument`

changelog/change_add_rubocop_rspec_rails_to_suggested_extensions.md, config/default.yml, docs/modules/ROOT/pages/extensions.adoc, spec/rubocop/cli/suggest_extensions_spec.rb
This PR adds [rubocop-rspec_rails](https://github.com/rubocop/rubocop-rspec_rails) to the `SuggestExtensions` list and extension doc.
=> Add rubocop-rspec_rails to suggested extensions and extension doc

changelog/change_adjust_offending_range_in_lsp.md, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop/cop/mixin/code_length.rb, lib/rubocop/cop/mixin/method_complexity.rb, spec/rubocop/cop/metrics/abc_size_spec.rb, spec/rubocop/cop/metrics/block_length_spec.rb, spec/rubocop/cop/metrics/class_length_spec.rb, spec/rubocop/cop/metrics/cyclomatic_complexity_spec.rb, spec/rubocop/cop/metrics/module_length_spec.rb
Fixes #12676.
Highlighting offenses for entire classes, modules, and methods is considered noisy in LSP. Instead, highlighting will be applied only to the class names or method names for offenses.
To maintain compatibility for uses outside of LSP, such as with `--disable-uncorrectable`, the behavior will be changed only when `RuboCop::LSP.enabled?` is true.
=> [Fix #12676] Adjust offending range in LSP

changelog/new_requires_gem_api.md, docs/modules/ROOT/pages/development.adoc, lib/rubocop/config.rb, lib/rubocop/cop/base.rb, lib/rubocop/cop/team.rb, lib/rubocop/lockfile.rb, lib/rubocop/rspec/shared_contexts.rb, spec/rubocop/config_spec.rb, spec/rubocop/cop/cop_spec.rb
Fixes #11920.
This PR is used by:
1. https://github.com/rubocop/rubocop/pull/12180
2. https://github.com/rubocop/rubocop-rails/pull/1137
=> Add new `requires_gem` API for declaring which gems a Cop needs

changelog/change_replace_regex_with_BundlerLockfileParser.md, lib/rubocop/config.rb
Depends on #12186, see the difference: https://github.com/amomchilov/rubocop/compare/add-requires_gem-api...parse-lockfile-with-bundler
Now that we have a Hash of all of the target's gems, we can just use that `target_rails_version_from_bundler_lock_file`, and remove the manual regex parsing.
=> Replace regex with `Bundler::LockfileParser`

changelog/change_make_rubocop_v_display_rubocop_rspec_rails_version.md, lib/rubocop/version.rb, spec/rubocop/version_spec.rb
This PR makes `rubocop -V` display rubocop-rspec_rails version when using it.
=> Make `rubocop -V` display rubocop-rspec_rails version when using it

Gemfile
This is a workaround for incompatibilities between Prism 0.24.0 and 0.25.0. To upgrade to Prism 0.25+, it is necessary to investigate the following build error and provide feedback to Prism:
https://github.com/rubocop/rubocop/actions/runs/8578707777/job/23512878899
I will proceed with these separately.
=> Workaround for incompatibilities between Prism 0.24.0 and 0.25.0

changelog/change_add_support_more_capybara_debugger_entry_points.md, config/default.yml, spec/rubocop/cop/lint/debugger_spec.rb
This PR makes add support more Capybara debugger entry points for `Lint/Debugger`
- page.save_and_open_page
- page.save_and_open_screenshot
- page.save_page
- page.save_screenshot
- save_page
- https://www.rubydoc.info/gems/capybara/Capybara%2FSession:save_page
- save_screenshot
- https://www.rubydoc.info/gems/capybara/Capybara%2FSession:save_screenshot
=> Add support more Capybara debugger entry points for `Lint/Debugger`

changelog/change_exclude_rakefile_rb_in_naming_filename.md, config/default.yml
=> Exclude `Rakefile.rb` from `Naming/FileName` check

changelog/fix_added_comments_for_infinite_loop_detected_error.md, lib/rubocop/runner.rb, spec/rubocop/runner_spec.rb
[#12547](https://github.com/rubocop/rubocop/issues/12547)
This pull request includes the following:
- Added a comment suggesting to upgrade Rubocop to the latest version in case of "Infinite loop detected" error.
- Modified RSpec accordingly.
=> [Fix #12547] User experience for infinite loop detected

changelog/fix_uninitialized_constant_bundler.md, lib/rubocop/lockfile.rb
Fixes #12823
The bug originates from #12186, which changed the `defined?` check in a way that didn't cover this broken reference to `Bundler` on line 66:
https://github.com/rubocop/rubocop/blob/a4447ea10744d65b8ea781ec5fbe591c1b514e92/lib/rubocop/lockfile.rb#L59-L68
This wasn't caught in CI, because none of the cops used by Rubocop (to check its own source code in CI) use Rails cops, so `RuboCop::Config#target_rails_version_from_bundler_lock_file` was never called in CI.
An easy way to reproduce this is to just modify a gem used by Rubocop itself (e.g. `RuboCop::Cop::Layout::IndentationStyle`), adding `requires_gem 'rubocop'` to its body. This triggers the `target_rails_version_from_bundler_lock_file` code path when you run `exe/rubycop .` to run rubocop on its own codebase. …
=> [Fix #12823] Fix uninitialized constant error

changelog/fix_false_positive_for_assignment_in_conditional.md, lib/rubocop/cop/lint/assignment_in_condition.rb, spec/rubocop/cop/lint/assignment_in_condition_spec.rb
This reverts d0828e532e1845ce44e522e05a2d978b87a890f1 and adds a testcase.
The correction is `return unless %i[asc desc].include?((order = params[:order]))` which just doesn't look right.
cc @jonas054 
=> Fix a false positive for `Lint/AssignmentInConditional` if assigning inside a method call

changelog/fix_an_error_for_style_arguments_forwarding.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
Fixes #12832.
This PR fixes an error for `Style/ArgumentsForwarding` when using block arg in nested method definitions.
=> [Fix #12832] Fix an error for `Style/ArgumentsForwarding`

Gemfile, lib/rubocop/cop/badge.rb, lib/rubocop/cop/registry.rb, spec/rubocop/comment_config_spec.rb
The fix for #12836 will be improved.
This issue is related to the development dependency rubocop-rspec_rails, and modifying RuboCop's production code was not appropriate. The version will be locked in the Gemfile until a correction can be made to rubocop-rspec_rails.
=> Workaround for rubocop-rspec_rails 2.28

changelog/fix_false_negatives_for_lint_unreachable_loop.md, lib/rubocop/cop/lint/unreachable_loop.rb, spec/rubocop/cop/lint/unreachable_loop_spec.rb
This PR fixes false negatives for `Lint/UnreachableLoop` when using pattern matching.
=> Fix false negatives for `Lint/UnreachableLoop`

changelog/fix_an_error_for_lint_mixed_case_range.md, lib/rubocop/cop/lint/mixed_case_range.rb, spec/rubocop/cop/lint/mixed_case_range_spec.rb
Fixes #12843.
This PR fixes an error for `Lint/MixedCaseRange` when a character between `Z` and `a` is used in the regexp range.
=> [Fix #12843] Fix an error for `Lint/MixedCaseRange`

changelog/fix_global_offenses_directive_comments.md, lib/rubocop/cop/base.rb, spec/rubocop/cli_spec.rb
Fix #12835
`Naming/FileName` now returns global offenses but there are quite a few projects that disable the cop with a comment, see https://github.com/search?q=%22rubocop%3Adisable+Naming%2FFileName%22&type=code. The change to global offenses in #12802 broke that behaviour.
While this is technically a new feature I classify this as a bugfix to restore previous behaviour.
=> [Fix #12835] Allow global offenses to be disabled by directive comments

changelog/fix_an_error_for_rubocop_lockfile.md, lib/rubocop/lockfile.rb
Fixes #12846.
This PR fixes an error for `RuboCop::Lockfile` when there is no Bundler environment.
From a performance perspective as well, resolving through `require 'bundler'` is not optimal. This PR ensures that the necessary `Bundler::LockfileParser` exists as a constant. This approach reduces unnecessary loading caused by `require 'bundler'` and ensures the presence of the essential `Bundler::LockfileParser`.
=> [Fix #12846] Fix an error for `RuboCop::Lockfile`

changelog/fix_error_for_lint_empty_file_with_cache.md, lib/rubocop/cached_data.rb, spec/rubocop/result_cache_spec.rb
Closes #12852.
A global offense goes into the cache but a range comes out. This results in errors when trying to display this range because begin/end at 0 is not valid. The global offense structure handles this, which is why only the second run will fail.
=> [Fix #12852] Correctly deserialize a global offense

Gemfile
This is a workaround for incompatibilities between Prism 0.25.0 and 0.26.0. To upgrade to Prism 0.26+, it is necessary to investigate the following build error and provide feedback to Prism: https://github.com/rubocop/rubocop/actions/runs/8748485587/job/24008584735?pr=12855
I will proceed with these separately.
=> Workaround for incompatibilities between Prism 0.25.0 and 0.26.0

changelog/change_set_custom_program_name_for_the_builtin_lsp_server.md, docs/modules/ROOT/pages/usage/lsp.adoc, lib/rubocop/lsp/server.rb
This PR sets custom program name for the built-in LSP server.
Before:
```console
$ ps aux | grep rubocop
user  17414  0.0  0.2  5557716 144376  ??  Ss  4:48PM  0:02.13 /Users/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/rubocop --lsp
```
After:
```console
$ ps aux | grep 'rubocop'
user  17414  0.0  0.2  5557716 144376  ??  Ss  4:48PM  0:02.13 rubocop --lsp /Users/user/src/github.com/rubocop/rubocop
```
When searching for the LSP server process, it is helpful to display the path to the project root instead of the Ruby command path. This approach is already being implemented in server mode: https://github.com/rubocop/rubocop/blob/v1.63.2/lib/rubocop/server/core.rb#L31
[1]: …
=> Set custom program name for the built-in LSP server

changelog/fix_error_for_rubocop_lockfile.md, lib/rubocop/lockfile.rb
Fixes #12848.
This PR fixes an error that occurs in `RuboCop::Lockfile` when the constant Bundler is uninitialized.
=> [Fix #12848] Fix an error for `RuboCop::Lockfile`

changelog/fix_an_incorrect_autocorrect_for_lint_unreachable_code.md, lib/rubocop/cop/lint/unreachable_code.rb, spec/rubocop/cop/lint/unreachable_code_spec.rb
This PR fixes false negatives for `Lint/UnreachableCode` when using pattern matching.
=> Fix false negatives for `Lint/UnreachableCode`

lib/rubocop/runner.rb, spec/rubocop/runner_spec.rb
This PR tweaks the infinite loop error message.
The single-line, monochromatic error message will be separated into error and hint sections, with each section color-coded to enhance visibility.
=> Tweak the infinite loop error message

lib/rubocop/options.rb, spec/rubocop/options_spec.rb
While looking at the output from the command `rubocop -h`, I noticed that the description of 3 options had a missing period at the end of the line, while all the other descriptions had one.
This PR adds those 3 missing periods :)
=> Add missing periods on CLI options descriptions

changelog/fix_handling_of_text_document_diagnostic.md, lib/rubocop/lsp/routes.rb, spec/rubocop/lsp/server_spec.rb
The `textDocument` parameter for the `textDocument/diagnostic` request is of type `TextDocumentIdentifier`, which has a single property `uri` of type `DocumentUri`.
Ref: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_diagnostic
According to the spec the `DocumentUri` type does not hold the contents of the document, which the handler currently relies on in order to publish diagnostics to the client.
This breaks the LSP mode in Neovim 0.10, which now supports pull diagnostics, and possibly other editors too. The same problem exists in `standardrb` (https://github.com/standardrb/standard/issues/575)
I have made the `textDocument/diagnostic` hander a no-op, since diagnostics are already being pushed to clients on …
=> Fix handling of textDocument/diagnostic

changelog/fix_false_positive_for_style_redundant_line_continuation.md, lib/rubocop/cop/style/redundant_line_continuation.rb, spec/rubocop/cop/style/redundant_line_continuation_spec.rb
Fixes #12862.
This PR fixes a false positive for `Style/RedundantLineContinuation` when line continuations involve `return` with a return value.
=> [Fix #12862] Fix a false positive for `Style/RedundantLineContinuation`

changelog/fix_rails_cops_outside_bundler_exec.md, lib/rubocop/lockfile.rb
Closes #12865
This PR improves upon #12826, which tried to `require 'bundler'` if it's available, we we reverted after #12846.
The issue _wasn't_ the attempt to require Bundler. It was that we were calling `Bundler.default_lockfile`, which raises `Bundler::GemfileNotFound` when you're in a folder with no `Gemfile.lock`.
I can't test this right now, so this is just "blind coding". Can you try it out, @AmShaegar13
=> [Fix #12865] `require 'bundler'` if possible and rescue `Bundler::GemfileNotFound`

changelog/fix_error_for_rubocop_cli.md, lib/rubocop/version.rb, spec/rubocop/cli/options_spec.rb
The config file is allowed to include ERB syntax which was being parsed as YAML as is without being resolved.
Uses `Util.silence_warnings` to supress the potential warnings from `check_duplication`. 
=> Fix an error for `rubocop -V` when `.rubocop.yml` contains ERB

changelog/fix_an_error_for_metrics_block_length.md, lib/rubocop/cop/metrics/utils/code_length_calculator.rb, spec/rubocop/cop/metrics/block_length_spec.rb, spec/rubocop/cop/metrics/utils/code_length_calculator_spec.rb
Fixes #12873.
This PR fixes an error for `Metrics/BlockLength` when the `CountAsOne` config is invalid.
Without the `-d` option, the cause is unclear:
```console
$ bundle exec rubocop --only Metrics/BlockLength
An error occurred while Metrics/BlockLength cop was inspecting /Users/koic/src/github.com/koic/rubocop-issues/12873/example.rb:2:2.
.
An error occurred while Metrics/BlockLength cop was inspecting /Users/koic/src/github.com/koic/rubocop-issues/12873/example.rb:2:2.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop/rubocop/issues
Mention the following information in the issue report: …
```
=> [Fix #12873] Fix an error for `Metrics/BlockLength`

changelog/fix_an_error_for_layout_first_array_element_indentation.md, lib/rubocop/cop/layout/first_array_element_indentation.rb, spec/rubocop/cli/autocorrect_spec.rb
Fixes https://github.com/standardrb/standard/issues/517#issuecomment-2084274653.
This PR fixes an infinite loop error for `Layout/FirstArgumentIndentation` when specifying `EnforcedStyle: with_fixed_indentation` of `Layout/ArrayAlignment`.
=> Fix an infinite loop error for `Layout/FirstArgumentIndentation`

docs/modules/ROOT/pages/usage/lsp.adoc, lib/rubocop/lsp/routes.rb
This PR adds documentation on enabling YJIT for LSP client to the LSP documentation. It also includes an update to display whether YJIT is enabled or not during LSP startup.
Although it has not been measured, due to its nature as a server, there is a potential for improved execution efficiency with YJIT.
=> Add documentation and log information for enabling YJIT in LSP

changelog/fix_autocorrect_for_numeric_predicate_and_negations.md, lib/rubocop/cop/style/numeric_predicate.rb, spec/rubocop/cop/style/numeric_predicate_spec.rb
When using `Style/NumericPredicate` cop with `EnforcedStyle: comparison` and having some negations, rubocop suggests invalid autocorrections. 
For example:
```ruby
!foo.zero?
!foo == 0
foo != 0
```
In this PR, I did the simplest change possible to just wrap the autocorrected code in the parentheses and it is assumed then after this other cops will convert it from `!(foo == 0)` to something like `foo != 0`. Which is actually the case.
=> Fix incorrect autocorrect when `Style/NumericPredicate` is used with negations

changelog/fix_fix_layout_comment_indentation_for_comment_only.md, lib/rubocop/cop/layout/comment_indentation.rb, spec/rubocop/cop/layout/comment_indentation_spec.rb
I'd like to allow the following code which uses pattern matching:
```ruby
case instruction
in :nop
in :inc
ret += 1
end
```
Before this patch, the indentation of "do nothing" comment is corrected to the same indent level as that of `in`, which is inconsistent with the indentation rule of `case ... when ... end`.
```console
$ ruby --version
ruby 3.3.1 (2024-04-23 revision c56cd86388) [x86_64-linux]
$ bundle show rubocop
/home/nek/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/rubocop-1.63.4
$ cat test.rb
case instruction
in :nop
in :inc
ret += 1
end
$ bundle exec rubocop test.rb --only Layout/CommentIndentation
C
Offenses:
test.rb:3:3: C: [Correctable] Layout/CommentIndentation: Incorrect indentation detected (column 2 instead of 0).
^^^^^^^^^^^^
1 file inspected, 1 …
```
=> Fix `Layout/CommentIndentation` for comment-only pattern matching

lib/rubocop/cop/style/special_global_vars.rb
The code block is currently empty and moved to the top (above the safety section), I assume because of the bad indentation. https://docs.rubocop.org/rubocop/cops_style.html#enforcedstyle-use_builtin_english_names
I didn't figure out how to build the docs locally. So this is a speculative fix on my part.
=> Fix docs for `Style/SpecialGlobalVars` `use_builtin_english_names`

lib/rubocop/cli.rb
This PR suppresses the following backtrace of `Interrupt` exception for LSP:
```console
$ bundle exec rubocop --lsp
^C/Users/koic/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/language_server-protocol-3.17.0.3/
lib/language_server/protocol/transport/io/reader.rb:16:in 'IO#gets': Interrupt
from /Users/koic/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/language_server-protocol-3.17.0.3/
lib/language_server/protocol/transport/io/reader.rb:16:in 'LanguageServer::Protocol::Transport::Io::Reader#read'
from /Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/lsp/server.rb:35:in 'RuboCop::LSP::Server#start'
(snip)
```
```console
$ bundle exec rubocop --lsp
^C
Exiting...
```
[1]: …
=> Suppress `Interrupt` exception for LSP

changelog/fix_a_false_positive_for_style_copyright.md, lib/rubocop/cop/style/copyright.rb, spec/rubocop/cop/style/copyright_spec.rb
Fixes #7189.
This PR fixes a false positive for `Style/Copyright` when using multiline copyright notice.
=> [Fix #7189] Fix a false positive for `Style/Copyright`

changelog/fix_false_positives_for_style_map_into_array.md, lib/rubocop/cop/style/map_into_array.rb, spec/rubocop/cop/style/map_into_array_spec.rb
Fixes #12894.
This PR fixes false positives for `Style/MapIntoArray` when using `each` without receiver with `<<` to build an array.
=> [Fix #12894] Fix false positives for `Style/MapIntoArray`

changelog/fix_target_rails_version_for_prereleases.md, lib/rubocop/config.rb, spec/rubocop/config_spec.rb
`canonical_segments` removes trailing zeroes, which is also why there's this `fetch(1, 0)`.
```rb
Gem::Version.new("7.0.0").canonical_segments
=> [7]
Gem::Version.new("8.0.0.alpha").canonical_segments
=> [8, "alpha"]
```
The `segments` method seems to do exactly what we want:
```rb
Gem::Version.new("7.0.0").segments
=> [7, 0, 0]
Gem::Version.new("8.0.0.alpha").segments
=> [8, 0, 0, "alpha"]
```
Taking the first two entries will always work.
-------
I've started adding some tests for this since there were absolutely none here beforehand. I understand that this rails-specific stuff should eventually be moved to `rubocop-rails`, but until then lets ensure everything works as expected.
[1]: …
=> [Fix #12898] Fix parsing of `TargetRailsVersion` for prerelases

changelog/fix_lockfile_parser_without_lockfile.md, lib/rubocop/lockfile.rb, spec/rubocop/lockfile_spec.rb
Fixes #12876
If a gemfile exists a lockfile path will be returned, even if no lockfile exists.
=> [Fix #12876] Fix lockfile parsing if only the gemfile exists

changelog/fix_no_exclude_limit_max.md, lib/rubocop/formatter/disabled_config_formatter.rb, spec/rubocop/cli/auto_gen_config_spec.rb
Fixes #12888. Basically, the problem here was a missing `no_exclude_limit?` when deciding if `Max` should be set. Factored out into its own method because of Metrics cops.
=> [Fix #12888] Fix `--no-exclude-limit` for cops with `Max` config option

lib/rubocop/lsp/routes.rb, spec/rubocop/lsp/server_spec.rb
Follow up https://github.com/standardrb/standard/pull/627.
=> LSP: Don't advertise support for Pull Diagnostics

changelog/change_support_active_support_extensions_enabled_for_style_symbol_proc.md, config/default.yml, lib/rubocop/cop/metrics/utils/code_length_calculator.rb, lib/rubocop/cop/style/symbol_proc.rb, spec/rubocop/cop/style/symbol_proc_spec.rb
Follow up https://github.com/rubocop/rubocop/commit/d39f07376d7928f7b6ee1df12cdba086cb552e5e.
This PR supports `AllCops:ActiveSupportExtensionsEnabled` instead of a TODO comment in `Style/SymbolProc` cop.
=> Support `AllCops:ActiveSupportExtensionsEnabled` for `Style/SymbolProc`

changelog/change_update_workspace_execute_command_lsp_method.md, docs/modules/ROOT/pages/configuration.adoc, docs/modules/ROOT/pages/usage/lsp.adoc, lib/rubocop/lsp.rb, lib/rubocop/lsp/routes.rb, spec/rubocop/lsp/server_spec.rb, spec/rubocop/lsp_spec.rb
Context: https://github.com/Shopify/ruby-lsp/pull/1453#issuecomment-1980179500
The `workspace/executeCommand` is an LSP method triggered by intentional user actions, so the user's intention for autocorrection is respected.
It has not yet been implemented in RuboCop's built-in LSP, but the same could be said for `textDocument/codeAction` LSP method, which might be implemented in the future.
This change slightly alters the behavior of `AutoCorrect: contextual` when using LSP (or the `--editor-mode` option), and this has been documented accordingly.
=> Respect user's intentions with `workspace/executeCommand` LSP method

changelog/change_add_back_rubocop_rspec_to_suggested_extensions.md, changelog/changelog/change_add_back_rubocop_rspec_to_suggested_extensions.md, config/default.yml
rubocop-rspec_rails provides rspec-rails specific cops, but generic rspec cops still apply, as rspec-rails depends on rspec (core, expectations and mocks)
This partially reverts #12813 
Also see https://github.com/rubocop/rubocop-rspec_rails/issues/28
=> Also suggest rubocop-rspec for those using rspec-rails

Gemfile, spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb, spec/rubocop/cop/layout/line_length_spec.rb
This PR usees the latest Prism for development.
Tests that fail due to Prism use `broken_on: :prism` to indicate unresolved issues. This clarifies which tests have issues caused by Prism.
=> Use the latest Prism for development

changelog/fix_false_negative_for_layout_empty_comment.md, lib/rubocop/cop/layout/empty_comment.rb, spec/rubocop/cop/layout/empty_comment_spec.rb
This PR fixes a false negative for `Layout/EmptyComment` when using an empty comment next to code after comment line.
=> Fix a false negative for `Layout/EmptyComment`

changelog/change_allow_cop_documentation_url_to_take_config.md, lib/rubocop/cli/command/show_docs_url.rb, lib/rubocop/cop/base.rb, lib/rubocop/cop/documentation.rb, spec/rubocop/cli/options_spec.rb, spec/rubocop/cop/cop_spec.rb
Fix #12884 (almost). It requires passing in a config object but that seems ok to require.
The current implementation is not very useful to consumers since it requires every extension to overwrite this method.
No official extension currenty does that.
The behaviour of `--show-docs-url` is almost what's required. It takes a config to construct this url and returns correct results for all official extensions.
The url it provides falls back to the default RuboCop docs url which is undesirable in all cases I can think about. That behaviour has been removed. No 3rd-party extension cops will be found on the RuboCop docs website. Only buildin cops will be found there.
All extensions that provide `DocumentationBaseURL` will now have result returned by `documentation_url` without needing to do …
=> [Fix #12884] Allow `cop_class.documentation_url` to take a config

changelog/new_support_allowed_methods_for_style_documentation_method.md, config/default.yml, lib/rubocop/cop/style/documentation_method.rb, spec/rubocop/cop/style/documentation_method_spec.rb
Fixes #11585.
This PR supports `AllowedMethods` for `Style/DocumentationMethod`.
=> [Fix #11585] Support `AllowedMethods` for `Style/DocumentationMethod`

spec/spec_helper.rb
These implementations are now identical since at least https://github.com/tmm1/test-queue/pull/124
> /home/user/Documents/rubocop/spec/spec_helper.rb:73: warning: method redefined; discarding old failure_count
/home/user/rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/test-queue-0.11.1/lib/test_queue/runner/rspec_ext.rb:4: warning: previous definition of failure_count was here
https://github.com/tmm1/test-queue/blob/e1674e1ec49e76cbbf68d83d2bc03aef83ce4e68/lib/test_queue/runner/rspec_ext.rb#L5
=> Remove redundant method overwrite in spec_helper

changelog/new_suggest_correct_formatter_name.md, lib/rubocop/formatter/formatter_set.rb, spec/rubocop/cli/options_spec.rb
This PR suggests correct formatter name when wrong similar format name is specified.
```console
$ bundle exec rubocop --format=quite
No formatter for "quite"
(snip)
```
```console
$ bundle exec rubocop --format=quite
Formatter "quite" not formatter. Did you mean? "quiet"
(snip)
```
=> Suggest correct formatter name

spec/rubocop/cop/layout/end_of_line_spec.rb, spec/rubocop/cop/style/word_array_spec.rb, spec/rubocop/result_cache_spec.rb, spec/support/encoding_helper.rb, tasks/spec_runner.rake
Just setting this is enough to emit a warning:
> warning: setting Encoding.default_internal
Use helpers to set internal/external encoding for the duration of a block without emitting these warnings.
Part of #12910
=> Remove warnings during tests when overwriting encoding

changelog/new_add_new_consistent_either.md, config/default.yml, lib/rubocop/cop/mixin/hash_shorthand_syntax.rb, lib/rubocop/cop/style/hash_syntax.rb, spec/rubocop/cli/auto_gen_config_spec.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
Related to feature request: https://github.com/rubocop/rubocop/issues/11436
Based on: https://github.com/rubocop/rubocop/pull/10776
This commit adds a new `consistent_either` option to `EnforcedShorthandSyntax` in `Style/HashSyntax`.
This allows to use both explicit and shorthand syntax, similarly to existing `either` option, but with the difference that it enforces consistency within a single hash.
This PR extends existing `consistent` option, and skips the `no_mixed_shorthand_syntax_check` offences when all values in the hash are ommitable.
```diff
@example EnforcedShorthandSyntax: consistent_either
+  # good - `foo` and `bar` values can be omitted, but they are consistent, so it's accepted
+ {foo: foo, bar: bar}
-  # bad - `bar` value can be omitted
-  {foo:, bar: bar}
-  # bad - mixed …
```
=> [Fix #11436] Add new `consistent_either` `SupportedShorthandSyntax` to `Style/HashSyntax`

changelog/fix_false_negatives_for_style_arguments_forwarding.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
Fixes #12919.
This PR fixes false negatives for `Style/ArgumentsForwarding` when forward target is `super`.
=> [Fix #12919] Fix false negatives for `Style/ArgumentsForwarding`

changelog/new_support_allow_modifiers_on_attrs_option_for_style_access_modifier_declarations.md, config/default.yml, lib/rubocop/cop/style/access_modifier_declarations.rb, spec/rubocop/cop/style/access_modifier_declarations_spec.rb
Fixes #12242
This PR supports `AllowModifiersOnAttrs` options for `Style/AccessModifierDeclarations`.
=> [Fix #12242] Support `AllowModifiersOnAttrs` option for `Style/AccessModifierDeclarations`

changelog/fix_false_positives_for_style_send_with_literal_method_name.md, lib/rubocop/cop/style/send_with_literal_method_name.rb, spec/rubocop/cop/style/send_with_literal_method_name_spec.rb
Fixes #12924.
This PR fixes false positives for `Style/SendWithLiteralMethodName` when `public_send` argument is a method name that cannot be autocorrected.
=> [Fix #12924] Fix false positives for `Style/SendWithLiteralMethodName`

changelog/fix_false_positives_for_style_redundant_line_continuation.md, lib/rubocop/cop/style/redundant_line_continuation.rb, spec/rubocop/cop/style/redundant_line_continuation_spec.rb
Fixes #12931.
This PR fixes false positives for `Style/RedundantLineContinuation` when line continuations involve `break`, `next`, or `yield` with a return value.
=> [Fix #12931] Fix false positives for `Style/RedundantLineContinuation`

lib/rubocop/cop/force.rb, lib/rubocop/cop/team.rb, spec/rubocop/cop/team_spec.rb
When a cop errors during a force callback, the following message would be logged:
> An error occurred while VariableForce cop was inspecting
This is not very helpful to figure out what is going on. Catch this error and package the cop into it so that it can later be unpacked to show the cop that is erroring.
Before:
```
An error occurred while VariableForce cop was inspecting /home/earlopain/Documents/rubocop/test.rb.
I'm broken!
/home/earlopain/Documents/rubocop/lib/rubocop/cop/lint/shadowed_argument.rb:77:in `after_leaving_scope'
/home/earlopain/Documents/rubocop/lib/rubocop/cop/force.rb:34:in `public_send'
...
```
After:
```
An error occurred while Lint/ShadowedArgument cop was inspecting /home/earlopain/Documents/rubocop/test.rb.
I'm broken! …
```
=> Fix error message when exception occurs during force callback

lib/rubocop/cop/lint/erb_new_arguments.rb
For #12910. Always passing the format argument warns since the first message takes no arguments. 
=> Avoid a ruby warning in `Lint/ErbNewArguments`

lib/rubocop/cop/layout/space_inside_string_interpolation.rb, spec/rubocop/cop/layout/space_inside_string_interpolation_spec.rb
Also for #12910. `space_offenses`/`no_space_offenses` expect a command format argument. This necessitates a change to the offense message.
This aligns the message with with `SpaceInsideArrayLiteralBrackets` and `SpaceInsideReferenceBrackets` which also use the space_offenses methods.
---------
Last warning coming from RuboCop itself. This does change the offense message text, though I think this is not expected to be stable? Let me know if this is not an acceptable change and I'll think about solving this differently.
=> Avoid a ruby warning in `Layout/SpaceInsideStringInterpolation`

changelog/fix_false_positive_for_super_arguments.md, lib/rubocop/cop/style/super_arguments.rb, spec/rubocop/cop/style/super_arguments_spec.rb
Fixes #12926. The following snippet demonstrates the issue:
```rb
class A
def positional_arg(a)
puts a
end
def block_arg(&block)
yield
end
end
class B < A
def positional_arg(a = nil)
a = 'b'
super
end
def block_arg(&block)
block = proc { puts 'b' }
super
end
end
B.new.positional_arg('a')
B.new.positional_arg
B.new.block_arg { puts 'a' }
B.new.block_arg
```
Modifying a methods block argument passes along the original block to `super`.
This fix is overly defensive and will miss some cases that could be autocorrected. This however would make this very complicated:
```rb
def foo(&blk)
super
blk = proc {} # Technically fine
end
```
The same goes for nested method definitions
[1]: …
=> [Fix #12926] Fix false positive for `Style/SuperArguments`

changelog/fix_end_position_of_diagnostic_for_lsp.md, lib/rubocop/lsp/routes.rb, spec/rubocop/lsp/server_spec.rb
I noticed that the diagnostics were always one character short when using vscode-rubocop, so I fixed it.
`character` of `Position` is zero-based
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#position
> Character offset on a line in a document (zero-based).
And, `Parser::Source::Range` is also zero-based
https://github.com/whitequark/parser/blob/3e260d2e37bcb3de8705489d1c2799c26c7a2215/lib/parser/source/range.rb#L104
> zero-based column number of the end of this range.
Therefore, `-1` is not necessary.
<details>
<summary>rubocop output json</summary>
demo.rb
```rb
require "rubocop"
class Foo
def foo
variable = 1
b = 2
end
end
```
```console
$ bundle exec rubocop -f json demo.rb 2>/dev/null | jq
```
```json
{
"metadata": {
"rubocop_version": …
```
=> Fix end position of diagnostic for LSP

.circleci/config.yml, .github/workflows/rubocop.yml
Working towards https://github.com/rubocop/rubocop/issues/8363
I'll do this in smaller steps since the workflow is somewhat large. Should be overall rather simple, though the codeclimate integration will need some extra work.
Newly added job output: https://github.com/rubocop/rubocop/actions/runs/9273549841/job/25513896170?pr=12941
------------------
Question: Is CodeClimate even still in use? The badges in the readme show some stats but the link gives 404.
=> Move `documentation-check` to GitHub actions

.circleci/config.yml, .github/workflows/rubocop.yml
The only thing left after this are the "normal" specs.
Unfortunatly GitHub doesn't support yml anchors so the matrix is duplicated. There are ways to have the matrix generated/reusable but that results in complex/unreadable actions from my experience. This ain't so bad, CircleCI didn't use/have matrix, you win some you loose some.
---------------
I'm moving the jruby job to the different jobs. I don't see why Jurby should have its own section instead of being part of the matrix. This also should speed up green CI by a bit. JRuby does take the longest and now it can execute these in parallel if there are enough available workers.
=> Move `ascii_spec`, `internal_investigation` to GitHub actions

spec/spec_helper.rb, spec/support/strict_warnings.rb
Closes #12910
This is inspired by how Rails approaches this. Depending on if https://github.com/whitequark/parser/pull/1013 gets merged or not, the `SUPPRESSED_WARNINGS` can be emptied in the future.
I also disable this when running on nightly/rc ruby. Recently there has been a bit of movement on warning regarding unused block args and that got dialed back a bit since they were very frequent. CI should not fail because ruby introduces new warnings, these can be fixed later and shouldn't bother other contributors.
=> Ensure RuboCop runs warning-free

.github/workflows/rubocop.yml
GitHub actions can run 4 workers at once. There's also no need to explicitly set this variable as these are all vms. I presume that CircleCI reported a value too high.
Also a good chance to see what the coverage upload is up to now.
=> Slightly speed up CI runs

.github/workflows/rubocop.yml
Fixes #12949, this uses the configured secret (https://github.com/rubocop/rubocop/issues/12949#issuecomment-2139496033) instead of the hardcoded value which probably hasn't worked for quite some time.
As secrets are not available to forks the job will be skipped for this PR but it should hopefully work once merged. I tested both scenarios in my fork and that went ok. cc @bquorning
=> [Fix #12949] Use the secret for the coverage reporter id

changelog/fix_an_error_for_style_copyright.md, lib/rubocop/cop/style/copyright.rb, spec/rubocop/cop/style/copyright_spec.rb
This PR fixes the following error for `Style/Copyright` when `AutocorrectNotice` is missing:
```console
$ cat .rubocop.yml
Style/Copyright:
Enabled: true
AutocorrectNotice: ~
$ bundle exec rubocop -d
(snip)
undefined method 'empty?' for nil
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/copyright.rb:61:
in 'RuboCop::Cop::Style::Copyright#verify_autocorrect_notice!'
```
=> Fix an error for `Style/Copyright`

docs/modules/ROOT/pages/cops_lint.adoc
Remove unintended indent in the doc of  `Lint/ShadowingOuterLocalVariable` to show the code block as expected
https://docs.rubocop.org/rubocop/cops_lint.html#lintshadowingouterlocalvariable 
=> Fix asciidoc syntax

changelog/fix_a_false_negative_for_style_arguments_forwarding.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
Fixes #12954.
This PR fixes a false negative for `Style/ArgumentsForwarding` when arguments forwarding in `yield`.
=> [Fix #12954] Fix a false negative for `Style/ArgumentsForwarding`

changelog/fix_false_positives_for_lint_nested_method_definition.md, lib/rubocop/cop/lint/nested_method_definition.rb, spec/rubocop/cop/lint/nested_method_definition_spec.rb
Fixes #12960.
This PR fixes false positives for `Lint/NestedMethodDefinition` when definition of method on variable.
Since method definitions using local variables such as `def obj.y` have already been accepted, the decision is to similarly accept method definitions using other variable types: https://github.com/rubocop/rubocop/blob/v1.64.1/spec/rubocop/cop/lint/nested_method_definition_spec.rb#L80-L89
=> [Fix #12960] Fix false positives for `Lint/NestedMethodDefinition`

.github/workflows/linting.yml, .github/workflows/rubocop.yml
As per https://github.com/rubocop/rubocop/pull/12947#issuecomment-2147256882
This also fixes an issue with that PR where rubocop would only lint itself when a yaml file got changed. I only noticed this after opening this file, the diff unfortunately didn't make that very visible. I've copied the conditions for the main workflow file which means yaml will be linted every time now, that seems fine. cc @bquorning
=> Ci lint once / actually run `internal_investigation`

changelog/fix_false_positives_for_style_super_arguments.md, lib/rubocop/cop/style/super_arguments.rb, spec/rubocop/cop/style/super_arguments_spec.rb
Fixes #12957.
This PR fixes false positives for `Style/SuperArguments` when calling super in a block.
Using zero arity `super` within a `define_method` block results in `RuntimeError`:
```ruby
def m
define_method(:foo) { super() } # => OK
end
def m
define_method(:foo) { super }   # => RuntimeError
end
```
Furthermore, any arguments accompanied by a block may potentially be delegating to `define_method`, therefore, `super` used within these blocks will be allowed. This approach might result in false negatives, yet ensuring safe detection takes precedence.
=> [Fix #12957] Fix false positives for `Style/SuperArguments`

.github/workflows/linting.yml
Fixing the configuration for linting.yml on CI.
Currently CI is failing ([e.g. here](https://github.com/rubocop/rubocop/actions/runs/9366635974)) with
```
Invalid workflow file: .github/workflows/linting.yml#L15
The workflow is not valid. .github/workflows/linting.yml (Line: 15, Col: 5): Required property is missing: runs-on
```
=> CI: Fix config for linting.yml

.github/workflows/rubocop.yml
Three commits:
1. Split specs running on ubuntu and windows.
We'll have some duplication, but it allows for some optimization.
2. Reduce some test matrixes
Reduce the test matrix for ascii_spec from 13 combinations to just four, and for windows specs from six to three.
Based on discussion in https://github.com/rubocop/rubocop/pull/12967#discussion_r1626082395 and https://github.com/rubocop/rubocop/pull/12965#issuecomment-2147419092.
3. Only run windows specs after ubuntu specs pass.
We don't _require_ windows specs to pass, and windows specs are very slow. By only running them _after_ ubuntu specs pass, we get the most important results first - and in case of failing specs, we'll save 30 minutes of CI use.
=> CI: Optimize for faster results and lower resource use

.github/workflows/rubocop.yml
It was actually like that before all the CI restructuring but I moved it into the matrix to speed things up a bit by separating out the individual rake tasks (`ìnternal_investigation`, `spec`, `ascii_spec`) but now having it there is actually a bother since windows specs wait on completion of it (about 4 minutes)
I specified the version as `jruby` instead of `jruby-9.4` to keep the theme of always getting the latest stable version.
=> CI: Run JRuby job outside of spec-ubuntu

changelog/change_add_count_blocks_to_metrics_block_nesting.md, config/default.yml, lib/rubocop/cop/metrics/block_nesting.rb, spec/rubocop/cop/metrics/block_nesting_spec.rb
Resolves #12970.
This PR adds `CountModifierForms` option to `Metrics/BlockNesting`.
Similar to the existing `CountBlocks`, the default is `false`. This means that existing modifier form code will not be detected by default, but this seems reasonable as part of the block nesting functionality. If user require the previous behavior, user can achieve it by setting `CountBlocks` to `true`.
=> [Fix #12970] Add `CountModifierForms` option to `Metrics/BlockNesting`

Gemfile, spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb, spec/rubocop/cop/layout/line_length_spec.rb
The tests are being updated to use Prism 0.30.0+. For future purposes, `broken_on: :prism` is intentionally left in the spec_helper.rb.
=> Run tests with Prism 0.30.0+

spec/rubocop/cop/layout/case_indentation_spec.rb, spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb, spec/rubocop/cop/layout/hash_alignment_spec.rb, spec/rubocop/cop/layout/multiline_operation_indentation_spec.rb, spec/rubocop/cop/layout/space_around_keyword_spec.rb, spec/rubocop/cop/lint/ambiguous_operator_precedence_spec.rb, spec/rubocop/cop/style/empty_case_condition_spec.rb, spec/rubocop/cop/style/explicit_block_argument_spec.rb, spec/rubocop/cop/style/guard_clause_spec.rb, spec/rubocop/cop/style/infinite_loop_spec.rb, spec/rubocop/cop/style/map_compact_with_conditional_block_spec.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb, spec/rubocop/cop/style/one_line_conditional_spec.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb, spec/rubocop/cop/style/safe_navigation_spec.rb, spec/rubocop/cop/style/single_line_methods_spec.rb, spec/rubocop/cop/style/ternary_parentheses_spec.rb
Most of these got disabled in #12822
It is however rather important that these cases parse since some extensions rely on parsing code line by line. This is the case when extracting code from a templating language like erb or haml
Prism was changed to allow these cases in https://github.com/ruby/prism/pull/2741
`packwerk` ran into issue: https://github.com/Shopify/packwerk/issues/400
`syntax_tree-erb` as well: https://github.com/davidwessman/syntax_tree-erb/issues/81
I myself observed the same in `rubocop-erb`
=> Enable a bunch of tests for prism

changelog/fix_false_negatives_for_lint_void.md, lib/rubocop/cop/lint/void.rb, spec/rubocop/cop/lint/void_spec.rb
Fixes #12979.
This PR fixes false negatives for `Lint/Void` when void expression with guard clause is not on last line.
=> [Fix #12979] Fix false negatives for `Lint/Void`

changelog/fix_false_positives_for_style_send_with_literal_method_name.md, lib/rubocop/cop/style/send_with_literal_method_name.rb, spec/rubocop/cop/style/send_with_literal_method_name_spec.rb
Fixes #12983.
This PR fixes false positives for `Style/SendWithLiteralMethodName` using `send` with writer method name.
Writer methods with names ending in `=` are always permitted because their behavior differs as follows:
```ruby
def foo=(foo)
@foo = foo
42
end
foo(1)         # => 1
send(:foo=, 1) # => 42
```
=> [Fix #12983] Fix false positives for `Style/SendWithLiteralMethodName`

changelog/fix_error_for_inherit_gem_without_gemfile.md, lib/rubocop/config_loader_resolver.rb, spec/rubocop/config_loader_spec.rb
Fixes #12975
https://github.com/rubocop/rubocop/blob/10d115f168ac61e07a3715ef3b72eb4c7518bf6e/lib/rubocop/lockfile.rb#L3-L10 Bundler may be loaded because the LockFile parsers needs it.
With the improvement to the isolated environment, 4 tests fail. Previously they operated on the gemfile from the project folder.
The two autogen tests relied on modified env, which now is not visible anymore.
-------
This uses `Bundler.with_unbundled_env` because bundler adds some variables that would otherwise make this hard to test. `Bundler.reset!` is needed because a bunch of paths are memoized which would cause bundler to always return the Gemfile path of the rubocop folder instead of the tempfile/pwd. I added a test for that. …
=> [Fix #12975] Fix an error for `gem_config_path` when bundler is loaded and no Gemfile exists

changelog/fix_an_error_for_style_redundant_regexp_character_class.md, lib/rubocop/ext/regexp_parser.rb, rubocop.gemspec
Fixes #12985.
This PR fixes an error for `Style/RedundantRegexpCharacterClass` when using regexp_parser gem 2.3.1 or older. This issue has already been resolved in regexp_parser gem 2.4.
In the past, there was an issue with compatibility with regexp_parser 1.x due to the following:
https://github.com/rubocop-hq/rubocop/pull/9102#issuecomment-737487246
Currently, many dependent gems including Capybara have permitted upgrading to regexp_parser 2.x:
https://rubygems.org/gems/regexp_parser/reverse_dependencies
Therefore, it would be a good time to specify `spec.runtime_dependency` as regexp_parser 2.4+.
=> [Fix #12985] Fix an error for `Style/RedundantRegexpCharacterClass`

changelog/fix_a_false_positive_for_style_redundant_begin.md, lib/rubocop/cop/style/redundant_begin.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
Fixes #12986.
This PR fixes a false positive for `Style/RedundantBegin` when endless method definition with `rescue`.
=> [Fix #12986] Fix a false positive for `Style/RedundantBegin`

changelog/fix_error_for_inherit_gem_git_gem.md, lib/rubocop/config_loader_resolver.rb, lib/rubocop/rspec/shared_contexts.rb, lib/rubocop/rspec/support.rb, spec/isolated_environment_spec.rb, spec/rubocop/config_loader_spec.rb
Fixes #12989
I also move the bundler isolation into the shared context and add a test for it
=> [Fix #12989] Fix an error for the `inherit_gem` config when the Gemfile contains an uninstalled git gem

lib/rubocop/cops_documentation_generator.rb
Anchors are not generated correctly for cops containing two or more slashes.
For example, if you select `Capybara/RSpec/PredicateMatcher` from the link below, the anchor is not working.
https://github.com/rubocop/rubocop-capybara/blob/2e9e33a1feffab0c36f489387afa307a04318a66/docs/modules/ROOT/pages/cops.adoc
I have fixed it so that it does not matter how many slashes there are.
=> Fix anchor if it contains two or more slashes

changelog/fix_error_for_lint_unmodified_reduce_accumulator.md, lib/rubocop/cop/lint/unmodified_reduce_accumulator.rb, spec/rubocop/cop/lint/unmodified_reduce_accumulator_spec.rb
=> Fix an error for `Lint/UnmodifiedReduceAccumulator` when the block is empty

Gemfile
This is a workaround to prevent the following warning in YARD:
```console
$ ruby -v
ruby 3.4.0dev (2024-06-14T03:14:32Z master 2677ab1607) [x86_64-darwin23]
$ cd path/to/rubocop
$ bundle exec rake
/Users/koic/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/yard-0.9.36/lib/yard/logging.rb:3:
warning: logger was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.5.0.
Add logger to your Gemfile or gemspec.
```
The fundamental resolution will likely be addressed in https://github.com/lsegal/yard/pull/1546.
=> Workaround for Ruby's warning in YARD

changelog/fix_false_negatives_for_lint_void_cop.md, lib/rubocop/cop/lint/void.rb, spec/rubocop/cop/lint/void_spec.rb
Fixes #12716.
This PR fixes false negatives for `Lint/Void` when using parenthesized void operators.
=> [Fix #12716] Fix false negatives for `Lint/Void`

spec/rubocop/cli_spec.rb
This is a workaround to prevent the following error in 3.4.0dev CI matrix:
```console
==> Failures
1) RuboCop::CLI profiling creates memory profile file
Got 3 failures from failure aggregation block.
(snip)
*.1) Failure/Error: expect(cli.run(['--profile', '--memory', 'example1.rb'])).to eq(0)
expected: 0
got: 2
(compared using ==)
*.2) Failure/Error: expect($stdout.string.include?('Building memory report...')).to be(true)
expected true
got false
*.3) Failure/Error: expect(File).to exist(memory_profile)
expected File to exist
```
https://github.com/rubocop/rubocop/actions/runs/9542192514/job/26296594698
It is necessary to investigate and resolve the error that occurred with Ruby 3.4-dev in #12999 separately. …
=> Workaround for Ruby's 3.4.0dev CI matrix error

spec/project_spec.rb
Check that if text in backticks is encountered and that text looks like a cop name, that the cops department is specified.
Not specifically for this repo but something I saw in `rubocop-rails`:
* https://github.com/rubocop/rubocop-rails/blob/02597007171ab3913a3559f9b8052f691759e4de/changelog/change_where_range_unsafe_autocorrect.md
* https://github.com/rubocop/rubocop-rails/blob/02597007171ab3913a3559f9b8052f691759e4de/changelog/fix_change_column_null_in_bulk_change_table.md
* https://github.com/rubocop/rubocop-rails/blob/02597007171ab3913a3559f9b8052f691759e4de/changelog/fix_where_range_complex_expressions.md
* https://github.com/rubocop/rubocop-rails/blob/02597007171ab3913a3559f9b8052f691759e4de/changelog/fix_where_range_spaces.md
It doesn't run the same checks on changelog as this does …
=> Add a spec for the changelog that cops in backticks have a department

changelog/change_make_style_map_compact_with_conditional_block_aware_of_filter_map.md, lib/rubocop/cop/style/map_compact_with_conditional_block.rb, spec/rubocop/cop/style/map_compact_with_conditional_block_spec.rb
Fixes #12616
This PR makes `Style/MapCompactWithConditionalBlock` aware of `filter_map`.
=> [Fix #12616] Make `Style/MapCompactWithConditionalBlock` aware of `filter_map`

spec/rubocop/config_spec.rb, spec/rubocop/cop/cop_spec.rb, spec/rubocop/cop/lint/redundant_cop_disable_directive_spec.rb, spec/rubocop/formatter/disabled_config_formatter_spec.rb, spec/rubocop/formatter/formatter_set_spec.rb, spec/rubocop/options_spec.rb, spec/rubocop/rake_task_spec.rb, spec/rubocop/result_cache_spec.rb, spec/rubocop/target_finder_spec.rb
The only places in tests that still write to these do so to reset the output
=> Consistently use the console mock helper in tests

changelog/fix_false_negatives_for_style_zero_length_predicate.md, lib/rubocop/cop/style/zero_length_predicate.rb, spec/rubocop/cop/style/zero_length_predicate_spec.rb
Fixes #12471.
This PR fixes false negatives for `Style/ZeroLengthPredicate` when using safe navigation operator.
=> [Fix #12471] Fix false negatives for `Style/ZeroLengthPredicate`

changelog/fix_false_positives_for_style_hash_except.md, lib/rubocop/cop/style/hash_except.rb, spec/rubocop/cop/style/hash_except_spec.rb
Fixes #13012.
This PR fixes false positives for `Style/HashExcept` when using `reject` and calling `include?` method with bang.
As the regression tests, the incorrect existing tests are being corrected.
=> [Fix #13012] Fix false positives for `Style/HashExcept`

changelog/fix_a_false_positive_for_style_method_call_with_args_parentheses.md, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
Fixes #13018.
This PR fixes a false positive for `Style/MethodCallWithArgsParentheses` when `EnforcedStyle: omit_parentheses` is set and parenthesized method call is used before constant resolution.
=> [Fix #13018] Fix a false positive for `Style/MethodCallWithArgsParentheses`

Gemfile, spec/rubocop/cli_spec.rb
https://github.com/rubocop/rubocop/pull/13002
https://github.com/SamSaffron/memory_profiler/pull/118
This causes issues in CI since it accidentally added a dependency on base64. The next release will fix that error
=> Ignore latest `memory_profiler` version

changelog/fix_an_error_for_style_super_arguments.md, lib/rubocop/cop/style/super_arguments.rb, spec/rubocop/cop/style/super_arguments_spec.rb
Fixes #13010.
This PR fixes an error for `Style/SuperArguments` when the hash argument is or-assigned.
=> [Fix #13010] Fix an error for `Style/SuperArguments`

changelog/fix_an_error_for_style_symbol_proc.md, lib/rubocop/cop/style/symbol_proc.rb, spec/rubocop/cop/style/symbol_proc_spec.rb
Fixes #13023.
This PR fixes an error for `Style/SymbolProc` when using lambda `->` with one argument and multiline `do`...`end` block.
=> [Fix #13023] Fix an error for `Style/SymbolProc`

changelog/change_make_server_mode_aware-of_auto_restart_for_bundle_update.md, docs/modules/ROOT/pages/usage/server.adoc, lib/rubocop/server/cache.rb, lib/rubocop/server/client_command/exec.rb, lib/rubocop/server/client_command/start.rb, spec/rubocop/server/rubocop_server_spec.rb
Resolves #12557.
Currently, the server mode only auto-restarts due to incompatible versions of RuboCop core. This PR will enable auto-restart when the SHA1 value of Gemfile.lock becomes incompatible. If Gemfile.lock is missing, it will continue to refer to the RuboCop core version as before.
The advantage is that it can cover cases of version incompatibility caused by `bundle update`, which will likely cover many scenarios like those in #12557.
The disadvantage is that the server mode may become slightly slower. However, it is unlikely to be slow enough for users to notice. The trade-off is considered acceptable.
In the future, it might be possible to detect changes in rubocop configuration as well, but for now, I'd like to see how things go with this change.
Before …
=> [Fix #12557] Make server mode aware of auto-restart for `bundle update`

changelog/fix_a_false_positive_for_lint_to_enum_arguments.md, lib/rubocop/cop/lint/to_enum_arguments.rb, spec/rubocop/cop/lint/to_enum_arguments_spec.rb
Fixes #12885.
This PR fixes a false positive for `Lint/ToEnumArguments` when enumerator is created for another method.
=> [Fix #12885] Fix a false positive for `Lint/ToEnumArguments`

changelog/new_add_new_gemspec_add_runtime_dependency_cop.md, config/default.yml, lib/rubocop.rb, lib/rubocop/cop/gemspec/add_runtime_dependency.rb, rubocop.gemspec, spec/rubocop/cop/gemspec/add_runtime_dependency_spec.rb
Follow up https://github.com/rubygems/rubygems/issues/7799#issuecomment-2192720316.
Prefer `add_dependency` over `add_runtime_dependency` as the latter is considered soft-deprecated.
```ruby
spec.add_runtime_dependency('rubocop')
end
spec.add_dependency('rubocop')
end
```
https://github.com/rubocop/ruby-style-guide/pull/943 has been opened for the Style Guide.
=> Add new `Gemspec/AddRuntimeDependency` cop

changelog/change_display_warning_messages_for_deprecated_api.md, lib/rubocop/config_loader.rb, lib/rubocop/cop/cop.rb, lib/rubocop/cop/legacy/corrector.rb, lib/rubocop/cop/mixin/alignment.rb, lib/rubocop/cop/mixin/allowed_methods.rb, lib/rubocop/cop/mixin/allowed_pattern.rb, lib/rubocop/cop/mixin/configurable_max.rb, lib/rubocop/cop/mixin/rescue_node.rb, lib/rubocop/cop/team.rb, lib/rubocop/cop/util.rb, spec/support/strict_warnings.rb
This PR displays warning messages for deprecated APIs.
The deprecated APIs are only soft-deprecated as explicitly mentioned in the documentation. Over three years have passed since RuboCop 1.0 was released: https://rubygems.org/gems/rubocop/versions/1.0.0
So it seems appropriate to start displaying deprecation warnings.
This aims to prepare for RuboCop 2.0 by providing users with the opportunity to become aware of the deprecated APIs and encouraging them to take action to avoid deprecated APIs.
=> Display warning messages for deprecated APIs

changelog/change_enable_yjit_by_default_in_server_mode.md, lib/rubocop/server/core.rb
YJIT tends to increase memory consumption as a trade-off for speed, but `--server` mode is usually used to speed up the execution of `rubocop` command locally. This patch is based on the hypothesis that it is acceptable to always enable YJIT by default in server mode to prioritize performance.
Therefore, this patch doesn't provide an option to disable YJIT in server mode. Whether this is truly necessary can be considered based on user feedback.
=> Enable YJIT by default in server mode

changelog/fix_a_false_positive_for_layout_space_around_operators.md, lib/rubocop/cop/layout/space_around_operators.rb, spec/rubocop/cop/layout/space_around_operators_spec.rb
Fixes #13033.
This PR fixes a false positive for `Layout/SpaceAroundOperators` when using multiple spaces between an operator and a tailing comment.
=> [Fix #13033] Fix a false positive for `Layout/SpaceAroundOperators`

changelog/change_support_autocorrect_for_lint_implicit_string_concatenation.md, lib/rubocop/cop/lint/implicit_string_concatenation.rb, spec/rubocop/cop/lint/implicit_string_concatenation_spec.rb
Resolves #13035.
This PR supports autocorrect for `Lint/ImplicitStringConcatenation`.
=> [Fix #13035] Support autocorrect for `Lint/ImplicitStringConcatenation`

lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/9178/files#r537218932
This PR tweaks autocorrection for `Style/SoleNestedConditional` to more appropriately add parentheses to method calls when arguments are present.
No changelog entry will be added due to the minor update to autocorrection.
=> Tweak autocorrect for `Style/SoleNestedConditional`

lib/rubocop/cop/cop.rb
This PR changes to use the `support_autocorrect?` class method instead of the `support_autocorrent?` instance method. A warning message was added in #13032 when using the `support_autocorrect?` instance method. This PR addresses the remaining codes that were missed.
When executing rubocop commad, show the following warning message
```
/bundle/ruby/3.3.0/gems/rubocop-1.65.0/lib/rubocop/cop/cop.rb:73: warning: `support_autocorrect?` is deprecated. Use `cop.class.support_autocorrect?`.
```
=> Use `support_autocorrect?` class method instead of the instance method

changelog/fix_an_error_for_lint_float_comparison.md, lib/rubocop/cop/lint/float_comparison.rb, spec/rubocop/cop/lint/float_comparison_spec.rb
Fixes #13051.
This PR fixes an error for `Lint/FloatComparison`
when comparing with rational literal.
NOTE: Using https://github.com/rubocop/rubocop-ast/pull/304 in the future will allow for a more fundamental resolution of the issue.
=> [Fix #13051] Fix an error for `Lint/FloatComparison`

changelog/fix_false_negatives_for_lint_implicit_string_concatenation.md, lib/rubocop/cop/lint/implicit_string_concatenation.rb, spec/rubocop/cop/lint/implicit_string_concatenation_spec.rb
Fixes #13044.
This PR fixes false negatives for `Lint/ImplicitStringConcatenation` when using adjacent string interpolation literals on the same line.
=> [Fix #13044] Fix false negatives for `Lint/ImplicitStringConcatenation`

changelog/fix_an_error_for_lint_useless_assignment_cop.md, lib/rubocop/cop/lint/useless_assignment.rb, spec/rubocop/cop/lint/useless_assignment_spec.rb
Fixes #13065.
This PR fixes an error for `Lint/UselessAssignment` when same name variables are assigned using chained assignment.
=> [Fix #13065] Fix an error for `Lint/UselessAssignment`

lib/rubocop/cop/style/redundant_regexp_escape.rb, lib/rubocop/ext/regexp_node.rb
The version got bumped in https://github.com/rubocop/rubocop/pull/12987
=> Drop `regexp_parser` < 2.0 compatibility code

.github/workflows/rubocop.yml, Gemfile
"Recent" simplecov versions have issues with the codeclimate reporter. To fix this:
* Bump to at least 0.20 (https://github.com/codeclimate/test-reporter/issues/413#issuecomment-1079155787)
* Use the new json formatter by setting `CC_TEST_REPORTER_ID`
* Use the produced coverage file instead of the internal `.resultset.json`
Coverage upload will not run here in this PR but I confirmed in my fork that this works: https://github.com/Earlopain/rubocop/actions/runs/10112313435/job/27966211379?pr=5
=> Bump `simplecov`

changelog/fix_explicitly_load_fileutils_before_calculating.md, lib/rubocop.rb
Related:
- https://github.com/rubocop/rubocop/issues/11438
- https://github.com/rubocop/rubocop/pull/11676
=> [Fix #11438] Explicitly load `fileutils` before calculating `before_us`

.simplecov
Now that simplecov >= 0.18 is unblocked, this can be enabled.
=> Enable branch coverage

changelog/fix_false_positive_zero_length_predicate.md, lib/rubocop/cop/style/zero_length_predicate.rb, spec/rubocop/cop/style/zero_length_predicate_spec.rb
Follow up to #13009.
Currently, the cop suggests changing `foo&.size&.>(0)` to `!foo&.empty?`. But this is not correct, because when `foo` is `nil`, original version returned `nil`, while the new version now returns `true` 😱 Imagine using this in a condition.
=> Fix a false positive for `Style/ZeroLengthPredicate` when using safe navigation and non-zero comparison

changelog/fix_incorrect_autocorrect_for_naming_rescued_exceptions_variable_name.md, lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb, spec/rubocop/cop/naming/rescued_exceptions_variable_name_spec.rb
Fixes #13076.
This PR fixes an incorrect autocorrect for `Naming/RescuedExceptionsVariableName` when using `error` for an omitted hash value.
=> [Fix #13076] Fix an incorrect autocorrect for `Naming/RescuedExceptionsVariableName`

changelog/new_config_validator_for_naming_predicate_name.md, lib/rubocop/cop/naming/predicate_name.rb, spec/rubocop/cli_spec.rb
- Remove references to autocorrect (it does not autocorrect)
- Add some more examples
=> Clarify docs in `Naming/PredicateName`

changelog/fix_false_positive_for_style_global_std_stream.md, lib/rubocop/cop/style/global_std_stream.rb, spec/rubocop/cop/style/global_std_stream_spec.rb
I also added a test for redundant constant base since that currently works and I almost accidentally broke that.
=> Fix false positive for `Style/GlobalStdStream` for namespaced constants

changelog/new_documentation_extension.md, config/default.yml, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop/cop/documentation.rb, spec/rubocop/cop/cop_spec.rb
The `rubocop-sorbet` extension hosts its documentation on GitHub in markdown format. This allows this extension to also benefit from providing documentation urls through RuboCop. It follows all the conventions that rubocop expects here, except for the file extension. GitHub doesn't render html files inline (for obvious reasons).
Documentation is available here as md: https://github.com/Shopify/rubocop-sorbet/blob/main/manual/cops_sorbet.md
=> Add new `DocumentationFormat` to serve documentation with extensions different than `html`

changelog/fix_false_positive_for_style_empty_else.md, lib/rubocop/cop/style/empty_else.rb, spec/rubocop/cop/style/empty_else_spec.rb
Fixes #13085.
This PR fixes a false positive for `Style/EmptyElse` when a comment-only `else` is used after `elsif` and `AllowComments: true` is set.
=> [Fix #13085] Fix a false positive for `Style/EmptyElse`

changelog/fix_autocorrect_for_style_multiple_comparison.md, lib/rubocop/cop/style/multiple_comparison.rb, spec/rubocop/cop/style/multiple_comparison_spec.rb
I caught an edge case for `Style/MultipleComparison` cop, when we have an expression with more comparisons that is followed by an expression with less comparisons.
```ruby
x = 1
x == 1 || x == 2 || x == 3  # <=== more comparisons
x == 1 || x == 2            # <=== less comparisons
```
Is corrected to
```ruby
x = 1
[1, 2, 3].include?(x)
[1, 2, 3, 1, 2, 3, 1, 2].include?(x)
```
But should be
```ruby
x = 1
[1, 2, 3].include?(x)
[1, 2].include?(x)
```
=> Fix an incorrect autocorrect for `Style/MultipleComparison` when statement with more comparisons precedes a statement with less comparisons

lib/rubocop/rspec/shared_contexts.rb
`RuboCop::Cop::Cop` is already deprecated:
https://github.com/rubocop/rubocop/blob/v1.65.1/lib/rubocop/cop/cop.rb#L8-L10
It should not be recommended in exception message.
=> Tweak an exception message of `RSpec.shared_context` for development

changelog/change_require_rubocop_ast_1_32_0_to_use_rubocop_ast_rational_api.md, lib/rubocop/cop/lint/float_comparison.rb, rubocop.gemspec
Follow up https://github.com/rubocop/rubocop-ast/pull/304
This PR requires RuboCop AST 1.32.0+ to use `RuboCop::AST::RationalNode` instead of workaround logic.
=> Require RuboCop AST 1.32.0+ to use `RuboCop::AST::RationalNode`

changelog/fix_an_incorrect_autocorrect_for_style_empty_line_between_defs.md, lib/rubocop/cop/layout/empty_line_between_defs.rb, spec/rubocop/cop/layout/empty_line_between_defs_spec.rb
This PR fixes the following incorrect autocorrect for `Layout/EmptyLineBetweenDefs` when two method definitions are on the same line separated by a semicolon:
```console
def a
end;def b
end
$ bundle exec rubocop --only Layout/EmptyLineBetweenDefs -a
```
It results in an autocorrection of the syntax error:
```ruby
def a
end;d
ef b
end
```
No syntax errors:
```ruby
def a
end;
def b
end
```
=> Fix an incorrect autocorrect for `Layout/EmptyLineBetweenDefs`

changelog/fix_an_error_for_lint_implicit_string_concatenation.md, lib/rubocop/cop/lint/implicit_string_concatenation.rb, spec/rubocop/cop/lint/implicit_string_concatenation_spec.rb
Fixes #13093.
This PR fixes an error for `Lint/ImplicitStringConcatenation` when implicitly concatenating a string literal with a line break and string interpolation.
=> [Fix #13093] Fix an error for `Lint/ImplicitStringConcatenation`

changelog/fix_an_error_for_style_in_pattern_then.md, lib/rubocop/cop/style/in_pattern_then.rb, spec/rubocop/cop/style/in_pattern_then_spec.rb
Fixes #13097.
This PR fixes an error for `Style/InPatternThen` when using alternative pattern matching deeply.
=> [Fix #13097] Fix an error for `Style/InPatternThen`

changelog/fix_an_error_for_style_identical_conditional_branches.md, lib/rubocop/cop/style/identical_conditional_branches.rb, spec/rubocop/cop/style/identical_conditional_branches_spec.rb
Fixes #13098.
This PR fixes an error for `Style/IdenticalConditionalBranches` when handling empty case branches.
=> [Fix #13098] Fix an error for `Style/IdenticalConditionalBranches`

changelog/fix_error_for_lint_implicit_string_concatenation.md, lib/rubocop/cop/lint/implicit_string_concatenation.rb, spec/rubocop/cop/lint/implicit_string_concatenation_spec.rb
Fixes #13107.
This PR fixes an error for `Lint/ImplicitStringConcatenation` when there are multiple adjacent string interpolation literals on the same line.
=> [Fix #13107] Fix an error for `Lint/ImplicitStringConcatenation`

changelog/fix_false_positives_for_style_arguments_forwarding.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
Fixes #13105.
This PR fixes false positives for `Style/ArgumentsForwarding` when forwarding kwargs/block arg with non-matching additional args.
=> [Fix #13105] Fix false positives for `Style/ArgumentsForwarding`

changelog/fix_error_for_style_guard_clause.md, lib/rubocop/cop/style/guard_clause.rb, spec/rubocop/cop/style/guard_clause_spec.rb
Erroring snippet:
```rb
if foo?
else
raise 'very long and detailed description of the error that makes it too long to fit on one line'
end
```
=> Fix an error for `Style/GuardClause` when if clause is empty and correction would not fit on single line

changelog/fix_ruby_version_detection_gemfile.md, lib/rubocop/target_ruby.rb, spec/rubocop/target_ruby_spec.rb
Some things going on here:
If I have a gemspec saying `target_ruby_version ">= 2.6"`, what RuboCop will actually use is 2.7 because it is the default version. All versions prior are simply discarded, even if rubocop is able to provide accurate results for these older versions.
There were tests for this but I believe that they lost what they actually were testing against during some refactor, somewhere here: #9515, #10629, and the PRs removing and reading analysis for older rubies.
This test for example used to check that the returned ruby version is 2.4 and not 2.3 which it didn't know how to analyse at one point (i.e. don't select versions below what we are currently supporting):
```rb
it 'sets target_ruby from required_ruby_version from inclusive requirement range' do
content = …
```
=> Fix detection of ruby versions through the gemfile below 2.7

changelog/fix_lockfile_parser_with_old_bundler.md, lib/rubocop/lockfile.rb
I recently found myself running rubocop against a folder with a lockfile generated with bundler v1. Bundler automatically loads the bundler version that is contained in the gemfile, even if locally you may have something more modern.
Bundler changed something between v1 and v2. In v1 `parser.dependencies` it used to return an array. Simply don't use the parser then, v2 is already 5 years old.
<details><summary>Stacktrace</summary>
<p>
```
undefined method 'values' for an instance of Array
/home/earlopain/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/rubocop-1.64.1/lib/rubocop/lockfile.rb:32:in 'RuboCop::Lockfile#dependencies'
/home/earlopain/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/rubocop-1.64.1/lib/rubocop/cli/command/suggest_extensions.rb:74:in …
```
=> Fix an error for the `Lockfile` parser when it contains incompatible `BUNDLED WITH` versions

changelog/fix_false_positive_for_style_map_into_array.md, lib/rubocop/cop/style/map_into_array.rb, spec/rubocop/cop/style/map_into_array_spec.rb
Fixes #13118
A proper correction would look something like this:
```rb
b = a.map do |x|
x
end.flatten
```
which I don't think makes much sense for this cop.
=> [Fix #13118] Fix a false positive for `Style/MapIntoArray` when splatting

changelog/fix_an_incorrect_autocorrect_for_style_if_with_semicolon.md, lib/rubocop/cop/style/if_with_semicolon.rb, spec/rubocop/cop/style/if_with_semicolon_spec.rb
This PR fixes an incorrect autocorrect for `Style/IfWithSemicolon` when a single-line `if/;/end` has an argument in the then body expression:
```ruby
if cond;do_something arg end
$ bundle exec rubocop --only `Style/IfWithSemicolon` -a
```
It results in an autocorrection of the syntax error:
```ruby
cond ? do_something arg : nil
```
No syntax errors:
```ruby
cond ? do_something(arg) : nil
```
=> Fix an incorrect autocorrect for `Style/IfWithSemicolon`

spec/project_spec.rb, spec/rubocop/cop/cop_spec.rb, spec/rubocop/cop/registry_spec.rb, spec/support/cops/same_name_in_multiple_namespace.rb
This method is deprecated and just calls through to `Registry.qualified_cop_name`. I've checked that the tests from `cop_spec` are all covered by `registry_spec`. They all are except for the last test which just doesn't make sense right now, the history is lost on me.
Also add a test for an unambiguous case. `rubocop-rspec` and `rubocop-capybara` currently define `RSpec/PredicateMatcher` and `Capybara/RSpec/PredicateMatcher`.
=> Remove duplicated `Cop.qualified_cop_name` tests

changelog/fix_false_positive_for_style_alias.md, lib/rubocop/cop/style/alias.rb, spec/rubocop/cop/style/alias_spec.rb
Fixes #13126.
This PR fixes a false positive for `Style/Alias` when using multiple `alias` in `def`.
=> [Fix #13126] Fix a false positive for `Style/Alias`

changelog/fix_false_negative_for_lint_void.md, lib/rubocop/cop/lint/void.rb, rubocop.gemspec, spec/rubocop/cop/lint/void_spec.rb
Improve `Lint/Void` to detect more void contexts:
1. Literals returned from `ensure`: the return value of `ensure` is always discarded. This is a tripping point for many devs including myself (one might easily assume that `ensure` behaves just like `rescue` and that the "ensured" value is returned.)
```ruby
def foo
bar
ensure
baz
42 # ⚠️ new offense: Literal `42` used in void context.
end
```
2. Handle void contexts in class method definitions (`defs`) and numbered parameter blocks (`numblock`):
```ruby
def self.foo=(value)
42 # ⚠️ new offense: Literal `42` used in void context.
end
```
```ruby
foo.tap do
_1 # ⚠️ new offense: Variable `_1` used in void context.
end
```
[1]: …
=> Fix false negatives in `Lint/Void` when using `ensure`, `defs` and `numblock`

changelog/fix_an_incorrect_autocorrect_for_style_trailing_body_on_method_definition.md, lib/rubocop/cop/correctors/line_break_corrector.rb, spec/rubocop/cop/style/trailing_body_on_method_definition_spec.rb
This PR fixes the following incorrect autocorrect for `Style/TrailingBodyOnMethodDefinition` when an expression precedes a method definition on the same line with a semicolon:
```console
foo;def some_method; body
end
$ rubocop --only Style/TrailingBodyOnMethodDefinition -a
```
It results in an autocorrection of the syntax error:
```ruby
foodef some_method
body
end
```
No syntax errors:
```ruby
foo;def some_method
body
end
```
=> Fix an incorrect autocorrect for `Style/TrailingBodyOnMethodDefinition`

lib/rubocop/cop/internal_affairs/empty_line_between_expect_offense_and_correction.rb, spec/rubocop/cop/internal_affairs/empty_line_between_expect_offense_and_correction_spec.rb
I mistyped and it errored. Forgot the bracket when starting the heredoc and other code was below it already
=> Fix an error for `InternalAffairs/EmptyLineBetweenExpectOffenseAndCorrection`

lib/rubocop/cop/style/format_string_token.rb, lib/rubocop/cop/style/method_call_without_args_parentheses.rb, lib/rubocop/cop/style/numeric_predicate.rb
Improve wording of `Style/NumericPredicate` docs.
=> Improve wording of various `Style/` cops documentations

README.md
The current backer/sponsor links seem outdated to what is actually shown on the site.
Relates to #13122
For example on the individuals part, someone called "Scott Ferreira" shows up in third place with ~1000$ who previously didn't show up at all. You can view the updated readme here: https://github.com/Earlopain/rubocop/tree/readme-sponsors?tab=readme-ov-file#open-collective-for-individuals
Overall it seems to mirror exactly what OpenSearch is showing:
Website:
Readme current:
Readme next:
=> Update OpenCollective readme section

changelog/fix_error_parallel_assignment.md, lib/rubocop/cop/style/parallel_assignment.rb, spec/rubocop/cop/style/parallel_assignment_spec.rb
`__FILE__` is treated as a StrNode but has no `begin`.
=> Fix an error for `Style/ParallelAssignment` when using `__FILE__`

changelog/fix_false_positives_for_style_redundant_condition.md, lib/rubocop/cop/style/redundant_condition.rb, spec/rubocop/cop/style/redundant_condition_spec.rb
Fix #13139.
This PR fixes false positives for `Style/RedundantCondition` when using modifier `if` or `unless`.
=> [Fix #13139] Fix false positives for `Style/RedundantCondition`

changelog/fix_error_target_ruby_gemspec_syntax_error.md, lib/rubocop/target_ruby.rb, spec/rubocop/target_ruby_spec.rb
Just let `Lint/Syntax` notify the user instead of raising an error.
=> Fix an error during `TargetRubyVersion` detection if the gemspec is not valid syntax

lib/rubocop/cop/internal_affairs/undefined_config.rb, spec/rubocop/cop/internal_affairs/undefined_config_spec.rb, spec/rubocop/file_finder_spec.rb
Going through the default config is fine for RuboCop itself but extensions need to inject their config for RuboCop to pick them up. This makes it necessary to load the extension, even if the extension itself doesn't make use of its own cops, like `rubocop-rails` or `rubocop-capybara`.
Instead just load `config/default.yml` from `Dir.pwd` in isolation and use just that. This would make https://github.com/rubocop/rubocop-capybara/pull/133 and https://github.com/rubocop/rubocop-rails/commit/288c7ce265d7fd0f5a244c6887224fc975ff2eb9 unnecessary. I also tested with https://github.com/rubocop/rubocop-rails/commit/9b450a8da5d5ff3fb73447a31ea09738f88dd6e4 and observed no issues with `bundle exec rake`.
Not sure how to write proper tests for this but I tested manually against most …
=> Load only project specific config for `InternalAffairs/UndefinedConfig`

changelog/new_all_cops_string_literals_frozen_by_default.md, config/default.yml, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop/config.rb, lib/rubocop/cop/base.rb, lib/rubocop/cop/mixin/frozen_string_literal.rb, lib/rubocop/cop/style/empty_literal.rb, spec/rubocop/cop/style/empty_literal_spec.rb, spec/rubocop/cop/style/redundant_freeze_spec.rb
While Ruby continues to not have this the default, user can opt into it using the `RUBYOPT` environment variable. To make RuboCop behave correctly when doing that, offer a config value to say how literals behave by default.
The most egregious cop `Style/FrozenStringLiteralComment` can already be configured appropriately by setting `EnforcedStyle` to `never`. This makes if possible to also change behaviour about cops that concern themselves with string literals (primarily `MutableConstant`).
=> [Fix #11977] Add new global `StringLiteralsFrozenByDefault` option

changelog/change_make_lint_useless_assignment_autocorrection_safe.md, config/default.yml, lib/rubocop/cop/lint/useless_assignment.rb, spec/rubocop/cli/options_spec.rb, spec/rubocop/cop/lint/useless_assignment_spec.rb
Fixes #13103.
This PR makes `Lint/UselessAssignment` autocorrection safe.
=> [Fix #13103] Make `Lint/UselessAssignment` autocorrection safe

lib/rubocop/cop/metrics/block_length.rb, lib/rubocop/cop/metrics/class_length.rb, lib/rubocop/cop/metrics/method_length.rb, lib/rubocop/cop/metrics/module_length.rb
When looking at the docs for cops that have CountAsOne, it is not immediately clear that all support `hash` as a value.
The possible values are a little hidden and the examples do not include `hash` in the configured values.
Example:
https://docs.rubocop.org/rubocop/cops_metrics.html#metricsclasslength
This change makes it so that the available values are shown on a new line. It also changes the examples to have `hash` as one of the configured values.
* ~[ ] Added tests.~ (only docs changed)
* ~[ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See …
=> Update docs to make CountAsOne values more clear.

lib/rubocop/cop/layout/line_length.rb
This PR simply adds some missing slashes `/` in the [documentation for Layout/LineLength](https://docs.rubocop.org/rubocop/cops_layout.html#layoutlinelength).
The slashes are missing after `Layout` as you can see in the screenshot below.
=> Docs: Fix missing slash for Layout/LineLength cop

changelog/fix_incorrect_autocorrect_for_lint_empty_conditional_body.md, lib/rubocop/cop/lint/empty_conditional_body.rb, spec/rubocop/cop/lint/empty_conditional_body_spec.rb
This PR fixes the following incorrect autocorrect for `Lint/EmptyConditionalBody` when missing `elsif` body with `end` on the same line.
```console
if cond_a
do_a
elsif cond_b;end
$ bundle exec rubocop -A --only Lint/EmptyConditionalBody
```
Syntax error with missing `end` keyword:
```ruby
if cond_a
do_a
```
No syntax errors:
```ruby
if cond_a
do_a
end
```
=> Fix incorrect autocorrect for `Lint/EmptyConditionalBody`

changelog/change_make_style_redundant_regexp_argument_respect_enforced_style_of_style_string_literals.md, lib/rubocop/cop/mixin/string_literals_help.rb, lib/rubocop/cop/style/empty_heredoc.rb, lib/rubocop/cop/style/empty_literal.rb, lib/rubocop/cop/style/quoted_symbols.rb, lib/rubocop/cop/style/redundant_regexp_argument.rb, spec/fixtures/html_formatter/expected.html, spec/rubocop/cop/style/redundant_regexp_argument_spec.rb
Fixes #13099.
This PR makes `Style/RedundantRegexpArgument` respect the `EnforcedStyle` of `Style/StringLiterals`. Also, combine the way to get the `EnforcedStyle` from `Style/StringLiterals` into `StringLiteralHelp`.
=> [Fix #13099] Make `Style/RedundantRegexpArgument` respect the `EnforcedStyle` of `Style/StringLiterals`

changelog/fix_server_cache_enametoolong.md, lib/rubocop/server/cache.rb
Fixes an error when the server cache directory has too long path, causing rubocop to fail even with caching disabled.
This is similar to https://github.com/rubocop/rubocop/pull/11726.
=> Don't fail cache when too long directory path

lib/rubocop/config_loader_resolver.rb, lib/rubocop/cop/mixin/line_length_help.rb, lib/rubocop/remote_config.rb, spec/rubocop/remote_config_spec.rb
> URI::RFC3986_PARSER.make_regexp is obsoleted. Use URI::RFC2396_PARSER.make_regexp explicitly
The `uri` gem is switching over its default parser from RFC 2396 to 3986. The new parser doesn't have `make_regexp` available but for compatibility a fallback was added.
Additionally, old versions of `uri` don't have the RFC2396 parser available. See https://github.com/ruby/uri/issues/118
I guess, for Ruby 3.4, `Lint/UriRegexp` needs a change because as it is now it provides bad directions.
=> Resolve ruby-head uri deprecation warning

changelog/fix_an_error_for_style_one_line_conditional.md, lib/rubocop/cop/style/one_line_conditional.rb, spec/rubocop/cop/style/one_line_conditional_spec.rb
This PR fixes the following error for `Style/OneLineConditional` when using if/then/else/end with multiple expressions in the `then` body:
```console
$ echo "if cond then x; y else z end" | bundle exec rubocop --stdin example.rb --only Style/OneLineConditional -a
F
Offenses:
example.rb:1:1: C: [Corrected] Style/OneLineConditional: Favor the ternary operator (?:) or multi-line constructs over single-line if/then/else/end constructs.
if cond then x; y else z end
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
example.rb:1:9: F: Lint/Syntax: unexpected token tSEMI
cond ? x; y : z
^
cond ? x; y : z
```
Before …
=> Fix an error for `StyleOneLineConditional`

changelog/fix_autocorrect_behavior_for_layout_block_alignment.md, lib/rubocop/cop/layout/block_alignment.rb, spec/rubocop/cop/layout/block_alignment_spec.rb
Contrary to the documentation, the autocorrect for `either` was set to `block_of_line`:
> `either` (which is the default) : the `end` is allowed to be in either
> location. The autocorrect will default to `start_of_line`.
So this PR corrects it to `start_of_line`.
=> Fix incorrect autocorrect behavior for `Layout/BlockAlignment`

changelog/change_remove_dependency_on_the_rexml_gem.md, lib/rubocop/formatter/junit_formatter.rb, rubocop.gemspec, spec/rubocop/formatter/junit_formatter_spec.rb
ReXML has been plagued by quite a few security issues recently ([1](https://www.ruby-lang.org/en/news/2024/07/16/dos-rexml-cve-2024-39908/), [2](https://www.ruby-lang.org/en/news/2024/08/01/dos-rexml-cve-2024-41123/), [3](https://www.ruby-lang.org/en/news/2024/08/01/dos-rexml-cve-2024-41946/), [4](https://www.ruby-lang.org/en/news/2024/08/22/dos-rexml-cve-2024-43398/)), all related to XML _parsing_. We don’t do any XML parsing in RuboCop, but we do do XML generation. And even that, we only do in one place: The jUnit formatter.
This PR removes our dependency on the `rexml` gem and instead builds the relatively simple XML from strings.
=> Remove dependency on the `rexml` gem

lib/rubocop/cop/team.rb, lib/rubocop/result_cache.rb
Since its inception in #7496, this never really worked despite good intentions. Because `ResultCache` instances are per-file, the instance variable supposed to do the heavy lifting just gets discarded.
Benchmarking with this change on the RuboCop repo itself yields about 100ms improvements for me with a primed cache. 3 warmup runs, 10 measured runs:
```
old:
$ hyperfine -w 3 "bundle exec rubocop"
Benchmark 1: bundle exec rubocop
Time (mean ± σ):      1.800 s ±  0.023 s    [User: 2.247 s, System: 1.050 s]
Range (min … max):    1.774 s …  1.845 s    10 runs
new:
$ hyperfine -w 3 "bundle exec rubocop"
Benchmark 1: bundle exec rubocop
Time (mean ± σ):      1.670 s ±  0.014 s    [User: 1.999 s, System: 1.040 s]
Range (min … max):    1.657 s …  1.696 s    10 runs
```
For Rails, ~3s improvement: …
=> Properly cache team checksums

Rakefile, exe/rubocop
Ruby wants to bundle it: https://github.com/ruby/ruby/pull/11492
This is pretty much all the gem does anyways (that's being used here): https://github.com/ruby/benchmark/blob/8d2c8a0d7ca72bff7e97a4800e16c72f232867e4/lib/benchmark.rb#L311-L315
I removed the `bench_cop` rake task since it uses `benchmark` and I believe it just isn't very useful. Dedicated tools like `vernier` or `stackprof` (which has buildin support in RuboCop these days) are much more suited for the task.
=> Remove `benchmark` dependency

lib/rubocop.rb, lib/rubocop/comment_config.rb, lib/rubocop/config.rb, lib/rubocop/config_validator.rb, lib/rubocop/cop/mixin/annotation_comment.rb, lib/rubocop/cop/style/magic_comment_format.rb
I'm doing performance profiling and was surprised for these to appear at all in the samples. Here are some numbers (3 warmup runs, 20 measured runs, cache used)::
```
$ hyperfine -w 3 -r 20 "bundle exec rubocop Rakefile"
Benchmark 1: bundle exec rubocop Rakefile
Time (mean ± σ):      1.169 s ±  0.016 s    [User: 0.976 s, System: 0.190 s]
Range (min … max):    1.138 s …  1.198 s    20 runs
$ hyperfine -w 3 -r 20 "bundle exec rubocop Rakefile"
Benchmark 1: bundle exec rubocop Rakefile
Time (mean ± σ):      1.145 s ±  0.011 s    [User: 0.959 s, System: 0.185 s]
Range (min … max):    1.131 s …  1.170 s    20 runs
$ hyperfine -w 3 -r 20 "bundle exec rubocop Rakefile"
Benchmark 1: bundle exec rubocop Rakefile
Time (mean ± σ):      1.136 s ±  0.020 s    [User: 0.950 s, System: 0.183 s]
Range …
```
=> Replace forwardable with explicit delegation for performance

changelog/fix_error_for_layout_empty_lines_around_exception_handling_keywords.md, lib/rubocop/cop/layout/empty_lines_around_exception_handling_keywords.rb, spec/rubocop/cop/layout/empty_lines_around_exception_handling_keywords_spec.rb
This PR fixes the following error for `Layout/EmptyLinesAroundExceptionHandlingKeywords` when `ensure` and `end` are on the same line:
```console
$ cat /tmp/example.rb
def do_something
ensure end
$ ruby -c /tmp/example.rb
Syntax OK
$ bundle exec rubocop /tmp/example.rb -a -d --only Layout/EmptyLinesAroundExceptionHandlingKeywords
(snip)
For /tmp: An error occurred while Layout/EmptyLinesAroundExceptionHandlingKeywords cop was inspecting /tmp/example.rb:1:0.
The range 28...29 is outside the bounds of the source
/Users/koic/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/parser-3.3.4.2/lib/parser/source/tree_rewriter.rb:406:
in 'Parser::Source::TreeRewriter#check_range_validity'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/corrector.rb:120:in …
```
=> Fix an error for `Layout/EmptyLinesAroundExceptionHandlingKeywords`
