rubocop/rubocop

- changelog/fix_frozen_literal_detection_in_lint_void.md
- lib/rubocop/cop/lint/void.rb
- spec/rubocop/cop/lint/void_spec.rb
Currently, `Lint/Void` looks for literals, and arrays/hashes composed of literals. However, returning a _frozen_ literal into a void context is just as pointless as returning a plain literal (and more expensive). This PR adds support for frozen literal detection.
```ruby
def foo
'hello'.freeze      # ⚠️ new offense: Literal 'hello'.freeze used in a void context
[1,2,3].freeze      # ⚠️ new offense: Literal [1,2,3].freeze used in a void context
[1, 'hello'.freeze] # ⚠️ new offense: Literal [1,'hello'.freeze] used in a void context
baz
end
```
NOTE: this isn't the same as `Style/RedundantFreeze` which doesn't detect nested structures
> Fix false negative for `Lint/Void` when using using frozen literals

- changelog/fix_false_negative_for_style_map_into_array.md
- lib/rubocop/cop/style/map_into_array.rb
- spec/rubocop/cop/style/map_into_array_spec.rb
Improve `Style/MapIntoArray` to detect cases where the destination array is initialized to an empty literal in ways other than `[]`.
```ruby
dest = []            # ✔️ currently supported
dest = Array.new     # ⚠️ new offense
dest = Array[]       # ⚠️ new offense
dest = Array([])     # ⚠️ new offense
dest = Array.new([]) # ⚠️ new offense
arr.each { |x| dest << x }
```
> Fix false negatives for `Style/MapIntoArray`

- changelog/fix_false_negatives_for_style_empty_literal.md
- lib/rubocop/cop/style/empty_literal.rb
- spec/rubocop/cli/autocorrect_spec.rb
- spec/rubocop/cop/style/empty_literal_spec.rb
Improve `Style/EmptyLiteral` to detect other common ways of creating empty literals.
```ruby
Array.new      # ✔️ existing offense
Hash.new       # ✔️ existing offense
Array[]        # ⚠️ new offense
Array([])      # ⚠️ new offense
Array.new([])  # ⚠️ new offense
Hash[]         # ⚠️ new offense
Hash([])       # ⚠️ new offense
Hash.new([])   # ⚠️ new offense
```
Also: improve offense message by including the actual offense source
> Fix false negatives for `Style/EmptyLiteral`

- changelog/change_allow_invalid_attr_name_in_naming_accessor_method_name.md
- lib/rubocop/cop/naming/accessor_method_name.rb
- spec/rubocop/cop/naming/accessor_method_name_spec.rb
Fixes #13150.
This PR allows `get_!`, `set_!`, `get_?`, `set_?`, `get_=`, and `set_=` method names in `Naming/AccessorMethodName`.
Names ending with `!`, `?`, or `=` are not appropriate as attribute names.
```console
$ ruby -e 'class X attr_reader :x! end'
-e:1:in 'Module#attr_reader': invalid attribute name 'x!' (NameError)
class X attr_reader :x! end
^^^^^^^^^^^
from -e:1:in '<class:X>'
from -e:1:in '<main>'
```
Therefore, they don't need to be recognized as intended accessor method names.
> [Fix #13150] Allow `get_!`, `set_!`, `get_?`, `set_?`, `get_=`, and `set_=` in `Naming/AccessorMethodName`

- changelog/fix_style_empty_else_without_else.md
- lib/rubocop/cop/style/empty_else.rb
- spec/rubocop/cop/style/empty_else_spec.rb
Fix for https://github.com/rubocop/rubocop/issues/13176
> Fix crash in `Style/EmptyElse` when `AllowComments: true` and the else clause is missing

- changelog/fix_false_positive_empty_literal.md
- lib/rubocop/cop/style/empty_literal.rb
- spec/rubocop/cop/style/empty_literal_spec.rb
The first parameter for Hash.new is the default value:
```rb
Hash.new([])[:foo]
```
Side note: this usage is most likely a programming error. You want the block form where different keys _don't_ share the same underlying array.
> Fix false positive for `Style/EmptyLiteral` with `Hash.new([])`

- lib/rubocop/cop/internal_affairs/node_matcher_directive.rb
- spec/rubocop/cop/internal_affairs/node_matcher_directive_spec.rb
There is code below that assumes the existance of two arguments
> Fix an error for `InternalAffairs/NodeMatcherDirective` when no second argument

- changelog/fix_style_map_into_array_autocorrect_detection.md
- lib/rubocop/cop/style/map_into_array.rb
- spec/rubocop/cop/style/map_into_array_spec.rb
Small improvement to `Style/MapIntoArray`'s autocorrection detection.
This cop can only autocorrect in a void context, and currently it only checks (kw)begin/(num)block contexts. This PR adapts some of the new logic from `Lint/Void` to expand void context detection to `ensure`, `def`, `defs`, and `for` contexts by delegating the responsibility to `rubocop-ast`.
e.g.
```ruby
def initialize
dest = []
list.each { dest << _1 } # 🆕 can now be autocorrected since it's in constructor
end
```
```ruby
def self.name=(value)
dest = []
list.each { dest << _1 } # 🆕 can now be autocorrected since it's in an assignment method
end
```
```ruby
def foo
bar
ensure
dest = []
list.each { dest << _1 } # 🆕 can now be autocorrected since ensure is always a void context
end
```
```ruby
for i in list
dest = [] …
```
> Fix false negatives in `Style/MapIntoArray` autocorrection

- lib/rubocop/comment_config.rb
- lib/rubocop/config.rb
- lib/rubocop/config_validator.rb
- lib/rubocop/cop/style/magic_comment_format.rb
- rubocop.gemspec
Introduced in https://github.com/rubocop/rubocop-ast/pull/312
Also see https://github.com/rubocop/rubocop/pull/13175
I performance tested this change and found no significant difference, which makes sense since it's basically the same thing.
This is pretty much a revert of the previous PR, changing `Forwardable` to `SimpleForwardable` (except for one class, which just didn't use it so I left that out)
cc @marcandre
> Use `rubocop-ast` `SimpleForwardable`

- lib/rubocop/config_loader.rb
- lib/rubocop/yaml_duplication_checker.rb
- spec/rubocop/config_loader_spec.rb
Once for the duplication check, and once again to convert it to a ruby hash
We can instead use the yaml ast from the duplication check and convert that into a hash directly.
```
$ hyperfine -w 5 -r 20 "bundle exec rubocop Rakefile"
Benchmark 1: bundle exec rubocop Rakefile
Time (mean ± σ):      1.041 s ±  0.014 s    [User: 0.898 s, System: 0.140 s]
Range (min … max):    1.013 s …  1.061 s    20 runs
$ hyperfine -w 5 -r 20 "bundle exec rubocop Rakefile"
Benchmark 1: bundle exec rubocop Rakefile
Time (mean ± σ):      1.013 s ±  0.008 s    [User: 0.865 s, System: 0.146 s]
Range (min … max):    0.998 s …  1.027 s    20 runs
```
~2.7%  Faster
```
$ hyperfine -w 5 -r 20 "bundle exec rubocop Rakefile"
Benchmark 1: bundle exec rubocop Rakefile
Time (mean ± σ):      3.485 s ±  0.027 s    [User: …
```
> Don't parse YAML twice

- changelog/fix_an_error_for_style_one_line_conditional.md
- lib/rubocop/cop/style/one_line_conditional.rb
- spec/rubocop/cop/style/one_line_conditional_spec.rb
This PR fixes the following error for `Style/OneLineConditional` when using nested if/then/else/end:
```console
$ echo "if cond then foo else if cond2 then bar else baz; end; end" | bundle exec rubocop --stdin dummy.rb -A --only Style/OneLineConditional -d
(snip)
An error occurred while Style/OneLineConditional cop was inspecting /Users/koic/src/github.com/rubocop/rubocop/dummy.rb:1:18.
/Users/koic/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/parser-3.3.4.2/lib/parser/source/tree_rewriter.rb:427
:in 'Parser::Source::TreeRewriter#trigger_policy'
```
> Fix an error for `Style/OneLineConditional`

- lib/rubocop/cop/internal_affairs/cop_description.rb
- lib/rubocop/cop/internal_affairs/useless_message_assertion.rb
- spec/rubocop/cop/internal_affairs/cop_description_spec.rb
- spec/rubocop/cop/internal_affairs/useless_message_assertion_spec.rb
This overwritten `relevant_file?` methods are preventing `Exclude` from working for these cops, since the behaviour is defined in the parent class `RuboCop::Cop::Base`.
You can verify this bug by applying the following patch and running `bundle exec rubocop`:
```patch
diff --git a/.rubocop_todo.yml b/.rubocop_todo.yml
index 8c0c585df..27293b8ff 100644
--- a/.rubocop_todo.yml
+++ b/.rubocop_todo.yml
@@ -10,6 +10,10 @@
InternalAffairs/NodeDestructuring:
Enabled: false
+InternalAffairs/CopDescription:
+  Exclude:
+    - 'lib/rubocop/cop/internal_affairs/cop_description.rb'
+
Metrics/ClassLength:
diff --git a/lib/rubocop/cop/internal_affairs/cop_description.rb b/lib/rubocop/cop/internal_affairs/cop_description.rb
index d5097d4d3..bf1814d90 100644
--- …
```
> Call super in `relevant_file?` for InternalAffairs cops

- changelog/fix_fix_omit_parentheses_style_for_pattern_match_with.md
- lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb
- spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
When using the `omit_parentheses` style of Style/MethodCallWithArgsParentheses, RuboCop issued offenses for the following code:
```ruby
case match
in :pattern1 then foo(value:)
in :pattern2 then bar(value:)
end
```
Dropping the parentheses, however, is a syntax error as the dangling `value:` is expecting the next line to be its value. Yup, it's one of those endless edge cases around the parentheses omission Bulgarian style we enjoy over here. 😅
> Fix omit_parentheses style for pattern match with value omission in single-line branch

- changelog/fix_wrong_autocorrect_guard_clause_heredoc.md
- lib/rubocop/cop/style/guard_clause.rb
- spec/rubocop/cop/style/guard_clause_spec.rb
The correction is a syntax error: the `end` keyword must be removed.
----
I want to add an assertion to `expect_correction` that the correction is valid syntax, but first a few more fixes to come.
> Fix wrong autocorrect for `Style/GuardClause` when using heredoc without `else` branch

- changelog/fix_wrong_autocorrect_method_call_arg_parens_omit_parens.md
- lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb
- spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
Whitespace after the line continuation character is a syntax error
>  Fix wrong autocorrect for `Style/MethodCallWithArgsParentheses` with `EnforcedStyle: omit_parentheses` and whitespace

- changelog/fix_wrong_autocorrect_lint_big_decimal_new.md
- lib/rubocop/cop/lint/big_decimal_new.rb
- spec/rubocop/cop/lint/big_decimal_new_spec.rb
`BigDecimal()` is a method defined on `Kernel`. `::BigDecimal(...)` is a syntax error
> Fix wrong autocorrect for `Lint/BigDecimalNew` when using `::BigDecimal.new`

- changelog/fix_a_false_positive_in.md
- lib/rubocop/cop/lint/parentheses_as_grouped_expression.rb
- spec/rubocop/cop/lint/parentheses_as_grouped_expression_spec.rb
The parentheses in the code below are required if you choose to call `rand` without parens:
```ruby
rand (a - b)..(c - d)
```
However, the current version of `Lint/ParenthesesAsGroupedExpression` will issue an offense for it.
> Fix a false positive in Lint/ParenthesesAsGroupedExpression with compound ranges

- changelog/fix_false_positive_arg_forwarding_ruby_3.0.md
- lib/rubocop/cop/style/arguments_forwarding.rb
- spec/rubocop/cop/style/arguments_forwarding_spec.rb
Having `...` and optional positional arguments is a syntax error in Ruyb 3.0 and lower
> Fix a false positive for `Style/ArgumentForwarding` with Ruby 3.0 and optional position arguments

- changelog/fix_autogen_config_absolute_config_path.md
- lib/rubocop/cli/command/auto_generate_config.rb
- spec/rubocop/cli/auto_gen_config_spec.rb
Rails does this in their `bin/rubocop` wrapper script. See https://github.com/rails/rails/issues/52878
> Fix `--auto-gen-config` when passing an absolute config path

- changelog/fix_false_positives_for_operator_method_call.md
- lib/rubocop/cop/style/operator_method_call.rb
- spec/rubocop/cop/style/operator_method_call_spec.rb
These cases are syntax errors as well, in addition to anonymous forwarding
> Fix false positives for `Style/OperatorMethodCall` with named forwarding

- lib/rubocop/rspec/expect_offense.rb
- spec/rubocop/cop/style/operator_method_call_spec.rb
Issues found with this:
* https://github.com/rubocop/rubocop/pull/13211
* https://github.com/rubocop/rubocop/pull/13215
* https://github.com/rubocop/rubocop/pull/13216
* https://github.com/rubocop/rubocop/pull/13219
* https://github.com/rubocop/rubocop/pull/13224
* https://github.com/rubocop/rubocop/issues/13225 (pending, couldn't figure it out)
I checked some repos in the rubocop org and they seem to not be affected by this change
> Ensure that the code for `expect_correction` is valid syntax

- changelog/fix_an_incorrect_autocorrect_for_style_arguments_forwarding.md
- lib/rubocop/cop/style/arguments_forwarding.rb
- spec/rubocop/cop/style/arguments_forwarding_spec.rb
Fixes #13220.
This PR fixes an incorrect autocorrect for `Style/ArgumentsForwarding` when using only forwarded arguments in brackets.
> [Fix #13220] Fix an incorrect autocorrect for `Style/ArgumentsForwarding`

- lib/rubocop/cop/lint/it_without_arguments_in_block.rb
Using `on_block` is expensive, since this checks each send node in a block. Instead, use `on_send`. This is much cheaper since a overwhelming majority of send nodes will not be named `it`.
From `bundle exec prof:slow_cops`
```
551  (    2.9%)  RuboCop::Cop::Layout::IndentationConsistency#on_begin
402  (    2.2%)  RuboCop::Cop::Layout::RedundantLineBreak#on_send
358  (    1.9%)  RuboCop::Cop::Lint::ItWithoutArgumentsInBlock#on_block
(snip)
```
After:
```
(103 previous entries)
42  (    0.2%)  RuboCop::Cop::Lint::ItWithoutArgumentsInBlock#on_send
(snip)
```
Overall, this saves about 200ms for the RuboCop repo.
> Improve performance of `Lint/ItWithoutArgumentsInBlock`

- changelog/fix_error_for_style_if_unless_modifier.md
- lib/rubocop/cop/mixin/statement_modifier.rb
- spec/rubocop/cop/style/if_unless_modifier_spec.rb
Fixes #13235.
This PR fixes an error for `Style/IfUnlessModifier` when multiline `if` that fits on one line and using implicit method call with hash value omission syntax.
> [Fix #13235] Fix an error for `Style/IfUnlessModifier`

- changelog/fix_fix_false_positive_for_style_collection_compact_when_using_delete_if.md
- lib/rubocop/cop/style/collection_compact.rb
- spec/rubocop/cop/style/collection_compact_spec.rb
This PR fixes `Style/CollectionCompact` to ignore `delete_if`. 
`Style/CollectionCompact` supports `delete_if` in https://github.com/rubocop/rubocop/pull/11815 and https://github.com/rubocop/rubocop/pull/12803.
but, `delete_if` always returns self, whereas `compact!` returns `nil` if no changes are made. Therefore, the two methods are not compatible.
By ignoring `delete_if`, we can prevent false positives and ensure more appropriate code style checks.
```ruby
irb(main):001> {:a => 1, :b => 2}.delete_if { |k, v| v.nil? }
=> {:a=>1, :b=>2}
irb(main):002> {:a => 1, :b => 2}.compact!
=> nil
irb(main):003> [1, 2].delete_if { |v| v.nil? }
=> [1, 2]
irb(main):004> [1, 2].compact!
=> nil
```
- [Array#delete_if](https://docs.ruby-lang.org/en/3.3/Array.html#method-i-delete_if)
- …
> Fix false positive for `Style/CollectionCompact` when using `delete_if`

- lib/rubocop/cop/internal_affairs/redundant_source_range.rb
- lib/rubocop/cop/lint/erb_new_arguments.rb
- lib/rubocop/cop/naming/predicate_name.rb
- lib/rubocop/cop/style/data_inheritance.rb
- lib/rubocop/cop/style/eval_with_location.rb
- lib/rubocop/cop/style/lambda.rb
- lib/rubocop/cop/style/multiline_memoization.rb
- lib/rubocop/cop/style/nested_parenthesized_calls.rb
- lib/rubocop/cop/style/struct_inheritance.rb
- lib/rubocop/cop/style/ternary_parentheses.rb
- spec/rubocop/cop/internal_affairs/redundant_source_range_spec.rb
This PR makes `InternalAffairs/RedundantSourceRange` aware that `source_range` is redundant in `add_offense(node.source_range)`.
> Make `InternalAffairs/RedundantSourceRange` aware of `add_offense`

- lib/rubocop/cop/base.rb
Related to https://github.com/rubocop/rubocop/pull/8882
This matters since there are quite a few public methods per cop class. In total, it gets called ~57k times, or ~104 times per cop class.
`method_defined?` is faster than string checking, so move that first. It also eliminates most of the checks, Base contains 98 methods.
Current:
```
$ hyperfine -w 10 -r 25 "bundle exec rubocop Rakefile --cache=false"
Benchmark 1: bundle exec rubocop Rakefile --cache=false
Time (mean ± σ):     932.8 ms ±   7.6 ms    [User: 828.0 ms, System: 104.0 ms]
Range (min … max):   919.5 ms … 952.2 ms    25 runs
```
With String:
```
$ hyperfine -w 10 -r 25 "bundle exec rubocop Rakefile --cache=false"
Benchmark 1: bundle exec rubocop Rakefile --cache=false
Time (mean ± σ):     924.1 ms ±   7.8 ms    [User: 816.3 …
```
> Optimize `Base.callbacks_needed` by reordering checks

- changelog/change_support_filter_filter_in_style_collection_compact.md
- lib/rubocop/cop/style/collection_compact.rb
- spec/rubocop/cop/style/collection_compact_spec.rb
This PR changes `Style/CollectionCompact` to support `filter/filter!`.
`filter/filter!` was introduced in Ruby 2.6 as an alias for `select/select!`, so I think it can be handled as the same way in this cop.
- https://docs.ruby-lang.org/en/3.3/Array.html#method-i-filter
- https://docs.ruby-lang.org/en/3.3/Hash.html#method-i-filter
> Support `filter/filter!` in `Style/CollectionCompact`

- changelog/change_deprecation_for_cop_cop_cops.md
- lib/rubocop/cop/cop.rb
- spec/rubocop/cop/cop_spec.rb
This has been long-marked as deprecated but not everyone has gotten the memo: https://github.com/search?q=%2F%3C+RuboCop%3A%3ACop%3A%3ACop%2F+lang%3Aruby+-is%3Afork&type=code
Some methods _are_ deprecated but its perfectly possible to just not use any of them.
Followup to https://github.com/rubocop/rubocop/pull/13032 and https://github.com/rubocop/rubocop/pull/13244
> Emit a deprecation when custom cops inherit from `RuboCop::Cop::Cop`

- changelog/change_enhance_autocorrect_for_naming_inclusive_language.md
- lib/rubocop/cop/naming/inclusive_language.rb
- spec/rubocop/cop/naming/inclusive_language_spec.rb
This PR enhances the autocorrect for `Naming/InclusiveLanguage` when a sole suggestion is set.
The value of `Suggestions` is an array `['an offense']`, but since it can be determined as a sole term, it is autocorrectable.
```yaml
Naming/InclusiveLanguage:
FlaggedTerms:
' a offense':
Suggestions:
- an offense
```
> Enhance the autocorrect for `Naming/InclusiveLanguage`

- lib/rubocop/cop/internal_affairs/redundant_message_argument.rb
- spec/rubocop/cop/internal_affairs/redundant_message_argument_spec.rb
The following `bad` cases cannot be replaced with the `good` case after v1 API:
```ruby
add_offense(node, message: message)
add_offense(node, message: message(node))
add_offense(node)
```
v1 API: https://docs.rubocop.org/rubocop/v1_upgrade_notes.html
As a result, there was an incorrect detection for calls like `add_offense(message: message)` where the `message` method is the value. As a workaround, a technique involving assignment to a local variable named `message` was used, but fundamentally, these cases should no longer be detected by this cop.
This PR modifies the cop to detect only `add_offense(node, message: MSG)` which can still be replaced with the good cases after v1 API.
[1]: …
> Tweak `InternalAffairs/RedundantMessageArgument` cop for v1 API

- lib/rubocop/yaml_duplication_checker.rb
The first commit is an attempt at an optimization, where I made it not traverse the yaml ast. This is not necessary since psych offers an api to get tokens as they are emitted. There must be some improvement with this change but it's not measurable. I left it in anyways since I think the code is neater with that approach. I'm not attached, I can drop that commit if you want.
---------
The second commit does improve performance: The keys array can grow quite large and checking for the existance of a key becomes expensive. The worst case scenario is also the most common one, where the key is not found. Instead, use a hash:
Current:
```
$ hyperfine -w 10 -r 25 "bundle exec rubocop Rakefile"
Benchmark 1: bundle exec rubocop Rakefile
Time (mean ± σ):     962.2 ms ±  11.4 ms    [User: 845.0 ms, …
```
> Improve yaml duplication checker performance

- changelog/change_make_server_mode_aware-of_auto_restart_for_config_update.md
- docs/modules/ROOT/pages/usage/server.adoc
- lib/rubocop/server/cache.rb
- spec/rubocop/server/rubocop_server_spec.rb
Fixes #13232.
This change was also planned in #13004. It is limited to detecting local files such as `.rubocop.yml`, but it should reduce the need to manually restart the server mode when configuration changes are detected. Since even in LSP, detection of configuration files beyond `.rubocop.yml` is not performed, it is expected to cover a reasonably practical use case.
Although the logic has increased compared to #13004, no significant speed degradation is anticipated.
Since it's unclear whether tracking dependencies between configuration files is practical, it will not be handled this, at least for now.
> [Fix #13232] Make server mode aware of auto-restart for local config update

- config/internal_affairs.yml
- lib/rubocop/cop/internal_affairs.rb
- lib/rubocop/cop/internal_affairs/cop_description.rb
- lib/rubocop/cop/internal_affairs/useless_message_assertion.rb
- spec/rubocop/cop/internal_affairs/cop_description_spec.rb
- spec/rubocop/cop/internal_affairs/useless_message_assertion_spec.rb
`InternalAffairs/CopDescription` and `InternalAffairs/UselessMessageAssertion` want to only look at a specific subset of files. To do that, they override the `relevant_file?` method.
Instead, just treat `InternalAffairs` like a RuboCop extension and inject the config so it goes through the usual processes.
There are more cops that could be added here (many only concern themselves with either specs or library code) but I'll leave that for a subsequent PR.
This removes the tests from https://github.com/rubocop/rubocop/pull/13209, the process of config inheritance is already well-tested and there nothing special here anymore. I've manually verified that this change works correctly in `rubocop-rails` and here as well of course (i.e. there are still offenses when there should be).
@splattael, …
> Ship a config for `InternalAffairs`

- changelog/fix_false_positives_for_style_access_modifier_declarations.md
- lib/rubocop/cop/style/access_modifier_declarations.rb
- spec/rubocop/cop/style/access_modifier_declarations_spec.rb
Fixes #13213.
This PR fixes false positives for `Style/AccessModifierDeclarations` when `AllowModifiersOnAttrs: true` and using splat with a percent symbol array, or with a constant.
> [Fix #13213] Fix false positives for `Style/AccessModifierDeclarations`

- changelog/fix_false_positive_redundant_safe_navigation.md
- lib/rubocop/cop/lint/redundant_safe_navigation.rb
- spec/rubocop/cop/lint/redundant_safe_navigation_spec.rb
Fix #13260
`FOO::BAR` isn't in snakecase. It should only look at the last part.
> [Fix #13260] Fix a false positive for `Lint/RedundantSafeNavigation` with namespaced constants

- docs/modules/ROOT/pages/configuration.adoc
Follow up https://github.com/rubocop/rubocop/pull/4304.
This PR tweaks the doc for `DisabledByDefault: true` in configuration.
> [Doc] Tweak the doc for `DisabledByDefault: true` in configuration

- spec/rubocop/cop/style/select_by_regexp_spec.rb
This PR refactors `style/select_by_regexp_spec` to prevent overwriting `ruby_version` within contexts.
I have split the changes into multiple commits to make the review process easier. If you prefer to squash commits, I will do so.
In `style/select_by_regexp_spec`, the `ruby_version` is being overwritten within the context of the shared_examples. As a result, the test is executed with a different `ruby_version` than the `ruby_version` specified in the caller of shared_examples.
For example, in `context 'when Ruby <= 2.2', :ruby22`, `ruby_version` 2.2 is specified, but due to a different `ruby_version` being set within the following contexts inside the shared_examples, the tests are actually being run with a different version than intended:
- …
> Refactor `style/select_by_regexp_spec` to prevent overwriting `ruby_version` within contexts

- changelog/fix_a_false_postiive_for_style_block_delimiters.md
- lib/rubocop/cop/style/block_delimiters.rb
- spec/rubocop/cop/style/block_delimiters_spec.rb
This PR fixes the following false positive for `Style/BlockDelimiters` when a single line do-end block with an inline `rescue` with a semicolon before `rescue`:
```console
$ echo "foo do next unless bar; rescue StandardError; end" | bundle exec rubocop --stdin dummy.rb -A --only Style/BlockDelimiters
F
Offenses:
dummy.rb:1:5: C: [Corrected] Style/BlockDelimiters: Prefer {...} over do...end for single-line blocks.
foo do next unless bar; rescue StandardError; end
^^
dummy.rb:1:24: F: Lint/Syntax: unexpected token kRESCUE
foo { next unless bar; rescue StandardError; }
^^^^^^
dummy.rb:1:46: F: Lint/Syntax: unexpected token tRCURLY
(Using Ruby 2.7 parser; configure using TargetRubyVersion …
```
> Fix a false positive for `Style/BlockDelimiters`

- changelog/change_make_style_select_by_regexp_aware_of_filter_in.md
- lib/rubocop/cop/style/select_by_regexp.rb
- spec/rubocop/cop/style/select_by_regexp_spec.rb
This PR makes `Style/SelectByRegexp` aware of `filter` in Ruby version 2.6 or above similar to https://github.com/rubocop/rubocop/pull/13245.
> Make `Style/SelectByRegexp` aware of `filter` in Ruby version 2.6 or above

- changelog/fix_false_positive_for_lint_ambiguous_range.md
- lib/rubocop/cop/lint/ambiguous_range.rb
- spec/rubocop/cop/lint/ambiguous_range_spec.rb
Fixes #13271.
This PR fixes a false positive for `Lint/AmbiguousRange` when using rational literals.
> [Fix #13271] Fix a false positive for `Lint/AmbiguousRange`

- changelog/change_report_and_correct_more_style_safe_navigation.md
- config/default.yml
- lib/rubocop/config_loader_resolver.rb
- lib/rubocop/cop/layout/def_end_alignment.rb
- lib/rubocop/cop/lint/safe_navigation_consistency.rb
- lib/rubocop/cop/style/safe_navigation.rb
- lib/rubocop/cop/style/trivial_accessors.rb
- lib/rubocop/cop/util.rb
- spec/rubocop/cop/style/safe_navigation_spec.rb
This change adds the ability for `Style/SafeNavigation` to detect offenses such as
```ruby
foo? && bar && bar.end_with?('baz')
```
`and` nodes nest leftward, ie. the above code becomes 
```
(and
(and
(send nil :foo?)
(send nil :bar))
(send
(send nil :bar) :end_with?
(send nil :baz)))
```
Because of this, the previously version of the cop was unable to find an offense for the above code because it was comparing `foo? && bar` with `bar.end_with?`. In order to support this, I had to greatly rewrite how `on_and` processes nodes. The new approach collects all the clauses of a (nested) `and` statement, and evaluates them in pairs. If a pair has an object detection on the LHS and a method call of that object on the RHS, it will be picked up by the cop as an offense and corrected. I also handled …
> [Fix #13256] Report and correct more `Style/SafeNavigation` offenses.

- changelog/fix_handle_custom_extractors_crash.md
- lib/rubocop/runner.rb
- spec/rubocop/runner_spec.rb
This previously only showed where the extractor was located. Now it also includes the file it was processing.
This still fully halts execution instead of continuing on with the remaining files. Making that work properly would be a bunch more work.
> [Fix #13149] Handle crashes in custom Ruby extractors more gracefully

- spec/rubocop/cop/alignment_corrector_spec.rb
- spec/support/cops/alignment_directive.rb
I'd like to get rid of the `loop` option. This test has a semi-good reason to use this option. But it's also easy not to rely on it.
Simply remove the directive comment in the correction
> Don't use `loop: false` for `AlignmentDirective` tests

- changelog/change_accessor_grouping_supports_rbs_inline_annotations.md
- lib/rubocop/cop/style/accessor_grouping.rb
- spec/rubocop/cop/style/accessor_grouping_spec.rb
[rbs-inline](https://github.com/soutaro/rbs-inline) is a utility to embed RBS type declarations into Ruby code as comments.
This avoids to group accessors having rbs-inline annotation comments in `Style/AccessorGrouping`.
refs: https://github.com/soutaro/rbs-inline/wiki/Syntax-guide
> Do not group accessors having rbs-inline annotations in `Style/AccessorGrouping`

- changelog/change_commented_keyword_allows_rbs_inline_annoattions.md
- lib/rubocop/cop/style/commented_keyword.rb
- spec/rubocop/cop/style/commented_keyword_spec.rb
[rbs-inline](https://github.com/soutaro/rbs-inline) is a utility to embed RBS type declarations into Ruby code as comments.
This allows to write rbs-inline annotation comment just after method definition in `Style/CommentedKeyword`.
refs: https://github.com/soutaro/rbs-inline/wiki/Syntax-guide
> Allow to write rbs-inline annotation after method definition in `Style/CommentedKeyword`

- changelog/new_allow_rbs_inline_annotation_option.md
- config/default.yml
- lib/rubocop/cop/layout/leading_comment_space.rb
- spec/rubocop/cop/layout/leading_comment_space_spec.rb
[rbs-inline](https://github.com/soutaro/rbs-inline) is a utility to embed RBS type declarations into Ruby code as comments.
The new option; `AllowRBSInlineAnnotation` for
`Layout/LeadingCommentSpace` allows to use rbs-inline's annotation comments in the Ruby code.
refs: https://github.com/soutaro/rbs-inline/wiki/Syntax-guide
> Add `AllowRBSInlineAnnotation` option to `Layout/LeadingCommentSpace`

- lib/rubocop/cop/style/safe_navigation.rb
- spec/rubocop/cop/style/safe_navigation_spec.rb
Small followup to #13267. Such a node doesn't have a receiver (it's a `Parser::Source::Range`:
```
(or
(send nil :x?)
(and
(send nil :z?)
(send nil :w?)))
```
```rb
foo? && (bar? || baz? && bat?)
```
cc @dvandersluis. Hope you don't mind me picking this up. The PR got merged a bit early.
No changelog, not released yet.
> Fix an error for mixed and/or in begin node for `Style/SafeNavigation`

- spec/support/strict_warnings.rb
It's OK to only print these during development for convenience. It's how rails does it as well.
> Only raise for warnings in CI

- lib/rubocop/cop/offense.rb
Pretty much every offense can be disabled through a todo comment. This method will only consider those when the user actually requested that.
At least that is how I understand this to work.
> Tweak docs for `Offense.correctable?`

- changelog/fix_false_positives_for_style_redundant_line_continuation.md
- lib/rubocop/cop/style/redundant_line_continuation.rb
- spec/rubocop/cop/style/redundant_line_continuation_spec.rb
Fixes #13145.
This PR fixes false positives for `Style/RedundantLineContinuation` when line continuations with comparison operator and the LHS is wrapped in parentheses.
> [Fix #13145] Fix false positives for `Style/RedundantLineContinuation`

- changelog/change_support_ruby34_for_lint_uri_regexp.md
- lib/rubocop/cop/lint/uri_regexp.rb
- spec/rubocop/cop/lint/uri_regexp_spec.rb
This PR supports Ruby 3.4 for `Lint/UriRegexp` to avoid the following warning:
```console
$ ruby -ruri -vwe "URI::DEFAULT_PARSER.make_regexp('http://example.com')"
ruby 3.4.0dev (2024-09-21T18:00:23Z master 9f574fa12f) +PRISM [x86_64-darwin23]
-e:1: warning: URI::RFC3986_PARSER.make_regexp is obsoleted. Use URI::RFC2396_PARSER.make_regexp explicitly.
```
> Support Ruby 3.4 for `Lint/UriRegexp`

- changelog/change_update_style_map_into_array_to_be_able_to_handle.md
- config/default.yml
- lib/rubocop/cop/style/map_into_array.rb
- spec/rubocop/cop/style/map_into_array_spec.rb
Updates `Style/MapIntoArray` to be able to handle code like:
```ruby
[].tap do |dest|
src.each { |e| dest << e ** 2 }
end
```
This only applies when an empty array is tapped, and no other code is in the tap block.
Fixes #13229.
> [Fix #13229] Update `Style/MapIntoArray` to be able to handle arrays created using `[].tap`

- Gemfile
- spec/rubocop/cop/layout/case_indentation_spec.rb
- spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb
- spec/rubocop/cop/layout/multiline_operation_indentation_spec.rb
- spec/rubocop/cop/layout/space_around_keyword_spec.rb
- spec/rubocop/cop/lint/ambiguous_operator_precedence_spec.rb
- spec/rubocop/cop/style/empty_case_condition_spec.rb
- spec/rubocop/cop/style/guard_clause_spec.rb
- spec/rubocop/cop/style/map_compact_with_conditional_block_spec.rb
- spec/rubocop/cop/style/one_line_conditional_spec.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
- spec/rubocop/cop/style/single_line_methods_spec.rb
This PR uses Prism 1.1 for development.
It has been updated in Prism 1.1 to correctly handle the following behavior of `parse.y` in Ruby 3.3 and later.
Ruby 3.3 raises a syntax error:
```console
$ ruby -cve 'next unless foo'
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-darwin23]
-e:1: Invalid next
next unless foo
ruby: compile error (SyntaxError)
```
It is valid syntax in Ruby 3.2:
```console
$ ruby -cve 'next unless foo'
ruby 3.2.4 (2024-04-23 revision af471c0e01) [x86_64-darwin23]
Syntax OK
```
It is incorrect that the Parser gem can still parse it with `--3.3` and later. I will provide feedback separately.
```console
$ ruby-parse --33 -e 'next unless foo'
(if
(send nil :foo) nil
(next))
```
[1]: …
> Use Prism 1.1 for development

- changelog/fix_an_incorrect_autocorrect_for_style_rescue_modifier.md
- lib/rubocop/cop/style/rescue_modifier.rb
- spec/rubocop/cop/style/rescue_modifier_spec.rb
Fixes #13291.
This PR fixes an incorrect autocorrect for `Style/RescueModifier` when using modifier rescue for method call with heredoc argument. The autocorrection of heredoc indentation after autocorrect will be left to other cops, such as `Layout/ClosingHeredocIndentation` and `Layout/HeredocIndentation`.
> [Fix #13291] Fix an incorrect autocorrect for `Style/RescueModifier`

- spec/rubocop/config_store_spec.rb
`Hash#inspect` is changing to use the Ruby 1.9 syntax for symbol keys (see ruby/ruby#10924).
This updates the spec to interpolate the config hash, so it implicitly works with both the old and new versions of `Hash#inspect`, fixing compatibility with Ruby HEAD.
[1]: …
> Make `ConfigStore.for` spec compatible with Ruby HEAD's new `Hash#inspect`

- changelog/fix_an_error_for_layout_access_modifier_indentation.md
- lib/rubocop/cop/layout/access_modifier_indentation.rb
- spec/rubocop/cop/layout/access_modifier_indentation_spec.rb
This PR fixes the following infinite loop error for `Layout/AccessModifierIndentation` when the access modifier is on the same line as the class definition.
```console
$ echo 'class A; private; def foo; end; end' | bundle exec rubocop --stdin dummy.rb -a --only Layout/AccessModifierIndentation
(snip)
Infinite loop detected in /Users/koic/src/github.com/rubocop/rubocop/dummy.rb and caused by Layout/AccessModifierIndentation
Hint: Please update to the latest RuboCop version if not already in use, and report a bug if the issue still occurs on this version.
Please check the latest version at https://rubygems.org/gems/rubocop.
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/runner.rb:322:in 'block in RuboCop::Runner#iterate_until_no_changes'
<internal:kernel>:191:in 'Kernel#loop'
```
In …
> Fix an error for `Layout/AccessModifierIndentation`

- changelog/fix_target_ruby_version_gemspec_name.md
- lib/rubocop/file_finder.rb
- lib/rubocop/target_ruby.rb
- spec/rubocop/file_finder_spec.rb
- spec/rubocop/target_ruby_spec.rb
As long as the folder contains only one gemspec, bundler will use it regardless of the name. For example, cloning rails (currently on 3.2 from the gemspec), renaming the folder to anything other than rails, and then running rubocop again results in 60 syntax errors since it's now failing to use the gemspec.
```
$ bundle exec rspec
[!] There was an error parsing `Gemfile`: There are no gemspecs at /home/earlopain/Documents/rubocop. Bundler cannot continue.
#
>  gemspec
#
```
```
$ bundle exec rspec
[!] There was an error parsing `Gemfile`: There are multiple gemspecs at /home/earlopain/Documents/rubocop. Please use the :name option to specify which one should be used. Bundler cannot continue.
#
>  gemspec
#
``` …
> Fix `TargetRubyVersion` from a gemspec when the gemspec is not named like the folder it is located in

- changelog/fix_wrong_autocorrect_redundant_begin_block_delims.md
- lib/rubocop/cop/style/block_delimiters.rb
- lib/rubocop/cop/style/redundant_begin.rb
- spec/rubocop/cli/autocorrect_spec.rb
Fixes #13302 / https://github.com/rubocop/rubocop/discussions/13294#discussioncomment-10866113
```rb
foo.map do |v|
begin
v.call
rescue StandardError
baz
end
end.compact
```
This previously turned into this:
```rb
foo.map { |v|
v.call
rescue StandardError
baz
}.compact
```
which is invalid syntax.
It's probably only relevant when the EnforcedStyle is set to this value but `autocorrect_incompatible_with` does not provide such granularity.
> [Fix #13302] Fix incompatible autocorrect between `Style/RedundantBegin` and `Style/BlockDelimiters` with `EnforcedStyle: braces_for_chaining`

- changelog/change_update_style_return_nil_in_predicate_method_definition.md
- config/default.yml
- lib/rubocop/cop/style/return_nil_in_predicate_method_definition.rb
- spec/rubocop/cop/style/return_nil_in_predicate_method_definition_spec.rb
While looking into #13114, I noticed another situation that should be handled by `Style/ReturnNilInPredicateMethodDefinition`.
```ruby
def foo?
if bar
true
else
nil
end
end
```
This change handles this situation.
> Update `Style/ReturnNilInPredicateMethodDefinition` to detect implicit `nil` returns inside `if`

- changelog/fix_avoid_syntax_error_when_correcting.md
- lib/rubocop/cop/style/operator_method_call.rb
- spec/rubocop/cop/style/operator_method_call_spec.rb
Previously, `foo./(bar)` was corrected to `foo /(bar)` which is a syntax error. 
This change ensures that a space is inserted for `/` operations to avoid this error.
Fixes #13225.
> [Fix #13225] Avoid syntax error when correcting `Style/OperatorMethodCall` with `/` operations followed by a parenthesized argument

- changelog/change_either_to_enforced_shorthand_syntax_for_hash_syntax.md
- config/default.yml
- lib/rubocop/cop/style/hash_syntax.rb
- spec/rubocop/cli/auto_gen_config_spec.rb
Follow up https://github.com/rubocop/rubocop/pull/10351#issuecomment-1008235461
As the current trend suggests, `EnforcedShorthandSyntax: either` seems to be a reasonable choice. Additionally, as a note from the developer, `either` was added later as an option for `EnforcedShorthandSyntax`. Had it been noticed from the beginning, it would likely have been the default. `EnforcedShorthandSyntax: always` is still maintained as an option, and users who prefer it will need to switch the setting. Rather than switching from `EnforcedShorthandSyntax: always` to the extreme of `EnforcedShorthandSyntax: never`, `EnforcedShorthandSyntax: either` leaves the choice to the user, making it a more balanced decision in that regard. …
> Set `EnforcedShorthandSyntax: either` by default for `Style/HashSyntax`

- changelog/change_add_support_in_style_arguments_forwarding_for.md
- lib/rubocop/cop/style/arguments_forwarding.rb
- spec/rubocop/cop/style/arguments_forwarding_spec.rb
Adds support to `Style/ArgumentsForwarding` for the following cases:
```ruby
def foo(*, **, &)
bar(*, **, &)
end
def foo(...)
bar(...)
end
```
```ruby
def foo(m, *, **, &)
bar(m, *, **, &)
end
def foo(m, ...)
bar(m, ...)
end
```
Fixes #13110.
> [Fix #13110] Add support in `Style/ArgumentsForwarding` for detecting forwarding of all anonymous arguments

- .github/ISSUE_TEMPLATE/bug_report.md
- CONTRIBUTING.md
- changelog/new_display_analysis_ruby_version.md
- lib/rubocop/version.rb
- spec/rubocop/cli/options_spec.rb
Fixes #13310.
This PR makes rubocop -V show the Ruby version being analyzed.
The analysis Ruby version is not displayed:
```console
$ bundle exec rubocop -V
1.66.1 (using Parser 3.3.5.0, rubocop-ast 1.32.3, running on ruby 3.3.5) [x86_64-linux]
- rubocop-performance 1.22.1
- rubocop-rspec 3.1.0
```
The analysis Ruby version is displayed:
```console
$ bundle exec rubocop -V
1.66.1 (using Parser 3.3.5.0, rubocop-ast 1.32.3, analyzing as Ruby 3.3, running on ruby 3.3.5) [x86_64-linux]
- rubocop-performance 1.22.1
- rubocop-rspec 3.1.0
```
> [Fix #13310] Display analysis Ruby version in `rubocop -V`

- changelog/fix_prevent_modifying_blocks_with.md
- lib/rubocop/cop/style/hash_each_methods.rb
- spec/rubocop/cop/style/hash_each_methods_spec.rb
If `keys.each` or `values.each` block that modifies the original hash is changed to `each_key` or `each_value`, it results in `RuntimeError: can't add a new key into hash during iteration`.
This change updates `Style/HashEachMethods` to not register an offense in these cases.
Fixes #13318.
> [Fix #13318] Prevent modifying blocks with `Style/HashEachMethods` if the hash is modified within the block

- changelog/fix_handle_literal_forward_slashes_inside_a_regexp_in.md
- lib/rubocop/cop/lint/literal_in_interpolation.rb
- spec/rubocop/cop/lint/literal_in_interpolation_spec.rb
Handle interpolation of forward slashes inside a regexp. They must be escaped or else the resulting regexp will be a syntax error.
Fixes #13319.
> [Fix #13319] Handle literal forward slashes inside a `regexp` in `Lint/LiteralInInterpolation`

- changelog/change_add_allowed_methods_to_first_method_argument_line_break.md
- config/default.yml
- lib/rubocop/cop/layout/first_method_argument_line_break.rb
- spec/rubocop/cop/layout/first_method_argument_line_break_spec.rb
Add `AllowedMethods` and `AllowedPatterns` to `Layout/FirstMethodArgumentLineBreak` allow for users to configure for methods they do not want to apply to the cop.
Fixes #13286.
> [Fix #13286] Add `AllowedMethods` and `AllowedPatterns` configuration to `Layout/FirstMethodArgumentLineBreak`

- changelog/change_refine_lint_safe_navigation_consistency.md
- config/default.yml
- lib/rubocop/cop/correctors/parentheses_corrector.rb
- lib/rubocop/cop/layout/empty_line_after_guard_clause.rb
- lib/rubocop/cop/lint/boolean_symbol.rb
- lib/rubocop/cop/lint/literal_in_interpolation.rb
- lib/rubocop/cop/lint/safe_navigation_consistency.rb
- lib/rubocop/cop/lint/symbol_conversion.rb
- lib/rubocop/cop/mixin/percent_array.rb
- lib/rubocop/cop/style/conditional_assignment.rb
- lib/rubocop/cop/style/if_inside_else.rb
- lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb
- lib/rubocop/cop/style/nested_modifier.rb
- lib/rubocop/cop/style/redundant_condition.rb
- lib/rubocop/cop/style/redundant_parentheses.rb
- lib/rubocop/cop/style/require_order.rb
- spec/rubocop/cop/lint/safe_navigation_consistency_spec.rb
Fixes #9816.
As highlighted in user feedback in #9816, the current implementation excessively requires the use of the safe navigation operator. This PR refines `Lint/SafeNavigationConsistency` cop to check that the safe navigation operator is applied consistently and without excess or deficiency.
> [Fix #9816] Refine `Lint/SafeNavigationConsistency`

- changelog/change_make_server_mode_aware_of_auto_restart_for_rubocop_todo_update.md
- docs/modules/ROOT/pages/usage/server.adoc
- lib/rubocop/server/cache.rb
- spec/rubocop/server/rubocop_server_spec.rb
Follow up #13233.
This PR makes server mode aware of auto-restart for .rubocop_todo.yml update. Similar to .rubocop.yml, updates to the default configuration file .rubocop_todo.yml can also trigger a server mode restart."
> Make server mode aware of auto-restart for .rubocop_todo.yml update

- lib/rubocop/config_validator.rb
Fix #13328
Enabled defaults to true and can always be set. So, even though a warning would be shown,
the config value still takes.
An alternative fix would be to set `Enabled: true` for the two cops in the config but at least to me, that doesn't seem necessary. I consider the warning a bug since `Enabled: false` deactivates the cop regardless.
> [Fix #13328] Declare `Enabled` as a common config key

- lib/rubocop/cops_documentation_generator.rb
Fixes #13331.
This PR fixes an error when using release task.
In Ruby 3.2 and later, this does not result in an error, but in Ruby 3.1 and earlier, the following error occurs.
```console
$ ruby -v
ruby 3.1.5p252 (2024-04-23 revision 1945f8dc0e) [x86_64-darwin23]
$ bundle exec rake cut_release:minor
Files:         687
Modules:        92 (   13 undocumented)
Classes:       649 (    4 undocumented)
Constants:    1197 ( 1181 undocumented)
Attributes:     37 (    0 undocumented)
Methods:      1504 ( 1309 undocumented)
27.94% documented
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cops_documentation_generator.rb:321:
warning: Passing only keyword arguments to Struct#initialize will behave differently from Ruby 3.2.
Please use a Hash literal like .new({k: v}) instead of .new(k: v). …
```
> [Fix #13331] Fix an error when using release task

- spec/rubocop/server/rubocop_server_spec.rb
These hashses are tied to the rubocop version, which means that a version bump will change these as well.
The first test previously passes since it relies on a changed hash, which it was always.
For the second test the hash must match when computed in the server.
Since the cache key is not cached itself, compute it again when preconditions changed instead of hardcoding it.
> Fix test failures caused by changes to the rubocop version

- changelog/fix_false_positives_for_style_redundant_line_continuation.md
- lib/rubocop/cop/style/redundant_line_continuation.rb
- spec/rubocop/cop/style/redundant_line_continuation_spec.rb
Fixes #13337.
This PR fixes false positives for `Style/RedundantLineContinuation` when a line continuation starts with `&&` and an assignment is used after a line break.
> [Fix #13337] Fix false positives for `Style/RedundantLineContinuation`

- changelog/fix_false_positves_for_lint_safe_navigation_chain.md
- lib/rubocop/cop/lint/safe_navigation_chain.rb
- spec/rubocop/cop/lint/safe_navigation_chain_spec.rb
Fixes #13341.
This PR fixes false positives for `Lint/SafeNavigationChain` when a safe navigation operator is used with a method call as the RHS operand of `&&` for the same receiver.
> [Fix #13341] Fix false positives for `Lint/SafeNavigationChain`

- changelog/fix_prevent_layout_line_length_from_breaking_up_a.md
- lib/rubocop/cop/mixin/check_line_breakable.rb
- spec/rubocop/cop/layout/line_length_spec.rb
If a method chain starting with a heredoc goes over the line length limit, breaking it onto multiple lines is a syntax error. This prevents the autocorrection that would do so.
```ruby
str = <<~HEREDOC.do_something.with_args(foo: '', bar: '', baz: '')
^^^^^^^^^^^^^^^^^^^^^^^^^^ Line is too long. [66/40]
text
HEREDOC
```
Fixes #13343.
> [Fix #13343] Prevent `Layout/LineLength` from breaking up a method with arguments chained onto a heredoc delimiter

- changelog/fix_ensure_style_block_delimiters_autocorrection_does.md
- lib/rubocop/cop/style/block_delimiters.rb
- spec/rubocop/cop/style/block_delimiters_spec.rb
When `Style/BlockDelimiters` autocorrects `{...}` to `do...end` with a trailing comment, it previously would insert a newline after the end of the `block` range, but in the cases where additional code follows on that line, it could change semantics or even cause a syntax error. This change ensures that that code is retained on the same line as the end of the block.
Fixes #13348.
> [Fix #13348] Ensure `Style/BlockDelimiters` autocorrection does not move other code between the block and comment

- changelog/fix_fix_disable_uncorrectable_to_not_insert_a_comment.md
- lib/rubocop/cop/autocorrect_logic.rb
- spec/rubocop/cli/disable_uncorrectable_spec.rb
With the following code and `--disable-uncorrectable` specified:
```ruby
{
key1: "something",
key1: "whatever"\
"something else",
}
```
Previously RuboCop corrected to a syntax error:
```ruby
{
key1: "something",
key1: "whatever"\ # rubocop:todo Lint/DuplicateHashKey
"something else",
}
```
With this correction, RuboCop uses the block form of `todo` instead:
```ruby
{
key1: 'something',
key1: 'whatever'\
'something else'
}
```
Fixes #13324.
> [Fix #13324] Fix `--disable-uncorrectable` to not insert a comment inside a string continuation

- changelog/fix_update_style_safe_navigation_to_not_autocorrect_if.md
- lib/rubocop/cop/style/safe_navigation.rb
- spec/rubocop/cop/style/safe_navigation_spec.rb
Updates `Style/SafeNavigation` to register an offense but not autocorrect code in the form
```
foo && (foo.bar? || (foo.baz? && foo.quux?))
```
Fixes #13336.
> [Fix #13336] Update `Style/SafeNavigation` to not autocorrect if the RHS of an `and` node is an `or` node

- changelog/fix_false_positive_space_before_brackets.md
- lib/rubocop/cop/layout/space_before_brackets.rb
- spec/rubocop/cop/layout/space_before_brackets_spec.rb
In addition to checking `[]`, `[]=` must also be considered. Followup to #10575
> [Fix #13356] Fix a false positive for `Layout/SpaceBeforeBrackets` when there is a dot before `[]=`

- changelog/fix_incorrect_autocorrect_for_style_block_delimiters_cop.md
- lib/rubocop/cop/layout/space_inside_block_braces.rb
- spec/rubocop/cli/autocorrect_spec.rb
Fixes #13353.
This PR fixes an incorrect autocorrect for `Style/BlockDelimiters` when `EnforcedStyle: semantic` is set and used with `Layout/SpaceInsideBlockBraces`.
> [Fix #13353] Fix an incorrect autocorrect for `Style/BlockDelimiters`

- changelog/new_allow_steep_annotation_option.md
- config/default.yml
- lib/rubocop/cop/layout/leading_comment_space.rb
- spec/rubocop/cop/layout/leading_comment_space_spec.rb
[Steep](https://github.com/soutaro/steep) is a type checker for Ruby.
The new option; `AllowSteepAnnotation` for `Layout/LeadingCommentSpace` allows to use Steep's annotation comments in the Ruby code.
refs: https://github.com/soutaro/steep/wiki/Release-Note-1.3#add-type-assertion-and-type-application-syntax
> Add AllowSteepAnnotation option to Layout/LeadingCommentSpace

- changelog/fix_interpolated_string_detection.md
- lib/rubocop/cop/mixin/frozen_string_literal.rb
- spec/rubocop/cop/style/redundant_freeze_spec.rb
- spec/rubocop/cop/style/redundant_interpolation_unfreeze_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/13361
Adds support for the (less common) variable interpolation syntax:
```ruby
"#$global_var"
"#@instance_var"
"#@@class_var"
```
> Fix false positives for `Style/RedundantInterpolationUnfreeze` and `Style/RedundantFreeze` with variable interpolation

- changelog/fix_false_negatives_for_style_map_into_array.md
- lib/rubocop/cop/style/map_into_array.rb
- spec/rubocop/cop/style/map_into_array_spec.rb
Bugfix https://github.com/rubocop/rubocop/pull/13119 fixed the splat bug in `Style/MapIntoArray`, but it also limited the types of offenses the cop recognized. For example,
```ruby
dest = []
arr.each { |e| dest << [1, e] }
arr.each { |e| dest << true }
arr.each { |e| dest << (cond? ? 1 : e) }
```
and several others are no longer detected as of 1.66.1
This PR restores the original cop behavior while preserving the splat fix.
> Fix false negatives for `Style/MapIntoArray` when using non-splatted arguments

- changelog/fix_style_multiple_comparison.md
- lib/rubocop/cop/style/multiple_comparison.rb
- spec/rubocop/cop/style/multiple_comparison_spec.rb
Fixes #13193.
Closes #13195.
In this PR I refactored the cop to not keep any internal state (via instance variables), and so the code became simpler and more bullet-proof.
> Fix false positive in `Style/MultipleComparison` when `ComparisonsThreshold` exceeds 2

- lib/rubocop/cop/metrics/cyclomatic_complexity.rb
This PR fixes the display of the broken example in the `Metrics/CyclomaticComplexity` document.
https://docs.rubocop.org/rubocop/cops_metrics.html#metricscyclomaticcomplexity
> [Doc] Fix the broken example in the `Metrics/CyclomaticComplexity` document

- changelog/fix_an_incorrect_autocorrect_for_naming_block_forwarding.md
- lib/rubocop/cop/naming/block_forwarding.rb
- spec/rubocop/cli/autocorrect_spec.rb
Fixes #13368.
This PR fixes an incorrect autocorrect for `Naming/BlockForwarding` with `Style/ExplicitBlockArgument`.
> [Fix #13368] Fix an incorrect autocorrect for `Naming/BlockForwarding`

- changelog/fix_false_positives_for_lint_safe_navigation_consistency.md
- lib/rubocop/cop/lint/safe_navigation_consistency.rb
- spec/rubocop/cop/lint/safe_navigation_consistency_spec.rb
Fixes #13365.
This PR fixes false positives for `Lint/SafeNavigationConsistency` when using safe navigation on the LHS with operator method on the RHS of `&&`.
> [Fix #13365] Fix false positives for `Lint/SafeNavigationConsistency`

- changelog/fix_fix_incorrect_autocorrect_with.md
- lib/rubocop/cop/variable_force/assignment.rb
- spec/rubocop/cop/lint/useless_assignment_spec.rb
- spec/rubocop/cop/variable_force/assignment_spec.rb
With code such as:
```ruby
a, b = func(c = 3)
[a, b]
```
`Lint/UselessAssignment` was previously considering the inner assignment (`c = 3`) to be part of the multiple assignment for autocorrection. This changes it to not consider assignment inside a method argument to be part of the containing `meta_assignment_node` for `masgn` and `for` nodes. 
Fixes #13364.
> [Fix #13364] Fix incorrect autocorrect with `Lint/UselessAssignment` a multiple assignment or `for` contains an inner assignment

- lib/rubocop.rb
- lib/rubocop/cop/correctors/alignment_corrector.rb
Followup to #13234. I encountered the following errors when running rubocop:
<details><summary>Details</summary>
<p>
```rb
An error occurred while Layout/ElseAlignment cop was inspecting /home/user/code/rubocop/lib/rubocop/runner.rb:366:8.
uninitialized constant #<Class:RuboCop::Cop::AlignmentCorrector>::StringIO
/home/user/code/rubocop/lib/rubocop/cop/correctors/alignment_corrector.rb:101:in 'RuboCop::Cop::AlignmentCorrector.remove'
/home/user/code/rubocop/lib/rubocop/cop/correctors/alignment_corrector.rb:50:in 'RuboCop::Cop::AlignmentCorrector.autocorrect_line'
/home/user/code/rubocop/lib/rubocop/cop/correctors/alignment_corrector.rb:25:in 'block in RuboCop::Cop::AlignmentCorrector.correct'
/home/user/code/rubocop/lib/rubocop/cop/correctors/alignment_corrector.rb:113:in 'block in …
```
> Fix an error when running with Ruby 3.4-dev

- changelog/fix_return_exit_code_0_with_display_only_correctable.md
- lib/rubocop/runner.rb
- spec/rubocop/cli_spec.rb
When `--display-only-correctable` or `--display-only-safe-correctable` is specified, and therefore no offenses are included that'd otherwise be shown, return exit code 0 instead of 1.
Fixes #13374.
> [Fix #13374] Return exit code 0 with `--display-only-correctable` and `--display-only-safe-correctable` when no offenses are displayed

- changelog/fix_when_removing_parens_in_style_ternary_parentheses.md
- lib/rubocop/cop/style/ternary_parentheses.rb
- spec/rubocop/cop/style/ternary_parentheses_spec.rb
When the condition to a ternary is a send node with arguments, and `Style/TernaryParentheses` removes parentheses around that condition, ensure the arguments are themselves parenthesized, because otherwise removing the surrounding parens will change the semantics of the ternary.
This also allows a number of test cases to be autocorrected which previously did not have autocorrect.
Fixes #13378.
> [Fix #13378] When removing parens in `Style/TernaryParentheses` with a `send` node condition, ensure its arguments are parenthesized

- lib/rubocop/cop/variable_force/branch.rb
This speeds the file from https://github.com/rubocop/rubocop/pull/13383 up from 1m21s to just 14s for me.
I see no measurable difference when running over RuboCop itself with this change.
> Fix a wrongly memoized method in `VariableForce`

- changelog/fix_error_handling_extractor_class.md
- lib/rubocop/runner.rb
- spec/rubocop/runner_spec.rb
Unfortunatly the change I made in #13263 is not sufficient. This gracefully handles the other case as well.
> Handle error in extractors when the extractor is a class

- config/default.yml
- lib/rubocop/cop/lint/unescaped_bracket_in_regexp.rb
Fixes incorrect documentation of `Lint/UnescapedBracketInRegexp`. Thanks @bquorning for noticing.
Re: https://github.com/rubocop/rubocop/pull/13385#discussion_r1815463298
> Fix documentation for `Lint/UnescapedBracketInRegexp`

- lib/rubocop/cops_documentation_generator.rb
- spec/rubocop/cops_documentation_generator_spec.rb
Using `:isolated_environment` results in yard not finding the annotations which causes it to not run a few codepaths. So, just generate the docs into a manually created tempfile and add an option to generate it into that folder instead of `Dir.pwd`
> Fix another error for the documentation generator on Ruby 2.7

- changelog/fix_false_negative_for_useless_assignment.md
- lib/rubocop/cop/variable_force/assignment.rb
- lib/rubocop/cop/variable_force/variable.rb
- lib/rubocop/cop/variable_force/variable_table.rb
- spec/rubocop/cop/lint/useless_assignment_spec.rb
Similar example false negative situation pointed in issue #13309 :
```ruby
foo = 1 # should have an offense
foo = 2
bar {
foo = 3
}
```
The issue here is that `Lint/UselessAssignment` checks if assignments have been used, however, the assignments check it based on the assignment having been referenced or the variable being used in a block. So, the false negative occurs because of the first assignment being unused but having the variable captured in a block. One potential way of solving this is too track reassignments (a new assignment follows a not referenced assignment).
Fixes #13309.
> [Fix #13309] Fix false negative with `Lint/UselessAssignment` when an useless assignment exists followed by a block

- changelog/fix_the_autocorrect_of_non_atomic_file_operation.md
- lib/rubocop/cop/lint/non_atomic_file_operation.rb
- spec/rubocop/cop/lint/non_atomic_file_operation_spec.rb
The Dir.mkdir method can take two arguments (path and mode) without using keywords.
However, the FileUtils.mkdir_p method requires the keyword mode: before the argument.
This PR fixes an issue where the autocorrect feature would not work correctly in such situations.
> Fix the autocorrect of non_atomic_file_operation

- changelog/fix_false_positives_for_style_guard_clause.md
- lib/rubocop/cop/style/guard_clause.rb
- spec/rubocop/cop/style/guard_clause_spec.rb
Fixes #13390.
This PR fixes false positives for `Style/GuardClause` when using a local variable assigned in a conditional expression in a branch.
> [Fix #13390] Fix false positives for `Style/GuardClause`

- changelog/fix_update_percent_literal_corrector_to_be_able_to.md
- lib/rubocop/cop/correctors/percent_literal_corrector.rb
- spec/rubocop/cop/style/symbol_array_spec.rb
- spec/rubocop/cop/style/word_array_spec.rb
Ruby allows putting a pair of brackets/parentheses inside a `%i`/`%w`/etc. array with the same character as delimiters.
For example:
```ruby
%i[a b[] c[][]]
```
Previously, `PercentLiteralCorrector` when correcting to `percent` style would insert unnecessary escapes when encountering such pairs:
```ruby
[:a, :'b[]', :'c[][]']
$ rubocop -A --only Style/SymbolArray test.rb
C
Offenses:
test.rb:1:1: C: [Corrected] Style/SymbolArray: Use %i or %I for an array of symbols.
[:a, :'b[]', :'c[][]']
^^^^^^^^^^^^^^^^^^^^^^
%i[a b\[\] c\[\]\[\]]
```
This change allows the backslashes to be omitted in this case, so the autocorrection is instead `%i[a b[] c[][]]`. …
> Update `PercentLiteralCorrector` to be able to write pairs of delimiters without excessive escaping

- .rubocop.yml
- spec/rubocop/cli/autocorrect_spec.rb
- spec/rubocop/cop/layout/first_array_element_line_break_spec.rb
- spec/rubocop/cop/lint/duplicate_methods_spec.rb
- spec/rubocop/cop/style/ambiguous_endless_method_definition_spec.rb
- spec/rubocop/cop/style/class_and_module_children_spec.rb
Noticed a few typos of `and offense` instead of `an offense`, so I corrected them. There's a few that were detected that I manually edited to remove some extra words.
> Fix typos `and offense` instead of `an offense`

- changelog/fix_false_positives_for_style_redundant_parenthese.md
- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
Fixes #13387.
This PR fixes false positives in `Style/RedundantParentheses` when parentheses are used around method chain with `do`...`end` block in keyword argument.
> [Fix #13387] Fix false positives for `Style/RedundantParentheses`

- changelog/fix_deserialization_encoding.md
- lib/rubocop/cached_data.rb
- spec/rubocop/result_cache_spec.rb
The first run would be fine but after loading rubocop would error. This is for the same reasons as https://github.com/rubocop/rubocop-ast/pull/289
Instead of rescuing the exception, delay buffer creation until it is first needed. This will prevent the error when all offenses are global.
> Fix deserialization of unknown encoding offenses

- lib/rubocop/cop/offense.rb
It says the string will be without department, but that is not true.
> Fix docs for `Offense.cop_name`

- changelog/fix_a_false_negative_for_style_redundant_line_continuation.md
- lib/rubocop/cop/style/redundant_line_continuation.rb
- spec/rubocop/cop/style/redundant_line_continuation_spec.rb
This PR fixes a false negative for `Style/RedundantLineContinuation` when there is a line continuation at the EOF.
> Fix a false negative for `Style/RedundantLineContinuation`

- changelog/fix_false_positive_for_lint_safe_navigation_consistency.md
- lib/rubocop/cop/lint/safe_navigation_consistency.rb
- spec/rubocop/cop/lint/safe_navigation_consistency_spec.rb
Fixes #13402.
This PR fixes a false positive for `Lint/SafeNavigationConsistency` when using unsafe navigation with both `&&` and `||`.
> [Fix #13402] Fix a false positive for `Lint/SafeNavigationConsistency`

- changelog/fix_bitwise_predicate_when_using_a_method.md
- lib/rubocop/cop/style/bitwise_predicate.rb
- spec/rubocop/cop/style/bitwise_predicate_spec.rb
Fix `Style/BitwisePredicate` when using a method.
When having a regular method named `positive?` or `zero?` the cop would raise an error.
```ruby
def positive?
some_ruby_code
end
```
Would throw a 
```
NoMethodError: undefined method `begin_type?' for nil:NilClass
```
> Fix `Style/BitwisePredicate` when using a method

- changelog/fix_fix_style_access_modifier_declarations_to_register.md
- lib/rubocop/cop/style/access_modifier_declarations.rb
- rubocop.gemspec
- spec/rubocop/cli/autocorrect_spec.rb
- spec/rubocop/cop/style/access_modifier_declarations_spec.rb
Although `private :foo, :bar` is listed in the examples for `Style/AccessModifierDeclarations` (either good or bad depending on the value of the `AllowModifiersOnSymbols` configuration), it isn't actually registered as an offense when `AllowModifiersOnSymbols` is false. 
This also affects autocorrection of groupable modifiers because as-is these are not considered properly when checking siblings (the `right_siblings_same_inline_method?` check). I added autocorrect specs for these. 
This adds test cases for `AllowModifiersOnSymbols` true and false, and fixes the false negative when false. 
NOTE: this relies on rubocop/rubocop-ast#325, and will have failing tests until that's merged.
[1]: …
> Fix `Style/AccessModifierDeclarations` to register access modifiers with multiple symbols

- changelog/change_update_lint_unused_method_argument_to_allow_the.md
- config/default.yml
- lib/rubocop/cop/lint/unused_method_argument.rb
- spec/rubocop/cop/lint/unused_method_argument_spec.rb
Augments the update to `Lint/UnusedMethodArgument` in #7747 to allow the exception classes used to indicate a not implemented method to be customized (when `IgnoreNotImplementedMethods` is `true`). This allows for codebases that don't want to use `NotImplementedError` or want a custom exception to be handled.
Fixes #11393.
> [Fix #11393] Update `Lint/UnusedMethodArgument` to allow the class names for `IgnoreNotImplementedMethods` to be configured

- changelog/fix_a_false_positive_for_style_redundant_line_continuation.md
- lib/rubocop/cop/style/redundant_line_continuation.rb
- spec/rubocop/cop/style/redundant_line_continuation_spec.rb
Fixes #13412.
This PR fixes a false positive for `Style/RedundantLineContinuation` when there is a line continuation at the end of Ruby code followed by `__END__` data.
> [Fix #13412] Fix a false positive for `Style/RedundantLineContinuation`

- changelog/fix_an_incorrect_autocorrect_for_style_redundant_condition.md
- lib/rubocop/cop/style/redundant_condition.rb
- spec/rubocop/cop/style/redundant_condition_spec.rb
Fixes #13199.
This PR makes `Style/RedundantCondition` skip autocorrection to avoid removing comments when a branch has a comment.
> [Fix #13199] Fix an incorrect autocorrect for `Style/RedundantCondition`

- changelog/fix_false_positives_for_naming_memoized_instance_variable_name.md
- lib/rubocop/cop/naming/memoized_instance_variable_name.rb
- spec/rubocop/cop/naming/memoized_instance_variable_name_spec.rb
Fixes #13415.
This PR fixes false positives for `Naming/MemoizedInstanceVariableName` when using `initialize_clone`, `initialize_copy`, or `initialize_dup`.
> [Fix #13415] Fix false positives for `Naming/MemoizedInstanceVariableName`

- changelog/fix_fix_lint_deprecated_open_ssl_constant_false.md
- lib/rubocop/cop/lint/deprecated_open_ssl_constant.rb
- spec/rubocop/cop/lint/deprecated_open_ssl_constant_spec.rb
Correct a false positive with `Lint/DeprecatedOpenSSLConstant` when the argument is a `csend` node.
> Fix `Lint/DeprecatedOpenSSLConstant` false positive when the argument is a `csend` node

- lib/rubocop/cop/gemspec/deprecated_attribute_assignment.rb
- lib/rubocop/cop/layout/block_alignment.rb
- lib/rubocop/cop/layout/rescue_ensure_alignment.rb
- lib/rubocop/cop/lint/numbered_parameter_assignment.rb
- lib/rubocop/cop/naming/variable_name.rb
- lib/rubocop/cop/style/redundant_self.rb
- lib/rubocop/cop/style/redundant_self_assignment_branch.rb
- lib/rubocop/cop/style/trailing_underscore_variable.rb
- rubocop.gemspec
Now that rubocop-ast has a `MasgnNode` and a `MlhsNode`, and `CasgnNode`, `AsgnNode` etc. has gotten some extra methods, we can remove some node destructuring from our code base.
See https://github.com/rubocop/rubocop-ast/pull/203 and https://github.com/rubocop/rubocop-ast/pull/326 for the implementations I depend on.
cc @dvandersluis 
> Reduce node destructuring

- changelog/change_update_lint_redundant_safe_navigation_to_register.md
- lib/rubocop/cop/lint/redundant_safe_navigation.rb
- spec/rubocop/cop/lint/redundant_safe_navigation_spec.rb
It is redundant to use safe-navigation on `self` because `self` always is the current object, and therefore not nil (other than if reopening `NilClass`).
```ruby
self&.foo
self.foo
```
> Update `Lint/RedundantSafeNavigation` to register an offense when the receiver is `self`

- lib/rubocop/cop/lint/literal_assignment_in_condition.rb
- lib/rubocop/cop/lint/useless_setter_call.rb
- lib/rubocop/cop/metrics/class_length.rb
- lib/rubocop/cop/metrics/utils/abc_size_calculator.rb
- lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb
- lib/rubocop/cop/style/method_call_without_args_parentheses.rb
- lib/rubocop/cop/style/parallel_assignment.rb
- lib/rubocop/cop/variable_force.rb
- spec/rubocop/cop/variable_force/assignment_spec.rb
Following #13413, this updates some code that uses `children` or `to_a` on assignment nodes with the methods now available in rubocop-ast.
> Update references to `children` on assignment nodes to node methods

- changelog/fix_false_positives_for_style_safe_navigation.md
- lib/rubocop/cop/style/safe_navigation.rb
- spec/rubocop/cop/style/safe_navigation_spec.rb
Fixes #13421 and #13423.
This PR fixes false positives for `Style/SafeNavigation` when using a method chain that exceeds the `MaxChainLength` value and includes safe navigation operator.
> [Fix #13421] Fix false positives for `Style/SafeNavigation`

- changelog/fix_false_positive_for_lint_float_comparison_against_nil.md
- lib/rubocop/cop/lint/float_comparison.rb
- spec/rubocop/cop/lint/float_comparison_spec.rb
Hi! This PR fixes a false positive for Lint/FloatComparison against nil.
Here is an example when a false positive can occur:
```ruby
Float(user_submitted_value, exception: false) == nil
```
If `user_submitted_value` is a value that cannot be made a Float, `nil` is returned because of the `exception: false` param. 
> Fix false positive for `Lint/FloatComparison` against nil

- lib/rubocop/cop/lint/circular_argument_reference.rb
```sh
$ ruby-parse --27 -e 'def foo(bar: bar); end'
(fragment:0):1:14: error: circular argument reference bar
(fragment:0):1: def foo(bar: bar); end
(fragment:0):1:              ^~~
```
> Document that `CircularArgumentReference` is useless on modern rubies

- changelog/fix_fix_empty_lines_around_method_body_for_methods.md
- lib/rubocop/cop/layout/block_alignment.rb
- lib/rubocop/cop/layout/empty_lines_around_method_body.rb
- lib/rubocop/cop/mixin/range_help.rb
- spec/rubocop/cop/layout/empty_lines_around_method_body_spec.rb
Fixes #13430
Fixes `Layout/EmptyLinesAroundMethodBody` to identify empty lines for methods which have arguments spanning multiple lines.
> Fix EmptyLinesAroundMethodBody for methods with arguments spanning multiple lines

- changelog/fix_false_positive_for_memoised_instance_variable_with_assignment.md
- lib/rubocop/cop/naming/memoized_instance_variable_name.rb
- spec/rubocop/cop/naming/memoized_instance_variable_name_spec.rb
Fixes #13434
Maybe this cop should not register offenses for methods that take arguments but let's fix wrong autocorrect first.
> [Fix #13434] False positive for `Naming/MemoizedInstanceVariableName` with assignment methods

- changelog/fix_incorrect_autocorrect_for_lint_redundant_splat_expansion.md
- lib/rubocop/cop/lint/redundant_splat_expansion.rb
- spec/rubocop/cop/lint/redundant_splat_expansion_spec.rb
Fixes incorrect offense and auto-correction for `Lint/RedundantSplatExpansion` cop when percent literal array is used as an argument in a **safe navigation** method call.
Here's a (renamed) production example from a Rails controller:
```ruby
params[:param_which_may_not_exist]&.exclude(*%w[foo bar])
```
When `AllowPercentLiteralArrayArgument` option is `true` (by default), the cop shouldn't register an offense, but it does:
and auto-corrects it to (removes the `*`):
```ruby
params[:param_which_may_not_exist]&.exclude(%w[foo bar])
```
which is not correct (nor desired in this case).
When `AllowPercentLiteralArrayArgument` is `false`, the cop prints an offense as expected, but the message is wrong (I believe):
The correct auto-correction (only in the latter case), should be:
```ruby …
```
> Recognize percent literal array arg in safe navigation for `Lint/RedundantSplatExpansion`

- changelog/fix_fix_incorrect_correction_in_lint_void_if_an.md
- lib/rubocop/cop/lint/void.rb
- spec/rubocop/cop/lint/void_spec.rb
With an operator called using a dot or safe navigation in a void context (eg. `a.==(b)`).
Previously it would correct to:
```ruby
a.
(b)
```
This change fixes the correction to:
```ruby
a
(b)
```
NOTE: The extra parentheses would be cleaned up by `Style/RedundantParentheses`.
> Fix incorrect correction in `Lint/Void` if an operator is called in a void context using a dot

- changelog/fix_incorrect_autocorrect_for_style_nested_ternary_operator.md
- lib/rubocop/cop/style/nested_ternary_operator.rb
- spec/rubocop/cop/style/nested_ternary_operator_spec.rb
This PR fixes an incorrect autocorrect for `Style/NestedTernaryOperator` when ternary operators are nested and the inner condition is parenthesized.
Before:
Autocorrect makes invalid syntax:
```console
$ echo 'foo ? (bar && baz) ? qux : quux : corge' | bundle exec rubocop --stdin dummy.rb -a --only Style/NestedTernaryOperator
F
Offenses:
dummy.rb:1:7: C: [Corrected] Style/NestedTernaryOperator: Ternary operators must not be nested. Prefer if or else constructs instead.
foo ? (bar && baz) ? qux : quux : corge
^^^^^^^^^^^^^^^^^^^^^^^^^
dummy.rb:2:11: F: Lint/Syntax: unexpected token tRPAREN
bar && baz) ? qux : quux
^ …
```
> Fix an incorrect autocorrect for `Style/NestedTernaryOperator`

- changelog/fix_incorrect_autocorrect_for_style_one_line_conditional.md
- lib/rubocop/cop/style/one_line_conditional.rb
- spec/rubocop/cop/style/one_line_conditional_spec.rb
This PR fixes an incorrect autocorrect for `Style/OneLineConditional` when the else branch of a ternary operator has multiple expressions.
Before:
The autocorrect makes incorrect code that is not compatible.
```console
$ echo 'if cond; foo; else bar; baz; end' | bundle exec rubocop --stdin dummy.rb -a --only Style/OneLineConditional
C
Offenses:
dummy.rb:1:1: C: [Corrected] Style/OneLineConditional: Favor the ternary operator (?:) or multi-line constructs over single-line if/then/else/end constructs.
if cond; foo; else bar; baz; end
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cond ? foo : bar; baz
```
`cond ? foo : bar; baz` is equivalent to `(cond ? foo : bar); baz`, not `cond ? foo : (bar; baz)`. …
> Fix an incorrect autocorrect for `Style/OneLineConditional`

- .github/workflows/rubocop.yml
- spec/support/strict_warnings.rb
In `rubocop-ast`, main gem tests should not fail when a warning is introduced. Sort of a followup to https://github.com/rubocop/rubocop/pull/13273
Ref https://github.com/rubocop/rubocop-ast/pull/337#discussion_r1838552501 cc @dvandersluis 
> Make strict warnings opt-in, in CI as well as locally

- changelog/fix_a_false_positive_for_layout_empty_line_after_guard_clause.md
- lib/rubocop/cop/layout/empty_line_after_guard_clause.rb
- spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb
This PR fixes a false positive for `Layout/EmptyLineAfterGuardClause` when using a guard clause outside oneliner block.
It avoids the following infinit loop error:
```console
return if condition; foo do
bar
end
$ bundle exec rubocop --only Layout/EmptyLineAfterGuardClause,Layout/EmptyLinesAroundBlockBody -a
C
Offenses:
example.rb:1:1: C: [Corrected] Layout/EmptyLineAfterGuardClause: Add empty line after guard clause.
return if condition; foo do
example.rb:2:1: C: [Corrected] Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body beginning.
0 files inspected, 2 offenses detected, 2 offenses corrected
Infinite loop detected in /Users/koic/src/github.com/koic/rubocop-issues/block/example.rb and
caused by …
```
> Fix a false positive for `Layout/EmptyLineAfterGuardClause`

- changelog/fix_false_positive_for_lint_interpolation_check.md
- lib/rubocop/cop/lint/interpolation_check.rb
- lib/rubocop/cop/style/variable_interpolation.rb
- spec/rubocop/cop/lint/interpolation_check_spec.rb
This PR fixes false positives for `Lint/InterpolationCheck` when using invalid syntax in interpolation.
```console
'#{%<expression>s}'
$ bundle exec rubocop -A /tmp/a/a.rb --only Lint/InterpolationCheck
F
Offenses:
/tmp/a/a.rb:1:1: W: [Corrected] Lint/InterpolationCheck: Interpolation in single quoted string detected. Use double quoted strings if you need interpolation.
'#{%<expression>s}'
/tmp/a/a.rb:1:17: F: Lint/Syntax: unexpected token tIDENTIFIER
"#{%<expression>s}"
^
````
A string interpolation should not be expected in a state where a syntax error occurs.
Before …
> Fix false positives for `Lint/InterpolationCheck`

- docs/modules/ROOT/pages/cops_layout.adoc
- lib/rubocop/cop/layout/line_length.rb
Remove the extra slash in the cop name.
> Fix typo: Layout//ParameterAlignment -> Layout/ParameterAlignment

- lib/rubocop/cop/layout/indentation_width.rb
- lib/rubocop/cop/lint/empty_ensure.rb
- lib/rubocop/cop/lint/ensure_return.rb
- lib/rubocop/cop/lint/useless_rescue.rb
- lib/rubocop/cop/lint/void.rb
- lib/rubocop/cop/style/redundant_assignment.rb
- rubocop.gemspec
`EnsureNode.body` has been deprecated in rubocop/rubocop-ast#337, and will be reimplemented in the next major version of rubocop-ast. In order to prepare for that, existing `EnsureNode.body` calls, which retreive the `ensure` branch of exception handling, have been replaced with `EnsureNode.branch`.
> Replace `EnsureNode.body` with `EnsureNode.branch`

- spec/spec_helper.rb
`net/http` removed old constants that webmock relies on. This can be reverted when https://github.com/bblimke/webmock/pull/1081 is released
> Fix a test failure on 3.4-dev with webmock

- changelog/change_array_intersect_none.md
- lib/rubocop/cop/style/array_intersect.rb
- spec/rubocop/cop/style/array_intersect_spec.rb
It's the inverse of `any?`.
There's further improvements to be made for `count == 0` and similar but it requires a more complex change.
> Make `Style/ArrayIntersect` aware of `none?`

- changelog/fix_update_style_access_modifier_declarations_to.md
- lib/rubocop/cop/style/access_modifier_declarations.rb
- spec/rubocop/cli/autocorrect_spec.rb
- spec/rubocop/cop/style/access_modifier_declarations_spec.rb
Similarly to #13404, update `Style/AccessModifierDeclarations` to handle attr methods with multiple parameters.
The autocorrect fix in #13443 does not affect attrs, so this PR handles autocorrect as well.  
Fixes #13453.
> [Fix #13453] Update `Style/AccessModifierDeclarations` to handle `attr_*` methods with multiple parameters

- lib/rubocop/cop/internal_affairs/numblock_handler.rb
Fix typo in `InternalAffairs/NumblockHandler` documentation
> [Doc] Fix missing backtick in `InternalAffairs/NumblockHandler` description

- lib/rubocop/cop/layout/argument_alignment.rb
- lib/rubocop/cop/layout/array_alignment.rb
- lib/rubocop/cop/layout/parameter_alignment.rb
Similar to #10628, change the description of these cops to use a consistent voice.
> Remove "here we check" from cop descriptions

- changelog/change_support_unicodedisplay_width_v3.md
- rubocop.gemspec
This updates `unicode-display_width` gem's version limit to 3.0 to 4.0.
Reference: [`unicode-display_width` change log at version 3.0.0](https://github.com/janlelis/unicode-display_width/blob/main/CHANGELOG.md#300)
> Support unicode-display_width v3

- changelog/fix_allow_to_write_generics_type_of_rbs__inline.md
- lib/rubocop/cop/style/commented_keyword.rb
- spec/rubocop/cop/style/commented_keyword_spec.rb
[rbs-inline](https://github.com/soutaro/rbs-inline) is a utility to embed RBS type declarations into Ruby code as comments.
This allows to write generics type rbs-inline annotation comment just after subclass definition in `Style/CommentedKeyword`.
refs: https://github.com/soutaro/rbs-inline/wiki/Syntax-guide#defining-classes
Follow https://github.com/rubocop/rubocop/pull/13222
> Allow to write generics type of rbs-inline annotation after subclass definition in `Style/CommentedKeyword`

- changelog/fix_update_layout_leading_comment_space_to_accept.md
- lib/rubocop/cop/layout/leading_comment_space.rb
- spec/rubocop/cop/layout/leading_comment_space_spec.rb
Accept a multiline shebang at the top of a file, eg.
```ruby
#!/usr/bin/env nix-shell
#! nix-shell -i ruby --pure
#! nix-shell -p ruby gh git
#! nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/aebe249544837ce42588aa4b2e7972222ba12e8f.tar.gz
puts "Hello world"
puts RUBY_VERSION
puts `gh --version`
```
FIxes #13477.
> [Fix #13477] Update `Layout/LeadingCommentSpace` to accept multiline shebangs at the top of the file

- changelog/fix_fix_autocorrection_for.md
- lib/rubocop/cop/style/access_modifier_declarations.rb
- spec/rubocop/cli/autocorrect_spec.rb
- spec/rubocop/cop/style/access_modifier_declarations_spec.rb
When correcting `Style/AccessModifierDeclarations` to remove an inline group of symbols, we need to move all methods below the bare access modifier.
This is handled in two ways:
1. If every method in the symbol list is defined in scope, they will all be moved below the access modifier (either a newly inserted one or an existed one)
2. If none of the methods are defined in scope, an offense will be registered but no correction will take place (like how it worked previously for a single symbol).
Fixes #13433.
> [Fix #13433] Fix autocorrection for `Style/AccessModifierDeclarations` for multiple inline symbols

- changelog/fix_incorrect_autocorrect_for_style_redundant_regexp_argument.md
- lib/rubocop/cop/style/redundant_regexp_argument.rb
- spec/rubocop/cop/style/redundant_regexp_argument_spec.rb
Fixes #13483.
This PR fixes an incorrect autocorrect for `Style/RedundantRegexpArgument` when using escaped double quote character.
> [Fix #13483] Fix an incorrect autocorrect for `Style/RedundantRegexpArgument`

- changelog/change_update_it_without_arguments_in_block_to_not.md
- lib/rubocop/cop/lint/it_without_arguments_in_block.rb
- lib/rubocop/cop/mixin/target_ruby_version.rb
- lib/rubocop/cops_documentation_generator.rb
- spec/rubocop/cop/lint/it_without_arguments_in_block_spec.rb
`it` as a block parameter should not register an offense in Ruby 3.4. Currently if using 3.4-dev and setting `TargetRubyVersion: 3.4` in `.rubocop.yml`, rubocop will give offenses when using `it`.
> Update `Lint/ItWithoutArgumentsInBlock` to not register an offense in Ruby 3.4

- lib/rubocop/cop/lint/number_conversion.rb
- lib/rubocop/cop/lint/regexp_as_condition.rb
- lib/rubocop/cop/style/conditional_assignment.rb
- lib/rubocop/cop/style/if_inside_else.rb
- lib/rubocop/cop/style/inverse_methods.rb
- lib/rubocop/cop/style/lambda_call.rb
- lib/rubocop/cop/style/nested_ternary_operator.rb
`IgnoredNode` is already included in `RuboCop::Cop::Base`, so including it again inside a cop is redundant.
> Remove unnecessary `include IgnoredNode`

- changelog/fix_infinite_loop_error_for_style_if_with_semicolon].md
- lib/rubocop/cop/style/if_with_semicolon.rb
- spec/rubocop/cop/style/if_with_semicolon_spec.rb
This PR fixes infinite loop error for `Style/IfWithSemicolon` when using nested if/;/end in if body.
```console
if cond1; foo + if cond2; bar
else
end
end
$ bundle exec rubocop -a -d
(snip)
/Users/koic/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/parser-3.3.6.0/lib/parser/source/tree_rewriter.rb:427:
in 'Parser::Source::TreeRewriter#trigger_policy'
/Users/koic/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/parser-3.3.6.0/lib/parser/source/tree_rewriter.rb:414:
in 'Parser::Source::TreeRewriter#enforce_policy'
/Users/koic/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+0/gems/parser-3.3.6.0/lib/parser/source/tree_rewriter/action.rb:234:
in 'Method#call'
```
The autocorrection for the nested conventional case is handled …
> Fix infinite loop error for `Style/IfWithSemicolon`

- CHANGELOG.md
- relnotes/v1.69.0.md
Change the name of the cop from
`Lint/BinaryOperatorWithIdenticalOperands` to
`Lint/NumericOperationWithConstantResult`
in the changelog as to prevent confusion
to what cop it is in reference to
-----
I was looking over the release for [`1.69.0`](https://github.com/rubocop/rubocop/releases/tag/v1.69.0) and noticed that the cop name listed in the changelog doesn't match what the actual cop name is. I didn't see anything on the PR (#13186) that showed this name (I could've missed it), so I figured it would be less confusing to have the names match.
I didn't add anything to the change log because I didn't think it really needed to be added as it is just updating the name within the change log.
[1]: …
> docs: fix cop name difference in changelog

- changelog/fix_an_incorrect_autocorrect_for_style_dig_chain.md
- lib/rubocop/cop/style/dig_chain.rb
- spec/rubocop/cop/style/dig_chain_spec.rb
Fixes #13502.
This PR fixes an incorrect autocorrect for `Style/DigChain` when using safe navigation method chain.
> [Fix #13502] Fix an incorrect autocorrect for `Style/DigChain`

- changelog/fix_incorrect_offenses_for_style_hash_except.md
- lib/rubocop/cop/style/hash_except.rb
- spec/rubocop/cop/style/hash_except_spec.rb
Fixes false positive for `Style/HashExcept` cop when using `reject`/`!include?`, `reject`/`!in?` or `select/!exclude?` combinations. Adds new test cases which fail on master.
The tests that have been changed in this patch weren't correct and actually produced the inverse result; for example, the first updated test in this patch expected that
```ruby
{foo: 1, bar: 2, baz: 3}.reject { |k, v| !%i[foo bar].include?(k) }
```
is auto-corrected to
```ruby
{foo: 1, bar: 2, baz: 3}.except(:foo, :bar)
```
when this shouldn't have been an offense for this cop since the code is equivalent to:
```ruby
{foo: 1, bar: 2, baz: 3}.slice(:foo, :bar)
```
<br />
This PR fixes these combinations:
```ruby
h.reject { |k, v| !k.in?(X) }
h.reject { |k, v| !X.include?(k) }
h.select { |k, v| !X.exclude?(k) }
``` …
> Fix false positives for `Style/HashExcept` cop

- changelog/fix_error_parallel_assignment_anon_splat.md
- rubocop.gemspec
- spec/rubocop/cop/style/parallel_assignment_spec.rb
Related to https://github.com/rubocop/rubocop/issues/13505
The fix was applied in https://github.com/rubocop/rubocop-ast/pull/340 but it still makes sense to test here as well
> Add anon splat tests to `Style/ParallelAssignment`

- lib/rubocop/cop/naming/accessor_method_name.rb
Update documentation of `Naming/AccessorMethodName` to be more specific about how to properly name an accessor method.
> [Doc] Improve documentation for `Naming/AccessorMethodName`

- changelog/fix_update_style_lambda_call_to_be_aware_of_safe.md
- lib/rubocop/cop/style/lambda_call.rb
- spec/rubocop/cop/style/lambda_call_spec.rb
Follows #13510.
Adds support for safe navigation in `Style/LambdaCall`.
> Update `Style/LambdaCall` to be aware of safe navigation

- lib/rubocop/cop/generator.rb
- spec/rubocop/cop/generator_spec.rb
Follows #13510. 
In order to try to encourage supporting `csend` nodes along with `send` nodes, I updated the generator to add an alias for the provided `def on_send` to `on_csend`. Of course, the user can remove it if its unnecessary, but it might prompt new cop developers to be thinking about safe navigation when they're working on method calls.
> Update the new cop generator to suggest supporting `on_csend` along with `on_send`

- lib/rubocop/cop/metrics/utils/code_length_calculator.rb
- spec/rubocop/cop/metrics/utils/code_length_calculator_spec.rb
The warning message previously offered `send` and `csend` as possible options, but they are not in fact valid, and will raise a warning if used. `method_call` should be offered instead.
> Improve warning when an invalid foldable type is given to `CodeLengthCalculator`

- changelog/fix_false_positive_unreachable_code.md
- lib/rubocop/cop/lint/unreachable_code.rb
- spec/rubocop/cop/lint/unreachable_code_spec.rb
If a developer decides to either redefine builtin methods like `exit`, `throw`, etc. or defines methods with the same name inside a `class`, `Lint/UnreachableCode` will treat these methods as if they were still the builtin ones, which leads to false positive reports.
E.g.:
```ruby
def exit;end
exit
puts "this is reachable"
^^^^^^^^^^^^^^^^^^^^^^^^
```
```ruby
class Dummy
def exit; end
end
d = Dummy.new
d.instance_eval do
exit
puts "this is reachable"
^^^^^^^^^^^^^^^^^^^^^^^^
end
```
This patch aims to address these cases by also checking if the called builtin has been redefined or not. The only exception is inside `instance_eval`, as we have no way to check the type of `self` and decide which methods are called, so in that case coverage is dropped instead. As a result, in the following …
> Fix some false positives in `Lint/UnreachableCode`.

- lib/rubocop/cop/internal_affairs/location_line_equality_comparison.rb
- lib/rubocop/cop/lint/binary_operator_with_identical_operands.rb
- lib/rubocop/cop/lint/deprecated_open_ssl_constant.rb
- lib/rubocop/cop/lint/literal_as_condition.rb
- lib/rubocop/cop/security/compound_hash.rb
- lib/rubocop/cop/style/fetch_env_var.rb
- lib/rubocop/cop/style/object_then.rb
Adds `RESTRICT_ON_SEND` configuration to `Lint/BinaryOperatorWithIdenticalOperands`, `Lint/DeprecatedOpenSSLConstant`, `Lint/LiteralAsCondition`, `Security/CompoundHash`, `Style/FetchEnvVar`, `Style/ObjectThen`, and `InternalAffairs/LocationLineEqualityComparison`.
> Add `RESTRICT_ON_SEND` to more cops

- changelog/fix_update_regexp_parser_dependency.md
- rubocop.gemspec
- spec/rubocop/cop/lint/unescaped_bracket_in_regexp_spec.rb
`Lint/UnescapedBracketInRegexp` had a false positive due to ammar/regexp_parser#93. The dependency is now updated, and a test has been added for this situation.
Fixes #13511.
> [Fix #13511] Update `regexp_parser` dependency

- changelog/fix_style_redundant_self_failure_with_kwnilarg_node.md
- lib/rubocop/cop/style/redundant_self.rb
- spec/rubocop/cop/style/redundant_self_spec.rb
The following ruby code leads to an error:
```ruby
def foo(a, **nil)
self.a
end
```
```
An error occurred while Style/RedundantSelf cop was inspecting rubocop/test.rb:1:5. undefined method `name' for an instance of RuboCop::AST::Node
rubocop/lib/rubocop/cop/style/redundant_self.rb:179:in `on_argument' 
rubocop/lib/rubocop/cop/style/redundant_self.rb:85:in `block in on_args' 
rubocop/lib/rubocop/cop/style/redundant_self.rb:85:in `each' rubocop/lib/rubocop/cop/style/redundant_self.rb:85:in `on_args'
```
> Fix `Style/RedundantSelf` cop failure with `kwnilarg` argument node

- changelog/fix_lint_unescaped_bracket_in_regexp_cop_for_invalid_regexp.md
- lib/rubocop/cop/lint/unescaped_bracket_in_regexp.rb
- spec/rubocop/cop/lint/unescaped_bracket_in_regexp_spec.rb
The `Lint/UnescapedBracketInRegexp` cop does not handle exceptions raised by the `regexp_parser` gem. While raising exceptions (or issuing dedicated warnings) might be useful for runtime-parsed regular expressions (e.g., `Regexp.parse(<string-literal>)`), this behavior appears to fall outside the scope of this cop.
Proposed fix: ignore regular expressions that the gem cannot parse. Alternatively, we could emit a warning, either here or in a different cop.
I could not find any discussion on this topic in [the PR](https://github.com/rubocop/rubocop/pull/13385) where this cop was implemented.
> Fix `Lint/UnescapedBracketInRegexp` failure in case of invalid regexp

- changelog/fix_style_redundant_argument_cop_failure_on_invalid_string_literal.md
- lib/rubocop/cop/style/redundant_argument.rb
- spec/rubocop/cop/style/redundant_argument_spec.rb
We have (roughly) this code in our test sutie:
```ruby
s.chomp("\x82")
```
it fails with this backtrace:
```
An error occurred while Style/RedundantArgument cop was inspecting test.rb:1:0.
invalid byte sequence in UTF-8
lib/rubocop/cop/style/redundant_argument.rb:121:in `sub'
lib/rubocop/cop/style/redundant_argument.rb:121:in `exclude_cntrl_character?'
lib/rubocop/cop/style/redundant_argument.rb:111:in `argument_matched?'
lib/rubocop/cop/style/redundant_argument.rb:90:in `redundant_argument?'
lib/rubocop/cop/style/redundant_argument.rb:67:in `on_send'
```
Seems like we have to check if provided value's encoding is valid before performing string operations.
> Fix `Style/RedundantArgument` cop failure while inspecting string literal with invalid encoding

- changelog/fix_style_string_concatenation_cop_failure_for_mixed_concats.md
- lib/rubocop/cop/style/string_concatenation.rb
- spec/rubocop/cop/style/string_concatenation_spec.rb
After years of using ruby daily I was enlightened about the 'implicit concatenation' syntax, which results in an error in the following code:
```ruby
"a" + b" "c"
```
Backtrace:
```
An error occurred while Style/StringConcatenation cop was inspecting test.rb:1:0.
undefined method `end_pos' for nil
lib/rubocop/cop/mixin/range_help.rb:33:in `contents_range'
lib/rubocop/cop/style/string_concatenation.rb:152:in `block in replacement'
lib/rubocop/cop/style/string_concatenation.rb:146:in `map'
lib/rubocop/cop/style/string_concatenation.rb:146:in `replacement'
lib/rubocop/cop/style/string_concatenation.rb:89:in `block in register_offense'
```
I'm not sure if proposed patch is the optimal one, but it should fix the issue.
NB: This cop uses `RESTRICT_ON_SEND = %i[+].freeze` so things like `"a" "b" …
> Fix `Style/StringConcatenation` cop failure when there are mixed implicit and explicit concatenation

- changelog/fix_style_redundant_parenthese_cop_failure_with_case_splat.md
- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
The following ruby code leads to an error:
```shell
rubocop --stdin bug.rb --only Style/RedundantParentheses -d <<EOF
_ = *(case when rand > 0.5 then 1 end)
EOF
```
Backtrace:
```
An error occurred while Style/RedundantParentheses cop was inspecting /bug.rb:1:5.
undefined method `begin_type?' for nil
lib/rubocop/cop/style/redundant_parentheses.rb:247:in `only_begin_arg?'
lib/rubocop/cop/style/redundant_parentheses.rb:230:in `keyword_with_redundant_parentheses?'
lib/rubocop/cop/style/redundant_parentheses.rb:139:in `find_offense_message'
lib/rubocop/cop/style/redundant_parentheses.rb:130:in `check'
lib/rubocop/cop/style/redundant_parentheses.rb:37:in `on_begin'
```
```shell
ruby-parse --legacy -e 'case when rand > 0.5 then 1 end'
(case nil
(when
(send
(send nil :rand) :>
(float 0.5))
(int …
```
> Fix `Style/RedundantParentheses` cop failure in case of splatted `case` node  without condition

- docs/modules/ROOT/pages/development.adoc
- lib/rubocop/cop/lint/circular_argument_reference.rb
- lib/rubocop/cop/lint/non_deterministic_require_order.rb
- lib/rubocop/cop/lint/refinement_import_methods.rb
- lib/rubocop/cop/lint/useless_else_without_rescue.rb
- lib/rubocop/cop/security/yaml_load.rb
Followup to https://github.com/rubocop/rubocop/pull/13473
* `Lint/CircularArgumentReference`: Invalid syntax on modern rubies
* `Lint/NonDeterministicRequireOrder`: Skipped in node handlers
* `Lint/UselessElseWithoutRescue`: Invalid syntax on modern rubies
* `Security/YAMLLoad`: Skipped in node handler
I left `Lint/RefinementImportMethods` alone and just added the removal timeframe in the docs.
Probably it could get an upper bound but docs currently don't handle both min/max at the same time.
> Specify `maximum_target_ruby_version` for a handful of cops, document it

- tasks/new_cop.rake
`InternalAffairs` cops are not added to `lib/rubocop.rb` or `config.default.yml`. Instead, they are required via `lib/rubocop/cop/internal_affairs.rb`, so if generating an `InternalAffairs` cop, automatically update the correct file.
I added these changes to the rake task, not to `RuboCop::Cop::Generator`, so that they would not affect other rubocop extensions. As far as I can tell, the other extensions tend to define their own `new_cop` rake task so they should not be affected.
> Update `rake new_cop` to handle `InternalAffairs` cops

- lib/rubocop/cop/lint/binary_operator_with_identical_operands.rb
Noticed this while looking at #13519, since the relevant operators are covered by the new `RESTRICT_ON_SEND`, we don't have to check for these anymore.
No changelog entry added as behavior is identical.
> Remove `MATH_OPERATORS` check from `Lint/BinaryOperatorWithIdenticalOperands`

- docs/modules/ROOT/pages/integration_with_other_tools.adoc
I've tried to add rubocop to my `.pre-commit-config.yaml` using snippet from [docs](https://docs.rubocop.org/rubocop/integration_with_other_tools.html#git-pre-commit-hook-integration-with-pre-commit), but it seems there's no `.pre-commit-hooks.yaml` at 1.8.1:
> An error has occurred: InvalidManifestError: 
> =====> ~/.cache/pre-commit/repopxc490ng/.pre-commit-hooks.yaml is not a file
It worked fine after changing `rev` to 1.69.0
> Specify newer repository revision for precommit integration in docs

- lib/rubocop/cop/layout/line_continuation_leading_space.rb
- spec/rubocop/cop/layout/line_continuation_leading_space_spec.rb
Use "of **the** next/previous line" instead of "of next/previous line".
> Fix grammar in `Layout/LineContinuationLeadingSpace` offense messages

- lib/rubocop/cop/layout/empty_lines_around_begin_body.rb
How about listing them in the order of bad → good, just like the examples of other cops?
(In addition, I removed unnecessary blank lines directly below `# bad` and `# good`.)
> Improve `Layout/EmptyLinesAroundBeginBody` example

- docs/modules/ROOT/pages/integration_with_other_tools.adoc
- tasks/cut_release.rake
It makes sense to both motivate users to use the latest RuboCop repo version when configuring `pre-commit` integration and specify the oldest supported version (v1.9) in docs.
See https://github.com/rubocop/rubocop/pull/13536#discussion_r1867451231
> Automatic pre-commit repository revision update in docs

- changelog/fix_style_redundant_condition_cop_failure_with_empty_arguments.md
- lib/rubocop/cop/mixin/comments_help.rb
- spec/rubocop/cop/style/redundant_condition_spec.rb
I’ve encountered an error with this Ruby code:
```
rubocop --stdin bug.rb -d <<EOF
test ? test : Proc.new {}
EOF
```
Backtrace:
```
An error occurred while Style/RedundantCondition cop was inspecting bug.rb:1:0.
undefined method `line' for nil
~/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/parser-3.3.5.0/lib/parser/source/map.rb:100:in `line'
lib/rubocop/cop/mixin/comments_help.rb:81:in `find_end_line'
lib/rubocop/cop/mixin/comments_help.rb:22:in `comments_in_range'
lib/rubocop/cop/mixin/comments_help.rb:15:in `contains_comments?'
lib/rubocop/cop/style/redundant_condition.rb:77:in `block in autocorrect'
```
It seems the issue is not with the cop itself but with `lib/rubocop/cop/mixin/comments_help.rb`:
1. The public API method `contains_comments?(node)` does not verify whether the …
> Fix `Style/RedundantCondition` cop failure in case of empty arguments node

- changelog/fix_layout_line_length_cop_failure_with_yard_like_string.md
- lib/rubocop/cop/mixin/line_length_help.rb
- spec/rubocop/cop/layout/line_length_spec.rb
The following ruby code leads to an error:
```
rubocop -c <(echo "Layout/LineLength:\n AllowURI: true\n Max: 1") --stdin bug.rb --only Layout/LineLength -d <<EOF
expect(some_exception_variable) {|e| e.url.should == 'http://host/path'}
EOF
```
(there's a `\t` in the beginning)
Backtrace:
```
An error occurred while Layout/LineLength cop was inspecting bug.rb.
undefined method `offset' for nil
lib/rubocop/cop/mixin/line_length_help.rb:76:in `extend_uri_end_position'
lib/rubocop/cop/mixin/line_length_help.rb:44:in `find_excessive_uri_range'
lib/rubocop/cop/layout/line_length.rb:359:in `check_uri_line'
lib/rubocop/cop/layout/line_length.rb:258:in `check_line'
lib/rubocop/cop/layout/line_length.rb:103:in `block in on_investigation_end'
lib/rubocop/cop/layout/line_length.rb:102:in `each' …
```
> Fix `Layout/LineLength` cop failure in case of tabbed YARD-comment-like string

- lib/rubocop/magic_comment.rb
For some reason, GitHub can't find the blob using the short 78b95b4 reference, even though it's the only commit with that prefix. Making the hash prefix slightly longer resolves the issue.
> Fix lib/rubocop/magic_comment.rb broken comment link

- changelog/fix_an_incorrect_autocorrect_for_style_multiple_comparison.md
- lib/rubocop/cop/style/multiple_comparison.rb
- spec/rubocop/cop/style/multiple_comparison_spec.rb
Fixes #13553.
This PR fixes an incorrect autocorrect for `Style/MultipleComparison` when a variable is compared multiple times after a method call.
> [Fix #13553] Fix an incorrect autocorrect for `Style/MultipleComparison`

- changelog/fix_style_frozen_string_literal_comment_cop_false_positive.md
- lib/rubocop/magic_comment.rb
- spec/rubocop/cop/lint/duplicate_magic_comment_spec.rb
- spec/rubocop/cop/style/frozen_string_literal_comment_spec.rb
```console
$ echo '# frozen_string_literal: TRUE' | rubocop --stdin bug.rb --only Style/FrozenStringLiteralComment
C
Offenses:
bug.rb:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
^
1 file inspected, 1 offense detected, 1 offense autocorrectable
```
Non-downcased literals are checked by `Style/MagicCommentFormat` cop.
> Fix `Style/FrozenStringLiteralComment` cop false positive in case of non-downcased value literal

- changelog/fix_bundler_duplicated_gem_cop_error_in_case_of_empty_branch.md
- lib/rubocop/cop/bundler/duplicated_gem.rb
- spec/rubocop/cop/bundler/duplicated_gem_spec.rb
An MRE:
```ruby
case
when Dir.exist?(local)
gem 'rubocop', path: local
when ENV['RUBOCOP_VERSION'] == 'master'
else
gem 'rubocop', '~> 0.90.0'
end
```
Backtrace:
```
NoMethodError:
undefined method `child_nodes' for nil
```
> Fix `Bundler/DuplicatedGem` cop error in case of empty branch

- changelog/fix_lint_non_actomic_file_operation_in_case_of_implicit_receiver.md
- lib/rubocop/cop/lint/non_atomic_file_operation.rb
- spec/rubocop/cop/lint/non_atomic_file_operation_spec.rb
```console
echo 'mkdir(path) unless FileTest.exist?(path)' | rubocop --stdin bug.rb --only Lint/NonAtomicFileOperation -d
An error occurred while Lint/NonAtomicFileOperation cop was inspecting bug.rb:1:0.
undefined method `name' for an instance of Parser::Source::Map::Send
lib/rubocop/cop/lint/non_atomic_file_operation.rb:135:in `autocorrect_replace_method'
lib/rubocop/cop/lint/non_atomic_file_operation.rb:123:in `autocorrect'
lib/rubocop/cop/lint/non_atomic_file_operation.rb:108:in `block in register_offense'
```
This patch removes offenses for IO-related methods without implicit receiver.
> Fix `Lint/NonAtomicFileOperation` cop error in case of implicit receiver

- spec/rubocop/cop/layout/argument_alignment_spec.rb
The cop was already handling this case (found in #13084) properly but it was not explicitly tested, so I've added tests.
> Add test cases for `Layout/ArgumentAlignment` for method call with square brackets and no dot

- changelog/fix_update_layout_extra_spacing_and.md
- lib/rubocop/cop/mixin/preceding_following_alignment.rb
- spec/rubocop/cop/layout/extra_spacing_spec.rb
- spec/rubocop/cop/layout/space_around_operators_spec.rb
The `PrecedingFollowingAlignment` mixin is used to determine if lines are aligned properly based on certain criteria. For alignment involving assignment or `<<`, it was previously just matching the text content at a given column, but this could cause a false result if a string containing the operator was perfectly aligned with the column.
This update fixes that by ensuring that the position is within the correct token type.
Fixes #13509.
> [Fix #13509] Update `Layout/ExtraSpacing` and `Layout/SpaceAroundOperators` to handle preceding operators inside strings

- changelog/fix_fix_style_redundant_line_continuation_false.md
- lib/rubocop/cop/style/redundant_line_continuation.rb
- spec/rubocop/cop/style/redundant_line_continuation_spec.rb
For example:
```
def do_something
foo \
|| bar \
end
```
The first continuation is required but the second is redundant.
> Fix `Style/RedundantLineContinuation` false negatives when a redundant continuation follows a required continuation

- changelog/fix_fix_disable_uncorrectable_to_not_insert_directives.md
- lib/rubocop/cop/autocorrect_logic.rb
- spec/rubocop/cli/disable_uncorrectable_spec.rb
Update `--disable-uncorrectable` to wrap directives around a string rather than inserting them into the string. 
I also refactored to avoid iterating over the AST repeatedly for each type of check.
Fixes #12995.
> [Fix #12995] Fix --disable-uncorrectable to not insert directives inside a string

- changelog/fix_style_method_call_without_args_parentheses_cop.md
- lib/rubocop/cop/style/method_call_without_args_parentheses.rb
- spec/rubocop/cop/style/method_call_without_args_parentheses_spec.rb
```console
echo 'h[:a], h[:b] = f()' | rubocop --stdin bug.rb --only Style/MethodCallWithoutArgsParentheses -d
Scanning bug.rb
An error occurred while Style/MethodCallWithoutArgsParentheses cop was inspecting bug.rb:1:15.
undefined method `name' for an instance of RuboCop::AST::SendNode
lib/rubocop/cop/style/method_call_without_args_parentheses.rb:111:in `block in variable_in_mass_assignment?'
lib/rubocop/cop/style/method_call_without_args_parentheses.rb:110:in `any?'
lib/rubocop/cop/style/method_call_without_args_parentheses.rb:110:in `variable_in_mass_assignment?'
lib/rubocop/cop/style/method_call_without_args_parentheses.rb:75:in `block in same_name_assignment?'
lib/rubocop/cop/style/method_call_without_args_parentheses.rb:105:in `block in any_assignment?'
``` …
> Fix `Style/MethodCallWithoutArgsParentheses` cop error in case of mass hash assignment

- changelog/fix_naming_rescue_exceptions_variable_name_cop_error.md
- lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb
- spec/rubocop/cop/naming/rescued_exceptions_variable_name_spec.rb
This code
```ruby
S = Struct.new(:exception)
s = S.new
begin
raise RuntimeError.new
rescue => s.exception
end
p s.exception
```
leads to an error:
```
An error occurred while Naming/RescuedExceptionsVariableName cop was inspecting test.rb:6:0.
undefined method `name' for an instance of RuboCop::AST::SendNode
lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb:157:in `variable_name'
lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb:67:in `on_resbody'
```
> Fix `Naming/RescueExceptionsVariableName` cop error in case of arbitrary expression

- changelog/fix_error_unescaped_bracket_scanner_error.md
- lib/rubocop/cop/lint/unescaped_bracket_in_regexp.rb
- spec/rubocop/cop/lint/unescaped_bracket_in_regexp_spec.rb
This is a followup to #13522. The added regex raises a `ScannerError`, which doesn't inherit from `ParserError`.
> Fix `Lint/UnescapedBracketInRegexp` cop failure with invalid multibyte escape

- .github/workflows/rubocop.yml
Rspec now lives under https://github.com/rspec/rspec Also see https://github.com/rspec/rspec/issues/153
Without this change, it will continue to test use stale code. I'll make PRs for other extensions.
> Update RSpec 4 CI to the monorepo

- spec/spec_helper.rb
- spec/support/strict_warnings.rb
It was removed beforehand but now emits a warning about that removal. Discussed in https://bugs.ruby-lang.org/issues/20900
Followup to https://github.com/rubocop/rubocop/pull/13466
For green CI when Ruby 3.4 gets added in the not-so-near future. This is the only warning at the current moment.
> `Net::HTTPSession` is deprecated now

- changelog/fix_fix_incorrect_autocorrect_when.md
- lib/rubocop/cop/layout/line_continuation_leading_space.rb
- spec/rubocop/cli/autocorrect_spec.rb
- spec/support/file_helper.rb
When both cops are activated and run in the same iteration of the correction loop, `Style/StringLiterals` undoes the moving of spaces that `Layout/LineContinuationLeadingSpace` performs. This is because `StringLiterals` takes the original string content and transforms it, rather than just modifying the delimiters, in order to handle escaping for quotes within the string.
By marking `Style/StringLiterals` as incompatible with `Layout/LineContinuationLeadingSpace`, it allows the correction to be deferred to the next inspection loop, thereby avoiding the problem.
Fixes #13320.
> [Fix #13320] Fix incorrect autocorrect when `Layout/LineContinuationLeadingSpace` and `Style/StringLiterals` autocorrects in the same pass

- changelog/fix_style_exact_regexp_match_cop_error_on_invalid_regexp.md
- lib/rubocop/cop/style/exact_regexp_match.rb
- spec/rubocop/cop/style/exact_regexp_match_spec.rb
This is a follow-up to https://github.com/rubocop/rubocop/pull/13573
Upon encounter with invalid regular expression (e.g `/^\P$/`) cop `Style/ExactRegexpMatch` throws an error.
NB: Maybe we should extract `Regexp::Parser.parse ... rescue ...`  to some shared utility module.
> Fix `Style/ExactRegexpMatch` cop error on invalid regular expression literal

- changelog/fix_fix_style_block_delimiters_when_an_operator_method.md
- lib/rubocop/cop/style/block_delimiters.rb
- spec/rubocop/cop/style/block_delimiters_spec.rb
Update `Style/BlockDelimiters` to not register an offense when braces are necessary to avoid changing precedence. Previously when an operator method was encountered, it was automatically evaluated (ie. not marked as ignored), but this can result in block delimiters being changed that affects block binding.
Now operator methods are evaluated for nodes to ignore, other than if it only has a single argument which is of block type.
As well, I added the missing `expect_corrections` tests for offenses without it.
Fixes #13299.
> [Fix #13299] Fix `Style/BlockDelimiters` to always accept braces when an operator method argument is chained

- changelog/fix_false_positives_for_style_file_null.md
- lib/rubocop/cop/style/file_null.rb
- spec/rubocop/cop/style/file_null_spec.rb
Fixes #13556.
This PR fixes false positives for `Style/FileNull` when using `'nul'` string.
This PR ensures only files that use the string `'/dev/null'` are targeted for detection. This is because the string `'nul'` is not limited to the null device. This behavior results in false negatives when the `'/dev/null'` string is not used, but it is a trade-off to avoid false positives.
> [Fix #13556] Fix false positives for `Style/FileNull`

- changelog/fix_reset_the_docs_version.md
- docs/modules/ROOT/pages/development.adoc
The development tutorial [here](https://docs.rubocop.org/rubocop/1.69/development.html#implementation) does not work as written. `NodePattern` is not available in the root namespace. This fix should help others who get tripped up when trying to use `NodePattern`.
> make `NodePattern` available for use throughout the tutorial

- changelog/change_lint_duplicate_set_element_cop_to_detect_sorted_set_duplicates.md
- lib/rubocop/cop/lint/duplicate_set_element.rb
- spec/rubocop/cop/lint/duplicate_set_element_spec.rb
`SortedSet` was in Ruby's standard library until 3.0, and I believe some people keep using it as a gem after its removal.
> Enhance `Lint/DuplicateSetElement` to detect offences within `SortedSet`

- changelog/fix_lint_non_atomic_file_operation_error_on_non_constant_receiver.md
- lib/rubocop/cop/lint/non_atomic_file_operation.rb
- spec/rubocop/cop/lint/non_atomic_file_operation_spec.rb
Follow-up to https://github.com/rubocop/rubocop/pull/13558
```console
echo 'storage[:files].delete(file) unless File.exists?(file)' | rubocop --stdin bug.rb --only Lint/NonAtomicFileOperation -d
An error occurred while Lint/NonAtomicFileOperation cop was inspecting bug.rb:1:0.
undefined method `name' for an instance of Parser::Source::Map::Send
lib/rubocop/cop/lint/non_atomic_file_operation.rb:136:in `autocorrect_replace_method'
lib/rubocop/cop/lint/non_atomic_file_operation.rb:124:in `autocorrect'
lib/rubocop/cop/lint/non_atomic_file_operation.rb:109:in `block in register_offense'
```
> Fix `Lint/NonAtomicFileOperation` cop error on non-constant receiver

- changelog/change_false_positives_numeric_result_constant.md
- lib/rubocop/cop/lint/numeric_operation_with_constant_result.rb
- spec/rubocop/cop/lint/numeric_operation_with_constant_result_spec.rb
Fix #13557. In addition to this, I also stumbled across https://github.com/rubocop/rubocop-jp/issues/70 which is about `x -= x` where x is an Array.
There's also `x - x` where `x` is a float (https://github.com/rubocop/rubocop/pull/13533#issuecomment-2513480793) but I don't feel that is worth documenting.
Crude machine-translation from (https://github.com/rubocop/rubocop-jp/issues/70):
> If mistakes and debug leftover code are expected, I have a feeling that the 0s and 1s that remain after auto-fixing are garbage after all.
I could imagine cases where I would be happy to be warned about leftover debugging or typos, but I couldn't think of a case where I would be happy to be auto-fixed to 0 or 1.
So I think it would be okay to simply stop supporting auto-fixes.
I think this makes sense? …
> [Fix #13557] Fix false positives for `Lint/NumericOperationWithConstantResult`

- changelog/fix_validate_that_cops_configs_are_hashes.md
- lib/rubocop/config.rb
- lib/rubocop/config_validator.rb
- spec/rubocop/config_spec.rb
Our team encountered a malformed configuration like:
```yaml
require:
- rubocop-demo1
- rubocop-demo2
Demo1: Enabled # ❌ Treated as the String "Enabled"
Demo2:
Enabled: true # ✅ Has to be a Hash
```
Which leads to this `NoMethodError` in `config_validator.rb`:
<details><summary>Stacktrace</summary>
```sh
$ bundle exec rubocop --parallel --cache-root tmp/cache/rubocop | 2s
undefined method `each_key' for an instance of String
/tmp/bundle/ruby/3.3.0/gems/rubocop-1.69.1/lib/rubocop/config_validator.rb:198:in `each_invalid_parameter'
/tmp/bundle/ruby/3.3.0/gems/rubocop-1.69.1/lib/rubocop/config_validator.rb:183:in `block in validate_parameter_names'
/tmp/bundle/ruby/3.3.0/gems/rubocop-1.69.1/lib/rubocop/config_validator.rb:181:in `each' …
```
> Validate that Cops’ configs are Hashes

- changelog/new_target_gem_version.md
- docs/modules/ROOT/pages/development.adoc
- lib/rubocop/cop/base.rb
- lib/rubocop/rspec/shared_contexts.rb
- spec/rubocop/cop/cop_spec.rb
This allows cops that require a gem to handle multiple different versions of a gem at the same time.
Previously the only piece of information you had was that the gem was present.
For example in rack 3.1, new status code aliases were added that should not be handled on earlier versions.
Since this only looks at the lockfile, default gems are not considered.
> [Fix #13284] Add new `target_gem_version` API

- lib/rubocop/config.rb
- lib/rubocop/cop/internal_affairs.rb
- lib/rubocop/cop/internal_affairs/cop_enabled.rb
- lib/rubocop/cop/layout/argument_alignment.rb
- lib/rubocop/cop/layout/first_argument_indentation.rb
- lib/rubocop/cop/layout/first_array_element_indentation.rb
- lib/rubocop/cop/layout/first_hash_element_indentation.rb
- lib/rubocop/cop/layout/hash_alignment.rb
- lib/rubocop/cop/layout/redundant_line_break.rb
- lib/rubocop/cop/mixin/dig_help.rb
- lib/rubocop/cop/mixin/statement_modifier.rb
- lib/rubocop/cop/mixin/string_literals_help.rb
- lib/rubocop/cop/style/arguments_forwarding.rb
- lib/rubocop/cop/style/empty_literal.rb
- lib/rubocop/cop/style/empty_method.rb
- lib/rubocop/cop/style/quoted_symbols.rb
- lib/rubocop/cop/style/redundant_parentheses.rb
- lib/rubocop/cop/style/safe_navigation.rb
- lib/rubocop/cop/style/single_line_do_end_block.rb
- lib/rubocop/cop/style/single_line_methods.rb
- spec/rubocop/config_spec.rb
- spec/rubocop/cop/internal_affairs/cop_enabled_spec.rb
Update `RuboCop::Cop::Config` to introduce a fluent interface for checking if a cop is enabled. Two methods have been added: `Config#cop_enabled?` to replace `config.for_cop(...)['Enabled']` and `Config#for_enabled_cop` (only returns configuration if the cop is enabled).
To help use the new methods, a new `InternalAffairs/CopEnabled` cop has been added as well.
> Add `Config#for_enabled_cop` and `Config#cop_enabled?`

- changelog/fix_style_hash_syntax_cop_error_on_implicit_call_message.md
- lib/rubocop/cop/style/hash_syntax.rb
- spec/rubocop/cop/style/hash_syntax_spec.rb
```console
echo 'JSON.method(:dump).(:a => 1)' | rubocop --stdin bug.rb --only Style/HashSyntax -d
An error occurred while Style/HashSyntax cop was inspecting bug.rb:1:20.
undefined method `end_pos' for nil
lib/rubocop/cop/style/hash_syntax.rb:275:in `argument_without_space?'
lib/rubocop/cop/style/hash_syntax.rb:256:in `autocorrect_ruby19'
lib/rubocop/cop/style/hash_syntax.rb:202:in `autocorrect'
lib/rubocop/cop/style/hash_syntax.rb:243:in `block (2 levels) in check'
```
> Fix `Style/HashSyntax` cop error in case of implicit `call` message

- docs/modules/ROOT/pages/development.adoc
- lib/rubocop/rspec/shared_contexts.rb
- spec/rubocop/cop/cop_spec.rb
Followup to #13543
This also fixes an issue I introduced by using `and_call_original`. Right now it actually parses the projects real gemfile which is certainly unexpected.
So instead, just unstub it that one specific case where it actually matters.
> Make it easy to stub gem versions for tests

- changelog/fix_add_new_style_it_assignment_cop_to_detect_fq_constants.md
- lib/rubocop/cop/lint/non_atomic_file_operation.rb
- spec/rubocop/cop/lint/non_atomic_file_operation_spec.rb
This works fine:
```console
echo 'File.delete(path) if File.exist?(path)' | rubocop --stdin bug.rb --only Lint/NonAtomicFileOperation
W
Offenses:
bug.rb:1:1: W: Lint/NonAtomicFileOperation: Use atomic file operation method FileUtils.rm_f. (https://rubystyle.guide#atomic-file-operations)
File.delete(path) if File.exist?(path)
```
This does not:
```console
echo 'File.delete(path) if ::File.exist?(path)' | rubocop --stdin bug.rb --only Lint/NonAtomicFileOperation
.
```
> Fix `Lint/NonAtomicFileOperation` cop to detect offenses with FQ constants

- changelog/fix_false_positives_for_style_multiple_comparison.md
- lib/rubocop/cop/style/multiple_comparison.rb
- spec/rubocop/cop/style/multiple_comparison_spec.rb
This PR fixes false positives for `Style/MultipleComparison` when using multiple safe navigation method calls.
> Fix false positives for `Style/MultipleComparison`

- changelog/fix_false_negatives_for_lint_void_in_certain_conditionals.md
- lib/rubocop/cop/lint/void.rb
- spec/rubocop/cop/lint/void_spec.rb
False negatives were appearing in non-modifier form of if blocks, e.g.
```ruby
if condition
42
end
something_else
```
This likely indicates a missing assignment or return.
Note that this is already the case for the extremely similar
```ruby
42 if condition
something_else
```
I'm not certain why there was previously a check for `expr.modifier_form?` introduced in #12981. The tests all pass without it and its removal fixes the new specs I've introduced as well.
This also fixes the related issue with ternary ifs identified in #13104, although not the more complicated `case` statement variant identified in the comments of that issue.
> [Fix #12393] Fix false negative in Lint/Void inside of non-modifier if blocks

- changelog/fix_update_layout_line_continuation_spacing_to_ignore.md
- lib/rubocop/cop/layout/line_continuation_spacing.rb
- spec/rubocop/cop/layout/line_continuation_spacing_spec.rb
Changing the spacing around a continuation inside a regexp will change the regexp, so they are now ignored by `Layout/LineContinuationSpacing`.
Fixes #13578.
> [Fix #13578] Update `Layout/LineContinuationSpacing` to ignore continuations inside a `regexp` or `xstr`

- changelog/fix_style_redundant_condition_cop_error_on_parentheses_and_modifier_if.md
- lib/rubocop/cop/mixin/comments_help.rb
- spec/rubocop/cop/style/redundant_condition_spec.rb
```console
echo 's ? s : (s.succ unless $VERBOSE)' | rubocop --stdin /bin/true --only Style/RedundantCondition -d
An error occurred while Style/RedundantCondition cop was inspecting /bin/true:1:0.
undefined method `line' for nil
lib/rubocop/cop/mixin/comments_help.rb:88:in `find_end_line'
lib/rubocop/cop/mixin/comments_help.rb:22:in `comments_in_range'
lib/rubocop/cop/mixin/comments_help.rb:15:in `contains_comments?'
```
Since I had to patch global `CommentHelper` to fix the bug I tried to keep it somewhat local so it does not break something accidentally.
> Fix `Style/RedundantCondition` cop error on parentheses and modifier `if`

- changelog/fix_lint_void_cop_error_on_if_without_body.md
- lib/rubocop/cop/lint/void.rb
- spec/rubocop/cop/lint/void_spec.rb
```console
echo 'if false; end; p :ok' | rubocop --stdin /bin/true --only Lint/Void -d
For /bin: An error occurred while Lint/Void cop was inspecting /bin/true:1:0.
undefined method `type' for nil
lib/rubocop/cop/lint/void.rb:248:in `entirely_literal?'
lib/rubocop/cop/lint/void.rb:158:in `check_literal'
lib/rubocop/cop/lint/void.rb:119:in `check_expression'
lib/rubocop/cop/lint/void.rb:111:in `block in check_begin'
lib/rubocop/cop/lint/void.rb:104:in `each'
lib/rubocop/cop/lint/void.rb:104:in `check_begin'
lib/rubocop/cop/lint/void.rb:91:in `on_begin'
```
> Fix `Lint/Void` cop error on `if` without body

- changelog/fix_fix_regression_in_layout_space_around_operators.md
- lib/rubocop/cop/layout/extra_spacing.rb
- lib/rubocop/cop/layout/space_around_operators.rb
- lib/rubocop/cop/mixin/preceding_following_alignment.rb
- spec/rubocop/cop/layout/space_around_operators_spec.rb
A regression was introduced in #13516, which caused different operators ending in an `=` character to no longer be handled properly. 
Previously to that PR, the `aligned_assignment?` method in `PrecedingFollowingAlignment` only looked that there was a literal `=` character on the line being checked in the same column. This was changed to ensure that that character was actually part of an operator token, however, a byproduct of the previous version is that non-assignment operators ending in `=` (namely, comparison operators `>=`, `<=`, `!=`, etc.) would be considered aligned. With the change, this was no longer the case, and when a number of different of these operators were aligned, `Layout/SpaceAroundOperators` would now register an offense.
I have updated the check to now consider all …
> [Fix #13586] Fix regression in `Layout/SpaceAroundOperators` when different comparison operators were aligned with each other

- changelog/fix_false_positives_for_lint_nested_method_definition_cop.md
- lib/rubocop/cop/lint/nested_method_definition.rb
- spec/rubocop/cop/lint/nested_method_definition_spec.rb
This PR fixes false positives for `Lint/NestedMethodDefinition` when defining a method on a constant or a method call.
It follows the same reasoning as #12961. This should respect the intent of the code and should not be linted.
> Fix false positives for `Lint/NestedMethodDefinition`

- lib/rubocop/cop/lint/unescaped_bracket_in_regexp.rb
- lib/rubocop/cop/style/exact_regexp_match.rb
- lib/rubocop/cop/util.rb
- spec/rubocop/cop/util_spec.rb
Follow-up to https://github.com/rubocop/rubocop/pull/13574#issuecomment-2538620973
Since we have two cops that need to safely parse regular expressions, it makes sense to add a specific method to the RuboCop::Cop::Util module.
> Extract regexp parsing to utilities module

- lib/rubocop/cop/style/exponential_notation.rb
The allowed mantissa for `engineering` is < 1000, not 10.
(The example below is correct.)
> [DOC] Fix typo in `Style/ExponentialNotation`

- changelog/new_support_passing_the_target_ruby_version_through_an.md
- docs/modules/ROOT/pages/configuration.adoc
- lib/rubocop/target_ruby.rb
- spec/rubocop/target_ruby_spec.rb
In version 1.67, the search order for the target ruby version changed to prefer gemspec files over `.ruby-version`. While this is a good change as the gemspec is a better authority on what version of ruby a gem requires, it complicates some internal testing at Stripe where we forbid tests from globbing the filesystem, and finding the gemspec requires globbing in parent directories.
As a workaround, this PR adds a new source for the target ruby version: the `RUBOCOP_TARGET_RUBY_VERSION` environment variable. This is now the first tried source for the target ruby version, giving an environmental override for situations where searching the filesystem isn't permitted.
> Support passing the target ruby version through an environment variable

- changelog/fix_dup_possibly_frozen_string_in_to_string_literal.md
- lib/rubocop/cop/util.rb
- spec/rubocop/cop/util_spec.rb
Currently, there are exactly three instances where the receiver-mutating
`String#force_encoding` method is used. In all cases except for
`to_string_literal`, a `String#dup` call is included to ensure compatibility
with frozen strings. I couldn't identify any counterexamples in rubocop core that would result
in a runtime error, but there is at least one instance in `rubocop-performance` [1]
where a frozen string might be passed. To ensure everything works correctly,
we need to add a `#dup` call in the implementation of `to_string_literal`.
For additional context, it's worth noting that the Prism parser might start
freezing AST leaf nodes in the future [2],
and whitequark's parser has some unpredictability in this regard [3].
[1] https://github.com/rubocop/rubocop-performance/pull/480
[2] …
> Dup possibly frozen string in `to_string_literal` helper

- changelog/fix_false_positive_raise_args_forwarding.md
- lib/rubocop/cop/style/raise_args.rb
- spec/rubocop/cop/style/raise_args_spec.rb
Fixes #13614
I also found out that `...` results in the same error, so ignore it as well. `**` was already correctly ignored, I just added a test.
> [Fix #13614] Fix false positives for `Style/RaiseArgs` with anonymous splat and triple dot forwarding

- changelog/fix_lint_literal_in_interpolation_error_on_invalid_string.md
- lib/rubocop/cop/lint/literal_in_interpolation.rb
- spec/rubocop/cop/lint/literal_in_interpolation_spec.rb
```console
echo '"#{"\201\203"}"' | rubocop --stdin bug.rb --only Lint/LiteralInInterpolation -d
An error occurred while Lint/LiteralInInterpolation cop was inspecting bug.rb:1:0.
invalid byte sequence in UTF-8
lib/active_support/core_ext/object/blank.rb:159:in `match?'
lib/active_support/core_ext/object/blank.rb:159:in `blank?'
lib/rubocop/cop/lint/literal_in_interpolation.rb:171:in `space_literal?'
lib/rubocop/cop/lint/literal_in_interpolation.rb:51:in `offending?'
lib/rubocop/cop/lint/literal_in_interpolation.rb:26:in `on_interpolation'
```
Co-authored-by: Koichi ITO <koic.ito@gmail.com>
> Fix `Lint/LiteralInInterpolation` cop error on invalid string literal

- changelog/fix_fix_false_negatives_in.md
- lib/rubocop/cop/style/redundant_line_continuation.rb
- spec/rubocop/cop/style/redundant_line_continuation_spec.rb
Fixes the following false negatives for `Style/RedundantLineContinuation`:
```ruby
x do
foo bar \
baz
end
y do
foo(bar, \
baz)
end
```
```ruby
foo bar \
baz
foo(bar, \
baz)
```
In both cases, the second continuation is redundant, but was not flagged properly. 
Fixes #12430.
> [Fix #12430] Fix false negatives in `Style/RedundantLineContinuation` when continuations are inside begin nodes

- changelog/fix_style_yoda_expression_cop_error_on_suffix_form_of_operator.md
- lib/rubocop/cop/style/yoda_expression.rb
- spec/rubocop/cop/style/yoda_expression_spec.rb
```console
echo '1 + C.+' | be rubocop --stdin bug.rb --only Style/YodaExpression -d
An error occurred while Style/YodaExpression cop was inspecting bug.rb:1:4.
undefined method `numeric_type?' for nil
lib/rubocop/cop/style/yoda_expression.rb:74:in `constant_portion?'
lib/rubocop/cop/style/yoda_expression.rb:70:in `yoda_expression_constant?'
lib/rubocop/cop/style/yoda_expression.rb:56:in `on_send'
```
> Fix `Style/YodaExpression` cop error on suffix form of operator

- changelog/fix_fix_crash_when_running_rubocop_d_on_a_config_with.md
- lib/rubocop/config_loader_resolver.rb
- lib/rubocop/path_util.rb
- spec/rubocop/config_loader_spec.rb
- spec/rubocop/path_util_spec.rb
When you use `inherit_from` with a remote config, and that config inherits itself, it's possible a overridden config warning would be triggered. However, `PathUtil#smart_path` does not expect a `RemoteConfig`, and thus was crashing.
```
undefined method `start_with?' for an instance of RuboCop::RemoteConfig
/src/rubocop/lib/rubocop/path_util.rb:42:in `smart_path'
/src/rubocop/lib/rubocop/config_loader_resolver.rb:178:in `duplicate_setting_warning'
/src/rubocop/lib/rubocop/config_loader_resolver.rb:174:in `warn_on_duplicate_setting'
```
I made two changes:
1. `PathUtil#smart_path` will no longer crash when given a `RemoteConfig`
2. The warning is no longer shown when looking at remote inheritence, because these files are not changable within the project. We already do the inverse when a …
> Fix crash when running `rubocop -d` on a config with a remote `inherit_from` that causes a duplicate setting warning

- .github/workflows/rubocop.yml
Now that Ruby 3.4 is out, `head` will relate to the 3.5 development branch, so 3.4 needs to be explicitly given.
PR for setup-ruby is here: https://github.com/ruby/setup-ruby/pull/677. Even though it's not yet merged (although I assume it will be shortly), an explicit "3.4" will still work (but refer to the release candidate for now).
`head` already is 3.5, as seen here: https://github.com/rubocop/rubocop/actions/runs/12496246734/job/34867800491?pr=13624#step:3:18 (can be seen in the GH actions of this PR as well)
> Add Ruby 3.4 to spec matrix

- changelog/fix_false_negatives_for_style_multiple_comparison.md
- lib/rubocop/cop/style/empty_else.rb
- lib/rubocop/cop/style/hash_syntax.rb
- lib/rubocop/cop/style/multiple_comparison.rb
- lib/rubocop/cop/style/yoda_condition.rb
- spec/rubocop/cop/style/multiple_comparison_spec.rb
Fixes #13623.
This PR fixes false negatives for `Style/MultipleComparison` when comparing with simple method calls.
> [Fix #13623] Fix false negatives for `Style/MultipleComparison`

- changelog/fix_cli_format_option_to_accept_fully_qualified_names.md
- lib/rubocop/formatter/formatter_set.rb
- spec/rubocop/cli/options_spec.rb
`FormatterSet#custom_formatter_class` accepts fully qualified constant names and there's even a spec for this (private) method. But since `#formatter_class` uses `/\A[A-Z]/` regexp to determine if provided formatter is custom, fully qualified values do not work with CLI.
> Fix `format` CLI option to accept fully qualified class names

- changelog/fix_style_missing_else_cop_error_on_configured_empty_else_cop.md
- lib/rubocop/cop/style/missing_else.rb
- spec/rubocop/cop/style/missing_else_spec.rb
If enforced style of `Style/EmptyElse` is not `both` cop `Style/MissingElse` raises on expressions with `elsif`.
See new test cases for details.
> Fix `Style/MissingElse` cop error if `Style/EmptyElse`'s style is not `both` and `if` expression contains `elsif`

- lib/rubocop/cli/command/execute_runner.rb
- lib/rubocop/runner.rb
- spec/rubocop/runner_spec.rb
Currently, these show a pretty useless backtrace at the end and stop further analysing.
Now it shows these errors at the end, like normal cop errors
<details><summary>Before</summary>
<p>
```
C
Offenses:
test.rb:8:3: C: [Corrected] Layout/HashAlignment: Align the keys and values of a hash literal if they span more than one line.
"deep" => { ...
^^^^^^^^^^^
test.rb:8:11: C: [Corrected] Layout/SpaceAroundOperators: Operator => should be surrounded by a single space.
"deep"  => {
^^
0 files inspected, 2 offenses detected, 2 offenses corrected
Infinite loop detected in /home/earlopain/Documents/test/test.rb and caused by Layout/HashAlignment -> Layout/SpaceAroundOperators
Hint: Please update to the latest RuboCop version if not already in use, and report a bug if the issue …
```
> Show infinite loop errors through the runner

- changelog/fix_fix_false_positive_for_naming_block_forwarding.md
- lib/rubocop/cop/naming/block_forwarding.rb
- spec/rubocop/cop/naming/block_forwarding_spec.rb
This change fixes a false positive for Naming/BlockForwarding with anonymous style, in the case where the method body just consists of the block argument, like so:
```
def foo(&block)
block
end
```
The actual change simply replaces `each_descendent` with `each_node`. This works because the method body in the problematic case consists just of the lvar node that should prevent an offense from being registered.
> Fix false positive for Naming/BlockForwarding

- LICENSE.txt
- README.md
- docs/modules/ROOT/pages/about/license.adoc
This PR bumps license years to 2025.
Happy New Year 🎉 
> Bump license years to 2025

- changelog/fix_false_negatives_for_style_multiple_comparison.md
- lib/rubocop/cop/style/multiple_comparison.rb
- spec/rubocop/cop/style/multiple_comparison_spec.rb
This PR makes `Style/MultipleComparison` respect `AllowMethodComparison: true (default)` when comparing with simple method calls.
#13627 resolved #13623, but to maintain the default `AllowMethodComparison: true`, comparisons involving method calls should always respect `AllowMethodComparison`.
This PR updates things so that the default `AllowMethodComparison: true` behavior remains compatible with what was released in 1.69.2, and if someone wants to address the issue from #13623, they can explicitly set `AllowMethodComparison: false`.
> Make `Style/MultipleComparison` respect `AllowMethodComparison: true`

- changelog/fix_style_float_division_cop_error_on_coercion_with_implicit_receiver.md
- lib/rubocop/cop/style/float_division.rb
- spec/rubocop/cop/style/float_division_spec.rb
Cop `Style/FloatDivision` fails on implicit `#to_f` receiver.
With `single_coerce` style:
```console
echo 'a.to_f / to_f' | rubocop --only Style/FloatDivision -c <(echo 'Style/FloatDivision:\n EnforcedStyle: single_coerce') --stdin bug.rb -d
An error occurred while Style/FloatDivision cop was inspecting bug.rb:1:0.
Expected a Parser::Source::Range, Comment or RuboCop::AST::Node, got NilClass
lib/rubocop/cop/corrector.rb:111:in `to_range'
lib/rubocop/cop/corrector.rb:120:in `check_range_validity'
lib/parser/source/tree_rewriter.rb:398:in `combine'
lib/parser/source/tree_rewriter.rb:194:in `replace'
lib/parser/source/tree_rewriter.rb:218:in `remove'
lib/rubocop/cop/style/float_division.rb:126:in `remove_to_f_method'
lib/rubocop/cop/style/float_division.rb:90:in `block in on_send'
```
With …
> Fix `Style/FloatDivision` cop error on implicit receiver

- lib/rubocop/cop/style/each_for_simple_loop.rb
- lib/rubocop/cop/style/mutable_constant.rb
- lib/rubocop/cop/style/random_with_offset.rb
`rubocop-ast` provides a neat method to make this possible.
> Simplify some `irange`/`erange` checks to simply `range`

- changelog/fix_style_class_and_module_children_cop_error_on_unindented_body.md
- lib/rubocop/cop/style/class_and_module_children.rb
- spec/rubocop/cop/style/class_and_module_children_spec.rb
If `Style/ClassAndModuleChildren` cop is configured with enforced style `compact`, the following code leads to and error (tree clobbering):
```ruby
module M
class C
def main; TOPLEVEL_BINDING; end
end
end
```
I patched the cop to skip indentation autocorrection in such cases; they should be handled by `Layout/IndentationWidth`.
> Fix `Style/ClassAndModuleChildren` cop error on `compact` enforced style and unindented body

- changelog/fix_false_positive_omit_parentheses.md
- lib/rubocop/cop/style/method_call_with_args_parentheses.rb
- lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb
- spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
When the range is open towards either the begin or ending, removing the parens can change meaning.
After the parens have been removed, either `Lint/RequireRangeParentheses`  or `Layout/SpaceInsideRangeLiteral` will complain further.
> [Fix #13645] Fix false positives for `Style/MethodCallWithArgsParentheses` and `omit_parentheses`

- changelog/change_update_layout_trailing_whitespace_to_support_blank_characters_other_than_space_and_tab.md
- lib/rubocop/cop/layout/trailing_whitespace.rb
- spec/rubocop/cop/layout/trailing_whitespace_spec.rb
This PR adds full-width spaces to `Layout/TrailingWhitespace`.
For example, in a Japanese IME, pressing the space key will enter a full-width space. This may cause unintentional full-width spaces to be entered, resulting in unexpected behavior.
It is unlikely that one would want to enter a trailing full-width space and should be removed.
> Add full-width space to `Layout/TrailingWhitespace`

- lib/rubocop/cop/layout/multiline_method_argument_line_breaks.rb
This pr updates the example for the `AllowMultilineFinalElement` configurable attribute for `Layout/MultilineMethodArgumentLineBreaks` to be `good` when `AllowMultilineFinalElement: true` and `bad` when `AllowMultilineFinalElement: false`
Before:
The example was
```
a,
b,
{
foo: "bar",
}
```
This is `good` in both cases and thus not particularly helpful
After:
I went with the example
```
a, b, {
foo: "bar",
}
```
This is `good` when `AllowMultilineFinalElement: true` and `bad` when `AllowMultilineFinalElement: false`
This matches the style the docs are currently in and is also close to the spec in `spec/rubocop/cop/layout/multiline_method_argument_line_breaks_spec.rb`
```
let(:cop_config) { { 'AllowMultilineFinalElement' => true } }
it 'ignores last argument that is a multiline hash' do …
```
> Update example for the `AllowMultilineFinalElement` configurable attribute for `Layout/MultilineMethodArgumentLineBreaks`

- lib/rubocop/config_loader.rb
- spec/rubocop/cli/options_spec.rb
- spec/rubocop/target_finder_spec.rb
Prior to this change, running `bundle exec rspec ./spec/rubocop/cli/options_spec.rb[1:1:3:1,1:2:1:1] ./spec/rubocop/target_finder_spec.rb[1:1:8:2:2:1,1:2:5:2:2:1] --seed 37240` would cause test failures. Updated to clear `ConfigLoader` state before specs in `cli/options_spec.rb` and `target_finder_spec.rb`.
Fixes #13604.
> Fix leaking `ConfigLoader` state in specs

- changelog/change_update_metrics_method_length_to_make_use_of.md
- lib/rubocop/cop/metrics/method_length.rb
- spec/rubocop/cop/metrics/method_length_spec.rb
Previously, `AllowedMethods` and `AllowedPatterns` were added to `Metrics/MethodLength` to allow specified methods to be longer than the configured maximum. However, this was not also applied to dynamic methods defined with `define_method`, which the cop also covers.
This change allows the allow lists to apply to dynamic methods as well.
> Update `Metrics/MethodLength` to make use of `AllowedMethods` and `AllowedPatterns` for methods defined dynamically with `define_method`

- changelog/fix_false_positives_for_style_redundant_initialize.md
- lib/rubocop/cop/style/redundant_initialize.rb
- spec/rubocop/cop/style/redundant_initialize_spec.rb
This fixes a false positive in the `Style/RedundantInitialize` cop when an empty initialize method is defined to accept arguments for duck typing purposes.
> Fix a false positive for `Style/RedundantInitialize`

- changelog/change_add_support_for_safe_navigation_to_layout_line_length.md
- lib/rubocop/cop/layout/line_length.rb
- lib/rubocop/cop/mixin/check_line_breakable.rb
- spec/rubocop/cop/layout/line_length_spec.rb
`Layout/LineLength` can currently autocorrect send nodes but not csend nodes, this extends the same correction to all method calls regardless of dot type. 
> Add support for safe navigation to `Layout/LineLength`

- changelog/change_add_support_for_safe_navigation_to_layout_heredoc_argument.md
- lib/rubocop/cop/layout/heredoc_argument_closing_parenthesis.rb
- spec/rubocop/cop/layout/heredoc_argument_closing_parenthesis_spec.rb
Allow `Layout/HeredocArgumentClosingParenthesis` to consider heredocs attached to a safe navigation method call. 
For consistency, I took all the existing tests and put them into shared examples so that they could be run against normal method calls as well as safe nav.
> Add support for safe navigation to `Layout/HeredocArgumentClosingParenthesis`

- changelog/change_add_support_for_safe_navigation_to_layout_hash_alignment.md
- lib/rubocop/cop/layout/hash_alignment.rb
- spec/rubocop/cop/layout/hash_alignment_spec.rb
Previously, `Layout/HashAlignment` ignored certain `send` nodes based on `EnforcedLastArgumentHashStyle` configuration, but this was not applied to safe navigation.
> Add support for safe navigation to `Layout/HashAlignment`

- changelog/change_add_support_for_safe_navigation_to.md
- lib/rubocop/cop/style/object_then.rb
- spec/rubocop/cop/style/object_then_spec.rb
Allow `Style/ObjectThen` to detect offenses when `then` or `yield_self` is used with safe navigation.
> Add support for safe navigation to `Style/ObjectThen`

- config/default.yml
- lib/rubocop/cop/style/redundant_current_directory_in_path.rb
`Style/RedundantCurrentDirectoryInPath` only considers paths given to `require_relative`, but this was not made clear from the documentation.
> [Doc] Improve documentation of `Style/RedundantCurrentDirectoryInPath` to point out that it only applies to `require_relative`

- changelog/change_update_style_redundant_self_assignment_to_handle.md
- lib/rubocop/cop/style/redundant_self_assignment.rb
- spec/rubocop/cop/style/redundant_self_assignment_spec.rb
Handle safe navigation on the RHS of assignment in `Style/RedundantSelfAssignment`.
For instance:
```ruby
foo = foo&.concat(ary)
self.foo = foo&.concat(ary)
other.foo = other.foo&.concat(ary)
other&.foo = other&.foo&.concat(ary)
```
These cases are now registered and corrected.
> Update `Style/RedundantSelfAssignment` to handle safe navigation on the right-hand side of the assignment

- changelog/change_fix_invalid_autocorrect_for.md
- lib/rubocop/cop/style/slicing_with_range.rb
- spec/rubocop/cop/style/slicing_with_range_spec.rb
Previously, `Style/SlicingWithRange` would autocorrect code such as `ary.[](0..-1)` to `ary.(0..-1)`, which is obviously incorrect. 
This updates the cop to handle `.[]` and `&.[]` correctly.
> Fix invalid autocorrect for `Style/SlicingWithRange` when calling `.[]` or `&.[]` with a correctable range

- docs/modules/ROOT/pages/configuration.adoc
Follow up https://github.com/rubocop/rubocop/pull/13653#discussion_r1907681441.
This PR adds "Setting the version tracking metadata for cops" section to configuration.adoc.
`VersionAdded`, `VersionChanged`, and `VersionRemoved` are only mentioned in #5978 and have not been documented. The content remains as described in #5978.
> [Doc] Add "Setting the version tracking metadata for cops" section

- changelog/change_add_support_for_safe_navigation_to_style_send_with_literal.md
- lib/rubocop/cop/style/send_with_literal_method_name.rb
- spec/rubocop/cop/style/send_with_literal_method_name_spec.rb
Handle `obj&.public_send` in `Style/SendWithLiteralMethodName`.
> Add support for safe navigation to `Style/SendWithLiteralMethodName`

- changelog/change_update_style_access_modifier_declarations_to_add.md
- config/default.yml
- lib/rubocop/cop/style/access_modifier_declarations.rb
- spec/rubocop/cop/style/access_modifier_declarations_spec.rb
Since `alias_method` returns a symbol of the new alias, it can be chained with an access modifier. This change allows code such as (or disallows it, if `AllowModifiersOnAliasMethod` is set to `false`):
```ruby
private alias_method :foo, :bar
```
Fixes #13606.
> [Fix #13606] Update `Style/AccessModifierDeclarations` to add `AllowModifiersOnAliasMethod` configuration (default `true`)

- Gemfile
- changelog/new_make_lsp_server_support_quick_fix_code_aciton.md
- changelog/new_support_ruby_lsp_addon.md
- lib/rubocop/lsp/diagnostic.rb
- lib/rubocop/lsp/logger.rb
- lib/rubocop/lsp/routes.rb
- lib/rubocop/lsp/runtime.rb
- lib/rubocop/lsp/stdin_runner.rb
- lib/ruby_lsp/rubocop/addon.rb
- lib/ruby_lsp/rubocop/wraps_built_in_lsp_runtime.rb
- spec/fixtures/ruby_lsp/example.rb
- spec/rubocop/lsp/server_spec.rb
- spec/ruby_lsp/rubocop/addon_spec.rb
This PR adds support for the Ruby LSP Add-on:
https://shopify.github.io/ruby-lsp/add-ons.html
Ruby LSP is widely used among Ruby developers.
This Add-on resolves the current dependency of Ruby LSP on RuboCop's internal APIs by allowing RuboCop itself to provide the features related to Ruby LSP, marking the start of potentially removing these dependencies in the future.
It may also be possible to integrate the Standard Ruby's LSP implementation into this RuboCop's LSP implementation at a later time. A future is envisioned in which Ruby LSP, Standard Ruby, and RuboCop don't each need to implement their own RuboCop runner for LSP but instead unify that functionality.
An option is available so it can work with both RuboCop's built-in LSP and Ruby LSP. RuboCop's built-in LSP will continue to …
> Add support for Ruby LSP as a built-in add-on

- Gemfile
- spec/ruby_lsp/rubocop/addon_spec.rb
This PR fixes the following build errors related to the RubyLSP add-on specs:
```console
$ bundle exec rspec ./spec/ruby_lsp/rubocop/addon_spec.rb
(snip)
6 examples, 5 failures
rspec ./spec/ruby_lsp/rubocop/addon_spec.rb:104 # RubyLSP::RuboCop::Addon textDocument/formatting has basic result information
rspec ./spec/ruby_lsp/rubocop/addon_spec.rb:109 # RubyLSP::RuboCop::Addon textDocument/formatting has autocorrected code
rspec ./spec/ruby_lsp/rubocop/addon_spec.rb:60 # RubyLSP::RuboCop::Addon textDocument/diagnostic has first diagnostic information
rspec ./spec/ruby_lsp/rubocop/addon_spec.rb:72 # RubyLSP::RuboCop::Addon textDocument/diagnostic has second diagnostic information
rspec ./spec/ruby_lsp/rubocop/addon_spec.rb:54 # RubyLSP::RuboCop::Addon textDocument/diagnostic …
```
> Fix build errors related to the RubyLSP add-on specs

- changelog/fix_style_hash_except_when_using_safe_navigation_with_active_support.md
- lib/rubocop/cop/style/hash_except.rb
- spec/rubocop/cop/style/hash_except_spec.rb
Fixes `Style/HashExcept` to recognize offenses when safe navigation is used and `ActiveSupportExtensionsEnabled` config option is enabled.
Previously, this code:
```ruby
{foo: 1, bar: 2, baz: 3}&.reject { |k, v| k.in?(%i[foo bar]) }
```
wouldn't register as offense (but without safe nav it would). Now it registers and autocorrects to:
```ruby
{foo: 1, bar: 2, baz: 3}&.except(:foo, :bar)
```
Additional context for the refactoring done in this PR: https://github.com/rubocop/rubocop/pull/13507#discussion_r1861491315
> Fix `Style/HashExcept` to recognize safe navigation with Active Support methods

- changelog/fix_dont_show_warnings_when_syntax_error.md
- lib/rubocop/cop/lint/syntax.rb
- spec/rubocop/cop/lint/syntax_spec.rb
```rb
{ a: a, a: a }
(
```
```
Offenses:
code.rb:1:9: F: Lint/Syntax: key is duplicated and overwritten
(Using Ruby 3.4 parser; configure using TargetRubyVersion parameter, under AllCops)
{ a: a, a: a }
^
code.rb:4:1: F: Lint/Syntax: unexpected token $end
(Using Ruby 3.4 parser; configure using TargetRubyVersion parameter, under AllCops)
1 file inspected, 2 offenses detected
```
This caused me quite the confusion... In prism, the useless literal warning for `/#{"\xcd"}/
` was masking the actual syntax error because they both had the same location, and the parser gem simply doesn't implement that warning.
> Dont show parser warnings in `Lint/Syntax`

- changelog/fix_maintain_precedence_in_autocorrect_for.md
- lib/rubocop/cop/style/sole_nested_conditional.rb
- spec/rubocop/cop/style/sole_nested_conditional_spec.rb
For comparison operators
Closes https://github.com/rubocop/rubocop/issues/13667
> [Fix #13667] Maintain precedence in autocorrect for `Style/SoleNestedConditional`

- changelog/fix_style_frozen_string_literal_comment_cop_error_on_weird_magic_comment.md
- lib/rubocop/cop/mixin/frozen_string_literal.rb
- lib/rubocop/cop/style/frozen_string_literal_comment.rb
- spec/rubocop/cop/style/frozen_string_literal_comment_spec.rb
If `Style/FrozenStringLiteralComment` is configured with enforced style `never` any unnormalized magic comment (e.g. `frozen-string-literal: true`) leads to an error:
```
NoMethodError:
undefined method `pos' for nil
```
> Fix `Style/FrozenStringLiteralComment` cop error on unnormalized magic comment and `never` enforced style

- changelog/change_add_support_for_safe_navigation_to_map_to_set.md
- lib/rubocop/cop/style/map_to_set.rb
- spec/rubocop/cop/style/map_to_set_spec.rb
Handles safe navigation in `map.to_set` method chains:
```
foo&.map { |x| [x, x * 2] }&.to_set
^^^ Pass a block to `to_set` instead of calling `map.to_set`.
```
> Add support for safe navigation to `Style/MapToSet`

- changelog/change_add_support_for_safe_navigation_to.md
- lib/rubocop/cop/style/collection_methods.rb
- spec/rubocop/cop/style/collection_methods_spec.rb
Handles safe navigation with non-preferred collection methods:
```
[1, 2, 3].detect { |e| e + 1 }
^^^^^^ Prefer `find` over `detect`.
```
> Add support for safe navigation to `Style/CollectionMethods`

- changelog/change_add_support_for_safe_navigation_to_method_call_without_args_parens.md
- lib/rubocop/cop/style/method_call_without_args_parentheses.rb
- spec/rubocop/cop/style/method_call_without_args_parentheses_spec.rb
Handles safe navigation method calls with unnecessary parens:
```
test = x&.test()
^^ Do not use parentheses for method calls with no arguments.
```
> Add support for safe navigation to `Style/MethodCallWithoutArgsParentheses`

- changelog/fix_fix_invalid_autocorrect_for_style_array_first_last.md
- lib/rubocop/cop/style/array_first_last.rb
- spec/rubocop/cop/style/array_first_last_spec.rb
`Style/ArrayFirstLast` previously mistakenly autocorrected code such as `ary.[](0)` to `ary..first(0)`.
This updates the autocorrection to handle `.[](0)` and `&.[](0)` correctly with `first`, and `.[](-1)` and `&.[](-1)` correctly with `last`.
> Fix invalid autocorrect for `Style/ArrayFirstLast` when calling `.[]` or `&.[]` with 0 or -1

- lib/rubocop/cop/layout/argument_alignment.rb
`Layout/ArgumentAlignment` checks method calls, not definitions.
> [DOC] Fix `Layout/ArgumentAlignment`

- changelog/change_add_support_for_safe_navigation_to_block_delimiters.md
- lib/rubocop/cop/style/block_delimiters.rb
- spec/rubocop/cop/style/block_delimiters_spec.rb
Although a lot of save navigation code was already handled by `Style/BlockDelimiters`, this updates the cop to ignore certain safe navigation method calls that require braces to avoid changing semantics.
For example, changing the braces to do-end in this case:
```ruby
foo&.bar baz {
y
}
```
This follows #13499.
> Add support for safe navigation to `Style/BlockDelimiters`

- spec/rubocop/cop/style/redundant_line_continuation_spec.rb
There was no test covering `string_concatenation?`, but the code is critical, `rubocop` detects 291 offenses without it. I added tests to cover.
Thanks to @Earlopain for pointing it out.
> Add missing test for string concatenation using continuations in `spec/rubocop/cop/style/redundant_line_continuation_spec.rb`

- changelog/fix_fix_syntax_error_introduced_by.md
- lib/rubocop/cop/lint/safe_navigation_chain.rb
- spec/rubocop/cop/lint/safe_navigation_chain_spec.rb
When an operator called without a dot is inside a hash, parentheses are needed in order to ensure valid syntax.
```
$ ruby -cwe '{ foo: a&.baz&.+ 1 }'
-e:1: warning: possibly useless use of a literal in void context
ruby: -e:1: syntax errors found (SyntaxError)
> 1 | { foo: a&.baz&.+ 1 }
|                 ^ expected a `}` to close the hash literal
|                  ^ unexpected integer, expecting end-of-input
|                    ^ unexpected '}', ignoring it
|                    ^ unexpected '}', expecting end-of-input
```
```
$ ruby -cwe '{ foo: (a&.baz&.+ 1) }'
Syntax OK
```
Fixes #13685.
> [Fix #13685] Fix syntax error introduced by `Lint/SafeNavigationChain` when adding safe navigation to an operator call inside a hash

- changelog/fix_style_conditional_assignment_cop_error_on_unless_without_else_and_assign_inside_condition_enforced_style.md
- lib/rubocop/cop/style/conditional_assignment.rb
- spec/rubocop/cop/style/conditional_assignment_assign_in_condition_spec.rb
If `Style/ConditionalAssignment` cop is configured with `assign_inside_condition` enforced style and `unless` node does not have `else` branch and error occurs.
```console
NoMethodError:
undefined method `begin_type?' for nil
Shared Example Group: "single line condition autocorrect" called from ./spec/rubocop/cop/style/conditional_assignment_assign_in_condition_spec.rb:920
```
There are actually two bugs, depending on `SingleLineConditionsOnly` confiuration option. Both are fixed.
> Fix `Style/ConditionalAssignment` cop error on `unless` without `else` and `assign_inside_condition` enforced style

- changelog/fix_fix_false_positive_in_redundant_line_continuation_eof.md
- lib/rubocop/cop/style/redundant_line_continuation.rb
- spec/rubocop/cop/style/redundant_line_continuation_spec.rb
If a commented out continuation is at the end of ruby code, a false positive for `Style/RedundantLineContinuation` is registered.
```ruby
foo # /
```
> Fix false positive in `Style/RedundantLineContinuation` when the ruby  code ends with a commented continuation

- spec/ruby_lsp/rubocop/addon_spec.rb
Fix #13683
`ruby-lsp` enables LSP mode (makes sense). Ideally the two requires should happen in isolation, but for now this prevents it from failing unrelated tests.
> [Fix #13683] Prevent `ruby-lsp` from failing unrelated tests

- changelog/fix_update_metrics_collection_literal_length_to_only.md
- lib/rubocop/cop/metrics/collection_literal_length.rb
- spec/rubocop/cop/metrics/collection_literal_length_spec.rb
As per #11584, `Metrics/CollectionLiteralLength` was only intended to apply to collection literals (`[]`, `{}` and `Set[]`), but the cop was too restrictive, so `foo[...]` would register an offense with more than `LengthThreshold` elements.
> Update `Metrics/CollectionLiteralLength` to only register for `[]` when called on `Set`

- changelog/change_add_support_for_safe_navigation_to_redundant_string_coercion.md
- lib/rubocop/cop/lint/redundant_string_coercion.rb
- spec/rubocop/cop/lint/redundant_string_coercion_spec.rb
Registers a `Lint/RedundantStringCoercion` for code such as:
```ruby
"this is the #{result&.to_s}"
puts result&.to_s
```
> Add support for safe navigation to `Lint/RedundantStringCoercion`

- docs/modules/ROOT/pages/configuration.adoc
RuboCop does not search in the root directory.
> [DOC] Fix config file locations

- changelog/fix_false_positives_for_lint_out_of_range_regexp_ref.md
- lib/rubocop/cop/lint/out_of_range_regexp_ref.rb
- spec/rubocop/cop/lint/out_of_range_regexp_ref_spec.rb
Fixes #13704.
This PR fixes false positives for `Lint/OutOfRangeRegexpRef` when matching with `match` using safe navigation.
> [Fix #13704] Fix false positives for `Lint/OutOfRangeRegexpRef`

- changelog/change_add_support_for_safe_navigation_to_numeric_operation_with_constant_result.md
- lib/rubocop/cop/lint/numeric_operation_with_constant_result.rb
- spec/rubocop/cop/lint/numeric_operation_with_constant_result_spec.rb
Registers a `Lint/NumericOperationWithConstantResult` offense for code such as:
```ruby
x&.*(0)
x&./(x)
```
Also did a small refactor to avoid calling node pattern matchers more than once unnecessarily.
> Add support for safe navigation to `Lint/NumericOperationWithConstantResult`

- changelog/fix_a_false_positive_for_style_frozen_string_literal_comment.md
- config/default.yml
- spec/rubocop/cli/auto_gen_config_spec.rb
This PR fixes a false positive for `Style/FrozenStringLiteralComment` when using the frozen string literal magic comment in Active Admin's arb files.
Fixes #13684.
> [Fix #13684] Fix a false positive for `Style/FrozenStringLiteralComment`

- spec/tasks/changelog_spec.rb
- tasks/changelog.rb
When the first 50 characters of a commit message are the same in multiple commits, `rake changelog:*` will generate the same filename for each of the commits, resulting in file clobbering and missed changelog entries.
By appending the current timestamp to the end of the filename, we should avoid this issue.
NB: A byproduct of this is that running `rake changelog:*` again on the same commit will generate an additional changelog entry.
> Append timestamp to generated changelog files to avoid clobbering

- changelog/fix_fix_false_negative_on.md
- lib/rubocop/cop/style/redundant_line_continuation.rb
- spec/rubocop/cop/style/redundant_line_continuation_spec.rb
Previously, `ends_with_backslash_without_comment?` considered any `#` character in the line to be the start of a comment, however an interpolated string also starts with an `#.` The method is now updated to exclude interpolation, and renamed to `ends_with_uncommented_backslash?`.
Fixes #13688.
> [Fix #13688] Fix false negative on `Style/RedundantLineContinuation` when the continuation is preceded by an interpolated string

- changelog/fix_disable_department_ignores_excludes.md
- lib/rubocop/comment_config.rb
- lib/rubocop/directive_comment.rb
- spec/rubocop/cli_spec.rb
- spec/rubocop/directive_comment_spec.rb
Fix #13257
When a whole department is enabled, then that cop would also run for code outside of that block, even if it is explicitly excluded via cop config.
This comes from https://github.com/rubocop/rubocop/pull/11603 were cops didn't run when explicitly enabled via `Department/Cop` but that logic should only apply when the cop is fully qualified.
> [Fix #13257] Don't consider cops to be opted in for department enables

- changelog/fix_cache_pruning_path_when_cache_root_specified_with_cli_option.md
- lib/rubocop/result_cache.rb
- spec/rubocop/result_cache_spec.rb
Fixes #13372.
This PR fixes inconsistent cache directory calculation during cache pruning when the `--cache-root` CLI option is used instead of ENV or YAML configuration.
In this work, I renamed method arguments and local variables to try to better distinguish among "cache root override" (an optional value), "cache root" e.g. `.cache`, and "cache working directory" e.g. `.cache/rubocop_cache`.
> [Fix #13372] Fix inconsistent cache directory when using --cache-root

- lib/rubocop/cop/style/trailing_comma_in_arguments.rb
Clarified that this cop requires trailing commas only for multi-line method calls.
> [DOC] Update `Style/TrailingCommaInArguments`

- changelog/change_add_support_for_safe_navigation_to_20250116114656.md
- lib/rubocop/cop/lint/float_comparison.rb
- spec/rubocop/cop/lint/float_comparison_spec.rb
Adds support to the cop for code such as:
```ruby
x&.eql?(1.0)
x&.equal?(1.0)
```
Also improves the message to be specific about equality/inequality.
> Add support for safe navigation to `Lint/FloatComparison`

- lib/rubocop/cop/layout/space_around_keyword.rb
`on_send` is only used for `not` keywords, so we can restrict to it to `:!` methods, which is how `not` is parsed.
> Set `RESTRICT_ON_SEND` for `Layout/SpaceAroundKeyword`

- changelog/change_add_support_for_safe_navigation_to_20250116122319.md
- lib/rubocop/cop/layout/multiline_method_call_brace_layout.rb
- spec/rubocop/cop/layout/multiline_method_call_brace_layout_spec.rb
Allows `Layout/MultilineMethodCallBraceLayout` to register offenses on methods called with safe navigation.
> Add support for safe navigation to `Layout/MultilineMethodCallBraceLayout`

- lib/rubocop/cops_documentation_generator.rb
In the [documentation](https://docs.rubocop.org/rubocop/cops_style.html#styleyodaexpression) of `Style/YodaExpression`, an empty table appears in the Configurable attributes section.
This PR removes it.
> Omit an empty configurable attributes section in documentation

- lib/rubocop/cop/internal_affairs/redundant_source_range.rb
- spec/rubocop/cop/internal_affairs/redundant_source_range_spec.rb
I only updated the cop for `node&.source_range&.source`, because the other variations (eg. `add_offense(node.source_range)`, `corrector.replace(node.source_range, ...)`, etc.) don't make sense to use when a potentially nil node.
> Add support for safe navigation to `InternalAffairs/RedundantSourceRange`

- lib/rubocop/cop/internal_affairs/single_line_comparison.rb
- spec/rubocop/cop/internal_affairs/single_line_comparison_spec.rb
Registers a `InternalAffairs/SingleLineComparison`for code such as:
```ruby
node&.first_line == node&.last_line
```
> Add support for safe navigation to `InternalAffairs/SingleLineComparison`

- changelog/change_add_support_for_safe_navigation_to_20250116130920.md
- lib/rubocop/cop/security/compound_hash.rb
- spec/rubocop/cop/security/compound_hash_spec.rb
Registers a `Security/CompoundHash` for code such as:
```ruby
[foo&.hash, bar&.hash].hash
```
> Add support for safe navigation to `Security/CompoundHash`

- changelog/change_add_support_for_safe_navigation_to_20250116124756.md
- lib/rubocop/cop/layout/multiline_method_argument_line_breaks.rb
- spec/rubocop/cop/layout/multiline_method_argument_line_breaks_spec.rb
Allows `Layout/MultilineMethodArgumentLineBreaks` to register offenses on methods called with safe navigation.
> Add support for safe navigation to `Layout/MultilineMethodArgumentLineBreaks`

- lib/rubocop/cop/internal_affairs/node_first_or_last_argument.rb
- spec/rubocop/cop/internal_affairs/node_first_or_last_argument_spec.rb
Registers an `InternalAffairs/NodeFirstOrLastArgument` offense for code such as:
```ruby
node.arguments&.first
node&.arguments&.last
node&.arguments[0]
node&.arguments[-1]
```
> Add support for safe navigation to `InternalAffairs/NodeFirstOrLastArgument`

- lib/rubocop/cop/internal_affairs/location_expression.rb
- spec/rubocop/cop/internal_affairs/location_expression_spec.rb
Registers an `InternalAffairs/LocationExpression` offense for code such as:
```ruby
node&.location&.expression
```
> Add support for safe navigation to `InternalAffairs/LocationExpression`

- changelog/fix_false_positives_for_style_block_delimiters.md
- lib/rubocop/cop/style/block_delimiters.rb
- spec/rubocop/cop/style/block_delimiters_spec.rb
This PR fixes false positives for `Style/BlockDelimiters` when using brace blocks as conditions under `EnforcedStyle: semantic`.
Fixes #13720.
> [Fix #13720] Fix false positives for `Style/BlockDelimiters`

- lib/rubocop/cop/metrics/cyclomatic_complexity.rb
- lib/rubocop/cop/metrics/perceived_complexity.rb
- spec/rubocop/cop/metrics/cyclomatic_complexity_spec.rb
- spec/rubocop/cop/metrics/perceived_complexity_spec.rb
Adds highlighting to the method name in `Metrics/CyclomaticComplexity`and `Metrics/PerceivedComplexity` offenses.
> Add highlighting to `Metrics/CyclomaticComplexity` and `PerceivedComplexity` offense messages

- changelog/change_make_style_redundant_parentheses_aware_of_parenthesized_assignment.md
- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
This PR makes `Style/RedundantParentheses` aware of parenthesized assignment.
> Make `Style/RedundantParentheses` aware of parenthesized assignment

- changelog/fix_incorrect_autocorrect_for_style_if_unless_modifier.md
- lib/rubocop/cop/mixin/statement_modifier.rb
- spec/rubocop/cop/style/if_unless_modifier_spec.rb
This PR fixes an incorrect autocorrect for `Style/IfUnlessModifier` when using omitted hash values in an assignment.
Fixes #13725.
> [Fix #13725] Fix an incorrect autocorrect for `Style/IfUnlessModifier`

- changelog/fix_rubocop_error_on_glob_pattern_and_matching_directory.md
- lib/rubocop/target_finder.rb
- spec/rubocop/target_finder_spec.rb
For this project layout
```console
app/        # dir
data.rb/  # dir
ruby.rb # file
```
when running rubocop with explicit glob pattern (e.g. `rubocop '/app/**/*.rb'`) it fails with the following error
```
Is a directory @ io_fread - <snip>/app/data.rb
lib/ruby/3.4.0/digest.rb:66:in 'IO#read'
lib/ruby/3.4.0/digest.rb:66:in 'block in Digest::Instance#file'
lib/ruby/3.4.0/digest.rb:64:in 'IO.open'
lib/ruby/3.4.0/digest.rb:64:in 'Digest::Instance#file'
lib/rubocop/result_cache.rb:161:in 'RuboCop::ResultCache#file_checksum'
lib/rubocop/result_cache.rb:95:in 'RuboCop::ResultCache#initialize'
lib/rubocop/runner.rb:175:in 'Class#new'
lib/rubocop/runner.rb:175:in 'RuboCop::Runner#cached_result'
lib/rubocop/runner.rb:180:in 'RuboCop::Runner#file_offense_cache'
lib/rubocop/runner.rb:167:in …
```
> Fix rubocop error on provided glob pattern matching directory

- lib/rubocop/cop/layout/class_structure.rb
- lib/rubocop/cop/layout/first_hash_element_indentation.rb
- lib/rubocop/cop/lint/duplicate_regexp_character_class_element.rb
- lib/rubocop/cop/lint/duplicate_set_element.rb
- lib/rubocop/cop/lint/float_out_of_range.rb
- lib/rubocop/cop/lint/mixed_case_range.rb
- lib/rubocop/cop/lint/mixed_regexp_capture_types.rb
- lib/rubocop/cop/lint/numeric_operation_with_constant_result.rb
- lib/rubocop/cop/lint/out_of_range_regexp_ref.rb
- lib/rubocop/cop/lint/redundant_regexp_quantifiers.rb
- lib/rubocop/cop/lint/rescue_exception.rb
- lib/rubocop/cop/lint/shared_mutable_default.rb
- lib/rubocop/cop/lint/useless_assignment.rb
- lib/rubocop/cop/style/each_for_simple_loop.rb
- lib/rubocop/cop/style/exact_regexp_match.rb
- lib/rubocop/cop/style/fetch_env_var.rb
- lib/rubocop/cop/style/hash_each_methods.rb
- lib/rubocop/cop/style/mutable_constant.rb
- lib/rubocop/cop/style/raise_args.rb
- lib/rubocop/cop/style/redundant_exception.rb
- lib/rubocop/cop/style/redundant_freeze.rb
- lib/rubocop/cop/style/redundant_regexp_character_class.rb
- lib/rubocop/cop/style/redundant_regexp_escape.rb
- lib/rubocop/cop/style/single_line_block_params.rb
- lib/rubocop/cop/style/string_methods.rb
This PR quotes class/method names with backticks to properly marked up.
> [DOC] Quote class/method names with backticks

- .github/workflows/stale.yml
Every night the stale action runs on my fork (and everyone else's whose fork is up to date), so let's just limit it to the main repository.
> Update stale GH action to only run on the original repo, and not forks

- Gemfile
Fixes `Gem::LoadError: You have already activated jar-dependencies 0.4.1, but your Gemfile requires jar-dependencies 0.5.2. Since jar-dependencies is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports jar-dependencies as a default gem.`
> Fix jruby CI error

- .github/workflows/linting.yml
- .github/workflows/rubocop.yml
- .github/workflows/spell_checking.yml
- .github/workflows/stale.yml
This reverts commit be6c04c9947a23b359acbde7b94417f8b666d8a7.
Unfortunately, the arm64 runners are not stable enough yet. To prioritize CI stability over speed improvements, https://github.com/rubocop/rubocop/pull/13731 will be reverted.
cc @bquorning 
> Revert "CI: Use arm64 runners"

- lib/rubocop/cop/layout/access_modifier_indentation.rb
"class" and "module" are used as keywords here, so it would be better to quote them.
> [DOC] Quote keywords

- changelog/fix_fix_false_positive_for_style_hash_except_and_20250123131635.md
- lib/rubocop/cop/mixin/hash_subset.rb
- spec/rubocop/cop/style/hash_except_spec.rb
- spec/rubocop/cop/style/hash_slice_spec.rb
`Style/HashExcept` and `Style/HashSlice` look for instances where `select` or `reject` blocks called on a hash can be replaced with `slice` or `except`. However, when the receiver of `include?` or the argument of `in?` is a range, this replacement can definitely not be made.
Fixes #13739.
> [Fix #13739] Fix false positive for `Style/HashExcept` and `Style/HashSlice` when checking for inclusion with a range

- .rubocop.yml
- spec/rubocop/lsp/severity_spec.rb
- spec/support/strict_warnings.rb
This PR updates `EnforcedStyle` of `RSpec/ExampleWithoutDescription` from `always_allow` (default) to `single_line_only` for development.
This repository typically does not use the following style.
```ruby
it do
...
end
```
In this case, descriptions are always written in `it`.
Follow up https://github.com/rubocop/rubocop/pull/13729#discussion_r1925634885.
> Update `EnforcedStyle` of `RSpec/ExampleWithoutDescription`

- changelog/fix_add_the_missing_include_20250127124604.md
- lib/rubocop/rspec/support.rb
- spec/spec_helper.rb
This PR adds missing `config.include RuboCop::RSpec::ExpectOffense`. This fixes #10081 
The `ExpectOffense` class is not referenced anywhere else in the code (other than rubocop's own spec_helper) and is not mentioned in the documentation so I assume it should be added automatically like this. If not, let me know and I'll send a PR updating the docs and mentioning it needs to be enabled explicitly instead.
> Add missing ExpectOffense include

- changelog/fix_false_negative_block_forwading_34.md
- lib/rubocop/cop/naming/block_forwarding.rb
- lib/rubocop/cop/style/arguments_forwarding.rb
- spec/rubocop/cop/naming/block_forwarding_spec.rb
- spec/rubocop/cop/style/arguments_forwarding_spec.rb
This worked around a bug in Ruby 3.3.0, where this syntax was accidentally disallowed. This check can now be reenabled for 3.4 where all versions accept it.
Reference:
* https://github.com/rubocop/rubocop/issues/12571
* https://github.com/rubocop/rubocop/pull/12577
* https://github.com/rubocop/rubocop/pull/12578
* https://bugs.ruby-lang.org/issues/20090
> Correctly handle anonymous block forwarding in blocks for Ruby >= 3.4

- changelog/fix_constant_definition_in_block_false_negative.md
- lib/rubocop/cop/lint/constant_definition_in_block.rb
- spec/rubocop/cop/lint/constant_definition_in_block_spec.rb
> Fix a false negative for `Lint/ConstantDefinitionInBlock` with numblocks

- lib/rubocop/cop/internal_affairs/redundant_source_range.rb
- spec/rubocop/cop/internal_affairs/redundant_source_range_spec.rb
`InternalAffairs/RedundantSourceRange` expects a receiver for `source_range`, so when one is not present, it was crashing. This updates the cop to ignore instances without a receiver.
> Fix crash in `InternalAffairs/RedundantSourceRange` when `source_range` has no receiver

- changelog/fix_false_positive_super_arguments_numblock.md
- lib/rubocop/cop/style/super_arguments.rb
- spec/rubocop/cop/style/super_arguments_spec.rb
Pretty much https://github.com/rubocop/rubocop/pull/12959/https://github.com/rubocop/rubocop/issues/12957
The existing test was wrong (same as the normal block one), adapt it
> Fix a false positive for `Style/SuperArguments` when calling super in a numblock

- changelog/fix_ambig_block_assoc_numblocks.md
- lib/rubocop/cop/lint/ambiguous_block_association.rb
- spec/rubocop/cop/lint/ambiguous_block_association_spec.rb
Again, not really much to explain
> Fix a false negative for `Lint/AmbiguousBlockAssociation` with numblocks

- changelog/fix_false_positive_unreachable_code_numblock.md
- lib/rubocop/cop/lint/unreachable_code.rb
- spec/rubocop/cop/lint/unreachable_code_spec.rb
> Fix a false positive for `Lint/UnreachableCode` with `instance_eval` numblock

- changelog/fix_false_negative_redundant_parens_numblock.md
- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
Use `type?` to make it more concise
> Fix a false negative for `Style/RedundantParentheses` with numblocks

- changelog/fix_wrong_autocorrect_sole_nested_cond_numblock.md
- lib/rubocop/cop/style/sole_nested_conditional.rb
- spec/rubocop/cop/style/sole_nested_conditional_spec.rb
See https://github.com/rubocop/rubocop/pull/10886
> Fix wrong autocorrect for `Style/SoleNestedConditional` when using numblocks

- changelog/fix_fix_style_identical_conditional_branches_20250129114423.md
- lib/rubocop/cop/style/identical_conditional_branches.rb
- spec/rubocop/cop/style/identical_conditional_branches_spec.rb
Previously, `Style/IdenticalConditionalBranches` would autocorrect inside an assignment improperly:
```ruby
y = if foo
bar
else
bar
end
y = if foo
else
end
bar
```
Before the correction, `y` would be assigned `bar`, but after `y` would be assigned `nil`.
This fixed the correction to correct to this instead:
```
if foo
else
end
y = bar
```
> Fix `Style/IdenticalConditionalBranches` autocorrect when condition is inside assignment

- changelog/fix_false_positive_for_layout_redundant_line_break_cop.md
- lib/rubocop/cop/layout/redundant_line_break.rb
- spec/rubocop/cop/layout/redundant_line_break_spec.rb
This PR fixes false positives for `Layout/RedundantLineBreak` when using numbered block parameter.
> Fix false positives for `Layout/RedundantLineBreak`

- Gemfile
This reverts commit b3c80614d9922d9e2d0e376e6464af1b6e85a196.
JRuby 9.4.11.0 has been released and it is available on CI. https://www.jruby.org/2025/01/29/jruby-9-4-11-0
> Remove workaround gem dependency from Gemfile for JRuby CI matrix

- changelog/fix_false_positive_assign_in_cond_numblock.md
- lib/rubocop/cop/lint/assignment_in_condition.rb
- spec/rubocop/cop/lint/assignment_in_condition_spec.rb
The first block check is redundant, since the method already checks for blocks.
> Fix a false positive for `Lint/AssignmentInCondition` when assigning in numblocks

- .github/workflows/rubocop.yml
As a workaround, the JRuby CI matrix is pinned to 9.4.10.0. The issue has been reported at https://github.com/jruby/jruby/issues/8606.
> Pin JRuby 9.4.10.0 to prevent build error on JRuby 9.4.11.0

- changelog/fix_false_negative_empty_line_defs_numblock.md
- lib/rubocop/cop/layout/empty_line_between_defs.rb
- spec/rubocop/cop/layout/empty_line_between_defs_spec.rb
> Fix a false negative for `Layout/EmptyLineBetweenDefs` with `DefLikeMacros` and numblocks

- changelog/fix_false_positive_access_mod_numblock.md
- lib/rubocop/cop/style/access_modifier_declarations.rb
- spec/rubocop/cop/style/access_modifier_declarations_spec.rb
See https://github.com/rubocop/rubocop/pull/11103
Apparently it used to error, now it is just a false positive for these.
There was another block type check during autocorrect. But it seems unnessesary now since there is no offense for blocks. So, I just removed it.
> Fix a false positive `Style/AccessModifierDeclarations` when using access modifier in a numblock

- changelog/fix_fix_false_positive_in_layout_extra_spacing_with_20250130132538.md
- lib/rubocop/cop/mixin/preceding_following_alignment.rb
- spec/rubocop/cop/layout/extra_spacing_spec.rb
Stops `Layout/ExtraSpacing` from considering the `=` that separates the method signature from body in an endless method.
Fixes #13751.
> [Fix #13751] Fix false positive in `Layout/ExtraSpacing` with `ForceEqualSignAlignment: true` for endless methods

- changelog/fix_false_positives_for_style_redundant_self_assignment.md
- lib/rubocop/cop/style/redundant_self_assignment.rb
- spec/rubocop/cop/style/redundant_self_assignment_spec.rb
Fixes #13750.
This PR fixes false positives for `Style/RedundantSelfAssignment` when assigning to attribute of `self`.
As mentioned in the feedback on #13750, `self.foo = foo.concat(ary)` is an assignment through a method call, which differs from a variable assignment like `foo = foo.concat(ary)`.
Although the original example suggests replacing `self.foo = foo.concat(ary)` with `self.foo += arg`, the autocorrect implementation didn't account for this. Furthermore, methods other than `concat`, such as `delete_if` or `unshift`, cannot be resolved by replacing them with `+=`. As a result, providing a simple autocorrect solution is not feasible. Furthermore, it is doubtful whether such a change can be regarded as an improvement to good style.
Given this, better approach would likely be to …
> [Fix #13750] Fix false positives for `Style/RedundantSelfAssignment`

- changelog/fix_unmod_reduce_numblock.md
- lib/rubocop/cop/lint/unmodified_reduce_accumulator.rb
- spec/rubocop/cop/lint/unmodified_reduce_accumulator_spec.rb
> Fix a false positive for `Lint/UnmodifiedReduceAccumulator` when omitting the accumulator in a nested numblock

- changelog/fix_else_alignment_numblock.md
- lib/rubocop/cop/layout/else_alignment.rb
- spec/rubocop/cop/layout/else_alignment_spec.rb
> Fix an error `Layout/ElseAlignment` when `else` is part of a numblock

- changelog/fix_false_positive_lint_void_numblock.md
- lib/rubocop/cop/lint/void.rb
- spec/rubocop/cop/lint/void_spec.rb
Followup https://github.com/rubocop/rubocop/pull/12688
Also remove a different block check that I don't think is doing anything. It was added in https://github.com/rubocop/rubocop/pull/13131 but all tests still pass
> Fix a false positive for `Lint/Void` when `each` numblock with conditional expressions that has multiple statements

- spec/rubocop/options_spec.rb
This PR stabilizes the following `help` command line option test.
```console
$ echo $PAGER
less
$ bundle exec rspec spec/rubocop/options_spec.rb
(snip)
rspec ./spec/rubocop/options_spec.rb:221 # RuboCop::Options option -h/--help lists all builtin formatters
rspec ./spec/rubocop/options_spec.rb:25 # RuboCop::Options option -h/--help shows help text
```
`help` option is implemented with OptionParser, if the environment vars `RUBY_PAGER` or `PAGER` are set, the mock for stdout will not be applied. 
https://github.com/ruby/optparse/blob/v0.6.0/lib/optparse.rb#L1053-L1071
To ensure stdout is mocked, a simple way is to temporarily delete these environment vars.
[1]: …
> Stabilize `help` command line option test

- changelog/fix_false_positive_for_useless_assignment.md
- lib/rubocop/cop/variable_force/variable.rb
- spec/rubocop/cop/lint/useless_assignment_spec.rb
As demonstrated in the issue #13395, there is a false positive as such:
```ruby
changed = false
^^^^^^^ Useless assignment to variable - `changed`.
if Random.rand > 1
changed = true
end
[].each do
changed = true
end
puts changed
```
In the presence of a conditional, the cop `Lint/UselessAssignment` can't be certain if the variable will be reassigned or not, so, very much like the case for blocks, the best approach is simply to ignore it.
There appears to be no benefit in actually looking into all branches and checking if all branches reassign since even then the outer assignment defines the variable.
This also applies to case statements.
> [Fix #13395] False positive for `Lint/UselessAssignment` when assigning in branch and block

- changelog/fix_incorrect_autocorrect_for_style_explicit_block_argument.md
- lib/rubocop/cop/style/explicit_block_argument.rb
- spec/rubocop/cop/style/explicit_block_argument_spec.rb
This PR fixes incorrect autocorrect for `Style/ExplicitBlockArgument` when using arguments of `zsuper` in method definition.
Fixes #13787
> [Fix #13787] Fix incorrect autocorrect for `Style/ExplicitBlockArgument`

- changelog/fix_style_each_with_object_cop_error_in_case_of_single_block_argument.md
- lib/rubocop/cop/style/each_with_object.rb
- spec/rubocop/cop/style/each_with_object_spec.rb
The following code leads to an error:
```console
echo '[].inject({}) { |h| h[rand] = rand; h }' | rubocop --stdin bug.rb --only Style/EachWithObject -d
An error occurred while Style/EachWithObject cop was inspecting bug.rb:1:0.
undefined method `source' for nil
lib/rubocop/cop/style/each_with_object.rb:74:in `autocorrect_block'
lib/rubocop/cop/style/each_with_object.rb:38:in `block (2 levels) in on_block'
```
This issue was found by [rubocop-nightly](https://github.com/viralpraxis/rubocop-nightly) in [nvim](https://rubygems.org/gems/nvim) gem.
> Fix `Style/EachWithObject` cop error in case if single block argument

- changelog/fix_fix_crash_in_layout_empty_lines_around_method_body_20250205120556.md
- lib/rubocop/cop/layout/empty_lines_around_method_body.rb
- spec/rubocop/cop/layout/empty_lines_around_method_body_spec.rb
Fixes crash in `Layout/EmptyLinesAroundMethodBody` when encountering an endless method on multiple lines.
```ruby
def foo(bar,
baz) = quux
```
```
$ rubocop -d test.rb
An error occurred while Layout/EmptyLinesAroundMethodBody cop was inspecting /Users/daniel/src/rubocop/test.rb:1:0.
The range 27...28 is outside the bounds of the source
/Users/daniel/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/parser-3.3.6.0/lib/parser/source/tree_rewriter.rb:406:in 'Parser::Source::TreeRewriter#check_range_validity'
/Users/daniel/src/rubocop/lib/rubocop/cop/corrector.rb:120:in 'RuboCop::Cop::Corrector#check_range_validity'
/Users/daniel/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/parser-3.3.6.0/lib/parser/source/tree_rewriter.rb:398:in 'Parser::Source::TreeRewriter#combine' …
```
> Fix crash in `Layout/EmptyLinesAroundMethodBody` for endless methods

- changelog/new_naming_predicate_name_optionally_use_sorbet_to_20250116223555.md
- config/default.yml
- lib/rubocop/cop/naming/predicate_name.rb
- spec/rubocop/cop/naming/predicate_name_spec.rb
- At the moment, the `Naming/PredicateName` cop checks for predicate methods based on the presence of a prefix in the method name. This is a common convention, but, for better or for worse, not all `has_` and `is_` methods, over time, return booleans.
- So, I had an idea to use Sorbet's `sig` to detect predicate methods based on the return type. If a method has a `sig` with a return type of `T::Boolean`, and the method name does not end with `?`, then it needs one.
- Add a `UseSorbetSigs` configuration option to the `Naming/PredicateName` cop. When set to `true`, the cop will check for predicate methods based on the presence of a Sorbet `sig` for the method with a return type of `T::Boolean` instead of based on method naming. …
> Naming/PredicateName: Optionally use Sorbet to detect predicate methods

- spec/support/strict_warnings.rb
This issue has been resolved in the latest WebMock 3.25.0: https://rubygems.org/gems/webmock/versions/3.25.0
> Remove useless suppressed WebMock warning

- .rubocop.yml
- changelog/new_support_rubocop_extension_plugin.md
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/extensions.adoc
- docs/modules/ROOT/pages/plugin_migration_guide.adoc
- docs/modules/ROOT/pages/usage/basic_usage.adoc
- lib/rubocop/config.rb
- lib/rubocop/config_loader.rb
- lib/rubocop/config_loader_resolver.rb
- lib/rubocop/cop/internal_affairs.rb
- lib/rubocop/cop/internal_affairs/plugin.rb
- lib/rubocop/options.rb
- lib/rubocop/plugin.rb
- lib/rubocop/plugin/configuration_integrator.rb
- lib/rubocop/plugin/load_error.rb
- lib/rubocop/plugin/loader.rb
- lib/rubocop/plugin/not_supported_error.rb
- lib/rubocop/rake_task.rb
- lib/rubocop/version.rb
- rubocop.gemspec
- spec/rubocop/cli_spec.rb
- spec/rubocop/config_obsoletion_spec.rb
- spec/rubocop/cop/generator_spec.rb
- spec/rubocop/options_spec.rb
- spec/rubocop/plugin/configuration_integrator_spec.rb
- spec/rubocop/plugin/loader_spec.rb
- spec/rubocop/plugin_spec.rb
- spec/rubocop/rake_task_spec.rb
- spec/rubocop/version_spec.rb
- spec/support/strict_warnings.rb
Support for extension plugins using lint_roller is introduced.
https://github.com/standardrb/lint_roller
Currently, lint_roller is the plugin mechanism adopted in Standard Ruby:
https://github.com/standardrb/standard/pull/551
And this proposal extends its adoption to RuboCop. This creates a future where extension gems compatible with lint_roller can be reused across linters that adopt lint_roller. It also means relying solely on lint_roller's unified plugin interface, reducing direct dependencies and achieving low coupling, much like how Rack was introduced in Rails 3.0 or how the LSP protocol model works.
Although this change references the first Standard Ruby implementation using lint_roller, some additional elements specific to RuboCop are included, such as the `--plugin` command-line …
> [Fix #6012] Support RuboCop extension plugin

- rubocop.gemspec
Given the feedback in https://github.com/standardrb/lint_roller/issues/8, there is a possibility that the lint_roller API may change.
To prevent unexpected issues caused by API incompatibility, the runtime dependency on lint_roller will be made stricter.
Expecting semantic versioning, the patch version will be updated.
> Make the lint_roller dependency version stricter

- lib/rubocop/lsp/runtime.rb
- lib/rubocop/lsp/server.rb
- lib/ruby_lsp/rubocop/addon.rb
- lib/ruby_lsp/rubocop/runtime_adapter.rb
The activation of `RuboCop::LSP.enable` is now centralized by enabling it during the instantiation of `RuboCop::LSP::Runtime`. This change brings together the spread-out calls to `LSP.enable` when using LSP, making them more organized.
As part of a long-term direction, the aim is to eventually remove the spread-out `RuboCop::LSP.enable` calls within Ruby LSP and the LSP feature of Standard Ruby.
Additionally, `RubyLSP::RuboCop::WrapsBuiltinLspRuntime` has been renamed to `RubyLsp::RuboCop::RuntimeAdapter`. This change follows the Adapter pattern (GoF) and reflects a class design that considers architectural principles.
Currently, there is no change log, as this corresponds to a refactoring of the internal structure.
Follow-up to https://github.com/rubocop/rubocop/pull/13628 and …
> Centralize `RuboCop::LSP.enable` activation and rename adapter class

- changelog/fix_false_negative_for_style_redundant_parentheses.md
- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
This PR fixes false negatives for `Style/RedundantParentheses` when chaining `[]` method calls.
Fixes #13807
> [Fix #13807] Fix false negatives for `Style/RedundantParentheses`

- changelog/fix_make_language_server_protocol_dependency_version_stricter
- rubocop.gemspec
The `language_server-protocol` gem is a library that adheres to the LSP specification. Since `X.Y.Z` represents the LSP version:
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/
Only the fourth value can be updated without affecting compatibility with the LSP specification: https://github.com/mtsmfm/language_server-protocol-ruby?tab=readme-ov-file#versioning
This PR strictly defines the runtime dependency version of the `language_server-protocol` gem in advance to prevent unintended incompatibilities.
> Make the language_server-protocol dependency version stricter

- lib/rubocop/cli/command/suggest_extensions.rb
- spec/rubocop/cli/suggest_extensions_spec.rb
This PR updates `SuggestExtensions` to properly handle plugin extensions.
For example, when changing the plugin specification for `rubocop-rake` from `require` to `plugins`:
```diff
inherit_from: .rubocop_todo.yml
-require:
-  - rubocop/cop/internal_affairs
+plugins:
+  - rubocop-internal_affairs
- rubocop-rake
+
+require:
AllCops:
```
Currently, `rubocop-rake` is unexpectedly displayed as part of `SuggestExtensions`:
```console
(snip)
The following RuboCop extension libraries are installed but not loaded in config:
* rubocop-rake
You can opt out of this message by adding the following to your config
(see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
AllCops:
SuggestExtensions: false
```
Ideally, when a …
> Make `SuggestExtensions` aware of plugin extensions

- Gemfile
This PR adds `fiddle` to the Gemfile for Ruby 3.4+ on Windows to suppress the following warning:
```console
C:/hostedtoolcache/windows/Ruby/3.4.1/x64/lib/ruby/3.4.0/win32/registry.rb:2:
warning: fiddle/import is found in fiddle, which will no longer be part of the default gems starting from Ruby 3.5.0.
You can add fiddle to your Gemfile or gemspec to silence this warning.
```
https://github.com/rubocop/rubocop/actions/runs/13231909961/job/36930325737?pr=13813#step:4:25
> Suppress `warning: fiddle/import is found in fiddle`

- changelog/new_make_server_mode_detect_local_paths_in_inherit_from_and_require.md
- docs/modules/ROOT/pages/usage/server.adoc
- lib/rubocop/config_loader_resolver.rb
- lib/rubocop/path_util.rb
- lib/rubocop/server/cache.rb
- spec/rubocop/path_util_spec.rb
- spec/rubocop/server/cache_spec.rb
This PR makes server mode detect local paths in .rubocop.yml under `inherit_from` and `require` for automatically restart.
Since this adds some extra processing, server mode may experience a slight performance degradation, but no significant delays are expected.
This change provides a trade-off by reducing the risk of users running with unexpected old configurations.
NOTE: Detection of incompatibility changes in the local configuration also includes changes to local file paths specified by `inherit_from` and `require` in .rubocop.yml. Changes involving remote files or those considered to be searched on `$LOAD_PATH` are not detected.
Resolves #13661 and follow-up to https://github.com/rubocop/rubocop/pull/13327#issuecomment-2411318067. …
> [Fix #13661] Make server mode detect local paths in `inherit_from` and `require`

- changelog/fix_fix_false_positives_for_20250210112523.md
- lib/rubocop/cop/lint/format_parameter_mismatch.rb
- lib/rubocop/cop/utils/format_string.rb
- spec/rubocop/cop/lint/format_parameter_mismatch_spec.rb
Previously the following cases were false positives due to the interpolated widths:
```ruby
format("%#{padding}s: %s", prefix, message)
sprintf("| %-#{key_offset}s | %-#{val_offset}s |", key, value)
```
This changes the regular expression to not consider text to be a template name (`%{name}`) if it begins with a `#`. It also extends the `NUMBER` regexp to allow for interpolation.
Fixes #12672.
> [Fix #12672] Fix false positives for `Lint/FormatParameterMismatch` when the width value is interpolated

- changelog/fix_fix_false_positive_for_format_specifier_with_20250210140055.md
- lib/rubocop/cop/utils/format_string.rb
- spec/rubocop/cop/lint/format_parameter_mismatch_spec.rb
Ruby's documentation lists `'%.d'` as a valid format specification (https://ruby-doc.org/3.4.1/format_specifications_rdoc.html#label-Precision+Specifier), but it is not handled by `RuboCop::Cop::Utils::FormatString`. It isn't explicitly mentioned in the Ruby 2.7 documentation, but it is valid there as well:
```
[1] pry(main)> RUBY_VERSION
=> "2.7.8"
[2] pry(main)> sprintf('%.d', 0)
=> ""
```
> Fix false positive for format specification with non-numeric precision

- lib/rubocop/plugin/configuration_integrator.rb
- spec/rubocop/plugin/configuration_integrator_spec.rb
This PR fixes an issue where plugin configuration keys were unexpectedly removed.
It resolves a problem where changes to a plugin's configuration for the same key as RuboCop's default configuration would result in the plugin's configuration being deleted. A regression test has been added to prevent this issue from recurring.
> Fix unexpected removal of plugin configuration value

- changelog/fix_fix_undefined_method_logger_when_processing_20250212102241.md
- lib/ruby_lsp/rubocop/addon.rb
- spec/ruby_lsp/rubocop/addon_spec.rb
The code for handling watched file notifications was crashing every time because it was trying to invoke `Logger()`, which is a module not a method. The actual method is `Logger.log`.
I added a test to verify that the runtime adapter is properly reloaded whenever the config file is updated.
Note: I did not use an RSpec's subject block for this test because we need to verify things _inside_ the `with_server` block, while add-ons are still loaded and activated (the method unloads them at the end). The watched files notification doesn't return a response (because it's an LSP notification and not a request) and so this is the only way to verify what's happening.
Please let me know if you want to include this in the changelog. …
> Fix undefined method Logger when processing watched file notifications

- lib/rubocop/cop/style/redundant_format.rb
- lib/rubocop/cop/utils/format_string.rb
- spec/rubocop/cop/style/redundant_format_spec.rb
Follows https://github.com/rubocop/rubocop/pull/13793#issuecomment-2638914275
Adds `Style/RedundantFormat` offenses when all format specifiers in the format string are given literal values that can be easily replaced. This applies to `%s`, `%d`, `%i`, `%u`, and `%f` with a variety of argument types (see tests for examples). This does not include things like `%x`, `%e`, `%g`, etc., which format numeric values in specific ways (as hexadecimal, scientific notation, etc.), as those are not straightforward and will make changing the code harder after inlining the value. 
I did not add a changelog entry since #13793 is not released yet.
> Update `Style/RedundantFormat` to register an offense for `format` arguments that can be easily inlined

- lib/rubocop/config_loader.rb
- spec/rubocop/config_loader_spec.rb
When using `Pathname` instance as an argument for `RuboCop::ConfigLoader.inject_defaults!`:
```ruby
project_root = Pathname.new(__dir__).join('..')
RuboCop::ConfigLoader.inject_defaults!(project_root.join('config', 'default.yml'))
```
The following error occurs:
```console
An error occurred while loading spec_helper.
Failure/Error: RuboCop::ConfigLoader.inject_defaults!(project_root.join('config', 'default.yml'))
NoMethodError:
undefined method `start_with?' for #<Pathname:0x00007f91f62406c8>
```
Investigating this error requires knowledge of RuboCop's internal implementation, which makes it difficult for users to troubleshoot. The simplest solution is to restore support for `Pathname` instance, maintaining the previous (private API period) behavior.
Before submitting …
> Allow `RuboCop::ConfigLoader.inject_defaults!` to accept `Pathname` instances

- changelog/fix_an_error_for_style_redundant_parentheses.md
- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
This PR fixes an error for `Style/RedundantParentheses` when a different expression appears before a range literal.
Fixes #13836.
> [Fix #13836] Fix an error for `Style/RedundantParentheses`

- changelog/change_plugin_is_loaded_automatically_with_rubocop_rspec_support.md
- docs/modules/ROOT/pages/plugin_migration_guide.adoc
- lib/rubocop/config_loader.rb
- lib/rubocop/rspec/cop_helper.rb
With this change, extension plugins that use `require 'rubocop/rspec/support'` for testing no longer need to include the following code in `spec/spec_helper.rb`.
```ruby
project_root = Pathname.new(__dir__).join('..')
RuboCop::ConfigLoader.inject_defaults!(project_root.join('config', 'default.yml'))
RuboCop::ConfigObsoletion.files << project_root.join('config', 'obsoletion.yml')
```
https://github.com/rubocop/rubocop-rails/blob/0e23cab4232cde7b1a74bafc758d19784576c527/spec/spec_helper.rb#L8-L10
In other words, extension plugins using RSpec can remove code related to `Inject`.
Accordingly, the purpose of `RuboCop::ConfigLoader.inject_defaults!` will be clarified and documented. When testing a plugin using `rubocop/rspec/support`, the plugin is loaded automatically, so this API is usually …
> Extension plugin is loaded automatically with `require 'rubocop/rspec/support'`

- changelog/fix_false_positives_fo_lint_redundant_type_conversion.md
- lib/rubocop/cop/lint/redundant_type_conversion.rb
- spec/rubocop/cop/lint/redundant_type_conversion_spec.rb
This PR fixes false positives for `Lint/RedundantTypeConversion` when passing block arguments when generating a Hash or a Set.
Fixes #13839.
> [Fix #13839] Fix false positives for `Lint/RedundantTypeConversion`

- lib/rubocop/plugin/load_error.rb
Users who encounter plugin load errors are usually those who have misconfigured the plugin, rather than the plugin developers.
The previous error message was more geared towards plugin developers.
```console
$ bundle exec rubocop lib/rubocop.rb
Error: Failed loading plugin `rubocop-performance` because we couldn't determine the corresponding plugin class to instantiate.
First, try upgrading it. If the issue persists, please check with the developer regarding the following points.
RuboCop plugin class names must either be:
- If the plugin is a gem, defined in the gemspec as `default_lint_roller_plugin'
spec.metadata['default_lint_roller_plugin'] = 'MyModule::Plugin'
- Set in YAML as `plugin_class_name'; example:
plugins:
- incomplete:
require_path: my_module/plugin
plugin_class_name: …
```
> Make plugin load error messages more user-friendly

- .rubocop.yml
- Gemfile
- lib/rubocop/rspec/cop_helper.rb
- spec/spec_helper.rb
This commit uses plugified RuboCop Performance (1.24) for development and suppresses the following warning:
```console
rubocop-performance extension supports plugin, specify `plugins: rubocop-performance`
instead of `require: rubocop-performance` in /Users/koic/src/github.com/rubocop/rubocop/.rubocop.yml.
For more information, see https://docs.rubocop.org/rubocop/plugin_migration_guide.html.
```
Furthermore, by skipping unnecessary processing in RuboCop's core tests, the following error is prevented.
```console
$ bundle exec rspec spec/rubocop/config_store_spec.rb:23
Run options: include {locations: {"./spec/rubocop/config_store_spec.rb" => [23]}}
Randomized with seed 950
F
Failures:
1) RuboCop::ConfigStore.for always uses config specified in command line …
```
> Use plugified RuboCop Performance (1.24) for development

- docs/modules/ROOT/pages/cops_naming.adoc
- docs/modules/ROOT/pages/cops_style.adoc
- lib/rubocop/cop/naming/block_forwarding.rb
- lib/rubocop/cop/style/arguments_forwarding.rb
Some bad formatting slipped into `Naming/BlockForwarding` and `Style/ArgumentsForwarding` during the previous release, which broke the [public docs](https://docs.rubocop.org/rubocop/cops_style.html) (wonky formatting, chopped-off navigation, and missing cop descriptions)
This fixes that
> Fix documentation formatting for `Naming/BlockForwarding` and `Style/ArgumentsForwarding`

- changelog/change_mark_style_redundant_format_as_unsafe_autocorrect.md
- config/default.yml
- lib/rubocop/cop/style/redundant_format.rb
This PR marks `Style/RedundantFormat` as unsafe autocorrect.
Fixes #13846.
> [Fix #13846] Mark `Style/RedundantFormat` as unsafe autocorrect

- lib/rubocop/cop/internal_affairs/example_description.rb
- spec/rubocop/cop/internal_affairs/example_description_spec.rb
This PR fixes false negatives for `InternalAffairs/ExampleDescription` when example description contains string interpolation.
Fixes #13850.
> [Fix #13850] Fix false negatives for `InternalAffairs/ExampleDescription`

- changelog/fix_all_cops_exclude_paths.md
- lib/rubocop/plugin/configuration_integrator.rb
- spec/rubocop/plugin/configuration_integrator_spec.rb
When relative paths are used in a plugin's configuration file under `AllCops: Exclude`, they must be converted to absolute paths. Otherwise, the exclusion paths will not match the paths being inspected, and the files will not be excluded.
This issue was reported in https://github.com/rubocop/rubocop-rails/issues/1443. And this issue was previously reported in https://github.com/rubocop/rubocop-rails/pull/187 and is essentially a necessary process for all extension gems.
On a side note, converting to the plugin system allows us to fix such potential bugs across all extension gems in a unified manner. Of course, there is also the risk of introducing bugs uniformly...
> Fix exclusion of relative paths in plugin's `AllCops: Exclude` as expected

- changelog/fix_an_error_for_style_redundant_format.md
- lib/rubocop/cop/style/redundant_format.rb
- spec/rubocop/cop/style/redundant_format_spec.rb
This PR fixes an error for `Style/RedundantFormat` when a template argument is used without keyword arguments.
Fixes #13844.
> [Fix #13844] Fix an error for `Style/RedundantFormat`

- changelog/fix_false_positives_for_lint_useless_constant_scoping.md
- lib/rubocop/cop/lint/useless_constant_scoping.rb
- spec/rubocop/cop/lint/useless_constant_scoping_spec.rb
This PR fixes false positives for `Lint/UselessConstantScoping` when a constant is used after `private` access modifier with arguments.
Fixes #13856.
> [Fix #13856] Fix false positives for `Lint/UselessConstantScoping`

- changelog/fix_an_error_for_style_redundant_format_cop.md
- lib/rubocop/cop/style/redundant_format.rb
- spec/rubocop/cop/style/redundant_format_spec.rb
Follow-up to https://github.com/rubocop/rubocop/issues/13844#issuecomment-2662583728.
This PR fixes an error for `Style/RedundantFormat` when numeric placeholders is used in the template argument.
> Fix an error for `Style/RedundantFormat`

- changelog/fix_an_error_lint_useless_constant_scoping.md
- lib/rubocop/cop/lint/useless_constant_scoping.rb
- spec/rubocop/cop/lint/useless_constant_scoping_spec.rb
This PR fixes an error for `Lint/UselessConstantScoping` hen multiple assigning to constants after `private` access modifier.
Fixes #13849.
> [Fix #13849] Fix an error for `Lint/UselessConstantScoping`

- changelog/fix_an_error_for_two_deprecated_allowed_pattern_apis.md
- lib/rubocop/cop/mixin/allowed_pattern.rb
This PR fixes `ArgumentError` related to two deprecated `AllowedPattern` APIs.
This bug was introduced in https://github.com/rubocop/rubocop/pull/13032, where arguments passed to methods using `alias` were not expanded properly.
Fixes #13861.
> [Fix #13861] Fix `ArgumentError` related to two deprecated `AllowedPattern` APIs

- lib/rubocop/cop/style/redundant_parentheses.rb
The `rubocop:disable Metrics/ClassLength` comment leaks in the actual documentation:
https://docs.rubocop.org/rubocop/cops_style.html#styleredundantparentheses
> Correct `Style/RedundantParentheses` documentation

- lib/rubocop/cop/style/redundant_format.rb
- spec/rubocop/cop/style/redundant_format_spec.rb
This PR tweaks the offense message of `Style/RedundantFormat`. Including the result of calls like `format('%10s', 'beepboop')` in the message helps users understand the cop's role in identifying cases where a string literal can be used instead.
Fixes #13866.
> [Fix #13866] Tweak the offense message of `Style/RedundantFormat`

- changelog/fix_error_plugin_no_bundler.md
- lib/rubocop/plugin.rb
- spec/rubocop/plugin_spec.rb
Because `Gem.loaded_specs` doesn't contain the gems yet at that point. The automatic injection of the config was removed, so no config is made available at all.
I don't particularly like the fix or test since it is somewhat close to bundler internals but I don't see a different solution. `try_activate` has been around in this form since at least the last 15 years
Initially I tried using `load` but that does not work since the gem is not activated. I've manually tested that this fixes the issue.
> [Fix #13867] Fix an error for plugins when not running RuboCop through Bundler

- lib/rubocop/plugin/load_error.rb
This PR removes an extra \` from the message printed when a plugin fails to load.
> plugin/load_error: remove extra tick

- lib/rubocop/rspec/shared_contexts.rb
- lib/rubocop/rspec/support.rb
- spec/rubocop/version_spec.rb
When a plugin is loaded in a test, it overrides `ConfigLoader.default_configuration` and does not revert it since it is a global cache. This allows for the state to be maintained when given as new spec metadata.
Fixes #13870.
> Prevent `version_spec` from leaking `ConfigLoader.default_configuration` changes

- changelog/change_add_forbidden_names_configuration_to_20250219104915.md
- config/default.yml
- lib/rubocop/cop/naming/variable_name.rb
- spec/rubocop/cop/naming/variable_name_spec.rb
Adds `ForbiddenNames` configuration to `Naming/VariableName` to allow disallowed identifiers to be specified, following https://github.com/rubocop/rubocop/pull/13825#issuecomment-2654192113. 
This applies to local variables, instance variables, class variables, global variables, method arguments (positional, keyword, rest or block), and block arguments. This explicitly does not apply to method names, because I can see there being use cases for overriding "reserved" methods (for instance, as per the issue, in Rails it would make sense to not override request with a local variable, but you may wish to override the request method).
Fixes #12948.
> [Fix #12948] Add `ForbiddenNames` configuration to `Naming/VariableName` to specify names that are forbidden

- changelog/fix_fix_style_redundant_format_when_given_20250220122052.md
- lib/rubocop/cop/style/redundant_format.rb
- spec/rubocop/cop/style/redundant_format_spec.rb
Update `Style/RedundantFormat` to handle double splatted arguments.
Fixes #13880.
> [Fix #13880] Fix `Style/RedundantFormat` when given double-splatted arguments

- changelog/fix_fix_style_redundant_format_for_annotated_template_20250220164253.md
- lib/rubocop/cop/style/redundant_format.rb
- spec/rubocop/cop/style/redundant_format_spec.rb
Fixes crash in `Style/RedundantFormat` when there is no hash key for a given template annotation.
Fixes #13882.
> [Fix #13882] Fix `Style/RedundantFormat` for annotated template strings with missing hash keys

- lib/rubocop/cop/style/line_end_concatenation.rb
- spec/rubocop/cop/style/line_end_concatenation_spec.rb
Improve the offense message for `Style/LineEndConcatenation` to refer to the actual operator being used.
> Improve offense message for `Style/LineEndConcatenation`

- docs/modules/ROOT/pages/extensions.adoc
Seems like a colon is missing.
> Fix plugin docs missing YAML colon

- changelog/fix_false_positive_trivial_accessor_numblock.md
- lib/rubocop/cop/style/trivial_accessors.rb
- spec/rubocop/cop/style/trivial_accessors_spec.rb
The first yielded argument for `instance_eval` is the object itself
> Fix a false positive for `Style/TrivialAccessors` with `instance_eval` and numblocks

- changelog/fix_update_style_hash_except_and_style_hash_slice_to_20250224092807.md
- lib/rubocop/cop/mixin/hash_subset.rb
- spec/rubocop/cop/style/hash_except_spec.rb
- spec/rubocop/cop/style/hash_slice_spec.rb
Update `Style/HashExcept` and `Style/HashSlice` to be able to handle when the value being called with `include?`, `exclude?` or `in?` is the hash value block argument (in which case, it cannot be replaced with `slice` or `except`).
eg:
```ruby
hash.select { |k, v| v.include?(k) }
```
Fixes #13885.
> [Fix #13885] Update `Style/HashExcept` and `Style/HashSlice` to not register an offense if selecting over the hash value

- changelog/fix_redundant_require_pp.md
- config/default.yml
- lib/rubocop/cop/lint/redundant_require_statement.rb
- spec/rubocop/cop/lint/redundant_require_statement_spec.rb
Fix #13876
Only the `pp` method is available. Requiring it brings in a bunch of other stuff, like the `PP` constant or a few `pretty_` methods.
There's code to handle this but it only works when those methods are exclusivly used in the file it is required in, which I don't think is a very realistic expectation.
All the other requires are truly redundant, this one looks out of place (especially for `Lint`)
Can we just remove it?
> [Fix #13876] Don't consider `pp` for `Lint/RedundantRequireStatement`

- changelog/change_update_lint_redundant_type_conversion_to_not_20250221105353.md
- lib/rubocop/cop/lint/redundant_type_conversion.rb
- spec/rubocop/cop/lint/redundant_type_conversion_spec.rb
Allows code such as the following to not register `Lint/RedundantTypeConversion` offenses, as the result could be `nil`:
```ruby
Integer("number", exception: false).to_i
```
Follows https://github.com/rubocop/rubocop/pull/13702#issuecomment-2661555711.
> Update `Lint/RedundantTypeConversion` to not register an offense when given a constructor with `exception: false`

- lib/rubocop/cop/lint/redundant_type_conversion.rb
Fix the "bad" example for sets.
> Fix typo in `Lint/RedundantTypeConversion` documentation

- changelog/fix_false_negative_for_style_redundant_self_assignment.md
- lib/rubocop/cop/style/redundant_self_assignment.rb
- spec/rubocop/cop/style/redundant_self_assignment_spec.rb
Add support for the case where the rhs method receives a block, e.g.:
```ruby
foo = foo.map! { |n| n * 2 }
foo.map! { |n| n * 2 }
```
> Fix false negative for `Style/RedundantSelfAssignment` when the method receives a block

- changelog/change_allow_merging_of_configured_arrays_and_non_arrays_20250222010203.md
- lib/rubocop/config_loader_resolver.rb
- spec/rubocop/config_loader_spec.rb
_See https://github.com/rubocop/rubocop/pull/13884#issuecomment-2675874658 for context._
Previously, merging would only be performed if the base value was an `Array`. If the derived value was an `Array`, but the base value was not, an overwrite would be performed.
For example, many cops specify a single `Reference` directly as a `String`. However, as `Reference` uses `Array(value)` behind the scenes, and accepts either a `String` or an `Array` of strings, a consumer may decide to add additional references.
Security/JSONLoad:
Reference: 'https://ruby-doc.org/stdlib-2.7.0/libdoc/json/rdoc/JSON.html#method-i-load'
Security/JSONLoad:
Reference:
- https://example.com#another-reason-to-use-json-parse-instead-of-load
Unfortunately, this would overwrite the original, even if configured to merge.. …
> Allow merging of configured arrays and non-arrays

- lib/rubocop/cop/lint/duplicate_methods.rb
- spec/rubocop/cop/lint/duplicate_methods_spec.rb
This methods seems to not do much anymore nowadays. All tests continue to pass if it is removed, so simply remove it.
I added a test which I think this method was supposed to cover to make extra sure
> Remove unnecessary `possible_dsl?` in `Lint/DuplicateMethods`

- changelog/change_update_style_redundant_condition_cop_to_detect_20250121092813.md
- lib/rubocop/cop/lint/float_comparison.rb
- lib/rubocop/cop/style/redundant_condition.rb
- spec/rubocop/cop/style/redundant_condition_spec.rb
Checks for ternary expressions that use `true` as the true branch and suggest replacing them with a logical OR (`||`) expression.
For example, a ternary like `condition ? true : variable` is considered redundant because it can be simplified to `condition || variable`. The cop promotes the use of more concise and readable code by encouraging the use of logical OR in such cases, improving both clarity and maintainability.
```ruby
#
#
#
```
> Update `Style/RedundantCondition` cop to detect conditional expressions where the true branch is `true` and suggest replacing them with a logical OR

- changelog/new_add_require_endless_method_option_to_style_endless_method.md
- changelog/new_add_require_single_line_endless_method_option_to_style_endless_method.md
- config/default.yml
- lib/rubocop/cop/style/endless_method.rb
- lib/rubocop/cop/style/single_line_methods.rb
- spec/rubocop/cop/style/endless_method_spec.rb
- spec/rubocop/cop/style/single_line_methods_spec.rb
Work on this began in PR #11064 but hasn't seen any significant activity in recent months.
Credit to @koic for doing most of the heavy lifting. I just extended it with another option
---
Fixes #11024.
This PR adds `require_always` and `require_single` options to `Style/EndlessMethod`
`require_always` by @koic requires that endless method definitions are used when possible.
`require_single_line` by @jtannas requires that single line methods be endless and forbids multiline endless methods.
```ruby
def my_method
x
end
def my_method = x.foo
.bar
.baz
def my_method = x
def my_method
x.foo
.bar
.baz
end
def my_method
x
end
def my_method
x.foo
.bar
.baz
end
def my_method = x
def my_method = x.foo
.bar
.baz
```
[1]: …
> [Fix #11024] Add `require` options to Style/EndlessMethod

- changelog/fix_fix_style_accessor_grouping_with_constants_20250225172211.md
- lib/rubocop/cop/style/accessor_grouping.rb
- spec/rubocop/cop/style/accessor_grouping_spec.rb
Closes https://github.com/rubocop/rubocop/issues/12692
> [Fix #12692] Fix `Style/AccessorGrouping` with constants

- changelog/change_add_partial_autocorrect_for_lint_literal_as_condition.md
- config/default.yml
- lib/rubocop/cop/lint/literal_as_condition.rb
- spec/rubocop/cli/options_spec.rb
- spec/rubocop/cop/lint/literal_as_condition_spec.rb
> Add partial autocorrect support for `Lint/LiteralAsCondition`

- changelog/fix_false_positives_for_style_endless_method.md
- lib/rubocop/cop/style/endless_method.rb
- spec/rubocop/cop/style/endless_method_spec.rb
Follow-up to https://github.com/rubocop/rubocop/pull/13874#issuecomment-2684036210
This PR fixes false positives for `Style/EndlessMethod` when using assignment method definitions.
Setter methods cannot be defined as endless methods.
```console
$ ruby -vc -e "def foo=(arg) = bar"
ruby 3.4.2 (2025-02-15 revision d2930f8e7a) +PRISM [x86_64-darwin23]
ruby: -e:1: syntax error found (SyntaxError)
> 1 | def foo=(arg) = bar
|     ^~~~ invalid method name; a setter method cannot be defined in an endless method definition
```
> Fix false positives for `Style/EndlessMethod`

- changelog/new_introduce_enforced_style_for_multiline_diff_comma_20250208163732.md
- config/default.yml
- lib/rubocop/cop/mixin/trailing_comma.rb
- lib/rubocop/cop/style/trailing_comma_in_array_literal.rb
- lib/rubocop/cop/style/trailing_comma_in_hash_literal.rb
- spec/rubocop/cop/style/trailing_comma_in_array_literal_spec.rb
- spec/rubocop/cop/style/trailing_comma_in_hash_literal_spec.rb
Introduce EnforcedStyleForMultiline "diff_comma".
[Fix #9935]
A new "diff_comma" enforced style for `Style::TrailingCommaInArrayLiteral`
and `Style::TrailingCommaInHashLiteral` that omits the trailing comma unless
the final item of the hash/array literal is at the end of line.
This style behaves similarly to "consistent_comma" with the exception of this case:
```ruby
a = { foo: 1, bar: 2,
baz: 3, qux: 4 }
a = { foo: 1, bar: 2,
baz: 3, qux: 4, }
a = { foo: 1, bar: 2,
baz: 3, qux: 4, }
a = { foo: 1, bar: 2,
baz: 3, qux: 4 }
```
In #9935 it was discussed whether this should be the behavior of
"consistent_comma" but some concerns were raised about whether this
was expected behavior or not, or whether the change would be
disruptive.
This style convention results in "clean diffs" where adding …
> Introduce EnforcedStyleForMultiline "diff_comma"

- changelog/fix_autocorrect_empty_cond_single_branch.md
- lib/rubocop/cop/lint/empty_conditional_body.rb
- spec/rubocop/cop/lint/empty_conditional_body_spec.rb
This currently produces wrong syntax:
```rb
var = if nil; end
var =
```
I chose not to offer autocorrect in such cases. But you could also:
* Remove the variable as well
* Assign nil to it
Not doing anything seems safest. There are others that will produce invalid syntax now, for example `x > if nil; end` but that is already a runtime error and not trivial to correctly handle. I'd leave this one for if somebody actually complains.
Found with https://github.com/rubocop/rubocop/pull/13183
> Fix wrong autocorrect for `Lint/EmptyConditionalBody` when assigning to a variable with single branch

- changelog/fix_fix_false_positive_with_20250226171903.md
- lib/rubocop/cop/layout/closing_parenthesis_indentation.rb
- spec/rubocop/cop/layout/closing_parenthesis_indentation_spec.rb
Closes https://github.com/rubocop/rubocop/issues/13909
> [Fix #13909] Fix false positive with `Layout/ClosingParenthesisIndentation` when first parameter is a hash

- changelog/fix_fix_writing_generics_type_of_rbs_inline_annotation_20250226233214.md
- lib/rubocop/cop/style/commented_keyword.rb
- spec/rubocop/cop/style/commented_keyword_spec.rb
[RBS::Inline](https://github.com/soutaro/rbs-inline) is a utility to embed RBS type declarations into Ruby code as comments.
I made rules for generics type below pull request, but nested classes were not supported.
Follow https://github.com/rubocop/rubocop/pull/13476
> Fix writing generics type of rbs-inline annotation for nested class in `Style/CommentedKeyword`

- changelog/fix_false_positives_for_style_redundant_condition.md
- config/default.yml
- lib/rubocop/cop/style/redundant_condition.rb
- spec/rubocop/cop/style/redundant_condition_spec.rb
This PR fixes false positives for `Style/RedundantCondition` when using when true is used as the true branch and condition is not predicate method.
Fixes #13913.
> [Fix #13913] Fix false positives for `Style/RedundantCondition`

- changelog/fix_an_error_for_lint_mixed_case_range_cop.md
- lib/rubocop/cop/lint/mixed_case_range.rb
- spec/rubocop/cop/lint/mixed_case_range_spec.rb
This PR fixes an error for `Lint/MixedCaseRange` when `/[[ ]]/` is used.
Fixes #13920.
> [Fix #13920] Fix an error for `Lint/MixedCaseRange`

- changelog/fix_lint_literal_as_condition_autocorrecting_rhs_and_nodes.md
- lib/rubocop/cop/lint/literal_as_condition.rb
- spec/rubocop/cop/lint/literal_as_condition_spec.rb
Fixes #13916.
~~This does mean some valid cases won't be caught, but for a Lint cop I presume its better to prioritize safety.~~
The right hand side of an && isn't a condition, its just executed conditionally. 
> [Fix #13916] Stop Lint/LiteralAsCondition from acting on the rhs of && statements.

- changelog/change_update_autocorrection_for_20250227114940.md
- config/default.yml
- lib/rubocop/cop/lint/empty_conditional_body.rb
- spec/rubocop/cli_spec.rb
- spec/rubocop/cop/lint/empty_conditional_body_spec.rb
In #10862, autocorrection was added to remove branches that had no body. This was made unsafe in #10867, because deleting a branch introduces a behaviour change if any of the branch conditions had side effects. There have been a considerable number of bugfix PRs since, and still broken examples, such as https://github.com/rubocop/rubocop/pull/10862#pullrequestreview-1065335927.
As a `Lint` cop, it'd be better to just not correct when unsafe. The user can decide whether the branch can be removed, or an explicit `nil` can be added.
Empty branches with comments (with `AllowComments: true` configuration) are still allowed and not corrected.
Fixes #12669.
> [Fix #12669] Update autocorrection for `Lint/EmptyConditionalBody` to be safe

- lib/rubocop/cop/internal_affairs/example_description.rb
- spec/rubocop/cop/internal_affairs/example_description_spec.rb
- spec/rubocop/cop/lint/deprecated_constants_spec.rb
- spec/rubocop/cop/lint/ensure_return_spec.rb
- spec/rubocop/cop/lint/unified_integer_spec.rb
- spec/rubocop/cop/lint/useless_times_spec.rb
- spec/rubocop/cop/style/access_modifier_declarations_spec.rb
- spec/rubocop/cop/style/case_equality_spec.rb
- spec/rubocop/cop/style/comparable_clamp_spec.rb
- spec/rubocop/cop/style/identical_conditional_branches_spec.rb
Also added `expect_correction`s to the tests where it was missing.
> Update `InternalAffairs/ExampleDescription` to handle `expect_no_corrections` with "registers an offense and corrects" description

- changelog/fix_fix_end_pattern_with_unmatched_parenthesis__20250228103004.md
- lib/rubocop/cop/utils/format_string.rb
The https://bugs.ruby-lang.org/issues/19379 bug seems to apply when using `(?-x:#...)` inside a regexp with the `x` extended mode option. Escaping the `#`s seems to fix it.
Fixes #13928.
> Fix `end pattern with unmatched parenthesis: / (RegexpError)` on Ruby 3.2.0

- changelog/fix_false_positive_redundant_freeze_numblock.md
- lib/rubocop/cop/style/redundant_freeze.rb
- spec/rubocop/cop/style/redundant_freeze_spec.rb
> Fix a false negative for `Style/RedundantFreeze` when calling methods that produce frozen objects with numblocks

- changelog/fix_false_positive_for_style_redundant_condition.md
- lib/rubocop/cop/style/redundant_condition.rb
- spec/rubocop/cop/style/redundant_condition_spec.rb
This PR fixes false positives for `Style/RedundantCondition` when a variable or a constant is used.
This fixes false positives that were not addressed in #13919. For example, logic that transforms `variable = 42` into `variable ? true : false` should not be detected. Since it is fundamentally impossible to determine what values a variable or constant might be assigned, they are always allowed.
> Fix false positives for `Style/RedundantCondition`

- changelog/fix_wrong_autocorrect_keyword_param_order_comments.md
- lib/rubocop/cop/lint/erb_new_arguments.rb
- lib/rubocop/cop/mixin/range_help.rb
- lib/rubocop/cop/style/expand_path_arguments.rb
- lib/rubocop/cop/style/keyword_parameters_order.rb
- lib/rubocop/cop/style/multiline_method_signature.rb
- lib/rubocop/cop/style/sole_nested_conditional.rb
- spec/rubocop/cop/style/keyword_parameters_order_spec.rb
Fix #13933
There is nothing sensible to do here, except to not offer autocorrect at all. I think.
The first commit extracts a method to get the arguments range into `RangeHelp` since it already exists a few times and I was about to add another one.
> [Fix #13933] Fix wrong autocorrect for `Style/KeywordParametersOrder` with comments

- changelog/fix_false_positive_for_style_inverse_methods.md
- lib/rubocop/cop/style/inverse_methods.rb
- spec/rubocop/cop/style/inverse_methods_spec.rb
This PR fixes false positives for `Style/InverseMethods` when using `any?` or `none?` with safe navigation operator.
Additionally, some specs for the existing incorrect behavior has been updated.
Fixes #13766.
> [Fix #13766] Fix false positives for `Style/InverseMethods`

- changelog/fix_disabling_of_departments_when_inheriting_configuration.md
- lib/rubocop/config_loader.rb
- spec/rubocop/config_loader_spec.rb
This fixes an issue where departments that were disabled in `rubocop-i18n` were unexpectedly enabled, even when they were also disabled in the user configuration.
Since `override_department_setting_for_cops` is processed in `resolve_inheritance`, unnecessary calls were being made. This caused `'override_department'` to be unexpectedly set for cop's `Enabled`.
It seems that part of the configuration processing changes introduced with plugin support was missed.
Fixes https://github.com/rubocop/rubocop-i18n/issues/66.
> Fix incorrect disabling of departments when inheriting configuration

- changelog/fix_double_negation_numblock.md
- lib/rubocop/cop/style/double_negation.rb
- spec/rubocop/cop/style/double_negation_spec.rb
Same as https://github.com/rubocop/rubocop/pull/10587
> Fix a false positive for `Style/DoubleNegation` when calling `define_method` with a numblock

- changelog/fix_method_call_args_numblock.md
- lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb
- spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
Some of this syntax is actually currently allowed on Ruby 3.4 with prism. See https://bugs.ruby-lang.org/issues/21168
> Fix some false positives for `Style/MethodCallWithArgsParentheses` with `EnforcedStyle: omit_parentheses` style and numblocks

- changelog/fix_false_negative_useless_constant_scoping_sclass.md
- lib/rubocop/cop/lint/useless_constant_scoping.rb
- spec/rubocop/cop/lint/useless_constant_scoping_spec.rb
Followup to https://github.com/rubocop/rubocop/commit/d83d67b7847d12e6c31c06cf2847b28997f669b2
Also see https://github.com/rubocop/rubocop/pull/13831#issuecomment-2697843782
> Fix a false negative for `Lint/UselessConstantScoping` for constants defined in `class << self`

- changelog/fix_wrong_autocorrect_rescue_modifier_mlhs.md
- lib/rubocop/cop/style/rescue_modifier.rb
- spec/rubocop/cop/style/rescue_modifier_spec.rb
It previously put the statement as is (`1, 2`), but that is not valid syntax on its own.
Found with https://github.com/rubocop/rubocop/pull/13183
> Fix wrong autocorrect for `Style/RescueModifier` when mllhs and the right-hand-side is not a bracketed array

- changelog/change_add_enforced_style_for_classes_and_20250227100212.md
- config/default.yml
- lib/rubocop/cop/style/class_and_module_children.rb
- spec/rubocop/cop/style/class_and_module_children_spec.rb
These new options allow the cop to be configured separately for classes and modules. If they are not set, or set to nil, the `EnforceStyle` value will be used instead.
I chose to do this rather than splitting the cop into two, as to avoid making changes that will affect a lot of configurations. I expect most people want the same style for both, as per the [style guide](https://github.com/rubocop/ruby-style-guide#namespace-definition).
Fixes #12851.
> [Fix #12851] Add `EnforcedStyleForClasses` and `EnforcedStyleForModules` configuration options to `Style/ClassAndModuleChildren`

- changelog/fix_obsoletion_cache_broken.md
- lib/rubocop/config_obsoletion.rb
Fix #13950
The `LOAD_RULES_CACHE` uses a _shared_ array, which can cause the index to become damaged. So, although the array has been modified, stale data is returned, causing the extension to ignore that is was loaded from a gem.
No tests for this one because I have no idea how and it would be incredibly specific anyways.
rehashing seems to be occasionally be performed by ruby, this demonstrates the problem:
```rb
array = []
hash = {}
hash[array] = "ok"
pp hash[array] # => "ok"
array << "added"
pp hash[array] # => nil
hash.rehash
pp hash[array] # => "ok"
```
Also see https://docs.ruby-lang.org/en/master/Hash.html#class-Hash-label-Modifying+an+Active+Hash+Key
> [Fix #13950] Obsoletion cache can be broken

- changelog/fix_false_negative_return_in_void_context.md
- lib/rubocop/cop/lint/return_in_void_context.rb
- spec/rubocop/cop/lint/return_in_void_context_spec.rb
Should be block happen to be called, the return will break out of the block and attribute the return value to the method.
This has been that way since the cop was added and there were no tests for blocks.
The only expection to the rule is when returning from inside a lambda.
Additionally, I simplified the implementation. The cop looked for `sdef` but then immediatly after required that the node be simply `def`.
> Fix a false negative for `Lint/ReturnInVoidContext` when returning out of a block

- lib/rubocop/cop/style/exponential_notation.rb
- spec/rubocop/cop/style/exponential_notation_spec.rb
The current offense message uses the potentially obscure `[1, 10[` form for an exclusive range. Using a ruby exclusive range is clearer for ruby developers.
> Tweak the offense message for `Style/ExponentialNotation`

- changelog/new_allow_writing_steep_annotaion_to_method_definition.md
- lib/rubocop/cop/style/commented_keyword.rb
- spec/rubocop/cop/style/commented_keyword_spec.rb
[Steep](https://github.com/soutaro/steep) is a type checker for Ruby.
Under certain circumstances, if the programmer writes `steep:ignore`, Steep will not do any type checking.
In particular, `steep:ignore` can be written on the same line as `def`, `end`, `begin`, `class` and `module` , but it is rejected by the `Style/CommentedKeyword` rules.
Another way to do this is to add options, but once an option is added, it is difficult to remove it, so the default rule written.
Also, it is unlikely that you would write `steep:ignore` if you were not using steep, so I defined it as a default rule.
refs: https://github.com/soutaro/steep/wiki/Release-Note-1.7#ignore-diagnostics-by-steepignore-comment
The more detailed you are, the …
> Allow writing Steep annotation on the same line as `def`, `end`, `begin`, `class` and `module` in `Style/CommentedKeyword`

- changelog/change_make_lint_redundant_type_conversion_aware_of_redundant_to_d.md
- lib/rubocop/cop/lint/redundant_type_conversion.rb
- spec/rubocop/cop/lint/redundant_type_conversion_spec.rb
This PR makes `Lint/RedundantTypeConversion` aware of redundant `to_d`.
```ruby
require 'bigdecimal/util'
BigDecimal(42).to_d == BigDecimal(42) # => true
```
> Make `Lint/RedundantTypeConversion` aware of redundant `to_d`

- changelog/fix_false_alarm_for_extracted_cop.md
- lib/rubocop/config_obsoletion/extracted_cop.rb
- spec/rubocop/config_obsoletion_spec.rb
Follow-up to https://github.com/rubocop/rubocop/issues/13950#issuecomment-2709112256
This prevents an unexpected warning that occurred because the config obsoletion was not considered in the plugin system introduced in #13792.
> Fix false alarm for config obsoletion

- changelog/fix_a_false_positive_for_lint_shared_mutable_default.md
- lib/rubocop/cop/lint/shared_mutable_default.rb
- spec/rubocop/cop/lint/shared_mutable_default_spec.rb
This PR fixes a false positive for `Lint/SharedMutableDefault` when `capacity` keyword argument is used.
NOTE: The `minimum_target_ruby_version: 3.4` is intentionally not specified. A false negative may occur in Ruby 3.3 or earlier, but the intent behind upgrading to Ruby 3.4 is prioritized.
Fixes #13969.
> [Fix #13969] Fix a false positive for `Lint/SharedMutableDefault`

- lib/rubocop/cop/style/format_string_token.rb
There have been some issues about `Style/FormatStringToken` acting unexpectedly due to all strings being evaluated even when not passed to a string formatting method. As such I have rewritten the docs to be clearer as to what the cop is doing and how to get the desired behaviour.
Ref: #11618, #12588
> Update documentation for `Style/FormatStringToken` for clarity

- changelog/change_allow_tls_1_1_and_tls_1_2_in_naming_variable_number.md
- config/default.yml
- spec/rubocop/config_loader_spec.rb
This PR allows `TLS1_1` and `TLS1_2` by default in `Naming/VariableNumber`. to accommodate OpenSSL version parameter names.
> Allow `TLS1_1` and `TLS1_2` by default in `Naming/VariableNumber`

- changelog/fix_false_positives_for_style_redundant_current_directory_in_path.md
- lib/rubocop/cop/style/redundant_current_directory_in_path.rb
- spec/rubocop/cop/style/redundant_current_directory_in_path_spec.rb
This PR fixes false positives for `Style/RedundantCurrentDirectoryInPath` when using a complex current directory path in `require_relative`.
Fixes #13975.
> [Fix #13975] Fix false positives for `Style/RedundantCurrentDirectoryInPath`

- changelog/fix_prevent_redundant_plugin_loading.md
- lib/rubocop/config_loader_resolver.rb
- spec/rubocop/version_spec.rb
This PR prevents redundant plugin loading when a duplicate plugin is specified in an inherited config.
> Prevent redundant plugin loading

- lib/rubocop/cop/lint/raise_exception.rb
Slightly rewrite documentation for `Lint/RaiseException` to improve clarity, and add additional examples.
> Improve documentation for `Lint/RaiseException`

- .rubocop.yml
- changelog/change_add_support_for_array_intersection_to_20250314093853.md
- lib/rubocop/cop/style/array_intersect.rb
- spec/rubocop/cop/style/array_intersect_spec.rb
Adds support for `Array#intersection` to `Style/ArrayIntersect`. 
Since [`Array#intersection`](https://ruby-doc.org/2.7.8/Array.html#method-i-intersection) allows for more variation than `Array#&` (ie. it can have zero or multiple arguments), the cop only considers it if given exactly 1 argument.
Fixes #13986.
> [Fix #13986] Add support for `Array#intersection` to `Style/ArrayIntersect`

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/extensions.adoc
"Plugin Migration Guide" page was previously placed under the "Cop Documentation" category, but it actually belongs to plugin extension, not cop: https://docs.rubocop.org/rubocop/1.74/plugin_migration_guide.html
Therefore, a new "Plugin Documentation" category has been created, and the "Plugin Migration Guide" page has been moved under it. And, the "Extensions" page will be moved to the new category.
To ensure existing URLs remain unchanged, the original page name has been retained.
> [Doc] Tweak navigation of docs

- changelog/change_add_forbidden_config_to_method_name_20250227140441.md
- config/default.yml
- lib/rubocop.rb
- lib/rubocop/cop/mixin/forbidden_identifiers.rb
- lib/rubocop/cop/mixin/forbidden_pattern.rb
- lib/rubocop/cop/naming/method_name.rb
- lib/rubocop/cop/naming/variable_name.rb
- spec/rubocop/cli/auto_gen_config_spec.rb
- spec/rubocop/cop/naming/method_name_spec.rb
Closes https://github.com/rubocop/rubocop/issues/13621
> [Fix #13621] Add `ForbiddenIdentifiers` config to `Naming/MethodName` cop

- changelog/fix_lint_useless_assignment_different_branch.md
- lib/rubocop/cop/variable_force/variable.rb
- spec/rubocop/cop/lint/useless_assignment_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/13990.
Fixes another false positive introduced in https://github.com/rubocop/rubocop/pull/13389, by making the check added in https://github.com/rubocop/rubocop/pull/13409 stricter. Instead of trying to detect conditionals by inspecting the type of the parent node, we can limit the check to reassignments in the same branch.
Correctly handling reassignments across branches would require tracking them differently: an assignment is only useless if it's reassigned in _all_ child branches.
This is a simpler alternative to https://github.com/rubocop/rubocop/pull/13992.
> [Fix #13990] Fix a false positive for Lint/UselessAssignment when a variable is reassigned in a different branch

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/freeform.md
Feature request and bugs automatically add labels but not all types of reports should get these, like doc issues for example.
Also add a link to GH discussions.
Looks like this https://github.com/Earlopain/rubocop/issues/new/choose
> Allow free-form issue creation

- .github/ISSUE_TEMPLATE/config.yml
Followup to https://github.com/rubocop/rubocop/pull/13998
I though it was not present because `config.yml` was added, but it just wasn't there in my fork because
private security reporting is disabled there
Looks like this right now:
> Remove duplicate security issue link

- spec/ruby_lsp/rubocop/addon_spec.rb
Closes #14000
The Ruby LSP had a small change in how watched file notifications are processed in the latest version. Essentially, if we received notifications before the initial indexing is complete, we delay processing them.
This is important in the case of switching branches or git pulling before the initial indexing is complete. If we tried to process those notifications immediately, we could end up double indexing depending on where we're at with the initial indexing.
This change is not relevant for the actual functionality of the add-on, but it does break the test. The solution is to invoke `index_all` with an empty array of URIs to index, which does nothing other than marking the initial indexing as complete. …
> Perform initial indexing before triggering watched file notifications

- Gemfile
- spec/rubocop/cop/lint/percent_string_array_spec.rb
- spec/rubocop/cop/lint/percent_symbol_array_spec.rb
With the release of Prism 1.4.0, the previously broken specs are now passing.
> Remove `broken_on: :prism` from specs

- changelog/fix_sole_nested_conditional_incorrect_autocorrections_20250320230831.md
- lib/rubocop/cop/style/sole_nested_conditional.rb
- spec/rubocop/cop/style/sole_nested_conditional_spec.rb
Fixes wrong autocorrections for this cop.
Two types of wrong autocorrections have been fixed, they're listed in sections below. While fixing all this, I noticed some duplication of coupled logic and things that could be simplified, so I took the opportunity to refactor the cop. Let me know if I changed too much, I could try splitting this into multiple PRs.
https://github.com/rubocop/rubocop/pull/10647 introduced logic to autocorrect `unless` with `&&`, e.g. this:
```ruby
unless foo && bar
5 if baz
end
```
is autocorrected to:
```ruby
if !foo && !bar && baz
5
end
```
`unless foo && bar` is not equivalent to `if !foo && !bar`; the correct form is `if !(foo && bar)` (or `!foo || !bar` if we follow [De Morgan's laws](https://en.wikipedia.org/wiki/De_Morgan%27s_laws)). A simple example …
> Fix incorrect autocorrections for `Style/SoleNestedConditional`

- changelog/new_support_itblock_in_layout_cops.md
- lib/rubocop/cop/layout/block_alignment.rb
- lib/rubocop/cop/layout/block_end_newline.rb
- lib/rubocop/cop/layout/else_alignment.rb
- lib/rubocop/cop/layout/empty_line_between_defs.rb
- lib/rubocop/cop/layout/empty_lines_around_access_modifier.rb
- lib/rubocop/cop/layout/empty_lines_around_block_body.rb
- lib/rubocop/cop/layout/indentation_width.rb
- lib/rubocop/cop/layout/line_length.rb
- lib/rubocop/cop/layout/multiline_block_layout.rb
- lib/rubocop/cop/layout/rescue_ensure_alignment.rb
- lib/rubocop/cop/layout/space_before_block_braces.rb
- lib/rubocop/cop/layout/space_inside_block_braces.rb
- rubocop.gemspec
- spec/rubocop/cop/layout/block_alignment_spec.rb
- spec/rubocop/cop/layout/block_end_newline_spec.rb
- spec/rubocop/cop/layout/else_alignment_spec.rb
- spec/rubocop/cop/layout/empty_line_between_defs_spec.rb
- spec/rubocop/cop/layout/empty_lines_around_access_modifier_spec.rb
- spec/rubocop/cop/layout/empty_lines_around_block_body_spec.rb
- spec/rubocop/cop/layout/indentation_width_spec.rb
- spec/rubocop/cop/layout/line_length_spec.rb
- spec/rubocop/cop/layout/multiline_block_layout_spec.rb
- spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb
- spec/rubocop/cop/layout/redundant_line_break_spec.rb
- spec/rubocop/cop/layout/rescue_ensure_alignment_spec.rb
- spec/rubocop/cop/layout/single_line_block_chain_spec.rb
- spec/rubocop/cop/layout/space_before_block_braces_spec.rb
- spec/rubocop/cop/layout/space_inside_block_braces_spec.rb
- spec/spec_helper.rb
This PR supports `it` block parameter in `Layout` cops.
> Support `it` block parameter in `Layout` cops

- changelog/new_support_itblock_in_metrics_cops.md
- lib/rubocop/cop/metrics/block_length.rb
- lib/rubocop/cop/metrics/method_length.rb
- lib/rubocop/cop/metrics/utils/code_length_calculator.rb
- lib/rubocop/cop/mixin/method_complexity.rb
- rubocop.gemspec
- spec/rubocop/cop/metrics/abc_size_spec.rb
- spec/rubocop/cop/metrics/block_length_spec.rb
- spec/rubocop/cop/metrics/block_nesting_spec.rb
- spec/rubocop/cop/metrics/class_length_spec.rb
- spec/rubocop/cop/metrics/method_length_spec.rb
- spec/rubocop/cop/metrics/module_length_spec.rb
- spec/spec_helper.rb
This PR supports `it` block parameter in `Metrics` cops.
> Support `it` block parameter in `Metrics` cops

- lib/rubocop/cop/internal_affairs/node_pattern_groups.rb
- spec/rubocop/cop/internal_affairs/node_pattern_groups_spec.rb
This PR supports `it` block parameter in `InternalAffairs` cops.
Based on my investigation, this appears to be the required `it` block parameter support for existing cops that support numbered block parameter.
> Support `it` block parameter in `InternalAffairs` cops

- changelog/fix_an_error_for_style_hash_fetch_chain.md
- lib/rubocop/cop/style/hash_fetch_chain.rb
- spec/rubocop/cop/style/hash_fetch_chain_spec.rb
Follow-up to https://github.com/rubocop/rubocop/pull/13952#issuecomment-2745256954.
This PR fixes an error for `Style/HashFetchChain` when no arguments are given to `fetch`.
> Fix an error for `Style/HashFetchChain`

- changelog/change_redundant_parentheses_for_chained_and.md
- lib/rubocop/cop/style/invertible_unless_condition.rb
- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
Follow-up to https://github.com/rubocop/rubocop/pull/14012#discussion_r2006625844 to see if this change is acceptable.
Offends cases such as `(x && y) && z` and autocorrects to `x && y && z` since parentheses have no bearing on expression evaluation.
I know that in some cases parentheses are redundant for the machine but not for the human since they might make the intention clearer; this cop already accepts redundant parentheses in cases such as: https://github.com/rubocop/rubocop/blob/4ac46fac606eb7e0643686bd622a532cd2f8c2d5/spec/rubocop/cop/style/redundant_parentheses_spec.rb#L805-L808
In case we don't want to change existing behavior, I'm also okay with that, but then I'd like to change this PR so it at least adds an expectation that `(x && y) && z` doesn't offend (currently, this case …
> Offend parentheses for chained && expressions in `Style/RedundantParentheses`

- changelog/fix_false_negative_lint_line_length_autocorrect.md
- lib/rubocop/cop/layout/line_length.rb
- lib/rubocop/cop/mixin/check_line_breakable.rb
- spec/rubocop/cop/layout/line_length_spec.rb
Fix `Layout/LineLength` to autocorrect long class method definitions just like it autocorrects regular method definitions.
> Fix false negative for `Layout/LineLength` when autocorrecting class method definitions

- changelog/fix_false_negative_for_layout_multiline_parameter_line_breaks.md
- lib/rubocop/cop/layout/multiline_method_parameter_line_breaks.rb
- spec/rubocop/cop/layout/multiline_method_parameter_line_breaks_spec.rb
Make `Layout/MultilineMethodParameterLineBreaks` handle class method definitions.
> Fix false negative for `Layout/MultilineMethodParameterLineBreaks` when class method definitions are used

- spec/rubocop/cop/annotation_comment_spec.rb
- spec/rubocop/cop/bundler/gem_filename_spec.rb
- spec/rubocop/cop/lint/ambiguous_range_spec.rb
- spec/rubocop/cop/lint/duplicate_branch_spec.rb
- spec/rubocop/cop/style/hash_except_spec.rb
- spec/rubocop/cop/style/hash_fetch_chain_spec.rb
- spec/rubocop/cop/style/hash_slice_spec.rb
- spec/rubocop/cop/style/infinite_loop_spec.rb
- spec/rubocop/cop/style/quoted_symbols_spec.rb
- spec/support/alignment_examples.rb
- spec/support/empty_lines_around_body_shared_examples.rb
- spec/support/multiline_literal_brace_layout_examples.rb
- spec/support/multiline_literal_brace_layout_method_argument_examples.rb
- spec/support/multiline_literal_brace_layout_trailing_comma_examples.rb
Consistently use `shared_examples` in specs over `shared_examples_for`.
Follows https://github.com/rubocop/rubocop/pull/14033#issuecomment-2751974004.
> Consistently use `shared_examples` in specs

- Gemfile
- changelog/change_prism_for_ruby_3.4.md
- docs/modules/ROOT/pages/compatibility.adoc
- docs/modules/ROOT/pages/configuration.adoc
- lib/rubocop/version.rb
- rubocop.gemspec
> [!NOTE]  
> Requires a release for rubocop-ast, but then that will be it.
Closes #13617
Now that `rubocop-ast` uses `prism` for 3.4, all the syntax is supported and it no longer needs to me marked experimental.
As you can seen, there's not much actually happening here, mainly just doc updates. That is because this behaviour is entirely controlled in `rubocop-ast` when `ParserEngine: default` is set.
This just bumps the `rubocop-ast` requirement to always get a version where that is the case.
> [Fix #13617] Proper support for Ruby 3.4

- changelog/new_enable_reusable_prism_parse_results_for_ruby_lsp_addon.md
- lib/rubocop/lsp/runtime.rb
- lib/rubocop/lsp/stdin_runner.rb
- lib/rubocop/runner.rb
- lib/ruby_lsp/rubocop/runtime_adapter.rb
Follow-up to https://github.com/Shopify/ruby-lsp/pull/1849
This feature utilizes https://github.com/ruby/prism/pull/3478 and https://github.com/rubocop/rubocop-ast/pull/359 to implement https://github.com/Shopify/ruby-lsp/pull/1849.
As described in https://github.com/rubocop/rubocop-ast/pull/359, it speeds up the processing around `Prism::Translation::Parser` via `ProcessedSource` by 1.3x when using the Ruby LSP add-on.
> Enable reusable Prism parse result for Ruby LSP add-on

- changelog/fix_lint_shadowing_outer_local_variable_false_negative.md
- lib/rubocop/cop/lint/shadowing_outer_local_variable.rb
- lib/rubocop/cop/style/hash_each_methods.rb
- spec/rubocop/cop/lint/shadowing_outer_local_variable_spec.rb
Fixes a false negative for this cop when block with shadowing variable is inside a condition:
```ruby
def some_method
foo = 1
bar.each { |foo| } if cond
^^^ # Before this PR, this wouldn't be an offense
end
```
Note that currently an offense would be raised if `foo` assignment happened inside a condition:
```ruby
def some_method
if cond
foo = 1
bar.each { |foo| } if cond2
^^^ # This is currently an offense
end
end
```
> Fix false negative for `Lint/ShadowingOuterLocalVariable`

- changelog/change_style_next_to_support_consecutive_conditionals.md
- config/default.yml
- lib/rubocop/cop/style/next.rb
- spec/rubocop/cop/style/next_spec.rb
Add `AllowConsecutiveConditionals` setting to `Style/Next` (default: `false`) to mimic the behavior of `Style/GuardClause`.
Enabling this setting allows you to write:
```ruby
values.each do |val|
if val == 1
bar
end
if val == 2
baz
end
end
```
instead of the asymmetrical:
```ruby
values.each do |val|
if val == 1
bar
end
next unless val == 2
baz
end
```
> Add `AllowConsecutiveConditionals` setting to `Style/Next` to allow consecutive conditional statements

- changelog/fix_style_if_inside_else_comment_autocorrect.md
- lib/rubocop/cop/style/if_inside_else.rb
- spec/rubocop/cop/style/if_inside_else_spec.rb
Fixes how comments are handled in autocorrection for `Style/IfInsideElse`. Previously, some of them would get deleted and some would be placed awkwardly.
Examples below are split for basic if...else form and modifier form.
This example:
```ruby
if foo
bar
else
if baz
qux # two
else
quux # four
end
end
```
would previously get autocorrected to:
```ruby
if foo
bar
elsif baz
qux
else
quux # four
end
```
After this PR, it's autocorrected to:
```ruby
if foo
bar
elsif baz
qux # two
else
quux # four
end
```
This example:
```ruby
if foo
bar
else
baz if qux # two
end
```
would previously get autocorrected to:
```ruby
if foo
bar
elsif qux
baz
end
```
After this PR, it's autocorrected to:
```ruby
if foo
bar
elsif qux
baz # two
end
``` …
> Fix comment autocorrection for Style/IfInsideElse

- changelog/fix_handling_of_long_heredoc_lines_with_splitstrings_enabled_20250322032415.md
- lib/rubocop/cop/layout/line_length.rb
- spec/rubocop/cop/layout/line_length_spec.rb
This fixes a problem we've been seeing related to heredocs and the `SplitStrings` configuration. Whenever we run Rubocop locally or in CI after enabling that setting, we see the following on many files with heredocs in them:
```
An error occurred while Layout/LineLength cop was inspecting /Users/mauro-oto/Projects/foo/spec/support/bar.rb:2:7.
undefined method `begin' for an instance of Parser::Source::Map::Heredoc
/Users/mauro-oto/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.74.0/lib/rubocop/cop/layout/line_length.rb:373:in `string_delimiter'
/Users/mauro-oto/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.74.0/lib/rubocop/cop/layout/line_length.rb:148:in `check_for_breakable_str'
/Users/mauro-oto/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.74. …
```
> Fix handling of long heredoc lines with SplitStrings enabled

- lib/rubocop/cop/style/raise_args.rb
Updates docs for this cop which are confusing. The first paragraph explains the exploded style, but then the second paragraph explains part of it again:
I didn't add a changelog entry for this change since it didn't seem substantial, but let me know if I should add it.
> Update Style/RaiseArgs docs

- changelog/change_rename_allow_named_parameter_to_only_numbered_parameters.md
- config/default.yml
- lib/rubocop/cop/style/it_block_parameter.rb
- spec/rubocop/cop/style/it_block_parameter_spec.rb
Follow-up to https://github.com/rubocop/rubocop/pull/14026#issuecomment-2754372368.
This PR renames `EnforcedStyle: allow_named_parameter` to `EnforcedStyle: only_numbered_parameters` in `Style/ItBlockParameter`.
> Rename `allow_named_parameter` to `only_numbered_parameters` in `Style/ItBlockParameter`

- lib/rubocop/cop/style/empty_literal.rb
The cop won't register `String.new` as an offense when frozen string literals are enabled, but this info is currently missing from cop documentation (I had to look up the code when enabling this cop on a project to verify what would autocorrect do). This PR adds the missing info.
> Add note about frozen string literals handling for `Style/EmptyLiteral`

- changelog/fix_do_not_emit_a_warning_for_an_actually_empty_file_20250327192458.md
- lib/rubocop/target_finder.rb
- spec/rubocop/target_finder_spec.rb
- spec/support/file_helper.rb
main:
```console
$ touch lockfile
$ bundle exec rubocop -d
<snip>
Unprocessable file <snip>/lockfile: EOFError, end of file reached
$ bundle exec rubocop lockfile
W
Offenses:
lockfile:1:1: W: Lint/EmptyFile: Empty file detected.
```
This seems to be inconsistent and does not make much sense to treat differently an actually empty file and e.g. a file with a single newline.
> Do not emit a warning for an actually empty file while checking if it is executable

- .rubocop.yml
Enables `RSpec/Dialect` to enforce consistency when defining `shared_examples`.
Follows #14034, https://github.com/rubocop/rubocop-rspec/pull/2065.
> Enable `RSpec/Dialect` to enforce `shared_examples` instead of `shared_examples_for`

- changelog/fix_incorrect_autocorrect_for_lint_deprecated_open_ssl_constant.md
- lib/rubocop/cop/lint/deprecated_open_ssl_constant.rb
- spec/rubocop/cop/lint/deprecated_open_ssl_constant_spec.rb
This PR fixes incorrect autocorrect for `Lint/DeprecatedOpenSSLConstant` cipher constant argument is not `cbc`.
Fixes #14053.
> [Fix #14053] Fix incorrect autocorrect for `Lint/DeprecatedOpenSSLConstant`

- changelog/fix_incorrect_autocorrect_for_style_redundant_condition.md
- lib/rubocop/cop/style/redundant_condition.rb
- spec/rubocop/cop/style/redundant_condition_spec.rb
This PR fixes incorrect autocorrect for `Style/RedundantCondition` when true is used as the true branch and the condition takes arguments.
Fixes #14051.
> [Fix #14051] Fix incorrect autocorrect for `Style/RedundantCondition`

- changelog/fix_style_conditional_assignment_cop_error_on_dynamic_string_node_in_branch_20250329232641.md
- lib/rubocop/cop/style/conditional_assignment.rb
- spec/rubocop/cop/style/conditional_assignment_assign_in_condition_spec.rb
Without this patch, new examples fail with this error:
```bash
RuboCop::Cop::Style::ConditionalAssignment SingleLineConditionsOnly false behaves like with `dstr` node in branch registers an offense for heredoc inside branch
Failure/Error: Parser::Source::Range.new(expression.source_buffer, begin_pos, expression.begin_pos)
ArgumentError:
Parser::Source::Range: end_pos must not be less than begin_pos
Shared Example Group: "with `dstr` node in branch" called from ./spec/rubocop/cop/style/conditional_assignment_assign_in_condition_spec.rb:1092
```
To be precise, only heredoc-related examples fail; string interpolation examples were applying autocorrection incorrectly. …
> Fix `Style/ConditionalAssignment` cop error on `dstr` node in branch

- docs/modules/ROOT/pages/plugin_migration_guide.adoc
The `Gem::Specification#require` method is private, which causes the following error when executing the bundle command:
```
[!] There was an error while loading `rubocop-foo.gemspec`: private method 'require' called for an instance of Gem::Specification. Bundler cannot continue.
```
> Fix method name in Plugin Migration Guide

- lib/rubocop/cop/style/global_std_stream.rb
`Ractor.new { STDOUT }` raises, `Ractor.new { $stdout }` doesn't.
Also see https://docs.ruby-lang.org/en/3.4/ractor_md.html#label-Global+variables
> Document `Style/GlobalStdStream` Ractor benefits

- lib/rubocop/cop/style/hash_syntax.rb
> hash_syntax.rb docs: Clarify you're allowed to mix syntaxes

- changelog/new_lint_redundant_type_conversion_to_json_to_s.md
- lib/rubocop/cop/lint/redundant_type_conversion.rb
- spec/rubocop/cop/lint/redundant_type_conversion_spec.rb
[`#to_json`](https://github.com/ruby/json?tab=readme-ov-file#casting-non-native-types) returns a JSON _string_ representation of the given object, so following it by a `.to_s` call is redundant. Here are [search results](https://github.com/search?q=%22.to_json.to_s%22%20language%3Aruby&type=code) for would-be offenses (2.1k at the time of writing).
This PR makes `Lint/RedundantTypeConversion` cop register code like:
```ruby
foo.to_json.to_s
```
as an offense, and autocorrect it to:
```ruby
foo.to_json
```
> Make `Lint/RedundantTypeConversion` register an offense for `to_json.to_s`

- changelog/fix_wrong_autocorrect_for_style_map_into_array.md
- lib/rubocop/cop/style/map_into_array.rb
- spec/rubocop/cop/style/map_into_array_spec.rb
Fixes wrong autocorrection for this cop when using `Array#push` or `Array#append` with a hash argument without braces. Previously, this:
```ruby
dest = []
src.each { |e| dest.push(e: 2) }
```
would get autocorrected to:
```ruby
dest = src.map { |e| e: 2 }
```
which is invalid syntax. Now it gets autocorrected to:
```ruby
dest = src.map { |e| { e: 2 } }
```
> Fix wrong autocorrection for `Style/MapIntoArray`

- changelog/fix_false_positives_for_enforced_style_for_multiline_diff_comma.md
- lib/rubocop/cop/mixin/trailing_comma.rb
- lib/rubocop/cop/style/trailing_comma_in_array_literal.rb
- lib/rubocop/cop/style/trailing_comma_in_hash_literal.rb
- spec/rubocop/cop/style/trailing_comma_in_array_literal_spec.rb
- spec/rubocop/cop/style/trailing_comma_in_hash_literal_spec.rb
This PR fixes false positives for `EnforcedStyleForMultiline: diff_comma` of `Style/TrailingCommaInArrayLiteral` and `Style/TrailingCommaInHashLiteral` when trailing comma with comment.
Fixes #14070.
> [Fix #14070] Fix false positives for `EnforcedStyleForMultiline: diff_comma`

- changelog/change_pluralize_reference_default_configs_20250401123209.md
- config/default.yml
- lib/rubocop/config_validator.rb
- lib/rubocop/cop/internal_affairs/undefined_config.rb
- lib/rubocop/cop/message_annotator.rb
- lib/rubocop/cops_documentation_generator.rb
- lib/rubocop/formatter/disabled_config_formatter.rb
- spec/rubocop/cli_spec.rb
- spec/rubocop/config_loader_spec.rb
- spec/rubocop/cop/internal_affairs/undefined_config_spec.rb
- spec/rubocop/cop/message_annotator_spec.rb
#13884 proposed warning `Reference` contains a `String`, as it breaks merging values across inherited configs. As per the discussion there, #13892 taught RuboCop to handle merging string and array configs, regardless of if the "parent" or "child" was the array.
What remained was the quirk that `Reference` could contain an `Array` in the first place. This PR teaches `MessageAnnotator` to prefer `References`, while continuing to support `Reference` for backwards compatibility. The default configs are updated to consistently use `References` accordingly, which now warns if it is not an `Array`.
Closes #13884
[1]: …
> Prefer `References` over `Reference` in cop config

- spec/rubocop/target_finder_spec.rb
In https://github.com/rubocop/rubocop/pull/14048 I meant to use "zero-sized" terminology consistently since it sounds better than "actually empty".
> Clarify zero-sized file spec description

- changelog/fix_style_redundant_line_continuation_cop_error_on_multiline_assignment_20250408235451.md
- lib/rubocop/cop/style/redundant_line_continuation.rb
- spec/rubocop/cop/style/redundant_line_continuation_spec.rb
```bash
$ cat /tmp/ruby.rb
a, b, \
c = [1, 2, 3]
```
```bash
bundle exec rubocop /tmp/ruby.rb --only Style/RedundantLineContinuation -d
For /tmp: An error occurred while Style/RedundantLineContinuation cop was inspecting /tmp/ruby.rb.
undefined method `parenthesized_call?' for an instance of Symbol
lib/rubocop/cop/style/redundant_line_continuation.rb:187:in `argument_newline?'
lib/rubocop/cop/style/redundant_line_continuation.rb:143:in `redundant_line_continuation?'
lib/rubocop/cop/style/redundant_line_continuation.rb:91:in `block in on_new_investigation'
lib/rubocop/cop/mixin/match_range.rb:14:in `block in each_match_range'
lib/rubocop/cop/mixin/match_range.rb:14:in `scan'
lib/rubocop/cop/mixin/match_range.rb:14:in `each_match_range' …
```
> Fix `Style/RedundantLineContinuation` cop error on multiline assignment

- changelog/fix_allow_writing_rbs_inline_annotation__after_end_20250408193945.md
- lib/rubocop/cop/style/commented_keyword.rb
- spec/rubocop/cop/style/commented_keyword_spec.rb
[RBS::Inline](https://github.com/soutaro/rbs-inline) is a utility to embed RBS type declarations into Ruby code as comments.
We can write type declarations as `#:` after end keyword, especially when assigning variables.
ref. https://github.com/soutaro/steep/blob/bfa83623798279cb36f9c627fb68824e22ab9293/lib/steep/source.rb#L304
So I fixed the rule to allow writing RBS::Inline annotations `#:` after the end keyword.
In strictly, it is correct to write it only after the end keyword in a block of variable assignments.
However, in the context of the end keyword, except for variable assignments and method definitions, Steep does not check type or outputs an error if it is not the correct type.
Also, RBS::Inline does not generate rbs from `#:` after the end keyword except in a block of variable …
> Allow writing RBS::Inline annotation `#:` after end keyword in `Style/CommentedKeyword`

- changelog/fix_style_conditional_assignment_cop_error_on_one_line_if_then_else_20250408231542.md
- lib/rubocop/cop/style/conditional_assignment.rb
- spec/rubocop/cop/style/conditional_assignment_assign_in_condition_spec.rb
```bash
echo 'bar = if foo then 1 else 2 end' | bundle exec rubocop --stdin bug.rb -c <(echo "Style/ConditionalAssignment:\n EnforcedStyle: assign_inside_condition") -d
An error occurred while Style/ConditionalAssignment cop was inspecting rubocop/bug.rb:1:0.
3.3.0/gems/parser-3.3.7.2/lib/parser/source/tree_rewriter.rb:427:in `trigger_policy'
3.3.0/gems/parser-3.3.7.2/lib/parser/source/tree_rewriter.rb:414:in `enforce_policy'
3.3.0/gems/parser-3.3.7.2/lib/parser/source/tree_rewriter/action.rb:234:in `call'
3.3.0/gems/parser-3.3.7.2/lib/parser/source/tree_rewriter/action.rb:234:in `swallow'
3.3.0/gems/parser-3.3.7.2/lib/parser/source/tree_rewriter/action.rb:98:in `with'
3.3.0/gems/parser-3.3.7.2/lib/parser/source/tree_rewriter/action.rb:120:i …
```
> Fix `Style/ConditionalAssignment` cop error on oneline if-then-else

- Rakefile
Follow-up to https://github.com/rubocop/rubocop/pull/14025
This PR uses the latest Ruby 3.5 Prism translation parser for docs.
> Use the latest Ruby 3.5 parser for docs

- changelog/fix_false_positives_for_style_redundant_parentheses_cop.md
- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
This PR fixes false negative for `Style/RedundantParentheses` when using some operator methods with a parenthesized argument.
> Fix false negative for `Style/RedundantParentheses`

- changelog/fix_redundant_current_directory_prefix_regexp_20250414044527.md
- lib/rubocop/cop/style/redundant_current_directory_in_path.rb
- spec/rubocop/cop/style/redundant_current_directory_in_path_spec.rb
Dots (i.e. periods) in regular expressions need to be escaped, otherwise they are a wildcard for any single character.
> Fix false positive in RedundantCurrentDirectoryInPath cop for one-character paths

- changelog/change_offend_redundant_parens_around_method_arguments.md
- lib/rubocop/cop/lint/missing_cop_enable_directive.rb
- lib/rubocop/cop/style/redundant_parentheses.rb
- lib/rubocop/formatter/pacman_formatter.rb
- spec/rubocop/comment_config_spec.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
Currently, `Style/RedundantParentheses` will register an offense for parens around a method argument in a parenthesized method call:
```ruby
x.foo((bar))
^^^^^ Don't use parentheses around a method call.
```
However, an offense isn't registered with an expression argument:
```ruby
x.foo((bar + baz))
```
This PR makes the latter example an offense:
```ruby
x.foo((bar + baz))
^^^^^^^^^^^ Don't use parentheses around a method argument.
```
As a consequence, offense message for the first example is updated as well:
```ruby
x.foo((bar))
^^^^^ Don't use parentheses around a method argument.
```
> Offend redundant parens around method arguments for `Style/RedundantParentheses`

- changelog/fix_style_safe_navigation_with_longer_and_chain.md
- lib/rubocop/cop/style/safe_navigation.rb
- spec/rubocop/cop/style/safe_navigation_spec.rb
Currently, longer && chains cause overlapping offenses for `Style/SafeNavigation` cop:
```ruby
a && a.b && a.b.c
^^^^^^^^ Use safe navigation (&.)...
^^^^^^^^^^^^ Use safe navigation (&.)...
```
and this fails during autocorrection with `Parser::Source::TreeRewriter detected clobbering` error because the same ranges are updated.
This PR fixes the cop to prevent clobbering by autocorrecting in two passes:
```ruby
a && a.b && a.b.c
a&.b && a.b.c # after first pass
a&.b&.c # after second pass
```
As a side effect of the fix, cases such as:
```ruby
a&.b && a.b.c
```
are now also registered as cop offenses, and autocorrected to:
```ruby
a&.b&.c
```
Previously, this would only be an offense if instead of `a&.b` there was `a.b`. …
> Fix `Style/SafeNavigation` with longer && chains

- changelog/fix_style_class_and_module_children_cop_error_on_one_liner_class_definition_20250416225515.md
- lib/rubocop/cop/style/class_and_module_children.rb
- spec/rubocop/cop/style/class_and_module_children_spec.rb
Currently RuboCop is unable to investigate programs like this
```ruby
class A < B
class C
class D; end
end
class E
end
end
```
Upon merging this patch, the Rails codebase will be error-free in the context of the state space traversal technique used by `rubocop-nightly`.
> Fix `Style/ClassAndModuleChildren` cop error on one-liner class definition

- changelog/fix_layout_multiline_operation_indentation_cop_error_on_indexasgn_without_arguments_20250418012616.md
- lib/rubocop/cop/layout/multiline_operation_indentation.rb
- lib/rubocop/cop/mixin/multiline_expression_indentation.rb
- spec/rubocop/cop/layout/multiline_operation_indentation_spec.rb
I believe this pattern is kinda unique since that's the only way to get this AST
```bash
$ ruby-parse --34 -e 'begin; rescue => __LINE__[]; end'
(kwbegin
(rescue nil
(resbody nil
(indexasgn
(int 1)) nil) nil))
```
and `Layout/MultilineOperationIdentation` crashes on it.
> Fix `Layout/MultilineOperationIdentation` cop error on `indexasgn` node without arguments

- lib/rubocop/cop/lint/useless_rescue.rb
- lib/rubocop/cop/style/arguments_forwarding.rb
- lib/rubocop/cop/style/eval_with_location.rb
- lib/rubocop/cop/style/hash_transform_keys.rb
- lib/rubocop/cop/style/hash_transform_values.rb
- lib/rubocop/cop/style/if_with_boolean_literal_branches.rb
Fixes various formatting issues in cop docs related to monospace formatting.
The places where double backticks have been added is [unconstrained formatting](https://docs.asciidoctor.org/asciidoc/latest/text/#unconstrained); it's required where only part of a word is formatted (e.g. \`rescue\`s -> \`\`rescue\`\`s).
Places where `\+ has been added is [literal monospace](https://docs.asciidoctor.org/asciidoc/latest/text/literal-monospace/), required to prevent e.g. bold formatting if the monospace text contains \*.
> Fix some asciidoc formatting issues in cop documentation

- .rubocop.yml
- Gemfile
Currently `lint-without-bundler` CI step fails because it uses latest `rubocop-rspec` gem version and there's a [new cop](https://github.com/rubocop/rubocop-rspec/pull/2066) which leads to ~600 offenses in the code base.
I briefly saw https://github.com/rubocop/rubocop/pull/14033 and it looks like we have no intention to forbid using `include_examples`. Let me know if I'm wrong.
> Bump `rubocop-rspec` development dependency

- changelog/fix_style_condtional_assignment_cop_error_on_indexed_assignment_without_arguments_20250418222231.md
- lib/rubocop/cop/style/conditional_assignment.rb
- spec/rubocop/cop/style/conditional_assignment_assign_in_condition_spec.rb
> Fix `Style/ConditionalAssignment` cop error on indexed assignment without arguments

- changelog/fix_false_positives_for_style_redundant_parentheses.md
- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
Follow-up to https://github.com/rubocop/rubocop/pull/14067#issuecomment-2820741234 The fix in #14093 had been overlooked.
This PR fixes false positives for `Style/RedundantParentheses` when parens around basic conditional as the second argument of a parenthesized method call.
> Fix false positives for `Style/RedundantParentheses`

- changelog/fix_false_positive_for_style_safe_navigation.md
- lib/rubocop/cop/style/safe_navigation.rb
- spec/rubocop/cop/style/safe_navigation_spec.rb
This PR fixes an error for `Style/SafeNavigation` when the RHS of `&&` is a complex `||` expression composed of `&&` conditions.
Fixes #14111
> [Fix #14111] Fix an error for `Style/SafeNavigation`

- changelog/change_enable_circ_arg_reference.md
- lib/rubocop/cop/lint/circular_argument_reference.rb
- spec/rubocop/cop/lint/circular_argument_reference_spec.rb
Closes #13611
It is allowed syntax again, without a warning. Conceptually it is very close to `Lint/SelfAssignment`, so I would say it makes sense to just enable this again.
> [Fix #13611] Enable `Lint/CircularArgumentReference` on Ruby 3.4

- changelog/fix_false_positives_for_style_redundant_parentheses_cop.md
- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
This PR fixes false positives for `Style/RedundantParentheses` when parens around unparenthesized method call as the second argument of a parenthesized method call.
Fixes #14120.
> [Fix #14120] Fix false positives for `Style/RedundantParentheses`

- CHANGELOG.md
- relnotes/v1.72.1.md
Noticed this while looking through the changelog to find the oldest version needed to have as a minimum requirement for proper plugin support.
maybe there should be a check somewhere that no two changelog entries refer to the same pull request/issue number, or possibly something that only lets a PR add the pr number it is created by or the issue it is linked to fixing
I didn't write an entry in the changelog for this because I presume it doesn't need one?
> Fix linked pr in changelog entry for "Extension plugin is loaded automatically with require 'rubocop/rspec/support'"

- changelog/fix_an_error_lint_boolean_symbol.md
- lib/rubocop/cop/lint/boolean_symbol.rb
- spec/rubocop/cop/lint/boolean_symbol_spec.rb
This PR fixes an infinite loop error for `Lint/BooleanSymbol` when using the rocket hash syntax with a boolean symbol key.
Fixes #14123.
> [Fix #14123] Fix an error for `Lint/BooleanSymbol`

- changelog/fix_false_positives_for_style_arguments_forwarding.md
- lib/rubocop/cop/style/arguments_forwarding.rb
- spec/rubocop/cop/style/arguments_forwarding_spec.rb
This PR fixes false positives for `Style/ArgumentsForwarding` when using default positional arg, keyword arg, and block arg in Ruby 3.1.
Fixes #14129.
> [Fix #14129] Fix false positives for `Style/ArgumentsForwarding`

- changelog/fix_style_class_and_module_children_cop_error_on_tab_intended_compactable_modules_20250422154713.md
- lib/rubocop/cop/style/class_and_module_children.rb
- spec/rubocop/cop/style/class_and_module_children_spec.rb
Before these changes most of weirdly-tab-intended programms like this
```ruby
module A
\tmodule B
\tmodule C
\tbody
\tend
\tend
end
```
were producing this error
```bash
Parser::ClobberingError:
```
This bug was found by `rubocop-nightly`.
> Fix `Style/ClassAndModuleChildren` cop error on tab-intended compactable modules

- changelog/fix_make_style_trailing_comma_in_arguments_cop_aware_of_square_brackets_20250423131225.md
- lib/rubocop/cop/mixin/trailing_comma.rb
- lib/rubocop/cop/style/trailing_comma_in_arguments.rb
- spec/rubocop/cop/style/trailing_comma_in_arguments_spec.rb
Resolves https://github.com/rubocop/rubocop/issues/14116
> [Fix #14116] Make `Style/TrailingCommaInArguments` cop aware of trailing commans in `[]` method call

- changelog/fix_lint_literal_as_condition_for_if_elsif_else.md
- lib/rubocop/cop/lint/literal_as_condition.rb
- spec/rubocop/cop/lint/literal_as_condition_spec.rb
Found while looking through #12840 to see what I had already implemented and what was left to do.
Initially I was surprised that this hadn't been reported yet, but I presume its because `Lint/LiteralAsCondition` as a cop doesn't get triggered that often, so an incorrect autocorrect for a specific case simply may not have occured yet. (Or, as in some observed cases, it may have been that the broken autocorrect was noticed and then worked around via a manual fix, and then not reported as an issue).
`correct_if_node` is getting a bit unwieldy, and would benefit from a refactor, which I'll do in another PR once i'm confident that all the functionality is there.
In any event, this PR fixes the broken autocorrect when a literal is the condition of an elsif:
```ruby
if bar
"a"
elsif true
"b" …
```
> Fix `Lint/LiteralAsCondition` autocorrect when a literal is the condition of an elsif followed by an else.

- changelog/fix_style_trailing_command_in_arguments_cop_error_on_comma_multiline_style_20250429084405.md
- lib/rubocop/cop/mixin/trailing_comma.rb
- spec/rubocop/cop/style/trailing_comma_in_arguments_spec.rb
Resolves https://github.com/rubocop/rubocop/issues/14137
All test cases for this cop are now tested with both `()` and `[]` brackets (if applicable).
Specs diff is quite big since I had to indent everything.
> [Fix #14137] Fix `Style/TrailingCommaInArguments` cop error if style is `comma`

- changelog/fix_layout_leading_comment_to_allow_rbs_comment_line_continuation_20250429122623.md
- lib/rubocop/cop/layout/leading_comment_space.rb
- spec/rubocop/cop/layout/leading_comment_space_spec.rb
At Shopify we use [RBS inline comments with Sorbet](https://sorbet.org/docs/rbs-support).
We added a syntax to allow splitting long signatures accross multiple lines like this:
```rb
#: (
#|   Integer,
#|   String
#| ) -> void
def foo; end
```
In combination with the syntax highlighting we added to the Ruby LSP, this makes it easier to read:
The issue is that Rubocop's `Layout/LeadingCommentSpace` rule will try to add a space before the `|` even with `AllowRBSInlineAnnotation` enabled.
This PR proposes adding `#|` to the list of allowed characters for RBS inline comments.
> Layout/LeadingCommentSpace: allow splitting long inline RBS comment signatures

- changelog/fix_false_positives_for_style_arguments_forwarding_cop.md
- lib/rubocop/cop/style/arguments_forwarding.rb
- spec/rubocop/cop/style/arguments_forwarding_spec.rb
This PR fixes false positives for `Style/ArgumentsForwarding` when using anonymous block argument forwarding to a method with a block.
Fixes #14131.
> [Fix #14131] Fix false positives for `Style/ArgumentsForwarding`

- changelog/fix_style_identical_conditional_branches_failure_with_implicit_if_then.md
- lib/rubocop/cop/style/identical_conditional_branches.rb
- spec/rubocop/cop/style/identical_conditional_branches_spec.rb
I observe an issue with the following ruby code:
```ruby
rubocop --only Style/IdenticalConditionalBranches -d --stdin bug.rb <<EOF
def fixed_point(value)
if value then value
else value
end
end
EOF
```
Backtrace:
```
An error occurred while Style/IdenticalConditionalBranches cop was inspecting bug.rb:2:2.
~/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/parser-3.3.5.0/lib/parser/source/tree_rewriter.rb:427:in `trigger_policy'
~/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/parser-3.3.5.0/lib/parser/source/tree_rewriter.rb:414:in `enforce_policy'
~/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/parser-3.3.5.0/lib/parser/source/tree_rewriter/action.rb:210:in `call'
~/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/parser-3.3.5.0 …
```
> Fix `Style/IdenticalConditionalBranches` cop failure in case of `if` node with implicit `then`

- changelog/fix_array_literal_in_regexp_cop_error_on_empty_interpolation_20250501213318.md
- lib/rubocop/cop/lint/array_literal_in_regexp.rb
- spec/rubocop/cop/lint/array_literal_in_regexp_spec.rb
```bash
echo '/#{}/' | bundle exec rubocop --stdin bug.rb -d
An error occurred while Lint/ArrayLiteralInRegexp cop was inspecting /bug.rb:1:0.
undefined method `array_type?' for nil
lib/rubocop/cop/lint/array_literal_in_regexp.rb:57:in `on_interpolation'
```
> Fix `Lint/ArrayLiteralInRegexp` cop error on empty interpolation

- changelog/fix_style_method_call_with_args_parentheses_with_complex_numbers_20250501222730.md
- lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb
- spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
`EnforcedStyle: omit_parentheses`
```bash
undefined method `sign?' for an instance of RuboCop::AST::Node
```
> Fix `Style/MethodCallWithArgsParentheses` cop error on complex numbers

- changelog/fix_lint_literal_as_condition_cop_error_on_if_without_body_20250501225733.md
- lib/rubocop/cop/lint/literal_as_condition.rb
- spec/rubocop/cop/lint/literal_as_condition_spec.rb
```bash
NoMethodError:
undefined method `source' for nil
```
> Fix `Lint/LiteralAsCondition` cop error on `if` without body

- changelog/change_make_layout_space_inside_hash_literal_braces_aware_of_hash_pattern.md
- lib/rubocop/cop/layout/space_inside_hash_literal_braces.rb
- spec/rubocop/cop/layout/space_inside_hash_literal_braces_spec.rb
This PR `Layout/SpaceInsideHashLiteralBraces` makes aware of hash pattern matching.
Hash literals and hash pattern matching are syntactically different features, but it would be practical to extend the existing `Layout/SpaceInsideHashLiteralBraces` cop rather than introducing a new one.
Fixes #14142.
> [Fix #14142] `Layout/SpaceInsideHashLiteralBraces` make aware of hash pattern matching

- changelog/change_make_layout_space_inside_array_literal_brackets_aware_of_array_pattern.md
- lib/rubocop/cop/layout/space_inside_array_literal_brackets.rb
- spec/rubocop/cop/layout/space_inside_array_literal_brackets_spec.rb
This PR `Layout/SpaceInsideArrayLiteralBrackets` makes aware of array pattern matching.
The same change as in #14143 will be applied to `Layout/SpaceInsideHashLiteralBraces` cop as well.
> `Layout/SpaceInsideArrayLiteralBrackets` make aware of array pattern matching

- changelog/fix_an_error_for_layout_space_after_semicolon.md
- lib/rubocop/cop/layout/space_after_semicolon.rb
- spec/rubocop/cli/autocorrect_spec.rb
- spec/rubocop/cop/layout/space_after_semicolon_spec.rb
This PR fixes the following error for `Layout/SpaceAfterSemicolon` with `Layout/SpaceBeforeSemicolon` when a sequence of semicolons appears.
```console
$ echo "foo;;" | bundle exec rubocop --stdin test.rb --enable-pending-cops -A --only Layout/SpaceAfterSemicolon,Layout/SpaceBeforeSemicolon
Infinite loop detected in /Users/koic/src/github.com/rubocop/rubocop/test.rb and caused by Layout/SpaceAfterSemicolon -> Layout/SpaceBeforeSemicolon
C
Offenses:
test.rb:1:4: C: [Corrected] Layout/SpaceAfterSemicolon: Space missing after semicolon.
foo;;
^
test.rb:1:5: C: [Corrected] Layout/SpaceBeforeSemicolon: Space found before semicolon.
foo; ;
^
1 file inspected, 2 offenses detected, 2 offenses corrected …
```
> Fix an infinite loop error for `Layout/SpaceAfterSemicolon` with `Layout/SpaceBeforeSemicolon`

- changelog/fix_autocorrect_issue_in_layout_hash_alignment_20250503213254.md
- lib/rubocop/cop/layout/hash_alignment.rb
- lib/rubocop/cop/mixin/hash_alignment_styles.rb
- spec/rubocop/cop/layout/hash_alignment_spec.rb
This is a fix with two parts.
Part 1 is to remove the attribute `max_key_width`. The `TableAlignment` class, by setting and storing a `max_key_width` value when processing the first key-value pair, didn't support hash literals with mixed separators (colon and hash rocket). The solution is to calculate the value when needed. This is less efficient, but correct.
Part 2 is to calculate the max width of separators (delimiters) in the whole hash literal, rather than assuming the width will be the same for all pairs. This, too, is done to support hashes with mixed separators.
> [Fix #14072] Resolve autocorrect issue in Layout/HashAlignment

- changelog/fix_lint_void_cop_error_on_empty_nested_begin_20250504003158.md
- lib/rubocop/cop/lint/void.rb
- spec/rubocop/cop/lint/void_spec.rb
Not the `begin` keyword actually:
```bash
echo '((); 1)' | be rubocop --stdin bug.rb --only Lint/Void -d
An error occurred while Lint/Void cop was inspecting bug.rb:1:0.
undefined method `begin_type?' for nil
lib/rubocop/cop/lint/void.rb:131:in `check_void_op'
lib/rubocop/cop/lint/void.rb:106:in `block in check_begin'
```
> Fix `Lint/Void` cop error on nested empty `begin`

- lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb
For some reason I didn't check that signless complex numbers work well with this cop.
In that case `(node.complex_type? && node.source.match?(/\A[+-]/))` would be `false` and we'd still try to send non-existend `sign?` message.
> Follow-up to #14146

- changelog/fix_layout_space_inside_array_literal_brackets_for_cop_error_on_array_pattern_without_brackets_20250505143301.md
- lib/rubocop/cop/layout/space_inside_array_literal_brackets.rb
- spec/rubocop/cop/layout/space_inside_array_literal_brackets_spec.rb
Array pattern might have no brackets:
```bash
$ echo 'case a; in a, b, _; end' | bundle exec rubocop --only Layout/SpaceInsideArrayLiteralBrackets --stdin bug.rb -d
An error occurred while Layout/SpaceInsideArrayLiteralBrackets cop was inspecting bug.rb:1:11.
undefined method '+' for nil
lib/rubocop/cop/layout/space_inside_array_literal_brackets.rb:132:in 'RuboCop::Cop::Layout::SpaceInsideArrayLiteralBrackets#next_to_newline?'
rubocop/cop/layout/space_inside_array_literal_brackets.rb:95:in 'RuboCop::Cop::Layout::SpaceInsideArrayLiteralBrackets#on_array'
```
This bug was introduced in https://github.com/rubocop/rubocop/pull/14144
> Fix `Layout/SpaceInsideArrayLiteralBrackets` cop error on array pattern without brackets

- changelog/fix_style_percent_q_literals_cop_error_on_unicode_escape_sequence.md
- lib/rubocop/cop/style/percent_q_literals.rb
- spec/rubocop/cop/style/percent_q_literals_spec.rb
Prior to these changes this cop would try to take `%q(\u)`, change `q` to `Q` and parse it. The result (processed source) would contain the `invalid_unicode_escape` diagnostic error -- but it would be ignored.
Since is that case `ast` is `nil` a `NoMethodError` is thrown.
I don't know if we should only check for this specific diagnostics or all of them.
> Fix `Style/PercentQLiterals` cop error on Unicode escape sequence

- changelog/fix_error_for_lint_useless_assignment_cop.md
- lib/rubocop/cop/lint/useless_assignment.rb
- spec/rubocop/cop/lint/useless_assignment_spec.rb
This PR fixes the following error for `Lint/UselessAssignment` when variables are assigned using unary operator in chained assignment and remain unreferenced.
```console
$ echo "a = -b = c" | bundle exec rubocop --stdin test.rb --enable-pending-cops -A --only Lint/UselessAssignment
An error occurred while Lint/UselessAssignment cop was inspecting /Users/koic/src/github.com/rubocop/rubocop/test.rb.
W
Offenses:
test.rb:1:1: W: [Corrected] Lint/UselessAssignment: Useless assignment to variable - a.
a = -b = c
^
test.rb:1:2: W: [Corrected] Lint/UselessAssignment: Useless assignment to variable - b.
-b = c
^
1 file inspected, 2 offenses detected, 2 offenses corrected
An error occurred while Lint/UselessAssignment …
```
> Fix an error for `Lint/UselessAssignment`

- lib/rubocop/formatter/html_formatter.rb
In ruby 3.5 most of the functionality wil require adding `cgi` as a dependency.
Only escape/unescape functions will remain (which is what RuboCop actually uses)
https://bugs.ruby-lang.org/issues/21258.
Note: ruby-lsp also requires "plain cgi". I will make a PR to them as well.
> Only load what is required from `cgi`

- changelog/fix_change_nil_representation_in_todo_file_comments_20250510150728.md
- lib/rubocop/formatter/disabled_config_formatter.rb
- spec/rubocop/cli/auto_gen_config_spec.rb
Some cops use `nil` as a supported value for enforced style in their configuration. This is expressed using tilde (`~`) in the configuration file. Nil usually means a fallback to some default value.
When we list supported styles in `.rubocop_todo.yml`, we should express these values as `~`, i.e., using YAML syntax. Before this change the `nil` values were shown as empty strings, which was confusing.
> [Fix #14077] Change `nil` representation in todo file comments

- changelog/fix_error_for_style_string_concatenation.md
- lib/rubocop/cop/style/string_concatenation.rb
- spec/rubocop/cop/style/string_concatenation_spec.rb
This PR fixes the following error for `Style/StringConcatenation` when using implicit concatenation with string interpolation:
```console
$ echo "\"string #{interpolation}\" 'foo' + 'bar'" | bundle exec rubocop --stdin example.rb --only Style/StringConcatenation -A -d
(snip)
An error occurred while Style/StringConcatenation cop was inspecting /Users/koic/src/github.com/rubocop/rubocop/example.rb:1:0.
undefined method 'end_pos' for nil
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/mixin/range_help.rb:34:in 'RuboCop::Cop::RangeHelp#contents_range'
```
> Fix an error for `Style/StringConcatenation`

- changelog/change_make_style_if_unless_modifier_allow_endless_method_definition.md
- lib/rubocop/cop/style/if_unless_modifier.rb
- spec/rubocop/cop/style/if_unless_modifier_spec.rb
This PR makes `Style/IfUnlessModifier` allow endless method definition in the `if` body.
The code `def method_name = body if condition` is considered a bad case by `Style/AmbiguousEndlessMethodDefinition` cop. So, to respect the user's intention to use an endless method definition in the `if` body, the following code is allowed:
```ruby
if condition
def method_name = body
end
```
Resolves #14156.
> [Fix #14156] Make `Style/IfUnlessModifier` allow endless method definition

- .github/workflows/rubocop.yml
This PR　temporarily disables Windows CI matrix for Ruby 2.7 to prevent the following CI error until the MSYS2 issue https://github.com/ruby/setup-msys2-gcc/pull/26#issuecomment-2874639475 is resolved:
```console
C:/hostedtoolcache/windows/Ruby/2.7.8/x64/lib/ruby/2.7.0/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
D:/a/rubocop/rubocop/vendor/bundle/ruby/2.7.0/gems/date-3.4.1/lib/date.rb:4:in `require': 127: The specified procedure could not be found.
D:/a/rubocop/rubocop/vendor/bundle/ruby/2.7.0/gems/date-3.4.1/lib/date_core.so (LoadError)
from D:/a/rubocop/rubocop/vendor/bundle/ruby/2.7.0/gems/date-3.4.1/lib/date.rb:4:in `<top (required)>'
from …
```
> Temporarily disable Windows CI matrix for Ruby 2.7

- lib/rubocop/cop/style/data_inheritance.rb
- lib/rubocop/cop/style/struct_inheritance.rb
Adds explanation for why these cops are useful. Note that this is already [noted in the style guide](https://rubystyle.guide/#no-extend-struct-new).
> Expand `Style/DataInheritance` and `Style/StructInheritance` docs

- changelog/fix_false_positives_for_style_sole_nested_conditional.md
- lib/rubocop/cop/style/sole_nested_conditional.rb
- spec/rubocop/cop/style/sole_nested_conditional_spec.rb
This PR fixes false positives for `Style/SoleNestedConditional` when using nested `if` and `not` in condition.
Fixes #14177.
> [Fix #14177] Fix false positives for `Style/SoleNestedConditional`

- changelog/fix_an_error_for_style_multiline_if_modifier_cop.md
- lib/rubocop/cop/style/multiline_if_modifier.rb
- spec/rubocop/cop/style/multiline_if_modifier_spec.rb
This PR fixes the following error for `Style/MultilineIfModifier` when using nested modifier:
```console
[
] unless inner unless outer
$ bundle exec rubocop example.rb --only Style/MultilineIfModifier -a -d
For /tmp: An error occurred while Style/MultilineIfModifier cop was inspecting /tmp/example.rb:1:0.
```
> Fix an error for `Style/MultilineIfModifier`

- changelog/change_comparable_between_unsafe.md
- config/default.yml
- lib/rubocop/cop/style/comparable_between.rb
Fixes #14082
Closes #14087
It relies on the fact that between? is available, which it doesn't have to be (especially for types that implement custom comparision methods.
> [Fix #14082] Mark `Style/ComparableBetween` as unsafe

- changelog/change_make_lint_duplicate_methods_aware_of_active_support_delegate.md
- lib/rubocop/cop/lint/duplicate_methods.rb
- spec/rubocop/cop/lint/duplicate_methods_spec.rb
This PR adds support for Active Support's method [`delegate`](https://api.rubyonrails.org/classes/Module.html#method-i-delegate) to `Lint/DuplicateMethods`. Previously, code such as:
```ruby
class A
def foo; end
delegate :foo, to: :bar
end
```
wouldn't register as offense in a project with Active Support extensions.
After this PR, an offense is registered. When `ActiveSupportExtensionsEnabled` is `false`, an offense is not registered.
> Make `Lint/DuplicateMethods` aware of Active Support's `delegate` method

- changelog/change_lint_duplicate_methods_delegate_prefix.md
- lib/rubocop/cop/lint/duplicate_methods.rb
- spec/rubocop/cop/lint/duplicate_methods_spec.rb
Follow-up to https://github.com/rubocop/rubocop/pull/14181#issuecomment-2882948451, cc @Earlopain.
Makes `Lint/DuplicateMethods` recognize `prefix` keyword argument for duplicate method created via `delegate`.
Additionally, makes a couple other adjustments (this should have been done in https://github.com/rubocop/rubocop/pull/14181 but it got merged a bit too soon):
- `delegate` method names can be strings or symbols (previously they could be only symbols)
- `to` is now a required keyword argument
- an offense won't be registered when `**kwargs` is used as `delegate` options
> Recognize `prefix` argument for `delegate` method in `Lint/DuplicateMethods`

- changelog/fix_style_access_modifier_declarations_false_positives_when_there_are_no_defs_20250511175839.md
- lib/rubocop/cop/style/access_modifier_declarations.rb
- spec/rubocop/cop/style/access_modifier_declarations_spec.rb
When there are no definitions two styles behave inconsistenly:
```ruby
$ echo 'private' | bundle exec rubocop --only Style/AccessModifierDeclarations --stdin /bin/false -c <(echo 'Style/AccessModifierDeclarations:\n EnforcedStyle: group')
.
$ echo 'private' | bundle exec rubocop --only Style/AccessModifierDeclarations --stdin /bin/false -c <(echo 'Style/AccessModifierDeclarations:\n EnforcedStyle: inline')
C
Offenses:
/bin/false:1:1: C: [Correctable] Style/AccessModifierDeclarations: private should be inlined in method definitions.
private
^^^^^^^
1 file inspected, 1 offense detected, 1 offense autocorrectable
```
I think in both cases there should be no offense (let `Lint/UselessAccessModifier` handle it). …
> Fix `Style/AccessModifierDeclarations` false positives with `inline` style and missing defs

- changelog/fix_incorrect_autocorrect_for_layout_space_before_brackets.md
- lib/rubocop/cop/layout/space_before_brackets.rb
- spec/rubocop/cop/layout/space_before_brackets_spec.rb
This PR incorrect autocorrect for `Layout/SpaceBeforeBrackets` when using space between receiver and left brackets, and a space inside left bracket.
Fixes #14189.
> [Fix #14189] Fix incorrect autocorrect for `Layout/SpaceBeforeBrackets`

- changelog/change_gemspec_duplicated_assignment_cop_to_detect_duplicated_indexed_assignments_20250516224426.md
- lib/rubocop/cop/gemspec/duplicated_assignment.rb
- spec/rubocop/cop/gemspec/duplicated_assignment_spec.rb
This patch aims to detect gemspecs like this one:
```ruby
...
spec.metadata["foo"] = "bar"
...
spec.metadata["foo"] = "baz" # offense
```
Mixed indexed and normal assignments are fine:
```ruby
spec.metadata = { ?? }
spec.metadata["foo"] = "bar"
```
but we can enhance this cop to detect duplicated keys when using both types of assignment:
```ruby
spec.metadata = { "foo" => "bar" }
spec.metadata["foo"] = "bar" # should be an offense
```
> Enhance `Gemspec/DuplicatedAssignment` cop to detect duplicated indexed assignment

- lib/rubocop/cop/metrics/abc_size.rb
- spec/rubocop/cop/metrics/abc_size_spec.rb
Before this patch `Metric` department cops highlighted method name inconsistently. To be precise, the only cop without highlight is `AbcSize`.
> Consistently highlight `Metric` cops method name in offense messages

- changelog/fix_useless_assign_splat_mlhs.md
- lib/rubocop/cop/variable_force/assignment.rb
- spec/rubocop/cop/lint/useless_assignment_spec.rb
- spec/rubocop/cop/variable_force/assignment_spec.rb
Fix #14193
The ast for `(left, right), *rest = foo` looks like this:
```
(masgn
(mlhs
(mlhs
(lvasgn :left)
(lvasgn :right))
(splat
(lvasgn :rest)))
(send nil :foo))
```
Because of the splat node, it must reach up one furhter to land at the conclusion that this is indeed multiple assignment. Otherwise, it gets treated as normal assignment, where the type of autocorrect is not appropriate.
> [Fix #14193] Fix `Lint/UselessAssignment` cop error when using nested assignment with splat

- .github/workflows/rubocop.yml
This PR enables Windows CI matrix for Ruby 2.7.
Reverts #14175.
> Enable Windows CI matrix for Ruby 2.7

- changelog/fix_layout_empty_lines_around_access_modifier_cop_error_on_trailling_modifier_20250525193657.md
- lib/rubocop/cop/layout/empty_lines_around_access_modifier.rb
- spec/rubocop/cop/layout/empty_lines_around_access_modifier_spec.rb
```bash
echo '1; private' | bundle exec rubocop --stdin bug.rb -c <(echo 'Layout/EmptyLinesAroundAccessModifier:\n EnforcedStyle: only_before') --only Layout/EmptyLinesAroundAccessModifier -d
configuration from /proc/self/fd/18
Default configuration from config/default.yml
Scanning //bug.rb
An error occurred while Layout/EmptyLinesAroundAccessModifier cop was inspecting //bug.rb:1:3.
The range 11...12 is outside the bounds of the source
/home/viralpraxis/.asdf/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/parser-3.3.8.0/lib/parser/source/tree_rewriter.rb:406:in 'Parser::Source::TreeRewriter#check_range_validity'
//lib/rubocop/cop/corrector.rb:120:in 'RuboCop::Cop::Corrector#check_range_validity'
/home/viralpraxis/.asdf/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/parser-3. …
```
> Fix `Layout/EmptyLinesAroundAccessModifier` cop error on trailing access modifier

- tasks/codespell.rake
Without this patch, running `bundle exec rake default` or `bundle exec rake codespell` without installed `codespell` (or if is not in `$PATH`) leads to an error:
```bash
bundle exec rake
git ls-files --empty-directory | xargs codespell
xargs: codespell: No such file or directory
rake aborted!
Command failed with status (127): [git ls-files --empty-directory | xargs codespell]
tasks/codespell.rake:10:in 'block (2 levels) in <top (required)>'
tasks/codespell.rake:8:in 'block in <top (required)>'
/home/viralpraxis/.asdf/installs/ruby/3.4.4/bin/bundle:25:in 'Kernel#load'
/home/viralpraxis/.asdf/installs/ruby/3.4.4/bin/bundle:25:in '<main>'
Tasks: TOP => default => codespell
(See full trace by running task with --trace)
```
It seems like it should just print the error message and continue: …
> Fix `codespell` rake task if not found in PATH

- changelog/change_add_allow_single_line_to_style_it_block_parameter.md
- config/default.yml
- lib/rubocop/cop/style/it_block_parameter.rb
- spec/rubocop/cop/style/it_block_parameter_spec.rb
This PR adds `EnforcedStyle: allow_single_line` as the default to `Style/ItBlockParameter`.
This adds the default configuration that follows `EnforcedStyle: allow_single_line (default)` of `Style/NumberedParameters` cop:
https://docs.rubocop.org/rubocop/1.75/cops_style.html#stylenumberedparameters
In RuboCop, numbered block parameters are allowed only in single-line blocks. It makes sense to apply the same default style to `it` block parameters as well.
> Add `EnforcedStyle: allow_single_line` as the default to `Style/ItBlockParameter`

- changelog/change_disable_lint_shadowing_outer_local_variable_by_20250203115238.md
- config/default.yml
Lint/ShadowingOuterLocalVariable cop was initially added as Syntax cop, which warns if the Ruby system issues warnings.
- https://github.com/rubocop/rubocop/commit/fd4eabea8b5b81e5bd742bfe7030d7e0ca242ecb
- https://github.com/rubocop/rubocop/commit/72d278959b40e08271afc102cd29626f16c58030
However, the Ruby warning corresponding to Lint/ShadowingOuterLocalVariable was removed in Ruby 2.6. This is because:
> It was introduced to ruby 1.9, a version which changes behaviors on conflicts of local vars and block param. I understand it is to tell the user the change, and let them fix if their program depends on 1.8 behavior. ruby 1.9.1 is released in 2009, almost seven years ago, and most ruby programmers today would have correct understanding of current behavior. In my opinion, the warning does …
> Disable `Lint/ShadowingOuterLocalVariable` by default

- lib/rubocop/cop/style/empty_string_inside_interpolation.rb
- spec/rubocop/cop/style/empty_string_inside_interpolation_spec.rb
```shell
echo '"#{cond ? foo : 1}"' | bundle exec rubocop --stdin bug.rb --only Style/EmptyStringInsideInterpolation -d
An error occurred while Style/EmptyStringInsideInterpolation cop was inspecting bug.rb:1:0.
lib/rubocop/cop/style/empty_string_inside_interpolation.rb:78:in 'RuboCop::Cop::Style::EmptyStringInsideInterpolation#empty_if_outcome': undefined method 'value' for an instance of RuboCop::AST::SendNode (NoMethodError)
node.if_branch&.nil_type? || node.if_branch&.value&.empty?
^^^^^^^
from lib/rubocop/cop/style/empty_string_inside_interpolation.rb:51:in 'block in RuboCop::Cop::Style::EmptyStringInsideInterpolation#on_interpolation'
```
> Fix `Style/EmptyStringInsideInterpolation` cop error on non-literal branch node

- spec/rubocop/cop/lint/mixed_case_range_spec.rb
- spec/rubocop/cop/lint/redundant_regexp_quantifiers_spec.rb
- spec/rubocop/cop/lint/redundant_string_coercion_spec.rb
- spec/rubocop/cop/style/class_and_module_children_spec.rb
A few minor spelling fixes that are not user facing.
> Minor spelling fixes (non-user facing)

- config/default.yml
- lib/rubocop/cop/style/empty_string_inside_interpolation.rb
- spec/rubocop/cop/style/empty_string_inside_interpolation_spec.rb
Follow-up to #13266.
The names `EnforcedStyle: trailing_conditional` and `EnforcedStyle: ternary` appear to be reversed. This PR swaps the names accordingly.
```ruby
"#{condition ? 'foo' : ''}"
"#{'foo' if condition}"
```
```ruby
"#{'foo' if condition}"
"#{condition ? 'foo' : ''}"
```
Also, since there were no test cases using `expect_no_offenses`, This PR added representative tests for each style. Since this has not been released yet, there is no changelog entry.
> Rename `EnforcedStyle` of `Style/EmptyStringInsideInterpolation`

- changelog/change_recognize_inequation_in_lint_identity_comparison.md
- lib/rubocop/cop/lint/identity_comparison.rb
- spec/rubocop/cop/lint/identity_comparison_spec.rb
Expands `Lint/IdentityComparison` to register:
```ruby
foo.object_id != bar.object_id
```
as an offense, and autocorrect to:
```ruby
!foo.equal?(bar)
```
> Recognize inequation in `Lint/IdentityComparison`

- changelog/fix_false_negatives_in_style_safenavigation_20250530140637.md
- lib/rubocop/cop/style/safe_navigation.rb
- spec/rubocop/cop/style/safe_navigation_spec.rb
Fix false negatives in Style/SafeNavigation #14205
```
puts(user.nil? ? nil : user.name)          # ❌
results << (user.nil? ? nil : user.name)   # ❌
results[0] = user.nil? ? nil : user.name   # ❌
```
to
```
puts(user.nil? ? nil : user.name)          # ✅ Offense found
results << (user.nil? ? nil : user.name)   # ✅ Offense found
results[0] = user.nil? ? nil : user.name   # ✅ Offense found
```
> [fix #14205] False negatives in `Style/Safenavigation`

- spec/rubocop/cop/gemspec/duplicated_assignment_spec.rb
We're already testing hash assignments here but I'd like to make sure array assignment is also not detected since it will be handled by a dedicated cop.
> Add extra spec for `Gemspec/DuplicatedAssignment` cop with array assignments

- spec/rubocop/cop/gemspec/duplicated_assignment_spec.rb
Nit: according to the spec [0] `metadata` keys should be strings
[0] https://guides.rubygems.org/specification-reference/#metadata
> Use valid `metadata` keys in `Gemspec/DuplicatedAssignment` cop specs

- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
This PR fixes false positives for `Style/RedundantParentheses` when using one-line hash `in` pattern matching in a method argument.
Fixes #14217.
> [Fix #14217] Fix false positives for `Style/RedundantParentheses`

- changelog/fix_lint_literal_as_condition_autocorrect_when_branches_have_comments.md
- lib/rubocop/cop/lint/literal_as_condition.rb
- spec/rubocop/cop/lint/literal_as_condition_spec.rb
It turns out `IfNodes` can get more complex!
This should cover the relatively simple case, although since nobody's reported anything yet I doubt this is a common code pattern.
> Fix `Lint/LiteralAsCondition` autocorrect when branches of a condition have comments

- changelog/fix_a_false_positive_for_style_redundant_parentheses_cop.md
- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
This PR fixes a false positive for `Style/RedundantParentheses` when using a one-line `rescue` expression as a method argument.
Fixes #14228.
> [Fix #14228] Fix false positive for `Style/RedundantParentheses`

- changelog/fix_an_error_for_style_safe_navigation_cop.md
- lib/rubocop/cop/style/safe_navigation.rb
- spec/rubocop/cop/style/safe_navigation_spec.rb
This PR fixes an error for `Style/SafeNavigation` when using ternary expression with index access call.
Fixes #14233
> [Fix #14233] Fix an error for `Style/SafeNavigation`

- changelog/fix_style_safe_navigation_cop_error_on_indexed_assignment_in_ternary_20250604135356.md
- lib/rubocop/cop/style/safe_navigation.rb
- spec/rubocop/cop/style/safe_navigation_spec.rb
Follow up to #14234
The same error happens when there's a `#[]=` method call in ternary expression.
> Follow up to #14234: handle indexed assignment

- changelog/fix_error_for_style_safe_navigation.md
- lib/rubocop/cop/style/safe_navigation.rb
- spec/rubocop/cop/style/safe_navigation_spec.rb
This PR fixes an error for `Style/SafeNavigation` when using ternary expression with operator method call.
Fixes #14236.
> [Fix #14236] Fix an error for `Style/SafeNavigation`

- Gemfile
This PR is a workaround to avoid the following build error in the Ruby LSP add-on test with Ruby LSP 0.24. https://github.com/rubocop/rubocop/actions/runs/15497886582/job/43638843391?pr=14251
The build error will be resolved in https://github.com/rubocop/rubocop-ast/pull/382.
> Workaround to avoid build error in Ruby LSP add-on test with Ruby LSP 0.24

- spec/rubocop/server/cache_spec.rb
This PR fixes the following build errors on Winsows matrix: https://github.com/rubocop/rubocop/actions/runs/15509910142/job/43669493524
> Fix build errors on Winsows matrix

- config/default.yml
- tasks/cut_release.rake
- tasks/references.rake
Reference URLs in the configuration may become outdated over time. To help catch issues early, especially before releasing a new version, this patch introduces a new rake task: `references:verify`.
The task iterates over existing references and reports any broken or unreachable URLs.
There's a bunch of unnecessary redirects in this repository, but some plugins actually contain unreachable links in their configs, so it'd be good to use this task in other repos too.
> Add new rake task to verify config references availability

- docs/modules/ROOT/pages/development.adoc
- lib/rubocop/rspec/expect_offense.rb
The existing documentation mentions `%{foo}`, `^{foo}`, & `_{foo}`, but doesn't explicitly explain what they do. The example is good, but we can complement it by explicitly stating their purposes.
* ~Added tests.~ _Not applicable_
* ~Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.~ _Not worth including_
> Improve `expect_offense` interpolation documentation

- changelog/fix_false_positives_for_style_redundant_array_flatten.md
- lib/rubocop/cop/style/redundant_array_flatten.rb
- spec/rubocop/cop/style/redundant_array_flatten_spec.rb
`Style/RedundantArrayFlatten` cop is already marked as unsafe, but this change prevents false positives when `Array#join` is used with an argument other than the default value `nil`.
Fix #14249.
> [Fix #14249] Fix false positives for `Style/RedundantArrayFlatten`

- changelog/change_add_allowed_patterns_and_allow_bang_methods_20250610090316.md
- config/default.yml
- lib/rubocop/cop/naming/predicate_method.rb
- spec/rubocop/cop/naming/predicate_method_spec.rb
* `AllowedPatterns` allows regular expressions to be set for allowing method names.
* `AllowBangMethods` allows method names ending with a bang (`!`) to always be accepted by the cop.
Fixes #14232.
> [Fix #14232] Add `AllowedPatterns` and `AllowBangMethods` configuration to `Naming/PredicateMethod`

- changelog/fix_an_error_for_lint_empty_interpolation.md
- lib/rubocop/cop/lint/empty_interpolation.rb
- spec/rubocop/cop/lint/empty_interpolation_spec.rb
This PR fixes an error for `Lint/EmptyInterpolation` when using a boolean literal inside interpolation.
Fixes #14273.
> [Fix #14273] Fix an error for `Lint/EmptyInterpolation`

- changelog/fix_false_positives_for_style_redundant_parentheses.md
- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
This PR fixes false positives for `Style/RedundantParentheses` when using parenthesized one-line pattern matching in endless method definition.
Fixes #14275.
> [Fix #14275] Fix false positives for `Style/RedundantParentheses`

- Gemfile
- rubocop.gemspec
Follow-up to https://github.com/rubocop/rubocop-ast/pull/382.
This PR fixes the following build error on when using Parser gem with `prism_result` and Ruby LSP >= 0.24. https://github.com/rubocop/rubocop/actions/runs/15497886582/job/43638843391?pr=14251
> Fix build error when using Ruby LSP >= 0.24

- changelog/fix_incorrect_autocorrect_for_lint_safe_navigation_chain.md
- lib/rubocop/cop/lint/safe_navigation_chain.rb
- spec/rubocop/cop/lint/safe_navigation_chain_spec.rb
This PR fixes incorrect autocorrect for `Lint/SafeNavigationChain` when a safe navigation is used on the left-hand side of a `-` operator when inside an array.
Fixes #14286.
> [Fix #14286] Fix incorrect autocorrect for `Lint/SafeNavigationChain`

- docs/modules/ROOT/pages/cops.adoc
This pull request fixes a few minor typos in the Cops documentation.
> Fix typos in Cops docs

- lib/rubocop/cop/lint/useless_access_modifier.rb
Long time ago there was not built-in check for the `included` method so people had to add it to their configurations manually.
It now produces this warning
```bash
rubocop-1.76.1/lib/rubocop/cop/lint/useless_access_modifier.rb:285: warning: method redefined; discarding old included_block?
rubocop-1.76.1/lib/rubocop/cop/lint/useless_access_modifier.rb:248: warning: previous definition of included_block? was here
```
I think if we want people to know there's no need to specify `included` in their configs there should be an explicit RuboCop-produced warning.
This patch simply skips matcher definition for this method.
> Fix warning on duplicated `Lint/UselessAccessModifier` `MethodsCreationContext` option

- changelog/fix_style_method_call_with_args_parentheses_false_positives_20250619020633.md
- lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb
- spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
Resolves https://github.com/rubocop/rubocop/issues/14307
> [Fix #14307] Fix `Style/MethodCallWithArgsParentheses` false positives

- changelog/fix_false_positives_for_style_redundant_parentheses.md
- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
This PR fixes false positives for `Style/RedundantParentheses` when assigning a parenthesized one-line `in` pattern matching.
Fixes #14292.
> [Fix #14292] Fix false positives for `Style/RedundantParentheses`

- changelog/fix_an_error_for_style_sole_nested_conditional.md
- lib/rubocop/cop/style/sole_nested_conditional.rb
- spec/rubocop/cop/style/sole_nested_conditional_spec.rb
This PR fixes an error for `Style/SoleNestedConditional` when autocorrecting nested if/unless/if.
Fix #14298.
> [Fix #14298] Fix an error for Style/SoleNestedConditional

- changelog/fix_lint_self_assignment_to_allow_inline_rbs_comments_20250618115326.md
- config/default.yml
- lib/rubocop/cop/lint/self_assignment.rb
- spec/rubocop/cop/lint/self_assignment_spec.rb
When using RBS, with Steep for example, it's sometimes useful to [add an inline type annotation](https://github.com/soutaro/steep/blob/6d66d0d174bc8d2fe6cd2ed8925936894c26f5c4/lib/steep.rb#L327).
These type annotations are inserted as comment, generally around assignments, after the rhs:
```rb
foo = [] #: Array[Integer]
```
Sometimes we also need to "cast" the type of a variable:
```rb
foo = foo #: Array[Numeric]
```
In those cases, the `Lint/SelfAssignment` cop will raise an offence for a useless self assignment.
This PR adds an option `AllowRBSInlineAnnotation` to `Lint/SelfAssignment` similar to the one used in (`Layout/LeadingCommentSpace`)[b543aee0a5831/config/default.yml#L1043] so the user can disable the offence when needed. …
> Fix `Lint/SelfAssignment` to allow inline RBS comments.

- changelog/new_add_new_gemspec_attribute_assignment_cop_20250601175128.md
- config/default.yml
- lib/rubocop.rb
- lib/rubocop/cop/gemspec/attribute_assignment.rb
- lib/rubocop/cop/gemspec/duplicated_assignment.rb
- lib/rubocop/cop/mixin/gemspec_help.rb
- spec/rubocop/cop/gemspec/attribute_assignment_spec.rb
See https://github.com/rubocop/rubocop/pull/14188#issuecomment-2890385223
The new `Gemspec/ConsistentAssignment` cop discourages mixing "normal" and "indexed" assignment styles.
Bad:
```ruby
spec.metadata = { 'a' => 'b' }
spec.metadata['c'] = 'd'
```
Good:
```ruby
spec.metadata = { 'a' => 'b', 'c' => 'd' }
spec.metadata['a'] = 'b'
spec.metadata['c'] = 'd]
```
> Add new `Gemspec/AttributeAssignment` cop

- changelog/fix_style_redundant_parentheses_multiline.md
- lib/rubocop/cop/correctors/parentheses_corrector.rb
- spec/rubocop/cop/style/parentheses_around_condition_spec.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
Given the following example:
```ruby
(
foo == 'a' ||
foo == 'b' ||
foo == 'c'
) && bar
```
`Style/MultipleComparison` will autocorrect it to:
```ruby
(
['a', 'b', 'c'].include?(foo)
) && bar
```
and then `Style/RedundantParentheses` will autocorrect that to:
```ruby
['a', 'b', 'c'].include?(foo)
&& bar
```
which is invalid syntax.
This PR attempts to resolve this by additionally removing space _after_ opening parentheses and _before_ closing parentheses, so that `Style/RedundantParentheses` autocorrects the example to:
```ruby
['a', 'b', 'c'].include?(foo) && bar
```
This of course affects some other examples. Let me know if the error should be resolved another way.
[1]: …
> Fix autocorrection syntax error for multiline expressions in Style/RedundantParentheses

- docs/modules/ROOT/pages/extensions.adoc
This pull request fixes a stale link to the `Parser` gem docs and a few minor typos in the "Plugin Configuration" documentation.
> Fix a stale link in the Plugin Configuration docs

- changelog/new_allow_long_fully_qualified_namespace_strings_20250618172915.md
- config/default.yml
- docs/modules/ROOT/pages/cops_layout.adoc
- lib/rubocop/cop/layout/line_length.rb
- lib/rubocop/cop/mixin/line_length_help.rb
- lib/rubocop/cop/style/if_unless_modifier.rb
- lib/rubocop/lsp/diagnostic.rb
- lib/ruby_lsp/rubocop/addon.rb
- spec/rubocop/cli/auto_gen_config_spec.rb
- spec/rubocop/cli/options_spec.rb
- spec/rubocop/cli_spec.rb
- spec/rubocop/config_loader_spec.rb
- spec/rubocop/cop/layout/line_length_spec.rb
- `AllowQualifiedName` allows long fully-qualified namespace strings to exceed max length. This works exactly as `AllowURI`.
Fixes https://github.com/rubocop/rubocop/issues/14128
> [Fix #14128] Allow long fully-qualified namespace strings to exceed max length

- docs/modules/ROOT/pages/development.adoc
Broken sample code on: https://docs.rubocop.org/rubocop/development.html#limit-by-ruby-or-gem-versions
> Fix missing quote in sample code

- changelog/fix_incorrect_autocorrect_for_lint_redundant_type_conversion.md
- lib/rubocop/cop/lint/redundant_type_conversion.rb
- spec/rubocop/cop/lint/redundant_type_conversion_spec.rb
This PR fixes the following incorrect autocorrect for `Lint/RedundantTypeConversion` when using parentheses with no arguments or any arguments.
First, this applies to parentheses with no arguments.
```console
$ echo '{k => v}.to_h()' | bundle exec rubocop --stdin test.rb -a --only Lint/RedundantTypeConversion
F
Offenses:
test.rb:1:9: F: Lint/Syntax: unexpected token tLPAREN2
{k => v}()
^
test.rb:1:10: W: [Corrected] Lint/RedundantTypeConversion: Redundant to_h detected.
{k => v}.to_h()
^^^^
{k => v}()
```
It is currently autocorrected to an invalid syntax with unnecessary parentheses. Since this case is …
> Fix incorrect autocorrect for `Lint/RedundantTypeConversion`

- changelog/fix_false_positives_for_lint_literal_as_condition.md
- lib/rubocop/cop/lint/literal_as_condition.rb
- spec/rubocop/cop/lint/literal_as_condition_spec.rb
This PR fixes false positives for `Lint/LiteralAsCondition` when a literal is used inside `||` in `case` condition.
Fixes #14329.
> [Fix #14329] Fix false positives for `Lint/LiteralAsCondition`

- changelog/change_add_non_boolean_predicates_config_to_20250623094531.md
- config/default.yml
- lib/rubocop/cop/naming/predicate_method.rb
- spec/rubocop/cop/naming/predicate_method_spec.rb
Allows `Naming/PredicateMethod` to be aware of methods that look like predicates but do not return a boolean value, when determining if a method's return value is boolean.
Fixes #14318.
> [Fix #14318] Add `WaywardPredicates` config to `Naming/PredicateMethod` to handle methods that look like predicates but aren't

- changelog/new_enhance_naming_method_name_cop_to_detect_offenses_within_define_method_calls_20250626032151.md
- lib/rubocop/cop/naming/method_name.rb
- spec/rubocop/cop/naming/method_name_spec.rb
ref: https://github.com/rubocop/rubocop/pull/14325#issuecomment-3004010614
This patch enhances `Naming/MethodName` to detect these offenses:
```ruby
define_method(:fooBar) {} # offense if style is `snake_case`
define_method(:foo_bar) {} # offense if style is `camelCase`
```
> Enhance `Naming/MethodName` cop to detect offenses within `define_method` calls

- changelog/change_add_non_boolean_predicates_config_to_20250623094531.md
In #14327 the new configuration name was changed but I forgot to update the changelog.
> Fix changelog for `Naming/PredicateMethod`

- changelog/new_enhance_naming_method_name_cop_to_handle_offenses_within_struct_members_20250623141515.md
- lib/rubocop/cop/naming/method_name.rb
- spec/rubocop/cop/naming/method_name_spec.rb
This patch enhances `Naming/MethodName` to detect these offenses:
```ruby
Struct.new(:fooBar) # offense if style is `snake_case`
Struct.new(:foo_bar) # offense if style is `camelCase`
```
Since the first argument of `Struct.new` might be a special string (`class_name`), it's ignored. See https://rubyapi.org/3.4/o/struct#method-c-new
> Enhance `Naming/MethodName` cop to handle offenses within `Struct` members

- changelog/new_enhance_security_eval_cop_to_detect_kernel_eval_20250630232046.md
- lib/rubocop/cop/security/eval.rb
- spec/rubocop/cop/security/eval_spec.rb
I'm not sure if `Kernel.eval` is not detected intentionally, but if it's not, here's a patch.
> Enhance `Security/Eval` cop to detect `Kernel.eval` calls

- changelog/fix_bug_where_specifying_format_disables_20250702192712.md
- lib/rubocop/cli.rb
When `--format` or `-f` CLI option is specified, `@options.keys` becomes `[:format, :formatters]` rather than just `[:format]`.
To ensure the following code works correctly, I believe we need to add `:formatters` to `DEFAULT_PARALLEL_OPTIONS` as well.
https://github.com/rubocop/rubocop/blob/da5d9d4213370d5292f289dc559691a76dc2fda1/lib/rubocop/cli.rb#L148-L153
Before the change, parallel execution was not enabled by default, as shown below:
```
$ bundle exec rubocop Gemfile --debug --format progress | grep "Use parallel by default."
$ echo $?
1
```
After the change, parallel execution is enabled by default.
```
$ bundle exec rubocop Gemfile --debug --format progress | grep "Use parallel by default."
Use parallel by default.
$ echo $?
0
```
FYI: As a background, I often run `bundle exec …
> Fix bug where specifying `--format` disables parallelization

- changelog/fix_false_positives_for_lint_duplicate_methods_20250618124754.md
- lib/rubocop/cop/lint/duplicate_methods.rb
- spec/rubocop/cop/lint/duplicate_methods_spec.rb
When there's a self-alias, there's no need to register an offense:
```ruby
class a
alias foo foo
def foo; end
end
```
Using the alias-self trick indicates that developer is trying to avoid "method redefinition" warning.
> Fix false positives for `Lint/DuplicateMethods` when the self-alias trick is used

- changelog/fix_incorrect_autocorrect_for_style_single_line_methods_cop.md
- lib/rubocop/cop/style/single_line_methods.rb
- spec/rubocop/cop/style/single_line_methods_spec.rb
Fix incorrect autocorrect for `Style/SingleLineMethods` when a single-line method definition contains a modifier.
Fixes #14344.
> [Fix #14344] Fix incorrect autocorrect for `Style/SingleLineMethods`

- changelog/fix_fix_incorrect_autocorrect_for_20250709134109.md
- lib/rubocop/cop/style/access_modifier_declarations.rb
- spec/rubocop/cop/style/access_modifier_declarations_spec.rb
I noticed that when running autocorrect for `Style/AccessModifierDeclarations`, the method above the group declaration was being deleted. So this:
```ruby
class MyThing
def other_method; end
def a_method_that_is_public; end
private
def my_other_private_method; end
end
```
After going through autocorrect would become:
```ruby
class MyThing
def other_method; end
private
private def my_other_private_method; end
end
```
This PR adds a spec demonstrating the behavior with as small a code sample as I could get down to, and then fixes the issue - when trying to change the code it was *always* using index `1`, which wasn't correct if the AST had the entire class body for what needed to be processed.
[1]: …
> Fix incorrect autocorrect for Style/AccessModifierDeclarations

- changelog/fix_style_it_block_parameter_cop_error_on_always_20250711053844.md
- lib/rubocop/cop/style/it_block_parameter.rb
- spec/rubocop/cop/style/it_block_parameter_spec.rb
For `->(_) {}`:
```shell
Failures:
1) RuboCop::Cop::Style::ItBlockParameter >= Ruby 3.4 EnforcedStyle: always does not register an offense for block with parameter and missing body
Failure/Error:
node.body.each_descendant(:lvar).select do |descendant|
descendant.source == block_argument_name
end
NoMethodError:
undefined method 'each_descendant' for nil
```
> Fix `Style/ItBlockParameter` cop error on `Always` style and missing block body

- changelog/fix_naming_method_name_cop_false_positives_with_define_method_and_operator_20250708164441.md
- lib/rubocop/cop/naming/method_name.rb
- spec/rubocop/cop/naming/method_name_spec.rb
Resolves https://github.com/rubocop/rubocop/issues/14350
> [Fix #14350] Fix `Naming/MethodName` cop false positives with `define_method` and operator name

- changelog/change_add_tsort_to_runtime_dependency.md
- rubocop.gemspec
This PR fixes the following build error in the Ruby 3.5 build matrix:
```console
$ bundle exec rake spec
(snip)
==> Failures
1) RuboCop Project requiring all of `lib` with verbose warnings enabled emits no warnings
Failure/Error: expect(warnings).to eq []
expected: []
got: ["/home/runner/work/rubocop/rubocop/lib/rubocop/cop/style/parallel_assignment.rb:3:
warning: tsort wa...om the standard library, but will no longer be part of
the default gems starting from Ruby 3.6.0\n"]
```
https://github.com/rubocop/rubocop/actions/runs/16236943172/job/45848342320
Please see for more details:
- https://bugs.ruby-lang.org/issues/21442
- https://github.com/ruby/ruby/pull/13841
> Add `tsort` to runtime dependency

- changelog/fix_update_lint_require_range_parentheses_to_not_20250714114905.md
- lib/rubocop/cop/lint/require_range_parentheses.rb
- spec/rubocop/cop/lint/require_range_parentheses_spec.rb
Update `Lint/RequireRangeParentheses` to not register a false positive when the begin element spans multiple lines. If the operator is on the same line as the end element, there is no ambiguity.
Fixes #14362.
> [Fix #14362] Update `Lint/RequireRangeParentheses` to not register false positives when range elements span multiple lines

- config/default.yml
- lib/rubocop/cop/internal_affairs/useless_restrict_on_send.rb
- lib/rubocop/cop/lint/rescue_type.rb
- lib/rubocop/cop/style/block_delimiters.rb
- lib/rubocop/cop/style/conditional_assignment.rb
- lib/rubocop/cop/style/dig_chain.rb
- lib/rubocop/cop/style/inverse_methods.rb
- lib/rubocop/cop/style/redundant_freeze.rb
- lib/rubocop/cop/style/redundant_line_continuation.rb
- lib/rubocop/cop/style/stabby_lambda_parentheses.rb
Updates cop descriptions (in class comments and default.yml) to use `checks` instead of `check` for consistency (eg. 173 uses of "checks" vs 18 of "check" in default.yml).
> Use consistent verb form of "checks" in cop descriptions

- changelog/change_expand_the_scope_of_it_assignment_to_consider_all_20250715094540.md
- config/default.yml
- lib/rubocop/cop/style/it_assignment.rb
- spec/rubocop/cop/style/it_assignment_spec.rb
Expands `Style/ItAssignment` to register offenses for all local variable assignment and method parameters named `it`. 
Fixes #14322.
> [Fix #14322] Expand the scope of `Style/ItAssignment` to consider all local variable and method parameter names

- changelog/fix_comment_duplication_bug_in_20250717062746.md
- lib/rubocop/cop/style/accessor_grouping.rb
- spec/rubocop/cop/style/accessor_grouping_spec.rb
As stated in the title, this addresses the following issue:
- Fix https://github.com/rubocop/rubocop/issues/14370
The logic to prevent comments from being removed during autocorrect was introduced in the following change, so the bug likely dates back to that point:
- https://github.com/rubocop/rubocop/pull/11063
When a method call does not have parentheses, its trailing comment appears to be associated with the last argument rather than the method call itself. As a result, it is possible for the end of the comment associated with `send_node.last_argument` to appear later in the source than the end of `send_node` itself.
> [Fix #14370] Fix comment duplication bug in `Style/AccessorGrouping` separated autocorrect

- changelog/fix_update_style_sole_nested_conditional_to_properly_20250716113042.md
- lib/rubocop/cop/style/sole_nested_conditional.rb
- spec/rubocop/cop/style/sole_nested_conditional_spec.rb
When `Style/SoleNestedConditional` autocorrects `if`s containing `and` nodes, and those `and` nodes contain assignments, ensure that the assignments are parenthesized so that operator precedence is maintained.
Fixes #14309.
> [Fix #14309] Update `Style/SoleNestedConditional` to properly correct assignments within `and`

- changelog/fix_an_error_for_style_parallel_assignment_cop.md
- lib/rubocop/cop/style/parallel_assignment.rb
- spec/rubocop/cop/style/parallel_assignment_spec.rb
This PR fixes the following error for `Style/ParallelAssignment` when a lambda with parallel assignment is used on the RHS.
```console
$ echo 'a, b = x, -> { a, b = x, y}' | \
RUBOCOP_TARGET_RUBY_VERSION=3.0 bundle exec rubocop --stdin example.rb --only Style/ParallelAssignment -a -d
(snip)
An error occurred while Style/ParallelAssignment cop was inspecting
/Users/koic/src/github.com/rubocop/rubocop/example.rb:1:15.
```
> Fix an error for `Style/ParallelAssignment`

- changelog/new_enhance_naming_method_name_cop_to_detect_offenses_within_data_members_20250719195315.md
- lib/rubocop/cop/naming/method_name.rb
- spec/rubocop/cop/naming/method_name_spec.rb
This is a follow-up to https://github.com/rubocop/rubocop/pull/14325.
> Enhance `Naming/MethodName` cop to detect offenses within `Data` members

- changelog/fix_false_negative_for_lint_useless_assignment.md
- lib/rubocop/cop/variable_force.rb
- spec/rubocop/cop/lint/useless_assignment_spec.rb
Fixes https://github.com/rubocop/rubocop-jp/issues/15. (This link is Japanese issue)
This PR fixes a false positive for `Lint/UselessAssignment` when the assignment is inside a loop body.
> Fix a false positive for Lint/UselessAssignment

- changelog/change_support_any_member_in_style_array_intersect.md
- lib/rubocop/cop/style/array_intersect.rb
- spec/rubocop/cop/style/array_intersect_spec.rb
Registers code like:
```ruby
array1.any? { |elem| array2.member?(elem) }
array2.none? { |elem| array2.member?(elem) }
```
as an offense under `Style/ArrayIntersect`, and autocorrects to:
```ruby
array1.intersect?(array2)
!array1.intersect?(array2)
```
> Offend `Array#any?` and `Array#none?` blocks in `Style/ArrayIntersect`

- lib/rubocop/cop/style/array_intersect.rb
Small follow-up to https://github.com/rubocop/rubocop/pull/14381, in which I added an unordered list, but with [broken formatting](https://docs.rubocop.org/rubocop/cops_style.html#stylearrayintersect):
Adding an empty line before and after the list fixes the formatting:
> Fix doc formatting for `Style/ArrayIntersect`

- changelog/fix_args_forwarding_tripple_dot_self.md
- lib/rubocop/cop/style/arguments_forwarding.rb
- spec/rubocop/cop/style/arguments_forwarding_spec.rb
There is a bit of logic to handle preceeding argument nodes that are not being forwarded. But the list is not exhaustive
and is missing for example `self` and `const`.
Instead, rely on the already matched arg nodes to use for autocorrect. `all_anonymous` needs a bit of special handling, because send classification does not contain the first node that is part of forwarding.
> [Fix #14390] Better handling of `Style/ArgumentsForwarding` for prefix arguments

- lib/rubocop/cop/style/parallel_assignment.rb
- rubocop.gemspec
It's used by just this single cop. The comment about it being stdlib is no longer true.
Note: `tsort` uses Tarjan's algorithm. I chose Kahn since the implementation is simpler. This is not performance-sensitive and inputs tend to be small, so the more complex implementation is not worth it.
I implemented this via the pseudo-code found on wikipedia https://en.wikipedia.org/wiki/Topological_sorting#Kahn's_algorithm
> Remove dependency on `tsort`

- changelog/fix_false_positives_for_lint_useless_assignment_rescue_retry.md
- lib/rubocop/cop/variable_force.rb
- spec/rubocop/cop/lint/useless_assignment_spec.rb
Fix #14394
When handling `rescue` there is this comment:
> Treat begin..rescue..end with retry as a loop.
So, we must do the same here. Updated the comment while I was there as well.
> [Fix #14394] Fix false positives for `Lint/UselessAssignment` with `retry` in `rescue` branch

- changelog/change_add_support_for_or_nodes_to_lint_literal_as_condition.md
- lib/rubocop/cop/lint/literal_as_condition.rb
- spec/rubocop/cop/lint/literal_as_condition_spec.rb
Just the basic support for now, although I think i might need to match what was done in #13966? @Earlopain, any thoughts?
> Add support for or nodes to `Lint/LiteralAsCondition`

- changelog/change_redundant_parentheses_false_negative_for_method_call_with_block.md
- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
Currently, `Style/RedundantParentheses` won't register code like:
```ruby
(foo.select { _1 }).one?
```
as an offense. Method calls **without** blocks are registered as offenses under this cop.
This patch registers redundant parentheses around method calls **with** blocks.
Here's the [real-world-rails](https://github.com/eliotsykes/real-world-rails) report:
<details>
<summary>Report</summary>
```ruby
it_behaves_like 'on successful import', 'following', 'merge', 'imports.txt', (%w(user@example.com user@test.com).map { |acct| { 'acct' => acct } })
it_behaves_like 'on successful import', 'following', 'overwrite', 'imports.txt', (%w(user@example.com user@test.com).map { |acct| { 'acct' => acct } })
it_behaves_like 'on successful import', 'blocking', 'merge', 'imports.txt', (%w(user@example.com …
```
> Register offense for parentheses around method calls with blocks in `Style/RedundantParentheses`

- changelog/fix_false_positives_for_lint_useless_assignment.md
- lib/rubocop/cop/variable_force.rb
- spec/rubocop/cop/lint/useless_assignment_spec.rb
This PR fixes false positives for `Lint/UselessAssignment` when duplicate assignments appear in `if` branch inside a loop and the variable is used outside `while` loop.
Fixes #14402.
> [Fix #14402] Fix false positives for `Lint/UselessAssignment`

- changelog/fix_false_negatives_for_layout_empty_lines_around_class_body.md
- lib/rubocop/cop/layout/empty_lines_around_class_body.rb
- spec/rubocop/cop/layout/empty_lines_around_class_body_spec.rb
This PR fixes false negatives for `Layout/EmptyLinesAroundClassBody` when a class body starts with a blank line and defines a multiline superclass.
Fixes #14411.
> [Fix #14411] Fix false negatives for `Layout/EmptyLinesAroundClassBody`

- changelog/fix_false_positives_for_style_map_to_set.md
- lib/rubocop/cop/style/map_to_set.rb
- spec/rubocop/cop/style/map_to_set_spec.rb
This PR fixes false positives for `Style/MapToSet` when using `to_set` with block argument. This is an issue similar to #14417.
> Fix false positives for `Style/MapToSet`

- changelog/fix_false_positives_for_style_safe_navigation.md
- lib/rubocop/cop/style/safe_navigation.rb
- spec/rubocop/cop/style/safe_navigation_spec.rb
This PR fixes false positives for `Style/SafeNavigation` when ternary expression with operator method call with method chain.
Fixes #14420.
> [Fix #14420] Fix false positives for `Style/SafeNavigation`

- changelog/fix_false_positive_empty_lines_argument.md
- lib/rubocop/cop/layout/empty_lines_around_arguments.rb
- spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb
Fix #14413
The previous implementation was doing a bunch of work to decide if a line was supposed to be considered or not.
For example, Module.new with method definitions may contain newlines that should be ignored.
This new implementation only considers the ranges between arguments. The old implementation seemed to have issues with array-style method calls. To be honest, I did not try to understand the original implementation.
This implementation works by checking each argument (and also the closing bracket), looking to the left of it for whitespace and checking if that range goes over multiple lines.
> [Fix #14413] Fix a false positive for `Layout/EmptyLinesAroundArguments` with multiline strings that contain only whitespace

- spec/rubocop/result_cache_spec.rb
It's not safe to assume that it is always nil when the test starts since other tests could already have accessed it.
I believe it's also not testing much, except that this method is indeed using a instance variable, so I opted to remove the test.
Writing something that really tests this seems very difficult.
Followup to https://github.com/rubocop/rubocop/pull/14414
> Fix flaky spec for `rubocop_extra_features`

- changelog/fix_fix_safe_navigation_cop_to_preserve_safe_20250805124624.md
- lib/rubocop/cop/style/safe_navigation.rb
- spec/rubocop/cop/style/safe_navigation_spec.rb
Fixes issue where safe navigation is lost when it exists in the check. For example, "check if the variable is not nil and the method call `foo` on that object doesn't return nil, if so, call `bar` on the result, else nil":
```ruby
variable&.foo ? variable.foo.bar : nil # bad
```
This fixes the autocorrect from the incorrect behavior that omits the original safe navigation, to the correct behavior that preserves the existing safe navigation.
```ruby
variable.foo&.bar # incorrect
variable&.foo&.bar # fixed
```
Fixes:
```diff
- foo&.bar && foo.bar.baz
+ foo&.bar&.baz
- if foo&.bar; foo.bar.baz; end
+ foo&.bar&.baz
- foo&.bar ? foo.bar.baz : nil
+ foo&.bar&.baz
```
This relates to a comment I placed in #14420. Fixing the issue with this PR rather than opening a new issue. …
> Fix Style/SafeNavigation cop to preserve existing safe navigation in check

- changelog/fix_false_negatives_regexp_cops.md
- lib/rubocop/cop/lint/duplicate_regexp_character_class_element.rb
- lib/rubocop/cop/style/symbol_array.rb
- lib/rubocop/target_finder.rb
- spec/rubocop/cli/autocorrect_spec.rb
Fix #14435
It does `expressions = expressions.to_a`, which does not create a copy. So other cops that run after would not see all
the expressions.
`.dup` would solve this, but all this does is work around a bug in `regexp_parser` < 2.7.0. RuboCop now requires >= 2.9.3 so all that code can simply be removed.
I didn't add a new test because the code that would be tested is gone now.
Also see https://github.com/rubocop/rubocop/pull/13875 for something quite similar.
> [Fix #14435] Fix false negatives for regexp cops when `Lint/DuplicateRegexpCharacterClassElement` is enabled

- docs/modules/ROOT/pages/usage/caching.adoc
Recently, I needed to invalidate the RuboCop cache based on the contents of an external config file, and thankfully RuboCop already has an `Rubocop::Cop::Base#external_dependency_checksum` method.
However, it took me some effort to find it. In this request, I added a mention of the method to the RuboCop documentation website.
WDYT?
> Mention RuboCop::Cop::Base#external_dependency_checksum in docs

- lib/rubocop/lsp/routes.rb
- spec/rubocop/lsp/server_spec.rb
Follow-up to https://github.com/rubocop/rubocop/pull/14431#issuecomment-3184481229
This PR fixes an unexpect diagnostic with `TextDocumentSyncKind.Incremental` on the LSP when `contentChanges` contains multiple entries.
Since #14431 changed `TextDocumentSyncKind` from `Full` to `Incremental`, it is necessary to handle the possibility that `params[:contentChanges]` may contain multiple entries.
Ref: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_synchronization
> Fix an unexpected diagnostic with `TextDocumentSyncKind.Incremental` on the LSP

- lib/rubocop/cop/lint/missing_cop_enable_directive.rb
- spec/rubocop/cop/lint/missing_cop_enable_directive_spec.rb
Changes offense range for `Lint/MissingCopEnableDirective` from start of line to whole comment. I think this is useful for IDEs because there's better offense visibility, and because the offense is naturally related to the directive comment.
Before (screenshot from VS Code):
After:
> Change offense range for Lint/MissingCopEnableDirective to whole comment

- changelog/fix_fix_14441_better_hash_access_handling_in_20250815010135.md
- lib/rubocop/cop/style/safe_navigation.rb
- spec/rubocop/cop/style/safe_navigation_spec.rb
- Fixes #14441
- Make the `matching_call_nodes?` method account for differences in arguments.
- Code like `foo[:bar] && foo[:baz].blank?` does not need safe navigation because the hash keys are different.
> [Fix #14441] Better hash access handling in `Style/SafeNavigation`

- changelog/change_update_style_redundant_begin_to_register_begin_20250818135329.md
- lib/rubocop/cop/style/redundant_begin.rb
- spec/rubocop/cop/style/redundant_begin_spec.rb
A `begin` block (without `rescue` or `ensure`) inside `if`, `case`, `while` or `until` is redundant, and can be handled by the cop.
Fixes #14453.
> [Fix #14453] Update `Style/RedundantBegin` to register `begin` blocks inside `if`, `unless`, `case`, `while` and `until` as redundant

- changelog/change_style_array_intersect_array_size_false_negatives.md
- lib/rubocop/cop/style/array_intersect.rb
- spec/rubocop/cop/style/array_intersect_spec.rb
Registers the following code as offenses under `Style/ArrayIntersect`:
```ruby
(a & b).size > 0
(a & b).size != 0
(a & b).size.positive?
(a & b).size == 0
(a & b).size.zero?
```
and autocorrects to:
```ruby
a.intersect?(b)
!a.intersect?(b)
```
In addition to `#size`, the patch takes into account `#length` and `#count` methods as well.
[real-world-rails](https://github.com/eliotsykes/real-world-rails) report:
<details>
<summary>Report</summary>
```ruby
(reply.ticket.label_ids & user.label_ids).size > 0
ticket.user == user || (ticket.label_ids & user.label_ids).size > 0
ticket.user == user || (ticket.label_ids & user.label_ids).size > 0 ||
(reply.ticket.label_ids & user.label_ids).size > 0
assert dave == ticket.user || (ticket.label_ids & dave.label_ids).size > 0
if (@new_sub_context_codes …
```
> Register array intersection size checks as offenses under `Style/ArrayIntersect`

- changelog/fix_an_incorrect_autocorrect_for_style_bitwise_predicate.md
- lib/rubocop/cop/style/bitwise_predicate.rb
- spec/rubocop/cop/style/bitwise_predicate_spec.rb
This PR fixes an incorrect autocorrect for `Style/BitwisePredicate` when using `&` with LHS flags in conjunction with `==` for comparisons.
Fixes #14469.
> [Fix #14469] Fix an incorrect autocorrect for `Style/BitwisePredicate`

- changelog/change_make_redundant_begin_aware_of_case_match.md
- lib/rubocop/cop/style/redundant_begin.rb
- spec/rubocop/cop/style/redundant_begin_spec.rb
Follow-up to https://github.com/rubocop/rubocop/pull/14463.
This PR makes `Style/RedundantBegin` aware of `case` pattern matching.
> Make `Style/RedundantBegin` aware of `case` pattern matching

- changelog/fix_false_negative_for_style_redundant_begin.md
- lib/rubocop/cop/style/redundant_begin.rb
- spec/rubocop/cop/style/redundant_begin_spec.rb
This PR fixes a false negative for `Style/RedundantBegin` using `begin` with multiple statements without `rescue` or `ensure`.
> Fix a false negative for `Style/RedundantBegin`

- changelog/change_false_negative_for_layout_end_alignment.md
- lib/rubocop/cop/correctors/alignment_corrector.rb
- lib/rubocop/cop/mixin/end_keyword_alignment.rb
- spec/rubocop/cli/autocorrect_spec.rb
- spec/rubocop/cop/layout/end_alignment_spec.rb
Registers offenses for code such as:
```ruby
module Foo
bar end
if test
foo
else
bar end
```
and autocorrects it to:
```ruby
module Foo
bar
end
if test
foo
else
bar
end
```
Note that such offenses have been previously ignored as false positives in https://github.com/rubocop/rubocop/commit/4bfe82e65c22bf17dfb7f524c83dd741da06bb29, which resolved https://github.com/rubocop/rubocop/issues/7778. It mentions introduction of `Layout/BlockEndNewline`, but that cop doesn't handle these kind of offenses, and doesn't seem like the right place for them.
> Fix false negative for `Layout/EndAlignment` when `end` is not on a separate line

- changelog/fix_lsp_prism_reuse.md
- lib/rubocop/runner.rb
- spec/ruby_lsp/rubocop/addon_spec.rb
Fix #14475
After autocorrect happened, it still reused it the parse result from the initial file, causing all kind of trouble.
cc @vinistock
> [Fix #14475] Fix cop errors during autocorrect for the buildin LSP when analyzing as Ruby 3.4

- lib/rubocop/runner.rb
It's a private method, but `rubocop-md` monkeypatches it and doesn't handle keywords.
There is a PR for this https://github.com/rubocop/rubocop-md/pull/45 but maybe this also makes sense for the time being.
> Don't use keyword argument for `get_processed_source`

- changelog/fix_dont_invalidate_cache_for_display_time_option.md
- lib/rubocop/result_cache.rb
Currently, running RuboCop with `--display-time` option will invalidate cache. This PR disables the option from affecting cache.
> Prevent --display-time CLI option from invalidating cache

- changelog/fix_lsp_addon_config_changes.md
- changelog/fix_lsp_addon_todo_changes.md
- lib/ruby_lsp/rubocop/addon.rb
- lib/ruby_lsp/rubocop/runtime_adapter.rb
- spec/ruby_lsp/rubocop/addon_spec.rb
I did not actually verify https://github.com/rubocop/rubocop/pull/14506 by making changes to a todo.
Since the adapter is given over to ruby-lsp, simply overwriting the instance variable doesn't do anything.
I've adapted tests to check for the presence of the reload log message, and added one that actually goes through and checks config changes in detail.
> Fix the built-in Ruby LSP add-on not restarting when config files change

- lib/ruby_lsp/rubocop/runtime_adapter.rb
This is meant to be used with sorbet, which we don't do. See this code snippet: https://github.com/Shopify/ruby-lsp/blob/83e7cb0b502a9cd5a7e49a6bfb490f624ced2bd8/jekyll/add-ons.markdown#registering-formatters
> If using Sorbet to develop the add-on, then include this interface to make sure the class is properly implemented
> Remove unnecessary include in the lsp runtime adapter

- changelog/fix_lsp_addon_dot_rubocop.md
- lib/rubocop/cli.rb
- lib/rubocop/cli/command/auto_generate_config.rb
- lib/rubocop/config_store.rb
- lib/ruby_lsp/rubocop/addon.rb
- lib/ruby_lsp/rubocop/runtime_adapter.rb
- spec/ruby_lsp/rubocop/addon_spec.rb
If the user specifies `-c foo.yml`, it should be used.
This consolidates option/cli handling to `apply_options!`. That way `force_default_config` is consistenly used as well.
That now also happens when generating a todo. It seems correct for consistency, but I didn't add a test for it and am ok with dropping that change.
Apart from this, I'm only aware of one extra difference between the ruby-lsp addons but it requires a change in ruby-lsp itself: https://github.com/Shopify/ruby-lsp/issues/3736
> Fix the built-in Ruby LSP add-on not respecting `.rubocop` config file

- Gemfile
Prism 1.5.0 polyfills `warn` in an incompatible way: https://github.com/ruby/prism/pull/3647
> Fix Ruby 2.7 CI

- changelog/fix_false_positives_for_style_redundant_regexp_escape.md
- lib/rubocop/cop/style/redundant_regexp_escape.rb
- spec/rubocop/cop/style/redundant_regexp_escape_spec.rb
This PR fixes false positives for `Style/RedundantRegexpEscape` when an escaped variable sigil follows `#` (e.g., `/#\@foo/`, `/#\@@bar/`, `/#\$baz/`).
These escapes are required to prevent interpolation (`#@ivar`, `#@@cvar`, `#$gvar`) and should not be removed.
> Fix false positives for `Style/RedundantRegexpEscape`

- changelog/change_support_for_position_encoding_utf_8_and_utf_32_20250830135957.md
- lib/rubocop/lsp/diagnostic.rb
- lib/rubocop/lsp/routes.rb
- lib/rubocop/lsp/runtime.rb
- lib/rubocop/lsp/server.rb
- spec/rubocop/lsp/server_spec.rb
Add support for positionEncoding 'utf-8' and 'utf-32'
> Add support for LSP `positionEncoding` `utf-8` and `utf-32`

- changelog/fix_false_negative_for_numblock_and_it_block_parameters.md
- lib/rubocop/cop/message_annotator.rb
- lib/rubocop/cop/style/it_block_parameter.rb
- lib/rubocop/cop/style/numbered_parameters.rb
- spec/rubocop/cop/style/it_block_parameter_spec.rb
- spec/rubocop/cop/style/numbered_parameters_spec.rb
This PR fixes false negatives for `Style/NumberedParameters` and `ItBlockParameter` when using multiline method chain with `EnforcedStyle: allow_single_line`.
`EnforcedStyle: allow_single_line` allows single-line usage, and numbered block parameters across multiple lines should be detected. This was an implementation bug, and the `same_line?` method should have been used instead of the `single_line?` or `multiline?` methods.
> Fix false negatives for `Style/NumberedParameters` and `ItBlockParameter`

- changelog/fix_fix_style_redundant_format_when_the_format_string_20250917121517.md
- lib/rubocop/cop/style/redundant_format.rb
- lib/rubocop/cop/utils/format_string.rb
- spec/rubocop/cop/style/redundant_format_spec.rb
- spec/rubocop/cop/utils/format_string_spec.rb
Updates `Style/RedundantFormat` to properly handle `*` as a width specifier when the width argument is not literal. Also updated to be able to handle `*` with a variable specifier (ie. `%1$*2$s` uses the 2nd argument as the width).
Fixes #14528.
> [Fix #14528] Fix `Style/RedundantFormat` when the format string has a variable width that isn't given as a literal value

- changelog/fix_incorrect_autocorrect_for_style_unless_else.md
- lib/rubocop/cop/style/unless_else.rb
- spec/rubocop/cop/style/unless_else_spec.rb
This PR fixes an incorrect autocorrect for `Style/UnlessElse` when using `unless` with `then`.
Fixes #14540.
> [Fix #14540] Fix an incorrect autocorrect for `Style/UnlessElse`

- changelog/fix_false_positives_for_style_redundant_parentheses.md
- lib/rubocop/cop/style/redundant_parentheses.rb
- spec/rubocop/cop/style/redundant_parentheses_spec.rb
This PR fixes false positives for `Style/RedundantParentheses` when parentheses are used around a one-line `rescue` expression as a condition.
Fixes #14557.
> [Fix #14557] Fix false positives for `Style/RedundantParentheses`

- lib/rubocop/cop/internal_affairs/on_send_without_on_csend.rb
- spec/rubocop/cop/internal_affairs/on_send_without_on_csend_spec.rb
Code is faulty but may happen when just typing.
> Fix an error for `InternalAffairsOnSendWithoutOnCSend` with `alias_method` and no arguments

- changelog/fix_an_incorrect_autocorrect_for_lint_deprecated_open_ssl_constant.md
- lib/rubocop/cop/lint/deprecated_open_ssl_constant.rb
- spec/rubocop/cop/lint/deprecated_open_ssl_constant_spec.rb
This PR fixes an incorrect autocorrect for `Lint/DeprecatedOpenSSLConstant` when using twice `Cipher` constant.
Fixes #14563.
> [Fix #14563] Fix an incorrect autocorrect for `Lint/DeprecatedOpenSSLConstant`

- changelog/change_enhance_constant_overwritten_in_rescue_to_detect_fully_qualified_constant_name_20250926173826.md
- lib/rubocop/cop/lint/constant_overwritten_in_rescue.rb
- spec/rubocop/cop/lint/constant_overwritten_in_rescue_spec.rb
Prior to theses changes, this would not be detected:
```ruby
begin
rescue => ::MyException
end
```
> Enhance `Lint::ConstantOverwrittenInRescue` to detect offenses within fully qualified constants

- changelog/change_make_style_lambda_call_autocorrection_contextual.md
- config/default.yml
`obj.(arg)` should not be autocorrected when it is an unfinished write of `obj.do_something(arg)`. Autocorrecting while editing into `obj.call(arg)` may cause confusion.
> Make `Style/LambdaCall` autocorrection contextual

- changelog/fix_false_positive_for_style_redundant_interpolation.md
- lib/rubocop/cop/style/redundant_interpolation.rb
- spec/rubocop/cop/style/redundant_interpolation_spec.rb
This PR fixes the following false positive for `Style/RedundantInterpolation` when using a one-line `=>` pattern matching:
```console
$ echo '"#{42 => var}"' | RUBOCOP_TARGET_RUBY_VERSION=3.0 bundle exec rubocop --stdin example.rb -A --only Style/RedundantInterpolation
C
Offenses:
example.rb:1:1: C: [Corrected] Style/RedundantInterpolation: Prefer to_s over string interpolation.
"#{42 => var}"
^^^^^^^^^^^^^^
(42 => var).to_s
```
This detection results in the following syntax error:
```console
$ ruby -cve '(42 => var).to_s'
ruby 3.4.5 (2025-07-16 revision 20cda200d3) +PRISM [arm64-darwin24]
ruby: -e:1: syntax error found (SyntaxError)
> 1 | (42 => var).to_s
|  ^~~~~~~~~ unexpected void value …
```
> Fix false positives for `Style/RedundantInterpolation`

- changelog/change_enhance_constant_overwritten_in_rescue_to_detect_nested_constant_20251002014136.md
- lib/rubocop/cop/lint/constant_overwritten_in_rescue.rb
- spec/rubocop/cop/lint/constant_overwritten_in_rescue_spec.rb
Follow-up to https://github.com/rubocop/rubocop/pull/14566
> Enhance `Lint/ConstantOverwrittenInRescue` to detect offenses within nested constants

- lib/rubocop/cop/style/one_line_conditional.rb
- spec/rubocop/cli_spec.rb
- spec/rubocop/cop/style/one_line_conditional_spec.rb
The offense message is now adjusted based on whether the cop autocorrects to a ternary operator or a multi-line conditional.
Fixes #14582.
> [Fix #14582] Tweak the offense message in `Style/OneLineConditional`

- changelog/fix_an_error_for_lint_self_assignment.md
- lib/rubocop/cop/lint/self_assignment.rb
- spec/rubocop/cop/lint/self_assignment_spec.rb
This PR fixes an error for `Lint/SelfAssignment` when using `[]=` assignment with no arguments.
Fixes #14587.
> [Fix #14587] Fix an error for `Lint/SelfAssignment`
