- config/disabled.yml
https://github.com/bbatsov/ruby-style-guide/pull/401
> fix link to style guide

- CHANGELOG.md
- lib/rubocop/cop/style/self_assignment.rb
- spec/rubocop/cop/style/self_assignment_spec.rb
> Add autocorrect for Style/SelfAssignment cop

- CHANGELOG.md
- lib/rubocop/cop/style/redundant_exception.rb
- lib/rubocop/cop/util.rb
- spec/rubocop/cop/style/redundant_exception_spec.rb
- spec/rubocop/cop/util_spec.rb
I made some mistakes with git that messed up my last pull request but this new one should be working.
> Add autocorrect to RedundantException

- CHANGELOG.md
- lib/rubocop/cop/lint/block_alignment.rb
- spec/rubocop/cop/lint/block_alignment_spec.rb
This is a minimalistic attempt to solve #1573. @jonas054, it would be great if you could provide some code failing examples in case this patch doesn't fulfill the criteria well enough.
> Fix auto-correct for BlockAlignment

- lib/rubocop/cop/style/first_parameter_indentation.rb
- spec/rubocop/cop/style/first_parameter_indentation_spec.rb
Add some more tricky cases to the specs, and fix code.
> [Fix #1622] Handle line breaks better in FirstParameterIndentation

- spec/rubocop/cop/style/space_around_operators_spec.rb
I saw #1665 and remembered that I had copy/pasted those exact specs recently.
cc @rrosenblum @bbatsov
> Fix more tests that do the wrong thing for SpaceAroundOperators

- lib/rubocop/cop/performance/detect.rb
> Improve perfomance/detect code

- config/default.yml
- lib/rubocop/cop/performance/detect.rb
- spec/rubocop/cop/performance/detect_spec.rb
Fix [this](https://github.com/bbatsov/rubocop/pull/1704/files#r26443115).
> Refactor config perfomance/detect code

- config/enabled.yml
I forgot to update the description in the enabled.yml when I updated this cop.
> Update description of Performance/Detect

- README.md
Make behaviors of rake integration more explicit.
> Update readme on rake task

- spec/rubocop/cop/style/documentation_spec.rb
Will rebase when #1808 lands for a green baseline.
> test `Documentation` with subclass with `#:nodoc:`

- CHANGELOG.md
- config/default.yml
Common Ruby source file for rack based applications. Outcome of #1814.
> Recognize rackup file (config.ru) out of the box

- CHANGELOG.md
- lib/rubocop/rake_task.rb
> [Fix #1849] Fix bug with nested arrays in Rake task configuration

- lib/rubocop/cop/style/case_indentation.rb
- lib/rubocop/cop/style/single_line_methods.rb
I found some duplicate code when I was fixing the parallel assignment cop. I figured I should clean it up.
> Remove duplicate code

- lib/rubocop/formatter/disabled_config_formatter.rb
This fixes the broken build caused by #1876.
> Do not put reference links in disabled_config_formatter

- .rubocop_todo.yml
- CHANGELOG.md
- lib/rubocop/cop/cop.rb
- spec/rubocop/cli_spec.rb
Fairly simplistic. Adding onto the logic that is used to display the style guide links.
> Show reference links when configured to display style guide links

- CHANGELOG.md
- lib/rubocop/cop/lint/non_local_exit_from_iterator.rb
- spec/rubocop/cop/lint/non_local_exit_from_iterator_spec.rb
> [Fix #1803] Don't warn for return from lambda

- CHANGELOG.md
- lib/rubocop/cop/style/documentation.rb
- spec/rubocop/cop/style/documentation_spec.rb
> Fix Style/Documentation false-positive offence #1905.

- CHANGELOG.md
- lib/rubocop/processed_source.rb
- spec/rubocop/cli_spec.rb
The idea is to display an error message saying what's wrong instead of showing a stack trace.
> Display an error and abort the program if input file can't be found

- CHANGELOG.md
- lib/rubocop/cop/lint/unneeded_disable.rb
- lib/rubocop/formatter/formatter_set.rb
- lib/rubocop/runner.rb
- spec/rubocop/cli_spec.rb
- spec/rubocop/cop/lint/unneeded_disable_spec.rb
I messed up when adding this cop and didn't support the `Enabled` configuration parameter.
> Fix UnneededDisable disabling

- CHANGELOG.md
- lib/rubocop/cop/performance/count.rb
- spec/rubocop/cop/performance/count_spec.rb
> Properly parse code in Performance/Count that extends enumerable

- config/enabled.yml
See https://github.com/JuanitoFatas/fast-ruby/pull/50#issue-98586885
> Style/ParallelAssignment doesn't have any performance benefits

- CHANGELOG.md
- lib/rubocop/cop/mixin/empty_lines_around_body.rb
- lib/rubocop/cop/style/symbol_proc.rb
- lib/rubocop/target_finder.rb
- spec/rubocop/cop/style/symbol_proc_spec.rb
Related to #2135, I was just too slow to submit this PR. :) Personally I'm indifferent about the auto-correct strategy. Is this what you were looking for, @bbatsov?
> Improve handling of super in SymbolProc

- lib/rubocop/config.rb
- lib/rubocop/cop/metrics/method_length.rb
- lib/rubocop/cop/mixin/annotation_comment.rb
- lib/rubocop/cop/style/trailing_blank_lines.rb
These are a few small tweaks that I came across while extracting out constants. The impact of this seems to only be about 1% overall. 
The code for extracting constants still needs work, but I figured I could put this out there. Extracting constants improves memory by about 10%.
> Performance tweaks phase 2

- CHANGELOG.md
Adding this since it was missing from https://github.com/bbatsov/rubocop/pull/2204
> Update changelog for [#2204]

- CHANGELOG.md
- lib/rubocop/config_loader.rb
- spec/rubocop/config_loader_spec.rb
- spec/support/host_environment_simulation_helper.rb
This should fix #2218 and #2215
The error was introduced here: https://github.com/bbatsov/rubocop/commit/2c32a61f5bf144a3c824c4287398b317a0f51096 and kind of here: https://github.com/sferik/rails_admin/commit/c1a495edf40124dbbb391acb4e9240f2ac15f8a9 and can be resolved by following the example of that second commit
> Fix error when safe yaml is only partially loaded

- lib/rubocop/cop/commissioner.rb
Add file and line information the callback methods so the location can be identified in the call stack.
> Add location information to callback methods

- CHANGELOG.md
- lib/rubocop/cop/performance/string_replacement.rb
- spec/rubocop/cop/performance/string_replacement_spec.rb
> String replacement regex options

- CHANGELOG.md
- lib/rubocop/cop/lint/eval.rb
- spec/rubocop/cli_spec.rb
- spec/rubocop/cop/lint/eval_spec.rb
> eval("string literal") is not a security risk

- CHANGELOG.md
- lib/rubocop/cop/mixin/statement_modifier.rb
- lib/rubocop/cop/style/dot_position.rb
- lib/rubocop/cop/style/extra_spacing.rb
- spec/rubocop/cop/style/dot_position_spec.rb
> Style/DotPosition doesn't break method calls with comment between dot and selector

- CHANGELOG.md
- lib/rubocop/cop/lint/literal_in_condition.rb
- lib/rubocop/cop/style/each_with_object.rb
- lib/rubocop/cop/util.rb
- spec/rubocop/cop/style/each_with_object_spec.rb
Otherwise we would change the meaning of the code!
> [Fix #2321] Don't replace reduce with each_with_object if accumulator var is assigned to

- CHANGELOG.md
- config/default.yml
- lib/rubocop.rb
- lib/rubocop/ast_node.rb
- lib/rubocop/cop/mixin/configurable_enforced_style.rb
- lib/rubocop/cop/style/align_hash.rb
- lib/rubocop/cop/style/command_literal.rb
- lib/rubocop/cop/style/empty_line_between_defs.rb
- lib/rubocop/cop/style/method_def_parentheses.rb
- lib/rubocop/cop/style/regexp_literal.rb
- spec/rubocop/cop/style/method_def_parentheses_spec.rb
> Add new style for Style/MethodDefParentheses

- lib/rubocop/cop/mixin/autocorrect_unless_changing_ast.rb
- lib/rubocop/cop/style/and_or.rb
- spec/rubocop/cop/style/and_or_spec.rb
This fixes both #1844 and #2375.
However, I have 3 other PRs which need to be reviewed before this one. The first one is #2366.
> Work on `Style/AndOr`

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/style/predicate_name.rb
- spec/rubocop/cop/style/predicate_name_spec.rb
> Add `NameWhitelist` config param for `Style/PredicateName`

- lib/rubocop/cop/lint/debugger.rb
Benchmarking shows that the NodePattern matcher is faster than the previous
implementation.
> Use NodePattern to make Lint/Debugger more concise

- .travis.yml
- Gemfile
- README.md
- Rakefile
- rubocop.gemspec
- spec/support/coverage.rb
* First commit addresses https://github.com/jujugrrr/rubocop/commit/24c04b34ad97478482040bc993916a36564adf4e.
* Second commit helps preventing things like https://github.com/jujugrrr/rubocop/commit/24c04b34ad97478482040bc993916a36564adf4e in the future.
* Third commit address https://github.com/bbatsov/rubocop/pull/2408#issuecomment-155560125
> Remove coveralls

- CHANGELOG.md
- lib/rubocop.rb
- lib/rubocop/comment_config.rb
- lib/rubocop/cop/lint/unneeded_disable.rb
- lib/rubocop/cop/lint/useless_assignment.rb
- lib/rubocop/name_similarity.rb
- spec/rubocop/cli_spec.rb
- spec/rubocop/cop/lint/unneeded_disable_spec.rb
Inspired by #2423. A little helpfulness from this cop would be welcomed, I figure.
> Add "did you mean" functionality to Lint/UnneededDisable

- spec/spec_helper.rb
I observed that the build is failing since we introduced Code Climate for coverage. I hope this will fix it.
> Allow submitting coverage results to Code Climate

- CHANGELOG.md
- lib/rubocop/cop/lint/nested_method_definition.rb
- lib/rubocop/cop/style/and_or.rb
- spec/rubocop/cop/lint/nested_method_definition_spec.rb
- spec/rubocop/cop/style/and_or_spec.rb
> Fix bug in Style/AndOr

- CHANGELOG.md
- lib/rubocop/cop/lint/useless_access_modifier.rb
- lib/rubocop/cop/style/align_parameters.rb
- lib/rubocop/cop/style/space_inside_hash_literal_braces.rb
- lib/rubocop/cop/style/trailing_blank_lines.rb
- spec/rubocop/cop/lint/useless_access_modifier_spec.rb
- spec/rubocop/cop/style/align_parameters_spec.rb
- spec/rubocop/cop/style/space_inside_hash_literal_braces_spec.rb
I wanted to batch a couple more fixes up, but there's no time to do more today. Review please!
> Fixes of the day

- lib/rubocop/result_cache.rb
A couple of comments were slightly wrong.
> Update comments for ResultCache

- spec/rubocop/cli/cli_options_spec.rb
The problem described by the comment was fixed
in https://github.com/bbatsov/rubocop/pull/2555/files#diff-136dc9359b5a71d3b9242666420aefc5L1441 .
> Remove an outdated comment

- lib/rubocop.rb
- lib/rubocop/cop/mixin/array_hash_indentation.rb
- lib/rubocop/cop/style/indent_array.rb
- lib/rubocop/cop/style/indent_hash.rb
Introduce `ArrayHashIndentation` to be used by `Style/IndentArray` and
`Style/IndentHash`. This should bring these up from the CodeClimate's
F-class.
> Reduce duplication in indentation cops

- CHANGELOG.md
- README.md
- lib/rubocop/config_loader.rb
- spec/rubocop/config_loader_spec.rb
- Applying fix recommended by @mikegee in https://github.com/bbatsov/rubocop/pull/2306#discussion_r43534112 
- Updating readme as requested by @baschtl in https://github.com/bbatsov/rubocop/pull/2306#issuecomment-169312041
> Fix remote config file to only load http and https urls and update readme

- CHANGELOG.md
- lib/rubocop/cop/style/file_name.rb
- lib/rubocop/node_pattern.rb
- spec/rubocop/cop/style/file_name_spec.rb
- spec/rubocop/node_pattern_spec.rb
Starting a new batched PR with enhancements to `NodePattern`.
> Nothingness visits Japan in the winter

- lib/rubocop/formatter/simple_text_formatter.rb
The local variable `summary` was being changed 5 times during the method. By extracting the building of the report summary to a helper class, it is much clearer what is going on.
It should also be much simpler to implement the frozen string literals (see #2585).
cc @rrosenblum
> SimpleTextFormatter#report_summary extract class

- lib/rubocop/ast_node.rb
- lib/rubocop/cli.rb
- lib/rubocop/cop/lint/unused_block_argument.rb
- lib/rubocop/cop/lint/unused_method_argument.rb
- lib/rubocop/cop/performance/redundant_block_call.rb
- lib/rubocop/cop/performance/redundant_merge.rb
- lib/rubocop/cop/style/next.rb
- lib/rubocop/cop/style/parallel_assignment.rb
- lib/rubocop/cop/style/rescue_modifier.rb
- lib/rubocop/formatter/disabled_lines_formatter.rb
- lib/rubocop/formatter/emacs_style_formatter.rb
- lib/rubocop/formatter/simple_text_formatter.rb
- lib/rubocop/formatter/text_util.rb
- lib/rubocop/node_pattern.rb
This is meant to be merged in after #2542. Once it is merged, this change set will drop to 2 commits.
> Fix frozen string literals

- lib/rubocop/cop/style/extra_spacing.rb
Implement `#autocorrect` as we usually do, rather than overriding `Cop#correct`.
I didn't quite get why it was done differently in this cop. @alexdowad perhaps you can explain.
> [Refactor] Do autocorrect in ExtraSpacing in a more standard way

- lib/rubocop/cop/performance/casecmp.rb
The code to implement this zero check was updated in #2617, but the comment wasn't updated.
> Update Casecmp comment to reflect zero retval check.

- CHANGELOG.md
- assets/output.html.erb
- spec/fixtures/html_formatter/expected.html
This is a new version of #2657, including a changelog update.
> Floating headers in HTML output

- CHANGELOG.md
- config/enabled.yml
- lib/rubocop.rb
- lib/rubocop/cop/lint/format_parameter_mismatch.rb
- lib/rubocop/cop/style/block_comments.rb
- lib/rubocop/cop/style/method_def_parentheses.rb
- lib/rubocop/cop/style/send.rb
- lib/rubocop/cop/style/special_global_vars.rb
- lib/rubocop/cop/style/trailing_blank_lines.rb
- lib/rubocop/cop/style/trivial_accessors.rb
- lib/rubocop/cop/style/zero_length_predicate.rb
- spec/rubocop/cop/metrics/block_nesting_spec.rb
- spec/rubocop/cop/style/zero_length_predicate_spec.rb
This is my first go at implementing a cop, so please be gentle. :grimacing: 
I had a few things that I was unsure about while going about it, so I'll go over them here:
Some cops seem to be named after their offense, e.g. `Style/TrailingBlankLines`, while others seem named after the "better" practice, e.g. `Style/SymbolProc`.
In the end I settled on `Style/ZeroLengthPredicate`, as I couldn't come up with a name including `Empty` that didn't sound very generic.
I wasn't quite sure how many tests to add, so I ended up adding tests for most positive case permutations. Should I also include the negative cases? In this cop, the `0` is hard coded, so I excluded such cases for now.
Thankful for any feedback.
:kissing_heart:
> Add new Style/ZeroLengthPredicate cop

- lib/rubocop/ast_node.rb
- lib/rubocop/cop/lint/duplicated_key.rb
- spec/rubocop/ast_node_spec.rb
- spec/rubocop/cop/lint/duplicated_key_spec.rb
Also beefs up Style/DuplicatedKey in the process. I'm sure this can be used to simplify Style/LiteralInCondition too, but it wasn't immediately obvious to me how.
> Add recursive literal checking

- lib/rubocop/ast_node.rb
- lib/rubocop/config.rb
- lib/rubocop/cop/style/method_call_parentheses.rb
- lib/rubocop/cop/style/nested_parenthesized_calls.rb
- lib/rubocop/token.rb
- spec/rubocop/config_loader_spec.rb
- spec/rubocop/cop/style/nested_parenthesized_calls_spec.rb
> Gasoline welcomes the spring

- lib/rubocop/cop/commissioner.rb
More performance work. Bit by bit, RC is getting faster and faster...
> A wave loudly clashing

- CHANGELOG.md
- lib/rubocop/cop/mixin/space_after_punctuation.rb
- lib/rubocop/cop/mixin/space_before_punctuation.rb
- lib/rubocop/cop/style/else_alignment.rb
- lib/rubocop/cop/style/indentation_width.rb
- spec/rubocop/cop/style/else_alignment_spec.rb
- spec/rubocop/cop/style/indentation_width_spec.rb
> [Fixes #2228] Use the config of a related cop whether it's enabled or not

- CHANGELOG.md
- config/enabled.yml
- lib/rubocop/cop/performance/casecmp.rb
- spec/rubocop/cop/performance/casecmp_spec.rb
This should be merged after, or instead of, #2692.
> Casecmp order

- rubocop.gemspec
367K -> 214K
and safer since nobody can forget to ignore things
> only ship selected files to reduce gem size

- lib/rubocop/cop/commissioner.rb
This is worth a ~20% speedup on a large private code base I work on,
presumably because many Commissioners never actually encounter all
possible node types.
> Lazily populate the Commissioner's callback cache.

- lib/rubocop/cop/style/empty_line_between_defs.rb
`Astrolabe::Node#sibling_index` scans the list of all siblings looking
for the target node, making it O(n) in the number of `def`s in a given
scope. This makes EmptyLineBetweenDefs quadratic in the size of a single
scope.
Instead, intercept `begin` nodes and walk the children explicitly,
keeping track of the previous node without having to do an O(n) scan to
find it.
> Optimize EmptyLineBetweenDefs

- CHANGELOG.md
- lib/rubocop/cop/style/conditional_assignment.rb
- spec/rubocop/cop/style/conditional_assignment_spec.rb
> [Fix #2719] ConditionalAssignment handles end alignment

- lib/rubocop/cop/metrics/parameter_lists.rb
> Fix a typo

- CHANGELOG.md
- lib/rubocop/cop/lint/literal_in_interpolation.rb
- spec/rubocop/cop/lint/literal_in_interpolation_spec.rb
I wouldn't recommend to use auto-correction but at least it works better now. :)
> Fix and improve LiteralInInterpolation auto-corrections

- CHANGELOG.md
- config/enabled.yml
- lib/rubocop/ast_node.rb
- lib/rubocop/cop/mixin/surrounding_space.rb
- lib/rubocop/cop/performance/casecmp.rb
- lib/rubocop/cop/performance/redundant_merge.rb
- lib/rubocop/cop/style/align_hash.rb
- lib/rubocop/cop/style/rescue_modifier.rb
- lib/rubocop/result_cache.rb
- spec/rubocop/ast_node_spec.rb
- spec/rubocop/cop/performance/redundant_merge_spec.rb
- spec/rubocop/cop/style/rescue_modifier_spec.rb
Another batched PR. Tweaks, fixes, tweaks, fixes.
> The deepest locksmithing

- CHANGELOG.md
- lib/rubocop/config_loader.rb
- spec/rubocop/config_loader_spec.rb
> Change requre: in config to be relative to the .rubocop.yml file itself

- CHANGELOG.md
- lib/rubocop/cop/rails/date.rb
- spec/rubocop/cop/rails/date_spec.rb
> Fix false positive in Rails/Date when to_time is chained with safe method

- lib/rubocop/cop/team.rb
no hard feels if you deny this pull request. just performing my morning code snoop.
love,
-me.
> tiny polish for DEFAULT_OPTIONS

- CHANGELOG.md
- lib/rubocop/cop/lint/nested_method_definition.rb
- spec/rubocop/cop/lint/nested_method_definition_spec.rb
> [Fix #2898] Allow method definitions inside Class.new(SuperClass)

- lib/rubocop/cop/performance/count.rb
Seems like the inline docs for this cop diverged - this updates the comments to match behavior.
> Update doc comments in Count cop to match behavior

- lib/rubocop/cop/performance/fixed_size.rb
- lib/rubocop/cop/performance/reverse_each.rb
I have been sitting on these for a little while. I was planning on converting more cops to use `NodePattern`, but haven't found the time lately. I figured that I can always make another PR, and I might as well put out there what I currently have.
> Use node pattern

- relnotes/v0.38.0.md
So that syntax highlighting doesn't get all messed up.
> Escape backtick in relnotes' markdown

- lib/rubocop/cop/mixin/statement_modifier.rb
- lib/rubocop/cop/style/case_indentation.rb
- lib/rubocop/cop/style/file_name.rb
- lib/rubocop/cop/style/special_global_vars.rb
> Reduce Metrics/AbcSize Max to 27.5

- README.md
Trying to explain something that people ask us about every now and then.
> [Fix #2425] Clarify in README how overriding config parameters works

- CHANGELOG.md
- lib/rubocop/cop/performance/redundant_merge.rb
- spec/rubocop/cop/performance/redundant_merge_spec.rb
> [Fix #3006] Handle non-local variable as receiver in RedundantMerge

- CHANGELOG.md
- lib/rubocop/cop/style/space_after_colon.rb
- spec/rubocop/cop/style/space_after_colon_spec.rb
> [Fix #2993] Check for space after optional keyword args colon

- CHANGELOG.md
- lib/rubocop/cop/performance/redundant_merge.rb
- spec/rubocop/cop/performance/redundant_merge_spec.rb
@lumeet, thanks for fixing #3006. I had a slightly different idea about the fix for this. I was thinking that we could register an offense for, and fix, this condition. Let me know what you think about this tweak.
> Handle element selector receivers in RedundantMerge

- CHANGELOG.md
- lib/rubocop/result_cache.rb
> Custom cop changes now bust the cache

- CHANGELOG.md
- lib/rubocop/cop/performance/end_with.rb
- lib/rubocop/cop/performance/start_with.rb
- spec/rubocop/cop/performance/end_with_spec.rb
- spec/rubocop/cop/performance/start_with_spec.rb
> [Fix #3039] Accept match without receiver in StartWith and EndWith

- lib/rubocop/path_util.rb
----
This method was extracted from `#match_path?` in PR #1732, but
the caller is simplified not to call it in PR #3030.
> Remove unused method: #hidden?

- lib/rubocop/cop/style/stabby_lambda_parentheses.rb
> Fix doc typo for stabby lambda parentheses

- .github/PULL_REQUEST_TEMPLATE.md
Ensure the PR template links render correctly when previewing the PR.
> Tweak PR template to correctly render links when opening a PR

- lib/rubocop/cop/style/empty_case_condition.rb
A couple minor tweaks that were discussed in #3087.
> Minor tweaks to EmptyCaseCondition

- CHANGELOG.md
https://github.com/bbatsov/rubocop/pull/3118
https://github.com/bbatsov/rubocop/issues/3116
replaced 3166 to 3116
> Fix typo of issue number.

- CHANGELOG.md
- lib/rubocop/ast_node.rb
- lib/rubocop/cop/style/space_after_not.rb
- spec/rubocop/cop/style/space_after_not_spec.rb
> Fix Style/SpaceAfterNot reporting on the not keyword

- lib/rubocop/cop/style/documentation.rb
- lib/rubocop/cop/style/multiline_method_call_indentation.rb
- spec/rubocop/cop/style/documentation_spec.rb
- spec/rubocop/cop/style/multiline_method_call_indentation_spec.rb
> Fixing up Style/MultilineMethodCallIndentation

- CHANGELOG.md
- lib/rubocop/ast_node.rb
- lib/rubocop/cop/mixin/if_node.rb
- lib/rubocop/cop/performance/redundant_merge.rb
- lib/rubocop/cop/style/infinite_loop.rb
- lib/rubocop/cop/style/nested_modifier.rb
- lib/rubocop/cop/style/parallel_assignment.rb
- spec/rubocop/cop/style/infinite_loop_spec.rb
Don't try to convert these to `Kernel#loop`.
> Accept modifier forms of while/until in InfiniteLoop

- CHANGELOG.md
- lib/rubocop/ast_node/traversal.rb
- spec/rubocop/cli/cli_options_spec.rb
- spec/rubocop/cop/rails/time_zone_spec.rb
> Return can take many arguments

- CHANGELOG.md
- Rakefile
- lib/rubocop/config_loader.rb
- spec/rubocop/config_loader_spec.rb
Fixes #3138. Catching the bug in a test is a bit cumbersome but I think it works.
> [Fix #3138] Fix encoding mismatch issue

- lib/rubocop/cop/style/unless_else.rb
- spec/rubocop/cop/style/unless_else_spec.rb
Wrote these specs while debugging #3263. These specs already pass and do not fix the issue in any way. I felt these specs should be included, hence the PR. Feel free to close if you think it does not make much of a difference.
> Add specs for nested conditionals in Style/UnlessElse cop

- config/enabled.yml
More links to the Ruby on Rails StyleGuide added for cops where an example was obvious.
> Add StyleGuide links for more Rails cops

- config/enabled.yml
This adds the styleguide link for the Style/NumericPredicate cop
> Add styleguide link for Style/NumericPredicate cop

- lib/rubocop/cop/style/parallel_assignment.rb
Just noticed while running the tests that there was some debugging output
> Remove debugging output

- CHANGELOG.md
> Fix a link definition position in CHANGELOG

- lib/rubocop/cached_data.rb
- lib/rubocop/config_loader.rb
- lib/rubocop/cop/team.rb
- lib/rubocop/formatter/html_formatter.rb
- lib/rubocop/processed_source.rb
- lib/rubocop/result_cache.rb
- spec/rubocop/formatter/html_formatter_spec.rb
- spec/rubocop/processed_source_spec.rb
- spec/rubocop/result_cache_spec.rb
- spec/support/file_helper.rb
These are several encoding refactorings I came up with while working on #3311. Supersedes #3546.
> Encoding refactorings

- .travis.yml
- CHANGELOG.md
- Rakefile
- lib/rubocop/cop/util.rb
- spec/rubocop/cop/style/string_literals_spec.rb
- spec/rubocop/cop/style/symbol_array_spec.rb
- spec/rubocop/cop/style/variable_number_spec.rb
This was a nasty one but I think I fixed it.
I added a couple of regression tests because I thought my fix would regress but it actually didn't. Let me know if you think it's worth keeping those.
> [Fix #3311] Detect encoding incompatibilities to spare bad autocorrection

- lib/rubocop/result_cache.rb
> Fixes a random test failure

- CHANGELOG.md
- lib/rubocop/cop/rails/save_bang.rb
- spec/rubocop/cop/rails/save_bang_spec.rb
> [Fix #3390] Fix SaveBang cop for multiple conditional

- lib/rubocop/cop/cop.rb
- lib/rubocop/cop/mixin/trailing_comma.rb
- lib/rubocop/cop/performance/sample.rb
- lib/rubocop/cop/style/line_end_concatenation.rb
- spec/rubocop/cli/cli_options_spec.rb
- spec/rubocop/cop/style/safe_navigation_spec.rb
This is a small compilation of tweaks that I have come across while going through the code recently. Nothing necessarily warrants a PR by itself, but as a whole, it seemed worth while.
> Various tweaks

- CHANGELOG.md
- lib/rubocop/cop/performance/case_when_splat.rb
> Fix changelog

- lib/rubocop/cop/style/extra_spacing.rb
Solution
-------
`aligned_tok?` method is very slow.
So, it doesn't call the method if the method is unnecessary.
Benchmark
------
In RuboCop directory
```sh
$ bundle exec rake 'bench_cop[Style/ExtraSpacing, ., 4]'
Benchmarking Style/ExtraSpacing on . (using default config)
(4 iterations, 811 files)
Finished parsing source, testing inspection...
29.650000   0.020000  29.670000 ( 29.672696)
$ bundle exec rake 'bench_cop[Style/ExtraSpacing, ., 4]'
Benchmarking Style/ExtraSpacing on . (using default config)
(4 iterations, 811 files)
Finished parsing source, testing inspection...
2.050000   0.020000   2.070000 (  2.070606)
```
```sh
$ time rubocop --cache false
814 files inspected, no offenses detected
real    0m43.040s
user    0m42.967s
sys     0m0.070s
$ time rubocop --cache false
814 files …
```
> Improve the performance of `Style/ExtraSpacing` cop

- manual/cops_style.md
run `bundle exec rake generate_cops_documentation`
> Add forgotten update the manual

- lib/rubocop/config_loader.rb
- lib/rubocop/cop/cop.rb
- lib/rubocop/cop/lint/useless_setter_call.rb
- lib/rubocop/cop/metrics/line_length.rb
- lib/rubocop/cop/style/and_or.rb
- lib/rubocop/cop/style/block_comments.rb
- lib/rubocop/cop/style/hash_syntax.rb
- lib/rubocop/cop/style/parallel_assignment.rb
- lib/rubocop/cop/util.rb
- lib/rubocop/cop/variable_force/assignment.rb
- lib/rubocop/cop/variable_force/locatable.rb
- lib/rubocop/cop/variable_force/reference.rb
- lib/rubocop/formatter/fuubar_style_formatter.rb
- lib/rubocop/node_pattern.rb
- lib/rubocop/processed_source.rb
I was very much surprised to see tons of Ruby warnings when I run rubocop with `RUBYOPT="-w"`.
So here's a fix for all of them that I see.
> Ruby warnings ⚠️

- lib/rubocop/cop/lint/each_with_object_argument.rb
- lib/rubocop/cop/lint/eval.rb
- lib/rubocop/cop/lint/useless_comparison.rb
- lib/rubocop/cop/rails/output.rb
- lib/rubocop/cop/rails/read_write_attribute.rb
- lib/rubocop/cop/rails/request_referer.rb
- lib/rubocop/cop/rails/scope_args.rb
- spec/rubocop/cop/lint/each_with_object_argument_spec.rb
- spec/rubocop/cop/lint/eval_spec.rb
- spec/rubocop/cop/rails/scope_args_spec.rb
More converting cops to use node pattern. I am working on going through the Style cops as well. I figured that I would reduce the size of the pull request and break these changes apart from the style changes.
> Convert more cops to use node pattern

- CHANGELOG.md
- lib/rubocop/cop/style/special_global_vars.rb
- spec/rubocop/cli/cli_options_spec.rb
- spec/rubocop/cop/style/special_global_vars_spec.rb
Hi guys.
I've saw issue #1747 and I've thought I could provide a little PR with updated message text. 
I am not sure if it's a good solution so any comments are welcome.
Thanks.
> [Fix 1747] Update Style/SpecialGlobalVars messages with require 'English' reminder

- CHANGELOG.md
- lib/rubocop/cop/mixin/access_modifier_node.rb
- lib/rubocop/cop/style/access_modifier_indentation.rb
- lib/rubocop/cop/style/array_join.rb
- lib/rubocop/cop/style/case_equality.rb
- lib/rubocop/cop/style/class_check.rb
- lib/rubocop/cop/style/colon_method_call.rb
- lib/rubocop/cop/style/each_with_object.rb
- lib/rubocop/cop/style/empty_literal.rb
- lib/rubocop/cop/style/even_odd.rb
- lib/rubocop/cop/style/lambda.rb
- lib/rubocop/cop/style/module_function.rb
- lib/rubocop/cop/style/nil_comparison.rb
- lib/rubocop/cop/style/non_nil_check.rb
- lib/rubocop/cop/style/op_method.rb
- lib/rubocop/cop/style/proc.rb
- lib/rubocop/cop/style/redundant_freeze.rb
- lib/rubocop/cop/style/send.rb
- lib/rubocop/cop/style/symbol_proc.rb
- spec/rubocop/cop/style/access_modifier_indentation_spec.rb
- spec/rubocop/cop/style/colon_method_call_spec.rb
- spec/rubocop/cop/style/empty_literal_spec.rb
I think this should finish up the conversion of most of the easy/obvious cops to use node pattern.
> More conversions to use node pattern

- .editorconfig
More info [here](http://editorconfig.org/).
> `.editorconfig` file added

- CHANGELOG.md
> Fix a pull request number in CHANGELOG

- .travis.yml
Ruby 2.2.6 and 2.3.3 have been released.
https://www.ruby-lang.org/en/downloads/
> Update Ruby versions in Travis CI

- lib/rubocop/cop/bundler/ordered_gems.rb
- spec/rubocop/cop/bundler/ordered_gems_spec.rb
Fixed #3776 
And I added some tests.
The Auto-Correction hasn't released yet. So, I didn't add an entry to changelog. 
> [Fix #3776] Fix AutoCorrect for `Bundler/OrderedGems` cop with inline comment

- manual/automated_code_review.md
- mkdocs.yml
Codacy provides an out-of-the-box solution for automated code review that uses RuboCop
> Add Codacy integration info

- config/default.yml
Bringing the default.yml to a common view
> Bringing the default.yml to a common view

- config/default.yml
- lib/rubocop/cop/style/file_name.rb
- spec/rubocop/cop/style/file_name_spec.rb
Related: https://github.com/bbatsov/rubocop/issues/3793
WDYT?
---
> Support Style/FileName: ExpectMatchingDefinition acronym

- CHANGELOG.md
- config/enabled.yml
- lib/rubocop.rb
- lib/rubocop/config_loader.rb
- lib/rubocop/cop/security/yaml_load.rb
- manual/cops.md
- manual/cops_rails.md
- manual/cops_security.md
- manual/cops_style.md
- spec/rubocop/cli/cli_options_spec.rb
- spec/rubocop/cop/security/yaml_load_spec.rb
Add ``Security/YAMLLoad``cop, covering the security issues around the use of ``YAML.load``: https://ruby-doc.org/stdlib-2.3.3/libdoc/yaml/rdoc/YAML.html#module-YAML-label-Security
> Add Security/YAMLLoad

- lib/rubocop/cop/bundler/duplicated_gem.rb
- lib/rubocop/cop/lint/block_alignment.rb
- lib/rubocop/cop/metrics/line_length.rb
- lib/rubocop/cop/performance/detect.rb
- lib/rubocop/cop/performance/flat_map.rb
ref: https://github.com/bbatsov/rubocop/pull/3822#discussion_r93826280
> Rename to `register_offense` for adding offenses method

- LICENSE.txt
- README.md
I think followings is not related to this pul-req so I skip followings.
Happy New Year!
> Bump license years for 2017

- lib/rubocop.rb
- lib/rubocop/cop/commissioner.rb
- lib/rubocop/cop/lint/safe_navigation_chain.rb
- lib/rubocop/cop/mixin/target_ruby_version.rb
- lib/rubocop/cop/performance/regexp_match.rb
- lib/rubocop/cop/rails/safe_navigation.rb
- lib/rubocop/cop/style/safe_navigation.rb
See. https://github.com/bbatsov/rubocop/pull/3824#discussion_r93827394
> Refactor target ruby version

- spec/rubocop/cop/cop_spec.rb
- spec/rubocop/path_util_spec.rb
- spec/rubocop/remote_config_spec.rb
- spec/rubocop/result_cache_spec.rb
Part #2 (see #3857). So far I have applied `RSpec/MultipleDescribe`, `RSpec/InstanceVariable`, and `RSpec/NamedSubject`. I'm done for now! The remaining cops that would be easy to resolve are `RSpec/AnyInstance`, `RSpec/LeadingSubject`, `RSpec/SubjectStub`, and `RSpec/VerifiedDoubles` but those aren't fun enough to do in my free time 😆 
> Refactor specs by applying rubocop-rspec

- README.md
backers and sponsors from Open Collective will automatically appear on your readme. for example: https://github.com/cyclejs/cyclejs#backers
Ad badges on top as well  
more info: https://github.com/OpenCollective/OpenCollective/wiki/Github-banner
> Ad Backers and Sponsors from Open Collective

- CHANGELOG.md
- lib/rubocop/cop/style/format_string.rb
- spec/rubocop/cop/style/format_string_spec.rb
Fixes #3839. See the issue for more context
> [Fix #3839] Detect hash literal for String#%

- lib/rubocop/cop/style/format_string.rb
Figured I would give this a go after doing #3872. Good candidate for node pattern refactoring.
> Refactor FormatString to use node pattern

- spec/project_spec.rb
Intended to help avoid issues like @pocke fixed in #3725 
> Add specs for enabled.yml and disabled.yml

- lib/rubocop/config.rb
- spec/rubocop/config_spec.rb
This change improves obsolete warnings in three ways.
Currently, RuboCop displays first obsolete warning only.
```yaml
Style/SingleSpaceBeforeFirstArg:
Enabled: false
Style/SpaceBeforeModifierKeyword:
Enabled: false
```
```
Error: The `Style/SingleSpaceBeforeFirstArg` cop has been renamed to `Style/SpaceBeforeFirstArg.
(obsolete configuration found in /tmp/tmp.9T2ers7SW8/.rubocop.yml, please update it)
```
This change makes to display all obsolete warnings.
```
Error: The `Style/SingleSpaceBeforeFirstArg` cop has been renamed to `Style/SpaceBeforeFirstArg.`
(obsolete configuration found in /tmp/tmp.9T2ers7SW8/.rubocop.yml, please update it)
The `Style/SpaceBeforeModifierKeyword` cop has been removed. Please use `Style/SpaceAroundKeyword` instead.
(obsolete configuration found in …
```
> Warn about obsolete cops and parameters

- config/default.yml
- config/enabled.yml
Numerous `config/default.yml` and `config/enabled.yml` organization improvements:
- Re-alphabetize many different cop configs
- Add a few more backtick escapes to some keywords and classes
- Improve a recently added `Description`
- Added a `Security` "header" and fixed up all the other headers to be uniform length
I considered squashing a few of the commits together but it's much easier to review and ensure that nothing was messed up with the reorganizing if you go commit by commit. I'm willing to squash down to four commits (based on the listed changes above) after PR is approved, or feel free to merge as is.
As there were no "functional" changes I elected not to add a line to `CHANGELOG` but as there are a fair number of lines being changed I could totally see the need for one if …
> Numerous config/* organization improvements

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/lint/safe_navigation_chain.rb
- manual/cops_lint.md
- spec/rubocop/cop/lint/safe_navigation_chain_spec.rb
See. https://github.com/bbatsov/rubocop/issues/3915
> Make configurable `Lint/SafeNavigationChain` whitelist

- .travis.yml
Taken from hanami/helpers@13f30e2
I'll close this PR if the build fails.
> Fix jruby on travis

- lib/rubocop/cop/style/ternary_parentheses.rb
- manual/cops_style.md
> Fix documentation of Style/TernaryParentheses

- lib/rubocop/cop/style/word_array.rb
- spec/rubocop/cop/style/word_array_spec.rb
@bbatsov, another bug fix for you, kind sir. Sorry it's a year late.
> [Fix #2740] Bandage on the wound of WordArray autoconfig ridiculousness

- README.md
I tried clicking on these today and they went nowhere. They need the
`open-collective` prefix to match the current headings.
> Fix sponsor/backer badge links in README

- .github/PULL_REQUEST_TEMPLATE.md
In github's PULL_REQUEST_TEMPLATE
tbaggery's article is a dead link (the whole domain is down) but it's still available here:
http://web.archive.org/web/20170127215021/http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
* Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* Added tests.
* Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed …
> Uses Thoughbot's commit message guidelines

- manual/integration_with_other_tools.md
> Add VS Code extension details

- lib/rubocop/cop/style/trailing_underscore_variable.rb
- manual/cops_style.md
> Add an example for `Style/TrailingUnderscoreVariable` cop into the documentation

- manual/extensions.md
Mentioning rubocop-thread_safety in the docs may have helped @tdeo in #4072.
> Mention rubocop-thread_safety as a known extension

- lib/rubocop/config.rb
I adjusted dot position to others.
> Fix dot position

- .travis.yml
Fix #3877 
In my environment, this problem is fixed by Ruby 2.4.1 🚀
> [Fix #3877] Update Ruby version to 2.4.1 in Travis CI

- spec/rubocop/remote_config_spec.rb
No new changes introduced. Just extends the test coverage for RemoteConfig.
@bbatsov
> Extend coverage of RemoteConfig

- CHANGELOG.md
- config/enabled.yml
- manual/cops_style.md
> [Fix #4219] Add a link to style guide for `Style/IndentationConsistency`

- CHANGELOG.md
- lib/rubocop/cop/rails/blank.rb
- lib/rubocop/cop/rails/present.rb
- spec/rubocop/cop/rails/blank_spec.rb
- spec/rubocop/cop/rails/present_spec.rb
> [Fix #4241] Safeguard against a nil receiver in Rails/Blank and Rails/Present

- lib/rubocop/cop/commissioner.rb
This is an idiom to get the correct stack trace.
> Use correct lineno against class_eval

- .rubocop.yml
- Rakefile
- appveyor.yml
- lib/rubocop/cop/lint/script_permission.rb
- spec/rubocop/cop/lint/script_permission_spec.rb
I had the chance to run RuboCop's tests on a Windows machine today. They all passed! Should we start testing RuboCop on Windows?
> Appveyor config file to start testing on Windows

- README.md
Just adding the Appveyor batch to the README (and checking if the github hooks are working).
> Add Windows build status

- lib/rubocop/cop/style/yoda_condition.rb
Build is failing because of a RuboCop offense that was introduced in #4174. This fixes that. 🙂 
> Fix failing build in `master`

- CHANGELOG.md
- lib/rubocop/cop/style/next.rb
- spec/rubocop/cop/style/next_spec.rb
> [Fix #4392] Fix auto-correct of Style/Next with a misaligned end

- CHANGELOG.md
- lib/rubocop.rb
- lib/rubocop/formatter/formatter_set.rb
- lib/rubocop/formatter/tap_formatter.rb
- lib/rubocop/options.rb
- manual/formatters.md
- spec/rubocop/formatter/tap_formatter_spec.rb
- spec/rubocop/options_spec.rb
Add new TAP formatter, it implements the [Test Anything Protocol](https://testanything.org).
> Add new TAP formatter

- .github/PULL_REQUEST_TEMPLATE.md
I guess it is more kind to first time contributor.
> Add description of rake commands that to PULL_REQUEST_TEMPLATE

- CHANGELOG.md
- lib/rubocop/cop/lint/script_permission.rb
- spec/rubocop/cop/lint/script_permission_spec.rb
In addition to adding auto-correct, I also modified the test suite to use real files rather than stubs.
> Add auto-correct to ScriptPermission

- lib/rubocop/cop/style/symbol_proc.rb
Remove a TODO by updating the node matcher.
> Update the node matcher for SymbolProc

- lib/rubocop/cop/style/string_literals_in_interpolation.rb
- manual/cops_style.md
This PR extends documentation for `Style/StringLiteralsInInterpolation cop`
> [FIX #4482] Extend documentation for Style/StringLiteralsInInterpolation cop

- CHANGELOG.md
- lib/rubocop/result_cache.rb
- spec/rubocop/result_cache_spec.rb
> [Fix #4469] Include permissions in file cache

- CHANGELOG.md
- lib/rubocop/cli.rb
... so that third party tools (like guard-rubocop) can run RuboCop within the same Ruby process instead of forking a new process.
> Mark RuboCop::CLI#run as a public API

- manual/cops_naming.md
Ref #4575 
Maybe, a check does not work for the documentation on Travis CI 😕.
> Add documentation for Naming cops

- lib/rubocop/cop/layout/else_alignment.rb
- manual/cops_layout.md
Fix Layout/ElseAlignment example code.
> Fix Layout/ElseAlignment example code

- CHANGELOG.md
- lib/rubocop/cop/lint/assignment_in_condition.rb
- spec/rubocop/cop/lint/assignment_in_condition_spec.rb
This makes it clear what the two possible states and solutions are.
> [Fix #4470] Improve the error message for Lint/AssignmentInCondition

- CHANGELOG.md
- config/enabled.yml
- relnotes/v0.43.0.md
`sort_by` insted of `sort`. I think it's a typo.
> fix typo Performance/SortWithBlock description

- manual/development.md
Follow up for "Other Information" of bbatsov/rubocop#4728.
This PR updates a little old manual/development.md part.
> Update manual/development.md [ci skip]

- CHANGELOG.md
- lib/rubocop/cop/lint/return_in_void_context.rb
- spec/rubocop/cop/lint/return_in_void_context_spec.rb
Fixes https://github.com/bbatsov/rubocop/issues/4736
> Fix ReturnInVoidContext cop when return is not inside a method.

- lib/rubocop/cop/lint/unneeded_require_statement.rb
Thank you for the merge of #4764. It was an errors because #4815 was not applied 💦 
This PR fixes following errors.
https://travis-ci.org/bbatsov/rubocop/jobs/282114496#L576-L610
> Fix a broken test

- lib/rubocop/cop/style/stderr_puts.rb
Follow up for https://github.com/bbatsov/rubocop/pull/4813#discussion_r142038277.
This PR refactored to the more intentional code @Drenmi suggested.
> Make small refactoring to `Style/StderrPuts` cop

- lib/rubocop/cop/layout/space_inside_parens.rb
- manual/cops_layout.md
> Add an example for Layout/SpaceInsideParens into the documentation

- CHANGELOG.md
- manual/development.md
I basically added a step by step to understand a bit of node pattern and also add autocorrect feature.
Any ideas or improvements are welcome.
* n/a Added tests.
* n/a The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* n/a Updated cop documentation with `rake generate_cops_documentation` (required only when you've added a new cop or changed the configuration/documentation of an existing cop).
> [Fix #2040] Document how to write a custom cop

- lib/rubocop/cop/style/unless_else.rb
- manual/cops_style.md
This PR adds documentation for `Style/UnlessElse` 
> [Fix #4910] Add documentation for Style/UnlessElse

- lib/rubocop/cop/style/semicolon.rb
- lib/rubocop/cop/style/when_then.rb
- manual/cops_style.md
I hope this matches the format you're looking for.
Thanks for all the work you do on rubocop!
Related to Issue #4910
> Added examples for the WhenThen and Semicolon Style Cops

- lib/rubocop/cop/rails/action_filter.rb
- manual/cops_rails.md
Add documentation for Rails/ActionFilter (#4910)
after_filter :do_stuff
append_around_filter :do_stuff
skip_after_filter :do_stuff
after_action :do_stuff
append_around_action :do_stuff
skip_after_action :do_stuff
> Add documentation for Rails/ActionFilter

- lib/rubocop/cop/style/flip_flop.rb
- manual/cops_style.md
Add documentation for Style/FlipFlop cop. (#4910)
``` ruby
(1..20).each do |x|
puts x if (x == 5) .. (x == 10)
end
(1..20).each do |x|
puts x if (x >= 5) && (x <= 10)
end
```
> Add documentation for Style/FlipFlop

- lib/rubocop/cop/style/proc.rb
- manual/cops_style.md
Adds an example to the Style::Proc cop.
Related to Issue #4910
> [#4910] Add example for Style/Proc

- lib/rubocop/cop/style/attr.rb
- manual/cops_style.md
Adds an example to the Style::Attr cop.
Related to Issue #4910
> [#4910] Add example for Style/Attr

- lib/rubocop/cop/style/case_equality.rb
- manual/cops_style.md
Adds an example to the Style::CaseEquality cop.
Related to Issue #4910
> [#4910] Add example for Style/CaseEquality

- lib/rubocop/cop/style/global_vars.rb
- manual/cops_style.md
This PR adds documentation for `Style/GlobalVars`
> [Fix #4910] Add documentation for Style/GlobalVars

- lib/rubocop/cop/style/comment_annotation.rb
- manual/cops_style.md
> Add code examples to Style/CommentAnnotation into the documentation

- lib/rubocop/cop/style/array_join.rb
- manual/cops_style.md
This PR adds documentation for Style/ArrayJoin
> [Fix #4910] Add documentation for Style/ArrayJoin

- lib/rubocop/cop/style/perl_backrefs.rb
- manual/cops_style.md
> Add code example to Style/PerlBackrefs into the documentation

- lib/rubocop/cop/naming/class_and_module_camel_case.rb
- manual/cops_naming.md
Adds an example to the Naming::ClassAndModuleCamelCase cop.
Related to Issue #4910 
> Add example to Naming::ClassAndModuleCamelCase cop

- spec/rubocop/cop/style/perl_backrefs_spec.rb
> Fix spec comment for style/perl_backrefs_spec

- lib/rubocop/cop/naming/constant_name.rb
- manual/cops_naming.md
Adds example to Naming::ConstantName cop 
> Add example to Naming::ConstantName cop 

- lib/rubocop/cop/layout/space_after_semicolon.rb
- manual/cops_layout.md
> Add code example to Lyout/SpaceAfterSemicolon into documentation

- lib/rubocop/cop/style/def_with_parentheses.rb
- manual/cops_style.md
Add documentation for Style/DefWithParentheses
> [Fix #4910] Add documentation for Style/DefWithParentheses

- lib/rubocop/cop/rails/has_and_belongs_to_many.rb
- manual/cops_rails.md
Add an example for Rails/HasAndBelongsToMany into the documentation
> [Fix #4910] Add an example for Rails/HasAndBelongsToMany into the documentation

- lib/rubocop/cop/layout/space_inside_block_braces.rb
- manual/cops_layout.md
Add example to Layout::SpaceInsideBlockBraces
Related to #4910
> Add example to Layout::SpaceInsideBlockBraces

- lib/rubocop/cop/layout/empty_lines.rb
- manual/cops_layout.md
Add example to Layout::EmptyLines
Related to #4910
> Add example to Layout::EmptyLines

- lib/rubocop/cop/layout/indent_array.rb
- manual/cops_layout.md
Refactored the example in Layout::IndentArray
Related to #4910
> Refactored example in Layout::IndentArray

- lib/rubocop/cop/style/not.rb
- manual/cops_style.md
Add example to Style::Not
Related to #4910
> Add example to Style::Not

- manual/development.md
- manual/node_pattern.md
- mkdocs.yml
I'm really excited about work with node pattern and I bring this extra tutorial about how to interpret and create node patterns and learn a bit about this small compiler.
Suggestions are welcome!
* (n/a) Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* (n/a) Added tests.
* (n/a) Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* (n/a) The new code doesn't generate RuboCop offenses that are checked by `rake internal_investigation`.
* (n/a) Updated cop documentation with …
> Introduce Node Pattern tutorial

- lib/rubocop/cop/style/empty_literal.rb
- manual/cops_style.md
> [#4910] Add documentation examples to Style/EmptyLiteral

- lib/rubocop/cop/style/single_line_methods.rb
- manual/cops_style.md
Adds examples to `Style/SingleLineMethods`.
> [#4910] Add examples to Style/SingleLineMethods

- lib/rubocop/cop/layout/indent_array.rb
- manual/cops_layout.md
Adds examples to layout/IndentArray
By the way, I'm kind of new to making pull requests on other people's repos, so I'm not 100% sure that I've rebased onto master properly, and I'm also under the impression that I can squash on merge, but please correct me if I'm wrong about either of these things!
> Add examples to Layout/IndentArray

- manual/cops_rails.md
fixed https://github.com/bbatsov/rubocop/pull/5120#issuecomment-346935729
> update manual/cops_rails by rake generate_cops_documentation

- lib/rubocop/cop/rails/output.rb
- manual/cops_rails.md
Adds documentation for Rails/Output
Contributing to #4910 
> Add documentation for Rails/Output

- lib/rubocop/cop/mixin/negative_conditional.rb
- lib/rubocop/cop/style/lambda.rb
- lib/rubocop/cop/style/method_missing.rb
- lib/rubocop/cop/style/missing_else.rb
- lib/rubocop/cop/style/mixin_grouping.rb
- lib/rubocop/cop/style/multiline_if_modifier.rb
- lib/rubocop/cop/style/multiline_if_then.rb
- lib/rubocop/cop/style/negated_if.rb
- lib/rubocop/cop/style/negated_while.rb
- lib/rubocop/cop/style/nested_parenthesized_calls.rb
- lib/rubocop/cop/style/numeric_literals.rb
- lib/rubocop/cop/style/numeric_predicate.rb
Applies annotated templates for style cops L-N.
CI issue is documentation fix applied in #5124 .
> [#5069] Apply annotated templates for style cops L-N

- lib/rubocop/cop/style/documentation.rb
- lib/rubocop/cop/style/each_with_object.rb
- lib/rubocop/cop/style/empty_literal.rb
- lib/rubocop/cop/style/even_odd.rb
- lib/rubocop/cop/style/format_string.rb
- lib/rubocop/cop/style/identical_conditional_branches.rb
- lib/rubocop/cop/style/if_unless_modifier.rb
- lib/rubocop/cop/style/if_unless_modifier_of_if_unless.rb
- lib/rubocop/cop/style/implicit_runtime_error.rb
Applies annotated templates for style cops D-I.
CI issue is documentation fix applied in #5124 .
> [#5069] Apply annotated templates for style cops D-I

- manual/basic_usage.md
Generated by copying and pasting output from `bundle exec rubocop test.rb`.
```
$ cat test.rb
def badName
if something
test
end
end
```
```
$ bundle exec rubocop test.rb 
W
Offenses:
test.rb:1:1: C: Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
def badName
^
test.rb:1:5: C: Naming/MethodName: Use snake_case for method names.
def badName
^^^^^^^
test.rb:2:3: C: Style/GuardClause: Use a guard clause instead of wrapping the code inside a conditional expression.
if something
^^
test.rb:2:3: C: Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
if something
^^
test.rb:4:5: W: Lint/EndAlignment: end at 4, 4 is not aligned with if at 2, 2.
end
^^^
1 …
```
> Update RuboCop report for test.rb file

- lib/rubocop/cop/style/alias.rb
- lib/rubocop/cop/style/and_or.rb
- lib/rubocop/cop/style/attr.rb
- lib/rubocop/cop/style/auto_resource_cleanup.rb
- lib/rubocop/cop/style/bare_percent_literals.rb
- lib/rubocop/cop/style/braces_around_hash_parameters.rb
- lib/rubocop/cop/style/class_check.rb
- lib/rubocop/cop/style/class_methods.rb
- lib/rubocop/cop/style/class_vars.rb
- lib/rubocop/cop/style/collection_methods.rb
- lib/rubocop/cop/style/comment_annotation.rb
- lib/rubocop/cop/style/commented_keyword.rb
- lib/rubocop/cop/style/copyright.rb
Applies annotated templates for style cops A-C
> [#5069] Apply annotated templates for style cops A-C

- lib/rubocop/cop/metrics/abc_size.rb
- lib/rubocop/cop/metrics/class_length.rb
- lib/rubocop/cop/metrics/cyclomatic_complexity.rb
- lib/rubocop/cop/metrics/line_length.rb
- lib/rubocop/cop/metrics/module_length.rb
- lib/rubocop/cop/metrics/parameter_lists.rb
- lib/rubocop/cop/metrics/perceived_complexity.rb
- lib/rubocop/cop/mixin/method_complexity.rb
- lib/rubocop/cop/mixin/too_many_lines.rb
- lib/rubocop/cop/naming/binary_operator_parameter_name.rb
- lib/rubocop/cop/naming/file_name.rb
- lib/rubocop/cop/naming/heredoc_delimiter_case.rb
- lib/rubocop/cop/security/json_load.rb
- lib/rubocop/cop/security/marshal_load.rb
Applies annotated templates for Metrics, Naming & Security Cops. As well as affiliated mixins.
> [#5069] Apply annotated templates for Metrics, Naming & Security Cops

- lib/rubocop/cop/layout/indent_heredoc.rb
- manual/cops_layout.md
Follow https://github.com/bbatsov/rubocop/pull/5106#issuecomment-346988555
> Mention `AllowHeredoc` in `Layout/IndentHeredoc`'s documentation'

- lib/rubocop/cop/style/while_until_modifier.rb
- manual/cops_style.md
> [#4910] Add documentation examples to Style/WhileUntilModifier

- lib/rubocop/cop/style/while_until_do.rb
- manual/cops_style.md
> [#4910] Add documentation examples to Style/WhileUntilDo

- lib/rubocop/cop/layout/indent_hash.rb
- manual/cops_layout.md
Adds examples to layout/IndentHash
> Add examples to Layout/IndentHash

- lib/rubocop/cop/layout/indent_hash.rb
- manual/cops_layout.md
Follow up of #4976.
This commit is a small change of document.
Define the default of style provided by `Layout/IndentHash` cop in example name.
> Update an example to `Layout/IndentHash`

- lib/rubocop/cop/layout/class_structure.rb
- manual/cops_layout.md
Follow up of https://github.com/bbatsov/rubocop/pull/5162#discussion_r154074070.
Example name indicates supported styles. It does not indicate bad and good. They are indicated by source code comments in the example code.
> Restyle example formatting for `Layout/ClassStructure` cop

- lib/rubocop/cop/performance/casecmp.rb
- lib/rubocop/cop/performance/compare_with_block.rb
- lib/rubocop/cop/performance/count.rb
- lib/rubocop/cop/performance/detect.rb
- lib/rubocop/cop/performance/flat_map.rb
- lib/rubocop/cop/performance/hash_each_methods.rb
- lib/rubocop/cop/performance/lstrip_rstrip.rb
- lib/rubocop/cop/performance/redundant_block_call.rb
- lib/rubocop/cop/performance/redundant_merge.rb
- lib/rubocop/cop/performance/redundant_sort_by.rb
- lib/rubocop/cop/performance/regexp_match.rb
- lib/rubocop/cop/performance/string_replacement.rb
- lib/rubocop/cop/performance/uri_default_parser.rb
Applies annotated string templates to all Performance cops that need them.
> [#5069] Apply annotated templates to Performance cops

- lib/rubocop/cop/lint/unneeded_disable.rb
- manual/cops_lint.md
> [#4910] Add documentation example for Lint/UnneededDisable

- lib/rubocop/cop/style/character_literal.rb
- manual/cops_style.md
> [#4910] Add documentation example for Style/CharacterLiteral.

- lib/rubocop/cop/layout/extra_spacing.rb
- lib/rubocop/token.rb
Moves `equal_sign?(token)` predicate method into `Token` class.
> CLEANUP - Move equal_sign? predicate method into Token

- lib/rubocop/cop/rails/action_filter.rb
- manual/cops_rails.md
This commit is a change of document format for `Rails/ActionFilter` cop.
> Restyle example formatting for `Rails/ActionFilter` cop

- config/default.yml
- config/disabled.yml
I think Description, StyleGuide, Reference and Enabled should be in enabled/disabled.yml.
> default.yml is the place to write only cop's default settings

- lib/rubocop/cop/rails/date.rb
- manual/cops_rails.md
This commit is a change of document format for `Rails/Date` cop.
> Restyle example formatting for `Rails/Date` cop

- lib/rubocop/cop/mixin/surrounding_space.rb
FIX: Layout/SpaceInsideArrayLiteralBrackets is too slow.
> [Fix #5243] FIX: Layout/SpaceInsideArrayLiteralBrackets is too slow.

- lib/rubocop/cop/rails/action_filter.rb
- lib/rubocop/cop/rails/active_support_aliases.rb
- lib/rubocop/cop/rails/blank.rb
- lib/rubocop/cop/rails/date.rb
- lib/rubocop/cop/rails/dynamic_find_by.rb
- lib/rubocop/cop/rails/enum_uniqueness.rb
- lib/rubocop/cop/rails/environment_comparison.rb
- lib/rubocop/cop/rails/find_by.rb
- lib/rubocop/cop/rails/http_positional_arguments.rb
- lib/rubocop/cop/rails/lexically_scoped_action_filter.rb
- lib/rubocop/cop/rails/pluralization_grammar.rb
- lib/rubocop/cop/rails/present.rb
Applies annotated templates for Rails cops starting with the letter A through P.
> [#5069] Apply annotated templates for Rails cops A-P

- lib/rubocop/cop/layout/indent_array.rb
- manual/cops_layout.md
Follow up of #5003.
This commit is a small change of document.
Define the default of style provided by `Layout/IndentArray` cop in example name.
> Update an example to `Layout/IndentArray`

- lib/rubocop/cop/rails/read_write_attribute.rb
- lib/rubocop/cop/rails/relative_date_constant.rb
- lib/rubocop/cop/rails/request_referer.rb
- lib/rubocop/cop/rails/reversible_migration.rb
- lib/rubocop/cop/rails/safe_navigation.rb
- lib/rubocop/cop/rails/save_bang.rb
- lib/rubocop/cop/rails/skips_model_validations.rb
- lib/rubocop/cop/rails/time_zone.rb
- lib/rubocop/cop/rails/uniq_before_pluck.rb
- lib/rubocop/cop/rails/validation.rb
Applies annotated templates for Rails cops starting with the letter R through Z.
> [#5069] Apply annotated templates for Rails cops R-Z

- lib/rubocop/cop/layout/space_inside_reference_brackets.rb
ref #5373 #5363 
Rubocop::Cop::SpaceInsideReferenceBrackets call Rubocop::Cop::Util#tokens when it does not need to call.
$ bundle exec ruby -Ilib ./bin/rubocop -C false  
BEFORE
75.22s user 0.66s system 99% cpu 1:16.21 total
AFTER
68.51s user 0.59s system 99% cpu 1:09.37 total
9% improvement.
master's stackprof result is followings:
```
Mode: cpu(1000)
Samples: 27421 (0.01% miss rate)
GC: 1936 (7.06%)
1936   (7.1%)        1936   (7.1%)     (garbage collection)
3483  (12.7%)        1831   (6.7%)     RuboCop::AST::Node#each_child_node
1642   (6.0%)        1642   (6.0%)     RuboCop::Token#end_pos
2679   (9.8%)        1505   (5.5%)     Parser::Lexer#advance
1404   (5.1%) …
```
> improve speed of RuboCop::Cop::SpaceInsideReferenceBrackets

- CHANGELOG.md
Added in #5294. Probably an improperly resolved merge conflict. Either
way, no sense in having both.
> Remove duplicated links.

- README.md
- mkdocs.yml
Updates Copyright year to 2018 .
> Update Copyright year to 2018

- CHANGELOG.md
- lib/rubocop/cop/rails/delegate.rb
- spec/rubocop/cop/rails/delegate_spec.rb
> [Fix #5393] Fix `Rails/Delegate`'s false positive with a method call with arguments

- lib/rubocop/cop/rails/validation.rb
- manual/cops_rails.md
#4910 This PR adds only documentation for the `Rails/Validation` cop.
> [#4910] Add examples for `Rails/Validation` cop

- manual/extensions.md
As discussed here: https://github.com/bbatsov/rubocop/pull/5411#issuecomment-356868398
> Add extension to `Known Custom Cops`

- lib/rubocop/cop/style/class_vars.rb
- manual/cops_style.md
> [#4910] Add examples for `Style/ClassVars` cop

- lib/rubocop/cop/style/safe_navigation.rb
- manual/cops_style.md
Adds documentation for PR #5090 and #5112 as requested by @bbatsov [here](https://github.com/bbatsov/rubocop/pull/5112).
> Improve documentation for `Style/SafeNavigation` cop

- CHANGELOG.md
My mistake.  This got accidentally added in #5471 .
> Remove extra line in CHANGELOG

- lib/rubocop/cop/style/mixin_usage.rb
- manual/cops_style.md
> Improve documentation for Style/MixinUsage.

- CHANGELOG.md
- lib/rubocop/cop/layout/tab.rb
- spec/rubocop/cop/layout/tab_spec.rb
> [Fix #5429] Detect tabs other than indentation by `Layout/Tab`

- lib/rubocop/cop/layout/initial_indentation.rb
- lib/rubocop/cop/performance/fixed_size.rb
- manual/cops_layout.md
- manual/cops_performance.md
Adds examples to 2 more cops to continue to chip away at #4910 .  (Checklist on this issue can be updated. There are some cops with documentation that are not checked off.)
1. ` Layout/InitialIndentation`
1. `Performance/FixedSize`
> Add examples to Layout/InitialIndentation & Performance/FixedSize

- lib/rubocop/cop/generator.rb
- manual/development.md
- spec/rubocop/cop/generator_spec.rb
Follow up of #5376 and #5522.
The full fix is left to autocorrect after #5522 is implemented.
This PR is updating template string and document which are not modified by autocorrect.
Since the template becomes baseline of code, This PR changed it ahead of time.
> Improve new cop template

- lib/rubocop/cop/style/redundant_return.rb
- manual/cops_style.md
This PR is only document change.
It was difficult to understand because the example codes was not annotated with `# bad` and `# good`. This PR improves the document by adding annotations and some good cases.
> Improve examples for `Style/RedundantReturn` cop

- lib/rubocop/cop/style/word_array.rb
> Remove unused QUESTION_MARK_SIZE constant.

- lib/rubocop/cop/rails/file_path.rb
- manual/cops_rails.md
Ideally, users would understand why Rubocop makes recommendations.
https://github.com/bbatsov/rubocop/issues/3779#issuecomment-357816968
> Justify Rails/FilePath in its documentation

- CHANGELOG.md
- lib/rubocop/cop/lint/number_conversion.rb
- manual/cops_lint.md
- spec/rubocop/cop/lint/number_conversion_spec.rb
> Update the message for NumberConversion to include a radix

- CHANGELOG.md
- lib/rubocop/cop/naming/memoized_instance_variable_name.rb
- spec/rubocop/cop/naming/memoized_instance_variable_name_spec.rb
> [Fix #5670] Suggest valid memoized instance variable for bang method

- CHANGELOG.md
- relnotes/v0.54.0.md
L43 and L47 have the same content. So I removed one of them.
> Remove a duplicate entry in the CHANGELOG

- lib/rubocop/cop/style/mutable_constant.rb
- manual/cops_style.md
> Added a heredoc example for Style/MutableConstant

- lib/rubocop/cop/style/negated_while.rb
- manual/cops_style.md
Added section with examples to Style/NegatedWhile cop documentation.
> [Fix #4910] Add examples to Style/NegatedWhile

- lib/rubocop/node_pattern.rb
Fixes #5763.
This PR updates documentation in NodePattern according #4815.
> [Fix #5763] Replace `nil` with `nil?` in NodePattern doc

- lib/rubocop/cop/layout/end_of_line.rb
- manual/cops_layout.md
Related to issue #4910.
This commit adds an examples to `Layout/EndOfLine` cop.
> [#4910] Add examples for `Layout/EndOfLine` cop

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/style/method_call_without_args_parentheses.rb
- manual/cops_style.md
- spec/rubocop/cop/style/method_call_without_args_parentheses_spec.rb
> [Fix #4753] Add IgnoredMethods option to `Style/MethodCallWithoutArgsParentheses` cop

- lib/rubocop/cop/style/nested_ternary_operator.rb
- lib/rubocop/cop/style/one_line_conditional.rb
- manual/cops_style.md
Added examples.
Changes are small and belongs to one topic, so i decided to put them in one PR
> [#4910] Add examples to NestedTernaryOperator and OneLineConditional

- lib/rubocop/cop/style/single_line_block_params.rb
- manual/cops_style.md
Updated documentation for Style/SingleLineBlockParams
> [#4910] Add examples to Style/SingleLineBlockParams

- lib/rubocop/cop/performance/unneeded_sort.rb
- manual/cops_performance.md
Add a more thorough description and more exhaustive examples to Performance/UnneededSort.
> Improve description and examples of Performance/UnneededSort

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/style/parentheses_around_condition.rb
- manual/cops_style.md
- spec/rubocop/cop/style/parentheses_around_condition_spec.rb
> [Fix #5757] Add option to allow parentheses around multiline conditions

- CHANGELOG.md
- lib/rubocop/cop/rails/save_bang.rb
- spec/rubocop/cop/rails/save_bang_spec.rb
Fix Rails/SaveBang when using negated if:
- The `conditional?` method was only checking for if/case/or/and but wasn't checking negated if
- This fixes #5819
> [Fix #5819] Rails/SaveBang when using negated if:

- config/default.yml
- config/enabled.yml
- lib/rubocop/cop/rails/blank.rb
- lib/rubocop/cop/rails/present.rb
- manual/cops_rails.md
Also reformat text for Rails/Blank and Rails/Present to make it
more readable.
> Fix documentation for Rails/Present cop

- lib/rubocop/cop/layout/empty_line_between_defs.rb
- manual/cops_layout.md
Fix grammar and improve wording of configuration setting descriptions.
* **N/A** Added tests.
* **N/A** Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
> Corrections to Layout/EmptyLineBetweenDefs docs

- spec/rubocop/cop/lint/duplicate_methods_spec.rb
There were no tests covering class methods being defined with an explicit receiver, e.g. `def A.some_method`.
Coverage for the duplicate_methods.rb file increases from 80.41 % to 93.81 %.
> Add more tests for Lint/DuplicateMethods

- manual/extensions.md
I wasn't sure where to look, and ended up looking at this file when the content is in development.md. I had to do a GitHub search to find that out.
> Make it easier to find writing custom cops guide

- lib/rubocop/cop/variable_force.rb
* replace dispatch_node with an inline code that uses a lookup table
* change throw/catch to a simple return value check for skipping child node processing
The throw/catch change removes two stack frames for each level of recursive nesting required
when traversing the AST.  The dispatch_node change removes an additional stack frame for levels
where the children are processed by the handler code.
Together these changes should help _a little_ with the general problem described in #5341, in which
ruby underreports the amount of available stack space.
This PR should cause no user-observable behavior changes.
> Minor refactor to reduce variable_force stack use

- lib/rubocop/cop/style/unneeded_percent_q.rb
- manual/cops_style.md
> [Fix #4910] added example for `Style/UnneededPercentQ`

- lib/rubocop/cop/correctors/alignment_corrector.rb
- lib/rubocop/cop/style/bare_percent_literals.rb
- lib/rubocop/cop/style/command_literal.rb
- lib/rubocop/cop/style/next.rb
> Use the #heredoc? method

- lib/rubocop/cop/style/unneeded_percent_q.rb
- manual/cops_style.md
There were some examples, but they were not formatted as code examples. This PR gives them the proper format.
> format examples for Style/UnneededPercentQ #4910

- lib/rubocop/cop/style/numeric_literal_prefix.rb
- manual/cops_style.md
This PR adds examples for Style/NumericLiteralPrefix. Existing explanations that are now covered by the examples are removed. 
> add examples for Style/NumericLiteralPrefix

- spec/rubocop/cop/rails/assert_not_spec.rb
> Test autocorrection `Rails/AssertNot` with a failure message

- lib/rubocop/cop/style/ip_addresses.rb
- spec/rubocop/cop/style/ip_addresses_spec.rb
Don't run `Style/IpAddresses` checks if the string is empty.
> [Fix #6027] Fix Style/IpAddresses choking on an empty string.

- manual/configuration.md
Follow up to help confused people (including myself) from https://github.com/rubocop-hq/rubocop/issues/6119
* [N/A? because docs?] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [N/A? because docs?] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
> Docs: example of merging Include with default.yml

- manual/configuration.md
* [N/A] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [N/A] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](../blob/master/CONTRIBUTING.md#changelog-entry-format).
* [N/A] The PR relates to *only* one subject with a clear title
> Docs: inherit_mode

- spec/rubocop/cop/layout/indent_array_spec.rb
- spec/rubocop/cop/layout/indent_heredoc_spec.rb
- spec/rubocop/cop/layout/indentation_width_spec.rb
- spec/rubocop/cop/layout/space_after_comma_spec.rb
- spec/rubocop/cop/layout/space_inside_reference_brackets_spec.rb
- spec/rubocop/cop/lint/unneeded_splat_expansion_spec.rb
- spec/rubocop/cop/lint/useless_assignment_spec.rb
- spec/rubocop/cop/performance/string_replacement_spec.rb
- spec/rubocop/cop/rails/delegate_allow_blank_spec.rb
- spec/rubocop/cop/style/conditional_assignment_assign_in_condition_spec.rb
- spec/rubocop/cop/style/hash_syntax_spec.rb
- spec/rubocop/cop/style/percent_literal_delimiters_spec.rb
- spec/rubocop/cop/style/raise_args_spec.rb
- spec/rubocop/cop/style/string_literals_in_interpolation_spec.rb
- spec/rubocop/cop/style/string_literals_spec.rb
- spec/rubocop/cop/style/trailing_comma_in_arguments_spec.rb
- spec/rubocop/cop/style/trailing_comma_in_array_literal_spec.rb
- spec/rubocop/cop/style/trailing_comma_in_hash_literal_spec.rb
- spec/rubocop/cop/style/unneeded_percent_q_spec.rb
I think this may be the last of the easy/obvious conversions to `expect_offense`/`expect_no_offenses`.
> Convert tests to use expect_offense

- manual/automated_code_review.md
> Add CodeFactor to Automated Code Review section

- .github/ISSUE_TEMPLATE.md
> Add Bundler mention in the version instructions

- CHANGELOG.md
- lib/rubocop/cop/style/for.rb
- manual/cops_style.md
- spec/rubocop/cop/style/for_spec.rb
* Add auto-correct to `Style/For`
* Update highlighting to cover the entire statement
> Add auto-correct to Style/For

- spec/rubocop/cop/lint/useless_assignment_spec.rb
> Refactor UselessAssignment spec to use expect_offense helper

- spec/rubocop/cop/metrics/block_nesting_spec.rb
> Refactor BlockNesting spec to use expect_offense helper

- spec/rubocop/cli/cli_auto_gen_config_spec.rb
- spec/rubocop/cli_spec.rb
- spec/rubocop/config_loader_spec.rb
- spec/rubocop/cop/layout/end_of_line_spec.rb
- spec/rubocop/cop/lint/syntax_spec.rb
- spec/rubocop/cop/naming/ascii_identifiers_spec.rb
- spec/rubocop/cop/style/ascii_comments_spec.rb
- spec/rubocop/cop/style/empty_literal_spec.rb
- spec/rubocop/file_finder_spec.rb
- spec/rubocop/options_spec.rb
- spec/rubocop/path_util_spec.rb
- spec/rubocop/processed_source_spec.rb
- spec/rubocop/target_finder_spec.rb
- spec/support/file_helper.rb
These are no longer necessary since ruby 2.0 (unless CI proves me wrong).
> Remove a bunch of unnecessary encoding comments

- lib/rubocop/cop/lint/unneeded_splat_expansion.rb
- spec/rubocop/cop/lint/unneeded_splat_expansion_spec.rb
> [Fix #6151] Clarify unneeded splat expansion's message

- lib/rubocop/cop/rails/save_bang.rb
Master build is broken after the merge of #6193 – because of new cop rules on master branch since that PR was opened.
> Fix Layout/EmptyLineAfterGuardClause offenses

- .travis.yml
We don’t run tests on Travis any more, and the GitHub -> Travis integration has now been removed.
> Remove Travis configuration file

- lib/rubocop/cop/rails/reversible_migration.rb
Follow up of https://github.com/rubocop-hq/rubocop/pull/6335/files#r220771156.
> Refactor `Rails/ReversibleMigration` to check the node type

- config/default.yml
- manual/configuration.md
- manual/development.md
Follow up of #6293.
config/enabled.yml and config/disabled.yml has been merged into config/default.yml.
> Update the development manual and configuration doc

- manual/configuration.md
I hope disabling something in Rubocop disables something in Rubocop ;-)
> Fix typo in documentation

- config/default.yml
- lib/rubocop/cop/style/collection_methods.rb
- manual/cops_style.md
This PR refers to the setting to default.yml as examples target.
```yaml
PreferredMethods:
collect: 'map'
collect!: 'map!'
inject: 'reduce'
detect: 'find'
find_all: 'select'
```
https://github.com/rubocop-hq/rubocop/blob/v0.59.2/config/default.yml#L964-L975
> Add examples for `Style/CollectionMethods`

- config/default.yml
- lib/rubocop/cop/layout/closing_parenthesis_indentation.rb
- lib/rubocop/cop/layout/comment_indentation.rb
- lib/rubocop/cop/layout/dot_position.rb
- lib/rubocop/cop/layout/else_alignment.rb
- lib/rubocop/cop/layout/empty_lines.rb
- lib/rubocop/cop/layout/empty_lines_around_arguments.rb
- lib/rubocop/cop/layout/empty_lines_around_begin_body.rb
- lib/rubocop/cop/layout/empty_lines_around_block_body.rb
- lib/rubocop/cop/layout/empty_lines_around_class_body.rb
- lib/rubocop/cop/layout/empty_lines_around_exception_handling_keywords.rb
- lib/rubocop/cop/layout/empty_lines_around_method_body.rb
- lib/rubocop/cop/layout/empty_lines_around_module_body.rb
- lib/rubocop/cop/layout/indent_hash.rb
- lib/rubocop/cop/layout/indent_heredoc.rb
- lib/rubocop/cop/layout/indentation_consistency.rb
- lib/rubocop/cop/layout/indentation_width.rb
- lib/rubocop/cop/layout/initial_indentation.rb
- lib/rubocop/cop/naming/class_and_module_camel_case.rb
- lib/rubocop/cop/style/global_vars.rb
- lib/rubocop/cop/style/method_def_parentheses.rb
- lib/rubocop/cop/style/module_function.rb
- lib/rubocop/cop/style/proc.rb
- manual/cops_layout.md
- manual/cops_naming.md
- manual/cops_style.md
This PR fixes a bunch of little typos that were annoying me.  It should not make any changes to functionality, as they are all in comments, descriptions, or the manual.
> fix a bunch of little typose ;-)

- tasks/spec_runner.rake
This corrects my mistake in #6432.
> Fix spec runner to not exit when done

- config/default.yml
- manual/cops_rails.md
Follow up of #6392.
#6392 has been changed in RuboCop 0.60. (The next version of 0.59.2 is not 0.59.3.)
> Update `VersionChanged` for `Rails/SkipsModelValidations`

- config/default.yml
- manual/cops_style.md
Resolves https://github.com/rubocop-hq/rubocop/pull/6199#issuecomment-435660384
I'm not sure should I change `VersionChanged` of this cop and add something to `CHANGELOG`.
> Fix rebase of `Style/DateTime tweaks`

- manual/node_pattern.md
> Remove extraneous backtick in node_pattern.md

- CHANGELOG.md
- lib/rubocop/cop/style/empty_case_condition.rb
- spec/rubocop/cop/style/empty_case_condition_spec.rb
Fixes #6511.
This issue is a regression by #6257.
This PR fixes an incorrect auto-correct for `Style/EmptyCaseCondition` when used as an argument of a method. The following is an issue example.
```ruby
do_some_work case
when object.nil?
Object.new
else
object
end
```
The following is a reproduction step.
```console
% rubocop -V
0.60.0 (using Parser 2.5.3.0, running on ruby 2.5.3 x86_64-darwin17)
% rubocop -a example.rb --only Style/EmptyCaseCondition
if object.nil?
Object.new
else
object
end
```
The above has a bug to remove method call.
This PR will make the following corrections.
```console
% rubocop -V
0.60.0 (using Parser 2.5.3.0, running on ruby 2.5.3 x86_64-darwin17)
% rubocop -a example.rb --only Style/EmptyCaseCondition
do_some_work if object.nil? …
```
> [Fix #6511] Fix an incorrect auto-correct for `Style/EmptyCaseCondition`

- lib/rubocop/cop/performance/open_struct.rb
- manual/cops_performance.md
Follow up of #6486.
This PR displays details missing in the document.
> Tweak a documentation for `Performance/OpenStruct`

- lib/rubocop/cop/style/begin_block.rb
- manual/cops_style.md
Related to issue #4910.
This commit adds an examples to `Style/BeginBlock` cop.
> [#4910] Add examples for `Style/BeginBlock`

- lib/rubocop/cop/style/method_call_with_args_parentheses.rb
- spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
This is yet another edge case for the `omit_parentheses` style for the
`Style/MethodCallWithArgsParentheses` cop.
If you have set the `AllowParenthesesInChaining` option, calls like
`Rails.logger.error("something")` will be allowed, as they are
technically chained. 😅
At least in our style guide, we want `AllowParenthesesInChaining` only
for symmetry.  I'm not really sure if this is general enough of a rule,
but what I have done in this change is:
> Don't let parenthesized calls if none of the previous calls are
> parenthesized.
Maybe I can also rename the setting to `AllowParenthesesInChainingForSymmetry`
or add separate one for symmetry? If you decide to omit the parentheses,
it's context sensitive and generally not well-defined.
Still, I'd like to lint cases like …
> Don't assume parentheses in chaining if there were none before

- CHANGELOG.md
I have forgotten to add the entries while fixing the bugs.
> Add changelog entries for the bug fixes to Style/MethodCallWithArgsParentheses

- README.md
Fixes: #6592 
Replace the coverage badge in `README.md`
> [Fix #6592] Fix Readme coverage badge

- LICENSE.txt
- README.md
- mkdocs.yml
This PR updates Copyright year to 2019.
> Update Copyright year to 2019

- CHANGELOG.md
- lib/rubocop/cop/correctors/percent_literal_corrector.rb
- lib/rubocop/cop/layout/closing_parenthesis_indentation.rb
- lib/rubocop/cop/rails/relative_date_constant.rb
- lib/rubocop/rspec/cop_helper.rb
- lib/rubocop/rspec/expect_offense.rb
- spec/rubocop/cop/internal_affairs/node_type_predicate_spec.rb
- spec/rubocop/cop/layout/closing_parenthesis_indentation_spec.rb
- spec/rubocop/cop/rails/relative_date_constant_spec.rb
- spec/rubocop/cop/style/word_array_spec.rb
I think we have discussed adding this helper method before. If everyone likes it, I will update the documentation. This will allow us to test an offense, highlighting, message, and auto-correction with a single method call.
> Proposed testing feature: expect_correction helper

- lib/rubocop/cop/performance/chain_array_allocation.rb
- spec/rubocop/cop/performance/chain_array_allocation_spec.rb
> Fix error message for `Performance/ChainArrayAllocation` cop

- CHANGELOG.md
Including the bug fix for #6720.
I didn't include the changelog update in my original PR because it was not a 'user observable' change but now that I see that there is a bug fix section, I have added it to that section.
> Update CHANGELOG to include new bug fix.

- lib/rubocop/rspec/expect_offense.rb
Follow up of #6752.
This PR aligns an example for `RSpec/ExpectOffense` cop.
> Align an example for `RSpec/ExpectOffense` cop

- lib/rubocop/cop/lint/deprecated_class_methods.rb
- lib/rubocop/cop/mixin/frozen_string_literal.rb
- manual/cops_lint.md
- spec/rubocop/cop/lint/deprecated_class_methods_spec.rb
> Remove argument of `iterator?` and `block_given?`

- spec/rubocop/cop/layout/rescue_ensure_alignment_spec.rb
Add a test to demonstrate the correct styles of a begin-rescue as the
RHS of an assignment.
> [Fix #6603] - Testing RescueEnsureAlignment

- lib/rubocop/cop/layout/space_in_lambda_literal.rb
- lib/rubocop/cop/layout/space_inside_reference_brackets.rb
- lib/rubocop/cop/lint/duplicate_methods.rb
- lib/rubocop/cop/lint/useless_assignment.rb
- lib/rubocop/cop/lint/useless_setter_call.rb
- lib/rubocop/cop/metrics/perceived_complexity.rb
- lib/rubocop/cop/mixin/too_many_lines.rb
- lib/rubocop/cop/rails/active_record_override.rb
- lib/rubocop/cop/rails/find_each.rb
- lib/rubocop/cop/rails/time_zone.rb
- lib/rubocop/cop/style/format_string.rb
- lib/rubocop/cop/style/optional_arguments.rb
- lib/rubocop/cop/style/redundant_sort_by.rb
- lib/rubocop/cop/style/unless_else.rb
- lib/rubocop/cop/util.rb
Using node extensions methods makes the code more readable and in some cases shorter.
> Avoid manual node deconstruction

- spec/rubocop/cop/layout/block_alignment_spec.rb
- spec/rubocop/cop/layout/block_end_newline_spec.rb
- spec/rubocop/cop/layout/closing_heredoc_indentation_spec.rb
- spec/rubocop/cop/layout/closing_parenthesis_indentation_spec.rb
- spec/rubocop/cop/layout/dot_position_spec.rb
- spec/rubocop/cop/layout/else_alignment_spec.rb
- spec/rubocop/cop/layout/empty_line_after_magic_comment_spec.rb
- spec/rubocop/cop/layout/empty_line_between_defs_spec.rb
- spec/rubocop/cop/layout/heredoc_argument_closing_parenthesis_spec.rb
- spec/rubocop/cop/layout/indent_assignment_spec.rb
- spec/rubocop/cop/layout/indent_hash_spec.rb
- spec/rubocop/cop/layout/space_inside_hash_literal_braces_spec.rb
- spec/rubocop/cop/layout/space_inside_parens_spec.rb
- spec/rubocop/cop/layout/space_inside_range_literal_spec.rb
> Convert more examples to expect_correction

- .gitignore
This would mildly improve my workflow.
> Add byebug_history to gitignore

- lib/rubocop/cop/layout/heredoc_argument_closing_parenthesis.rb
- spec/rubocop/cop/layout/heredoc_argument_closing_parenthesis_spec.rb
This fixes a few edge cases I noticed running this on the Flexport codebase.
Previously, the cop was not able to autocorrect the case below because it found a violation on the outer `query.order` call instead of the inner `Arel.sql` call. This PR fixes that and adds a spec.
```rb
query.order(Arel.sql(<<-SQL,
foo
SQL
))
```
Now that autocorrects to this after two passes, first finding the inner violation, then the outer:
```rb
query.order(Arel.sql(<<-SQL))
foo
SQL
```
Previously the cop conservatively ignored these cases, but now it fixes them.
Old:
```rb
query.joins({
foo: []
}).order(Arel.sql(<<-SQL),
bar
SQL
)
```
New:
```rb
query.joins({
foo: []
}).order(Arel.sql(<<-SQL))
bar
SQL
```
```
description(
<<-TEXT
foobarbaz
TEXT
.foo
)
```
Autocorrecting these cases is beyond the scope of …
> Fix edge cases for HeredocArgumentClosingParenthesis

- lib/rubocop/cop/style/redundant_parentheses.rb
- lib/rubocop/cop/style/sample.rb
Follow up #6773.
This PR refactors with `range_type`.
> Refactor with `range_type`

- CHANGELOG.md
Follow up https://github.com/rubocop-hq/rubocop/commit/8be5e07b93a75868dd7b2c828ff4c3b22b7743b1.
> Move an unreleased changelog entry

- manual/node_pattern.md
A much needed update to the doc after some recent changes to `NodePattern`.
> Bring NodePattern doc up to date

- manual/development.md
Only `on_send` was mentioned in this guide, and this is only the tip of the iceberg.
* [-] Squashed related commits together.
* [-] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
> Add a reference to the list of available parser hooks

- README.md
- config/default.yml
- lib/rubocop/cop/layout/class_structure.rb
- manual/cops.md
- manual/cops_layout.md
- manual/cops_lint.md
- manual/cops_metrics.md
- manual/cops_naming.md
- manual/cops_style.md
- manual/index.md
- spec/rubocop/cli/cli_options_spec.rb
- spec/rubocop/cli_spec.rb
Update styleguide link to point to new styleguide - https://rubystyle.guide
* [  ] Added tests.
> Update style guide links

- lib/rubocop/cop/layout/indent_first_argument.rb
- lib/rubocop/cop/layout/indent_first_parameter.rb
- manual/cops_layout.md
Hopefully the documentation speaks for itself to resolve the confusion here: https://github.com/rubocop-hq/rubocop/issues/5975#issuecomment-503740279
> Add comments clarifying IndentFirstParameter vs IndentFirstArgument

- lib/rubocop/config.rb
- lib/rubocop/processed_source.rb
- spec/rubocop/cli_spec.rb
Showing it came from `RuboCop`.
> [Fix #6793] Clarify ruby version error

- lib/rubocop/cop/style/commented_keyword.rb
I cleaned up this cop. All the code for heredoc detection was a leftover from a time when the cop didn't use `processed_source.comments` but looked at raw lines.
> Simplify Style/CommentedKeyword

- lib/rubocop/cop/metrics/line_length.rb
- manual/cops_metrics.md
Follow up https://github.com/rubocop-hq/rubocop/pull/7232#issuecomment-515312095.
This PR adds a description for `Metrics/LineLength`.
> Add a description for `Metrics/LineLength`

- lib/rubocop/cop/layout/extra_spacing.rb
Forgotten in 3a31899a376c47a3e9d69b66b8c178f3d8b61050 :disappointed:
> Remove obsolete comment for unary plus

- lib/rubocop/cop/layout/block_alignment.rb
- manual/cops_layout.md
> Fix Layout/BlockAlignment example in manual

- lib/rubocop/formatter/pacman_formatter.rb
> Fix a typo in pacman_formatter [ci skip]

- lib/rubocop/cop/style/redundant_return.rb
- manual/cops_style.md
This PR adds examples of `AllowMultipleReturnValues` option for `Style/RedundantReturn`.
> Add examples for `Style/RedundantReturn`

- lib/rubocop/cop/style/documentation_method.rb
- manual/cops_style.md
This PR adds examples for `Style/DocumentationMethod`.
> Add examples for `Style/DocumentationMethod`

- lib/rubocop/cop/lint/unused_method_argument.rb
- manual/cops_lint.md
This PR adds examples for `Lint/UnusedMethodArgument`.
> Add examples for `Lint/UnusedMethodArgument`

- lib/rubocop/cop/style/semicolon.rb
- manual/cops_style.md
This PR adds examples for `Style/Semicolon`.
> Add examples for `Style/Semicolon`

- lib/rubocop/cop/layout/trailing_whitespace.rb
- manual/cops_layout.md
This PR adds examples for `Layout/TrailingWhitespace` cop.
> Add examples for `Layout/TrailingWhitespace`

- lib/rubocop/node_pattern.rb
:wink: @Drenmi: This feels like cheating …
> Reduce ABC size of NodePattern#compile_any_order

- lib/rubocop/cop/style/next.rb
- manual/cops_style.md
Examples with the same behavior help to better focus on the Style differences
> Keep the examples in Style/Next doc consistent

- lib/rubocop/config_validator.rb
Follow up of https://github.com/rubocop-hq/rubocop/commit/418973b.
https://github.com/jruby/jruby/issues/5935 has been resolved and JRuby 9.2.9.0 has been released.
> Remove workaround code for a JRuby's bug

- lib/rubocop/cop/layout/first_argument_indentation.rb
- lib/rubocop/cop/layout/first_parameter_indentation.rb
- lib/rubocop/cop/metrics/line_length.rb
- manual/cops_layout.md
- manual/cops_metrics.md
A few minor cleanups related to the good work by @scottmatthewman on https://github.com/rubocop-hq/rubocop/issues/7077.
> Minor cleanup of new cop names in cop docs

- manual/development.md
Not sure if these are the best approaches, but they've been working for me. I jotted this down in my private notes for my future self but then realized others may benefit too :)
lmk if there's more / different to say here!
> Add specific techniques for testing locally against codebase

- lib/rubocop/cop/style/trailing_underscore_variable.rb
- manual/cops_style.md
This is only document change.
This PR is a change of document format for `Style/TrailingUnderscoreVariable` cop.
> Restyle example formatting for `Style/TrailingUnderscoreVariable` cop.

- CHANGELOG.md
- lib/rubocop/config.rb
- lib/rubocop/cop/bundler/insecure_protocol_source.rb
- lib/rubocop/cop/lint/each_with_object_argument.rb
- lib/rubocop/cop/mixin/alignment.rb
- lib/rubocop/cop/style/infinite_loop.rb
- lib/rubocop/node_pattern.rb
- lib/rubocop/options.rb
- lib/rubocop/runner.rb
- manual/configuration.md
- manual/cops_bundler.md
- relnotes/v0.28.0.md
- relnotes/v0.31.0.md
- spec/rubocop/cli/cli_options_spec.rb
- spec/rubocop/cop/lint/each_with_object_argument_spec.rb
- spec/rubocop/options_spec.rb
This PR unifies wording.
cf. https://github.com/rails/rails/pull/35503
> Replace "can not" with "cannot"

- CHANGELOG.md
- lib/rubocop/cop/style/guard_clause.rb
- spec/rubocop/cop/style/guard_clause_spec.rb
> [Fix #7574] Fix corner case in Style/GuardClause

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/mixin/frozen_string_literal.rb
- lib/rubocop/cop/style/frozen_string_literal_comment.rb
- manual/cops_style.md
- spec/fixtures/html_formatter/expected.html
- spec/rubocop/cli/cli_auto_gen_config_spec.rb
- spec/rubocop/cli/cli_autocorrect_spec.rb
- spec/rubocop/cli/cli_disable_uncorrectable_spec.rb
- spec/rubocop/cli/cli_options_spec.rb
- spec/rubocop/cli_spec.rb
- spec/rubocop/cop/style/frozen_string_literal_comment_spec.rb
Bringing https://github.com/rubocop-hq/rubocop/pull/7435 over the finish line.
* Addressed merge conflicts
* Addressed error message comment from @bbatsov (https://github.com/rubocop-hq/rubocop/pull/7435#issuecomment-570307705)
cc @bbatsov @koic @pirj @parkerfinch
> Enforce frozen string literal true

- manual/cops_naming.md
> referencd -> referenced

- CHANGELOG.md
I forgot to include this in my original PR. Thanks
> Add Changelog entry for new NodePattern operator ` [#7693]

- manual/basic_usage.md
> Update docs for --fail-fast option in Basic Usage doc

- spec/rubocop/result_cache_spec.rb
This PR suppresses the following warnings that are displayed when running tests, and makes them executable test code.
```console
% cd path/to/rubocop
% bundle exec rspec ./spec/rubocop/result_cache_spec.rb:278
Run options: include {:focus=>true,
:locations=>{"./spec/rubocop/result_cache_spec.rb"=>[278]}}
Randomized with seed 7133
Couldn't create cache directory. Continuing without cache.
Permission denied
.Couldn't create cache directory. Continuing without cache.
Read-only file system
.
Finished in 0.20314 seconds (files took 1.93 seconds to load)
2 examples, 0 failures
Randomized with seed 7133
```
> Add spec for warning messages when cache location is invalid

- lib/rubocop.rb
- lib/rubocop/ast_aliases.rb
- lib/rubocop/error.rb
- lib/rubocop/ext/processed_source.rb
- lib/rubocop/runner.rb
This has temporary compatibility with `rubocop-ast` 0.0.2
> [Fix rubocop-hq/rubocop-ast#7] Improve rubocop-ast separation

- spec/rubocop/cop/metrics/method_length_spec.rb
Difficult to make a smaller PR...
> Spec: remove trailing whitespace

- CHANGELOG.md
There's no way to push directly to `master`, even for [doc] only commits, right?
> Amend Changelog [doc] [ci skip]

- docs/modules/ROOT/pages/development.adoc
- legacy-docs/development.md
* [-] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
> Fix Node Pattern manual link

- lib/rubocop/cop/style/redundant_conditional.rb
Prelude to https://github.com/rubocop-hq/rubocop-ast/pull/26
> Refactor cop; call `to_a` on COMPARISON_OPERATORS

- spec/rubocop/config_loader_spec.rb
- spec/spec_helper.rb
> Disable broken tests

- spec/rubocop/cop/style/redundant_return_spec.rb
Use newer `expect_offense + expect_correction` instead of the older
`inspect_source + autocorrect_source`.
Part of #8127
> Refactor specs for `Style/RedundantReturn` cop

- docs/modules/ROOT/pages/cops_metrics.adoc
- lib/rubocop/cop/metrics/cyclomatic_complexity.rb
> Typo fix [doc] [ci skip]

- docs/modules/ROOT/pages/cops_style.adoc
- lib/rubocop/cop/style/multiline_block_chain.rb
This PR updates examples of `Style/MultilineBlockChain` cop.
> Update examples of `Style/MultilineBlockChain` cop

- lib/rubocop/cop/naming/binary_operator_parameter_name.rb
- spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb
- spec/rubocop/cop/layout/multiline_operation_indentation_spec.rb
**Update multiline layout specs to use DENYLIST**
Use DENYLIST rather than BLACKLIST in example code being used to test the multiline cops.
**Use DENYLISTED in BinaryOperatorParameterName cop**
Prefer DENYLIST to BLACKLIST in code as well as in cop config names.
> More black list and white list updates

- spec/rubocop/cop/gemspec/ordered_dependencies_spec.rb
Use newer `expect_offense` + `expect_correction` in Gemspec cops.
Part of #8127
> Refactor specs in Gemspec cops

- lib/rubocop/cli.rb
- lib/rubocop/cli/command/auto_genenerate_config.rb
- lib/rubocop/config_store.rb
- lib/rubocop/result_cache.rb
- lib/rubocop/runner.rb
- lib/rubocop/target_finder.rb
- spec/rubocop/result_cache_spec.rb
This PR extracts some duplicated logic into `ConfigStore#for_pwd`.
> Extract `ConfigStore#for_pwd`

- Gemfile
- bin/rubocop-profile
Does this look good to you, @fatkodima ?
> Add `--memory` option to `bin/rubocop-profile` (and basic `--help` too)

- lib/rubocop/cop/security/eval.rb
- lib/rubocop/cop/security/json_load.rb
- lib/rubocop/cop/security/marshal_load.rb
- lib/rubocop/cop/security/open.rb
- lib/rubocop/cop/security/yaml_load.rb
This PR uses `Cop::Base` API for `Security` department's cops.
> Use `Cop::Base` API for `Security` department

- lib/rubocop/cop/migration/department_name.rb
This PR uses `Cop::Base` API for `Migration` department's cop.
> Use `Cop::Base` API for `Migration` department

- lib/rubocop/cop/metrics/abc_size.rb
- lib/rubocop/cop/metrics/block_length.rb
- lib/rubocop/cop/metrics/block_nesting.rb
- lib/rubocop/cop/metrics/class_length.rb
- lib/rubocop/cop/metrics/cyclomatic_complexity.rb
- lib/rubocop/cop/metrics/method_length.rb
- lib/rubocop/cop/metrics/module_length.rb
- lib/rubocop/cop/metrics/parameter_lists.rb
- lib/rubocop/cop/metrics/perceived_complexity.rb
- lib/rubocop/cop/mixin/code_length.rb
- spec/rubocop/cop/metrics/abc_size_spec.rb
- spec/rubocop/cop/metrics/block_length_spec.rb
- spec/rubocop/cop/metrics/class_length_spec.rb
- spec/rubocop/cop/metrics/module_length_spec.rb
This PR uses `Cop::Base` API for `Metrics` department's cops.
> Use `Cop::Base` API for `Metrics` department

- lib/rubocop/cop/mixin/uncommunicative_name.rb
- lib/rubocop/cop/naming/accessor_method_name.rb
- lib/rubocop/cop/naming/ascii_identifiers.rb
- lib/rubocop/cop/naming/binary_operator_parameter_name.rb
- lib/rubocop/cop/naming/block_parameter_name.rb
- lib/rubocop/cop/naming/class_and_module_camel_case.rb
- lib/rubocop/cop/naming/constant_name.rb
- lib/rubocop/cop/naming/file_name.rb
- lib/rubocop/cop/naming/heredoc_delimiter_case.rb
- lib/rubocop/cop/naming/heredoc_delimiter_naming.rb
- lib/rubocop/cop/naming/memoized_instance_variable_name.rb
- lib/rubocop/cop/naming/method_parameter_name.rb
- lib/rubocop/cop/naming/predicate_name.rb
- lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb
- spec/rubocop/cop/naming/file_name_spec.rb
This PR uses `Cop::Base` API for `Naming` department's cops.
> Use `Cop::Base` API for `Naming` department

- lib/rubocop/cop/internal_affairs/method_name_equal.rb
- lib/rubocop/cop/internal_affairs/node_destructuring.rb
- lib/rubocop/cop/internal_affairs/offense_location_keyword.rb
- lib/rubocop/cop/internal_affairs/redundant_location_argument.rb
- lib/rubocop/cop/internal_affairs/redundant_message_argument.rb
- lib/rubocop/cop/internal_affairs/useless_message_assertion.rb
This PR uses `Cop::Base` API for `InternalAffairs` department's cop.
> Use `Cop::Base` API for `InternalAffairs` department

- spec/rubocop/cop/lint/script_permission_spec.rb
> Add no-correction spec for Lint/ScriptPermission

- docs/modules/ROOT/pages/v1_upgrade_notes.adoc
> Tweak recommendation for cops' instance variables [doc]

- .circleci/config.yml
- .github/workflows/rubocop.yml
- .mergify.yml
Must have label 'auto-merge' and pass all CI.
As an added security, PRs with reviews pending / with changes requested won't be merged.
Auto-deletes the branches on successful merging.
> Enable mergify

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops.adoc
- docs/modules/ROOT/pages/cops_lint.adoc
- lib/rubocop.rb
- lib/rubocop/cop/lint/useless_method_definition.rb
- lib/rubocop/formatter/html_formatter.rb
- spec/rubocop/cop/lint/useless_method_definition_spec.rb
> Add new `Lint/UselessMethodDefinition` cop

- docs/modules/ROOT/pages/cops_style.adoc
- lib/rubocop/cop/style/method_called_on_do_end_block.rb
This PR clears good and bad cases for `Style/MethodCalledOnDoEndBlock`.
> Update examples for `Style/MethodCalledOnDoEndBlock`

- lib/rubocop/cop/layout/trailing_empty_lines.rb
- lib/rubocop/cop/layout/trailing_whitespace.rb
- spec/rubocop/cop/layout/trailing_empty_lines_spec.rb
- spec/rubocop/cop/layout/trailing_whitespace_spec.rb
Follow #7868.
This PR uses `Cop::Base` API for `Layout` department's cops between T and Z.
> Use `Cop::Base` API for `Layout` department [T-Z]

- CHANGELOG.md
- lib/rubocop/cop/layout/empty_line_between_defs.rb
- spec/rubocop/cop/layout/empty_line_between_defs_spec.rb
> Fix an infinite loop error for `Layout/EmptyLineBetweenDefs`

- lib/rubocop/cop/style/conditional_assignment.rb
Follow #7868.
This PR uses `Cop::Base` API for `Style/ConditionalAssignment`.
> Use `Cop::Base` API for `Style/ConditionalAssignment`

- CHANGELOG.md
- lib/rubocop/cop/lint/unreachable_loop.rb
- spec/rubocop/cop/lint/unreachable_loop_spec.rb
> Fix a false positive for `Lint/UnreachableLoop` when conditional branch includes continue statement preceding break statement

- CHANGELOG.md
Somehow this changelog item ended up in 0.90 instead of master.
> Put changelog item for #8629 in correct version

- lib/rubocop/cop/layout/class_structure.rb
- lib/rubocop/cop/layout/empty_line_after_guard_clause.rb
- lib/rubocop/cop/layout/empty_line_after_multiline_condition.rb
- lib/rubocop/cop/layout/empty_lines_around_attribute_accessor.rb
- lib/rubocop/cop/lint/unreachable_loop.rb
- lib/rubocop/cop/mixin/visibility_help.rb
- lib/rubocop/cop/style/combinable_loops.rb
- lib/rubocop/cop/style/keyword_parameters_order.rb
- lib/rubocop/cop/style/redundant_assignment.rb
- lib/rubocop/cop/style/redundant_parentheses.rb
https://github.com/rubocop-hq/rubocop-ast/pull/93
> Use sibling helpers from rubocop-ast

- CHANGELOG.md
- lib/rubocop/comment_config.rb
- spec/rubocop/comment_config_spec.rb
> Fix rubocop comment directives handling of cops with multiple levels in department name

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_bundler.adoc
- lib/rubocop/cop/bundler/duplicated_gem.rb
- spec/rubocop/cop/bundler/duplicated_gem_spec.rb
> Fix a false positives for `Bundler/DuplicatedGem` when a gem conditionally duplicated within `if-elsif` or `case-when` statements

- lib/rubocop/cop/lint/to_enum_arguments.rb
- lib/rubocop/rspec/shared_contexts.rb
- spec/rubocop/cop/lint/to_enum_arguments_spec.rb
Follow up of https://github.com/rubocop-hq/rubocop/pull/8941#issuecomment-716695976
@marcandre
> Support arguments forwarding in `Lint/ToEnumArguments` cop

- docs/modules/ROOT/pages/cops_style.adoc
- lib/rubocop/cop/style/multiple_comparison.rb
> Improve doc for MultipleComparison

- lib/rubocop/cop/mixin/configurable_formatting.rb
- lib/rubocop/cop/naming/method_name.rb
- lib/rubocop/cop/naming/variable_name.rb
- lib/rubocop/cop/naming/variable_number.rb
For context https://github.com/rubocop-hq/rubocop/commit/51ff1d7e29c985732fe129082c98d66c531a2611#r43837211
@pirj @bbatsov 
@marcandre maybe you have other ideas on how to implement that?
> Fix introduced incompatibility for ConfigurableFormatting#message

- changelog/change_memoized_instance_variable_cop.md
- config/default.yml
- docs/modules/ROOT/pages/cops_naming.adoc
- lib/rubocop/cop/naming/memoized_instance_variable_name.rb
- spec/rubocop/cop/naming/memoized_instance_variable_name_spec.rb
Closes #5717 
As for me, code is a bit hairy, but splitting it further probably won't make it better.
[Rendered without space changes](https://github.com/rubocop-hq/rubocop/commit/4635fcab3dbf8a0ee0f9c1f1eab9f14c83bdebcb?w=1)
> Support `defined?`-based memoization for `Naming/MemoizedInstanceVariableName` cop

- lib/rubocop/cop/bundler/duplicated_gem.rb
- lib/rubocop/cop/bundler/gem_comment.rb
- lib/rubocop/cop/gemspec/duplicated_assignment.rb
- lib/rubocop/cop/gemspec/required_ruby_version.rb
- lib/rubocop/cop/gemspec/ruby_version_globals_usage.rb
This PR uses `Cop::Base` API for some `Bundler` and `Gemspec` cops.
> Use `Cop::Base` API for some `Bundler` and `Gemspec` cops

- .github/workflows/rubocop.yml
> CI: Only pushes to master should trigger builds

- lib/rubocop/cop/layout/end_of_line.rb
- lib/rubocop/cop/lint/no_return_in_begin_end_blocks.rb
- lib/rubocop/cop/style/numeric_literals.rb
- lib/rubocop/cop/style/redundant_argument.rb
- spec/rubocop/cop/layout/end_of_line_spec.rb
- spec/rubocop/cop/team_spec.rb
Follow #7868.
This PR uses `Cop::Base` API for several cops.
> Use `Cop::Base` API for several cops

- .github/ISSUE_TEMPLATE/bug_report.md
- CONTRIBUTING.md
Fixes #9124.
This PR updates example for `rubocop -V` of issue template.
> [Fix #9124] Update example for `rubocop -V` of issue template

- changelog/fix_fix_an_error_for_lintinterpolationcheck.md
- lib/rubocop/cop/lint/interpolation_check.rb
- spec/rubocop/cop/lint/interpolation_check_spec.rb
Closes https://github.com/rubocop-hq/rubocop/issues/8684
> [Fix #8684] Fix an error for `Lint/InterpolationCheck` cop

- lib/rubocop/cop/style/hash_like_case.rb
Resolves #9296.
This PR suppresses error information when `MinBranchesCount` of `Style/HashLikeCase` is not a positive integer.
```console
% bundle exec rubocop --only Style/HashLikeCase
(snip)
An error occurred while Style/HashLikeCase cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/9296/example.rb:1:0.
.
An error occurred while Style/HashLikeCase cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/9296/example.rb:1:0.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues
Mention the following information in the issue report:
1.7.0 (using Parser …
```
> [Fix #9296] Suppress error info when `Style/HashLikeCase`'s config is illegal

- README.md
> minor typo: "aim the ease" -> "aim to ease"

- docs/modules/ROOT/pages/cops_style.adoc
- lib/rubocop/cop/style/numeric_predicate.rb
> Fix typo: "as it its" → "as its"

- lib/rubocop/config.rb
See https://github.com/rubocop-hq/ruby-style-guide/pull/863
> Avoid tap.

- lib/rubocop/cli/command/suggest_extensions.rb
> Use https for links to suggested extensions.

- lib/rubocop/cop/correctors/alignment_corrector.rb
- lib/rubocop/cop/layout/access_modifier_indentation.rb
- lib/rubocop/cop/layout/argument_alignment.rb
- lib/rubocop/cop/layout/array_alignment.rb
- lib/rubocop/cop/layout/assignment_indentation.rb
- lib/rubocop/cop/layout/block_end_newline.rb
- lib/rubocop/cop/layout/closing_parenthesis_indentation.rb
- lib/rubocop/cop/layout/comment_indentation.rb
- lib/rubocop/cop/layout/else_alignment.rb
- lib/rubocop/cop/layout/first_argument_indentation.rb
- lib/rubocop/cop/layout/first_array_element_indentation.rb
- lib/rubocop/cop/layout/first_hash_element_indentation.rb
- lib/rubocop/cop/layout/first_parameter_indentation.rb
- lib/rubocop/cop/layout/indentation_consistency.rb
- lib/rubocop/cop/layout/indentation_style.rb
- lib/rubocop/cop/layout/indentation_width.rb
- lib/rubocop/cop/layout/multiline_method_call_indentation.rb
- lib/rubocop/cop/layout/multiline_operation_indentation.rb
- lib/rubocop/cop/layout/parameter_alignment.rb
- lib/rubocop/cop/mixin/alignment.rb
- lib/rubocop/cop/mixin/multiline_element_indentation.rb
- lib/rubocop/cop/mixin/multiline_expression_indentation.rb
- spec/support/cops/alignment_directive.rb
Follow https://github.com/rubocop/rubocop/pull/7868.
This PR uses `Cop::Base` API for almost all cops mixing `Alignment` module.
> Use `Cop::Base` API for `Alignment`

- .rubocop.yml
- lib/rubocop/cop/style/commented_keyword.rb
Note that 'instance_methods' is not a valid category.
> Remove (almost) redundant setting.

- lib/rubocop/cli/command/auto_genenerate_config.rb
- lib/rubocop/config_loader.rb
- lib/rubocop/result_cache.rb
- spec/rubocop/cli/auto_gen_config_spec.rb
- spec/rubocop/cli/autocorrect_spec.rb
- spec/rubocop/cli/disable_uncorrectable_spec.rb
- spec/rubocop/cli_spec.rb
Follow https://github.com/rubygems/rubygems/pull/4530.
> Prefer `File.read` instead of `IO.read`

- changelog/change_drop_ruby_24.md
This PR fixes the PR number for #9648.
> Tweak a changelog entry

- CHANGELOG.md
* [N/A] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [N/A] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.
> Fix wrong link for SingleLineBlockChain

- changelog/new_support_autocorrection_for_identical_conditional_branches.md
- config/default.yml
- lib/rubocop/cop/style/identical_conditional_branches.rb
- spec/rubocop/cop/style/identical_conditional_branches_spec.rb
This PR supports auto-correction for `Style/IdenticalConditionalBranches`.
> Support auto-correction for `Style/IdenticalConditionalBranches`

- lib/rubocop/cop/style/mutable_constant.rb
In case of `CONST ||= expr`, the analysis was done twice, once with the correct value, but another time with `nil`.
Moreover, checks for the `nil` case were done where they didn't belong.
Finally, all `@memo ||= expr` or similar would trigger a callback for nothing.
> Optimize and simplify `MutableConstant` Cop

- config/default.yml
- lib/rubocop/cop/style/case_equality.rb
Follow up of https://github.com/rubocop/rubocop/pull/4880#issuecomment-338499947
This PR is a change of document format for `Style/CaseEquality` cop.
> Restyle example formatting for `Style/CaseEquality`

- lib/rubocop/cop/style/optional_boolean_parameter.rb
- spec/rubocop/cop/style/optional_boolean_parameter_spec.rb
I noticed on stackoverflow that some people have confusion about how to correct `Style/OptionalBooleanParameter`, so this change makes the messaging more explicit.
> Update the message for `Style/OptionalBooleanParameter`

- .github/workflows/rubocop.yml
https://github.com/ruby/setup-ruby/pull/253 has been merged and follow up to https://github.com/rubocop/rubocop/pull/10327#issuecomment-1003868439.
> CI against Ruby 3.1 on Windows

- tasks/cut_release.rake
Follow up to https://github.com/rubocop/rubocop/commit/bb7e5b07.
> Follow the version specification `~` for antora.yml

- lib/rubocop/cop/lint/redundant_safe_navigation.rb
- lib/rubocop/cop/naming/predicate_name.rb
- lib/rubocop/cop/style/if_with_boolean_literal_branches.rb
- lib/rubocop/cop/style/nested_parenthesized_calls.rb
- lib/rubocop/cop/style/trivial_accessors.rb
This PR is documentation was added according to the following policy for "AllowedMethods" option
- Add code examples for cop that don't have code examples
- Add default values for cop that don't have default values
> Enhanced documentation for "AllowedMethods" option

- lib/rubocop/cop/style/guard_clause.rb
This PR is following documentation improvements have been made
- Fixed an incorrect bad case that was not wrapped in `def`
- Added a supplement on acceptable cases of conditions with `elsif` or `else` branches
refs: https://github.com/rubocop/rubocop/issues/10904 , https://github.com/rubocop/rubocop/issues/10904#issuecomment-1211741427
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry …
> Enhanced documentation for `Style/GuardClause`

- lib/rubocop/cop/layout/block_alignment.rb
> [Fix #10949] Fix documentation error for `Layout/BlockAlignment`

- spec/rubocop/cop/layout/multiline_block_layout_spec.rb
> Fixed trivial typo

- lib/rubocop/cop/style/rescue_modifier.rb
> Fix "led" → "lead" typo

- config/default.yml
- docs/modules/ROOT/pages/cops_style.adoc
> Style/DateTime: Fix styleguide link

- lib/rubocop/config.rb
- lib/rubocop/cop/badge.rb
- lib/rubocop/cop/base.rb
- lib/rubocop/cop/registry.rb
- spec/rubocop/cop/badge_spec.rb
- spec/rubocop/cop/cop_spec.rb
- spec/rubocop/cop/registry_spec.rb
Changes as requested from https://github.com/rubocop/rubocop/pull/11264#issuecomment-1349666086
> Change `Badge#department` type back to `Symbol`

- lib/rubocop/cop/style/yoda_expression.rb
- spec/rubocop/cop/style/yoda_expression_spec.rb
Follow up to https://github.com/rubocop/rubocop/pull/11333#discussion_r1059600587.
> Improve offense message for `Style/YodaExpression` cop

- .github/workflows/rubocop.yml
https://github.com/ruby/setup-ruby/pull/435 has been merged.
> CI against Ruby 3.2 on Windows

- .pre-commit-hooks.yaml
This PR adds a description to ` .pre-commit-hooks.yaml` which enables this description to appear on the main list of pre-commit hooks (https://pre-commit.com/hooks.html).
> Add RuboCop project description to .pre-commit-hooks.yaml

- Gemfile
- spec/project_spec.rb
- spec/rubocop/cli/auto_gen_config_spec.rb
- spec/rubocop/cli/autocorrect_spec.rb
- spec/rubocop/cli/options_spec.rb
- spec/rubocop/cli_spec.rb
- spec/rubocop/comment_config_spec.rb
- spec/rubocop/config_loader_spec.rb
- spec/rubocop/config_spec.rb
- spec/rubocop/cop/generator_spec.rb
- spec/rubocop/cop/message_annotator_spec.rb
- spec/rubocop/cop/registry_spec.rb
- spec/rubocop/cop/team_spec.rb
- spec/rubocop/formatter/auto_gen_config_formatter_spec.rb
- spec/rubocop/formatter/clang_style_formatter_spec.rb
- spec/rubocop/formatter/emacs_style_formatter_spec.rb
- spec/rubocop/formatter/formatter_set_spec.rb
- spec/rubocop/formatter/git_hub_actions_formatter_spec.rb
- spec/rubocop/formatter/junit_formatter_spec.rb
- spec/rubocop/formatter/offense_count_formatter_spec.rb
- spec/rubocop/formatter/progress_formatter_spec.rb
- spec/rubocop/formatter/quiet_formatter_spec.rb
- spec/rubocop/formatter/simple_text_formatter_spec.rb
- spec/rubocop/formatter/tap_formatter_spec.rb
- spec/rubocop/options_spec.rb
- spec/rubocop/target_finder_spec.rb
This PR is use RuboCop RSpec 2.18.1
> Use RuboCop RSpec 2.18.1

- lib/rubocop/cop/mixin/allowed_methods.rb
This PR is fixes: https://github.com/rubocop/rubocop/pull/10829#issuecomment-1403082579
> Add a description of the `AllowedMethods` module documentation

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_style.adoc
- docs/modules/ROOT/pages/extensions.adoc
- lib/rubocop/cop/autocorrect_logic.rb
- lib/rubocop/cop/internal_affairs/inherit_deprecated_cop_class.rb
- lib/rubocop/cop/style/class_and_module_children.rb
- lib/rubocop/cop/style/disable_cops_within_source_code_directive.rb
- lib/rubocop/formatter/simple_text_formatter.rb
- relnotes/v1.0.0.md
- spec/rubocop/cop/layout/end_of_line_spec.rb
- spec/rubocop/cop/layout/line_length_spec.rb
- spec/rubocop/cop/lint/ambiguous_regexp_literal_spec.rb
- spec/rubocop/cop/style/disable_cops_within_source_code_directive_spec.rb
- spec/rubocop/cop/style/if_unless_modifier_spec.rb
This PR is use RuboCop instead of Rubocop.
> Use RuboCop instead of Rubocop

- lib/rubocop/cop/lint/to_enum_arguments.rb
Follow up https://github.com/rubocop/rubocop/pull/11592#issuecomment-1440603117.
This PR adds examples for `Lint/ToEnumArguments`.
> Add examples for `Lint/ToEnumArguments`

- CHANGELOG.md
- relnotes/v1.49.0.md
This PR is a follow-up to #11122.
I forgot to add the changes to the CHANGELOG, so I added it this PR. I completely forgot, I'm sorry.
> Add missing changes to the CHANGELOG and release note

- .github/workflows/rubocop.yml
Follow up https://github.com/rubocop/rubocop/pull/10806#discussion_r918415067.
test-queue 0.7.0 supports RSpec 4.0 (dev):
https://github.com/tmm1/test-queue/releases/tag/v0.7.0
> Use test-queue for RSpec 4.0 (dev)

- lib/rubocop/cop/naming/variable_name.rb
Added the following:.
- Description of `AllowedIdentifiers` options
- Good case supplement
> Improve `Naming/VariableName`cop documentation

- lib/rubocop/cop/style/dir_empty.rb
- spec/rubocop/cop/style/dir_empty_spec.rb
> Improve error message for `Style/DirEmpty`

- README.md
This PR adds reference to RuboCop's built-in LSP to quickstart section in the README.
While I recognize that the quickstart section is expanding, I think that due to its potential to dramatically change the development experience, LSP is worth mentioning as a second form of magic.
To keep the quickstart text concise, I have not mentioned the required RuboCop version. It can be easily found by referring to the linked page.
> [Docs] Add reference to LSP to quickstart section

- changelog/fix_nested_special_glob_characters.md
- lib/rubocop/target_finder.rb
- spec/rubocop/target_finder_spec.rb
> [Fix #12052] Handle all glob special characters

- changelog/fix_false_negative_for_string_literals_in_interpolation_dsym.md
- lib/rubocop/cop/mixin/string_help.rb
- spec/rubocop/cop/style/string_literals_in_interpolation_spec.rb
> Fix a false negative for `Style/StringLiteralsInInterpolation` for symbols with interpolation

- changelog/fix_rubocop_loaderror_from_symlinks_on_windows.md
Follow-up to #12062 where changelog entry was not added.
> Add changelog entry for #12062

- lib/rubocop/cop/utils/regexp_ranges.rb
Fix `warning: instance variable @pairs not initialized` warning
> Fix instance variable not initialized warning

- docs/modules/ROOT/pages/development.adoc
This PR updates document in cop generator's output. b3ef2d2bfa752bd21274b40c46d5ce542a73439f seems to have changed this.
> Update document in create a new cop

- docs/modules/ROOT/pages/usage/lsp.adoc
This PR adds [Helix](https://docs.helix-editor.com/languages.html) to the LSP doc.
> [Docs] Add Helix to the LSP doc

- lib/rubocop/cop/lint/empty_block.rb
Just a small documentation edit.
> Edit empty block overview text

- lib/rubocop/cop/layout/indentation_width.rb
- lib/rubocop/cop/layout/space_inside_parens.rb
Follow up: https://github.com/rubocop/rubocop/pull/12176#issuecomment-1752002311
> Remove redundant true/false returns

- .github/workflows/rubocop.yml
https://github.com/ruby/setup-ruby/pull/555 has been merged.
> CI against Ruby 3.3 on Windows

- spec/rubocop/cop/style/arguments_forwarding_spec.rb
This PR adds specs for `Style/ArgumentsForwarding`, which adds missing tests due to the incorrect specification of `TargetRubyVersion`, addressing the current behavior that was lacking.
> Add specs for `Style/ArgumentsForwarding`

- lib/rubocop/cop/internal_affairs/node_matcher_directive.rb
- spec/rubocop/cop/internal_affairs/node_matcher_directive_spec.rb
Closes #12665
Allow `self.` as a prefix for the method name.
I've added tests for both symbol and string arguments. All tests were for symbols but the original issues made use of strings, so just double-checking that that also works.
Since the regex would have gone over the line limit I've enabled free-spacing mode for it to have it span across multiple lines.
> [Fix #12665] Fix infinite loop for `InternalAffairs/NodeMatcherDirective` with class methods

- spec/rubocop/cop/lint/useless_times_spec.rb
This PR fixes a description of example for `Lint/UselessTimes`
> Fix a description of example for `Lint/UselessTimes`

- lib/rubocop/cop/bundler/gem_version.rb
- lib/rubocop/cop/gemspec/dependency_version.rb
- lib/rubocop/cop/style/if_with_boolean_literal_branches.rb
See #12910
This aren't all cops where this happens, just the ones with trivial solutions
> Avoid some warnings "too many arguments for format string"

- CHANGELOG.md
Hi there! This is a minor CHANGELOG fix for the latest release.
Thanks for maintaining RuboCop ❤️
> Fix changelog PR number for ActiveSupportExtensionsEnabled on Style/SymbolProc

- spec/rubocop/cli/auto_gen_config_spec.rb
This was coincidentally fixed with #12730. Reverting that PR makes this test fail. #11916  can be closed now.
> Add a regression test for issue #11916

- lib/rubocop/cop/style/safe_navigation.rb
Improve documentation of the `Style/SafeNavigation` cop.
> Improve wording of `Style/SafeNavigation` documentation

- Gemfile
> Remove `yard` workarounds

- docs/modules/ROOT/pages/automated_code_review.adoc
[Document update] Add Codety Scanner(a open source code scanner https://github.com/codetyio/codety-scanner ) into the automated review tool list. 
There're examples of the Codety's code review automation using Rubocop: 
* GitHub pull request review automation: https://github.com/codetyio/codety-scanner/pull/45 
* GitHub Check Runs: https://github.com/codetyio/codety-scanner/runs/29753344339
> Update automated code review page, add Codety Scanner into the tool list

- lib/rubocop/cops_documentation_generator.rb
This will allow the rails extension to insert the target rails version. I ran the documentation task and confirmed there are no changes here.
Here is how usage would look: https://github.com/rubocop/rubocop-rails/pull/1368
> Allow extensions to contribute documentation sections

- lib/rubocop/cops_documentation_generator.rb
Instead of:
* https://docs.rubocop.org/rubocop/1.66/cops_bundler.html#examples
* https://docs.rubocop.org/rubocop/1.66/cops_bundler.html#examples-2
* https://docs.rubocop.org/rubocop/1.66/cops_bundler.html#examples-3
Do this:
* https://docs.rubocop.org/rubocop/1.66/cops_bundler.html#examples-bundlerduplicatedgem
* https://docs.rubocop.org/rubocop/1.66/cops_bundler.html#examples-bundlerduplicatedgroup
* https://docs.rubocop.org/rubocop/1.66/cops_bundler.html#examples-bundlergemcomment
Links like this will continue to work when new cops are added. Anchors to cops themselves are kept as is, since these already consistently work between versions.
Right now, adding a new cop potentially shifts these numbers around which causes links like that to go to a different place than expected when …
> Generate predictable header ids for duplicate headers

- changelog/new_duplicate_branch_ignore_elses_option.md
- config/default.yml
- lib/rubocop/cop/lint/duplicate_branch.rb
- spec/rubocop/cop/lint/duplicate_branch_spec.rb
> Add new `IgnoreDuplicateElseBranch` option to `Lint/DuplicateBranch`

- docs/modules/ROOT/pages/cops_style.adoc
- lib/rubocop/cop/style/keyword_arguments_merging.rb
> Minor documentation change

- lib/rubocop/cop/style/missing_respond_to_missing.rb
This is one of those where it is not immediatly obvious what you should actually do.
Add code demonstrating what this cop is for and add basic example implementations.
Please do take a closer look at the added example code. I _think_ this is what you want here but it is possible I misunderstood something about the process.
> Add some explanation to `Style/MissingRespondToMissing`

- spec/rubocop/cop/style/word_array_spec.rb
Ref: https://github.com/rubocop/rubocop/pull/13524#discussion_r1864992807
> Follow-up to #13524: minor style fix

- lib/rubocop/cop/mixin/space_before_punctuation.rb
Followup to https://github.com/rubocop/rubocop/pull/12378
Added to rubocop-ast with https://github.com/rubocop/rubocop-ast/pull/272
> Remove a now unnecessary token check

- lib/rubocop/cop/style/it_assignment.rb
Very similar to https://github.com/rubocop/rubocop/pull/13238, assume that there are few local variables named `it`
Before:
```
$ bundle exec rake prof:slow_cops
stackprof tmp/rubocop-stackprof.dump --text --method 'Kernel#public_send'
738  (    2.6%)  RuboCop::Cop::Layout::IndentationConsistency#on_begin
544  (    1.9%)  RuboCop::Cop::RSpec::VariableDefinition#on_send
531  (    1.9%)  RuboCop::Cop::Style::ItAssignment#on_block
(snip)
```
After:
```
$ bundle exec rake prof:slow_cops
stackprof tmp/rubocop-stackprof.dump --text --method 'Kernel#public_send'
(snip)
2  (    0.0%)  RuboCop::Cop::Lint::ConstantDefinitionInBlock#on_class
2  (    0.0%)  RuboCop::Cop::Style::ArgumentsForwarding#on_def
2  (    0.0%)  RuboCop::Cop::Style::ItAssignment#on_lvasgn
2  (    0.0%) …
```
> Improve performance of `Style/ItAssignment`

- lib/rubocop/cop/layout/empty_lines_around_exception_handling_keywords.rb
- lib/rubocop/cop/layout/first_hash_element_line_break.rb
- lib/rubocop/cop/layout/multiline_hash_key_line_breaks.rb
- lib/rubocop/cop/mixin/trailing_comma.rb
There were some cops incorrectly referenced. I fixed them.
> [DOC] Fix broken cop references

- lib/rubocop/cops_documentation_generator.rb
Follows https://github.com/rubocop/rubocop/pull/13707#discussion_r1918955089
Minor refactor to use better parameter names and ordering.
> Use better parameter names in `CopsDocumentationGenerator`

- lib/rubocop/cop/layout/first_parameter_indentation.rb
- lib/rubocop/cop/layout/space_after_colon.rb
- lib/rubocop/cop/layout/space_after_comma.rb
- lib/rubocop/cop/layout/space_after_semicolon.rb
- lib/rubocop/cop/layout/space_before_comma.rb
- lib/rubocop/cop/layout/space_before_semicolon.rb
- lib/rubocop/cop/lint/binary_operator_with_identical_operands.rb
- lib/rubocop/cop/lint/numeric_operation_with_constant_result.rb
Quote cop names and symbols with backticks.
> [DOC] Quote cop names and symbols with backticks

- lib/rubocop/cop/layout/multiline_method_call_indentation.rb
- lib/rubocop/cop/layout/rescue_ensure_alignment.rb
- lib/rubocop/cop/lint/debugger.rb
- lib/rubocop/cop/lint/missing_super.rb
- lib/rubocop/cop/lint/nested_method_definition.rb
- lib/rubocop/cop/lint/next_without_accumulator.rb
- lib/rubocop/cop/lint/redundant_string_coercion.rb
- lib/rubocop/cop/lint/suppressed_exception.rb
- lib/rubocop/cop/lint/useless_ruby2_keywords.rb
- lib/rubocop/cop/mixin/hash_shorthand_syntax.rb
- lib/rubocop/cop/naming/block_forwarding.rb
- lib/rubocop/cop/style/arguments_forwarding.rb
- lib/rubocop/cop/style/it_assignment.rb
- lib/rubocop/cop/style/nested_parenthesized_calls.rb
- lib/rubocop/cop/style/redundant_double_splat_hash_braces.rb
- lib/rubocop/cop/style/redundant_each.rb
- lib/rubocop/cop/style/redundant_parentheses.rb
- lib/rubocop/cop/style/safe_navigation.rb
- lib/rubocop/cop/style/semicolon.rb
- lib/rubocop/cop/style/super_arguments.rb
Followup https://github.com/rubocop/rubocop/commit/6844e0b469e7b48591b6b575679be074c01a6212, from https://github.com/rubocop/rubocop-ast/pull/357
> Use node groups in traversal methods

- lib/rubocop/cop/style/parallel_assignment.rb
The first condition checks if something is not an array. That includes blocks or method calls which are also not arrays
> Remove dead code in `Style/ParallelAssignment`

- docs/modules/ROOT/pages/plugin_migration_guide.adoc
Based on #13858, additional details will be added to the Plugin Migration Guide. While further expansion is possible, a brief background will be included for now in response to the feedback.
Closes #13858
> [Doc] Update the Plugin Migration Guide

- .github/workflows/linting.yml
- lib/rubocop/plugin.rb
- spec/rubocop/plugin_spec.rb
Followup to https://github.com/rubocop/rubocop/pull/13869
The test is more involved, but also much closer to the actual problem.
> Use `gem` instead of `Gem.try_activate`

- .rubocop.yml
- config/internal_affairs.yml
> Move internal affairs config into proper config file

- lib/rubocop/cops_documentation_generator.rb
`CopsDocumentationGenerator` is a private API used primarily for generating documentation for extension gems managed by RuboCop HQ.
With the plugin migration in #13792, the implementation was changed to use `RuboCop::ConfigLoader.inject_defaults!` instead of `Inject`, as shown below:
```diff
-  RuboCop::Performance::Inject.defaults!
+  RuboCop::ConfigLoader.inject_defaults!("#{__dir__}/../config/default.yml")
```
However, switching to this API caused issues in https://github.com/rubocop/rubocop-rspec/pull/2047. This PR addresses those issues in a centralized manner within `CopsDocumentationGenerator`.
As a result, the changes in extension gems will look like this:
```diff
-  RuboCop::ConfigLoader.inject_defaults!("#{__dir__}/../config/default.yml")
-
- …
```
> Make `CopsDocumentationGenerator` support plugin system for extensions

- changelog/fix_false_positive_redundant_freeze_numblock.md
Appreciate you giving me credit @Earlopain but you deserve it :joy:
> Fix changelog for #13935

- .github/workflows/rubocop.yml
9.4.12.0 has been released which should contain a fix for this
> Use latest jruby again

- docs/modules/ROOT/pages/extensions.adoc
> Fix docs: change `RuboCop::Runners` to `RuboCop::Runner`

- docs/modules/ROOT/pages/integration_with_other_tools.adoc
This pull request fixes stale links to related websites/docs and a few minor typos in the "Integration with Other Tools" documentation.
> Fix stale links in the Integration with Other Tools docs

- spec/rubocop/cop/layout/space_inside_array_literal_brackets_spec.rb
> Follow-up to #14159: add specs for empty constant pattern

- lib/rubocop/target_finder.rb
Refactors part of `TargetFinder` so it doesn't allocate an array for hidden files and use binary search, but instead check if the file is hidden only when it's necessary to know.
It's not a huge optimization because it only removes two allocations (for an Array, after `.select` and `.sort`) and bsearch, but I believe the logic reads better.
This is the benchmark for [gitlabhq](https://github.com/gitlabhq/gitlabhq) when running RuboCop on the whole codebase (I did a simple `Benchmark.measure` around `#target_files_in_dir`):
> Optimize hidden files logic in TargetFinder

- spec/ruby_lsp/rubocop/addon_spec.rb
They are quite long in their setup, so I moved what I could outside. I want to add some more tests for the lsp, this should make them more concise
> Remove some boilerplate when testing the lsp addon
