lib/rubocop/ast/node.rb
Two more node matchers that are not used in any of the 3 "official" extensions:
```
$ for r in rubocop{,-performance,-rspec,-rails}; do echo "==== $r" ; git -C $r grep -P 'asgn_rhs|module_definition\?' origin/master; done
==== rubocop
origin/master:lib/rubocop/ast/node.rb:      # Note: for masgn, #asgn_rhs will be an array node
origin/master:lib/rubocop/ast/node.rb:      def_node_matcher :asgn_rhs, '[assignment? (... $_)]'
origin/master:lib/rubocop/ast/node.rb:      def_node_matcher :module_definition?, <<~PATTERN
origin/master:lib/rubocop/cop/metrics/module_length.rb:          module_definition?(node) do
origin/master:lib/rubocop/cop/metrics/module_length.rb:        def_node_matcher :module_definition?, <<~PATTERN
==== rubocop-performance
==== rubocop-rspec
==== rubocop-rails
```
See …
=> Remove unused node matchers in Node

CHANGELOG.md, lib/rubocop/cop/style/constant_visibility.rb, spec/rubocop/cop/style/constant_visibility_spec.rb
This closes #7242.
The cop was not able to deal with multi-statement bodies because it did
not know how to handle a `:begin` node inside a class or module body.
Fixing that revealed another pattern-matching bug that had been masked
before because the pattern was never actually used in the specs.
=> [Fix #7242] Make Style/ConstantVisibility work

config/default.yml, manual/cops_metrics.md
This commit fixes a typographic error in the docs for Metrics/AbcSize, as a punctuation mark has been slid in one of the links of this section, causing following the affected link to open an unexpected page.
=> Fix typographic error in docs for Metrics/AbcSize

appveyor.yml
Ruby 2.6 has been released and this Ruby version is available on Appveyor.
https://www.appveyor.com/docs/windows-images-software/#ruby
=> CI against Ruby 2.6 on Appveyor

lib/rubocop/cop/layout/extra_spacing.rb
Workaround was introduced in e1552c53ef1caa98b1b101045db851c23c6db9ba because back then there was no token for unary plus. Nowadays parser has `tUNARY_NUM` (since v2.4.0.1; also see whitequark/parser#384).
```
$ ruby-parse _2.4_ -E -e '+42'
+42
^~ tINTEGER 42                                 expr_end     [0 <= cond] [0 <= cmdarg]
+42
^ false "$eof"                               expr_end     [0 <= cond] [0 <= cmdarg]
(int 42)
$ ruby-parse _2.6_ -E -e '+42'
+42
^ tUNARY_NUM "+"                                expr_end     [0 <= cond] [0 <= cmdarg]
+42
^~ tINTEGER 42                                 expr_end     [0 <= cond] [0 <= cmdarg]
+42
^ false "$eof"                               expr_end     [0 <= cond] [0 <= cmdarg]
(int 42)
```
=> Remove workaround for unary plus

CHANGELOG.md, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
`Style/RedundantParentheses` does not give an offense for method calls where the first argument is a hash literal, but it does so when the hash literal is called with methods. This fix allows for the detection of methods after the hash literal.
This closes https://github.com/rubocop-hq/rubocop/issues/7256.
=> [Fix #7256] Fix `Style/RedundantParentheses` for method calls beginning with hash literals

CHANGELOG.md, lib/rubocop/cop/layout/space_inside_array_literal_brackets.rb, spec/rubocop/cop/layout/space_inside_array_literal_brackets_spec.rb
Before 6840af5cda4cce4bf7bf32e9bf477a6a6eea0b51 it did not matter that `Layout/SpaceInsideArrayLiteralBrackets` did not know tabs could occur in indentation. Now it does.
This closes #7263.
=> [Fix #7263] Support tab-indented array literals

CHANGELOG.md, lib/rubocop/cop/layout/space_inside_string_interpolation.rb, spec/rubocop/cop/layout/space_inside_string_interpolation_spec.rb
This closes #7252 and resolves #5620.
This is a quick solution that completely ignores leading/trailing space inside multi-line `#{…}` interpolations for now. I might refine it later: While browsing the `SpaceInside*` cops I noticed that most of them perform some kind of multi-line detection but each in a slightly different way. There seems to be potential for unification there.
=> [Fix #7252] Ignore space in multi-line interpolations

CHANGELOG.md, lib/rubocop/cop/lint/format_parameter_mismatch.rb, spec/rubocop/cop/lint/format_parameter_mismatch_spec.rb
This fixes #7262 and removes some obsolete code.
=>  [Fix #7262] Detect more named format sequences

CHANGELOG.md, lib/rubocop/cop/lint/number_conversion.rb, spec/rubocop/cop/lint/number_conversion_spec.rb
Fixes #7253.
This PR fixes an error for `Lint/NumberConversion` when `#to_i` called without a receiver.
```ruby
class Time
def mod(modulus)
to_i % modulus
end
end
```
```console
% rubocop --only Lint/NumberConversion -d
For /Users/koic/src/github.com/koic/rubocop-issues/7253: configuration
from /Users/koic/src/github.com/koic/rubocop-issues/.rubocop.yml
configuration from
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rubocop-performance-1.4.1/config/default.yml
configuration from
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rubocop-performance-1.4.1/config/default.yml
Default configuration from
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rubocop-0.73.0/config/default.yml
configuration from …
```
=> [Fix #7253] Fix an error for `Lint/NumberConversion`

CHANGELOG.md, lib/rubocop/cop/naming/variable_name.rb, spec/rubocop/cop/naming/variable_name_spec.rb
Fixes #7275.
This PR makes `Style/VariableName` aware of argument names when invoking a method.
=> [Fix #7275] Fix a false negative for `Style/VariableName`

lib/rubocop/cop/generator.rb, spec/rubocop/cop/generator_spec.rb
This PR suppresses `Style/RedundantFreeze` warning for new cop generated by `rake new_cop` task.
=> Suppress `Style/RedundantFreeze` warning for new cop

manual/extensions.md
Cookstyle is a wrapper around Rubocop that provides a customized config and a set of Chef Infra cookbook specific cops.
=> Add Cookstyle to the list of custom cops

CHANGELOG.md, lib/rubocop/cop/correctors/multiline_literal_brace_corrector.rb, spec/rubocop/cli/cli_autocorrect_spec.rb
This fixes #7271 and closes #6498 as well.
The problem during auto-correction was that both cops were inserting _after_ the last item of the array or hash: one was inserting a comma, the other the closing brace – and those might come out in the wrong order.
The solution is to still let them insert in the same location, but in different directions: The comma is inserted _after_ the last item and the brace _before_ the characters following the last item. That way, the comma always precedes the closing brace.
=> [Fix #7271] Correct multiline braces and trailing commas together

spec/rubocop/cop/lint/big_decimal_new_spec.rb, spec/rubocop/cop/lint/deprecated_class_methods_spec.rb, spec/rubocop/cop/lint/empty_ensure_spec.rb, spec/rubocop/cop/lint/empty_interpolation_spec.rb, spec/rubocop/cop/lint/inherit_exception_spec.rb, spec/rubocop/cop/lint/ordered_magic_comments_spec.rb, spec/rubocop/cop/lint/percent_string_array_spec.rb, spec/rubocop/cop/lint/percent_symbol_array_spec.rb, spec/rubocop/cop/lint/redundant_with_index_spec.rb, spec/rubocop/cop/lint/redundant_with_object_spec.rb, spec/rubocop/cop/lint/safe_navigation_consistency_spec.rb, spec/rubocop/cop/lint/string_conversion_in_interpolation_spec.rb, spec/rubocop/cop/lint/to_json_spec.rb, spec/rubocop/cop/lint/unneeded_cop_enable_directive_spec.rb, spec/rubocop/cop/lint/unneeded_require_statement_spec.rb, spec/rubocop/cop/lint/uri_regexp_spec.rb, spec/rubocop/cop/metrics/line_length_spec.rb, spec/rubocop/cop/security/json_load_spec.rb, spec/rubocop/cop/security/yaml_load_spec.rb
This covers the easy to convert tests from metrics, security, and lint. There will be more changes to come.
=> Convert some tests to use expect_correction

.rubocop_todo.yml, CHANGELOG.md, lib/rubocop/config_loader.rb, spec/rubocop/config_loader_spec.rb
It causes unexpected cop warnings because treats as truthy value if passed neither true nor false in 'Enabled' key's value like "Enabled: disable".  
Our team occurred a problem that, unexpected  cop was in effect.
The cause was the wrong config value like an "Enabled: disabled".
=> Show warning message if passed string to 'Enabled' key in .rubocop.yml

CHANGELOG.md, lib/rubocop/cop/mixin/safe_mode.rb
Discussion in https://github.com/rubocop-hq/rubocop-performance/pull/72. It looks like `Performance/Count` and `Performance/Detect` were the only cops making use of the `SafeMode` feature. Rather than disabling the cops from running, we have flagged them as unsafe for auto-correction.
This will need to wait until the change is merged into RuboCop-Performance, and a new version of the gem is released.
=> Deprecate the SafeMode module

CHANGELOG.md, lib/rubocop/config.rb, lib/rubocop/cop/cop.rb, lib/rubocop/cop/message_annotator.rb, manual/configuration.md, spec/rubocop/cop/message_annotator_spec.rb, tasks/cops_documentation.rake
Resolves https://github.com/rubocop-hq/rubocop-rails/issues/107 and follow up https://github.com/rubocop-hq/rubocop-rails/pull/109#issuecomment-521983107.
This PR makes it possible to set a style guide URL (`StyleGuideBaseURL`) for each department.
For example, RuboCop Rails gem (Rails department) supports The Rails Style Guide. In that case, set .rubocop.yml as follows.
```yaml
require:
- rubocop-rails
AllCops:
StyleGuideBaseURL:  https://rubystyle.guide
Rails:
StyleGuideBaseURL:  https://rails.rubystyle.guide
```
In practice `Rails: StyleGuideBaseURL: https://rails.rubystyle.guide` will be set in config/default.yml of rubocop-rails.
```console
time = Time.new
```
```console
% bundle exec rubocop --display-style-guide example.rb
W
Offenses: …
```
=> Make it possible to set StyleGuideBaseURL per department

CHANGELOG.md, lib/rubocop/cop/mixin/frozen_string_literal.rb, lib/rubocop/magic_comment.rb, spec/rubocop/cop/style/frozen_string_literal_comment_spec.rb
=> [Fix #7241] Make `Style/FrozenStringLiteralComment` match only true & false

CHANGELOG.md, lib/rubocop/cop/style/conditional_assignment.rb, spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb
Handle inner conditional inside else.
An inner conditional such as
```ruby
if cond1
a = 1
else
if cond2
a = 2
end
end
```
was not correctly handled. It should not be treated as an `elsif`, because it is an `else` and there's special logic for `else` branches.
=> Fix ConditionalAssignment auto-correct

spec/rubocop/cli/cli_autocorrect_spec.rb, spec/rubocop/cli/cli_disable_uncorrectable_spec.rb, spec/rubocop/cli_spec.rb, spec/rubocop/cop/layout/align_arguments_spec.rb, spec/rubocop/cop/layout/empty_lines_around_begin_body_spec.rb, spec/rubocop/cop/layout/empty_lines_around_exception_handling_keywords_spec.rb, spec/rubocop/cop/layout/extra_spacing_spec.rb, spec/rubocop/cop/layout/indent_first_argument_spec.rb, spec/rubocop/cop/layout/indent_first_hash_element_spec.rb, spec/rubocop/cop/layout/indentation_width_spec.rb, spec/rubocop/cop/layout/space_around_operators_spec.rb, spec/rubocop/cop/layout/space_inside_string_interpolation_spec.rb, spec/rubocop/cop/layout/tab_spec.rb, spec/rubocop/cop/lint/empty_interpolation_spec.rb, spec/rubocop/cop/lint/literal_in_interpolation_spec.rb, spec/rubocop/cop/lint/string_conversion_in_interpolation_spec.rb, spec/rubocop/cop/style/character_literal_spec.rb, spec/rubocop/cop/style/command_literal_spec.rb, spec/rubocop/cop/style/format_string_spec.rb, spec/rubocop/cop/style/hash_syntax_spec.rb, spec/rubocop/cop/style/line_end_concatenation_spec.rb, spec/rubocop/cop/style/regexp_literal_spec.rb, spec/rubocop/cop/style/string_literals_in_interpolation_spec.rb, spec/rubocop/cop/style/string_literals_spec.rb, spec/rubocop/cop/style/unneeded_interpolation_spec.rb, spec/rubocop/cop/style/variable_interpolation_spec.rb, spec/rubocop/cop/team_spec.rb
https://github.com/jruby/jruby/issues/4260 has been resolved and JRuby 9.2.8.0  is available on CircleCI.
https://hub.docker.com/r/circleci/jruby/tags
```console
% docker run --rm -it circleci/jruby:9.2
Unable to find image 'circleci/jruby:9.2' locally
9.2: Pulling from circleci/jruby
9cc2ad81d40d: Pull complete
e6cb98e32a52: Pull complete
ae1b8d879bad: Pull complete
2383fa4462e7: Pull complete
7ac3ce9f2067: Pull complete
ce9a16d8ddcb: Pull complete
b250e79d9c7f: Pull complete
ce3b7f0ecca6: Pull complete
2405779516de: Pull complete
902dc7b355a1: Pull complete
432a6994cb77: Pull complete
66a081bddadb: Pull complete
1576af617cb5: Pull complete
4233b310ce28: Pull complete
51c0ac4a73c0: Pull complete
c43fdb6f1fe8: Pull complete
909d5a0f7f69: Pull complete
940e076596c5: Pull complete …
```
=> Use squiggly heredoc instead of strip_indent

CHANGELOG.md, lib/rubocop/cop/layout/multiline_block_layout.rb, lib/rubocop/cop/layout/space_around_block_parameters.rb, manual/cops_layout.md, spec/rubocop/cop/layout/multiline_block_layout_spec.rb, spec/rubocop/cop/layout/space_around_block_parameters_spec.rb
This fixes #5788, which talks about auto-correct introducing `Metrics/LineLength` offenses. I took the approach of changing, not only auto-correct, but the reporting of the offense. Parameter lists that would be too long for one line are just left alone.
The `Layout/SpaceAroundBlockParameters` cop had to be updated too, if we're to accept these parameter lists with line breaks in them.
=> Allow split parameters that would not fit on one line in MultilineBlockLayout

lib/rubocop/cop/style/rescue_modifier.rb, manual/cops_style.md
fixes #7289 
Adds a description to the cop specifying the reason for not using modifier form rescue. The reasons are similar to the ones mentioned in the https://thoughtbot.com/blog/don-t-inline-rescue-in-ruby blog.
=> Added description for RescueModifier cop explaining reasons for not to use modifier form rescue

spec/rubocop/cop/lint/script_permission_spec.rb
This reverts commit 4b632c416456bad003d18812dc3c1ee1095bf9f5.
Parser got fixed in the meantime.
=> Revert "Tweak test to avoid issue with Parser 2.5.0.2."

CHANGELOG.md, lib/rubocop/cop/lint/debugger.rb, spec/rubocop/cop/lint/debugger_spec.rb
The `byebug` gem [added a method](https://github.com/deivid-rodriguez/byebug/releases/tag/v10.0.0)  called `remote_byebug` for triggering breakpoints in ruby code running remotely. This PR makes the `Debugger` cop fail if it finds a call to `remote_byebug`. 
=> Add check for calls to remote_byebug to Lint/Debugger Cop.

CHANGELOG.md, lib/rubocop/cop/style/block_delimiters.rb, spec/rubocop/cop/style/block_delimiters_spec.rb
Update Style/BlockDelimiters to handle attribute assignment.
Fixes #7305 by recognizing that blocks as arguments of assignment methods can safely be mutated from one block delimiter style to the other.
=> Register BlockDelimiters offense with attribute assignment

CHANGELOG.md, lib/rubocop/cop/style/if_unless_modifier.rb, manual/cops_style.md, spec/rubocop/cop/style/if_unless_modifier_spec.rb
Make `Style/IfUnlessModifier` work in two directions. Apart from the already existing reporting of `if`/`unless` expressions on normal form that could be changed to modifier form, we add reporting and correcting of modifier form `if`/`unless` expressions that make the line too long and should be written on normal form.
It could be argued that `Metrics/LineLength` should be responsible for reporting and correcting lines that are too long, but I think it's easier to put this logic in `Style/IfUnlessModifier`.
=> [Fix #3534] Report long modifier lines in IfUnlessModifier

CHANGELOG.md, config/default.yml, manual/cops_style.md
- We noticed that this auto-correction by this cop can cause bugs
where strings are explicitly expected as hash keys.
=> Mark Style/StringHashKeys as unsafe

lib/rubocop/cop/mixin/safe_mode.rb
We have received a couple of questions about this in https://github.com/rubocop-hq/rubocop/pull/7249. If there is a plan to release a minor or revision update, we may want to include this.
`rubocop-performance` hasn't created their 1.5.0 release yet. Maybe it would be easier for that version to jump to 1.15.0 🤣
=> Fix the warning message about which version of rubocop-performance to upgrade to

CHANGELOG.md, config/default.yml, lib/rubocop.rb, lib/rubocop/cop/lint/format_parameter_mismatch.rb, lib/rubocop/cop/style/format_string_token.rb, lib/rubocop/cop/utils/format_string.rb, manual/cops_style.md, spec/rubocop/cop/lint/format_parameter_mismatch_spec.rb, spec/rubocop/cop/style/format_string_token_spec.rb, spec/rubocop/cop/utils/format_string_spec.rb
This extracts and unifies the format string parsing from two different cops. As a consequence, `Style/FormatStringToken` is now able to inspect more variants of format sequences.
I didn't really know where to best put the `FormatString` class, so I am open for suggestions. Maybe there is a place for such auxiliary classes that I overlooked.
=> [Fix #7091] Extract FormatString parser

CHANGELOG.md, lib/rubocop/cop/style/frozen_string_literal_comment.rb, spec/rubocop/cli/cli_autocorrect_spec.rb, spec/rubocop/cli/cli_disable_uncorrectable_spec.rb, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/cli_spec.rb, spec/rubocop/cop/style/frozen_string_literal_comment_spec.rb, spec/rubocop/cop/team_spec.rb
`FrozenStringLiteralComment` should only be concerned about inserting/removing the magic comment as necessary but not about its spacing. So it should never insert empty lines.
The spacing is the responsibility of `EmptyLineAfterMagicComment`.
This closes #7261.
The change itself was pretty straightforward but I was surprised how much impact it had on other specs, especially on `cli_autocorrect_spec.rb` although the examples there mostly did not care at all about how `FrozenStringLiteralComment` works. By adding a lot of `--only`s I tried to restrict these examples to the cops they really need (if possible) such that they will not be affected by similar changes in the future.
=> [Fix #7261] Do not insert empty lines in FrozenStringLiteralComment

CHANGELOG.md, lib/rubocop/config_loader.rb
[Fix #7321]
As described in detail in the above issue, disallowing YAML aliasing can force unnecessary repetition in the `.rubocop.yml` file. This PR sets `aliases: true` in the `YAML.safe_load` call, so that users can use YAML aliases in their `.rubocop.yml`.
=> Allow YAML aliases In Configuration

CHANGELOG.md, config/default.yml, lib/rubocop/cop/naming/method_name.rb, manual/cops_naming.md, spec/rubocop/cop/naming/method_name_spec.rb
Resolves #6075.
This PR supports `IgnoredPatterns` option for `Naming/MethodName`.
```yaml
Naming/MethodName:
IgnoredPatterns:
- '\A\s*onSelectionBulkChange\s*'
- '\A\s*onSelectionCleared\s*'
```
Method names matching patterns are always allowed, both `EnforcedStyle: snake_case` and `EnforcedStyle: camelCase`.
=> [Fix #6075] Support `IgnoredPatterns` option for `Naming/MethodName`

lib/rubocop/config_loader_resolver.rb
Recent builds fail for ruby-head. A new warning that's been added in ruby-head says:
```
The last argument is used as the keyword parameter
```
This warning is emitted when a method parameter is declared with a double asterisk, e.g.,
```
def some_method(arg, **opts)
```
but a call does not use double asterisk, e.g.,
```
x = some_method(my_arg, my_opts)
```
=> Fix new warnings from Ruby

CHANGELOG.md, lib/rubocop/runner.rb, spec/rubocop/cli/cli_autocorrect_spec.rb
After all other cops are finished we invoke the `Lint/UnneededCopDisableDirective` cop, since it depends on the results of the other cops. If it's an `--auto-correct` run, correcting `UnneededCopDisableDirective` offenses can introduce new `UnneededCopEnableDirective` offenses. For this reason we must do one more inspection after `UnneededCopDisableDirective` has corrected a file.
=> [Fix #4802] Detect all UnneededCopEnableDirective offenses

CHANGELOG.md, lib/rubocop/cop/style/access_modifier_declarations.rb, spec/rubocop/cop/style/access_modifier_declarations_spec.rb
Fixes #7326.
This PR fixes a false positive for `Style/AccessModifierDeclarations` when access modifier name is used for hash literal value.
=> [Fix #7326] Fix a false positive for `Style/AccessModifierDeclarations`

CHANGELOG.md, lib/rubocop/cop/style/safe_navigation.rb, spec/rubocop/cop/style/safe_navigation_spec.rb
=> [Fix #7161] Fix `Style/SafeNavigation` cop to preserve comments

.rubocop.yml, lib/rubocop/config_obsoletion.rb, lib/rubocop/cop/mixin/safe_mode.rb
Related https://github.com/rubocop-hq/rubocop/pull/7249.
In #7249, the following deprecation  warning is displayed for all operations of `rubocop` command.
```console
% bundle exec rubocop -v
The `SafeMode` option will be removed in `RuboCop` 0.76. Please update
`rubocop-performance` to 1.5.0 or higher.
0.74.0
```
I noticed that with the `ConfigObsolete` module, RuboCop can only show the warning when using `SafeMode`.
```console
require: rubocop-performance
Performance/Count:
SafeMode: false
Error: obsolete parameter SafeMode (for Performance/Count) found in .rubocop.yml
`SafeMode` has been removed. Use `SafeAutoCorrect` instead.
```
OTOH, RuboCop Performance happens the following error when `SafeMode` module will removed:
```console
NameError: …
```
=> Change warning location of `SafeMode`

CHANGELOG.md, lib/rubocop/cop/variable_force/variable.rb, spec/rubocop/cop/lint/useless_assignment_spec.rb
Assignments in modifier if/unless conditions are special. The following program
exits with the error "undefined local variable or method `a' for main:Object"
when executed.
```
puts a if (a = @x)
```
A preceding assignment to `a` is needed to put it in scope. So there are no
useless assignments in
```
a = nil
puts a if (a = @x)
```
=> [Fix #3591] Handle modifier if in Variable#reference!()

lib/rubocop/cop/style/frozen_string_literal_comment.rb, manual/cops_style.md
Closes #7332.
This PR updates a description to Ruby version where frozen string literals will be introduced.
AFAIK, matz has not given up the possibility of defaulting to a frozen string in the future. In Ruby 3.0, matz was abandant for changing it because there were not enough tools to prevent destructive changes (I heard that at RubyKaigi 2019 and RubyConf Taiwan 2019).
Frozen string literals are being introduced around Ruby.
- https://github.com/ruby/ruby/blob/master/lib/erb.rb
- https://github.com/ruby/psych
- https://github.com/ruby/csv
- https://github.com/rubygems/rubygems
- https://github.com/bundler/bundler
- others
So this cop remains enabled by default.
cf. https://bugs.ruby-lang.org/issues/11473#note-53 …
=> [Fix #7332] Update doc for `Style/FrozenStringLiteralComment`

CHANGELOG.md, lib/rubocop/cop/style/braces_around_hash_parameters.rb, spec/rubocop/cop/style/braces_around_hash_parameters_spec.rb
Users are getting false positives saying that hash braces should be removed although doing so would change semantics for a block with `do`..`end`. We fix the false positive by allowing the braces in this particular case.
=> [Fix #5212] Allow braces around block with do..end

lib/rubocop/cop/lint/assignment_in_condition.rb, lib/rubocop/cop/style/parentheses_around_condition.rb, lib/rubocop/cop/style/ternary_parentheses.rb, manual/cops_lint.md, manual/cops_style.md
This is only document change.
This commit adds examples of `AllowSafeAssignment` option for `Lint/AssignmentInCondition` cop, `Style/ParenthesesAroundCondition` cop, and `Style/TernaryParentheses` cop.
=> Add examples of `AllowSafeAssignment` option

CHANGELOG.md, lib/rubocop/cop/style/redundant_self.rb, spec/rubocop/cop/style/redundant_self_spec.rb
Fixes #7353.
This PR fixes a false positive for `Style/RedundantSelf` when receiver and multiple assigned lvalue have the same name.
=> [Fix #7353] Fix a false positive for `Style/RedundantSelf`

lib/rubocop/cop/generator/configuration_injector.rb, spec/rubocop/cop/generator_spec.rb
It generates invalid YAML if the new cop is named the last in alphabetical order.
```bash
$ bundle exec rake 'new_cop[Zzz/Zzz]'
(snip)
$ tail config/default.yml
Description: 'Use #empty? when testing for objects of length 0.'
Enabled: true
Safe: false
VersionAdded: '0.37'
Zzz/Zzz:
Description: 'TODO: Write a description of the cop.'
Enabled: true
VersionAdded: '0.75'
VersionChanged: '0.39'
```
`VersionChanged` on the last line is not for `Zzz/Zzz` cop, but it is put under `Zzz/Zzz` cop accidentally.
This pull request will fix the problem.
----------------- 
=> Fix new_cop task to avoid generating invalid YAML for the config file

CHANGELOG.md, lib/rubocop/cop/style/nested_modifier.rb, spec/rubocop/cop/style/nested_modifier_spec.rb
Fixes #7358.
This PR fix an incorrect autocorrect for `Style/NestedModifier` when parentheses are required in method arguments.
=> [Fix #7358] Fix an incorrect autocorrect for `Style/NestedModifier`

CHANGELOG.md, lib/rubocop/cop/style/ternary_parentheses.rb, spec/rubocop/cop/style/ternary_parentheses_spec.rb
Fixes #7361.
This PR fixes a false positive for `Style/TernaryParentheses` when only the closing parenthesis is used in the last line of condition.
It prevents the following syntax errors caused by auto-correction:
```ruby
(
foo || bar
) ? a : b
```
```console
% rubocop --only Style/TernaryParentheses -a
```
The following autocorrected code has a syntax error.
```ruby
foo || bar
? a : b
```
```console
example.rb:3: warning: invalid character syntax; use ?\s
example.rb:3: syntax error, unexpected '?', expecting end-of-input
? a : b
```
For example, it accepts parentheses to be used when a conditional is a long line.
=> [Fix #7361] Fix a false positive for `Style/TernaryParentheses`

lib/rubocop/cop/offense.rb
Remove redundant aliasing of the corrected? and corrected_with_todo? method.
=> remove alias to corrected methods

CHANGELOG.md, lib/rubocop/cop/layout/indent_assignment.rb, spec/rubocop/cop/layout/indent_assignment_spec.rb
Fixes #7369.
This PR fixes an infinite loop error for `Layout/IndentAssignment` with `Layout/IndentFirstArgument` when using multiple assignment.
```console
a.b = a.c =
e = ''
```
```console
% rubocop --auto-correct --only Layout/IndentAssignment,Layout/IndentFirstArgument
C
Offenses:
example.rb:2:3: C: [Corrected] Layout/IndentAssignment: Indent the first
line of the right-hand-side of a multi-line assignment.
e = ''
^^^^^^
example.rb:2:9: C: [Corrected] Layout/IndentFirstArgument: Indent
the first argument one step more than the start of the previous line.
e = ''
^^^^^^
0 files inspected, 2 offenses detected, 2 offenses corrected
/Users/koic/src/github.com/koic/rubocop-issues/7369/example.rb. …
```
=> [Fix #7369] Fix an infinite loop error for `Layout/IndentAssignment`

CHANGELOG.md, config/default.yml, manual/cops_style.md
Resolves #7345.
This PR marks unsafe for `Style/YodaCondition`.
A Ruby committer @knu says "Reversing operands is an unsafe modification in Ruby and can easily break existing code that is written for a reason". Thank you.
=> [Fix #7345] Mark unsafe for `Style/YodaCondition`

config/default.yml, lib/rubocop.rb, lib/rubocop/cop/layout/closing_parenthesis_indentation.rb, lib/rubocop/cop/layout/indent_heredoc.rb, lib/rubocop/cop/migration/department_name.rb, lib/rubocop/cop/mixin/alignment.rb, lib/rubocop/cop/registry.rb, lib/rubocop/cop/style/class_and_module_children.rb, lib/rubocop/cop/style/infinite_loop.rb, lib/rubocop/cop/style/multiline_memoization.rb, manual/cops.md, manual/cops_migration.md, spec/rubocop/cli/cli_autocorrect_spec.rb, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/cli_spec.rb, spec/rubocop/comment_config_spec.rb, spec/rubocop/cop/generator_spec.rb, spec/rubocop/cop/lint/unneeded_cop_disable_directive_spec.rb, spec/rubocop/cop/metrics/line_length_spec.rb, spec/rubocop/cop/migration/department_name_spec.rb, spec/rubocop/cop/registry_spec.rb
Ever since departments (namespaces) were introduced, or almost since then, it's been possible to give cop names on the command line, in configuration and in `rubocop:disable` comments without a preceding department name. RuboCop deduces what the department should be and errors out only if it doesn't find exactly one matching department.
The optional department functionality was added as a way to stay backwards compatible with configuration that was created before departments existed. But the grace period is coming to an end. We start now by issuing warnings whenever cop names without departments are encountered. Later on, in a future version, we will remove the department deduction functionality and require that departments always be given for cop names.
**Note:** Warnings about …
=> Deprecate departmentless cop names

lib/rubocop/cop/style/single_line_methods.rb, manual/cops_style.md
This PR adds exmaple of `AllowIfMethodIsEmpty` option for `Style/SingleLineMethods`.
=> Add exmaple of `AllowIfMethodIsEmpty` option

CHANGELOG.md, lib/rubocop/cop/correctors/alignment_corrector.rb, spec/rubocop/cop/alignment_corrector_spec.rb, spec/support/cops/alignment_directive.rb
This fixes #7177 and fixes #7370.
There was a bug in the `AlignmentCorrector` used by many cops to shift pieces of code to the left or right: The corrector already knew not to touch the contents of some heredocs, but was not aware that the contents of other string literals must not be changed either. So it happily inserted or removed leading spaces inside string literals.
I started by writing some specs for the `AlignmentCorrector` because there were none and that class was only implicitly covered by specs in the cops that use the corrector.
While doing that I stumbled across a few bugs/shortcomings in the heredoc handling and fixed them straight away. Finally it felt safe enough to teach the corrector to recognize and avoid regular string literals.
In order to exercise the …
=> [Fix #7177] Do not insert spaces into string literals when aligning

CHANGELOG.md, lib/rubocop/cop/style/or_assignment.rb, spec/rubocop/cop/style/or_assignment_spec.rb
Fixes #7367.
This PR fixes an error for `Style/OrAssignment` cop when `then` branch body is empty.
=> [Fix #7367] Fix an error for `Style/OrAssignment`

manual/development.md
Added single quotes around new cop examples in the development readme.
Zshell requires the quotes and bash still understands them correctly. So this makes the examples a bit more universal.
=> Added single quotes around new cop examples.

CHANGELOG.md, lib/rubocop/ast/node/mixin/method_dispatch_node.rb, lib/rubocop/cop/style/mixin_usage.rb, spec/rubocop/cop/layout/empty_lines_around_access_modifier_spec.rb, spec/rubocop/cop/lint/useless_access_modifier_spec.rb
Fixes #7212.
Fixes #7246.
This PR fixes a false positive for `Layout/EmptyLinesAroundAccessModifier` and `UselessAccessModifier` when using method with the same name as access modifier around a method definition.
The main changes are as follows.
- Added test for where #7194 change did not find a regression.
- The implementation needed to resolve #7186 will be moved to `Style/MixinUsage` cop. This solves false positives that occurred in other cops.
=> [Fix #7212] Fix a false positive for `Layout/EmptyLinesAroundAccessModifier`

CHANGELOG.md, lib/rubocop/cop/layout/space_inside_block_braces.rb, spec/rubocop/cli/cli_autocorrect_spec.rb, spec/rubocop/cop/layout/space_inside_block_braces_spec.rb
Fixes #7363.
This PR fixes an incorrect autocorrect for `Layout/SpaceInsideBlockBraces` and `Style/BlockDelimiters` when using multiline empty braces.
As a result of applying the two auto-corrections, the code is converted to have the following syntax error code:
```console
do_something {
}
% rubocop --auto-correct --only Style/BlockDelimiters,Layout/SpaceInsideBlockBraces
do_something doend
```
`doend` is because `Layout/SpaceInsideBlockBraces` cop auto-corrects to single-line empty braces:
```console
% rubocop --auto-correct --only Layout/SpaceInsideBlockBraces
do_something {}
```
and `Style/BlockDelimiters` auto-corrects to `do` ... `end`.
```console
% rubocop --auto-correct --only Style/BlockDelimiters
do_something do …
```
=> [Fix #7363] Fix an incorrect autocorrect when multiline empty braces

lib/rubocop/cop/style/method_call_with_args_parentheses.rb, manual/cops_style.md
Follow up of https://github.com/rubocop-hq/rubocop/pull/4880#issuecomment-338499947.
This PR is a change of document format for `Style/MethodCallWithArgsParentheses` cop.
=> Restyle example formatting for `Style/MethodCallWithArgsParentheses`

CHANGELOG.md, manual/basic_usage.md
Within the Basic Usage page, make a brief mention of the use of `.rubocop.yml` to change RuboCop's behaviour. The additional content links to the **Configuration** page to go into more detail.
Fixes #6759.
=> [Fix #6759] Reference configuration in Basic Usage

lib/rubocop/cop/lint/void.rb, manual/cops_lint.md
This PR is a change of document format for `Lint/Void` cop.
=> Restyle example formatting for `Lint/Void`

CHANGELOG.md, mkdocs.yml
The official documentation of Rubocop only list the known extensions in the [Extensions 
section of the documentation](http://docs.rubocop.org/en/stable/extensions/#known-custom-cops). I know by experience that it can be difficult to find the cops documentation of those extensions since there is not mention of the manual folder in the `README.md` of the extension  (maybe we can just do this) or in the official documentation.
So I started this PR by basically putting a link to the cops documentation file of each _rubocop-hq_ extensions.
**I pretty sure there is a more elegant way to do this and I'll be pleased to hear any suggestions and the preferences of others**
=> Add Extensions Cops Documentation references in the official docs.

CHANGELOG.md, lib/rubocop/cop/style/format_string_token.rb, spec/rubocop/cop/style/format_string_token_spec.rb
This fixes #7407 by improving upon earlier attempts at avoiding false
positives: Strings that look like format strings in the `unannotated`
style (with simple format sequences such as `%a`) can as well be
something else depending on the context (e.g. date/time formats, encoded
URLs).
The documentation of the cop has long had a note about in which typical
contexts such strings are considered format strings. This is now
reflected in a node matcher in the code.
=> [Fix #7407] Better detect typical format string contexts

CHANGELOG.md, lib/rubocop/cop/style/format_string_token.rb, lib/rubocop/formatter/clang_style_formatter.rb, lib/rubocop/formatter/emacs_style_formatter.rb, lib/rubocop/formatter/file_list_formatter.rb, lib/rubocop/formatter/pacman_formatter.rb, lib/rubocop/formatter/simple_text_formatter.rb, lib/rubocop/formatter/tap_formatter.rb, manual/cops_style.md
The cop `Style/FormatStringToken` used to treat `sprintf`, `format`, and `%` methods as typical use cases of `printf`-style format strings, but ironically not the `printf` method itself.
This fixes #7410.
=> [Fix #7410] Add printf as a typical format string context

CHANGELOG.md, lib/rubocop/formatter/formatter_set.rb, lib/rubocop/options.rb, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/formatter/formatter_set_spec.rb, spec/rubocop/options_spec.rb
Fixed an issue where passing a formatter alias which started with the
same character as another caused an error.
Specifically, passing in `-f p` caused an error as this matched
both 'pacman' and 'progress' in
Rubocop:: Formatter::FormatterSet::BUILTIN_FORMATTERS_FOR_KEYS
=> [Fix #7389] Ambiguous formatter matching

CHANGELOG.md, lib/rubocop/formatter/pacman_formatter.rb
Removed `tput` from packman formatter and replaced with `IO#winsize` because `tput` is a *nix only command
Fixes #7391 
=> [Fix #7391] Use IO#winsize for Windows compatibility

lib/rubocop/cop/correctors/percent_literal_corrector.rb
Since https://github.com/ruby/ruby/pull/2437, `Symbol#to_s` returns frozen string.
PercentLiteralCorrector uses `Symbol#to_s` and `String#gsub!`. So the corrector raises an error for SymbolArray cop spec.
```
FrozenError:
can't modify frozen String: "bar"
```
This pull request fixes the problem.
I'm not sure I should write a changelog entry, because this change is only for ruby 2.7-dev.
I think we can omit it. This change does not affect most people yet.
=> Fix PercentLiteralCorrector with Ruby 2.7-dev

manual/extensions.md
This pull request adds [rubocop-rake](https://github.com/rubocop-hq/rubocop-rake) to the extension list.
I'd like to get more cop ideas and contributions to rubocop-rake by adding it to the list.
=> Add rubocop-rake to the extension list

.rubocop.yml
In the project's `.rubocop.yml` we overwrite the default
`AllCops/Exclude` and do not exclude `.git`.
On my machine fixing this saves 1 of 3 seconds for a simple `rubocop
--list-target-files`.
=> Exclude .git from internal investigation

CHANGELOG.md, lib/rubocop/cop/style/safe_navigation.rb, spec/rubocop/cop/style/safe_navigation_spec.rb
This fixes #7397 
When moving comments around, the original implementation failed to limit the comments to the section of code being analyzed. It was pulling the comments for the entire file.
=> [Fix #7397] Fix issue where Style/SafeNavigation adds extra comments

CHANGELOG.md, lib/rubocop/cop/layout/empty_line_after_guard_clause.rb, spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb
If you'd call a method on a heredoc string the cop couldn't
recognize that a heredoc is passed. The same happened if the heredoc was
given to a method, the result of which is passed as a value in another
call.
Here are the two examples:
```ruby
def foo
raise ArgumentError, <<~END.squish.it.good unless guard
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Add empty line after guard clause.
A multiline message
that will be squished.
END
return_value
end
```
```ruby
def foo
raise ArgumentError, call(<<~END.squish) unless guard
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Add empty line after guard clause.
A multiline message
that will be squished.
END
return_value
end
```
=> Fix heredoc edge cases in Layout/EmptyLineAfterGuardClause

Gemfile, lib/rubocop/cop/layout/empty_line_after_magic_comment.rb, lib/rubocop/cop/style/expand_path_arguments.rb
RuboCop Performance 1.5.0 has been released.
https://github.com/rubocop-hq/rubocop-performance/releases/tag/v1.5.0
This PR bumps RuboCop Performance to 1.5.0 and suppresses the following new offenses.
```console
(snip)
lib/rubocop/cop/layout/empty_line_after_magic_comment.rb:58:14: C:
Performance/Detect: Use reverse.find instead of select.last.
.select     { |comment| MagicComment.parse(comment.text).any?  }
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/rubocop/cop/style/expand_path_arguments.rb:163:17: C:
Performance/Count: Use count instead of reject...count.
paths.reject { |path| path == '.' }.count
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
[1]: …
=> Bump RuboCop Performance to 1.5.0

lib/rubocop/cop/lint/unused_block_argument.rb, manual/cops_lint.md
This PR adds examples for `Lint/UnusedBlockArgument`.
=> Add examples for `Lint/UnusedBlockArgument`

CHANGELOG.md, lib/rubocop/cop/layout/indent_assignment.rb, spec/rubocop/cop/layout/indent_assignment_spec.rb
Fixes #7404.
This PR fixes a false negative for `Layout/IndentAssignment` when multiple assignment with line breaks on each line.
=> [Fix #7404] Fix a false negative for `Layout/IndentAssignment`

CHANGELOG.md, config/default.yml, manual/cops_metrics.md, spec/rubocop/config_loader_spec.rb
As described in #6964, including cop directives in the line length calculation causes long comments to push otherwise good code in an awkward direction. This PR changes the default value of `IgnoreCopDirectives` to `true` for `Metrics/LineLength`, which should remove some noisy warnings. In particular, this will prevent rubocop from discouraging single-line cop directives where they make sense.
=> [Fix #6964] Set default `IgnoreCopDirectives` to `true` for `Metrics/LineLength`

CHANGELOG.md, lib/rubocop/cop/style/format_string_token.rb, spec/rubocop/cop/style/format_string_token_spec.rb
`%%` is technically a format sequence in the `unannotated` style. But it
cannot be written in another style in a sensible way.
This closes #7439.
=> [Fix #7439] Ignore percent escapes

CHANGELOG.md, lib/rubocop/cop/layout/multiline_assignment_layout.rb, spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb
Assignments from `:[]=` or setter methods (`foo.bar=(value)`) like the ones below did not produce cop reports and were not autocorrected. Now, they are!
```ruby
hash[:foo] = if true
^^^^^^^^^^^^^^^^^^^^ Right hand side of multi-line assignment is on the same line as the assignment operator `=`.
end
```
```ruby
foo.bar = if true
^^^^^^^^^^^^^^^^^^^^ Right hand side of multi-line assignment is on the same line as the assignment operator `=`.
end
```
=> Fix assignment edge-cases in Layout/MultilineAssignmentLayout

lib/rubocop/cop/style/frozen_string_literal_comment.rb, manual/cops_style.md
=> Document support for frozen_string_literal: false

CHANGELOG.md, lib/rubocop/cop/style/if_unless_modifier.rb, spec/rubocop/cop/style/if_unless_modifier_spec.rb
A bug was discovered in https://github.com/rubocop-hq/rubocop/pull/7308#issuecomment-544236793
When `Style/IfUnlessModifier` decides that a line on modifier form is too long and that it should be written on normal form, it must respect comments that disable the `Metrics/LineLength` cop for the line in question. If that cop is disabled, then there can be no offense.
=> Make IfUnlessModifier respect rubocop:disable comments

CHANGELOG.md, lib/rubocop/cop/lint/void.rb
Fixes #7446
Now, if `merge` is used in a void context, the `Lint/Void` cop will
register an offense and the mutating `merge!` method will be suggested.
=> [Fix #7446] Add `merge` to `NONMUTATING_METHODS`

CHANGELOG.md, lib/rubocop/cop/style/safe_navigation.rb, spec/rubocop/cop/style/safe_navigation_spec.rb
Fixes #7442.
This PR fixes an incorrect autocorrect for `Style/SafeNavigation` when an object check followed by a method call with a comment at EOL.
=> [Fix #7442] Fix an incorrect autocorrect for `Style/SafeNavigation`

CHANGELOG.md, lib/rubocop/cop/style/multiline_when_then.rb, spec/rubocop/cop/style/multiline_when_then_spec.rb
Fixes #7434.
This PR fixes an incorrect autocorrect for `Style/MultilineWhenThen` when the body of `when` branch starts with `then`.
The following is a reproduction procedure.
```console
case foo
when bar
then do_something
end
```
```
Syntax OK
```
```console
% rubocop example.rb
C
Offenses:
example.rb:5:3: C: Style/MultilineWhenThen: Do not use then for
multiline when statement.
then do_something
^^^^
```
It is changed to the code with syntax error as follows.
```ruby
case foo
when bar do_something
end
```
```console
example.rb:4: syntax error, unexpected tIDENTIFIER, expecting do or '{'
or '('
when bar do_something
```
```console
% rubocop example.rb -a
C
Offenses:
example.rb:5:1: C: …
```
=> [Fix #7434] Fix an incorrect autocorrect for `Style/MultilineWhenThen`

lib/rubocop/cli.rb, lib/rubocop/config.rb, lib/rubocop/config_loader.rb, lib/rubocop/config_loader_resolver.rb, lib/rubocop/config_validator.rb, lib/rubocop/cop/commissioner.rb, lib/rubocop/cop/layout/end_of_line.rb, lib/rubocop/cop/layout/indent_first_argument.rb, lib/rubocop/cop/naming/file_name.rb, lib/rubocop/cop/style/copyright.rb, lib/rubocop/cop/style/format_string.rb, lib/rubocop/cop/style/inverse_methods.rb, lib/rubocop/options.rb, lib/rubocop/runner.rb, lib/rubocop/target_finder.rb
I picked a few of the `Metrics/AbcSize` offenses from the todo list and reduced the complexity of the methods.
=> Reduce ABC complexity

lib/rubocop/result_cache.rb, spec/rubocop/result_cache_spec.rb
This closes #7454. I was able to reproduce this without Catalina by mounting a
filesystem image read-only -- before stubbing the filesystem in the specs.
=> [Fix #7454] Skip cache on read-only filesystems

lib/rubocop/config_validator.rb
Follow https://github.com/rubocop-hq/rubocop/pull/6601
`VersionRemoved` is an unused parameter, but it is the same kind of parameter as `VersionAdded` and `VersionChanged`.
This PR adds `VersionRemoved` to these internal params.
=> Add `VersionRemoved` to internal params

CHANGELOG.md, config/default.yml, manual/cops_naming.md
Add `os` to `AllowedNames` in the default configuration for cop
`Naming/UncommunicativeMethodParamName` in order to allow name that
is valid and it is pointless to replace it with i.e. `operating_system`
=> Allow `os` as method parameter in default config

lib/rubocop/cop/style/non_nil_check.rb, manual/cops_style.md
This PR is a change of document format for `Style/NonNilCheck` cop.
=> Restyle example formatting for `Style/NonNilCheck`

CHANGELOG.md, lib/rubocop/cop/metrics/abc_size.rb, lib/rubocop/cop/metrics/utils/abc_size_calculator.rb, lib/rubocop/cop/mixin/method_complexity.rb, spec/rubocop/cli/cli_disable_uncorrectable_spec.rb, spec/rubocop/cop/metrics/abc_size_spec.rb, spec/rubocop/cop/metrics/utils/abc_size_calculator_spec.rb
Providing component values gives more insights to fix the offense.
`Metrics/AbcSize: Assignment Branch Condition size for choose_move is too high. [<8, 12, 6> 15.62/15]`
definitetly provides more information than
`Metrics/AbcSize: Assignment Branch Condition size for choose_move is too high. [15.62/15]`
=> [Fix #7396]: Display ABC components with the value

CHANGELOG.md, lib/rubocop/cop/util.rb
The forward slash character has no special meaning when it appears in a regex. This will let `Performance/StartWith` and `Performance/EndWith` correct code like the following:
```ruby
path =~ %r{/\z}
```
To:
```ruby
path.end_with?('/')
```
I noticed this problem thanks to @eregon's comment here: https://github.com/rails/rails/pull/37504#discussion_r339314567
`LITERAL_REGEX` is only used in RuboCop Performance, so I couldn't add a test to demonstrate the new behaviour. Arguably the constant should be defined there instead, but removing it from RuboCop would introduce an incompatibility with all existing versions of RuboCop Performance. I opted to update the constant in-place; let me know if another approach is preferable. …
=> Add forward slash to LITERAL_REGEX

lib/rubocop/cop/lint/useless_access_modifier.rb, manual/cops_lint.md
This PR updates document for `Lint/UselessAccessModifier`.
#7467 is the trigger.
This PR separated good cases and bad cases for example code and clarified the options that cop has.
=> Update document for `Lint/UselessAccessModifier`

README.md
The JRuby version 9.1+ is listed as a supported Ruby implementation in the README. However, Rubocop's CircleCI configuration is only testing against JRuby 9.2. This PR updates the README to list JRuby 9.2+ as the supported JRuby implementation.
Alternatively, if we want to continue to support JRuby 9.1.x, we can update the CircleCI configuration to include testing against JRuby 9.1.
With regards to unchecked items on the checklist below, there's no related issue, there's only one commit so there's no need to squash. We also don't need to add tests, update the Changelog, or generate docs for this change if I understand correctly. Let me know if that's not the case or if I missed anything.
[1]: …
=> Update JRuby version in README

manual/basic_usage.md
This is a typo fix in the command line flags documentation
=> Fix typo in command line flags

lib/rubocop/cop/style/array_join.rb, manual/cops_style.md
Just a markdown syntax fix
I'm not totally sure if I should add a changelog entry given that this is one character in docs, but if you want I am happy to.
* [*] Wrote [good commit messages][1].
* [*] Feature branch is up-to-date with `master` (if not - rebase it).
* [*] Squashed related commits together.
* [*] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [*] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.
=> Typo fix in Style/ArrayJoin docs

spec/rubocop/cop/style/parallel_assignment_spec.rb
This PR adds a workaround that skips some tests when using JRuby to stabilize CI.
All tests are successful.
```console
% ruby -v
jruby 9.2.8.0 (2.5.3) 2019-08-12 a1ac7ff Java HotSpot(TM) 64-Bit Server
VM 25.5-b02 on 1.8.0_05-b13 +jit [darwin-x86_64]
% bundle exec rspec ./spec/rubocop/cop/style/parallel_assignment_spec.rb
(snip)
Finished in 2.19 seconds (files took 7.43 seconds to load)
89 examples, 0 failures
Randomized with seed 46036
```
Four tests fail. The following fails with JRuby 9.2.9.0.
```console
% ruby -v
jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e Java HotSpot(TM) 64-Bit Server
VM 25.5-b02 on 1.8.0_05-b13 +jit [darwin-x86_64]
% bundle exec rspec ./spec/rubocop/cop/style/parallel_assignment_spec.rb
(snip)
Failures:
1) RuboCop::Cop::Style::ParallelAssignment behaves like allowed …
```
=> Workaround to skip some tests when using JRuby

manual/extensions.md
Recently I created a custom cop generator.
https://github.com/pocke/custom_cops_generator
It generates a boilerplate of custom cop extension gem.
I think it is helpful for creators for a custom cop.
And I'd like to move the repository to under the rubocop-hq organization. What do you think, @rubocop-hq/rubocop-core ?
If it is ok, I'll move the repository and update this pull request to refer the moved repository.
Thanks!
=> Add custom cop generator to the manual

lib/rubocop/ast/node.rb, lib/rubocop/ast/node/block_node.rb, lib/rubocop/cop/internal_affairs.rb, lib/rubocop/cop/internal_affairs/method_name_equal.rb, lib/rubocop/cop/layout/multiline_method_argument_line_breaks.rb, lib/rubocop/cop/lint/disjunctive_assignment_in_constructor.rb, lib/rubocop/cop/lint/ineffective_access_modifier.rb, lib/rubocop/cop/lint/redundant_with_index.rb, lib/rubocop/cop/lint/redundant_with_object.rb, lib/rubocop/cop/lint/useless_access_modifier.rb, lib/rubocop/cop/lint/useless_setter_call.rb, lib/rubocop/cop/metrics/method_length.rb, lib/rubocop/cop/style/alias.rb, lib/rubocop/cop/style/eval_with_location.rb, lib/rubocop/cop/style/mixin_grouping.rb, lib/rubocop/cop/style/trivial_accessors.rb, spec/rubocop/cop/internal_affairs/method_name_equal_spec.rb
This PR adds new `InternalAffairs/MethodNameEqual` cop.
```ruby
node.method_name == :do_something
node.method?(:do_something)
```
This cop is an internal cop and will not be added to a changelog entry.
=> Add new `InternalAffairs/MethodNameEqual` cop

lib/rubocop/config_obsoletion.rb, spec/rubocop/config_obsoletion_spec.rb
In April 2019, "Add IndentFirstArgument and IndentFirstParameter" https://github.com/rubocop-hq/rubocop/pull/6982 forked the existing `FirstParameterIndentation` cop into two and added new argument-related functionality.
A few weeks ago, these two cops were renamed as part of broad renaming effort (https://github.com/rubocop-hq/rubocop/issues/7077), and it just so happened `IndentFirstParameter` now has the name of the old pre-forked cop.
https://github.com/rubocop-hq/rubocop/pull/7468/files#diff-a19f978b95beb4caeb1831d6bef7e443R11
The obsoletion config now thinks the two forked cops are the same, but they are not. When I try to run RuboCop locally from master against our codebase, I get this spurious warning:
```
Error: The `Layout/FirstParameterIndentation` cop has been renamed to …
```
=> Fix an obsoletion misconfig that inadvertently blocks use of `Layout/FirstParameterIndentation`

lib/rubocop/rake_task.rb
This PR fixes the following error when using `rake internal_investigation:auto_correct` task.
```console
% bundle exec rake internal_investigation:auto_correct
Running RuboCop...
-P/--parallel can not be combined with --auto-correct.
RuboCop failed!
```
=> Fix an error for `rake internal_investigation:auto_correct` task

CHANGELOG.md, lib/rubocop/cop/style/redundant_return.rb, spec/rubocop/cop/style/redundant_return_spec.rb
=> [Fix #7493] Detect redundant returns at end of longer methods

lib/rubocop/cop/style/numeric_literals.rb, manual/cops_style.md
This PR is a change of document format for `Style/NumericLiterals` cop.
=> Restyle example formatting for `Style/NumericLiterals`

mkdocs.yml
Migration department is introduced by https://github.com/rubocop-hq/rubocop/pull/7385, but the ToC of the manual does not contain the department.
This pull request adds Migration department to the ToC.
note: I've noticed this problem with an article (Japanese) :heart:  https://qiita.com/sakuraya/items/e8089c6c824716c156d9#migrationdepartmentname
=> Add migration department to ToC of manual

lib/rubocop/cop/layout/first_array_element_indentation.rb, manual/cops_layout.md
Little fix for a typo I found while reading the docs. 🎈
=> Fix typo in Layout/FirstArrayElementIndentation

CHANGELOG.md, lib/rubocop/cop/correctors/space_corrector.rb, spec/rubocop/cop/layout/space_inside_array_literal_brackets_spec.rb
Fixed Layout/SpaceInsideArrayLiteralBrackets to correct empty lines.
See https://github.com/rubocop-hq/rubocop/issues/7509 for details.
=> [Fix #7509] Layout/SpaceInsideArrayLiteralBrackets to correct empty lines

CHANGELOG.md, lib/rubocop/cop/layout/space_around_keyword.rb, spec/rubocop/cop/layout/space_around_keyword_spec.rb
The `Layout/WhitespaceAroundKeyword` cop complains when `super::MyConst` is used. However, in Ruby, modules and classes are normal objects and can be returns by methods including by using `super`. Therefore, `super::MyConst` should be considered valid style.
This type of usage is distinct from the intention of this cop, which is to avoid missing space such as around `something = 123if test` and `while(something)`.
I considered adding a test that verifies that the cop complains when a keyword other than `super` is used in the same manner (it does). However, I believe this is a syntax error in every other case and so the behavior of this cop is perhaps best left undefined. The alternative would be to suggest that `yield ::` is the correct form of `yield::`, which is false; they're both …
=> [Fix #7517] Layout/WhitespaceAroundKeyword: allow `super::const`

CHANGELOG.md, lib/rubocop/cop/lint/redundant_splat_expansion.rb, lib/rubocop/cop/style/redundant_parentheses.rb, lib/rubocop/cop/style/redundant_sort.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
Fixes #7515.
This PR fixes a false negative for `Style/RedundantParentheses` when calling a method with safe navigation operator.
=> [Fix #7515] Fix a false negative for `Style/RedundantParentheses`

lib/rubocop/cop/cop.rb, lib/rubocop/cop/team.rb, lib/rubocop/result_cache.rb, lib/rubocop/runner.rb, spec/rubocop/cop/team_spec.rb, spec/rubocop/result_cache_spec.rb
Internally at Flexport, we've written a few cops to enforce Rails Engine isolation. They've helped us incrementally modularize our system, and we think they might be valuable to others too. I'm working to open source them now.
For example, `GlobalModelAccessFromEngine` (https://github.com/flexport/rubocop-flexport/pull/5) forbids code within Rails Engines from directly accessing global models in the main `app/` directory. Another example is `EngineApiBoundary` (https://github.com/flexport/rubocop-flexport/pull/6).
(Note: we considered upstream these to `rubocop-rails`, and @koic suggested we create our gem instead: https://github.com/rubocop-hq/rubocop-rails/pull/152#issuecomment-554839724)
These cops read from the filesystem, taking a holistic view of our codebase while they inspect. …
=> Allow cops to invalidate results cache

CHANGELOG.md, lib/rubocop/cop/metrics/line_length.rb, spec/rubocop/cop/metrics/line_length_spec.rb
Fixes https://github.com/rubocop-hq/rubocop/issues/7477. Previously the cop naively checked for the character `;` anywhere in the source code, which would match semicolons within string literals and cause correctness issues.
Now the cop instead uses the tokenizer output to find semicolons.
=> [Fix #7477] Fix semicolon line length autocorrection

CHANGELOG.md, lib/rubocop/cop/style/even_odd.rb, spec/rubocop/cop/style/even_odd_spec.rb
```ruby
n % 2 == 2
```
is auto-corrected to
```
n.?
```
by `Style/EvenOdd`, which is clearly a mistake.
```
tmp-numbers.rb:1:1: C: [Corrected] Style/EvenOdd: Replace with Integer#?.
n % 2 == 2
^^^^^^^^^^
tmp-numbers.rb:1:3: E: Lint/Syntax: unexpected token tEH
(Using Ruby 2.3 parser; configure using TargetRubyVersion parameter, under AllCops)
n.?
^
```
I am not sure this unusual edge case warrants an entry in the changelog. Just let me know if I should add one.
=> Fix false positive in Style/EvenOdd

CHANGELOG.md, config/default.yml, manual/cops_style.md
The name of the `Whitelist` parameter of `Style/TrivialAccessors` was recently changed to `AllowedMethods`.
However, there were two places where the name was accidentally changed to `AllowedMethod` instead (Note the missing trailing `s`).
Fixes https://github.com/rubocop-hq/rubocop/issues/7530
=> Fix typo of missing `s` in AllowedMethods parameter

CHANGELOG.md, lib/rubocop/cop/mixin/trailing_comma.rb, spec/rubocop/cop/style/trailing_comma_in_arguments_spec.rb
Fixes #7532.
This PR fixes an error for `Style/TrailingCommaInArguments` when using an anonymous function with multiple line arguments with `EnforcedStyleForMultiline: consistent_comma`.
=> [Fix #7532] Fix an error for `Style/TrailingCommaInArguments`

CHANGELOG.md, lib/rubocop/cop/layout/space_before_block_braces.rb, spec/rubocop/cli/cli_autocorrect_spec.rb
Fixes #7534.
Fix an incorrect autocorrect for `Style/BlockDelimiters` cop and `Layout/SpaceBeforeBlockBraces` cop with `EnforcedStyle: no_space` when using multiline braces.
=> [Fix #7534] Fix an incorrect autocorrect for `Layout/SpaceBeforeBlockBraces`

CHANGELOG.md, lib/rubocop/config_validator.rb, spec/rubocop/cli_spec.rb, spec/rubocop/config_spec.rb, spec/rubocop/cop/generator_spec.rb, spec/rubocop/formatter/disabled_config_formatter_spec.rb
This PR addresses the issue raised in #7231. Loading the config file will now memorize the warning for unknown cops and will exit with status `1` if the run would otherwise exit with `0` (STATUS_SUCCESS).
=> Fix #7231 unknown cop in config file will exit with code 2

.rubocop_todo.yml, CHANGELOG.md, lib/rubocop/cop/cop.rb, spec/rubocop/cop/lint/syntax_spec.rb
=> [Fix #7513] Fix abrupt error on autocorrecting with `--disable-uncorrectable`

lib/rubocop/result_cache.rb, lib/rubocop/runner.rb
This PR aims to answer https://github.com/rubocop-hq/rubocop/pull/7496#discussion_r350462926 by @exterm on https://github.com/rubocop-hq/rubocop/pull/7496 "Allow cops to invalidate results cache" with code comments.
An alternative (more invasive) implementation I considered was to pull the cop mobilization logic out of `Runner` into a new helper module `RuboCop::Cop::Mobilizer`. Then the runner could just pass the `config` and `options` to the `ResultCache`, which could then create its own "standby" teams internally. This would more cleanly contain the team-level external dependency checksum caching logic within the `ResultCache`, but it would require more refactoring.
[1]: …
=> Add comments explaining external dependency checksum caching

CHANGELOG.md
I found two mistakes in CHANGELOG.
This pull request fixes them.
First, "Replace `Time.zone.current` with `Time.zone.today` on `Rails::Date` cop message." entry was in a wrong place.
It was changed in v0.69.0 actually, but it was placed in v0.68.1 section. And it had duplicated `## Bug fixes` header.
Second, it is a cop name typo.
It should be `Lint/DisjunctiveAssignmentInConstructor`, but it was `Style/DisjunctiveAssignmentInConstructor`.
I guess we overlooked the changelog entry when renaming the cop in the pull request. https://github.com/rubocop-hq/rubocop/pull/6608
=> Tweak CHANGELOG

config/default.yml, manual/cops_gemspec.md
This PR fixes a typo in config/default.yml.
The typo included in the following commit.
https://github.com/rubocop-hq/rubocop/commit/248e921
There is only one similar typo.
```console
% git grep '^ *-$'
config/default.yml:    -
```
This fix removes unnecessary default value `none` from manual/cops_gemspec.md.
=> Fix a typo in default.yml

config/default.yml
In certain rails projects, `tmp` can contain hundreds of thousands of files.
Excluding `tmp` in my project seems to decrease `time bin/rubocop` from 90s to 20s, though that's just an anecdote and not a scientific benchmark.
Does anyone put code in `tmp` that they actually want to lint? That'd be rare, right?
* [N/A] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [N/A] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [N/A?] Run `bundle …
=> In default.yml, Exclude tmp

CHANGELOG.md, lib/rubocop/cop/style/attr.rb, spec/rubocop/cop/style/attr_spec.rb
=> [Fix #7029] Make `Style/Attr` not flag offense for custom `attr` method

Gemfile
This PR solves a broken document as follows:
```console
% ruby -v
ruby 2.7.0dev (2019-12-08T15:13:07Z master 0e71fbc18e) [x86_64-darwin17]
% bundle exec rake generate_cops_documentation
Files:         473
Modules:        83 (   76 undocumented)
Classes:       437 (  411 undocumented)
Constants:     628 (  620 undocumented)
Attributes:     31 (    0 undocumented)
Methods:      1080 (  961 undocumented)
8.46% documented
* generated /Users/koic/src/github.com/rubocop-hq/rubocop/manual/cops_bundler.md
* generated /Users/koic/src/github.com/rubocop-hq/rubocop/manual/cops_gemspec.md
* generated /Users/koic/src/github.com/rubocop-hq/rubocop/manual/cops_layout.md
* generated /Users/koic/src/github.com/rubocop-hq/rubocop/manual/cops_lint.md
* generated …
```
=> Workaround for broke docs with YARD 0.9.20 when using Ruby 2.7.0-dev

config/default.yml, manual/cops_gemspec.md
Follow up of https://github.com/rubocop-hq/ruby-style-guide/pull/782 and https://github.com/rubocop-hq/ruby-style-guide/pull/784.
This PR adds the Style Guide URL for `Gemspec/RubyVersionGlobalsUsage`.
=> Add the Style Guide URL for `Gemspec/RubyVersionGlobalsUsage`

CHANGELOG.md, config/default.yml, lib/rubocop/cop/layout/space_around_operators.rb, manual/cops_layout.md, spec/rubocop/cli/cli_auto_gen_config_spec.rb, spec/rubocop/cop/layout/space_around_operators_spec.rb
This PR add `EnforcedStyleForExponentOperator` parameter to `Layout/SpaceAroundOperators` cop in order to allow spaces around `**`.
There are some old discussion in #2972.
=> Add `EnforcedStyleForExponentOperator` parameter to `Layout/SpaceAroundOperators`

CONTRIBUTING.md
This PR adds how to write a breaking change entry to the CONTRIBUTING.md
This change is based on:
> All breaking changes are clearly marked with **(Breaking)** in the Changelog.
https://metaredux.com/posts/2019/12/15/a-uniform-rubocop.html
=> Add how to write a breaking change entry to the CONTRIBUTING.md

lib/rubocop/cop/lint/redundant_cop_disable_directive.rb
This is just a line I stumbled across. There is no need to use the
regexp machinery just to match a fixed substring.
=> Remove unnecessary use of regexp

CHANGELOG.md, lib/rubocop/cop/style/percent_literal_delimiters.rb, spec/rubocop/cop/style/percent_literal_delimiters_spec.rb
This fixes #7193 and actually follows up on https://github.com/rubocop-hq/rubocop/pull/5020, which claimed to fix the situation where escaped delimiters are contained in a percent literal but only did so for `%w` literals.
=> [Fix #7193] Prevent PercentLiteralDelimiters from breaking certain %i literals

spec/rubocop/cop/style/numeric_predicate_spec.rb
This PR suppresses the following deprecation warning when using Ruby 2.7.0-dev.
```console
% ruby -v
ruby 2.7.0dev (2019-12-23T02:48:54Z master 048f797bf0) [x86_64-darwin17]
(snip)
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.0/lib/rspec/core/shared_example_group.rb:36:
warning: The last argument is used as keyword parameters; maybe **
should be added to the call
/Users/koic/src/github.com/rubocop-hq/rubocop/spec/rubocop/cop/style/numeric_predicate_spec.rb:12:
warning: The called method is defined here
```
https://bugs.ruby-lang.org/issues/14183
=> Suppress a deprecation warning when using Ruby 2.7.0-dev

.rubocop_todo.yml, CHANGELOG.md, lib/rubocop/config_loader.rb, lib/rubocop/cop/generator.rb, lib/rubocop/cop/generator/configuration_injector.rb, lib/rubocop/cop/registry.rb, lib/rubocop/cop/style/method_call_with_args_parentheses.rb, lib/rubocop/rspec/shared_contexts.rb, manual/configuration.md, manual/development.md, manual/index.md, manual/versioning.md, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/generator_spec.rb, spec/rubocop/cop/registry_spec.rb
New cops, introduced or significantly changed between major versions, are introduced with `pending` status. This is done to avoid frustration over numerous offences during updates between minor versions. RuboCop will emit a warning that new cops were introduced, and suggest to explicitly enable or disable them in the user configuration file.
Based on https://github.com/rubocop-hq/rubocop/pull/7184
Fixes #5979
=> [Fix #5979] Introduce cops with special status

lib/rubocop/config_loader.rb, lib/rubocop/config_validator.rb, spec/rubocop/config_loader_spec.rb
This fixes #7593. There is no changelog entry because this is not a
user-facing bug: From a user's perspective RuboCop exits immediately in
any case.
Merry Christmas :christmas_tree:
=> [Fix #7593] Do not Kernel#abort on validation errors

CHANGELOG.md, lib/rubocop/cop/layout/space_before_block_braces.rb, spec/rubocop/cop/layout/space_before_block_braces_spec.rb
Fixes #7590.
This PR fixes an error for `Layout/SpaceBeforeBlockBraces` when using with `EnforcedStyle: line_count_based` of `Style/BlockDelimiters` cop.
=> [Fix #7590] Fix an error for `Layout/SpaceBeforeBlockBraces`

CHANGELOG.md, lib/rubocop/cop/style/yoda_condition.rb, spec/rubocop/cop/style/yoda_condition_spec.rb
Fixes #7569.
This PR makes `Style/YodaCondition` cop accept `__FILE__ == $0`
I think that both operands `__FILE__ == $0` can be assumed to be read-only, as mentioned in #7569. If users try to assign `__FILE__`, an error will occur. Also, it is not usually assigned to `$0` by users.
Therefore, this PR will make `Style/YodaCondition` cop accept both `__FILE__` and `$0` on the left side.
Also, this PR will change only an idiom `__FILE__ == $0`.
=> [Fix #7569] Make `Style/YodaCondition` accept `__FILE__ == $0`

Gemfile
This PR fixes the following error when using Parser 2.7.0.0.
https://circleci.com/gh/rubocop-hq/rubocop/78846
```console
% cd path/to/repo/rubocop
% bundle exec rake internal_investigation
Running RuboCop...
invalid byte sequence in UTF-8
/Users/koic/src/github.com/whitequark/parser/lib/parser/lexer/dedenter.rb:40:in `split'
/Users/koic/src/github.com/whitequark/parser/lib/parser/lexer/dedenter.rb:40:in `dedent'
/Users/koic/src/github.com/whitequark/parser/lib/parser/builders/default.rb:288:in `block in dedent_string'
/Users/koic/src/github.com/whitequark/parser/lib/parser/builders/default.rb:285:in `each'
/Users/koic/src/github.com/whitequark/parser/lib/parser/builders/default.rb:285:in `dedent_string'
/Users/koic/src/github.com/whitequark/parser/lib/parser/ruby23.rb:5713:in …
```
=> Fix an error when using Parser 2.7.0.0

Gemfile
This PR fixes a build error when using Ruby 2.7.0 with YARD.
```console
% cd path/to/repo/rubocop
% ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin17]
rake aborted!
LoadError: cannot load such file -- e2mmap
/Users/koic/.rbenv/versions/2.7.0/bin/bundle:23:in `load'
/Users/koic/.rbenv/versions/2.7.0/bin/bundle:23:in `<main>'
Tasks: TOP => default => documentation_syntax_check =>
yard_for_generate_documentation
(See full trace by running task with --trace)
```
After adding `e2mmap` gem, the following error occurs.
```console
rake aborted!
LoadError: cannot load such file -- irb/slex
/Users/koic/.rbenv/versions/2.7.0/bin/bundle:23:in `load'
/Users/koic/.rbenv/versions/2.7.0/bin/bundle:23:in `<main>'
Tasks: TOP => default => …
```
=> Workaround for a build error when using Ruby 2.7.0 with YARD

CHANGELOG.md, lib/rubocop/cop/gemspec/ordered_dependencies.rb, spec/rubocop/cop/gemspec/ordered_dependencies_spec.rb
Fixes #7576.
This PR fixes the following error for `Gemspec/OrderedDependencies` when using a local variable in an argument of dependent gem.
```console
% cat example.gemspec
Gem::Specification.new do |s|
%w[foo bar].each { |dep| s.add_dependency dep }
s.add_dependency 'baz'
end
% rubocop --only Gemspec/OrderedDependencies example.gemspec -d
(nsip)
An error occurred while Gemspec/OrderedDependencies cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/7576/example.gemspec.
undefined method `str_type?' for nil:NilClass
```
Since it is difficult to trace variables and list gem names, this PR will skip them.
And `add_dependency`, `add_runtime_dependency`, and `add_development_dependency` accept a symbol.
e.g. `add_dependency(:foo)`
The original implementation raises the same …
=> [Fix #7576] Fix an error for `Gemspec/OrderedDependencies`

lib/rubocop/ast/node/mixin/conditional_node.rb, lib/rubocop/ast/node/mixin/method_dispatch_node.rb, lib/rubocop/cop/layout/line_length.rb, spec/rubocop/ast/send_node_spec.rb
Used the gem zombie_scout to scout for unused methods in the lib. Found a few of them that I'm proposing to remove since they are not being called anywhere. I was also able to remove some specs that were related with the unused code.
=> Remove unused code

lib/rubocop/ast/node/mixin/conditional_node.rb, lib/rubocop/ast/node/mixin/method_dispatch_node.rb, lib/rubocop/cop/layout/line_length.rb, spec/rubocop/ast/send_node_spec.rb
Reverts rubocop-hq/rubocop#7600
As pointed out by @bbatsov the removed code consists of public API methods and we can be breaking some unknown extension.
=> Revert "Remove unused code"

CHANGELOG.md, lib/rubocop/cop/style/numeric_predicate.rb, spec/rubocop/cop/style/numeric_predicate_spec.rb
Fixes #7595.
This PR makes `Style/NumericPredicate` aware of ignored methods when specifying ignored methods.
The following is a reproduction procedure.
```console
Style/NumericPredicate:
EnforcedStyle: comparison
IgnoredMethods: 'zero?'
if foo.zero?
puts 'hello'
end
% bundle exec rubocop --only Style/NumericPredicate --cache false example.rb
C
Offenses:
example.rb:1:4: C: Style/NumericPredicate: Use foo == 0 instead of
foo.zero?.
if foo.zero?
^^^^^^^^^
```
This PR resolves the issue caused by the callback node itself not being checked.
=> [Fix #7595] Make `Style/NumericPredicate` aware of ignored methods

Gemfile
Follow up of https://github.com/rubocop-hq/rubocop/pull/7597
https://github.com/whitequark/parser/pull/642 has been merged and Parser 2.7.0.1 has been released.
https://rubygems.org/gems/parser/versions/2.7.0.1
=> Remove workaround code for Parser 2.7.0.0

Gemfile
Follow up of https://github.com/rubocop-hq/rubocop/pull/7606#discussion_r361956264.
This PR removes redundant Parser gem dependency from Gemfile.
It is redundant with the specification in gemspec.
=> Remove redundant Parser gem dependency from Gemfile

CHANGELOG.md, lib/rubocop/cop/mixin/frozen_string_literal.rb, spec/rubocop/cop/style/frozen_string_literal_comment_spec.rb
=> [Fix #7586] Fix infinite loop in Style/FrozenStringLiteralComment

CHANGELOG.md, lib/rubocop/cop/layout/hash_alignment.rb, spec/rubocop/cop/layout/hash_alignment_spec.rb
Fixes [#7291](https://github.com/rubocop-hq/rubocop/issues/7291)
Before this change, the Layout/HashAlignment cop always gave the same error message: "Align the elements of a hash literal if they span more than one line."
This was confusing in situations where a hash appeared to be aligned, but was not according to the configured alignment settings.
This PR changes the error message to reflect which part(s) of a hash must be aligned to pass the cop.
=> [Fix #7291] Add better message for layout/HashAlignment

rubocop.gemspec
Follow up of https://github.com/rubocop-hq/rubocop/pull/7606#discussion_r361963001.
Parser 2.7.0.0 has the following issue.
https://github.com/rubocop-hq/rubocop/pull/7597
This PR changes to require Parser gem 2.7.0.1 or higher.
Parser 2.7 is compatible with Parser 2.6, so I think it's safe to upgrade.
=> Require Parser 2.7.0.1 or higher

CHANGELOG.md, lib/rubocop/cop/lint/debugger.rb, spec/rubocop/cop/lint/debugger_spec.rb
Rails' [Web Console](https://github.com/rails/web-console) has been around for a while now and I like debugging my applications with it. I recently shipped a `console` call in production (this is what spawns it). While the `console` call is not a security vulnerability, it results in a `NoMethodError` as Web Console is not available in production, I would have loved to have this caught by a linter. 
Do you think it has a place in `Lint/Debugger`?
=> Recognize rails/web-console debug calls in Lint/Debugger

Gemfile
YARD 0.9.21 has been released.
https://rubygems.org/gems/yard/versions/0.9.21
This PR reverts the following workaround code for YARD.
- https://github.com/rubocop-hq/rubocop/pull/7598
- https://github.com/rubocop-hq/rubocop/pull/7558
=> Revert workaround for YARD

CHANGELOG.md, config/default.yml, manual/cops_style.md
Auto-correction of `Style/FrozenStringLiteralComment` changes the state of
string objects in a program and may thus break it.
This closes #7287.
=> [Fix #7287] Auto-correction of FrozenStringLiteralComment is unsafe

lib/rubocop/config_validator.rb, lib/rubocop/cop/autocorrect_logic.rb, manual/cops_lint.md, manual/cops_style.md, spec/rubocop/config_spec.rb, spec/rubocop/cop/cop_spec.rb, tasks/cops_documentation.rake
=> [Fix #7611] An unsafe cop cannot have a safe auto-correction

CHANGELOG.md, lib/rubocop/cop/migration/department_name.rb, spec/rubocop/cop/migration/department_name_spec.rb
Fixes #7620.
This PR fixes the following false positive for `Migration/DepartmentName` when a disable comment contains a plain comment.
```console
% rubocop --only Migration/DepartmentName
C
Offenses:
example.rb:1:50: C: Migration/DepartmentName: Department name is missing.
^^^^
```
The following is an example disable comment.
```ruby
```
The token used after `# rubocop: disable` are `A-z`, `/`, `,`.
And `A-z` includes `all`.
```ruby
```
This PR will change the processing of `Migration/DepartmentName` cop to finish when an invalid token is used.
=> [Fix #7620] Fix a false positive for `Migration/DepartmentName`

spec/rubocop/ast/range_node_spec.rb
This PR adds a spec for beginless range for Ruby 2.7.
https://bugs.ruby-lang.org/issues/14799
=> Add a spec of beginless range for Ruby 2.7

CHANGELOG.md, lib/rubocop/cop/style/multiline_when_then.rb, spec/rubocop/cop/style/multiline_when_then_spec.rb
Fixes #7616.
This PR fixes an incorrect autocorrect for `Style/MultilineWhenThen` for when statement with then is an array or a hash.
The following is a reproduction procedure.
```console
case condition
when foo then {
key: 'value'
}
end
Syntax OK
```
It is changed to the code with syntax error as follows.
```console
% bundle exec rubocop -a --only Style/MultilineWhenThen
(snip)
case condition
when foo {
key: 'value'
}
end
example.rb:3: syntax error, unexpected ':', expecting '}'
key: 'value'
example.rb:4: syntax error, unexpected '}', expecting end-of-input
```
The same is true when replacing a hash with an array.
The PR will accept these cases without offense. …
=> [Fix #7616] Fix an incorrect autocorrect for `Style/MultilineWhenThen`

CHANGELOG.md, lib/rubocop/cop/migration/department_name.rb, spec/rubocop/cop/migration/department_name_spec.rb
Fixes #7627.
This PR fixes a false negative for `Migration/DepartmentName` when there is space around `:`.
For example, `# rubocop : disable` is a valid syntax for a disable comment.
=> [Fix #7627] Fix a false negative for `Migration/DepartmentName`

CHANGELOG.md, lib/rubocop/cop/layout/multiline_block_layout.rb, spec/rubocop/cop/layout/multiline_block_layout_spec.rb
Fixes #7628.
Autocorrect for `Layout/MultilineBlockLayout` removed a trailing comma for single arguments that could potentially change semantics. 
Introduced `include_trailing_comma?` method to determine whether this trailing comma is both present and required in order to include it where necessary.
Tests added for this case and also to make sure it functioned correctly with nested parentheses.
=> [Fix #7628] Include trailing comma for single arg

CHANGELOG.md, lib/rubocop/cop/lint/debugger.rb, spec/rubocop/cop/lint/debugger_spec.rb
It's ambiguous and we can play games and try not to recognize:
```ruby
console(with, arguments_or) do
with_a_block
end
```
But, other use cases will come up. Web Console supports
`binding.console`, which is safe to recognize, so let's drop
the ambiguous `console` one.
=> Remove `console` from `Lint/Debugger`

CHANGELOG.md, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
Before this change:
```ruby
foo(a) || bar(b) do
^^^ Omit parentheses for method calls with arguments.
pass
end
```
This resulted in a `SyntaxError` if corrected. The check for a call
with a logical operator did not take into account that the parent of a
send node with a block is the block node itself.
After this change, the code below is lawful:
```ruby
foo(a) || bar(b) do
pass
end
```
=> Fix  edge case in `omit_parentheses` style of `Style/MethodCallWithArgsParentheses`

spec/rubocop/cop/style/mutable_constant_spec.rb, spec/rubocop/cop/style/redundant_freeze_spec.rb
It has been abandoned in the Ruby 3.0 period, but may default in the long run. So these tests are left with a provisional value of 4.0.
=> Defer tests where frozen string by default

Rakefile
This PR uses Ruby 2.7 parser for `rake documentation_syntax_check`.
With this change, example code written using Ruby 2.7 syntax can be analyzed.
The following error occurs in `Lint/CircularArgumentReference` example code when Ruby 2.7 parser is used.
```consle
% bundle exec rake documentation_syntax_check
Files:         474
Modules:        83 (   11 undocumented)
Classes:       438 (    3 undocumented)
Constants:     631 (  621 undocumented)
Attributes:     31 (    0 undocumented)
Methods:      1081 (  960 undocumented)
29.55% documented
lib/rubocop/cop/lint/circular_argument_reference.rb: Syntax Error in an
example. circular argument reference pie
lib/rubocop/cop/lint/circular_argument_reference.rb: Syntax Error in an
example. circular argument reference dry_ingredients
```
The error is …
=> Use Ruby 2.7 parser for `rake documentation_syntax_check`

Gemfile
REXML gem has been unbundled since Ruby 2.8.0-dev (Ruby 3.0).
https://github.com/ruby/ruby/commit/c3ccf23d5807f2ff20127bf5e42df0977bf672fb
This PR fixes a build error when using Ruby 2.8.0-dev with crack.
```console
% cd path/to/repo/rubocop
% ruby -v
ruby 2.8.0dev (2020-01-14T00:46:52Z master 440013b2fa) [x86_64-darwin17]
(snip)
An error occurred while loading spec_helper. - Did you mean?
rspec ./spec/spec_helper.rb
Failure/Error: require 'webmock/rspec'
LoadError:
cannot load such file -- rexml/parsers/streamparser
Starting test-queue master (/tmp/test_queue_74588_13980.sock)
```
https://circleci.com/gh/rubocop-hq/rubocop/81817
The following PR has been opened to resolve the error.
https://github.com/jnunemaker/crack/pull/62
This patch is a workaround until a new …
=> Workaround for a build error when using Ruby 2.8.0-dev with crack

CHANGELOG.md, lib/rubocop/cop/layout/empty_line_between_defs.rb, spec/rubocop/cop/layout/empty_line_between_defs_spec.rb
I came across this while cleaning up tests. We have made similar changes to this in the past. The extra context makes it a little easier to quickly identify which method contains the offense.
=> Add the method name to the highlight area of Layout/EmptyLineBetweenDefs

CHANGELOG.md, lib/rubocop/ast/node/regexp_node.rb, spec/rubocop/ast/regexp_node_spec.rb
Fixes rubocop-hq/rubocop-performance#95.
This PR fixes `RuboCop::AST::RegexpNode` to return correct information
from multi-line regexp.
- `#regopt` - find regopt node instead of checking first node.
- `#content` - join all child string nodes instead of returning first node.
=> [Fix rubocop-hq/rubocop-performance#95] Fix to return correct info from multi-line regexp

spec/rubocop/cli/cli_options_spec.rb, spec/support/suppress_pending_warning.rb
Follow up of https://github.com/rubocop-hq/rubocop/pull/7646#discussion_r365585616.
This PR accepts pending cops in the development build.
Some tests fail with the following warnings when using the `Enabled: pending` status.
```console
% bundle exec rake spec
(snip)
1) RuboCop::CLI --only when one cop is given accepts cop names from
plugins
Failure/Error: raise output
RuntimeError:
The following cops were added to RuboCop, but are not
configured. Please set Enabled to either `true` or `false` in your
`.rubocop.yml` file:
- Style/ZeroLengthPredicate
Inspecting 2 files
..
2 files inspected, no offenses detected
in <top (required)>'
```
This PR prevents those tests from catching a pending cop warning.
OTOH, this PR …
=> Accept pending cops in the development build

CHANGELOG.md, lib/rubocop/cop/variable_force.rb, spec/rubocop/cop/variable_force_spec.rb
Fixes #7655.
This PR fixes the following error when processing a regexp with a line break at the start of capture parenthesis.
```console
% cat examle.rb
/(
pattern
)/ =~ string
% bundle exec rubocop -d
(snip)
An error occurred while VariableForce cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/7655/examle.rb.
end pattern with unmatched parenthesis: /(
/
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/variable_force.rb:194:in
`initialize'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/variable_force.rb:194:in
`new'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/variable_force.rb:194:in
`regexp_captured_names'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/variable_force.rb:174:in
`process_regexp_named_captures' …
```
=> [Fix #7655] Fix an error when processing a line break regexp

CHANGELOG.md, lib/rubocop/ast/traversal.rb
Fix #7647 
```yaml
AllCops:
TargetRubyVersion: 2.7
```
```ruby
#!/usr/bin/env ruby
def hello(meaning)
spliters = [',', '.', '!']
spliters.each { meaning = meaning.split(_1).first }
meaning.delete('"').strip.gsub("\r\n", '; ')
end
```
```
$ pwd
/home/sei/src/github.com/rubocop-hq/rubocop
$ cd 7647
$ ../exe/rubocop
.
```
=> [Fix #7647] Handle numblock

lib/rubocop/cop/layout/space_around_operators.rb, manual/cops_layout.md
This is only document change.
This commit adds examples of `AllowForAlignment` option for `Layout/SpaceAroundOperators` cop.
=> Add examples of `AllowForAlignment` option for `Layout/SpaceAroundOperators`

Gemfile
This PR fixes the following build error when using cc-test-reporter with SimpleCov 0.18.
```console
$ #!/bin/bash -eo pipefail
./tmp/cc-test-reporter before-build
COVERAGE=true bundle exec rake spec
./tmp/cc-test-reporter format-coverage --output
tmp/codeclimate.$CIRCLE_JOB.json
Starting test-queue master (/tmp/test_queue_228_47138309905180.sock)
==> Summary (2 workers in 36.1115s)
[ 1]                         8753 examples, 0 failures, 9 pending
254 suites in 36.1034s      (pid 160 exit 0 )
[ 2]                         6772 examples, 0 failures, 2 pending
239 suites in 36.1054s      (pid 161 exit 0 )
Coverage report generated for RSpec, rspec-1, rspec-2, rspec-fork-163,
rspec-fork-164, rspec-fork-165 to /home/circleci/project/coverage. 21266
/ 21459 LOC (99.1%) covered.
Error: json: …
```
=> Workaround for cc-test-reporter with SimpleCov 0.18

manual/configuration.md
In debugging some Rubocop configuration, I came across some documentation that seems to be out of date.
- `.ruby-version` has not been preferred to `TargetRubyVersion:` since https://github.com/rubocop-hq/rubocop/pull/3261
- `.ruby-version` has not had to be in the same directory as the `rubocop` invocation since https://github.com/rubocop-hq/rubocop/pull/5326
* ~~Commit message starts with `[Fix #issue-number]` (if the related issue exists).~~
* ~~Added tests.~~
* ~~Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#cha …
=> Update documentation to reflect current precedence in TargetRuby

manual/formatters.md
I found it hard to realize how to use the "Auto Gen Config" formatter from the documentation. I ended up finding the right parameter in the code: [`lib/rubocop/formatter/formatter_set.rb`](https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/formatter/formatter_set.rb).
I thought it'd be worth being explicit on how to use each formatter in the documentation.
=> Updates docs to be more explicit when using formatters

CHANGELOG.md, lib/rubocop/cop/layout/space_before_first_arg.rb, spec/rubocop/cop/layout/space_before_first_arg_spec.rb
Fixes #7675.
This PR fixes a false negative for `Layout/SpaceBeforeFirstArg` when a vertical argument positions are aligned.
=> [Fix #7675] Fix a false negative for `Layout/SpaceBeforeFirstArg`

CHANGELOG.md, config/default.yml, manual/cops_naming.md
`pp` is standard parameter name for `PrettyPrint`
=> allow paremeter name `pp` for `pretty_print`

LICENSE.txt, README.md, mkdocs.yml
This PR updates Copyright year to 2020.
=> Update Copyright year to 2020

CHANGELOG.md, lib/rubocop/cop/migration/department_name.rb, spec/rubocop/cop/migration/department_name_spec.rb
Fixes #7619.
This PR supports autocorrect of legacy names for `Migration/DepartmentName`.
Auto-correction for legacy names complements legacy department names.
Migration to new cop names are expected to be modified using Gry gem.
https://github.com/pocke/gry
=> [Fix #7619] Support autocorrect of legacy names for `Migration/DepartmentName`

CHANGELOG.md, lib/rubocop/cop/layout/line_length.rb, manual/cops_layout.md, spec/rubocop/cop/layout/line_length_spec.rb
Shortens long lines by inserting a line break into blocks like this:
```rb
foo.bar { |baz| batbatbatbatbatbatbatbat(baz) }
foo.bar { |baz|
batbatbatbatbatbatbatbat(baz) }
foo.bar do |baz|
batbatbatbatbatbatbatbat(baz)
end
```
=> Add line length autocorrect for blocks

manual/cops_style.md, tasks/cops_documentation.rake
Follow up of #5979.
This PR shows pending status in cop status of manual.
The pending status is not enabled status and may lead to misreading.
=> Show pending status in cop status of manual

README.md
Generally if you want to install something using `bundler`, you _do_ require it in your `Gemfile`.
=> Fix apparent typo in README

manual/node_pattern.md
The separate file for the documentation of `NodePattern` is missing this.
=> NodePattern: document ^ [doc]

lib/rubocop/cop/style/symbol_array.rb, manual/cops_style.md
=> Fix incorrect formatting

CHANGELOG.md, config/default.yml, lib/rubocop/cop/style/block_delimiters.rb, manual/cops_style.md, spec/rubocop/cop/style/block_delimiters_spec.rb
The motivating use case for this in our codebase is to switch [Sorbet](https://sorbet.org/) `sig` declarations from `do...end` to `{...}`:
Syntax highlight for do/end on type signatures are distracting:
Braces are less distracting:
Currently the first is enforced by `line_count_based`, which we want for all other methods.
=> Add RequiredBracesMethods param to BlockDelimiters

lib/rubocop/ast/node.rb
None of these methods actually accept an array of symbols.
=> Fix documentation [doc]

CHANGELOG.md, lib/rubocop/node_pattern.rb, spec/rubocop/node_pattern_spec.rb
Fixes #7644, as well as adds support for unification with unions.
=> [Fixes #7644] NodePattern: Fix unification within unions

CHANGELOG.md, lib/rubocop/cop/mixin/configurable_enforced_style.rb, lib/rubocop/cop/style/method_call_with_args_parentheses.rb
Closes #7688. Caused by #7623.
Going forward, `Cop#support_autocorrect?` should probably be turned into
a class method.
=> [Fix #7688] Support MethodCallWithArgsParentheses.new without config

lib/rubocop/node_pattern.rb, manual/node_pattern.md, spec/rubocop/ast/node_spec.rb, spec/rubocop/node_pattern_spec.rb
This PR proposes extending the `NodePattern` to allow searching the descendants.
See the example in `manual/node_pattern.md `
=> NodePattern: Add ` for descendant search

rubocop.gemspec
This PR suppress the following warning.
```console
% cd path/to/rubocop
% bundle install
Your Gemfile lists the gem pry (>= 0) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the
version of one of them later.
Using rake 12.3.3
Using public_suffix 4.0.3
(snip)
```
`pry` gem is already in the Gemfile.
This looks like it was accidentally added in #7663.
=> Remove duplicate dependency development gem

CHANGELOG.md, config/default.yml, lib/rubocop/cop/lint/useless_setter_call.rb, manual/cops_lint.md
This closes #7309, which was an attempt to fix false positives with code. It was deemed too complex, so we're adding documentation for a, hopefully, very rare problem.
The cop configuration now marks the cop as "not safe".
=> Improve documentation for Lint/UselessSetterCall

CHANGELOG.md, config/default.yml, spec/rubocop/target_finder_spec.rb
Steep 0.12.0 has introduced `Steepfile`.
See <https://github.com/soutaro/steep/blob/v0.12.0/CHANGELOG.md#0120-2020-02-11>.
We can write the Ruby DSL in `Steepfile`. For example:
```ruby
target :app do
check "lib"
signature "sig"
library "set", "pathname"
end
```
=> Add `Steepfile` to default `Include` list

CHANGELOG.md, lib/rubocop/cop/style/ternary_parentheses.rb, spec/rubocop/cop/style/ternary_parentheses_spec.rb
Fix #7716.
This PR fixes an infinite loop error for `Style/TernaryParentheses` with `Style/RedundantParentheses` when using `EnforcedStyle: require_parentheses_when_complex`.
```ruby
!foo.nil? ? 1 : 2
```
```yaml
Style/TernaryParentheses:
EnforcedStyle: require_parentheses_when_complex
```
First, auto-corrected by `Style/TernaryParentheses` (`EnforcedStyle: require_parentheses_when_complex`).
```console
% bundle exec rubocop -a --only Style/TernaryParentheses
Offenses:
example.rb:2:1: C: [Corrected] Style/TernaryParentheses: Use parentheses
for ternary expressions with complex conditions.
!foo.nil? ? 1 : 2
^^^^^^^^^^^^^^^^^
```
```diff
% git diff example.rb
diff --git a/7716/example.rb b/7716/example.rb
index ae08c67..31212d8 …
```
=> [Fix #7716] Fix an infinite loop error for `Style/TernaryParentheses`

CHANGELOG.md, lib/rubocop/comment_config.rb, lib/rubocop/cop/lint/redundant_cop_enable_directive.rb, manual/configuration.md, manual/cops_lint.md, spec/rubocop/comment_config_spec.rb
A hash mark `#` on a comment line doesn't start a new comment, so we have to pretend that it does in order to support disabling of cops on a single comment line.
=> [Fix #7708] Support EOL disable comments on comment lines

CHANGELOG.md, lib/rubocop/cop/style/or_assignment.rb, spec/rubocop/cop/style/or_assignment_spec.rb
Fixes #7712.
This PR fixes an incorrect autocorrect for `Style/OrAssignment` when using `elsif` branch.
The following is a reproduction procedure.
```ruby
foo = if foo
foo
elsif
bar
else
'default'
end
```
It is changed to the code with syntax error as follows.
```console
% bundle exec rubocop -a --only Style/OrAssignment
(snip)
foo ||= elsif
bar
else
'default'
example.rb:1: syntax error, unexpected `elsif'
foo ||= elsif
```
The or assignment operator replaced when using `elsif` branch is complicated.
The PR will accept the above case without offense.
=> [Fix #7712] Fix an incorrect autocorrect for `Style/OrAssignment`

CHANGELOG.md, lib/rubocop/cop/style/nested_parenthesized_calls.rb, spec/rubocop/cop/style/nested_parenthesized_calls_spec.rb
Closes https://github.com/rubocop-hq/rubocop/issues/7719
=> [Fix #7719] Fix `Style/NestedParenthesizedCalls` cop for newline

lib/rubocop/cop/mixin/hash_transform_method.rb
Follow up of https://github.com/rubocop-hq/rubocop/pull/7663/files#r381151515.
This PR removes a print debug code.
It would be better if print debug could be detected by project automation in the future.
=> Remove a print debug code

CHANGELOG.md, relnotes/v0.80.0.md
This pull request adds the cop name to the CHANGELOG. It will improve grep-ability.
I tried updating RuboCop and got the following message.
```bash
$ rubocop 
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
- Style/HashEachMethods
- Style/HashTransformKeys
- Style/HashTransformValues
Inspecting 0 files
0 files inspected, no offenses detected
```
But I cannot find `Style/HashEachMethods` cop form the CHANGELOG. It was a bit confusing. So I think this change will be helpful for users who update RuboCop.
=> Mention `Style/HashEachMethods` cop name in the CHANGELOG

CHANGELOG.md, lib/rubocop/cop/style/redundant_condition.rb, spec/rubocop/cop/style/redundant_condition_spec.rb
This fixes #7709. The solution is to wrap the range in parentheses. This did make me wonder whether it would be valuable to have a lint cop that checks for double pipe or followed by a range.
=> 7709 redundant condition range

CHANGELOG.md, lib/rubocop/cop/style/inverse_methods.rb, spec/rubocop/cop/style/inverse_methods_spec.rb
Closes https://github.com/rubocop-hq/rubocop/issues/7682
=> [Fix #7682] Fix `Style/InverseMethods` autofix leaving parenthesis

mkdocs.yml
Right now https://docs.rubocop.org/en/latest/versioning.md gives 404
error. It is fixed by adding the "Versioning" doc to list of documents.
=> Add missing "Versioning" doc to the manual

manual/versioning.md
=> Remove spurious "and" from the versioning doc

manual/node_pattern.md
There was an unclosed code block that was messing up everything below "` for descendants"
[This is the documentation](https://docs.rubocop.org/en/latest/node_pattern/#using-node-matcher-macros)
And it looks like:
=> Fix  Node Pattern documentation

config/default.yml, manual/cops_style.md
This PR added `VersionAdded` to `Style/HashTransformKeys` and `Style/HashTransformValue`.
This Cops was added at #7663 and published at 0.80.0.
=> Add `VersionAdded` to Style/HashTransformKeys, Style/HashTransformValues

CHANGELOG.md, lib/rubocop/config.rb, lib/rubocop/config_loader.rb, spec/rubocop/cli/cli_options_spec.rb
Fixes #7745.
This PR suppresses a pending cop warnings when pending cop's department is disabled.
```console
% rubocop -V
0.80.0 (using Parser 2.7.0.2, running on ruby 2.7.0 x86_64-darwin17)
```
```yaml
Style:
Enabled: false
```
The following pending cop warning is displayed for disabled Style department.
```console
The following cops were added to RuboCop, but are not configured. Please
set Enabled to either `true` or `false` in your `.rubocop.yml` file:
- Style/HashEachMethods
- Style/HashTransformKeys
- Style/HashTransformValues
Inspecting 0 files
0 files inspected, no offenses detected
```
A pending cop warning is not displayed for disabled Style department.
```console
Inspecting 0 files
0 files inspected, no offenses …
```
=> [Fix #7745] Suppress pending cop warnings when department is disabled

CHANGELOG.md, lib/rubocop/cop/layout/line_length.rb, spec/rubocop/cop/layout/line_length_spec.rb
Fixes #7759.
This PR fixes the following error for `Layout/LineLength` cop when using lambda syntax that argument is not enclosed in parentheses.
```ruby
-> x {}
```
```console
% bundle exec rubocop --only Layout/LineLength -d
(snip)
An error occurred while Layout/LineLength cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/7759/example.rb:1:0.
undefined method `begin_pos' for nil:NilClass
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/layout/line_length.rb:127:in
`check_for_breakable_block'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/layout/line_length.rb:71:in
`on_block'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/commissioner.rb:57:in
`block (2 levels) in trigger_responding_cops' …
```
=> [Fix #7759] Fix an error for `Layout/LineLength`

CHANGELOG.md, lib/rubocop/config.rb, lib/rubocop/config_loader.rb, manual/versioning.md, spec/rubocop/cli/cli_options_spec.rb
Follow up of https://github.com/rubocop-hq/rubocop/pull/7757#issuecomment-591358283.
When warning about a pending cop, this PR displays the version with the cop added.
```console
% rubocop
The following cops were added to RuboCop, but are not configured. Please
set Enabled to either `true` or `false` in your `.rubocop.yml` file:
- Style/HashEachMethods
- Style/HashTransformKeys
- Style/HashTransformValues
```
```console
% rubocop
The following cops were added to RuboCop, but are not configured. Please
set Enabled to either `true` or `false` in your `.rubocop.yml` file:
- Style/HashEachMethods (0.80)
- Style/HashTransformKeys (0.80)
- Style/HashTransformValues (0.80)
For more information: https://docs.rubocop.org/en/latest/versioning/
```
Before submitting the PR make …
=> Display version with cop added when pending cops warning

manual/basic_usage.md
This PR adds `--safe` command-line flag to Basic Usage manual.
=> Add `--safe` command-line flag to Basic Usage

CHANGELOG.md, config/default.yml, lib/rubocop/cop/layout/array_alignment.rb, manual/cops_layout.md, spec/rubocop/cop/layout/array_alignment_spec.rb
Hello 👋
We have `with_fixed_indentation` option for `Layout/ArgumentAlignment` and `Layout/ParameterAlignment`. So we can write our code this way:
```ruby
foo :bar,
:baz
```
```ruby
method_call(a,
b)
```
And we in our company decided to use this style (with `with_fixed_indentation`) for all alignments. But we can't use this this option for `Layout/ArrayAlignment` because it doesn't support this flag.
We want to write multi-line arrays in this style:
```ruby
array = [a,
b]
```
in order to have the same style of code in whole project in all cases.
I've used these cops as examples:
- https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/layout/argument_alignment.rb
- https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/layout/parameter_alignment.rb
Extended exciting …
=> [Fix #7654] Support with_fixed_indentation option for Layout/ArrayAlignment cop

Rakefile, tasks/spec_runner.rake
This PR removes the following deprecated development Rake tasks.
```console
% cd repo/to/rubocop
% bundle exec rake -T | grep Deprecated
rake parallel                             # Deprecated: Run test and
RuboCop in parallel
rake parallel:ascii_spec                  # Deprecated: Run RSpec code
examples in parallel with ASCII encoding
rake parallel:spec                        # Deprecated: Run RSpec code
examples in parallel
```
These tasks has been removed from RuboCop 0.59.1.
https://github.com/rubocop-hq/rubocop/commit/19b69083d2dc9960700e2ecc29040327a3913feb
These are used only for RuboCop repository development, they will be safely removed.
=> Remove deprecated development Rake tasks

CHANGELOG.md, lib/rubocop/formatter/junit_formatter.rb, spec/rubocop/formatter/junit_formatter_spec.rb
Fixes #7733.
This PR fixes rubocop-junit-formatter imcompatibility XML for JUnit formatter
The original rubocop-junit-formatter displayed all cops with or without offenses.
https://github.com/mikian/rubocop-junit-formatter/blob/v0.1.4/lib/rubocop/formatter/junit_formatter.rb#L9
It then displays all cops in XML elements, like the original rubocop-junit-formatter.
In the future, it would be preferable to display only enabled cops.
https://github.com/mikian/rubocop-junit-formatter/blob/v0.1.4/lib/rubocop/formatter/junit_formatter.rb#L7-L8
=> [Fix #7733] Fix rubocop-junit-formatter imcompatibility XML

CHANGELOG.md, lib/rubocop/ast/node.rb, spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb
Fixes #7779.
This PR fixes a false positive for `Style/MultilineMethodCallIndentation` when using Ruby 2.7's numbered parameter.
=> [Fix #7779] Fix a false positive for `Style/MultilineMethodCallIndentation`

CHANGELOG.md, lib/rubocop/cop/style/hash_transform_keys.rb, lib/rubocop/cop/style/hash_transform_values.rb, spec/rubocop/cop/style/hash_transform_keys_spec.rb, spec/rubocop/cop/style/hash_transform_values_spec.rb
Because arrays do not have `transform_values` & `transform_keys` methods. 
Closes https://github.com/rubocop-hq/rubocop/issues/7767
=> [Fix #7767] Skip array literals in `Style/HashTransformValues` & `Style/HashTransformKeys`

CHANGELOG.md, config/default.yml, lib/rubocop/cop/style/collection_methods.rb, manual/cops_style.md, spec/rubocop/cop/style/collection_methods_spec.rb
Updates `Style/CollectionMethods` cop to prefer `include?` over `member?`.
Per [ruby-style-guide#804](https://github.com/rubocop-hq/ruby-style-guide/issues/804).
=> Prefer `include?` over `member?` in `Style/CollectionMethods`

CHANGELOG.md, rubocop.gemspec
Updating rubocop.gemspec to allow `unicode-display_width:1.7.0`
All tests pass against version 1.7.0, so we assume that there are no breaking changes and the dependency is safe to update.
=> Allow unicode-display_width 1.7.0

config/default.yml, manual/cops_lint.md, manual/cops_migration.md, manual/cops_style.md, spec/project_spec.rb
All cops have `VersionAdded`. This PR adds `VersionAdded` metadata to cops who missing the version.
The cops who were missing `VersionAdded` are:
- Migration/DepartmentName (0.75) ... https://github.com/rubocop-hq/rubocop/commit/1f84782
- Lint/RedundantSplatExpansion (0.76) ... https://github.com/rubocop-hq/rubocop/commit/ba43182
- Lint/ToJSON (0.66) ... https://github.com/rubocop-hq/rubocop/commit/a823c57
Also `VersionAdded` does not include tiny version.
This PR will add these rules to the project_spec.rb.
=> Add `VersionAdded` metadata to cops who missing the version

CHANGELOG.md, config/default.yml, lib/rubocop/cop/lint/suppressed_exception.rb, lib/rubocop/formatter/clang_style_formatter.rb, lib/rubocop/formatter/tap_formatter.rb, lib/rubocop/processed_source.rb, manual/cops_lint.md
Follow https://github.com/rubocop-hq/rubocop/issues/7052#issuecomment-494360787.
This PR changes `AllowComments` option of `Lint/SuppressedException` to true by default.
As is used in RuboCop repo itself, it is a common practice to use source code comments to explain when exception handling is not performed.
I think that `Suppressing Exceptions` rule can be refined to a suitable example.
https://github.com/rubocop-hq/ruby-style-guide#dont-hide-exceptions
=> Change `AllowComments` of `Lint/SuppressedException` to true by default

CHANGELOG.md, lib/rubocop/cop/style/redundant_sort.rb, spec/rubocop/cop/style/redundant_sort_spec.rb
This PR supports Ruby 2.7's numbered parameter for `Style/RedundantSort`.
=> Support Ruby 2.7's numbered parameter for `Style/RedundantSort`

CHANGELOG.md, lib/rubocop/cop/layout/block_end_newline.rb, spec/rubocop/cop/layout/block_end_newline_spec.rb
Fixes #7791.
This PR fixes an error on auto-correction for `Layout/BlockEndNewline` when `}` of multiline block without processing is not on its own line.
=> [Fix #7791] Fix an error for `Layout/BlockEndNewline`

CHANGELOG.md, lib/rubocop/ast/node.rb, spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb
Resolves #7795.
This PR makes `Layout/EmptyLineAfterGuardClause` aware of `and return`.
It was proposed based on the following code controlled by Rails controller.
```ruby
render :foo and return if condition
do_something
```
I think that it can be generalized as a control flow.
```ruby
foo(arg) and return if condition
do_something
```
So it will be newly detected by `Layout/EmptyLineAfterGuardClause` cop.
=> [Fix #7795] Make `Layout/EmptyLineAfterGuardClause` aware of `and return`

CHANGELOG.md, lib/rubocop/cop/mixin/end_keyword_alignment.rb, spec/rubocop/cop/layout/end_alignment_spec.rb
Resolves #7778.
This PR resolves a false positive for `Layout/EndAlignment` when a non-whitespace is used before the `end` keyword.
```console
if cond
else 'foo' end
% bundle exec rubocop -a --only Layout/EndAlignment
(snip)
W
Offenses:
example.rb:2:12: W: Layout/EndAlignment: end at 2, 11 is not aligned
with if at 1, 0.
else 'foo' end
^^^
```
This PR changes to not offense it.
I think the responsibility will be clear if different (maybe new) cop like `Layout/BlockEndNewline` cop handle the offense case.
So I think this role is preferably separated by `Layout/EndAlignment` cop.
=> [Fix #7778] Fix a false positive for `Layout/EndAlignment`

CHANGELOG.md, lib/rubocop/cop/lint/safe_navigation_chain.rb, spec/rubocop/cop/lint/safe_navigation_chain_spec.rb
This PR supports Ruby 2.7's numbered parameter for `Lint/SafeNavigationChain`.
=> Support Ruby 2.7's numbered parameter for `Lint/SafeNavigationChain`

config/default.yml, lib/rubocop/cop/style/trailing_comma_in_arguments.rb, lib/rubocop/cop/style/trailing_comma_in_array_literal.rb, lib/rubocop/cop/style/trailing_comma_in_hash_literal.rb, manual/cops_style.md
Close #7536
Improved documentation for `Style/TrailingCommaInArguments`, `Style/TrailingCommaInArrayLiteral` and `Style/TrailingCommaInHashLiteral` by adding following things:
- Added description for `EnforcedStyleForMultiline` configuration options. 
- Added more examples to distinguish between  `comma` and `consistent_comma`
- Corrected Style/TrailingCommaInArrayLiteral and Style/TrailingCommaInHashLiteral related comments in `config/default.yml `
----
=> [Fix #7536] Improve documentation for Style/TrailingCommaIn… cops

lib/rubocop/cop/lint/nested_method_definition.rb, manual/cops_lint.md
As-is, the code examples for the `Lint/NestedMethodDefinition` cop are wrong: both `class_eval` and `module_exec` are available on the class and module level respectively, and not on an instance. Only the eigenclass example, and, ironically, the "bad" example of just using `def` directly, actually work.
=> Nested methods doc fix

CHANGELOG.md, lib/rubocop/cop/lint/erb_new_arguments.rb, spec/rubocop/cop/lint/erb_new_arguments_spec.rb
This PR fixes the following error for `Lint/ErbNewArguments` cop when inspecting `ActionView::Template::Handlers::ERB.new`.
```console
% cd path/to/rails/rails # rails/rails@f265e0dd
% bundle exec rubocop -d --only Lint/ErbNewArguments
actionview/lib/action_view/template/handlers.rb
For /Users/koic/src/github.com/rails/rails: configuration from
/Users/koic/src/github.com/rubocop-hq/rubocop/config/default.yml
Scanning
/Users/koic/src/github.com/rails/rails/actionview/lib/action_view/template/handlers.rb
An error occurred while Lint/ErbNewArguments cop was inspecting
/Users/koic/src/github.com/rails/rails/actionview/lib/action_view/template/handlers.rb:14:45.
undefined method `each_with_index' for nil:NilClass
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/li …
```
=> Fix an error for `Lint/ErbNewArguments` cop

manual/cops_lint.md, spec/rubocop/cli/cli_options_spec.rb
This PR fixes the following two CI errors.
First, this PR updates the metadata for `Lint/RaiseException`.
Follow d5b25ef.
Second, this PR commits a workaround patch. It should be updated to a test that is not affected by a pending department in future.
```console
% bundle exec rspec ./spec/rubocop/cli/cli_options_spec.rb:307
(snip)
Run options: include {:focus=>true, :locations=>{"./spec/rubocop/cli/cli_options_spec.rb"=>[307]}}
Randomized with seed 31394
F
Failures:
1) RuboCop::CLI --only when one cop is given when specifying a pending cop when Style department is disabled does not show pending cop warning
Failure/Error: expect(output).to eq(inspected_output)
expected: "Inspecting 2 files\n..\n\n2 files inspected, no offenses detected\n"
got: "The following cops were added to RuboCop, …
```
=> Fix CI errors

CHANGELOG.md, lib/rubocop/cop/style/inverse_methods.rb
These two cops had an interaction between their auto-corrections which produced code that wasn't semantically equivalent to the original. Example:
```ruby
[].reject { |x| !x }
```
was being corrected to:
```ruby
[].select(&:!)
```
This change fixes that by marking `Style/InverseMethods` auto-correct as incompatible with that of `Style/SymbolProc`.
=> [Fix #7236] Prevent bad auto-correction from Style/InverseMethods and Style/SymbolProc

CHANGELOG.md, config/default.yml, lib/rubocop/cop/style/end_block.rb, manual/cops_style.md, spec/rubocop/cop/style/end_block_spec.rb
`Style/EndBlock` seems like a simple cop & should support safe auto-correction.
=> Add auto-correction for `Style/EndBlock` cop

CHANGELOG.md, config/default.yml, lib/rubocop/cop/lint/unused_method_argument.rb, manual/cops_lint.md, spec/rubocop/cop/lint/unused_method_argument_spec.rb
=> [Fix #7739] Allow methods raising NotImplementedError in `Lint/UnusedMethodArgument`

CHANGELOG.md, config/default.yml, lib/rubocop/ast/node.rb, lib/rubocop/cop/style/access_modifier_declarations.rb, manual/cops_style.md, spec/rubocop/cop/style/access_modifier_declarations_spec.rb
=> [Fix #7740] Make `Style/AccessModifierDeclarations` not flag symbol method-name

lib/rubocop/cop/lint/loop.rb, manual/cops_lint.md, spec/rubocop/cop/lint/loop_spec.rb
The given examples were not equivalent, because begin/end ensures that the body runs at least once, while the proposed examples don't.
=> Fix "good" examples for Lint/Loop cop

CHANGELOG.md, config/default.yml, lib/rubocop/cop/lint/boolean_symbol.rb, manual/cops_lint.md, spec/rubocop/cop/lint/boolean_symbol_spec.rb
=> Add auto-correction for `Lint/BooleanSymbol` cop

CHANGELOG.md, lib/rubocop/cop/migration/department_name.rb, spec/rubocop/cop/migration/department_name_spec.rb
Fixes #7814.
This PR fixes a false positive for `Migrate/DepartmentName` cop when inspecting an unexpected disabled comment format.
e.g. `# rubocop:disable Style:BlockComments`
The above expected format is `# rubocop:disable Style/BlockComments`.
`Migration/DepartmentName` cop's role is to complement a department name.
The role would be simple if another feature could detect unexpected disable comment format.
=> [Fix #7814] Fix a false positive for `Migrate/DepartmentName` cop

CHANGELOG.md, config/default.yml, lib/rubocop/cop/mixin/method_complexity.rb, manual/cops_metrics.md, spec/rubocop/cop/metrics/abc_size_spec.rb, spec/rubocop/cop/metrics/cyclomatic_complexity_spec.rb, spec/rubocop/cop/metrics/perceived_complexity_spec.rb
**Rationale:**
At work we make extensive use of functional objects to encapsulate business transactions. These objects will have a single public method `#call`, which stacks all the edge-cases as guard clauses towards the top.
It usually looks something like:
```ruby
def call
#
return error(post.errors.full_messages.to_sentence) unless post.valid?
return error("Author har been blocked from posting.") if author.blocked?
return error("Author doesn't have an active subscription.") unless author.current_subscription.active?
#
create_post!
send_notifications!
#
success(post: post)
end
```
We find this makes it very easy to understand what's going on, business transactions become composable and easy to test.
This almost always leads to `Metrics` cops violations for `#call`. However, the method …
=> Support IgnoredMethod configuration in method complexity cops

CHANGELOG.md, lib/rubocop/ast/builder.rb, lib/rubocop/ast/node.rb, lib/rubocop/ast/node/block_node.rb, lib/rubocop/cop/style/lambda.rb, spec/rubocop/ast/block_node_spec.rb, spec/rubocop/cop/style/lambda_spec.rb
This PR supports Ruby 2.7's numbered parameter for `Style/Lambda`.
And this PR maps `numblock` to `BlockNode`.
I considered the introduction of `NumblockNode`, but most will overlap with `BlockNode`. IMHO, probably `NumblockNode` class does not need to be split now.
=> Support Ruby 2.7's numbered parameter for `Style/Lambda`

CHANGELOG.md, lib/rubocop/cop/layout/multiline_method_call_indentation.rb, spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb
When block passed to class constant.
Closes #7825 
=> [Fix #7825] Fix crash for `Layout/MultilineMethodCallIndentation`

CHANGELOG.md, lib/rubocop/cop/style/hash_each_methods.rb, spec/rubocop/cop/style/hash_each_methods_spec.rb
Fixes #7831.
This PR fix a false positive for `Style/HashEachMethods` when there is no receiver for `keys` and `values`.
The following is an examples.
```ruby
values.each { |k, v| do_something(k, v) }
keys.each { |k, v| do_something(k, v) }
```
False negatives occur in cases such as object that inherit Hash, but that is perhaps a corner case.
I think it is more worthwhile to resolve the false positives with common naming of `values`.
=> [Fix #7831] Fix a false positive for `Style/HashEachMethods`

lib/rubocop/cop/style/nested_parenthesized_calls.rb, manual/cops_style.md
method1(method2 arg, method3, arg) is not equivalent to method1(method2 arg, method3, arg)
method1(method2 arg, method3 arg) would be incorrect as well
method1(method2 arg) vs method1(method2(arg)) would be an example that illustrates the code standards and is correct in terms of syntax
=> Fix Style/NestedParenthesizedCalls docs

CHANGELOG.md, relnotes/v0.81.0.md
I fix typo of PR link in CHANGELOG
=> Fix typo in CHANGELOG

CHANGELOG.md, lib/rubocop/cop/lint/raise_exception.rb, spec/rubocop/cop/lint/raise_exception_spec.rb
Resolve part of #7842.
This PR fixes a false positive for `Lint/RaiseException` when raising Exception with explicit namespace.
`Exception` belonging to a namespace is expected to inherit `StandardError`.
This PR makes `Lint/RaiseException` aware of the following differences:
```ruby
Gem::Exception.new.is_a?(StandardError) # => true
Exception.new.is_a?(StandardError)      # => false
```
On the other hand, the following case have not been resolved by this PR.
```ruby
module Gem
def self.foo
raise Exception
end
end
Gem.foo #=> Gem::Exception
```
The above case will be resolved separately from this PR.
=> [#7842] Fix a false positive for `Lint/RaiseException`

CHANGELOG.md, lib/rubocop/cop/lint/uri_regexp.rb, spec/rubocop/cop/lint/uri_regexp_spec.rb
=> Fix `Lint/UriRegexp` to register offense with array arguments

CHANGELOG.md, lib/rubocop/cop/style/trailing_comma_in_block_args.rb, spec/rubocop/cop/style/trailing_comma_in_block_args_spec.rb
Fixes #7841.
This PR fixes an error for `Style/TrailingCommaInBlockArgs` cop when lambda literal (`->`) has multiple arguments. It will not be checked in the case of lambda literal because lambda literal (`->`) never have a block arguments.
```console
% ruby -ce '-> (foo, bar) { do_something(foo, bar) }'
Syntax OK
% ruby -ce '-> { |foo| do_something }'
-e:1: syntax error, unexpected '|'
-> { |foo| do_something }
^
% ruby -ce '-> (foo, bar,) { do_something(foo, bar) }'
-e:1: syntax error, unexpected ')'
-> (foo, bar,) { do_something(foo, bar) }
^
-e:1: syntax error, unexpected '}', expecting end-of-input
r,) { do_something(foo, bar) }
^
```
=> [Fix #7841] Fix an error for `Style/TrailingCommaInBlockArgs` cop

.rubocop_todo.yml, CHANGELOG.md, config/default.yml, lib/rubocop/cli.rb, lib/rubocop/config.rb, lib/rubocop/config_loader.rb, lib/rubocop/config_validator.rb, lib/rubocop/cop/registry.rb, lib/rubocop/options.rb, lib/rubocop/runner.rb, manual/basic_usage.md, manual/versioning.md, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/registry_spec.rb, spec/rubocop/options_spec.rb
Resolves #7850.
This PR will add `--enable-pending-cops` and `--disable-pending-cops` command-line options and `NewCops` will be provided in .rubocop.yml.
When `NewCops` is `enable`, pending cops are enabled in bulk.
```yaml
AllCops:
NewCops: enable
```
Can be overridden by the `--enable-pending-cops` command-line option.
When `NewCops` is `disable`, pending cops are disabled in bulk.
```yaml
AllCops:
NewCops: disable
```
Can be overridden by the `--disable-pending-cops` command-line option.
The default value of `NewCops` is `pending`.
=> [Fix #7850] Make it possible to enable/disable pending cops

manual/configuration.md
The documentation looks incorrect regarding the the todo escape hatch. This change fixes that issue.
=> Fix small `rubocop:todo` typo.

CHANGELOG.md, lib/rubocop/cop/corrector.rb, spec/rubocop/cop/corrector_spec.rb
Please expose `@source_rewriter`'s `wrap` method which can be particularly useful (equivalent to `insert_before` + `insert_after`)
=> Add #wrap to corrector

CHANGELOG.md, config/default.yml, lib/rubocop/cop/style/case_equality.rb, manual/cops_style.md, spec/rubocop/cop/style/case_equality_spec.rb
For some constant, specially direct subclasses of `BasicObject`, using `is_a?` is not an option since `BasicObject` doesn't respond to that method.
In those cases it would be interesting to allow this config so apps can opt-out that cop only when the receiver is a constant.
=> Add option to allow case equality when the receiver is a constant

.rubocop_todo.yml, lib/rubocop/ast/node/array_node.rb, lib/rubocop/config_loader.rb, lib/rubocop/cop/lint/percent_string_array.rb, spec/rubocop/ast/array_node_spec.rb
This PR suppresses a RuboCop offenses when using `rubocop --enable-pending-cops`.
```console
% path/to/rubocop
% ./exe/rubocop --enable-pending-cops
(snip)
Offenses:
lib/rubocop/config_loader.rb:58:14: C: Style/HashEachMethods: Use
each_key instead of keys.each.
hash.keys.each do |key|
^^^^^^^^^
lib/rubocop/cop/lint/percent_string_array.rb:45:18: C:
Style/HashEachMethods: Use each_value instead of values.each.
node.values.each do |value|
^^^^^^^^^^^
1142 files inspected, 2 offenses detected
```
`Style/HashEachMethods` cop will be enabled by default in RuboCop 1.0.
And this PR adds `each_value` method to `ArrayNode` for prevents the following `NoMethodError`.
```console
RuboCop::ErrorWithAnalyzedFileLocation:
cause: #<NoMethodError: undefined method `each_value' for …
```
=> Suppress an offenses when using `rubocop --enable-pending-cops`

CHANGELOG.md
I fixed typo of PR link and added missing PR link in CHANGELOG.
=> Fix typo of pr link and add missing pr link in CHANGELOG

CHANGELOG.md, lib/rubocop/cop/lint/boolean_symbol.rb, spec/rubocop/cop/lint/boolean_symbol_spec.rb
It replaces a boolean symbol in a hash value as if it were a key,
generating a broken piece of code.
```ruby
{ null: :false }
{ null :false => }
{ null: false }
```
```ruby
{ false: :false }
{ false => :false => }
{ false => false }
```
=> Fix an auto-correction bug in Lint/BooleanSymbol

CHANGELOG.md, config/default.yml, lib/rubocop/cop/lint/raise_exception.rb, manual/cops_lint.md, spec/rubocop/cop/lint/raise_exception_spec.rb
Fixes #7842.
This PR adds `AcceptImplicitNamespaces` option to `Lint/RaiseException`.
Users can specify and accept an implicit namespace as follows:
```yaml
Lint/RaiseException:
AllowImplicitNamespaces:
- 'Gem'
```
```ruby
module Gem
def self.foo
raise Exception
end
end
Gem.foo #=> Gem::Exception
```
`Gem` is specified by default.
https://ruby-doc.org/stdlib-2.7.0/libdoc/rubygems/rdoc/Gem/Exception.html
This way does not prevent all false positives, but it expect some cases can be solved.
=> [Fix #7842] Add `AcceptImplicitNamespaces` to `Lint/RaiseException`

lib/rubocop/cop/style/trailing_comma_in_arguments.rb, manual/cops_style.md
The existing documentation for the `no_comma` option does not clearly indicate that the cop requires that there is no comma present. It only states that a comma is not required.
Also, there is a grammatical error in the existing documentation.
=> Update docs for TrailingCommaInArguments cop

config/default.yml, lib/rubocop/target_ruby.rb, manual/cops_layout.md, manual/cops_style.md
Follow #7384, #7857, and #7869.
This PR fixes the next release version with 0.82 because RuboCop 0.81 has been released. This version (0.82) is based on #7851.
=> Fix the next release version

.rubocop.yml, lib/rubocop/config.rb, lib/rubocop/config_loader_resolver.rb
Pending cops will be enabled by default in RuboCop 1.0.
This PR enables `NewCops` for RuboCop development. It will be a verification that enables pending cops.
And this PR suppresses the following offense.
```console
% cd path/to/rubocop
(snip)
lib/rubocop/config_loader_resolver.rb:184:7: C:
Style/HashTransformValues: Prefer transform_values over Hash[_.map {...}].
Hash[config.map { |cop, params| [cop, yield(params)] }]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1144 files inspected, 1 offense detected
```
=> Enable `NewCops` for RuboCop development

CHANGELOG.md, lib/rubocop/ast/node.rb, lib/rubocop/cop/style/if_unless_modifier.rb, spec/rubocop/cop/style/if_unless_modifier_spec.rb
`Style/IfUnlessModifier` can autocorrect long lines which use an if/unless modifier to
`if...end` form. It can also autocorrect `if...end` form to modifier form if the body
is only a single line.
Obviously, there is the potential for an infinite autocorrect loop here. The cop tried
to avoid that by checking whether the `if...end` conditional would overflow the maximum
length of a line if converted to modifier form.
However, the check is based only on the size of the conditional code itself and not
*other* statements which may follow after `end`, like this:
if condition
do_this
end; other_statement; yet_another
This (hideous) code could result from an autocorrect of something like this:
do_this if condition; other_statement; yet_another
So the cop still can and does cause infinite loops. A …
=> Avoid infinite loop when autocorrecting with Style/IfUnlessModifier

lib/rubocop/cop/layout/space_around_method_call_operator.rb, spec/rubocop/cop/layout/space_around_method_call_operator_spec.rb
This PR fixes the following false positive for `Layout/SpaceAroundMethodCallOperator` cop when there is a space between `.` operator and a comment.
```ruby
foo. # comment
bar.baz
```
```console
% rubocop --only Layout/SpaceAroundMethodCallOperator
(snip)
C
Offenses:
example.rb:1:5: C: Layout/SpaceAroundMethodCallOperator: Avoid using
spaces around a method call operator.
foo. # comment
^
```
Also this PR does not add to the changelog entry because `Layout/SpaceAroundMethodCallOperator` cop has not been released yet.
=> Fix a false positive for `Layout/SpaceAroundMethodCallOperator`

CHANGELOG.md, lib/rubocop/cop/style/case_equality.rb, spec/rubocop/cop/style/case_equality_spec.rb
When the method receiver is implicit it was failing with a NoMethodError in `nil` error.
* [ x Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
=> Fix `Style/CaseEquality` when `AllowOnConstant` is `true`

CHANGELOG.md, config/default.yml, lib/rubocop/cop/layout/trailing_whitespace.rb, manual/cops_layout.md
Fixes #7860.
This PR changes `AllowInHeredoc` option of `Layout/TrailingWhitespace` to `true` by default. The default behavior will be more safe.
=> [Fix #7860] Change `AllowInHeredoc` option of `Layout/TrailingWhitespace` to `true`

CHANGELOG.md, lib/rubocop/cli.rb, spec/rubocop/cli/cli_options_spec.rb
Transferring options to the `ConfigLoader` must be done before we validate the `--parallel` flag against configuration. Since we cache the configuration when reading it to perform validation, the cached configuration will not take all the given options into account, which leads to different behavior when running the actual inspection if the `--parallel` flag is given.
=> [Fix #7790] Set options in ConfigLoader earlier

CHANGELOG.md, lib/rubocop/cli.rb, spec/rubocop/cli/cli_options_spec.rb
This fixes another problem that's similar to the one reported in #7790. The problem is still that configuration is read and cached when we validate options vs configuration. By acting on all options first, we make sure that the first time we read configuration, it's done according to the given options. Specifically, it's the `--force-default-config` option that's now being respected.
=> [Fix #7881] Call act_on_options earlier in CLI#run()

CHANGELOG.md, lib/rubocop/cop/layout/multiline_operation_indentation.rb, manual/cops_layout.md
Update the cop documentation to make it more clear which operands should be aligned, and which should always be indented.
=> [Fix #7094] Clarify alignment in MultilineOperationIndentation

manual/basic_usage.md
[This](https://github.com/rubocop-hq/rubocop/commit/61090b15d99c0c4b174d9c50c92ccab039f1af85) commit broke the table and this PR fixes it.
* n/a Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* n/a Added tests.
* n/a Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* n/a Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.
=> Fix the command flags table

CHANGELOG.md, lib/rubocop/cop/style/multiline_when_then.rb, manual/cops_style.md, spec/rubocop/cop/style/multiline_when_then_spec.rb
Fixes #7635
This PR fixes a false positive for `Style/MultilineWhenThen` when `then` required for a body of `when` is used.
=> [Fix #7635] Fix a false positive for `Style/MultilineWhenThen`

manual/versioning.md
On https://docs.rubocop.org/en/latest/versioning/, the first sentence under Release Policy reads:
> We're following http://semver.org/[SemVer] (as much as one can be following it when the major version is 0).
This PR changes the semver link to a markdown link. The other line changes are to keep the paragraph aligned to textwidth=72.
=> Fix semantic versioning link

.simplecov, CHANGELOG.md, config/default.yml, spec/rubocop/target_finder_spec.rb
This list looks fairly comprehensive, so lets add .simplecov the ruby config file for simplecov gem
https://github.com/colszowka/simplecov#using-simplecov-for-centralized-config
=> Add .simplecov to rubocop default include list

lib/rubocop/config_loader.rb, spec/rubocop/cli/cli_options_spec.rb
This PR displays `N/A` for pending cop warnings without `VersionAdded` specified.
3rd party cop may not have `VersionAdded` specified.
```console
% rubocop
The following cops were added to RuboCop, but are not configured. Please
set Enabled to either `true` or `false` in your `.rubocop.yml` file:
- Style/VersionAddedIsNotSpecified ()
For more information: https://docs.rubocop.org/en/latest/versioning/
```
```console
% rubocop
The following cops were added to RuboCop, but are not configured. Please
set Enabled to either `true` or `false` in your `.rubocop.yml` file:
- Style/VersionAddedIsNotSpecified (N/A)
For more information: https://docs.rubocop.org/en/latest/versioning/
```
[1]: …
=> Display `N/A` for pending cop warnings without `VersionAdded` specified

CHANGELOG.md, lib/rubocop/options.rb, spec/rubocop/cli/cli_options_spec.rb
This PR fixes an error when running `rubocop --only` or `rubocop --except` options without cop name argument.
```consle
% rubocop --only
undefined method `empty?' for nil:NilClass
/Users/koic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/options.rb:87:in `block in add_cop_selection_csv_option'
/Users/koic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-0.82.0/lib/rubocop/options.rb:206:in `block in option'
/Users/koic/.rbenv/versions/2.7.1/lib/ruby/2.7.0/optparse.rb:1589:in `block in parse_in_order'
/Users/koic/.rbenv/versions/2.7.1/lib/ruby/2.7.0/optparse.rb:1575:in `catch'
```
```console
% rubocop --only
--only argument should be [COP1,COP2,...].
```
The same is true for `rubocop --except`. …
=> Fix an error when running `--only` or `--except` options

CHANGELOG.md, lib/rubocop/cop/mixin/hash_transform_method.rb, spec/rubocop/cop/style/hash_transform_keys_spec.rb, spec/rubocop/cop/style/hash_transform_values_spec.rb
Follow up to rubocop-hq/rubocop-rails#239.
This PR fixes an incorrect autocorrect for `Style/HashTransformKeys` and `Style/HashTransformValues` cops when line break before `to_h` method.
In the future, duplicate code in RuboCop Rails may be removed, making it dependent on RuboCop core code. It centralizes the resolution of problems.
cc @diogoosorio
=> Fix an incorrect autocorrect for hash transform methods

CHANGELOG.md, lib/rubocop/cop/layout/space_around_operators.rb, spec/rubocop/cli/cli_autocorrect_spec.rb, spec/rubocop/cop/layout/space_around_operators_spec.rb
Fixes #7899.
This PR fixes the following infinite loop error for `Layout/SpaceAroundOperators` with `Layout/ExtraSpacing` when using `ForceEqualSignAlignment: true`.
```console
% bundle exec rubocop -V
0.82.0 (using Parser 2.7.1.1, running on ruby 2.7.0 x86_64-darwin17)
Layout/ExtraSpacing:
ForceEqualSignAlignment: true
test123456                = nil
test1234                   = nil
test1_test2_test3_test4_12 =nil
% bundle exec rubocop -a --only Layout/ExtraSpacing,Layout/SpaceAroundOperators
(snip)
Infinite loop detected in /Users/koic/src/github.com/koic/rubocop-issues/7899/example.rb.
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/runner.rb:287:in `check_for_infinite_loop'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/runner.rb …
```
=> [Fix #7899] Fix an infinite loop error for `Layout/SpaceAroundOperators`

CHANGELOG.md, config/default.yml, lib/rubocop/cop/lint/ambiguous_operator.rb, lib/rubocop/cop/lint/ambiguous_regexp_literal.rb, lib/rubocop/cop/lint/useless_else_without_rescue.rb, lib/rubocop/cop/mixin/parser_diagnostic.rb, lib/rubocop/cop/style/lambda_call.rb, lib/rubocop/cop/util.rb, manual/cops_lint.md, spec/rubocop/cop/lint/ambiguous_regexp_literal_spec.rb
This PR supports autocorrection for `Lint/AmbiguousRegexpLiteral`.
=> Support autocorrection for `Lint/AmbiguousRegexpLiteral`

CHANGELOG.md, config/default.yml, lib/rubocop/cop/lint/useless_access_modifier.rb, manual/cops_lint.md, spec/rubocop/cop/lint/useless_access_modifier_spec.rb
This PR supports autocorrection for `Lint/UselessAccessModifier`.
=> Support autocorrection for `Lint/UselessAccessModifier`

CHANGELOG.md, lib/rubocop/config_loader.rb, manual/configuration.md, spec/rubocop/config_loader_spec.rb
A typical use case for this new feature would be excluding files that are ignored by Git.
=> [Fix #595] Add ERB pre-processing for configuration files

CHANGELOG.md, config/default.yml, lib/rubocop/cop/lint/ambiguous_operator.rb, manual/cops_lint.md, spec/rubocop/cop/lint/ambiguous_operator_spec.rb
This PR supports autocorrection for `Lint/AmbiguousOperator`.
=> Support autocorrection for `Lint/AmbiguousOperator`

CHANGELOG.md, lib/rubocop/config.rb, lib/rubocop/config_loader.rb, lib/rubocop/config_loader_resolver.rb, lib/rubocop/config_validator.rb, manual/configuration.md, spec/rubocop/config_loader_spec.rb
Implement the more intuitive functionality, that if a cop sets `Enabled: true` in user configuration, it will be enabled even if its department is disabled in the same configuration file, or in any inherited file.
=> [Fix #7390] Override disabled department for enabled cops

CHANGELOG.md, lib/rubocop/cop/layout/line_length.rb, lib/rubocop/cop/mixin/line_length_help.rb, lib/rubocop/cop/mixin/statement_modifier.rb, spec/rubocop/cop/layout/line_length_spec.rb, spec/rubocop/cop/style/if_unless_modifier_spec.rb
_This is a new attempt at a PR that was first made in #7924. The changes are pretty much the same but the description should be more correct this time._
There's no reason to have two implementations of the same logic. They weren't exactly the same, but I think the one in `LineLengthHelp` was correct, apart from falling back to `Layout/IndentationWidth:Width` if `Layout/IndentationStyle:IndentationWidth` is `nil`, which is now added to match the description of the `Layout/IndentationStyle` parameters in `default.yml`.
Added some examples on line length with tabs indentation in `line_length_spec.rb`.
Updated `if_unless_modifier_spec` to cover the fallback on `Layout/IndentationWidth:Width` better, and removed an example that could not happen in real execution ("without any IndentationWidth …
=> [Fix #7885] Re-use LineLengthHelp for statement modifiers

CHANGELOG.md, lib/rubocop/cop/mixin/frozen_string_literal.rb, spec/rubocop/cop/style/frozen_string_literal_comment_spec.rb
Fixes #7929 
The frozen_string_literal comment can exist anywhere in the "leading comment lines" (i.e. before the first line of ruby code). If it appears after any ruby code it is ignored which does not cause any errors but could cause the absence of an expected error which is bad.
The previous implementation was checking if this comment was one of the first three comments which had two issues:
- The comments it was checking could be anywhere, even after ruby code
- Since it was only checking three comments, it's possible that you can have an appropriate frozen_string_literal but this cop would show an error.
This commit updates the logic to look at all leading comment lines, which may be more or less than three depending on where the first non-comment token is.
Before …
=> [Fix #7929] Accept frozen_string_literal anywhere in leading comment lines

CHANGELOG.md
In https://github.com/rubocop-hq/rubocop/pull/7867 a breaking change was introduced, but not linked in the Change log.  It would be nice to not have to track down which change was introduced and instead link it, following the convention of the other breaking entries.
=> Update Change log to link the breaking change introduced in #7867

CHANGELOG.md, lib/rubocop/cop/lint/parentheses_as_grouped_expression.rb, manual/cops_lint.md, spec/rubocop/cop/lint/parentheses_as_grouped_expression_spec.rb
This PR fixes a false positive for `Lint/ParenthesesAsGroupedExpression` when using an intended grouped parentheses.
```ruby
puts (2 + 3) * 4
```
I noticed this false positive in implementing this cop's auto-correction. So, I plan to open a PR that implements auto-correction separately from this PR.
=> Fix a false positive for `Lint/ParenthesesAsGroupedExpression`

CHANGELOG.md, lib/rubocop/cop/lint/literal_as_condition.rb, manual/cops_lint.md, spec/rubocop/cop/lint/literal_as_condition_spec.rb
This PR fixes a false positive for `Lint/LiteralAsCondition` when using `true` literal in `while` and similar cases.
`while true` is a known idiom. Normally `loop` is used, OTOH `while true` may be selected for speeding up. Users use these methods depending on use case. That was introduced as part of RubyKaigi 2019.
https://rubykaigi.org/2019/presentations/ktou.html
=> Fix a false positive for `Lint/LiteralAsCondition`

CHANGELOG.md, lib/rubocop/options.rb, lib/rubocop/runner.rb, lib/rubocop/target_finder.rb, manual/basic_usage.md, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/options_spec.rb, spec/rubocop/target_finder_spec.rb
The default for file names on the command line that are not recognized as a Ruby file now becomes to inspect the files. With the `--only-recognized-file-types` option, the old behavior of skipping the file is kept.
=> [Fix #4245] Arbitrary files on command line

lib/rubocop/cop/generator.rb, spec/rubocop/cop/generator_spec.rb
Other libraries like `rubocop-rspec` which rely on rubocop's generator
will be able to provide in their own version to be used in generated config. 
example: https://github.com/rubocop-hq/rubocop-rspec/pull/905
=> Allow Generator to take version_added parameter

lib/rubocop/cop/mixin/target_ruby_version.rb, manual/cops_lint.md, manual/cops_style.md, tasks/cops_documentation.rake
Follow up to https://github.com/rubocop-hq/rubocop/pull/7921#discussion_r422328979.
This PR adds required Ruby version to cops manual generated by `rake generate_cops_documentation`.
=> Add required Ruby version to generated cops manual

CHANGELOG.md, config/default.yml, manual/cops_lint.md
Fixes https://github.com/rubocop-hq/rubocop/issues/7936
This PR marks [Lint/BooleanSymbol](https://docs.rubocop.org/en/stable/cops_lint/#lintbooleansymbol) as unsafe. 
As mentioned in the issue, the auto-corrected code is not equivalent to the problem code and therefore can't be run safely without changing the meaning of the code. 
=> [Fix #7936] Mark as Lint/BooleanSymbol unsafe

CHANGELOG.md, config/default.yml, lib/rubocop/cop/style/if_with_semicolon.rb, manual/cops_style.md, spec/rubocop/cop/style/if_with_semicolon_spec.rb
This PR supports autocorrection for `Style/IfWithSemicolon` cop.
And it change to accept the following case that without `else` branch.
```ruby
if cond; run end
```
That case is corrected to a modifier form by `Style/IfUnlessModifier` cop.
```ruby
run if cond
```
Therefore, this cop does not handle it.
=> Support autocorrection for `Style/IfWithSemicolon`

CHANGELOG.md, config/default.yml, lib/rubocop/cop/lint/empty_when.rb, lib/rubocop/cop/lint/suppressed_exception.rb, lib/rubocop/cop/style/empty_method.rb, lib/rubocop/cop/util.rb, manual/cops_lint.md, spec/rubocop/cop/lint/empty_when_spec.rb
Fixes #3696 and #3754.
This PR add `AllowComments` option to `Lint/EmptyWhen` cop.
This option is enabled by default based on user feedback. It is also the same default as the option of `Lint/SuppressedException` set in #7805.
=> [Fix #3696] Add `AllowComments` option to `Lint/EmptyWhen` cop

CHANGELOG.md, config/default.yml, lib/rubocop/cop/lint/parentheses_as_grouped_expression.rb, manual/cops_lint.md, spec/rubocop/cop/lint/parentheses_as_grouped_expression_spec.rb
Follow up to https://github.com/rubocop-hq/rubocop/pull/7909.
This PR supports autocorrection for `Lint/ParenthesesAsGroupedExpression`.
=> Support autocorrection for `Lint/ParenthesesAsGroupedExpression`

CHANGELOG.md, config/default.yml, lib/rubocop/cop/layout/condition_position.rb, manual/cops_layout.md, spec/rubocop/cop/layout/condition_position_spec.rb
This PR supports autocorrection for `Layout/ConditionPosition`.
=> Support autocorrection for `Layout/ConditionPosition`

CHANGELOG.md, lib/rubocop/cop/style/guard_clause.rb, manual/cops_style.md, spec/rubocop/cop/style/guard_clause_spec.rb
Fixes #7928.
This PR fixes a false message for `Style/GuardClause` when using `and` or `or` operators for guard clause in `then` or `else` branches.
The following is an example:
```console
if cond
foo || raise('hi')
else
bar
end
```
```console
% bundle exec rubocop --only Style/GuardClause
(snip)
Offenses:
example.rb:1:1: C: Style/GuardClause: Use a guard clause (raise('hi') if cond) instead of wrapping the code inside a conditional expression.
if cond
^^
```
```console
% bundle exec rubocop --only Style/GuardClause
(snip)
Offenses:
example.rb:1:1: C: Style/GuardClause: Use a guard clause (foo || raise('hi') if cond) instead of wrapping the code inside a conditional
expression.
if cond
^^
``` …
=> [Fix #7928] Fix a false message for `Style/GuardClause`

CHANGELOG.md, config/default.yml, lib/rubocop/cop/lint/ensure_return.rb, manual/cops_lint.md, spec/rubocop/cop/lint/ensure_return_spec.rb
This PR supports autocorrection for `Lint/EnsureReturn`.
=> Support autocorrection for `Lint/EnsureReturn`

CHANGELOG.md, lib/rubocop/cop/style/guard_clause.rb, spec/rubocop/cop/style/guard_clause_spec.rb
Fixes #7928.
This PR fixes a false positive for `Style/GuardClause` when assigning the result of a guard condition with `else`.
=> [Fix #7928] Fix a false positive for `Style/GuardClause`

CHANGELOG.md, config/default.yml, lib/rubocop/cop/style/optional_arguments.rb, manual/cops_style.md
This PR marks unsafe for `Style/OptionalArguments` cop because changing method signature makes interface incompatible.
The incompatibility between good example and bad example shows that.
=> Mark unsafe for `Style/OptionalArguments` cop

CHANGELOG.md, config/default.yml, spec/rubocop/target_finder_spec.rb
We should also support `rakefile` when looking for Ruby files to
process.
As of rake-13.0.1
```
DEFAULT_RAKEFILES = [
"rakefile",
"Rakefile",
"rakefile.rb",
"Rakefile.rb"
].freeze
```
=> add `rakefile` (lowercase) to default config

CHANGELOG.md, lib/rubocop/cop/lint/ambiguous_operator.rb, spec/rubocop/cop/lint/ambiguous_operator_spec.rb
Fixes #7953.
This PR fixes the following error for `Lint/AmbiguousOperator` when a method with no arguments is used in advance.
```console
foo
bar +1
% bundle exec rubocop --only Lint/AmbiguousOperator -d
(snip)
An error occurred while Lint/AmbiguousOperator cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/7953/example.rb.
undefined method `source_range' for nil:NilClass
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/lint/ambiguous_operator.rb:75:in
`offense_position?'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/lint/ambiguous_operator.rb:63:in
`block in find_offense_node_by'
```
=> [Fix #7953] Fix an error for `Lint/AmbiguousOperator`

CHANGELOG.md, config/default.yml, lib/rubocop/cop/style/and_or.rb, manual/cops_style.md, spec/rubocop/cli_spec.rb
This PR changes enforced style to `conditionals` for `Style/AndOr` cop.
It forward porting from https://github.com/rubocop-hq/rubocop-rails/pull/224.
=> Change enforced style to `conditionals` for `Style/AndOr`

CHANGELOG.md, lib/rubocop/cop/lint/parentheses_as_grouped_expression.rb, spec/rubocop/cop/lint/parentheses_as_grouped_expression_spec.rb
Fixes #7962.
This PR fixes the following false positive for `Lint/ParenthesesAsGroupedExpression` when heredoc has a space between the same string as the method name and `(`.
```ruby
foo(
<<~EOS
foo (
)
EOS
)
```
This PR adds a reproduction test and reverts a required logic removed by #7909.
=> [Fix #7962] Fix a false positive for `Lint/ParenthesesAsGroupedExpression`

lib/rubocop/cop/autocorrect_logic.rb, spec/rubocop/cli/cli_disable_uncorrectable_spec.rb
The column where the offence begins has nothing to do with if the line is small enough to contain `eol_comment` or not.
=> Fix calculation in disable_offense.

lib/rubocop/cop/style/frozen_string_literal_comment.rb, spec/rubocop/cli/cli_disable_uncorrectable_spec.rb
When working on #7868 I found #7964, and when working on #7964 I found this. Need a yak shaving emoji...
=> Improve frozen_string_literal_comment autocorrection

CHANGELOG.md, lib/rubocop/cop/style/slicing_with_range.rb, spec/rubocop/cop/style/slicing_with_range_spec.rb
Supports any expression as start index (only int previously), as noticed here: https://github.com/rubocop-hq/rubocop/pull/7921#issuecomment-627615843.
Still correctly ignores startless range.
* ~[ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).~
=> More powerful SlicingWithRange

CHANGELOG.md, lib/rubocop/cop/style/hash_syntax.rb, spec/rubocop/cop/style/hash_syntax_spec.rb
Fixes #7972.
Fix an incorrect autocorrect for `Style/HashSyntax` when using a return value uses `return`.
=> [Fix #7972] Fix an incorrect autocrrect for `Style/HashSyntax`

config/default.yml, manual/cops_layout.md
Follow up to https://github.com/rubocop-hq/rubocop/pull/7985#discussion_r426227175.
RuboCop 0.84 will be cut before RuboCop 1.0.
=> Update `VersionChanged` from 1.0 to 0.84

CHANGELOG.md, config/default.yml, lib/rubocop/cop/layout/empty_lines_around_attribute_accessor.rb, manual/cops_layout.md, spec/rubocop/cop/layout/empty_lines_around_attribute_accessor_spec.rb
Fixes #7976 and #7981
This PR adds `IgnoreAliasSyntax` and` IgnoredMethods` options for `Layout/EmptyLinesAroundAttributeAccessor` .
Users can configure a behavior for `alias` syntax using `IgnoreAliasSyntax` option. Ignored by default (true).
And users can specify ignored methods using `IgnoredMethods`. By default, set `alias_method`, `public`, `protected`, and `private` provided by Ruby.
`cattr_accessor`, `attribute`, other methods provided by Rails (and other gems) can be set by user applications or RuboCop Rails gem.
=> [Fix #7976] Add ignore options for `Layout/EmptyLinesAroundAttributeAccessor`

CHANGELOG.md, config/default.yml, lib/rubocop/cop/style/double_negation.rb, manual/cops_style.md, spec/rubocop/cop/style/double_negation_spec.rb
This PR adds `EnforcedStyle` option for `Style/DoubleNegation` cop, and `EnforcedStyle: context` by default based on #7833 survey.
```ruby
#
```
Ruby will return the last evaluated value.
This PR only supports simple contexts, such as the end of line value of method, and when using `return`.
A complex contexts should also be supported, such as when branching with `if` and others in the future.
=> Add `EnforcedStyle` for `Style/DoubleNegation` cop

CHANGELOG.md
Follow up #7982. I forgot to update the changelog 💦 
=> Fix option names in the changelog

CHANGELOG.md, lib/rubocop/cop/lint/suppressed_exception.rb, spec/rubocop/cop/lint/suppressed_exception_spec.rb
To avoid false negatives for single line `rescue` statements with a comment on the next line, we look for comments, not on the line after `rescue`, but one lines between `rescue` and the corresponding `end`.
=> [Fix #7886] Look for comments between rescue and end

CHANGELOG.md, lib/rubocop/cop/layout/empty_lines_around_attribute_accessor.rb, spec/rubocop/cop/layout/empty_lines_around_attribute_accessor_spec.rb
Fixes #7991.
This PR fixes an error for `Layout/EmptyLinesAroundAttributeAccessor` when attribute method is method chained.
=> [Fix #7991] Fix an error for `Layout/EmptyLinesAroundAttributeAccessor`

CHANGELOG.md, manual/contributing.md, tasks/check_commit.rake, tasks/spec_runner.rake
I typically want to run `rubocop` and `rspec` on the last commit (or few last commits), so I thought maybe this rake task could be useful to others?
If not, I'll use it for myself and simply add something like `tasks/local` in `.gitignore`
=> Check commit rake task

spec/rubocop/cop/lint/empty_when_spec.rb, spec/rubocop/cop/lint/suppressed_exception_spec.rb
The current `:config` shared context only takes into account the defaults when a `cop_config` is defined (See [#7970] & [#7999]). These two specs are modified to state explicitly what is being tested; if instead `let(:cop_config) { {} }` the specs fail, which can be surprising.
=> Explicit config

CHANGELOG.md, lib/rubocop/cop/migration/department_name.rb, manual/configuration.md, spec/rubocop/cop/migration/department_name_spec.rb
Fixes #7993.
This PR fixes a false positive for `Migration/DepartmentName` cop when a disable comment contains an unexpected character for department name.
=> [Fix #7993] Fix a false positive for `Migration/DepartmentName`

Gemfile, lib/rubocop/cop/layout/end_of_line.rb, lib/rubocop/cop/style/bare_percent_literals.rb
RuboCop Performance 1.6.0 has been released.
https://github.com/rubocop-hq/rubocop-performance/releases/tag/v1.6.0
This PR bumps RuboCop Performance to 1.6.0 and suppresses the following new offenses.
```console
(snip)
Offenses:
lib/rubocop/cop/layout/end_of_line.rb:78:41: C: Performance/EndWith: Use
String#end_with? instead of a regex match anchored to the end of the
string.
when :lf then MSG_DETECTED if /\r$/.match?(line)
^^^^^^^^^^^^^^^^^^
lib/rubocop/cop/layout/end_of_line.rb:79:35: C: Performance/EndWith: Use
String#end_with? instead of a regex match anchored to the end of the
string.
else MSG_MISSING unless /\r$/.match?(line)
^^^^^^^^^^^^^^^^^^
lib/rubocop/cop/style/bare_percent_literals.rb:67:37: C:
Performance/StartWith: Use String#start_with? instead of a regex …
```
=> Bump RuboCop Performance to 1.6

CHANGELOG.md, lib/rubocop/cop/lint/suppressed_exception.rb, spec/rubocop/cop/lint/suppressed_exception_spec.rb
Fixes #8008.
This PR fixes an error for `Lint/SuppressedException` when empty rescue block in `def`.
=> [Fix #8008] Fix an error for `Lint/SuppressedException`

CHANGELOG.md, lib/rubocop/cop/lint/deprecated_open_ssl_constant.rb, spec/rubocop/cop/lint/deprecated_open_ssl_constant_spec.rb
Fixes #8012.
This PR fixes an incorrect autocorrect for `Lint/DeprecatedOpenSSLConstant` when deprecated OpenSSL constant is used in a block.
=> [Fix #8012] Fix incorrect autocorrect for `Lint/DeprecatedOpenSSLConstant`

lib/rubocop/cop/cop.rb, spec/rubocop/cop/bundler/duplicated_gem_spec.rb, spec/rubocop/cop/bundler/gem_comment_spec.rb, spec/rubocop/cop/bundler/insecure_protocol_source_spec.rb, spec/rubocop/cop/bundler/ordered_gems_spec.rb, spec/rubocop/cop/cop_spec.rb, spec/rubocop/cop/gemspec/duplicated_assignment_spec.rb, spec/rubocop/cop/gemspec/ordered_dependencies_spec.rb, spec/rubocop/cop/gemspec/ruby_version_globals_usage_spec.rb, spec/rubocop/cop/layout/rescue_ensure_alignment_spec.rb, spec/rubocop/cop/style/rescue_modifier_spec.rb
Fixes https://github.com/rubocop-hq/rubocop/issues/8005.
When using the `expect_offense` and `expect_no_offenses` spec helpers, the processed source is given the special filename "(string)", unless a mock filename is passed as its second argument.
Since https://github.com/rubocop-hq/rubocop/pull/7970, the default configuration for the cop under test is loaded when using the `config` shared context. If this configuration features an `Include` key, `expect_offense` won't work unless a matching mock filename is specified.
Instead of forcing specs for cops with a default `Include` configuration to do that, I think we can always inspect anonymous sources.
=> [Fix #8005] Always inspect anonymous sources

lib/rubocop/comment_config.rb, lib/rubocop/cop/correctors/lambda_literal_to_method_corrector.rb, lib/rubocop/cop/layout/heredoc_argument_closing_parenthesis.rb, lib/rubocop/cop/lint/nested_percent_literal.rb, lib/rubocop/cop/migration/department_name.rb, lib/rubocop/cop/mixin/configurable_formatting.rb, lib/rubocop/cop/mixin/ignored_pattern.rb, lib/rubocop/cop/mixin/line_length_help.rb, lib/rubocop/cop/naming/predicate_name.rb, lib/rubocop/cop/style/inline_comment.rb
Minor performance optimization.
Replaced calls of `#match` method with `#match?` for `String`/`Regexp` classes in boolean context when matching details like captured substrings are ignored e.g.
```ruby
REGEXES.any? { |regex| literal.match(regex) }
```
becomes
```ruby
REGEXES.any? { |regex| literal.match?(regex) }
```
=> Use Regexp/String method #match? instead of #match

CHANGELOG.md, lib/rubocop/cop/lint/suppressed_exception.rb, spec/rubocop/cop/lint/suppressed_exception_spec.rb
This PR fixes a false positive for `Lint/SuppressedException` when empty rescue with comment in `def`.
```console
def foo
do_something
rescue
end
% bundle exec rubocop --only Lint/SuppressedException
(snip)
W
Offenses:
example.rb:3:1: W: Lint/SuppressedException: Do not suppress exceptions.
rescue
^^^^^^
```
The above code should not be warned because `AllowComments: true` by defualt.
=> Fix a false positive for `Lint/SuppressedException`

CHANGELOG.md, lib/rubocop/config_loader_resolver.rb, spec/rubocop/config_loader_spec.rb
When a file inherits from a url inheriting from a gem, like so:
```yaml
inherit_from: http://example.com/default.yml
```
```yaml
inherit_gem:
somegem: default.yml
```
```yaml
Layout/LineLength:
Max: 48
```
Rubocop would then incorrectly try to resolve a URL like this:
`http://example.com//private/var/folders/69/bjrqv8v1225f7yqnxknm3fb80000gn/T/d20200518-94245-6dqeew/work/gems/somegem/default.yml`
With this change, local gem paths are no longer taken by mistake for relative remote paths.
=> Fix resolving `inherit_gem` in remote configs

lib/rubocop/cop/commissioner.rb, lib/rubocop/cop/team.rb, lib/rubocop/rspec/cop_helper.rb, lib/rubocop/runner.rb, spec/rubocop/cop/commissioner_spec.rb, spec/rubocop/cop/layout/leading_empty_lines_spec.rb, spec/rubocop/cop/team_spec.rb, spec/rubocop/result_cache_spec.rb
Excluding non-relevant cops is a duty of `Team`, not `Commissioner`.
Before this PR:
* a second call to `Commissioner#investigate` could be missing a cop that was excluded previously
* a force might be added by Team for a single cop that is later judged to be non relevant by a `Commissioner` but the later can't exclude the force now
* cops judged not relevant by the `Commissioner` were still looped through (e.g. in `autocorrect_all_cops`)
PR also includes some code cleanup. This is a prelude to #7968
=> Better separation of concerns between Team and Commissioner

CHANGELOG.md, lib/rubocop/cop/lint/deprecated_open_ssl_constant.rb, spec/rubocop/cop/lint/deprecated_open_ssl_constant_spec.rb
Fixes #8035.
This PR fixes the following false positive for `Lint/DeprecatedOpenSSLConstant` when using double quoted string argument.
```console
OpenSSL::Cipher::AES256.new('cbc')
OpenSSL::Cipher::AES256.new("cbc")
% bundle exec rubocop --only Lint/DeprecatedOpenSSLConstant -a
(snip)
Offenses:
example.rb:1:1: W: [Corrected] Lint/DeprecatedOpenSSLConstant: Use
OpenSSL::Cipher.new('AES-256-cbc') instead of OpenSSL::Cipher::AES256.new('cbc').
OpenSSL::Cipher::AES256.new('cbc')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
example.rb:2:1: W: [Corrected] Lint/DeprecatedOpenSSLConstant: Use
OpenSSL::Cipher.new('AES-256-"cbc"') instead of OpenSSL::Cipher::AES256.new("cbc").
OpenSSL::Cipher::AES256.new("cbc")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
=> [Fix #8035] Fix a false positive for `Lint/DeprecatedOpenSSLConstant`

CHANGELOG.md, lib/rubocop/config_loader_resolver.rb, spec/rubocop/config_loader_spec.rb
Before this change, when inheriting a configuration from a gem, rubocop:
1. would fail to find it, if the gem specified in the Gemfile has a `path` or `git` option (because rubygems is unaware of those gems)
2. would always load the config of the latest installed version of a gem, regardless of the version specified in the Gemfile
This commit changes that, so if executed in the context of Bundler (`defined?(Bundler)`) it will first try to get the gem path via Bundler, and fallback to the previous `Gem::Specification` path when not found.
This solves the two mentioned issues while maintaining the possibility to run rubocop in a globally installed context, i.e. without Bundler.
[1]: …
=> Make the config loader Bundler-aware

lib/rubocop/cli.rb, lib/rubocop/cli/command/auto_genenerate_config.rb, lib/rubocop/config_store.rb, lib/rubocop/result_cache.rb, lib/rubocop/runner.rb, spec/rubocop/result_cache_spec.rb
=> [Fix #8027] Avoid avoidable `File.directory?` in RuboCop::ConfigStore

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/configuration.adoc, docs/modules/ROOT/pages/cops_layout.adoc, docs/modules/ROOT/pages/cops_security.adoc, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/layout/heredoc_indentation.rb, lib/rubocop/cop/style/frozen_string_literal_comment.rb, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/cop/layout/heredoc_indentation_spec.rb
Since we dropped support for Ruby 2.3 in 58738943eb3f7a41266b4546a829fd0a5a13703d, there’s some cleanup to be done:
- Documentation should not refer to Ruby 2.3.
- Code comments should not refer to Ruby 2.3.
- `Layout/HeredocIndentation` cop should not allow `active_support`, `powerpack` and `unindent` styles, only the `squiggly` style.
Those three issues are fixed by this PR.
Please note that after removing functionality from `Layout/HeredocIndentation` I couldn’t resist cleaning up the remaining code and specs. Those changes _may_ be deemed large enough for a separate pull request. Please let me know.
=> Ruby 2.3 cleanup

CHANGELOG.md, config/default.yml, lib/rubocop/cop/naming/file_name.rb, manual/cops_naming.md, spec/rubocop/cop/naming/file_name_spec.rb
https://github.com/rubocop-hq/rubocop/issues/6289 describes a limitation of the existing `ExpectMatchingDefinition: true` option on the `Naming/FileName` cop: It generates false positives when run on a project with classes which (by design) aren't namespaced with modules to match their file paths.
This PR addresses that issue by adding a new option to the `Naming/FileName` cop: `CheckDefinitionPathHieararchy`. This defaults to `true`; if set to `false`, it modifies the `ExpectMatchingDefinition` option to _only_  check whether each source file's class or module name matches the file name -- not whether the nested module hierarchy matches the subdirectory path.
=> [Fix #6289] Naming/FileName: Add ExpectMatchingClass option

CONTRIBUTING.md, docs/modules/ROOT/pages/versioning.adoc, lib/rubocop/config_loader.rb, manual/versioning.md, spec/rubocop/cli/cli_options_spec.rb
Fixes #8057.
This PR updates the following document links.
- https://docs.rubocop.org/en/latest/versioning/  -> https://docs.rubocop.org/rubocop/versioning.html
- https://docs.rubocop.org/en/latest/development/ -> https://docs.rubocop.org/rubocop/development.html
=> [Fix #8057] Update document links

spec/project_spec.rb
I made tiny change in spec/project_spec.rb.
I think "has" is better than "have".
=> Ffix small typo in spec file

docs/modules/ROOT/pages/integration_with_other_tools.adoc
vim-rubocop hasn't been updated since 2015. I think for most users, picking one of the general linting plugins makes more sense, so let's put those first?
=> Update vim integrations

docs/modules/ROOT/pages/cops_naming.adoc, tasks/cops_documentation.rake
Follow up to #8047.
This PR fixes the following error.
```console
% CI=true bundle exec rake generate_cops_documentation
Files:         485
Modules:        84 (   12 undocumented)
Classes:       450 (    3 undocumented)
Constants:     643 (  632 undocumented)
Attributes:     31 (    0 undocumented)
Methods:      1121 (  995 undocumented)
29.50% documented
* generated
/Users/koic/src/github.com/rubocop-hq/rubocop/docs/modules/ROOT/pages/cops_bundler.adoc
* generated
/Users/koic/src/github.com/rubocop-hq/rubocop/docs/modules/ROOT/pages/cops_gemspec.adoc
* generated
/Users/koic/src/github.com/rubocop-hq/rubocop/docs/modules/ROOT/pages/cops_layout.adoc
* generated
/Users/koic/src/github.com/rubocop-hq/rubocop/docs/modules/ROOT/pages/cops_lint.adoc
* generated …
```
=> Update assertion to docs synchronized

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_naming.adoc, lib/rubocop/cop/naming/class_and_module_camel_case.rb, spec/rubocop/cop/naming/class_and_module_camel_case_spec.rb
=> [Fix #8063] Add new `AllowedNames` option for `Naming/ClassAndModuleCamelCase`

CHANGELOG.md, docs/modules/ROOT/pages/formatters.adoc, legacy-docs/formatters.md, lib/rubocop/formatter/junit_formatter.rb, lib/rubocop/options.rb, spec/rubocop/options_spec.rb
Speeds up test report processing for large codebases and helps address
the sorts of concerns raised at
https://github.com/mikian/rubocop-junit-formatter/issues/18.
In one case for me, this reduced the number of `testcase` xml elements from 66,000 to 1, which made a material difference in terms of jenkins test report load times.
Refactors file_finished method in junit_formatter.rb to reduce
complexity.
Fixes buggy error message when --disable-uncorrectable is run without
--auto-correct, which I noticed because I added similar error messaging
when you try to run --display-only-failed without --format junit.
Tests, CHANGELOG.md, and help message updates to accompany new option
=> New option --display-only-failed for junit format

lib/rubocop/rspec/cop_helper.rb, lib/rubocop/rspec/expect_offense.rb, spec/rubocop/cop/bundler/ordered_gems_spec.rb, spec/rubocop/cop/gemspec/ordered_dependencies_spec.rb, spec/rubocop/cop/layout/class_structure_spec.rb, spec/rubocop/cop/layout/heredoc_indentation_spec.rb, spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb, spec/rubocop/cop/style/rescue_modifier_spec.rb
In some places, we spec what happens after `one` auto-correct iteration, and in some places we spec what happens after _many_ auto-correct iterations.
As mentioned in #8003, there is no longer any reason to use helpers like `autocorrect_source_with_loop`. This PR removes that method and all our uses of it.
=> expect_correction with loop

CHANGELOG.md, lib/rubocop/cop/lint/mixed_regexp_capture_types.rb, spec/rubocop/cop/lint/mixed_regexp_capture_types_spec.rb
Fixes #8083.
This PR fixes an error for `Lint/MixedRegexpCaptureTypes` cop when using a regular expression that cannot be processed by regexp_parser gem.
https://github.com/ammar/regexp_parser
Probably false negatives will be made, however false negatives will be reduced when a processing pattern of regexp_parser increases.
So this PR relies on regexp_parser for error resolution.
=> [Fix #8083] Fix an error for `Lint/MixedRegexpCaptureTypes`

CHANGELOG.md, lib/rubocop/cop/lint/suppressed_exception.rb, spec/rubocop/cop/lint/suppressed_exception_spec.rb
Fixes #8081.
This PR fixes an error for `Lint/SuppressedException` when empty rescue block in `do` block.
```console
foo do
rescue Foo
end
% bundle exec rubocop --only Lint/SuppressedException
(snip)
W
Offenses:
example.rb:2:1: W: Lint/SuppressedException: Do not suppress exceptions.
rescue Foo
^^^^^^^^^^
```
`do` block rescue is a syntax introduced in Ruby 2.5.
=> [Fix #8081] Fix an error for `Lint/SuppressedException`

CHANGELOG.md, lib/rubocop/cop/lint/suppressed_exception.rb, spec/rubocop/cop/lint/suppressed_exception_spec.rb
Fixes #8096
This PR fixes a false positive for `Lint/SuppressedException`
when empty rescue block in defs.
```console
def self.foo
rescue Foo
end
% bundle exec rubocop --only Lint/SuppressedException
(snip)
W
Offenses:
example.rb:2:1: W: Lint/SuppressedException: Do not suppress exceptions.
rescue Foo
^^^^^^^^^^
```
=> [Fix #8096] Fix a false positive for `Lint/SuppressedException`

lib/rubocop/rspec/expect_offense.rb, spec/rubocop/cop/bundler/ordered_gems_spec.rb, spec/rubocop/cop/layout/array_alignment_spec.rb, spec/rubocop/cop/layout/class_structure_spec.rb, spec/rubocop/cop/layout/extra_spacing_spec.rb, spec/rubocop/cop/layout/heredoc_argument_closing_parenthesis_spec.rb, spec/rubocop/cop/layout/heredoc_indentation_spec.rb, spec/rubocop/cop/layout/space_around_block_parameters_spec.rb, spec/rubocop/cop/layout/space_inside_array_literal_brackets_spec.rb, spec/rubocop/cop/lint/useless_access_modifier_spec.rb, spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb, spec/rubocop/cop/style/rescue_modifier_spec.rb
Related to #8062, #8075 and #8076, this PR changes `#expect_correction` to always do looped autocorrection.
For most cops and specs, this won't change anything. The offense is corrected in one go, and the second iteration doesn't change anything.
For a few specs, something will change. A few specs have to explicitly pass `loop: false` to test the result of the first round of autocorrect, and another few specs need to pass it to avoid exceptions such as `InfiniteCorrectionLoop`. And that's the real value of using looped autocorrection in the specs – we will find more errors before releasing them to our users.
(Also in this PR: Fixing two bugs in `#expect_correction`, discovered when enabling the looping)
* [-] …
=> Always loop when testing autocorrection

lib/rubocop/cop/cop.rb, lib/rubocop/cop/registry.rb, lib/rubocop/cop/team.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/generator_spec.rb, spec/rubocop/cop/registry_spec.rb
This PR:
* moves registry-related globals to Registry (while maintaining compatibility)
* makes `Registry` dupable
* makes `Registry` lazy enough to allow delisting (useful for base classes, see #8023)
* adds `with_temporary_global` for easy testing that won't affect the global registry
Prelude to autocorrect refactor #7868
=> Registry improvements

spec/rubocop/cop/registry_spec.rb, spec/rubocop/cop/team_spec.rb, spec/rubocop/formatter/disabled_config_formatter_spec.rb
Got rid of class declarations in specs that littered the root namespace.
#8095 allowed to dynamically declare cops with `Class.new`.
* [-] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
=> Fix leaky constant declarations

CHANGELOG.md, lib/rubocop/cop/layout/heredoc_indentation.rb, spec/rubocop/cop/layout/heredoc_indentation_spec.rb
Empty lines were already excluded for calculation of indentation in `Layout/HeredocIndentation`. We need to do the same thing for lines consisting only of whitespace.
=> [Fix #8108] Disregard whitespace lines in HeredocIndentation

CHANGELOG.md, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/format_parameter_mismatch.rb, lib/rubocop/cop/utils/format_string.rb, spec/rubocop/cop/lint/format_parameter_mismatch_spec.rb, spec/rubocop/cop/utils/format_string_spec.rb
The cop failed to process format string in invalid format and raised exception. There are several cases when format string contains valid segments but these segments aren't compatible.
For instance numbered format cannot be mixed with unnumbered or named. Such format string will lead to ArgumentError when code is executed but sometimes it's needed e.g. in tests to check how the code handles such invalid format strings.
Example of such code - [tests in RubySpec project](https://github.com/ruby/spec/blob/master/core/string/modulo_spec.rb#L186-L187)
- check whether current format string is valid in `Lint::FormatParameterMismatch` cope
- added offense "Format string is invalid because formatting sequence types (numbered, named or unnumbered) are mixed." it if it's invalid
- added `#valid?` …
=> Fix Lint::FormatParameterMismatch cop

.gitignore, .rubocop.yml
Those who want to avoid typing `bundle exec` before each command that is provided by a dependent gem, e.g. `rake`, `yard`, `rspec`, `rubocop` itself, Bundler provides a convenient way of creating binstubs in `bin` directory.
Commands can be run like `bin/rake`, `bin/yard`, `bin/rspec` etc then.
This can further simplify the usage by employing [`direnv`](https://github.com/direnv/direnv) that has a nice option in its `.envrc` file:
PATH_add bin
After that (and approving `.envrc` changes with `direnv allow`) it's possible to run `yard`, `rspec` and `rubocop` with no prefixes. I stick to this in every repository I contribute to even if I have to deal with unstaged changes in my `bin`.
Not prefixing with `bundle exec` may cause you trouble if you have several versions of a gem installed and …
=> Ignore bundle binstubs

rubocop.gemspec
See https://github.com/rubocop-hq/rubocop-ast/pull/26
=> Limit rubocop-ast to pre 1.0

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/struct_inheritance.rb, spec/rubocop/cop/style/struct_inheritance_spec.rb
=> Add auto-correct for `Style/StructInheritance`

CHANGELOG.md, lib/rubocop/rspec/expect_offense.rb
Followup to https://github.com/rubocop-hq/rubocop/pull/8069.
This allows `expect_offense` to be used when the dynamically generated part of the source code is not highlighted by the offense.
I couldn't find a spec in this repo that could be rewritten to use this option, but I have an open PR on RuboCop Rails that would benefit from it: https://github.com/rubocop-hq/rubocop-rails/pull/257/files#diff-d9cf3a5c58c7f3acbad8f9812ca8006bR70
=> Let format_offense add variable-width whitespace

docs/modules/ROOT/pages/cops_layout.adoc, lib/rubocop/cop/layout/space_before_block_braces.rb
For `EnforcedStyleForEmptyBraces` option
Closes #8106
=> [Fix #8106] Add missing config documentation for `Layout/SpaceBeforeBlockBraces`

README.md
Contributors came to a common conclusion in #8112
Closes #8112 since we will support 2.4 for a year.
=> Add Ruby EOL support policy

CHANGELOG.md, lib/rubocop/cop/lint/format_parameter_mismatch.rb, spec/rubocop/cop/lint/format_parameter_mismatch_spec.rb
Fix a bug introduced in https://github.com/rubocop-hq/rubocop/pull/8042
Closes https://github.com/rubocop-hq/rubocop/issues/8115.
=> Lint/FormatParameterMismatch. Fix bug with formating in argument

CHANGELOG.md, lib/rubocop/cop/utils/format_string.rb, spec/rubocop/cop/lint/format_parameter_mismatch_spec.rb, spec/rubocop/cop/utils/format_string_spec.rb
Fixes #8124.
This PR fixes a false positive for `Lint/FormatParameterMismatch` using named parameters with escaped `%`.
=> [Fix #8124] Fix a false positive for `Lint/FormatParameterMismatch`

CHANGELOG.md, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/redundant_regexp_escape.rb, spec/rubocop/cop/style/redundant_regexp_escape_spec.rb
We must allow `%r` delimiters to be escaped, e.g. `%r~\~~`
=> [Fix #8131]: Ignore escapes of delimiters in Style/RedundantRegexpEscape

CHANGELOG.md, lib/rubocop/cop/mixin/configurable_naming.rb, spec/rubocop/cop/naming/variable_name_spec.rb
Changed regexp for fix the problem with camelCase and one symbol variables.
* [+ ] Wrote [good commit messages][1].
* [ +] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ +] Feature branch is up-to-date with `master` (if not - rebase it).
* [ +] Squashed related commits together.
* [ +] Added tests.
* [ +] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [ +] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [ +] Run `bundle exec rake default`. It executes all tests …
=> [Fix #8132] Fix the problem with Naming/MethodName: EnforcedStyle: camelCase and _ or i variables.

CHANGELOG.md, lib/rubocop/cop/mixin/regexp_literal_help.rb, lib/rubocop/cop/style/redundant_regexp_character_class.rb, lib/rubocop/cop/style/redundant_regexp_escape.rb, spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb, spec/rubocop/cop/style/redundant_regexp_escape_spec.rb
Also correct the handling of interpolations and comments - we need to
preserve their width in the checked pattern source without their
contents triggering the cop in question, so that we can correctly
highlight following offenses based on the offset in the pattern_source.
=> [Fix #8098]: Fix false-positive in Style/RedundantRegexpCharacterClass

CHANGELOG.md, lib/rubocop/name_similarity.rb
Fixes #7979 
In #7979 it was reported that `DidYouMean::SpellChecker` may not always be available. We can work around that by doing a feature check before using the `SpellChecker` class.
I did not add any tests.
=> DidYouMean::SpellChecker may not be available

CHANGELOG.md, lib/rubocop/cop/layout/empty_lines_around_attribute_accessor.rb, spec/rubocop/cop/layout/empty_lines_around_attribute_accessor_spec.rb
This PR fixes the following false positive for `Layout/EmptyLinesAroundAttributeAccessor` when using attribute accessors in `if` ... `else` branches.
```ruby
if condition
attr_reader :foo
else
do_something
end
```
```console
% bundle exec rubocop --only Layout/EmptyLinesAroundAttributeAccessor
(snip)
C
Offenses:
example.rb:2:3: C: Layout/EmptyLinesAroundAttributeAccessor: Add an
empty line after attribute accessor.
attr_reader :foo
^^^^^^^^^^^^^^^^
```
=> Fix a false positive for `Layout/EmptyLinesAroundAttributeAccessor`

lib/rubocop/cop/style/redundant_self.rb
No need to allocate an array for every check.
It is also faster when converted to Set, but I preserved the logic. Will update with set, if requested.
=> Extract static array into constant in RedundantSelf cop

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/multiline_ternary_operator.rb, spec/rubocop/cop/style/multiline_ternary_operator_spec.rb
This PR supports autocorrection for `Style/MultilineTernaryOperator`.
=> Support autocorrection for `Style/MultilineTernaryOperator`

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/nested_ternary_operator.rb, spec/rubocop/cop/style/nested_ternary_operator_spec.rb
This PR supports autocorrection for `Style/NestedTernaryOperator`.
=> Support autocorrection for `Style/NestedTernaryOperator`

README.md, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/compatibility.adoc, lib/rubocop/target_ruby.rb
Follow up https://github.com/rubocop-hq/rubocop/pull/7943#discussion_r422450919 and https://github.com/rubocop-hq/rubocop/issues/8112#issuecomment-640539334.
This PR updates obsolete rubies, adds a doc for compatibility and  replaces compatibility description with compatibility doc link to keep README.md simple.
=> Update obsolete rubies and add a doc for compatibility

docs/modules/ROOT/pages/extensions.adoc
This PR adds another known extension, [rubocop-packaging](https://github.com/utkarsh2102/rubocop-packaging) to the [extension docs](https://docs.rubocop.org/rubocop/0.85/extensions.html).
And lastly, thanks @bbatsov, for this wonderful tool! :heart: 
Signed-off-by: Utkarsh Gupta <<utkarsh@debian.org>>
=> Add rubocop-packaging as a known extension in the docs

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_metrics.adoc, lib/rubocop.rb, lib/rubocop/cop/layout/hash_alignment.rb, lib/rubocop/cop/lint/redundant_cop_disable_directive.rb, lib/rubocop/cop/metrics/cyclomatic_complexity.rb, lib/rubocop/cop/metrics/utils/abc_size_calculator.rb, lib/rubocop/cop/metrics/utils/iterating_block.rb, lib/rubocop/cop/mixin/multiline_expression_indentation.rb, lib/rubocop/cop/naming/file_name.rb, lib/rubocop/cop/style/block_delimiters.rb, lib/rubocop/cop/style/conditional_assignment.rb, lib/rubocop/cop/style/empty_case_condition.rb, lib/rubocop/cop/style/identical_conditional_branches.rb, lib/rubocop/cop/style/if_inside_else.rb, lib/rubocop/cop/style/sample.rb, lib/rubocop/cop/style/semicolon.rb, spec/rubocop/cli/cli_disable_uncorrectable_spec.rb, spec/rubocop/cop/metrics/cyclomatic_complexity_spec.rb
This PR fixes CyclomaticComplexity for `||=`, `&&=`, `&.`
Blocks are tricky as some blocks clearly add to the complexity 
```
hash.transform_values { ... } # => should adds 1
```
Other builtin methods don't actually add to the cyclomatic
complexity, like `tap`, `yield_self`, `class_eval`, ...
```
obj.tap { ... } # => should no count
```
As @jonas054 pointed out, others methods in general can not be known.
This PR takes the conservative approach and counts only known iterating/conditional methods and ignores the rest.
If the default for CyclomaticComplexity remains at 6, there would be 34 new todos in the main gem.
If we bump it at 7, there are 5 new todos, 2 can be removed.
Bumping to 8 would have 1 new todo and 4 that would be removed.
I'm proposing to bump it to 7.
=> Fixes Metrics/CyclomaticComplexity

lib/rubocop/cop/lint/raise_exception.rb, spec/rubocop/cop/lint/raise_exception_spec.rb
This PR refines offense range for `Lint/RaiseException`.
The following is an example.
```ruby
raise Exception.new('Message')
```
```console
% bundle exec rubocop example.rb --only Lint/RaiseException
(snip)
Offenses:
example.rb:1:1: W: Lint/RaiseException: Use StandardError over
Exception.
raise Exception.new('Message')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
```console
% bundle exec rubocop example.rb --only Lint/RaiseException
(snip)
Offenses:
example.rb:1:7: W: Lint/RaiseException: Use StandardError over
Exception.
raise Exception.new('Message')
^^^^^^^^^
```
=> Refine offense range for `Lint/RaiseException`

lib/rubocop/cop/lint/safe_navigation_with_empty.rb, spec/rubocop/cop/lint/safe_navigation_with_empty_spec.rb
This PR refines offense range for `Lint/SafeNavigationWithEmpty`.
The following is an example.
```ruby
return unless foo&.empty?
```
```console
% bundle exec rubocop example.rb --only Lint/SafeNavigationWithEmpty
(snip)
Offenses:
example.rb:1:1: W: Lint/SafeNavigationWithEmpty: Avoid calling empty?
with the safe navigation operator in conditionals.
return unless foo&.empty?
^^^^^^^^^^^^^^^^^^^^^^^^^
```
```console
% bundle exec rubocop example.rb --only Lint/SafeNavigationWithEmpty
(snip)
Offenses:
example.rb:1:15: W: Lint/SafeNavigationWithEmpty: Avoid calling empty?
with the safe navigation operator in conditionals.
return unless foo&.empty?
^^^^^^^^^^^
``` …
=> Refine offense range for `Lint/SafeNavigationWithEmpty`

lib/rubocop/cop/style/nested_ternary_operator.rb, spec/rubocop/cop/style/nested_ternary_operator_spec.rb
Fixes #8173.
This PR fixes an error for `Style/NestedTernaryOperator` when a nested ternary operator expression with block.
No changelog has been added due to the bug fix for an unreleased feature.
=> [Fix #8173] Fix an error for `Style/NestedTernaryOperator`

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/regexp_as_condition.rb, spec/rubocop/cop/lint/regexp_as_condition_spec.rb
This PR supports autocorrection for `Lint/RegexpAsCondition`.
=> Support autocorrection for `Lint/RegexpAsCondition`

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc
Follow up https://github.com/rubocop-hq/rubocop/pull/8169#issuecomment-647012793.
`Lint/RaiseException` cop is unsafe due to incompatibility between bad and good cases. The following is an example.
```console
% cat /tmp/example_for_exception.rb
begin
raise Exception
rescue
puts 'Handle exception'
end
% ruby example_for_exception.rb
example_for_exception.rb:2:in `<main>': Exception (Exception)
```
```console
% cat example_for_starndard_error.rb
begin
raise StandardError
rescue
puts 'Handle exception'
end
% ruby /tmp/example_for_starndard_error.rb
Handle exception
```
=> Mark unsafe for `Lint/RaiseException` cop

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/raise_exception.rb, spec/rubocop/cop/lint/raise_exception_spec.rb
This PR supports autocorrection for `Lint/RaiseException`.
=> Support autocorrection for `Lint/RaiseException`

docs/modules/ROOT/pages/usage/basic_usage.adoc, lib/rubocop/cli/command/init_dotfile.rb, spec/rubocop/cli_spec.rb
The link in the generated .rubocop.yml is outdated.
- I updated it.
- I updated the spec that controls the content of .rubocop.yml.
- I also updated the link to the same page where it appears in the docs.
=> Fix link to documentation about configuration in .rubocop.yml

CHANGELOG.md, lib/rubocop/cop/layout/multiline_block_layout.rb, spec/rubocop/cop/layout/multiline_block_layout_spec.rb
Fixes #8179.
This PR fixes an infinite correction loop error for `Layout/MultilineBlockLayout` when missing newline before opening parenthesis `(` for block body.
```ruby
foo do |o| (
bar
)
end
```
```console
% rubocop -a --only Layout/MultilineBlockLayout
C
Offenses:
example.rb:3:12: C: [Corrected] Layout/MultilineBlockLayout: Block body
expression is on the same line as the block start.
foo do |o| ( ...
^
Infinite loop detected in /Users/koic/src/github.com/koic/rubocop-issues/8179/example.rb.
/Users/koic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-0.85.1/lib/rubocop/runner.rb:276:in
`block in iterate_until_no_changes'
/Users/koic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-0.85.1/lib/ruboc …
```
=> [Fix #8179] Fix an infinite correction loop for `Layout/MultilineBlockLayout`

README.md
This PR adresses issue https://github.com/rubocop-hq/rubocop/issues/8182
Added a Readme Badge section to the readme, with an example badge other people can use in their projects to show adherence to The Ruby Style Guide.
I've thrown it between the Compatibility and Team sections; I'm willing to modify the order on request.
The section and badge have been taken and modified from the Standard proyect.
=> Add Readme Badge section to README.md

CHANGELOG.md, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/yoda_condition.rb, spec/rubocop/cop/style/yoda_condition_spec.rb
Fixes #8185.
This PR fixes a false positive for `Style/YodaCondition` when interpolation is used on the left side.
String interpolation (and Regexp interpolation) contains variables, I think it's acceptable to use it on the left hand side.
=> [Fix #8185] Fix a false positive for `Style/YodaCondition`

CHANGELOG.md, lib/rubocop/cop/style/redundant_fetch_block.rb, spec/rubocop/cop/style/redundant_fetch_block_spec.rb
Fixes #8195
This PR fixes an error for `Style/RedundantFetchBlock` when using `#fetch` with empty block.
=> [Fix #8195] Fix an error for `Style/RedundantFetchBlock`

lib/rubocop/rspec/shared_contexts.rb
This PR removes an unused `require`.
=> Remove unused require

CHANGELOG.md, lib/rubocop/cop/style/redundant_regexp_character_class.rb, spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb
=> [Fix #8193] Avoid false positive in Style/RedundantRegexpCharacterClass

lib/rubocop/cli.rb, lib/rubocop/cli/command/auto_genenerate_config.rb, lib/rubocop/config_loader.rb
While working on #8176, I'm constantly exceeding the maximum allowed class length for this class.
This PR refactors it to be thinner.
=> Small refactors in `ConfigLoader`

CHANGELOG.md, docs/modules/ROOT/pages/usage/auto_correct.adoc, lib/rubocop/options.rb, lib/rubocop/rake_task.rb, spec/rubocop/cli/cli_autocorrect_spec.rb, spec/rubocop/cli/cli_disable_uncorrectable_spec.rb, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/cli_spec.rb, spec/rubocop/cop/lint/syntax_spec.rb, spec/rubocop/options_spec.rb, spec/rubocop/rake_task_spec.rb
I'm proposing slightly different options than in #8156:
`-a` / `--auto-correct` are now safe only, replacing `--safe-auto-correct`
`-A` / `--auto-correct-all` apply safe and unsafe corrections
Help reads:
```
...
-a, --auto-correct               Auto-correct offenses (only when it's safe).
-A, --auto-correct-all           Auto-correct offenses (safe and unsafe)
...
```
=> [Fixes #8156] CLI options change: auto-correct now safe by default.

CHANGELOG.md, lib/rubocop/cop/style/redundant_regexp_character_class.rb, spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb
If the first element of a character class was an escaped-] our pattern
was treating it as a single element classs containing a single backslash
(which is invalid, and incorrect).
=> [Fix #8205] Avoid false positive in Style/RedundantRegexpCharacterClass

CHANGELOG.md, lib/rubocop/cop/style/redundant_fetch_block.rb, spec/rubocop/cop/style/redundant_fetch_block_spec.rb
=> Fix a false positive for `Style/RedundantFetchBlock` when using with `Rails.cache`

lib/rubocop/config_obsoletion.rb, spec/rubocop/config_obsoletion_spec.rb
For context:
https://github.com/rubocop-hq/rubocop-rails/pull/267 description 
and https://github.com/rubocop-hq/rubocop-rails/pull/267#issuecomment-649744622
=> Remove Rails/DefaultScope from ConfigObsoletion

CHANGELOG.md, docs/modules/ROOT/pages/compatibility.adoc, lib/rubocop/target_ruby.rb, rubocop.gemspec, spec/rubocop/cli_spec.rb
This PR permits to specify TargetRubyVersion 2.8.
RuboCop AST supports Ruby 2.8 (3.0) with https://github.com/rubocop-hq/rubocop-ast/pull/48.
=> Permit to specify TargetRubyVersion 2.8

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/interpolation_check.rb, spec/rubocop/cop/lint/interpolation_check_spec.rb
This PR supports autocorrection for `Lint/InterpolationCheck` and marks it unsafe because autocorrected code is incompatible.
=> Support autocorrection for `Lint/InterpolationCheck`

docs/modules/ROOT/pages/automated_code_review.adoc
I recently found a new tool that can run Rubocop on Github PRs: https://github.com/reviewdog/action-rubocop
=> Add reviewdog tool to docs

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/if_unless_modifier_of_if_unless.rb, spec/rubocop/cop/style/if_unless_modifier_of_if_unless_spec.rb
This PR supports auto-correction for `Style/IfUnlessModifierOfIfUnless`.
From:
```ruby
condition ? then_part : else_part unless external_condition
```
To:
```ruby
unless external_condition
condition ? then_part : else_part
end
```
Branch indentation is left to `Layout/IndentationWidth` cop to keep the code simple.
=> Support auto-correction for `Style/IfUnlessModifierOfIfUnless`

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/safe_navigation_with_empty.rb, spec/rubocop/cop/lint/safe_navigation_with_empty_spec.rb
This PR supports autocorrection for `Lint/SafeNavigationWithEmpty`.
=> Support autocorrection for `Lint/SafeNavigationWithEmpty`

lib/rubocop/rake_task.rb
Use global Rake namespace to avoid namespace issues with custom rubocop-rake tasks as described in rubocop-hq/rubocop-rake#24
=> fix rubocop-hq/rubocop-rake#24

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_bundler.adoc, docs/modules/ROOT/pages/cops_gemspec.adoc, lib/rubocop/cop/mixin/ordered_gem_node.rb, spec/rubocop/cop/bundler/ordered_gems_spec.rb
I think it is a small improvement if `activeadmin` is sorted before `active_admin-sortable_tree`.
It is a breaking change though, with a frequent real world example: `paper_trail` vs `paperclip`. v1 might be the perfect timing, or it might not be worth it...
=> [Fixes #8207] Don't consider underscores and dashes when sorting gems

lib/rubocop/cop/mixin/configurable_formatting.rb, lib/rubocop/cop/naming/method_name.rb, lib/rubocop/cop/naming/variable_name.rb, lib/rubocop/cop/naming/variable_number.rb, spec/rubocop/cop/naming/variable_number_spec.rb
In order to use the new autocorrection API in rubocop-rspec, I need `ConfigurableFormatting` to call `add_offense` using the new API. This was also mentioned in https://github.com/rubocop-hq/rubocop/pull/7868#issuecomment-641595191
I had to change spec/rubocop/cop/naming/variable_number_spec.rb – the example introduced in #3728 was impossible to change to use `expect_offense` without splitting the shared example in two. I am still not sure what the example _does_, but at least it works the same way as before.
* [-] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new …
=> Use new cop API in ConfigurableFormatting

CHANGELOG.md, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/class_vars.rb, spec/rubocop/cop/style/class_vars_spec.rb
`class_variable_set(:@@name, 2)` has the same effect as `@@name = 2`
This variation can be within the class definition:
```ruby
class A
class_variable_set(:@@name, 2)
end
```
Or it could be called elsewhere, with the class as receiver:
```ruby
class A; end
class B
def change(name, value)
A.class_variable_set(":@@#{name}", value)
end
end
```
=> Detect class_variable_set in Style/ClassVars

CHANGELOG.md, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
Fixes https://github.com/rubocop-hq/rubocop/issues/8208
Do not consider the parentheses around a yielded hash literal as redundant.
=> Fix Style/RedundantParentheses with hash literal as first argument to yield

CHANGELOG.md, lib/rubocop/cop/lint/parentheses_as_grouped_expression.rb, spec/rubocop/cop/lint/parentheses_as_grouped_expression_spec.rb
This PR fixes the following false positive for `Lint/ParenthesesAsGroupedExpression`
- when an expression is followed by an operator
```ruby
func (x) || y
```
- when an expression is followed by a chain of functions
```ruby
func (x).func.func.func.func.func
```
This PR adds some reproduction tests.
I was initially thinking of changing the auto-correct to produce things such as `func((x) || y)` and `func((x).func.func.func.func.func)`, but since we probably do not want `eq (x).to_i` to become suddenly `eq((x).to_i)` (https://github.com/rubocop-hq/rubocop/pull/7909), I went with ignoring these pasterns. This is because the current auto-correct behavior breaks the code for these pasterns. Please do tell me if we would prefer going in another direction 🙏 
I'm not very …
=> Fix false positives for Lint/ParenthesesAsGroupedExpression 

lib/rubocop/cop/mixin/uncommunicative_name.rb, lib/rubocop/cop/naming/method_parameter_name.rb
If not having a name is a possible syntax, it is acceptable
Needed for https://github.com/rubocop-hq/rubocop-ast/pull/52
=> Simplify logic for UncommunicativeName. 

CHANGELOG.md, lib/rubocop/config_loader.rb, spec/rubocop/config_loader_spec.rb
If there's a specific project configuration, we want the exclusions for the user configuration to be ignored, just like the rest of the configuration is ignored.
Note that this solution slightly changes behavior if people are running rubocop for within a subproject folder that resolves to a `.rubocop.yml` different from the one in the root folder. However, I believe that if people are doing this, they are probably using `--ignore-parent-exclusion` already, so it's not going to be an issue.
=> [Fix #7433] User vs project exclusion inheritance

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_naming.adoc, lib/rubocop/cop/naming/ascii_identifiers.rb, spec/rubocop/cop/naming/ascii_identifiers_spec.rb
Closes #7458 
Implementation as suggested in https://github.com/rubocop-hq/rubocop/pull/7459#issuecomment-546032027
=> Add new `AsciiConstants` option for `Naming/AsciiIdentifiers`.

docs/modules/ROOT/pages/configuration.adoc
Clarify path relativity's effect on cops with customisable paths.
As shown in https://github.com/rubocop-hq/rubocop/issues/8240, cops that specify paths do not do what's initially expected when configured in subdirectories. Hopefully this will save somebody else a bit of time.
=> [Fix #8240] Improve documentation on path relativity

Gemfile, lib/rubocop/cop/style/redundant_regexp_escape.rb
This PR bumps RuboCop Performance to 1.7.
=> Bump RuboCop Performance to 1.7

CHANGELOG.md, lib/rubocop/options.rb, spec/rubocop/options_spec.rb
Fixes #8252.
This PR fixes a command line option name from `--safe-autocorrect` to `--safe-auto-correct`, which is compatible with RuboCop 0.66 and lower.
Before:
```console
% bundle exec ./exe/rubocop --safe-auto-correct
invalid option: --safe-auto-correct
Did you mean?  safe-autocorrect
For usage information, use --help
```
After:
```console
% bundle exec ./exe/rubocop --safe-auto-correct
--safe-auto-correct is deprecated; use --auto-correct
Inspecting 1082 files
```
=> [Fix #8252] Fix a typo for `--safe-auto-correct` command line option

lib/rubocop/rspec/expect_offense.rb, spec/rubocop/cop/style/frozen_string_literal_comment_spec.rb
Part of #8003
Use `^{}` to denote an offense at an empty line in `expect_offense`. This format was suggested by @marcandre in [Issue 8003 comment](https://github.com/rubocop-hq/rubocop/issues/8003#issuecomment-641567272). I think it has the advantage of familiarity with existing `^` and `^{name}` syntax.
Example:
```ruby
expect_offense(<<~RUBY)
^{} Missing frozen string literal comment.
puts 1
RUBY
```
I have enabled pending frozen string literal specs as coverage for this change.
Also corrected which line the offense is added to in the frozen string literal
specs (always the first line). As the first line is non-empty in some of these
cases, a normal caret `^` is used to mark the offense.
[1]: …
=> Add expect_offense mark for offense on empty line

CHANGELOG.md, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop/config_loader.rb, spec/rubocop/config_loader_spec.rb
If passing a configuration with a custom name, like `rubocop --config .my_custom_project_config.yml`, that configuration should act as the project configuration and we want personal configuration files disregarded.
That's actually the only case where `find_files_upwards` can return an empty list, because when given an existing `.rubocop.yml` as the starting point, it will at least return that file, and the fallback to personal config files will not be applied.
Well, there's another case where `find_files_upwards` could return an empty list, which is when giving it a non existent file as the starting point. However, I don't think that ever happens in real life, and in tests it was only happening once, and due to a typo I believe.
So, we can completely remove the explicit fallback to look …
=> Don't load exclusions from personal files when passing a config with a custom name

CHANGELOG.md, lib/rubocop/formatter/disabled_config_formatter.rb, spec/rubocop/cli/cli_auto_gen_config_spec.rb
Fixes #8256.
This PR fixes an error for `--auto-gen-config` when running a cop who do not support auto-correction.
=> [Fix #8256] Fix an error for `--auto-gen-config` when running a cop without autocorrect

CHANGELOG.md, lib/rubocop/cop/style/bisected_attr_accessor.rb, spec/rubocop/cop/style/bisected_attr_accessor_spec.rb
=> Fix an error for `Style/BisectedAttrAccessor` when using `attr_reader` and `attr_writer` with splat arguments

CHANGELOG.md, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/deprecated_open_ssl_constant.rb, spec/rubocop/cop/lint/deprecated_open_ssl_constant_spec.rb
Testing on some Linux-based CI systems revealed the upper case cipher name is not always accepted, but lower case always is. I didn't ran into this when developing https://github.com/rubocop-hq/rubocop/pull/7950 
Example output on a random VM:
```
user@app1:~$ cat /etc/issue
Ubuntu 16.04.3 LTS \n \l
user@app1:~$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
user@app1:~$ irb
irb(main):001:0> require 'openssl'
=> true
irb(main):002:0> OpenSSL::Cipher.new('AES-256-GCM')
RuntimeError: unsupported cipher algorithm (AES-256-GCM)
from (irb):2:in `initialize'
from (irb):2:in `new'
from (irb):2
from /home/deploy/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'
irb(main):003:0> OpenSSL::Cipher.new('aes-256-gcm')
=> #<OpenSSL::Cipher:0x00560ce9b75470>
``` …
=> Fix Lint/DeprecatedOpenSSLConstant auto-correction of OpenSSL::Cipher to use lower case

CHANGELOG.md, lib/rubocop/cop/style/bisected_attr_accessor.rb, spec/rubocop/cop/style/bisected_attr_accessor_spec.rb
=> Fix false positives for `Style/BisectedAttrAccessor` when accessors have different access modifiers

.gitignore, CHANGELOG.md, Gemfile, bin/rubocop-profile, tasks/prof.rake
To have profiling turned on, I was thinking of something like this, but maybe it should be only in `bin/something` and/or the rake task?
=> Basic support for profiling

CHANGELOG.md, lib/rubocop/cop/layout/empty_lines_around_access_modifier.rb, spec/rubocop/cop/layout/empty_lines_around_access_modifier_spec.rb
Fixes #8232.
This PR fixes a false positive and an incorrect auto-correct for `Layout/EmptyLinesAroundAccessModifier` when `end` immediately after access modifier.
=> [Fix #8232] Fix a false positive for `Layout/EmptyLinesAroundAccessModifier`

lib/rubocop/cop/style/missing_else.rb
Some years ago, the logic for generating the `message` was extracted to a method, leaving a couple of unnecessary lines behind. See b11ef7741f38b7c23761695f5b3bcb7a0219dfeb.
* [-] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
=> Remove unnecessary logic from MissingElse

lib/rubocop/cop/mixin/statement_modifier.rb, lib/rubocop/cop/style/if_unless_modifier.rb, spec/rubocop/cop/style/while_until_modifier_spec.rb, spec/support/condition_modifier_cop.rb
While `IfUnless` had the right logic, `WhileUntil` did not.
This contradicts the test for #4010 which I believe was incorrect.
=> [Fixes #8273] Fix false positive for Style/WhileUntilModifier.

CHANGELOG.md, lib/rubocop/cop/correctors/multiline_literal_brace_corrector.rb, spec/rubocop/cop/layout/multiline_array_brace_layout_spec.rb, spec/rubocop/cop/layout/multiline_method_call_brace_layout_spec.rb
=> [Fix-7777-7776]: Generate valid code if comment exists before closing brace

CHANGELOG.md, lib/rubocop/cop/style/if_unless_modifier.rb, spec/rubocop/cop/style/if_unless_modifier_spec.rb
=> Fix `Style/IfUnlessModifier` bad precedence detection

lib/rubocop/config_loader.rb, lib/rubocop/file_finder.rb, spec/rubocop/file_finder_spec.rb
The `find_files_upwards` is only used to find the _last_ file upwards. So I replaced it with `find_last_file_upwards`.
It makes the code easier to understand and the new method will be useful for fixing a bug I plan to get to later.
=> Small file finding refactor

CHANGELOG.md, lib/rubocop/cop/autocorrect_logic.rb, lib/rubocop/cop/layout/multiline_block_layout.rb, spec/rubocop/cop/layout/multiline_block_layout_spec.rb
Before this commit when deciding whether to trigger a Layout/MultilineBlockLayout it would not consider any extra spaces required to join the lines. This commit fixes that issue.
For example the below would trigger a LayoutMultilineBlockLayout warning before but not anymore:
```
some_result = lambda do
|so_many, parameters, it_will, be_too_long, for_one_line, line_length, has_increased, add_3_more|
do_something
end
```
~I had to disable the AbcSize metric for the method I was extending, as much as I tried I couldn't get a nice method with an Abc < 15. The best I got was 15.07 :unamused:. I could get it < 15 but IMHO it looked worse and seemed to go against the spirit of the cop.~ (Thanks to @jonas054 I fixed this issue)
**Note:** I also updated the max_line_length to default to the new …
=> [Fix #8189] Consider spaces for Layout/MultilineBlockLayout

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_naming.adoc
Also sort these `of` entries alphabetically.
=> Add `of` to `AllowedNames` of `MethodParameterName` cop

lib/rubocop/path_util.rb, lib/rubocop/rspec/shared_contexts.rb, spec/rubocop/cli/cli_auto_gen_config_spec.rb, spec/rubocop/cli_spec.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/generator/require_file_injector_spec.rb, spec/rubocop/formatter/html_formatter_spec.rb, spec/rubocop/target_finder_spec.rb, spec/spec_helper.rb
Current code used `Dir.pwd` everywhere except for inside the `PathUtil` module itself. It also used `Dir.chdir` vs `PathUtil.chdir` inconsistently across the board.
Since the wrappers don't seem to provide anything on top of the raw functionality, I figured it'd be best to remove them?
=> Remove `PathUtil.pwd` and `PathUtil.chdir`

CHANGELOG.md, lib/rubocop/cop/style/accessor_grouping.rb, spec/rubocop/cop/style/accessor_grouping_spec.rb
=> Fix `Style/AccessorGrouping` to not register offense for accessor with comment

CHANGELOG.md, lib/rubocop/cop/layout/space_around_method_call_operator.rb
Closes #8021 
```
Finished in 44.9 seconds
$ rake prof:slow_cops
stackprof tmp/stackprof.dump --text --method 'RuboCop::Cop::Commissioner#trigger_responding_cops'
4065  (   18.0%)  RuboCop::Cop::Layout::SpaceAroundMethodCallOperator#on_send   <========== 1
509  (    2.3%)  RuboCop::Cop::Style::TrailingMethodEndStatement#on_def
386  (    1.7%)  RuboCop::Cop::Layout::IndentationConsistency#on_begin
369  (    1.6%)  RuboCop::Cop::Style::NumericPredicate#on_send
337  (    1.5%)  RuboCop::Cop::MultilineExpressionIndentation#on_send
299  (    1.3%)  RuboCop::Cop::Layout::FirstArgumentIndentation#on_send
285  (    1.3%)  RuboCop::Cop::Lint::DuplicateMethods#on_def
274  (    1.2%)  RuboCop::Cop::Metrics::ModuleLength#on_module
269  (    1.2%)  RuboCop::Cop::Layout::DefEndAlignment#on_send
264  ( …
```
=> Rewrite `Layout/SpaceAroundMethodCallOperator` cop to make it faster

spec/rubocop/cop/lint/empty_when_spec.rb, spec/rubocop/cop/lint/literal_in_interpolation_spec.rb, spec/rubocop/cop/lint/multiple_comparison_spec.rb, spec/rubocop/cop/lint/redundant_splat_expansion_spec.rb, spec/rubocop/cop/lint/rescue_type_spec.rb, spec/rubocop/cop/lint/unified_integer_spec.rb, spec/rubocop/cop/lint/unused_block_argument_spec.rb, spec/rubocop/cop/lint/unused_method_argument_spec.rb
Part of #8127
Use newer expect_correction API in Lint namespace cops.
Move expected corrections to directly follow expected offenses.
=> Refactor spec use expect_correction in Lint cops

lib/rubocop/cop/badge.rb
Profiled with `memory_profiler`.
```
$ bin/rubocop-profile lib/rubocop/cop/style
```
```
Total allocated: 682975704 bytes (8263326 objects)
Total retained:  6103832 bytes (39018 objects)
....
62890239  /Users/fatkodima/.rbenv/versions/2.6.5/lib/ruby/2.6.0/set.rb
43983225  /Users/fatkodima/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/parser-2.7.1.4/lib/parser/source/tree_rewriter.rb
43851800  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/cop/base.rb
43461557  /Users/fatkodima/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-ast-0.1.0/lib/rubocop/ast/node.rb
39761197  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/cop/style/commented_keyword.rb
28841125  /Users/fatkodima/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/r …
```
=> Memoize `Badge#to_s` to reduce memory allocations

lib/rubocop/cop/style/commented_keyword.rb
Profiled with `memory_profiler`.
```
bin/rubocop-profile lib/rubocop/cop/style
```
```
Total allocated: 681427009 bytes (8246313 objects)
Total retained:  6103832 bytes (39018 objects)
.....
62890239  /Users/fatkodima/.rbenv/versions/2.6.5/lib/ruby/2.6.0/set.rb
43983225  /Users/fatkodima/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/parser-2.7.1.4/lib/parser/source/tree_rewriter.rb
43851800  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/cop/base.rb
43461557  /Users/fatkodima/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-ast-0.1.0/lib/rubocop/ast/node.rb
39761197  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/cop/style/commented_keyword.rb       <=======
28841125 …
```
=> Optimize `Style/CommentedKeyword` to reduce memory usage

lib/rubocop/result_cache.rb
Profiled with https://github.com/SamSaffron/memory_profiler
```
$ bin/rubocop-profile
```
```
Total allocated: 103806408 bytes (777343 objects)
Total retained:  5333518 bytes (36291 objects)
.......
28757864  /Users/fatkodima/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-ast-0.1.0/lib/rubocop/ast/node_pattern.rb
14626676  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/result_cache.rb   <========
11528376  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop.rb
10214354  /Users/fatkodima/.rbenv/versions/2.6.5/lib/ruby/2.6.0/find.rb
....
```
```
Total allocated: 91409243 bytes (777654 objects)
Total retained:  5333558 bytes (36292 objects)
....
28757864 …
```
=> Reduce memory usage in `ResultCache#rubocop_checksum`

lib/rubocop/cop/lint/literal_as_condition.rb, spec/rubocop/cop/lint/debugger_spec.rb, spec/rubocop/cop/lint/duplicate_hash_key_spec.rb, spec/rubocop/cop/lint/duplicate_methods_spec.rb, spec/rubocop/cop/lint/implicit_string_concatenation_spec.rb, spec/rubocop/cop/lint/literal_as_condition_spec.rb, spec/rubocop/cop/lint/next_without_accumulator_spec.rb, spec/rubocop/cop/lint/non_local_exit_from_iterator_spec.rb, spec/rubocop/cop/lint/rand_one_spec.rb, spec/rubocop/cop/lint/redundant_splat_expansion_spec.rb, spec/rubocop/cop/lint/script_permission_spec.rb, spec/rubocop/cop/lint/unused_block_argument_spec.rb, spec/rubocop/cop/lint/useless_access_modifier_spec.rb, spec/rubocop/cop/lint/useless_comparison_spec.rb, spec/rubocop/cop/lint/void_spec.rb
Part of #8127
Use the newer `expect_offense` API to specify expected offense locations and messages.
Also fixed the offense location for `Lint/LiteralAsCondition` cop in a `case ... when condition`.
=> Refactor Lint cops to use expect_offense

lib/rubocop/cop/base.rb, lib/rubocop/cop/style/bisected_attr_accessor.rb, lib/rubocop/cop/variable_force/variable.rb
Tested with `memory_profiler`.
```
bin/rubocop-profile lib/rubocop/cop/style
```
```
Total allocated: 607510304 bytes (7590379 objects)
Total retained:  6108170 bytes (39014 objects)
62891167  /Users/fatkodima/.rbenv/versions/2.6.5/lib/ruby/2.6.0/set.rb   <=========
43983225  /Users/fatkodima/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/parser-2.7.1.4/lib/parser/source/tree_rewriter.rb
43851880  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/cop/base.rb
43484285  /Users/fatkodima/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-ast-0.1.0/lib/rubocop/ast/node.rb
28841125  /Users/fatkodima/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-ast-0.1.0/lib/rubocop/ast/node_pattern.rb
.....
```
```
Total allocated: …
```
=> Reduce allocated Sets

lib/rubocop/cop/style/trailing_method_end_statement.rb, spec/rubocop/cop/style/trailing_method_end_statement_spec.rb
I ran `bin/rubocop-profile` on the `rails/rails` source code with all cops enabled.
```
$ rake prof:slow_cops
```
```
stackprof tmp/stackprof.dump --text --method 'RuboCop::Cop::Commissioner#trigger_responding_cops'
17864  (    7.3%)  RuboCop::Cop::Style::TrailingMethodEndStatement#on_def     <=========
7838  (    3.2%)  RuboCop::Cop::Layout::SpaceInsideReferenceBrackets#on_send
7395  (    3.0%)  RuboCop::Cop::Layout::SpaceInsideArrayLiteralBrackets#on_array
4130  (    1.7%)  RuboCop::Cop::Layout::SpaceBeforeFirstArg#on_send
3993  (    1.6%)  RuboCop::Cop::Style::DocumentationMethod#on_def
3705  (    1.5%)  RuboCop::Cop::Style::NumericPredicate#on_send
......
```
```
stackprof tmp/stackprof.dump --text --method 'RuboCop::Cop::Commissioner#trigger_responding_cops'
7882  (    3.7%) …
```
=> Rewrite `Style/TrailingMethodEndStatement` to make it faster

CHANGELOG.md, docs/modules/ROOT/pages/cops_gemspec.adoc, lib/rubocop/cop/gemspec/required_ruby_version.rb, spec/rubocop/cop/gemspec/required_ruby_version_spec.rb
It's possible to use `required_ruby_version` to allow all minor versions of a particular major version of Ruby:
spec.required_ruby_version = '~> 2'
Previously this would cause `Gemspec/RequiredRubyVersion` to crash with:
undefined method `[]' for nil:NilClass
lib/rubocop/cop/gemspec/required_ruby_version.rb:71:in `extract_ruby_version'
I discovered this problem by running RuboCop on the [real-world-ruby-apps](https://github.com/jeromedalbert/real-world-ruby-apps) repo, which includes the htty gem:
https://github.com/htty/htty/blob/8db7a36d5dffcd6eef66580f052a86bcf1f3636b/htty.gemspec#L21
I've added docs and tests for the pessimistic operator, which otherwise works well.
[1]: …
=> Handle major version requirements in Gemspec/RequiredRubyVersion

lib/rubocop/cop/lint/duplicate_methods.rb, lib/rubocop/cop/lint/nested_method_definition.rb, lib/rubocop/cop/style/auto_resource_cleanup.rb, lib/rubocop/cop/style/numeric_predicate.rb
Tested on `rails` codebase.
```
stackprof tmp/stackprof.dump --text --method 'RuboCop::Cop::Commissioner#trigger_responding_cops'
8202  (    3.5%)  RuboCop::Cop::Layout::SpaceInsideReferenceBrackets#on_send
8089  (    3.4%)  RuboCop::Cop::Layout::SpaceInsideArrayLiteralBrackets#on_array
4437  (    1.9%)  RuboCop::Cop::Layout::SpaceBeforeFirstArg#on_send
4172  (    1.8%)  RuboCop::Cop::Style::DocumentationMethod#on_def
3988  (    1.7%)  RuboCop::Cop::Style::NumericPredicate#on_send   <============= 1
3642  (    1.5%)  RuboCop::Cop::Layout::IndentationConsistency#on_begin
3596  (    1.5%)  RuboCop::Cop::Layout::FirstArgumentIndentation#on_send
3428  (    1.5%)  RuboCop::Cop::Lint::DuplicateMethods#on_def       <============= 2
3079  (    1.3%) …
```
=> Optimize `Lint/DuplicateMethods`, `Lint/NestedMethodDefinition`, `Style/AutoResourceCleanup` and `Style/NumericPredicate` cops a bit

tasks/cut_release.rake
This PR wraps quotes as a string to prevent `1.10` from interpreted as `1.1` for docs/antora.yml.
Without quoting, version `1.10` is interpreted as float `1.1`, so final `0` is missing.
=> Prevent missing final zero of version number for docs/antora.yml

CHANGELOG.md, lib/rubocop/cop/style/percent_literal_delimiters.rb, spec/rubocop/cop/style/percent_literal_delimiters_spec.rb
Previously this would crash with:
ArgumentError: invalid byte sequence in UTF-8
lib/rubocop/cop/style/percent_literal_delimiters.rb:105:in `match?'
I discovered this problem by running RuboCop on the [real-world-rails](https://github.com/eliotsykes/real-world-rails) repo, which includes the discourse repo:
https://github.com/discourse/discourse/blob/544a9865c6e5890f37e762292cbe5558db843dcf/spec/helpers/application_helper_spec.rb#L263
=> Handle invalid characters in Style/PercentLiteralDelimiters

lib/rubocop/rspec/expect_offense.rb
Fixes `[...]` abbreviation introduced in #8297
Fix crash in `expect_offense` where multiple offenses are detected by the
cop by some were not included in the annotated source. For example:
```ruby
expect_offense(<<~RUBY)
x % 2 == 0
^^^^^^^^^^ Replace with `Integer#even?`
x % 2 != 0
RUBY
```
=> Fix expect_offense when annotations missing

lib/rubocop/rspec/expect_offense.rb
An offense added by a cop to an empty file with have line number = 1.
For example:
```ruby
RSpec.describe RuboCop::Cop::Style::Copyright, :config do
context 'when the source code file is empty' do
it 'registers an offense' do
expect_offense('^ Include a copyright notice matching [...]')
end
end
end
```
Ensure the line number matches for `expect_offense` on an empty file.
=> Fix line number for empty file offense

CHANGELOG.md, lib/rubocop/config_loader.rb, lib/rubocop/file_finder.rb, lib/rubocop/rspec/shared_contexts.rb, spec/rubocop/config_loader_spec.rb
In previous PRs, #8176 and #8239, I fixed particular cases of this problem, but it was still not fixed in general. So, if I have my personal configuration at `~/.config/rubocop/config.yml` and my project is at `~/Code/my_project`, then my personal configuration won't be loaded thanks to those PRs. However, if I have my personal configuration at `~/.rubocop.yml`, then `rubocop` will still load exclusions from there because `$HOME` is an ancestor of the current project folder, and that's how `find_last_file_upwards` currently works.
To fix this problem in general, I made sure `find_last_file_upwards` (and any configuration search in general) doesn't go past the current project's root. To do that, I needed to define what the root of a project is. While there were other options, like presence …
=> Don't load configuration files outside of the current project unless there's no project specific configuration

CHANGELOG.md, lib/rubocop/cop/layout/space_around_method_call_operator.rb, spec/rubocop/cop/layout/space_around_method_call_operator_spec.rb
=> Fix crash for `Layout/SpaceAroundMethodCallOperator` when using `Proc#call` shorthand syntax

CHANGELOG.md, lib/rubocop/cop/style/hash_as_last_array_item.rb, spec/rubocop/cop/style/hash_as_last_array_item_spec.rb
=> Fix a false positive for `Style/HashAsLastArrayItem` when hash is not a last array item

CHANGELOG.md, lib/rubocop/cop/style/redundant_condition.rb, spec/rubocop/cop/style/redundant_condition_spec.rb
Fixes #8299
This PR fixes an incorrect auto-correct for `Style/RedundantCondition` when using `raise` without argument parentheses in `else`.
=> [Fix #8299] Fix an incorrect auto-correct for `Style/RedundantCondition`

CHANGELOG.md, lib/rubocop/cop/style/redundant_regexp_escape.rb, spec/rubocop/cop/style/redundant_regexp_escape_spec.rb
The previous code wouldn't detect character classes that had ":" as
their first element (due to a poor attempt at avoiding issues due to
POSIX bracket expressions). The handling of nested character classes was
also improved to avoid false-negatives.
=> [Fix #8335] Improve class detection in `Style/RedundantRegexpEscape`

lib/rubocop/comment_config.rb
This PR fixes the following build error when using Ruby 2.8.0-dev.
```console
% ruby -v
ruby 2.8.0dev (2020-07-14T04:19:55Z master e60cd14d85) [x86_64-darwin17]
% bundle exec rspec ./spec/rubocop/cop/lint/redundant_cop_disable_directive_spec.rb:47
Run options: include {:focus=>true,
:locations=>{"./spec/rubocop/cop/lint/redundant_cop_disable_directive_spec.rb"=>[47]}}
Randomized with seed 2998
F
Failures:
1) RuboCop::Cop::Lint::RedundantCopDisableDirective.check when there
are disabled lines and there are no offenses and a comment disables
itself and another cop disabled on the same range returns no offense
Failure/Error: range.cover?(line_range.min) && range.cover?(line_range.max)
FloatDomainError:
Infinity
```
The above error is due to the following Ruby 2.8.0-dev's changeset. …
=> Fix build error when using Ruby 2.8.0-dev

CHANGELOG.md, lib/rubocop/cop/style/case_like_if.rb, spec/rubocop/cop/style/case_like_if_spec.rb
=> Fix crash for `Style/CaseLikeIf` when checking against `equal?` and `match?` without a receiver

CHANGELOG.md, lib/rubocop/cop/style/multiline_method_signature.rb
Follow up #7952.
This PR sets default max line length to 120 for `Style/MultilineMethodSignature`.
A forgotten change have been found as well as:
https://github.com/rubocop-hq/rubocop/pull/8203/files#diff-533235edf6b414408f1b9f380c00af0d
=> Set default max line length to 120 for `Style/MultilineMethodSignature`

CHANGELOG.md, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
`class Point < Struct.new(:x, :y); end` was getting auto-corrected to
`class Point < Struct.new :x, :y; end` which is invalid Ruby code. Allow
the parentheses in this case for the following configurations:
```ruby
Style/MethodCallWithArgsParentheses:
EnforcedStyle: omit_parentheses
```
=> Allow parentheses in single-line inheritance

lib/rubocop/cop/lint/ambiguous_block_association.rb, lib/rubocop/cop/lint/big_decimal_new.rb, lib/rubocop/cop/lint/debugger.rb, lib/rubocop/cop/lint/deprecated_class_methods.rb, lib/rubocop/cop/lint/duplicate_methods.rb, lib/rubocop/cop/lint/format_parameter_mismatch.rb, lib/rubocop/cop/lint/ineffective_access_modifier.rb, lib/rubocop/cop/lint/inherit_exception.rb, lib/rubocop/cop/lint/interpolation_check.rb, lib/rubocop/cop/lint/rand_one.rb, lib/rubocop/cop/lint/uri_regexp.rb
Ran on larger `discourse` codebase (3.5k files).
```
$ bin/rubocop-profile --force-default-config --cache false --only Lint ../discourse
```
```
1   965  (    7.3%)  RuboCop::Cop::Lint::DeprecatedClassMethods#on_send
2   952  (    7.2%)  RuboCop::Cop::Lint::Debugger#on_send
3   806  (    6.1%)  RuboCop::Cop::Lint::AmbiguousBlockAssociation#on_send
642  (    4.8%)  RuboCop::Cop::Lint::ParenthesesAsGroupedExpression#on_send
623  (    4.7%)  RuboCop::Cop::Lint::SafeNavigationChain#on_send
4   605  (    4.6%)  RuboCop::Cop::Lint::FormatParameterMismatch#on_send
5   533  (    4.4%)  RuboCop::Cop::Lint::DuplicateMethods#on_send
6   500  (    3.8%)  RuboCop::Cop::Lint::InterpolationCheck#on_str
7   493  (    3.7%)  RuboCop::Cop::Lint::IneffectiveAccessModifier#on_class
8   473  (    3.6%) …
```
=> Small `Lint` cops perf tweaks

CHANGELOG.md, lib/rubocop/cop/style/hash_syntax.rb, spec/rubocop/cli/cli_autocorrect_spec.rb
Fixes #8347.
This PR fixes an incorrect auto-correct for `EnforcedStyle: hash_rockets` of `Style/HashSyntax` with `Layout/HashAlignment`.
=> [Fix #8347] Fix an incorrect auto-correct for `Style/HashSyntax`

lib/rubocop/path_util.rb, lib/rubocop/target_finder.rb
I tested only startup time (before any cop starts running):
```
$ exe/rubocop --force-default-config --cache false ../discourse
```
```
Finished in 16.0 seconds
```
```
Total allocated: 625.52 MB (11372432 objects)
Total retained:  5.48 MB (46807 objects)
allocated memory by location
120.67 MB  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/path_util.rb:58
89.80 MB  /Users/fatkodima/.rbenv/versions/2.7.0/lib/ruby/2.7.0/pathname.rb:42
68.33 MB  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/target_finder.rb:120
67.99 MB  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/target_finder.rb:131
64.09 MB  /Users/fatkodima/.rbenv/versions/2.7.0/lib/ruby/2.7.0/pathname.rb:46
24.98 MB  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/target_finder.rb:135 …
```
=> Optimize cli startup time and memory

lib/rubocop/cop/commissioner.rb
`@cops` does not change, so `@callbacks` need not be invalidated. Not particularly relevant as `Commissionner` are currently recreated, but that could change
=> No need to clear this cache.

lib/rubocop/cop/mixin/code_length.rb
Was removed in #8356, but rubocop-rspec uses it.
See https://github.com/rubocop-hq/rubocop-rspec/issues/974
=> Put back CodeLength#irrelevant_line.

CHANGELOG.md, lib/rubocop/config.rb, spec/rubocop/config_spec.rb
I noticed that `for_department` is quite error prone. This fixes it:
* Don't rely on the department name being an unknown cop. E.g. `for_department('Foo')` would return the config for the cop "Foo/Foo" if it exists, instead of the department's.
* Don't provide 'Enabled' at the department level unless it is specified in the config.
* Accept symbols (like that returned by `Badge#department`) too
=> Config#for_department: be more accurate

CHANGELOG.md, lib/rubocop/config.rb, lib/rubocop/cop/base.rb, spec/rubocop/config_spec.rb
This optimization saves about 5MB of unneeded intermediate hashes...
=> Add Config#for_badge

spec/rubocop/cop/style/parallel_assignment_spec.rb
This reverts commit 7743366d6ed9203d16cae443b8b8e22a54cc21ba.
https://github.com/jruby/jruby/issues/5968 has been solved by JRuby 9.2.12.0.
=> Revert "Workaround to skip some tests when using JRuby"

CHANGELOG.md, lib/rubocop/cop/style/empty_method.rb, spec/rubocop/cop/style/empty_method_spec.rb
This PR fixes the following infinite loop error for `Style/EmptyMethod`.
```ruby
def foo(arg
); end
```
The following error occurs without auto-correction.
```console
% bundle exec rubocop --only Style/EmptyMethod -a example.rb
(snip)
Offenses:
example.rb:1:1: C: [Corrected] Style/EmptyMethod: Put empty method
definitions on a single line.
def foo(arg ...
^^^^^^^^^^^^
/Users/koic/src/github.com/koic/rubocop-issues/empty_method/example.rb.
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/runner.rb:288:in `check_for_infinite_loop'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/runner.rb:271:in `block in iterate_until_no_changes' …
```
=> Fix an infinite loop error for `Style/EmptyMethod`

lib/rubocop/comment_config.rb
This reverts commit ee123f42b505f2ae91cd53db0af247bcc3e6cade.
See #8343
=> Revert "Fix build error when using Ruby 2.8.0-dev"

lib/rubocop/cop/style/string_concatenation.rb, spec/rubocop/cop/style/string_concatenation_spec.rb
Not a native speaker, but from my point of view it should either be:
- "Prefer string interpolation to string concatenation", or
- "Prefer using string interpolation instead of string concatenation"
Rationale:
concatenation is a noun
example from dictionary.com: "those who prefer the bittersweet **to** the saccharine"
```diff
- Prefer string interpolation and string formatting instead of string concatenation:
+ Prefer using string interpolation and string formatting instead of string concatenation:
+ Prefer string interpolation and string formatting to string concatenation:
```
* [-] Added an entry to the …
=> Fix spelling mistake

docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/ensure_return.rb, spec/rubocop/cop/lint/ensure_return_spec.rb
`Lint/EnsureReturn` autocorrection had many issues.
It was attempting to autocorrect `return` statements but was producing completely different expressions, potentiall losing comments too.
There is no way to auto-correct a `return` statement in an ensure because without one, the result of the block is not the last expression of the ensure block:
```
def foo
bar
ensure
return 42
end
```
This always return `42` and not the result of `bar`, and there is no other ensure block that can do this.
=> [fixes #8385] Fix Lint/EnsureReturn autocorrect and false negatives

lib/rubocop/rspec/expect_offense.rb
Before
```
1) RuboCop::Cop::Style::RedundantPercentQ with %q strings registers an offense for only single quotes
Failure/Error: expect(actual_annotations).to eq(expected_annotations)#, ''
expected: %q('hi')
^^^^^^^^ Use `%q` only for strings that contain oth single quotes and double quotes.
got: %q('hi')
^^^^^^^^ Use `%q` only for strings that contain both single quotes and double quotes.
(compared using ==)
Diff:
@@ -1,3 +1,3 @@
%q('hi')
-^^^^^^^^ Use `%q` only for strings that contain oth single quotes and double quotes.
+^^^^^^^^ Use `%q` only for strings that contain both single quotes and double quotes.
```
After
```
1) RuboCop::Cop::Style::RedundantPercentQ with %q strings registers an offense for only single quotes
Failure/Error: expect(actual_annotations).to …
```
=> Remove a useless section from spec output

lib/rubocop/cop/layout/empty_lines.rb, lib/rubocop/cop/layout/extra_spacing.rb, lib/rubocop/cop/layout/indentation_style.rb, lib/rubocop/cop/metrics/utils/code_length_calculator.rb, lib/rubocop/cop/style/bisected_attr_accessor.rb, lib/rubocop/target_finder.rb
Follow https://github.com/rubocop-hq/rubocop/commit/8798bc8.
~~RuboCop AST 0.1.0 requires `Set`.~~
~~https://github.com/rubocop-hq/rubocop-ast/commit/8e595c3.~~
~~RuboCop requires RuboCop AST 0.1.0 or higher. Therefore this PR removes redundant `require 'set'`.~~
This PR makes RuboCop to explicitly require `set` only once at lib/rubocop.rb
https://github.com/rubocop-hq/rubocop/blob/v0.88.0/lib/rubocop.rb#L6
It focuses on the obviously redundant code in the rubocop repository.
=> Remove redundant `require 'set'`

CHANGELOG.md, lib/rubocop/cop/metrics/cyclomatic_complexity.rb, lib/rubocop/cop/mixin/method_complexity.rb, lib/rubocop/cop/style/conditional_assignment.rb, lib/rubocop/cop/style/if_inside_else.rb, spec/rubocop/cop/metrics/cyclomatic_complexity_spec.rb
This PR builds on #8037 
See #8276 for discussion.
=> [Fixes #8276] Metrics/CyclomaticComplexity now discounts repeated uses of &. on same lvar receiver

CHANGELOG.md, lib/rubocop/cop/style/accessor_grouping.rb, spec/rubocop/cop/style/accessor_grouping_spec.rb
Fixes #8406.
This PR improves `Style/AccessorGrouping`'s auto-correction to remove redundant blank lines.
This PR doesn't update to `Cop::Base` to make it clear the difference between the changes. Will be updated with other `Style` cops in different PR.
=> [Fix #8406] Improve `Style/AccessorGrouping`'s auto-correction

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_metrics.adoc, lib/rubocop/cop/lint/redundant_cop_disable_directive.rb, lib/rubocop/cop/metrics/perceived_complexity.rb, lib/rubocop/cop/style/identical_conditional_branches.rb, lib/rubocop/cop/variable_force/variable.rb, spec/rubocop/cop/metrics/perceived_complexity_spec.rb
`Metrics/PerceivedComplexity` currently ignores `else` branches in `case` statement which seems like a clear bug, considering the weight if gives to `else` in if statements:
```ruby
if foo
bar
else
baz
end
case
when foo
bar
else
baz
end
```
For the rest, there's no clear definition of what `PerceivedComplexity` is  supposed to do, but it sounds like it's the same thing as `CyclomaticComplexity` with a twist for `case` and `if` with `else`.
This PR fixes the `else` issue and makes the same changes that #8149 made for CyclomaticComplexity (`||=`, iterating methods, etc.) Default bumped also from 7 to 8. 3 new todos all of which are already CyclomaticComplexity todos.
If we're ok with these fixes, it would be best for v1 as it is breaking.
=> Tweaks to Metrics/PerceivedComplexity

CHANGELOG.md, lib/rubocop/cop/style/missing_respond_to_missing.rb, spec/rubocop/cop/style/missing_respond_to_missing_spec.rb
Fixes #8330.
This PR fixes a false positive for `Style/MissingRespondToMissing` when defined method with inline access modifier.
=> [Fix #8330] Fix a false positive for `Style/MissingRespondToMissing`

CHANGELOG.md, lib/rubocop/cop/lint/self_assignment.rb, spec/rubocop/cop/lint/self_assignment_spec.rb
Fixes #8422.
Fix an error for `Lint/SelfAssignment` when using or-assignment for constant.
=> [Fix #8422] Fix an error for `Lint/SelfAssignment`

CHANGELOG.md, lib/rubocop/cop/style/single_argument_dig.rb, spec/rubocop/cop/style/single_argument_dig_spec.rb
Fixes #8423.
This PR fixes an error for `Style/SingleArgumentDig` when without a receiver.
This cop wouldn't have to offense when `dig` method without a receiver.
=> [Fix #8423] Fix an error for `Style/SingleArgumentDig`

CHANGELOG.md, lib/rubocop/cop/lint/ineffective_access_modifier.rb, spec/rubocop/cop/lint/ineffective_access_modifier_spec.rb
Fixes #8424.
This PR fixes an error for `Lint/IneffectiveAccessModifier` when there is `begin...end` before a method definition.
=> [Fix #8424] Fix an error for `Lint/IneffectiveAccessModifier`

config/default.yml, docs/modules/ROOT/pages/cops_layout.adoc
This PR fixes a style guide link for `Layout/SpaceInsideHashLiteralBraces`.
=> Fix a style guide link for `Layout/SpaceInsideHashLiteralBraces`

spec/rubocop/cop/style/for_spec.rb, spec/rubocop/cop/style/format_string_spec.rb, spec/rubocop/cop/style/format_string_token_spec.rb, spec/rubocop/cop/style/guard_clause_spec.rb, spec/rubocop/cop/style/hash_syntax_spec.rb, spec/rubocop/cop/style/hash_transform_keys_spec.rb, spec/rubocop/cop/style/hash_transform_values_spec.rb, spec/rubocop/cop/style/if_unless_modifier_spec.rb, spec/rubocop/cop/style/infinite_loop_spec.rb, spec/rubocop/cop/style/inverse_methods_spec.rb, spec/rubocop/cop/style/lambda_call_spec.rb, spec/rubocop/cop/style/lambda_spec.rb, spec/rubocop/cop/style/line_end_concatenation_spec.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb, spec/rubocop/cop/style/method_call_without_args_parentheses_spec.rb, spec/rubocop/cop/style/method_def_parentheses_spec.rb, spec/rubocop/cop/style/min_max_spec.rb, spec/rubocop/cop/style/mixin_grouping_spec.rb, spec/rubocop/cop/style/multiline_if_modifier_spec.rb, spec/rubocop/cop/style/multiline_if_then_spec.rb, spec/rubocop/cop/style/multiline_memoization_spec.rb, spec/rubocop/cop/style/multiline_when_then_spec.rb, spec/rubocop/cop/style/mutable_constant_spec.rb
Part of #8127
Use newer `expect_offense` and `expect_correction` in specs for Style cops F-M.
Merge `'register offense'` and `'auto-correct'` spec examples where possible.
Restores trailing whitespace to `method_call_with_args_paretheses_spec.rb` that was accidentally removed by merging examples in #7026
=> Use new expect_correction in Style F-M

spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
Follow-up to 56f074d48 [#8438]
=> Avoid actual trailing whitespaces.

spec/rubocop/cop/style/access_modifier_declarations_spec.rb, spec/rubocop/cop/style/alias_spec.rb, spec/rubocop/cop/style/and_or_spec.rb, spec/rubocop/cop/style/array_join_spec.rb, spec/rubocop/cop/style/attr_spec.rb, spec/rubocop/cop/style/bare_percent_literals_spec.rb, spec/rubocop/cop/style/block_comments_spec.rb, spec/rubocop/cop/style/block_delimiters_spec.rb, spec/rubocop/cop/style/character_literal_spec.rb, spec/rubocop/cop/style/class_and_module_children_spec.rb, spec/rubocop/cop/style/class_check_spec.rb, spec/rubocop/cop/style/class_methods_spec.rb, spec/rubocop/cop/style/collection_methods_spec.rb, spec/rubocop/cop/style/colon_method_call_spec.rb, spec/rubocop/cop/style/command_literal_spec.rb, spec/rubocop/cop/style/comment_annotation_spec.rb, spec/rubocop/cop/style/conditional_assignment_assign_in_condition_spec.rb, spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb, spec/rubocop/cop/style/copyright_spec.rb, spec/rubocop/cop/style/def_with_parentheses_spec.rb, spec/rubocop/cop/style/dir_spec.rb, spec/rubocop/cop/style/documentation_spec.rb, spec/rubocop/cop/style/each_for_simple_loop_spec.rb, spec/rubocop/cop/style/each_with_object_spec.rb, spec/rubocop/cop/style/empty_case_condition_spec.rb, spec/rubocop/cop/style/empty_else_spec.rb, spec/rubocop/cop/style/empty_literal_spec.rb, spec/rubocop/cop/style/empty_method_spec.rb, spec/rubocop/cop/style/encoding_spec.rb, spec/rubocop/cop/style/even_odd_spec.rb
Part of #8127
Use newer `expect_offense` and `expect_correction` in specs for Style cops A-E.
Merge `'register offense'` and `'auto-correct'` spec examples where possible.
=> Use new expect_correction in Style A-E

CHANGELOG.md, lib/rubocop/cop/mixin/statement_modifier.rb, lib/rubocop/cop/style/if_unless_modifier.rb, spec/rubocop/cop/style/if_unless_modifier_spec.rb
Fixes #8283.
Fixes #8226.
Fixes #8025, #8006, #7969 (look like duplicates).
1. The code to calculate line length for `Style/IfUnlessModifier` when considering conversion to single-line form now uses the same method that actually computes the replacement. This allows us to take into account a comment on a first line of the if-end condition or some code that is on the same line before the if-condition (which both contribute to the line length).
2. Added code so that if-end condition that is either an element of an array or a value of a hash now correctly converted to a single-line form with parentheses.
=> [Fix #8283] Fix length calculation for `Style/IfUnlessModifier`

CHANGELOG.md, lib/rubocop/cop/style/struct_inheritance.rb, spec/rubocop/cop/style/struct_inheritance_spec.rb
This PR fixes the following incorrect auto-correct for `Style/StructInheritance` incorrect auto-correct for `Style/StructInheritance` when there is a comment before class declaration.
```console
class Foo < Struct.new(:foo)
end
% bundle exec rubocop --only Style/StructInheritance -a
(snip)
Offenses:
example.rb:2:13: C: [Corrected] Style/StructInheritance: Don't extend an
instance initialized by Struct.new. Use a block to customize the struct.
class Foo < Struct.new(:foo)
^^^^^^^^^^^^^^^^
end
```
This issue has been reported on rubocop-jp. (Japanese)
https://github.com/rubocop-hq/rubocop-jp/issues/61
[1]: …
=> Fix an incorrect auto-correct for `Style/StructInheritance`

CHANGELOG.md, lib/rubocop/cop/layout/first_method_argument_line_break.rb, spec/rubocop/cop/layout/first_method_argument_line_break_spec.rb
Fixes #8444.
This PR fixes an error for `Layout/FirstMethodArgumentLineBreak` when using kwargs in `super`
=> [Fix #8444] Fix an error for `Layout/FirstMethodArgumentLineBreak

CHANGELOG.md, lib/rubocop/cop/mixin/statement_modifier.rb, spec/rubocop/cop/style/if_unless_modifier_spec.rb
=> [Fix #7957] Fix Style/IfUnlessModifier to remain multiline if code after end keyword makes it too long

lib/rubocop/cop/style/explicit_block_argument.rb, spec/rubocop/cop/style/explicit_block_argument_spec.rb
A trailing comma is valid syntax after the last positional argument, but not after a block argument.
$ ruby -ce "foo(a, b,)"
Syntax OK
$ ruby -ce "foo(a, &b,)"
-e:1: syntax error, unexpected ',', expecting ')'
foo(a, &b,)
I didn't add a changelog entry because this cop hasn't been released yet.
=> Handle trailing comma in method call argument list in Style/ExplicitBlockArgument

docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/explicit_block_argument.rb, spec/rubocop/cop/style/explicit_block_argument_spec.rb
I don't see a reason not to handle this case, and it's far more common in our codebase than the case where yield is called with arguments.
As with https://github.com/rubocop-hq/rubocop/pull/8453, I didn't add a changelog entry because this cop hasn't been released yet.
=> Register an offense for yield without arguments in Style/ExplicitBlockArgument

spec/rubocop/cop/layout/def_end_alignment_spec.rb, spec/rubocop/cop/layout/empty_lines_around_access_modifier_spec.rb, spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb, spec/rubocop/cop/layout/empty_lines_around_begin_body_spec.rb, spec/rubocop/cop/layout/empty_lines_around_block_body_spec.rb, spec/rubocop/cop/layout/empty_lines_around_class_body_spec.rb, spec/rubocop/cop/layout/empty_lines_around_exception_handling_keywords_spec.rb, spec/rubocop/cop/layout/empty_lines_around_method_body_spec.rb, spec/rubocop/cop/layout/empty_lines_around_module_body_spec.rb, spec/rubocop/cop/layout/empty_lines_spec.rb, spec/support/empty_lines_around_body_shared_examples.rb
Part of #8127
Refactor specs in spec/rubocop/cop/layout/ starting with letters (A-E) to use newer helpers `expect_offense` / `expect_correction` instead of old `inspect_source` / `autocorrect_source`
=> Refactor spec/rubocop/cop/layout/ to use expect_offense (A-E). #8127

lib/rubocop/cop/layout/multiline_method_argument_line_breaks.rb, lib/rubocop/cop/mixin/check_line_breakable.rb
Required for rubocop-hq/rubocop-ast#91
=> Don't mutate `#arguments`.

lib/rubocop.rb, lib/rubocop/cop/mixin/surrounding_space.rb, lib/rubocop/cop/tokens_util.rb, lib/rubocop/cop/util.rb
Ran on 30k files.
```
(1) 74659  (    6.8%)  RuboCop::Cop::Layout::SpaceInsideReferenceBrackets#on_send
(2) 39346  (    3.6%)  RuboCop::Cop::Layout::SpaceInsideArrayLiteralBrackets#on_array
38575  (    3.5%)  RuboCop::Cop::Style::RedundantSelf#on_block
33935  (    3.1%)  RuboCop::Cop::Layout::SpaceBeforeFirstArg#on_send
26757  (    2.4%)  RuboCop::Cop::Layout::FirstArgumentIndentation#on_send
26271  (    2.4%)  RuboCop::Cop::StringHelp#on_str
24590  (    2.2%)  RuboCop::Cop::Layout::DefEndAlignment#on_send
23826  (    2.2%)  RuboCop::Cop::Layout::IndentationConsistency#on_begin
(3) 17870  (    1.6%)  RuboCop::Cop::Layout::SpaceInsideHashLiteralBraces#on_hash
16582  (    1.5%)  RuboCop::Cop::MultilineExpressionIndentation#on_send
15623  (    1.4%)  RuboCop::Cop::Interpolation#on_dstr …
```
=> Optimize getting node tokens

lib/rubocop/cop/style/access_modifier_declarations.rb, lib/rubocop/cop/style/colon_method_call.rb, lib/rubocop/cop/style/eval_with_location.rb, lib/rubocop/cop/style/expand_path_arguments.rb, lib/rubocop/cop/style/format_string.rb, lib/rubocop/cop/style/format_string_token.rb, lib/rubocop/cop/style/hash_syntax.rb, lib/rubocop/cop/style/inverse_methods.rb, lib/rubocop/cop/style/method_call_without_args_parentheses.rb, lib/rubocop/cop/style/numeric_predicate.rb, lib/rubocop/cop/style/random_with_offset.rb, lib/rubocop/cop/style/redundant_exception.rb, lib/rubocop/cop/style/redundant_sort.rb, lib/rubocop/cop/style/signal_exception.rb, lib/rubocop/cop/style/zero_length_predicate.rb
Ran on `discourse` codebase:
```
$ bin/rubocop-profile --force-default-config --cache false --only Style ../discourse
```
```
5228  (    9.0%)  RuboCop::Cop::Style::RedundantSelf#on_block
3376  (    5.8%)  RuboCop::Cop::StringHelp#on_str
1   1975  (    3.4%)  RuboCop::Cop::Style::AccessModifierDeclarations#on_send
2   1960  (    3.4%)  RuboCop::Cop::Style::FormatStringToken#on_str
1712  (    2.9%)  RuboCop::Cop::Style::TrailingCommaInArguments#on_send
3   1560  (    2.7%)  RuboCop::Cop::Style::NumericPredicate#on_send
1471  (    2.5%)  RuboCop::Cop::Style::ConditionalAssignment#on_send
4   1453  (    2.5%)  RuboCop::Cop::Style::MethodCallWithoutArgsParentheses#on_send
5   1278  (    2.2%)  RuboCop::Cop::Style::ZeroLengthPredicate#on_send
6   1150  (    2.0%) …
```
=> Small `Style` cops perf tweaks

docs/modules/ROOT/pages/usage/basic_usage.adoc
On the [Command Line flags page](https://docs.rubocop.org/rubocop/usage/basic_usage.html#command-line-flags), the "See Auto-correct" hyperlink is malformed. Currently it points to `xref:auto_correct.adoc` when it should be `xref:usage/auto_correct.adoc`
I wasn't sure if this warranted being included in the changle-log, I couldn't see any examples of others like this in the past so I excluded it and it doesn't look like there's any tests on the docs so these were excluded also.
Edit: These CI Failures seem unrelated to my changes and I took the current master if that helps for my fork
=> adds fix for usage docs to point to correct auto-correct docs

CHANGELOG.md, lib/rubocop/cop/lint/out_of_range_regexp_ref.rb, spec/rubocop/cop/lint/out_of_range_regexp_ref_spec.rb
Last match global variables are set when the regexp is matched, not when it's defined. This meant that the previous implementation gave incorrect results when those things happened separately, e.g. when a regexp was assigned to a local variable or a constant and then matched elsewhere.
This change means that the cop only handles matching on regexp literals, but that was the only case where it worked correctly before anyway. It should be possible to improve the cop to handle more complex cases with `VariableForce`, but that can be done as a separate change.
=> Set valid ref range when regexp is matched in Lint/OutOfRangeRegexpRef

CHANGELOG.md, lib/rubocop/cop/mixin/range_help.rb, lib/rubocop/cop/style/nested_parenthesized_calls.rb, spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb, spec/rubocop/cop/layout/multiline_operation_indentation_spec.rb, spec/rubocop/cop/style/nested_parenthesized_calls_spec.rb, spec/rubocop/cop/style/redundant_percent_q_spec.rb, spec/rubocop/cop/style/string_literals_in_interpolation_spec.rb, spec/rubocop/cop/style/string_literals_spec.rb
When describing the code that should be detected / auto-corrected, some specs do not escape line continuations properly.
For example:
```ruby
<<~RUBY
something \
continues
RUBY
```
results in the string `"something   continues\n"` instead of the desired `"something \\\n  continues\n"`
Correct specs escape the backslash or use single quoted heredocs to keep the line continuation in the source under test, like:
```ruby
<<~'RUBY'
something \
continues
RUBY
<<~RUBY
something \\
continues
RUBY
```
In correcting the specs, it became apparent that `Style/NestedParenthesizedCalls` cop did not behave as intended. `RangeHelp` mixin has been adapted to optionally include line continuations (backslash newline sequence).
Feedback is welcome on whether this behaviour on replacing whitespace with …
=> Fix line continuations in spec examples

CHANGELOG.md, lib/rubocop/cop/lint/uri_regexp.rb, spec/rubocop/cop/lint/uri_regexp_spec.rb
Fixes #8466.
This PR fixes a false positive for `Lint/UriRegexp` when using `regexp` method without receiver.
=> [Fix #8466] Fix a false positive for `Lint/UriRegexp`

spec/rubocop/cop/style/negated_if_spec.rb, spec/rubocop/cop/style/negated_unless_spec.rb, spec/rubocop/cop/style/negated_while_spec.rb, spec/rubocop/cop/style/nested_modifier_spec.rb, spec/rubocop/cop/style/nested_parenthesized_calls_spec.rb, spec/rubocop/cop/style/next_spec.rb, spec/rubocop/cop/style/nil_comparison_spec.rb, spec/rubocop/cop/style/non_nil_check_spec.rb, spec/rubocop/cop/style/not_spec.rb, spec/rubocop/cop/style/numeric_literal_prefix_spec.rb, spec/rubocop/cop/style/numeric_literals_spec.rb, spec/rubocop/cop/style/numeric_predicate_spec.rb, spec/rubocop/cop/style/one_line_conditional_spec.rb, spec/rubocop/cop/style/or_assignment_spec.rb, spec/rubocop/cop/style/parallel_assignment_spec.rb, spec/rubocop/cop/style/parentheses_around_condition_spec.rb, spec/rubocop/cop/style/percent_literal_delimiters_spec.rb, spec/rubocop/cop/style/percent_q_literals_spec.rb, spec/rubocop/cop/style/perl_backrefs_spec.rb, spec/rubocop/cop/style/proc_spec.rb
Part of #8127
Use newer `expect_offense` and `expect_correction` in specs for Style cops N-P
Merge `'register offense'` and `'auto-correct'` spec examples where possible.
* Use single-quoted heredoc for nested_parenthesized_calls_spec line continuation
=> Use new expect_correction in Style N-P

lib/rubocop/cop/lint/uri_regexp.rb, spec/rubocop/cop/lint/uri_regexp_spec.rb
Follow https://github.com/rubocop-hq/rubocop/pull/8467#issuecomment-669996714.
This PR fixes false positive for `Lint/UriRegexp` when using `regexp` with variable receiver.
=> Fix a false positive for `Lint/UriRegexp`

CHANGELOG.md, lib/rubocop/cop/correctors/percent_literal_corrector.rb, spec/rubocop/cop/style/symbol_array_spec.rb, spec/rubocop/cop/style/word_array_spec.rb
Fix line number when array element contains newline so that extra newlines
are not added to the result
Use `expect_correction` for embedded newline in percent literal array
=> Fix autocorrect for percent literal array with newlines

CHANGELOG.md, lib/rubocop/cop/lint/out_of_range_regexp_ref.rb, spec/rubocop/cop/lint/out_of_range_regexp_ref_spec.rb
Followup to @marcandre's comment here: https://github.com/rubocop-hq/rubocop/pull/8463#issuecomment-669550324
`when`, `grep`, `gsub`, `gsub!` `sub`, `sub!`, `[]`, `slice`, `slice!` `scan`, `index`, `rindex`, `partition`, `rpartition`, `start_with?`, and `end_with?` can all be used to match regexps and set last match global variables, so we should update the range of valid references when we encounter them.
These were all of the relevant methods I could find from a quick grep of [ruby/spec](https://github.com/ruby/spec), although there could well be more.
**Update:** I read through the [String class' docs](https://ruby-doc.org/core-2.7.1/String.html) and added several more methods.
[1]: …
=> Handle more matching methods in Lint/OutOfRangeRegexpRef

spec/rubocop/cop/style/ternary_parentheses_spec.rb, spec/rubocop/cop/style/trailing_body_on_class_spec.rb, spec/rubocop/cop/style/trailing_body_on_method_definition_spec.rb, spec/rubocop/cop/style/trailing_body_on_module_spec.rb, spec/rubocop/cop/style/trailing_comma_in_arguments_spec.rb, spec/rubocop/cop/style/trailing_comma_in_array_literal_spec.rb, spec/rubocop/cop/style/trailing_comma_in_hash_literal_spec.rb, spec/rubocop/cop/style/trailing_method_end_statement_spec.rb, spec/rubocop/cop/style/trailing_underscore_variable_spec.rb, spec/rubocop/cop/style/unpack_first_spec.rb, spec/rubocop/cop/style/variable_interpolation_spec.rb, spec/rubocop/cop/style/when_then_spec.rb, spec/rubocop/cop/style/word_array_spec.rb, spec/rubocop/cop/style/yoda_condition_spec.rb, spec/rubocop/cop/style/zero_length_predicate_spec.rb
Part of #8127
Use newer `expect_offense` and `expect_correction` in specs for Style cops T-Z.
Merge `'register offense'` and `'auto-correct'` spec examples where posible.
Fix autocorrect spec for non-ascii word array in `Style/WordArray`
=> Refactor specs to use expect_offense in Style cops T-Z

CHANGELOG.md, lib/rubocop/cop/style/conditional_assignment.rb, spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb
`Style/ConditionalAssignment` cop detects most comparison operators: `<=`, `>=`, `==`, `!=`, `===`, `<=>`, `=~`, `!~`.
Add detection for `<` and `>`.
=> Recognise < > as comparison operators in cond assign

Rakefile, lib/rubocop/cli/command/show_cops.rb, lib/rubocop/comment_config.rb, lib/rubocop/config.rb, lib/rubocop/config_loader.rb, lib/rubocop/config_validator.rb, lib/rubocop/cop/lint/redundant_cop_disable_directive.rb, lib/rubocop/cop/migration/department_name.rb, lib/rubocop/cops_documentation_generator.rb, lib/rubocop/formatter/disabled_config_formatter.rb, lib/rubocop/formatter/junit_formatter.rb, lib/rubocop/options.rb, lib/rubocop/runner.rb, spec/project_spec.rb, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/comment_config_spec.rb, spec/rubocop/cop/team_spec.rb, spec/rubocop/formatter/disabled_config_formatter_spec.rb, spec/rubocop/result_cache_spec.rb
Follow https://github.com/rubocop-hq/rubocop/pull/8095
This PR uses new `RuboCop::Cop::Registry` APIs instead of deprecated APIs.
- `Cop.registry` -> `Registry.global`
- `Cop.all` -> `Registry.all`
- `Cop.qualified_cop_name` -> `Registry.qualified_cop_name`
=> Use new `RuboCop::Cop::Registry` APIs instead of deprecated APIs

lib/rubocop/rspec/shared_contexts.rb, spec/rubocop/cop/cop_spec.rb, spec/rubocop/formatter/clang_style_formatter_spec.rb, spec/rubocop/formatter/emacs_style_formatter_spec.rb, spec/rubocop/formatter/file_list_formatter_spec.rb, spec/rubocop/formatter/junit_formatter_spec.rb
Poking around in the tests, I noticed that we were parsing this source
for every test, even in cases where we never use it, which is most of
them. This removes the default `let(:source)` and stops automatically
calling `begin_investigation` on the cop. Instead it calls it in places
where it is necessary.
I benchmarked it locally, and while not a huge win, it consistently cut
about 2-3 seconds off my build times, from ~52 seconds to ~50 seconds.
=> remove `let(:source)` from `shared_contexts.rb`

lib/rubocop/comment_config.rb, lib/rubocop/cop/correctors/line_break_corrector.rb, lib/rubocop/cop/layout/class_structure.rb, lib/rubocop/cop/layout/comment_indentation.rb, lib/rubocop/cop/layout/extra_spacing.rb, lib/rubocop/cop/layout/leading_comment_space.rb, lib/rubocop/cop/lint/redundant_cop_disable_directive.rb, lib/rubocop/cop/migration/department_name.rb, lib/rubocop/cop/mixin/alignment.rb, lib/rubocop/cop/mixin/check_line_breakable.rb, lib/rubocop/cop/mixin/line_length_help.rb, lib/rubocop/cop/mixin/multiline_literal_brace_layout.rb, lib/rubocop/cop/mixin/percent_array.rb, lib/rubocop/cop/mixin/statement_modifier.rb, lib/rubocop/cop/mixin/trailing_comma.rb, lib/rubocop/cop/style/ascii_comments.rb, lib/rubocop/cop/style/block_comments.rb, lib/rubocop/cop/style/commented_keyword.rb, lib/rubocop/cop/style/empty_case_condition.rb, lib/rubocop/cop/style/empty_else.rb, lib/rubocop/cop/style/if_unless_modifier.rb, lib/rubocop/cop/style/inline_comment.rb, lib/rubocop/cop/style/safe_navigation.rb, lib/rubocop/cop/style/single_line_methods.rb, lib/rubocop/cop/util.rb, rubocop.gemspec, spec/rubocop/cop/style/empty_case_condition_spec.rb, spec/rubocop/cop/style/safe_navigation_spec.rb
This PR fixes all occurrences of `ProcessedSource#find_comment`, `each_comment`, `comments_before_line`, `commented?` and improves processing in general.
Fixes two cops with bad comment treatment: `Style/EmptyCaseCondition`, `SaveNavigation`. I didn't check other cops, is just that the processing for these was clearly erroneous.
`util.rb`'s `comment_line?` remains though, even though it is a bad API (it should probably be something like `ProcessedSource#line_is_comment?(line_nb)` instead).
This PR relies on [an unreleased version of `rubocop-ast`](https://github.com/rubocop-hq/rubocop-ast/pull/83)
=> Refactor comment access

lib/rubocop/cop/style/multiline_memoization.rb, spec/rubocop/cop/style/multiline_memoization_spec.rb
For `Style/MultilineMemoization` cop, when `EnforcedStyle` is `braces`, ensure the offense message reflects that.
With `EnforcedStyle: braces`, multiline memoization should look like:
```ruby
foo ||= (
bar
baz
)
```
so an offense for:
```ruby
foo ||= begin
bar
baz
end
```
should say:
```
Wrap multiline memoization blocks in `(` and `)`.
```
Found when updating specs in #8438
=> Alter multiline memoization message for braces enforced style

CHANGELOG.md, lib/rubocop/cop/mixin/statement_modifier.rb, spec/rubocop/cop/style/if_unless_modifier_spec.rb
=> [Fix 8497] Fix Style/IfUnlessModifier to handle if-end condition in method argument list

CHANGELOG.md, lib/rubocop/formatter/auto_gen_config_formatter.rb, lib/rubocop/formatter/progress_formatter.rb, lib/rubocop/formatter/quiet_formatter.rb, lib/rubocop/formatter/simple_text_formatter.rb, spec/rubocop/cli/cli_auto_gen_config_spec.rb, spec/rubocop/cli/cli_autocorrect_spec.rb, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/cli_spec.rb, spec/rubocop/formatter/auto_gen_config_formatter_spec.rb, spec/rubocop/formatter/quiet_formatter_spec.rb, spec/rubocop/formatter/simple_text_formatter_spec.rb
Solve https://github.com/rubocop-hq/rubocop/issues/8362
- When doing investigation only, without `-a`. It
- When running safe corrector:
=> [#8362] Display correctable offenses in summary

lib/rubocop/cop/correctors/condition_corrector.rb, lib/rubocop/cop/correctors/parentheses_corrector.rb, lib/rubocop/cop/mixin/negative_conditional.rb, lib/rubocop/cop/mixin/rescue_node.rb, lib/rubocop/cop/style/negated_if.rb, lib/rubocop/cop/style/negated_unless.rb, lib/rubocop/cop/style/negated_while.rb, lib/rubocop/cop/style/nested_modifier.rb, lib/rubocop/cop/style/nested_parenthesized_calls.rb, lib/rubocop/cop/style/nested_ternary_operator.rb, lib/rubocop/cop/style/next.rb, lib/rubocop/cop/style/nil_comparison.rb, lib/rubocop/cop/style/non_nil_check.rb, lib/rubocop/cop/style/not.rb, lib/rubocop/cop/style/numeric_literal_prefix.rb, lib/rubocop/cop/style/numeric_predicate.rb, lib/rubocop/cop/style/one_line_conditional.rb, lib/rubocop/cop/style/option_hash.rb, lib/rubocop/cop/style/optional_arguments.rb, lib/rubocop/cop/style/or_assignment.rb, lib/rubocop/cop/style/parallel_assignment.rb, lib/rubocop/cop/style/parentheses_around_condition.rb, lib/rubocop/cop/style/perl_backrefs.rb, lib/rubocop/cop/style/preferred_hash_methods.rb, lib/rubocop/cop/style/proc.rb, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cop/style/non_nil_check_spec.rb
Follow #7868.
This PR uses `Cop::Base` API for almost `Style` department's N-P cops.
It targets cop that names begin between N and P. And several N-P cops will be excluded from this PR target and addressed separately.
=> Use `Cop::Base` API for `Style` department [N-P]

CHANGELOG.md, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/shadowing_outer_local_variable.rb
Make it clear that ruby [no longer warns](https://docs.ruby-lang.org/en/2.6.0/NEWS.html#label-Language+changes) about variable shadowing:
> The “shadowing outer local variable” warning is removed. [Feature [#12490](https://bugs.ruby-lang.org/issues/12490)]
=> Lint/ShadowingOuterLocalVariable: clarify the ruby warning [doc]

lib/rubocop/cop/style/raise_args.rb, lib/rubocop/cop/style/random_with_offset.rb, lib/rubocop/cop/style/redundant_assignment.rb, lib/rubocop/cop/style/redundant_begin.rb, lib/rubocop/cop/style/redundant_condition.rb, lib/rubocop/cop/style/redundant_fetch_block.rb, lib/rubocop/cop/style/redundant_file_extension_in_require.rb, lib/rubocop/cop/style/redundant_freeze.rb, lib/rubocop/cop/style/regexp_literal.rb, lib/rubocop/cop/style/return_nil.rb, lib/rubocop/cop/style/safe_navigation.rb, lib/rubocop/cop/style/sample.rb, lib/rubocop/cop/style/self_assignment.rb, lib/rubocop/cop/style/semicolon.rb, lib/rubocop/cop/style/send.rb, lib/rubocop/cop/style/signal_exception.rb, lib/rubocop/cop/style/single_line_block_params.rb, lib/rubocop/cop/style/single_line_methods.rb, lib/rubocop/cop/style/slicing_with_range.rb, lib/rubocop/cop/style/special_global_vars.rb, lib/rubocop/cop/style/stabby_lambda_parentheses.rb, lib/rubocop/cop/style/stderr_puts.rb, lib/rubocop/cop/style/string_hash_keys.rb, lib/rubocop/cop/style/string_methods.rb, lib/rubocop/cop/style/strip.rb, lib/rubocop/cop/style/struct_inheritance.rb, lib/rubocop/cop/style/symbol_literal.rb, lib/rubocop/cop/style/symbol_proc.rb
Follow #7868.
This PR uses `Cop::Base` API for almost `Style` department's R-S cops.
It targets cop that names begin between R and S. And some R-S cops will be excluded from this PR target and addressed separately.
=> Use `Cop::Base` API for `Style` department [R-S]

lib/rubocop/cop/util.rb
This PR fixes a typo for a deprecated comment API.
The referenced API `ProcessedSource#contains_comment?` is below.
https://github.com/rubocop-hq/rubocop-ast/blob/v0.3.0/lib/rubocop/ast/processed_source.rb#L123-L127
=> Fix a typo for a deprecated comment API

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/mixin/hash_transform_method.rb, lib/rubocop/cop/style/hash_transform_keys.rb, lib/rubocop/cop/style/hash_transform_values.rb, spec/rubocop/cop/style/hash_transform_keys_spec.rb, spec/rubocop/cop/style/hash_transform_values_spec.rb
Followup to https://github.com/rubocop-hq/rubocop/pull/7663.
Since Ruby 2.6, `Hash#to_h` accepts a block which is called with each pair and must return a key and value to include in the new hash: https://rubyreferences.github.io/rubychanges/2.6.html#to_h-with-a-block
If either the key or the value are always returned unchanged, using `Hash#transform_keys` or `Hash#transform_values` is faster and clearer.
This is similar to the existing logic that detects `map { ... }.to_h`.
=> Handle to_h with block in Style/HashTransformKeys and Style/HashTransformValues

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/case_like_if.rb, spec/rubocop/cop/style/case_like_if_spec.rb
=> Fix a false positive for `Style/CaseLikeIf` when conditional contains comparison with a class

lib/rubocop/cop/style/ternary_parentheses.rb, lib/rubocop/cop/style/trailing_body_on_class.rb, lib/rubocop/cop/style/trailing_body_on_method_definition.rb, lib/rubocop/cop/style/trailing_body_on_module.rb, lib/rubocop/cop/style/trailing_comma_in_block_args.rb, lib/rubocop/cop/style/trailing_underscore_variable.rb, lib/rubocop/cop/style/trivial_accessors.rb, lib/rubocop/cop/style/unless_else.rb, lib/rubocop/cop/style/unpack_first.rb, lib/rubocop/cop/style/variable_interpolation.rb, lib/rubocop/cop/style/when_then.rb, lib/rubocop/cop/style/while_until_do.rb, lib/rubocop/cop/style/while_until_modifier.rb, lib/rubocop/cop/style/yoda_condition.rb, lib/rubocop/cop/style/zero_length_predicate.rb, spec/rubocop/cop/cop_spec.rb
Follow #7868.
This PR uses `Cop::Base` API for almost `Style` department's T-Z cops.
It targets cop that names begin between T and Z. And several T-Z cops will be excluded from this PR target and addressed separately.
=> Use `Cop::Base` API for `Style` department [T-Z]

CHANGELOG.md, lib/rubocop/cop/bundler/gem_comment.rb, spec/rubocop/cop/bundler/gem_comment_spec.rb
`Bundler/GemComment` cop isn't aware of trailing comments.
```ruby
gem 'rubocop'
gem 'rubocop' # It's a cool gem
```
This pull request fixes this problem.
The cop will allow both of the `gem 'rubocop'` with this patch.
In `gem 'rubocop' # It's a cool gem`, the comment isn't associated with the `send` node. Actually it is associated with the `str` node, which is `'rubocop'`.
So we need to check comments for descendants. 
=> Allow a trailing comment as a description comment for `Bundler/GemComment`

docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/empty_file.rb
Follow #8532.
`Lint/EmptyFile` cop does not support auto-correction. This PR removes unnecessary `extend AutoCorrector` for `Lint/EmptyFile`.
=> Remove unnecessary `extend AutoCorrector` for `Lint/EmptyFile`

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc
@bbatsov [wrote](https://github.com/rubocop-hq/rubocop/pull/7307#discussion_r463971537):
> I think the cop is actually unsafe (as it doesn't actually check the source to figure out if it's ok to add the magic comment). Unsafe for a cop means that it yields false positives or the suggestions can change the meaning of the code. Unsafe for auto-correct means the cop the cop suggestions are safe, but the auto-correct can't apply those reliably.
I would propose a different definition.  Unsafe for a cop means that it yields false positives *and that's it*. (e.g. "don't use `dig` with single argument" is unsafe, as it could be a custom method in a gem dependency and thus perfectly o.k. and without another alternative). The `Lint/FrozenStringLiteral` cop is a good example where the fact that we …
=> Mark `Lint/FrozenStringLiteralComment` as `Safe`, but with unsafe auto-correction.

lib/rubocop/rspec/cop_helper.rb, lib/rubocop/rspec/expect_offense.rb
When example code for specs has a syntax error, give further details to help
find it.
For example (from my own mistake that took some spotting of `%{access_modifier)` ending in wrong kind of bracket):
```ruby
expect_offense(<<~RUBY, access_modifier: access_modifier)
class Test
%{access_modifier)
^{access_modifier} `#{access_modifier}` should be inlined in method definitions.
end
RUBY
```
```
1) RuboCop::Cop::Style::AccessModifierDeclarations when `inline` is configured offends when protected is not inlined
Failure/Error:
raise 'Error parsing example code: ' \
"#{@processed_source.diagnostics.map(&:render).join("\n")}"
RuntimeError:
Error parsing example code: (string):2:3: fatal: unterminated string meets end of file
(string):2:   %{access_modifier)
(string):2:   ^                 
``` …
=> Add diagnostics to error message in specs code parse

spec/rubocop/cop/style/if_unless_modifier_spec.rb, spec/rubocop/cop/style/non_nil_check_spec.rb, spec/rubocop/cop/style/trailing_comma_in_arguments_spec.rb, spec/rubocop/cop/style/word_array_spec.rb
Part of #8127
Use newer `expect_offense` and `expect_correction` in remaining specs for Style cops.
=> Use new expect_offense in remaining Style cops

CHANGELOG.md, lib/rubocop/cop/style/rescue_modifier.rb, spec/rubocop/cop/style/rescue_modifier_spec.rb
=> [Fix #8507] Fix Style/RescueModifier to handle parentheses

lib/rubocop/rspec/expect_offense.rb, spec/rubocop/cop/metrics/abc_size_spec.rb, spec/rubocop/cop/metrics/block_length_spec.rb, spec/rubocop/cop/metrics/block_nesting_spec.rb, spec/rubocop/cop/metrics/class_length_spec.rb, spec/rubocop/cop/metrics/module_length_spec.rb
Replace `inspect_source` with `expect_offense` in Metric cop specs.
Return offenses from `expect_offense` to allow specifying offense end line.
Part of #8127
=> Use newer expect_offense in Metric cops

docs/modules/ROOT/pages/usage/auto_correct.adoc
Also provides example of two ways of being unsafe
Followup to #8529
=> Tweak definition of 'Safe: false'

spec/rubocop/config_loader_spec.rb
`default_configuration` needs to be cleared before `ConfigLoader` specs to clear
the general default.
It also needs to be cleared after `ConfigLoader` specs to clear the custom
configuration introduced in its isolated environment.
[Fixes #8548]
=> Reset default_configuration after config_loader specs

spec/rubocop/cop/lint/binary_operator_with_identical_operands_spec.rb, spec/rubocop/cop/lint/float_comparison_spec.rb, spec/rubocop/cop/lint/shadowed_exception_spec.rb
Part of #8127
Use newer `expect_offense` in remaining Lint cops.
Some new cops have been added following the older `inspect_source` convention. Also spotted one used in checking stderr output that was missed in my earlier PRs.
=> Use new expect_correction in remaining Lint cops

lib/rubocop/cop/layout/space_before_first_arg.rb, lib/rubocop/cop/style/redundant_self.rb
Ran on 30k files.
```
(1) 40325  (    4.2%)  RuboCop::Cop::Style::RedundantSelf#on_block
(2) 36305  (    3.8%)  RuboCop::Cop::Layout::SpaceBeforeFirstArg#on_send
29707  (    3.1%)  RuboCop::Cop::Layout::FirstArgumentIndentation#on_send
28531  (    3.0%)  RuboCop::Cop::StringHelp#on_str
26386  (    2.7%)  RuboCop::Cop::Layout::DefEndAlignment#on_send
26277  (    2.7%)  RuboCop::Cop::Layout::IndentationConsistency#on_begin
23386  (    2.4%)  RuboCop::Cop::Layout::SpaceInsideReferenceBrackets#on_send
18628  (    1.9%)  RuboCop::Cop::MultilineExpressionIndentation#on_send
15428  (    1.6%)  RuboCop::Cop::Layout::ArgumentAlignment#on_send
14030  (    1.5%)  RuboCop::Cop::Layout::LineLength#on_potential_breakable_node
12924  (    1.3%) …
```
=> Optimize `Layout/SpaceBeforeFirstArg` and `Style/RedundantSelf` cops

spec/support/alignment_examples.rb, spec/support/multiline_literal_brace_layout_examples.rb, spec/support/multiline_literal_brace_layout_method_argument_examples.rb
Part of #8127
Refactor from `inspect_source` and `autocorrect_source` to `expect_offense` and
`expect_correction` in support shared examples.
Unroll `construct()` in multiline examples to make (most) annotations clearer.
=> Use expect_offense in support shared examples

spec/rubocop/cop/internal_affairs/useless_message_assertion_spec.rb
Related to #8127
Spec case to ensure detection of specs using the new `expect_offense` syntax with `described_class::MSG`.
NOTE: Using `strip_indent` for the inner heredoc to prevent its annotation
being recognised at the outer level.
=> Add internal spec case for expect_offense with MSG

config/default.yml, docs/modules/ROOT/pages/cops_style.adoc
Autocorrect was implemented but somehow not enabled.
The cop and autocorrect are still left unsafe.
Closes #8512 
=> [Fix #8512] Enable autocorrect for `Style/NumericPredicate`

CHANGELOG.md, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/case_equality.rb, spec/rubocop/cop/style/case_equality_spec.rb
Follow https://github.com/rubocop-hq/rubocop/pull/8322#discussion_r468672970
This PR fixes an incorrect auto-correction for `Style/CaseEquality` cop when comparing with `===` against a regular expression receiver.
This PR auto-correct `===` with `match?` to keep compatibility of returning a boolean value.
=> Prevent an incorrect auto-correction for `Style/CaseEquality` cop

CHANGELOG.md, lib/rubocop/cop/mixin/empty_lines_around_body.rb, spec/support/empty_lines_around_body_shared_examples.rb
=> [Fix #8524] Fix `Layout/EmptyLinesAroundClassBody` and `Layout/EmptyLinesAroundModuleBody` to handle access modifier

CHANGELOG.md, lib/rubocop/cop/lint/constant_resolution.rb, spec/rubocop/cop/lint/constant_resolution_spec.rb
=> [Fix #8518] Fix `Lint/ConstantResolution` cop reporting offense for `module` and `class` definitions

spec/rubocop/cop/layout/empty_lines_around_module_body_spec.rb, spec/rubocop/cop/layout/line_length_spec.rb, spec/rubocop/cop/layout/space_after_comma_spec.rb, spec/rubocop/cop/layout/space_around_keyword_spec.rb, spec/rubocop/cop/layout/space_around_operators_spec.rb, spec/rubocop/cop/layout/space_before_first_arg_spec.rb, spec/rubocop/cop/layout/space_inside_array_literal_brackets_spec.rb, spec/rubocop/cop/layout/space_inside_array_percent_literal_spec.rb, spec/rubocop/cop/layout/space_inside_block_braces_spec.rb, spec/rubocop/cop/layout/space_inside_percent_literal_delimiters_spec.rb
Part of #8127
Refactored specs in spec/rubocop/cop/layout/ starting with letters (E-S) to use newer helpers expect_offense / expect_correction instead of old inspect_source / autocorrect_source
=> Refactored specs in spec/rubocop/cop/layout to use 'expect_offense'

lib/rubocop/cop/layout/space_inside_array_percent_literal.rb, lib/rubocop/cop/layout/space_inside_percent_literal_delimiters.rb, lib/rubocop/cop/lint/percent_string_array.rb, lib/rubocop/cop/style/percent_literal_delimiters.rb, lib/rubocop/cop/style/percent_q_literals.rb, lib/rubocop/cop/style/redundant_capital_w.rb, lib/rubocop/cop/style/redundant_interpolation.rb
Follow #7868.
This PR uses `Cop::Base` API for cops mixing `PercentLiteral` module.
=> Use `Cop::Base` API for `PercentLiteral`

lib/rubocop/cop/correctors/alignment_corrector.rb, lib/rubocop/cop/correctors/empty_line_corrector.rb, lib/rubocop/cop/layout/block_alignment.rb, lib/rubocop/cop/layout/class_structure.rb, lib/rubocop/cop/layout/closing_heredoc_indentation.rb, lib/rubocop/cop/layout/condition_position.rb, lib/rubocop/cop/layout/def_end_alignment.rb, lib/rubocop/cop/layout/dot_position.rb, lib/rubocop/cop/layout/empty_comment.rb, lib/rubocop/cop/layout/empty_line_after_guard_clause.rb, lib/rubocop/cop/layout/empty_line_after_magic_comment.rb, lib/rubocop/cop/layout/empty_line_between_defs.rb, lib/rubocop/cop/layout/empty_lines.rb, lib/rubocop/cop/layout/empty_lines_around_access_modifier.rb, lib/rubocop/cop/layout/empty_lines_around_arguments.rb, lib/rubocop/cop/layout/empty_lines_around_attribute_accessor.rb, lib/rubocop/cop/layout/empty_lines_around_begin_body.rb, lib/rubocop/cop/layout/empty_lines_around_block_body.rb, lib/rubocop/cop/layout/empty_lines_around_class_body.rb, lib/rubocop/cop/layout/empty_lines_around_exception_handling_keywords.rb, lib/rubocop/cop/layout/empty_lines_around_method_body.rb, lib/rubocop/cop/layout/empty_lines_around_module_body.rb, lib/rubocop/cop/layout/end_alignment.rb, lib/rubocop/cop/mixin/empty_lines_around_body.rb, lib/rubocop/cop/mixin/end_keyword_alignment.rb, spec/rubocop/cop/layout/empty_lines_around_class_body_spec.rb
Follow #7868.
This PR uses `Cop::Base` API for almost `Style` department's cops.
It targets cop that names begin between A and E. And some A-E cops will be excluded from this PR target and addressed separately.
=> Use `Cop::Base` API for `Layout` department [A-E]

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/one_line_conditional.rb, spec/rubocop/cli_spec.rb, spec/rubocop/cop/style/one_line_conditional_spec.rb
Fixes #7705.
This is continuation of work started in https://github.com/rubocop-hq/rubocop/pull/7710 by https://github.com/Lykos. I basically used the code proposed in that PR, fixed some minor things, added more specs, and also added a new config parameter called `AlwaysCorrectToMultiline` (I think this addresses the suggestion raised in https://github.com/rubocop-hq/rubocop/pull/7710#issuecomment-593073187). 
=> [Fix #7705] Fix `Style/OneLineConditional` to handle if/then/elsif/then/else and add AlwaysCorrectToMultiline config option

lib/rubocop/core_ext/string.rb
I thought that `/\A\s*\z/.match?` would be better, but it is actually much slower (up to 50x).
=> Optimize String#blank.

docs/modules/ROOT/pages/extensions.adoc
This PR adds rubocop-minitest to the extension list.
https://github.com/rubocop-hq/rubocop-minitest
=> Add rubocop-minitest to the extension list

spec/rubocop/cli_spec.rb, spec/spec_helper.rb
Follow https://github.com/rubocop-hq/rubocop/pull/8588#issuecomment-680679448
This PR skips a test due to the following JRuby 9.2.13.0 regression:
https://github.com/jruby/jruby/issues/6365
=> Workaround for JRuby 9.2.13.0 regression

CHANGELOG.md, lib/rubocop/cop/team.rb, spec/rubocop/cop/team_spec.rb
Fixes #8590.
This PR fixes the following error when auto-correcting encoding mismatch file.
```ruby
puts 'Ｔｈｉｓ ｆｉｌｅ ｅｎｃｏｄｉｎｇ ｉｓ ＵＴＦ－８．'
```
```console
% bundle exec rubocop --cache false -a
(snip)
Cannot extract source from uninitialized Source::Buffer
/Users/koic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/parser-2.7.1.4/lib/
parser/source/buffer.rb:148:in `source'
/Users/koic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/parser-2.7.1.4/lib/
parser/source/buffer.rb:297:in `source_range'
/Users/koic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/parser-2.7.1.4/lib/
parser/source/tree_rewriter.rb:116:in `initialize'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/corrector.rb:18:in
`initialize'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/ …
```
=> [Fix #8590] Fix an error when auto-correcting encoding mismatch file

CHANGELOG.md, lib/rubocop.rb, lib/rubocop/cop/lint/mixed_regexp_capture_types.rb, lib/rubocop/cop/lint/out_of_range_regexp_ref.rb, lib/rubocop/ext/regexp_node.rb, spec/rubocop/ext/regexp_node_spec.rb
We are starting to have more Cops handling `Regexp`. This PR
* simplifies the access to the regexp parsed tree with `RegexpNode#parsed_tree`
* caches to avoid reparsing the same node multiple times
* adds `RegexpNode#each_capture` which simplifies processing.
This could be helpful for #8504 too.
I'm hesitating between adding it to `rubocop-ast` or extending it as in this PR.
=> Parsed Regexp utilities

CHANGELOG.md, lib/rubocop/cop/style/redundant_regexp_escape.rb, spec/rubocop/cop/style/redundant_regexp_escape_spec.rb
We should allow line continuations (i.e. an escaped `\n`)
=> [Fix #8583] Allow line continuations in `Style/RedundantRegexpEscape`

CHANGELOG.md, lib/rubocop/cop/mixin/regexp_literal_help.rb, spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb
I agree with @marcandre's comment in #8593 that this cop (and `Style/RedundantRegexpEscape`) should use a Regexp parser rather than the hacky "blank-out interpolations" approach fixed here. However, for now, this fix seemed straightforward - I'll try and take a look at the parser suggestion over the weekend.
=> [Fix #8593] Ignore multi-line interpolations in `Style/RedundantRegexpCharacterClass`

lib/rubocop/cop/style/redundant_regexp_character_class.rb, lib/rubocop/cop/style/redundant_regexp_escape.rb
Follow #7868.
This PR uses `Cop::Base` API for cops mixing `RegexpLiteralHelp` module.
=> Use `Cop::Base` API for `RegexpLiteralHelp`

CHANGELOG.md, docs/modules/ROOT/pages/development.adoc, lib/rubocop/cop/base.rb, lib/rubocop/cop/commissioner.rb, spec/rubocop/cop/commissioner_spec.rb
Many of the recent optimizations for Cops seem to be to modify `on_send` to check early for the `node.method_name` against a specific list of names.
This PR makes this pattern builtin so it is easy to do (just define `RESTRICT_ON_SEND = %i[foo bar baz]`) *and* makes it even more efficient.
Let's imagine 100 cops defining `on_send` that could have such a restricted method list. On a run over 10k `SendNode`, if these cops are optimized with the first thing in `on_send` being `return if SOME_LIST.include?(node.method_name)`, there would still be 100*10k calls to `on_send`, and 100*10k calls to `Set#include?` (assuming that `SOME_LIST` is a `Set`, as it should). With this PR, if the Cops are optimized with the right constant, then there would be only 10k hash lookups.
cc/ @fatkodima
=> Allow cops to restrict callbacks `on_send` to specific method names only

lib/rubocop/cop/correctors/empty_line_corrector.rb, lib/rubocop/cop/correctors/multiline_literal_brace_corrector.rb, lib/rubocop/cop/layout/first_array_element_line_break.rb, lib/rubocop/cop/layout/first_hash_element_line_break.rb, lib/rubocop/cop/layout/first_method_argument_line_break.rb, lib/rubocop/cop/layout/first_method_parameter_line_break.rb, lib/rubocop/cop/layout/hash_alignment.rb, lib/rubocop/cop/layout/heredoc_argument_closing_parenthesis.rb, lib/rubocop/cop/layout/heredoc_indentation.rb, lib/rubocop/cop/layout/initial_indentation.rb, lib/rubocop/cop/layout/leading_comment_space.rb, lib/rubocop/cop/layout/leading_empty_lines.rb, lib/rubocop/cop/layout/multiline_array_brace_layout.rb, lib/rubocop/cop/layout/multiline_array_line_breaks.rb, lib/rubocop/cop/layout/multiline_assignment_layout.rb, lib/rubocop/cop/layout/multiline_block_layout.rb, lib/rubocop/cop/layout/multiline_hash_brace_layout.rb, lib/rubocop/cop/layout/multiline_hash_key_line_breaks.rb, lib/rubocop/cop/layout/multiline_method_argument_line_breaks.rb, lib/rubocop/cop/layout/multiline_method_call_brace_layout.rb, lib/rubocop/cop/layout/multiline_method_definition_brace_layout.rb, lib/rubocop/cop/mixin/first_element_line_break.rb, lib/rubocop/cop/mixin/multiline_element_line_breaks.rb, lib/rubocop/cop/mixin/multiline_literal_brace_layout.rb
Follow #7868.
This PR uses `Cop::Base` API for almost `Style` department's cops.
It targets cop that names begin between F and M. And some F-M cops will be excluded from this PR target and addressed separately.
=> Use `Cop::Base` API for `Layout` department [F-M]

lib/rubocop/cop/lint/top_level_return_with_argument.rb
Follow #7868, #8377, and #8395
This PR uses `Cop::Base` API for `Lint/TopLevelReturnWithArgument`.
=> Use `Cop::Base` API for `Lint/TopLevelReturnWithArgument`

lib/rubocop/cop/correctors/percent_literal_corrector.rb, lib/rubocop/cop/mixin/percent_array.rb, lib/rubocop/cop/style/symbol_array.rb, lib/rubocop/cop/style/word_array.rb
Follow #7868.
This PR uses `Cop::Base` API for cops mixing `PercentArray` module.
=> Use `Cop::Base` API for `PercentArray`

docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/guard_clause.rb
"Good" example would throw another exception regarding the need of an empty line after a guard clause.
=> Add empty line after guard clause on docs

lib/rubocop/cop/correctors/punctuation_corrector.rb, lib/rubocop/cop/layout/rescue_ensure_alignment.rb, lib/rubocop/cop/layout/space_after_colon.rb, lib/rubocop/cop/layout/space_after_comma.rb, lib/rubocop/cop/layout/space_after_method_name.rb, lib/rubocop/cop/layout/space_after_not.rb, lib/rubocop/cop/layout/space_after_semicolon.rb, lib/rubocop/cop/layout/space_around_equals_in_parameter_default.rb, lib/rubocop/cop/layout/space_around_keyword.rb, lib/rubocop/cop/layout/space_around_operators.rb, lib/rubocop/cop/layout/space_before_block_braces.rb, lib/rubocop/cop/layout/space_before_comma.rb, lib/rubocop/cop/layout/space_before_comment.rb, lib/rubocop/cop/layout/space_before_first_arg.rb, lib/rubocop/cop/layout/space_before_semicolon.rb, lib/rubocop/cop/layout/space_in_lambda_literal.rb, lib/rubocop/cop/layout/space_inside_array_literal_brackets.rb, lib/rubocop/cop/layout/space_inside_block_braces.rb, lib/rubocop/cop/layout/space_inside_hash_literal_braces.rb, lib/rubocop/cop/layout/space_inside_parens.rb, lib/rubocop/cop/layout/space_inside_range_literal.rb, lib/rubocop/cop/layout/space_inside_reference_brackets.rb, lib/rubocop/cop/layout/space_inside_string_interpolation.rb, lib/rubocop/cop/mixin/space_after_punctuation.rb, lib/rubocop/cop/mixin/space_before_punctuation.rb, lib/rubocop/cop/mixin/surrounding_space.rb, spec/rubocop/formatter/junit_formatter_spec.rb
Follow #7868.
This PR uses `Cop::Base` API for almost `Layout` department's cops.
It targets cop that names begin between N and S. And several N-S cops will be excluded from this PR target and addressed separately.
=> Use `Cop::Base` API for `Layout` department [N-S]

CHANGELOG.md, lib/rubocop/cop/utils/format_string.rb
This adds a workaround for https://github.com/oracle/truffleruby/issues/1484. With this change Rubocop no longer crashes when parsing files, an all the tests pass under Truffleruby 20.2.0 and head. Unfortunately, the tests are still too slow to add it to CI. 
This change also improves performance a little bit:
```
require "benchmark/ips"
Benchmark.ips do |x|
x.config(time: 5, warmup: 2)
source = "this is my source"
x.report("to_enum") { source.to_enum(:scan, /this is/).map { Regexp.last_match } }
x.report("workaround") do
match_datas = []
source.scan(/this is/) { match_datas << Regexp.last_match }
match_datas
end
x.compare!
end
```
With `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]`
```
Warming up --------------------------------------
to_enum    53.745k i/100ms …
```
=> Fix crash in Truffleruby

CHANGELOG.md, lib/rubocop/cop/style/case_like_if.rb, spec/rubocop/cop/style/case_like_if_spec.rb
If a class overrides one of `#==`, `#eql?`, or `equal?` and the overridden method has no arguments, then `CaseLikeIf#find_target_in_equality_node` would error as it assumes there is at least one argument.
Without the fix, the new spec returns an error:
```shell
➜  rubocop (master) ✔ bundle exec rspec spec/rubocop/cop/style/case_like_if_spec.rb:340
Run options: include {:focus=>true, :locations=>{"./spec/rubocop/cop/style/case_like_if_spec.rb"=>[340]}}
Randomized with seed 42434
F
Failures:
1) RuboCop::Cop::Style::CaseLikeIf does not register an offense when an object overrides `equal?` with no arity
Failure/Error: if argument.literal? || const_reference?(argument)
NoMethodError:
undefined method `literal?' for nil:NilClass
Finished in 0.03323 seconds (files took 1.35 seconds to load)
1 …
```
=> Fix `Style/CaseLikeIf` not properly handling overriden equality methods

CHANGELOG.md, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/duplicate_require.rb, spec/rubocop/cop/lint/duplicate_require_spec.rb
Fixes #8627.
This PR fixes a false positive for `Lint/DuplicateRequire` when same feature argument but different require method.
=> [Fix #8627] Fix a false positive for `Lint/DuplicateRequire`

lib/rubocop/core_ext/string.rb
Overwrite `treetop`s bad definition of `blank?` if it exists.
=> [Fixes #8636] Circumvent treetop's folly

CHANGELOG.md
`Style/KeywordParametersOrder` was introduced in #8563, not `#8562`.
/cc @fatkodima 
=> Fix changelog entry for KeywordParametersOrder

CHANGELOG.md, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/string_concatenation.rb, spec/rubocop/cop/style/string_concatenation_spec.rb
Fixes #8470.
If any of the parts in the expression are too complex, an offense will be registered but autocorrection will not take place (ideally the complex expression should be replaced with a variable or method call that could then be interpolated more simply).
The following disable autocorrection:
* multiline statements
* heredocs (which otherwise were autocorrecting into a syntax error)
* nested interpolation
* expressions with blocks (block braces inside interpolation braces)
=> [Fix #8470] Do not try to autocorrect Style/StringConcatenation if any of the parts are too complex

CHANGELOG.md, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cli/cli_autocorrect_spec.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
Fixes #8572.
This PR fixes a false positive for `Style/RedundantParentheses` when like method argument parentheses.
=> [Fix #8572] Fix a false positive for `Style/RedundantParentheses`

CHANGELOG.md, lib/rubocop/result_cache.rb
Fixes #8629.
`File.mtime` is faster, but inconsistent in CI, because in each CI build the mtime changes, which means that the rubocop cache implicitly cannot be used as-is. It's obviously slower to calculate a hash for each file, but this is still more performant (both in memory consumption and iterations per second) than the original.
I wrote a benchmark to test memory and IPS: https://gist.github.com/dvandersluis/0ddbc936fc858fbbec9cf8fb796ec9a2
```
Calculating -------------------------------------
original     1.770M memsize (   622.000  retained)
587.000  objects (     3.000  retained)
50.000  strings (     2.000  retained)
mtime    27.343k memsize (     0.000  retained)
482.000  objects (     0.000  retained)
50.000  strings (     0.000  retained)
file hash     1.586M memsize ( …
```
=> Calculate rubocop_checksum by caculating a crc32 for each file rather than using mtime

lib/rubocop/cop/generator.rb, spec/rubocop/cop/generator_spec.rb
I've been using https://github.com/rubocop-hq/rubocop-extension-generator/ to generate my own RuboCop extensions and it bugs me that it contains a broken link to `RuboCop::AST::NodePattern`.
I've filed a related issue at https://github.com/rubocop-hq/rubocop-extension-generator/issues/11, but when I got around to fix this problem, I've realized that this is an issue on RuboCop's side. 
So I've updated the link
=> Fix link to AST::NodePattern in cop generator

CHANGELOG.md, lib/rubocop/cop/layout/def_end_alignment.rb, spec/rubocop/cop/layout/def_end_alignment_spec.rb
This PR fixes a false positive for `Layout/DefEndAlignment` when using refinements and `private def`.
It prevents the following error when auto-correcting.
```console
using Module.new {
refine Hash do
class << Hash
private def _ruby2_keywords_hash(*args)
end
end
end
}
% bundle exec rubocop -a --only Layout/DefEndAlignment example.rb
(snip)
W
Offenses:
example.rb:5:7: W: [Corrected] Layout/DefEndAlignment: end at 5, 6 is
not aligned with using Module.new {
refine Hash do
class << Hash
private def at 1, 0.
end
^^^
/Users/koic/src/github.com/koic/rubocop-issues/rails/example.rb.
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/runner.rb:289:in …
```
=> Fix a false positive for `Layout/DefEndAlignment`

docs/modules/ROOT/pages/usage/auto_correct.adoc
A forgotten dash leads to wrong html output, as seen here, in the bottom of the page: https://docs.rubocop.org/rubocop/0.90/usage/auto_correct.html
=> Fix documentation markup in auto_correct.adoc

CHANGELOG.md, lib/rubocop/cop/style/class_and_module_children.rb, spec/rubocop/cop/style/class_and_module_children_spec.rb
This PR fixes the following incorrect auto-correct for `Style/ClassAndModuleChildren` when using cbase class name.
```console
class ::Foo
end
% bundle exec rubocop -A --only Style/ClassAndModuleChildren
(snip)
C
Offenses:
example.rb:1:7: C: [Corrected] Style/ClassAndModuleChildren: Use nested
module/class definitions instead of compact style.
class ::Foo
^^^^^
module
class Foo
end
end
example.rb:3: syntax error, unexpected '\n', expecting '.' or &. or :: or '['
```
=> Fix a false positive for `Style/ClassAndModuleChildren`

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/usage/caching.adoc, lib/rubocop/options.rb, lib/rubocop/result_cache.rb, lib/rubocop/runner.rb, spec/rubocop/options_spec.rb, spec/rubocop/result_cache_spec.rb
This PR introduces the `--cache-root` command line option and support for the `RUBOCOP_CACHE_ROOT` env variable to control the cache root directory.
It takes precedence over everything else (even the config file) which makes it perfectly suited for CI usage where it's very helpful to control the cache path (without interference from the config file) to consistently be able to save and restore rubocop's cache files.
=> Feature: add support for RUBOCOP_CACHE_ROOT env variable to control cache path

CHANGELOG.md, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/safe_navigation.rb, spec/rubocop/cli/cli_autocorrect_spec.rb, spec/rubocop/cop/style/safe_navigation_spec.rb
This PR fixes the following error for `Style/SafeNavigation` when checking `foo&.empty?` in a conditional.
```console
do_something if ENV['VERSION'] && ENV['VERSION'].empty?
% bunble exec rubocop -a example.rb --only Style/SafeNavigation,Lint/SafeNavigationWithEmpty
(snip)
W
Offenses:
example.rb:1:17: W: [Corrected] Lint/SafeNavigationWithEmpty: Avoid
calling empty? with the safe navigation operator in conditionals.
do_something if ENV['VERSION']&.empty?
^^^^^^^^^^^^^^^^^^^^^^
example.rb:1:17: C: [Corrected] Style/SafeNavigation: Use safe
navigation (&.) instead of checking if an object exists before calling
the method.
do_something if ENV['VERSION'] && ENV['VERSION'].empty?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0 files inspected, 2 offenses detected, …
```
=> Fix a false positive for `Style/SafeNavigation`

CHANGELOG.md, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/hash_as_last_array_item.rb, spec/rubocop/cop/style/hash_as_last_array_item_spec.rb
Fixes #8617.
`Style/HashAsLastArrayItem` currently changes arrays of hashes so that the final hash has no braces (if `EnforcedStyle: no_braces` is set). This PR changes that behaviour so that an array of all hashes is ignored.
=> [Fix #8617] Style/HashAsLastArrayItem no longer flags hashes if all elements in an array are hashes

CHANGELOG.md, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/useless_method_definition.rb, spec/rubocop/cop/lint/useless_method_definition_spec.rb
=> Fix `Lint/UselessMethodDefinition` to not register an offense when method definition includes optional arguments

CHANGELOG.md, lib/rubocop/cop/style/redundant_self_assignment.rb
Those two returns self, not modifies its receiver in place. So that was my mistake when implementing this cop.
=> Fix a false positive for `Style/RedundantSelfAssignment` when calling coercion methods

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, spec/rubocop/cop/lint/safe_navigation_chain_spec.rb
Closes https://github.com/rubocop-hq/rubocop/issues/8500
=> [Fix #8500] Add `in?` to AllowedMethods for `Lint/SafeNavigationChain` cop

CHANGELOG.md, lib/rubocop/cop/naming/binary_operator_parameter_name.rb, spec/rubocop/cop/naming/binary_operator_parameter_name_spec.rb
Fixes #8664.
This PR fixes a false positive for `Naming/BinaryOperatorParameterName` when naming multibyte characters method name.
=> [Fix #8664] Fix a false positive for `Naming/BinaryOperatorParameterName`

CHANGELOG.md, lib/rubocop/cop/bundler/duplicated_gem.rb, spec/rubocop/cop/bundler/duplicated_gem_spec.rb
Closes https://github.com/rubocop-hq/rubocop/issues/8604
=> [Fix #8604] Fix a false positive for `Bundler/DuplicatedGem` when gem is duplicated in condition

spec/rubocop/config_obsoletion_spec.rb, spec/rubocop/cop/cop_spec.rb, spec/rubocop/cop/gemspec/ordered_dependencies_spec.rb, spec/rubocop/cop/layout/argument_alignment_spec.rb, spec/rubocop/cop/layout/def_end_alignment_spec.rb, spec/rubocop/cop/layout/space_inside_array_percent_literal_spec.rb, spec/rubocop/cop/lint/redundant_cop_disable_directive_spec.rb, spec/rubocop/cop/style/multiline_memoization_spec.rb, spec/rubocop/cop/style/safe_navigation_spec.rb, spec/rubocop/cop/style/symbol_proc_spec.rb, spec/rubocop/result_cache_spec.rb
- Removes various test setup that is no longer in use discovered with [rspectre](https://github.com/dgollahon/rspectre). (Most cases are instances of leftovers from switching to the `expect_` style of tests).
- Fixes cop spec where an `options` `let` was never consumed by anything. I believe this test was meant to test the behavior when `cop_options` was empty.
=> Clean up unused spec setup

CHANGELOG.md, lib/rubocop/cop/mixin/hash_transform_method.rb, lib/rubocop/cop/style/hash_transform_keys.rb, lib/rubocop/cop/style/hash_transform_values.rb, spec/rubocop/cop/style/hash_transform_keys_spec.rb, spec/rubocop/cop/style/hash_transform_values_spec.rb
We can't know for certain when the receiver is a hash, which is why these cops are marked as unsafe. However there are some false positives that we can detect.
Array literals and `each_with_index` were already handled; here I'm adding `with_index` and `zip`.
=> [Fix #8630] Fix some hash transformation false positives

CHANGELOG.md, lib/rubocop/cop/style/explicit_block_argument.rb, spec/rubocop/cop/style/explicit_block_argument_spec.rb
Fixes #8671.
This PR fixes an error for `Style/ExplicitBlockArgument` when using safe navigation method call.
=> [Fix #8671] Fix an error for `Style/ExplicitBlockArgument`

CHANGELOG.md, lib/rubocop/cop/layout/empty_line_after_multiline_condition.rb, spec/rubocop/cop/layout/empty_line_after_multiline_condition_spec.rb
=> Fix an error for `Layout/EmptyLineAfterMultilineCondition` when conditional is at the top level

CHANGELOG.md, lib/rubocop/cop/style/hash_transform_keys.rb, lib/rubocop/cop/style/hash_transform_values.rb, spec/rubocop/cop/style/hash_transform_keys_spec.rb, spec/rubocop/cop/style/hash_transform_values_spec.rb
See also https://github.com/rubocop-hq/rubocop-rails/pull/353.
If the `each_with_object` hash is used in the transformed key or value, `Style/HashTransformKeys` or `Style/HashTransformValues` can't be used.
=> Fix a false positive for Style/HashTransformKeys and Style/HashTransformValues

CHANGELOG.md, lib/rubocop/cop/layout/space_inside_hash_literal_braces.rb, spec/rubocop/cop/layout/space_inside_hash_literal_braces_spec.rb
Fixes #8642.
I'm not 100% sure I understand what `ConfigurableEnforcedStyle` is doing (it'd be great if it could have more documentation added!), but the problem here is that the detected style was flipping between `space` and `nospace` depending on which hash was being evaluated. The fix is to just pass the defined `style` to `ambiguous_or_unexpected_style_detected` rather than trying to calculate it.
---
Consider the following code (which is also added as a test):
```ruby
{}
{key: 1}
```
1. When the first empty hash is evaluated by the cop, the memoized detected style (in `ConfigurableEnforcedStyle`) is `nil`. Because the spacing for the empty has is correct, `correct_style_detected` is called, which sets [`detected_as_strings` and …
=> [Fix #8642] Fix a false negative for `Style/SpaceInsideHashLiteralBraces` when a correct empty hash precedes the incorrect hash

.rubocop.yml, spec/rubocop/cop/layout/empty_line_between_defs_spec.rb, spec/rubocop/cop/layout/empty_lines_around_access_modifier_spec.rb, spec/rubocop/cop/layout/empty_lines_around_block_body_spec.rb, spec/rubocop/cop/layout/empty_lines_around_method_body_spec.rb, spec/rubocop/cop/layout/first_array_element_line_break_spec.rb, spec/rubocop/cop/layout/first_hash_element_line_break_spec.rb, spec/rubocop/cop/layout/multiline_block_layout_spec.rb, spec/rubocop/cop/lint/literal_in_interpolation_spec.rb, spec/rubocop/cop/lint/useless_method_definition_spec.rb, spec/rubocop/cop/style/bisected_attr_accessor_spec.rb, spec/rubocop/cop/style/class_methods_definitions_spec.rb, spec/rubocop/cop/style/line_end_concatenation_spec.rb, spec/rubocop/cop/style/method_def_parentheses_spec.rb, spec/rubocop/cop/style/mixin_grouping_spec.rb, spec/rubocop/cop/style/parentheses_around_condition_spec.rb, spec/rubocop/cop/style/redundant_assignment_spec.rb, spec/rubocop/cop/style/redundant_begin_spec.rb, spec/rubocop/cop/style/single_line_methods_spec.rb, spec/rubocop/cop/style/trailing_body_on_class_spec.rb, spec/rubocop/cop/style/trailing_body_on_method_definition_spec.rb, spec/rubocop/cop/style/trailing_body_on_module_spec.rb, spec/rubocop/cop/style/trailing_comma_in_block_args_spec.rb, spec/rubocop/cop/style/trailing_method_end_statement_spec.rb, spec/support/misc_helper.rb
The "internal-use" part of #8692 I'm confident enough to merge:
* adds a `trailing_whitespace` helper for RuboCop
* removes 10 useless trailing whitespaces in out codebase
* uses `trailing_whitespace` wherever needed
* disallows trailing whitespaces in heredocs in our codebase.
=> Whitespace internal

CHANGELOG.md, lib/rubocop/cop/mixin/configurable_naming.rb, lib/rubocop/cop/naming/file_name.rb, spec/rubocop/cop/naming/file_name_spec.rb, spec/rubocop/cop/naming/method_name_spec.rb, spec/rubocop/cop/naming/variable_name_spec.rb
Closes https://github.com/rubocop-hq/rubocop/issues/8683
=> [Fix #8683] Make naming cops work with non-ascii characters

CHANGELOG.md, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/useless_method_definition.rb, spec/rubocop/cop/lint/useless_method_definition_spec.rb
Note that not calling `super` at all from `initialize` is left to `Lint/MissingSuper` cop.
=> [Fixes #8626] Fix false negatives for `Lint/UselessMethodDefinition`.

CHANGELOG.md, lib/rubocop/result_cache.rb
Not too sure how come the CI [sometimes gets](https://app.circleci.com/pipelines/github/rubocop-hq/rubocop/2221/workflows/1bf844cb-7fa5-49cd-9f7a-d0b084e0a2f4/jobs/134769) an encoding error:
```
RuboCop::ResultCache#save when the default internal encoding is UTF-8 writes non UTF-8 encodable data to file with no exception
Failure/Error:
rubocop_extra_features
.select { |path| File.file?(path) }
.sort!
.each { |path| digest << Zlib.crc32(IO.read(path)).to_s } # mtime not reliable
Encoding::InvalidByteSequenceError:
"\xCE" on US-ASCII
```
=> Fix cache to avoid encoding exception.

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops.adoc, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop.rb, lib/rubocop/cop/lint/useless_times.rb, spec/rubocop/cop/lint/useless_times_spec.rb
This cop looks for pointless uses of `Integer#times` and replaces or removes them as necessary (I found some of these in my codebase at work, sadly). When the integer is <= 0, the block will never be yielded to, so the entire thing can be removed. When the integer is 1, the block will only ever yield once, so the `1.times` call can (generally) be replaced with the block body.
Auto-correction is enabled in most cases, but because `Integer#times` returns its receiver (and the replacement won't), I've marked it as unsafe.
The cop will remove `0.times` and `-5.times` (etc.) calls, since they will never do anything. The cop will replace `1.times` with its block, and if the block arg is used at all, replace it with 1.
Auto-correction will not be attempted in a couple more complex cases, such as …
=> Add new cop `Lint/UselessTimes`

lib/rubocop/cop/lint/identity_comparison.rb
Follow https://github.com/rubocop-hq/rubocop/pull/8699#issuecomment-691098197 and #8606.
This PR uses `RESTRICT_ON_SEND` for `Lint/IdentityComparison`.
=> Use `RESTRICT_ON_SEND` for `Lint/IdentityComparison`

CHANGELOG.md, lib/rubocop/cop/lint/ambiguous_operator.rb, spec/rubocop/cop/lint/ambiguous_operator_spec.rb
Fixes #8704.
This PR fixes an error for `Lint/AmbiguousOperator` when using safe navigation operator with a unary operator.
=> [Fix #8704] Fix an error for `Lint/AmbiguousOperator`

CHANGELOG.md, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/multiline_ternary_operator.rb, spec/rubocop/cop/style/multiline_ternary_operator_spec.rb
This PR fixes the following incorrect auto-correct for `Style/MultilineTernaryOperator` when returning a multiline ternary operator expression.
```console
return distance_in_minutes == 0 ?
locale.t(:less_than_x_minutes, count: 1) :
locale.t(:x_minutes, count: distance_in_minutes)
% bundle exec rubocop -a --only Style/MultilineTernaryOperator
(snip)
Inspecting 2 files
C.
Offenses:
example.rb:1:8: C: [Corrected] Style/MultilineTernaryOperator: Avoid
multi-line ternary operators, use if or unless instead.
return distance_in_minutes == 0 ? ...
^^^^^^^^^^^^^^^^^^^^^^^^^^
2 files inspected, 1 offense detected, 1 offense corrected
return if distance_in_minutes == 0
locale.t(:less_than_x_minutes, count: 1)
else
locale.t(:x_minutes, count: distance_in_minutes)
end …
```
=> Fix an incorrect auto-correct for `Style/MultilineTernaryOperator`

config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc
Followup to https://github.com/rubocop-hq/rubocop/pull/8707, https://github.com/rubocop-hq/ruby-style-guide/pull/841.
=> Add style guide link for Lint/ConstantDefinitionInBlock

CHANGELOG.md, lib/rubocop/cop/style/case_equality.rb, rubocop.gemspec, spec/rubocop/cop/style/case_equality_spec.rb
Follow https://github.com/rubocop-hq/rubocop/pull/8322#discussion_r468443896
Fix a false positive for `Style/CaseEquality` cop when the receiver is not a camel cased constant.
The following constant should not be replaced with `is_a?`.
What kind of object is actually assigned depends on the constant. e.g.:
```ruby
REGEXP_CONSTANT === something #=> does not register an offense.
```
This PR will only consider camel-cased constant as class name. e.g.:
```ruby
Array === something #=> auto-correct to `something.is_a?(Array)`
```
=> Fix a false positive for `Style/CaseEquality` cop

CHANGELOG.md, lib/rubocop/runner.rb, spec/rubocop/runner_spec.rb, spec/support/cops/a_to_b_cop.rb, spec/support/cops/b_to_a_cop.rb, spec/support/cops/b_to_c_cop.rb, spec/support/cops/c_to_a_cop.rb, spec/support/file_helper.rb
Closes #8621
Adds the information about which Cops exactly caused an infinite loop
Tracks the corrected offenses on each iteration. 
In the case of exceeding `MAX_ITERATIONS`, it just returns cop names from the latest iteration.
In the case of duplicated sources, it returns a list of iterations (with cop names) starting from the first time this exact source has already been generated. In most cases, I imagine there would only be 2 or 3 iterations between looped states but it should handle all cases.
Examples:
- `Test/ClassMustBeAModuleCop -> Test/ModuleMustBeAClassCop`
- `Test/ClassMustBeAModuleCop, Test/AtoB -> Test/ModuleMustBeAClassCop, Test/BtoA`
- `Test/AtoB -> Test/BtoC -> Test/CtoA`
[1]: …
=> [Fix #8621] Helpful Infinite Loop message

CHANGELOG.md, lib/rubocop/cop/lint/empty_file.rb, spec/rubocop/cop/lint/empty_file_spec.rb
=> Fix an offense creation for `Lint/EmptyFile`

CHANGELOG.md, lib/rubocop/cli/command/execute_runner.rb, spec/rubocop/cli/cli_options_spec.rb
Fixes #8673.
This PR returns only JSON result when specifying `--format=json` and `--stdin` to fix the JSON parse error.
=> [Fix #8673] Fix the JSON parse error when specifying `--format=json` and `--stdin`

docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/to_json.rb
I'm trying to understand the existing description of this cop. Does this new example improve the description?
* [N/A] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [N/A] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [N/A to this type of code comments?] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.
=> Docs: Improve example of Lint/ToJSON

CHANGELOG.md, lib/rubocop/cop/lint/identity_comparison.rb, spec/rubocop/cop/lint/identity_comparison_spec.rb
Fixes #8720.
This PR fixes an error for `IdentityComparison` when calling `object_id` method without receiver in LHS or RHS.
=> [Fix #8720] Fix an error for `Lint/IdentityComparison`

CHANGELOG.md, lib/rubocop/cop/layout/rescue_ensure_alignment.rb, spec/rubocop/cop/layout/rescue_ensure_alignment_spec.rb
Fixes #8710 and #8717.
This PR fixes a false positive for `Layout/RescueEnsureAlignment` when `Layout/BeginEndAlignment` cop is not enabled status (e.g. pending, disabled).
This patch includes workaround for pending status until RuboCop 1.0 is released.
=> [Fix #8710] Fix a false positive for `Layout/RescueEnsureAlignment`

CHANGELOG.md, lib/rubocop/cop/style/optional_boolean_parameter.rb, spec/rubocop/cop/style/optional_boolean_parameter_spec.rb
This PR stops the OptionalBooleanParameter cop from complaining about code calling Ruby's `respond_to_missing?(arg, private = false)` method in response to issue [8489](https://github.com/rubocop-hq/rubocop/issues/8489).
This is currently non-configurable, but I'm happy to modify it if that'd be useful!
=> [#8489] Exclude method respond_to_missing? from OptionalBooleanParameter cop.

CHANGELOG.md, lib/rubocop/cop/mixin/configurable_numbering.rb, spec/rubocop/cop/naming/variable_number_spec.rb
Fixes #8726.
Fix a false positive for `Naming/VariableNumber` when naming multibyte character variable name.
=> [Fix #8726] Fix a false positive for `Naming/VariableNumber`

CHANGELOG.md, lib/rubocop/cop/lint/useless_times.rb, spec/rubocop/cop/lint/useless_times_spec.rb
Fixes #8730.
This PR fixes an error for `Lint/UselessTimes` when there is a blank line in the method definition.
=> [Fix #8730] Fix an error for `Lint/UselessTimes`

CHANGELOG.md, lib/rubocop/cop/style/hash_as_last_array_item.rb, spec/rubocop/cop/style/hash_as_last_array_item_spec.rb
Arrays can be passed implicitly to setters, in which case removing the braces causes a syntax error. For example:
```ruby
config.cache_store = :redis_cache_store, { url: ENV['REDIS_URL'] } 
```
This change fixes `Style/HashAsLastArrayItem` to not mark the above as an offense or try to correct it.
Fixes #8740.
=> [Fix #8740] Fix a false positive for `Style/HashAsLastArrayItem` when the hash is in an implicit array

CHANGELOG.md, lib/rubocop/cop/lint/useless_times.rb, spec/rubocop/cop/lint/useless_times_spec.rb
This PR fixes the following error for `Lint/UselessTimes` when using empty block argument.
```console
def foo
1.times do
end
end
% rubocop --only Lint/UselessTimes -d
(snip)
Scanning /Users/koic/src/github.com/koic/rubocop-issues/bar/example.rb
An error occurred while Lint/UselessTimes cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/bar/example.rb:2:2.
undefined method `source' for nil:NilClass
/Users/koic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-0.91.0/lib/rubocop/cop/lint/useless_times.rb:76:in `autocorrect_block'
/Users/koic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-0.91.0/lib/rubocop/cop/lint/useless_times.rb:57:in `block in on_send'
/Users/koic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-0.91.0/ …
```
=> Fix an error for `Lint/UselessTimes`

CHANGELOG.md, lib/rubocop/cop/metrics/utils/abc_size_calculator.rb, spec/rubocop/cop/metrics/utils/abc_size_calculator_spec.rb
`var += ...` was counted twice
`obj.method += ...` was not counted
`Const ||= ...` was crashing [#8742]
=> [Fixes #8742] `Metrics/AbcSize`: Fix assignment counts for various cases.

CHANGELOG.md, lib/rubocop/cop/style/multiline_when_then.rb, spec/rubocop/cop/style/multiline_when_then_spec.rb
This PR fixes the following incorrect auto-correct for `Style/MultilineWhenThen` when line break for multiple condidate values of `when` statement.
```console
case condition
when :foo,
:bar then nil
end
% rubocop -a
(snip)
E
Offenses:
example.rb:3:11: E: Lint/Syntax: unexpected token kNIL
(Using Ruby 2.7 parser; configure using TargetRubyVersion parameter,
under AllCops)
:bar nil
^^^
example.rb:3:11: C: [Corrected] Style/MultilineWhenThen: Do not use then
for multiline when statement.
:bar then nil
^^^^
case condition
when :foo,
:bar nil
end
example.rb:3: syntax error, unexpected `nil', expecting `then' or ',' or
';' or '\n'
:bar nil
```
Before submitting the …
=> Fix an incorrect auto-correct for `Style/MultilineWhenThen`

CHANGELOG.md, lib/rubocop/cop/style/random_with_offset.rb, spec/rubocop/cop/style/random_with_offset_spec.rb
This cop only works correctly for ranges with literal integer bounds.
=> Ignore non-integer ranges in Style/RandomWithOffset

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc
Fixes #8749.
Not sure if there's a way to test default exclusions so I didn't try to add tests for it but I am happy to if desired.
=> [Fix #8749] Disable `Style/IpAddresses` by default in gemfiles and gemspec files

CHANGELOG.md, lib/rubocop/cop/layout/case_indentation.rb
`find_message` is overridden in `Layout::CaseIndentation` but did not actually annotate the message, so the cop name was not being shown in the output.
Fixes #8764.
=> [Fix #8764] Fix `Layout/CaseIndentation` to properly output annotated error messages

CHANGELOG.md, lib/rubocop/cop/style/redundant_return.rb, spec/rubocop/cop/style/redundant_return_spec.rb
=> Fix a false positive for `Style/RedundantReturn` when a rescue has an else clause

lib/rubocop/cop/style/commented_keyword.rb, lib/rubocop/cop/style/multiline_block_chain.rb, lib/rubocop/cop/style/redundant_conditional.rb, lib/rubocop/cop/style/redundant_percent_q.rb, lib/rubocop/cop/style/redundant_return.rb, lib/rubocop/cop/style/redundant_self.rb, lib/rubocop/cop/style/redundant_sort.rb, lib/rubocop/cop/style/redundant_sort_by.rb, lib/rubocop/cop/style/rescue_standard_error.rb
Follow #7868.
This PR uses `Cop::Base` API for some `Style` cops.
=> Use `Cop::Base` API for some `Style` cops

CHANGELOG.md, lib/rubocop/cop/style/one_line_conditional.rb, spec/rubocop/cop/style/one_line_conditional_spec.rb
Fixes #8771.
This PR fixes an error for `Style/OneLineConditional` when using `if-then-elsif-then-end`.
=> [Fix #8771] Fix an error for `Style/OneLineConditional`

CHANGELOG.md, lib/rubocop/cop/mixin/statement_modifier.rb, lib/rubocop/cop/style/if_unless_modifier.rb, spec/rubocop/cli/cli_autocorrect_spec.rb
=> [Fix #8576] Fix `Style/IfUnlessModifier` to ignore cop disable comment directives when considering conversion to modifier form

CHANGELOG.md, lib/rubocop/cop/lint/redundant_cop_disable_directive.rb, spec/rubocop/cop/lint/redundant_cop_disable_directive_spec.rb
First fix for #8372 (I split it into two PRs since it touches two cops), fixes `Lint/RedundantCopDisableDirective` autocorrection so that it doesn't clobber blank lines. There were no tests previously for autocorrection, so this change also adds tests to ensure whitespace is managed correctly.
=> [Fix #8372] Fix `Lint/RedundantCopDisableDirective` autocorrection removing a preceding newline incorrectly

lib/rubocop/version.rb, rubocop.gemspec
Currently, always links to the latest stable documentation. This PR will link to documents that match each published version.
It will be effective since the next release.
=> Specify the release version of document URL for rubygems.org

CHANGELOG.md, lib/rubocop/cop/layout/array_alignment.rb, spec/rubocop/cop/layout/array_alignment_spec.rb
`Layout/ArrayAlignment` was considering parallel assignment as an array, and then getting into a auto-correction loop trying to fix it.
Fixes #8774.
=> [Fix #8774] Fix false positive with `Layout/ArrayAlignment` for parallel assignment

CHANGELOG.md, docs/modules/ROOT/pages/compatibility.adoc, lib/rubocop/target_ruby.rb, rubocop.gemspec, spec/rubocop/cli_spec.rb
Fixes #8165 and Follows https://github.com/whitequark/parser/pull/729.
Parser 2.7.1.5 includes https://github.com/whitequark/parser/pull/717 and fixes #8165. And this PR updates Ruby 2.8 to Ruby 3.0.
=> [Fix #8165] Require Parser gem 2.7.1.5

lib/rubocop/cop/style/mixin_usage.rb, rubocop.gemspec
Also bump `rubocop/ast` requirement.
See https://github.com/rubocop-hq/rubocop/issues/8765
=> Simplify `Style/MixinUsage` and don't depend on broken `Node#macro?`

spec/rubocop/cop/layout/access_modifier_indentation_spec.rb
rubocop-hq/rubocop/120 fixes `#macro?` and the proposed PR does not consider `<something> = ...` as an acceptable wrapper, and this spec would no longer pass.
It used to pass because `macro?` considered anything inside a block as ok.
We can either consider that assignments don't change "macro scope" (and tweak the other PR), or tweak this spec as in this PR.
=> Tweak spec for Layout/AccessModifierIndentation

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/optional_boolean_parameter.rb, spec/rubocop/cop/style/optional_boolean_parameter_spec.rb
Follow up https://github.com/rubocop-hq/rubocop/pull/8725
Closes https://github.com/rubocop-hq/rubocop/issues/8489
=> Add `AllowedMethods` option to `Style/OptionalBooleanParameter` cop

lib/rubocop/rspec/expect_offense.rb, lib/rubocop/runner.rb
The message for `InfiniteCorrectionLoop` was changed in #8701, but it now crashes if `expect_corrections` in a spec causes an infinite loop:
```console
Failure/Error:
root_cause = offenses_by_iteration[loop_start..-1]
.map { |x| x.map(&:cop_name).uniq.join(', ') }
.join(' -> ')
NoMethodError:
undefined method `map' for nil:NilClass
```
This fixes that crash by capturing the offenses in `expect_offenses` and passing them into `RuboCop::Runner::InfiniteCorrectionLoop.new`.
=> Fix crash when `expect_corrections` runs into an infinite loop

CHANGELOG.md, lib/rubocop/target_finder.rb
Faster find of hidden files in `TargetFinder` class which improves rubocop initial startup speed.
Benchmarks now show a 57x improvement in one large project tested:
```
Comparison:
select:       50.6 i/s
glob:        0.9 i/s - 57.38x  (± 0.00) slower
```
=> Fix #8650 for improved hidden files finder performance

lib/rubocop.rb, rubocop.gemspec
Loading the version first also gives an opportunity for `rubocop/ast` to react.
Removing handling of rubocop-ast <1.0 in gemspec no longer needed
See also: rubocop-hq/rubocop-ast#123
=> Add callback for `rubocop/ast`

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/date_time.rb, spec/rubocop/cop/style/date_time_spec.rb
`Style/DateTime` did not have autocorrection enabled, so I added it to replace `DateTime` with `Time`. I have marked this as unsafe because we are not checking if the date being used is historic or not (unless a `start` parameter is passed in, such as in `iso8601`, in which case an offense isn't registered anyways).
I did not enable autocorrection for `to_datetime` because the message just states to not use it.
=> Enable autocorrection for `Style/DateTime`

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/array_coercion.rb
Fixes #8783, #8391, and #8334.
This PR disables `Style/ArrayCoercion` cop. Because false positive will occur if the argument of `Array()` is not an array (e.g. Hash, Set), an array will be returned as an incompatibility result.
=> [Fix #8783] Disable `Style/ArrayCoercion` cop by default

docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/comment_annotation.rb, spec/rubocop/cop/style/comment_annotation_spec.rb
The consensus in the issue is that the cop is working as expected, but the documentation does not explain well enough. This change adds an explicit test for comment blocks, as well as a documentation note.
Closes #5713.
=> [Fix #5713] Be more explicit about how Style/CommentAnnotation works

docs/modules/ROOT/pages/usage/basic_usage.adoc
Add a line to the Basic Usage page with an example of the syntax required for multiple cops on one flag.
Affects documentation only. No code or test changes.
=> Document syntax for multiple cops named in a command-flag

CHANGELOG.md, lib/rubocop/target_finder.rb
By getting a list of all directories in rood_dir, removing directories based on rubocop config Exclude strings, and then finally 
searching for all files.
Note: git displays the diff a little odd as it intermingles 2 removed and 2 added functions.
* [x Feature branch is up-to-date with `master` (if not - rebase it).
=> Fix #8646 for faster find of all files

CHANGELOG.md, docs/modules/ROOT/pages/cops_metrics.adoc, lib/rubocop/cop/metrics/block_length.rb, lib/rubocop/cop/metrics/class_length.rb, lib/rubocop/cop/mixin/hash_transform_method.rb, lib/rubocop/cop/variable_force/branch.rb, spec/rubocop/cop/metrics/block_length_spec.rb, spec/rubocop/cop/metrics/class_length_spec.rb
=> [Fix #8102] Consider class-length instead of block-length for Struct.new

CHANGELOG.md, lib/rubocop/cop/style/raise_args.rb, spec/rubocop/cop/style/raise_args_spec.rb
The use of opposite_style_detected prevents cops from detecting
subsequent offenses once the first correct style has been detected.
Related to #8809, #8802, and #8800.
=> [Fix #8759] Fix multiple offense detection for Style/RaiseArgs

CHANGELOG.md, lib/rubocop/cop/style/for.rb, spec/rubocop/cop/style/for_spec.rb
The use of `opposite_style_detected` prevents cops from detecting
subsequent offenses once the first correct style has been detected.
Related to #8802, #8800, and #8759 
=> Fix multiple offense detection for Style/For

CHANGELOG.md, lib/rubocop/cop/layout/space_around_equals_in_parameter_default.rb, spec/rubocop/cop/layout/space_around_equals_in_parameter_default_spec.rb
This cop is only being handled once per line, due to a
mis-use of the 'opposite_style_detected'/'unrecognized_style_detected'
methods.
Very similar to the issue in #8800
=> [Fix #8801] Fix Layouts/SpaceAroundEqualsInParameterDefault

CHANGELOG.md, lib/rubocop/cop/layout/space_inside_block_braces.rb, spec/rubocop/cop/layout/space_inside_block_braces_spec.rb
SpaceInsideBlockBraces was incorrectly only
detecting the first offense in a single line.
This resulted in requiring running `rubocop -a` multiple times against a file, before all of the corrections were performed.
=> [Fix #8799] Fix ability to detect/autocorrect multiple offences in a single line.

CHANGELOG.md, lib/rubocop/cop/style/method_def_parentheses.rb, spec/rubocop/cop/style/method_def_parentheses_spec.rb
Fix the ability to correctly identify and auto-correct multiple
MethodDefParentheses violations in a single file.
=> [Fix #8514] Correct multiple Style/MethodDefParentheses per file.

CHANGELOG.md, lib/rubocop/cop/style/explicit_block_argument.rb, spec/rubocop/cop/style/explicit_block_argument_spec.rb
Fixes https://github.com/rubocop-hq/rubocop/issues/8825
=> Fix crash in Style/ExplicitBlockArgument

docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/accessor_grouping.rb
See https://github.com/rubocop-hq/rubocop/pull/8241#issuecomment-702304766
=> Document interaction of `Style/AccessorGrouping` and `Sorbet` [doc]

CHANGELOG.md, lib/rubocop/cop/style/case_like_if.rb, spec/rubocop/cop/style/case_like_if_spec.rb
=> [Fix #8354] Fix Style/CaseLikeIf to handle regexp named captures

lib/rubocop/cop/metrics/class_length.rb, spec/rubocop/cop/metrics/class_length_spec.rb
Follow #8122.
This PR fixes the following error for `Metrics/ClassLength` when using or assignment (`||=`).
```console
Constant ||= Struct.new {}
% bundle exec rubocop --only Layout/ClassLength -d example.rb
(snip)
Scanning /Users/koic/src/github.com/koic/rubocop-issues/8122/example.rb
An error occurred while Metrics/ClassLength cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/8122/example.rb:1:0.
undefined method `class_definition?' for nil:NilClass
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/metrics/class_length.rb:43:in `on_casgn'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/commissioner.rb:99:in `block (2 levels) in trigger_responding_cops' …
```
=> Fix an error for `Metrics/ClassLength`

CHANGELOG.md, lib/rubocop/cop/style/string_concatenation.rb, spec/rubocop/cop/style/string_concatenation_spec.rb
`Style/StringConcatenation` autocorrect combines strings into a single string, but currently does not escape double quotes.  The autocorrect creates an invalid string.
Before:
```ruby
"He said " + "\"Arrest that man!\"."
```
Autocorrect: (quotes not escaped)
```ruby
"He said "Arrest that man!"."
#=> syntax error, unexpected tCONSTANT, expecting end-of-input
```
Before:
```ruby
"He said " + "\"Arrest that man!\"."
```
Autocorrect: (quotes escaped)
```ruby
"He said \"Arrest that man!\"."
```
=> Fix #8830 bad autocorrect of `Style/StringConcatenation` when string includes double quotes.

CHANGELOG.md, lib/rubocop/cop/style/redundant_condition.rb, spec/rubocop/cop/style/redundant_condition_spec.rb
This PR fixes the following incorrect autocorrect for `Style/RedundantCondition` when using assignment by hash key access.
The result of auto-correction is syntax error.
```console
if @columns_cache[table_name]
@columns_cache[table_name]
else
@columns_cache[table_name] = super(table_name)
end
% bundle exec rubocop -a --only Style/RedundantCondition
(snip)
C
Offenses:
example.rb:1:1: C: [Corrected] Style/RedundantCondition: Use double
pipes || instead.
if @columns_cache[table_name] ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
@columns_cache[table_name] || []=(table_name, super(table_name))
example.rb:1: syntax error, unexpected '=', expecting end-of-input …
```
=> Fix a false positive for `Style/RedundantCondition`

CHANGELOG.md, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/combinable_loops.rb, spec/rubocop/cop/style/combinable_loops_spec.rb
If the same iterable method is called multiple times with different arguments it is not a combinable loop, and thus a false positive for `Style/CombinableLoops`.
Fixes #8848.
=> [Fix #8848] Fix a false positive for `Style/CombinableLoops` when using the same method with different arguments

CHANGELOG.md, lib/rubocop/cop/lint/ambiguous_regexp_literal.rb, spec/rubocop/cop/lint/ambiguous_regexp_literal_spec.rb
Fixes #8843.
This PR fixes an incorrect autocorrect for `Lint/AmbiguousRegexpLiteral` when sending method to regexp literal receiver.
=> [Fix #8843] Fix an incorrect autocorrect for `Lint/AmbiguousRegexpLiteral`

CHANGELOG.md, lib/rubocop/cop/lint/boolean_symbol.rb, spec/rubocop/cop/lint/boolean_symbol_spec.rb
=> Fix a false positive for `Lint/BooleanSymbol` when used within `%i[...]`

CHANGELOG.md, lib/rubocop/cop/style/redundant_interpolation.rb, spec/rubocop/cop/style/redundant_interpolation_spec.rb
Fixes #8835.
This PR fixes an incorrect autocorrect for `Style/RedundantInterpolation` when using string interpolation for non-operator methods.
=> [Fix #8835] Fix an incorrect autocorrect for `Style/RedundantInterpolation`

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG.md, lib/rubocop/result_cache.rb
* When rubocop is ran in debug mode (`--debug`) and rubocop uses a cache, output the location of cache used. (This is to inform about possible differences between runs..)
* Encourage users submitting bugs to use debug mode.
=> [Fix #8842]: Add notification about cache being used to debug mode

CHANGELOG.md, lib/rubocop/cached_data.rb, spec/rubocop/result_cache_spec.rb
"Unsupported" status should be saved to cache, later to be used by total_correctable_count
This might resolve multiple reports on auto-correct for cops that don't have auto-correct on them
https://github.com/rubocop-hq/rubocop/issues/8804
https://github.com/rubocop-hq/rubocop/issues/8755
=> [Fix-8804] Save actual status to cache

CHANGELOG.md, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/ambiguous_block_association.rb
Fixes: #7495 
Add an example in the documentation for `Lint/AmbiguousBlockAssociation` to illustrate both good solutions for this cop.
=> [Fix #7495] Documentation for `Lint/AmbiguousBlockAssociation` cop is confusing

CHANGELOG.md, lib/rubocop/cop/gemspec/required_ruby_version.rb, spec/rubocop/cop/gemspec/required_ruby_version_spec.rb
Closes https://github.com/rubocop-hq/rubocop/issues/7408
In the process, also make the cop work with array of versions.
=> [Fix #7408] Make `Gemspec/RequiredRubyVersion` cop aware of `Gem::Requirement`

CHANGELOG.md, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/redundant_begin.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
This PR makes `Style/RedundantBegin` aware of `begin` without `rescue` or `ensure`.
I got the inspiration below.
https://github.com/faker-ruby/faker/pull/1988
=> Make `Style/RedundantBegin` aware of `begin` without `rescue`
