rubocop/rubocop

CHANGELOG.md, lib/rubocop/cop/layout/empty_lines_around_access_modifier.rb, lib/rubocop/cop/style/access_modifier_declarations.rb, spec/rubocop/cop/layout/empty_lines_around_access_modifier_spec.rb, spec/rubocop/cop/style/access_modifier_declarations_spec.rb
Fixes #8855.
This PR fixes an error for `Layout/EmptyLinesAroundAccessModifier` and `Style/AccessModifierDeclarations` when using only access modifier.
=> [Fix #8855] Fix an error when using only access modifier

docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/format_string_token.rb
This PR fixes an example for `Style/FormatStringToken`.
It seems that kwarg to `format` method has been forgotten.
=> Fix an example for `Style/FormatStringToken`

lib/rubocop/cop/layout/dot_position.rb, spec/rubocop/cli/cli_autocorrect_spec.rb, spec/rubocop/cop/layout/dot_position_spec.rb
Hi,
I'd like to show an issue I've been having with multi-offenses autocorrect for the `Layout/DotPosition` cop, I have a potential fix coming in a second commit.
In some cases, when having multiple offenses for this cop, it only autocorrects the first it finds and exits, which is very painful when relying on auto-correct to change from one style to another.
I'm not familiar with the `ConfigurableEnforcedStyle`, but my guess is that it is used for guessing the best style to use when auto-generating a config file.
I've found accross the code multiple use of both the pattern `return unless opposite_style_detected` and simple calls to `opposite_style_detected`:
```
$ git grep opposite_style_detected
lib/rubocop/cop/layout/access_modifier_indentation.rb:74: …
```
=> Test multi-offenses for Layout/DotPosition cop

CHANGELOG.md, lib/rubocop/cop/style/ternary_parentheses.rb, spec/rubocop/cop/style/ternary_parentheses_spec.rb
Previously, the check for `defined?` in `unsafe_autocorrect?` only applied when the argument was a single send node with no receiver, but that meant that most times `defined?` was used in a ternary wrapped in parens, it would be autocorrected incorrectly (since `defined?` would then be called on the entire ternary instead of the argument). This change makes `unsafe_autocorrect?` return true if there is any `defined?` call without parentheses.
Fixes #8782.
=> [Fix #8782] Mark any condition with defined? as an unsafe autocorrection if it is not parenthesized

docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/redundant_safe_navigation.rb
Improves explanation re: purpose of cop
* [N/A] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format).
=> Docs: RedundantSafeNavigation

CHANGELOG.md, lib/rubocop/cop/style/redundant_begin.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
=> [Fix #8864] Fix false positive for `Style/RedundantBegin` with a postfix `while` or `until`

CHANGELOG.md, lib/rubocop/cop/style/redundant_begin.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
Fixes #8869.
This PR fixes a false positive for `Style/RedundantBegin` when using `begin` for or assignment and method call.
=> [Fix #8869] Fix a false positive for `Style/RedundantBegin`

CHANGELOG.md, lib/rubocop/cop/lint/ambiguous_regexp_literal.rb, spec/rubocop/cop/lint/ambiguous_regexp_literal_spec.rb
Fixes #8862.
This PR fixes an error for `Lint/AmbiguousRegexpLiteral` when using regexp without method calls in nested structure.
=> [Fix #8862] Fix an error for `Lint/AmbiguousRegexpLiteral`

CHANGELOG.md, lib/rubocop/cop/metrics/class_length.rb, spec/rubocop/cop/metrics/class_length_spec.rb
Fixes #8872.
This PR fixes an error for `Metrics/ClassLength` when multiple assignments to constants.
=> [Fix #8872] Fix an error for `Metrics/ClassLength`

CHANGELOG.md, lib/rubocop/cop/style/redundant_begin.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
Fixes #8871.
This PR fixes a false positive for `Style/RedundantBegin` when using `begin` for method argument or part of conditions.
`begin` keyword may be redundant when using only one expression in `begin` of each issue case.
However, since it is the unintended case for #8822, I think it can be implemented as an enhancement different from this bug fix.
=> [Fix #8871] Fix a false positive for `Style/RedundantBegin`

CHANGELOG.md, lib/rubocop/cop/style/class_equality_comparison.rb, spec/rubocop/cop/style/class_equality_comparison_spec.rb
Fixes #8875.
This PR fixes an incorrect auto-correct for `Style/ClassEqualityComparison` when comparing string class name, and it tweaks the offense message.
=> [Fix #8875] Fix incorrect autocorrect for `Style/ClassEqualityComparison`

CHANGELOG.md, lib/rubocop/cop/metrics/class_length.rb, spec/rubocop/cop/metrics/class_length_spec.rb
Fixes #8880.
This PR fixes an error for `Style/ClassLength` when overlapping constant assignments.
=> [Fix #8880] Fix an error for `Style/ClassLength`

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/redundant_safe_navigation.rb, spec/rubocop/cop/lint/redundant_safe_navigation_spec.rb
Closes #8867 
Closes #8868 
I reworked this to make an offense only when used inside conditions and only for whitelisted methods.
cc @bbatsov @marcandre @natematykiewicz
=> Rework `Lint/RedundantSafeNavigation` to be more safe

CHANGELOG.md, lib/rubocop/cop/style/string_concatenation.rb, spec/rubocop/cop/style/string_concatenation_spec.rb
=> Fix an error for `Style/StringConcatenation` when correcting nested concatenable parts

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_layout.adoc, docs/modules/ROOT/pages/cops_lint.adoc, docs/modules/ROOT/pages/cops_style.adoc, spec/rubocop/cli/cli_autocorrect_spec.rb
Fixes #7966.
This PR enables all pending cops for RuboCop 1.0.
=> [Fix #7966] Enable all pending cops for RuboCop 1.0

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/format_string_token.rb, spec/rubocop/cop/style/format_string_token_spec.rb
This PR adds `MaxAllowedUnannotated` option to `Style/FormatStringToken` cop.
`MaxAllowedUnannotated` defines the number of `unannotated` style token
in a format string to be allowed when enforced style is not `unannotated`.
For example:
MaxAllowedUnannotated: 1
``` ruby
format("%s", foo) # => allowed
format("%s: %d", foo, bar) # => unallowed
```
MaxAllowedUnannotated: 2
``` ruby
format("%s", foo) # => allowed
format("%s: %d", foo, bar) # => allowed
format("%s: %d(%s)", foo, bar, baz) # => unallowed
```
The default value of MaxAllowedUnannotated is 1.
=> [Fix #7944] Add `MaxAllowedUnannotated` option to `Style/FormatStringToken` cop.

.rubocop.yml, CHANGELOG.md, lib/rubocop/cop/badge.rb, spec/rubocop/cop/badge_spec.rb, spec/rubocop/cop/generator_spec.rb, spec/rubocop/cop/registry_spec.rb
Fixes #8044.
This is a pretty deep change. As I described in the issue page (https://github.com/rubocop-hq/rubocop/issues/8044#issuecomment-667700656) I can't see a way to fix this problem without changing the way cop departments are computed. So I'm proposing this fix.
After the fix the conflicting cops `RuboCop::Cop::Rails::HttpStatus` and `RuboCop::Cop::RSpec::Rails::HttpStatus` will belong to `Rails` and `RSpec/Rails` departments, respectively. Previously they both belong to `Rails` department, thus the issue.
The biggest problem with this solution that all the dependent gems that have deep nested cops would need to update their `config/default.yml` files to reflect the changes. For example, for `rubocop-rspec` the following seven cops would need to be updated: …
=> [Fix #8044] Change cop department name calculation

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_layout.adoc, lib/rubocop/cop/layout/trailing_whitespace.rb, spec/rubocop/cop/layout/trailing_whitespace_spec.rb
I extracted #8695 to remove all trailing whitespaces in our own codebase.
This PR fixes `Layout/TrailingWhitespace` auto-correction in Heredocs to be safe. Instead of removing the trailing whitespace (which is never equivalent), it inserts `#{}` after it (which evaluates to an empty string) and thus makes the trailing whitespace no longer trailing. Maybe a more explicit form like `#{ '' }` or `#{ :trailing_whitespace!; '' }` would be better though?
Given the fact that we can now autocorrect correctly trailing whitespaces in heredoc, and that they can be a pain to deal with for Rubyists like me that set their editor to automatically trim their whitesapce, I feel that the default should be changed in general. I assume that most projects have much less occurrences of trailing whitespace in …
=> Handling trailing whitespace in Heredoc

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_security.adoc, lib/rubocop/cop/security/open.rb, spec/rubocop/cop/security/open_spec.rb
This PR makes `Security/Open` aware of `URI.open` and tweaks the doc.
`URI.open` has the same security risk as `Kernel#open`.
```console
% ruby -ve "p open('| ls').read"
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
"CHANGELOG.md\nCODE_OF_CONDUCT.md\nCONTRIBUTING.md\n...
```
```console
% ruby -ropen-uri -ve "p URI.open('| ls').read"
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
"CHANGELOG.md\nCODE_OF_CONDUCT.md\nCONTRIBUTING.md\n...
```
I got this issue feedback from @amatsuda. Thank you!
=> Make `Security/Open` aware of `URI.open`

CHANGELOG.md, lib/rubocop/cop/naming/binary_operator_parameter_name.rb, spec/rubocop/cop/naming/binary_operator_parameter_name_spec.rb
Defining the match operator `=~` triggered a false positive for
`Naming/BinaryOperatorParameterName`, which should not be triggered
for pattern/matchable relations according to the [Ruby style guide](https://rubystyle.guide/#other-arg).
The method which triggered this false positive for me was as follows:
```ruby
def =~(re)
re.match?(to_s)
end
```
=> [Fix #8901] Fix a false positive for `Naming/BinaryOperatorParameterName`

CHANGELOG.md, lib/rubocop/cop/style/safe_navigation.rb, spec/rubocop/cop/style/safe_navigation_spec.rb
Previously, every comment within the source range of the `if` being auto-corrected was captured and moved above the rewritten line. This resulted in comment duplication, as some comments belonged to internal blocks within the if. This change only considers line ranges between internal if blocks as entry points for comments that are allowed to be moved.
I had tried looking into `Parser::Source::Comment.associate_locations` as a way to determine what node each comment belonged to, but this does not associate comments in the way we're expecting for this cop.
Fixes #8781.
=> [Fix #8781] Change how comments are determined for `Style/SafeNavigation` autocorrection

lib/rubocop/cop/lint/to_json.rb, spec/rubocop/cop/lint/to_json_spec.rb
This PR removes redundant blank for `Lint/ToJSON`'s offense message.
No similar issues were found.
```console
% git grep "MSG = ' "
(END)
% git grep '\^\^  '
(END)
```
=> Remove redundant blank for `Lint/ToJSON`'s offense message

CHANGELOG.md, lib/rubocop/cop/correctors/percent_literal_corrector.rb, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/config_store_spec.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
=> Handle redundant parentheses around an interpolated expression for `Style/RedundantParentheses` cop

CHANGELOG.md, lib/rubocop/cop/layout/class_structure.rb, spec/rubocop/cop/layout/class_structure_spec.rb
This PR fixes the following incorrect auto-correct for `Layout/ClassStructure` when heredoc constant is defined after public method.
```console
class Foo
def foo
end
CONSTANT = <<~EOS.freeze
str
EOS
end
% bundle exec rubocop --only Layout/ClassStructure -a
(snip)
class Foo
CONSTANT = <<~EOS.freeze
def foo
end
str
EOS
end
```
=> Fix an incorrect auto-correct for `Layout/ClassStructure`

CHANGELOG.md, docs/modules/ROOT/pages/development.adoc, lib/rubocop/cop/base.rb, lib/rubocop/cop/commissioner.rb, spec/rubocop/cop/commissioner_spec.rb
I double-checked that this has basically no performance impact (less than ~0.1% overall) after #8785 (otherwise that would add ~4-5% overall)
=> Add `after_<type>` callbacks

CHANGELOG.md, lib/rubocop/cli/command/version.rb, lib/rubocop/config.rb, lib/rubocop/config_loader.rb, lib/rubocop/config_loader_resolver.rb, lib/rubocop/version.rb, spec/rubocop/cli/cli_options_spec.rb
This PR shows extension cop versions when using `--verbose-version` option.
Before:
```console
% rubocop -V
0.93.1 (using Parser 2.7.2.0, rubocop-ast 0.8.0, running on ruby 2.7.2 x86_64-darwin19)
```
After:
```console
% rubocop -V
0.93.1 (using Parser 2.7.2.0, rubocop-ast 0.8.0, running on ruby 2.7.2 x86_64-darwin19)
- rubocop-performance 1.8.1
- rubocop-rspec 1.43.2
```
This information is not shown in `rubocop -v` as it is needed in the bug report, first.
It shows extension cop versions named rubocop-feature (e.g. rubocop-performance, rubocop-rspec).
Extention names separated by two or more, such as rubocop-feature-foo, are not supported by this PR. First of all, this is aimed at supporting the extension cop managed by RuboCop Headquarters.
This feature searches for version constant in …
=> Show extension cop versions when using `--verbose-version` option

CHANGELOG.md, docs/modules/ROOT/pages/cops_layout.adoc, lib/rubocop/cop/layout/space_around_operators.rb, spec/rubocop/cop/layout/space_around_operators_spec.rb
This PR fixes a false positive for `Layout/SpaceAroundOperators` when upward alignment. Two false positive examples are shown.
1. `@output` and `@logger` assignments are aligned with the same margin
```ruby
@integer_message = 12345
@output  = StringIO.new
@logger  = Logger.new(@output)
```
2. `expected` and `tagging` assignments are aligned with a blank line in between
```ruby
expected = posts(:welcome)
tagging  = Tagging.all.merge!(includes: :taggable).find(taggings(:welcome_general).id)
assert_no_queries { assert_equal expected, tagging.taggable }
```
I got this issue feedback from @kamipo. Thank you!
cf: https://github.com/rails/rails/pull/36943
=> Fix a false positive for `Layout/SpaceAroundOperators`

lib/rubocop/version.rb
Follow #8908.
This PR fixes the following error when ocurring cop error.
```console
(snip)
An error occurred while Layout/ExtraSpacing cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/43/example.rb.
undefined method `config_store' for nil:NilClass
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/version.rb:35:in
`extension_versions'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/version.rb:21:in
`version'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cli/command/execute_runner.rb:62:in
`display_error_summary'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cli/command/execute_runner.rb:27:in
`execute_runner' …
```
=> Fix an error when ocurring cop error

CHANGELOG.md, lib/rubocop/cop/lint/debugger.rb, spec/rubocop/cop/lint/debugger_spec.rb
This PR is a revival of PR #7853. Please see the PR #7853 description for details.
Closes #7853
=> Remove `save_screenshot` from `Lint/Debugger` (revival)

CHANGELOG.md, lib/rubocop/cop/style/redundant_regexp_character_class.rb, spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb
Fix following incorrect behavior.
```console
/[a]+/
/[a]{2,10}/
% bundle exec rubocop --only Style/RedundantRegexpCharacterClass -a
(snip)
/a]/
/a]{2,10/
```
The cause of this bug is that Regexp::Expression::CharacterSet#te contains quantifier. Regexp::Expression::CharacterSet has quantifier attribute.
```ruby
[15] pry(RuboCop)> Regexp::Parser.parse("[a]{2,10}").expressions.first
=> #<Regexp::Expression::CharacterSet:0x00007faa945d8090
@closed=true,
@conditional_level=0,
@expressions=
[#<Regexp::Expression::Literal:0x00007faa945cfa08
@conditional_level=0,
@level=0,
@nesting_level=2,
@options={},
@quantifier=nil,
@set_level=1,
@text="a",
@token=:literal,
@ts=1,
@type=:literal>],
@level=0,
@negative=false,
@nesting_level=1,
@options={},
@quantifier= …
```
=> Fix an incorrect auto-correct for `Style/RedundantRegexpCharacterClass` due to quantifier

CHANGELOG.md, rubocop.gemspec, spec/rubocop/cop/layout/indentation_consistency_spec.rb
Fixes #8919 and follow https://github.com/rubocop-hq/rubocop-ast/pull/141.
This PR requires rubocop-ast 1.0.1 to awaken of struct constructor. And it will also add a reproduction test for #8919
=> [Fix #8919] Require RuboCop AST to 1.0.1 or higher

README.md, docs/modules/ROOT/pages/installation.adoc, tasks/cut_release.rake
This PR updates conservative Gemfile version lock for doc with RuboCop 1.0's versioning.
https://docs.rubocop.org/rubocop/1.0/versioning.html
=> Update conservative Gemfile version lock for doc

CHANGELOG.md, lib/rubocop/cop/layout/empty_lines_around_access_modifier.rb, spec/rubocop/cop/layout/empty_lines_around_access_modifier_spec.rb
Rubocop Layout/EmptyLinesAroundAccessModifier fails with `undefined method blank? for nil:NilClass` when the first line is a comment and the second line is `private`
=> Fix an error for Layout/EmptyLinesAroundAccessModifier

CONTRIBUTING.md, Rakefile, changelog/new_add_rake_tasks_for_alternative_way_to.md, spec/project_spec.rb, tasks/changelog.rake, tasks/changelog.rb, tasks/cut_release.rake
Specs also check `changelog/` entries.
Rake tasks `rake cut_release:*` and `rake release` will insure that `changelog/` is empty before proceeding.
=> Add rake tasks for alternative way to specify Changelog entries

lib/rubocop/cop/layout/def_end_alignment.rb, spec/rubocop/cop/layout/def_end_alignment_spec.rb
This already passes on RuboCop AST 1.0.1 (which is required since https://github.com/rubocop-hq/rubocop/pull/8928) via https://github.com/rubocop-hq/rubocop-ast/pull/142, but I think it's worth adding as an integration test anyway, and we can also now drop the refinement-specific check added in https://github.com/rubocop-hq/rubocop/pull/8653.
=> Add test for anonymous module with private method

CHANGELOG.md, changelog/fix_fix_autocorrection_for.md, config/default.yml, docs/modules/ROOT/pages/cops_layout.adoc, lib/rubocop/cop/layout/trailing_whitespace.rb, spec/rubocop/cop/layout/trailing_whitespace_spec.rb
Fix Changelog too, update cop "Changed" attribute
See https://github.com/rubocop-hq/rubocop/pull/8692#issuecomment-713737050
=> Fix autocorrection for `Layout/TrailingWhitespace` in heredocs.

CHANGELOG.md, changelog/fix_fix_changelog_task_to_build_a_correct.md, spec/project_spec.rb, spec/tasks/changelog_spec.rb, tasks/changelog.rb
Re #8930. I found a couple issues when using `rake changelog:fix` to write a changelog item for another PR. Foremost, `[Fix #xxxx]` as requested in the contributing guidelines was not being parsed properly (it was only looking for `Fixes`, now it accepts both). `tasks/changelog.rb` did not have a spec, so I added a basic one that just covers this issue but is not exhaustive.
I also updated the tests in `project_spec.rb`:
* Only links at the start of a changelog item are evaluated (eg. 7th item here: https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#bug-fixes-18)
* Issues on other rubocop-hq repos are accepted (eg. last item here: https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#bug-fixes-18)
* Ensures that a changelog item does not have `[Fix #xxxx]` in it.
* …
=> Fix changelog item generation

changelog/fix_fix_8708_fix_bad_regexp_recognition_in.md, lib/rubocop/cop/lint/out_of_range_regexp_ref.rb, spec/rubocop/cop/lint/out_of_range_regexp_ref_spec.rb
`Lint/OutOfRangeRegexpRef` was using the wrong regexp to determine how many capturing groups there are, in a few cases, that are now fixed. I also updated the error message to be a bit more straightforward because I found it hard to understand, but please let me know if you'd like me to reword or revert.
Also I have no idea what the plural of `regexp` should be. 😅 
Fixes #8708.
=> [Fix #8708] Fix bad regexp recognition in `Lint/OutOfRangeRegexpRef` when there are multiple regexps

lib/rubocop/cop/corrector.rb, lib/rubocop/cop/mixin/line_length_help.rb, lib/rubocop/cop/naming/predicate_name.rb, lib/rubocop/cop/style/semicolon.rb, lib/rubocop/cop/team.rb, lib/rubocop/cop/util.rb, lib/rubocop/magic_comment.rb
```
bin/rubocop-profile --memory lib/rubocop/cop
```
```
Total allocated: 1.14 GB (16969980 objects)
Total retained:  7.35 MB (54861 objects)
....
....
47.01 MB  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/cop/team.rb   (1)
23.77 MB  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/cop/util.rb   (2)
19.01 MB  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/cop/corrector.rb   (3)
13.81 MB  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/cop/naming/predicate_name.rb   (4)
11.79 MB  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/cop/mixin/line_length_help.rb   (5)
7.71 MB  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/cop/style/semicolon.rb   (6)
7.45 MB  /Users/fatkodima/Desktop/oss/rubocop/lib/rubocop/magic_comment.rb   (7)
....
```
```
Total allocated: …
```
=> Optimize memory usage

docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/flip_flop.rb
This PR updates doc for `Lint/FlipFlop` based on the change to flip-flop in Ruby 2.7.
=> Update doc for `Lint/FlipFlop`

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/layout/extra_spacing.rb, lib/rubocop/cop/style/multiple_comparison.rb, spec/rubocop/cop/style/multiple_comparison_spec.rb
This PR accepts comparisons of multiple method calls for `Style/MultipleComparison` to avoid unnecessary method calls.
```ruby
foo if a == b.lightweight || a == b.heavyweight
```
This change can reduce RuboCop's own disable comment.
=> Accept method calls for `Style/MultipleComparison`

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/multiple_comparison.rb, spec/rubocop/cop/style/multiple_comparison_spec.rb
This PR supports auto-correction for `Style/MultipleComparison`.
=> Support auto-correction for `Style/MultipleComparison`

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/multiple_comparison.rb, spec/rubocop/cop/style/multiple_comparison_spec.rb
Follow https://github.com/rubocop-hq/rubocop/pull/8939#issuecomment-717021466.
This PR adds `AllowMethodComparison` option for `Lint/MultipleComparison`.
```ruby
#
#
```
=> Add `AllowMethodComparison` option for `Lint/MultipleComparison`

lib/rubocop/rspec/expect_offense.rb, spec/rubocop/cop/layout/end_of_line_spec.rb, spec/rubocop/cop/layout/extra_spacing_spec.rb, spec/rubocop/cop/layout/indentation_width_spec.rb, spec/rubocop/cop/layout/trailing_empty_lines_spec.rb, spec/rubocop/cop/layout/trailing_whitespace_spec.rb
Part of #8127
Refactored specs in spec/rubocop/cop/layout/ to use 'expect_offense' matcher :  
- end_of_line_spec.rb, 
- extra_spacing_spec.rb, 
- indentation_width_spec.rb,
- trailing_empty_lines_spec.rb, 
- trailing_whitespace_spec.rb
=> refactor the following layout specs to use 'expect_offense':

changelog/new_add_regexpregexpexpressionloc_and.md, lib/rubocop.rb, lib/rubocop/cop/lint/duplicate_regexp_character_class_element.rb, lib/rubocop/ext/regexp_node.rb, lib/rubocop/ext/regexp_parser.rb, spec/rubocop/ext/regexp_node_spec.rb
The source information provided by `regexp_parser` is difficult to use.
This PR adds a `parser`-like location map to these nodes. E.g.:
```
[a-z]{2,}
^^^^^^^^^ expression
^^^^ quantifier
^^^^^     body
^         begin
^     end
```
Will be useful for #8948
=> Add `Regexp::Expression#loc` and `#expression`. Remove `parsed_tree_expr_loc`

lib/rubocop/cop/commissioner.rb, lib/rubocop/cop/force.rb, lib/rubocop/cop/lint/useless_access_modifier.rb, lib/rubocop/cop/offense.rb, lib/rubocop/formatter/formatter_set.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/offense_spec.rb, spec/rubocop/formatter/colorizable_spec.rb
In Ruby, there seems to be a trend to separate `send` into `public_send` and `__send__`.
https://github.com/ruby/ruby/commit/3198e7ab
~RuboCop does not override `send`, so this PR enables `Style/Send` cop to prevent use `send` method.~
~In future, `Style/Send` may be able to move to `Lint/Send`, but for now I think it's good to stay with `Style` department.~
~Also, `Style/Send` remains disabled by default because considering user applications overriding `send` method.~
This PR changes to `public_send` to suppress unnecessary scope to(private, protected) method calls. On the other hand, this PR will not make the change to `__send__` because the change to `__send__` is premature
https://bugs.ruby-lang.org/issues/17100 …
=> Use `public_send` instead of `send` when public sendable

spec/tasks/changelog_spec.rb, tasks/changelog.rb
Uses `issues` in link instead of `pull` when the commit refers to an issue.
=> Tweak default changelog entry

changelog/change_add_ignoredmethods_and_ignoredclasses_to.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/number_conversion.rb, spec/rubocop/cop/lint/number_conversion_spec.rb
Fixes #8950, to an extent. There are going to inherently be a number of false positives possible from this cop since it applies to basically any receiver of `to_i`, etc. other than `Time` and `DateTime`, which were hardcoded. Since this cop is disabled by default we probably don't have a lot of external coverage here (searching github for Lint/NumberConversion returns a lot of inline disables though!)
Instead, the classes to ignore are now configurable, and `IgnoredMethods` was added as well (so the rails duration helpers could be allowed in configuration). This of course isn't going to help when assigned to a variable, because those are checked as well:
```ruby
x = 10.minutes
x.to_i # will be registered
```
Another potential issue is that `Integer(10.minutes)` will work but …
=> [Fix #8950] Add `IgnoredMethods` and `IgnoredClasses` to `Lint/NumberConversion`

CHANGELOG.md, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/redundant_regexp_character_class.rb, spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb
This commit uses `RegexpParser::Map#body` instead of `Parser::Source::Range#adjust` in Style/RedundantRegexpCharacterClass.
When regular expression are written by %r literal, RedundantRegexpCharacterClass made incorrect loc as following.
```
%r{abc[\d]+}
^^^^^^
```
This bug are caused by calling`node.loc.begin.adjust` to get range of character class with %r regexp.
`Parser::Source::Range#adjust` adjust based on `Parser::Source::Range#begin_pos` but it with %r literal doesn't indicate start of regular expression source, point to location of '%'.
So, RedundantRegexpCharacterClass makes incorrect loc if %r literal are used in code.
```
r = %r{abc}
^      # `node.loc.begin.begin_pos`
```
```
r = %r{abs}
^   # `node.loc.begin.end_pos`
```
Ref. #8948 
Before submitting the PR …
=> [Fix #8948] Fix autocorrection for Style/RedundantRegexpCharacterClass with %r

CHANGELOG.md, lib/rubocop/cop/lint/literal_in_interpolation.rb, spec/rubocop/cop/lint/literal_in_interpolation_spec.rb
%W and %I split the content into words before expansion treating each interpolation as a word component.
For example, the following array literal evaluates to `["-H", "Cookie: a=1; b=2", "https://example.com/"]`.
```ruby
args = %W[-H #{"Cookie: a=1; b=2"} https://example.com/]
```
However, Lint/LiteralInInterpolation will wrongly auto-correct it to this:
```ruby
args = %W[-H Cookie: a=1; b=2 https://example.com/]
```
Which gives a completely different set of elements: `["-H", "Cookie:", "a=1;", "b=2", "https://example.com/"]`.
This fix teaches the cop not to expand an interpolation when the expanded value contains a space character.
=> Prevent Lint/LiteralInInterpolation from removing necessary interpolation

CHANGELOG.md, docs/modules/ROOT/pages/cops_layout.adoc, lib/rubocop/cop/layout/else_alignment.rb, spec/rubocop/cop/layout/else_alignment_spec.rb
Fix the problem of broken indent of else iniside block with rescue:
```ruby
var = array.map do |i|
code
rescue
code
else
code
end
var = array.map do |i|
code
rescue
code
else
code
end
```
=> Fix Layout/ElseAlignment for rescue/else/ensure inside do/end blocks with assignment.

CHANGELOG.md, lib/rubocop/cop/lint/empty_block.rb, spec/rubocop/cli_spec.rb
Fixes #8971.
This PR fixes the following false alarm for `# rubocop:disable Lint/EmptyBlock` inline comment with `Lint/RedundantCopDisableDirective`.
```ruby
assert_equal nil, combinator {}.call # rubocop:disable Lint/EmptyBlock
% bundle exec rubocop example.rb
W
Offenses:
example.rb:3:38: W: Lint/RedundantCopDisableDirective: Unnecessary
disabling of Lint/EmptyBlock.
assert_equal nil, combinator {}.call # rubocop:disable Lint/EmptyBlock
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1 file inspected, 1 offense detected, 1 offense auto-correctabl
```
`Lint/EmptyBlock` is `AllowComments: true` by default. `Lint/RedundantCopDisableDirective` was occurring because
`# rubocop:disable Lint/EmptyBlock` inline comment was treated as an allowed comment by `Lint/EmptyBlock`. …
=> [Fix #8971] Fix a false alarm for `# rubocop:disable Lint/EmptyBlock`

CHANGELOG.md, lib/rubocop/cop/style/keyword_parameters_order.rb, spec/rubocop/cop/style/keyword_parameters_order_spec.rb
Fixes #8976.
This PR fixes the following incorrect auto-correct for `Style/KeywordParametersOrder` when `kwoptarg` is before `kwarg` and argument parentheses omitted.
```console
def do_something foo: :default_value, bar:
lvar = 42
end
% bundle exec rubocop --only Style/KeywordParametersOrder -a
C
Offenses:
example.rb:1:18: C: [Corrected] Style/KeywordParametersOrder: Place
optional keyword parameters at the end of the parameters list.
def do_something foo: :default_value, bar:
def do_something bar:, foo: :default_value  lvar = 42
end
example.rb:1: syntax error, unexpected local variable or method,
expecting ';' or '\n'
...bar:, foo: …
```
=> [Fix #8976] Fix an incorrect auto-correct for `Style/KeywordParametersOrder`

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_naming.adoc, lib/rubocop/cop/naming/heredoc_delimiter_case.rb, spec/rubocop/cop/naming/heredoc_delimiter_case_spec.rb
This PR supports auto-correction for `Naming/HeredocDelimiterCase`.
=> Support auto-correction for `Naming/HeredocDelimiterCase`

changelog/new_support_autocorrect_for_binary_operator_parameter_name.md, config/default.yml, docs/modules/ROOT/pages/cops_naming.adoc, lib/rubocop/cop/naming/binary_operator_parameter_name.rb, spec/rubocop/cop/naming/binary_operator_parameter_name_spec.rb
This PR supports auto-correction for `Naming/BinaryOperatorParameterName`.
=> Support auto-correction for `Naming/BinaryOperatorParameterName`

changelog/new_support_autocorrect_for_style_double_negation.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/double_negation.rb, spec/rubocop/cop/style/double_negation_spec.rb
This PR supports auto-correction for `Style/DoubleNegation`.
=> Support auto-correction for `Style/DoubleNegation`

changelog/fix_spaces_in_blank_parens.md, docs/modules/ROOT/pages/cops_layout.adoc, lib/rubocop/cop/layout/space_inside_parens.rb, spec/rubocop/cop/layout/space_inside_parens_spec.rb
According to the docs, empty parens should always have no spaces. However, when `spaces` was set as the `style` for `SpaceInsideParens`, the Cop would register an offence if there was not a space inside the empty parens.
Empty parens should not have spaces.
This commit fixes `SpaceInsideParens` Cop when the `style` is `spaces` so that it doesn't require a space inside the parens. Moreover, it registers an offence when there _is_ a space inside empty parens.
Additionally, a test was added for the default `style` to ensure there are no spaces inside empty parens.
And finally, the docs were updated to show that spaces are not permitted with _either_ `style`.
Note, had to extract out `process_with_space_style` to avoid method length Cop offence.
Fixes …
=> [Fix #8966] Fix spaces in empty parens.

changelog/new_display_time_command_line_option.md, exe/rubocop, lib/rubocop/options.rb, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/options_spec.rb
This shows the elapsed time of the Rubocop command without needing to show all of the output of `--debug`.
```bash
$ rubocop
...
865 files inspected, 218 offenses detected, 148 offenses auto-correctable
$
```
```bash
$ rubocop --display-time
...
865 files inspected, 218 offenses detected, 148 offenses auto-correctable
Finished in 16.146678999997675 seconds
$
```
Fixes #8925.
- I tried testing this through the CLI specs but because it occurs outside of the CLI - essentially wrapping the CLI command itself - it wasn't working. Any thoughts or tips on testing this?
=> [Fix #8925] Add `--display-time` option for outputting time.

docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/nested_percent_literal.rb
This PR adds good examples for `Lint/NestedPercentLiteral` because complement examples that has only bad example.
=> Add good examples for `Lint/NestedPercentLiteral`

changelog/new_support_autocorrect_for_lint_useless_setter_call.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/loop.rb, lib/rubocop/cop/lint/useless_setter_call.rb, lib/rubocop/cop/style/bisected_attr_accessor.rb, lib/rubocop/cop/style/case_like_if.rb, lib/rubocop/cop/style/mixin_grouping.rb, lib/rubocop/cop/util.rb, spec/rubocop/cop/lint/useless_setter_call_spec.rb
This PR supports auto-correction for `Lint/UselessSetterCall`.
=> Support autocorrect for lint useless setter call

changelog/change_variable_number.md, config/default.yml, docs/modules/ROOT/pages/cops_naming.adoc, lib/rubocop/cop/mixin/configurable_formatting.rb, lib/rubocop/cop/mixin/configurable_numbering.rb, lib/rubocop/cop/naming/method_name.rb, lib/rubocop/cop/naming/variable_name.rb, lib/rubocop/cop/naming/variable_number.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/naming/variable_number_spec.rb
This PR renames and extends an existing cop to also handle symbols and method names, as in the style guide https://rubystyle.guide/#snake-case-symbols-methods-vars-with-numbers
=> Renamed `Naming/VariableNumber` cop to `Naming/IdentifierNumber`. Extended this cop to handle symbols and method names

CHANGELOG.md, lib/rubocop/cop/style/redundant_regexp_escape.rb, lib/rubocop/ext/regexp_node.rb, lib/rubocop/ext/regexp_parser.rb, spec/rubocop/cop/style/redundant_regexp_escape_spec.rb
Auto-correction by Style/RedundantRegexpEscape can corrupt a program by removing a character at the wrong index when it deals with a regexp pattern containing multibyte characters.
```console
% cat a.rb
x = s[/[一二\.]+/]
p x
% be rubocop -a a.rb
F
Offenses:
a.rb:1:7: F: Lint/Syntax: unterminated string meets end of file
(Using Ruby 2.4 parser; configure using TargetRubyVersion parameter, under AllCops)
x = s[/[一二\.]+]
^
a.rb:1:15: C: [Corrected] Style/RedundantRegexpEscape: Redundant escape inside regexp literal
x = s[/[一二\.]+/]
^^
% cat a.rb
x = s[/[一二\.]+]
p x
```
Note that the closing slash is removed instead of the redundant backslash.
The problem is that the cop mixes byte index with character index and …
=> Fix multibyte support in the regexp node handler

CHANGELOG.md, lib/rubocop/cop/layout/space_around_block_parameters.rb, spec/rubocop/cop/layout/space_around_block_parameters_spec.rb
There was a bug in how Layout/SpaceAroundBlockParameters autocorrected block parameters with a trailing comma with both leading and trailing whitespace.
=> Fix Layout/SpaceAroundBlockParameters bug related to trailing commas

CHANGELOG.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/raise_args.rb, spec/rubocop/cop/style/raise_args_spec.rb
```yaml
Style/RaiseArgs
AllowedCompactTypes: [] # default
```
Add custom exception names that should be ignored when
Style/RaiseArgs investigates code with `EnforcedStyle: exploded`.
This is useful for certain exception types where we really do want an
instance of an exception to be raised. e.g. in Rails:
```ruby
raise ActiveRecord::RecordInvalid.new(my_model)
```
Or to raise a custom error type that wraps an object.
To allow the above to pass even while `EnforcedStyle: exploded` is set
while still not allowing other Exception types:
```yaml
Style/RaiseArgs
AllowedCompactTypes:
- 'ActiveRecord::RecordInvalid'
- 'MyCustomWrappedError'
```
---
=> Add AllowedCompactTypes option for Style/RaiseArgs

changelog/new_support_autocorrect_for_lint_else_layout.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/else_layout.rb, spec/rubocop/cop/lint/else_layout_spec.rb
This PR supports auto-correction for `Lint/ElseLayout`.
=> Support auto-correction for `Lint/ElseLayout`

CHANGELOG.md, relnotes/v1.1.0.md
Some changelog entries are lost at ea2de20a4e8775edf5b75ad67fd9acebb4d0f339.
=> Restore lost entries in the CHANGELOG

changelog/fix_an_error_for_negated_if_else_condition.md, lib/rubocop/cop/style/negated_if_else_condition.rb, spec/rubocop/cop/style/negated_if_else_condition_spec.rb
Fixes #8998.
This PR fixes an error for `Style/NegatedIfElseCondition` when using negated condition and `if` branch body is empty.
=> [Fix #8998] Fix an error for `Style/NegatedIfElseCondition`

changelog/fix_false_positive_for_multiple_comparison.md, lib/rubocop/cop/style/multiple_comparison.rb, spec/rubocop/cop/style/multiple_comparison_spec.rb
Fixes #8996.
This PR fixes a false positive for `Style/MultipleComparison` when comparing two sides of the disjunction is unrelated.
=> [Fix #8996] Fix a false positive for `Style/MultipleComparison`

CHANGELOG.md, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/mixin/statement_modifier.rb, lib/rubocop/cop/style/if_unless_modifier.rb, lib/rubocop/cop/style/while_until_modifier.rb, spec/support/condition_modifier_cop.rb
=> [Fix #8499] Fix Style/IfUnlessModifier to prevent offense when first-line comment and code after end block

lib/rubocop/cop/lint/redundant_cop_enable_directive.rb, spec/rubocop/cop/lint/redundant_cop_enable_directive_spec.rb
If the redundant cop enable directive contains a list of cops, and that list is comma separated without a white-space after the commas, the autocorrection returned a wrong output.
Before
```ruby
```
This commit fixes that behaviour and adds a corresponding test.
After
```ruby
```
---
Hello RuboCop Team 👋 
This is the simplest way I could come up with to fix that issue (#8118) without breaking other tests. I'm open to suggestions and/or changes.
=> [Fix #8118] fix autocorrect for redundant cop enable directive

Gemfile, changelog/change_remove_obsolete_gem_safeyaml.md, lib/rubocop/config_loader.rb, spec/rubocop/config_loader_spec.rb
AFAIK, there is no longer any reason to use `SafeYAML`.
This is what was causing issues on `ruby-head`, the gem is incompatible with keyword parameters.
=> Remove obsolete gem `SafeYAML` compatibility

.rubocop.yml, spec/rubocop/cop/generator_spec.rb
Fix a few minor issues that were overlooked in #9002. 
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.
=> Fix RuboCop RSpec todos

changelog/fix_literal_in_interpolation_infinite_loop.md, lib/rubocop/cop/lint/literal_in_interpolation.rb, spec/rubocop/cop/lint/literal_in_interpolation_spec.rb
=> Fix an infinite loop when autocorrecting `Layout/TrailingWhitespace` + `Lint/LiteralInInterpolation`

CHANGELOG.md, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop/target_ruby.rb, spec/rubocop/target_ruby_spec.rb
Closes #8761
- Added `GemspecFile` class to search upwards for `<project_base>.gemspec` and read from `required_ruby_version` if present in the file
- Placed it in the `Sources` array right before `Default`
- Created specs over new class
- Update docs to clarify which files are looked at for ruby version
- Updated changelog
=> [Fix #8761] Read `required_ruby_version` from gemspec file if it exists 

changelog/fix_mark_styleinfiniteloop_as_unsafe.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/infinite_loop.rb
I noticed this while backporting `Ractor`. In particular `Ractor::ClosedError` and `CloseQueueError` are `StopIteration`
=> Mark `Style/InfiniteLoop` as unsafe

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md, tasks/cut_release.rake
This PR updates RuboCop version of CONTRIBUTING.md when releasing and tweaks example of `rubocop -V`.
This PR related to #6342.
=> Update RuboCop version of CONTRIBUTING.md when releasing

spec/rubocop/cop/layout/space_inside_array_literal_brackets_spec.rb
These specs were added in #6585 which very honestly says:
> Adds tests and docs for multiline arrays in the `compact` style.
>
> My goal here is just to document current behavior, or, if this is not the desired behavior, to draw maintainer attention to the problem.
I believe that the specs should document the _desired_ behavior. If that means marking some of our existing specs as `pending`, well, so be it.
* [-] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry …
=> Failing spec for Layout/SpaceInsideArrayLiteralBrackets

changelog/change_allow_allowedidentifiers_to_be_specified.md, config/default.yml, docs/modules/ROOT/pages/cops_naming.adoc, lib/rubocop/cop/naming/variable_number.rb, spec/rubocop/cop/naming/variable_number_spec.rb
`AllowedMethods` would have been a good mixin here, but I didn't think that `AllowedMethods` itself made sense as a configuration option (since we are checking for symbols, it's not necessarily methods, so I landed on `AllowedIdentifiers` instead). It'd be good to have a generic version of `AllowedMethods`, but I'll come back to that later.
Fixes #9012.
=> [Fix #9012] Allow `AllowedIdentifiers` to be specified for `Naming/VariableNumber`

changelog/new_support_autocorrect_for_style_if_inside_else.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/if_inside_else.rb, spec/rubocop/cop/style/if_inside_else_spec.rb
This PR supports auto-correction for `Style/IfInsideElse`.
Existing `elsif` and (not inside) `else` indentation is expected to be auto-corrected by `Layout/IndentationWidth`.
=> Support auto-correction for `Style/IfInsideElse`

changelog/change_add_note_to_keywords_of_comment_annotation.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/commissioner.rb, lib/rubocop/cop/generator.rb, spec/rubocop/cli/cli_options_spec.rb
This PR adds `# NOTE: ` annotation that is occasionally used to keywords of `Style/CommentAnnotation`.
=> Add `NOTE` to keywords of `Style/CommentAnnotation`

changelog/change_mark_unsafe_for_collection_compact.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/collection_compact.rb
Fixes #9023.
This PR marks unsafe for `Style/CollectionCompact` by default because false positives may occur in the nil check of block arguments to the receiver object.
For example, `[[1, 2], [3, nil]].reject { |first, second| second.nil? }` and `[[1, 2], [3, nil]].compact` are not compatible. This will work fine when the receiver is a hash object.
=> [Fix #9023] Mark unsafe for `Style/CollectionCompact`.

changelog/change_update_lintemptyblock_to_allow_for_empty.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/empty_block.rb, spec/rubocop/cop/lint/empty_block_spec.rb
Update `Lint/EmptyBlock` to allow for empty lambdas. Fixes #9015.
=> [Fix #9015] Update `Lint/EmptyBlock` to allow for empty lambdas.

changelog/new_add_allow_methods_to_constant_definition_in_block.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/constant_definition_in_block.rb, spec/rubocop/cop/lint/constant_definition_in_block_spec.rb
Fixes #9025.
This PR adds `AllowedMethods` option to `Lint/ConstantDefinitionInBlock`.
The following example can be allowed by configuring `AllowedMethods`.
```ruby
class TestEnum < T::Enum
enums do
Foo = new("foo")
end
end
```
Example configuration:
```yaml
Lint/ConstantDefinitionInBlock:
AllowedMethods:
- enums
```
=> [Fix #9025] Add `AllowedMethods` to `Lint/ConstantDefinitionInBlock`

changelog/change_mark_autocorrection_for_lintloop_as.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/loop.rb
The case in #9011 
```ruby
loop do
key = generate_key
break if some_check?
end
puts key
```
cannot be detected by static analysis, so instead I've marked autocorrection for `Lint/Loop` as unsafe and added an explanation.
=> [Fix #9011] Mark autocorrection for `Lint/Loop` as unsafe

changelog/change_update.md, config/default.yml, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/document_dynamic_eval_definition.rb, spec/rubocop/cop/style/document_dynamic_eval_definition_spec.rb
Look for comment blocks either inside the heredoc or inside the method call that document the dynamic code. If inline comments are not found, the cop checks for any comment blocks and tries to match it to the source code that will be evaluated, by constructing a regex with wildcards for each interpolation. None of this processing will take place unless necessary (ie. an interpolated heredoc with comment blocks and no matching inline comments).
Fixes #9026.
=> [Fix #9026] Update `Style/DocumentDynamicEvalDefinition` to detect comment blocks that document the evaluation

changelog/change_update_layoutlinelength_autocorrection.md, config/default.yml, docs/modules/ROOT/pages/cops_layout.adoc, lib/rubocop/cop/layout/line_length.rb, lib/rubocop/cop/mixin/check_line_breakable.rb, spec/rubocop/cli/cli_auto_gen_config_spec.rb, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/cli_spec.rb, spec/rubocop/cop/layout/line_length_spec.rb
Added the ability to autocorrect a long argument list when it's not a hash.
I think part of the confusion in #8978 is that `Layout/LineLength` marks every offense as correctable even though only a subset are. I'm not 100% sure if inheriting from `Base` instead of `Cop` would help here, but because `autocorrect` is defined on the cop, it's considered to be always autocorrectable. In order to try to get around this, I added a second commit which overrides `correctable?` so that only offense the cop can actually correct are marked. I'm happy to remove this if it's too much of a hack or not desirable!
=> [Fix #8978] Update `Layout/LineLength` autocorrection to be able to handle method calls with long argument lists

changelog/change_allow_enums_by_default_for_constant_definition_in_block.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/constant_definition_in_block.rb
Follow https://github.com/rubocop-hq/rubocop/issues/9025#issuecomment-726203458.
This PR allow `enums` method by default for `Lint/ConstantDefinitionInBlock`.
#9027 was worried about false negatives for users who have defined constants in user custom `enums` method's block. But it would be worthwhile to be able to resolve this realistic issue for Sorbet by default rather than not knowing if it would happen or not. And there is not much imagination that the false negatives will occur.
=> Allow `enums` by default for `Lint/ConstantDefinitionInBlock`

changelog/fix_an_error_for_document_dynamic_eval_definition.md, docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/document_dynamic_eval_definition.rb, spec/rubocop/cop/style/document_dynamic_eval_definition_spec.rb
Fixes #9032.
This PR fixes an error for `Style/DocumentDynamicEvalDefinition` when using eval-type method with interpolated string that is not heredoc without comment doc.
It may be better to provide an option to accept non-heredoc interpolated-string in future.
=> [Fix #9032] Fix an error for `Style/DocumentDynamicEvalDefinition`

spec/rubocop/cop/naming/variable_number_spec.rb
Follow https://github.com/rubocop-hq/rubocop/pull/8727#discussion_r489470828
This PR corrects two test cases for `Naming/VariableNumber`.
Thanks @dvandersluis!
=> Correct test cases for `Naming/VariableNumber`

config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc
Follow https://github.com/rubocop-hq/rubocop/pull/9033#issuecomment-726588888
`VersionChanged` has been updated to 1.4 by #9036, but if the next release is 1.3.1 it will be 1.3 correctly.
So I think #9036 change can be included in the 1.3.1 bugfix release :-)
=> Update `VersionChanged` of `Lint/ConstantDefinitionInBlock`

changelog/fix_a_false_positive_for_naming_variable_number.md, lib/rubocop/cop/mixin/configurable_numbering.rb, spec/rubocop/cop/naming/variable_number_spec.rb
Fixes #9041.
This PR fixes a false positive for `Naming/VariableNumber` when using integer symbols.
=> [Fix #9041] Fix a false positive for `Naming/VariableNumber`

CHANGELOG.md, lib/rubocop/target_ruby.rb, spec/rubocop/target_ruby_spec.rb
This fixes an issue when the `required_ruby_version` uses `Gem::Requirement` to define the Ruby version.
Gemspec:
```
...
s.required_ruby_version = Gem::Requirement.new('< 3.0.0')
...
```
Backtrace using v1.3.0:
```
undefined method `match' for nil:NilClass
296/home/travis/build/grupopv/jekyll-tasks/vendor/bundle/ruby/2.5.0/gems/rubocop-1.3.0/lib/rubocop/target_ruby.rb:165:in `version_from_str'
297/home/travis/build/grupopv/jekyll-tasks/vendor/bundle/ruby/2.5.0/gems/rubocop-1.3.0/lib/rubocop/target_ruby.rb:144:in `find_version'
298/home/travis/build/grupopv/jekyll-tasks/vendor/bundle/ruby/2.5.0/gems/rubocop-1.3.0/lib/rubocop/target_ruby.rb:22:in `initialize'
```
Related to https://github.com/rubocop-hq/rubocop/issues/8761 …
=> Fix `required_ruby_version` issue when using `Gem::Requirement`

CHANGELOG.md, lib/rubocop/target_finder.rb, spec/rubocop/target_finder_spec.rb
RuboCop exits with `SystemStackError` because "stack level too deep" if the target directory has the "**" directory.
```
foo
└── **
└── bar.rb
```
```
Traceback (most recent call last):
9197: from exe/rubocop:12:in `<main>'
9196: from /Users/unasuke/.rbenv/versions/2.7.1/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
9195: from exe/rubocop:13:in `block in <main>'
9194: from /Users/unasuke/src/github.com/rubocop-hq/rubocop/lib/rubocop/cli.rb:41:in `run'
9193: from /Users/unasuke/src/github.com/rubocop-hq/rubocop/lib/rubocop/cli.rb:72:in `execute_runners'
9192: from /Users/unasuke/src/github.com/rubocop-hq/rubocop/lib/rubocop/cli.rb:65:in `run_command'
9191: from /Users/unasuke/src/github.com/rubocop-hq/rubocop/lib/rubocop/cli/environment.rb:18:in `run'
9190: from …
```
=> Fix stack level too deep error if target directory contains `**`

.circleci/config.yml, Rakefile, changelog/change_have_cut_release_handle_configdefault.md, docs/modules/ROOT/pages/development.adoc, lib/rubocop/cop/generator.rb, lib/rubocop/cop/generator/configuration_injector.rb, spec/rubocop/cop/generator_spec.rb, tasks/cops_documentation.rake, tasks/cut_release.rake
* task `cut_release` will replace the string "<<next_version>>" in the default.yml file with the version being cut (matching is permissive: quoted or unquoted, with "-" or "_", etc.)
* task `generate_cops_documentation` now does nothing and only prints out that doc generation is now automatic
* processing code moved to new task `update_cops_documentation` (no public description) that is triggered by `cut_release`
* new cop generator uses this by default instead of the next minor version
Did I forget anything?
=> Have `cut_release` handle "config/default" and generate cops doc.

changelog/fix_false_negative_for_negated_if_else_condition.md, lib/rubocop/cop/style/negated_if_else_condition.rb, spec/rubocop/cop/style/negated_if_else_condition_spec.rb
Fixes #9050.
This PR fixes a false positive for `Style/NegatedIfElseCondition` when `if` with `!!` condition'.
=> [Fix #9050] Fix a false positive for `Style/NegatedIfElseCondition`

config/default.yml, docs/modules/ROOT/pages/cops_layout.adoc, docs/modules/ROOT/pages/cops_lint.adoc, docs/modules/ROOT/pages/cops_style.adoc, spec/project_spec.rb
This PR removes redundant patch version of `VersionChanged` from default.yml.
Related PR ... https://github.com/rubocop-hq/rubocop/pull/7802
=> Remove redundant patch version from default.yml

CHANGELOG.md, lib/rubocop/cop/layout/class_structure.rb, spec/rubocop/cop/layout/class_structure_spec.rb
=> [Fix #6962] Limit `Layout/ClassStructure` constant order offense to literal constants

CHANGELOG.md, lib/rubocop/cop/style/documentation.rb, spec/fixtures/html_formatter/expected.html, spec/rubocop/cop/style/documentation_spec.rb
Closes https://github.com/rubocop-hq/rubocop/issues/8788
=> [Fix #8788] Change `Style/Documentation` to not trigger offense with only macros

Gemfile, lib/rubocop/cop/internal_affairs/useless_message_assertion.rb, lib/rubocop/cop/layout/empty_line_between_defs.rb, lib/rubocop/cop/mixin/visibility_help.rb, lib/rubocop/cop/style/documentation.rb, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, lib/rubocop/cop/util.rb, lib/rubocop/cop/variable_force/branch.rb, lib/rubocop/cop/variable_force/scope.rb, lib/rubocop/rake_task.rb, lib/rubocop/runner.rb
This PR bumps RuboCop Performance to 1.9 and suppresses the new `Performance/BlockGivenWithExplicitBlock` and `Performance/MethodObjectAsBlock` cop's offenses.
```console
(snip)
lib/rubocop/rake_task.rb:69:69: C:
Performance/BlockGivenWithExplicitBlock: Check block argument explicitly
instead of using block_given?.
yield(*[self, task_args].slice(0, task_block.arity)) if
block_given?
^^^^^^^^^^^^
lib/rubocop/runner.rb:67:35: C: Performance/MethodObjectAsBlock: Use
block explicitly instead of block-passing a method object.
Parallel.each(target_files, &method(:file_offenses))
^^^^^^^^^^^^^^^^^^^^^^^
1200 files inspected, 12 offenses detected, 5 offenses auto-correctable
```
[1]: …
=> Bump RuboCop Performance to 1.9

.github/workflows/rubocop.yml
Fixes #9047.
This PR fixes the following GitHub Actions error.
```console
Run # set TMPDIR, git core.autocrlf
Error: Unable to process command '::set-env name=TMPDIR::D:\a\_temp'
successfully.
Error: The `set-env` command is disabled. Please upgrade to using
Environment Files or opt into unsecure command execution by setting the
`ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For
more information see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
https://github.com/rubocop-hq/rubocop/pull/9062/checks?check_run_id=1409773152
=> [Fix #9047] Fix deprecating `set-env` for GitHub Actions

changelog/fix_an_error_for_space_around_method_call_operator.md, lib/rubocop/cop/layout/space_around_method_call_operator.rb, spec/rubocop/cop/layout/space_around_method_call_operator_spec.rb
Fixes #9060.
This PR fixes the following error for `Layout/SpaceAroundMethodCallOperator` when using `__ENCODING__`.
```console
__ENCODING__
% bundle exec rubocop --only Layout/SpaceAroundMethodCallOperator -d example.rb
(snip)
An error occurred while Layout/SpaceAroundMethodCallOperator cop was
inspecting
/Users/koic/src/github.com/koic/rubocop-issues/9060/example.rb:1:0.
undefined method `double_colon' for
#<Parser::Source::Map:0x00007f8f12a3fae0>
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/layout/space_around_method_call_operator.rb:54:in
`on_const'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/commissioner.rb:100:in
`public_send'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/commissioner.rb:100:in
`block (2 levels) in …
```
=> [Fix #9060] Fix an error for `Layout/SpaceAroundMethodCallOperator`

changelog/change_update_lint_unmodified_reduce_accumulator.md, lib/rubocop/cop/lint/unmodified_reduce_accumulator.rb, spec/rubocop/cop/lint/unmodified_reduce_accumulator_spec.rb
Reduce blocks that just return something in the form `accumulator[element]` are now accepted by `Lint/UnmodifiedReduceAccumulator` (the issue asked for all methods on the accumulator to be allowed but this was the only exception previously due to the check for accumulator index). Other accumulator indexes are still offenses.
Fixes #9059.
=> Update `Lint/UnmodifiedReduceAccumulator` to accept blocks which return in the form `accumulator[element]`

CHANGELOG.md, relnotes/v1.2.0.md, spec/rubocop/cop/lint/parentheses_as_grouped_expression_spec.rb, spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb
Just auto-corrected the typos that I found when when I was working on another PR's CHANGELOG. :)
=> s/when when/when/

CHANGELOG.md, lib/rubocop/cop/lint/ambiguous_regexp_literal.rb, spec/rubocop/cop/lint/ambiguous_regexp_literal_spec.rb
I found that autocorrecting an RSpec code `expect('hello').to match /h/` with `Lint::AmbiguousRegexpLiteral` produces invalid Ruby code that misses an opening paren.
```ruby
expect('hello').to match /h/
expect('hello').to match(/h/)
expect('hello').to(match /h/))
```
I debugged a little bit, then found that the autocorrector adds the outer parens first, so it rewrites
```ruby
expect('hello').to match /h/
```
to
```ruby
expect('hello').to(match /h/)
```
then internally invokes this same autocorrector again, then fails to properly autocorrect at this second correction.
Attatched the failing specs and a possible fix (I'm not a Rubocop guy, so I'm not at all confident if I'm doing it right, but it seems like this change fixes my problem anyway).
Before submitting the PR make …
=> Correcting Lint::AmbiguousRegexpLiteral autocorrection to correctly correct my RSpec code

changelog/new_redirect_offence_reports_to_stderr_when.md, docs/modules/ROOT/pages/usage/basic_usage.adoc, lib/rubocop/cli/command/execute_runner.rb, lib/rubocop/options.rb, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/options_spec.rb
This adds `--stderr` to make it easier to use `--stdin` in shell scripts, editor integration, CI workflow, etc.
In response to feedbacks, I altered this PR from changing the behavior of `--stdin` to adding a new option. 
<details>
<summary>Here's the original description.</summary>
This makes editor integration much easier to implement by eliminating the need to process the output.
In the short term, existing editor plugins that expect `====================` will be broken, but it should be relatively easy to fix.
For example, [vscode-ruby-rubocop](https://github.com/misogi/vscode-ruby-rubocop/blob/master/src/rubocop.ts) can check if stderr output contains (or ends with) `====================` to see if it needs to delete warnings from stdout output. (to support any version of rubocop) …
=> Add an option to redirect offence reports to stderr

changelog/change_allow_specifying_a_pull_request_id_when.md, tasks/changelog.rake
Currently:
```sh
rake changelog:fix # => issue#666 if commit contains "[Fixes #666]", otherwise pull#x (amend manually later)
```
This PR adds the possibility to create the PR first, then specify the ID, amend commit and force push:
```sh
git push
<create PR> 
rake changelog:fix[42] # => pull#42
git commit -a --amend
git push --force
```
=> Allow specifying a pull request ID when calling `rake changelog:*`

changelog/change_lintmissingsuper_exclude_method_missing.md, config/default.yml, lib/rubocop/cop/lint/missing_super.rb, spec/project_spec.rb, spec/rubocop/cop/lint/missing_super_spec.rb
Contrary to the other hooks, these have very valid cases to be completely taken over:
```ruby
def method_missing(method, *args)
nil
end
def method_missing(method, *args)
delegate_to.send(method, *args)
end
```
While a class has a "right" to expect its other hooks to be called, these hooks aren't necessarily called the same way.
From https://github.com/testdouble/standard/issues/195#issuecomment-729863480
=> `Lint/MissingSuper`: exclude `method_missing` and `respond_to_missing?`

CHANGELOG.md, lib/rubocop/cop/metrics/method_length.rb, spec/rubocop/cop/metrics/method_length_spec.rb
=> [Fix #8993] Allow `ExcludedMethods` config of `Metrics/MethodLength` cop to contain regex

changelog/fix_MultilineMethodCallIndentation_indexed_assignment.md, lib/rubocop/cop/mixin/multiline_expression_indentation.rb, spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb
The `[]=` operator is a send node in the AST, which we need to consider while traveling up the ancestor hierarchy of send nodes, looking for the base of alignment.
=> [Fix #7338] Handle assignment with []= in MultilineMethodCallIndentation

changelog/change_improve_gemspec_files_attribute.md, rubocop.gemspec
This makes the gemspec independent of the git utility by replacing the
files attribute value with Ruby Dir for listing all the required files.
In addition, we exclude bin folder as these files are strictly development
concerns and can cause issues when distributed. The same goes for the
assets which are unnecessary for the distributed package. Both the README.txt
and LICENSE.txt are no longer mentioned as well as they are automatically
included in the generated file list via the extra_rdoc_files attribute.
This change reduces the overall package size from 440K down to 432K.
The version file is now loaded with the require_relative method to
increase performance and skip unnecessary lookup.
[1]: …
=> Improve the gemspec to load only the necessary files without the git utility

changelog/fix_MultilineMethodCallIndentation_inside_brackets.md, lib/rubocop/cop/mixin/multiline_expression_indentation.rb, spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb
Searching for the root of a method call chain should only consider method calls with a dot operator. We should stop if it's another kind of send node.
This is an improvement on a recent fix for the same cop. That commit only fixed the problem for the `[]=` operator. This solution is more comprehensive.
=> [Fix #7726] Handle method call chains inside square brackets

CHANGELOG.md, config/default.yml, lib/rubocop/cop/layout/empty_line_between_defs.rb, lib/rubocop/options.rb, spec/rubocop/cop/layout/empty_line_between_defs_spec.rb
* EmptyLineBetweenMethodDefs
* EmptyLineBetweenClassDefs
* EmptyLineBetweenModuleDefs
This cop previous had ability to check for empty lines between method
definitions only. This commit allows the cop to check for empty lines between class
and module definitions as well.
All three configs are enabled by default.
Closes #9064
=> [Fix #9064] Add three new config options for `Layout/EmptyLineBetweenDefs` cop

changelog/fix_fix_gemspec_to_include_assets_directory.md, rubocop.gemspec
Fix current release of rubocop 1.4.0 that not includes the assets directory used by html report.
```
rubocop --format html --out tmp/rubocop.html
```
```
No such file or directory @ rb_sysopen - /Users/javierav/.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/rubocop-1.4.0/assets/output.html.erb
```
=> Fix gemspec to include assets directory

CHANGELOG.md, lib/rubocop/cop/style/redundant_argument.rb, spec/rubocop/cop/style/redundant_argument_spec.rb
Also
* Add check for explicit receiver must be present.
* Refactor tests for the cop.
Closes #9083
=> [Fix #9083] Fix `Style/RedundantArgument` cop raising offense for more than one argument

changelog/change_deprecate_enforce_superclass_module.md, lib/rubocop/cop/mixin/enforce_superclass.rb
RuboCop core depended on this module when it supported Rails department. Rails department has been extracted to RuboCop Rails gem. I forgot to remove it when extracting Rails department from the core.
rubocop-hq/rubocop-rails#390 is ready to be removed from RuboCop core.
First of all, as soft deprecation, the document only indicates that it is a deprecation warning.
After releasing RuboCop Rails several times, I will display a deprecation warning and will remove it in RuboCop 2.0.
=> Deprecate `EnforceSuperclass` module`

changelog/fix_an_incorrect_autocorrect_for_format_string.md, lib/rubocop/cop/style/format_string.rb, spec/rubocop/cop/style/format_string_spec.rb
Fixes #9089
This PR fixes an incorrect auto-correct for `Style/FormatString` when using springf with second argument that uses an operator.
=> [Fix #9089] Fix an incorrect auto-correct for `Style/FormatString`

changelog/fix_infinite_disable_uncorrectable.md, lib/rubocop/cop/autocorrect_logic.rb, spec/rubocop/cli/cli_disable_uncorrectable_spec.rb
The `# rubocop:todo` and `# rubocop:enable` must be placed outside the heredoc. Otherwise they won't have any effect and we will just add more and more comments until we crash.
=> [Fix #7670] Handle offenses inside heredocs for --disable-uncorrectable

changelog/fix_updated_lintunmodifiedreduceaccumulator.md, lib/rubocop/cop/lint/unmodified_reduce_accumulator.rb, spec/rubocop/cop/lint/unmodified_reduce_accumulator_spec.rb
Handle cases in `Lint/UnmodifiedReduceAccumulator` when there are fewer block elements than expected. Fixes #9070.
=> [Fix #9070] Fix `Lint/UnmodifiedReduceAccumulator` when there aren't enough block arguments

changelog/fix_an_incorrect_autocorrect_for_style_and_or.md, lib/rubocop/cop/style/and_or.rb, spec/rubocop/cop/style/and_or_spec.rb
Fixes #8053.
This PR fixes an incorrect auto-correct for `Style/AndOr` when `or` precedes `and`.
=> [Fix #8053] Fix an incorrect auto-correct for `Style/AndOr`

changelog/change_upgrade_regexp_parser_to_20.md, lib/rubocop/cop/style/redundant_regexp_escape.rb, lib/rubocop/ext/regexp_node.rb, lib/rubocop/ext/regexp_parser.rb, rubocop.gemspec
regexp_parser 2.0 is out, which introduced char-based indices we wanted.
https://github.com/ammar/regexp_parser/issues/72
https://github.com/ammar/regexp_parser/pull/73
Methods we use that used to return byte-based indices now return char-based indices, so we can revert the changes made in #8989.
https://github.com/ammar/regexp_parser/blob/master/CHANGELOG.md#200---2020-11-25---janosch-m%C3%BCller
=> Upgrade regexp_parser to 2.0

changelog/change_update_configobsoletion_so_that.md, lib/rubocop/config_obsoletion.rb, lib/rubocop/config_validator.rb
In #9098 it was desired to change some parameters and have a deprecation warning be shown but still accept the old parameters. `ConfigObsoletion` previously would just error if anything was obsolete; this adds a new `severity: :warning` option to the `OBSOLETE_PARAMETERS` hash, for which issues will be warned about but rubocop will still complete.
I don't have any more tests for this because there is nothing to add to the hash until #9098 is merged, so I'll add them in there once this is accepted.
=> Update `ConfigObsoletion` so that parameters can be deprecated but still accepted

changelog/new_add_max_optional_parameters_to_parameter_lists_cop.md, config/default.yml, lib/rubocop/cop/metrics/parameter_lists.rb, spec/rubocop/cop/metrics/parameter_lists_spec.rb
This is an implementation of https://rubystyle.guide/#keyword-arguments-vs-optional-arguments
Not sure if something like `IgnoredMethods` should be added - like for this https://github.com/rubocop-hq/rubocop/compare/master...fatkodima:too_many_default_arguments-cop?expand=1#diff-3b2d7d0e5589b3568a72de6447fa1095b2e9bae437f299ab43196979d0d50c01R36
=> `Metrics/ParameterLists` supports `MaxOptionalParameters` config parameter

changelog/fix_false_positive_for_empty_lines_around_arguments.md, lib/rubocop/cop/layout/empty_lines_around_arguments.rb, spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb
Fixes #9097.
This PR fixes a false positive for `Layout/EmptyLinesAroundArguments` when blank line is inserted between method with arguments and receiver.
=> [Fix #9097] Fix a false positive for `Layout/EmptyLinesAroundArguments`

changelog/change_preset_ruby_stdlib_api_for_variable_number.md, config/default.yml
Fixes #9104
This PR presets some stdlib method names for `AllowedIdentifiers` of `Naming/VariableNumber`.
=> [Fix #9104] Preset some stdlib method names for `Naming/VariableNumber`

changelog/fix_an_incorrect_autocorrect_for_style_redundant_condition.md, lib/rubocop/cop/style/redundant_condition.rb, spec/rubocop/cop/style/redundant_condition_spec.rb
Fixes #9105
This PR fixes an incorrect auto-correct for `Style/RedundantCondition` when using operator method in `else`.
=> [Fix #9105] Fix an incorrect auto-correct for `Style/RedundantCondition`

changelog/change_update_metricsblocklength_and.md, config/default.yml, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop.rb, lib/rubocop/config_obsoletion.rb, lib/rubocop/cop/metrics/block_length.rb, lib/rubocop/cop/metrics/method_length.rb, lib/rubocop/cop/mixin/ignored_methods.rb, lib/rubocop/cop/mixin/method_complexity.rb, lib/rubocop/core_ext/hash.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/config_obsoletion_spec.rb, spec/rubocop/cop/lint/number_conversion_spec.rb, spec/rubocop/cop/metrics/abc_size_spec.rb, spec/rubocop/cop/metrics/block_length_spec.rb, spec/rubocop/cop/metrics/cyclomatic_complexity_spec.rb, spec/rubocop/cop/metrics/method_length_spec.rb, spec/rubocop/cop/style/block_delimiters_spec.rb, spec/rubocop/cop/style/class_equality_comparison_spec.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb, spec/rubocop/cop/style/method_call_without_args_parentheses_spec.rb, spec/rubocop/cop/style/numeric_predicate_spec.rb, spec/rubocop/cop/style/symbol_proc_spec.rb
As mentioned by @bbatsov at https://github.com/rubocop-hq/rubocop/pull/9058#issuecomment-729918462
1. The two cops that were configured using `ExcludedMethods` instead of `IgnoredMethods` (`Metrics/BlockLength` and `Metrics/MethodLength`) have been changed to use `IgnoredMethods` going forward. I changed the `IgnoredMethods` mixin so that it can be configured to allow for those two cops to continue accepting `ExcludedMethods` without adding that config key to the reset of the cops.
2. All cops that use the `IgnoredMethods` mixin now can accept an array of both strings and regexes, and both are applied.
Questions:
* ~Is there a good way to document this so that users will know they can use regexes for `IgnoredMethods` everywhere now?~ I added a new section to configuration.adoc.
* Is there …
=> Unification of `IgnoredMethods`

changelog/change_update_lintunmodifiedreduceaccumulator.md, config/default.yml, lib/rubocop/cop/lint/unmodified_reduce_accumulator.rb, rubocop.gemspec, spec/rubocop/cop/lint/unmodified_reduce_accumulator_spec.rb
Re https://github.com/rubocop-hq/rubocop/pull/9071#issuecomment-733042996
Adds support for numblocks and non-traditional arguments to `Lint/UnmodifiedReduceAccumulator`.
=> Update `Lint/UnmodifiedReduceAccumulator` to handle numblocks and more than 2 arguments.

changelog/fix_false_positive_for_method_call_without_args_parentheses.md, lib/rubocop/cop/style/method_call_without_args_parentheses.rb, spec/rubocop/cop/style/method_call_without_args_parentheses_spec.rb
This PR fixes the following false positive for `Style/MethodCallWithoutArgsParentheses` when assigning to a default argument with the same name.
```console
def foo(test = test())
end
Syntax OK
% rubocop --only Style/MethodCallWithoutArgsParentheses -a example.rb
C
Offenses:
example.rb:1:20: C: [Corrected] Style/MethodCallWithoutArgsParentheses:
Do not use parentheses for method calls with no arguments.
def foo(test = test())
^^
def foo(test = test)
end
example.rb:1: circular argument reference - test
```
It prevents `example.rb:1: circular argument reference - test`. …
=> Fix a false positive for `Style/MethodCallWithoutArgsParentheses`

changelog/new_support_autocorrect_for_sole_nested_conditional.md, config/default.yml, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
This PR supports auto-correction for `Style/SoleNestedConditional`.
Part of auto-correction of indentation will be left to other `Layout` cop.
=> Support auto-correction for `Style/SoleNestedConditional`

changelog/fix_false_positive_for_style_first_argument_indentation.md, lib/rubocop/cop/layout/first_argument_indentation.rb, spec/rubocop/cop/layout/first_argument_indentation_spec.rb
Fixes #9115.
This PR fixes a false positive for `Style/FirstArgumentIndentation` when argument has expected indent width and the method is preceded by splat for `EnforcedStyle: consistent_relative_to_receiver`.
=> [Fix #9115] Fix a false positive for `Style/FirstArgumentIndentation`

changelog/fix_fix_9095_use_merged_config_instead_of.md, lib/rubocop/config_loader.rb, spec/rubocop/config_loader_spec.rb
=> [Fix #9095] use merged_config instead of config for pending new cop check 

changelog/change_update_stylesymbolproc_to_be_aware_of.md, config/default.yml, lib/rubocop/cop/style/symbol_proc.rb, spec/rubocop/cop/style/symbol_proc_spec.rb
Follows https://github.com/rubocop-hq/rubocop/pull/9101#issuecomment-734036252
> Independently, I think SymbolProc should be fixed to catch { _1.foo }
Adds numblock awareness to `Style/SymbolProc`, with autocorrection.
=> Update `Style/SymbolProc` to be aware of numblocks.

CHANGELOG.md, changelog/fix_if_with_semicolon_correction.md, lib/rubocop/cop/style/if_with_semicolon.rb, spec/rubocop/cop/style/if_with_semicolon_spec.rb
Continuation of #8831.
This change fixes autocorrection for Style/IfWithSemicolon when elsif present.
In case of one of more elsif conditions present, the autocorrector will create a full if, elsif, else structure.
=> [Fix #8820] Fixes `IfWithSemicolon` autocorrection when `elsif` is present

changelog/fix_incorrect_autocorrect_for_class_and_module_children.md, lib/rubocop/cop/style/class_and_module_children.rb, spec/rubocop/cop/style/class_and_module_children_spec.rb
Fixes #9128.
This PR fixes an incorrect auto-correct for `Style/ClassAndModuleChildren` when namespace is defined as a class in the same file.
It is still undetectable when class definition exists in the different file, but it can be detected in the same file. This PR solves the latter.
=> [Fix #9128] Fix an incorrect auto-correct for `Style/ClassAndModuleChildren`

CHANGELOG.md, spec/project_spec.rb
The 1.5.0 release broke a couple changelog tests, this fixes them.
I also added a test for the `changelog/` entries to make sure the link is formatted properly.
=> Fix the changelog

changelog/fix_allowed_identifiers_for_naming_variable_number.md, lib/rubocop/cop/naming/variable_number.rb, spec/rubocop/cop/naming/variable_number_spec.rb
https://github.com/rubocop-hq/rubocop/pull/9017 Adds `AllowedIdentifiers` option to allow a preconfigured list of names for symbols and method definitions to ignore for the `Naming/VariableNumber` cop. The cop also checks for variable names, but for whatever reason, does not utilize `AllowedIdentifiers`. It is not intuitive that `AllowedIdentifiers` only checks method names and symbols but ignores variable assignment, so therefore it should be included. Further fixes https://github.com/rubocop-hq/rubocop/issues/9012.
=> AllowedIdentifiers should also check variable assignments.

changelog/change_added_notification_if_any_gems_are.md, docs/modules/ROOT/pages/extensions.adoc, lib/rubocop/cli/command/suggest_extensions.rb, spec/rubocop/cli_spec.rb
Follows #9130.
Also allows individual extensions to be disabled instead of disabling everything:
```yaml
AllCops:
SuggestExtensions:
rubocop-rake: false
```
=> Add tests and documentation for SuggestExtensions

lib/rubocop/cop/naming/variable_number.rb
A rubocop offense was merged to master in #9136, this fixes it.
=> Fix rubocop failure

changelog/fix_an_error_for_layout_empty_lines_around_arguments.md, lib/rubocop/cop/layout/empty_lines_around_arguments.rb, spec/rubocop/cop/layout/empty_lines_around_arguments_spec.rb
Fixes #9140.
This PR fixes an error for `Layout/EmptyLinesAroundArguments` when multiline style argument for method call without selector.
=> [Fix #9140] Fix an error for `Layout/EmptyLinesAroundArguments`

changelog/fix_fix_issues_with_suggestextensions_when.md, lib/rubocop/cli/command/suggest_extensions.rb
This fixes #9145 (and #9148). `SuggestExtensions` relies on Bundler to enumerate gems, but Bundler is not guaranteed to be present.
Fixes two issues:
1. Bundler is not required (`uninitialized constant RuboCop::CLI::Command::SuggestExtensions::Bundler`)
2. Bundler is required but there is no Gemfile  (`Could not locate Gemfile or .bundle/ directory`)
I'm not exactly sure how to write tests for this since bundler _is_ a development dependency and I can't add and remove a Gemfile on the fly. Any suggestions?
=> [Fix #9145] Fix issues with SuggestExtensions when bundler is not available, or when there is no gemfile

changelog/change_make_lintshadowingoutervariable_aware_of.md, lib/rubocop/cop/lint/shadowing_outer_local_variable.rb, spec/rubocop/cop/lint/shadowing_outer_local_variable_spec.rb
Block given to `Ractor.new` should not access outer variables, so shadowing the outer local variables should be encouraged.
Closes #9080 
=> [Fix #9080] Make `Lint/ShadowingOuterVariable` aware of `Ractor`

changelog/change_relax_regexp_parser_requirement.md, rubocop.gemspec
See https://github.com/rubocop-hq/rubocop/pull/9102#issuecomment-737487246
=> Relax regexp_parser requirement.

changelog/fix_fix_stylestringconcatenation_autocorrect.md, lib/rubocop/cop/style/string_concatenation.rb, spec/rubocop/cop/style/string_concatenation_spec.rb
When single quoted strings
Closes #8985 
=> [Fix #8985] Fix `Style/StringConcatenation` autocorrect generating invalid ruby

rubocop.gemspec
User can upgrade upcoming RuboCop safely, even if incompatible APIs are introduced in future RuboCop AST major updates.
The purpose is to safety the runtime impact for users, as it is already specified `rubocop-ast` in the Gemfile so that development can try the latest.
=> Safely upgrade compatible with RuboCop AST

changelog/fix_a_false_positive_for_multiline_method_call_indentation.md, lib/rubocop/cop/layout/multiline_method_call_indentation.rb, spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb
Fixes #9155.
This PR fixes a false positive for `Layout/MultilineMethodCallIndentation` when multiline method chain has expected indent width and the method is preceded by splat for `EnforcedStyle: indented_relative_to_receiver`
=> [Fix #9155] Fix a false positive for `Layout/MultilineMethodCallIndentation`

changelog/fix_incorrect_autocorrect_for_sole_nested_conditional.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
Fixes #9152.
This PR fixes an incorrect auto-correct for `Style/SoleNestedConditional` when nested `||` operator modifier condition.
=> [Fix #9152] Fix an incorrect auto-correct for `Style/SoleNestedCondional`

lib/rubocop/cop/style/redundant_regexp_escape.rb, lib/rubocop/ext/regexp_node.rb, lib/rubocop/ext/regexp_parser.rb
Follow https://github.com/rubocop-hq/rubocop/pull/9154, https://github.com/rubocop-hq/rubocop/issues/9155, and https://github.com/rubocop-hq/rubocop/pull/9102.
This is a step towards the widespread use of regexp_parser 2.0.
RuboCop core accepts regexp_parser 1.8 (#9154) , but several code is already incompatible with regexp_parser 1.8. It can cause issue because these combination of versions.
Therefore, this PR ports code for regexp_parser 1.8 that will never be maintained from https://github.com/rubocop-hq/rubocop/pull/9102.
Implementation of this patch, code is intentionally duplicated because it is evaluated only when the class is defined. Also, since obsoleted code for regexp_parser 1.8 is assumed to never be maintained, the target to be removed is clear.
To be honest, it's ugly as …
=> Support regexp_parser 1.8 and 2.x series

changelog/fix_false_positive_for_heredoc_argument_closing_parenthesis.md, lib/rubocop/cop/layout/heredoc_argument_closing_parenthesis.rb, spec/rubocop/cop/layout/heredoc_argument_closing_parenthesis_spec.rb
Fixes #9161.
This PR fixes a false positive for `Layout/HeredocArgumentClosingParenthesis` when using subsequence closing parentheses in the same line.
=> [Fix #9161] Fix a false positive for `Layout/HeredocArgumentClosingParenthesis`

changelog/fix_dont_suggest_extensions_that_are.md, lib/rubocop/cli/command/suggest_extensions.rb, spec/rubocop/cli_spec.rb
`SuggestExtensions` checks against your gemfile for installed gems in order to make suggestions, but it did not account for rubocop extensions that were installed as dependencies of dependencies (ie. in Gemfile.lock but not Gemfile). This changes that so that it continues to look at only `Gemfile` to determine what to suggest, but it's filtered down by all activated gems.
Also I figured out a way that I could test without having to mock out bundler, so it uses bundler to ensure this works (and also I added some test cases that were missing from #9149).
=> [Fix #9151] Don't suggest extensions that are installed but not direct dependencies

changelog/support_autocorrect_for_style_single_line_block_params.md, config/default.yml, lib/rubocop/cop/style/single_line_block_params.rb, spec/rubocop/cop/style/single_line_block_params_spec.rb
This PR supports auto-correct for `Style/SingleLineBlockParams`.
=> Support auto-correct for `Style/SingleLineBlockParams`

changelog/change_add_did_you_mean_message_when_warning.md, lib/rubocop/config_validator.rb, spec/rubocop/cli_spec.rb
Try to suggest a replacement cop when an invalid cop name is found in the config.
eg:
```
Error: unrecognized cop Layout/LyneLenth found in .rubocop.yml
Did you mean `Layout/LineLength`?
unrecognized cop Lint/LiteralInCondition found in .rubocop.yml
Did you mean `Lint/LiteralAsCondition`?
```
=> Add "did you mean" message when failing due to invalid cops in configuration

changelog/change_add_styleperlbackrefs_targets_and_change.md, lib/rubocop/cop/style/perl_backrefs.rb, spec/rubocop/cop/style/perl_backrefs_spec.rb
As I mentioned at https://github.com/rubocop-hq/rubocop/pull/9166#issuecomment-739158825, it would be better if `Style/PerlBackrefs` corrects some other back-refs and their English aliases like this:
|Bad|Good|
|---|---|
|$&|Regexp.last_match(0)|
|$MATCH|Regexp.last_match(0)|
|$`|Regexp.last_match.pre_match|
|$PREMATCH|Regexp.last_match.pre_match|
|$'|Regexp.last_match.post_match|
|$POSTMATCH|Regexp.last_match.post_match|
|$+|Regexp.last_match(-1)|
|$LAST_PAREN_MATCH|Regexp.last_match(-1)|
=> Add `Style/PerlBackrefs` targets and change message more detailed

changelog/fix_handle_send_nodes_with_unparenthesized.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
If a condition is rewritten by `Style/SoleNestedConditional` that was an unparenthesized send node, it would be rewritten to a syntax error. This changes it to wrap the send node in parens.
Fixes #9174.
=> [Fix #9174] Handle send nodes with unparenthesized arguments in `Style/SoleNestedConditional`

changelog/fix_remove_backref_related_code_from.md, lib/rubocop/cop/style/special_global_vars.rb
As mentioned in https://github.com/rubocop-hq/rubocop/pull/9166, some unused back-ref related code is written in SpecialGlobalVars.
=> Remove back-ref related code from `Style/SpecialGlobalVars`

changelog/fix_handle_attr_accessor_on_last_line.md, lib/rubocop/cop/layout/empty_lines_around_attribute_accessor.rb, spec/rubocop/cop/layout/empty_lines_around_attribute_accessor_spec.rb
I figured I should probably push a fix up after writing so many of my own cops. Let me know if I got the process right. I'd like to contribute more fixes for issues we run into at Chef.
The fix:
In Style/EmptyLinesAroundAttributeAccessor we check the line+1 to see if it's empty. That's fine until the attr_accessor is on the last line and then the next line is nil and `blank?` fails. When we're checking the next line and it is nil then there is no next line and the attr_accessor is on the last line. We don't need to pad with an empty line so we're good at that point and we can continue on with life.
Fixes #9184
Signed-off-by: Tim Smith <tsmith@chef.io>
=> Handle attr_accessors on the last line in EmptyLinesAroundAttributeAccessor

changelog/new_support_autocorrection_for_style_float_division.md, config/default.yml, lib/rubocop/cop/style/float_division.rb, spec/rubocop/cop/style/float_division_spec.rb
This PR supports auto-correction for `Style/FloatDivision`.
=> Support auto-correction for `Style/FloatDivision`

changelog/new_support_autocorrection_for_style_redundant_argument.md, config/default.yml, lib/rubocop/cop/style/redundant_argument.rb, spec/rubocop/cop/style/redundant_argument_spec.rb
This PR supports auto-correction for `Style/RedundantArgument`.
=> Support auto-correction for `Style/RedundantArgument`

config/default.yml
Follow https://github.com/rubocop-hq/rubocop/pull/9186#issuecomment-740405392.
This PR updates the reference for `Style/FloatDivision`.
The new link is a comprehensive reference that includes the old link address, so this PR is replacing the URL rather than adding new link.
=> Update reference for `Style/FloatDivision`

changelog/change_update_formatters_to_output_correctable.md, lib/rubocop/formatter/emacs_style_formatter.rb, lib/rubocop/formatter/simple_text_formatter.rb, lib/rubocop/formatter/tap_formatter.rb, spec/rubocop/cli/cli_auto_gen_config_spec.rb, spec/rubocop/cli/cli_autocorrect_spec.rb, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/cli_spec.rb, spec/rubocop/formatter/clang_style_formatter_spec.rb, spec/rubocop/formatter/emacs_style_formatter_spec.rb, spec/rubocop/formatter/progress_formatter_spec.rb, spec/rubocop/formatter/quiet_formatter_spec.rb, spec/rubocop/formatter/simple_text_formatter_spec.rb, spec/rubocop/formatter/tap_formatter_spec.rb
Some cops only are able to correct in specific situations, but it is unclear from the output which offenses are auto-correctable and which aren't (I kept running into this while working on #9176 and found it confusing). This adds a tag to the output for offenses which are correctable but not corrected yet:
```
Offenses:
test.rb:5:41: C: [Correctable] Layout/LineLength: Line is too long. [123/40]
attr_accessor :name, :unit_number, :street_name, :city, :province, :postal_code, :location, :direction, :country, :region
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test.rb:11:41: C: [Correctable] Layout/LineLength: Line is too long. [113/40]
Model.where(username: username, email: email, first_name: first_name, last_name: last_name, country: country) …
```
=> [Proposal] Update formatters to output `[Correctable]` for correctable offenses

changelog/change_change_stylestringconcatenation_to.md, config/default.yml, lib/rubocop/cop/style/string_concatenation.rb, spec/rubocop/cop/style/string_concatenation_spec.rb
Line end concatenation between two strings is handled by `Style/LineEndConcatenation`.
Fixes #8897.
=> [Fix #8897] Change `Style/StringConcatenation` to accept line-end concatenation

lib/rubocop/cop/naming/accessor_method_name.rb
There was a bit of confusion in #7801 about how `Naming/AccessorMethodName` works so I've updated the documentation. Functionality of the cop has not changed.
=> [Fix #7801] Update documentation for `Naming/AccessorMethodName`

lib/rubocop/cop/base.rb, lib/rubocop/cop/cop.rb, spec/rubocop/cli/cli_autocorrect_spec.rb
This addresses a few things:
1) Calling `add_offense` or `add_offense { |corrector| # don't auto-correct }` should be handled the same way. An empty corrector is now replaced by `nil`.
2) Tweaks how the status is handled. Status `:uncorrected` is reserved for cases where there is a corrector but it is not applied.
3) Old style cops' `auto_correct` method is now called even when run without auto-correction. This way we can know if they can auto-correct or not. It also simplifies logic.
I should have done 3) during my refactor (I don't see how it could be incompatible)
=> [Fix #9175] Fix status for offenses that are not correctable.

lib/rubocop/cop/correctors/string_literal_corrector.rb, lib/rubocop/cop/layout/line_length.rb, lib/rubocop/cop/mixin/string_help.rb, lib/rubocop/cop/style/character_literal.rb, lib/rubocop/cop/style/ip_addresses.rb, lib/rubocop/cop/style/string_literals.rb, lib/rubocop/cop/style/string_literals_in_interpolation.rb, spec/rubocop/cli/cli_autocorrect_spec.rb
Extracted from #9176, follows #7868.
* `Layout/LineLength`
* `Style/CharacterLiteral`
* `Style/IpAddresses`
* `Style/StringLiterals`
* `Style/StringLiteralsInInterpolation`
Also Updated `StringHelp` and `StringLiteralCorrector` for use with `Base` instead of `Cop`.
=> Updated 5 cops to inherit from `Base` instead of `Cop`

changelog/fix_an_incorrect_autocorrect_for_sole_nested_conditional.md, lib/rubocop/cop/style/if_unless_modifier.rb, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cli/cli_autocorrect_spec.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
Fixes #9160.
This PR fixes an incorrect auto-correct for `Style/IfUnlessModifier` and `Style/SoleNestedConditional` when auto-correction conflicts for guard condition.
=> [Fix #9160] Fix an incorrect auto-correct for `Style/SoleNestedConditional`

changelog/fix_fix_configobsoletionextractedcop_raising.md, lib/rubocop/config_obsoletion/extracted_cop.rb, spec/rubocop/config_obsoletion_spec.rb, spec/rubocop/cop/generator_spec.rb
In #9169, an obsoletion message was added to let users know they need to use `rubocop-rails` for Rails cops and `rubocop-performance` for Performance cops if config for those extensions was found. The warning was suppressed if the gems were found in the codebase's lockfile.
However, this ignored the fact that rubocop can be run without Bundler, which would cause the errors to be constantly emitted, because RuboCop could not determine that the gem was activated.
This is now fixed by checking the configuration's `loaded_features` for the extensions, instead of the bundle. This allows for two types of configuration to be fixed now:
1. Directly requring the extensions:
```yaml
require:
- rubocop-rails
- rubocop-performance
```
2. Inheriting from a gem that requires the extension:
```yaml …
```
=> [Fix #9196] Fix ConfigObsoletion::ExtractedCop raising errors for loaded features when Bundler is not activated

spec/project_spec.rb
I spent quite a bit of time today trying to debug why tests seemed to be randomly failing in #9197. This change makes the failure message way more clear about what's happening and offers guidance (so that the next time someone accidentally pushes something onto the global registry they'll have an easier time debugging it).
For example:
```
Failure/Error: expect(configuration_keys).to match_all_cops
Cop registry does not match configuration keys.
Check if a new cop is missing configuration, or if cops were accidentally added to the registry in another test.
Diff:
@@ -237,6 +237,49 @@
"Naming/RescuedExceptionsVariableName",
"Naming/VariableName",
"Naming/VariableNumber",
+ "Performance/AncestorsInclude",
+ "Performance/ArraySemiInfiniteRangeSlice",
...
+ "Performance/UriDefaultParser", …
```
=> Improve the test output from project_spec when there are missing configuration keys

tasks/changelog.rb
Follow https://github.com/rubocop-hq/rubocop/commit/905e3632fb662ec8a22f5be7aae0edfd6f6ca501#commitcomment-44955820.
This PR removes the last line break (EOL) from existing contributor line and adds it to the end of new contributor line.
=> Prevent broken changelog

lib/rubocop/cop/gemspec/required_ruby_version.rb, lib/rubocop/cop/registry.rb, spec/rubocop/formatter/disabled_config_formatter_spec.rb, spec/spec_helper.rb
This insures that there are no side effects from running a particular spec.
Use `:restore_registry` / `RuboCop::Cop::Registry.with_temporary_global` if
need to modify registry (e.g. with `stub_cop_class`).
See also https://github.com/rubocop-hq/rubocop/pull/9197#issuecomment-742325730
=> Freeze global registry when testing

changelog/change_allow_extensions_to_disable_cop.md, lib/rubocop/config_obsoletion.rb, spec/rubocop/config_obsoletion_spec.rb
Noticed [this change](https://github.com/rubocop-hq/rubocop-rails/commit/151b8a68c4964c998dad3ffd1a8c67048e2696aa) made to `rubocop-rails`. There needs to be a way for an extension to disable an obsoletion (ie. rubocop-rails should not have `Rails/*` raise an error)
```yaml
extracted:
Rails/*: ~
```
Follows #9143. 
=> Allow extensions to disable cop obsoletions

changelog/change_make_style_redundant_argument_aware_of_string_chomp.md, config/default.yml, lib/rubocop/cop/style/redundant_argument.rb, spec/rubocop/cop/style/redundant_argument_spec.rb
This PR makes `Style/RedundantArgument` aware of `String#chomp`.
I was able to notice it in the following suggestion.
https://github.com/rubocop-hq/rubocop/pull/9200#discussion_r539920849
=> Make `Style/RedundantArgument` aware of `String#chomp`

changelog/fix_a_false_positive_for_style_redundant_freeze.md, lib/rubocop/cop/style/redundant_freeze.rb, spec/rubocop/cop/style/redundant_freeze_spec.rb
Fixes #9213.
This PR fixes a false positive for `Style/RedanduntFreeze` when using `Array#*`.
=> [Fix #9213] Fix a false positive for `Style/RedanduntFreeze`

changelog/change_update.md, lib/rubocop/cop/naming/memoized_instance_variable_name.rb, spec/rubocop/cop/naming/memoized_instance_variable_name_spec.rb
`Naming/MemoizedInstanceVariableName` was previously not aware of dynamically defined methods, and when defined inside another method (such as a module's `inherited` callback), it used the wrong value as the method name.
Fix to be able to find `define_method` and `define_singleton_method` and use that as the node to check against, so that the recommended ivar name is correct.
Fixes #9205.
=> [Fix #9205] Update `Naming/MemoizedInstanceVariableName` to handle dynamically defined methods

Gemfile
This PR fixes the following build error of Ruby 2.4 matrix.
```console
bundle install
(snip)
Gem::RuntimeRequirementNotMetError: memory_profiler requires Ruby
version >=
2.5.0. The current ruby version is 2.4.10.364.
An error occurred while installing memory_profiler (1.0.0), and
Bundler cannot continue.
Make sure that `gem install memory_profiler -v '1.0.0' --source
'https://rubygems.org/'` succeeds before bundling.
```
https://app.circleci.com/pipelines/github/rubocop-hq/rubocop/3451/workflows/35bcf304-ebf8-4fd2-9982-fadba1fde7ec/jobs/159519
=> Fix build error for Ruby 2.4 matrix

lib/rubocop/cop/registry.rb, spec/spec_helper.rb
Updated spec_helper to freeze the registry inside a `before(:suite)` callback and reset it in `after(:suite)` so that the frozen registry doesn't break the rubocop run after specs complete in `rake default`.
I would have liked to wrap everything in a `Registry.with_temporary_global` block, but rspec doesn't allow for `around(:suite)` unfortunately.
Follows #9204.
=> [Fix #9207] Fix `can't modify frozen RuboCop::Cop::Registry` when running `bundle exec rake default`.

changelog/change_simple_math_bin_op_with_ident_ops.md, config/default.yml, lib/rubocop/cop/lint/binary_operator_with_identical_operands.rb, spec/rubocop/cop/lint/binary_operator_with_identical_operands_spec.rb
Fixes #8482 
I have removed several operators (`-`, `/`, `%`, `|` and `^`) from the ignore list, because each of them makes no sense with identical operands and looks like a bug (for example, `whatever` `-` `whatever` is always `0`, etc).
```ruby
x * x
x + x
...
x / x
x % x
...
```
=> Allow simple math for `Lint/BinaryOperatorWithIdenticalOperands` cop

changelog/change_suppress_any_config_warnings_for_rubocop.md, lib/rubocop.rb, lib/rubocop/cop/lint/shadowed_exception.rb, lib/rubocop/util.rb, lib/rubocop/version.rb, spec/rubocop/cli/cli_options_spec.rb
Because `rubocop -V` now loads the config in order to show versions of extensions, any config warnings (such as pending cops) are shown as well, which makes the output too dirty. This change suppresses any warnings as to only output the version information.
=> Suppress any config warnings for `rubocop -V`.

changelog/new_ambiguous_assignment_cop.md, config/default.yml, lib/rubocop.rb, lib/rubocop/cop/lint/ambiguous_assignment.rb, spec/rubocop/cop/lint/ambiguous_assignment_spec.rb
=> Add new `Lint/AmbiguousAssignment` cop

lib/rubocop/cop/layout/empty_line_between_defs.rb
This is a small documentation-only change to add an example for `Layout/EmptyLineBetweenDefs` for the `AllowAdjacentOneLineDefs` config option.
=> Added example for `AllowAdjacentOneLineDefs` config to `Layout/EmptyLineBetweenDefs`

changelog/fix_an_error_for_style_keyword_parameters_order.md, config/default.yml, lib/rubocop/cop/style/keyword_parameters_order.rb, spec/rubocop/cop/style/keyword_parameters_order_spec.rb
Fixes #9234.
This PR fixes the error for `Style/KeywordParametersOrder` and makes it aware of block keyword parameters.
Keyword parameters can be used with block arguments as well as method arguments, but `Style/KeywordParametersOrder` cop were unaware of it.
This PR adds block arguments to the targets for consistency. If the cop need an option to the above customize, I will open a separate PR.
=> [Fix #9234] Fix an error for `Style/KeywordParametersOrder`

changelog/change_add_ignoreliteralbranches_option_to.md, config/default.yml, lib/rubocop/cop/lint/duplicate_branch.rb, spec/rubocop/cop/lint/duplicate_branch_spec.rb
I noticed that the standard gem [disabled `Lint/DuplicateBranch`](https://github.com/testdouble/standard/pull/228) and the straw that broke the camel's back for them was that this kind of case layout registered an offense:
```ruby
case size
when "small" then 100
when "medium" then 250
when "large" then 1000
else 250
end
```
While it's true that the `medium` case and the `else` case are duplicates, I'd argue that this duplication is beneficial because it clearly outlines what possible values are expected.
Introduced a new configuration, `IgnoreLiteralBranches`, which when true will not consider any branches that just return a basic literal value, or a composite literal (array, hash, etc.) that only contains basic literals (see test for examples). As well, added `IgnoreConstantBranches` to …
=> Add `IgnoreLiteralBranches` and `IgnoreConstantBranches` options to `Lint/DuplicateBranch`

changelog/fix_a_false_positive_for_style_symbol_proc, lib/rubocop/cop/style/symbol_proc.rb, spec/rubocop/cop/style/symbol_proc_spec.rb
While upgrading to rubocop `1.6.1`, I noticed that the `Style/SymbolProc` was registering an offense on the following code:
```ruby
array.map { _2.first }
```
And suggesting to autocorrect to `array.map(&:first)`, which is incorrect in such case.
I believe this was introduced in https://github.com/rubocop-hq/rubocop/pull/9127
I suggest changing the cop to only register offenses for the `_1` numbered block argument.
=> Fix wrong offense in Style/SymbolProc

changelog/change_allow_only_and_except_to_be_able_to.md, lib/rubocop/options.rb, lib/rubocop/runner.rb, spec/rubocop/cli/cli_options_spec.rb
Previously, cop names passed to `--only` or `--except` were qualified immediately, but because the configuration is not yet loaded when `Options.parse` is called, it could not properly resolve cops that are added by an extension or a local `require`. This was generally not a problem because unresolved cops were accepted, but in the case of a cop that shares a name with a default cop, this resulted in raising a warning that the department name was wrong, and in fact loading the wrong cop.
Instead, qualifying cop names is now done lazily, so that they are only qualified right before they are needed. This ensures that the full registry is present and external cops can be properly detected.
Fixes #9235.
[1]: …
=> [Fix #9235] Allow `--only` and `--except` to be able to properly qualify cops added by require.

spec/rubocop/cop/layout/argument_alignment_spec.rb, spec/rubocop/cop/layout/class_structure_spec.rb, spec/rubocop/cop/layout/comment_indentation_spec.rb, spec/rubocop/cop/layout/first_array_element_line_break_spec.rb, spec/rubocop/cop/layout/hash_alignment_spec.rb, spec/rubocop/cop/layout/indentation_style_spec.rb, spec/rubocop/cop/layout/indentation_width_spec.rb, spec/rubocop/cop/layout/line_length_spec.rb, spec/rubocop/cop/layout/space_around_method_call_operator_spec.rb, spec/rubocop/cop/layout/space_before_block_braces_spec.rb, spec/rubocop/cop/layout/space_inside_block_braces_spec.rb
- Replace old `inspect_source` and `autocorrect_source` with `expect_offense` and `expect_correction`.
- Merge split specs for registering and corrections same offenses.
- Remove useless correction checks when we check for `expect no offenses`.
Except files:
spec/rubocop/cop/layout/end_of_line_spec.rb
spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb
spec/rubocop/cop/layout/trailing_empty_lines_spec.rb
=> Use new expect_offense and expect_correction in Layout specs

lib/rubocop/cop/layout/rescue_ensure_alignment.rb
This PR fixes a workaround for `Layout/RescueEnsureAlignment` due to `Layout/BeginEndAlignment` is enabled with RuboCop 1.0 release.
=> Fix a workaround for `Layout/RescueEnsureAlignment`

changelog/new_support_autocorrection_for_style_commented_keyword.md, config/default.yml, lib/rubocop/cop/style/commented_keyword.rb, spec/rubocop/cli/cli_autocorrect_spec.rb, spec/rubocop/cli_spec.rb, spec/rubocop/cop/style/commented_keyword_spec.rb
This PR supports auto-correction for `Style/CommentedKeyword`.
Auto-correction removes comments from `end` keyword and keeps comments for `class`, `module`, `def` and `begin` above the keyword.
=> Support auto-correction for `Style/CommentedKeyword`

docs/modules/ROOT/pages/integration_with_other_tools.adoc
Add Mega-Linter in the list of Other Integration tools
If you have remarks about rubocop page in Mega-Linter documentation, please tell me :)
https://nvuillam.github.io/mega-linter/descriptors/ruby_rubocop/
Notes:
- Default Github commit message
- Not added changelog as it is just documentation
- No need tests as it is documentation
=> docs: Add Mega-Linter in integration in other tools

changelog/fix_fix_false_positive_for_stylesymbolproc.md, lib/rubocop/cop/style/symbol_proc.rb, spec/rubocop/cop/style/symbol_proc_spec.rb
The changes in #9127 to keep the node pattern DRY accidentally broke the check that the lvar matches the argument name.
Fixes #9257.
=> [Fix #9257] Fix false positive for `Style/SymbolProc` when the block uses a variable from outside the block

changelog/fix_an_incorrect_for_multiline_when_then.md, lib/rubocop/cop/style/multiline_when_then.rb, spec/rubocop/cop/style/multiline_when_then_spec.rb
I found not autocorrecting with Style/MultilineWhenThen cop.
```ruby
case foo
when bar, baz then
case foo
when bar, baz
case foo
when bar, baz then
```
In version 0.91.0 correctly corrected, in version 0.91.1 not corrected, from #8750.
Multiple condition values may be in one line, so fixed.
=> Fix Style/MultilineWhenThen cop to correct when one line has multiple condidate values

changelog/change_add_ignoredpatterns_configuration_to.md, config/default.yml, lib/rubocop/cop/lint/unreachable_loop.rb, spec/rubocop/cop/lint/unreachable_loop_spec.rb
In #9237:
```
test_spec.rb:7:5: W: Lint/UnreachableLoop: This loop will have at most one iteration.
SomeClass.should_receive(:test).exactly(2).times { raise StandardError }
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
`Lint/UnreachableLoop` is registering on `times` here because it is an [`enumerator_method`](https://github.com/rubocop-hq/rubocop-ast/blob/master/lib/rubocop/ast/node/mixin/method_identifier_predicates.rb#L10-L13). However, it is actually an RSpec method in this case.
Since we don't know what the receiver is, `IgnoredPatterns` can now be used to have the block receiver be allowed. For instance:
```yaml
Lint/UnreachableLoop:
IgnoredPatterns:
- !ruby/regexp /exactly\(\d+\)\.times/
``` …
=> [Fix #9237] Add `IgnoredPatterns` configuration to `Lint/UnreachableLoop`

changelog/new_support_autocorrect_for_multiline_method_signature.md, lib/rubocop/cop/style/multiline_method_signature.rb, spec/rubocop/cop/style/multiline_method_signature_spec.rb
This PR supports auto-correction for `Style/MultilineMethodSignature`.
=> Support auto-correction for `Style/MultilineMethodSignature`

.rubocop_todo.yml, changelog/fix_fix_extracted_gem_warning_when_the.md, lib/rubocop/config_loader.rb, lib/rubocop/options.rb, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/config_obsoletion_spec.rb
`ConfigObsoletion::ExtractedCop` looks for loaded features in the config, but features added using `--require` were not being added to `ConfigLoader.loaded_features`. Now they are!
Fixes #9251.
=> [Fix #9251] Fix extracted cop warning when the extension is loaded using `--require`

changelog/fix_fix_calculation_of_cop_department_for.md, lib/rubocop/config.rb, spec/rubocop/config_spec.rb
This fixes an issue I ran into with rubocop-i18n. This gem provides two nested departments, I18n/RailsI18n and I18n/GetText. The intent is to enable one and disable the other. However, disabling a department would not disable its cops.
I tracked this issue down to how RuboCop::Config calculates a cops department before looking at that department's configuration: It only considers the part before the first `/`.
This pull request changes this method by considering instead all parts before the last `/`.
=> Fix calculation of cop department for nested departments

.circleci/config.yml
This PR specifies Code Climate Test Reporter 0.7.0 as a workaround to prevent `cannot execute binary file: Exec format error`.
See: https://github.com/codeclimate/test-reporter/issues/449
=> Specify Code Climate Test Reporter 0.7.0 as a workaround

spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb, spec/rubocop/cop/layout/trailing_empty_lines_spec.rb
- In trailing empty lines specs use `expect_no_offenses` and `raise_error` for offense message checking.
- In indention specs inline specs from shared example because they have different messages.
=> Use new expect_offense instead of old inspect_source in all remaining specs

changelog/fix_fix_lintambiguousregexpliteral_when.md, lib/rubocop/cop/util.rb, spec/rubocop/cop/lint/ambiguous_regexp_literal_spec.rb
`Cop::Util#add_parentheses` expected every node to have arguments, but `match_with_lvasgn` does not. This will not correct spaces properly (see the tests), but it will be picked up by `Lint/ParenthesesAsGroupedExpression`.
Fixes #9245.
=> [Fix #9245] Fix `Lint/AmbiguousRegexpLiteral` when given a `match_with_lvasgn` node

lib/rubocop/rspec/expect_offense.rb, spec/rubocop/cop/layout/trailing_empty_lines_spec.rb
Add source to `expect_correction` as dependency when there is no `expect_offense` before. It useful for testing examples where we don't able to specify source using `expect_offense`. For example in specs with missing newline.
=> Add source to `expect_correction` as dependency

changelog/change_update_stylecollectionmethods_to_be.md, config/default.yml, lib/rubocop/cop/style/collection_methods.rb, spec/rubocop/cop/style/collection_methods_spec.rb
The `Style/CollectionMethods` cop previously was not accepting anything that had additional arguments (since the first iteration it seems), so this is now a bit more permissive (we should watch for false positives). Additionally, some methods accept a symbol instead of a block/proc argument. For example, `inject`/`reduce` have accepted a final symbol since 1.9.0.
Fixes #9262.
=> [Fix #9262] Update `Style/CollectionMethods` to be handle additional arguments and methods that accept a symbol instead of a block

changelog/fix_when_a_cop_defined_in_an_extension_is.md, lib/rubocop/config.rb, lib/rubocop/config_loader_resolver.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/config_spec.rb
With `DisabledByDefault: true` in a config, `Enabled: false` is automatically added to every key in the default configuration.
In normal operation, the configuration from any config files (including via inheritence) is then merged into that default configuration, so that if a cop is explicitly enabled it overrides the default disable (in `ConfigLoaderResolver#merge_with_default`). This works even if `inherit_from` or `inherit_gem` are specified.
However, extensions inject their configuration in when they are required, and the injection code that extensions use also calls `merge_with_default`. In that case, the **extension's** configuration gets merged into rubocop's default, which then becomes the default configuration (note, depending on how many extensions are `require`d by the user, …
=> [Fix #9244] When a cop defined in an extension is explicitly enabled, ensure that it remains enabled.

.circleci/config.yml
This reverts commit e476dbbab182ead247f09793f50defb7a2f8c6f4.
https://github.com/codeclimate/test-reporter/issues/449 has been resolved.
=> Revert "Specify Code Climate Test Reporter 0.7.0 as a workaround"

changelog/fix_fix_error_in_metricsclasslength_when_the.md, lib/rubocop/cop/metrics/utils/code_length_calculator.rb, spec/rubocop/cop/metrics/class_length_spec.rb
=> [Fix #9274] Fix error in `Metrics/ClassLength` when the class only contains comments.

Rakefile, changelog/fix_add_support_for_endless_methods_to.md, config/default.yml, lib/rubocop/cop/style/single_line_methods.rb, spec/rubocop/cop/style/single_line_methods_spec.rb
`Style/SingleLineMethods` would raise an error when encountering a Ruby 3.0 endless method. I updated it to ignore single line methods (and I am working on a new cop for endless methods).
=> Add support for endless methods to `Style/SingleLineMethods`.

changelog/fix_update_stylemethoddefparentheses_to.md, config/default.yml, lib/rubocop/cop/style/method_def_parentheses.rb, spec/rubocop/cop/style/method_def_parentheses_spec.rb
Endless methods require parentheses as part of the definition, or else it is a syntax error. Therefore, `Style/MethodDefParentheses` should never consider endless methods, as rewriting to remove the parens would lead to invalid code.
=> Update `Style/MethodDefParentheses` to ignore endless method definitions since parentheses are always required

changelog/new_frozen_ragexp_and_range_literals.md, lib/rubocop/cop/style/mutable_constant.rb, lib/rubocop/cop/style/redundant_freeze.rb, spec/rubocop/cop/style/mutable_constant_spec.rb, spec/rubocop/cop/style/redundant_freeze_spec.rb
This PR makes `Style/RedundantFreeze` and `Style/MutableConstant` cops aware of frozen regexp and range literals when using Ruby 3.0.
- https://bugs.ruby-lang.org/issues/15504
- https://bugs.ruby-lang.org/issues/16377
```console
% ruby -ve 'p(/regexp/.frozen?); p (0..42).frozen?'
ruby 3.0.0dev (2020-12-23T03:25:41Z master 02233ed024) [x86_64-darwin19]
true
true
```
```console
% ruby -ve 'p(/regexp/.frozen?); p (0..42).frozen?'
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
false
false
```
=> Ruby 3.0's Regexp and Range literals will be frozen

changelog/fix_fix_layoutemptylinebetweendefs_error.md, config/default.yml, lib/rubocop/cop/layout/empty_line_between_defs.rb, spec/rubocop/cop/layout/empty_line_between_defs_spec.rb
Previously, `Layout/EmptyLineBetweenDefs` would error when encountering an endless method because `node.loc.end` is nil when endless. Now the end position for an endless method can be calculated. If `AllowAdjacentOneLineDefs` is `true`, endless methods are treated like single-line methods.
=> Fix `Layout/EmptyLineBetweenDefs` error with endless methods

.rubocop_todo.yml, changelog/fix_endless_emthod_method_call_with_args_parentheses.md, config/default.yml, lib/rubocop/cop/style/method_call_with_args_parentheses.rb, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
When an endless method definition calls another method with arguments, parentheses are required or it will be a syntax error. Therefore, parentheses are required even for the `omit_parentheses` style. If there are no arguments, the method call will continue to be matched to the enforced style as before.
=> Fix `Style/MethodCallWithArgsParentheses` for endless method definitions

changelog/fix_error_for_heredoc_argument_closing_parenthesis.md, lib/rubocop/cop/layout/heredoc_argument_closing_parenthesis.rb, spec/rubocop/cop/layout/heredoc_argument_closing_parenthesis_spec.rb
Fixes #8046.
This PR fixes an error for `Layout/HeredocArgumentClosingParenthesis` when existing an argument between heredoc of end and closing parentheses.
`Layout/HeredocArgumentClosingParenthesis` alone reproduced an error without being affected by other cops.
=> [Fix #8046] Fix an error for `Layout/HeredocArgumentClosingParenthesis`

changelog/fix_bug_in_stylelambdacall.md, lib/rubocop/cop/style/lambda_call.rb, spec/rubocop/cop/style/lambda_call_spec.rb
- The Style/LambdaCall Cop used to ignore all offenses after encountering an opposite style because during the first encounter, we set `no_acceptable_style!` and in the next iterations we early returned nil for `opposite_style_detected` check. This caused the Cop to never got around to adding the offense
- This PR fixes the behaviour by letting the Cop add the offense first before checking for `opposite_style_detected`
- This PR also updates tests to illustrate the multiple opposite style scenarios
=> [Fix #9225] Fix Style/LambdaCall ignoring further offenses after opposite style is detected

spec/rubocop/cop/alignment_corrector_spec.rb
- Replace old `inspect_source` and `autocorrect_source` with `expect_offense` and `expect_correction`.
- Use loop: false to prevent RuboCop::Runner::InfiniteCorrectionLoop error.
=> Use new expect_offense and expect_correction in AlignmentCorrector specs

lib/rubocop/rspec/cop_helper.rb, spec/rubocop/cop/layout/end_of_line_spec.rb
- Inline and remove spec helper inspect_source_file because it is used only in one place
=> Inline and remove spec helper inspect_source_file

changelog/change_support_allow_percent_literal_array_argument_for_redundant_splat_expansion.md, config/default.yml, lib/rubocop/cop/lint/redundant_splat_expansion.rb, spec/rubocop/cop/lint/redundant_splat_expansion_spec.rb
Resolves https://github.com/testdouble/standard/issues/223.
This PR adds `AllowPercentLiteralArrayArgument` option to `Lint/RedundantSplatExpansion.
I think it makes sense to allow the following splat usage.
```ruby
expect(data).to include(*%w[
id type firstName lastName displayName photo
phoneNumber publicPhone primaryMobile publicMobile publicEmail
social primaryFacility facilities
])
```
Therefore this PR defaults to `AllowPercentLiteralArrayArgument: true`.
User can set `AllowPercentLiteralArrayArgument: false` if prefer RuboCop 1.6 or lower behavior.
=> Add `AllowPercentLiteralArrayArgument` option to `Lint/RedundantSplatExpansion`

CHANGELOG.md, tasks/changelog.rb
Fix the following build error.
```console
Failures:
1) RuboCop Project Changelog has link definitions for all implicit
links
Failure/Error:
expect(changelog.include?("[#{name}]: http"))
.to be(true), "missing a link for #{name}. " \
'Please add this link to the bottom of the file.'
missing a link for @h-lame. Please add this link to the bottom of
the file.
```
https://github.com/rubocop-hq/rubocop/runs/1607857673
And this PR makes `rake changelog:merge` aware of GitHub account name with hyphen.
=> Fix a build error

changelog/change_require_parser_3_0_0_0.md, docs/modules/ROOT/pages/compatibility.adoc, rubocop.gemspec
Ruby 3.0 and Parser 3.0.0.0 have been released.
- https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/
- https://rubygems.org/gems/parser/versions/3.0.0.0
This PR requires Parser 3.0.0.0 or higher due to suppress the following warning when using Ruby 3.0.0.
```console
% ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
% rubocop
warning: parser/current is loading parser/ruby30, which recognizes
warning: 3.0.0-dev-compliant syntax, but you are running 3.0.0.
warning: please see
https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```
And this PR removes "experimental" label from support matrix.
CI matrix will be updated when CI image is released.
[1]: …
=> Require Parser 3.0.0.0 or higher

docs/modules/ROOT/pages/usage/basic_usage.adoc
=> Fix auto_correct docs link in basic_usage page

changelog/fix_false_positive_for_layout_space_before_brackets.md, config/default.yml, lib/rubocop/cop/layout/space_before_brackets.rb, spec/rubocop/cop/layout/space_before_brackets_spec.rb
Fixes #9290.
This PR fixes a false positive for `Layout/SpaceBeforeBrackets` when using array literal argument for method call.
If receiver is a method call, it is difficult to prevent false positives.
Therefore, This PR change behaviour to detect only when receiver is a variable.
As a result, safe detection is possible.
=> [Fix #9290] Fix a false positive for `Layout/SpaceBeforeBrackets`

.circleci/config.yml, .github/workflows/rubocop.yml, .mergify.yml
Follow https://github.com/rubocop-hq/rubocop/pull/9288.
Ruby 3.0.0 has been released and this Ruby version is available on `circleci/ruby:3.0` image.
- https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/
- https://hub.docker.com/r/circleci/ruby/tags/
=> CI against Ruby 3.0

changelog/fix_incorrect_autocorrect_for_redundant_cop_disable_directive.md, lib/rubocop/comment_config.rb, lib/rubocop/cop/lint/redundant_cop_disable_directive.rb, spec/rubocop/cop/lint/redundant_cop_disable_directive_spec.rb
Fixes #9298.
This PR fixes an incorrect auto-correct for `Lint/RedundantCopDisableDirective` when there is a blank line before inline comment.
=> [Fix #9298] Fix an incorrect auto-correct for `Lint/RedundantCopDisableDirective`

changelog/fix_incorrect_autocorrect_for_style_raise_args.md, lib/rubocop/cop/style/raise_args.rb, spec/rubocop/cop/style/raise_args_spec.rb
Fixes #9303.
This PR fixes an incorrect auto-correct for `Style/RaiseArgs` with `EnforcedStyle: compact` when using exception instantiation argument.
=> [Fix #9303] Fix an incorrect auto-correct for `Style/RaiseArgs`

changelog/fix_incorrect_autocorrect_for_style_redundant_return.md, lib/rubocop/cop/style/redundant_return.rb, spec/rubocop/cop/style/redundant_return_spec.rb
Fixes #9314.
This PR fixes an incorrect auto-correct for `Style/RedundantReturn` when multiple return values have a parenthesized return value.
There may be anther approach that modifies `ReturnNode#arguments` of RuboCop AST (in future).
=> [Fix #9314] Fix an incorrect auto-correct for `Style/RedundantReturn`

changelog/fix_an_error_for_layout_empty_line_between_def.md, lib/rubocop/cop/layout/empty_line_between_defs.rb, spec/rubocop/cop/layout/empty_line_between_defs_spec.rb
Fixes #9308.
This PR fixes an error for `Layout/EmptyLineBetweenDefs` when using endless class method.
=> [Fix #9308] Fix an error for `Layout/EmptyLineBetweenDefs`

changelog/change_make_deterministic_require_order_not_to_register_offense_for_ruby3.md, lib/rubocop/cop/lint/non_deterministic_require_order.rb, spec/rubocop/cop/lint/non_deterministic_require_order_spec.rb
`Dir.glob` and `Dir[]` sort the results by default in Ruby 3.0.
- https://bugs.ruby-lang.org/issues/8709
- https://github.com/ruby/ruby/commit/2f1081a451f21ca017cc9fdc585883e5c6ebf618
This PR will make not to register an offense when using Ruby 3.0.
So users don't need this cop when using Ruby 3.0.
It can be deprecated when supporting only Ruby 3.0 and higher.
I will open a PR about a new cop against `Dir.glob.sort` and `Dir[]`.sort, which became redundant in Ruby 3.0.
=> Make `Lint/NonDeterministicRequireOrder` not to register offense for Ruby 3

lib/rubocop/cop/layout/multiline_operation_indentation.rb
fix wrong example of MultilineOperationIndentation
=> fix wrong example of MultilineOperationIndentation

LICENSE.txt, README.md, docs/modules/ROOT/pages/about/license.adoc
This PR bumps license years to 2021.
=> Bump license years to 2021

spec/project_spec.rb
Re https://github.com/rubocop-hq/rubocop/pull/9310#discussion_r550726758
Added a test to make sure `Safe: true` isn't added to the configuration, as it is the default value.
=> Add project_spec test to ensure that `Safe: true` is not given in a config, since it is redundant

CHANGELOG.md, changelog/fix_incorrect_offense_for_style_empty_literal.md, lib/rubocop/cop/style/empty_literal.rb, spec/rubocop/cop/style/empty_literal_spec.rb
Fixes #9316
`Hash.new { _1[_2] = [] }` is valid code but the cop was not parsing the
numblock correctly when parsing ruby27. Now it treats both the above and
`Hash.new { |h, k| h[k] = [] }`
as valid statements.
Update the parsing in `Style/EmptyLiteral#hash_with_block` to account for `numblock`s in addition to regular `block`
=> [Fix #9316] Make `Style/EmptyLiteral` not register offense when using a numbered block

changelog/change_mark_style_mutable_constant_as_unsafe.md, config/default.yml
Follow https://github.com/rubocop-hq/rubocop/pull/8529.
`Style/MutableConstant` is the same as `Style/FrozenStringLiteralComment`, freezing object is unsafe auto-correction.
=> Mark `Style/MutableConstant` as unsafe

changelog/change_support_unicodedisplay_width_v2.md, lib/rubocop.rb, rubocop.gemspec
Adds support for v2 of `unicode-display_width`. This version emits a [warning](https://github.com/janlelis/unicode-display_width/blob/main/lib/unicode/display_width/no_string_ext.rb#L3-L6) when requiring the `no_string_ext` version, since omitting `String` extensions is the default. To compensate, I've reverted to the normal `require`, but this will of course include `String` extensions when the gem version is < 2. (It may make sense to require the `unicode-display_width`version be >= 2, to avoid unintentionally using a conflicting `String` API, let me know which approach you'd prefer.)
The only use of this library appears to be an invocation of `Unicode::DisplayWidth.of` in `lib/rubocop/cop/mixin/alignment.rb`, so this should be compatible with the v2 library …
=> Support unicode-display_width v2

changelog/new_support_asdfs_toolversions_file.md, config/default.yml, lib/rubocop/target_ruby.rb, spec/rubocop/target_ruby_spec.rb
Hey all,
Happy new year! 🎉
First time contribution so apologies in advance if I'm going about this the wrong way. I figured this could be a worthwhile feature addition to Rubocop. 
For context:
I recently switched to [asdf](https://github.com/asdf-vm/asdf) from rbenv on my personal dev environment.
I decided to try out Ruby 3.0 today on a project, and when I started getting errors from Rubocop on Ruby 3.0-specific syntax, I realized that project had a leftover `.ruby-version` pointing to 2.6.3 which surprisingly Rubocop was picking up.
At that point I felt there was an opportunity to extend the target version detection logic to be aware of asdf's `.tool-versions` file, so here is a proposed change to support that.
Suggest reading the commit message for detail.
Thanks! …
=> Support asdf's .tool-versions file

changelog/fix_first_hash_element_line_break_on_single_element_hash.md, lib/rubocop/cop/mixin/first_element_line_break.rb, spec/rubocop/cop/layout/first_hash_element_line_break_spec.rb
Fix Layout/FirstHashElementLineBreak to consider below as a multi-line
hash even though it only has one element:
{:foo => {
:bar => "baz",
}}
Now FirstHashElementLineBreak will correct the above to:
{
:foo => {
:bar => "baz",
},
}
Fixes #9312.
=> [Fix #9312] Fix `Layout/FirstHashElementLineBreak` for single line hash

changelog/fix_an_error_for_style_if_inside_else.md, lib/rubocop/cop/style/if_inside_else.rb, spec/rubocop/cop/style/if_inside_else_spec.rb
Fixes #9333.
This PR fixes an error for `Style/IfInsideElse` when using a modifier `if` nested inside an `else` after `elsif`.
=> [Fix #9333] Fix an error for `Style/IfInsideElse`

changelog/fix_an_incorrect_for_style_nested_parenthesized_calls.md, lib/rubocop/cop/style/method_call_with_args_parentheses.rb, lib/rubocop/cop/style/nested_parenthesized_calls.rb, spec/rubocop/cli/cli_autocorrect_spec.rb
Fixes #9335.
This PR fixes an incorrect auto-correct for `EnforcedStyle: require_parentheses` of `Style/MethodCallWithArgsParentheses` with `Style/NestedParenthesizedCalls`.
=> [Fix #9335] Fix an incorrect auto-correct for `NestedParenthesizedCalls`

Gemfile, bin/console, spec/spec_helper.rb
This PR uses IRB instead of Pry.
Since IRB has many enhancements since Ruby 2.7.
https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/
It replace this PR with the standard REPL IRB.
Since use of IRB is limited to RuboCop development tool, there is no impact on end users.
TIPS: If you cannot do syntax highlighting or multi-line editing with IRB of Ruby 2.7 or higher, please check the following setting.
```ruby
IRB.conf[:USE_READLINE] = true
```
If `IRB.conf[:USE_READLINE]` is true, either remove it or set to `false`, Reline is used instead of Readline.
=> Use IRB instead of Pry

changelog/change_update_stylesinglelinemethods_to_correct.md, config/default.yml, lib/rubocop/cop/style/single_line_methods.rb, spec/rubocop/cli/cli_autocorrect_spec.rb, spec/rubocop/cop/style/single_line_methods_spec.rb
Follows #9281.
If `Style/EndlessMethod` is enabled and not using the `disallow` style, single line methods will be corrected to endless methods instead. My rationale here is that if the user is allowing endless methods, they are a "smaller" correction for single line methods than replacing with a normal method definition.
I went back and forth about if this should be configured independently from the `Style/EndlessMethod` configuration. I think it makes sense to keep all the configuration for endless methods in one place, but if we'd rather have it specifically configured for `Style/SingleLineMethods`,  I'd be happy to make that change.
=> Update `Style/SingleLineMethods` to correct to an endless method definition if they are allowed

changelog/fix_handling_of_comments_during_autocorrection.md, lib/rubocop/cop/mixin/comments_help.rb, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
I learned the hard way that the `comments_before_line` won't stop until the very first line in the processed file, and that it doesn't care whether the comments begin their own line or not. So I replaced it in the 2 cops that use it.
In one of them (that uses the CommentsHelp mixin) the code already tried to limit the damage by looking for consecutive lines, so it would only break if there is a node with inline comment and missing separating line. 
The other one however would completely mess the comments, bringing all of the unrelated one to the new position, so I added spec for that case. It also fixes #9233 
=> Improve comments handling in couple of auto-corrections

changelog/fix_an_error_for_lint_redundant_dir_glob_sort.md, lib/rubocop/cop/lint/redundant_dir_glob_sort.rb, spec/rubocop/cop/lint/redundant_dir_glob_sort_spec.rb
Fixes #9342.
This PR fixes an error for `Lint/RedundantDirGlobSort` when using `collection.sort`.
=> [Fix #9342] Fix an error for `Lint/RedundantDirGlobSort`

changelog/fix_duplicate_ext_cop_versions_when_using_rubocop_verbose_version.md, lib/rubocop/config_loader.rb, spec/rubocop/cli/cli_options_spec.rb
Follow https://github.com/rubocop-hq/rubocop/issues/9349#issuecomment-756570411.
This PR fixes duplicate extension cop versions when `rubocop -V`.
The following is an example:
```yaml
require:
inherit_from: ext.yml
require:
- rubocop-performance
If there are duplicate requires, extension cop display will also be duplicated.
Duplicate requires will be displayed in duplicate.
```console
% rubocop -V
1.8.0 (using Parser 3.0.0.0, rubocop-ast 1.4.0, running on ruby 2.7.2 x86_64-darwin19)
- rubocop-performance 1.9.2
- rubocop-rspec 2.0.0
- rubocop-rspec 2.0.0
```
Even if there are duplicate requires, they will only be displayed once per extension cop.
```console
% rubocop -V
1.8.0 (using Parser 3.0.0.0, rubocop-ast 1.4.0, running on ruby 2.7.2 x86_64-darwin19)
- …
=> Fix duplicate extension cop versions when `rubocop -V`

CHANGELOG.md, changelog/fix_faulty_calculation_in_uncommunicative_name.md, lib/rubocop/cop/mixin/uncommunicative_name.rb, spec/rubocop/cop/naming/block_parameter_name_spec.rb, spec/rubocop/cop/naming/method_parameter_name_spec.rb
Fix #8229
`UncommunicativeName#check` does faulty calculation of location when a parameter has a prefix like `_`, `*`.
As for the file below,
```ruby
def test1(_a); end
def test2(__a); end
def test3(*a); end
def test4(**a); end
def test5(**__a); end
```
it shows offenses with faulty locations.
```shell
$ rubocop test.rb
C
Offenses:
test.rb:3:11: C: Naming/MethodParameterName: Method parameter must be at least 3 characters long.
def test1(_a); end
^
test.rb:5:11: C: Naming/MethodParameterName: Method parameter must be at least 3 characters long.
def test2(__a); end
^
test.rb:7:11: C: Naming/MethodParameterName: Method parameter must be at least 3 characters long.
def test3(*a); end
^
test.rb:9:11: C: Naming/MethodParameterName: Method parameter must be at least 3 …
```
=> [Fix #8229] Fix faulty calculation in UncommunicativeName

changelog/fix_wrap_in_parens_before_replacing_unless.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
Fix edge case in `Style/SoleNestedConditional` auto-correct.
I think it only applies to an outer `unless` with multiple conditions, but without parens.
The addition of parentheses is correct.
However, the `!` is the wrong place.
It should be before the parentheses.
=> Fix sole nested conditional handle parens

changelog/fix_fix_stylesinglelinemethods.md, lib/rubocop/cop/style/single_line_methods.rb, spec/rubocop/cop/style/single_line_methods_spec.rb
Previously this was adding extra parens erroneously. Fixes #9355.
=> [Fix #9355] Fix `Style/SingleLineMethods` autocorrection to endless method when the original code had parens

spec/spec_helper.rb
Re: https://github.com/rubocop-hq/rubocop/pull/9341#issuecomment-757504942
#9341 replaced pry with irb but it is useful for debugging. This change will just allow pry to be used in rspec if it's activated from Gemfile.local.
=> Allow `pry` to be activated in rspec if in the local gemfile.

changelog/fix_do_not_register_offense_for.md, config/default.yml, lib/rubocop/cop/style/explicit_block_argument.rb, spec/rubocop/cop/style/explicit_block_argument_spec.rb
When the block arguments and yield arguments are not an exact match, no offense is raised. Fixes #9304.
=> [Fix #9304] Do not register offense for `Style/ExplicitBlockArgument` when the `yield` arguments are not an exact match with the block arguments.

changelog/fix_string_concatenation_correctioon_in_handle_double_quote.md, lib/rubocop/cop/style/string_concatenation.rb, spec/rubocop/cop/style/string_concatenation_spec.rb
This PR will resolve following problem. 
```ruby
'"bar"' + foo
```
after `rubocop  -A`
```ruby
""bar"#{foo}"
```
`""bar"#{foo}"` should be `"\"bar\"#{foo}"`
This pull request doesn't have related issue.
=> Fix an incorrect auto-correct for `StringConcatenation` when concat string includes double quote and interpolation.

changelog/fix_fix_errors_being_reported_with_rubocop_v.md, lib/rubocop/config.rb, lib/rubocop/config_loader.rb, lib/rubocop/config_store.rb, lib/rubocop/version.rb, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/config_store_spec.rb, spec/rubocop/version_spec.rb
Currently if the configuration has anything invalid in it (obsolete cops, invalid cops, etc.), `rubocop -V` will output error messages from config validation but not the actual version information.
```shell
$ rubocop -V
Error: The `Style/MethodMissing` cop has been split into `Style/MethodMissingSuper` and `Style/MissingRespondToMissing`.
(obsolete configuration found in .rubocop.yml, please update it)
```
This change allows the config to be loaded without being validated, which allows `rubocop -V` to output properly. Only the version command is affected.
```shell
$ rubocop -V
1.6.1 (using Parser 2.7.2.0, rubocop-ast 1.3.0, running on ruby 2.6.6 x86_64-darwin18)
- rubocop-performance 1.9.1
- rubocop-rspec 2.0.1
$ rubocop
Error: The `Style/MethodMissing` cop has been split into …
```
=> Show `rubocop -V` output even if the configuration is invalid

changelog/fix_incorrect_autocorrect_for_style_sole_nested_conditional.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
Fixes #9366.
This PR fixes an incorrect auto-correct for `Style/SoleNestedConditional` when using method arguments without parentheses for outer condition.
=> [Fix #9366] Fix an incorrect auto-correct for `Style/SoleNestedConditional`

lib/rubocop/cop/naming/variable_number.rb
Configurable attribute for AllowedIdentifiers is plural
=> Fix typo for AllowedIdentifiers example

changelog/fix_an_incorrect_autocorrect_for_style_sole_nested_conditional.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
Fixes #9370.
This PR fixes an incorrect auto-correct for `Style/SoleNestedConditional` when using nested `unless` modifier multiple conditional.
=> [Fix #9370] Fix an incorrect auto-correct for `Style/SoleNestedCondtional`

changelog/fix_error_for_style_if_inside_else.md, lib/rubocop/cop/style/if_inside_else.rb, spec/rubocop/cop/style/if_inside_else_spec.rb
Fixes #9372.
This PR fixes an error for `Style/IfInsideElse` when nested `if` branch code is empty.
=> [Fix #9372] Fix an error for `Style/IfInsideElse`

changelog/change_mark_unsafe_for_style_float_division.md, config/default.yml, lib/rubocop/cop/style/float_division.rb
Fixes #9380.
This PR marks `Style/FloatDivision` as unsafe.
If operand variable is a string object then `.to_f` will be removed and an error will occur.
=> [Fix #9380] Mark `Style/FloatDivision` as unsafe

changelog/new_support_ignored_methods_for_style_format_string_token.md, config/default.yml, lib/rubocop/cop/style/format_string_token.rb, spec/rubocop/cop/style/format_string_token_spec.rb
Fixes #7452.
This PR supports `IgnoredMethods` option for `Style/FormatStringToken`.
It solves library-specific issues as follows:
```Ruby
get '/catalogue/:book_id/book', to: redirect('book/%{book_id}', status: 301)
^^^^^^^^^^ Prefer annotated tokens ...
```
The default is empty for RuboCop cores. I will set `redirect` to `IgnoredMethods` in RuboCop Rails by default.
```yaml
Style/FormatStringToken:
IgnoredMethod:
- redirect
```
=> [Fix #7452] Support `IgnoredMethods` option for `Style/FormatStringToken`

.pre-commit-hooks.yaml, changelog/new_add_precommit_hook.md, docs/modules/ROOT/pages/integration_with_other_tools.adoc
Add an entry point (hook) for using RuboCop with the pre-commit
framework. The entry point allows users to add a minimal pre-commit
config to their project and then it will run RuboCop on commit.
For details on the pre-commit project, see: https://pre-commit.com/.
Here is the framework's introduction:
> Git hook scripts are useful for identifying simple issues before
> submission to code review. We run our hooks on every commit to
> automatically point out issues in code such as missing semicolons,
> trailing whitespace, and debug statements. By pointing these issues
> out before code review, this allows a code reviewer to focus on the
> architecture of a change while not wasting time with trivial style
> nitpicks.
>
> As we created more libraries and projects we recognized that sharing
> …
=> [Fix #7827] Add pre-commit hook

changelog/fix_a_suggestion_message_when_not_auto_correctable.md, lib/rubocop/cop/base.rb, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/cli_spec.rb
This PR fixes a suggestion message when not auto-correctable.
RuboCop can specify `AutoCorrect: false`. In this case, even though auto-correct will not possible, auto-correct will be suggested.
The following sets `AutoCorrect: false` to `Style/StringLiterals`.
```console
Style/StringLiterals:
AutoCorrect: false
puts "hello"
```
Running rubocop suggests `1 offense auto-correctable`.
```console
% rubocop
(snip)
C
Offenses:
example.rb:3:6: C: [Correctable] Style/StringLiterals: Prefer
single-quoted strings when you don't need string interpolation or
special symbols.
puts "hello"
^^^^^^^
1 file inspected, 1 offense detected, 1 offense auto-correctable
```
Running `rubocop -a` suggests `1 more offense can be corrected with rubocop -A` next. …
=> Fix a suggestion message when not auto-correctable

changelog/fix_incorrect_autocorrect_for_style_nil_comparison.md, lib/rubocop/cop/style/nil_comparison.rb, spec/rubocop/cop/style/nil_comparison_spec.rb
Fixes #9387.
This PR fixes incorrect auto-correct for `Style/NilComparison` when using `!x.nil?` and `EnforcedStyle: comparison`.
=> [Fix #9387] Fix incorrect auto-correct for `Style/NilComparison`

changelog/change_make_style_ascii_comments_allow_copyright_notice.md, config/default.yml, lib/rubocop/cop/style/ascii_comments.rb, spec/rubocop/cli/cli_options_spec.rb
Fixes #9345.
This PR makes `Style/AsciiComments` allow copyright notice "©" by default.
=> [Fix #9345] Make `Style/AsciiComments` allow copyright notice

changelog/fix_infinite_loop_error_for_non_nil_check.md, lib/rubocop/cop/style/non_nil_check.rb, spec/rubocop/cli/cli_autocorrect_spec.rb, spec/rubocop/cop/style/non_nil_check_spec.rb
This PR fixes the following infinite loop error for `IncludeSemanticChanges: false` of `Style/NonNilCheck` with `EnforcedStyle: comparison` of `Style/NilComparison`.
```ruby
!(foo == nil)
```
```yaml
Style/NilComparison:
Enabled: true
EnforcedStyle: comparison # alternative config
```
```console
% bundle exec rubocop -A
(snip)
C
Offenses:
example.rb:3:1: C: [Corrected] Style/InverseMethods: Use != instead of
inverting ==.
!(foo == nil)
^^^^^^^^^^^^^
example.rb:3:5: C: [Corrected] Style/NonNilCheck: Prefer
!expression.nil? over expression != nil.
foo != nil
^^
example.rb:3:6: C: [Corrected] Style/NilComparison: Prefer the use of
the == comparison.
!foo.nil?
^^^^
0 files inspected, 3 offenses detected, 3 offenses corrected …
```
=> Fix an infinite loop error for `Style/NonNilCheck` with `Style/NilComparison`

changelog/fix_dont_autocorrect_layoutlinelength_for_a.md, lib/rubocop/cop/mixin/check_line_breakable.rb, spec/rubocop/cop/layout/line_length_spec.rb
When the first argument of a method call is a hash, and the method is not parenthesized, autocorrection would move the argument to a new line, which would cause a syntax error:
```ruby
foo x: a_really_long_value_that_triggers_the_line_length_cop
foo
x: a_really_long_value_that_triggers_the_line_length_cop
#=> SyntaxError: unexpected ':', expecting end-of-input
```
Now, if there is more than one pair, the line break will be added after the first argument instead of before it so that the syntax error is avoided.
Fixes #9374.
=> [Fix #9374] Fix autocorrection for `Layout/LineLength` when the first argument to a send node is a overly long hash pair

CHANGELOG.md, lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb, spec/rubocop/cop/naming/rescued_exceptions_variable_name_spec.rb
Fixes #7766
The old code used `node.body&.each_descendant(:lvar)` to replace the exception variable. The problem is, that doesn't work if the rescue body is a single variable with the name of the exception variable. Using `each_node` will consider that case too.
=> [Fix #7766] Rename rescue body vars when renaming exception name

spec/project_spec.rb
Small test update to show better error messages when configuration is missing for a (new) cop, rather than failing.
=> Improve project_spec tests when expected configuration for a cop is missing.

CHANGELOG.md, changelog/fix_fix_namingrescuedexceptionsvariablename.md, lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb, spec/rubocop/cop/naming/rescued_exceptions_variable_name_spec.rb
Follows #9398. Fixes the corrector to stop autocorrecting when the exception variable is reassigned, either with `lvasgn` or `masgn`. The assignments will be corrected but further uses of that variable will not be changed.
The previous PR also added to the wrong changelog so I've combined the two PRs into a single changelog item in `changelog/`.
Fixes #7766 (again 😆).
=> [Fixes #7766] Fix `Naming/RescuedExceptionsVariableName` autocorrection issues.

lib/rubocop/cop/style/non_nil_check.rb, spec/rubocop/cop/style/non_nil_check_spec.rb
This PR tweaks offense messages for `Style/NonNilCheck` cop.
In particular, the following incorrect message will be corrected.
```ruby
foo != nil
```
```yaml
Style/NonNilCheck:
IncludeSemanticChanges: true
```
There is a mismatch between offense message and auto-corrected code.
```console
% rubocop --only Style/NonNilCheck
(snip)
C
Offenses:
example.rb:1:5: C: [Corrected] Style/NonNilCheck: Prefer !expression.nil? over expression != nil.
foo != nil
^^
foo
```
This PR fixes to the correct message `Explicit non-nil checks are usually redundant.`.
[1]: …
=> Tweak offense messages for `Style/NonNilCheck` cop

changelog/fix_rubocop_todo_link_injection_when.md, lib/rubocop/cli/command/auto_genenerate_config.rb, spec/rubocop/cli/cli_auto_gen_config_spec.rb
The `rubocop --auto-gen-config` script will insert `inherit_from: .rubocop_todo.yml` at the top of the rubocop config file if the line doesn't already exist. However, if the config file has a YAML document start sigil (`---`), this will elide the remainder of the config file when running rubocop. This PR resolves the issue by injecting the `inherit_from` entry after the first such sigil, if one exists.
=> Fix rubocop_todo link injection when YAML doc start sigil exists

lib/rubocop/cop/style/eval_with_location.rb, spec/rubocop/cop/style/eval_with_location_spec.rb
The messages from `Style/EvalWithLocation` were a little over-wordy, not specific enough (it said `eval` for `class_eval`, etc.), and did not include the binding argument for `eval`. I also rewrote the cop description comment to be more clear.
=> Improve offense messages for `Style/EvalWithLocation`.

lib/rubocop/cop/style/single_line_methods.rb, spec/rubocop/cop/style/single_line_methods_spec.rb
Follow https://github.com/rubocop-hq/rubocop/pull/9281#issuecomment-751654689.
This PR fixes a typo for `Style/SingleLineMethods`.
`EnforcedStyle: allow` -> `EnforcedStyle: allow_single_line`
=> Fix a typo for `Style/SingleLineMethods`

changelog/change_added_allowedcops_configuration_to.md, config/default.yml, lib/rubocop/cop/style/disable_cops_within_source_code_directive.rb, spec/rubocop/cop/style/disable_cops_within_source_code_directive_spec.rb
Allows specific cops to be allowed to be enabled/disabled when `Style/DisableCopsWithinSourceCodeDirective` is enabled.
I also changed the cop's message to be clearer (it'll also show which cops are not allowed when some are allowed).
Fixes #9399.
=> [Fixes #9399] Added `AllowedCops` configuration to `Style/DisableCopsWithinSourceCodeDirective`

changelog/change_empty_line_magic_comment_with_shareable_constant_value.md, lib/rubocop/magic_comment.rb, spec/rubocop/cop/layout/empty_line_after_magic_comment_spec.rb
=> Change `Layout/EmptyLineAfterMagicComment` to accept `shareable_constant_values` directive

changelog/new_added_info_severity_level_to_allow.md, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop/cop/severity.rb, lib/rubocop/formatter/git_hub_actions_formatter.rb, lib/rubocop/options.rb, lib/rubocop/runner.rb, spec/rubocop/cli_spec.rb, spec/rubocop/cop/offense_spec.rb, spec/rubocop/cop/severity_spec.rb, spec/rubocop/options_spec.rb
Cops can now be configured to have `Severity: info` which will cause offenses to be reported but not cause the `rubocop` command to return `1` if there are any. It can be overridden by `--fail-level` and works with `--display-only-fail-level-offenses`.
Fixes #9340.
=> [Fixes #9340] Added `info` Severity level to allow offenses to be listed but not return a non-zero error code

lib/rubocop/rspec/expect_offense.rb, spec/rubocop/cop/layout/trailing_empty_lines_spec.rb
`Layout/TrailingEmptyLines` did not previously work great with `expect_offense`, because by using a heredoc with an inline annotation, a newline was added implicitly, which would make the cop succeed. Previously in #9263, these were changed to use `expect_no_offenses` in conjunction with `raise_error` to try to capture the offense. This works but makes the spec hard to read as it implies the opposite of what is actually happening.
I have now updated this to be able to properly use the "correct" expectation (ie. `expect_offense` when there's actually an offense), by adding an optional argument to `expect_offense` to `chomp` the source being processed (so that the newline added for the annotation does not become part of the source). This is only really useful for this cop in particular, but …
=> Fix `Layout/TrailingEmptyLines` spec to not need to use `raise_error`.

changelog/change_number_conversion_to_handle_symbols.md, lib/rubocop/cop/lint/number_conversion.rb, spec/rubocop/cop/lint/number_conversion_spec.rb
=> [Fix #7902] Change `Link/NumberConversion` to detect symbol form of conversion methods

lib/rubocop/cop/generator.rb, spec/rubocop/cop/generator_spec.rb
Follow #9421.
This PR tweaks new cop template.
New cop development will rarely need `subject(:cop) { described_class.new(config) }`.
So I think there aren't any development tips lost by replacing it with `RSpec.describe ..., :config`.
Perhaps `let(:config) { RuboCop::Config.new }` can also be removed, but I'll look at it separately. Maybe not as explicitly unnecessary as `subject(:cop) { described_class.new(config) }`.
=> Tweak new cop template

changelog/change_class_structure_to_detect_inline_modifiers.md, lib/rubocop/cop/layout/class_structure.rb, spec/rubocop/cop/layout/class_structure_spec.rb
Fix https://github.com/rubocop-hq/rubocop/issues/9415
* Added check for inline def modifiers. Now they can be handle as `public_methods`, `protected_methods`, and `private methods` respectively.
* Fixed autocorrection range for methods with modifier.
* Fixed test that now throws new offence for inline modifier but was created for another reason.
=> [Fix #9415] Change `Layout/ClassStructure` to detect inline modifiers

changelog/fix_fix_false_negatives_for.md, lib/rubocop/cop/style/eval_with_location.rb, spec/rubocop/cop/style/eval_with_location_spec.rb
Found two issues in `Style/EvalWithLocation`:
* It did not register an offense for `Kernel.eval` (or `::Kernel.eval`)
* If given improper arguments, it did not register an offense.
Previously if `eval` methods were given any arguments in the file and line spots, the cop would not register an offense. This change allows the cop to detect improper values for file (anything other than `__FILE__`, which the cop previously was implicitly expecting) and line (as before, `__LINE__` with an offset as appropriate).
This should be merged after #9409 and I'll fix up the messages in the new tests to reflect those changes once merged.
=> Fix false negatives for `Style/EvalWithLocation`

changelog/fix_error_in_layout_class_structure.md, lib/rubocop/cop/layout/class_structure.rb, spec/rubocop/cop/layout/class_structure_spec.rb
=> [Fix #9425] Fix error in `Layout/ClassStructure` when initializer comes after private attribute macro

changelog/fix_an_incorrect_autocorrect_for_class_methods_definitions.md, lib/rubocop/cop/mixin/comments_help.rb, spec/rubocop/cop/style/class_methods_definitions_spec.rb
This PR fixes the following incorrect auto-correct for `Style/ClassMethodsDefinitions` when defining class methods with `class << self` and there is no blank line between method definition and attribute accessor.
```console
class A
class << self
def three
end
attr_reader :two
end
end
```
```console
% bundle exec rubocop --only Style/ClassMethodsDefinitions -a
(snip)
C
Offenses:
example.rb:2:3: C: [Corrected] Style/ClassMethodsDefinitions: Do not
define public methods within class << self.
class << self ...
^^^^^^^^^^^^^
```
The syntax is broken as follows.
```console
class A
class << self    attr_reader :two
end
def self.three
end
end
example.rb:2: syntax …
```
=> Fix an incorrect auto-correct for `Style/ClassMethodsDefinitions`

changelog/fix_an_error_for_style_eval_with_location.md, lib/rubocop/cop/style/eval_with_location.rb, spec/rubocop/cop/style/eval_with_location_spec.rb
Fixes #9433
This PR fixes an error for `Style/EvalWithLocation` when using eval with block argument.
=> [Fix #9433] Fix an error for `Style/EvalWithLocation`

changelog/fix_fix_lintsymbolconversion_for_implicit.md, lib/rubocop/cop/lint/symbol_conversion.rb, spec/rubocop/cop/lint/symbol_conversion_spec.rb
=> [Fix #9440] Fix `Lint/SymbolConversion` for implicit `to_sym` without a receiver

changelog/fix_error_with_colorization_for_severity_info.md, lib/rubocop/formatter/simple_text_formatter.rb, spec/rubocop/formatter/simple_text_formatter_spec.rb
=> [Fix #9444] Fix error on colorization for offenses with `Severity: info`

changelog/fix_false_positive_for_layout_space_before_bracket.md, lib/rubocop/cop/layout/space_before_brackets.rb, spec/rubocop/cop/layout/space_before_brackets_spec.rb
Fixes #9438
This PR fixes a false positive for `Layout/SpaceBeforeBrackets` when space is used in left bracket.
=> [Fix #9438] Fix a false positive for `Layout/SpaceBeforeBrackets`

changelog/fix_an_error_for_style_nil_comparison.md, lib/rubocop/cop/style/nil_comparison.rb, spec/rubocop/cop/style/nil_comparison_spec.rb
Fixes #9449.
This PR fixes an error for `Style/NilComparison` when using `x == nil` as a guard condition'.
=> [Fix #9449] Fix an error for `Style/NilComparison`

changelog/fix_false_positive_for_lint_symbol_conversion.md, lib/rubocop/cop/lint/symbol_conversion.rb, spec/rubocop/cop/lint/symbol_conversion_spec.rb
Fixes #9455.
This PR fixes a false positive for `Lint/SymbolConversion` when hash keys that contain `":"`.
=> [Fix #9455] Fix a false positive for `Lint/SymbolConversion`

changelog/fix_a_false_positive_for_lint_symbol_conversion.md, lib/rubocop/cop/lint/symbol_conversion.rb, spec/rubocop/cop/lint/symbol_conversion_spec.rb
Fixes #9457.
This PR fixes a false positive for Lint/SymbolConversion when hash keys that end with `=`.
=> [Fix #9457] Fix a false positive for `Lint/SymbolConversion`

changelog/fix_dont_correct_stylesinglelinemethods.md, lib/rubocop/cop/style/single_line_methods.rb, spec/rubocop/cop/style/single_line_methods_spec.rb
In #9295, `Style/SingleLineMethods` was updated to correct to an endless method if enabled in `Style/EndlessMethod`, however, it did not check that the correct ruby version was being targetted. Now, methods will never be corrected to endless methods prior to ruby 3.0, regardless of the config.
Fixes #9466.
=> [Fix #9466] Don't correct `Style/SingleLineMethods` using endless methods if the target ruby is < 3.0

changelog/change_improve_offense_message_when_there_is_an.md, lib/rubocop/cop/layout/empty_line_between_defs.rb, spec/rubocop/cop/layout/empty_line_between_defs_spec.rb
When there is a range allowed for empty lines, the offense message takes that into account.
Fixes #9437.
=> [Fix #9437] Improve offense message when there is an allowed range of empty lines.

changelog/fix_an_error_for_sole_nested_conditional.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
Fixes #9448.
This PR fixes an error for `Style/SoleNestedConditional` when using nested `unless` modifier single as in single expression.
=> [Fix #9448] Fix an error for `Style/SoleNestedConditional`

changelog/fix_an_error_for_lint_deprecated_constants.md, lib/rubocop/cop/lint/deprecated_constants.rb, spec/rubocop/cop/lint/deprecated_constants_spec.rb
Fixes #9473.
This PR fixes the following error for `Lint/DeprecatedConstants` when using `__ENCODING__`.
```console
__ENCODING__
% bundle exec rubocop --only Lint/DeprecatedConstants -d
(snip)
Scanning /Users/koic/src/github.com/koic/rubocop-issues/9473/example.rb
An error occurred while Lint/DeprecatedConstants cop was inspecting /Users/koic/src/github.com/koic/rubocop-issues/9473/example.rb.
undefined method `expression' for nil:NilClass
/Users/koic/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-ast-1.4.1/lib/rubocop/ast/node.rb:244:in `source'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/lint/deprecated_constants.rb:40:in `on_const'
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/cop/commissioner.rb:100:in …
```
=> [Fix #9473] Fix an error for `Lint/DeprecatedConstants`

changelog/new_add_allowed_method_option_to_if_with_boolean_literal_branche.md, config/default.yml, lib/rubocop/cop/style/if_with_boolean_literal_branches.rb, spec/rubocop/cop/style/if_with_boolean_literal_branches_spec.rb
Fixes #9459.
This PR adds `AllowedMethods` option to `Style/IfWithBooleanLiteralBranches` and set `nonzero?` as default value.
=> [Fix #9459] Add `AllowedMethods` option to `Style/IfWithBooleanLiteralBranches`

changelog/fix_incorrect_autocorrect_for_style_if_with_boolean_literal_branches.md, lib/rubocop/cop/style/if_with_boolean_literal_branches.rb, spec/rubocop/cop/style/if_with_boolean_literal_branches_spec.rb
Fixes #9454.
This PR fixes an incorrect auto-correct for `Style/IfWithBooleanLiteralBranches` when using `elsif do_something?` with boolean literal branches.
=> [Fix #9454] Fix an incorrect auto-correct for `Style/IfWithBooleanLiteralBranches`

changelog/change_mark_unsafe_autocorrect_for_if_with_boolean_literal_branches.md, config/default.yml, lib/rubocop/cop/style/if_with_boolean_literal_branches.rb
Follow https://github.com/rubocop-hq/rubocop/pull/9461#issuecomment-770046288.
This PR marks `Style/IfWithBooleanLiteralBranche` as unsafe auto-correction.
=> Mark `Style/IfWithBooleanLiteralBranche` as unsafe auto-correction

changelog/fix_fix_styleguidebaseurl_not_functioning.md, lib/rubocop/cop/message_annotator.rb, spec/rubocop/cop/message_annotator_spec.rb
Currently, you can set the StyleGuideBaseURL config for cops that ship
within RuboCop or other RuboCop plugins that use a DEPT/COP format. If
the project has nested departments this doesn't work as the message
annotator does not properly split the cop name to determine the
department to lookup in the config.
With this change, just the cop name is split off from the full DEPT/COP
string allowing the StyleGuideBaseURL to function with nested
departments.
We have nested departments in Cookstyle like `Chef/Deprecations/Foo` and
we'd like to be able to enable this config by default so we can point
our users at our documentation and define the URL at the department level.
Signed-off-by: Tim Smith <tsmith@chef.io>
=> [#9452] `StyleGuideBaseURL` not functioning with nested departments

tasks/changelog.rb
Follow https://github.com/rubocop-hq/rubocop/commit/7b54f43.
This PR supports co-contributor signature for changelog build and prevents the following build error when using `rake changelog:merge` for co-contributor signature.
```console
Failures:
1) RuboCop Project Changelog has link definitions for all implicit links
Failure/Error:
expect(changelog.include?("[#{name}]: http"))
.to be(true), "missing a link for #{name}. " \
'Please add this link to the bottom of the file.'
missing a link for @jdufresne. Please add this link to the bottom
of the file.
Finished in 4 minutes 51.7 seconds (files took 4.62 seconds to load)
15455 examples, 1 failure, 14 pending
```
https://github.com/rubocop-hq/rubocop/runs/1782491421
**Replace this text with a summary of the …
=> Support co-contributor signature for changelog build

changelog/fix_infite_loop_error_for_first_parameter_indentation.md, lib/rubocop/cop/layout/first_argument_indentation.rb, spec/rubocop/cli/cli_autocorrect_spec.rb
Fixes #9453.
This PR fixes the following infinite loop error for `Layout/FirstParameterIndentation` when `EnforcedStyle: with_fixed_indentation` is specified for `Layout/ArgumentAlignment`.
```console
RSpec.describe MyController, type: :controller do
it 'abc' do
expect(response).to redirect_to(path(
obj1,
id: obj2.id
))
end
end
AllCops:
NewCops: enable
Layout/ArgumentAlignment:
EnforcedStyle: with_fixed_indentation
% bundle exec rubocop -a --only Layout/ArgumentAlignment,Layout/FirstArgumentIndentation
(snip)
/Users/koic/src/github.com/koic/rubocop-issues/9453/example.rb and
caused by Layout/FirstArgumentIndentation -> Layout/ArgumentAlignment
/Users/koic/src/github.com/rubocop-hq/rubocop/lib/rubocop/runner.rb:304:in …
```
=> [Fix #9453] Fix an infinite loop error for `Layout/FirstParameterIndentation`

docs/modules/ROOT/pages/integration_with_other_tools.adoc
When using pre-commit, extensions that require additional gems must be
specified using `additional_dependencies` in `.pre-commit-config.yaml`.
=> [Fix #9488] Document how to use pre-commit with RuboCop extensions

changelog/fix_incorrect_autocorrect_for_first_argument_indentation.md, lib/rubocop/cop/layout/first_argument_indentation.rb, spec/rubocop/cli/cli_autocorrect_spec.rb
Fixes #9490 and a regression of #9486.
This PR fixes incorrect auto-correct for `Layout/FirstArgumentIndentation` when specifying `EnforcedStyle: with_fixed_indentation` of `Layout/ArgumentAlignment` and `EnforcedStyle: consistent` of `Layout/FirstArgumentIndentation`.
And this resolves the following Standard gem build error when upgrading to RuboCop 1.9.1.
```console
2) Failure:
Standard::CliTest#test_autocorrectable
[/home/runner/work/standard/standard/test/standard/cli_test.rb:14]:
--- expected
+++ actual
@@ -98,13 +98,13 @@
```
https://github.com/testdouble/standard/runs/1805630903
=> [Fix #9490] Fix incorrect auto-correct for `Layout/FirstArgumentIndentation`

lib/rubocop/cop/layout/multiline_assignment_layout.rb
I was looking for exactly the configurable attributes `SupportedTypes` for the cop Layout/MultilineAssignmentLayout.  But, I had to look in the code to found out this attribute and in `config/default.yml` to found the available parameters. I thought it might be useful to add this info in the documentation. 
UPDATE
To make `SupportedTypes` appear in the documentation, I had to change the name of the attribute, I named it `AssignmentTypes`.
=> Add documentation for Layout/MultilineAssignmentLayout `SupportedTypes`

changelog/fix_incorrect_autocorrect_for_lint_deprecated_open_ssl_constant.md, lib/rubocop/cop/lint/deprecated_open_ssl_constant.rb, spec/rubocop/cop/lint/deprecated_open_ssl_constant_spec.rb
Fixes #9492.
This PR fixes an incorrect auto-correct for `Lint/DeprecatedOpenSSLConstant` when using no argument algorithm.
=> [Fix #9492] Fix an incorrect auto-correct for `Lint/DeprecatedOpenSSLConstant`

changelog/fix_an_error_for_style_explicit_block_argument.md, lib/rubocop/cop/style/explicit_block_argument.rb, spec/rubocop/cop/style/explicit_block_argument_spec.rb
Fixes #9497.
This PR fixes an error for `Style/ExplicitBlockArgument` when `yield` is inside block of `super`.
=> [Fix #9497] Fix an error for `Style/ExplicitBlockArgument`

changelog/fix_a_false_positive_for_layout_space_before_brackets.md, lib/rubocop/cop/layout/space_before_brackets.rb, spec/rubocop/cop/layout/space_before_brackets_spec.rb
Fixes #9499.
This PR fixes a false positive for `Layout/SpaceBeforeBrackets` when multiple spaces are inserted inside the left bracket.
=> [Fix #9499] Fix a false positive for `Layout/SpaceBeforeBrackets`

changelog/fix_an_error_for_lint_redundant_splat_expansion.md, lib/rubocop/cop/lint/redundant_splat_expansion.rb, spec/rubocop/cop/lint/redundant_splat_expansion_spec.rb
Fixes #9507.
This PR fixes an incorrect auto-correct for `Lint/RedundantSplatExpansion` when expanding `Array.new` call on method argument
=> [Fix #9507] Fix an incorrect auto-correct for `Lint/RedundantSplatExpansion`

lib/rubocop/cop/lint/duplicate_require.rb
Node pattern can use sets so this avoids an unnecessary join.
=> Slightly clean up the node pattern for `Lint/DuplicateRequire`.

lib/rubocop/cop/style/double_negation.rb
Fix a typo in `Style/DoubleNegation` correcting `nagation` to `negation`.
* [] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
=> Fix typo in Style/DoubleNegation, nagation => negation

changelog/new_add_new_gemspec_date_assignment_cop.md, config/default.yml, lib/rubocop.rb, lib/rubocop/cop/gemspec/date_assignment.rb, spec/rubocop/cli/cli_options_spec.rb, spec/rubocop/cop/gemspec/date_assignment_spec.rb
Follow https://github.com/rubocop-hq/rubocop-rails/issues/432.
This PR adds new `Gemspec/DateAssignment` cop.
This cop checks that `date =` is not used in gemspec file. It is set automatically when the gem is packaged.
```ruby
s.name = 'your_cool_gem'
spec.date = Time.now.strftime('%Y-%m-%d')
end
s.name = 'your_cool_gem'
end
```
RubyGems doesn't expect the value to be set.
https://github.com/rubygems/rubygems/blob/be08d8307eda3b61f0ec0460fe7fbcf647b526e6/lib/rubygems/specification.rb#L1679-L1681
=> Add new `Gemspec/DateAssignment` cop

changelog/fix_update_lintdebugger_so_that_only.md, config/default.yml, config/obsoletion.yml, lib/rubocop/cop/lint/debugger.rb, spec/rubocop/cop/lint/debugger_spec.rb
Prior to #8929, `Lint/Debugger` looked for a specific receiver/method pair, but that PR changed it so that any of the `DebuggerReceivers` would apply, *or also* no receiver. This caused regressions (#7636 and #9500, for instance) because method names specified as debugger by this cop would now register offenses when called with no receiver.
In order to fix it, I changed the configuration for `Lint/Debugger` a bit, but in a way that should not cause any major incompatibility. The allow list is now specified including its receiver so that the receiver can be checked. Existing configurations that just pass in a method name will be treated as expecting no receiver (there's a slight incompatibility there because previously `foo` would be matched by `Kernel.foo` but I think this is ok (and is …
=> [Fix #9500] Update `Lint/Debugger` so that only specific receivers for debug methods lead to offenses

changelog/fix_false_negative_for_lint_else_layout.md, lib/rubocop/cop/lint/else_layout.rb, spec/rubocop/cop/lint/else_layout_spec.rb
Regression by https://github.com/rubocop-hq/rubocop/commit/219dfe1.
This PR fixes a false negative for `Lint/ElseLayout` when using multiple `elsif`s.
@kakutani (w/ @asakusarb) Thank you for finding this false negative issue.
=> Fix a false negative for `Lint/ElseLayout`

CHANGELOG.md, changelog/new_add_autocorrect_for_styleevalwithlocation_cop.md, lib/rubocop/cop/style/eval_with_location.rb, spec/rubocop/cop/style/eval_with_location_spec.rb
Fix #9403 
- Add auto-correct to `Style/EvalWithLocation` cop for the following cases (along with unit tests to verify the corrections):
- File argument is incorrect
- Line argument is incorrect
- Line argument is missing
- Line and file arguments are missing
- Does not attempt to autocorrect if the method being called is `eval` and the binding argument is missing
=> [Fix #9403] Add autocorrect for `Style/EvalWithLocation`

changelog/fix_incorrect_autocorrect_for_hash_conversion.md, lib/rubocop/cop/style/hash_conversion.rb, spec/rubocop/cop/style/hash_conversion_spec.rb
Fixes #9513.
This PR fixes an incorrect auto-correct for `Style/HashConversion` when using hash argument `Hash[]`.
=> [Fix #9513] Fix an incorrect auto-correct for `Style/HashConversion`

changelog/fix_false_positive_for_lint_multiple_comparison.md, lib/rubocop/cop/lint/multiple_comparison.rb, spec/rubocop/cop/lint/multiple_comparison_spec.rb
Fixes #9349.
This PR fixes a false positive for `Lint/MultipleComparison` when using `&`, `|`, and `^` (DSL) set operation operators.
e.g. `Arel::Match`'s DSL methods.
https://github.com/rails/rails/blob/v6.1.1/activerecord/lib/arel/math.rb#L21-L23
I think that the cop can probably allow using these operators by default.
=> [Fix #9349] Fix a false positive for `Lint/MultipleComparison`

changelog/new_add_ignore_modules_to_constant_visibility_cop.md, config/default.yml, lib/rubocop/cop/style/constant_visibility.rb, spec/rubocop/cop/style/constant_visibility_spec.rb
To not register offense for module definitions.
Issue #8724
=> Add `IgnoreModules` configuration to `Style/ConstantVisibility`

changelog/change_improve_documentation_for_style_eval_with_location_cop.md, lib/rubocop/cop/style/eval_with_location.rb
This PR is to improve documentation for `Style/EvalWithLocation` cop.
There are no description and example for the case that a string variable is given as a code string like below.
```ruby
code = <<-RUBY
def do_something
end
RUBY
eval code
```
I added description and example to make this case clear.
=> Improve documentation for Style/EvalWithLocation cop

spec/rubocop/result_cache_spec.rb
I know this cop can be controversial, and maybe we don't want to *always* enforce its recommended style.
But in all three cases found in our spec suite, the mock (defined by `expect`) is entirely unnecessary - using a stub (with `allow`) is enough. If any of the stubs are changed, other expectations in each example will fail.
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING. …
=> Enable RSpec/StubbedMock

lib/rubocop/cop/lint/debugger.rb
The [Lint section of our documentation](https://docs.rubocop.org/rubocop/1.10/cops_lint.html#lintdebugger) is currently (as of v1.10.0) broken right in the middle of the `Lint/Debugger` section because of this code block which wasn't properly closed.
Problematic formatting was added in #9504.
=> Fix typo in documentation syntax

changelog/fix_error_for_style_trailing_method_end_statement.md, lib/rubocop/cop/style/trailing_method_end_statement.rb, spec/rubocop/cop/style/trailing_method_end_statement_spec.rb
Fixes #9523.
This PR fixes an error for `Style/TrailingMethodEndStatement`  when endless method definition signature and body are on different lines.
=> [Fix #9523] Fix an error for `Style/TrailingMethodEndStatement`

changelog/fix_incorrect_autocorrect_for_style_multiple_comparison.md, lib/rubocop/cop/style/multiple_comparison.rb, spec/rubocop/cop/style/multiple_comparison_spec.rb
Fixes #9520.
This PR fixes an incorrect auto-correct for `Style/MultipleComparison` when comparing a variable with multiple items in `if` and `elsif` conditions.
=> [Fix #9520] Fix an incorrect auto-correct for `Style/MultipleComparison`

changelog/fix_return_minimal_known_ruby_version_from.md, lib/rubocop/target_ruby.rb, spec/rubocop/target_ruby_spec.rb
Closes #9482 and #9329
The class to match `required_ruby_version` from `.gemspec` files could return invalid ruby versions. 
- This PR makes it so that it will only return a value from the `KNOWN_RUBIES` array. Specifically the minimal known ruby will be returned.
- The version parsing is also greatly improved by leveraging existing classes from the `Gem` library.
=> Required ruby version fixes

docs/modules/ROOT/pages/cops_lint.adoc
Fixed another typo in docs similar to:
https://github.com/rubocop-hq/rubocop/pull/9522
[Currently broken](https://docs.rubocop.org/rubocop/cops_lint.html#lintconstantresolution)
=> Fixed typo in docs part 2

changelog/change_add_allow_splat_argument_option_to_hash_conversion.md, config/default.yml, lib/rubocop/cop/style/hash_conversion.rb, spec/rubocop/cop/style/hash_conversion_spec.rb
Resolves #9526.
This PR add `AllowSplatArgument` option to `Style/HashConversion` and the option is true by default.
This is because `Hash[*ary]` is not allowed because it is strict.
As discussed in https://github.com/rubocop-hq/rubocop/pull/9478#discussion_r567259779, the correction code from `Hash[*arg]` is not simply determined. So, I think it's better to allow it by default as a simple notation.
On the other hand, there may be case where some users want to use the existing behavior, so this PR have made it optional.
=> [#9526] Add `AllowSplatArgument` option to `Style/HashConversion`

docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/duplicate_branch.rb
The second `IgnoreLiteralBranches` was probably supposed to be `IgnoreContentBranches` :)
=> Fix mislabelled example under Lint/DuplicateBranch

docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/endless_method.rb
A missing blank line was causing the list to be rendered like this:
```
The supported styles are: * allow_single_line (default) - only single line endless method definitions are allowed. * allow_always - all endless
```
=> Fix broken list in Style/EndlessMethod doc

spec/rubocop/cop/style/raise_args_spec.rb
The example when in addition to a custom exception instance initialized with an argument is passed to `raise` followed by a message.
See https://github.com/rubocop-hq/ruby-style-guide/issues/395#issuecomment-785172382
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.
=> Specify raise with a custom exception instance

changelog/new_add_allow_if_method_has_arguments_option_to_style_symbol_proc.md, config/default.yml, lib/rubocop/cop/style/symbol_proc.rb, spec/rubocop/cop/style/symbol_proc_spec.rb
Fixes #9525.
This PR adds `AllowIfMethodWithArguments` option to `Style/SymbolProc`.
```ruby
something.do_something(foo) { |o| o.bar }
something.do_something(foo, &:bar)
```
```ruby
something.do_something(foo) { |o| o.bar }
```
If user prefer a style that allows block for method with arguments, the user can set `true` to `AllowIfMethodWithArguments`.
It may be possible to consider defaulting to `AllowIfMethodWithArguments: true`, but at the time of this patch `Style/SymbolProc` cop respect keeping the existing behavior.
=> [Fix #9525] Add `AllowIfMethodWithArguments` option to `Style/SymbolProc`

changelog/fix_error_for_style_redundant_begin.md, lib/rubocop/cop/style/redundant_begin.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
Fixes #9539.
This PR fixes an error for `Style/RedundantBegin` when using body of `begin` is empty.
=> [Fix #9539] Fix an error for `Style/RedundantBegin`

changelog/fix_fix_stylehashconversion_when_the.md, lib/rubocop/cop/style/hash_conversion.rb, spec/rubocop/cop/style/hash_conversion_spec.rb
When the argument to `Hash[]` is a send node without parens, the `to_h` would be added to the wrong thing.
Fixes #9541.
=> [Fix #9541] Fix `Style/HashConversion` when the correction needs to be wrapped in parens

.circleci/config.yml
This PR pins the JRuby CI image to 9.2.14 to avoid the following error in JRuby 9.2.15.0:
```console
#!/bin/bash -eo pipefail
bundle exec rake internal_investigation
rake aborted!
LoadError: no such file to load -- racc/info
/usr/local/bundle/gems/parser-3.0.0.0/lib/parser.rb:12:in `<main>'
/usr/local/bundle/gems/rubocop-ast-1.4.1/lib/rubocop/ast.rb:3:in
`<main>'
/usr/local/bundle/gems/rubocop-ast-1.4.1/lib/rubocop-ast.rb:3:in
`<main>'
/home/circleci/project/lib/rubocop.rb:14:in `<main>'
tasks/cops_documentation.rake:4:in `<main>'
/home/circleci/project/Rakefile:21:in `block in <main>'
/home/circleci/project/Rakefile:21:in `<main>'
/opt/jruby/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
Exited with code exit status 1
CircleCI received exit code 1
``` …
=> Workaround for JRuby 9.2.15.0 regression

CHANGELOG.md, changelog/fix_fix_layoutfirstargumentindentation_for.md, lib/rubocop/cop/layout/first_argument_indentation.rb, spec/rubocop/cop/layout/first_argument_indentation_spec.rb
Continuation of #9538.
Operators were explicitly allowed by `Layout/FirstArgumentIndentation`, however when an operator method is called as a method (ie. not as a bare operator), the cop should still apply.
=> Fix `Layout/FirstArgumentIndentation` for operator methods not called as operators.

lib/rubocop/cop/internal_affairs/node_matcher_directive.rb, spec/rubocop/cop/internal_affairs/node_matcher_directive_spec.rb
This PR fixes the following error for `InternalAffairs/NodeMatcherDirective`.
```console
def_node_matcher :foo?, format(PATTERN, type: 'const')
% bundle exec rubocop --only InternalAffairs/NodeMatcherDirective -d
(snip)
Scanning
/Users/koic/src/github.com/koic/rubocop-issues/ia_cop/example.rb
An error occurred while InternalAffairs/NodeMatcherDirective cop was
inspecting
/Users/koic/src/github.com/koic/rubocop-issues/ia_cop/example.rb:1:0.
undefined method `value' for s(:send, nil, :format,
s(:const, nil, :PATTERN),
s(:hash,
s(:pair,
s(:sym, :type),
s(:str, "const")))):RuboCop::AST::SendNode
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/internal_affairs/node_matcher_directive.rb:100:in
`insert_directive' …
```
=> Fix an error for `InternalAffairs/NodeMatcherDirective`

changelog/fix_false_positive_for_style_trailing_body_on_method_definition.md, lib/rubocop/cop/style/trailing_body_on_method_definition.rb, spec/rubocop/cop/style/trailing_body_on_method_definition_spec.rb
This PR fixes a false positive for `Style/TrailingBodyOnMethodDefinition` when endless method definition body is after newline in opening parenthesis.
=> Fix a false positive for `Style/TrailingBodyOnMethodDefinition`

changelog/fix_make_metrics_length_cops_aware_of_multi_line_kwargs.md, lib/rubocop/cop/metrics/utils/code_length_calculator.rb, spec/rubocop/cop/metrics/utils/code_length_calculator_spec.rb
Fixes #9533.
This PR makes calculation of length of multiline hash argument with and without brace the same.
=> [Fix #9533] Fix calc of multiline hash arg length for metrics length cops

Gemfile, lib/rubocop/cop/mixin/preferred_delimiters.rb, lib/rubocop/cop/style/command_literal.rb, lib/rubocop/cop/style/regexp_literal.rb, spec/support/alignment_examples.rb
This PR bumps RuboCop Performance to 1.10 and suppresses the new `Performance/RedundantSplitRegexpArgument` cop's offenses.
```console
(snip)
Offenses:
lib/rubocop/cop/mixin/preferred_delimiters.rb:18:42: C: [Corrected]
Performance/RedundantSplitRegexpArgument: Use string as argument instead
of regexp.
preferred_delimiters[type].split(//)
^^
lib/rubocop/cop/mixin/preferred_delimiters.rb:18:42: C: [Corrected]
Style/StringLiterals: Prefer single-quoted strings when you don't need
string interpolation or special symbols.
preferred_delimiters[type].split("")
^^
lib/rubocop/cop/style/command_literal.rb:168:58: C: [Corrected]
Performance/RedundantSplitRegexpArgument: Use string as argument instead
of regexp.
(command_delimiter || default_delimiter).split(//)
^^ …
```
=> Bump RuboCop Performance to 1.10

changelog/fix_false_positive_for_style_unless_logical_operators.md, lib/rubocop/cop/style/unless_logical_operators.rb, spec/rubocop/cop/style/unless_logical_operators_spec.rb
Fixes #9551.
This PR fixes a false positive for `Style/UnlessLogicalOperators` when using `||` operator and invoked method name includes "or" in the conditional branch.
This is an issue due to string matching of source code instead of AST.
=> [Fix #9551] Fix a false positive for `Style/UnlessLogicalOperators`

changelog/new_added_allow_rescue_nil_config_to_suppressed_exception.md, config/default.yml, lib/rubocop/cop/lint/suppressed_exception.rb, spec/rubocop/cop/lint/suppressed_exception_spec.rb
Based off: https://github.com/rubocop/rubocop/pull/7297
Also the comment by @bbatsov https://github.com/rubocop/rubocop/pull/7297#issuecomment-523501395
> If some people disagree we can extend the existing behaviour with some config option, but I definitely imagine cases where a return value of nil might be the reasonable thing to do.
I personally have been bitten by explicit `rescue nil`s and would prefer to flag it. I've set `AllowRescueNil` to default to `true` so as not to break existing configurations. Setting it to false renders `rescue nil` and 
```
begin
do_something
rescue
nil
end
```
as offences.
=> Add rescue nil config to suppressed exceptions

lib/rubocop/cop/style/trailing_body_on_method_definition.rb
Follow https://github.com/rubocop/rubocop/pull/9548#issuecomment-787423830.
This PR adds example for `Style/TrailingBodyOnMethodDefinition` cop and removes a redundant condition from the cop. I noticed the redundant condition when writing the example description.
=> Add example for style trailing body on method definition

changelog/fix_comments_negated_if_else_condition_cop.md, lib/rubocop/cop/style/negated_if_else_condition.rb, spec/rubocop/cop/style/negated_if_else_condition_spec.rb
=> [Fix #9429] Fix `Style/NegatedIfElseCondition` autocorrect to keep comments in correct branch

changelog/fix_an_error_for_style_class_methods_definitions.md, lib/rubocop/cop/mixin/comments_help.rb, spec/rubocop/cop/style/class_methods_definitions_spec.rb
This PR fixes the following error for `Lint/ClassMethodsDefinitions` when defining class methods with `class << self` with comment only body.
```console
% cat /tmp/example.rb
class Foo
class << self
def do_something
end
end
end
% rubocop /tmp/example.rb --only Style/ClassMethodsDefinitions -d
For /private/tmp: Default configuration from
/Users/koic/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-1.11.0/config/default.yml
Scanning /private/tmp/example.rb
An error occurred while Style/ClassMethodsDefinitions cop was inspecting
/private/tmp/example.rb:2:2.
undefined method `gsub' for nil:NilClass
/Users/koic/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-1.11.0/lib/rubocop/cop/style/class_methods_definitions.rb:147:in `extract_def_from_sclass' …
```
=> Fix an error for `Style/ClassMethodsDefinitions`

lib/rubocop/cop/style/hash_syntax.rb, spec/rubocop/cop/team_spec.rb
Follow #7868.
This PR uses `Cop::Base` API for `Style/HashSyntax` cop.
=> Use `Cop::Base` API for `Style/HashSyntax`

docs/modules/ROOT/pages/integration_with_other_tools.adoc
Missed one instance of `rubocop-hq` in #9537.
=> Correct stray rubocop-hq reference.

docs/modules/ROOT/pages/cops_style.adoc, lib/rubocop/cop/style/redundant_self.rb
Fixes grammatical mistake in Style::RedundantSelf documentation by updating `an` to `a`.
=> Fix typo in Style::RedundantSelf documentation

lib/rubocop/comment_config.rb, lib/rubocop/cop/lint/redundant_cop_disable_directive.rb, lib/rubocop/cop/mixin/documentation_comment.rb, lib/rubocop/cop/mixin/line_length_help.rb, lib/rubocop/cop/style/disable_cops_within_source_code_directive.rb, lib/rubocop/directive_comment.rb, spec/rubocop/directive_comment_spec.rb
- Directive comment regexp and matching helper moved to DerectiveComment.
- Direct execution of private directive comment regexp replaced with matching helper from DerectiveComment.
- In other cases added `before_comment` and `single_line?` helpers to prevent direct execution of private directive comment regexp.
=> Move checking directive comments from CommentConfig to DirectiveComment 

spec/rubocop/comment_config_spec.rb
Added readability to CommentConfig spec source by replacing string joining with heredoc.
=> Add readability to CommentConfig spec source

spec/rubocop/comment_config_spec.rb
Added missing spec for CommentConfig#cop_disabled_line_ranges
=> Add spec for CommentConfig#cop_disabled_line_ranges

changelog/fix_fix_inconsistency_when_dealing_with_uris.md, lib/rubocop/cop/mixin/line_length_help.rb, spec/rubocop/cop/layout/line_length_spec.rb
The `LineLength` cop uses `LineLengthHelp#allowed_uri_position?` to determine if the URI is in an allowed position. Previously it checked that the URL either ended the line, or ended one character before the end of the line:
https://github.com/rubocop/rubocop/blob/291aec7f04775dbe8aaff0c6a2d7328aaca0427b/lib/rubocop/cop/mixin/line_length_help.rb#L26-L30
It looks like this was added originally in #5361... also to handle disparity between single and double quotes. 🤔 
As it turns out, ruby's default URI parser (which we use to match parts of strings as a URL), accepts `'` as a valid character, but does not accept `"`. It also matches `)`. Therefore, the URL extracted from the string differs depending on the type of quote being used:
```ruby
regexp = URI::DEFAULT_PARSER.make_regexp(['http', …
```
=> [Fix #9558] Fix inconsistency when dealing with URIs that are wrapped in single quotes vs double quotes

changelog/fix_incorrect_autocorrect_for_style_class_equality_comparison.md, lib/rubocop/cop/style/class_equality_comparison.rb, spec/rubocop/cop/style/class_equality_comparison_spec.rb
Fixes #9582.
This PR fixes incorrect auto-correct for `Style/ClassEqualityComparison` when comparing `Module#name` for equality.
=> [Fix #9582] Fix incorrect auto-correct for `Style/ClassEqualityComparison`

changelog/fix_update_naming_rescued_exceptions_variable_name.md, lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb, spec/rubocop/cop/naming/rescued_exceptions_variable_name_spec.rb
=> [Fix #9586] Update `Naming/RescuedExceptionsVariableName` to not register on inner rescues when nested.

lib/rubocop/cop/style/rescue_modifier.rb, spec/rubocop/cop/style/rescue_modifier_spec.rb, spec/rubocop/cop/team_spec.rb
Follow https://github.com/rubocop/rubocop/pull/7868.
This PR uses `Cop::Base` API for `Style/RescueModifier`. It uses `corrector.remove`, `corrector.before_insert`, and `corrector.after_insert` instead of `corrector.replace` to prevent `Parser::ClobberingError` when auto-correction.
This change degenerates the code indentation that auto-corrected for `foo rescue bar rescue baz`, but I think nested `rescue` is an edge case and is not a critical path as it can be auto-corrected with `Layout/IndentationWidth` cop.
=> Use `Cop::Base` API for `Style/RescueModifier`

changelog/fix_an_error_when_processing_dir_is_named_empty_braces.md, lib/rubocop/target_finder.rb, spec/rubocop/target_finder_spec.rb
Fixes #9593.
This PR fixes the following error when processing a directory is named `{}`.
```console
% mkdir {}
% rubocop
(snip)
File name too long - /tmp//////////////////////////////////////////////...
```
=> [Fix #9593] Fix an error when processing a directory is named `{}`

spec/rubocop/comment_config_spec.rb
- Added spec for CommentConfig#comment_only_line?
- Also fixed typo in another spec
=> Add spec for CommentConfig#comment_only_line?

.circleci/config.yml, spec/rubocop/cli/options_spec.rb
This PR reverts workaround #9545 and https://github.com/rubocop/rubocop/pull/9347/commits/d0c8ae60c608ffcb6b73b31bf32411033c56e5ae.
@headius Thanks for solving these issue and releasing JRuby 9.2.16.0!
=> CI against latest stable version of JRuby (9.2.16.0)

changelog/fix_fix_valid_shareable_constant_value.md, lib/rubocop/magic_comment.rb, spec/rubocop/magic_comment_spec.rb
This PR fixes a tiny bug infected since https://github.com/rubocop/rubocop/pull/9412.
But I guess It breaks to the surface yet, because RuboCop does not have `shareable_constant_value` related cop yet.
=> Fix RuboCop::MagicComment#valid_shareable_constant_value?

changelog/fix_error_for_style_case_like_if.md, lib/rubocop/cop/style/case_like_if.rb, spec/rubocop/cop/style/case_like_if_spec.rb
Fixes #9599.
This PR fixes an error for `Style/CaseLikeIf` when using `include?` without a receiver.
=> [Fix #9599] Fix an error for `Style/CaseLikeIf`

changelog/change_make_style_redundant_begin_aware_of_memoization.md, lib/rubocop/cop/mixin/uncommunicative_name.rb, lib/rubocop/cop/style/redundant_begin.rb, lib/rubocop/ext/regexp_parser.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
Fixes #9601.
This PR makes `Style/RedundantBegin` aware of redundant `begin`/`end` blocks around memoization.
=> [Fix #9601] Make `Style/RedundantBegin` aware of `begin` blocks around memoization

changelog/fix_false_positive_for_style_sole_nested_conditional.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
Fixes #9603.
This PR fixes a false positive for `Style/SoleNestedConditional` when using nested modifier on value assigned in condition.
=> [Fix #9603] Fix a false positive for `Style/SoleNestedConditional`

changelog/new_allow_excluding_some_constants_from.md, config/default.yml, lib/rubocop/cop/style/documentation.rb, spec/rubocop/cli/auto_gen_config_spec.rb, spec/rubocop/cop/style/documentation_spec.rb
For example, a very common idiom is to define a ClassMethods module that
contains the class methods created by the parent module. In such cases,
it might be desired to document the parent module, but not the
ClassMethods module.
=> Allow excluding some constants from Style/Documentation

changelog/fix_error_for_layout_indentation_consistency.md, lib/rubocop/cop/layout/indentation_consistency.rb, spec/rubocop/cop/layout/indentation_consistency_spec.rb
Fixes #9606.
This PR fixes the following error for `Layout/IndentationConsistency` when using access modifier at the top level.
```console
public
def foo
end
% bundle exec rubocop --only Layout/IndentationConsistency example.rb -d
(snip)
Scanning /Users/koic/src/github.com/koic/rubocop-issues/9606/example.rb
An error occurred while Layout/IndentationConsistency cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/9606/example.rb:1:0.
undefined method `source_range' for nil:NilClass
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/layout/indentation_consistency.rb:165:in
`base_column_for_normal_style'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/layout/indentation_consistency.rb:181:in
`check_normal_style' …
```
=> [Fix #9606] Fix an error for `Layout/IndentationConsistency`

lib/rubocop/comment_config.rb, lib/rubocop/directive_comment.rb, spec/rubocop/directive_comment_spec.rb
- CommentConfig#directive_parts replaced  with DirectiveComment instance.
- Further we're going to continue moving part of responsibility to DirectiveComment
=> Replace CommentConfig#directive_parts with DirectiveComment instance

changelog/fix_incorrect_autocorrect_for_style_eval_with_location.md, lib/rubocop/cop/style/eval_with_location.rb, spec/rubocop/cop/style/eval_with_location_spec.rb
Fixes https://github.com/testdouble/standard/issues/275.
This PR fixes the following incorrect auto-correct for `Style/EvalWithLocation` when using `#instance_eval` with a string argument in parentheses.
```console
instance_eval('@foo = foo')
% rubocop -A --only Style/EvalWithLocation
(snip)
C
Offenses:
example.rb:1:1: C: [Corrected] Style/EvalWithLocation: Pass __FILE__ and
__LINE__ to instance_eval.
instance_eval('@foo = foo')
^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
```console
instance_eval('@foo = foo'), __FILE__, __LINE__
example.rb:1: syntax error, unexpected ',', expecting end-of-input
instance_eval('@foo = foo'), __FILE__, __LINE__
```
```console
% cat …
```
=> Fix an incorrect auto-correct for `Style/EvalWithLocation`

changelog/change_disable_suggested_extensions_when_using.md, lib/rubocop/cli/command/suggest_extensions.rb, spec/rubocop/cli_spec.rb
=> [Fix #9617] Disable suggested extensions when using the `--stdin` option

changelog/fix_false_positive_for_style_redundant_self_cop.md, lib/rubocop/cop/style/redundant_self.rb, spec/rubocop/cop/style/redundant_self_spec.rb
Fixes #9613.
This PR fixes a false positive for `Style/RedundantSelf` when a self receiver on an lvalue of mlhs arguments.
=> [Fix #9613] Fix a false positive for `Style/RedundantSelf`

changelog/fix_fix_infinite_loop_between.md, lib/rubocop/cop/layout/indentation_width.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/layout/indentation_width_spec.rb, spec/rubocop/cop/layout/rescue_ensure_alignment_spec.rb
There was an autocorrect infinite loop between `Layout/IndentationWidth` and `Layout/RescueEnsureAlignment`, as well as a false positive, for actually correct cases such as
```ruby
def a
rescue StandardError
ensure
a
end
```
due to `Layout/IndentationWidth` getting confused by there being no body before the rescue. It will now only check indentation of a rescue node if it has a body.
I also added a test to make sure the two cops autocorrect properly when used in unison.
Fixes testdouble/standard#112.
=> Fix infinite loop between `Layout/IndentationWidth` and `Layout/RescueEnsureAlignment` autocorrection

changelog/fix_an_incorrect_autocorrect_for_style_struct_inheritance.md, lib/rubocop/cop/style/struct_inheritance.rb, spec/rubocop/cop/style/struct_inheritance_spec.rb
Fixes #9627.
This PR fixes an incorrect auto-correct for `Style/StructInheritance` when extending instance of Struct without `do` ... `end` and class body is empty.
=> [Fix #9627] Fix an incorrect auto-correct for `Style/StructInheritance`

changelog/fix_allow_parentheses_in_yield_arguments_with_style_method_call_with_args_parentheses.md, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
When using the `omit_parentheses` style, we don't recognize `yield`
argument calls and require parentheses omission. If we yield multiple
values, we cannot omit the parentheses in method calls as this won't be
valid Ruby. We currently register offenses for:
```ruby
yield File.basename(path)
^^^^^^^^^^^^^^^^^^^ Omit parentheses for method calls with arguments.
yield File.basename path # 👈 This compiles.
yield path, File.basename(path)
^^^^^^^^^^^^^^^^^^^ Omit parentheses for method calls with arguments.
yield path, File.basename path  # 👈 This DOES NOT!!!
```
If we treat yield arguments as any other method call arguments, we'll
allow the parentheses and let people write valid Ruby in the cases
above.
=> Allow parentheses in yield arguments for `Style/MethodCallWithArgsParentheses`

changelog/new_add_allow_parentheses_in_string_interpolation_config_to_style_method_call_with_args_parentheses.md, config/default.yml, lib/rubocop/cop/style/method_call_with_args_parentheses.rb, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
If we are calling methods in string interpolation with the `omit_parentheses`
style for the `Style/MethodCallWithArgsParentheses` cop, they are
currently forced to be without parentheses:
```ruby
"#{part 1}, #{part 2}, #{part 3}"
```
My coworkers at Dext want to be able to put spaces while calling methods
in interpolation, and I don't blame them. Having spaces reduces the
noise of following a method call in a string, especially if the string
happens to have multiple interpolations in it.
I want to add the `AllowParenthesesInStringInterpolation` cop configuration
that allows the use of parentheses in string interpolation calls.
```ruby
"#{part(1)}, #{part(2)}, #{part(3)}"
```
=> Calls with braces in interpolation for `Style/MethodCallWithArgsParentheses`

lib/rubocop/cop/registry.rb, spec/rubocop/cop/registry_spec.rb
Part of https://github.com/rubocop/rubocop/issues/9519
- Added department check to Registry
- Added names for department to Registry
=> Add department checking to Registry

changelog/fix_false_positive_for_style_redundant_return.md, lib/rubocop/cop/style/redundant_return.rb, spec/rubocop/cop/style/redundant_return_spec.rb
Fixes https://github.com/testdouble/standard/issues/277.
This PR fixes the following false positive for `Style/RedundantReturn` when using `return` with splat argument.
```console
class MyClass
def something
data = [1, 2, 3]
return *data
end
end
```
Auto-corrected to invalid code.
```console
% rubocop --only Style/RedundantReturn -a
(snip)
class MyClass
def something
data = [1, 2, 3]
*data
end
end
example.rb:4: syntax error, unexpected '\n', expecting '='
```
Auto-corrected to valid code.
```console
% rubocop --only Style/RedundantReturn -a
(snip)
class MyClass
def something
data = [1, 2, 3]
data
end
end
Syntax OK
``` …
=> Fix an incorrect auto-correct for `Style/RedundantReturn`

config/default.yml, lib/rubocop/cop/lint/symbol_conversion.rb, spec/rubocop/cop/lint/symbol_conversion_spec.rb
The `consistent` style works the same as the previous default style (now called `strict`), in that symbol conversions should be explicit. However, in the case of a hash with a mix of symbol keys requiring quoting and not, this style now enforces that all keys are quoted for consistency.
Fixes #9621.
=> [Fix #9621] Add `consistent` style to `Lint/SymbolConversion` to require all symbol keys in a hash to use the same convention

lib/rubocop/comment_config.rb, lib/rubocop/directive_comment.rb, spec/rubocop/directive_comment_spec.rb
Last part of https://github.com/rubocop/rubocop/issues/9563
- Refactored CommentConfig
- Extra logic moved to DirectiveComment
=> [Fix #9563] Refactor CommentConfig

changelog/fix_incorrect_autocorrect_for_lint_number_conversion.md, lib/rubocop/cop/lint/number_conversion.rb, spec/rubocop/cop/lint/number_conversion_spec.rb
For example, the following auto-correction test code is invalid syntax:
```ruby
"1,2,3,foo,5,6,7,8".split(',').map({ |i| Integer(i, 10) })
```
This PR removes invalid parentheses and auto-corrects it to valid syntax:
```ruby
"1,2,3,foo,5,6,7,8".split(',').map { |i| Integer(i, 10) }
```
=> Fix an incorrect auto-correct for `Lint/NumberConversion`

changelog/fix_a_false_positive_for_style_access_modifier_declarations.md, lib/rubocop/cop/style/access_modifier_declarations.rb, spec/rubocop/cop/style/access_modifier_declarations_spec.rb
Fixes #5953.
This PR fixes a false positive for `Style/AccessModifierDeclarations` when using `module_function` with symbol.
=> [Fix #5953] Fix a false positive for `Style/AccessModifierDeclarations`

changelog/fix_fixed_stylebisectedattraccessor.md, lib/rubocop/cop/style/bisected_attr_accessor.rb, lib/rubocop/cop/style/bisected_attr_accessor/macro.rb, spec/rubocop/cop/style/bisected_attr_accessor_spec.rb
This ended up being a pretty heavy refactor of the `Style/BisectedAttrAccessor` cop.
Previously we were doing multiple passes at determining what macros are relevant for the cop, and which names within them. Despite that, if a macro had multiple names and was rewritten, we'd lose context of what other names there were and only the first one would survive the autocorrection.
Instead, I have now extracted a `Macro` value object that encapsulates all the data for the macro, including visibility (since macros of different visibilities are not combined), bisected and non-bisected attribute names, etc. When investigating a class, any macros found have objects created, and they are retained to be used to correct the class as a whole after wards (but we still register offenses on individual macro …
=> [Fix #9622] Fixed `Style/BisectedAttrAccessor` autocorrection to handle multiple bisected attrs in the same macro

changelog/fix_false_positive_for_layout_empty_line_after_guard_clause.md, lib/rubocop/cop/layout/empty_line_after_guard_clause.rb, lib/rubocop/directive_comment.rb, spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb, spec/rubocop/directive_comment_spec.rb
Fixes #9608.
This PR fixes a false positive for `Layout/EmptyLineAfterGuardClause` when using guard clause is after `rubocop:enable` comment.
=> [Fix #9608] Fix a false positive for `Layout/EmptyLineAfterGuardClause`

changelog/fix_error_for_layout_line_length.md, lib/rubocop/cop/mixin/check_line_breakable.rb, spec/rubocop/cop/layout/line_length_spec.rb
This PR fixes the following infinite loop error for `Layout/LineLength` when over limit at right hand side of multiple assignment.
```console
Layout/LineLength:
Max: 40
a = fooooooooooooooooooooooooooooooooooooo, b
% bundle exec rubocop --only Layout/LineLength -a
(snip)
0 files inspected, 200 offenses detected, 200 offenses corrected
Infinite loop detected in /tmp/example.rb and caused by Layout/LineLength
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/runner.rb:290:in
`block in iterate_until_no_changes'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/runner.rb:286:in
`loop'
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/runner.rb:286:in
`iterate_until_no_changes'
``` …
=> Fix an error for `Layout/LineLength`

changelog/fix_fix_layoutmultilinemethodcallindentation.md, lib/rubocop/cop/layout/multiline_method_call_indentation.rb, lib/rubocop/cop/layout/multiline_operation_indentation.rb, lib/rubocop/cop/mixin/multiline_expression_indentation.rb, spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb, spec/rubocop/cop/layout/multiline_operation_indentation_spec.rb
`MultilineExpressionIndentation#right_hand_side`, which is used by both `Layout/MultilineMethodCallIndentation` and `Layout/MultilineOperationIndentation` was not correctly calculating the RHS when the send node looks like an operator but has a receiver (ie. `foo.&`). This was leading to an autocorrection loop with `Layout/ArgumentAlignment`, `Layout/ClosingParenthesisIndentation` and `Layout/FirstArgumentIndentation`.
I split out the `right_hand_side` method to be defined in each of the two cops so that the right behaviour can be in place for each cop.
Fixes #9641.
=> [Fix #9641] Fix `Layout/MultilineMethodCallIndentation` triggering on method calls that look like operators

changelog/fix_error_for_style_multiline_method_signature.md, lib/rubocop/cop/style/multiline_method_signature.rb, spec/rubocop/cop/style/multiline_method_signature_spec.rb
This PR fixes the following error and the incorrect auto-correct for `Style/MultilineMethodSignature` when line break after opening parenthesis.
```ruby
class Foo
def foo(
arg
)
end
end
```
```console
% rubocop -a --only Style/MultilineMethodSignature example.rb
(snip)
C
Offenses:
example.rb:2:3: C: [Corrected] Style/MultilineMethodSignature: Avoid
multi-line method signatures.
def foo( ...
^^^^^^^^
Infinite loop detected in /private/tmp/example.rb and caused by Style/MultilineMethodSignature
/Users/koic/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-1.12.0/lib/rubocop/runner.rb:304:in
`check_for_infinite_loop'
/Users/koic/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-1.12.0/lib/r …
```
=> Fix an error for `Style/MultilineMethodSignature`

changelog/fix_style_redundant_being_removing_comments_on_assignment_statement_correction.md, lib/rubocop/cop/style/redundant_begin.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
`Style/RedundantBegin` cop currently removes comments that occur
before the first child node of the `begin` block. This happens
because comments are skipped when navigating the node tree.
Currently,
```ruby
var ||= begin
foo
end
```
will correct to
```ruby
var ||= foo
```
This PR changes that correction to
```ruby
var ||= foo
```
Other comments in the vicinity (before and after `begin/end` block,
and after first child node) are still preserved, as they
already were before this change.
=> Fix `Style/RedundantBegin` removing comments on assignment statement correction

changelog/fix_incorrect_autocorrect_for_style_single_line_methods.md, lib/rubocop/cop/style/single_line_methods.rb, spec/rubocop/cop/style/single_line_methods_spec.rb
Fix the following incorrect auto-correct for `Style/SingleLineMethods` when using single line class method definition.
```console
def self.some_method; body end
% rubocop --only Style/SingleLineMethods -a
(snip)
Offenses:
example.rb:1:1: C: [Corrected] Style/SingleLineMethods: Avoid
single-line method definitions.
def self.some_method; body end
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
```console
def some_method() = body
```
`self` is lost due to auto-correction.
```console
def self.some_method() = body
```
=> Fix an incorrect auto-correct for `Style/SingleLineMethods`

changelog/fix_when_highlights_contain_multibyte_characters.md, lib/rubocop/formatter/clang_style_formatter.rb, lib/rubocop/formatter/tap_formatter.rb, spec/rubocop/formatter/clang_style_formatter_spec.rb, spec/rubocop/formatter/tap_formatter_spec.rb
When multibyte characters were included in the output results, they were not highlighted in the correct position.
* I'd like to see multibyte characters highlighted by their position
```
hash.rb:4:3: C: [Correctable] Layout/HashAlignment: Align the keys of a hash literal if they span more than one line.
'あああああ'=>1,
^^^^^^^^^^^^^^^
hash.rb:4:10: C: [Correctable] Layout/SpaceAroundOperators: Surrounding space missing for operator =>.
'あああああ'=>1,
^^
hash.rb:5:14: C: [Correctable] Layout/SpaceAfterComma: Space missing after comma.
'いいいい' => 2,"うううう" =>3,
^
hash.rb:5:15: C: [Correctable] Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
'いいいい' => 2,"うううう" =>3,
^^^^^^^^^^
hash.rb:5:22: C: [Correctable] Layout/SpaceAroundOperators: …
```
=> Fix when highlights contain multibyte characters

changelog/fix_incorrect_autocorrect_for_style_and_or.md, lib/rubocop/cop/style/and_or.rb, spec/rubocop/cli/autocorrect_spec.rb
This PR fixes the following incorrect auto-correct for `EnforcedStyle: require_parentheses` of `Style/MethodCallWithArgsParentheses` with `EnforcedStyle: conditionals` of `Style/AndOr`.
```console
if foo and bar :arg
end
% rubocop --only Style/AndOr,Style/MethodCallWithArgsParentheses -a
(snip)
Offenses:
example.rb:1:8: C: [Corrected] Style/AndOr: Use && instead of and.
if foo and bar :arg
^^^
example.rb:1:12: C: [Corrected] Style/MethodCallWithArgsParentheses: Use
parentheses for method calls with arguments.
if foo and bar :arg
^^^^^^^^
1 file inspected, 2 offenses detected, 2 offenses corrected
```
```console
if foo && bar(:arg))
end
example.rb:1: syntax error, unexpected ')', expecting `then' or ';' or '\n'
if foo && bar(:arg))
``` …
=> Fix an incorrect auto-correct for `Style/AndOr`

changelog/fix_incorrect_autocorrect_for_ambiguous_operator.md, lib/rubocop/cop/util.rb, spec/rubocop/cli/autocorrect_spec.rb
This PR fixes the following incorrect auto-correct for `Style/MethodCallWithArgsParentheses` with `Lint/AmbiguousOperator`.
```console
def foo(&block)
do_something &block
end
% rubocop --only Style/MethodCallWithArgsParentheses,Lint/AmbiguousOperator -a
Inspecting 4 files
..WC
Offenses:
example.rb:2:3: C: [Corrected] Style/MethodCallWithArgsParentheses: Use
parentheses for method calls with arguments.
do_something &block
example.rb:2:16: W: [Corrected] Lint/AmbiguousOperator: Ambiguous block
operator. Parenthesize the method arguments if it's surely a block
operator, or add a whitespace to the right of the & if it should be a
binary AND.
do_something &block
^
ripper/example.rb:6:5: C: [Corrected]
Style/MethodCallWithArgsParentheses: Use parentheses for …
```
=> Fix an incorrect auto-correct for `Lint/AmbiguousOperator`

changelog/fix_incorrect_autocorrect_for_style_hash_conversion.md, lib/rubocop/cop/style/hash_conversion.rb, spec/rubocop/cop/style/hash_conversion_spec.rb
Fixes #9672.
This PR fixes an incorrect auto-correct for `Style/HashConversion` when using  multi-argument `Hash[]` as a method argument.
=> [Fix #9672] Fix an incorrect auto-correct for `Style/HashConversion`

spec/spec_helper.rb
I stumbled upon this while looking into some info on rspec's `shared_context`. I don't fully follow the implications of the change. Reading the info from the commit, I was expecting to need to change some areas of context inclusion. 
https://relishapp.com/rspec/rspec-core/docs/example-groups/shared-context
https://github.com/rspec/rspec-core/commit/ed2d59c8a97d32f4a20e91d0abdad87f90d2b930
=> Configure rspec shared_context_metadata_behavior to :apply_to_host_groups (compatibility for rspec 4)

changelog/fix_parentheses_in_forwarded_args_for_style_method_call_with_args_parentheses.md, lib/rubocop/cop/style/method_call_with_args_parentheses.rb, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
The new-style arguments delegation included in Ruby 2.7 and expanded in
Ruby 3.0 is required to be parenthesized, since the syntax is clashing with the
endless `start...` range, which can be started with `start ...` as well. Currently,
the most iffy cop of them all is issuing offenses for:
```ruby
def delegated_call(...)
@proxy.call(...)
^^^^^ Omit parentheses for method calls with arguments.
end
```
Removing the parens will  start an endless range with the beginning being the
result of the method call without arguments. See the parse trees below for more
details:
```bash
-> ruby-parse -e "def foo(...); bar(...); end"
(def :foo
(args
(forward-arg))
(send nil :bar
(forwarded-args)))
-> ruby-parse -e "def foo(...); bar ...; end"
(def :foo
(args
(forward-arg))
(erange
(send nil :bar) nil)) …
```
=> Parenthesized forwarded args in `Style/MethodCallWithArgsParentheses` `omit_parentheses`

changelog/fix_an_error_for_style_string_chars.md, lib/rubocop/cop/style/string_chars.rb, spec/rubocop/cop/style/string_chars_spec.rb
Fixes #9676.
This PR fixes an error for `Style/StringChars` when using `split` without parentheses.
=> [Fix #9676] Fix an error for `Style/StringChars`

changelog/fix_incorrect_autocorrect_for_style_redundant_begin.md, lib/rubocop/cop/style/redundant_begin.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
Fixes #9681.
This PR fixes an incorrect auto-correct for `Style/RedundantBegin` when using modifier `if` single statement in `begin`.
=> [Fix #9681] Fix an incorrect auto-correct for `Style/RedundantBegin`

.rubocop.yml, CHANGELOG.md, config/default.yml, lib/rubocop/cop/layout/redundant_line_break.rb, spec/rubocop/cop/layout/redundant_line_break_spec.rb
Set the default value for this new configuration option to `false`, since we suspect that many users might consider the `do`..`end` variant with line breaks more readable.
For RuboCop's own sources we set it to `true`, i.e., the same behavior as before the parameters existed, at least for now.
=> [Fix #9691] Add configuration option InspectBlocks to RedundantLineBreak

changelog/fix_incorrect_autocorrect_for_if_unless_modifier.md, lib/rubocop/cop/style/if_unless_modifier.rb, spec/rubocop/cop/style/if_unless_modifier_spec.rb
This PR fixes the following incorrect auto-correct for `Style/IfUnlessModifier` when using a method with heredoc argument.
```console
Layout/LineLength:
Max: 80
fooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo(<<~EOS) if condition
string
EOS
% bundle exec rubocop --only Style/IfUnlessModifier -a
(snip)
C
Offenses:
example.rb:1:70: C: [Corrected] Style/IfUnlessModifier: Modifier form of
if makes the line too long.
fooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo(<<~EOS) if condition
^^
```
Auto-corrected to unexpected invalid syntax code.
```console
if condition
fooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo(<<~EOS)
end …
```
=> Fix an incorrect auto-correct for `Style/IfUnlessModifier`

changelog/new_bundler_gem_comment_limiting_version_specifications.md, lib/rubocop/cop/bundler/gem_comment.rb, spec/rubocop/cop/bundler/gem_comment_spec.rb
The problem I'm trying to solve:
There are multiple reasons one might lock the version of a gem in the Gemfile:
1. When a minimum version of the gem is needed to support the project. (Like `">= 2.0"`.)
2. When a specific version of the gem has a known bug. (Should be done like `"!= 2.4.0"`.)
3. When a major version of the gem is incompatible with the project. (Usually looks like `"< 3.0"`.)
4. For no reason. Some gems even provide instructions like "add `gem 'mygem', '~> 2.3'` to your Gemfile".
The last two reasons lead to a project's dependencies falling behind because the `bundle update` process will not update to 3.0 without manual intervention. This would cause dependencies to continue to fall behind and in some cases even limit other non-locked dependencies because of …
=> Add restrictive_version_specifiers to Bundler/GemComment

changelog/fix_incorrect_autocorrect_for_style_hash_conversion.md, lib/rubocop/cop/style/hash_conversion.rb, spec/rubocop/cop/style/hash_conversion_spec.rb
Fixes #9683.
This PR fixes an incorrect auto-correct for `Style/HashConversion` when using `zip` method in `Hash[]`.
=> [Fix #9683] Fix an incorrect auto-correct for `Style/HashConversion`

.rubocop.yml, lib/rubocop/cop/layout/end_of_line.rb, lib/rubocop/cop/metrics/utils/abc_size_calculator.rb, lib/rubocop/cop/style/combinable_loops.rb, lib/rubocop/cop/style/redundant_self_assignment.rb
This PR sets false for `SafeMultiline` for `Performance/StartWith` and `Performance/EndWith` to .rubocop.yml in this rubocop/rubocop repository.
It is because multiline regular expression matching that corresponds to `start_with?` and `end_with?` are not used in the repository.
=> Set false to `SafeMultiline` for `Performance/StartWith` and `Performance/EndWith`

changelog/new_ignored_methods_options_for_lint_ambiguous_block_association.md, config/default.yml, docs/modules/ROOT/pages/cops_lint.adoc, lib/rubocop/cop/lint/ambiguous_block_association.rb, spec/rubocop/cop/lint/ambiguous_block_association_spec.rb
This PR adds support for `IgnoredMethods` parameter in `Lint/AmbiguousBlockAssociation` cop to allow better DSL support.
It fixes #9684 and is also related with #7486.
=> [Fix #9684] Support `IgnoredMethods` option for `Lint/AmbiguousBlockAssociation`

changelog/change_auto_disable_parallel.md, lib/rubocop/options.rb, lib/rubocop/rake_task.rb, spec/rubocop/options_spec.rb
This came up in a conversation in https://github.com/rubocop/rubocop/pull/9640. We probably should have made it work this way from the start instead of raising an exception.
It felt a big weird to handle this inside of a "validation". Please let me know if there is a better place for the code or if there is better error message.
I left in the code to delete the parallel flag from the rake task to avoid printing the warning about parallel being ignored.
=> Auto disable parallel when combined with --auto-correct, --auto-gen-config, or --fail-fast

changelog/fix_an_error_for_style_struct_inheritance.md, lib/rubocop/cop/style/struct_inheritance.rb, spec/rubocop/cop/style/struct_inheritance_spec.rb
Fixes #9698.
This PR fixes an error for `Style/StructInheritance` when extending instance of `Struct` without `do` ... `end` and class body is empty and single line definition.
=> [Fix #9698] Fix an error for `Style/StructInheritance`

changelog/fix_have_styleredundantargument_use_correct.md, lib/rubocop/cop/base.rb, lib/rubocop/cop/cop.rb, lib/rubocop/cop/style/redundant_argument.rb
The culprit was actually a Cop that was doing a `require 'parser/current'` that was avoidable and not actually the best thing to do.
=> Avoid parser warning

.rubocop.yml
Following up on the discussion in #9678, this PR only removes one line of configuration for RuboCop itself.
Change the setting for internal inspections so that the `Layout/RedundantLineBreak` cop does not report multiline blocks. The opinion of the core team seems to lean towards allowing `do ... end` blocks when the author feels it's more readable than a single line block with braces.
This commit does not revert any previous changes. That should be done later on case-by-case basis if desired.
=> Change RedundantLineBreak: InspectBlocks to false internally

lib/rubocop/cop/style/single_line_methods.rb, spec/rubocop/cop/style/single_line_methods_spec.rb
This PR fixes the following error for `Style/SingleLineMethods`.
```console
% cat  example.rb
def some_method; 42 end
% bundle exec rubocop --only Style/SingleLineMethods -d
(snip)
undefined method `arguments' for s(:int, 42):RuboCop::AST::IntNode
Did you mean?  argument?
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/cop/style/single_line_methods.rb:118:in `method_body_source'
```
This is a regression of #9704.
=> Fix an error for `Style/SingleLineMethods`

changelog/fix_fix_false_positive_for.md, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
=> [Fix #9707] Fix false positive for `Style/MethodCallWithArgsParentheses` with `omit_parentheses` style on an endless `defs` node

CHANGELOG.md, lib/rubocop/config_loader_resolver.rb, spec/rubocop/config_loader_spec.rb
For configuration files whose name begins with `.rubocop`, the paths in `Include` parameters are relative to the directory of the configuration file.
When another configuration file inherits from such a file, we cannot just copy the `Include` paths. We must modify them so they select the files that were originally intended.
=> [Fix #5576] Treat relativity of Include parameters correctly

changelog/fix_treat_parens_around_array_items_the_same.md, lib/rubocop/cop/style/redundant_parentheses.rb, spec/rubocop/cop/style/redundant_parentheses_spec.rb
Previously there was a disparity between these two code blocks:
```ruby
[
(
1
),
2
]
```
```ruby
[
x = (
1
),
y = 2
]
```
The first was accepted as "plausible" but the second registered an offense (and was autocorrected to a syntax error because the comma in an array cannot be on its own line).
This change allows both to be treated the same by looking for any ancestor to be an array or hash rather than just the direct parent.
=> [Fix #9689] Treat parens around array items the same for children and deeper descendants

changelog/fix_an_incorrect_autocorrect_for_style_hash_conversion.md, lib/rubocop/cop/style/hash_conversion.rb, spec/rubocop/cop/style/hash_conversion_spec.rb
This PR fixes the following incorrect auto-correct for `Style/HashConversion` when `Hash[]` as a method argument without parentheses.
```console
do_something Hash[a: b, c: d], 42
% bundle exec rubocop --only Style/HashConversion -a
(snip)
C
Offenses:
example.rb:1:14: C: [Corrected] Style/HashConversion: Prefer literal
hash to Hash[key: value, ...].
do_something Hash[a: b, c: d], 42
^^^^^^^^^^^^^^^^
```
Auto-corrected to invalid syntax.
```ruby
do_something {a: b, c: d}, 42
example.rb:1: syntax error, unexpected ':', expecting '}'
do_something {a: b, c: d}, 42
```
Auto-corrected to valid syntax.
```ruby
do_something({a: b, c: d}, 42)
``` …
=> Fix an incorrect auto-correct for `Style/HashConversion`

CHANGELOG.md, changelog/fix_resolve_symlinks_when_excluding_directories.md, lib/rubocop/target_finder.rb, spec/rubocop/target_finder_spec.rb, spec/support/file_helper.rb
Resolve symlinks when excluding directories, i.e. if `foo/**/*` is present in the Exclude list and there is a `bar` symlink pointing to `foo`, files under `bar` will be properly excluded.
Fixes #9636.
=> [Fix #9636] Resolve symlinks when excluding directories

changelog/change_add_no_parallel_option.md, lib/rubocop/options.rb, spec/rubocop/options_spec.rb
Fix #7544
We just discovered --parallel and added it to our .rubocop file. Turns out you can't use it with -a.
We would like to leave --parallel in our .rubocop file but would occasionally like to use -a. So we would like a --no-parallel flag to override our default - so we can do
rubocop --no-parallel -a
Note that master failed `bundle exec rake default`
=> --no-parallel (-P/--parallel can not be combined with --auto-correct)

changelog/fix_incorrect_autocorrect_for_style_method_call_with_args_parentheses.md, lib/rubocop/cop/style/method_call_with_args_parentheses.rb, lib/rubocop/cop/style/rescue_modifier.rb, spec/rubocop/cli/autocorrect_spec.rb
This PR fixes the following incorrect auto-correct for `Style/MethodCallWithArgsParentheses` with `Style/RescueModifier`.
```console
do_something arg rescue nil
% bundle exec rubocop -a --only
Style/MethodCallWithArgsParentheses,Style/RescueModifier
(snip)
C
Offenses:
example.rb:1:1: C: [Corrected] Style/MethodCallWithArgsParentheses: Use
parentheses for method calls with arguments.
do_something arg rescue nil
^^^^^^^^^^^^^^^^
example.rb:1:1: C: [Corrected] Style/RescueModifier: Avoid using rescue
in its modifier form.
do_something arg rescue nil
^^^^^^^^^^^^^^^^^^^^^^^^^^^
1 file inspected, 2 offenses detected, 2 offenses corrected
```
Auto-corrected to invalid syntax.
```ruby
begin
do_something(arg
rescue
nil
end) …
```
=> Fix an incorrect auto-correct for `Style/MethodCallWithArgsParentheses`

changelog/fix_autocorrect_for_lint_unused_block_argument.md, lib/rubocop/cop/lint/unused_block_argument.rb, spec/rubocop/cop/lint/unused_block_argument_spec.rb
Not sure if there is a better solution. But I think this cop should restrict itself to arguments and not make corrections within block body as suggested in the issue.
Closes #9713
=> [Fix #9713] Skip autocorrection for block_local_variables in `Lint/UnusedBlockArgument`

Gemfile
This PR reverts https://github.com/rubocop/rubocop/commit/b15e034.
The following tests will fail depending on the run tests sequence when using RuboCop Performance to 1.11.0.
```console
% bundle exec rspec --seed 33314 ./spec/rubocop/config_obsoletion_spec.rb
Run options: include {:focus=>true}
All examples were filtered out; ignoring {:focus=>true}
Randomized with seed 33314
....F....
Failures:
1) RuboCop::ConfigObsoletion#validate when the configuration includes
any extracted cops when the extensions are not loaded prints a warning
message
Failure/Error: expect(expected_message).to eq(e.message)
expected: "`Rails` cops have been extracted to the
`rubocop-rails` gem.\n(obsolete configuration found in
example/.rubocop.yml, please update it)"
got: "`Performance` cops have been extracted to …
```
=> Workaround for random build error

changelog/fix_an_error_for_style_if_unless_modifier.md, lib/rubocop/cop/style/if_unless_modifier.rb, spec/rubocop/cop/style/if_unless_modifier_spec.rb
Fixes #9729.
This PR fixes an error for `Style/IfUnlessModifier` when variable assignment is used in the branch body of if modifier.
=> [Fix #9729] Fix an error for `Style/IfUnlessModifier`

docs/modules/ROOT/pages/index.adoc
・The "Extension" link is attached in the "Next Step" text.
・I suggested adding a link in "extensions" in the "Overview" text.
=> Add link to index.adoc

docs/modules/ROOT/pages/cops_lint.adoc, docs/modules/ROOT/pages/cops_naming.adoc, docs/modules/ROOT/pages/cops_style.adoc
Adds escaping to regular expressions that broke Asciidoc parsing of several cop documents.
Current documentation at https://docs.rubocop.org/rubocop/cops_style.html#configurable-attributes-97 looks like this:
The same document, in IntelliJ's Asciidoc previewer, after this PR:
Unticked items are not applicable.
=> Docs: fix escaping of pipes in regexes that appear in table cells

changelog/fix_an_incorrect_autocorrect_for_style_sole_nested_conditional_cop.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/style/sole_nested_conditional_spec.rb
Fixes #9750.
This PR fixes an incorrect auto-correct for `Style/SoleNestedConditional` when when using nested `if` within `unless foo == bar`.
This patch leaves auto-correction from `(!foo == bar)` to `foo != bar` to `Style/InverseMethods` cop thus simplify its role and implementation. And this PR adds a cli test to prevent unintended auto-correction when using `Style/IfUnlessModifier` together for the patch.
=> [Fix #9750] Fix an incorrect auto-correct for `Style/SoleNestedConditional`

changelog/fix_a_false_positive_for_lint_number_conversion.md, lib/rubocop/cop/lint/number_conversion.rb, spec/rubocop/cop/lint/number_conversion_spec.rb
This PR fixes the following false positive and incorrect auto-correct for `Lint/NumberConversion` when `:to_f` is one of multiple method arguments.
```console
delegate :to_f, to: :description, allow_nil: true
% bundle exec rubocop --only Lint/NumberConversion -A example.rb
(snip)
W
Offenses:
example.rb:1:1: W: [Corrected] Lint/NumberConversion: Replace unsafe
number conversion with number class parsing, instead of using :to_f, use
stricter { |i| Float(i) }.
delegate :to_f, to: :description, allow_nil: true
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
delegate { |i| Float(i) }, to: :description, allow_nil: true
example.rb:1: syntax error, unexpected ',', …
```
=> Fix a false positive for `Lint/NumberConversion`

changelog/new_support_ruby_3_1_experimental.md, docs/modules/ROOT/pages/compatibility.adoc, lib/rubocop/rspec/shared_contexts.rb, lib/rubocop/target_ruby.rb, rubocop.gemspec, spec/rubocop/cli_spec.rb
RuboCop AST 1.5 supports Ruby 3.1.
https://github.com/rubocop/rubocop-ast/pull/182.
This PR supports `TargetRubyVersion 3.1`.
=> Support `TargetRubyVersion 3.1` (experimental)

changelog/fix_fix_two_autocorrection_issues_for.md, lib/rubocop/cop/style/negated_if_else_condition.rb, spec/rubocop/cop/style/negated_if_else_condition_spec.rb
Previously, when swapping the `if` and `else` branches, if one of the branches only had a single statement, the branch would end up not being spaced out properly.
Additionally, when there is a node with a comment inside the `if` that has an identical node with a comment *before* the `if` statement, `CommentsHelp.begin_pos_with_comment` returns an incorrect range, which was causing a clobbering error. I fixed this by creating ranges of the entire body of the if and else branches, so that they can just be swapped without relying on `ProcessedSource#ast_with_comments`. See rubocop/rubocop-ast#179.
=> [Fix #9731] Fix two autocorrection issues for `Style/NegatedIfElseCondition`

changelog/fix_support_deprecated_socket.md, lib/rubocop/cop/lint/deprecated_class_methods.rb, spec/rubocop/cop/lint/deprecated_class_methods_spec.rb
Fixed https://github.com/rubocop/rubocop/issues/9716
- Refactored original class to add functionality to not autocorrect and suggest replacing with instance method.
- Added Socket.gethostbyaddr and Socket.gethostbyname
=> [Fix #9716] Support deprecated Socket.gethostbyaddr and Socket.gethostbyname

changelog/fix_prevent_infinite_loops_during_symlink.md, lib/rubocop/target_finder.rb, spec/rubocop/target_finder_spec.rb
https://github.com/rubocop/rubocop/pull/8815 introduced a traversal strategy that used recursion.
https://github.com/rubocop/rubocop/pull/9703 then fixed an issue with this traversal which accounted for directories and symlinks.
When a symlink points to a parent directory that contains that symlink it'll cause this to go into a loop until the filename is too long for glob to handle.
We prevent this by checking for the inclusion of a symlink's real path in the base directory's realpath. If the base directory's path starts with the symlink's destination then we are in a loop and should skip processing the directory
=> Prevent infinite loops during symlink traversal

changelog/fix_autocorrect_when_doublequotes_are.md, changelog/fix_dont_autocorrect_global_variable.md, lib/rubocop/cop/mixin/string_literals_help.rb, spec/rubocop/cop/style/string_literals_spec.rb
With this config:
```
Style/StringLiterals:
EnforcedStyle: double_quotes
```
`'\\'` is not autocorrected to `"\\"` which it could
and
`'#$foo'` is autocorrected to `"\#$foo"` which it shouldn't, because it adds an escape.
Sorry I did those two in the same PR, but that would have added conflicts otherwise, since they change the same line.
Let me know if you'd really rather have 2 PRs.
=> Fix string literal autocorrect

changelog/fix_update_variableforce_to_be_able_to.md, lib/rubocop/cop/variable_force/branch.rb, spec/rubocop/cop/lint/useless_assignment_spec.rb
`VariableForce::Branch` was not aware of `case-match` nodes and thus did not properly mark all assignments in the following code as used, which caused rubocop to register a false positive `Lint/UselessAssignment`.
```ruby
def f
case '0'
in String
res = 1 # would not be registered, causing an offense
else
res = 2 # would be registered
end
res
end
```
Fixes #9762.
=> [Fix #9762] Update `VariableForce` to be able to handle `case-match` nodes

changelog/fix_fix_styleclassandmodulechildren_false.md, lib/rubocop/cop/style/class_and_module_children.rb, spec/rubocop/cop/style/class_and_module_children_spec.rb
This fix makes `Style/ClassAndModuleChildren` register an offense for the following type of code with the `compact` style:
```ruby
class Foo::Bar
class Baz
end
end
```
Fixes #9761.
=> [Fix #9761] Fix `Style/ClassAndModuleChildren` false negative for `compact` style when a class/module is partially nested

changelog/fix_fix_styleemptyliteral_to_not_register.md, lib/rubocop/cop/mixin/frozen_string_literal.rb, lib/rubocop/cop/style/empty_literal.rb, spec/rubocop/cop/style/empty_literal_spec.rb
`Style/EmptyLiteral` replaces `String.new` with `''`, unless the file has a `frozen-string-literal: true` magic comment. However, if `Style/FrozenStringLiteral` is also enabled, this will cause broken code, because the magic comment will be added afterwards.
This change makes string behaviour the same if `Style/FrozenStringLiteral` is enabled as if the magic comment is found. However, if `Style/FrozenStringLiteral` is enabled but there is a `frozen-string-literal: false` magic comment, `Style/EmptyLiteral` will continue to replace the literal.
Fixes #9773.
=> [Fix #9773] Fix `Style/EmptyLiteral` to not register offenses for `String.new` when `Style/FrozenStringLiteral` is enabled

changelog/new_support_summary_report_for_junit_formatter.md, docs/modules/ROOT/pages/formatters.adoc, lib/rubocop/formatter/junit_formatter.rb, spec/rubocop/formatter/junit_formatter_spec.rb
Fixes #9780.
This PR supports summary report for `JUnitFormatter`.
It adds the following attributes to the `<testsuite>` element.
- `tests` attribute ... Inspected file count.
- `failures` attribute ... Total offense count.
This is a JUnit format example:
```xml
% rubocop -f junit --display-only-failed lib/rubocop/formatter/junit_formatter.rb
<?xml version='1.0'?>
<testsuites>
<testsuite name='rubocop' tests='1' failures='2'>
<testcase classname='lib.rubocop.formatter.junit_formatter' name='Layout/LineLength'>
<failure type='Layout/LineLength' message='Layout/LineLength: Line is too long. [110/100]'>
/Users/koic/src/github.com/rubocop/rubocop/lib/rubocop/formatter/junit_formatter.rb:65:101
</failure>
</testcase>
<testcase classname='lib.rubocop.formatter.junit_formatter' …
```
=> [Fix #9780] Support summary report for `JUnitFormatter`

changelog/change_update_lintemptyblock_to_handle_procs.md, lib/rubocop/cop/lint/empty_block.rb, spec/rubocop/cop/lint/empty_block_spec.rb
`Lint/EmptyBlock` now treats procs the same way as lambdas (governed by the `AllowLambdas` configuration).
Fixes #9770.
=> [Fix #9770] Update `Lint/EmptyBlock` to handle procs the same way as lambdas

changelog/fix_an_incorrect_autocorrect_for_style_redundant_begin.md, lib/rubocop/cop/style/redundant_begin.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
This PR fixes an incorrect auto-correct for `Style/RedundantBegin` when using multi-line `if` in `begin` block.
And fixes https://github.com/testdouble/standard/issues/289 that is causing the following infinite loop error due to `Style/RedundantBegin` with `Style/MultilineMemoization`.
```ruby
@memo ||= begin
if condition
do_something
end
end
% bundle exec rubocop -a --only Style/RedundantBegin,Style/MultilineMemoization
(snip)
C
Offenses:
example.rb:1:1: C: [Corrected] Style/MultilineMemoization: Wrap
multiline memoization blocks in begin and end.
@memo ||= (if condition ...
^^^^^^^^^^^^^^^^^^^^^^^
example.rb:1:11: C: [Corrected] Style/RedundantBegin: Redundant begin
block detected.
@memo ||= begin
^^^^^
0 files inspected, 2 offenses detected, 2 …
```
=> Fix an incorrect auto-correct for `Style/RedundantBegin`

changelog/change_update_stylenillambda_to_handle_procs_as.md, lib/rubocop/cop/style/nil_lambda.rb, spec/rubocop/cop/style/nil_lambda_spec.rb
Similarly to #9775, updates `Style/NilLambda` to handle procs as well.
Like I wrote in https://github.com/rubocop/rubocop/pull/9775#issuecomment-832989444, the naming is a bit off here, but I think it's better than the two alternatives -- create a separate `Style/NilProc` cop (duplication) or rename `Style/NilLambda` to `NilLambdaAndProc` or something (breaking change).
=> Update `Style/NilLambda` to handle procs as well

changelog/fix_clobbering_error_in_class_and_module_children_cop.md, lib/rubocop/cop/style/class_and_module_children.rb, spec/rubocop/cop/style/class_and_module_children_spec.rb
=> [Fix #9766] Fix a clobbering error for `Style/ClassAndModuleChildren` with `compact` style

config/default.yml
I forgot to update default.yml in #9775  and #9776.
=> Update default.yml for changes to `Lint/EmptyBlock` and `Style/NilLambda`

docs/modules/ROOT/pages/configuration.adoc
I rewrote this section a bit because it was not worded very clearly. I also wanted to make sure it's explicit that `EnabledByDefault` will also enable cops that are disabled by RuboCop.
=> Clarify documentation about the `Enabled` and `EnabledByDefault`/`DisabledByDefault`

changelog/fix_false_positive_for_style_trivial_accessors.md, config/default.yml, lib/rubocop/cop/style/trivial_accessors.rb, spec/rubocop/cop/style/trivial_accessors_spec.rb
Fixes #9771.
This PR fixes a false positive for `Style/TrivialAccessors` when defining a method that is not a writer.
=> [Fix #9771] Fix a false positive for `Style/TrivialAccessors`

lib/rubocop/cop/internal_affairs/example_description.rb, spec/rubocop/cop/layout/condition_position_spec.rb, spec/rubocop/cop/layout/empty_lines_spec.rb, spec/rubocop/cop/lint/else_layout_spec.rb, spec/rubocop/cop/lint/out_of_range_regexp_ref_spec.rb, spec/rubocop/cop/lint/unmodified_reduce_accumulator_spec.rb, spec/rubocop/cop/lint/useless_setter_call_spec.rb, spec/rubocop/cop/lint/void_spec.rb, spec/rubocop/cop/naming/method_name_spec.rb, spec/rubocop/cop/naming/variable_name_spec.rb, spec/rubocop/cop/style/document_dynamic_eval_definition_spec.rb, spec/rubocop/cop/style/format_string_token_spec.rb
Follow https://github.com/rubocop/rubocop/pull/9796#discussion_r631650841.
This PR makes `InternalAffairs/ExampleDescription` aware of descriptions starting with `handles` and `works` when using `expect_no_offenses`.
=> Make `InternalAffairs/ExampleDescription` aware of several words

changelog/new_make_layout_argument_alignment_aware_of_kwargs.md, lib/rubocop/cop/layout/argument_alignment.rb, lib/rubocop/cop/layout/first_hash_element_indentation.rb, lib/rubocop/cop/layout/hash_alignment.rb, spec/rubocop/cop/layout/argument_alignment_spec.rb
This PR makes `Layout/ArgumentAlignment` aware of kwargs and fixes https://github.com/testdouble/standard/issues/216.
=> Make `Layout/ArgumentAlignment` aware of kwargs

changelog/fix_fix_invalid_line_splitting_by.md, lib/rubocop/cop/mixin/check_line_breakable.rb, spec/rubocop/cop/layout/line_length_spec.rb
When a `send` node has heredoc arguments, the line cannot be split after the heredoc or it will be a syntax error.
Fixes #9799.
=> [Fix #9799] Fix invalid line splitting by `Layout/LineLength` for `send` nodes with heredoc arguments

changelog/fix_fix_autocorrection_for_layoutlinelength.md, lib/rubocop/cop/mixin/check_line_breakable.rb, spec/rubocop/cop/layout/line_length_spec.rb
Previously in #9382, `Layout/LineLength` was fixed for unparenthesized `send` nodes with a hash, but now it is applied to all argument types, since the ruby parser will interpret it as a method call with no arguments.
Fixes #9749.
=> [Fix #9749] Fix autocorrection for `Layout/LineLength` to not move the first argument of an unparenthesized `send` node to the next line

changelog/fix_lint_void_false_positive.md, lib/rubocop/cop/lint/void.rb, spec/rubocop/cop/lint/void_spec.rb
=> [Fix #9792] Fix false positive for `Lint/Void` cop

changelog/change_disable_parallel_with_cache_false.md, lib/rubocop/options.rb, spec/rubocop/options_spec.rb
This closes #9744. 
Modify the behavior of `--parallel` combined with `--cache false` to emit a warning and disable parallel. It previously would raise an error and halt execution. This is consistent with the changes in #9647
=> [Change #9744] Auto disable parallel when combined with cache false

changelog/fix_class_and_module_children_preserve_comment.md, lib/rubocop/cop/style/class_and_module_children.rb, spec/rubocop/cop/style/class_and_module_children_spec.rb
=> [Fix #9767] Fix `Style/ClassAndModuleChildren` cop to preserve comments

spec/rubocop/cli/options_spec.rb
Follow https://github.com/ruby/psych/pull/487.
This PR fixes the following Ruby 3.1.0-dev build matrix error.
```console
% ruby -ryaml -ve 'p Psych::VERSION'
ruby 3.1.0dev (2021-05-17T10:51:51Z master ee611341c9) [x86_64-darwin19]
"4.0.0"
% bundle exec rspec ./spec/rubocop/cli/options_spec.rb
(snip)
Failures:
1) RuboCop::CLI options --show-cops with no args prints the current
configuration
Failure/Error: printed_config = YAML.load(out.join) #
rubocop:disable Security/YAMLLoad
Psych::DisallowedClass:
Tried to load unspecified class: Regexp
Shared Example Group: "prints config" called from
./spec/rubocop/cli/options_spec.rb:1104
Finished in 25.97 seconds (files took 1.02 seconds to load)
117 examples, …
```
=> Fix a build error for Ruby 3.1.0-dev

.github/workflows/rubocop.yml, .mergify.yml
This PR skips mingw build matrix due to the following build error.
```console
D:/ruby-mingw/lib/ruby/3.1.0/yaml.rb:3: warning: It seems your ruby
installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your
ruby.
LoadError: 126: The specified module could not be found.   -
D:/ruby-mingw/lib/ruby/3.1.0/x64-mingw32/psych.so
<internal:D:/ruby-mingw/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in
`require': 126: The specified module could not be found.   -
D:/ruby-mingw/lib/ruby/3.1.0/x64-mingw32/psych.so (LoadError)
from
<internal:D:/ruby-mingw/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
from D:/ruby-mingw/lib/ruby/3.1.0/psych.rb:13:in `<top (required)>'
from …
```
=> Workaround for mingw build error

changelog/fix_false_negative_for_layout_hash_alignment.md, lib/rubocop/cop/layout/hash_alignment.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/layout/hash_alignment_spec.rb
This PR fixes a false negative for `Layout/HashAlignment` when set `EnforcedStyle: with_fixed_indentation` of `ArgumentAlignment`. It is a regression of #9798.
=> Fix a false negative for `Layout/HashAlignment`

changelog/fix_an_error_for_layout_argument_alignment.md, lib/rubocop/cop/layout/argument_alignment.rb, lib/rubocop/cop/layout/hash_alignment.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/layout/argument_alignment_spec.rb
Fixes #9811.
This PR fixes an error for `Layout/ArgumentAlignment` with `Layout/FirstHashElementIndentation` when setting
`EnforcedStyle: with_fixed_indentation`.
=> [Fix #9811] Fix an error for `Layout/ArgumentAlignment`

changelog/fix_false_negative_for_style_top_level_method_definition.md, lib/rubocop/cop/style/top_level_method_definition.rb, spec/rubocop/cop/style/top_level_method_definition_spec.rb
Fixes #9819.
This PR fixes a false negative for `Style/TopLevelMethodDefinition` when defining a top-level method after a class definition.
=> [Fix #9819] Fix a false negative for `Style/TopLevelMethodDefinition`

changelog/fix_false_range_for_lint_redundant_cop_disable_directive.md, lib/rubocop/cop/lint/redundant_cop_disable_directive.rb, lib/rubocop/directive_comment.rb, spec/rubocop/cop/lint/redundant_cop_disable_directive_spec.rb
Fixes #9822.
This PR fixes a false directive comment range for `Lint/RedundantCopDisableDirective`.
=> [Fix #9822] Fix a false range for `Lint/RedundantCopDisableDirective`

lib/rubocop/cop/style/when_then.rb, spec/rubocop/cop/style/when_then_spec.rb
This PR refines offense message for `Style/WhenThen`. It uses actual value of `when` for offense message.
=> Refine offense message for `Style/WhenThen`

lib/rubocop/cop/layout/space_around_keyword.rb, new_support_pattern_matching_for_layout_space_around_keyword.md, spec/rubocop/cop/layout/space_around_keyword_spec.rb
This PR supports Ruby 2.7's pattern matching syntax for `Layout/SpaceAroundKeyword`.
The following is a technical note.
There are the following differences between `case ... when` and `case ... in`.
So there is a TODO test for this patch's test and I confirmed this syntax below:
https://bugs.ruby-lang.org/issues/17925
An answer will determine whether to enable or discard the commented out test in the future.
=> Support Ruby 2.7's pattern matching syntax for `Layout/SpaceAroundKeyword`

changelog/fix_fix_incorrect_corrections_for.md, config/default.yml, lib/rubocop/cop/layout/hash_alignment.rb, lib/rubocop/cop/mixin/hash_alignment_styles.rb, spec/rubocop/cop/layout/hash_alignment_spec.rb
Keyword splats were previously treated as pairs using colon style, which some hacks in the Alignment classes to handle them (see #3919). However, this did not account for all possibilities and would cause previous pairs on the same line as the `kwsplat` to be removed by autocorrection.
Instead, now a special `KeywordSplatAlignment` type was added to handle `kwsplat`s. The previously behaviour about `kwsplat`s was retained (they will still be aligned with the beginning of the rest of the hash, regardless of enforced style), and the hacks in `KeyAlignment` and `TableAlignment` for `kwsplat`s were removed.
=> [Fix #9836] Fix incorrect corrections for `Layout/HashAlignment` when a `kwsplat` node is on the same line as a `pair` node with table style

changelog/new_add_allowed_receivers_option_for_style_hash_each_methods.md, config/default.yml, lib/rubocop/cop/style/hash_each_methods.rb, spec/rubocop/cop/style/hash_each_methods_spec.rb
Fixes #9839.
This PR adds `AllowedReceivers` option for `Style/HashEachMethods`.
`Style/HashEachMethods` cop is already marked as unsafe. This PR can use allow list to rule out false positives.
=> [Fix #9839] Add `AllowedReceivers` option for `Style/HashEachMethods`

changelog/new_support_guard_if_unless_of_pattern_matching_for_layout_space_around_keyword.md, lib/rubocop/cop/layout/space_around_keyword.rb, spec/rubocop/cop/layout/space_around_keyword_spec.rb
This PR supports guard `if` and `unless` syntax keywords of Ruby 2.7's pattern matching for `Layout/SpaceAroundKeyword`.
```ruby
case 42
in 42 if true
puts 'hello'
end
```
These nodes are called `if-guard` and `unless-guard` when using guard `if` and `unless` in pattern matching.
```ruby
% ruby-parse example.rb
(case-match
(int 42)
(in-pattern
(int 42)
(if-guard
(true))
(send nil :puts
(str "hello"))) nil)
```
See below for this guard semantics:
https://github.com/whitequark/parser/pull/574#issuecomment-498365609
=> Support Ruby 2.7's pattern matching for `Layout/SpaceAroundKeyword`

lib/rubocop/rake_task.rb
This is quite pedantic, but while looking through the code in `rake_task` I noticed a typo in a comment&mdash;"correct" was, ironically enough, misspelled. My tiny little contribution to making rubocop even better. :)
=> Fix trivial typo in rake_task.rb

changelog/fix_fix_stylequotedsymbols_for_hashrocket.md, lib/rubocop/cop/style/quoted_symbols.rb, spec/rubocop/cop/style/quoted_symbols_spec.rb
`Style/QuotedSymbols` was not correcting symbols in hash-rocket hashes correctly.
Fixes #9845.
=> [Fix #9845] Fix `Style/QuotedSymbols` for hash-rocket hashes

changelog/fix_fix_styleredundantself_to_allow.md, lib/rubocop/cop/style/redundant_self.rb, spec/rubocop/cop/style/redundant_self_spec.rb
Previously, `Style/RedundantSelf` registered false positives when a condition used `self` to avoid shadowing a local variable:
```ruby
a = self.a if self.a
```
This was because the condition was not correlated to the lvar assign because they happen at different times. This is now fixed so `if`, `unless`, `while` and `until` nodes are covered.
Fixes #9843.
=> [Fix #9843] Fix `Style/RedundantSelf` to allow conditional nodes to use `self` in the condition when a variable named is shadowed inside

changelog/fix_missing_option_for_lint_empty_in_pattern.md, config/default.yml
Fixes #9850.
This PR fixes missing `AllowComments` option for `Lint/EmptyInPattern`.
=> [Fix #9850] Fix missing option for `Lint/EmptyInPattern`

changelog/fix_allow_braced_numeric_blocks_in_style_Method_call_with_args_parentheses.md, lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb, spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb
This is yet another fix for the `omit_parentheses` style of the
`Style/MethodCallWithArgsParentheses` cop. We're issuing offenses for
braced `numblock` calls:
```ruby
updated_ids = Set.new(items_to_update) { _1.remote_id.to_s }
^^^^^^^^^^^^^^^^^ Omit parentheses for method calls with arguments.
```
Removing the parens leads to code that doesn't compile so this is not good.
Numeric block have their own AST node type:
```
-> ruby-parse -e "Set.new(items_to_update) { _1.remote_id }"
(numblock
(send
(const nil :Set) :new
(send nil :items_to_update)) 1
(send
(lvar :_1) :remote_id))
```
vs
```
-> ruby-parse -e "Set.new(items_to_update) { |it| it.remote_id }"
(block
(send
(const nil :Set) :new
(send nil :items_to_update))
(args
(procarg0
(arg :it)))
(send
(lvar :it) :remote_id))
```
Send nodes …
=> Allow braced numeric block calls in Style/MethodCallWithArgsParentheses

.github/workflows/rubocop.yml, .mergify.yml
MinGW master build problem addressed in PR #9808 is fixed.
This reverts commit ac00a838b6d537fd4f3b5e4ac1cd67df1bdd73ea, reversing
changes made to 5f6452403da77df245ac160804122c975a901ac0.
=> Revert "Merge pull request #9808" - fix MinGW CI

docs/modules/ROOT/pages/configuration.adoc
Text rendered, before:
> This affects cops that have customisable paths: if the default is db/migrate/.rb, and the cop is enabled in db/migrate/.rubocop.yml, the path will need to be explicitly set as .rb, as the default will look for db/migrate/db/migrate/*.rb. This is unlikely to be what you wanted.
After:
> This affects cops that have customisable paths: if the default is db/migrate/*.rb, and the cop is enabled in db/migrate/.rubocop.yml, the path will need to be explicitly set as *.rb, as the default will look for db/migrate/db/migrate/*.rb. This is unlikely to be what you wanted.
=> configuration: * seems to bind before `; escape it

changelog/new_support_basic_auth_to_download_shared_config.md, changelog/new_support_token_auth_to_download_shared_config.md, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop/remote_config.rb, spec/rubocop/remote_config_spec.rb
This PR adds Token auth support so that users can inherit shared config from the internal private repo.  
This addresses https://github.com/rubocop/rubocop/issues/9827
=> [Fix #9827] Add basic auth support to download raw yml config from private repo

changelog/changelog/new_support_pattern_matching_for_layout_indentation_width.md, lib/rubocop/cop/layout/indentation_width.rb, spec/rubocop/cop/layout/indentation_width_spec.rb
This PR supports Ruby 2.7's pattern matching for `Layout/IndentationWidth`.
=> Support Ruby 2.7's pattern matching for `Layout/IndentationWidth`

changelog/new_support_pattern_matching_for_style_identical_conditional_branches.md, lib/rubocop/cop/style/identical_conditional_branches.rb, spec/rubocop/cop/style/identical_conditional_branches_spec.rb
This PR supports Ruby 2.7's pattern matching syntax for `Style/IdenticalConditionalBranches` cop.
This `Style/IdenticalConditionalBranches` cop is detecting for `if` and` case`.
Therefore, I think about detecting `case-match` with the cop instead of a new cop.
It may also be suitable for the cop's role of detecting duplicated conditional branches.
=> Support pattern matching for `Style/IdenticalConditionalBranches` cop

CHANGELOG.md, new_support_pattern_matching_for_layout_space_around_keyword.md
This changelog file ended up in the root directory instead of `changelog/` so it didn't get merged in.
=> Fix orphaned changelog file

changelog/fix_fix_error_in_layouthashalignment_with_an.md, lib/rubocop/cop/layout/hash_alignment.rb, spec/rubocop/cop/layout/hash_alignment_spec.rb
=> [Fix #9861] Fix error in `Layout/HashAlignment` with an empty hash literal

changelog/fix_incorrect_autocorrect_for_layout_dot_position.md, lib/rubocop/cop/layout/dot_position.rb, spec/rubocop/cop/layout/dot_position_spec.rb
This PR fixes the following incorrect auto-correct for `Layout/DotPosition` when using only dot line.
```console
foo
.bar
.
baz
% rubocop --only Layout/DotPosition -a
(snip)
C
Offenses:
example.rb:3:3: C: [Corrected] Layout/DotPosition: Place the . on the
next line, together with the method name.
.
^
```
```consle
foo
.bar
.baz
example.rb:4: syntax error, unexpected '.', expecting end-of-input
.baz
```
```console
foo
.bar
.baz
Syntax OK
```
=> Fix an incorrect auto-correct for `Layout/DotPosition`

lib/rubocop/cop/style/raise_args.rb
Whilst `MyCustomError.new` violates this Rubocop rule, the documentation implies the only way of fixing it is to pass an argument representing the exception message, whereas actually if your custom exception has a default message, it's quite possible you just want to use the default message. This can be achieved without violating this Rubocop rule, by omitting the call to `.new`.
I spent an embarrassingly long time figuring that one out, so thought a change to the documentation might help future developers!
------
=> Clarify that you can raise exceptions without arguments

lib/rubocop/cop/layout/redundant_line_break.rb
Follow #7868.
This PR uses `Cop::Base` API for `Layout/RedundantLineBreak`.
=> Use `Cop::Base` API for `Layout/RedundantLineBreak`

changelog/new_support_one_line_pattern_matching.md, lib/rubocop/cop/layout/space_around_keyword.rb, lib/rubocop/cop/layout/space_around_operators.rb, spec/rubocop/cop/layout/space_around_keyword_spec.rb, spec/rubocop/cop/layout/space_around_operators_spec.rb
This PR supports one-line pattern matching syntax for `Layout/SpaceAroundKeyword` and `Layout/SpaceAroundOperators`.
`match-pattern` node changes differently in Ruby 2.7 and Ruby 3.0.
```console
% ruby-parse -e '42 in foo'
(match-pattern
(int 42)
(match-var :foo))
```
```console
% ruby-parse -e '42 => foo'
(match-pattern
(int 42)
(match-var :foo))
```
And one-line `in` syntax that represents one-line pattern maching changes
from `match-pattern` node to `match-pattern-p` in Ruby 3.0.
```console
% ruby-parse -e '42 in foo'
(match-pattern-p
(int 42)
(match-var :foo))
```
=> Support one-line pattern matching syntax

changelog/new_support_pattern_matching_for_lint_literal_as_condition.md, lib/rubocop/cop/lint/literal_as_condition.rb, spec/rubocop/cop/lint/literal_as_condition_spec.rb
This PR supports Ruby 2.7's `in` pattern syntax for `Lint/LiteralAsCondition`.
=> Support Ruby 2.7's `in` pattern syntax for `Lint/LiteralAsCondition`

changelog/new_disable_all_cop_department_with_directive_comment.md, docs/modules/ROOT/pages/configuration.adoc, lib/rubocop/cop/lint/missing_cop_enable_directive.rb, lib/rubocop/cop/lint/redundant_cop_disable_directive.rb, lib/rubocop/cop/lint/redundant_cop_enable_directive.rb, lib/rubocop/cop/migration/department_name.rb, lib/rubocop/directive_comment.rb, spec/rubocop/cop/lint/missing_cop_enable_directive_spec.rb, spec/rubocop/cop/lint/redundant_cop_disable_directive_spec.rb, spec/rubocop/cop/lint/redundant_cop_enable_directive_spec.rb, spec/rubocop/cop/migration/department_name_spec.rb, spec/rubocop/directive_comment_spec.rb
New feature for request https://github.com/rubocop/rubocop/issues/9519
- Added checking for department only to directive comment.
- Added note about new feature to documentation.
=> [Fix #9519] Disable all cop department with directive comment 

changelog/fix_fix_empty_line_after_guard_clause_with.md, lib/rubocop/cop/layout/empty_line_after_guard_clause.rb, spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb
Fixes https://github.com/rubocop/rubocop/issues/9852
=> [Fix #9852] Fix empty line after guard clause with and and heredoc

changelog/fix_false_positive_for_style_regexp_literal.md, lib/rubocop/cop/style/regexp_literal.rb, spec/rubocop/cop/style/regexp_literal_spec.rb
Fixes #9874.
This PR fixes a false positive for `Style/RegexpLiteral` when using `%r` regexp literal with `EnforcedStyle: omit_parentheses` of `Style/MethodCallWithArgsParentheses`.
=> [Fix #9874] Fix a false positive for `Style/RegexpLiteral`

changelog/fix_a_false_positive_for_style_regexp_literal.md, lib/rubocop/cop/style/regexp_literal.rb, spec/rubocop/cop/style/regexp_literal_spec.rb
This PR fixes the following false positive for `Style/RegexpLiteral` when using a regexp starts with a blank as a method argument.
```console
do_something %r| regexp|
% bundle exec rubocop --only Style/RegexpLiteral -a
(snip)
Offenses:
example.rb:1:14: C: [Corrected] Style/RegexpLiteral: Use // around regular expression.
do_something %r| regexp|
^^^^^^^^^^^
do_something / regexp/
example.rb:1: syntax error, unexpected end-of-input
```
=> Fix a false positive for `Style/RegexpLiteral`

changelog/fix_an_incorrect_autocorrect_for_layout_line_length.md, lib/rubocop/cop/mixin/check_line_breakable.rb, spec/rubocop/cop/layout/line_length_spec.rb
This PR fixes an incorrect auto-correct for `Layout/LineLength` when using heredoc as the first method argument and omitting parentheses.
```console
foo <<~RUBY, arg
RUBY
% bundle exec rubocop --only Layout/LineLength -a
(snip)
C
Offenses:
example.rb:1:16: C: [Corrected] Layout/LineLength: Line is too long. [16/15]
foo <<~RUBY, arg
^
foo <<~RUBY,
arg
RUBY
example.rb:1: syntax error, unexpected end-of-input
```
=> Fix an incorrect auto-correct for `Layout/LineLength`

spec/rubocop/cop/layout/multiline_array_brace_layout_spec.rb, spec/rubocop/cop/layout/multiline_hash_brace_layout_spec.rb, spec/rubocop/cop/layout/multiline_method_call_brace_layout_spec.rb, spec/rubocop/cop/layout/redundant_line_break_spec.rb, spec/support/alignment_examples.rb, spec/support/multiline_literal_brace_layout_trailing_comma_examples.rb
[Fix #8127]
Replace `autocorrect_source` with newer `expect_correction` in remaining
specs:
* 'multiline literal brace layout trailing comma'
* 'misaligned'
=> [Fix #8127] Use expect_correction in remaining specs

changelog/fix_indentation_in_class_and_module_children.md, lib/rubocop/cop/style/class_and_module_children.rb, spec/rubocop/cop/style/class_and_module_children_spec.rb
Fixes the auto-corrected indentation for Style/ClassAndModuleChildren with compact style .
~~This PR adds a failing spec for an issue with the Style/ClassAndModuleChildren cop not dedenting code correctly.~~
~~I noticed this as I was wishing to add a new style, and found that the compact style does not remove whitespace correctly.~~
~~I am curious if this is normal behaviour. I.e. do the indentation checks occur last, and so can be used for auto-correcting whitespace?~~
~~I am trying to familiarise myself with the codebase to work out exactly how to implement this functionality in an idiomatic way. But if you have any pointers that would be helpful. I'd be happy to have a go at fixing this.~~
[1]: …
=> Fix dedenting Style/ClassAndModuleChildren

changelog/fix_gem_version_not_respecting_tags.md, lib/rubocop/cop/bundler/gem_version.rb, spec/rubocop/cop/bundler/gem_version_spec.rb
https://github.com/rubocop/rubocop/pull/9807 seems to be stale. This pull request completes the work it set out to do and will close #9803 and #9807.
I originally wanted to create a pull request to merge into https://github.com/rubocop/rubocop/pull/9807, however, I was not able to figure that out. Probably due to my inexperience when working on git projects across multiple forks.
This differs slightly from https://github.com/rubocop/rubocop/pull/9807 given the conversation that has happened in that pull request:
- This proposal does not take the hosted git service into consideration
- This proposal also checks for `branch`
=> [Fix #9803] Update Bundler/GemVersion to check commit references

changelog/fix_a_false_positive_for_layout_closing_parenthesis_indentation.md, lib/rubocop/cop/layout/closing_parenthesis_indentation.rb, spec/rubocop/cop/layout/closing_parenthesis_indentation_spec.rb
This PR fixes a false positive for `Layout/ClosingParenthesisIndentation` when using keyword arguemnts.
=> Fix a false positive for `Layout/ClosingParenthesisIndentation`

changelog/change_string_concatenation_enforced_styles.md, config/default.yml, lib/rubocop/cop/style/string_concatenation.rb, spec/rubocop/cop/style/string_concatenation_spec.rb
=> [Fix #9144] Add `aggressive` and `conservative` enforced styles for `Style/StringConcatenation` cop

.rubocop.yml, changelog/change_set_check_strings_false_and_remove_master_for_naming_inclusive_language.md, config/default.yml, spec/rubocop/cop/naming/inclusive_language_spec.rb, tasks/cut_release.rake
Fixes #9895 and follow up https://github.com/rubocop/rubocop/pull/9893#issuecomment-870343243.
This PR disables `Naming/InclusiveLanguage` by default because it has an unexpectedly impact for many users who give feedback.
=> [Fix #9895] Disable `Naming/InclusiveLanguage` by default

.rubocop.yml, .rubocop_todo.yml, Gemfile, Rakefile, tasks/changelog.rake, tasks/cops_documentation.rake, tasks/prof.rake
https://github.com/rubocop/rubocop-rake
=> Add rubocop-rake

changelog/fix_incorrect_autocorrect_for_layout_hash_alignment.md, lib/rubocop/cop/layout/hash_alignment.rb, spec/rubocop/cli/autocorrect_spec.rb
Fixes https://github.com/testdouble/standard/issues/306.
This PR fixes an incorrect auto-correct for `Layout/HashAlignment` when setting `EnforcedStyle: with_fixed_indentation` of `Layout/ArgumentAlignment` and using misaligned keyword arguments.
=> Fix an incorrect auto-correct for `Layout/HashAlignment`

changelog/fix_LineEndStringConcatenationIndentation.md, lib/rubocop/cop/layout/line_end_string_concatenation_indentation.rb, spec/rubocop/cop/layout/line_end_string_concatenation_indentation_spec.rb
A multiline string literal such as
```ruby
%(
foo
bar
)
```
is parsed as a `dstr`, and should just be skipped by this cop, as opposed to strings made up of several literals concatenated with backslash.
=> [Fix #9894] Handle multiline strings in LineEndStringConcatenationIndentation

CHANGELOG.md, changelog/fix_make_comment_annotation_style_configurable.md, config/default.yml, lib/rubocop/cop/style/comment_annotation.rb, spec/rubocop/cop/style/comment_annotation_spec.rb
[Fix #9890]
Make the separator for the Style/CommentAnnotation cop configurable. By default, the enforced style will be the current behaviour of annotation keyword followed by a colon (`:`), and a space. A new supported style is added to only require a space following the annotation keyword.
=> [Fix #9890] Make Colon After Comment Annotation Configurable

changelog/fix_space_around_singleton_class_operator.md, lib/rubocop/cop/layout/space_around_operators.rb, spec/rubocop/cop/layout/space_around_operators_spec.rb
We classify the `<<` operator used for the singleton class construct `class << self` as an operator like any other. This means that not inspecting it was a bug, and this change fixes it.
=> [Fix #8469] Add singleton class operator inspection

changelog/fix_incorrect_autocorrect_for_lint_useless_time.md, lib/rubocop/cop/lint/useless_times.rb, spec/rubocop/cop/lint/useless_times_spec.rb
Fixes #9907.
This PR fixes an incorrect auto-correct for `Lint/UselessTimes` when using block variable for `1.times`.
=> [Fix #9907] Fix an incorrect auto-correct for `Lint/UselessTimes`

changelog/fix_line_end_string_concatenation_indentation.md, lib/rubocop/cop/layout/line_end_string_concatenation_indentation.rb, spec/rubocop/cop/layout/line_end_string_concatenation_indentation_spec.rb
By checking that the inspected node is multiline, we should get rid of this false positive. Happens for code like
```ruby
puts 'a'"#{b}"
```
We're also checking that none of the children is multiline. This is done to skip weird corner cases that are impossible to have a consistent alignment rule for.
It turns out that the new multiline checks make it possible to remove a couple of old conditions when checking if it's a concatenation with backslashes we're inspecting. It is perhaps possible to search for backslash and newline in the code, but I'd like to avoid that, because I'm afraid of other weird corner cases if we take the regexp search approach.
=> [Fix #9905] Fix single line concatenation false positive

changelog/fix_autogenconfig_bug_for_HashSyntax.md, lib/rubocop/cop/style/hash_syntax.rb, spec/rubocop/cli/auto_gen_config_spec.rb
We must call `ruby19_check()` even if there are no hash rockets in the inspected node, to give it a chance to register that the correct style has been detected. The generation of `.rubocop_todo.yml` depends on it.
=> [Fix #9891] Fix --auto-gen-config bug for Style/HashSyntax

changelog/fix_override_warning.md, lib/rubocop/config_loader_resolver.rb, spec/rubocop/config_loader_spec.rb
The list of files from `inherit_from` is iterated over in reverse order. If we first reverse and then iterate with indices, the indices will start at 0 for the item that was originally last in the list. This is not what we want.
=> [Fix #9869] Print correct file in override warning

changelog/fix_an_error_for_layout_hash_alignment.md, lib/rubocop/cop/layout/hash_alignment.rb, spec/rubocop/cop/layout/hash_alignment_spec.rb
Fixes #9914.
This PR fixes an error for `Layout/HashAlignment` when using aligned hash argument for `proc.()`.
=> [Fix #9914] Fix an error for `Layout/HashAlignment`

.rubocop_todo.yml, changelog/fix_incorrect_autocorrect_for_style_block_delimiters.md, lib/rubocop/cop/style/block_delimiters.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/style/block_delimiters_spec.rb
Fixes #9902
This PR fixes an incorrect auto-correct for `Style/BlockDelimiters` when there is a comment after the closing brace.
It prevents `Style/CommentedKeyword` from removing source code comment after `end` keyword.
=> [Fix #9902] Fix an incorrect auto-correct for `Style/BlockDelimiters`

changelog/fix_class_structure_eol_comment_bug.md, lib/rubocop/cop/layout/class_structure.rb, spec/rubocop/cop/layout/class_structure_spec.rb
The algorithm for finding the start of a code segment to move must be aware of the fact that some comments are end-of-line comments. Those are not the comments we're looking for. It's only comments above the given code line that are interesting.
=> [Fix #9848] Handle EOL comments in ClassStructure auto-correct

changelog/fix_first_argument_indentation_false_pos.md, lib/rubocop/cop/layout/first_argument_indentation.rb, spec/rubocop/cop/layout/first_argument_indentation_spec.rb
Setter calls are a kind of method invocation that `Layout/FirstArgumentIndentation` should just skip.
=> [Fix #9434] Fix false positive in FirstArgumentIndentation

changelog/fix_github_actions_in_non_default_directory.md, lib/rubocop/formatter/git_hub_actions_formatter.rb, spec/rubocop/formatter/git_hub_actions_formatter_spec.rb
In some cases (specifically when running inside the container with
non-default `working-directory`) GitHub cannot link absolute paths
produced by formatter to the code, while relative [to the project root] 
paths works.
Output relative paths if they're inside current directory, so this
usecase is covered.
I can craft a public repo with reproducer, since I see this issue in private repo, but hopefully you believe me ._.
I doubt that we should care about usecases outside of GHA, so this PR could break reporting only if project is checked out into non-default directory and `rubocop` runs from some outer directory (i. e. not from the project root), but such cases should be trivially fixable by changing `working-directory`. 
In the case in question it's unfixable or non-trivially fixable …
=> Fixup GitHub Actions formatter when run in non-default directory

changelog/fix_autocorrect_in_Style_DoubleCopDisableDirective.md, lib/rubocop/cop/style/double_cop_disable_directive.rb, spec/rubocop/cli/disable_uncorrectable_spec.rb, spec/rubocop/cop/style/double_cop_disable_directive_spec.rb
Just removing cop names from disable directives is not a good solution. It's bound to cause infinite loop errors when those cops try to add the disable directives back. The natural solution is to put in commas instead.
=> [Fix #9922] Replace extra disable directives with comma

changelog/fix_false_autocorrection_for_layout_end_alignment.md, lib/rubocop/cop/layout/end_alignment.rb, spec/rubocop/cop/layout/end_alignment_spec.rb
Fixes #9928.
This PR fixes an infinite loop error and a false auto-correction behavior for `Layout/EndAlignment` when using operator methods and `EnforcedStyleAlignWith: variable`.
This infinite loop error is due to an offense being registered but not auto-corrected.
`EnforcedStyleAlignWith: variable` enforces alignment to variable, it should be auto-corrected to be aligned to variable even when operator method is used.
=> [Fix #9928] Fix a false auto-correct for `Layout/EndAlignment`

changelog/fix_error_message_for_dept.md, lib/rubocop/config_validator.rb, spec/rubocop/cli_spec.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/config_spec.rb
This is a smaller change that the one suggested in #9752. Instead of allowing to use top level departments in configuration, I just made a better error message. I think this change has a lower risk of causing new problems down the line.
When there are cop departments that seem to have a structure, like in the cookstyle gem where departments are named `Chef/Style`, `Chef/Correctness`, etc., it's easy to assume that there is a `Chef` department that can disable all departments under it. This is not the case, but the error message `Error: unrecognized cop Chef found in .cookstyle.yml` is not informative enough.
If an unrecognized cop or department is the first part of existing departments, we list the existing departments. This should help the user realize what needs to be changed. Example: …
=> [Fix #9752] Improve error message for top level department

changelog/new_add_pattern_matching_doc_and_test_for_lint_duplicate_branch.md, lib/rubocop/cop/lint/duplicate_branch.rb, rubocop.gemspec, spec/rubocop/cop/lint/duplicate_branch_spec.rb
This PR supports Ruby 2.7's pattern matching for `Lint/DuplicateBranch`.
~~When https://github.com/rubocop/rubocop-ast/pull/192 is merged, please remove the `Lint::DuplicateBranch#case_match_branches(node)` private method and use `AST::CaseMatchNode#branches` instead.~~
And this PR uses rubocop/rubocop-ast#192 feature, so it requires RuboCop AST 1.8.0 or higher.
=> Support Ruby 2.7's pattern matching for `Lint/DuplicateBranch`

changelog/fix_incorrect_autocorrect_for_style_hash_transform_values.md, lib/rubocop/cop/mixin/hash_transform_method.rb, spec/rubocop/cop/style/hash_transform_values_spec.rb
Fixes #9940.
This PR fixes an incorrect auto-correct for `Style/HashTransformValues` when value is a hash literal for `_.to_h{...}`.
=> [Fix #9940] Fix an incorrect auto-correct for `Style/HashTransformValues`

changelog/fix_heredoc_trailing_spaces.md, lib/rubocop/cop/layout/heredoc_indentation.rb, lib/rubocop/cop/layout/trailing_whitespace.rb, lib/rubocop/cop/mixin/heredoc.rb, spec/rubocop/cop/layout/trailing_whitespace_spec.rb
Whitespace-only lines within heredocs that are shorter than the indentation level, or equal to it, should be removed when correcting trailing whitespace. Inserting string interpolation tokens on these lines changes the indentation level for squiggly heredocs.
Although I mentioned in #9945 that `Layout/HeredocIndentation` does some unnecessary changes to empty lines within heredocs, I've chosen to only fix the actual bug here, which is in `Layout/TrailingWhitespace`. If both these cops are enabled, `Layout/TrailingWhitespace` will clean up after `Layout/HeredocIndentation` to make the code both readable and correct.
=> [Fix #9945] Fix heredoc indentation in trailing space corrections

changelog/new_support_pattern_matching_for_style_conditional_assignment.md, lib/rubocop/cop/style/conditional_assignment.rb, spec/rubocop/cop/style/conditional_assignment_assign_in_condition_spec.rb, spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb
This PR supports Ruby 2.7's pattern matching for `Style/ConditionalAssignment`.
This `Style/IdenticalConditionalBranches` cop is detecting for `if` and `case`.
Therefore, I think about detecting `case-match` with the cop instead of a new cop.
=> Support Ruby 2.7's pattern matching for `Style/ConditionalAssignment`

spec/rubocop/lockfile_spec.rb, spec/spec_helper.rb
This PR is a workaround for `undefined method 'add_dependency_names' for nil:NilClass` CI build error when using Bundler 2.2.25 on Windows.
```console
Failures:
1) RuboCop::Lockfile#gems returns all the dependencies
Failure/Error: @parser = lockfile ?
Bundler::LockfileParser.new(lockfile) : nil
NoMethodError:
undefined method `add_dependency_names' for nil:NilClass
4) RuboCop::Lockfile#includes_gem? for an included dependency
Failure/Error: @parser = lockfile ?
Bundler::LockfileParser.new(lockfile) : nil
NoMethodError:
undefined method `add_dependency_names' for nil:NilClass
5) RuboCop::Lockfile#dependencies returns all the dependencies
Failure/Error: @parser = …
```
=> Workaround for CI build error when using Bundler 2.2.5 on Windows

spec/rubocop/lockfile_spec.rb, spec/spec_helper.rb
Not sure why the failure was specific to Windows, but I think the reason is that these specs were parsing an invalid lockfile. Since the `specs:` section didn't exist, bundler was failing to parse the lockfile source,and then trying to use it while parsing specs, resulting in a method being called on `nil`.
=> Try fix CI errors on Windows

lib/rubocop/cop/bundler/ordered_gems.rb, lib/rubocop/cop/gemspec/ordered_dependencies.rb, lib/rubocop/cop/internal_affairs.rb, lib/rubocop/cop/internal_affairs/inherit_deprecated_cop_class.rb, spec/rubocop/cop/internal_affairs/inherit_deprecated_cop_class_spec.rb, spec/support/cops/class_must_be_a_module_cop.rb, spec/support/cops/module_must_be_a_class_cop.rb
This PR adds `InternalAffairs/InheritDeprecatedCopClass` cop.
Here is a note of progress towards the V1 API. `Bundler/OrderedGems` and `Gemspec/OrderedDependencies` cops are not migrated to V1 API yet. All cops in rubocop org will be migrated when the two cops are migrated.
=> Add `InternalAffairs/InheritDeprecatedCopClass` cop

changelog/fix_prevent_an_infinite_loop_when_a_detected.md, lib/rubocop/cop/style/single_line_block_params.rb, spec/rubocop/cop/style/single_line_block_params_spec.rb
When a method has fewer block arguments than expected (via the cop's configuration) but the names are correct, an offense is registered but autocorrection doesn't change anything, which leads to an infinite loop.
This change allows blocks with fewer than expected arguments as long as the names are correct.
Fixes #9958.
=> [Fix #9958] Prevent an infinite loop when a detected method has fewer arguments than expected

changelog/fix_make_styleidenticalconditionalbranches.md, lib/rubocop/cop/style/identical_conditional_branches.rb, spec/rubocop/cop/style/identical_conditional_branches_spec.rb
`Style/IdenticalConditionalBranches` was choking on ternaries, so this change allows it to register an offense without crashing. Ternaries are not corrected by this change.
=> [Fix #9959] Make `Style/IdenticalConditionalBranches` able to handle ternary `if`s

changelog/fix_fix_styleexplicitblockargument_adding_a.md, lib/rubocop/cop/style/explicit_block_argument.rb, lib/rubocop/cop/util.rb, spec/rubocop/cop/style/explicit_block_argument_spec.rb
When `Style/ExplicitBlockArgument` adds the block argument to a `def` or `send` node, if the node already had empty parentheses after it, the corrector would add a second set, ie:
```ruby
def my_method()
foo { yield }
end
```
would become 
```ruby
def my_method(&block)()
foo(&block)
end
```
In the original issue, once all these corrections (plus from `Lint/UnusedMethodArgument` and `Style/DefWithParentheses`) were resolved, the method would end up without a block argument.
Fixes #9955.
=> [Fix #9955] Fix `Style/ExplicitBlockArgument` adding a second set of parentheses

changelog/change_make_layout_leading_comment_space_aware_of_nodoc.md, lib/rubocop/cop/layout/leading_comment_space.rb, spec/rubocop/cop/layout/leading_comment_space_spec.rb
This PR makes `Layout/LeadingCommentSpace` aware of `#:nodoc`.
The following mention is the trigger.
https://twitter.com/kamipo/status/1421031611588485121
It seems that there was no definitive comment on whether to allow `#:nodoc:`.
- https://github.com/rubocop/rubocop/issues/277
- https://github.com/rubocop/rubocop/commit/db79146
I've look RDoc doc's example of Ruby 3.0 and it looks to include leading comment space.
```ruby
module MyModule # :nodoc:
class Input
end
end
module OtherModule # :nodoc: all
class Output
end
end
```
https://docs.ruby-lang.org/en/3.0.0/RDoc/Markup.html#class-RDoc::Markup-label-Controlling+what+is+documented
I also considered making it an option for the presence or absence of leading comment space in `#:nodoc:`, but I think it would be better to consistent it …
=> Make `Layout/LeadingCommentSpace` aware of `#:nodoc`

changelog/fix_an_infinite_loop_error_for_layout_hash_alignment.md, lib/rubocop/cop/layout/hash_alignment.rb, spec/rubocop/cli/autocorrect_spec.rb
Fixes #9954.
This PR fixes an infinite loop error for `Layout/HashAlignment` when `EnforcedStyle: with_fixed_indentation` is specified for `Layout/ArgumentAlignment`.
=> [Fix #9954] Fix an infinite loop error for `Layout/HashAlignment`

changelog/fix_a_false_autocorrection_for_layout_end_alignment.md, lib/rubocop/cop/layout/end_alignment.rb, spec/rubocop/cop/layout/end_alignment_spec.rb
Fixes #9953.
Fix an infinite loop error and a false auto-correction behavior for `Layout/EndAlignment` when using a conditional statement in a method argument.
=> [Fix #9953] Fix a false auto-correction behavior for `Layout/EndAlignment`

changelog/fix_inherit_mode-for-extensions.md, lib/rubocop/config_loader_resolver.rb, spec/rubocop/config_loader_spec.rb
See https://github.com/rubocop/rubocop-rspec/issues/1126
`config/default.yml`:
```yaml
RSpec:
Language:
Examples:
inherit_mode:
merge:
- Regular
Regular:
- it
- specify
- example
- scenario
- its
```
`.rubocop.yml`:
```yaml
require:
RSpec:
Language:
Examples:
Regular:
- mycustomexamplealias
```
Previously, locally-set `inherit_mode` in extension default configuration was not respected.
I'd love a preliminary review. If you're fine with the approach, I'll add a proper test coverage.
=> Fix `inherit_mode` for arrays in extension default

changelog/fix_parentheses_are_always_required_when_a.md, lib/rubocop/cop/style/method_def_parentheses.rb, spec/rubocop/cop/style/method_def_parentheses_spec.rb
Ruby requires parens around an argument list when argument forwarding is used.
Fixes #9975.
=> [Fix #9975] Parentheses are always required for `Style/MethodDefParentheses` when a forwarding argument (`...`) is used

changelog/change_enable_basic_autocorrection_for.md, lib/rubocop/cop/style/semicolon.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/style/semicolon_spec.rb
I noticed that `Style/Semicolon` doesn't do autocorrection, so this adds basic auto-correction (replaces semicolons between statements with a new line, indentation will be fixed by other cops).
A small autocorrection conflict between this and `Style/SingleLineMethods` is prevented by adding that to `autocorrect_incompatible_with` (which we need to document somewhere because I can never remember what it's called 😬).
=> Update `Style/Semicolon` to add autocorrection

changelog/fix_add_wholeword_configuration_to.md, config/default.yml, lib/rubocop/cop/naming/inclusive_language.rb, spec/rubocop/cop/naming/inclusive_language_spec.rb
This is a *naive* fix for #9957.
Allows `FlaggedTerms` to be set up to only match against a whole word (and enables it for `slave`). This allows false positives like `SLAVersion` and `TeslaVehicle` to not be flagged by the cop.
However, we don't have an inflector for identifiers, and this cop is explicitly case insensitive, which means that enabling this will also stop flagging partial word matches like `DatabaseSlave`. This really only affects class names since `database_slave` will still be flagged.
=> [Fix #9957] Add `WholeWord` configuration to `Naming/InclusiveLanguage`'s `FlaggedTerms` config

changelog/fix_redundant_sort_false_positive.md, lib/rubocop/cop/style/redundant_sort.rb, spec/rubocop/cop/style/redundant_sort_spec.rb
Currently, `Style/RedundantSort` doesn't allow `sort(_id: 1).first` and suggests `min(_id: 1)` but it's not equivalent.
```ruby
require 'bundler/inline'
gemfile do
source 'https://rubygems.org'
gem 'mongo'
end
mongo_client = Mongo::Client.new('mongodb://mongo/test')
mongo_client['users'].find.sort(_id: 1).first
mongo_client['users'].find.min(_id: 1)
```
~~* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).~~
=> Don't register an offense when sort method has arguments

changelog/fix_update_layoutspacebeforecomment_to.md, lib/rubocop/cop/layout/space_before_comment.rb, lib/rubocop/cop/layout/space_inside_parens.rb, lib/rubocop/cop/mixin/space_before_punctuation.rb, rubocop.gemspec, spec/rubocop/cop/layout/space_before_comma_spec.rb, spec/rubocop/cop/layout/space_before_comment_spec.rb, spec/rubocop/cop/layout/space_before_semicolon_spec.rb, spec/rubocop/cop/layout/space_inside_parens_spec.rb
This fixes false negatives involving heredocs for `Layout/SpaceBeforeComma`, `Layout/SpaceBeforeComment`, `Layout/SpaceBeforeSemicolon` and `Layout/SpaceInsideParens`.
These cops rely on `processed_source.tokens` to determine layout, but heredocs mix up the order of tokens which causes layout issues after heredocs to be missed. This change uses `processed_source.sorted_tokens` to resolve this.
~Because that method is currently private, in this PR each cop has a new private method that calls `processed_source.send(:sorted_tokens)`. I have opened rubocop/rubocop-ast#195 to move that method to be public, after which I will replace all these methods.~
Requires `rubocop-ast` >= 1.9.0.
[1]: …
=> Fix layout false negatives around heredocs

changelog/change_mark_unsafe_autocorrect_for_style_identical_conditional_branches.mdb, config/default.yml, lib/rubocop/cop/style/identical_conditional_branches.rb
Follow up to https://github.com/rubocop/rubocop/pull/9982#issuecomment-893950972
This PR marks `Style/IdenticalConditionalBranches` as unsafe auto-correction.
`Style/IdenticalConditionalBranches` cop is marked unsafe auto-correction as the order of method calls must be guaranteed in the following case:
```ruby
if method_that_modifies_global_state # 1
method_that_relies_on_global_state # 2
foo                                # 3
else
method_that_relies_on_global_state # 2
bar                                # 3
end
```
In such a case, auto-correction may change the invocation order.
=> Mark `Style/IdenticalConditionalBranches` as unsafe auto-correction

changelog/fix_indent_hash_values_in.md, lib/rubocop/cop/layout/line_end_string_concatenation_indentation.rb, spec/rubocop/cop/layout/line_end_string_concatenation_indentation_spec.rb
Make `Layout/LineEndStringConcatenationIndentation` work like `Layout/MultilineOperationIndentation` when `EnforcedStyle` is `indented`. This means that concatenated strings in hash literals shall be indented, just like other concatenated strings.
=> [Fix #9927] Indent hash values in LineEndStringConcatenationIndentation

spec/rubocop/cop/lint/duplicate_methods_spec.rb
See https://github.com/rubocop/rubocop-ast/pull/197#issuecomment-896167768.
This will be reverted once rubocop/rubocop-ast#197 is released.
=> Temporarily mark some `Lint/DuplicateMethods` specs as pending

changelog/fix_treat_casgn_nodes_like_other_assignment.md, lib/rubocop/cop/layout/space_around_operators.rb, spec/rubocop/cop/layout/space_around_operators_spec.rb
`casgn` nodes were being treated as "special assignment" which wasn't being laid out properly considering `Layout/ExtraSpacing`, and thus creating an infinite autocorrection loop.
Fixes #7422.
=> [Fix #7422] Treat `casgn` nodes like other assignment nodes in `Layout/SpaceAroundOperators`

lib/rubocop/cop/lint/duplicate_methods.rb, rubocop.gemspec, spec/rubocop/cop/lint/duplicate_methods_spec.rb
Requires rubocop/rubocop-ast#197 in order to fix `Node#parent_module_name`.
Properly handles the updated format of `parent_module_name` and adds tests to ensure the case from #5022 works.
Also reverts the pending tests in #9995.
=> [Fix #5022] Fix false negative for `Lint/DuplicateMethods` inside `class << self`

changelog/fix_incorrect_autocorrect_for_lint_ambiguous_regexp_literal.md, lib/rubocop/cop/lint/ambiguous_regexp_literal.rb, spec/rubocop/cop/lint/ambiguous_regexp_literal_spec.rb
Fixes #10002.
This PR fixes an incorrect auto-correct for `Lint/AmbigousRegexpLiteral` when using nested method arguments without parentheses.
=> [Fix #10002] Fix an incorrect auto-correct for `Lint/AmbigousRegexpLiteral`

Rakefile, changelog/new_parallel_static_analysis_by_default.md, lib/rubocop/cli.rb, lib/rubocop/options.rb, spec/rubocop/cli_spec.rb, spec/rubocop/options_spec.rb
Modern PCs have multi-core. RuboCop has `--parallel` option, but it is not used by default. This means that there is extra core resources for static analysis because multi-core is not being used effectively.
This PR will be parallel processing by default, so RuboCop will run faster in proportion to number of cores. Options that can be parallel processing, such as `--only`, `--except`, and others have the
same default behavior.
However, there are options that cannot be parallel processing, such as auto-correction and others, so they are serial processing as before.
`--parallel` can be a hidden option for some users. This change is expected to reduce user's wait time for running RuboCop.
Below is an example on my development PC.
Before:
```console
% cd path/to/rubocop
./exe/rubocop …
```
=> Parallel static analysis by default

changelog/change_mark_unsafe_autocorrect_for_style_commented_keyword.md, config/default.yml, lib/rubocop/cop/style/commented_keyword.rb
Fixes #9989
This PR mark unsafe auto-correct for `Style/CommentedKeyword` because it may remove meaningful comments.
=> [Fix #9989] Mark unsafe auto-correct for `Style/CommentedKeyword`

lib/rubocop/cop/style/block_delimiters.rb
Follow https://github.com/rubocop/rubocop/issues/7898#issuecomment-617181785
This PR updates the doc for `Style/BlockDelimiters` cop.
=> Update the doc for `Style/BlockDelimiters`

config/default.yml
`Style/WhenThen` cop looks like an implementation of "Semicolon in `when`" rule.
From https://rubystyle.guide/#one-line-cases to https://rubystyle.guide/#no-when-semicolons
=> Update `StyleGuide` URL for `Style/WhenThen`

lib/rubocop/cop/style/missing_else.rb, spec/rubocop/cop/style/missing_else_spec.rb
This PR adds doc and test for about pattern matching for `Style/MissingElse`.
Pattern matching is allowed to have no `else` branch because unlike already existing `if` and `case`,
it raises `NoMatchingPatternError` if the pattern does not match and without having `else`.
```ruby
case 'a'
in 'b'
end
```
=> Add doc and test for about pattern matching for `Style/MissingElse`

changelog/fix_false_positive_for_layout_rescue_ensure_alignment.md, lib/rubocop/cop/layout/rescue_ensure_alignment.rb, spec/rubocop/cop/layout/rescue_ensure_alignment_spec.rb
Fixes #9973.
This PR fixes a false positive for `Layout/RescueEnsureAlignment` when aligned `rescue` keyword and leading dot.
=> [Fix #9973] Fix a false positive for `Layout/RescueEnsureAlignment`

changelog/change_update_stylewordarray_to_register_an.md, config/default.yml, lib/rubocop/cop/mixin/percent_array.rb, lib/rubocop/cop/style/word_array.rb, spec/rubocop/cop/style/word_array_spec.rb
Updates `Style/WordArray` to mark `%w()` arrays as offenses if they contain any values with spaces.
Fixes #9962.
=> [Fix #9962] Update `Style/WordArray` to register an offense in `percent` style if any values contain spaces

changelog/fix_false_positive_for_style_identical_conditional_branches.md, lib/rubocop/cop/style/identical_conditional_branches.rb, spec/rubocop/cop/style/identical_conditional_branches_spec.rb
Fixes #9980.
This PR fixes a false positive for `Style/IdenticalConditionalBranches` when assigning to a variable used in a condition.
=> [Fix #9980] Fix a false positive for `Style/IdenticalConditionalBranches`

lib/rubocop/cop/documentation.rb
If you go to https://docs.rubocop.org/rubocop-rspec/2.0/upgrade_to_version_2.html, links to the second-level cops docs are broken. The last one is correct, https://docs.rubocop.org/rubocop-rspec/2.0/cops_rspec.html, while others have anchors, e.g. https://docs.rubocop.org/rubocop-rspec/2.0/upgrade_to_version_2.html#cops_capybara.adoc. This is probably due to `cops_docs.adoc` vs `cops_docs/` name clash.
Suspect: https://docs.antora.org/antora/2.3/page/page-id/#important
Ideally, we would generate `cops_rspec_capybara.adoc` instead of `cops_rspec/capybara.adoc.`
Other RuboCop extensions don't seem to make use of sub-departments, and will be unaffected by this change.
Related PR https://github.com/rubocop/rubocop-rspec/pull/1183 …
=> Fix sub-department cop doc generation

lib/rubocop/config_loader.rb
Minor fix to english sentence when new cops are introduced.
=> Fix english in pending banner text

lib/rubocop/cop/mixin/percent_array.rb, lib/rubocop/cop/style/symbol_array.rb, lib/rubocop/cop/style/word_array.rb, spec/rubocop/cop/style/symbol_array_spec.rb, spec/rubocop/cop/style/word_array_spec.rb
Fixes #10007 and #10008.
This PR tweaks offense message for `Style/WordArray` and `Style/SymbolArray` cops. It is a clear message suggested by #10008.
=> [Fix #10008] Tweak offense message for `Style/WordArray` and `Style/SymbolArray` cops

changelog/fix_fix_conflict_between.md, lib/rubocop/cop/style/sole_nested_conditional.rb, spec/rubocop/cli/autocorrect_spec.rb
When both `Style/SoleNestedConditional` and one of `Style/NegatedIf` or `Style/NegatedUnless` detect offenses on the same nested if, both corrections are applied, which results in the second clause of the resulting conditional to be inverted.
Fixes #10016.
=> [Fix #10016] Fix conflict between `Style/SoleNestedConditional` and `Style/NegatedIf` or `Style/NegatedUnless`

Gemfile, spec/rubocop/config_obsoletion_spec.rb
This PR bumps RuboCop Performance to 1.11 and prevents random build error https://github.com/rubocop/rubocop/pull/9721 cause by it.
=> Bump RuboCop Performance to 1.11

changelog/fix_error_for_rescue_ensure_alignment.md, lib/rubocop/cop/layout/rescue_ensure_alignment.rb, spec/rubocop/cop/layout/rescue_ensure_alignment_spec.rb
Follow up to https://github.com/rubocop/rubocop/pull/9974#issuecomment-899336636.
This PR fixes an error for `Layout/RescueEnsureAlignment` when using zsuper with block.
=> Fix an error for `Layout/RescueEnsureAlignment`

changelog/fix_false_positive_for_style_double_negation.md, lib/rubocop/cop/style/double_negation.rb, spec/rubocop/cop/style/double_negation_spec.rb
Fixes #10010.
This PR fixes a false positive for `Style/DoubleNegation` when `!!` is used at return location and before `rescue` keyword.
=> [Fix #10010] Fix a false positive for `Style/DoubleNegation`

changelog/fix_false_positive_for_style_redundant_self_assignment_branch.md, lib/rubocop/cop/style/redundant_self_assignment_branch.rb, spec/rubocop/cop/style/redundant_self_assignment_branch_spec.rb
Fixes #10011.
This PR fixes a false positive for `Style/RedundantSelfAssignmentBranch` when using instance variable, class variable, and global variable.
=> [Fix #10011] Fix a false positive for `Style/RedundantSelfAssignmentBranch`

changelog/fix_false_positive_for_style_redundant_begin.md, lib/rubocop/cop/style/redundant_begin.rb, spec/rubocop/cop/style/redundant_begin_spec.rb
Fixes #10004.
This PR fixes a false positive for `Style/RedundantBegin` when using one-liner with semicolon.
=> [Fix #10004] Fix a false positive for `Style/RedundantBegin`

changelog/fix_fix_styleencoding_to_handle_more.md, lib/rubocop/cop/style/encoding.rb, lib/rubocop/magic_comment.rb, spec/rubocop/cop/style/encoding_spec.rb, spec/rubocop/magic_comment_spec.rb
Refactors `Style/Encoding` to make use of the `MagicComment` class. Now `Style/Encoding` can handle the following situations:
* multiple encoding magic comments
* encoding magic comments following other magic comments
* magic comments containing multiple directives (only the encoding is removed)
Fixes #10014.
=> [Fix #10014] Fix `Style/Encoding` to handle more situations properly

changelog/fix_incorrect_autocorrect_for_redundant_self_assignment_branch.md, lib/rubocop/cop/style/redundant_self_assignment_branch.rb, spec/rubocop/cop/style/redundant_self_assignment_branch_spec.rb
Fixes #10024.
This PR fixes an incorrect auto-correct for `Style/RedundantSelfAssignmentBranch` when using multiline `if` / `else` conditional assignment.
=> [Fix #10024] Fix an incorrect auto-correct for `Style/RedundantSelfAssignmentBranch`

lib/rubocop/cop/style/hash_as_last_array_item.rb, spec/rubocop/cop/style/hash_as_last_array_item_spec.rb
**Fix autocorrect bug with HashAsLastArrayItem**
Fixes #9939 
When running autocorrect with:
```
Style/TrailingCommaInHashLiteral:
EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
EnforcedStyleForMultiline: comma
Style/HashAsLastArrayItem:
EnforcedStyle: no_braces
```
there was an edge case where it created incorrect code:
before autocorrect
```
x = [
1,
{
a: 1,
b: 2,
},
]
```
after autocorrect:
```
x = [
1,
a: 1,
b: 2,
,
]
```
With this PR, the result of applying autocorrect makes executable code =>
```
x = [
1,
a: 1,
b: 2,
]
```
- The PR contains commits that are not squashed, that's because I specifically wanted to receive feedback before and ***then I can squash the two commits*** (this way I can show the two approaches)
- The first commit represents the original …
=> [Fix #9939] Fix/hash as last array item

CHANGELOG.md, changelog/change_recognize_shareable_constant_value_magic.md, lib/rubocop/cop/style/mutable_constant.rb, spec/rubocop/cop/style/mutable_constant_spec.rb, spec/rubocop/magic_comment_spec.rb
Ruby 3.0 supports [shareable_constant_value](https://docs.ruby-lang.org/en/3.0.0/doc/syntax/comments_rdoc.html#label-shareable_constant_value+Directive)  magic comment. This PR updates Style/MutableConstant to honour shareable_constant_value magic comment.
Fixes [#9328](https://github.com/rubocop/rubocop/issues/9328)
Took PR [9410](https://github.com/rubocop/rubocop/pull/9410) as reference. Tried to add @caalberts as co-author in changelog, but changelog spec fails.
=> [Fix rubocop#9328] Honour shareable_constant_value magic comment

changelog/change_interpolated_string_literals_are_no.md, lib/rubocop/cop/mixin/frozen_string_literal.rb, lib/rubocop/cop/style/frozen_string_literal_comment.rb, lib/rubocop/cop/style/mutable_constant.rb, lib/rubocop/cop/style/redundant_freeze.rb, spec/rubocop/cop/style/mutable_constant_spec.rb, spec/rubocop/cop/style/redundant_freeze_spec.rb
Note, this PR is strongly inspired by https://github.com/rubocop/rubocop/pull/8743. Kudos to @sambostock :heart: 
----
Since [Ruby 3.0 or higher](https://bugs.ruby-lang.org/issues/17104) interpolated strings are not frozen automatically anymore.
Therefore, two changes must happen to how we treat interpolated literals
* `Style/MutableConstant` should enforce freezing them
* `Style/RedundantFreeze` should not consider it redundant to freeze them
The behaviour for Ruby 2.7 or lower is kept.
=> Address `frozen_string_literal` no longer applying to interpolated strings in Ruby 3.0 or higher

lib/rubocop/config_loader.rb, spec/rubocop/cli/options_spec.rb
Follow up to #8414.
Perhaps the parentheses used in the old plain-text format message remain.
In the current YAML format comment it would look redundant.
```console
- Gemspec/DateAssignment (1.10)
```
```console
Gemspec/DateAssignment: # (new in 1.10)
Enabled: true
```
```console
Gemspec/DateAssignment: # new in 1.10
Enabled: true
```
=> Remove redundant parentheses in pending cops message

changelog/change_add_rubyjard_debugger_calls_to.md, config/default.yml, lib/rubocop/cop/lint/debugger.rb, spec/rubocop/cop/lint/debugger_spec.rb
This PR adds a call to [RubyJard](https://rubyjard.org/) debugger, which is `jard`, to `Lint/Debugger/DebuggerMethods`
=> Add `RubyJard` debugger calls to Lint/Debugger/DebuggerMethods

changelog/change_mark_style_struct_inheritance_as_unsafe_auto_correction.md, config/default.yml, lib/rubocop/cop/style/struct_inheritance.rb
Fixes #10036.
This PR marks `Style/StructInheritance` as unsafe auto-correction.
=> [Fix #10036] Mark `Style/StructInheritance` as unsafe auto-correction

changelog/fix_an_incorrect_autocorrect_for_style_block_delimiters.md, lib/rubocop/cop/style/block_delimiters.rb, spec/rubocop/cop/style/block_delimiters_spec.rb
Fixes #10033.
This PR fixes an incorrect auto-correct for `Style/BlockDelimiters` when there is a comment after the closing brace and using method chain.
=> [Fix #10033] Fix an incorrect auto-correct for `Style/BlockDelimiters`

changelog/fix_false_positive_for_style_hash_except.md, lib/rubocop/cop/style/hash_except.rb, spec/rubocop/cop/style/hash_except_spec.rb
Fixes #10031.
This PR fixes a false positive for `Style/HashExcept` when comparing with hash value.
=> [Fix #10031] Fix a false positive for `Style/HashExcept`

changelog/new_make_lint_debugger_aware_of_debug_rb.md, config/default.yml, lib/rubocop/cop/lint/debugger.rb, spec/rubocop/cop/lint/debugger_spec.rb
This PR makes `Lint/Debugger` aware of debug.rb.
https://github.com/ruby/debug
debug.rb has `binding.break` and `binding.b` commands (`b` for short).
=> Make `Lint/Debugger` aware of debug.rb

changelog/fix_updated_annotationcomment_to_be_able_to.md, config/default.yml, lib/rubocop.rb, lib/rubocop/cop/mixin/annotation_comment.rb, lib/rubocop/cop/mixin/documentation_comment.rb, lib/rubocop/cop/style/comment_annotation.rb, spec/rubocop/cop/annotation_comment_spec.rb, spec/rubocop/cop/style/comment_annotation_spec.rb
This change first refactors `AnnotationComment` to be an actual class modeling an annotation comment, and then updates it to be able to handle multiword phrases as annotation keywords.
With config:
```yaml
Style/CommentAnnotation:
Keywords:
- TODO
- TODO LATER
```
```sh
test.rb:1:1: C: [Correctable] Style/CommentAnnotation: Annotation keywords like TODO LATER should be all upper case, followed by a colon, and a space, then a note describing the problem.
^^^^^^^^^^^
```
Fixes #6630.
=> [Fix #6630] Updated `Style/CommentAnnotation` to be able to handle multiword keyword phrases

changelog/fix_a_false_positive_for_style_redundant_sort.md, lib/rubocop/cop/style/redundant_sort.rb, spec/rubocop/cop/style/redundant_sort_spec.rb
Fixes #10061.
This PR fixes a false positive for `Style/RedundantSort` when using `size` method in the block.
=> [Fix #10061] Fix a false positive for `Style/RedundantSort`

changelog/fix_a_false_positive_for_layout_single_line_block_chain.md, lib/rubocop/cop/layout/single_line_block_chain.rb, spec/rubocop/cli/autocorrect_spec.rb, spec/rubocop/cop/layout/single_line_block_chain_spec.rb
This PR fixes the following incorrect auto-correct for `Layout/SingleLineBlockChain` when method call chained on a new line after a single line block with trailing dot.
It also fixes the following incorrect auto-correction between `Layout/SingleLineBlockChain` and `Layout/DotPosition` cops.
```console
example.select { |item| item.cond? }.
join('-')
Syntax OK
% bundle exec rubocop -a --only Layout/DotPosition,Layout/SingleLineBlockChain example.rb
example.select { |item| item.cond? }
.join('-')
example.rb:3: syntax error, unexpected '.', expecting end-of-input
.join('-')
```
=> Fix a false positive for `Layout/SingleLineBlockChain`

changelog/fix_hardcoded_block_parameter_name.md, lib/rubocop/cop/style/explicit_block_argument.rb, spec/rubocop/cop/style/explicit_block_argument_spec.rb
The autocorector would generate invalid code if the old code already defined the block parameter with any other name than `&block`.
=> Style/ExplicitBlockArgument: do not assume the block parameter name

changelog/fix_error_for_lint_number_conversion.md, lib/rubocop/cop/lint/number_conversion.rb, spec/rubocop/cop/lint/number_conversion_spec.rb
This PR fixes the following error for `Lint/NumberConversion` when using nested number conversion methods.
```console
var.to_i.to_f
% bundle exec rubocop --only Lint/NumberConversion -A
(snip)
An error occurred while Lint/NumberConversion cop was inspecting
/Users/koic/src/github.com/koic/rubocop-issues/number/example.rb:1:0.
W
Offenses:
example.rb:1:1: W: [Corrected] Lint/NumberConversion: Replace unsafe
number conversion with number class parsing, instead of using
var.to_i.to_f, use stricter Float(var.to_i).var.to_i.to_f
^^^^^^^^^^^^^
example.rb:1:7: W: [Corrected] Lint/NumberConversion: Replace unsafe
number conversion with number class parsing, instead of using var.to_i,
use stricter Integer(var, …
```
=> Fix an error for `Lint/NumberConversion`

changelog/change_mark_style_and_or_as_unsafe_auto_correction.md, config/default.yml, lib/rubocop/cop/style/and_or.rb, spec/rubocop/cli/autocorrect_spec.rb
This PR marks `Style/AndOr` as unsafe auto-correction.
cf: https://github.com/rubocop/rubocop-rails/issues/210
=> Mark `Style/AndOr` as unsafe auto-correction

changelog/fix_false_positive_for_style_mutable_constant.md, lib/rubocop/cop/mixin/frozen_string_literal.rb, spec/rubocop/cop/style/mutable_constant_spec.rb
Fixes #10070.
This PR fixes a false positive for `Style/MutableConstant` when using non-interpolated heredoc in Ruby 3.0.
=> [Fix #10070] Fix a false positive for `Style/MutableConstant`

changelog/change_update_naminginclusivelanguage_to_be.md, config/default.yml, lib/rubocop/cop/naming/inclusive_language.rb, spec/rubocop/cop/naming/inclusive_language_spec.rb
Changes `Naming/InclusiveLanguage` to be disabled by default, and updates the offense message to be more neutral.
=> Update `Naming/InclusiveLanguage` to be disabled by default.

changelog/fix_fix_layoutlinelength_reported_length.md, lib/rubocop/cop/layout/line_length.rb, spec/rubocop/cop/layout/line_length_spec.rb
If `IgnoreCopDirectives` is enabled, the directive comment is not included in the calculation, but it is included in the count that is shown in the offense. This change makes it not be included there either.
=> Fix `Layout/LineLength` reported length when ignoring directive comments

changelog/fix_fix_how_mindigits_is_calculated_for.md, lib/rubocop/cop/style/numeric_literals.rb, lib/rubocop/rspec/cop_helper.rb, spec/rubocop/cop/layout/line_length_spec.rb, spec/rubocop/cop/style/numeric_literals_spec.rb
Previously, `MinDigits` is incremented regardless of if the offense is disabled or not.
Fixes #10066.
=> [Fix #10066] Fix how `MinDigits` is calculated for `Style/NumericLiterals` when generating a configuration file

lib/rubocop/cop/metrics/abc_size.rb
When I introduce ABC to people, they don't know how to interpret the numbers. Having a scale like this might help.
I'm basing this proposed scale partly on my own experience, and partly on CodeClimate, which uses a similar metric called `flog`.
> What’s a good Flog score? It’s subjective, of course, but Jake Scruggs .. suggested that scores above 20 indicate the method may need refactoring, and above 60 is dangerous. Similarly, Code Climate will flag methods with scores above 25, and considers anything above 60 “very complex”.
> https://codeclimate.com/blog/deciphering-ruby-code-metrics/
We can't directly compare `flog` scores and ABC, but the above is still a useful reference in determining our own scale.
* N/A Commit message starts with `[Fix #issue-number]` (if the …
=> Docs: Interpreting ABCSize

spec/rubocop/cop/layout/case_indentation_spec.rb
This test has been around for a while but eventually was [changed](https://github.com/rubocop/rubocop/commit/ddb1ba77c7947e04a226fe57ae7789c2eca7a74b#diff-cbedb596a9e288e54ae57df6b0110c55194521811c147de4a0dbb9f6749af655L597-R447) to use `expect_corrections`, and then the test statement was [inverted](https://github.com/rubocop/rubocop/commit/9a06e8407cde299fe4814292d9b7ff0f83723f9e#diff-cbedb596a9e288e54ae57df6b0110c55194521811c147de4a0dbb9f6749af655L435-R435) accidentally.
This fixes up the test to be clearer.
=> Fix confusing test in case_indentation_spec.rb

lib/rubocop/rspec/expect_offense.rb, spec/rubocop/cop/layout/line_length_spec.rb, spec/rubocop/cop/lint/heredoc_method_call_position_spec.rb, spec/rubocop/cop/lint/script_permission_spec.rb, spec/rubocop/cop/style/empty_else_spec.rb
If autocorrection doesn't change anything, `expect_no_corrections` is clearer about what will happen (vs having to figure out if there is some small change that is not immediately evident). This change also fixes the existing specs that use the wrong method.
=> Guard against `expect_corrections` with no changes

lib/rubocop/cop/lint/binary_operator_with_identical_operands.rb
In #9221, `Lint/BinaryOperatorWithIdenticalOperands` was updated to ignore some simple arithmetic operands, but this was not reflected in the documentation.
=> Update the documentation for `Lint/BinaryOperatorWithIdenticalOperands`

changelog/change_lintbooleansymbol_should_be_marked_as.md, config/default.yml
Although the correction is unsafe, the cop itself will not find false positives.
=> `Lint/BooleanSymbol` should be marked as `SafeAutoCorrect: false` rather than `Safe: false`

changelog/fix_false_negative_for_style_arguments_forwarding.md, lib/rubocop/cop/style/arguments_forwarding.rb, spec/rubocop/cop/style/arguments_forwarding_spec.rb
Fixes #10090.
This PR fixes a false negative for `Style/ArgumentsForwarding` when using only kwrest arg.
=> [Fix #10090] Fix a false negative for `Style/ArgumentsForwarding`

changelog/fix_fix_lintambiguousoperatorprecedence_with.md, lib/rubocop/cop/lint/ambiguous_operator_precedence.rb, spec/rubocop/cop/lint/ambiguous_operator_precedence_spec.rb
=> [Fix #10096] Fix `Lint/AmbiguousOperatorPrecedence` with `and`/`or` operators

changelog/new_allow_http_protocol_to_bundler_insecure_protocol_source.md, config/default.yml, lib/rubocop/cop/bundler/insecure_protocol_source.rb, spec/rubocop/cop/bundler/insecure_protocol_source_spec.rb
Fixes #10103.
This PR adds `AllowHttpProtocol` option to `Bundler/InsecureProtocolSource`.
This `AllowHttpProtocol` option is `true` by default for safe autocorrection.
If user don't allow `http://`, set `false` to the option.
=> [Fix #10103] Add `AllowHttpProtocol` option to `Bundler/InsecureProtocolSource`

lib/rubocop/cop/naming/block_parameter_name.rb
Fix a typo in docs for config option name for Naming/BlockParameterName in the code example
=> Typo in docs for config option for Naming/BlockParameterName

changelog/fix_redundant_freeze_env_values.md, lib/rubocop/cop/style/redundant_freeze.rb, spec/rubocop/cop/style/redundant_freeze_spec.rb
Ref: https://github.com/rubocop/rubocop/pull/6784
`ENV["foo"]` returns a new mutable string on every call.
```ruby
>> ENV["PATH"].frozen?
=> true
>> ENV["PATH"].object_id
=> 260
>> ENV["PATH"].object_id
=> 280
```
As such it's perfectly legitimate to freeze them in a pattern such as:
```ruby
PATH = ENV["PATH"].freeze
```
=> `Style/RedundantFreeze` stop considering `ENV` values as immutable

changelog/fix_update_layoutdotposition_to_be_able_to.md, lib/rubocop/cop/layout/dot_position.rb, spec/rubocop/cop/layout/dot_position_spec.rb
Updates `Layout/DotPosition` to be able to detect misplaced dots when the dot is on the same line as a heredoc start.
Fixes #10110.
=> [Fix #10110] Update `Layout/DotPosition` to be able to handle heredocs

docs/modules/ROOT/pages/development.adoc, lib/rubocop/cop/generator.rb, spec/rubocop/cop/generator_spec.rb, tasks/new_cop.rake
I also removed `github_user` from the Generator as it is no longer necessary (since the changelog rake tasks insert the username themselves).
=> Update the `rake new_cop` instructions for changelogs

lib/rubocop/cop/lint/require_relative_self_path.rb, spec/rubocop/cop/lint/require_relative_self_path_spec.rb
Running RuboCop on `rubocop-ast`:
```sh
lib/rubocop/ast/node_pattern/lexer.rb:4:3: W: [Correctable] Lint/RequireRelativeSelfPath: Remove the require_relative that requires itself.
require_relative 'lexer.rex'
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/rubocop/ast/node_pattern/parser.rb:3:1: W: [Correctable] Lint/RequireRelativeSelfPath: Remove the require_relative that requires itself.
require_relative 'parser.racc'
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Those files are requiring different files but they have the same name so `Lint/RequireRelativeSelfPath` is registering a false positive. This change fixes that.
=> Fix false positive for `Lint/RequireRelativeSelfPath` when requiring  file with the same name but different extension

lib/rubocop/cop/bundler/ordered_gems.rb, lib/rubocop/cop/correctors/ordered_gem_corrector.rb, lib/rubocop/cop/gemspec/ordered_dependencies.rb, lib/rubocop/cop/mixin/ordered_gem_node.rb, spec/rubocop/cop/team_spec.rb
=> Use `Cop::Base` for `Bundler/OrderedGems` and `Gemspec/OrderedDependencies`

changelog/fix_fix_crash_with_styleredundantsort_when.md, lib/rubocop/cop/style/redundant_sort.rb, spec/rubocop/cop/style/redundant_sort_spec.rb
The check added in #10062 for `size` wasn't handling blocks that aren't just a single send node. Fixes #10118.
=> [Fix #10118] Fix crash with `Style/RedundantSort` when the block doesn't only contain a single `send` node

changelog/fix_fix_styleredundantself_for_pattern.md, lib/rubocop/cop/style/redundant_self.rb, spec/rubocop/cop/style/redundant_self_spec.rb
A `match-as` node creates a local variable within an `in-pattern` node that wasn't being registered by `Style/RedundantSelf`. 
=> [Fix #10106] Fix `Style/RedundantSelf` for pattern matching

changelog/fix_fix_configuration_loading_to_not_raise.md, lib/rubocop/config.rb, lib/rubocop/config_loader.rb, lib/rubocop/config_validator.rb, spec/rubocop/config_loader_spec.rb
Previously, when a configuration file inherits another that sets `TargetRubyVersion` to an obsolete version, a config validation error is raised by RuboCop. This causes an irreconcilable issue if the inherited config is shared with other projects or not editable (from upstream, etc.).
In order to fix this, the target ruby version check is moved to happen after all the config resolution steps have completed, so at that point, all the various `TargetRubyVersion` values have been collapsed into a single value that can be verified. This allows for any number of complicated inheritence chains without causing issues.
Fixes #9934.
=> [Fix #9934] Fix configuration loading to not raise an error for an obsolete ruby version that is overridden

changelog/new_space_inside_parens_compact.md, config/default.yml, lib/rubocop/cop/layout/space_inside_parens.rb, spec/rubocop/cop/layout/space_inside_parens_spec.rb
```yml
Layout/SpaceInsideParens:
EnforcedStyle: compact
```
```ruby
@example 
f(3)
g = (a + 3)
y( )
g( f( x ) )
g( f( x( 3 ) ), 5 )
f( 3 )
g = ( a + 3 )
y()
g( f( x ))
g( f( x( 3 )), 5 )
```
=> Implemented Layout/SpaceInsideParens with EnforcedStyle: compact

changelog/change_update_lintelselayout_to_be_able_to.md, lib/rubocop/cop/lint/else_layout.rb, lib/rubocop/cop/util.rb, spec/rubocop/cop/lint/else_layout_spec.rb
This was previously explicitly ignored since the cop's first version, but I'm not really sure why. I think this is probably preferable.
Fixes #10130.
=> [Fix #10130] Update `Lint/ElseLayout` to be able to handle an `else` with only a single line

changelog/fix_fix_layoutredundantlinebreak_adding.md, lib/rubocop/cop/layout/dot_position.rb, lib/rubocop/cop/layout/redundant_line_break.rb, lib/rubocop/cop/mixin/heredoc.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/config_spec.rb, spec/rubocop/cop/layout/case_indentation_spec.rb, spec/rubocop/cop/layout/redundant_line_break_spec.rb, spec/rubocop/options_spec.rb, spec/rubocop/result_cache_spec.rb
When `Layout/RedundantLineBreak` finds a multiline method chain that can be collapsed to a single line, it adds an extra space between each method. Although the spaces could also be detected by `Layout/SpaceAroundMethodCallOperator`, this change allows the cop to calculate if a correction will fit on the line better (as demonstrated by the fixes in the 2nd commit).
```ruby
foo.
bar.
baz
```
Before:
```ruby
foo. bar. baz
```
After:
```ruby
foo.bar.baz
```
=> Fix `Layout/RedundantLineBreak` adding extra space within method chains

spec/rubocop/cli/options_spec.rb, spec/rubocop/config_loader_spec.rb, spec/rubocop/cop/internal_affairs/undefined_config_spec.rb, spec/support/cops/class_must_be_a_module_cop.rb, spec/support/cops/module_must_be_a_class_cop.rb
This should replace be the last official uses of `Cop` in RuboCop itself. Follows #7868.
=> Replace `Cop` with `Base` in tests to prepare for deprecating `Cop`

changelog/change_update_styleredundantsort_to_be_unsafe.md, config/default.yml, lib/rubocop/cop/style/redundant_sort.rb, spec/rubocop/cop/style/redundant_sort_spec.rb
In an array where there are multiple elements where `a <=> b == 0`, or where the transformation done by the block has the same result, there will be a different element returned between `sort.last` and `max` (or `sort_by.last` and `max_by`), because `sort.last` will take the last element but `max` will return the first element. As such, this is not a safe change, as the specific element returned will change.
Honestly, we should probably revert #10062 as well because that adds a special case for `size` that doesn't really exist in reality. In that issue, `size` was the catalyst, but the exact same issue would happen with `length`, or any other transformation that results in multiple elements having the same value. If we revert #10062, then #10119 can be closed as well. If this is desired, …
=> Update `Style/RedundantSort` to be unsafe

changelog/new_add_new_security_io_read_cop.md, config/default.yml, lib/rubocop.rb, lib/rubocop/cop/security/io_methods.rb, spec/rubocop/cli/options_spec.rb, spec/rubocop/cop/generator_spec.rb, spec/rubocop/cop/security/io_methods_spec.rb
Follow up to https://github.com/rubocop/rubocop/pull/9695#issuecomment-820151271.
This PR adds new `Security/IoMethods` cop.
It checks for the first argument to `IO.read`, `IO.binread`, `IO.write`, `IO.binwrite`, `IO.foreach`, and `IO.readlines`.
If argument starts with a pipe character (`'|'`) and the receiver is the `IO` class, a subprocess is created in the same way as `Kernel#open`, and its output is returned.
Consider to use `File.read` to disable the behavior of subprocess invocation.
This cop is unsafe because false positive will occur if the variable passed as the first argument is a command that is not a file path.
```ruby
IO.read(path)
IO.read('path')
File.read(path)
File.read('path')
IO.read('| command') # Allow intentional command invocation.
```
Below are links related to …
=> Add new `Security/IoMethods` cop

changelog/fix_causing_a_variable_to_be_shadowed.md, lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb, spec/rubocop/cop/naming/rescued_exceptions_variable_name_spec.rb
Fixes #9588
Fix causing a variable to be shadowed from outside the rescue block. 
=> [Fix #9588] Fix causing a variable to be shadowed from outside the rescue block

changelog/fix_update_lintassignmentincondition_to_not.md, lib/rubocop/cop/lint/assignment_in_condition.rb, spec/rubocop/cop/lint/assignment_in_condition_spec.rb
Assignments within a block are not relevant to this cop because they don't affect the same scope.
Fixes #10136.
=> [Fix #10136] Update `Lint/AssignmentInCondition` to not consider assignments within blocks in conditions

changelog/fix_update_stylemutableconstant_to_not.md, lib/rubocop/cop/mixin/frozen_string_literal.rb, lib/rubocop/cop/style/mutable_constant.rb, spec/rubocop/cop/style/mutable_constant_spec.rb
In #10006 `Style/MutableConstant` was updated to consider `dstr` nodes as unfrozen in Ruby 3.0 even when `frozen_string_literal: true` is specified, and requires `.freeze` on those strings. However, a multiline string is considered a `dstr` node but does not contain interpolation so would still be frozen.
```ruby
CONST = 'foo' \
'bar'
CONST.frozen? #=> true
```
Fixes #10134.
=> [Fix #10134] Update `Style/MutableConstant` to not consider multiline uninterpolated strings as unfrozen in ruby 3.0

.rubocop.yml, changelog/fix_fix_stylewordarray_to_exclude_files_in.md, lib/rubocop/cop/mixin/percent_array.rb, spec/rubocop/cop/style/word_array_spec.rb
When `Style/WordArray` is in `percent` style, offenses are registered for percent arrays that contain "invalid" characters, in order to replace them with a bracketed array instead. However, when this is the case, `--auto-gen-config` doesn't handle the file properly. This updates it to exclude the file since the result is inconsistent.
Fixes #10135.
=> [Fix #10135] Fix `Style/WordArray` to exclude files in `--auto-gen-config` when `percent` style is given but brackets are required

CHANGELOG.md, relnotes/v1.22.0.md
Added changelog for #10132 and moved #8431 from changes to new features.
=> Minor update to changelog and release notes

changelog/fix_fix_false_positive_for_layoutdotposition.md, lib/rubocop/cop/layout/dot_position.rb, spec/rubocop/cop/layout/dot_position_spec.rb
The fix in #10113 caused a false positive when a heredoc receives a method on the same line as its start, such as
```ruby
<<HEREDOC.squish
foo
HEREDOC
```
This should not have registered an offense because the dot is on the same line as the receiver.
Fixes #10140.
=> [Fix #10140] Fix false positive for `Layout/DotPosition` when a heredoc receives a method on the same line as the start sigil in `trailing` style

changelog/fix_an_error_for_lint_require_relative_self_path.md, lib/rubocop/cop/lint/require_relative_self_path.rb, spec/rubocop/cop/lint/require_relative_self_path_spec.rb
Fixes #10143.
This PR fixes an error for `Lint/RequireRelativeSelfPath` when using a variable as an argument of `require_relative`.
=> [Fix #10143] Fix an error for `Lint/RequireRelativeSelfPath`

lib/rubocop/cop/style/quoted_symbols.rb
Follow-up to https://github.com/rubocop/rubocop/issues/10154#issuecomment-932497540.
Improves documentation for `Style/QuotedSymbols` to clarify what style is chosen by default when not configured.
=> Clarify documentation for `Style/QuotedSymbols`

lib/rubocop/config_loader.rb, lib/rubocop/rake_task.rb, lib/rubocop/result_cache.rb, lib/rubocop/runner.rb, spec/rubocop/cli_spec.rb
Fix some instances of `rubocop` => `RuboCop`.
=> Fix inconsistent capitalization of `RuboCop`

changelog/fix_fix_stylequotedsymbols_handling_escaped.md, lib/rubocop/cop/mixin/string_literals_help.rb, lib/rubocop/cop/style/quoted_symbols.rb, lib/rubocop/cop/util.rb, spec/rubocop/cop/style/quoted_symbols_spec.rb, spec/rubocop/cop/style/string_literals_spec.rb
Two cases are improved here:
1. Escaped double quotes (`\"`) within a double-quoted string are handled correctly (replaced with an unescaped double quote) when converting to a single-quoted string.
2. Escaped backslashes (`\\`) are treated properly and not doubled for both single- and double-quoted strings.
Fixes #10148.
=> [Fix #10148] Fix `Style/QuotedSymbols` handling escaped characters incorrectly

changelog/fix_update_styleselectbyregexp_to_ignore.md, lib/rubocop/cop/style/select_by_regexp.rb, spec/rubocop/cop/style/select_by_regexp_spec.rb
Since `hash.grep` does not work in the same way as other enumerables, this update looks for receivers that look like hashes and does not register `Style/SelectByRegexp` offenses on them. This includes literal hashes (`{}`), `Hash.new`, `Hash[]`, `to_h` and `to_hash` (the latter two could potentially cause a false negative if they're overridden to not return hashes, but I can live with that).
I added explicit tests for receivers that I have confirmed works as expected (array, range, set). In case we ever extend this with more exceptions those will be covered.
Fixes #10145.
=> [Fix #10145] Update `Style/SelectByRegexp` to ignore cases where the receiver appears to be a hash

lib/rubocop/cop/internal_affairs.rb, lib/rubocop/cop/internal_affairs/location_line_equality_comparison.rb, lib/rubocop/cop/layout/end_alignment.rb, lib/rubocop/cop/mixin/statement_modifier.rb, lib/rubocop/cop/style/multiline_in_pattern_then.rb, lib/rubocop/cop/style/multiline_when_then.rb, lib/rubocop/cop/util.rb, spec/rubocop/cop/internal_affairs/location_line_equality_comparison_spec.rb
This cop enforces the use of `same_line?` instead of location line comparison for equality.
```ruby
node.loc.line == node.parent.loc.line
same_line?(node, node.parent)
```
=> Add new `InternalAffairs/LocationLineEqualityComparison` cop

tasks/changelog.rb
I noticed that the changelog specs were outputting text by accident, there was a leftover debugging puts.
=> Removed stray `puts` from changelog.rb

changelog/fix_false_positive_for_style_parentheses_around_condition.md, lib/rubocop/cop/style/parentheses_around_condition.rb, spec/rubocop/cop/style/parentheses_around_condition_spec.rb
Fixes #10227.
This PR fixes a false positive for `Style/ParenthesesAroundCondition` when parentheses in multiple expressions separated by semicolon.
=> [Fix #10227] Fix a false positive for `Style/ParenthesesAroundCondition`

changelog/fix_a_false_positive_for_style_string_literals.md, lib/rubocop/cop/mixin/string_literals_help.rb, lib/rubocop/cop/style/quoted_symbols.rb, spec/rubocop/cop/style/string_literals_spec.rb
Follow up to https://github.com/rubocop/rubocop/pull/10166#issuecomment-956190960.
This PR fixes a false positive for `Style/StringLiterals` when `EnforcedStyle: double_quotes` and using single quoted string with backslash.
It has moved a separate implementation for `Style/QuotedSymbols` to resolve #10152 to `Style/QuotedSymbols` to prevent impact on `Style/StringLiterals`'s false positives.
=> Fix a false positive for `Style/StringLiterals`

changelog/fix_format_string_token_nested_ignored_methods.md, lib/rubocop/cop/style/format_string_token.rb, spec/rubocop/cop/style/format_string_token_spec.rb
=> [Fix #10203] Fix `Style/FormatStringToken` to respect `IgnoredMethods` with nested structures

changelog/change_make_lint_number_conversion_aware_of_rational.md, lib/rubocop/cop/lint/number_conversion.rb, spec/rubocop/cop/lint/number_conversion_spec.rb
This PR makes `Lint/NumberConversion` aware of `to_r`. It treats `Rational` the same as` Integer`, `Float`, and `Complex`.
=> Make `Lint/NumberConversion` aware of `to_r`

changelog/fix_inherit_from_remote_should_follow_remote_includes_path.md, lib/rubocop/remote_config.rb, spec/rubocop/remote_config_spec.rb
Fixes #10174.
This PR is fix inherit_from_remote should follow remote includes path starting with `./`
In the example of issue, it tries to load `./base.yml` in the same hierarchy as `ruby-2.7.yml`, but the uri of `./base.yml` is 
`https://raw.githubusercontent.com/testdouble/standard/main/config/./base.yml`.
If the uri is `https:// ~ /./base.yml`, [ ConfigLoaderResolver#remote_file?](https://github.com/rubocop/rubocop/blob/df440defe93aa94306fe22b674be7214edcfa4b9/lib/rubocop/config_loader_resolver.rb#L221) returns false, so an instance of URI::Generic is created and an error occurs.
In this PR, if remote includes path starts with `./`, it will be removed.
=> [Fix #10174] Fix inherit_from_remote should follow remote includes path starting with `./`

rubocop.gemspec
Ruby gems now allows MFA to be required for pushes: https://guides.rubygems.org/mfa-requirement-opt-in/
This allows users to have confidence that the actual authors were responsible for updates (obviously that doesn't mean that it can't be a malicious update, but at least it's not from someone who got access to a pusher's account).
I don't have push access but I hope all of us who do have MFA set up anyways (and if anyone doesn't it's easy to set up).
If this is acceptable, I'd like to create a cop to check for this as well.
=> Require MFA for gem pushes

lib/rubocop/cop/style/empty_method.rb
=> Fix bad indenting in docs

CONTRIBUTING.md, spec/project_spec.rb
The changelog entry file format doesn't require a link to GitHub account URL (`[@username]: https://github.com/username`), so contributors can write it in one line.
This PR tweaks CONTRIBUTING.md and adds a project spec for that.
It will prevent the following breaking changelog generation.
https://github.com/rubocop/rubocop/commit/f598124
=> Tweak changelog format doc and add a project spec

changelog/fix_last_column_number_for_json_formatter.md, lib/rubocop/formatter/json_formatter.rb, spec/rubocop/formatter/json_formatter_spec.rb
Fixes #10241.
This PR fixes `last_column` value for `JSONFormatter`.
The minimum value of `start_column: real_column` is 1. So, the minimum value of `last_column` should be 1.
And non-zero value of `last_column` should be used as is.
This patch to `last_column` seems to be required only for `JSONFormatter` and not required for other formatters.
It solves a potential `JSONFormatter` issue for cops that use `add_global_offense`.
=> [Fix #10241] Fix `last_column` value for `JSONFormatter`

changelog/fix_a_false_positive_for_lint_ambiguous_range.md, lib/rubocop/cop/lint/ambiguous_range.rb, spec/rubocop/cop/lint/ambiguous_range_spec.rb
Fixes #10230.
This PR fixes a false positive for `Lint/AmbiguousRange` when a range is composed of some literals.
If it's just literals, it's clear even without parentheses, so this PR will accept them.
=> [Fix #10230] Fix a false positive for `Lint/AmbiguousRange`

changelog/change_update_namingfilename_to_recognize.md, config/default.yml, lib/rubocop/cop/naming/file_name.rb, spec/rubocop/cop/naming/file_name_spec.rb
Allows `Struct`s assigned to constants to be used for `ExpectMatchingDefinition` of `Naming::FileName`.
Allow refactors the cop's tests to use `expect_offense` and adds some documentation for options that aren't explained.
Fixes #10221.
=> [#10221] Update `Naming::FileName` to recognize `Struct`s as classes that satisfy the `ExpectMatchingDefinition` requirement

config/default.yml
This PR adds [rubocop-graphql](https://github.com/DmitryTsepelev/rubocop-graphql) to the `SuggestExtensions` list.
=> Add rubocop-graphql to suggested extensions

changelog/change_namingfilename_make.md, config/default.yml, lib/rubocop/cop/naming/file_name.rb, spec/rubocop/cop/naming/file_name_spec.rb
fixes https://github.com/rubocop/rubocop/issues/10220
confirmed that it fixes the issue:
```
parts/monitors/foo/bar.rb:1:1: C: Naming/FileName: bar.rb should define a class or module called Monitors::Foo::Bar. (https://rubystyle.guide#snake-case-files)
module Monitors
^
```
=> Naming/FileName: make CheckDefinitionPathHierarchy roots configureable

lib/rubocop/cop/layout/space_in_lambda_literal.rb, spec/rubocop/cop/layout/space_in_lambda_literal_spec.rb
This PR tweaks offense range for `Layout/SpaceInLambdaLiteral` when `EnforcedStyle`' is `require_no_space`.
=> Tweak offense range for `Layout/SpaceInLambdaLiteral`

lib/rubocop/cop/gemspec/require_mfa.rb
Examples for `Gemspec/RequireMFA` are not showing up properly, so this should fix it.
=> Fix docs for `Gemspec/RequireMFA`

lib/rubocop/cop/security/open.rb, spec/rubocop/cop/security/open_spec.rb
Following #10249, I was taking a look at `Security/Open` and I think it's not completely clear about what it is expected to report on.
The cop only is interested in cases where it can be dynamically opening a pipe, but this is not super clear from the documentation, examples, or tests.
I added more examples and fleshed out the tests a bit.
=> Update docs and tests for `Security/Open`

changelog/change_display_deprecation_message_for_enforce_super_class_module.md, lib/rubocop/cop/mixin/enforce_superclass.rb
Follow up to #9087.
This PR displays deprecation message for `EnforceSuperclass` module.
> https://github.com/rubocop/rubocop-rails/pull/390 is ready to be removed from RuboCop core.
> First of all, as soft deprecation, the document only indicates that it is a deprecation warning.
> After releasing RuboCop Rails several times, I will display a deprecation warning and
> will remove it in RuboCop 2.0.
After #9087, I've released RuboCop Rails more than 10 times in about a year, so it's time to get a deprecated warning.
=> Display deprecation message for `EnforceSuperclass` module

changelog/change_make_lint_deprecated_class_methods_aware_of_env_freeze.md, lib/rubocop/cop/lint/deprecated_class_methods.rb, spec/rubocop/cop/lint/deprecated_class_methods_spec.rb
This PR makes `Lint/DeprecatedClassMethods` aware of `ENV.freeze`. Calling `Env.freeze` raises `TypeError` since Ruby 2.7.
```console
% ruby -ve 'ENV.freeze'
ruby 2.6.7p197 (2021-04-05 revision 67941) [x86_64-darwin19]
% ruby -ve 'ENV.freeze'
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-darwin19]
Traceback (most recent call last):
1: from -e:1:in `<main>'
-e:1:in `freeze': cannot freeze ENV (TypeError)
```
> Ruby does not allow `ENV` to be frozen, so calling `::freeze` raises `TypeError`.
https://ruby-doc.org/core-2.7.0/ENV.html#method-c-freeze
There are no deprecated warnings in Ruby 2.6 and sudden the error since Ruby 2.7. Therefore I'm not sure whether it's appropriate to do it with `Lint/DeprecatedClassMethods` cop. But, I think it would be redundant to create a new cop for …
=> Make `Lint/DeprecatedClassMethods` aware of `ENV.freeze`

CHANGELOG.md
Should have been --auto-correct and --auto-correct-all. The error is only in the changelog.
Sadly, `--safe-autocorrect`, which is the wrong name, was actually how this was implemented. This was fixed later in https://github.com/rubocop/rubocop/issues/8252. So that typo must remain.
=> Fix --autocorrect typo in changelog

docs/modules/ROOT/pages/development.adoc
This PR adds a few sentences in docs of development section.
It would be clear if the rake task 'new_cop' can only be run inside the project directory itself.
By this documentation, there will be no more confusion like the conversation in the gitter; link: https://gitter.im/bbatsov/rubocop?at=5c3607a11d1c2c3f9ce7c23d .
=> Add kind instruction to cop development documentation
